influxdata/influxdb

- LICENSE
> update the year in the LICENSE file

- collectd/collectd.go
- collectd/collectd_test.go
- graphite/graphite.go
- graphite/graphite_tcp.go
- graphite/graphite_test.go
- graphite/graphite_udp.go
- server.go
- server_test.go
Change WriteSeries signature from:
```go
WriteSeries(database, retentionPolicy, name string, tags map[string]string, timestamp time.Time, values map[string]interface{}) (uint64, error)
```
To
```go
WriteSeries(database, retentionPolicy string, points ...influxdb.Point) (uint64, error)
```
> Change WriteSeries signature

- influxql/ast.go
Just a small correction in a comment
> correction: orthography

- influxql/ast.go
- tests/README.md
- tests/create_write_query
Starting a place to store end to end testing via scripts.  I'm open to naming advice for files.
> End to end test scripts

- package.sh
- scripts/init.sh
WIP, nowhere near ready for merging.
> Add initial version of new release script

- httpd/handler.go
- httpd/handler_test.go
Re-implementation of existing 0.7+ feature.
> Support pretty-print ouput on query endpoint

- package.sh
Notes: as I'm on Debian I've checked this only on Wheezy, but if the FPM docs are to be believed I suppose the rpm package should also work
> packaging: small improvements to package metadata

- metastore.go
- server.go
- shard.go
- tests/create_write_query
Persist measurement metadata to the meta store.
> Fix measurement persistence.

- package.sh
Also, check return codes to make sure everything worked OK.
> Explicitly set AWS creds during upload

- cmd/influx/main.go
- cmd/influxdb/main.go
- Command history is now persistent to disk
- Added `help` command
- Fixed erorsr not printing out for invalid commands
> CLI Enhancements

- httpd/handler_test.go
- influxql/ast.go
- influxql/parser.go
- influxql/parser_test.go
- server.go
Basic support for `SHOW TAG KEYS`.  Support for `WHERE` clause will come in a later PR.
> issue #1411: wire up show tag keys

- tests/siege/urlgen
Should address https://github.com/influxdb/influxdb/issues/1437
> Fix tests/seige/urlgen for non-macs

- client/influxdb_test.go
- httpd/handler_test.go
- raft/handler_test.go
- raft/log_test.go
Creating this PR to see if we can determine why these tests pass on some boxes, but not others.
> Intermittent tests passing/failing

- database.go
- influxdb.go
- influxql/ast.go
- influxql/engine.go
- influxql/parser.go
- server.go
- udp.go
- util.go
Cleans up a lot of (but not all) golint warnings.
> golint cleanup

- cmd/influx/main.go
- cmd/influx/main_test.go
Made this testable and added some very basic test coverage for now.
> CLI - add some basic test coverage for now

- server.go
Small fix: @otoolep please review.
> Change locks to read locks since that's what's actually needed

- httpd/handler.go
- httpd/handler_test.go
- tests/query_with_gzip.sh
Fixes https://github.com/influxdb/influxdb/issues/1449
> Add gzip capability to HTTP endpoints

- server.go
- server_test.go
Fixes https://github.com/influxdb/influxdb/issues/1444
> Log Unauthorized requests

- httpd/handler.go
- server.go
What other data should we export in this response?  I'm looking for the easy pass right now, mostly for things that will assist us in integration testing.
Things like available disk space, etc. can come later.
Comments/Ideas welcome.
> Start of a status http endpoint

- database.go
- influxql/ast.go
- influxql/ast_test.go
- influxql/engine.go
- server_test.go
Needs fixing. Failing test case in `server_test.go` at `TestServer_ExecuteQuery` test
> Fix queries that have only time in their where clause

- httpd/handler.go
The previous routing gzipped all routes and overwrote the Content-Length header. This header was needed for the metastore copy and caused it to break clustering. This commit fixes this issue by adding a `gzipped` flag to the `route` struct.
> Add optional gzip flag to handler

- influxql/engine.go
- server.go
- server_test.go
> Select wildcard functionality implemented

- cmd/influx/main.go
- server.go
- server_test.go
Also had to format the code before committing. This was due to a merge of a branch and not being formatted.  Not sure how we could of avoided that.
> CLI needs to echo out errors from client library.

- package.sh
Altered the shell line to contain #!/usr/bin/env bash instead of !#/bin/bash, bash is not at /usr/bin on freebsd.
> Changed first line to use /usr/bin/env bash as bash can't be expected

- httpd/handler_test.go
- influxdb.go
> Time stamps were not being set to now if they were blank

- admin/admin.go
- admin/admin_test.go
- cmd/influxd/config.go
- cmd/influxd/config_test.go
- cmd/influxd/run.go
- etc/config.sample.toml
Add some various cleanups to the admin interface.
> Admin interface updates

- influxql/engine.go
@pauldix is this what you were thinking?
> emit in batches of 1000

- influxql/engine.go
> make the fields public to all for serializing them later

- database.go
- httpd/handler_test.go
- influxdb.go
- influxql/ast.go
- server.go
- server_test.go
> Broadcast field types

- server.go
It is quite possible that multiple applyCreateFieldsIfNotExist messages
will sit unapplied in the Raft commit log, each carrying exactly the same
information about new fields. So during application of this message only
change the Metastore if the fields actually changed.
> Only update Metastore if new fields were created

- broker_test.go
> skipping intermittent failing test

- httpd/handler.go
We use our own http server for server level functions, as well as client facing functions.  With the addition of continuous queries, the http log is very noisy.  This change now only logs end user generated traffic.
> Only log client facing http routes

- httpd/handler.go
- httpd/handler_test.go
> Basic index endpoints for http

- cmd/influxd/server_integration_test.go
- messaging/broker.go
The wait time after the read had to be increased x3.
> Add batch test of 3-node and 5-node clusters

- commands.go
- server.go
server.go is getting long, so start breaking it up a little.
> Move Raft command types to own file

- commands.go
- httpd/handler_test.go
- metastore.go
- server.go
- server_test.go
> Change delete to drop for [dD]ropDatabase

- cmd/influxd/config.go
- cmd/influxd/run.go
- cmd/influxd/server_integration_test.go
- etc/config.sample.toml
- messaging/broker.go
- server.go
Not finished yet - this brings back the anonymous reporting feature from the v0.8.x series.
> Bring back stats reporting.

- database.go
> Remove field value count when writing to disk

- tests/create_write_multiple_query.sh
- tests/create_write_single_query.sh
- tests/siege/urlgen
- tests/tmux/README.md
- tests/tmux/sample.json
- tests/tmux/seed.sh
This was due to a breaking change in #1700
> Update tests to insert with fields, not values

- cmd/influxd/config.go
- cmd/influxd/config_test.go
- cmd/influxd/run.go
- server.go
I sure hope I haven't screwed up anything.
> Add flag to config that disables running CQs

- server_test.go
Opened issue #1727 to fix and re-enable test.
> Disable test. Issue #1727

- package.sh
> Explicitly name installation binaries

- messaging/broker_test.go
> disabling test until fixed.  Issue #1726

- CHANGELOG.md
- internal_test.go
- shard.go
- tx.go
> Refactor shard group time bound checking

- internal_test.go
Unit test code only -- self-merging on green build.
> More shard "contains" unit tests

- commands.go
- internal_test.go
This introduces consistency into the code, and makes testing easier.
> Store Measurement commands in batches

- server.go
- server_test.go
+ fix error when execute ALTER RETENTION POLICY bar ON foo DURATION 1h
+ add test to verify the fix
Signed-off-by: Kai Zhang <zhangk1985@gmail.com>
> Fix error when alter retention policy

- tests/urlgen/urlgen.go
Issue: 1818
This is meant to replace the urlgen shell script.
> Rewrite urlgen in Go

- raft/log.go
This pull request adds a check for newer terms in the streaming endpoint.
/cc @pauldix
> Update higher term on leader during stream request.

- CHANGELOG.md
> Update change log for #1862

- CHANGELOG.md
- client/influxdb.go
- client/influxdb_test.go
- cmd/influxd/server_integration_test.go
- httpd/handler.go
- influxdb_test.go
This is the merge to master as the branch I was working on was created from a different branch.  Self merging on green.
> Update client write

- cmd/influxd/server_integration_test.go
This was based on feedback that the client library was taking 10 seconds per point to insert with multiple fields.  I was unable to reproduce that (the test runs sub-second with 10 values/2 fields).
Self merging on green as it is just more test coverage.
> Added tests for writing multiple values/fields for client

- CHANGELOG.md
- httpd/handler.go
- httpd/handler_test.go
> Return status code 200 for measurement not found errors on show series.

- cmd/influxd/run.go
So to know/see where it's actually located.
> Also print the broker path.

- cmd/influxd/server_integration_test.go
- server.go
- server_test.go
> Use _id for Series IDs

- CHANGELOG.md
- database.go
- httpd/handler_test.go
- server.go
> Support sorting of retention policies

- httpd/handler.go
- uuid/uuid.go
> Replace code.google.com/p/go-uuid with TimeUUID from gocql

- raft/handler.go
- raft/handler_test.go
- raft/log.go
- raft/transport.go
- raft/transport_test.go
This pull request adds term responses back into `RequestVote()`. It also adds additional logging when votes are requested and responses are returned.
> Return term from vote, add term logging.

- CHANGELOG.md
- server.go
> Switch on "SHOW DIAGNOSTICS" statement

- cmd/influxd/server_integration_test.go
The timeout goroutine would continue to run (until the timeout)
even after queryAndWait returned.  This causes thousands of extra
goroutines to linger around and makes the test stack traces very
difficult to read.
> Exit all queryAndWait goroutines when returning

- etc/config.sample.toml
> Update sample toml to include join-urls

- admin/admin.go
- cmd/influxd/restore_test.go
- cmd/influxd/run.go
- cmd/influxd/server_integration_test.go
- messaging/client.go
- server.go
- test/messaging.go
This PR makes sure we close any listeners, connections and goroutines that were opened or started.
> Close resources when stopping a node

- cmd/influxd/server_integration_test.go
Based on feedback from @extemporalgenome.
> Refactor the queryAndWait in the integration tests

- package.sh
Turns out `GOPATH` can actually be set to multiple directories. Account for this during packaging.
http://golang.org/cmd/go/#hdr-GOPATH_environment_variable
> Use the first directory of GOPATH

- cmd/influx/main.go
When running the database dump or execute command return a valid exit code.
> improved exit code(s) for influx CLI

- server_test.go
A sync flag is what is really needed here.
> Give enough time for writes to occur

- etc/config.sample.toml
> Remove snapshot port/bind-address from sample config

- cmd/influxd/server_integration_test.go
- opentsdb/opentsdb.go
> OpenTSDB Input - use "value" as the field name

- circle-test.sh
Source: https://github.com/golang/tools/blob/master/README
> Avoid downloading go vet as included in go binary

- CHANGELOG.md
- client/influxdb.go
> Always send auth headers for client requests if present

- cmd/influxd/server_integration_test.go
- influxql/ast.go
- influxql/functions.go
- influxql/functions_test.go
- influxql/parser.go
replaces #2472 and fixes #2471
> normalize Call.Name to be lowercase

- raft/log.go
This was unused code and it was preventing some of my local tooling from working.
> Removing unused code

- graphite/graphite_test.go
Noticed some spelling errors in the graphite tests.
> Correct spelling in test titles

- client/influxdb.go
> remove unused function

- server.go
- server_test.go
- Fixed typo
- Increased coverage on server
> Additional server tests

- CHANGELOG.md
- raft/log.go
Adding additional logging for https://github.com/influxdb/influxdb/issues/2517.
> Add additional logging for RequestVote.

- CHANGELOG.md
- cmd/influxd/server_integration_test.go
- influxql/ast.go
- influxql/engine_test.go
- influxql/functions.go
- influxql/functions_test.go
- influxql/parser_test.go
- server_test.go
- tests/distinct-data-scenarios.sh
- tx.go
Fixes #1891, https://github.com/influxdb/influxdb/issues/2596
> Count distinct 1891

- CHANGELOG.md
- cmd/influxd/server_integration_test.go
- tx.go
> Return an error if user attempts to group by field

- tcp/client.go
- tcp/listener.go
- tcp/listener_test.go
- tcp/messages.go
> first pass at tcp client/server with proto buffs

- cmd/influxd/restore_test.go
- collectd/collectd.go
- collectd/collectd_test.go
- data/coordinator.go
- data/coordinator_test.go
- data/node.go
- data/points.go
- data/points_test.go
- data/rpc.go
- data/rpc_test.go
- graphite/graphite.go
- graphite/graphite_tcp.go
- graphite/graphite_test.go
- graphite/graphite_udp.go
- influxdb.go
- influxdb_test.go
- opentsdb/opentsdb.go
- server.go
- server_test.go
- tsdb/meta.go
- tsdb/points.go
- tsdb/points_test.go
- tsdb/shard.go
- tsdb/shard_test.go
- udp/udp.go
Ground work for replacing the implementation of Points with a byte buffer backed version.
> Convert Points to interface

- tsdb/meta.go
- tsdb/shard.go
- tsdb/shard_test.go
This PR pulls the in memory index out into something that can be shared across shards. It keeps the information for field encoding local to each shard.
> Shared metadata index

- meta/data.go
- meta/data_test.go
- meta/errors.go
- meta/internal/meta.pb.go
- meta/internal/meta.proto
- meta/store.go
- meta/store_test.go
This pull request implements the accessors and mutators on the in-memory metadata object (`meta.Data`) and it implements the accessors and mutators on the clustered implementation (`meta.Store`).
> Implement meta.Store and meta.Data.

- influxql/INFLUXQL.md
Bringing the InfluxQL spec up to date.  Currently a WIP.
> InfluxQL specification update

- cmd/influxd/help.go
- cmd/influxd/run.go
> Fix influxd help usage

- batcher.go
- batcher_test.go
This batcher generates a batch from the incoming points. A Batch is generated when either a) a certain size is reached, or b) a certain amount of time passes.
> Points batcher for data ingest

- cmd/influx/main.go
i don't know if you want this but it took very little effort and i thought it was useful to have another way to get the version of the install
```sh
> influx -version
InfluxDB shell 0.9
> influx -h
Usage of InfluxDB REPL version 0.9:
-database="": database to connect to the server.
-dump=false: dump the contents of the given database to stdout
-execute="": Execute command and quit.
-host="localhost": influxdb host to connect to
-output="column": format specifies the format of the server responses:  json, csv, or column
-password="": password to connect to the server.  Leaving blank will prompt for password (--password="")
-port=8086: influxdb port to connect to
-username="": username to connect to the server.
-version=false: Displays the InfluxDB version.
```
> name the FlagSet for the shell and add a version flag

- influxql/parser_test.go
go vet ./...
was broken on master
> fix vet errors

- CHANGELOG.md
- CONTRIBUTING.md
> Adding pr checklist

- batcher.go
- batcher_test.go
- collectd/collectd.go
- graphite/graphite_tcp.go
- graphite/graphite_udp.go
This allows the Batcher to be flushed on request, so when client code is terminating it allows pending data to be processed, minimizing any data loss.
This change was more extensive than I initially envisioned because I had to add the "flush" channel as a type attribute. And since I was adding that as a type attribute, I decided to make all of them attributes.
> Add flusher functionality Batcher

- client/influxdb_test.go
Similar to the ParsePoints benchmarks for the line protocol for comparison.
> Add JSON unmarshal benchmarks

- services/httpd/handler.go
If content-type is "application/json", we'll process the request as
of old JSON write API.  Otherwise, we assume line protocol but check
the first byte in case a older client is still sending JSON without the
correct content-type header.
> Use content type switch for /write API

- cluster/points_writer.go
- cluster/points_writer_test.go
- cluster/service.go
- cmd/influxd/run/config.go
- cmd/influxd/run/server.go
- meta/store.go
- meta/store_test.go
- services/httpd/config.go
- services/httpd/handler.go
- services/httpd/handler_test.go
- services/httpd/service.go
- tests/create_write_single_query.sh
- tsdb/query_executor.go
> Basic influxd service wired up for reading/writing

- client/influxdb.go
- cluster/points_writer.go
- cluster/points_writer_test.go
- meta/data.go
- tsdb/meta.go
Also fixes an issue where default retention policy would not be used and writing points with no tags would cause the DB to panic when restarted.
> Update client to use line protocol

- influxql/ast.go
- influxql/ast_test.go
- influxql/parser.go
- influxql/parser_test.go
- tsdb/meta.go
- tsdb/query_executor.go
- tsdb/query_executor_test.go
- tsdb/shard.go
- tsdb/store.go
* Pulled over updates to ast and parser from master
* Updated store and shard to be able to drop series
* Pulled updates to database.go from master into tsdb/meta.go
> Wire up DROP SERIES.

- cluster/internal/data.pb.go
- cluster/internal/data.proto
- cluster/points_writer.go
- cluster/points_writer_test.go
- cluster/rpc.go
- cluster/rpc_test.go
- cluster/service.go
- cluster/service_test.go
- cluster/shard_writer.go
- cluster/shard_writer_test.go
- cmd/influxd/run/server.go
* Remove OwnerID from protobuf since it's not needed
* Rename PointsWriter.Store to TSDBStore match how MetaStore is named
> Protobuf fixes

- cmd/influxd/run/server_test.go
- services/httpd/handler.go
- tsdb/tx.go
More tests.  This fixes a couple bugs as well. Added back in Epoch for query results.
> Integration tests

- cmd/influxd/run/server_test.go
This is a refactoring of the server integration tests.  This should speed up adding them back in significantly.
This new pattern has several features we didn't have before:
- All tests are grouped by their topic but are actual individual tests
- Errors will occur within each test so it is easier to debug
- Each test can be run in parallel so to avoid a monolithic table test.
> And then there were table tests!

- services/httpd/handler.go
- tests/create_future_writes.sh
- tests/create_write_multiple_query.sh
- tests/create_write_single_query.sh
- tests/create_write_single_with_multiple_measurements_values_tags.sh
- tests/create_write_single_with_multiple_tags_query.sh
- tests/distinct-data-scenarios.sh
Line protocol parsing already checks for this but JSON write path can cause the tsdb store to panic if they are not set.
> Ensure JSON point writes have names and at least 1 field

- cluster/service.go
- cmd/influxd/run/server_test.go
- services/httpd/service.go
- tsdb/store.go
Some good test refactoring here.
- All loggers are silenced unless `-v` is passed to test suite
- Ability to `init` a test suite
- Ability to `skip` a test
- time helpers for `mustParseTime`, `yesterday`
@pauldix several tests are skipped with issues that likely need you to look at or assign out as bugs.
> And even more Integration tests

- errors.go
- tsdb/meta.go
- tsdb/query_executor.go
- tsdb/query_executor_test.go
- tsdb/shard.go
- tsdb/store.go
* Add deleteMeasurement to store and shard
* Add DropMeasurement to DatabaseIndex
* Update ErrMeasurementNotFound and ErrDatabaseNotFound to not include the first line of the stack trace.
> Wire up DROP MEASUREMENT

- cmd/influxd/run/server_helpers_test.go
- cmd/influxd/run/server_test.go
- tsdb/tx.go
Mostly aggregation testing this time.  Have several `FIXME` that have to be addressed.
- Fixed error message regressions
- Moved helper/convenience code to it's own file
- Aggregation Tests
- User Tests
> Integration tests - the battle continues

- cluster/service.go
Fixes https://github.com/influxdb/influxdb/issues/2774
This occurs when someone tries to hit the TCP cluster endpoint with an HTTP server.  Locking message size down to prevent a panic.
> Messages over 1GB are probably not valid

- cluster/points_writer.go
- cmd/influxd/main.go
- cmd/influxd/run/command.go
- cmd/influxd/run/config.go
- cmd/influxd/run/config_command.go
- cmd/influxd/run/config_test.go
- cmd/influxd/run/server.go
- cmd/influxd/run/server_helpers_test.go
- errors.go
- etc/config.sample.toml
- influxql/scanner.go
- meta/config.go
- meta/data.go
- meta/data_test.go
- meta/internal/meta.pb.go
- meta/internal/meta.proto
- meta/store.go
- meta/store_test.go
- services/collectd/config.go
- services/opentsdb/config.go
- tsdb/shard.go
This commit adds the ability to cluster multiple nodes together to share the same metadata through raft consensus.
> Multi-node clustering

- cluster/config.go
- cluster/config_test.go
- cluster/service.go
- cluster/service_test.go
- cluster/shard_writer.go
- cluster/shard_writer_test.go
- cmd/influxd/run/server.go
- cmd/influxd/run/server_helpers_test.go
- meta/store.go
- meta/store_test.go
This pull request integrates the `tcp.Mux` into `influxd run`.
> Influxd mux integration

- cmd/influxd/run/server.go
- meta/store.go
> Add mux.Serve()

- README.md
> Retention policy not created by default

- meta/store.go
This pull request removes the `VisitShardGroups` helper function so that `errInvalidate` can be returned if no shard is found.
> Invalidate cache on shard owner lookup.

- CHANGELOG.md
- meta/store.go
> Add missing call to WaitGroup.Done()

- cmd/influxd/run/server_test.go
This PR rounds out the Database Commands by testing Drop Database.  It also adds numerous tag query scenarios.
> Integration tests for Drop Database and More Tag Scenarios

- etc/config.sample.toml
This is the bare minimum. Some additional comments might be helpful, since I removed all of the old ones. I think a lot of them were no longer very useful, so we should rethink these.
> Create a valid default config for v0.9.0

- CHANGELOG.md
- cmd/influxd/run/server.go
- services/opentsdb/config.go
- services/opentsdb/config_test.go
- services/opentsdb/handler.go
- services/opentsdb/service.go
- services/opentsdb/service_test.go
Similar functionality exists for Graphite and has already been committed.
> Support setting openTSDB write consistency

- services/retention/service.go
> Consolidate imports for retention service

- cmd/influxd/run/server_helpers_test.go
- cmd/influxd/run/server_test.go
This PR introduces:
- Aggregate function tests for ints
- Aggregate function tests for strings (they should be empty, not panic)
- Update any skipped tests with a github issue # for tracking.
> More aggregation tests for ints, update skipped tests with issue numbers

- cmd/influxd/run/server_helpers_test.go
- cmd/influxd/run/server_test.go
Adds integration testing for:
- Where with boolean data types
- Limit and Offset
- Where with tags
> More integration testing

- services/graphite/service_test.go
- tcp/mux_test.go
Make InfluxDB win32 friendly, fix unit test is failed on the windows
> Make InfluxDB win32 friendly, fix unit test is failed on the windows

- client/README.md
This commit updated the docs to reflect the current code.
> Name is now Measurement per issue #2564

- tsdb/meta.go
- tsdb/shard.go
- tsdb/store.go
Code was not doing what comments said it should do.
> Series was not already dropped, return false (and other fixes)

- tsdb/query_executor.go
> SHOW DIAGNOSTICS is not yet (re)implemented

- influxql/parser.go
- influxql/parser_test.go
> Only ORDER BY ASC is valid for now

- cmd/influxd/run/server_test.md
Document the integration tests.
> Docs on integration testing

- cmd/influxd/run/server_test.go
> Integration tests for drop measurement

- CHANGELOG.md
- meta/store.go
This pull request sets the replication factor to the number of nodes currently in the cluster.
> Ensure default retention policies are fully replicated

- cmd/influxd/run/server_test.md
@corylanou - some minor typo fixes
> fix typos in server_test.md

- CHANGELOG.md
- tsdb/points.go
- tsdb/points_test.go
> Fix parsing negative floats

- cmd/influxd/run/server_test.go
Just tests.  Self merging on green.
> Show series integration tests

- cmd/influxd/run/server_test.go
Just tests.  Merging on green.
> SHOW MEASUREMENTS integration tests

- cmd/influxd/run/server_test.go
Just tests.  Merging on green.
> SHOW TAGS integration tests

- cmd/influxd/run/server_test.go
> Show tag field integration tests

- cmd/influxd/run/server_test.go
Just tests.  Merging on green.
> More integration tests for retention policy

- cmd/influxd/run/server_test.go
> fix version assertion in server_test

- CHANGELOG.md
- services/udp/service.go
> Don't log each UDP batch

- tsdb/points.go
- tsdb/points_test.go
fixes #3037
cc @beckettsean @jwilder
> allow comments in line protocol

- tsdb/README.md
showing escape characters and proper string quoting
> more examples for line protocol

- CHANGELOG.md
- cmd/influx/main.go
- cmd/influx/main_test.go
> Fix CLI panic on malformed INSERT

- package.sh
> Add support for tgz package

- client/influxdb.go
- cluster/points_writer.go
- cluster/points_writer_test.go
- cmd/influxd/backup/backup.go
- cmd/influxd/restore/restore.go
- cmd/influxd/run/server_helpers_test.go
- cmd/influxd/run/server_test.go
- influxql/NOTES
- influxql/ast.go
- influxql/ast_test.go
- influxql/engine.go
- influxql/functions.go
- influxql/parser.go
- meta/data_test.go
- services/hh/queue.go
- services/hh/queue_test.go
- services/httpd/handler.go
- services/httpd/response_logger.go
- services/opentsdb/handler.go
- toml/toml.go
- tsdb/points.go
- tsdb/query_executor.go
- tsdb/shard.go
- tsdb/shard_test.go
- tsdb/snapshot_writer.go
I focused primarily on comments, but several strings were corrected.
> Fix spelling errors in comments and strings.

- influxql/engine.go
That minor style fix we discussed for the short vs longer function names.
> Code style fix after review of #2956

- tsdb/shard.go
This small changes assist with distributed query support.
> Minor changes to field codec functions

- meta/store.go
> Use salted hashes for in memory password cache

- CHANGELOG.md
- tsdb/points.go
- tsdb/points_test.go
> Fix panic parsing floats without decimal

- cmd/influx/main.go
Making the formatting of the cli info consistent.
> Output consistency for usage in cli

- CHANGELOG.md
> Updated changelog to have correct name

- cmd/influx/main.go
> Update link in CLI shell help command

- cmd/influx/main.go
- influxql/functions.go
- influxql/parser.go
- meta/store.go
- services/graphite/parser.go
- services/httpd/handler.go
- tsdb/points.go
- tsdb/query_executor.go
- tsdb/shard.go
In go it's better to just continue flow without "else", if it is return in
"if" statement.
> Fix style issues with else

- tsdb/mapper.go
> mapper takes Statement instead of *SelectStatement

- QUERIES.md
- influxql/INFLUXQL.md
- shared/admin/index.html
Updating documentation in two spots and updating the suggested query that shows up in the admin page for SHOW RETENTION POLICIES "ON"
> docs tweaks for new syntax show retention policies

- cmd/influx/main.go
fixes https://github.com/influxdb/influxdb/issues/3235
> Remove DUMP from CLI

- cmd/influxd/run/server_test.go
Adds integration test for creating a continuous query.
> Continuous Query Tests

- services/httpd/handler.go
> Respond to OPTIONS requests on /query endpoint

- api/http/api.go
- api/http/points.go
This PR fixes some bugs in the exporter, as well as adds a "upgrade_artificat" to any series that do not conform to the expected format.
> v0.8.9 Export - fix export bugs, refactor yield, export markers for invalid series

- tsdb/mapper.go
This change uses a `heap` instead of arrays for the `tagSetCursor` look-ahead, which results in up to 25x faster queries when querying across many series.  Queries that used to be fast stay fast.  Queries that used to be slow get much faster.
> Query performance optimization

- tsdb/engine/bz1/bz1.go
- tsdb/engine/bz1/bz1_test.go
This commit fixes issues found from using a more complex `testing/quick` implementation of the `WriteIndex()` test. The newer test inserts multiple sets of random data that's confined to a smaller random space so there's more chance of overlapping data.
The fixes were primarily around inserting old data or inserting the same timestamp multiple times for a single write. The block splitting was not working correctly before and the sorting and deduping was not  handled correctly.
/cc @pauldix
> Ffix bz1 quickcheck bugs

- CHANGELOG.md
- tsdb/executor.go
- tsdb/executor_test.go
> Fix panic when running derivative on non-numeric values

- CHANGELOG.md
- tsdb/points.go
- tsdb/points_test.go
> Fix panic when parsing value in scientific notation with trailing i

- cmd/influxd/run/server_test.go
Recent changes must have fixed issue #2874.
> Re-enable test "TestServer_Query_Now"

- CHANGELOG.md
- tsdb/batcher.go
> Align batcher stats for i386

- CONTRIBUTING.md
> updating bug report example to line protocol

- cmd/influxd/run/server_test.go
Added this as part of working on issue #3603.
> Add new server-level unit test

- CHANGELOG.md
Update changelog for #3517 #3522.  Enable CQ deadlock test. Thanks for the fixes and test script @dim!
> CQ deadlock changelog and test

- meta/store_test.go
Instead of trying to start all the nodes with dynamic peer addresses
set, alwasy start one, then join the rest to this one.  The SetPeers
in the test may be causing leadership changes and sporadic failures.
Possible fix for #3655
> Change how cluster is started in tests

- cmd/influxd/run/server_test.go
Test code only, merging on green.
> Add some unit tests related to partner testing

- services/retention/service.go
Cosmetic change, removing duplicated message.
> Don't repeat retention policy log message

- CHANGELOG.md
- meta/data.go
- meta/data_test.go
- meta/store_test.go
> Update shard retention time when policy changes

- tsdb/engine/wal/wal.go
- tsdb/engine/wal/wal_test.go
If a flush is happening and you bring up a cursor for a series, if that series didn't have any data in the cache (after the flush started) then it would return no data. What it should have done instead is return the data that is in the flush cache, which is held in separate area of memory until it is committed to the index.
/cc @jwilder and @jhorwit2
> Fix bug querying data from WAL while compacting.

- tsdb/engine/bz1/bz1.go
- tsdb/engine/wal/wal.go
> Make bz1 close the WAL before closing bolt so it can flush

- api/http/api.go
- api/http/points.go
When you export, you will now get comments inline in the `DML`:
`# Found 999 Series for export`
As well as count totals for each series exported:
`# Series FOO - Points Exported: 999`
With a total at the bottom:
`# Points Exported: 999`
> 0.8.9 Export Updates

- cmd/influx_stress/influx_stress.go
> Update stress to work with fewer than 10k series.

- tsdb/shard.go
> Fix map concurrent race with adding a shard to a series in the index.

- tsdb/engine/wal/wal.go
- tsdb/engine/wal/wal_test.go
Fixes #3792 
/cc @DanielMorsing
> Ensure WAL cache gets sorted when needed.

- tsdb/engine/bz1/bz1.go
- tsdb/engine/bz1/bz1_test.go
> Fix missing data in aggregates with bz1

- tsdb/engine/wal/wal.go
> Fix metafile so it doesn't get trampled by other goroutines.

- tsdb/mapper.go
If the cursor gives a start time before or after the chunk that we
are currently getting, don't bother to put it on the heap and don't
bother to seek it again in the futile hopes that the key will change.
For a synthetic database where there was only entries for a tiny
slice of time, it cut queries from 183 seconds to 30 seconds doing
`select mean(value) from cpu where time > now - 2h group by time(1h)`
> WIP don't bother seeking a cursor if it wont yield a useful value

- CHANGELOG.md
- services/retention/config.go
- services/retention/service.go
Minor changes:
- fix typo in log message.
- increase retention check period since the minimum retention period is 1 hour.
> Minor retention tweaks

- client/README.md
Updating imports in the README example so that it will compile
> Updating imports in README example

- CONTRIBUTING.md
> Add note re cloning forks

- tsdb/executor.go
- tsdb/functions.go
- tsdb/functions_test.go
- tsdb/mapper.go
- tsdb/shard.go
Move these functions into the tsdb package. Getting ready to refactor these to be more integrated with the query engine.
> move aggregate functions

- influxql/functions.go
- influxql/functions_test.go
- tsdb/executor.go
- tsdb/mapper.go
- tsdb/shard.go
Reverts influxdb/influxdb#3951
> Revert "move aggregate functions"

- influxql/ast.go
- influxql/parser.go
- influxql/parser_test.go
- influxql/scanner_test.go
- influxql/token.go
- meta/statement_executor.go
- meta/statement_executor_test.go
This pull request adds the ability to list all shards in the cluster and return their id, start time, end time, expiry time, and owner ids. Shards are grouped by database.
Fixes #3562
> SHOW SHARDS

- etc/config.sample.toml
noticed those when packaging 0.9.3 for Debian.
> removed trailing spaces

- tsdb/engine/bz1/bz1.go
```
> show stats
name: engine
tags: path=/home/philip/.influxdb/data/graphite/default/1, version=bz1
blks_write      blks_write_bytes        blks_write_bytes_c      points_write    points_write_dedupe     slow_insert
----------      ----------------        ------------------      ------------    -------------------     -----------
726             2982000                 1046039                 142000          142000                  4
```
> Basic instrumentation for bz1 engine

- CHANGELOG.md
- services/opentsdb/service.go
This is not really an error, so don't log it.
> Cleanly terminate openTSDB connection on EOF

- cmd/influx_stress/influx_stress.go
- tsdb/engine/wal/wal.go
If the memory gets 5x above the partition size threshold, the WAL will start returning write failures to the clients. This will allow them to backoff their write volume.
Also updated the stress script to track failed requests and output messages on failure and when it returns to success.
> Update WAL to fail writes if pressure too high.

- CHANGELOG.md
- cmd/influxd/run/server.go
- etc/config.sample.toml
- tsdb/config.go
- tsdb/query_executor.go
> Control whether each query should be logged

- package.sh
> Add package post-uninstall script

- cluster/service.go
Add simple stats to cluster, showing number, and type of, requests processed.
Example output:
```
> show stats
name: cluster
-------------
map_shard_req   map_shard_resp
1               2
```
> Add cluster-service stats

- CHANGELOG.md
- influxql/parser.go
- influxql/parser_test.go
> Update, and ease maintainabilty of, SHOW errors

- cluster/internal/data.pb.go
- cmd/influxd/run/server.go
- influxql/ast.go
- influxql/parser.go
- influxql/parser_test.go
- influxql/scanner_test.go
- influxql/token.go
- meta/data.go
- meta/data_test.go
- meta/errors.go
- meta/internal/meta.pb.go
- meta/internal/meta.proto
- meta/state.go
- meta/statement_executor.go
- meta/statement_executor_test.go
- meta/store.go
- meta/store_test.go
- services/copier/internal/internal.pb.go
- tsdb/internal/meta.pb.go
This reverts commit 0bdb36f6dcf93a8ae44732c0300ca4503fad061a, reversing
changes made to 3085fbc138de95893bb354f0b5401191331a06ef.
> Revert "Merge pull request #4233 from influxdb/drop-server"

- balancer.go
- errors.go
> Complete lint of project root.

- CHANGELOG.md
- client/influxdb.go
See https://github.com/influxdb/influxdb/issues/4344
> make client.Write default to c.precision if none is given

- influxql/ast.go
> Fix infinite recursion in DeleteStatement.String()

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- tsdb/executor.go
> Prevent multiple selectors overwriting each other during post processing

- stress/config.go
> Add negative jitter

- client/influxdb.go
> ref #4098 lint client package

- CHANGELOG.md
- uuid/uuid.go
Issue: Enable `golint` on the code base #4098
> Changes to make the uuid subpakage golint-able.

- CHANGELOG.md
- models/points.go
- tsdb/engine/tsm1/cursor_test.go
- tsdb/engine/tsm1/tsm1.go
- tsdb/engine/tsm1/wal.go
- tsdb/engine/tsm1/wal_test.go
This pull request adds quickcheck testing for the tsm1 WAL.
> Add tsm1 WAL QuickCheck

- QUERIES.md
- cluster/rpc.go
- cmd/influxd/run/config.go
- cmd/influxd/run/server_test.go
- influxql/INFLUXQL.md
- models/points.go
- models/points_test.go
- services/graphite/README.md
- tsdb/meta.go
> WIP tag name --> tag key, field name --> field key

- cmd/influx_stress/influx_stress.go
Previously the test file would over write any flags passed to
influx_stress, now flags overwrite config file options
> Flags overwriting config file

- tsdb/functions.go
- tsdb/functions_test.go
Same thing we did for the map functions.
> update reduce func signatures to not have influxql.Call arguments

- cluster/points_writer.go
- cluster/points_writer_test.go
* non-existant --> non-existent
* propogate --> propagate
> Fix typos.

- CONTRIBUTING.md
necessarly -> necessarily
libaries -> libraries
CirceCI -> CircleCI
> Fix typos for Contributing doc.

- tsdb/engine/tsm1/tsm1_test.go
Running this test with -race triggers a number of data races:
WARNING: DATA RACE
Write by goroutine 22:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*dataFile).close()
/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1855 +0xe8
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*dataFile).Delete()
/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1835 +0x99
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).rewriteFile.func1()
/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1179 +0x62
Previous read by goroutine 13:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).filesAndLock()
/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:476 +0x1b2 …
> Add test for data races in tsm1 Write

- tsdb/engine/tsm1/tsm1.go
- tsdb/engine/tsm1/tsm1_test.go
Fixes #4388. This also fixes the issue of blocks in compacted files not having consistent size up to the max points in a block number.
__There is a potential bug that this introduces:__ If a write comes into a range of time for while a compaction has happened and it had to be split across multiple files, the resulting data will be wrong. I can either continue this PR or address it in a new PR as it'll require significant reworking of the `Write` and `rewriteFile` functions.
Work in this PR:
* refactor compaction
* rework compaction cleanup logic to work with multiple resulting files
* ensure the uint64 number for a series key doesn't use 0 or MaxInt64 for sentinel values
* ensure we're actually combining blocks into the max block size
> Ensure compactions don't create files much larger than 2GB.

- client/influxdb.go
Fixed minor typo and removed double spaces from comments.
Thanks for reviewing it =)
(I have already signed the CLA)
> Fix typo and double spaces for comments

- models/points.go
> condense skipWhitespace code

- CHANGELOG.md
- importer/v8/importer.go
> Importer fixes.  

- CHANGELOG.md
- toml/toml_test.go
Test code only, merging on green.
> Enable toml test TestConfig_Encode fixes #4691

- meta/statement_executor.go
- meta/statement_executor_test.go
> SHOW SHARDS now includes database name and retention policy

- client/v2/client.go
- client/v2/example_test.go
This should make the v2 client godoc examples behave better
> Fixup the v2 client godoc examples

- cmd/influxd/run/server.go
- services/registration/service.go
We should be using [https://github.com/influxdb/enterprise-client](https://github.com/influxdb/enterprise-client) for communicating with Enterprise.
@otoolep Since you did the original work, would you mind reviewing this PR? Also, I couldn't find anywhere where the anonymous usage stats were being reported. Am I just missing them somewhere?
> Updated to use the new Enterprise Client

- client/v2/client.go
fixes https://github.com/influxdb/telegraf/issues/351
> Create a new query request for each Query

- pkg/slices/strings.go
> Complete lint for pkg/slices

- CONTRIBUTING.md
Adds some syntax highlighting to the contributing file for easier readability.
> adds syntax highlighting for bash

- CHANGELOG.md
- etc/config.sample.toml
- services/opentsdb/config.go
- services/opentsdb/config_test.go
- services/opentsdb/service.go
Fix https://github.com/influxdb/influxdb/issues/4783
> Allow openTSDB point errors logging to be disabled

- services/udp/config.go
- services/udp/service.go
My first go at contributing.
Just added some basic comments to make golint pass on services/udp
Apologies in advance if I have done something incorrect with regards to submitting a PR
> Added some comments to the udp service so golint passes. Ref #4098

- CHANGELOG.md
- services/admin/config.go
[Issue here](https://github.com/influxdb/influxdb/issues/4098)
- [✓] CHANGELOG.md updated
- [✓] Rebased/mergable
- [✓] Tests pass
- [✓] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)
> fixed export lint issues in services/admin

- services/admin/config.go
Issue described [here](https://github.com/influxdb/influxdb/issues/4098)
> linted service/admin

- tsdb/cursor.go
Simple refactoring based on PR feedback.  No new code, mostly just deleting unnecessary code based on refactor.
> Refactor newPointHeap

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- tsdb/cursor.go
Fixes time ranges not being inclusive in a where clause.  1 character bug fix, lot of tests to prevent regression :-). Fixes #4193
> Fix time inclusive comparison

- tsdb/engine/tsm1/cache.go
This code may actually change soon due to internal design changes, but this will ensure testing output is constant.
Previously this code was simply iterating over the map of checkpoints in whatever order Go provided, which was wrong. Instead get the checkpoints, sort them, and then walk the map in that order of the sorted checkpoints.
> Clone should sort values

- stress/basic.go
Master wont build without these fixes.
Sorry I didn't notice this earlier.
> Update to new v2 client

- services/collectd/config.go
- services/precreator/service.go
- services/subscriber/config.go
- services/subscriber/service.go
- services/subscriber/udp.go
Also 1 slight code change that fixed an if statement
that golint didn't like.
> Comment additions to conform to golint

- services/registration/config.go
- services/registration/service.go
- services/retention/config.go
Small batch of lint fixes.
Part of #4098.
> Comment additions to services to satisfy golint

- influxql/INFLUXQL.md
- influxql/parser.go
I was reading through the InfluxQL doc while following along with the parser code, so I made a lot of small clean ups along the way.
> Influxql doc updates

- shared/admin/index.html
Simple PR to add query templates for the new SHOW STATS and SHOW DIAGNOSTICS commands for v0.9.4.
> Add query templates for show stats and show diagnostics

- tsdb/engine/tsm1/cache.go
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/encoding.go
- tsdb/engine/tsm1/log.go
- tsdb/engine/tsm1/tsm1.go
This will make this function much more useful, for working with the WAL cache.
> Deduplicate supports requesting sort order

- etc/config.sample.toml
> Clarify engine comment about tsm1 in the sample config

- tsdb/engine/tsm1/data_file.go
- tsdb/engine/tsm1/data_file_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/file_store_test.go
This adds query support back to the dev tsm engine.  I still need to add the deduping logic in the `FileStore`, but that will be addressed in subsequent PR.
> TSM Queries

- CHANGELOG.md
- tsdb/shard.go
> Fix data race in TSDB

- influxql/ast.go
- influxql/ast_test.go
- influxql/result.go
- tsdb/query_executor_test.go
- tsdb/raw.go
Reverts influxdb/influxdb#4984
> Revert "fix raw math query panic"

- cmd/influx_inspect/tsm.go
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/data_file.go
- tsdb/engine/tsm1/data_file_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/tombstone.go
This allows `drop measurement` and `drop series` to work with the update tsm engine.
> Implement delete series/measurement

- cmd/influx_inspect/tsm.go
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/data_file.go
- tsdb/engine/tsm1/data_file_test.go
- tsdb/engine/tsm1/encoding_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/file_store_test.go
* Fixes FileStats not actually getting loaded for MMAP'd files
* Changes compaction planning and naming scheme to updated design
* Avoid scanning index too frequently during TSM compactions
> Update compaction planning

- tsdb/aggregate.go
- tsdb/query_executor_test.go
pr #4984 fix math query without aggregate functions, this pr makes math query with aggregate functions
works
> fix aggregate math query

- cmd/influxd/run/server_test.go
- tsdb/aggregate.go
Fixes nits from https://github.com/influxdb/influxdb/pull/5013.
> Test and variable rename for aggregate math

- CONTRIBUTING.md
> Fix install path in CONTRIBUTING.md

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- tsdb/aggregate.go
Fixes #5042 
Simple fix and tests for fill and count.
> Count with fill(none) will drop 0 valued intervals

- etc/config.sample.toml
> removed trailing space

- shared/admin/index.html
Hello.
I suppose this DROP RETENTION POLICY in admin UI is a bit incomplete - the name of the DB is requiered.
> Complete DROP RETENTION POLICY query template

- test.sh
Small optimization that should save a few minutes during CircleCI build process.
> Only save docker image if changed from load

- tsdb/engine/tsm1/compact_test.go
Fixes #5096 and will allow #4981 to be merged after rebase.
> Fix rename temp file on windows

- cluster/balancer.go
- cluster/points_writer.go
- cluster/service.go
- cluster/shard_mapper.go
- cluster/shard_writer.go
- cmd/influxd/run/config.go
- cmd/influxd/run/config_test.go
- cmd/influxd/run/server.go
- monitor/service.go
- node.go
- services/collectd/service.go
- services/continuous_querier/service.go
- services/graphite/service.go
- services/hh/config.go
- services/hh/node_processor.go
- services/hh/service.go
- services/httpd/handler.go
- services/meta/client.go
- services/meta/config.go
- services/meta/config_test.go
- services/meta/service.go
- services/opentsdb/service.go
- services/precreator/service.go
- services/retention/service.go
- services/snapshotter/service.go
- services/subscriber/service.go
- services/udp/service.go
- tsdb/config.go
- tsdb/config_test.go
- tsdb/query_executor.go
The beginning of cutting over to the meta Service/Client.  Nothing works yet.  Just builds.
> WIP - buildable meta -> services/meta

- cmd/influx_stress/influx_stress.go
- stress/basic.go
- stress/config.go
Fixes https://github.com/influxdb/influxdb/issues/5237
> Add flag to specify db and clarify flag descriptions

- tcp/mux.go
There were 16 data races being detected without this mutex.  The test suite for `services/meta` now runs cleanly with the `-race` and `-parallel 256` flags passed in.
/cc @dgnorton @pauldix
> Fix data race in services/meta tests

- services/meta/client.go
- services/meta/data.go
- services/meta/service_test.go
- services/meta/store_fsm.go
> Add CreateDataNode to meta client/service

- build.py
- scripts/post-install.sh
- scripts/post-uninstall.sh
- scripts/pre-install.sh
- Fixes an issue with pre-installation script that can overwrite existing configurations.
- Re-enables ARM builds facilitated by the `build.py` script.
- Added optional `--goarm=` flag to `build.py` for customization around ARM version to target
- ~~Added basic Go bootstrapping retry logic when cross-compiling (the script will attempt to bootstrap Go for the target build).~~
- Small bug fixes around iterations and release candidates in `build.py`.
> WIP - Build and Packaging Updates

- services/meta/client.go
- services/meta/internal/meta.pb.go
- services/meta/internal/meta.proto
- services/meta/service_test.go
- services/meta/store.go
- services/meta/store_fsm.go
> Wire up meta.ClusterID and tests

- services/meta/client.go
- services/meta/service_test.go
- services/meta/store_fsm.go
> Wire up meta service and client delete data node

- services/meta/client.go
- services/retention/service.go
* Remove VisitRetentionPolicies from meta client.
* Update retention enforcer to run on every data node.
cc @dgnorton, @corylanou
> Update meta client and retention service.

- services/meta/service_test.go
- services/retention/service.go
Merging as it's just vet fixes.
/cc @dgnorton @pauldix 
You can re-enable your git commit hooks now.
> Fix vet warnings

- CHANGELOG.md
- cmd/influxd/backup/backup.go
> Ensure the backup directory exists.

- build.py
Included in this update:
- Added `--no-get` flag, which means that `go get` will not be run before building. Running `go get` on every run can cause issues if you have local changes when attempting to build. If not using `--no-get` with local changes, then any local un-committed changes will be stashed while `get` is run, and then re-applied once it completes (this was the default behaviour with `package.sh`).
- Added a `--debug` flag, which displays verbose debug output.
- Changed 32-bit build classification from `386` to `i386` for easier integration with package managers.
- Added a `--bucket=<S3 bucket>` flag, if you want to upload to the non-default S3 bucket.
- Minor updates and changes to output
- Moved `boto` module import to the upload function, which will now return an error if …
> Updates to build.py

- cluster/balancer_test.go
- cluster/points_writer_test.go
- cluster/service_test.go
- cluster/shard_writer_test.go
- cmd/influxd/restore/restore.go
- cmd/influxd/run/server_helpers_test.go
- cmd/influxd/run/server_test.go
- monitor/service_test.go
- services/collectd/service_test.go
- services/continuous_querier/service_test.go
- services/graphite/service_test.go
- services/hh/node_processor_test.go
- services/httpd/handler_test.go
- services/meta/client.go
- services/meta/handler.go
- services/opentsdb/service_test.go
- services/precreator/service_test.go
- services/subscriber/service_test.go
- tsdb/query_executor_test.go
- tsdb/raw_test.go
This gets all the tests running and green again with the exception of restore related ones which need to be rebased with master because they are out of date.
@dgnorton @corylanou
> Passing test suite

- CHANGELOG.md
- cmd/influxd/backup/backup.go
> Validate metadata backup blob

- services/continuous_querier/service.go
- services/continuous_querier/service_test.go
- services/meta/client.go
> convert CQ service to use new meta client

- cmd/influxd/backup/backup.go
- cmd/influxd/restore/restore.go
> Improve backup/restore logging and help commands

- cmd/influxd/run/backup_restore_test.go
- cmd/influxd/run/server.go
- node.go
- services/meta/data.go
- services/meta/service_test.go
- services/meta/store_fsm.go
fixes #5426 only for single node.
//cc @jwilder @dgnorton
> Allow for node upgrade

- CHANGELOG.md
- tsdb/functions.go
- tsdb/functions_test.go
> Update first() and last() to handle varying types

- tsdb/engine/tsm1/reader.go
> fix determine the file size

- services/meta/service_test.go
> fix cross platform error

- tsdb/engine/tsm1/mmap_windows.go
> fix munmap bug in the windows

- node.go
fix rename file fail on the windows
> fix rename file fail on the windows

- tsdb/engine/tsm1/reader.go
- tsdb/engine/tsm1/reader_test.go
> Fix reading too far in fileAccess.readBytes

- cmd/influx_tsm/README.md
- cmd/influx_tsm/main.go
The output of this fine tool seemed a little off. :-) I had to look at the source to learn what the number represented.
> Make it clear what the trailing parallel factor is

- tsdb/batcher.go
- tsdb/config.go
- tsdb/engine.go
- tsdb/engine/engine.go
- tsdb/meta.go
- tsdb/query_executor.go
- tsdb/shard.go
- tsdb/store.go
> Lint tsdb and tsdb/engine package

- CONTRIBUTING.md
- client/influxdb_test.go
- cmd/influxd/run/server.go
> Fix additional influxdata renames

- client/v2/client.go
Just minor cleanup from golint that I found while working in the client v2 code.
> Fix golint warnings.

- services/continuous_querier/continuous_queries.md
I was reading to get an overview on CQs and tidied up a few typos as I went.
I suggest someone visits this document in the future as not sure how much it's changed as of 0.10.
> Tidy up README

- CHANGELOG.md
- influxql/select.go
- influxql/select_test.go
Fixes https://github.com/influxdata/influxdb/issues/5630
Fixes #5628
> Make sure parenthesized SELECT arguments are evaluated properly without panic

- CONTRIBUTING.md
Since we're updating the README in #5645, I thought I would get the CLA updated with the correct links.
> Update link to CLA

- influxql/README.md
> Remove DELETE FROM from query spec

- influxql/call_iterator.go
- influxql/select_test.go
> Support derivative() call for integer fields in the new query engine

- services/meta/raft_state.go
> Fix go vet

- services/httpd/handler_test.go
Added test to http handler for checking the version header information.
Fixes #1692
> Added test coverage to httpd handler version header

- CHANGELOG.md
- cmd/influx_tsm/b1/reader.go
- cmd/influx_tsm/bz1/reader.go
- cmd/influx_tsm/main.go
These changes were already made to the 0.10 branch, and should be included
> influx_tsm bugfixes in 0.10.0

- cmd/influxd/run/config.go
- cmd/influxd/run/config_command.go
- services/graphite/config.go
- services/udp/config.go
Hello !
I made a **TEMPORARY** workaround for #4752.
What do you think about ?
BTW, This PR merge master branch, is it correct ? Or do you prefer an other branch (0.9.6) ???
> Workaround for #4752

- CHANGELOG.md
- cmd/influx_tsm/b1/reader.go
- cmd/influx_tsm/bz1/reader.go
> influx_tsm: close bolt databases properly

- cmd/influx_tsm/README.md
Added a suggestion to run influx_tsm under a screen session to avoid interruptions due to console disconnects.
> screen suggestion for influx_tsm

- tsdb/engine/tsm1/cache.go
The intent of this change is to ensure that all statistic fields of the
resulting tsm1_cache measurement are initialized on initialization of
the cache. That way, any consumer of those measurements doesn't
have to deal with the null case.
Signed-off-by: Jon Seymour <jon@wildducktheories.com>
> tsm: cache: ensure all statistics are initialised on cache creation.

- tsdb/engine/tsm1/cache.go
Since we are not locking but relying on atomic arithmetic,
use Add rather than Set. Will also result in slightly less garbage
being created.
Signed-off-by: Jon Seymour <jon@wildducktheories.com>
> tsm: cache: during writes, update the memSize statistic outside the lock

- cmd/influxd/run/server.go
Already checked the `c.Meta.Dir ` at https://github.com/influxdata/influxdb/blob/master/cmd/influxd/run/server.go#L112
> No need check Meta.Dir twice

- cmd/influx_tsm/b1/reader.go
- cmd/influx_tsm/bz1/reader.go
- cmd/influx_tsm/converter.go
- cmd/influx_tsm/main.go
- cmd/influx_tsm/tracker.go
- cmd/influx_tsm/tsdb/codec.go
- cmd/influx_tsm/tsdb/database.go
- cmd/influx_tsm/tsdb/values.go
- cmd/influxd/restore/restore.go
- cmd/influxd/run/config.go
- cmd/influxd/run/server.go
> Linted cmd/ packages. Refs #4098

- CHANGELOG.md
- cluster/rpc.go
- cluster/rpc_test.go
- influxql/internal/internal.pb.go
- influxql/internal/internal.proto
- influxql/iterator.go
- influxql/iterator_test.go
Adds missing binary marshaling to `influxql.SeriesList`.
/cc @jsternberg
> Add SeriesList binary marshaling

- test.sh
This updates the circle CI build to reduce some intermittent failures.  
Specifically:
* Remove go tip
* Test with go1.6
> Update circle ci build envs

- Godeps
- build.py
Pinning golang.org/x/tools dependency in preparation for Go 1.4 [EOL](https://groups.google.com/forum/#!topic/golang-announce/JMs4_CGbXWk).
> Pin golang.org/x/tools build dependency

- influxql/iterator.gen.go
- influxql/select.go
- influxql/select_test.go
> Have division always return a float in the new query engine

- influxql/call_iterator.go
Export needed function for Kapacitor.
Also changes `tags != nil` to `len(tags) > 0` for the top/bottom functions, since Kapacitor is not explicitly passing nil.
> Export needed function for Kapacitor

- CHANGELOG.md
- influxql/ast.go
- influxql/ast_test.go
> Support using field regex comparisons in the WHERE clause

- stress/basic.go
- stress/config.go
Fixes https://github.com/influxdata/influxdb/issues/5972
> Fix concurrent map access

- client/v2/client.go
Simple addition to v2 client for a helper method to add many points at once.
> Add AddPoints method to v2 client

- influxql/ast.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/iterator_test.go
- influxql/parser_test.go
- influxql/select.go
- influxql/select_test.go
> Various fixes for binary expression math between iterators

- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/select.go
- influxql/select_test.go
> Make binary expressions with either point being nil return a nil point

- CHANGELOG.md
- services/meta/client.go
- services/meta/data.go
> make CREATE USER default to IF NOT EXISTS

- cluster/query_executor.go
This got missed when I cherry-picked parts of the previous PR.
> Wire up DROP SHARD to executor

- cmd/influx_tsm/README.md
I also made minor tweaks to the formatting, but the warning is [here](https://github.com/influxdata/influxdb/compare/ross-influx-tsm-doc-update?expand=1#diff-d60883eeecee971a66d53ce474fddfb0R93).
/cc @joelegasse
> Update influx_tsm README with information about shard permissions

- CHANGELOG.md
> Update CHANGELOG with 0.11 release notes

- services/snapshotter/client.go
> add snapshotter client

- cmd/influxd/run/server.go
- cmd/influxd/run/server_dataonly.go
- cmd/influxd/run/server_default.go
> Add a build tag to disable all services except TCP endpoint

- influxql/statement_rewriter.go
- influxql/statement_rewriter_test.go
- tsdb/meta.go
> Rename the special condition "name" to "_name" to reduce conflicts

- tcp/mux.go
If the mux listener gets a invalid request, log the IP address of the
client to help users track down the issue.
Since the listener is started before the services that use it are ready,
it can receive requests and block indefinitely waiting for the handler
channel to receive.  If the channel is block, end the connection early
to prevent clients from accruing blocked connections.
> Improve logging and blocked connection handling in muxer

- services/meta/data.go
> rename CloneUserInfos to CloneUsers

- CHANGELOG.md
- cluster/config.go
- cmd/influxd/run/server.go
- influxql/query_manager.go
- influxql/query_manager_test.go
> Limit the maximum number of concurrent queries

- influxql/ast.go
- influxql/ast_test.go
> Fix eval when types do not match between the lhs and rhs

- influxql/iterator.go
> Modify fill(null) to fill(none) in SELECT INTO queries

- client/README.md
> remove unneeded 'import' in client/README.md

- influxql/internal/internal.pb.go
- influxql/iterator.gen.go.tmpl
Regenerated the protobuf file for influxql to use a newer protobuf.
> Fix a bad merge that removed ExpandSources from AuxIterators

- CHANGELOG.md
- services/httpd/handler.go
> Extend http routes

- .github/PULL_REQUEST_TEMPLATE.md
> update PR template to avoid stale InfluxQL spec

- services/httpd/handler.go
> Fix inconsistent route name

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/ast.go
- influxql/call_iterator.go
- influxql/parser_test.go
- influxql/select.go
- influxql/select_test.go
The difference function is implemented very similar to how derivative is
implemented. It is an aggregate function that acts over the entire
aggregate. This function will also have the same problems that
derivative has with getting values from the previous interval or point.
This will be fixed separately as part of #5943.
Fixes #1825.
> Implement the difference function

- CHANGELOG.md
Signed CLA and based off master
> Fix typo in url of issue referenced in CHANGELOG.md

- cluster/config.go
- cluster/query_executor.go
- cmd/influxd/run/server.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/monitor.go
- influxql/query_manager.go
- services/httpd/handler.go
- tsdb/engine/tsm1/iterator.gen.go
- tsdb/engine/tsm1/iterator.gen.go.tmpl
Also modified the query manager to be able to return custom error messages.
Fixes #6077.
> Implement the point limit monitor

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/ast.go
- influxql/call_iterator.go
- influxql/functions.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/parser_test.go
- influxql/select.go
- influxql/select_test.go
> Implement simple moving average

- CHANGELOG.md
- cluster/config.go
- cluster/query_executor.go
- cluster/query_executor_test.go
- cmd/influxd/run/server.go
- etc/config.sample.toml
> Limit bucket count in selection

- CHANGELOG.md
- services/meta/client.go
- services/meta/client_test.go
> Check ShardGroup Duration when recreating database

- CHANGELOG.md
- services/meta/client_test.go
- services/meta/data.go
> Ensure ShardGroupDuration checked when recreating an RP

- cmd/influxd/run/server.go
> Clarify the upgrade error message.

- CHANGELOG.md
> Update CHANGELOG.md with release notes for 0.12.0

- CONTRIBUTING.md
This commit provides instructions on how to install the `tmpl` utility and how to generate templates in the project.
Fixes #6215
/cc @e-dard
> Add tmpl to contributing document

- services/admin/assets/index.html
Link the Admin UI to the 0.12 docs.
> Update documentation link

- etc/config.sample.toml
> Fix config typo

- cluster/service.go
If a non-existant shard was requested as part of the iterator,
the influxd server would panic. Now it handles this situation by
skipping the offending shard and returning properly when none could be
found.
> Fix processCreateIteratorRequest panic

- CHANGELOG.md
- client/v2/client.go
- client/v2/client_test.go
> Ensure Client is safe for concurrent use

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/ast.go
- influxql/call_iterator.go
- influxql/parser_test.go
> Allow percentile to be used as a selector

- CHANGELOG.md
- cmd/influx_inspect/info.go
If FieldCodec f is nil return nil when FieldCoded.Fields() is called.
Fixes #6294
> Check FieldCodec f in FieldCoded.Fields()

- CHANGELOG.md
Removed bugfixes from 0.13.0 that were included in 0.12.1.
> Update the changelog in master from v0.12.1

- cmd/influxd/run/server_default.go
- services/httpd/handler.go
- services/meta/write_authorizer.go
This PR adds a WriteAuthorizer interface, similar to the existing QueryAuthorizer interface.
> add WriteAuthorizer interface

- CHANGELOG.md
- influxql/ast.go
- influxql/call_iterator.go
- influxql/functions.gen.go
- influxql/functions.gen.go.tmpl
- influxql/iterator.go
- influxql/iterator_test.go
- influxql/select.go
- influxql/select_test.go
> Add elapsed function

- cmd/influxd/run/server.go
- cmd/influxd/run/server_dataonly.go
- cmd/influxd/run/server_default.go
> Skip raft.db in dataonly build

- CHANGELOG.md
- cmd/influxd/run/config.go
- cmd/influxd/run/config_test.go
> Fix setting uint config options via env vars

- tsdb/engine/tsm1/float.go
This commit changes the `FloatDecoder.val` from a `float64` type to a `uint64` to avoid an additional type conversion during read. Now the type gets converted to a `float64` only on call to `Values()`.
/cc @jwilder 
```
benchmark                                   old ns/op     new ns/op     delta
BenchmarkEngine_CreateIterator_Count_1M     12145578      11839383      -2.52%
benchmark                                   old allocs     new allocs     delta
BenchmarkEngine_CreateIterator_Count_1M     74             73             -1.35%
```
> Optimize tsm1.FloatDecoder

- CHANGELOG.md
- cluster/config.go
- cmd/influxd/run/server.go
- influxql/query_executor.go
> Log slow queries if they pass a configurable threshold

- Godeps
- tsdb/engine/tsm1/encoding.go
- tsdb/engine/tsm1/encoding_test.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/file_store_test.go
- tsdb/engine/tsm1/int.go
- tsdb/engine/tsm1/iterator.gen.go
- tsdb/engine/tsm1/iterator.gen.go.tmpl
- tsdb/engine/tsm1/reader.go
- tsdb/engine/tsm1/timestamp.go
- tsdb/engine/tsm1/timestamp_test.go
Update the `simple8b` depedency to the latest version.
/cc @jwilder
> update dep: simple8b @ b421ab40

- .gitattributes
> Attempt to use union merge strategy on CHANGELOG

- tsdb/engine/tsm1/compact.go
If the first block had tombstones and there was only 1 block left, we could end up skipping the dedup step during compactions allowing the deleted data to come back in to the new TSM file incorrectly.
> Fix first block not getting purged when deleting series

- CHANGELOG.md
- influxql/README.md
related to https://github.com/influxdata/docs.influxdata.com/issues/337
@benbjohnson @jsternberg
> fix #6505: update InfluxQL README.md for regex_lit

- influxql/README.md
> Add NAME token to the list of reserved keywords

- monitor/service.go
Small change to allow the monitor service to be started and stopped multiple times, if necessary.
> Allow Monitor to be restarted

- influxql/README.md
This changes the `DELETE SERIES` specification to `DELETE`.
/cc @gunnaraasen
> Fix DELETE Spec

- CHANGELOG.md
- influxql/call_iterator.go
- influxql/call_iterator_test.go
> Support booleans for min() and max()

- test.sh
> Remove automatic upload of packages to S3

- services/meta/file_windows.go
- tsdb/engine/tsm1/file_windows.go
Fix build tag for `windows` build.
> Fix invalid build tag

- client/v2/client.go
> Cherry pick #6565 into 0.13

- cmd/influxd/run/backup_restore_test.go
Skipping an intermittent test.  Logged a follow up issue here: #6590
> intermittent test failing

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/statement_rewriter.go
- influxql/statement_rewriter_test.go
- tsdb/shard.go
> Update SHOW FIELD KEYS to return the field type with the field key

- .mention-bot
Does what is says in the dot-file.
> Filtering some authors from mention bot

- tsdb/engine/tsm1/engine.go
This commit changes the `tsm1.Engine` to create individual series iterators in batches so that it can be parallelized. Iterators are combined at the end so they can be redistributed to the parallelized merge iterator.
/cc @jwilder @toddboom 
The query time for a `SELECT count(value) FROM cpu` across 1B points on an AWS c4.8xlarge instance dropped from `16s` (62.5M pt/sec) to `9s` (111M pt/sec).
> Parallelize query planning

- client/README.md
> fix import block in example

- CHANGELOG.md
- cmd/influxd/run/server.go
> query-log-enabled not ignored in config anymore

- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
This reverts commit d99c5e26f69659d71c7ebeef4b64308e60970a08.
There is a problem with this commit that can cause data loss.  Reverting until it can be fixed.
Re-opens #6557
> Revert "Fix memory spike when compacting overwritten points"

- coordinator/points_writer.go
- coordinator/points_writer_test.go
Removes some unused references.
> Remove references to Hinted Handoff

- CHANGELOG.md
- influxql/query_executor.go
> Print the query executor's stack trace on a panic to the log

- CHANGELOG.md
- tsdb/store.go
> Fix loop variable reuse in database close

- tcp/mux.go
This change allows for TCP connections with unregistered first bytes coming in to the `tcp.Mux` to be passed-through to a default listener, replaying the first byte, as though the `Mux` was never there.
As written in the comment, this can be useful for serving HTTP debug/status info on the same port as the internal maintenance port.
> Add DefaultListener to tcp.Mux

- .hooks/pre-commit
- Godeps
- LICENSE_OF_DEPENDENCIES.md
- build.py
- cmd/influxd/run/config_test.go
- influxql/ast.go
- tsdb/engine/tsm1/file_store_test.go
- tsdb/engine/tsm1/tombstone.go
- tsdb/engine/tsm1/writer.go
- tsdb/shard.go
This PR fixes a bunch of outstanding `vet` issues.
`go vet` does not seem to be running on Circle. @rossmcdonald any ideas?
> Fix vet issues

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- coordinator/statement_executor.go
- services/meta/errors.go
> check that RPs exist before creating CQ

- build.py
> Removed unused variable in build script

- influxql/query_executor.go
- services/httpd/handler.go
We need more context when panics are recovered.
> Add more context to recovered panics

- tsdb/engine/tsm1/tombstone.go
[`os.Open`](https://godoc.org/os#Open) is documented as:
> Open opens the named file for reading. If successful, methods on the returned file can be used for reading;
That suggests the file's methods should only be called if opening was successful. The original code would `defer f.Close()` right after `os.Open`, before ensuring that `err` is `nil`, so `f.Close()` would run even if `os.Open` did not return successfully.
Apply https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow suggestion to keep the normal path at minimal indentation, and indent the error handling code instead. This improves code readability.
(This is my first PR to InfluxDB, and I welcome any feedback/criticism for how I can do better.)
> tsdb/engine/tsm1: Check os.Open error before using file.

- etc/config.sample.toml
Fixes https://github.com/influxdata/influxdb/issues/6682
> Remove cluster section from sample configuration

- models/points_test.go
- tsdb/engine/tsm1/engine.go
This PR fixes a vet issue that somehow got through CI, and reverts a fat-finger error on my part. :grimacing:
> Vet fix and revert 

- tsdb/engine/tsm1/engine_test.go
> Benchmarks to count allocs in WritePoints.

- monitor/service.go
> Update comment for SetPointsWriter in the monitoring service

- CHANGELOG.md
- coordinator/points_writer_test.go
- coordinator/statement_executor.go
> batch SELECT INTO writes

- influxql/call_iterator.go
- influxql/functions.gen.go
- influxql/functions.gen.go.tmpl
I still need to write a test for this specific use case but this is the general idea.
> Count and Sum return 0 for empty intervals

- influxql/iterator.go
This pull request moves iterator merging into its own function so it can be reused.
> Add Iterators.Merge()

- CHANGELOG.md
- services/httpd/handler.go
- services/httpd/handler_test.go
> Set X-Influxdb-Version header on every request (even 404 requests)

- CHANGELOG.md
- services/meta/client.go
> lock auth properly

- tsdb/engine/tsm1/engine.go
Restore would try to open the shard if there was an error.  If there
was an error, the files written are very likely to be partially written
and they can cause the server to panic.
To prevent a shard from trying to open broken files, we now write to
a temp file and rename it to the actual name only after fully writing
and fsyncing the file.
> Ensure restore doesn't write broken files

- stress/v2/ponyExpress/ponyExpress.go
- stress/v2/ponyExpress/ponyExpress_query.go
- stress/v2/ponyExpress/ponyExpress_write.go
> Fix write to and query from cluster

- stress/v2/ponyExpress/ponyExpress.go
- stress/v2/ponyExpress/ponyExpress_query.go
- stress/v2/ponyExpress/ponyExpress_write.go
> Add ssl, un, pw support to v2 stress

- services/admin/assets/index.html
I think navbar-brand has to reload the page.
> Fixed admin page reloaded when navbar-brand clicked

- .github/PULL_REQUEST_TEMPLATE.md
Ironically, I deleted the PR template from this PR. How meta.
@jwilder @pauldix this cool by you? If so I'll replicate to other repositories too.
> add syntax example to optional PR requirements

- CHANGELOG.md
- tsdb/engine/tsm1/cache.go
> Fix panic: runtime error: index out of range

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
> Fix fill(previous) when used with math operators

- CHANGELOG.md
- coordinator/points_writer.go
- coordinator/points_writer_test.go
> Drop writes from before the retention policy time window

- services/meta/errors.go
> Remove unused errors

- stress/v2/stressql/statement/parser.go
> Add @ symbol to -v2 stress

- CHANGELOG.md
- cmd/influxd/backup/backup.go
- cmd/influxd/help/help.go
- cmd/influxd/main.go
- cmd/influxd/restore/restore.go
- cmd/influxd/run/command.go
- cmd/influxd/run/config_command.go
> Always use the demo config when outputting a new config

- CHANGELOG.md
- services/collectd/service.go
> Support loading a folder for collectd typesdb files

- circle.yml
- test.sh
Will automatically upload builds when a version tag is applied.
> Update circle.yml to automate release upload on version tag

- coordinator/statement_executor.go
- tsdb/shard.go
SHOW MEASUREMENTS doesn't need to visit every shard in the open source
version since all of them contain the same database index.
Fixes #6950.
> Optimize SHOW MEASUREMENTS so it consults the database index directly

- circle.yml
> Correct Docker image name for Circle builds

- .github/ISSUE_TEMPLATE.md
> Add debug commands to issue template

- importer/README.md
> add example data to importer README.md

- CHANGELOG.md
- services/continuous_querier/service.go
> Log the CQ execution time when continuous query logging is enabled

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- CHANGELOG.md
- Dockerfile_build_ubuntu64
- build.py
- man/Makefile
- man/footer.txt
- man/influx.txt
- man/influxd-backup.txt
- man/influxd-config.txt
- man/influxd-restore.txt
- man/influxd-run.txt
- man/influxd-version.txt
- man/influxd.txt
> Create man pages for commands

- .github/ISSUE_TEMPLATE.md
> Add additional debug commands

- .github/ISSUE_TEMPLATE.md
> Add heap profile to issue template

- CHANGELOG.md
- coordinator/meta_client.go
- coordinator/meta_client_test.go
- coordinator/statement_executor.go
- services/meta/client.go
- services/meta/data.go
> revert previous DefaultRetentionPolicyName change

- CHANGELOG.md
- services/meta/client.go
- services/meta/client_test.go
- services/meta/config.go
- services/meta/data.go
> fix #7081: hardcode auto gen RP name

- CHANGELOG.md
- services/udp/README.md
- services/udp/service.go
> Fix incrementing pointsRx twice

- Godeps
- LICENSE_OF_DEPENDENCIES.md
Also reorganizing Godeps so it lists the dependencies in alphabetical
order.
> Update LICENSE_OF_DEPENDENCIES.md with github.com/retailnext/hllpp

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/ast.go
- influxql/ast_test.go
> Support wildcards in aggregate functions

- cmd/influx_inspect/README.md
> Update influx inspect readme with DDL information

- CHANGELOG.md
- models/points.go
- models/points_test.go
> Fix panic with parsing empty key

- influxql/call_iterator.go
- influxql/call_iterator_test.go
> benchmark tests for median aggrergator

- CHANGELOG.md
- influxql/query_executor.go
- services/httpd/handler.go
- services/httpd/handler_test.go
> Support tools for running async queries

- TODO.md
It would be a breaking change to v1, but it is something we likely want
to consider when we are working on v2.
> Add issue #2124 to the TODO list for v2

- CHANGELOG.md
> Update issue link to "Remove IF EXISTS/IF NOT ..."

- models/statistic.go
- monitor/service.go
> Fix "nil map" panic in statistics collection.

- influxql/README.md
Gets the InfluxQL Readme in sync with the 1.0 docs version of the same doc.
Also see https://github.com/influxdata/docs.influxdata.com/pull/605
> Update Influxql Readme

- tsdb/engine/tsm1/engine.go
This should handle concurrent calls to `DeleteSeriesRange` and ensure that compactions aren't restarted until all requests have been handled.
This may also help with #7168, but @e-dard would have to give this a look to see.
> TSM: Handle concurrent deletes for compaction

- CHANGELOG.md
- models/points.go
- models/points_test.go
> Allow blank lines in the line protocol input

- influxql/ast.go
- influxql/parser_test.go
> Properly output the SHOW TAG VALUES command so it can be reparsed

- TODO.md
Closes #4461.
/cc @beckettsean
> Add TODO to change time boundaries for v2

- CHANGELOG.md
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
> Merge 1.0 to master

- CHANGELOG.md
- etc/config.sample.toml
> Fixing typo within example configuration file

- tsdb/shard.go
> Fix engine tags in stats

- CHANGELOG.md
- tsdb/shard.go
> Emit fieldsCreated stat in shard measurement

- CHANGELOG.md
- client/influxdb.go
> Read an invalid JSON response as an error in the influx client

- influxql/parser_test.go
intended to prevent future regressions from #7316.  Test only, self-merging on green.
> Add test to prevent future parsing regressions for time durations

- tsdb/meta.go
- tsdb/meta_test.go
This calculates a max size of the `SeriesIDs` to avoid a bunch of `appends` that would resize it.
```
benchmark                                         old ns/op     new ns/op     delta
BenchmarkMeasurement_SeriesIDForExp_EQRegex-8     67843610      64845446      -4.42%
BenchmarkMeasurement_SeriesIDForExp_NERegex-8     20727611      21460651      +3.54%
benchmark                                         old allocs     new allocs     delta
BenchmarkMeasurement_SeriesIDForExp_EQRegex-8     35             4              -88.57%
BenchmarkMeasurement_SeriesIDForExp_NERegex-8     4              4              +0.00%
benchmark                                         old bytes     new bytes     delta
BenchmarkMeasurement_SeriesIDForExp_EQRegex-8     4655870       804843        -82.71% …
```
> Reduce allocations in idsForExpr

- Godeps
We are out of sync between projects, getting all projects back in sync.
> update protobuf dependency

- tsdb/engine/tsm1/encoding.go
Fix off-by-one error that could panic.
> Fix off-by-one error that could panic.

- services/meta/data.go
- services/meta/data_test.go
> Stablize the sorting of meta.ShardGroupInfos

- tsdb/engine/tsm1/compact.go
This is causing a fatal error: fault panic when packing blocks.
cc @joelegasse
> Revert re-using byte slices during compactions

- services/meta/client.go
The cacheData is read-only and does not need to be cloned.  Cloning
it for read operations can be expensive with lots of shards/database/RPs/etc.
cc @corylanou
> Don't clone the cached meta store

- CHANGELOG.md
- services/meta/client_test.go
- services/meta/data.go
- services/meta/errors.go
> Do not automatically reset the shard duration when using ALTER RETENTION POLICY

- DOCKER.md
- Dockerfile_build_ubuntu32
- Dockerfile_build_ubuntu64
- Dockerfile_build_ubuntu64_git
- appveyor.yml
- build-docker.sh
- build.py
- circle.yml
- cmd/influxd/run/server_suite_test.go
- cmd/influxd/run/server_test.go
Updated circleci and build scripts to use go 1.7.1
Updated failed test that specific for duration format in string.
> Use go 1.7.1 for testing

- CHANGELOG.md
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/int.go
- tsdb/engine/tsm1/int_test.go
- tsdb/engine/tsm1/reader.go
- tsdb/engine/tsm1/tombstone.go
- tsdb/engine/tsm1/tombstone_test.go
> Backport 1.0.2 Fixes

- CHANGELOG.md
- coordinator/points_writer.go
- coordinator/points_writer_test.go
- etc/config.sample.toml
- services/meta/client_test.go
- services/meta/data.go
- services/meta/errors.go
- services/subscriber/config.go
- services/subscriber/config_test.go
- services/subscriber/service.go
> Merge 1.0 branch

- cmd/influx/cli/cli.go
Fixes https://github.com/influxdata/influxdb/issues/7414
> Prevent writing auth command to influx_history

- coordinator/statement_executor.go
- services/httpd/response_logger.go
These fixed are along the way of reading `influxDB`'s source code. They are pretty trivial fixed.
> fixed two typo

- tsdb/engine/tsm1/engine.go
> Skip cleanup if dir does not exist

- DOCKER.md
- Dockerfile_build_ubuntu32
- Dockerfile_build_ubuntu64
- Dockerfile_build_ubuntu64_git
- build-docker.sh
- circle.yml
> Use go1.7.3

- CHANGELOG.md
> Highlight new query features

- CHANGELOG.md
- cmd/influxd/run/config.go
- etc/config.sample.toml
- services/admin/service.go
> Backport disable/deprecate admin interface

- cmd/influx/cli/cli.go
> Fix the `-execute` and `-import` when there is no TTY

- cmd/influx_inspect/README.md
Updates the flags in the `influx_inspect export` example to match the changes made in https://github.com/influxdata/influxdb/pull/7327/files.
> Update example in influx_inspect README.md

- cmd/influx_inspect/help/help.go
- cmd/influx_inspect/verify/verify.go
- man/influx_inspect.txt
> Mention verify subcommand in influx_inspect help

- CHANGELOG.md
> Merge 1.1 branch

- tsdb/config.go
- tsdb/engine/tsm1/engine.go
- tsdb/index.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/log_file.go
- tsdb/shard.go
Several fixes to get TSI runnable in the server.
@benbjohnson @e-dard
> TSI Fixes/Workarounds

- CHANGELOG.md
- tsdb/shard.go
- tsdb/shard_test.go
> Fix incorrect error message

- monitor/reporter.go
- monitor/service.go
contributes to issue #4098 
Added a comment to the Reporter interface
Fixed a capitalisation typo which presented a linting error
Added comment to type Statistics.
> Make monitor golintable

- services/httpd/handler_test.go
- services/httpd/response_logger.go
> Use X-Forwarded-For IP address in HTTP logger if present

- CHANGELOG.md
- services/meta/client.go
- services/meta/client_test.go
- services/retention/service.go
> Prune shards in meta data

- scripts/init.sh
fixes init.sh stop error on busybox systems
Fixes #7535
> make init.sh compatible with busybox

- CHANGELOG.md
- CONTRIBUTING.md
- DOCKER.md
- Dockerfile_build_ubuntu32
- Dockerfile_build_ubuntu64
- Dockerfile_build_ubuntu64_git
- build-docker.sh
- circle.yml
> Backport 7692

- CHANGELOG.md
- models/points.go
- models/points_test.go
> Backport 7679

- .github/PULL_REQUEST_TEMPLATE.md
This should help us keep docs more up to date.
// @rkuchan
> Add Documentation Task to Pull Request Template

- tsdb/engine/tsm1/file_store.gen.go
- tsdb/engine/tsm1/file_store.gen.go.tmpl
> Fix unchecked error in templated Read${TYPE}Block

- pkg/escape/bytes.go
- pkg/escape/strings.go
- pkg/escape/strings_test.go
> String escape & unescape unit tests & optimizations

- CHANGELOG.md
> Merge 1.1.1 to master

- CHANGELOG.md
Thanks @inselbuch for noticing the issue
> Fix changelog typo for fill linear PR

- CHANGELOG.md
- client/v2/client.go
- client/v2/client_test.go
- models/points.go
- models/points_test.go
- services/graphite/parser_test.go
- stress/v2/statement/query.go
- stress/v2/stress_client/commune_test.go
- stress/v2/stress_client/reporting_test.go
- stress/v2/stress_client/response.go
- stress/v2/stress_client/response_test.go
- stress/v2/stress_client/stressTest.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/engine.go
Panicing in libraries is bad :-(.
> Return Error instead of panic when decoding point values.

- influxql/parser.go
> Prefer built-in string -> []rune conversion

- monitor/config.go
- monitor/config_test.go
> Require database name on monitor config

- cmd/influxd/run/server_bench_test.go
These seem to have been broken in #7368.
> Fix broken server benchmarks

- cmd/influxd/run/config.go
- cmd/influxd/run/config_test.go
- services/continuous_querier/config.go
- services/continuous_querier/config_test.go
- services/precreator/config.go
- services/precreator/config_test.go
- services/retention/config.go
- services/retention/config_test.go
> Add more config validation

- influxql/iterator.go
- tsdb/engine/tsm1/engine.go
Also, fix the `Iterators.Merge(IteratorOptions)` function so it consults
the `Ordered` attribute to determine which iterator it should use to
merge the input iterators.
> Fix for subqueries to use the parallel iterator correctly

- CHANGELOG.md
- services/subscriber/service.go
- services/subscriber/service_test.go
> Ensure subscriber service respects config

- CHANGELOG.md
- tsdb/meta.go
- tsdb/shard.go
> [1.2] Backport #7847

- tsdb/meta.go
Fixes https://github.com/influxdata/influxdb/issues/7697
> Add stats on dropped measurements and series; Fixes #7697

- CHANGELOG.md
- cmd/influxd/run/server_helpers_test.go
- cmd/influxd/run/server_test.go
- coordinator/points_writer.go
- tsdb/shard.go
> allow partial writes on field conflicts

- CHANGELOG.md
- cmd/influxd/run/server_helpers_test.go
- cmd/influxd/run/server_test.go
- coordinator/points_writer.go
- tsdb/shard.go
> backport: allow partial writes on field conflicts

- services/meta/client.go
- services/meta/client_test.go
> [Backport 1.2] Fixes #7860.

- cmd/influxd/run/server_suite_test.go
- coordinator/statement_executor.go
> [Backport 1.2] #7866

- cmd/influxd/run/server_test.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/iterator.go
- influxql/select.go
> Support the WHERE clause in outer queries with subqueries

- cmd/influxd/run/server_test.go
- influxql/ast.go
- influxql/ast_test.go
- influxql/functions.gen.go
- influxql/functions.gen.go.tmpl
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/iterator.go
- influxql/parser_test.go
- influxql/select.go
> Backport #7841 and #7846 to 1.2

- client/README.md
Hello,
I have tried this example as it is for now. Encountered an error that AddPoint function expects only one argument. Checked projects GoDoc and updated the example in your error handling style. It works like this.
(seemed unnecessary as it is related to the README example function fix)
> Updating Readme to make writePoints function work

- CHANGELOG.md
Just a starter - @pauldix tweak as necessary.
> Update release notes for 1.2

- CHANGELOG.md
- influxql/ast.go
- influxql/ast_test.go
> Fix EvalType when a parenthesis expression is used

- cmd/influxd/run/server_test.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
> fix panic in query execution

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/ast.go
This is a port of #7934 to the `master` branch
> Porting #7934 to master

- tsdb/index/tsi1/log_file.go
- tsdb/index/tsi1/log_file_test.go
This PR changes how we store series within a `LogFile`. Prior to this, a reference to each series was stored on each measurement in a `LogFile` unordered. This gave constant time insertion, but when we needed to perform either a compaction, or iterate over all series (e.g., for a meta query such as `SHOW SERIES`) the series on each measurement would have to be sorted, and then all measurement series resorted when measurements were combined.
With this PR we'll keep them sorted on the measurements, and the merge multiple measurements' series when the `SeriesIterator` is called.
> Store series in sorted order in LogFile

- CHANGELOG.md
- coordinator/shard_mapper.go
- influxql/ast.go
- influxql/ast_test.go
- tsdb/shard.go
> Map types correctly when using a regex and one of the measurements is empty

- CHANGELOG.md
- models/points.go
- models/points_test.go
- tsdb/meta.go
- tsdb/shard.go
- tsdb/store.go
> Backport 7832 & 7929 & 8011

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
> Dividing aggregate functions with different outputs doesn't panic

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/ast.go
> Map types correctly when selecting a field with multiple measurements where one of the measurements is empty

- CHANGELOG.md
- models/points.go
- models/points_test.go
> Point.UnmarshalBinary() bounds check

- CHANGELOG.md
- influxql/statement_rewriter.go
> Include IsRawQuery in the rewritten statement for meta queries

- tsdb/engine/tsm1/engine.go
- tsdb/shard.go
> Fix panic: interface conversion: tsm1.Value is tsm1.IntegerValue, not tsm1.FloatValue

- CHANGELOG.md
- cmd/influxd/run/config.go
- cmd/influxd/run/server.go
- coordinator/config.go
- monitor/build_info.go
- monitor/config.go
- monitor/diagnostics/diagnostics.go
- monitor/go_runtime.go
- monitor/network.go
- monitor/service.go
- monitor/system.go
- services/collectd/config.go
- services/continuous_querier/config.go
- services/graphite/config.go
- services/httpd/config.go
- services/meta/config.go
- services/opentsdb/config.go
- services/precreator/config.go
- services/retention/config.go
- services/subscriber/config.go
- services/udp/config.go
- tsdb/config.go
> Report subset of config values in SHOW DIAGNOSTICS

- .github/PULL_REQUEST_TEMPLATE.md
This should help reduce churn related to config changes.
> Mention config settings in PR template

- tsdb/index/internal/file_set.go
- tsdb/index/tsi1/file_set.go
- tsdb/index/tsi1/file_set_test.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_file.go
- tsdb/index/tsi1/index_files.go
- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/log_file.go
- tsdb/index/tsi1/log_file_test.go
- tsdb/index/tsi1/series_block.go
- tsdb/index/tsi1/series_block_test.go
- tsdb/index/tsi1/tag_block.go
- tsdb/index/tsi1/tag_block_test.go
- tsdb/index/tsi1/tsi1.go
> [WIP] TSI Compaction Refactor

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- Godeps
- etc/config.sample.toml
- influxql/README.md
- influxql/ast.go
- influxql/ast_test.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/parser.go
- influxql/parser_test.go
- influxql/scanner.go
- influxql/select_test.go
- influxql/token.go
- services/continuous_querier/service.go
- services/continuous_querier/service_test.go
- tsdb/config.go
- tsdb/config_test.go
- tsdb/engine/tsm1/encoding.gen.go
- tsdb/engine/tsm1/encoding.gen.go.tmpl
- tsdb/engine/tsm1/encoding_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/wal.go
- tsdb/index/inmem/inmem.go
- tsdb/shard.go
`n` only gets updated when there are max tag values limits set.  The re-slicing slices off all series that need to get created causing them to not get created.
Fixes #8169
> Fix series not getting created

- circle.yml
- pkg/estimator/hll/hll.go
- tsdb/engine/tsm1/cache_test.go
- tsdb/engine/tsm1/wal.go
- tsdb/shard.go
- tsdb/store_test.go
> Prevent panic on engine/cardinality race

- CHANGELOG.md
- tests/server_helpers.go
- tests/server_test.go
`LocalServer` was racy with closing and writing.
Fixes #8177 
Fixes #8159
> Fix race in test helpers

- tsdb/index/tsi1/series_block.go
> Use variable length encoding of tag count

- etc/config.sample.toml
Fixed to shared-secret
- [ x] Rebased/mergable
- [ x] Tests pass
- [ x] CHANGELOG.md updated
> Fix spelling mistake in HTTP section of config -- shared-sercret

- CHANGELOG.md
- services/httpd/handler.go
- services/httpd/handler_test.go
- services/meta/client.go
- services/meta/data.go
- services/meta/data_test.go
> Reduce cost of admin user check

- CHANGELOG.md
- cmd/influxd/run/server_test.go
- influxql/select.go
> Backporting two query engine fixes for 1.2.3

- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/log_file.go
> remove TSI debugging info

- tsdb/store.go
- tsdb/store_test.go
> Ensure MeasurementNames deduplicates measurements across shards

- .gitignore
- build.py
- circle-test.sh
- test.sh
> Use go junit formatter to output tests in junit format on CircleCI

- CHANGELOG.md
> Add changelog for 8187

- CHANGELOG.md
- influxql/ast.go
- influxql/ast_test.go
> Cherry Pick Security Fixes to 1.2

- etc/config.sample.toml
> Fix spelling mistake in HTTP section of config (influxdb#8231)

- CHANGELOG.md
- cmd/influx/cli/cli.go
> Cherry Pick sanitize passwords in CLI history

- tsdb/index/tsi1/doc.go
I removed specific sizing and tried to generalize at a higher level than what was previously in the spec.
> Add TSI documentation

- CONTRIBUTING.md
Changes Google Groups to InfluxData Community.
> Update CONTRIBUTING with InfluxData Community link

- CHANGELOG.md
> update 1.2 CHANGELOG

- tsdb/meta.go
- tsdb/meta_test.go
The lazy sorting of series caused a deadlock since it can take
a `Lock` when a caller may have already acquired an `RLock`.
`filters` should be called w/o any locks as the function already acquires
locks as needed.
Same root cause as #8263 which was introduced in #8204
Fixes #8354
> Fix deadlock in Measurement

- CHANGELOG.md
- services/httpd/response_writer.go
- services/httpd/response_writer_test.go
> Set the CSV output to an empty string for null values

- CHANGELOG.md
> Update 1.2.4 release date

- CHANGELOG.md
- etc/config.sample.toml
> Small edits to the etc/config.sample.toml file

- cmd/influx_inspect/report/report.go
This PR is a simple change to sort the keys for the series measurements, fields and tags during the `influx_inspect report --detailed` command. No other changes to the functionality, simply making things look more legible.
[sample output](https://gist.github.com/sebito91/d2ded39ce760f79da7b7cd385c96d98a)
> sort influx_inspect detailed report results

- tsdb/engine/tsm1/engine_test.go
The test for backing up a shard assumed the files would appear sorted in the tar archive. For some reason, it only ever fails on my machine :shrug:
This was fixed in January by updating to `ioutil.ReadDir` for generating the backup, but was broken again by TSI.
This time, I just fixed the test to not assume the files would be sorted.
> tsm: fixed test to not require sorted backup tarball

- tsdb/shard.go
> Expose shard meta info on Shard

- CHANGELOG.md
- influxql/parser.go
- influxql/parser_test.go
> Add nanosecond duration literal support

- pkg/estimator/hll/compressed.go
> Fix HLL variableLengthList size decoding.

- CHANGELOG.md
Bring CHANGELOG up-to-date with 1.1 and 1.2 releases.
> Add 1.2.4 and 1.1.5 CHANGELOG updates.

- tests/server_test.go
The test cases demonstrate that the following issues are resolved
through some newer features.
Related to #813, #5095, #2467, #5345, and #5150.
> Add test cases for older issues that are now resolved

- Godeps
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_file_test.go
- tsdb/index/tsi1/index_files.go
- tsdb/index/tsi1/index_files_test.go
- tsdb/index/tsi1/log_file.go
- tsdb/index/tsi1/log_file_test.go
Also added `murmur3` to `Godeps`.
> Fix tsi go vet issues.

- services/meta/data.go
- services/meta/data_internal_test.go
> remove unused NewShardOwner func

- tsdb/index/tsi1/index.go
> Fix compile error

- CONTRIBUTING.md
- Dockerfile_build_ubuntu32
- Dockerfile_build_ubuntu64
- Dockerfile_build_ubuntu64_git
- circle.yml
> Update to go1.8.3

- influxql/select.go
- tests/server_test.go
> Queries for `bottom()` with no tags got messed up while changing the implementation

- CHANGELOG.md
- services/httpd/handler.go
- services/httpd/handler_test.go
> URL query parameter credentials take priority over Authentication header

- etc/config.sample.toml
This PR should qualify for "trivial PR" so that the following check list is assumed to be non-relevant.
> Fix typos in comments.

- Godeps
> Update gogo protobuf dependency

- Godeps
(cherry picked from commit 6b3aa44)
> Update gogo protobuf

- CHANGELOG.md
- tsdb/store.go
The merging of values & `SHOW TAG VALUES` broke during the transition to TSI.
Fixes #8443.
> Fix SHOW TAG VALUES deduplication.

- CHANGELOG.md
- tsdb/store.go
https://github.com/influxdata/influxdb/pull/8447
> Fix SHOW TAG VALUES deduplication. (1.3)

- CHANGELOG.md
- etc/config.sample.toml
- services/httpd/config.go
- services/httpd/config_test.go
- services/httpd/gzip.go
- services/httpd/handler.go
- services/httpd/handler_test.go
- services/httpd/io.go
- services/httpd/io_test.go
> Configuration to limit size of client request body

- cmd/influxd/run/server.go
remove duplicated assignment in cmd/influxd/run/server
> remove duplicated assignment in cmd/influxd/run/server

- etc/config.sample.toml
Point out that this limit is only checked every 10 seconds.
> Update the comment for `max-select-point`

- models/points.go
> optimize point split, which reduce unnecessary allocate

- cmd/influx_inspect/help/help.go
Fixes https://github.com/influxdata/influxdb/pull/8366#issuecomment-309402335 mentioned by @freeseacher.
> Add dumptsi command to help command.

- CHANGELOG.md
- pkg/mmap/mmap_solaris.go
> Fix building on solaris/illumos

- tsdb/index/inmem/inmem.go
This may fix the deadlocks seen in #8500.
> Fix possible deadlocks in inmem index

- CHANGELOG.md
- etc/config.sample.toml
- services/collectd/README.md
- services/collectd/config.go
- services/collectd/service.go
- services/collectd/service_test.go
> 8426 add a config option so collectd can generate multiple fields, not multiple measurements

- cmd/influxd/run/server.go
> Remove the repeat code

- tsdb/index/tsi1/index.go
> Fix TSI issue with spaces in tag values.

- tsdb/index/tsi1/index.go
> Fix TSI issue with spaces in tag values (1.3)

- CHANGELOG.md
- tsdb/index/inmem/meta.go
> Free RLock prior to returning

- CHANGELOG.md
> Update changelog release date for 1.3.1

- client/README.md
> Correct the client package README

- CHANGELOG.md
- services/continuous_querier/service.go
- services/continuous_querier/service_test.go
> Accomodate for time zones with continuous query scheduling

- CHANGELOG.md
We have landed changelog updates to 1.3 that didn't get cherry picked from master; edit those into master's changelog.
> Update CHANGELOG with 1.3 release dates.

- tsdb/shard_test.go
tsdb.Shard and tsdb.Shards both implement tsdb.ShardGroup and neither
were tested within the tsdb package itself. This adds tests for those
methods which are used by the query engine.
> Improve test cases in the tsdb package for the ShardGroup interface

- CHANGELOG.md
- tests/server_helpers.go
- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/index.go
- tsdb/index/inmem/inmem.go
- tsdb/index/inmem/meta.go
- tsdb/index/tsi1/file_set.go
- tsdb/index/tsi1/index.go
- tsdb/store.go
- tsdb/store_internal_test.go
- tsdb/store_test.go
Backport `SHOW TAG VALUES` performance improvements.
> [1.3] Backport #8660

- CHANGELOG.md
- influxql/iterator.go
> 13 backport of #8681

- pkg/slices/strings_test.go
> Test slices strings Exists* functions

- CHANGELOG.md
> Update CHANGELOG for 1.3.3 release

- tsdb/index/inmem/inmem.go
This change will apply fine-grained authorization rules to the `SHOW SERIES` query.
> auth: apply FGA to SHOW SERIES

- CHANGELOG.md
- coordinator/statement_executor.go
- influxql/ast.go
- influxql/ast_test.go
- influxql/iterator.gen.go
- influxql/iterator.gen.go.tmpl
- influxql/iterator.go
- influxql/iterator_test.go
- services/continuous_querier/service.go
- services/continuous_querier/service_test.go
> Backport time zone fixes to 1.3.

- CHANGELOG.md
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/iterator.gen.go
- tsdb/engine/tsm1/iterator.gen.go.tmpl
- tsdb/engine/tsm1/iterator.go
(cherry picked from commit 3caeee8)
> fix: cursor leak when cur == nil and aux or conds is not empty

- CHANGELOG.md
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
> Backport #8714

- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/iterator.gen.go
- tsdb/engine/tsm1/iterator.gen.go.tmpl
- tsdb/engine/tsm1/iterator.go
> log message when iterator is closed by finalizer

- coordinator/shard_mapper.go
- coordinator/shard_mapper_test.go
- coordinator/statement_executor.go
- query/select.go
- query/select_test.go
> Pass the select options to the shard mapper again

- coordinator/statement_executor.go
- influxql/README.md
- influxql/ast.go
- influxql/ast_test.go
- influxql/parse_tree.go
- influxql/parser.go
- influxql/parser_test.go
- influxql/token.go
> Update parser and AST for explain statement

- CHANGELOG.md
- tsdb/index/inmem/inmem.go
> fix race condition reading seriesByID map

- CHANGELOG.md
- tsdb/index/inmem/inmem.go
> Fix race condition accessing map in inmem index

- tsdb/shard.go
> Fix panic when the engine already closed in a shard

- CHANGELOG.md
- tsdb/shard.go
> Back port #8787

- CHANGELOG.md
- query/explain.go
- query/iterator.go
- tsdb/engine/tsm1/engine.go
> Include the number of scanned cached values in the iterator cost

- tsdb/index/tsi1/index.go
> auth: apply series auth to TSI

- CHANGELOG.md
- tsdb/engine/tsm1/cache.go
- tsdb/engine/tsm1/cache_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/wal.go
> Backport #8804

- query/compile.go
- query/iterator.go
> Fix time constraints in subqueries from the refactor

- services/httpd/response_writer.go
- services/httpd/response_writer_test.go
> uint64 support in the csv handler

- tsdb/shard.go
> Correctly check if the Shard is ready for queries or writes

- tsdb/engine/tsm1/encoding.gen.go
- tsdb/engine/tsm1/encoding.gen.go.tmpl
- tsdb/engine/tsm1/encoding.gen_test.go
> fix FindValues panic for empty array

- releng/packages/build.bash
- releng/packages/fs/usr/local/bin/influxdb_packages.bash
> Updated packaging script to better handle static packaging

- LICENSE_OF_DEPENDENCIES.md
We are no longer using this dependency however we failed
to remove the license file when we stopped using this
with removal of the admin interface.
> Remove unused glyphicons package from licenses file.

- releng/packages/build.bash
> Master 1657 -- bugfix in packaging script

- cmd/influx_stress/examples/template.toml
just a simple wording fix when I was reading the docs.
> simple typo fix

- query/emitter.go
> Support the unsigned type in query.Emitter

- CHANGELOG.md
- tsdb/engine/tsm1/cache.go
- tsdb/engine/tsm1/engine.go
> [BP 1.3] Fix race on cache entry

- CHANGELOG.md
- cmd/influx/cli/cli.go
- cmd/influx/cli/cli_test.go
I'm trying to fix #8590 . It's my first PR, happy to hear any comments.
> Influx CLI: Make cli case insensitive

- CHANGELOG.md
> Document that query ordering must be consistent in subqueries

- CHANGELOG.md
- tsdb/batcher.go
> Fix a minor memory leak when batching points for some services.

- cmd/influx_inspect/dumptsi/dumptsi.go
- coordinator/statement_executor.go
- coordinator/statement_executor_test.go
- tests/server_concurrent_test.go
- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/index.go
- tsdb/index/inmem/inmem.go
- tsdb/index/inmem/meta.go
- tsdb/index/tsi1/file_set.go
- tsdb/index/tsi1/index.go
- tsdb/shard.go
- tsdb/store.go
- tsdb/store_test.go
> auth: add series auth to 'show tag values'

- CHANGELOG.md
- scripts/init.sh
- scripts/post-install.sh
- scripts/post-uninstall.sh
Some systems don't have `which` installed.
Also fix some whitespace issues.
> Use `command` instead of `which`

- build.py
similar to https://github.com/influxdata/telegraf/issues/1704
> always force the file inside the tarball owned by root

- CHANGELOG.md
- releng/packages/fs/usr/local/bin/influxdb_packages.bash
- releng/packages/spec/clean_install/_install_uninstall.bash
- releng/packages/spec/clean_install/run.bash
- releng/source-tarball/Dockerfile
- releng/source-tarball/fs/usr/local/bin/influxdb_tarball.bash
> Backport including manpages in releng packaging

- CHANGELOG.md
- scripts/init.sh
- scripts/post-install.sh
- scripts/post-uninstall.sh
> Backport: Use `command` instead of `which`

- releng/packages/fs/usr/local/bin/influxdb_packages.bash
> backport to fix names used in build script

- cmd/influx_inspect/dumptsm/dumptsm.go
- cmd/influx_inspect/export/export.go
- cmd/influx_inspect/export/export_test.go
> Update influx inspect to support unsigned types

- client/README.md
- client/influxdb.go
- client/influxdb_test.go
- client/v2/client_test.go
- models/points.go
- models/points_test.go
> Add support for uint64 in the clients

- releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash
> Ensure Windows binaries have .exe suffix

- query/point.go
> Support marshaling unsigned points

- tsdb/engine/tsm1/compact.go
This reuses some intermediate buffers and structs while compacting
files.
> Reduce allocation in tsmKeyIterator.Next

- releng/packages/spec/clean_install/_install_uninstall.bash
> Fix manpage test

- CONTRIBUTING.md
- Dockerfile_build_ubuntu32
- Dockerfile_build_ubuntu64
- Dockerfile_build_ubuntu64_git
- Dockerfile_build_ubuntu64_go19
- circle.yml
- releng/_go_versions.sh
> Update to next version of Go with security fixes

- CONTRIBUTING.md
- Dockerfile_build_ubuntu32
- Dockerfile_build_ubuntu64
- Dockerfile_build_ubuntu64_git
- circle.yml
- releng/_go_versions.sh
> 1.3: Update to next version of Go with security fixes

- cmd/influx_inspect/report/report.go
This updates the `influx_inspect report` command to be able to report cardinalities across
all dbs and shards.  The dir parameter was made more flexible and can be any dir to walk.  If the tool finds TSM files, it extrapolates the db, rp and id from the path and collects cardinalities on series.  To restrict to specific db or rp, you can specify that db or rp as the dir.  
It also will report the estimated delta of new seres from the cumulative total per db.  This allows you to see if new shards are adding new series or if they exist already.  If they are new, the estimated cardinality of the new series is shown.
Example output:
```
$influx_inspect report  ~/.influxdb/data
DB      RP      Shard   File                    Series  New (Est) Load Time
stress  autogen 23 …
```
> Update influx_inspect to report total cardinalities

- tests/server_test.go
> Add an integration test for writing the uint protocol and reading it

- tsdb/engine/tsm1/engine.go
The scheduling logic ended up favoring more backlogged shards
too much and would starve active, less backed up shards.  This
occurred because the scheduling kicks in once a second.  When it
runs, it schedules as many compactions as it can.  A backed up shard
would end up having more compactions to run during the loop an would
generally get to schedule them more frequently.
This now allows each shard to try and schedule one compaction at a time
which provides a more balanced approach.  At some point, we'll probably
want to more directly balanc the each shards backlog vs letting it happen
somewhat randomly.
> Only schedule one compaction per shard at a time

- cmd/influx_inspect/report/report.go
This adds a `-exact` flag that can be used to report exact cardinality counts instead of the default estimated counts.  This is not the default since using `influx_inspect report` is intended to troubleshoot high cardinality shards and `-exact` will end up using a lot of memory in some cases.
This also orders the output of shards by ID as well as reports the time range per file and total for all files.
> Add support for exact cardinality count to influx_inspect

- tsdb/engine/tsm1/reader.go
`readKey` never sets `err`, therefore call sites checking for errors are unnecessary
> remove unnecessary err value

- build.py
- releng/packages/fs/usr/local/bin/influxdb_packages.bash
Fixes #8951.
Will add changelog on 1.3 backport.
> Add rpm dependency on shadow-utils for useradd

- CHANGELOG.md
- build.py
- releng/packages/fs/usr/local/bin/influxdb_packages.bash
> 1.3: add RPM dependency on shadow-utils

- cmd/influxd/run/command.go
- cmd/influxd/run/config.go
- cmd/influxd/run/config_command.go
- cmd/influxd/run/config_test.go
- cmd/integration_config_test.go
- cmd/integration_test.go
- services/httpd/service.go
Seeking feedback on the patterns introduced here, before following up with more tests for other configuration settings.  Particularly open to suggestions on simplifying reading and writing in test, even though I'm using the v2 client.
> Initial integration tests for config settings

- tsdb/index/tsi1/index.go
TSI did not check that max select series limit during planning
the same way that inmem did.  This means that the limit could be
set but the planning of a high cardinality query would still OOM
the server.  This fixes that limit as well as makes the query interruptible
during planning.
> Fix max select series limit for tsi

- services/udp/README.md
> Fix mis-typing in README.md of UDP Service

- CHANGELOG.md
> Update CHANGELOG for EXPLAIN ANALYZE feature

- pkg/metrics/descriptors.go
- pkg/metrics/descriptors_test.go
> fix overflow for 32-bit architecture

- tsdb/engine/tsm1/iterator.gen.go
- tsdb/engine/tsm1/iterator.gen.go.tmpl
> Add updated template for EXPLAIN ANALYZE

- tsdb/engine/tsm1/reader.go
This fixes a regression where deleting series keys would happen
one at a time instead of in bulk.
Fixes a regression introduced in #8981
> Delete series in batches

- coordinator/statement_executor.go
- query/iterator.gen.go
- query/iterator.gen.go.tmpl
- query/query_executor.go
- query/select.go
> fixes #9007

- releng/packages/fs/usr/local/bin/influxdb_packages.bash
Fixes for backward compatibility with 1.3.5 and earlier packages.
> Packaging fixes

- releng/packages/fs/usr/local/bin/influxdb_packages.bash
- releng/raw-binaries/build.bash
- releng/source-tarball/build.bash
> Packaging fixes backport

- QUERIES.md
Updated Queries.md to add example statements to Select, GroupBy and Delete
> Updated Queries.md

- services/storage/series_cursor.go
- services/storage/store.go
> check nil iterator

- Dockerfile
- docker/entrypoint.sh
- docker/init-influxdb.sh
The multistage build lets us build the image inside of one container and
then copy over the results to a new image so the build dependencies
aren't needed in the final container.
The resulting container should be identical to the official built ones
for every release, but coming from source instead.
> Use multistage builds in a Dockerfile to compile and create an image from source

- cmd/store/query/query.go
The store dev / test tool is for internal testing. This PR adds support for the additional frames.
> add additional frame types to store tool; count total points processed

- query/iterator.gen.go.tmpl
- tsdb/engine/tsm1/iterator.gen.go.tmpl
> Update the influxql path inside of the template files

- services/storage/rpc_service.go
> don't send empty ReadResponse

- Godeps
> Update Godeps to latest yamux with SYN fix

- tsdb/engine/tsm1/batch_cursor.gen.go
- tsdb/engine/tsm1/batch_cursor.gen.go.tmpl
> also slice values for batch cursors

- circle.yml
> Remove reference to docker cache dir

- services/storage/rpc_service.go
TODO(sgc): implement `writer` type that handles all the details
of writing frames to the RPC stream. Additional responsibilities
of writer include
* point frame recycling to reduce memory pressure
* skip empty point frames
* skip series frames with no points
> check and flush frames while streaming points for a series

- cmd/influxd/run/command_test.go
> Use the isolated temp dir for the test pid server

- tests/server_test.go
> Skip cardinality tests in race mode

- Godeps
- query/point.go
> Update influxql so DataType constants are the type DataType

- coordinator/statement_executor.go
- tsdb/store.go
Ensures that `SHOW TAG KEYS` and `SHOW TAG VALUES` works across all retention policies.
> SHOW TAG {KEYS, VALUES} across RPs

- services/storage/batch_cursor.go
> don't panic here; nil cursor is handled for now. fixes #9090

- cmd/influxd/run/config.go
- etc/config.sample.toml
Renaming for discoverability for the initial release of ifql
> rename config section to ifql

- README.md
> Fix wrong link to key concepts in README

- CHANGELOG.md
- tsdb/engine/tsm1/encoding.gen.go
- tsdb/engine/tsm1/encoding.gen.go.tmpl
- tsdb/engine/tsm1/encoding.gen_test.go
> Backport 9117
