influxdata/influxdb

http/query_handler.go

Looks like this field was just mistakenly overlooked when it was
introduced.

fix(http): set org ID on event metric

---

ui/src/shared/copy/v2/notifications.ts
ui/src/types/arguments.ts
ui/src/variables/components/CSVVariableBuilder.tsx
ui/src/variables/components/MapVariableBuilder.tsx
ui/src/variables/components/UpdateVariableOverlay.tsx
ui/src/variables/components/VariableArgumentsEditor.tsx
ui/src/variables/components/VariableForm.tsx
ui/src/variables/constants/index.ts

Closes #12831 
Does some clean up for map var notifications and adds the constant variable type to the create/update overlays.

feat(ui/variables/csv): add csv variable

---

CHANGELOG.md
ui/src/dashboards/components/DashboardHeader.tsx
ui/src/dashboards/components/DashboardPage.tsx
ui/src/pageLayout/components/RenamablePageTitle.scss
ui/src/pageLayout/components/RenamablePageTitle.tsx

feat(ui): Add orgname to dashboard page title

---

query/stdlib/influxdata/influxdb/operators.go
query/stdlib/influxdata/influxdb/rules.go
query/stdlib/influxdata/influxdb/source.go

The read range procedure that uses the new rpc endpoints will now accept
filters using the same rules as the previous physical from procedure
spec.
Related to #12851.

feat(query): add push down rule for filters to read range procedure

---

storage/engine_schema.go
storage/reads/merge.go
storage/reads/merge_test.go
storage/reads/store.go
storage/reads/string_iterator_reader.go
storage/reads/string_iterator_reader_test.go
storage/reads/string_iterator_writer.go
storage/readservice/store.go
tsdb/cursor.go
tsdb/cursors/arrayvalues.gen.go
tsdb/cursors/arrayvalues.gen.go.tmpl
tsdb/cursors/arrayvalues.gen.go.tmpldata
tsdb/cursors/arrayvalues.gen_test.go
tsdb/cursors/gen.go
tsdb/cursors/string.go
tsdb/tsm1/array_encoding.go
tsdb/tsm1/encoding.go
tsdb/tsm1/encoding_test.go
tsdb/tsm1/engine.go
tsdb/tsm1/engine_schema.go
tsdb/tsm1/engine_schema_test.go
tsdb/tsm1/engine_test.go
tsdb/tsm1/file_store.go
tsdb/tsm1/reader.go
tsdb/tsm1/reader_index.go
tsdb/tsm1/reader_index_iterator.go
tsdb/tsm1/reader_index_iterator_test.go
tsdb/tsm1/reader_range_iterator.go
tsdb/tsm1/reader_range_iterator_test.go
tsdb/tsm1/reader_time_range.go

This PR has been separated into multiple commits in an effort to aid reviewers. Therefore it is my recommendation each commit is reviewed in isolation. 
Closes #13369
The implementation follows the RFC with the exception of one outstanding detail, noted in `engine_schema.go`:
> // TODO(sgc): extend prefix when filtering by `\x00 == <measurement>`
Should be addressed by completing issue #13497.
----
I will create some larger data sets with the `influxd generate` tools and run benchmarks to gather empirical evidence regarding the performance characteristics and any potential hotspots.
It would be worth extending `TSMIndexIterator` to support a min and optionally max prefix, to reduce the search space. I presented this scenario in the RFC:
> We can eliminate the prefix check in the linear …

Implementation of storage schema TagValues API

---

storage/reads/merge.go
storage/reads/merge_test.go

Assume that `StringIterator` always returns values in order, then retain that order on merge. Cost is `log(n)` per call to `MergedStringIterator.Next()` where `n` is the quantity of non-empty `StringIterator`s.
Closes #13440

fix(storage): Assume sorted StringIterators, and retain sorted order

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/13081
CellUpdate shouldn't update the name

fix(http): fix the swagger for cell update

---

task/backend/scheduler_test.go

Skips flakey Task scheduler tests that seems that run slow and fail on Circle. See #13358

test(task/scheduler): skip flakey parallel tests

---

CHANGELOG.md
ui/cypress/e2e/buckets.test.ts
ui/src/buckets/actions/index.ts
ui/src/buckets/components/BucketList.tsx
ui/src/buckets/components/BucketOverlayForm.tsx
ui/src/buckets/components/BucketRow.tsx
ui/src/buckets/components/RenameBucketForm.tsx
ui/src/buckets/components/RenameBucketOverlay.tsx
ui/src/buckets/components/UpdateBucketOverlay.tsx
ui/src/index.tsx
ui/src/organizations/actions/orgs.ts
ui/src/organizations/components/OrgProfileTab.tsx
ui/src/organizations/components/RenameOrgForm.tsx
ui/src/organizations/components/RenameOrgOverlay.tsx
ui/src/shared/components/dangerConfirmation/DangerConfirmationForm.tsx
ui/src/shared/components/dangerConfirmation/DangerConfirmationOverlay.tsx
ui/src/shared/copy/v2/notifications.ts
ui/src/types/dashboards.ts

Closes #13494 
Adds a danger zone warning users about the perils of editing a bucket name.

feat(ui/buckets): add buckets danger zone

---

tsdb/tsm1/file_store.go
tsdb/tsm1/metrics.go
tsdb/tsm1/metrics_test.go

Adds prometheus metrics recording compaction levels for TSM files.
Closes https://github.com/influxdata/influxdb/issues/11969

feat(storage): add tsm level metrics

---

query/iterator.go
query/subquery_test.go

Use the timezone when evaluating time literals in subqueries

---

pkg/lifecycle/resource.go
tsdb/tsi1/index.go
tsdb/tsi1/index_file.go
tsdb/tsi1/index_test.go
tsdb/tsi1/partition.go
tsdb/tsi1/partition_test.go

When a tsi1 partition closes, it waits on the wait group for compactions
and then acquires the lock. Unfortunately, a compaction may start in the
mean time, holding on to some resources. Then, close will attempt to
close those resources while holding the lock. That will block until
the compaction has finished, but it also needs to acquire the lock
in order to finish, leading to deadlock.
One cannot just move the wait group wait into the lock because, once
again, the compaction must acquire the lock before finishing. Compaction
can't finish before acquiring the lock because then it might be operating
on an invalid resource.
This change splits the locks into two: one to protect just against
concurrent Open and Close calls, and one to protect all of the other
state. We then just close the …

tsi1: partition close deadlock

---

query/stdlib/influxdata/influxdb/operators.go
query/stdlib/influxdata/influxdb/rules.go
query/stdlib/influxdata/influxdb/rules_test.go
query/stdlib/influxdata/influxdb/source.go
query/stdlib/influxdata/influxdb/storage.go
storage/reads/reader.go

If a pattern is seen that matches reading the tag keys, it will be
replaced with a direct RPC call to read the tag keys which should be
better optimized than reading from the storage engine tsm1 files.
Related to #12851.

feat(query): implement the read tag keys rpc call in the query engine

---

ui/src/cloud/actions/limits.ts
ui/src/cloud/apis/limits.ts
ui/src/cloud/components/LimitChecker.tsx
ui/src/dashboards/components/DashboardPage.tsx
ui/src/dataExplorer/components/DataExplorer.tsx
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/shared/components/TimeSeries.tsx
ui/src/shared/constants/errors.ts
ui/src/shared/copy/notifications.ts
ui/src/timeMachine/actions/queries.ts

Rate Limiting notifications on read/write endpoints

---

CHANGELOG.md
ui/package-lock.json
ui/src/authorizations/actions/index.ts
ui/src/authorizations/components/AllAccessTokenOverlay.tsx
ui/src/authorizations/components/GenerateTokenDropdown.tsx
ui/src/authorizations/components/TokensTab.tsx
ui/src/authorizations/containers/TokensIndex.tsx
ui/src/authorizations/utils/permissions.ts
ui/src/index.tsx
ui/src/organizations/apis/index.ts
ui/src/shared/copy/v2/notifications.ts

feat(ui): Create all access token 

---

cmd/influx/authorization.go

feat(cmd/influx): find auths by org

---

query/stdlib/influxdata/influxdb/operators.go
query/stdlib/influxdata/influxdb/rules.go
query/stdlib/influxdata/influxdb/rules_test.go
query/stdlib/influxdata/influxdb/source.go
query/stdlib/influxdata/influxdb/storage.go
storage/reads/reader.go

If a pattern is seen that matches the `v1.tagValues(...)` call, then it
will be replaced with a direct RPC call to read the tag values for the
selected tag key which should be better optimized than reading from the
storage engine tsm1 files.
Fixes #12851.

feat(query): implement the read tag values rpc call in the query engine

---

CHANGELOG.md
ui/src/clockface/components/dropdowns/Dropdown.tsx

Closes #13341 
Only add `dropdown--action` classname (which removes padding for dots) if there is no `selectedID` prop

Fix Dropdown Overlapping Dot & Text

---

ui/src/members/components/SelectUsers.tsx

Closes #13472 
Updated the dropdown to be disabled if there are no users or users array is empty.

Update add users dropdown with an empty state

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/13401
get labels services are protected by authorizer, so have the orgID as optional, could provide more flexibility.

fix(http): make getting labels orgID optional

---

CHANGELOG.md
ui/package-lock.json
ui/src/authorizations/components/BucketsSelector.scss
ui/src/authorizations/components/BucketsSelector.tsx
ui/src/authorizations/components/BucketsTokenOverlay.tsx
ui/src/authorizations/components/GenerateTokenDropdown.tsx
ui/src/authorizations/components/SelectableBucket.tsx
ui/src/authorizations/components/TokenRow.tsx
ui/src/authorizations/components/TokensTab.tsx
ui/src/authorizations/utils/permissions.ts
ui/src/dashboards/constants/index.ts
ui/src/index.tsx
ui/src/style/chronograf.scss
ui/src/timeMachine/components/builderCard/BuilderCardHeader.tsx

feat(ui): Add option to generate read / write token

---

authorizer/task.go
authorizer/task_test.go
cmd/influxd/launcher/launcher.go

Closes #12730
Move task validator from the /task directory to the /authorizer directory to match the pattern used by other resources.

refactor(tasks): move validator to authorizer package

---

CHANGELOG.md
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/dataLoaders/components/lineProtocolWizard/configure/LineProtocol.tsx
ui/src/dataLoaders/components/lineProtocolWizard/verify/StatusIndicator.tsx
ui/src/dataLoaders/reducers/dataLoaders.ts
ui/src/types/dataLoaders.ts

Closes #13599
show line protocol error message

fix(ui): Display error message from writing line protocol

---

ui/src/authorizations/utils/permissions.ts
ui/src/buckets/actions/index.ts
ui/src/buckets/components/BucketList.tsx
ui/src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx
ui/src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx
ui/src/dataLoaders/components/lineProtocolWizard/LineProtocolWizard.tsx
ui/src/organizations/actions/orgs.ts
ui/src/scrapers/components/CreateScraperOverlay.tsx
ui/src/telegrafs/components/Collectors.tsx

Closes #13627
Create scraper was failing when the bucket was changed because on bucket select change it was looking for `organizationID` on the bucket. I updated the create scraper overlay to use params orgID for setting the state when the bucket selection is changed.

Fix create scraper bucket dropdown

---

http/document_service.go
http/document_test.go

Fixes an issue introduced by #13085
Document org and orgID params should be optional, and not required.

fix(http): make org param optional in document get request

---

ui/src/shared/apis/query.ts

Closes #13279
Sometimes Flux queries return errors as a JSON object that looks like this:
```
{
code: 'internal error',
error: 'wups'
}
```
We only handled responses that look like this:
```
{
code: 'internal error',
message: 'wups'
}
```
This resulted in some errors messages not displaying in the UI. This commit updates our error message detection to handle both cases.

Detect more errors in JSON query responses

---

task/backend/query_logreader.go
task/backend/storetest/logstoretest.go

tasks should be able to pull from a table with both success and failed results
Co-authored-by: AlirieGray <alirie@influxdata.com>
Co-authored-by: docmerlin <emrys@influxdata.com>
Closes #

task(fix): Tasks should no longer have inaccurate response data

---

http/proxy_query_service.go
http/proxy_query_service_test.go

In our internal use of this handler, some of these errors weren't
wrapped in the expected influxdb.Error type.

fix(http): use influxdb.Error in ProxyQueryHandler

---

gather/recorder.go

Closes https://github.com/influxdata/influxdb/issues/13647
recent changes, result tags with no bkt id and org id to be dropped. 
Manually tested scrapers works fine after this change

fix(gather): add bkt and org id to scraper writer

---

query/stdlib/influxdata/influxdb/rules.go
storage/reads/reader.go

The RPC call should translate `_measurement` and `_field` to their
proper shortened byte strings when requesting the tag values.
This also fixes the planner rewrites to return the root node even when
no rewrite happened as this is required by the planner.

fix(storage): translate _measurement and _field to the proper strings

---

cmd/influxd/launcher/query_test.go
cmd/influxd/launcher/storage_test.go
query/stdlib/testing/end_to_end_test.go
storage/reads/merge.go
storage/reads/merge_test.go
storage/reads/stream_reader.go
storage/reads/stream_reader_test.go
storage/readservice/cursor.go
storage/series_cursor.go

This PR addresses #13581 and comes with some small perf improvements. It will also improve group read performance as it no longer does a redundant sort of the series keys.
`Store.Read`
```
Consuming data...
Series:   827942
Points:   0
Time:     8163ms
Series/s: 101422.339
Points/s: 0.000
```
`engine.CreateSeriesCursor`
```
Series:   827942
Time:     4612ms
Series/s: 179532.229
```
`Store.Read`
```
Consuming data...
Series:   827942
Points:   0
Time:     5313ms
Series/s: 155844.129
Points/s: 0.000
```
`engine.CreateSeriesCursor`
```
Series:   827942
Time:     732ms
Series/s: 1130639.508
```
Closes #13581

Remove sort behavior from Store.Read RPC, fix Tags invariant violation

---

ui/src/timeMachine/apis/queryBuilder.ts

Currently, slight changes in the form of a Flux metaquery can have drastic performance implications. To solve this issue, the Flux language provides helper metaquery functions such as `v1.tagKeys` and `v1.tagValues` which are guaranteed to be as fast as possible. 
In #12791, we switched away from using the `v1.tagKeys` and `v1.tagValues` functions in the query builder to their underlying Flux implementations in order to implement a UI feature. While the new metaqueries used in the query builder were still optimized at the time, the Flux language has since changed and this is no longer the case.
In addition, the metaqueries in the UI no longer hit the same code-path in Flux which has exposed a logic bug in the queries. So when executed, the metaqueries return the following error: 
schema …

Update query builder metaqueries

---

ui/src/shared/copy/notifications.ts
ui/src/shared/reducers/notifications.test.ts

tests were failing locally because jest could not import `NotificationStyle` enum from `src/types`.

Import NotificationStyle enum directly from notification types

---

id.go
id_test.go
source.go

The encoding/json docs explain that you need to provide a MarshalText
method to encode integer types as map keys, otherwise they will be
formatted as a string version of the decimal number.
Providing MarshalText and UnmarshalText also uses those methods as a
fallback for MarshalJSON and UnmarshalJSON, so we no longer need
explicit versions of those latter methods.
Apparently Sources were using IDs as map keys and were providing the
,string attribute on the JSON tag on the struct. This was not correct so
that attribute has been removed. Existing sources will no longer be
readable as a result of this change.
Fixes #13277.

fix: encode IDs as JSON map keys properly

---

ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx
ui/src/dashboards/selectors/index.ts
ui/src/variables/selectors/index.tsx

Closes #13651 
Map variables need to display their key name instead of their key values. This adds a selector to return an array of value entries from a selector. Using entries allows the variable dropdown to handle and render items without switching on types. However, displaying keys and values revealed an issue where variable two keys could have the same value. This can be resolved in a separate issue, https://github.com/influxdata/influxdb/issues/13658.

fix(ui/var/dropdown): display map key names in dropdown

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE
.github/PULL_REQUEST_TEMPLATE.md

I noticed the GitHub bug report, feature request, and pull request templates were dropped when the 2.0 branch was switched to `master`. I've cleaned up the templates from the 1.x branch.

docs: update issue and PR templates

---

storage/reads/reader.go

Translate the measurement and field tag key names to their non-storage
names and add the `_start` and `_stop` tag keys to the output since
they aren't real tags, but ones that are added by range.
https://github.com/influxdata/influxdb/pull/13705#issuecomment-487752507

fix(storage/reads): translate measurement and field tag key names

---

CHANGELOG.md
ui/cypress/e2e/explorer.test.ts
ui/package-lock.json
ui/package.json
ui/src/shared/constants/fluxFunctions.ts
ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
ui/src/timeMachine/components/fluxFunctionsToolbar/FluxFunctionsToolbar.tsx
ui/src/timeMachine/components/fluxFunctionsToolbar/FunctionCategory.tsx
ui/src/timeMachine/components/fluxFunctionsToolbar/ToolbarFunction.tsx
ui/src/timeMachine/utils/insertFunction.ts
ui/src/types/shared.ts

Closes #13667
- If a user clicks on a function in the raw text editor, the builder adds the appropriate imports for said function
- It does not duplicate imports
- Maintains cursor / line positioning
- Add e2e tests

feat(ui/explorer): add imports to flux scripts

---

tsdb/tsi1/index_test.go

This test does a lot of fuzzing against the tsi1 index and logs out what operations were performed in what order. Since it's a lot of operations, it's needlessly verbose if it passes. Set it up to only log if it fails.

tsi1: don't do verbose debug logging unless test fails

---

build.py
scripts/post-install.sh
scripts/pre-install.sh

This change sets the ownership of directories on package generation with fpm instead that in post-install to make `rpm -V` pass.
For more details, see: influxdata/EAR#716

fix(package): make rpm verify pass after installation

---

CHANGELOG.md
ui/src/onboarding/actions/index.ts
ui/src/onboarding/components/CompletionStep.tsx
ui/src/onboarding/constants/index.ts
ui/src/organizations/actions/orgs.ts
ui/src/shared/copy/notifications.ts
ui/src/templates/constants/defaultTemplates.ts

This adds another default template for creating a Local Metrics Dashboard and also instanciates that dashboard as part of the quickstart.

adding local metrics dashboard for quickstart

---

CHANGELOG.md
ui/src/templates/constants/defaultTemplates.ts

Updating the system dashboard so that it works if you start to build rollups of the system data. This is backwards compatible.

Fixing templates to address float != int error

---

task/backend/storetest/storetest.go

Part of: #3343
This PR updates the storetest for tasks:
1. Add coverage for `ListTask` with OrgID
1. Removes duplicate code
1. Tests the "After" `TaskSearchParameter`

test(tasks): added coverage for ListTasks with OrgID

---

logger/fields.go
storage/retention.go
storage/retention_test.go
task/backend/executor/executor.go
tsdb/series_file.go
tsdb/series_partition.go
tsdb/tsi1/partition.go
tsdb/tsm1/engine.go

PR #12878 removed the `trace_id` field from logging. This adds it back in most of the places it was removed, but now the `trace_id` field matches the Jaeger `trace_id` for the context, so some cross-referencing is possible.
Fixes #13580

chore(log): Put trace_id back in logs

---

storage/reads/mergegroupresultset.go
storage/reads/mergegroupresultset_test.go

This fix ensures the `groupByMergedGroupResultSet` produces a merged `GroupCursor` that unions all the `Keys` for the current partition key.
This PR is required for #13623
The new test case verifies that each `GroupResultSet` instances with the **same partition key** is correctly merged when the Keys of each `GroupResultSet` differ. 
How does it do that? The test uses helper functions to construct a series of protobuf frames that are decoded into `GroupResultSet` instances, required by the function to be tested, `NewGroupByMergedGroupResultSet`.
https://github.com/influxdata/influxdb/blob/fb39ac39ce4a2ad275d1a7d046232d70df9eb62b/storage/reads/stream_reader_test.go#L733
Each `newStreamReader` takes a series of protobuf `ReadResponse` instances to construct an RPC response. It returns a …

Ensure GroupCursor Keys is union of keys from all GroupCursors of current partition key

---

ui/src/templates/constants/defaultTemplates.ts

Corrected version of PR #13724 
> builder configs are not required for templates or exports. I am removing them from the default templates and i have this open issue to remove them from exports and templates: #13722

Remove builderConfigs from default Templates

---

CHANGELOG.md
ui/src/shared/constants/fluxFunctions.ts

fixing window example

---

Makefile

This fixes builds for ARM64 -- which requires the 'noasm' tag -- while not changing other builds for other architectures.
Closes #

Fix ARM64 builds

---

CHANGELOG.md
ui/src/shared/constants/fluxFunctions.ts

fix a typo in the range example

---

CHANGELOG.md
ui/src/shared/constants/fluxFunctions.ts

update the system time function

---

storage/reads/group_resultset.go
storage/reads/group_resultset_test.go

This manifested as incorrect sort ordering when serialized via RPC, resulting in an `invalid partition key order` error.
This fix introduces a delimiter to ensure sort keys cannot collide.

Ensure sort keys are correctly delimited to avoid collisions

---

.circleci/config.yml
kv/task.go
task/backend/storetest/storetest.go
task/platform_adapter.go
task/servicetest/servicetest.go

Closes #12021
When creating a task, not all fields were available in the response.  This loads the task from the backing store to return all fields.

fix(task): lookup fully hydrated task after creation

---

storage/engine_schema.go
storage/reads/string_iterator_writer.go
storage/reads/string_iterator_writer_test.go
tsdb/tsm1/engine_schema.go
tsdb/tsm1/engine_schema_test.go

Formalized this post condition in the documentation and added additional
unit tests.
Added a nil guard and unit test to WriteStringIterator.

Ensure Tag(Keys|Values) APIs never return (nil, nil)

---

ui/src/cloud/utils/limits.ts

was referencing `dashboard` instead of `dashboards` inside a get to limits status.

Fix reference to redux state in get

---

storage/engine.go
storage/engine_test.go
storage/wal/wal.go
storage/wal/wal_test.go
tsdb/tsm1/cache.go
tsdb/tsm1/cache_test.go
tsdb/tsm1/engine_delete_prefix.go
tsdb/tsm1/engine_delete_prefix_test.go
tsdb/tsm1/engine_test.go
tsdb/tsm1/file_store.go
tsdb/tsm1/predicate.go
tsdb/tsm1/predicate_test.go
tsdb/tsm1/reader.go
tsdb/tsm1/reader_index.go
tsdb/tsm1/reader_index_test.go
tsdb/tsm1/reader_prefix_tree.go
tsdb/tsm1/reader_range_iterator_test.go
tsdb/tsm1/reader_test.go
tsdb/tsm1/reader_time_range.go
tsdb/tsm1/reader_time_range_test.go
tsdb/tsm1/tombstone.go
tsdb/tsm1/tombstone_test.go

This PR implements most of predicate deletes from the engine layer down. Specifically,
- the tsm1 reader index can delete a prefix with a predicate
- the cache can delete a prefix with a predciate
- the tsm1 engine can delete a prefix with a predicate
- the storage engine can delete a bucket with a predicate
- tsm1 tombstones can record predicate data
- predicates are applied when reading tombstones
- the wal includes predicate data
- converts a predicate protobuf into an efficient series key matcher

tsm1: predicate deletes

---

.github/PULL_REQUEST_TEMPLATE.md

Adds the changelog task to the PR template, which was removed in https://github.com/influxdata/influxdb/pull/13373.

fix(.github): Add changelog task back into PR template

---

CHANGELOG.md
ui/src/dashboards/components/variablesControlBar/VariableDropdown.test.tsx
ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx
ui/src/dashboards/selectors/index.ts

fix(ui): ensure map type variables can get selected key

---

CHANGELOG.md
ui/src/timeMachine/constants/queryBuilder.ts
ui/src/timeMachine/utils/queryBuilder.test.ts
ui/src/timeMachine/utils/queryBuilder.ts

Closes #13775
Updates the Flux code generated by the query builder to use the `aggregateWindow` helper when possible. Queries previously generated like so:
```
from(bucket: "telegraf")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r._measurement == "cpu" or r._measurement == "disk")
|> filter(fn: (r) => r._field == "used_percent")
|> window(period: v.windowPeriod)
|> mean()
|> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
|> yield(name: "mean")
```
Will now be generated as:
```
from(bucket: "telegraf")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r._measurement == "cpu" or r._measurement == "disk")
|> filter(fn: (r) => r._field == "used_percent")
|> aggregateWindow(every: v.windowPeriod, fn: mean)
|> …
```

Generate more idiomatic Flux in query builder

---

CHANGELOG.md
ui/src/shared/components/FluxEditor.tsx
ui/src/shared/utils/fluxEditor.ts

Expand tab key presses to 2 spaces in the Flux editor

---

ui/src/cloud/actions/limits.ts

Closes #13807 
Bucket creation on cloud was showing a notification for 2 buckets even when the user is allowed to have upto two buckets as the free tier value. Updated the bucket limits check if number of buckets is `greater than` max buckets rather than `greater than equal to`.
This allows user to create at least 2 buckets without errors.

Update max buckets to be greater than the number

---

http/dashboard_service.go

We're currently swallowing all dashboard creation failures with a 500 response. Returning the response directly will correctly respond with 400-level responses when they apply.

fix(http): return correct response code when dashboard creation fails

---

tsdb/tsm1/reader_mmap.go

**Note!** - this has not been proved. It’s become very hard to try and reproduce this bug. So consider this conjecture…
We have recently being hitting a very rare segfault where a read of the TSM index is accessing unmapped data. 
The panic typically looks like this:
```
unexpected fault address 0x7f534ccbdb00
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f534ccbdb00 pc=0xe92628]
goroutine 73939753 [running]:
runtime.throw(0x16e97e5, 0x5)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc248f62a70 sp=0xc248f62a40 pc=0x42d892
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc248f62aa0 sp=0xc248f62a70 pc=0x442fc1
github.com/influxdata/influxdb/tsdb/tsm1.(*readerOffsetsIterator).Length(...) …
```

fix(storage): don't remap renamed TSM file

---

ui/src/me/components/UserPageHeader.tsx
ui/src/pageLayout/containers/Nav.tsx

Closes #13820 
Update the Nav item for settings to only display the username for Cloud2
Update the title in the homepage/settings page to display `<hello> <username>! Welcome to InfluxCloud! for Cloud2 users.

Update account and org header for cloud specific

---

ui/src/cloud/actions/limits.ts
ui/src/shared/components/TimeSeries.tsx
ui/src/shared/copy/notifications.ts
ui/src/timeMachine/actions/queries.ts

Query limit notification should include cool down timer
Documentation on error headers :https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L1556-L1563

Extract "retry after" from query limit error response headers and reveal to user in notifications

---

ui/src/dataLoaders/components/lineProtocolWizard/configure/LineProtocol.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/LineProtocolTabs.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/TabBody.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/__snapshots__/LineProtocol.test.tsx.snap

Closes #13812 
Update line protocol's drag and drop to not handle write protocol data
Clean line protocol by removing unused actions

Update line protocol to write data only once

---

http/api_handler_test.go
http/auth_test.go
http/bucket_test.go
http/dashboard_test.go
http/document_test.go
http/health_test.go
http/label_test.go
http/org_test.go
http/scraper_service_test.go
http/task_service_test.go
http/telegraf_test.go
http/user_resource_mapping_test.go
http/variable_test.go

If there's malformed json in our http handler tests, they fail without giving a reason. This resolves that.

chore(http): surface unmarshaling failures in tests

---

tsdb/series_segment.go

On rare occasion, when an influxdb instance is terminated abruptly on a particular ARM platform, the series segment file contains only zeros. Assuming hardware and OS are functioning properly, this change should prevent that from happening, by forcing a `sync()` after zero-padding with `truncate()`.
Helps #10543

fix(series file): Sync series segment after truncate

---

CHANGELOG.md
http/swagger.yml
http/task_service_test.go
kv/task.go
task.go

Closes #12386
This PR adds a `Description` property to Tasks in the Swagger definition as well as in the API.

feat(tasks): add description field to tasks

---

query/influxql/function.go
query/influxql/spectests/show_databases.go
query/influxql/spectests/show_retention_policies.go
query/influxql/transpiler.go

The `databases()` function was moved into the `influxdata/influxdb/v1`
package and so it wouldn't work anymore. The `percentile()` call was
changed to `quantile()` and the argument was changed to `q`. This also
updates `median()` to use `median()` since we now produce AST's and not
the spec so we can use the `median()` definition instead.

fix(query/influxql): update transpiler for moved/renamed code

---

dashboard.go
http/dashboard_service.go
http/dashboard_test.go
http/swagger.yml
testing/dashboards.go

Closes https://github.com/influxdata/influxdb/issues/13086
fixed the issue usingView, removed viewID, added more test coverage

fix(http): create view

---

CHANGELOG.md
ui/cypress/e2e/scrapers.test.ts
ui/src/scrapers/components/ScraperList.tsx
ui/src/scrapers/components/ScraperRow.tsx
ui/src/scrapers/components/__snapshots__/Scrapers.test.tsx.snap

Closes #13546
Scrapers list is now using Resource LIst and resource Card to display scrapers info.

chore(ui): Use ResourceList component for Scrapers List

---

query/iterator.gen.go
query/iterator.gen.go.tmpl
query/select.go
query/subquery_test.go

This was previously "fixed" in revision a76c82947. Unfortunately, that
change broke other queries that had a raw query in the outer query even
if it fixed select queries with an aggregate on the outer portion.
This changes things so that if a call iterator is used, the subquery is
told that the aggregate can be unordered so it will not attempt to sort
the data which shouldn't be sorted. This causes both of these test cases
to pass.
The additional subquery test was created by Adam Anthony. Thanks!

Fix the ordering for selectors within a subquery with different outer tags

---

go.mod
go.sum
http/swagger_test.go

The API slightly changed: LoadSwaggerFromYAMLData is now replaced
by LoadSwaggerFromData.
See: https://github.com/getkin/kin-openapi/pull/67

chore(dep): update kin-openapi to v0.2.0

---

authorizer/scraper.go
authorizer/scraper_test.go

Closes #
Scrapers will write the data to tsdb.
Therefore, when creating a scraper, should check if the user has permission to write to the bucket.

fix(http): check write permission when creating a scraper

---

CHANGELOG.md
ui/src/shared/components/CSVExportButton.tsx
ui/src/shared/components/ExportOverlay.tsx
ui/src/shared/utils/download.ts
ui/src/shared/utils/downloads.test.ts
ui/src/telegrafs/components/TelegrafConfigOverlay.tsx

Closes #13781
When a resource is downloaded or exported, it should use the name of the resource. remove spaces and lowercase.

feat(ui): Export and download resource with formatted resource name

---

CHANGELOG.md
cmd/influxd/launcher/launcher.go
http/api_handler.go
http/authentication_middleware.go
http/platform_handler.go
kv/service.go
kv/service_test.go
kv/session.go
session.go

This change adds in two CLI args for specifying session length and whether or not the session should be renewed. `session-length` and `session-renew-disabled`. 
The defaults are 60 for session length and false for session renew disabled.

feat(authentication): Add cli args for specifying session length and renewal

---

storage/reads/table.gen.go
storage/reads/table.gen.go.tmpl
storage/reads/table.go

The copy was unnecessary since it was just going to be copied
immediately afterwards into an Arrow buffer. In the future, we will want
to have storage directly send the arrow buffer, but right now we are
putting it in an array and copying it anyway.
Even when we send an arrow buffer, the underlying sequence of bytes is
probably going to be different and we will rely on the allocator to
reuse bytes so let's remove the extra copy.

fix(storage/reads): stop copying the values to an unnecessary buffer in the storage reader

---

cmd/influx/cli/cli.go

Closes #10451
There is no need to print such messages in the CLI output of the version
flag. Besides being unnecessary, it makes harder to automate some tests
for those installing influxDB CE by themselves and/or automating
dockerfiles.

Fix version output (v1.7)

---

cmd/influx/cli/cli.go

Closes #10451
There is no need to print such messages in the CLI output of the version
flag. Besides being unnecessary, it makes harder to automate some tests
for those installing influxDB CE by themselves and/or automating
dockerfiles.

Fix version output (v1.8)

---

http/swagger.yml
http/task_service_test.go
task.go
tsdb/tsi1/cache_test.go
ui/cypress/e2e/tasks.test.ts

This PR adds a `log` property to the `Run` schema in the swagger documentation, and adds an "omitempty" to the log property on the Run struct in task.go

fix(swagger): add log property to task runs endpoint docs

---

http/dashboard_service.go
http/dashboard_test.go
http/variable_service.go
id.go
id_test.go
kv/passwords_test.go

Closes #13873
https://github.com/influxdata/influxdb/blob/e725e1a2bc7361b3cbf3e3b85984cd6cbf1d9db2/http/org_service.go#L268-L273
conv `ErrInvalidID` `ErrInvalidIDLength` to `influxdb.Error`.
so all callers of `ID.DecodeFromString` no need to wrap err returned by `ID.DecodeFromString` to `influxdb.Error`.

fix(influxdb): use influxdb.Error in ID.Decode

---

task/backend/scheduler.go

Now that the run status updates are transactional actions
We no longer have to add a timer to keep things on track.
This is causing a problem where some runs are showing up without a start or stop time if the system is busy.
I would rather have the scheduler hang on the update then leave a run action without required fields.

fix(task): Remove timeout on task run updates

---

releng/packages/fs/usr/local/bin/influxdb_packages.bash

I updated `build.py` in https://github.com/influxdata/influxdb/pull/13397, but I didn't update `releng` to match those.
@gshif I haven't tested `releng` scripts locally yet, because I think I need more context on this.

fix(releng): update releng to match build.py

---

bolt/organization.go
bolt/organization_test.go
http/org_test.go
http/swagger.yml
inmem/organization_service.go
inmem/organization_test.go
kv/org.go
kv/org_test.go
organization.go
testing/onboarding.go
testing/organization_service.go

Closes https://github.com/influxdata/influxdb/issues/13479
Closes https://github.com/influxdata/influxdb/issues/13480
Add createdat, updatedat in org resource

feat(influxdb): add org create and update time

---

cmd/influxd/launcher/launcher.go
query/control/controller.go
query/control/controller_test.go
query/control/metrics.go
storage/readservice/service.go
task/backend/analytical_storage_test.go
task/backend/logreaderwriter_test.go

The controller implementation is primarily used by influxdb so it
shouldn't be part of the flux repository. This copies the code from flux
to influxdb so it can be removed from the next flux release.
Related to influxdata/flux#1251.

refactor(query/control): move the controller from flux to influxdb

---

storage/engine.go

I don't see anywhere obvious that an engine would be closed twice, but
if it was, the RLock would have been held permanently, such that a Lock
could not be taken later.
Running go test ./storage/... did not trigger a double-close.

fix(storage): add missing RUnlock in Engine.Close

---

go.mod

As of golang/go#31960, go1.13 (or tip) will always add the go directive
to go.mod. Add it now as go 1.12 so that we don't have churn later as
people start using 1.13, before we're ready to officially switch to
building influxdb with 1.13.

chore: add go directive to go.mod

---

query/stdlib/influxdata/influxdb/source.go
query/stdlib/testing/testing.go
storage/reads/table.gen.go
storage/reads/table.gen.go.tmpl
storage/reads/table.go

The storage table reader will now work correctly when there are multiple
outputs. The table interface now implements the new table and column
reader interfaces and works properly with `execute.CopyTable`. The
source uses `execute.CopyTable` to buffer the table in memory when there
are multiple output transformations.
Fixes #12891.

fix(storage/reads): fix the storage tables to work correctly with multiple transformations

---

ui/src/shared/components/HeatmapContainer.tsx

heatmaps were not displaying properly because the isValid function was buggy.

Correctly check if columnKeys include xColumn in heatmap

---

query/control/controller_test.go

In the QueueSize test, it was possible that after the `done` channel was
closed, one of the queries from the queue would begin executing. If all
three began executing before the shutdown was done, the third would
block on attempting to send a value to the `executing` channel and it
would never finish so the controller would report that shutdown failed.
This increases the queue size to a combination of the concurrency quota
and the queue size so all of the started queries will never block when
sending a signal to the executing channel.

fix(query/control): queue size test was flaky

---

authorizer/telegraf.go
authorizer/telegraf_test.go
bolt/lookup_service_test.go
bolt/organization.go
bolt/telegraf.go
http/swagger.yml
http/telegraf.go
http/telegraf_test.go
inmem/lookup_service_test.go
inmem/telegraf.go
kv/lookup_service_test.go
kv/org.go
kv/telegraf.go
telegraf.go
telegraf_test.go
testing/telegraf.go
ui/cypress/support/commands.ts
ui/mocks/dummyData.ts
ui/package-lock.json
ui/package.json
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/telegrafs/components/__snapshots__/Collectors.test.tsx.snap

Closes https://github.com/influxdata/influxdb/issues/13147
rename telegraf config's OrganizationID to OrgID
only merged after https://github.com/influxdata/influxdb/issues/13404 resolved

fix(influxdb): rename telegraf orgID

---

CHANGELOG.md
ui/package-lock.json
ui/src/dashboards/constants/cellEditor.ts
ui/src/dashboards/resources.ts
ui/src/shared/components/XYContainer.tsx
ui/src/shared/utils/formatNumber.test.ts
ui/src/shared/utils/formatNumber.ts
ui/src/shared/utils/mocks/resourceToTemplate.ts
ui/src/shared/utils/view.ts
ui/src/shared/utils/vis.ts
ui/src/timeMachine/components/view_options/LineOptions.tsx
ui/src/timeMachine/components/view_options/YAxisBase.tsx
ui/src/types/dashboards.ts

Closes #14051 
When formatting ticks with a binary unit prefix, the generated tick intervals aren't super nice. I've created https://github.com/influxdata/vis/issues/79 and https://github.com/influxdata/vis/issues/80 to track this issue.

Enable formatting line graph y ticks with binary prefix

---

authorizer/task.go
authorizer/task_test.go

Closes #13771
This PR adds a check for if a task is inactive to the `ForceRun` and `Retry` functions, and returns an error if the task is inactive.

fix(tasks): adds check for inactive task in ForceRun and Retry

---

storage/reads/table.go

When a buffered column reader was used, the length was not reset to
whatever the requested length was for the buffer so it was possible for
the length to be longer than the actual columns.

fix(storage/reads): ensure that the column reader gets its length set

---

cmd/influx/task.go
http/swagger.yml
kv/task.go
task.go
task/mock/task_control_service.go
task/servicetest/servicetest.go

Closes #12694
This PR adds a `RunID` property to run logs.

feat(tasks): add runID to Log struct

---

tsdb/engine/tsm1/batch_string.go
tsdb/engine/tsm1/batch_string_test.go
tsdb/engine/tsm1/compact.gen.go
tsdb/engine/tsm1/compact.gen.go.tmpl
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go

`StringArrayEncodeAll` will panic if the total length of strings contained in the src slice is > 0xffffffff. This change adds a unit test to replicate the issue and an associated fix to return an error.
This also raises an issue that compactions will be unable to make progress under the following condition:
* multiple string blocks are to be merged to a single block and
* the total length of all strings exceeds the maximum block size that
snappy will encode (0xffffffff)
The observable effect of this will be errors in the logs indicating a compaction failure.
Fixes #13687

Don't panic when encoding string blocks and length of source slice is too large

---

CHANGELOG.md
ui/package-lock.json
ui/package.json
ui/src/shared/components/HeatmapContainer.tsx
ui/src/shared/components/HistogramContainer.tsx
ui/src/shared/components/LatestValueTransform.tsx
ui/src/shared/components/RefreshingViewSwitcher.tsx
ui/src/shared/components/ScatterContainer.tsx
ui/src/shared/components/VisTableTransform.tsx
ui/src/shared/components/XYContainer.tsx
ui/src/shared/components/cells/Cell.scss
ui/src/shared/constants/index.ts
ui/src/shared/utils/latestValues.test.ts
ui/src/shared/utils/latestValues.ts
ui/src/shared/utils/useVisDomainSettings.ts
ui/src/shared/utils/view.ts
ui/src/shared/utils/vis.ts
ui/src/timeMachine/actions/index.ts
ui/src/timeMachine/components/VisDataTransform.tsx
ui/src/timeMachine/components/VisSwitcher.tsx
ui/src/timeMachine/components/view_options/HeatmapOptions.tsx
ui/src/timeMachine/components/view_options/HistogramOptions.tsx
ui/src/timeMachine/components/view_options/ScatterOptions.tsx
ui/src/timeMachine/selectors/index.ts
ui/src/types/dashboards.ts

Closes https://github.com/influxdata/giraffe/issues/65
Closes https://github.com/influxdata/giraffe/issues/66
- Library has been renamed from _vis_ to _giraffe_
- This release fixes a performance regression causing tooltips to render slowly
- This release adds tooltips to scatterplots

Upgrade vis library

---

tsdb/engine/tsm1/batch_string.go
tsdb/engine/tsm1/batch_string_test.go
tsdb/engine/tsm1/compact.gen.go
tsdb/engine/tsm1/compact.gen.go.tmpl
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go

Back port #13699
StringArrayEncodeAll will panic if the total length of strings
contained in the src slice is > 0xffffffff. This change adds a unit
test to replicate the issue and an associated fix to return an error.
This also raises an issue that compactions will be unable to make
progress under the following condition:
* multiple string blocks are to be merged to a single block and
* the total length of all strings exceeds the maximum block size that
  snappy will encode (0xffffffff)
The observable effect of this is errors in the logs indicating a
compaction failure.
Fixes #13687

Back port: Don't panic when length of source slice is too large

---

ui/src/shared/utils/useVisDomainSettings.ts

Fixes the following crash:
The regression was introduced in https://github.com/influxdata/influxdb/commit/eee441680910ca6cc55b23a666eacd84a12d6909. A default argument was supplied to an argument in the `useVisDomainSettings`, but the default was never being used since `null` and not `undefined` was being passed.

fix(ui): prevent visualization crash in DE

---

ui/src/dashboards/components/DashboardHeader.tsx
ui/src/shared/components/TimeRangeDropdown.tsx
ui/src/shared/components/dateRangePicker/DatePicker.tsx
ui/src/shared/components/dateRangePicker/DateRangePicker.scss
ui/src/shared/components/dateRangePicker/DateRangePicker.tsx

Closes #13829 
Add separate input element to handle text based inputs to the date picker. 
If text input is invalid do not update the timeRange, but continue displaying in text input. 
When opening date picker for the first time, select time range that was already selected in Time Range Dropdown. So that if Past 5m were selected -> lower= now-5m and upper = now.

Separate input element from date-picker

---

http/task_test.go
query/control/controller.go
query/control/controller_test.go

fix(query): recover from panics during compiler and start steps

---

tsdb/series_file_test.go
tsdb/series_index.go
tsdb/series_index_test.go

Previously the series file did not include tombstones in the total count. This commit now includes tombstones in the count as well as fixes an issue where replayed tombstone records could exist but their underlying ID did not exist. This caused the count to become negative and with the count being `uint64` it caused the count to rollover to `math.Uint64Max`.
Related: https://github.com/influxdata/influxdb/issues/13690

fix(tsdb): Fix series file count

---

http/swagger.yml
http/task_service.go
kv/task.go
task/backend/analytical_storage.go
task/servicetest/servicetest.go

This PR updates the swagger document to reflect the correct default and maximum number of runs returned by `FindRuns`. It also updates the `FindRuns` function to set the number returned to the default if the limit is 0 or not set, and set it to the maximum if it was higher than the maximum. Previously, it was set to the maximum whether it was zero or greater than the max.

chore(tasks): update run limits in swagger and FindRuns

---

CHANGELOG.md
dashboard.go
dashboard_test.go
ui/package-lock.json
ui/package.json
ui/src/shared/components/Checkbox.scss
ui/src/shared/components/Checkbox.tsx
ui/src/shared/components/XYContainer.tsx
ui/src/shared/utils/featureFlag.ts
ui/src/style/chronograf.scss
ui/src/timeMachine/actions/index.ts
ui/src/timeMachine/components/view_options/LineOptions.tsx
ui/src/timeMachine/reducers/index.ts
ui/src/types/dashboards.ts

Adds an option to shade the area below lines in a line graph.

Add option to shade area below line graphs

---

telegraf.go
telegraf_test.go

Close https://github.com/influxdata/idpe/issues/3758
This change will allow existing old telegraf configs still work with UI before any migration. 
This change won't change the data stored in bolt, unless user made an update.
Manually tested as well.

fix(influxdb): telegraf compatible mode

---

http/task_service.go
http/task_service_test.go
kv/task.go
task/backend/analytical_storage.go
task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go
task/backend/executor/executor.go
task/backend/executor/executor_test.go
task/backend/scheduler.go
task/backend/scheduler_test.go
task/backend/task.go
task/mock/scheduler.go
task/mock/task_control_service.go
task/options/options.go
task/options/options_errors.go
task/servicetest/servicetest.go
task_errors.go

Closes #14119
This PR moves task errors from various locations in the project into a single file in the root directory called `task_errors.go`.

chore(tasks): consolidate task errors into task_errors.go

---

ui/src/templates/components/TemplateCard.tsx

Closes #14098
Add type metadata to User Templates

Add type metadata to User Templates

---

CHANGELOG.md
ui/package-lock.json
ui/package.json
ui/src/dataLoaders/components/verifyStep/DataListening.tsx
ui/src/shared/apis/query.ts
ui/src/shared/components/TimeSeries.tsx
ui/src/timeMachine/actions/queries.ts
ui/src/timeMachine/apis/queryBuilder.ts
ui/src/variables/utils/ValueFetcher.ts

Update client version to resolve query bottleneck

---

ui/src/dashboards/components/VEOHeader.tsx
ui/src/pageLayout/components/RenamablePageTitle.tsx

Closes #13650
I would have liked to have done this with an id.  Unfortunately, Clockface does not expose ids for buttons ... yet

fix: only click save once to save cell

---

storage/engine.go
tsdb/tsm1/compact.go
tsdb/tsm1/compact_test.go
tsdb/tsm1/engine.go
tsdb/tsm1/file_store.go

Adds the ability to set the current generation to use when compacting
the cache only. Previously, we used the current generation for all
files but this causes issues and we should only use the current
generation for level 1 compaction.

fix(storage): Add WithCurrentGenerationFunc() for generation injection.

---

storage/engine_test.go
tsdb/tsm1/file_store.go

These metrics weren't being properly intialized on opening the file store, and
weren't being properly updated on compaction.
Closes #13689

fix(storage): initialize tsm file metrics, update after compaction

---

ui/src/pageLayout/components/CloudNav.tsx
ui/src/shared/constants/index.ts
ui/src/shared/utils/featureFlag.ts

Subnav should be visible in acceptance but feature flagged in production
env var is `CLOUD_BILLING_VISIBLE`

fix(ui/cloudNav): Update cloud subnav feature flag to use env var

---

ui/src/shared/components/ScatterContainer.tsx
ui/src/shared/components/XYContainer.tsx
ui/src/shared/utils/vis.ts
ui/src/timeMachine/selectors/index.ts

fix(ui): enable selecting more columns in line visualizations

---

CHANGELOG.md
ui/src/authorizations/actions/index.ts
ui/src/dataExplorer/components/SaveAsTaskForm.tsx
ui/src/tasks/actions/index.ts
ui/src/tasks/components/TaskForm.test.tsx
ui/src/tasks/components/TaskForm.tsx
ui/src/tasks/components/TaskTokenDropdown.tsx
ui/src/tasks/components/__snapshots__/TaskForm.test.tsx.snap
ui/src/tasks/containers/TaskEditPage.tsx
ui/src/tasks/containers/TaskPage.tsx
ui/src/tasks/reducers/index.ts

Closes #14020 
Added token dropdown on task form
Added redux state to store the selected token
Updated edit task page to show token dropdown.
Updated task form in data explorer to include a token dropdown

Add dropdown to select token when creating a new task

---

ui/src/shared/components/Gauge.tsx
ui/src/shared/constants/gaugeSpecs.ts

I investigated https://github.com/influxdata/influxdb/issues/14175 + https://github.com/influxdata/EAR/issues/823  and discovered the root issue is that the threshold settings component emits nonsensical settings. I opened up https://github.com/influxdata/influxdb/issues/14190 to track resolution.
In the meantime I made some minor gauge tweaks. It now displays better on HiDPI / Retina screens.
Before (you will need a HiDPI screen to see the blurriness): 
After:
I also tweaked how the gauge behaves when the needle position is beyond the domain of the gauge (for example if the current value is 6,000,000 and the max value for the gauge is 100). Before the needle would display at an essentially random position ¯\_(ツ)_/¯ (some sort of modular arithmetic).
Now it will be clamped to just beyond …

Gauge polish

---

go.mod
go.sum
http/bucket_service.go
http/client.go
http/influxdb/client.go
http/influxdb/source_proxy_query_service.go
http/org_service.go
http/query_handler.go
http/source_proxy_service.go
http/task_service.go

Closes #14203 
The HTTP service clients would inject any trace into the request header.  Also, the http.Client would also inject the header.  Because version 1.0.2 of opentracing used http.Header.Add multiple trace spans would be propagated.
Opentracing version 1.1.0 switches to http.Header.Set so that last span injection wins.

fix client tracing propagation from doubly recording

---

http/swagger.yml
http/user_service.go
session.go
user.go

`/me` will now include an `oauthID` attribute. If influxdb has a configured OAuth provider, then we should expect `/me` to include the corresponding provider id for that user. If influxdb does not have OAuth configured, and is reliant on the local username/password bolt store, then `oauthID` will be omitted.

feat(me): return oauth id with user object

---

tsdb/tsm1/array_cursor_iterator.gen.go
tsdb/tsm1/array_cursor_iterator.gen.go.tmpl
tsdb/tsm1/array_cursor_iterator.go
tsdb/tsm1/engine.go
tsdb/tsm1/file_store.go
tsdb/tsm1/metrics.go

Adds a total cursor counter and seek location counter to a new `readMetrics` that is added to each `Engine`. Default labels group by `engine_id` and `node_id`.

feat(tsdb): Add basic tsdb read metrics

---

http/query.go
http/query_handler.go
http/query_handler_test.go

`FluxService` must be dead code (until now; I'm using for the query capacity tool) since I don't think it worked at all since auth changes were made several months ago.
I added the orgID to the HTTP query string, similar to `FluxQueryService`.

fix(http): add org ID to flux handler

---

ui/src/dataExplorer/components/SaveAsTaskForm.tsx
ui/src/tasks/components/TaskTokenDropdown.tsx

Closes #14219 
Updated the token dropdown in data explorer to only show relevant tokens which have read and write permissions on the buckets selected in from and to
Create a filter to find all tokens with read bucket selected in `from`
Create a filter to find all tokens with write bucket selected in `to`
Create an intersection between the two arrays to find the tokens relevant to both `from` and `to`
Update the dropdown to display an empty state if there are no tokens being listed

Display relevant tokens based on permissions in token dropdown

---

CHANGELOG.md
cmd/influxd/inspect/inspect.go
cmd/influxd/inspect/report_tsm.go
cmd/influxd/inspect/verify_wal.go
storage/wal/verifier_test.go
storage/wal/verify.go

Closes #9768 
Also see #10993 
Adds `verify-wal` sub-command to `influxd inspect` which will check WAL files for corruption. Given a directory, the tool simply attempts to parse all the entries in any WAL files it finds. If a corrupt entry is found, the file is reported to the user. Do we want to update docs on this tool?
Usage: `$ influxd inspect verify-wal --data-dir=/my/storage/dir/`

feat(storage): Add influxd inspect verify-wal tool

---

tsdb/tsm1/file_store.go
tsdb/tsm1/metrics_test.go

The counts weren't adding all the level 4+ files, so the last one to be counted
would override the rest.

fix(storage): fix counts for level 4+ files

---

cmd/influxd/inspect/export_blocks.go
cmd/influxd/inspect/inspect.go
tsdb/explode.go
tsdb/tsm1/block_exporter.go
tsdb/tsm1/block_exporter_test.go
tsdb/tsm1/encoding.go

Adds export tooling to `influxd inspect export-blocks` so that we
can dump out block data in SQL format for better analysis during
the debugging process.
```sql
SELECT org_id, bucket_id, key, COUNT(*), SUM("count")
FROM blocks
GROUP BY org_id, bucket_id, key
ORDER BY COUNT(*) DESC
LIMIT 10;
```
```sql
SELECT org_id, bucket_id, key, COUNT(DISTINCT filename)
FROM blocks
GROUP BY org_id, bucket_id, key
ORDER BY COUNT(DISTINCT filename) DESC
LIMIT 10;
```
_Note: This requires `sqlite3` version `3.25.0` for the windowing functions, however, version `3.28.0` is advised since it includes additional windowing features._
```sql
SELECT
SUM(tbl.overlapping) AS overlapping_blocks, 
COUNT(*) AS total_blocks,
CAST(SUM(tbl.overlapping) AS FLOAT)/COUNT(*) AS pct_overlapping
FROM (
SELECT min_time > …
```

feat(tsdb): Add block exporter.

---

query/stdlib/testing/end_to_end_test.go

The underlying bug that caused them to be flaky has been fixed.

fix(query/stdlib): remove skip from the flux e2e tests

---

ui/src/cloud/components/AssetLimitAlert.tsx
ui/src/cloud/components/CheckoutButton.tsx
ui/src/shared/constants/index.ts

Add a button to go to checkout when in cloud, billing page is visible, and the user is being rate limited.

feat(ui/cloud): add cloud checkout button

---

tsdb/tsm1/report.go

Previously the logic was inverted so `--pattern` matched everything but the specified value.

report-tsm --pattern flag incorrectly matches everything but specified value

---

tsdb/tsm1/reader_block_iterator.go

Fixes the `tsm1.BlockIterator` so that it returns the current key if there are still additional entries remaining. This previously caused multiple entries not to be merged together during compaction because the iterator would check if the next key matched the current key but the key for the next set of entries was returned.

fix(tsdb): Fix tsm1 block merge.

---

tsdb/engine/tsm1/engine_test.go
tsdb/engine/tsm1/wal.go

Closes #14229
This PR fixes a strange bug where data can re-appear after a restart. The issue arises if the cache is snapshotted _before_ a write lands in the WAL. In such a scenario, the Engine thinks that the WAL is empty, and decides it does not need truncating when the cache snapshot completes.
The data in the WAL then persists after the snapshot, and is then replayed again on startup. The catch is that if a user attempts to delete this data post-snapshot, no delete entry will be added to the WAL because the cache is empty. So when the replay happens there is no delete command to replay.

Prevent data from re-appearing on startup in some cases

---

storage/reads/datatypes/storage_common.proto
tsdb/tsm1/array_cursor.gen.go
tsdb/tsm1/array_cursor.gen.go.tmpl

Closes https://github.com/influxdata/flux/issues/1427
Closes #14249
This PR changes how storage read cursors work. Previously storage returned points in the domain `[start, end]`.
However, Flux's `range` function uses the range `[start, stop)`. 
Storage now uses the domain `[start, end)`.

Storage reads should be in domain [start, end)

---

tsdb/engine/tsm1/batch_string.go

It was introduced in #13699.
Updates #14265.

Remove stray fmt.Println in tsm1.StringArrayEncodeAll

---

http/query_handler.go

Closes https://github.com/influxdata/idpe/issues/3887
removed the hard code EInternal, use whatever the query service returns.

fix(http): invalid compilation should not be 500 error

---

task/backend/task_service_checkpointer.go
task/backend/task_service_checkpointer_test.go

This PR implements the `Checkpoint` and `Last` functions using a Task Service

feat(tasks): add last and checkpoint functions

---

tests/server_delete_test.go
tsdb/index/inmem/inmem.go
tsdb/shard_test.go

Fixes #10052.
This PR fixes an issue where field keys would reappear in results when querying previously dropped measurements.
The issue manifests itself when duplicates of a new series are inserted into the `inmem` index. In this case, a map
https://github.com/influxdata/influxdb/blob/7ca4e644f160d06c7470cad8c4d83e5ded3923c1/tsdb/index/inmem/inmem.go#L248-L255
which tracks the number of series belonging to a measurement was incorrectly incremented once for each duplication of the series. Then, when it came time to drop the measurement, the index assumed there were still several series
https://github.com/influxdata/influxdb/blob/7ca4e644f160d06c7470cad8c4d83e5ded3923c1/tsdb/index/inmem/inmem.go#L1134-L1140
belonging to the measurement left in the index (because the counter was higher than …

fix(storage): Fix issue where fields re-appear

---

CHANGELOG.md
task/backend/executor/executor.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

Closes https://github.com/influxdata/influxdb/issues/14239
This is an attempt to bubble up an error so that it fails a task appropriately.
Need help with testing and knowledge on desired task behavior.

fix(tasks) report errors found when iterating over flux query

---

storage/reads/datatypes/storage_common.pb.go
ui/src/shared/constants/fluxFunctions.ts

Adds `sql.to`, `strings.strlen`, `strings.substring`, `movingAverage` and removes the `mergeKey` parameter from  `map()`.

Updated functions list for flux 0.35.1

---

appveyor.yml
task/backend/analytical_storage.go

We on occasion will see a run in chronograf with missing run data.
We need to find out if we are submitting incomplete data or if we submit full data and somethinge else is happening.

fix(tasks): Add a log message for run transition clairity

---

http/query_handler.go
http/query_handler_test.go

Flux errors that are returned from the query service will be adapted to
an influxdb.Error and then will be written to HTTP correctly.

feat(http): handle flux errors that are returned from the query service

---

http/auth_service.go

Closes https://github.com/influxdata/influxdb/issues/14202
fix the issue. Keep the logic if userid is not present in post auth request, use the current user id

fix(http): fixed auth userid overwrite

---

http/task_service.go
http/task_service_test.go
kv/task.go
task/backend/analytical_storage.go
task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go
task/backend/executor/executor.go
task/backend/executor/executor_test.go
task/backend/executor/task_executor.go
task/backend/scheduler.go
task/backend/scheduler_test.go
task/mock/scheduler.go
task/mock/task_control_service.go
task/servicetest/servicetest.go
task_errors.go

This PR adds pointers to the errors in the "task_errors" file so that they don't have to be dereference throughout the code base.

chore(tasks): use pointers for task errors

---

CHANGELOG.md
CONTRIBUTING.md
Dockerfile
Dockerfile_build_ubuntu32
Dockerfile_build_ubuntu64
Dockerfile_build_ubuntu64_git
Dockerfile_build_ubuntu64_go1.12
Dockerfile_jenkins_ubuntu32
Jenkinsfile
appveyor.yml
releng/_go_versions.sh
services/httpd/response_writer_test.go
test.sh

This PR updates the Go runtime used to build InfluxDB to Go 1.12.

Update Go version to 1.12

---

ui/package.json
ui/src/shared/components/AlertCheckContainer.tsx
ui/src/shared/components/CheckPlot.tsx
ui/src/shared/components/GreaterThresholdMarker.tsx
ui/src/shared/components/HeatmapPlot.tsx
ui/src/shared/components/HistogramPlot.tsx
ui/src/shared/components/LessThresholdMarker.tsx
ui/src/shared/components/RangeThresholdMarkers.tsx
ui/src/shared/components/ScatterPlot.tsx
ui/src/shared/components/ThresholdMarker.tsx
ui/src/shared/components/ThresholdMarkerArea.tsx
ui/src/shared/components/ThresholdMarkers.scss
ui/src/shared/components/ThresholdMarkers.tsx
ui/src/shared/components/ViewSwitcher.tsx
ui/src/shared/components/XYPlot.tsx
ui/src/shared/components/cells/Cell.scss
ui/src/shared/utils/useDragBehavior.ts
ui/src/shared/utils/vis.ts
ui/src/style/chronograf.scss
ui/src/types/dashboards.ts
ui/yarn.lock

Closes #14293 
Introduces a new visualization type (`CheckPlot`) for visualizing checks.
These visualizations are simple `_value` vs. `_time` plots with additional features layered on top. For now, the first of such features is an interactive visualization of check thresholds (`ThresholdMarkers`).
A later PR will add the ability to create a `CheckPlot` through the UI.
I also changed some confusing naming:
- `XYContainer` -> `XYPlot`
- `HistogramContainer` -> `HistogramPlot`
- `ScatterContainer` -> `ScatterPlot`
- `HeatmapContainer` -> `HeatmapPlot` 
A `range` threshold with an `OK` status level:
A `range` threshold with a `WARN` status level and `within: false`:
`INFO` status level:
`UNKNOWN` status level:

Add ThresholdMarkers controls

---

cmd/influx/authorization.go

Additional to the API fix of https://github.com/influxdata/influxdb/pull/14344
the influx CLI is ignoring the user flag. This fix should patch that issue.
Manually tested.

fix(cmd/influx): user flag shouldn't be ignore

---

query/iterator.gen.go
query/iterator.gen.go.tmpl
query/subquery_test.go

The sort order of points when performing aggregates never took into
account if they were ascending or descending so when multiple series
were aggregated, it would ensure they were sorted in the correct order.
But it wouldn't reverse this order when descending was used.
Additionally, it seems that the iterator template and the iterator file
itself became out of sync. It seems the template was not reverted
correctly from a previously incorrect change and only the float type was
changed to the correct version and the tests used the float version.

Subquery ordering with aggregates in descending mode was wrong

---

kv/service.go

This PR implements the `Check` function on the kv service, and simply returns a success response if the kv store does not implement the Check interface.

feat(tasks): add health check to kv service

---

http/query_handler.go
http/query_handler_test.go
query/control/controller.go
query/control/controller_test.go

If we handle the flux errors in the query controller, it makes it so we
are handling the errors in the location where the happen rather than at
a layer further up the stack.
This should simplify it so the errors are handled in this single
location instead.

refactor(query): handle flux errors in the query controller instead of http

---

ui/src/cloud/components/CheckoutButton.tsx
ui/src/shared/constants/index.ts

Updates the cloud checkout button to go to billing instead of directly to `/checkout`.

fix(ui/cloud): update location for upgrade button

---

ui/src/templates/components/createFromTemplateOverlay/CreateFromTemplateOverlay.tsx
ui/src/templates/components/createFromTemplateOverlay/TemplateBrowserList.tsx
ui/src/templates/constants/defaultTemplates.ts

Addresses #14341
When trying to create a Dashboard from a template via the Dashboard index the templates from `@influxdata/influxdb-templates` were not listed.  
Import the templates from our package and display them to the user.

fix(templates): import static templates for creating dashboards

---

ui/src/dataLoaders/components/lineProtocolWizard/configure/LineProtocol.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/__snapshots__/LineProtocol.test.tsx.snap

Add documention link in line protocol sub header. 
Link is : https://v2.docs.influxdata.com/v2.0/write-data/#write-data-in-the-influxdb-ui

feat(ui): Add link to documentation when uploading line protocol

---

ui/src/cloud/actions/limits.ts
ui/src/cloud/reducers/limits.ts
ui/src/cloud/utils/limits.ts
ui/src/dashboards/components/DashboardPage.tsx
ui/src/dataExplorer/components/DataExplorer.tsx

Fixes an issue where alerts for writes and reads rate were not being checked and updated. Currently, only adds this alert to the DataExplorer and DashboardPage, and does not address future work that should generalize alerts for any resource type to display on every page.

fix(ui/cloud): display alerts for read or write rates

---

http/swagger.yml

There was a mistake in our swagger, changed name to period

Fix aggregate window: change name parameter to period

---

ui/src/buckets/components/BucketCard.tsx
ui/src/buckets/components/BucketContextMenu.tsx
ui/src/buckets/components/BucketList.tsx
ui/src/dataExplorer/components/DataExplorerPage.tsx
ui/src/dataExplorer/components/DeleteDataButton.tsx
ui/src/dataExplorer/components/DeleteDataOverlay.tsx
ui/src/index.tsx
ui/src/shared/components/DeleteDataForm/BucketsDropdown.tsx
ui/src/shared/components/DeleteDataForm/DeleteButton.tsx
ui/src/shared/components/DeleteDataForm/DeleteDataForm.scss
ui/src/shared/components/DeleteDataForm/DeleteDataForm.tsx
ui/src/shared/components/DeleteDataForm/FilterEditor.tsx
ui/src/shared/components/DeleteDataForm/FilterRow.tsx
ui/src/shared/components/DeleteDataForm/TimeRangeDropdown.tsx
ui/src/shared/components/DeleteDataOverlay.tsx
ui/src/shared/components/TimeRangeDropdown.tsx
ui/src/shared/components/dateRangePicker/DateRangePicker.tsx
ui/src/shared/utils/featureFlag.ts
ui/src/style/chronograf.scss
ui/src/timeMachine/components/Queries.tsx

Closes #14354
Closes #14355
Adds a "Delete Data" overlay accessible from the buckets list:
The API doesn't exist yet, so the relevant parts of the code are stubbed out and the UI is feature flagged.
The overlay is also accessible from the DE:

Add delete with predicate overlays

---

storage/engine.go

Deleting from the cache takes a lock which blocks writes. Snapshot to clear the
cache before deleting to reduce the lock contention.
Closes #14399

fix(storage): run snapshot before retention deletes

---

.github/stale.yml
CHANGELOG.md
ui/src/shared/copy/notifications.ts

Closes #
The notification types on the manual run task were swapped. this fixes that.

Fixed task manual run notification type

---

task/backend/analytical_storage.go

Hotfix to allow marshaling of requests to query.
Was unseen as CSV from query with encoded errors are not detected.

fix(task/backend): add auth id for marshaling

---

services/httpd/handler.go
services/httpd/handler_test.go
tests/server_test.go

If a series was split by the encoder because of chunking and it was
reconstructed by the http handler, it would not reset the partial
indicator for the series to indicate if the series was still partial or
not. That meant that a result that returned more than the 10,000 values
in a single series with chunking disabled would say that the series was
partial, but it was not.
This fixes it so the handler now correctly sets the partial attribute of
the series to indicate if the series is still partial or not. This was
done when merging results, but was not done with series.

Fix the http handler to not mislabel series as partial

---

ui/src/buckets/components/BucketsTab.tsx
ui/src/cloud/components/AssetLimitAlert.tsx
ui/src/dashboards/components/DashboardPage.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/dataExplorer/components/DataExplorer.tsx
ui/src/shared/components/cloud/CloudOnly.scss
ui/src/style/chronograf.scss
ui/src/tasks/containers/TasksPage.tsx

Fixes the `AssetLimitAlert` to not wrap children because this caused clipping of the `DataExplorer` and `DashboardPage` contents.

fix(ui/asset-alert): fix asset-alert clipping dashboard contents

---

logger/fields.go
task/backend/executor/executor.go
task/backend/scheduler.go

Closes https://github.com/influxdata/idpe/issues/3983
Revert the [changes](https://github.com/influxdata/influxdb/pull/14053) to logger level that silently broke output for the IDPE service. 
Logs for the cloud-based service were no longer displaying information for a variety of tasks, including the `retention_enforcer`, as the log-level was artificially raised to `Debug` from `Info`. In this case the `NewOperation` should not override the `Info` level of the logging messages, as the default value for `log-level` is always `info`.

move logger facility back to Info from Debug

---

ui/src/shared/utils/latestValues.test.ts
ui/src/shared/utils/latestValues.ts
ui/src/timeMachine/components/Vis.tsx

Changes the `latestValues` logic to ignore null/empty Flux rows. This prevents a single stat/gauge crash.
Also wraps the time machine `Vis` in a error boundary, to mitigate the results of a crash.
Closes #14422

fix(ui): avoid single stat crash

---

ui/src/shared/apis/query.ts
ui/src/shared/components/TimeSeries.tsx
ui/src/timeMachine/actions/queries.ts
ui/src/timeMachine/actions/queryBuilder.ts
ui/src/timeMachine/apis/QueryBuilderFetcher.ts
ui/src/timeMachine/apis/queryBuilder.ts
ui/src/types/promises.ts
ui/src/utils/promises.ts
ui/src/utils/restartable.test.ts
ui/src/variables/actions/index.ts
ui/src/variables/utils/ValueFetcher.ts
ui/src/variables/utils/hydrateVars.ts

Fixes all the `CancellationError`s showing up in HoneyBadger.
Also took the opportunity to rename the unwieldy `WrappedCanceablePromise<T>` type to `CancelBox<T>`.

Catch cancellation errors more reliably

---

task/backend/analytical_storage.go
task/backend/read_table_test.go

This PR adds a test for errors in the ReadTable function when looking up runs in `analytical_store.go`, and also handles errors when iterating over the runs table

test(tasks): add test for ReadTable in analytical store

---

.github/stale.yml

If you label an issue with `stale-exempt`, it won't be automatically marked as stale or closed.

chore: prevent stale-exempt labelled issue from closing

---

tsdb/tsm1/file_store.go

Closes #
From `KeyCursor.current` comment,  `KeyCursor.current` should only contain overlapping blocks.
https://github.com/influxdata/influxdb/blob/063d487c4e66f09d6cfc7a04e93950baad9fcbb6/tsdb/tsm1/file_store.go#L1277-L1282
In `KeyCursor.nextDescending` method, append nonoverlapping blocks to `KeyCursor.current`.
https://github.com/influxdata/influxdb/blob/063d487c4e66f09d6cfc7a04e93950baad9fcbb6/tsdb/tsm1/file_store.go#L1450-L1458
But in `ReadFloatArrayBlock` func, nonoverlapping blocks are ignored.
https://github.com/influxdata/influxdb/blob/063d487c4e66f09d6cfc7a04e93950baad9fcbb6/tsdb/tsm1/file_store_array.gen.go#L82-L91
In `KeyCursor.nextDescending` method, should only append overlapping blocks to `KeyCursor.current`.
---

fix(tsm1): check if blocks are overlapping in KeyCursor.Next

---

ui/src/alerting/components/CheckCard.tsx
ui/src/alerting/components/NotificationRuleCard.tsx
ui/src/authorizations/components/TokenRow.tsx
ui/src/clockface/components/resource_list/ResourceEditableName.tsx
ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
ui/src/scrapers/components/ScraperRow.tsx
ui/src/tasks/components/TaskCard.tsx
ui/src/telegrafs/components/CollectorCard.tsx
ui/src/templates/components/TemplateCard.tsx

__Describe your proposed changes here.__
Fixes an issue where clicking on a dashboard name from the dashboards index caused an incorrect redirect due to default behavior on the anchor tag.

fix(ui/dashboards): prevent default on anchor tag

---

CHANGELOG.md
authorizer/task.go
authorizer/task_test.go

Prior to this change the UpdateTask action would authorize the original task and not the updated task.
This change ensures that the update being applied to a task is authorized.

fix: enforce bucket authentication on task update

---

ui/package.json
ui/yarn.lock

Closes #13725
Just propagating the fix from here: https://github.com/influxdata/clockface/pull/190

fix(ui): upgrade clockface to 0.0.19

---

kv/org.go

Fixes a bug that was introduced by #11301. Specifically, the `FindResourceOrganizationID` function it introduces does not handle task resources.
Closes #11491
Referencing tasks handler from a bolt client feels like a major smell and I'd love ideas for how to better communicate between the two bolt stores.

fix: task members endpoints

---

CHANGELOG.md
http/query_handler.go
http/query_handler_test.go
http/swagger.yml

If client requests with `Accept-Encoding: gzip`, then
compress response and return with `Content-Encoding: gzip`.
This increases the server-side load by about 12%, but saves network bandwidth.
```
benchmark                     old ns/op     new ns/op     delta
Benchmark_Query_no_gzip-4     123609        137885        +11.55%
benchmark                     old allocs     new allocs     delta
Benchmark_Query_no_gzip-4     149            150            +0.67%
benchmark                     old bytes     new bytes     delta
Benchmark_Query_no_gzip-4     14297         15205         +6.35%
```

feat(http): gzip compress the query CSV response.

---

tsdb/config.go
tsdb/series_file.go
tsdb/series_partition.go
tsdb/store.go

Closes #14066 
Limit concurrent series partition snapshots, to reduce memory and disk contention.

feat(storage): Limit concurrent series partition compaction

---

task.go
task/backend/executor/executor_metrics.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

Closes #14336
This PR refactors the metrics for the new task executor, and adds the following new metrics:
1. Errors Counter
1. Run Duration
1. Percent Workers Busy
1. Percent Promise Queue Usage
1. Manual runs count
1. Resume runs count

feat(tasks): add new executor prometheus metrics

---

query/statement_rewriter.go
query/statement_rewriter_test.go

Closes #14386 
Wrote this fix last week after discussions in storage re cardinality. 
Adds a `distinct` call to the rewritten queries for `SHOW SERIES EXACT CARDINALITY` and `SHOW SERIES CARDINALITY FROM <measurement>`.
See updated unit tests for the exact rewrites. 
This is the most straightforward fix to the current cardinality bug on 1.x `tsi1`, in which series keys are counted more than once if they are duplicated across shards. The only series cardinality query which is not affected by the bug is `SHOW SERIES CARDINALITY` (run across an entire database) since it is not rewritten and does bitmap level calculations or HLL if on a cluster. 
It is now confirmed that the cardinality bugs were behind https://github.com/influxdata/EAR/issues/992, so I want to continue the conversation and …

fix(query): make show series exact cardinality count only distinct series

---

mock/dependencies.go
query/dependency.go
query/stdlib/influxdata/influxdb/storage.go
query/stdlib/influxdata/influxdb/to_test.go

This change adds a `LookupName()` method to the `BucketLookup` and `OrganizationLookup` interfaces.
Both IDs and names are needed in the idpe implementation of `to()`, and the user can only provide one or the other but not both.  This change is part of the fix for influxdata/idpe#4077.
Companion PR in idpe:
https://github.com/influxdata/idpe/pull/4146

fix(query): add LookupName method to dependency interfaces (needed by flux to())

---

ui/src/authorizations/containers/TokensIndex.tsx
ui/src/buckets/containers/BucketsIndex.tsx
ui/src/dashboards/components/DashboardHeader.tsx
ui/src/dashboards/components/DashboardPage.tsx
ui/src/labels/containers/LabelsIndex.tsx
ui/src/members/actions/index.ts
ui/src/members/containers/MembersIndex.tsx
ui/src/onboarding/components/CompletionAdvancedButton.tsx
ui/src/onboarding/components/CompletionStep.tsx
ui/src/organizations/actions/orgs.ts
ui/src/organizations/apis/index.ts
ui/src/organizations/components/CreateOrgOverlay.tsx
ui/src/organizations/components/RenameOrgForm.tsx
ui/src/organizations/containers/OrgProfilePage.tsx
ui/src/pageLayout/components/AccountNavSubItem.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/scrapers/containers/ScrapersIndex.tsx
ui/src/shared/containers/RouteToOrg.tsx
ui/src/shared/containers/SetOrg.tsx
ui/src/telegrafs/components/CollectorCard.tsx
ui/src/telegrafs/containers/TelegrafsPage.tsx
ui/src/templates/containers/TemplatesIndex.tsx
ui/src/types/members.ts
ui/src/types/orgs.ts
ui/src/variables/containers/VariablesIndex.tsx

Link #14482 
This PR uses the locally generated client instead of `@influxdata/influx` for API calls. I figured it would be best to open a bunch of smaller PRs rather than one massive PR for all of the types.

refactor(ui): use locally generated client for buckets and orgs

---

query/stdlib/influxdata/influxdb/rules.go
query/stdlib/influxdata/influxdb/rules_test.go

The `exists` operator now gets pushed down to storage correctly. If
`exists` is used on a tag, then it will be rewritten to `tag != ""`
which is how storage defines if a tag exists. If `not exists` is used,
then it will use `tag == ""` which is how you would query storage for
only if a tag doesn't exist.
The `tag == ""` and `tag != ""` are different. For `tag == ""`, the
predicate is impossible for the storage layer to return true with.
Ideally, we would just rewrite this to return nothing and we wouldn't
bother with even querying storage. Instead, we just do not rewrite this
predicate because it cannot be rewritten to make sense with storage. If
we see `tag != ""`, it is the only one that can be passed through as-is
because `tag != ""` returns the same values as `exists tag`. It will …

feat(query/stdlib): push down exists operator to storage

---

query/control/controller.go
query/stdlib/influxdata/influxdb/metrics.go
query/stdlib/influxdata/influxdb/source.go
query/stdlib/influxdata/influxdb/source_test.go
query/stdlib/influxdata/influxdb/storage.go
storage/readservice/service.go

This adds a prometheus histogram metric to query execution that records the duration of read requests to storage.
influxdata/idpe#4126

feat(query): add storage request duration metric

---

.github/CODEOWNERS

We've been writing UI code off of the swagger spec before an actual API implementation exists. Recently, we coded against a spec that was changed during the implementation of the API. This broke our UI code, but we didn't find out about it until working on an unrelated task days later (when we regenerated our client from the spec).
By adding some UI representation to review `swagger.yml`, we can more proactively identify these issues.

chore(swagger): update codeowners file for swagger spec

---

ui/src/shared/utils/getMinDurationFromAST.test.ts
ui/src/shared/utils/getMinDurationFromAST.ts
ui/src/variables/utils/getWindowVars.ts

Closes #14535
Our computation of `v.windowPeriod` has been failing ever since we started using the `extern` parameter to substitute variables in the UI. An overly zealous `catch` block swallowed these errors as they happened. 
- Updated `v.windowPeriod` computation to not fail
- Added a `console.warn` statement for when this happens, so that we catch it sooner next time
If we can figure out how to run the WASM parser in our Jest environment, we could add much better coverage for these types of regressions. I'm not quite sure what that would involve yet. Another possibility is to display the value of the `v.windowPeriod` variable somewhere in the UI (perhaps in the variables sidebar), so that we can test this via Cypress.

fix(ui): fix v.windowPeriod computation

---

mock/points_writer.go
query/stdlib/influxdata/influxdb/to.go
storage/points_writer.go
storage/points_writer_test.go

This adds a buffered synchronous PointsWriter.  It wraps a regular PointsWriter and allows for fast buffered writing of points.  It is not thread-safe.

feat(query): Buffered writer for to function

---

http/org_service.go
http/query_handler.go
http/query_handler_test.go
http/requests.go
http/requests_test.go
http/swagger.yml
http/write_handler.go

Closes #13906
The org parameter could be `Organization.name` or `Organization.id` for '/write' and '/query'.

fix(http): The org parameter takes either the ID or Name interchangeably

---

CHANGELOG.md
authorizer/task.go
authorizer/task_test.go
http/swagger.yml
http/task_service.go
http/task_test.go
kv/task.go
task.go
task/servicetest/servicetest.go
task_errors.go

Add a type to task's to allow tasks to be filterable.

feat(task): Add task types

---

http/errors.go
http/errors_test.go

This will only attempt to parse an error as JSON if it has the content
type `application/json` so that it stops trying to parse the result as
JSON when it isn't JSON.
While the real error message is included, the addition of the "could not
parse json" makes it very confusing to read and distracts from the real
issue.
#3944

fix(http): use the content type header to determine how to parse http errors

---

tsdb/engine/tsm1/engine.go

Closes #14058 
Backport for 1.8 branch.
Instead of only logging error message when compaction fails, log the message and clear all tmp.tsm files so we can try again

Clean tmp tsm files when replace fails

---

ui/src/alerting/components/CheckNameTableField.tsx
ui/src/alerting/components/StatusSearchBar.tsx
ui/src/alerting/components/StatusTableField.scss
ui/src/alerting/components/StatusTableField.tsx
ui/src/alerting/components/TagsTableField.scss
ui/src/alerting/components/TagsTableField.tsx
ui/src/alerting/components/TimeTableField.tsx
ui/src/alerting/containers/AlertHistoryIndex.scss
ui/src/alerting/containers/AlertHistoryIndex.tsx
ui/src/eventViewer/components/BackToTopButton.tsx
ui/src/eventViewer/components/ErrorRow.tsx
ui/src/eventViewer/components/EventTable.scss
ui/src/eventViewer/components/EventTable.tsx
ui/src/eventViewer/components/EventViewer.reducer.ts
ui/src/eventViewer/components/EventViewer.tsx
ui/src/eventViewer/components/FooterRow.tsx
ui/src/eventViewer/components/Header.tsx
ui/src/eventViewer/components/LimitDropdown.tsx
ui/src/eventViewer/components/LoadingRow.tsx
ui/src/eventViewer/components/TableRow.tsx
ui/src/eventViewer/types/index.ts
ui/src/eventViewer/utils/fakeLoadRows.ts
ui/src/shared/utils/useDebouncedValue.ts
ui/src/shared/utils/useMountedEffect.ts
ui/src/style/chronograf.scss

Closes #14393
Adds a page for viewing check statuses. 
The page visualizes events from the status bucket in an infinite table:
When first displayed, the table records the current "now", and displays rows ordered from most recent to least recent.
The table can be refreshed to load any new statuses that have been written since you first viewed the page:
The table can also be searched:
As you'll see in the code, I'm hoping this can provide the foundation for a more general event viewer that can be used in place of the table visualization.
To that end, there's a control for how many rows are loaded at once:
This lets someone exploring their event data tailor their UI experience to their data. Data sets with less indexing are slower to search, so it may be desirable to use a lower row limit to …

feat(ui): add alert history page

---

CHANGELOG.md
task/backend/analytical_storage.go
task/servicetest/servicetest.go

Closes #13575
This PR fixes an issue where setting a limit in the query for getting runs for a task did not work, and would instead return all runs for the task. A limit was added to the flux function retrieving the runs, and the length of the runs was checking before adding to the runs to be returned.

fix(tasks): add run limit check to analytical store

---

CHANGELOG.md
task/backend/analytical_storage.go
task/servicetest/servicetest.go

Closes #14439
This PR sorts runs in the `handleGetRuns` function in `task_service.go` by most recent `scheduledFor` time.

feat(tasks): sort runs by most recently scheduled

---

ui/src/shared/components/CheckPlot.tsx
ui/src/shared/constants/index.ts
ui/src/timeMachine/components/view_options/CheckOptions.tsx
ui/src/timeMachine/components/view_options/OptionsSwitcher.tsx
ui/src/timeMachine/components/view_options/ScatterOptions.tsx

Closes #14633
Currently, the only supported visualization option is the color scheme. I think that before adding more, we should consider as a whole what these visualization options should be (e.g. is it exactly the same as an `XYView`? or would a scatterplot more appropriate? should we allow setting the y domain, or derive it from the thresholds of a check? etc. etc.)

feat(ui): stub out check visualization options

---

ui/webpack.dev.ts
ui/webpack.prod.ts

Disables running ESLint through the fork-ts-checker-webpack-plugin in development, due to its tendency to overuse CPU.
I think this OK since linter errors, unlike typechecking errors, are usually confined to the file you are working within. So they're a good fit to run via an editor, rather than the build tool.

chore(ui): disable eslint via fork-ts-checker-webpack-plugin

---

pkg/rhh/rhh.go
storage/engine_test.go
tsdb/index_test.go
tsdb/tsi1/index_test.go

This PR adds some performance improvements to the RHH structures used in the Series File and TSI index. These improvements will help with both reads and writes to the index. 
These improvements lead to upto a `98%` reduction in the number of objects allocated on the write path, and a `54%` reduction the amount of memory allocated. I would expect similar improvements on the read path, since the same APIs are called.
Previously all hashmap calls that are instrumented would create a new map (`prometheus.Labels`) whenever they were called, which caused a lot of allocations.
This PR pre-creates all the necessary maps (which are only used in a read-only capacity).
```
⇒  benchstat old.txt new.txt
name                                                     old time/op    new time/op    delta …
```

perf(storage): reduce allocations when accessing series file or TSI

---

CHANGELOG.md
http/swagger.yml
ui/mocks/dummyData.ts
ui/package.json
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx
ui/src/dataLoaders/constants/pluginConfigs.ts
ui/src/dataLoaders/reducers/dataLoaders.test.ts
ui/src/onboarding/actions/index.ts
ui/src/onboarding/components/CompletionStep.tsx
ui/src/onboarding/constants/index.ts
ui/src/organizations/actions/orgs.ts
ui/src/shared/components/ViewOverlay.tsx
ui/src/shared/copy/notifications.ts
ui/src/templates/components/StaticTemplateViewOverlay.tsx
ui/src/templates/constants/defaultTemplates.ts
ui/src/types/dataLoaders.ts
ui/src/types/templates.ts
ui/yarn.lock

Closes https://github.com/influxdata/influxdb-templates/issues/9
Closes https://github.com/influxdata/influxdb/issues/14505

feat(templates): adding new templates, removing calls to create templates

---

task/backend/analytical_storage.go

We currently have some data that has both a status tag and a status field
because of that we need to exclude the status field from the query results
We also need to limit after we sort the list so we get the correct group of runs

fix(task): Fix inconsistancies in run query

---

task/backend/analytical_storage.go
task/servicetest/servicetest.go

Because we were grouping by taskID and status we are returning limit(n) results for
"success" and limit(n) results for "failed" runs.
In addition we were creating run's from the 2 tables which would cause the order to be [table1...,table2...].

fix(task): Make runs sorting and limits work

---

mock/storage_reads.go
storage/reads/reader.go
storage/reads/reader_test.go

If the reader produces more than one table with the same group key, we
discard the later ones because the stream should never give us more than
one table with the same group key.
This is an error and it indicates the server sent us a bad set of data.
This change makes it so that the client is tolerant of that data and
will discard it if it exists.
#4177

fix(storage/reads): remove duplicate tables from the stream

---

http/check_test.go
notification/check/check.go
notification/check/check_test.go
notification/check/threshold.go
testing/checks.go

Closes https://github.com/influxdata/influxdb/issues/14581
convert the threshold to typed struct.

feat(notification/check): convert threshold type

---

go.mod
go.sum
query/stdlib/testing/end_to_end_test.go

See https://github.com/influxdata/flux/pull/1706 for context on the changes.

refactor(query/stdlib): update tests for new Flux test name conventions

---

go.mod
go.sum
query/stdlib/experimental/to.go
query/stdlib/experimental/to_test.go
query/stdlib/influxdata/influxdb/to.go
query/stdlib/influxdata/influxdb/to_test.go

influxdata/flux#1668
This PR creates a new flux function `to` in package `experimental`.
This follows the same general pattern of `influxdb.to`.  There is no need to the experimental `to` in OSS, so just the `experimental.ToOpSpec` and `experimental.ToProcedureSpec` are defined here, with the transformation defined in `idpe`.

feat(query/stdlib): add an experimental "to" function

---

check.go
http/check_service.go
http/check_test.go
kv/check.go
kv/check_test.go
kv/task.go
notification/check/check.go
notification/check/check_test.go
notification/check/deadman.go
notification/check/threshold.go
notification/check/threshold_test.go
notification/flux/ast.go
testing/checks.go

Closes #14331
This PR generates a flux script by constructing the corresponding AST by hand and then passing that to `ast.Format`. Additionally, it creates a task when a check is created.

feat(notification/check): generate task from check

---

kv/task.go
kv/task_test.go
task/servicetest/servicetest.go

Current behavior is that the first execution of a task happens based on the create time
of the task when using a 'every' schedule. If you create a task at 12:02 and want
the task to run every 15m. The first execution would happen at 12:17, and the 2nd would happen
at 12:30.
To fix this behavior I refactored the kv task to give a single source of knowledge.
We now have one function for finding exactly what the last scheduled task was.
We also now have a single method that calculates when the next schedule is due.
By unifying the logic it should always work the same way weather your asking when to run
or when creating a task.

fix(task): Unify task scheduling across create and query

---

http/swagger.yml
ui/src/alerting/actions/notifications/rules.ts
ui/src/alerting/components/notifications/EditRuleOverlay.tsx
ui/src/alerting/components/notifications/NewRuleOverlay.tsx
ui/src/alerting/components/notifications/RuleCard.tsx
ui/src/alerting/components/notifications/RuleEndpointDropdown.tsx
ui/src/alerting/components/notifications/RuleMessage.tsx
ui/src/alerting/components/notifications/RuleOverlayContents.tsx
ui/src/alerting/components/notifications/RuleOverlayFooter.scss
ui/src/alerting/components/notifications/RuleOverlayFooter.tsx
ui/src/alerting/components/notifications/utils/index.ts
ui/src/alerting/constants/index.ts
ui/src/alerting/reducers/notifications/rules.test.ts
ui/src/style/chronograf.scss
ui/src/types/alerting.ts
ui/yarn.lock

Part of #14619
I connected what parts of the notification rule UI I could to the API, but ran into an issue with the required `authorizationID` field. This field needs to be removed, but has not been removed yet. Once it has, I'll finish this up.

feat(ui): integrate notification rule overlays with API

---

authorizer/task.go
http/task_service.go
http/task_service_test.go
kv/session.go
kv/task.go
kv/task_test.go
task.go
task/backend/analytical_storage.go
task/backend/executor/executor.go
task/backend/executor/executor_test.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go
task/servicetest/servicetest.go
ui/yarn.lock

Passing tokens to tasks is cumbersome and we needed a way to more easily create tasks. With this change we no longer need a token on task create. We take the user that created the task and pass that in as the "owner". As far as the task is concerned the owner is the source of permissions.
This is done by adding an additional field on task create that is `OwnerID`. We will no longer respect the token passed in and it will be deprecated soon.
Things to do still:
Task updates need to allow for owners to be set.

feat(task): impersonate user on task execution

---

pkg/data/gen/arrays.gen.go
pkg/data/gen/arrays.gen.go.tmpl
storage/reads/helpers_test.go
storage/reads/response_writer.gen.go
storage/reads/response_writer.gen.go.tmpl
storage/reads/response_writer.go
storage/reads/response_writer_test.go
tsdb/cursors/arrayvalues.gen.go
tsdb/cursors/arrayvalues.gen.go.tmpl
tsdb/cursors/arrayvalues.go

The `ResponseWriter` would truncate the last series if the byte size of the points frames exceeded the `writeSize` constant, causing a `Flush` to occur and the cumulative `ResponseWriter.sz` to reset to zero. Because `ResponseWriter.sz` was not incremented for each frame, it remained at zero, which resulted in the final `Flush` short circuiting.
This PR implements the `Size` method for the `cursors.Array` types to be used to estimate the size of frame. This is in place of calling the Protocol Buffer `Size` function, which can be very expensive for varint types.

fix(storage): Ensure ResponseWriter flushes all buffered data

---

CHANGELOG.md
http/swagger.yml
http/task_service.go
kv/task.go
task.go

Closes #12170
Adds ability to find tasks with a name specified in the query parameters. An exact matched is used, to be consistent with the way filtering by name works with other resources such as buckets.
For example, a request to `http://localhost:9999/api/v2/tasks?name=mytask` will return the task(s) with the name `mytask`

feat(tasks): add ability to find tasks by name

---

notification/check/threshold.go
notification/check/threshold_test.go

Modifies the flux script so that the start and every nodes are replace on the provided flux script. Additionally, we assign pipeline to `data`. 
TODO:

fix(notification/check): assign flux pipeline to data and replace durations with every

---

authorizer/check.go
authorizer/check_test.go
authorizer/notification_rule.go
authorizer/notification_rule_test.go

This simplifies our permissions for a&n. A user with read/write permissions to an org has read/write permissions for a&n.

chore(authorizer): simplify permissions for alerts and notifications

---

authorizer/task.go
authorizer/task_test.go
http/swagger.yml
http/task_service_test.go
kv/task.go
task.go
task/backend/coordinator/coordinator_test.go
task_errors.go

We had previously removed token's from the task api but left the token in place in several locations in the stack.
Now we can cleanly remove the extra tokens.

feat(task): Remove token's from task structures

---

check.go
http/api_handler.go
http/check_service.go
http/check_test.go
http/notification_rule.go
kv/check.go
kv/check_test.go
kv/notification_rule.go
kv/notification_rule_test.go
mock/check_service.go
testing/checks.go
testing/notification_rule.go

Closes https://github.com/influxdata/influxdb/issues/14710
remove the task service of checks and notifications from kv, add them in http controller
Todo: figure out a way to make two service in one transaction

chore(http): split taskservice from check and notification

---

CHANGELOG.md
ui/cypress/e2e/buckets.test.ts
ui/cypress/e2e/scrapers.test.ts
ui/src/buckets/components/BucketCard.tsx
ui/src/buckets/components/BucketList.tsx
ui/src/buckets/components/RenameBucketForm.tsx
ui/src/buckets/components/RenameBucketOverlay.tsx
ui/src/buckets/components/UpdateBucketOverlay.tsx
ui/src/buckets/containers/BucketsIndex.tsx
ui/src/index.tsx
ui/src/me/components/GettingStarted.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/pageLayout/utils/index.ts
ui/src/scrapers/components/Scrapers.tsx
ui/src/scrapers/containers/ScrapersIndex.tsx
ui/src/settings/components/LoadDataHeader.tsx
ui/src/settings/components/LoadDataNavigation.tsx
ui/src/settings/components/LoadDataTabbedPage.tsx
ui/src/settings/components/SettingsNavigation.tsx
ui/src/settings/components/SettingsTabbedPage.tsx
ui/src/shared/components/DeleteDataOverlay.tsx
ui/src/telegrafs/containers/TelegrafsPage.tsx

- Create `Load Data` tab
- Move `Buckets`, `Telegrafs`,  and `Scrapers` from settings into load data
- Extend URL activator utility to scan URLs of any length
- Change orientation of tabs in settings page to be horizontal
Created this issue: https://github.com/influxdata/influxdb/issues/14708

refactor(ui): introduce "Load Data" tab

---

kv/check.go

When a check is created, its initial createdat and updatedat timestamps should be the same.

fix(kv): check createdat and updatedat should be identical

---

storage/metrics.go
storage/retention.go
storage/retention_test.go

Fixes https://github.com/influxdata/idpe/issues/4366
When many buckets are hosted in a single InfluxDB instance, cardinality for the storage_retention_checks_total measurement becomes a material burden. The metric doesn't seem to be valuable, so we'll remove it.

chore(storage): remove metric storage_retention_checks_total

---

kv/task.go

Currently we look up task authorization for all task lookups even if we are only
looking up the task for internal use's. We can keep the same interface but cutdown
on the amount of lookups we do by using seperate internal functions for task lookup
and task with id lookup

fix(task): Remove unnecessary auth lookups

---

storage/bucket_service.go
storage/bucket_service_test.go
storage/engine.go
storage/engine_test.go
storage/retention.go
storage/retention_test.go
tsdb/tsm1/cache.go
tsdb/tsm1/cache_test.go
tsdb/tsm1/engine_delete_prefix.go
tsdb/tsm1/engine_delete_prefix_test.go
tsdb/tsm1/engine_test.go

This PR adds some deeper tracing around deletes in the storage engine. The main use-case is for helping with performance work around deletes.

refactor(storage): add deeper tracing around deletes

---

query/dependency.go
query/dependency_test.go

The secret service is wrapped to be compatible with the flux interface
to the secret service.
The organization id is not part of the flux interface so this code
extracts the organization id from the query context so that it can lookup
a secret within the organization.
influxdata/flux#1680

feat(query): wrap the secret service for flux

---

authorizer/task_test.go
query/preauthorizer_test.go
query/stdlib/experimental/to.go
query/stdlib/influxdata/influxdb/to.go
ui/cypress/e2e/tasks.test.ts

This change makes it so that if an org or orgID are missing on calls to the `to` function
that the orgID is retrieved from the request context.
This is consistent with how `from` works.

fix(query/to): make orgID default to the context org

---

cmd/influxd/launcher/launcher.go

Closes #13289
Add `inspect` as subcommand when `influxd --help` is run. Currently, only flags are printed when running `influxd --help` while only subcommands are printed when running `influxd help`.
This PR adds the `inspect` command to the list of available commands when running `influxd --help`. It would be simple to add the `generate` command to this list if that is desired as well.

fix(launcher): print inspect as a subcommand when running with --help flag

---

cmd/influxd/inspect/inspect.go
cmd/influxd/inspect/verify_series.go
tsdb/series_verify.go
tsdb/series_verify_test.go

Closes #14279
Adds the influx_inspect verify-seriesfile tool to 2.x, called now with `influxd inspect verify-seriesfile`.
By default it will look for all series files in `$HOME/.influxdbv2/engine/_series`. If the `--series-file` flag is set, only that file is verified. The `--c` flag specifies the maximum number of concurrent workers used during verification. The `--db` flag that was available in 1.x has been removed.

feat(inspect): add verify-seriesfile tool to 2.x

---

CHANGELOG.md
cmd/influxd/launcher/launcher.go
task/backend/coordinator.go
task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go
task/backend/coordinator/support_test.go
task/backend/coordinator_test.go
task/backend/middleware/middleware.go
task/backend/middleware/middleware_test.go
task/backend/middleware/options.go

This is a WIP
This separates the current task coordinators reponsibilities into both a coordinator type and a task service middleware.
The task service middleware handles delegation to a persistent task service implementation and then notifies a middlware.Coordinator implementation that the action has taken place.
It is the job of the new `coordinator.Coordinator` to delegate the appropriate actions to a `backend.Scheduler` implementation.

refactor(tasks): separate coordinator and middleware

---

cmd/influxd/inspect/dump_tsi1.go
cmd/influxd/inspect/inspect.go
tsdb/tsi1/dump_tsi1.go

Closes #14754
Add the `dumptsi` tool to 2.x, now called with `influxd inspect dump-tsi`. The old functionality of the tool is retained, but the output can be difficult to read, as tsi information is printed as raw bytes. This is the largest drawback of this tool, and something that needs to be done in the future is reformatting the output to be more usable.
The ability to manually input file paths that will be checked as indexes has been removed, as has the requirement to specify a series file path. The tool now infers the series file and index file directories if none are specified.

feat(tsi1): port the dump-tsi tool to 2.x

---

http/swagger.yml

Closes #14513
Closes #13879
* added missing Permission types: `notificationRules`, `notificationEndpoints`, `checks`
* `Authorization` links use `Link` as a type
* Run's logs are readonly
* `TaskCreateRequest` and `TaskUpdateRequest` has `description` property to update Task description

docs(http): update swagger for easily use in clients

---

http/swagger.yml

Closes #13368
The `FluxSuggestions` schema is defined as:
```yaml
FluxSuggestions:
type: object
properties:
funcs:
type: object
properties:
name:
type: string
params:
type: object
```
but go implementation has a structure:
```go
// fluxParams contain flux funciton parameters as defined by the semantic graph
type fluxParams map[string]string
// suggestionResponse provides the parameters available for a given Flux function
type suggestionResponse struct {
Name   string     `json:"name"`
Params fluxParams `json:"params"`
}
// suggestionsResponse provides a list of available Flux functions
type suggestionsResponse struct {
Functions []suggestionResponse `json:"funcs"`
}
```
The `FluxSuggestions` should be defined as:
```yaml
FluxSuggestions:
type: object
properties:
funcs:
type: array
items: …
```

docs(http): update suggestions swagger definition to reflect reality

---

authorizer/notification_endpoint.go
authorizer/notification_endpoint_test.go
http/api_handler.go
http/notification_endpoint.go
http/notification_endpoint_test.go
kv/notification_endpoint.go
kv/notification_endpoint_test.go
mock/notification_endpoint_service.go
notification_endpoint.go
testing/notification_endpoint.go

Closes https://github.com/influxdata/influxdb/issues/14828
Move secret store from kv to http, manually tested with a local vault cluster. 
- [] http/swagger.yml updated (if modified Go structs or API)

fix(http): fix notfication endpoint secret store

---

kv/notification_rule.go
kv/org.go

When using a internal function in kv we can only use internal funciton calls.
By trying to use a Public function we attempt to create a read lock after acquiring a write lock

fix(notifications): fix a double locking notification rule lookup

---

CHANGELOG.md
ui/src/alerting/components/CheckCard.tsx
ui/src/alerting/components/endpoints/EndpointCard.tsx
ui/src/alerting/components/notifications/RuleCard.tsx
ui/src/clientLibraries/components/ClientLibraries.tsx
ui/src/clientLibraries/components/ClientLibraryList.tsx
ui/src/clientLibraries/components/LibraryCard.tsx
ui/src/clientLibraries/constants/mocks.ts
ui/src/clientLibraries/containers/ClientLibrariesPage.tsx
ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
ui/src/index.tsx
ui/src/onboarding/components/CompletionAdvancedButton.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/settings/components/LoadDataNavigation.tsx
ui/src/shared/utils/relativeTimestampFormatter.ts
ui/src/style/chronograf.scss
ui/src/telegrafs/components/Collectors.tsx
ui/src/telegrafs/components/TelegrafExplainer.scss
ui/src/telegrafs/components/TelegrafExplainer.tsx

Closes #14839 
Closes #14827 
Closes #14748 
- Make Telegraf explainer widget appear to the right of the list instead of below
- Ensure onboarding "advanced" button goes to correct location
- Standardize formatting of updated at timestamps in resource cards
- Introduce "Client Libraries" page
- Feature flag name: `clientLibrariesPage`
- Uses mock data & type
- Intentionally left very plain in anticipation of an actual design for this page

refactor(ui): fix update timestamps, fix onboarding button, and create client libraries page

---

ui/src/dashboards/components/Dashboard.tsx
ui/src/dashboards/components/DashboardPage.tsx
ui/src/shared/components/CheckPlot.tsx
ui/src/shared/components/HeatmapPlot.tsx
ui/src/shared/components/HistogramPlot.tsx
ui/src/shared/components/ScatterPlot.tsx
ui/src/shared/components/TimeSeries.tsx
ui/src/shared/components/XYPlot.tsx
ui/src/shared/components/cells/Cell.scss
ui/src/shared/components/cells/Cell.tsx

- Move the `IntersectionObserver` logic out of the `Cell` component and into the `TimeSeries` component
- Removed state from `DashboardPage` and moved the "inView" logic into `TimeSeries`
- Consolidates all logic of wether a `Cell` should fetch data in one place
- Allows @alexpaxton to replace all local page components with `@influxdata/clockface`
- Enables @alexpaxton to remove `FancyScrollbars`
- Enables extracting `ReactGridLayout` and styles into presentational components that can be shared across multiple projects (like Quartz)

refactor(dashboards): move time series fetcing descision to TimeSeries

---

ui/src/buckets/components/BucketsTab.tsx
ui/src/buckets/containers/BucketsIndex.tsx
ui/src/cloud/actions/limits.ts
ui/src/cloud/apis/limits.ts
ui/src/cloud/components/LimitChecker.tsx
ui/src/cloud/components/RateLimitAlert.tsx
ui/src/cloud/reducers/limits.ts
ui/src/cloud/utils/limits.ts
ui/src/dashboards/components/DashboardPage.tsx
ui/src/dataExplorer/components/DataExplorer.tsx
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/shared/components/cloud/CloudOnly.scss
ui/src/shared/constants/fluxFunctions.ts
ui/src/shared/copy/notifications.ts
ui/src/telegrafs/containers/TelegrafsPage.tsx

Closes #14824 
Add rate limit alert to load data pages and dashboard/de pages for cardinality.

feat(limits): Add Cardinality limit alerts

---

mock/task_service.go
task/backend/analytical_storage.go
task/backend/analytical_storage_test.go

If we are caching run's in the kv storage system it is possible to get
the the cached version from the kv store and the recently completed run
from the analytical store. We just need to only show analytical results if
we find a duplicate.

fix(task): Remove allowance for duplicate run's in run list

---

ui/src/alerting/components/notifications/RuleMessage.tsx

in rule overlay if no endpoint is selected it still looked like one was selected.

Select endpoint if none is selected

---

notification/rule/http.go
notification/rule/http_test.go

Removes `name` call from `monitor.notify` for http rule.

fix(notification/rule): remove name from notify call

---

kv/bucket.go
kv/bucket_test.go
kv/org.go
kv/org_test.go
kv/service.go

Adds the ability to customize validation of organization and bucket IDs in the `kv.Service`.

feat(kv): Add kv.Service org & bucket ID validation hooks.

---

CHANGELOG.md
ui/src/buckets/components/BucketAddDataButton.scss
ui/src/buckets/components/BucketAddDataButton.tsx
ui/src/buckets/components/BucketCard.tsx
ui/src/buckets/components/BucketContextMenu.tsx
ui/src/style/chronograf.scss

- Move `Rename` , `Add Data`, and `Delete Data by Filter` into resource card instead of context menu
- Use Clockface `Popover` for `Add Data` button
Despite making each bucket card a bit busier, I predict this change will make the options more discoverable and faster to access.

refactor(ui): expose bucket options as buttons instead of context menu

---

authorizer/bucket.go
authorizer/bucket_test.go
bolt/bucket_test.go
bucket.go
http/bucket_service.go
http/bucket_test.go
http/swagger.yml
inmem/bucket_service.go
kv/bucket.go
kv/org.go
testing/bucket_service.go
ui/cypress/e2e/onboarding.test.ts

Removes system bucket creation and hardcodes them into the response instead.
This is a short-term, stopgap solution for problems with #14539. Better solution to come in the following days.

fix(kv): mock system buckets

---

tsdb/tsm1/cache.go
tsdb/tsm1/cache_entry.go
tsdb/tsm1/cache_test.go
tsdb/tsm1/engine_delete_prefix.go
tsdb/tsm1/engine_delete_prefix_test.go
tsdb/tsm1/engine_schema.go
tsdb/tsm1/engine_schema_test.go
tsdb/tsm1/engine_test.go
tsdb/tsm1/ring.go

This PR adds several commits that significantly improve the performance of executing prefix-based deletes in the `tsm1.Cache`.
All deletes in 2.x are "prefix-based", because series data is segmented between buckets using an `<org, bucket>` id as the measurement name in the TSM engine and the TSI index.
We have recently been seeing issues where contention over the Cache (contention between a delete and some writes) is becoming problematic and affecting write throughput. This often manifests during a retention check (which is executed as a prefix-based delete for each bucket in the system, across varying time periods).
I tested the improvements in this PR with a benchmark that measures CPU time and allocations when deleting from a cache with 100K keys in it. There are two benchmarks: one …

perf(storage): improve prefix deletion in Cache

---

task/backend/executor/task_executor.go

When a task is told to execute it can be enqueued waiting for a worker.
This statistic will be superior to the existing delta based on scheduled for,
the current system can be effected by a user having slow queries or a long "delay" on the task.
This new way of measuring the same thing should allow us to accuratly measure when it is the task system's fault.

feat(task): Task execution will accurately measure queue delta

---

kv/urm.go

Closes https://github.com/influxdata/influxdb/issues/14876
Issue only happens in cloud,
if an org dependent resource doesn't exist, such an error shouldn't be a stopper to prevent the whole remove process. 
Manually tested

fix(kv): ignore not found error when removing org dep resources

---

CHANGELOG.md
storage/reads/stream_reader.go
storage/reads/stream_reader_test.go

Expose ability to Peek on `reads.ResultSetStreamReader` and `reads.GroupResultSetStreamReader`. The purpose being to allows creators of this type to pre-emptively peek at a frame before creating a cursor.
When creating multiple stream readers like these for multiple partitions and joining them into a single sequential or merged result set, a peek on each partition could be issued concurrently by the caller. This would allow us to quickly discard empty results, potentially reducing latency on reads.

perf(storage): expose ability to peek on stream readers

---

Makefile
ui/package.json
ui/webpack.common.ts
ui/webpack.prod.ts
ui/yarn.lock

We were getting runtime errors in the prod builds via honeybadger.
They were unreadable because we did not have source maps for giraffe.
We were only able to get this working for prod builds but not dev
despite trying putting it in the webpack common file.  This is good
'nuff for our purpose now, but maybe we'll need further investigation.
Bonus commit... I added a new make target of influxd so I would not
need to type so much.

build(webpack): add source maps for @influxdata/giraffe prod builds

---

tsdb/tsi1/partition.go

The previous behaviour always involved waiting `100ms`, even if there were no compactions running. This change just checks first and then initialises the same ticker behaviour if there are compactions running.
Also reduces the wait to `10ms`.

perf(storage): optimistically check compactions

---

CHANGELOG.md
ui/src/onboarding/components/AdminStep.tsx
ui/src/onboarding/components/__snapshots__/AdminStep.test.tsx.snap

e2e tests are failing because the fancyscroll bar component hides
the admin step during certain points in onboarding.
We were able to reproduce when the form in the admin step had been
marked as valid.
The use of the scrollbar in the setting seemed unneeded as it could
be rendered in a quite small window.
Therefore, we removed the scrollbar altogether for now.
Co-authored-by: Christopher Henn <chris@chrishenn.net>

fix(onboarding): remove fancy scrollbar that hides content

---

storage/engine.go
tsdb/tsi1/config.go
tsdb/tsi1/file_set.go
tsdb/tsi1/index.go
tsdb/tsi1/index_test.go
tsdb/tsi1/partition.go

Removes the original implementation of TSI cardinality stats which would cache all files except for the active log file and then merge the stats together on demand. This caused deleted series in the active log file to be ignored.
This PR changes the computation so all file stats are computed together. It also includes a new time based cache (`stats-ttl`) that defaults to `0` (disabled).

fix(tsi1): Remove TSI cardinality stats cache

---

chronograf/server/server.go
go.mod
go.sum
tools.go
tsdb/series_id.go

We were still referring to megacheck in tools.go; this confused
dependent projects also using staticcheck.

ci: use latest staticcheck

---

notification/rule/http.go
notification/rule/http_test.go
notification/rule/rule.go
notification/rule/slack.go
notification/rule/slack_test.go

Previously, I believed that we needed to pivot the table we statuses we fetched, but after testing it out in acceptance it became clear that that was not the case.

fix(notification/rule): remove fieldsAsCols pivot from rules

---

ui/src/shared/components/ColorSchemeDropdown.tsx

For whatever reason, we now have xy views stored with an empty array in the `colors` field. Attempting to open the visualization options for such a view results in a crash.
This commit updates the `ColorSchemeDropdown` to access the `colors` field more defensively.
Closes #14950

fix(ui): prevent crash when opening line visualization options

---

ui/src/alerting/actions/checks.ts

The easiest path forward for fixing
https://github.com/influxdata/influxdb/issues/14966 is to have the UI
use put instead of patch for updating checks. Long term, we will want to
be able to use patch, but as of now patch is not functional.

fix(ui): change patchCheck to putCheck for updating check in UI

---

notification/endpoint/endpoint_test.go
notification/endpoint/slack.go

Related to https://github.com/influxdata/influxdb/issues/14952
This is a partial fix of slack token is not required, we still need to update the generated flux

fix(notification/endpoint): remove slack token requirement

---

ui/src/timeMachine/utils/rawFluxDataTable.ts

When parsing a Flux CSV file with hundreds of thousands of lines for the "Raw Data View", we would see a
Maximum call stack size exceeded
error. This was because every line in the CSV was being passed as an argument in a single `Array.prototype.push` call, and there are [limits][0] to how many arguments can be passed to a function.
This commit avoids passing the arguments all at once.
[0]: https://stackoverflow.com/questions/22747068/is-there-a-max-number-of-arguments-javascript-functions-can-accept
Closes #14566

fix(ui): fix max call stack exceeded error when parsing CSV

---

pkg/limiter/write_test.go
pkg/limiter/writer.go

Closes #9886
`rate.Limiter.WaitN(ctx, n)`
> returns an error if n exceeds the Limiter's burst size
InfluxDB uses WaitN() to rate limit writes in an io.Writer wrapper, passing the length of the byte slice for n. So, when TSM compaction writes a file larger than compact-throughput-burst, the write fails, rather than being throttled. This causes the entire compaction to unwind, retry, etc.
This change splits calls to the wrapped `Write()` into chunks no larger than the rate limiter's burst threshold.

fix(storage): guard against compaction burst throughput limit

---

notification/endpoint/endpoint_test.go
notification/endpoint/slack.go
notification/rule/slack.go
notification/rule/slack_test.go

Previously, we expected that both token and url would be provided, but
we've become aware that the user may provide either or both of them.
Closes https://github.com/influxdata/influxdb/issues/14952

fix(notification/rule): conditionally include url and token for slack rule

---

CHANGELOG.md
ui/cypress/e2e/collectors.test.ts
ui/cypress/e2e/labels.test.ts
ui/cypress/e2e/tokens.test.ts
ui/cypress/e2e/variables.test.ts
ui/src/authorizations/components/AllAccessTokenOverlay.tsx
ui/src/authorizations/components/BucketsTokenOverlay.tsx
ui/src/authorizations/components/TokensTab.tsx
ui/src/authorizations/containers/TokensIndex.tsx
ui/src/index.tsx
ui/src/members/components/AddMembersOverlay.tsx
ui/src/members/components/Members.tsx
ui/src/organizations/components/OrgProfileTab.tsx
ui/src/organizations/components/RenameOrgForm.tsx
ui/src/organizations/components/RenameOrgOverlay.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/settings/components/LoadDataNavigation.tsx
ui/src/settings/components/SettingsNavigation.tsx
ui/src/templates/components/StaticTemplateCard.tsx
ui/src/templates/components/TemplateCard.tsx
ui/src/templates/components/createFromTemplateOverlay/TemplateBrowserEmpty.tsx
ui/src/templates/containers/TemplatesIndex.tsx
ui/src/variables/components/CreateVariableOverlay.tsx
ui/src/variables/components/RenameVariableOverlay.tsx
ui/src/variables/components/UpdateVariableOverlay.tsx
ui/src/variables/components/VariableCard.tsx
ui/src/variables/components/VariablesTab.tsx

- Move `Tokens` tab to `Load Data` page
- Expose all `Settings` tabs in nav menu
- Prefix all settings page URLS with `settings/`

refactor(ui): settings navigation

---

notification/flux/ast.go
notification/rule/http.go
notification/rule/http_test.go

Closes: #14987
The body of the JSON webhook would be:
{
"version": 1,
"rule_name": notification._notification_rule_name,
"rule_id": notification._notification_rule_id,
"endpoint_name": notification._notification_endpoint_name,
"endpoint_id": notification._notification_endpoint_id,
"check_name": r._check_name,
"check_id": r._check_id,
"check_type": r._type,
"source_measurement": r._source_measurement,
"source_timestamp": r._source_timestamp,
"level": r._level,
"message": r._message,
}
Closes #

feat(notification/rule): add JSON body for the HTTP POST

---

notification/check/deadman.go
notification/check/deadman_test.go
notification/check/threshold.go

Closes https://github.com/influxdata/influxdb/issues/15007
If the user specifies an aggregate window in the query they provide us,
we remove it so that we can property detect the deadman. This is not the
solution we will want long term, but should be sufficient for now.

fix(notification/check): remove the aggregateWindow from the deadman query

---

kv/task.go
task/servicetest/servicetest.go

When the flux script removes a offset it should be removed from the task

fix(task): clean up offset when removed in script

---

kv/task.go

We need to only update the updated at time when we recieve a external request for
an update. LatestCompleted is an internal request from the scheduler.

fix(task): Dont update updatedAt on latestCompleted updates

---

notification/check/deadman.go
notification/check/deadman_test.go

Discovered that the deadman table needs to be pivoted before the data
can be passed to deadman.

fix(notification/check): pivot table before sending to deadman call

---

task/backend/scheduler.go

The current behavior is that the update is pushed into the scheduler,
and the scheduler cherry pick's what it needs. This leaves the task itself out
meaning any logging the scheduler did was not going to have the new task information in it.

fix(task): Update task in scheduler to show updated logs.

---

ui/src/alerting/components/CheckCard.tsx

Closes https://github.com/influxdata/influxdb/issues/15022
After we switched to using PUT in the API, we'll need to include the
entire check in our update request. Ideally we could just always use
PATCH, but due to a defect in the API we currently cannot.

fix(ui/src/alerting/components/CheckCard): include entire check in update

---

notification/flux/ast.go
notification/rule/http.go
notification/rule/http_test.go

This adds the _version: 1 correctly to the body of the HTTP POST.
Additionally, this fixes the imports when using secrets.
The POSTed JSON body now is:
```json
{
"_check_id": "046cac59e2aa3000",
"_check_name": "High CPU User Usage",
"_level": "crit",
"_measurement": "notifications",
"_message": "High CPU User Usage: rsavage.prod is crit",
"_notification_endpoint_id": "046cad0c83aec000",
"_notification_endpoint_name": "HTTP Endpoint",
"_notification_rule_id": "046dff53d4183000",
"_notification_rule_name": "HTTP Notification",
"_source_measurement": "cpu",
"_source_timestamp": 1567797375000000000,
"_start": "2019-09-06T19:15:59Z",
"_status_timestamp": 1567797376416632300,
"_stop": "2019-09-06T19:16:20.362006739Z",
"_time": "2019-09-06T19:16:20.609629338Z",
"_type": "threshold",
"_version": …
```

feat(notification/rule): add _version: 1 to HTTP body

---

CHANGELOG.md
ui/src/alerting/components/builder/AlertBuilder.scss
ui/src/alerting/components/builder/AlertBuilder.tsx
ui/src/alerting/components/builder/CheckConditionsCard.tsx
ui/src/alerting/components/builder/CheckMatchingRulesCard.tsx
ui/src/alerting/components/builder/CheckMessageCard.tsx
ui/src/alerting/components/builder/CheckMetaCard.tsx
ui/src/alerting/components/builder/DeadmanConditions.tsx
ui/src/alerting/components/builder/ThresholdStatement.tsx
ui/src/timeMachine/components/TimeMachineAlerting.tsx

Closes #15023 
Closes #14955 
- Remove the matching rules card (@russorat says it doesn't work and is not critical for next week)
- I did not delete the component for this in case we want to add it back in after launch
- Move `Status Message Template` into its own card and add some documentation
- Cards in check builder stretch to fill the screen width, but also have minimum sizes to avoid being squished on smaller screens

refactor(ui): update check builder design

---

notification/flux/ast.go
notification/rule/pagerduty.go
notification/rule/pagerduty_test.go

Semantically, we've done the following:
// name of the client sending the alert.
client: "influxdata"
// url of the client sending the alert.
client_url: the endpoint URL for now (needs to change to rule) tracked in https://github.com/influxdata/influxdb/issues/15042
// The class/type of the event, for example ping failure or cpu load
class: check's name
// Logical grouping of components of a service, for example app-stack
group: source measurement
Co-authored-by: Alirie Gray <alirie.gray@gmail.com>
Closes #15032

fix(notification/rule): convert time, trigger, severity

---

ui/src/alerting/components/notifications/utils/index.ts

Closes https://github.com/influxdata/influxdb/issues/15000
When submitted, with the default draft rule, the request would fail due
to the backend attempting to contruct flux with empty string values.

fix(notificationRules): remove initial tag filter from draft rule

---

notification/rule/pagerduty.go
notification/rule/pagerduty_test.go

Previously, the URL would cause pages to be sent to incorrect addresses.
Token is only needed for PagerDuty REST API and not events.
Requires: https://github.com/influxdata/flux/pull/1825

fix(notification/rule): pagerduty does not need token and url

---

CHANGELOG.md
ui/src/alerting/constants/index.ts
ui/src/authorizations/components/BucketsTokenOverlay.tsx
ui/src/buckets/components/BucketAddDataButton.scss
ui/src/buckets/components/BucketCard.tsx
ui/src/buckets/components/BucketOverlayForm.tsx
ui/src/buckets/components/CreateBucketOverlay.tsx
ui/src/buckets/components/UpdateBucketOverlay.tsx
ui/src/buckets/constants/index.ts
ui/src/dataLoaders/components/BucketsDropdown.tsx
ui/src/shared/components/ThresholdMarkers.tsx
ui/src/tasks/components/TasksOptionsBucketDropdown.tsx

Closes #14946 
Closes #15036 
Closes #14804 
Closes #15057 
System buckets removed from generate token overlay:
No system buckets in dropdown during scraper / telegraf config creation:
No system buckets in save as task form

refactor(ui): alerting details polish

---

ui/src/alerting/components/SentTableField.tsx
ui/src/types/alerting.ts

The "Sent" column on the notification history page was always showing a green checkbox, even when a particular notification wasn't sent.
Issue seems to be https://github.com/influxdata/idpe/issues/4645, but this is a UI-only workaround.

fix(ui): show notifications history sent column properly

---

ui/cypress/e2e/notificationEndpoints.test.ts
ui/src/alerting/constants/index.ts

This is so that in cloud there is not a weird UX for initial users who
see http, but cannot create an http endpoint.

fix(ui): use slack as default endpoint

---

ui/src/alerting/utils/history.ts

We want to display a row for each notification, but we were displaying a row for each field for each notification.
By filtering out the system fields (those that start with an underscore), we are in left with only a single user-specific field.

fix(ui): deduplicate rows on notifications history page

---

http/write_handler.go

Prevents write from continuing on after error condition met.

fix(http): add return after returning system bucket errror

---

CHANGELOG.md
ui/assets/index.html
ui/src/index.html
ui/src/style/_reset.scss

Add viewport scaling meta to html and css to correct responsive scaling on mobile devices.

Add viewport scaling to html meta responsive mobile scaling

---

task/backend/executor/executor_metrics.go
task/backend/executor/task_executor.go
task/backend/scheduler.go
task/backend/scheduler_metrics.go
task/backend/scheduler_test.go

We need to be able to see how long its taking task's to run as well
be able to see the start delta time per task.

feat(task): add run duration to task metrics

---

task/backend/executor/executor_metrics.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go
task_errors.go

Closes https://github.com/influxdata/idpe/issues/4262
This PR makes a change to the new executor, which will be put into effect when the new scheduler is merged.
Previously, executor metrics only reported the number of errors thrown by the executor, without any information on what type of errors were occurring. This PR attaches an error type to the error metric, so that developers can observe error trends in the tasks dashboard.

feat(tasks): report error messages to metrics

---

CHANGELOG.md
task/backend/scheduler.go

Closes idpe #4648
This PR adds the ability to set the default concurrency for the task scheduler with an environment variable called `DEFAULT_CONCURRENCY`

feat(tasks): use env variable for concurrency

---

http/bucket_service.go

Closes https://github.com/influxdata/idpe/issues/4595
post bucket validation should not return 500 errors.

fix(http): post bucket validation.

---

pkg/limiter/write_test.go
pkg/limiter/writer.go

Closes #9886 for the 2.0 branch
`rate.Limiter.WaitN(ctx, n)`
> returns an error if n exceeds the Limiter's burst size
InfluxDB uses WaitN() to rate limit writes in an io.Writer wrapper, passing the length of the byte slice for n. So, when TSM compaction writes a file larger than compact-throughput-burst, the write fails, rather than being throttled. This causes the entire compaction to unwind, retry, etc.
This change splits calls to the wrapped Write() into chunks no larger than the rate limiter's burst threshold.

fix(storage): guard against compaction burst throughput limit (#14985)

---

task/backend/scheduler.go
task/backend/scheduler_metrics.go

The first pass failed to save the correct execution metrics,
it will now compare the difference between start and finish.

fix(task): execution metric now shows correct data

---

ui/src/alerting/constants/index.ts
ui/src/buckets/components/Retention.tsx
ui/src/shared/components/DurationSelector.tsx
ui/src/shared/constants/index.ts
ui/src/shared/utils/duration.test.tsx
ui/src/shared/utils/duration.ts
ui/src/shared/utils/getMinDurationFromAST.ts
ui/src/timeMachine/actions/queries.ts
ui/src/timeMachine/components/FunctionSelector.tsx
ui/src/timeMachine/constants/queryBuilder.ts
ui/src/timeMachine/selectors/index.ts
ui/src/variables/utils/getTimeRangeVars.ts
ui/src/variables/utils/getWindowVars.ts

Shows the computed value of the aggregate window period in the function selector dropdown:
Not in this PR, but I also want to add the `v.timeRangeStart`, `v.timeRangeStop`, and `v.windowPeriod` variables to this list as well:

feat(ui): show auto window period in function selector dropdown

---

ui/src/variables/components/VariableForm.tsx

Closes https://github.com/influxdata/influxdb/issues/15060
Previously, the create button for a variable wouldn't be enabled unless
the user clicked in the text box, despite a query being present. This
adds an aditional check to the `isFormValid` method that ensures that if
a query is present the create button will be enabled.

fix(variables/components/VariableForm): check to see if form is valid

---

cmd/influxd/inspect/export_index.go
cmd/influxd/inspect/inspect.go
tsdb/explode.go
tsdb/tsi1/sql_index_exporter.go
tsdb/tsi1/sql_index_exporter_test.go

This pull request adds a utility function to `influxd inspect` called `export-index`. This will dump the contents of a TSI index to a SQL file which can be imported into `sqlite3` to inspect.
```sh
$ influxd inspect export-index -h
This command will export all series in a TSI index to
another format for easier inspection and debugging.
Usage:
influxd inspect export-index [flags]
Flags:
-h, --help                 help for export-index
--index-path string    Path to the index directory of the data engine (default "/Users/benbjohnson/.influxdbv2/engine/index")
--series-path string   Path to series file (default "/Users/benbjohnson/.influxdbv2/engine/_series")
```
```
$ influxd inspect export-index
CREATE TABLE IF NOT EXISTS measurement_series (
org_id    INTEGER NOT NULL,
bucket_id INTEGER …
```

feat(tsdb): Add SQL export for TSI indexes

---

cmd/influx_inspect/buildtsi/buildtsi.go
cmd/influxd/inspect/build_tsi.go
cmd/influxd/inspect/inspect.go
cmd/influxd/inspect/report_tsi1.go

This PR adds a new `inspect` tool, allowing the operator to rebuild their TSI index.
The tool uses the same APIs for building TSI indexes as we use elsewhere. It contains several configuration options for tweaking performance. The tool documentation explains these

feat(tools): add build-tsi tool

---

cmd/influxd/launcher/launcher.go
go.mod
nats/publisher.go
nats/server.go
nats/subscriber.go

Closes #12697 
Closes #10628
This PR ensures that a port is free for the nats server, if it's initialised multiple times during tests. The obvious thing would have been to tell the server to bind to a random port `:0` but I couldn't for the life of me get that working with the library.
This will work until we rip out NATS.

fix(tests): ensure NATS server port free

---

task/backend/executor/executor_metrics.go
task/backend/scheduler.go
task/backend/scheduler_metrics.go
task/backend/scheduler_test.go
task_errors.go

Closes idpe 4708
Errors in the new executor were previously changed to use influxdb.Error objects and report error codes to metrics in [this PR](https://github.com/influxdata/influxdb/pull/14926/).
This PR implements the same change for error reporting in the scheduler which is currently in use, which will give developers a more accurate picture of what system errors are occurring and need to be responded to. Will not need to be updated when the new scheduler goes into effect, as the new executor already handles this behavior. 
TODO:

fix(tasks): report error codes to metrics

---

ui/cypress/e2e/checks.test.ts
ui/src/alerting/components/AlertingIndex.scss
ui/src/alerting/components/CheckAlertingButton.tsx
ui/src/alerting/components/CheckCards.tsx
ui/src/alerting/components/CheckEOHeader.tsx
ui/src/alerting/components/CheckEOSaveButton.tsx
ui/src/alerting/components/ChecksColumn.tsx
ui/src/alerting/components/CreateCheckDropdown.tsx
ui/src/alerting/components/NewCheckEO.tsx
ui/src/alerting/components/NewDeadmanCheckEO.tsx
ui/src/alerting/components/NewThresholdCheckEO.tsx
ui/src/alerting/components/builder/CheckConditionsCard.tsx
ui/src/index.tsx
ui/src/shared/utils/view.ts
ui/src/timeMachine/components/QueryBuilder.tsx
ui/src/timeMachine/utils/queryBuilder.ts

Closes #15162 
Closes #15163 
Closes #15164 
Closes #15165 
Have the user select the type of check they are making before opening the check editor
Move validation popover to save button instead of radio buttons
Don't show function selector if check is deadman
Remove check type toggle from conditions card

refactor(ui): split check creation flow

---

task/backend/executor/executor.go
task/backend/executor/executor_test.go

Implementations of the backend.Executor produce errors limited to querying the KV store. The remainder of the errors will be processed in the implementation of a `RunPromise`.
Closes #15161

fix(task): Improve Executor#Execute error consistency

---

http/swagger.yml

The `/query` swagger endpoint now specifies that error messages are
returned as the standard JSON schema. The standard JSON schema has also
been changed slightly so that only `code` and `message` are documented
and the intention is that we will flatten the message from an
`influxdb.Error` before we encode the JSON.
#14974

docs(http): fix the documentation for the query swagger endpoint

---

CHANGELOG.md
jsonweb/token.go
jsonweb/token_test.go

Closes #14971 
This introduces the `jsonweb` package which contains types for parsing JWTs into a type suitable for use as an `influxdb.Authorizer`. This opens up the ability to start work on jwt based authentication in the API.
The original issue imagined an authorizer type. However, this has evolved into the form of a token type which happens to implement Authorizer interface. The next piece of work will be to integrate this into https://github.com/influxdata/influxdb/blob/master/http/authentication_middleware.go#L104
Update: I have a draft PR of the next piece of work which based on this one here https://github.com/influxdata/influxdb/pull/15151
These could also be merged if that is more preferrable.

feat(auth): add new jsonweb package

---

cmd/influx/repl.go
cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/query_test.go
go.mod
go.sum
query/bridges.go
query/control/controller.go
query/control/controller_test.go
query/stdlib/influxdata/influxdb/buckets.go
query/stdlib/influxdata/influxdb/dependencies.go
query/stdlib/influxdata/influxdb/from.go
query/stdlib/influxdata/influxdb/metrics.go
query/stdlib/influxdata/influxdb/source.go
query/stdlib/influxdata/influxdb/source_test.go
query/stdlib/influxdata/influxdb/storage.go
query/stdlib/influxdata/influxdb/to.go
query/stdlib/influxdata/influxdb/to_test.go
query/stdlib/influxdata/influxdb/v1/databases.go
storage/readservice/service.go
storage/readservice/store.go
storage/wal/verifier_test.go
task/backend/analytical_storage_test.go
task/options/options.go
tsdb/tsm1/metrics_test.go

Connected to https://github.com/influxdata/flux/issues/1795.
This is the counterpart of https://github.com/influxdata/flux/pull/1879.
I moved dependency management from `readservice` to `stdlib/influxdata/influxdb` because of circular dependencies and because that seems its natural place.
Added a Launcher test to check that dynamic queries work.

refactor(dependencies): use new dependency injection framework

---

authorizer/task_test.go
bolt/passwords.go
errors.go
errors_test.go
http/dashboard_test.go
http/document_test.go
http/errors.go
http/errors_test.go
http/query_handler_test.go
http/router_test.go
http/task_service_test.go
http/write_handler_test.go
inmem/passwords.go
kv/passwords_test.go
query/control/controller_test.go
task/servicetest/servicetest.go
testing/passwords.go
testing/telegraf.go
testing/user_resource_mapping_service.go

The http error schema has been changed to simplify the outward facing
API. The `op` and `error` attributes have been dropped because they
confused people. The `error` attribute will likely be readded in some
form in the future, but only as additional context and will not be
required or even suggested for the UI to use.
Errors are now output differently both when they are serialized to JSON
and when they are output as strings. The `op` is no longer used if it is
present. It will only appear as an optional attribute if at all. The
`message` attribute for an error is always output and it will be the
prefix for any nested error. When this is serialized to JSON, the
message is automatically flattened so a nested error such as:
influxdb.Error{
Msg: errors.New("something bad happened"),
Err: …

refactor: http error serialization matches the new error schema

---

tsdb/tsm1/array_cursor_test.go
tsdb/tsm1/file_store.go

All seeks must be added to the c.current slice so the min and max read values can be updated on each read pass.

fix(tsm1): Fix duplicate points

---

task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

I chose to add a execute function that allow's the task executor to match expectation from
the scheduler but I left in the existing executor method that return's promises. This is
because I like to be able to have the accountablilty and visiblity inside what's happening
with each execution even though the promise isn't required for the scheduler. This function signature will be used by the coordinator and potentially other's that want to ensure a 'execution' is completed.

fix(task): Update task executor to match the expected executor interface

---

task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

We needed the coordinator to be able to execute manual runs and resume runs.
These two functions have been added, but we also needed to allow for the executor to be
mocked out. To do that we needed to return a Promise interface instead of an actual
struct. Both these changes are to facilitate coordinator work and testing.

feat(task): add functions to the task executor to allow for coordinator control

---

cmd/influxd/launcher/query_test.go
query/stdlib/experimental/to.go
query/stdlib/experimental/to_test.go
query/stdlib/packages.go

There was already an implementation of `experimental.to()` in enterprise, this adds it to OSS as well.

feat(query/stdlib/experimental): add experimental.to() implementation to OSS

---

CHANGELOG.md
etc/config.sample.toml
services/httpd/config.go
services/httpd/handler.go
services/httpd/handler_test.go

Adds `pprof-auth-enabled` and `ping-auth-enabled` configuration options which can enable authentication on all `/debug` and `/ping` endpoints. This also covers the prometheus `/metrics` and deprecated `/status` endpoints.
With these additions, all InfluxDB endpoints will require authentication with the following configuration:
```
[http]
auth-enabled = true
pprof-auth-enabled = true
ping-auth-enabled = true
```
Note that `go tool pprof` does not support authentication so it will not work when `pprof-auth-enabled` is enabled.

feat(httpd): Add option to authenticate debug/pprof and ping endpoints

---

http/notification_endpoint.go
http/swagger.yml
kv/notification_endpoint.go
testing/notification_endpoint.go

* Added `TraceSpan` parameter into  Get all notification endpoints operation
* Fixed handler path for a list of all labels for a notification endpoint
* Fixed filtering NotificationEndpoints by `limit` and `offset`

fix(http): fixed http NotificationEndpoint

---

http/swagger.yml

Add `ParenExpression` to swagger definition. 
The `ParenExpression ` was introduce in https://github.com/influxdata/flux/pull/1848.

fix(http): add ParenExpression

---

Gopkg.lock
Gopkg.toml

Update InfluxQL dependency to v1.0.1, which has fix related to expanding regex in queries.

chore(influxdb): Update InfluxQL dependency

---

bolt/user.go
http/bucket_test.go
http/check_test.go
http/notification_endpoint_test.go
http/user_resource_mapping_test.go
http/user_service.go
inmem/user_service.go
testing/user_service.go
user.go

Don't omit status on user responses

fix(influxdb): Always return user status

---

http/swagger.yml

Added discriminator for `Check` into swagger definition.

fix(http): add discriminator for Check schema

---

task/backend/executor/limits.go
task/backend/executor/limits_test.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go
task_errors.go

The new task executor handles limit's differently then the old executor
instead of front loading limits by creating a runner for every task that might run
the new executor has a large worker pool and queue. This allow's us to have a unlimited
concurrency per task and helps us avoid a back log of task's execution based on a
arbitrary execution limit. This add's the ability to add an optional task execution limit
so a user can still have the advantages of limiting concurrency.

feat(task): add limit function for task concurrency

---

http/swagger.yml

1. Added a `discriminator` for a `Threshold` schema
1. Added `links` into `CheckBase` schema

fix(http): add a discriminator for a Threshold schema, add links into CheckBase schema

---

http/swagger.yml

1. `NotificationRuleBase`: the `endpointID` should be required and editable, there is missing a links property
https://github.com/influxdata/influxdb/blob/c3127c8cdd87d8b6963811eded8074a31fe712d2/notification/rule/rule.go#L91
1. `NotificationRule`: add discriminator
1. add a missing `TraceSpan` parameter into a `GetNotificationRules` and `GetChecks`

fix(http): update NotificationRuleBase and NotificationRule schema to reflect reality

---

storage/engine_test.go
task/backend/scheduler_test.go
tsdb/tsm1/file_store.go
tsdb/tsm1/metrics_test.go

This commit removes the level=0 label from TSM Disk Usage metrics, since TSM level starts always (from 1 up to 4+).
ex:
before fix  :
```
storage_tsm_files_disk_bytes{engine_id="0",level="0",node_id="0"} 0
storage_tsm_files_disk_bytes{engine_id="0",level="1",node_id="0"} 3.3855125e+07
storage_tsm_files_disk_bytes{engine_id="0",level="2",node_id="0"} 2.3737882e+07
storage_tsm_files_disk_bytes{engine_id="0",level="3",node_id="0"} 1.86620984e+08
```
After fix :
```
storage_tsm_files_disk_bytes{engine_id="0",level="1",node_id="0"} 3.3855125e+07
storage_tsm_files_disk_bytes{engine_id="0",level="2",node_id="0"} 2.3737882e+07
storage_tsm_files_disk_bytes{engine_id="0",level="3",node_id="0"} 1.86620984e+08
```

fix(storage): remove level=0 from TSM disk bytes metrics.

---

CHANGELOG.md
ui/package.json
ui/src/templates/constants/defaultTemplates.ts
ui/yarn.lock

don't merge until https://github.com/influxdata/influxdb-templates/pull/24 is closed and a new version of the templates package is cut.
Closes #

fix(templates): add jmeter template

---

task.go
task/backend/coordinator/coordinator_test.go
task/backend/coordinator/support_test.go
task/backend/coordinator/task_coordinator.go
task/backend/coordinator/task_coordinator_support_test.go
task/backend/coordinator/task_coordinator_test.go
task/backend/schedulable_task_service.go
task/backend/schedulable_task_service_test.go
task/backend/scheduler/scheduler.go
task_errors.go

Closes #15129
This PR implements a new Coordinator called (temporarily) `TaskCoordinator' to work with the new Scheduler currently in progress.
This addition includes several abstractions, including:
1. `SchedulableTask`, a wrapper around the `Task` struct to make it work with the `Schedulable` type expected by the Scheduler.
1. `SchedulableTaskService`, a wrapper around the `TaskService` to provide the API for updating a task with a new `LatestCompleted` value.
This new coordinator currently lives alongside the old coordinator in `task_coordinator.go`. The old code will be removed once the new system has been fully implemented and tested. 
TODO (when scheduler is completed):
This PR also adds helper functions `LatestCompletedTime` and `OffsetDuration` to the Task struct to return Go Time …

refactor(tasks): create coordinator for new scheduler/executor

---

CHANGELOG.md
ui/src/shared/constants/fluxFunctions.ts

fix(fluxFunctions): add getColumn, getRecord, tableFind

---

CHANGELOG.md
auth.go
http/authentication_middleware.go
http/authentication_test.go
jsonweb/token.go

Closes #14972 
This PR adds support for JWT authorization to the http auth middleware.
This uses the new `jsonweb` package authorizer types.
When `Token` based authorization is used an attempt is first made to deserialize the payload as a JWT. If the token is well-formed, it is assumed that JWT based authorization is being attempted. The token is then validated and if successful the permission claims are passed down via the usual Authorizer on context strategy.
Given the token is not a well-formed JWT, then it is regarded as a lookup token for an associated Authorization in the AuthorizationService and treated as such. The Authorization is looked up using the token payload as the key.
Currently there is no decision as to how to configure a signing key, so this PR just introduces the …

feat(auth): add jwt support in auth middleware

---

CHANGELOG.md
bolt/user.go
inmem/user_service.go
kv/user.go
testing/onboarding.go
testing/user_service.go

Closes #15274
Adds `active` as the default status for the user response.

fix(http): Ensures users are created with an active status

---

CHANGELOG.md
ui/src/shared/components/FluxEditor.tsx
ui/src/style/chronograf.scss
ui/src/timeMachine/components/EditorShortcutsTooltip.scss
ui/src/timeMachine/components/EditorShortcutsTooltip.tsx
ui/src/timeMachine/components/Queries.tsx

Add commenting shortcut to the script editor.
Show shortcuts in question mark tooltip

feat(ui): Add shortcut for commenting in script editor

---

CHANGELOG.md
tsdb/tsm1/cachestatus_string.go

Added missing string values for CacheStatus type.
Closes: #15284.

fix(storage): added missing string values for CacheStatus type.

---

http/notification_rule.go
kv/notification_rule.go
testing/notification_rule.go

1. Fixed handler path for a list of all labels for a notification rule
1. Fixed filtering `NotificationRules` by `limit` and `offset`

fix(notification/rule): fixed http NotificationRule

---

Dockerfile

This pull request exposes port `6060` in the `Dockerfile` to allow the port to be accessed when the `http.debug-pprof-enabled` flag is set.

Expose debug pprof port 6060

---

CHANGELOG.md
ui/cypress/e2e/checks.test.ts
ui/src/alerting/components/CheckEOHeader.tsx
ui/src/alerting/components/CheckEOSaveButton.tsx
ui/src/alerting/components/builder/ThresholdCondition.tsx
ui/src/shared/components/dashed_button/DashedButton.tsx
ui/src/timeMachine/utils/queryBuilder.ts

Closes https://github.com/influxdata/influxdb/issues/15334
Disable saving threshold check if no threshold is selected

fix: Disable saving threshold check if no threshold selected

---

ui/src/dataExplorer/components/SaveAsVariable.tsx
ui/src/store/configureStore.ts
ui/src/types/arguments.ts
ui/src/types/stores.ts
ui/src/variables/actions/index.ts
ui/src/variables/components/CreateVariableOverlay.tsx
ui/src/variables/components/UpdateVariableOverlay.tsx
ui/src/variables/components/VariableArgumentsEditor.tsx
ui/src/variables/components/VariableForm.test.tsx
ui/src/variables/components/VariableForm.tsx
ui/src/variables/components/VariableFormContext.test.tsx
ui/src/variables/components/VariableFormContext.tsx
ui/src/variables/components/__snapshots__/VariableForm.test.tsx.snap
ui/src/variables/reducers/index.ts
ui/src/variables/selectors/index.tsx

Closes #15059
If a user re-selects the same variable type when adding a variable, no action takes place

fix(ui): ignore false change events in VariableForm

---

task/backend/executor/executor_metrics.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

We would like to be able to see some task metrics with tag's about what type of task they are. Right now the check's and notifications are different types of tasks and seeing stat's broken down in new way's will be helpful

feat(task): add type to some specific metrics in new execution.

---

ui/jest.config.js
ui/package.json
ui/tsconfig.json
ui/tsconfig.test.json

while exploring containerization of the frontend, i decided to remove the
existing environment configuration from package.json and push it into
external files in an attempt to improve the caching strategies available
for local development. the CI pipeline should be watching the lock file,
but changes to the testing environment locally shouldn't cause a rebuild
of node_modules.

chore(ui): relocate testing configuration

---

ui/src/dashboards/components/EditVEO.tsx

Closes #15233 
As the user types a new y axis label the a new view is created and triggers the `useEffect` hook.
Only execute queries if a cellID or dashboardID changes.  Could probably only do this on the mounting of the component but 🤷‍♂ .

fix(VEO): only execute queries if cellID or dashboardID change

---

CHANGELOG.md
ui/src/dashboards/components/variablesControlBar/VariableDropdown.test.tsx
ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx
ui/src/dashboards/selectors/index.ts
ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.test.tsx
ui/src/variables/mocks/index.ts
ui/src/variables/utils/hydrateVars.test.ts
ui/src/variables/utils/hydrateVars.ts

Closes #14054
Map variable types are key-value pairs. Previously, the dashboard variable dropdown showed the keys (correct behavior), but the query variable dropdown would show values. Both now show keys.
1. Click data explorer
1. Change to script editor mode
1. Click variables tab
1. Click on your map variable type
1. It should show the key, not the value.

fix: Map type Variables selector shows keys, not values

---

storage/engine.go
tsdb/tsm1/engine.go

This PR enables us to inject a limiter into a storage engine to control the concurrent number of compactions that can execute.
The use-case for this is when running multiple storage engines and wanting to limit concurrent compactions across them.

feat(storage): allow compaction limiter to be injected into engine

---

query/bridges.go

The QueryServiceProxyBridge would not check for errors properly because
it would return any error encountered when running the query as a read
error on the `io.Reader`. This made it so that the csv decoder could not
identify if the error was related to the query or if it was related to
reading. The csv decoder needed to tell the difference because an error
with reading from the `io.Reader` needs to be returned as a decoder
error while an error from the query needs to be returned as-is.
Instead of adapting the csv decoder to do that, we instead lazily
initialize the result iterator when `More()` is called and call `Peek()`
on the reader. If no bytes can be read, we assume this was an error
while executing the query and return it as such. If we are able to read
at least one byte, we decode …

fix(query): update the QueryServiceProxyBridge to check for an error properly

---

task/backend/check_task_error.go
task/backend/executor/executor_metrics.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go
task_errors.go

This PR adds a function `IsUnrecoverable` that determines if an error is not recoverable by the system (i.e. requires user intervention to fix) and deactivates the task with a log message if so. Note that this change is only implemented in the new executor system, and so it will not be in use until the new system is switched over.
This PR also generalizes the worker `finish` and metrics `LogError` methods to accept a generic error type, and catches unspecified errors as an "unknown" type.
Future work:
1. Notify the user that their task was deactivated in a more apparent way than a log message (will require notification bucket work)
1. Retry tasks that can be recovered (for example, timeout errors)
1. Record this feature to be documented (ex. in Changelog) when the new executor system is …

feat(tasks): deactivate task on unrecoverable error

---

task/backend/scheduler.go
task/backend/scheduler_metrics.go
task_errors.go

This PR updates the methods in the old scheduler to pass a Go error rather than an InfluxDB error, to match the pattern in the new executor. In this way, any errors without a specific InfluxDB error will be recorded in the metrics as "unknown" rather than lost.

fix(tasks): use go errors for scheduler metrics

---

ui/src/clientLibraries/components/ClientCSharpOverlay.tsx
ui/src/clientLibraries/components/ClientJavaOverlay.tsx
ui/src/clientLibraries/components/ClientPythonOverlay.tsx

Part of #15159 
Adding documentation for `Java`, `C#` and `Python` client:

feat(ui): Add documentation for Java, C# and Python client

---

ui/cypress/e2e/buckets.test.ts
ui/src/buckets/components/BucketCard.tsx
ui/src/buckets/components/BucketContextMenu.tsx
ui/src/buckets/components/UpdateBucketOverlay.tsx
ui/src/shared/copy/notifications.ts

Closes # [4893](https://github.com/influxdata/idpe/issues/4893)
Resource fetching for overlays is a problem that exists in many places in the UI. 
Currently a lot of our overlays do not fetch the resources they need, instead they rely on parent components to fetch resources and place in to redux state. They also do not warn user if the resource they need can not be found in redux state. 
I'm suggesting this PR as a general pattern for data fetching and errors in overlays. 
Would love to hear concerns / feedback

fix: Place resource fetch logic in overlay

---

client/v2/client.go

This is a cherry pick of https://github.com/influxdata/influxdb/pull/15385 onto the 1.7 branch

fix(http): honor insecure-skip-very even if custom tls config is specified

---

ui/.dockerignore
ui/assets/index.html
ui/src/utils/env.test.ts
ui/src/utils/env.ts
ui/webpack.common.ts
ui/webpack.prod.ts

hopefully this commit doesnt do anything for everyone else, but it opens up the ability to
change the static folder of the project through the environment variable
STATIC_FOLDER so that we can cache static files and not cache the index
file (allowing more passive deployment strategies), and allows the user
to change the base path of the project with the BASE_PATH variable,
opening up the ability to run an instance behind an nginx proxy,
though that change is pending an update to the `@influxdata/oats` package
before we can turn it on

chore(ui): allow deployment configuration

---

ui/jest.config.js

We need to chart how our testing push is doing, so lets expose it! This has an HTML reporter for consumption by people looking for testing blindspots, and a Cobertura reporter for showing the aggregate nicely in jenkins / CI tools.

chore(ui): adding a coverage reporter to see how we are doing

---

http/swagger.yml
notification/endpoint/endpoint_test.go
notification/endpoint/pagerduty.go

Partially https://github.com/influxdata/influxdb/issues/15104
the api and swagger changes for the pagerduty clientURL to be optional

fix(notification/endpoint): pagerduty clientURL should be optional

---

ui/src/shared/constants/fluxFunctions.ts

Some of the Flux math functions were incorrectly named. This update corrects those and points to the correct full documentation links.

fix(flux): udpated incorrectly named flux functions

---

CHANGELOG.md
ui/cypress/e2e/collectors.test.ts
ui/src/telegrafs/components/Collectors.tsx

Closes #15246 
This PR fixes the search funcitonality in the ui/telegraf input field.
The problem originated by an invalid prop filter, where the frontend was expecting results to be filtered based on a label array property, rather than a string.
Solution
Updated the frontend filter functionality to search for the filter parameter based on the correct property - `telegrafconfig.name`

fix(ui/telegraf): filter functionality

---

ui/src/clientLibraries/components/ClientCSharpOverlay.tsx
ui/src/clientLibraries/components/ClientGoOverlay.tsx
ui/src/clientLibraries/components/ClientJSOverlay.tsx
ui/src/clientLibraries/components/ClientJavaOverlay.tsx
ui/src/clientLibraries/components/ClientLibraries.tsx
ui/src/clientLibraries/components/ClientPythonOverlay.tsx
ui/src/clientLibraries/constants/index.ts
ui/src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx
ui/src/dataLoaders/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap
ui/src/index.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/settings/components/LoadDataNavigation.tsx

Closes https://github.com/influxdata/influxdb/issues/15159

feat(clientLibs): Fix up client libs page

---

.gitignore
CHANGELOG.md
ui/package.json
ui/src/client/index.ts
ui/yarn.lock

Closes #15312
- Adds a custom response handler for the new api routes created by oats that immediately logs the user out and returns them to `/signin` when a 403 is returned from the API
- upgrades to oats 0.5.0
* If you'd like to see which routes use the new api and go through this handler, you can add a log statement [here](https://github.com/influxdata/influxdb/blob/bs_bugfix_403_logout/ui/src/client/index.ts#L4)
* To force 403s from the API (only works on the api calls that use `client/index`):
* change [authentication_middleware.go](https://github.com/influxdata/influxdb/blob/bs_bugfix_403_logout/http/authentication_middleware.go#L110) to something [like this](https://gist.github.com/hoorayimhelping/c138a0f393b3face916637b3db29ffe2) (change the id to match yours, which can be found …

feat(ui): add 403 signout handler to new api requests

---

task/backend/check_task_error.go
task/backend/executor/executor_metrics.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

This PR comments out the deactivation logic for unrecoverable errors, to be restored when a user notification system is put in place to alert users when they have a task that is going to be deactivated.
This PR also adds a new metric for the new executor called "Unrecoverable Counter" which will allow engineers to see in one place all of the errors for which we would like to deactivate the offending tasks.
The error message "filesystem service uninitialized" is also added to the list of unrecoverable errors.

fix(tasks): replace deactivation of unrecoverable errors with metric

---

ui/scripts/upload_sourcemap.sh

Closes #15402
[Honeybadger's Docs](https://app.honeybadger.io/projects/61122/sourcemaps#uploading-your-files) mention linking `<additional source files>` that are referenced from this sourcemap.
I ran this script locally at `10/16/2019 21:20:39 UTC` using the correct values, and [it seems to have worked correctly](https://app.honeybadger.io/projects/61122/source_map_uploads)
This PR hooks that up so that it's called on deploy.
**Note:** I never actually confirmed that this mapped errors correctly. More than happy to wait on deploying this until that confirmation.

chore(ui): add giraffe and clockface sourcemaps to honeybadger config

---

CHANGELOG.md
http/authentication_middleware.go

This is to gain some small visibility into the reason behind a failed authorization.
Now when a user receives an unauthorized error, an info level log message is written to STDOUT containing the error which produced it.

chore(gateway): log error on unauthorized attempt

---

authorizer/task_test.go
cmd/influx/task.go
cmd/influxd/launcher/tasks_test.go
http/task_service_test.go
kv/task.go
task.go
task/backend/analytical_storage.go
task/backend/analytical_storage_test.go
task/backend/coordinator/task_coordinator_test.go
task/backend/executor/limits.go
task/backend/executor/limits_test.go
task/backend/executor/task_executor.go
task/backend/middleware/middleware_test.go
task/backend/run_recorder.go
task/backend/scheduler.go
task/backend/scheduler_test.go
task/mock/task_control_service.go
task/servicetest/servicetest.go
task_test.go

Closes #14523
This PR converts the the type of the `StartedAt`, `ScheduledFor`, `FinishedAt`, and `RequestedAt` properties of the Task Run struct from strings to Go time.Time objects. This will reduce the complexity of having to parse/format these timestamps throughout the internal task systems. 
These properties will still be stored in the database as strings, for backwards compatibility.

refactor(tasks): use Go time objects for timestamps on task Runs

---

CHANGELOG.md
ui/src/me/components/UserPageHeader.tsx
ui/src/pageLayout/components/RenamablePageTitle.scss
ui/src/pageLayout/components/RenamablePageTitle.tsx
ui/src/shared/components/PageTitleWithOrg.tsx

Closes #15494 
This PR aims to make the page headers more compact by splitting the text into 2 lines. On most pages the subtitle is the current org name, and on the home page there's an explainer line for the random language greeting.
This should help with real estate issues on dashboard headers (long org names + long dashboard names exacerbate the issue)

refactor(ui): redesign all page headers to make use of PageSubTitle

---

predicate/parser.go
predicate/parser_test.go

fix tag values parsing: hex, negative number, time duration

fix(predicate): add some other values

---

ui/cypress/e2e/labels.test.ts
ui/webpack.dev.ts

Currently the parsing for this is so slow as to make it useless.  Will re-enable when parsing speed is improved.

build(webpack): remove eslint from ForkTsChecker plugin

---

CHANGELOG.md
http/middleware.go
http/org_service.go
http/swagger.yml

fix(http): /api/v2/orgs/:id/owners|members to 404

---

cmd/influxd/launcher/launcher.go
vault/secret.go

the flags have to match the flags with the exception of beign lower case and
all `_` be changed to `-` in the flag. This is a result of using the cobra
flag to env var mapping with the `-` replaced to `_`.

fix(vault): rename flags to match env vars and add missing token flag

---

CHANGELOG.md
ui/cypress/e2e/buckets.test.ts
ui/cypress/e2e/collectors.test.ts
ui/cypress/e2e/labels.test.ts
ui/cypress/support/commands.ts
ui/cypress/tsconfig.json
ui/src/telegrafs/components/CollectorCard.tsx
ui/src/telegrafs/components/CollectorList.tsx
ui/src/telegrafs/components/__snapshots__/Collectors.test.tsx.snap

Closes #15247
UI/Telegrafs should be sortable based on bucket name
Modified the sortKey to accurately reflect the bucket's location in the data, thereby integrating the existing sort functionality.

fix(ui/collectorList-telegraf): sort telegrafs based on buckets

---

kv/bucket.go

This code is no longer necessary, as we now enforce this behavior for http-originating bucket creations here: https://github.com/influxdata/influxdb/blob/master/http/bucket_service.go#L377
Without this change, all system buckets that are created or updated will have the incorrect type.

fix(kv): allow system buckets to be created

---

ui/cypress/e2e/explorer.test.ts
ui/src/timeMachine/components/QueriesSwitcher.scss
ui/src/timeMachine/components/QueriesSwitcher.tsx
ui/src/timeMachine/utils/queryBuilder.ts

Closes #15488 
Replace the overlay confirmation interaction with a `ConfirmationButton`

refactor(ui): convert confirmation overlay to confirmation button

---

query/stdlib/influxdata/influxdb/rules.go
query/stdlib/influxdata/influxdb/rules_test.go

When `exists` was used in conjunction with any other pushed down
expression, the `exists` was not rewritten properly because the rewrite
did not descend into logical expressions.
This is now fixed so those expressions will be rewritten correctly. This
affected the following form:
filter(fn: (r) => r._measurement == "cpu" and exists r.host)
It did not affect the following:
filter(fn: (r) => r._measurement == "cpu")
|> filter(fn: (r) => exists r.host)

fix(query/stdlib): fix rewritten pushable expressions when a logical expression is present

---

semaphore.go
storage/engine.go
tsdb/tsm1/engine.go

This feature adds the concept of a semaphore to the `tsm1.Engine`, which can be used to limit full compactions. By default this feature is disabled; the full compaction behaviour does
not change. 
When this feature is enabled, compactions can be limited across multiple storage engines running in multiple processes through an implementation of an `influxdb.Semaphore`.
Currently the `Semaphore` interface defines non-blocking acquisition methods as that's what's used in the `tsm1.Engine`. We could extend the interface in the future to add blocking methods.

feat: add full compaction semaphore abstraction

---

tsdb/series_partition.go

Closes #
If `SeriesIndex.Recover` fails, the most recent series cannot be queried because the WAL segment has not yet been loaded into the cache.
Therefore, if the `SeriesIndex.Recover` fails, the `SeriesPartition` should not open successfully.

fix(tsdb): add missing err in SeriesPartition.Open

---

ui/package.json
ui/yarn.lock

The version of react-redux we use has a security vulnerability that is
considered critical severity. https://github.com/influxdata/influxdb/network/alert/ui/yarn.lock/lodash-es/open

chore(ui): update to latest react-redux

---

CHANGELOG.md
ui/jest.config.js
ui/mocks/dummyData.ts
ui/src/dashboards/actions/views.test.ts
ui/src/dashboards/actions/views.ts

Closes #15239 
When the view editor overlay is loaded, `getViewForTimeMachine` is called. `getViewForTimeMachine` checks the store for the relevant `view` based on the `viewID` passed in to the function. Previously (the buggy state), `getViewForTimeMachine` dispatched a `SET_VIEW` action with a `null` view, even if `view` already existed in the store. Now, it only dispatches a null view if there is no view.
e2e tests are waiting on https://github.com/influxdata/influxdb/pull/15538 since the changes Deniz is making are necessary for me to write tests on this component.

fix(ui): exiting out of a configure cell leaves cell content intact

---

CHANGELOG.md
ui/cypress/e2e/checks.test.ts
ui/src/alerting/actions/checks.ts

Closes #15554 
Newly created checks without labels were not rendering on the checks list.
Steps for reproduction can be found on #15554 
Ensure that check labels exist before mapping the values. Added testing to ensure that the checks list page should render a check once it has been created

fix(ui/checks): checks render once they've been created

---

CHANGELOG.md
ui/src/shared/components/BoxTooltip.tsx

Closes #15518 
Sometimes hovering over the EventMarker in the alerting checks box would trigger the `BoxTooltip` to periodically render to the right of the mouse rather than the left. Since the div that was being rendered would render over the previous div, the previous div's `onMouseOut` event would be triggered, thereby closing the div that had just been rendered. Once the `div` for the `BoxTooltip` was gone, the mouse was left in the same position, triggering the `onMouseOver` event. This cycle would continue until the mouse was moved.
Once the problem was clear, I tried to fix the underlying issue (that the `BoxTooltip` was rendering in the incorrect area). Unfortunately, after quite a few attempts, I was unable to correctly render the `BoxTooltip` consistently enough based on the …

fix(ui/boxtooltip): Preventing constant toggle b/w onMouseOver and onMouseOut on EventMarker

---

ui/webpack.dev.ts

This allows you to pass a root url into the dev server, for when all else fails and you need to hard code some paths. currently, this is used by the hot module replacement mechanism within webpack development server to define the base path of the websocket server from a client's perspective. now we can hide a dev server, running at `http://localhost:9999`, behind the url `https://secure.local:8000`, and HMR should still work. Check the changes in monitor-ci for configuring the ingress controller to pass the correct headers.

fix(ui): allow hmr feature with proxied ingress controllers

---

tsdb/engine/tsm1/file_store.go

Fixes #14107
Backports #15608 
fix(storage): Renaming corrupt data files fails

fix(storage): Renaming corrupt data files fails

---

CHANGELOG.md
http/task_service.go

Closes #15177 
Changes success status code for task runs endpoint (`/api/v2/tasks/:id/runs`) from 200 to 201.
Note that the `swagger.yml` file already documented a 201 status for this endpoint, so this PR rectifies that discrepancy.

fix(api): change task ID runs success status from 200 to 201

---

ui/package.json

Closes #15421
all references are removed from this library. if tests pass, it should be fine to delete, cause that's why we have tests.

chore(ui): remove react tooltip

---

ui/cypress/e2e/explorer.test.ts
ui/src/shared/components/TimeRangeDropdown.tsx
ui/src/shared/components/dateRangePicker/DateRangePicker.tsx
ui/src/timeMachine/components/Queries.tsx

Closes #15420 
The current Data Explorer DateRangePicker was set in a modal that would render to a fixed location on the screen (middle)
Refactored the way the component was being rendered so that it was relative to the dropdown and within a popover

fix(ui/timerangedropdown): refactored the daterangepicker implementation from modal to popover

---

CHANGELOG.md
ui/cypress/e2e/labels.test.ts
ui/cypress/e2e/onboarding.test.ts
ui/package.json
ui/src/dataLoaders/components/lineProtocolWizard/configure/LineProtocolTabs.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/__snapshots__/LineProtocolTabs.test.tsx.snap
ui/src/me/components/account/__snapshots__/Settings.test.tsx.snap
ui/src/variables/components/__snapshots__/VariableForm.test.tsx.snap
ui/webpack.common.ts
ui/yarn.lock

Closes #15499
Apply [clockface 1.0.3](https://github.com/influxdata/clockface/releases/tag/v1.0.3) to fix TextAreas.

fix(ui): Make TextAreas the proper size

---

ui/src/alerting/components/notifications/StatusLevels.tsx
ui/src/alerting/components/notifications/utils/index.ts

Closes #15155 
This adds back the ability for a notification to fire if a status changes from `OK` to `CRIT` etc.  
Would love to add tests but rule creation is waiting for https://github.com/influxdata/influxdb/issues/14799 until we can start adding some e2e's.

feat: add status changes back to rules

---

CHANGELOG.md
http/swagger.yml
kv/task.go
task.go
task/servicetest/servicetest.go

Closes #15153 
This PR exposes `lastRunStatus` and `lastRunError` in the task API object and records corresponding fields on the backend task model. If `lastRunStatus` is `"failed"`, `lastRunError` is recorded as the last message in the task run log. Otherwise, `lastRunError` is cleared. Both new fields are excluded from the response if empty.
The [task update logic](https://github.com/influxdata/influxdb/pull/15650/files#diff-305c59262c657f72f86a5054a59d462eR745) is augmented to allow the status and error to be updated, and the [task run finish logic](https://github.com/influxdata/influxdb/pull/15650/files#diff-305c59262c657f72f86a5054a59d462eR1580) takes advantage of this new capability. [Tests](https://github.com/influxdata/influxdb/pull/15650/files#diff-bf1d0d8dc888d493a547519debfe320d …

feat(tasks): expose lastRunStatus and lastRunError in task API

---

ui/src/shared/constants/fluxFunctions.ts

Depends on #15616 
Added `prometheus.histogramQuatile()` to `fluxFunctions.ts`.

Updated Flux functions list for flux 0.51.0

---

task/options/options.go
ui/cypress/e2e/tasks.test.ts

Closes #15583 
Use `EvalOptions` instead of `EvalAST` to avoid missing dependencies in the rest of the AST when we only need the options.
This change removes most of the flux script pre-checking we do on task creation. As a result, a UI test is skipped until more robust static pre-checking is available after the Flux team's Algorithm W work is completed. Relevant [Flux issue](https://github.com/influxdata/flux/issues/2085).

fix(flux): use flux.EvalOptions over problematic flux.EvalAST

---

cmd/influx/delete.go

Closes https://github.com/influxdata/influxdb/issues/15676
Remove the duplicate usage, when issue wrong influx delete command.
Manually tested

fix(cmd/influx): remove dup usage

---

task/options/options.go
ui/cypress/e2e/tasks.test.ts

Reverts influxdata/influxdb#15665
Fixes #15688 
Due the task validation regression introduced by this PR, we've opted to revert it for the time being.

Revert "fix(flux): use flux.EvalOptions over problematic flux.EvalAST"

---

ui/cypress/e2e/tasks.test.ts
ui/src/tasks/components/TaskHeader.tsx

Closes #15552 
Task names don't populate the form correctly when toggling between tasks
Since this bug could not be reproduced, I added tests to ensure that the correct names are displaying when toggling between tasks using the navbar, the cancel button, and the save button
For more info, please see:

feat(tests): added tests to validate bug unreproducible

---

ui/src/timeMachine/components/view_options/TableOptions.tsx

Closes #15569
This replaces https://github.com/influxdata/influxdb/pull/15655

fix(ui): add filter to fieldOptions when dragging a column

---

task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

Ensure new scheduler threads auth on context when calling FinishRun.
FinishRun will result in a call to the API to write a point which contains the run. This ensures the executor passes the authentication is has down through the context.Context.

fix(tasks): thread auth on context when calling FinishRun

---

models/points.go
models/points_test.go

This PR enables `uint64` support in InfluxDB. This means that you can write unsigned integers into the database. To differentiate between unsigned integer values and signed integer values, use the `u` suffix. 
Example:
```
influx write -o edd -b edd  "cpu,region=west balance=-232i,space=23432u
```
Where `balance` is a regular signed integer, and `space` is an unsigned integer.
Within the TSM storage engine both signed and unsigned integers are compressed in the same way. You cannot mix signed and unsigned integers within the same series, e.g., you **cannot** do this:
```
influx write -o edd -b edd  "cpu,region=west space=23432u
influx write -o edd -b edd  "cpu,region=west space=100i
```
The approach here is temporary. We should make this change permanent by removing all the code that …

fix: enable uint64 support

---

ui/cypress/e2e/collectors.test.ts
ui/cypress/e2e/tasks.test.ts

Makes collector e2e test lest flaky

test(ui): rejigger the collector tests to be less flaky

---

CHANGELOG.md
ui/cypress/e2e/collectors.test.ts
ui/src/clockface/components/inputs/multipleInput/MultipleInput.tsx
ui/src/dataLoaders/components/collectorsWizard/configure/PluginConfigForm.tsx
ui/src/dataLoaders/components/configureStep/streaming/ConfigFieldSwitcher.test.tsx

Closes #15500
This wasn't actually a bug, but a confusing interaction. This uri array component expects users to hit enter to add an item to the list (good luck, mobile / tablet users). This adds a button to help out that interaction. It also changes the way the form is handled so that it doesn't fire an empty event, causing an error.
The bug was reported for nginx, but the confusing interaction also appeared in redis, so this fix has been applied there as well. e2e tests were added to both.

feat(ui): tweak telegraf nginx and redis flows

---

bolt/kv.go
inmem/kv.go
kv/store.go
kv/task.go
kv/task_private_test.go
mock/kv.go
task/servicetest/servicetest.go
testing/kv.go

Implementations of the `kv.Bucket#Cursor` API may use the hints to instruct the access or read behavior to the underlying key/value store.
The `findAllTasks` function was also fixed to ensure that paging works as expected when using a name filter. Tests were added to verify this behavior.
Redundant error checks were also removed.

feat(kv): Cursor API accepts hints for improving performance

---

pkger/models.go
pkger/service.go
pkger/service_test.go

little cleanup for pkger. this makes any bucket/label resource skipped if it imposes no updates to an existing resource. if it is new, still runs. It is going to change existing state on a resource, it runs. If it is identical in every field the pkger exposes, then we skip it.

feat(pkger): update pkg application to skip resources that impose no changes

---

pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/testdata/dashboard_single_stat_plus_line.json
pkger/testdata/dashboard_single_stat_plus_line.yml

adds support for single stat plus line views to influx packages

feat(pkger): add single stat plus line view support to pkger

---

ui/package.json
ui/webpack.dev.ts
ui/webpack.prod.ts
ui/webpack.vendor.ts
ui/yarn.lock

this adds the ability for developers to compare bundle optimizations. when analyzing in develop mode (read: `yarn start`), assets are uncompressed and can be viewed at `http://localhost:9998`. When in production mode (read: `yarn build`), the analysis can be reached by opening `build/bundle-report.html`.
as a point of order, remember that file size isn't as important from a network resource perspective, and that many small files is fine (production will start running http2 soon to remove much of the overhead of asset handshakes), but that large files slow down the time to first render + interaction by increasing time spent parsing the file (read: its an interpreted language). Best case scenario is to send a small file with only enough code to represent the current view, and to start …

feat(ui): adding bundle analyzer for prod and dev

---

task/backend/executor/task_executor.go

When using a run duration we need a start time that is valid to
obtain a accurate run duration delta

fix(task): Set a valid start time for run duration

---

ui/cypress/e2e/buckets.test.ts
ui/src/buckets/components/BucketCard.tsx
ui/src/buckets/components/BucketList.tsx
ui/src/buckets/components/BucketsTab.tsx
ui/yarn.lock

Zs sortbyseconds #14923

---

ui/src/pageLayout/containers/Nav.tsx
ui/src/pageLayout/utils/index.test.ts
ui/src/pageLayout/utils/index.ts
ui/src/shared/constants/index.ts

Closes https://github.com/influxdata/influxdb/issues/15734

fix(ui): update util to allow matching the homepage as the active icon

---

CHANGELOG.md
tsdb/tsm1/array_cursor_iterator.go
tsdb/tsm1/engine_cursor_test.go

Closes https://github.com/influxdata/influxdb/issues/15732
1. Adds a failing test which demonstrates the incorrect reporting of stats from the `arrayCursorIterator.Stats()` method.
2. Updates `arrayCursorIterator.Stats()` to accumulate all the cursor field stats values into a single response.
@stuartcarnie showed me that the `builldXArrayCursor` methods actually retain previously read stats and accumlate them on calls to `reset` which is how all read stats are accumulated in the end.

fix(storage): array cursor iterator should return stats of all observed cursors

---

ui/src/shared/actions/predicates.ts
ui/src/shared/components/DeleteDataForm/TimeRangeDropdown.tsx
ui/src/shared/reducers/predicates.ts

Closes #15716
1. Selecting a timerange would trigger an error due to duplication action naming
2. Timerange wasn't in a popover
3. Selecting a timerange wouldn't close the picker once it had been applied
1. Renamed the action that was setting the timerange to avoid triggering two different actions with the same name
2. Refactored the timerange to be in a popover
3. Created a helper function to close the popover when a timerange had been applied

fix(DWP-date): date selector refactored to popover and fixed reducer error

---

ui/src/shared/components/DeleteDataForm/FilterRow.tsx
ui/src/shared/utils/featureFlag.ts

Closes #15715
Enabling the `deleteWithPredicate` feature flag was causing both equality filters to be displayed in the app
Renaming the `inequality` feature flag and setting the new flags in the `featureFlag` utility file so that it remains a separate piece of functionality

fix(DWP-not): added new featureflag for DWP inequality filter

---

CHANGELOG.md
ui/src/shared/actions/predicates.ts
ui/src/shared/reducers/predicates.test.ts
ui/src/shared/reducers/predicates.ts

Closes #15717 
State wouldn't reset after a un/successful delete with predicate submission
Created a new action and case to dispatch after the API call resolve / rejects

fix(DWP): reset redux state when DWP resolves or rejects

---

ui/src/dashboards/components/variablesControlBar/VariablesControlBar.scss
ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx
ui/src/shared/components/cells/Cell.scss
ui/src/shared/components/tables/TableGraphs.scss
ui/src/shared/components/tables/TableSidebar.tsx
ui/src/timeMachine/components/RawFluxDataTable.scss
ui/src/timeMachine/components/RawFluxDataTable.tsx

- Modify table cells and raw data table to match "dark cell" aesthetic
- Modify variables control bar to match "dark cell" aesthetic
- Add link to docs in empty variables control bar
- Replace `FancyScrollbars` with `DapperScrollbars` in table cell sidebar

refactor(ui): update appearance of tables

---

CHANGELOG.md
cmd/influx/query.go
cmd/influx/repl.go

fix(cmd/influx): fix long startup when running `influx help` and other similar commands. 

---

query/promql/internal/promqltests/go.mod
query/promql/internal/promqltests/go.sum

We need to start updating Flux in both the main module and in `promqltests`.  This PR just updates the Flux version for the latter.

build(query): update promqltests to latest Flux version

---

CHANGELOG.md
ui/cypress/e2e/buckets.test.ts
ui/cypress/e2e/explorer.test.ts
ui/src/buckets/components/BucketCard.tsx
ui/src/buckets/selectors/index.test.ts
ui/src/buckets/selectors/index.ts
ui/src/dataExplorer/components/DeleteDataButton.tsx
ui/src/shared/components/DeleteDataForm/BucketsDropdown.tsx

Closes #15719
Closes #15720 
Delete with predicate dropdown bucket list was not alphabetized 
Alphabetized dropdown bucket list for delete with predicate, wrote in edge case for default system buckets and added e2e tests

fix(bucket-list): wrapped DWP in featureFlag and sorted bucket list

---

predicate/parser.go
predicate/parser_test.go
ui/src/buckets/selectors/index.test.ts

Closes #15643 
predicate/parser NotEqual case would `fallthrough` to the default error whenever requests with a `!=` were being made
Updated the predicate/parsers `parseTagRuleNode` NEQ case to handle queries where the equality filter is NotEqual

fix(predicate/parser): updated case statement for NotEqual on deleteWithPredicate API

---

cmd/influx/pkg.go
cmd/influxd/launcher/launcher.go
http/swagger.yml
pkger/models.go
pkger/models_test.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go
pkger/testdata/variables.json
pkger/testdata/variables.yml
pkger/testdata/variables_associates_label.yml
variable.go

Only issue here is the #15758 issue is waiting on some feedback for a name for hte service endpoints. This is ready to go once that gets going. PR is compared against teh http server branch, which is up to date as of writing this. Once merged, will jigger this to pint at master.
PR isn't as big as the LOCs indicate. Found a nice abstraction for a testrunner on the parser side, ended up moving some bits around there to take advantage. Thanks for your patience 😬 
Dry run:
Application Summary:

feat(pkger): add support for variable resource to pkger

---

http/swagger.yml
predicate/predicate_test.go
predicate/tag_rule.go
ui/src/buckets/selectors/index.test.ts
ui/src/buckets/selectors/index.ts
ui/src/shared/components/DeleteDataForm/FilterRow.tsx
ui/src/shared/utils/featureFlag.ts

Closes #15798 
This PR deals with two separate problems:
1. The issue noted above was the result of inconsistent behavior in the test.
2. The API still couldn't handle `!=` deleteWithPredicate conditions
1. Refactored the `getSortedBucketNames` to break the data into two separate arrays that are sorted, concatenated and mapped.
2. Connected the `datatypes.ComparisonNotEqual` to the `influxdb.NotEqual` case in `predicate/tag_rule`

fix(flakey-test): refactored getSortedBucketNames for more consistency and predictability. Finished DWP API functionality

---

CHANGELOG.md
task/options/flux_deps.go
task/options/options.go
ui/cypress/e2e/tasks.test.ts

Closes #15583 
Wire fake flux dependencies to allow use of `http.post`, etc. in tasks.

fix(tasks): fake flux deps

---

http/check_service.go
http/check_test.go
http/notification_rule.go
http/notification_rule_test.go
http/swagger.yml

Closes #15553 
API response for `checks` and `notificationRules` was not returning a reference to the query in the response: `/api/v2/notificationRules/ID/query`
Updated `check_service` & `notification_rule` to return a reference to the `/query`  in the response links. Updated tests and swagger.yml to reflect these changes

fix(http/links): Added query links to checks and notificationRules response, updated swagger.yml

---

dashboard.go
http/pkger_http_server.go
http/pkger_http_server_test.go
http/swagger.yml
pkger/clone_resource.go
pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go

This is the start of exporting existing resources in the form of a package. 
no associations included at this time. It will only include the resources that are described in the API call. The next body of work will add all associations with labels to every entity that is mapped.
note about this work. I ended up coupling the dec/enc fields via constants. I am using some types directly as json/yaml for the encoding, but most are using the Resource type. This buys us more extensible encoding/decoding support. We can add jsonnet/toml/yada yada with a small LoC change. Adding specific Decode/Encode to each type could make this work with less LoCs, but there are quite a few gotchas in those. Not to mention you'll have to create new methods for a new enc/dec if they don't' follow the std lib's …

feat(pkger): add export functonality to pkger for existing buckets/label/dash/vars

---

http/pkger_http_server.go
pkger/clone_resource.go
pkger/models.go
pkger/parser.go
pkger/service.go
pkger/service_test.go

this PR adds associations for resources that are being exported and adds those to the new package that is created. 
Closes #15764

feat(pkger): add support for exporting resource associations

---

ui/package.json
ui/src/me/components/GettingStarted.scss
ui/webpack.common.ts
ui/webpack.dev.ts
ui/webpack.prod.ts
ui/yarn.lock

Closes #15842
Closes influxdata/clockface#362
we saw some weirdness where css inclusion order was changed when building in production mode. this was the result of some drift between our dev and production environments (specifically the use of MiniCssExtract). I went ahead and dragged as much into the common webpack as made sense to hopefully make our build process feel a bit more deterministic.
the second commit is me fixing the error that used to only show up in production, but now should show up everywhere (cause same same, but different)

fix(ui): make a more deterministic build

---

ui/cypress/e2e/collectors.test.ts
ui/cypress/support/commands.ts
ui/src/telegrafs/components/Collectors.tsx

Zs filtering telegraph input #15601

---

.circleci/config.yml

Closes #
Adds a selenium_accept job to circleci and adds it to the nightly workflow.

test: add selenium acceptance tests to nightly build - Bonitoo/selenium nightly

---

ui/cypress/e2e/explorer.test.ts
ui/src/timeMachine/components/view_options/BinCountInput.tsx

Closes https://github.com/influxdata/influxdb/issues/15841
In Histograms, let the user delete all input in Custom bin sizes to input new numbers, and make Auto bin size mode less aggressive.

fix(ui): Allow easier manipulation of custom bin sizes in Histograms

---

CHANGELOG.md
ui/src/index.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/settings/components/SettingsNavigation.tsx

Closes influxdata/idpe#5244
Hide Members tabs and navigation options in Cloud environments.
While logged in, change [this line](https://github.com/influxdata/influxdb/blob/master/ui/src/shared/constants/index.ts#L56) to `true`. It should change your environment to cloud and change the navigation.

fix(ui): don't show members information in cloud

---

ui/cypress/e2e/dashboardsIndex.test.ts
ui/src/dashboards/components/dashboard_index/Table.tsx

Closes https://github.com/influxdata/influxdb/issues/15656
When dashboards length is 0, props.children evaluates to null rather than false, so that clockface will render the default state.

fix(ui): Show empty dashboards state

---

ui/src/authorizations/components/BucketsSelector.tsx

Closes https://github.com/influxdata/influxdb/issues/15869
Updates the text including the preposition, ie "read from", "write to", etc.

fix(ui): Use correct text when generating token

---

tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go

Closes #15876 
Makes `tsm1.Engine.Digest()` safe for concurrent calls.

fix(tsm1): make digest safe for concurrent use

---

crud_log.go
duration.go
http/task_service.go
kv/task.go
kv/task_test.go
task.go
task/backend/coordinator.go
task/backend/coordinator/task_coordinator.go
task/backend/coordinator/task_coordinator_test.go
task/backend/coordinator_test.go
task/backend/middleware/check_middleware.go
task/backend/middleware/check_middleware_test.go
task/backend/middleware/middleware.go
task/backend/middleware/middleware_test.go
task/backend/middleware/notification_middleware.go
task/backend/middleware/notification_middleware_test.go
task/backend/schedulable_task_service_test.go
task/backend/scheduler_test.go
task/mock/task_control_service.go
task/servicetest/servicetest.go

Closes #14522
This PR updates the internal Task struct to use Go time.Time and time.Duration objects for time values instead of timestamp strings.
Continuation of refactoring work started in https://github.com/influxdata/influxdb/pull/15406

refactor(tasks): use go time in task struct

---

ui/src/alerting/components/CheckAlertingButton.tsx
ui/src/alerting/components/builder/CheckMetaCard.tsx

Closes https://github.com/influxdata/influxdb/issues/15108
Changes:
1. Define Query
2. Configure Check
Name editing removed in the card (bottom left).
Looks like this:

fix(ui): update wording and remove name editing in checks page

---

tsdb/tsi1/file_set.go
tsdb/tsi1/index_file.go
tsdb/tsi1/index_file_test.go
tsdb/tsi1/log_file.go
tsdb/tsi1/partition.go

Fixes #15859.
This PR fixes a defect in the TSI index where a filter using the negated equality (`!=`) operator could result in no matching series being returned for any series stored within the `IndexFile` portions of the index.
The root cause of this was due to missing legacy-handling code in the index for this particular iterator.
This defect was particularly troublesome to track down because there is nothing fundamentally wrong with the TSI index data, only how that data is read in certain circumstances. Around `1.6.1` we added some improvements to the TSI index by persisting sets of series ids as serialised roaring bitmaps. To handle existing TSI indexes we needed to ensure we could deserialise the new bitmaps collections and the legacy collections (variable length encoded blocks of …

fix(tsi1): address index defect when using negated equality operator

---

http/pkger_http_server.go
http/pkger_http_server_test.go
http/pkger_parse_err_test.go
http/swagger.yml
pkger/parser.go
pkger/parser_test.go
pkger/service.go

this change is to provide a more robust response when encountering a validation error during the application of a package. The errors returned enables the API consumer to the errors and have pin point accuracy of where in their package things went amuck, regardless of it being JSON/YML/gzipped/etc. 
<details>
<summary>example of updated API response for validation errors, a 422 is returned with the following body</summary>
```json
{
"diff": ... same,
"summary": ... same,
"errors": [
{
"kind": "dashboard",
"fields": [
"resources",
"charts",
"kind"
],
"idxs": [
3,
10,
null
],
"reason": "invalid chart kind provided: "
},
{
"kind": "dashboard",
"fields": [
"resources",
"charts",
"height"
],
"idxs": [
3,
11,
null
],
"reason": "must be greater than 0"
},
{
"kind": "dashboard",
"fields": [ …
```

feat(pkger): extend apply HTTP API to return parse err with 422 resp

---

ui/src/shared/components/tables/TableGraph.tsx

The fix for getting sorting to work
Closes #15888 

fix(ui): arrows in table

---

CHANGELOG.md
cmd/influx/authorization.go
cmd/influx/bucket.go
cmd/influx/delete.go
cmd/influx/main.go
cmd/influx/organization.go
cmd/influx/pkg.go
cmd/influx/query.go
cmd/influx/repl.go
cmd/influx/setup.go
cmd/influx/task.go
cmd/influx/user.go
cmd/influx/user_resource_mapping.go
cmd/influx/write.go

Closes #15805 
Adds support for insecure skip verify flag in `influx` cli.

feat: add support for insecure skip verify on cli http clients

---

pkger/clone_resource.go
pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/service_test.go
pkger/testdata/dashboard_heatmap.json
pkger/testdata/dashboard_heatmap.yml
pkger/testdata/dashboard_scatter.json
pkger/testdata/dashboard_scatter.yml

Closes #
- Adds an export for the scatter and heatmap charts
- Also adds 2 additional pkger fields for the heatmap, and scatter charts (`xDomain`, `yDomain`). At first, didn't realized these existed, but you can create these fields when in the chronograf UI. Decided to add these to make sure we're backwards compatible.

feat(pkger): exports scatter and heatmap charts

---

tsdb/tsm1/predicate.go
tsdb/tsm1/predicate_test.go

Fixes #15916.
If a predicate was passed in with multiple key/value matches for the
same tag key, then the value index would be incorrect. This ensures that
each tag key can only be added to the location map once.

fix(storage): fixes panic when building predicates

---

ui/src/alerting/components/builder/AlertBuilder.scss

Closes #15831
CSS textarea wasn't being set correctly
Updated the scss file to correctly set the textarea

fix(ui/alertbuilder): updated scss file to accurately set textarea height

---

cmd/influx/pkg.go

drops unneccessary shorthand for table borders that was causing panic (should be 1 char, but had 2). In hindsight, a shorthand here doesn't do us much good 🤷‍♂

fix(influx): bad shorthand var for pkg command

---

ui/src/external/monaco.fluxTheme.ts
ui/src/shared/components/FluxMonacoEditor.scss
ui/src/shared/components/FluxMonacoEditor.tsx
ui/src/style/fonts/fonts.scss
ui/src/style/fonts/icon-font.scss
ui/tsconfig.test.json

Closes #15637
I promise that i'm not a bad programmer and that this is the only way to style monaco. it feels real bad to put color definitions in a react component, some sass files, and a template function, but i swear it forced me to.

feat(ui): add some color to monaco

---

ui/src/shared/components/LatestValueTransform.tsx
ui/src/shared/components/ViewSwitcher.tsx
ui/src/shared/utils/formatStatValue.ts
ui/src/shared/utils/latestValues.test.ts
ui/src/shared/utils/latestValues.ts
ui/src/templates/api/index.ts

Zs singlestatstring #15314

---

ui/src/shared/selectors/getResourcesStatus.ts

Closes #15865
getResourceStatus threw an error: `Cannot read property 'status' of undefined`
Added helper function before checking to see whether the resource is defined in the state before checking the status. Also added in a default error for when the resource is undefined on the state

fix(getResourcesStatus): added checks for status prop in getResourceStatus

---

cmd/influx/bucket.go

ref #15828 
This fixes a mismatch between tabwriter keys introduced by 9d44ac3635b2800c1dd8e90ac23729e1d298eb0a.
It's probably worth considering adding org names back in the response. Expecting users to work with orgIDs for everything feels like bad UX when it's really an internal implementation detail.

fix(cli): add organization back to bucket response

---

bucket.go
kv/bucket.go
task/backend/analytical_storage.go

Fixes #14900
* Removed an unused function as cleanup.
* Users without true system buckets won't have fake buckets returned if they don't specify their org in the request, but this shouldn't break tasks. It wasn't working correctly previously, and considering the small number of people this impacts in a meaningless way, I'm not sure it's worth doing "correctly" for code we'll rip out soon.

fix(kv): don't stub system buckets when searching by name

---

.gitignore

If you move between `master` and `1.8` you can end up with a bunch of stuff in your working directory that git wants to stage. However these build artefacts are not relevant to 1.8.
This PR adds them to the `.gitignore` file.

chore: ignore 2.0 build artefacts via gitignore

---

ui/src/shared/components/GreaterThresholdMarker.tsx
ui/src/shared/components/LessThresholdMarker.tsx
ui/src/shared/components/RangeThresholdMarkers.tsx
ui/src/shared/components/ThresholdMarker.tsx
ui/src/shared/components/ThresholdMarkers.tsx

Closes https://github.com/influxdata/influxdb/issues/15832
Single marker dragging fix:
Double marker dragging fix:

fix(ui): Delay threshold re-rendering until mouse up when dragging markers

---

ui/src/clientLibraries/components/ClientCSharpOverlay.tsx
ui/src/clientLibraries/components/ClientGoOverlay.tsx
ui/src/clientLibraries/components/ClientJSOverlay.tsx
ui/src/clientLibraries/components/ClientJavaOverlay.tsx
ui/src/clientLibraries/components/ClientPythonOverlay.tsx

This PR is a follow up task to a feature that was released last week. It autofills the server location and organization id into the example text so that a user may more readily copy pasta their way to success :tm:
It would be nice to know where to put a bucket and token selection mechanism to finish out the last few tidbits of info in this page.

feat(ui): autofilling the organization in the client examples

---

CHANGELOG.md
authorizer/password.go
authorizer/password_test.go
bolt/onboarding.go
bolt/passwords.go
bolt/passwords_test.go
cmd/influx/main.go
cmd/influx/user.go
http/api_handler.go
http/authentication_middleware.go
http/session_handler.go
http/session_test.go
http/user_service.go
http/user_test.go
inmem/onboarding.go
inmem/passwords.go
inmem/passwords_test.go
kv/onboarding.go
kv/passwords.go
kv/passwords_test.go
mock/passwords.go
passwords.go
testing/onboarding.go
testing/passwords.go

one thing to note here is that new endpoint was created. there was no
endpoint for setting an initial password that worked. The existing endpoint
was a bit messy and coupled across multiple routes. Having multiple auth
schemes proved incredibly taxing to write against.
update: this came up in discussion in another topic with @goller and from that conversation decided to fixup the password service interface here. To provide the user id instead of name as the first arg to each set/compare func in the PasswordService.
closes: https://github.com/influxdata/influxdb/issues/15977

feat: add support for setting password and org for a new user in the cli

---

cmd/influxd/launcher/launcher.go

turns out all we need to do is auth the service deps themselves.... there is no perm for pkg stuffs yet, when that gets donezo, we can add an authorizer for pkger.SVC no prob.
closes: #15897

feat(pkger): add authentication to service dependencies for pkger

---

cmd/influxd/launcher/engine.go
cmd/influxd/launcher/flusher.go
cmd/influxd/launcher/launcher.go
storage/readservice/cursor.go
storage/readservice/store.go
ui/cypress/e2e/buckets.test.ts
ui/cypress/e2e/dashboardsView.test.ts
ui/cypress/e2e/explorer.test.ts
ui/cypress/fixtures/routes.json
ui/src/buckets/components/BucketAddDataButton.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/PrecisionDropdown.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/Tab.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/TabBody.tsx
ui/src/dataLoaders/components/lineProtocolWizard/verify/StatusIndicator.tsx
ui/src/onboarding/components/SigninForm.tsx
ui/src/shared/components/SingleStat.tsx
ui/src/timeMachine/components/RawDataToggle.tsx
ui/src/timeMachine/components/RawFluxDataTable.tsx
ui/src/timeMachine/components/view_options/ViewTypeDropdown.tsx
ui/src/timeMachine/constants/index.ts
ui/src/timeMachine/constants/visGraphics.tsx

Closes #15438
Closes #13848
I've added a temporary directory backed storage engine.  To turn it on one runs with `--e2e-testing` 
Just like all other bolt-backed resources, one can clear and reset the state of the running process with a request to /debug/flush:
```
GET /debug/flush HTTP/1.1
Host: localhost
```
Included in this PR is a cypress test that exercises writing data to influx and removing it after the tests run.

feat(storage/readservice): define engine interface

---

task/backend/analytical_storage.go
task/backend/analytical_storage_test.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go
task/backend/support_test.go

This changes the way authentication for the `_tasks` system bucket is crafted within the analytical store.
Prior to this I threaded the author of the tasks authentication onto the FinishRun call. This meant the user needed the permission to write to the system tasks bucket. However, upon reflection the actor here is the system itself attempting to record something. It is archiving a run from short-term to long-term storage. Not the user.
I believe it is therefor safe for the analytical store to craft this permission itself. The downstream storage at the end of the run recorder still has to verify the authenticity of the authorization.
This closes an issue we are experiencing with backwards compatibility with legacy system bucket recording of runs.

fix(tasks): construct permissions for finish run to write to system buckets

---

cmd/influx/bucket.go
cmd/influx/internal/tabwriter.go
cmd/influx/main.go
cmd/influx/pkg.go
cmd/influx/pkg_test.go
http/pkger_http_server_test.go
pkger/clone_resource.go
pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go

big chunk of the work for: #15921 
couple other odds and ends that got extended here, having abiliy to turn off headers for the `influx bucket find` call (no need to `grep -v` first line), and the ability to take TTY inputs for the `influx pkg` cmd. This enables inputs like `<<EOF` document inputs, which is handy for scripting.

feat(pkger): add ability to export resources to pkg in cli

---

ui/global.d.ts
ui/src/shared/utils/featureFlag.ts
ui/src/timeMachine/components/TimeMachineFluxEditor.scss
ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
ui/webpack.common.ts

Closes #15955
This allows the user to switch to using monaco through the feature flag mechanism we use for testing. As the monaco codebase is fairly large and its impact on performance hasn't been charted, I made the feature flag lazy load the libraries on switch to prevent our customers from seeing an impact in production.

feat(ui): lazy load monaco in runtime

---

cmd/influx/main.go
cmd/influx/pkg.go
cmd/influx/pkg_test.go

adds ability to validate and summarize a package form `influx` cli. I was refactoring the cli for pkg up a bit here to tighten things up.

feat(influx): add pkg summary and validate cmds

---

jsonweb/token.go
jsonweb/token_test.go

When a token is parsed without an ID it should not lead to a panic.
This fixes the scenario when a token has no ID. Instead of panicing it just returns an invalid influx ID. (0).

fix(jwt): panic on call to token.Identifier()

---

pkg/encoding/simple8b/encoding.go

Using `unsafe.Pointer` to convert a slice to array pointer fails `checkptr`. This adds slice versions of array functions used by batch decoding.
Fixes #15509

fix(storage): simple8b passes checkptr

---

inmem/kv_test.go
storage/retention_test.go
task/backend/scheduler.go
tsdb/tsm1/cache_entry.go
tsdb/tsm1/tombstone.go

This PR ensures that `influxd` can be built on a 32-bit architecture. 
In order to keep 32-bit supported we will need to add a dedicated CI pipeline.

feat: enable 32-bit support for influxd

---

pkger/clone_resource.go
pkger/models.go
pkger/models_test.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go
pkger/testdata/bucket.json
pkger/testdata/bucket.yml

Closes #15987 
after discussion with @goller, we'd like pkger to reflect teh same API as the http bucket api for rentention rules in place of retention period.

feat(pkger): move bucket pkger model to reflect http APIs retention rules

---

jsonweb/token.go

When converting a jwt token to a influxdb.Auth the id must be present for json marshal to work. A workaround is in place but the workaround created an invalid id.

fix(jwt): jwt id's can't be invalid when marshaling

---

cmd/influx/pkg.go
http/swagger.yml
pkger/models.go
pkger/service.go
pkger/service_test.go

This is a small refactor of the pkger.Diff type. After discussion with @goller, looking to increase connascence across old and new types, and this brings a step close to that.

chore(pkger): refactor diff into common types for easier access

---

ui/src/shared/components/CodeSnippet.tsx
ui/src/shared/components/TemplatedCodeSnippet.tsx
ui/src/telegrafs/components/TelegrafOutputOverlay.test.tsx
ui/src/telegrafs/components/TelegrafOutputOverlay.tsx

Closes #15962 
Removes the assumption that users would need a bucket to get a telegraf output config, and adds a test for that condition!

fix(ui): allow telegraf output without buckets

---

http/swagger.yml
ui/jest.config.js
ui/src/timeMachine/actions/queryBuilder.ts
ui/src/timeMachine/components/TagSelector.tsx
ui/src/timeMachine/reducers/index.test.ts
ui/src/timeMachine/reducers/index.ts

Connects #15984
**This is a non-user facing change.**
This sets up the redux store ahead of the UI changes to add `group()` in the query builder.
It introduces a new concept: the idea of a builder's aggregate function type. In current production, this would only be `filter`. This change is striving to add `group`, so that in the query builder, a user can toggle between filtering columns and grouping columns. 
The end goal is something resembling this (subject to change)
**When reviewing this, please think about how this is named and if there's a better name for this concept.**

chore(ui): add filter and group concepts to tags in redux [WIP]

---

ui/src/overlays/components/RouteOverlay.tsx
ui/src/telegrafs/components/TelegrafOutputOverlay.tsx

there was an issue in which the overlay controller wasn't notified of the route change for route based overlays in the app. this showed up when a user is on the telegraf output overlay and tried clicking the link to the token page. The route would change, but the modal would remain open. The solution is to just connect route overlays fully to a route.

fix(ui): allow users to go to the token page

---

storage/reads/reader.go
storage/reads/table.gen.go
storage/reads/table.gen.go.tmpl
storage/reads/table.go
storage/reads/table_test.go
storage/reads/tags_cache.go

This adds an lru cache for the columns that are produced as tags. When
producing the columns that are part of the group key, it will generate
the column and then keep it in an lru cache to reuse for future tables.
The start and stop column are effectively cached for every table because
they are special and will be the same for all of the tables.
For the tags, it retains the most recently used since they may be used
by a future table. That way most of the columns will get shared with
each other.
When the size differs, a slice is used so the underlying data is still
shared, but the size is different.
Fixes #15985.

feat(storage/reads): add cache to reuse tags when reading from storage

---

authorizer/notification_endpoint.go
authorizer/notification_endpoint_test.go
http/notification_endpoint.go

In the current system the api always adds "UserID" to the filter. This only
allows the system to look up endpoints that user created. The behavior should be
that we filter based on user input and use authorizer to hide things they shouldn't see.

fix(endpoint): when looking up a endpoint we should allow org only lookup

---

ui/cypress/e2e/buckets.test.ts
ui/cypress/e2e/explorer.test.ts
ui/src/dataExplorer/components/DeleteDataOverlay.tsx
ui/src/shared/components/DeleteDataOverlay.tsx

Closes #16011
Selecting to delete with predicate from an active bucket was not updating the selected bucket once an initial bucket was set
The solution to this problem was to separate some of the logic from where the initial bucket name was being received, and also making sure to reset the deleteWithPredicate reducer component to its default state when the overlay is closed.
Buckets:
Data Explorer:

fix(ui): DWP should default bucket name to selected bucket

---

ui/src/buckets/components/BucketExplainer.tsx
ui/src/telegrafs/components/Collectors.tsx
ui/src/telegrafs/components/TelegrafExplainer.tsx

Closes #15990
Due to its position on the page and the lack of context, it was unclear to users what Telegraf was
Added a conditionally rendered textbox with larger text to indicate to the user what Telegraf is. Also updated the background color for the existing bucket and telegraf explainer text to make it stand out more

fix(ui): updated telegraf description to be more explicit

---

ui/package.json
ui/src/shared/components/TimeSeries.tsx
ui/yarn.lock

Closes influxdata/honeybadger-errors#5
this error looks like we just need a polyfill, so I added one according to MDN's instructions, which is a mirror from the w3c, found here: https://github.com/w3c/IntersectionObserver/tree/master/polyfill

fix(ui): polyfill for IntersectionObserver

---

http/swagger.yml
http/task_service.go
kv/task.go
kv/task_test.go
task.go
task/servicetest/servicetest.go

This PR adds an "Active" filter to the `TaskFilter` struct to enable filtering by Task Status. The "Active" is a pointer to a bool, so it may be true, false, or nil when it is not set explicitly.
This PR also refactors the `findTasksByOrg` function to be more DRY, as well as consolidating multiple filter functions in kv/task.go with duplicated functionality.

feat(tasks): add ability to filter by active tasks

---

ui/src/timeMachine/selectors/index.test.ts
ui/src/timeMachine/selectors/index.ts

Closes #15908 
The previous solution failed to account for query boundaries where `now()` was being set as the upper bound in the `lower` property of the timeRange, and `upper` was being set to `null`
Updated `getEndTime` to check to see if `lower` includes `now()` and sets returns a moment reference to `now`

fix(ui): updated getEndTime to account for now() selections as the upper bound of the query

---

ui/src/telegrafs/reducers/index.ts

Closes https://github.com/influxdata/honeybadger-errors/issues/4
codemirror was expecting the `value` passed in to be a `string`, but the value was being set to `null` in particular default situations
Updated the reducer to default setting the `telegrafConfig` to an empty string rather than `null`

fix(ui): updated telegrafs reducer to set correctly set props

---

CHANGELOG.md
dashboard.go
http/dashboard_service.go
http/dashboard_test.go
http/swagger.yml

Closes #16052
Adds an optional `?include=properties` query string to `GET /dashboards/:dashboardID` that returns each cells properties

feat(http): add cell properties to dashboard response

---

CHANGELOG.md
ui/src/dashboards/components/DashboardImportOverlay.tsx
ui/src/shared/copy/notifications.ts
ui/src/tasks/components/TaskImportOverlay.tsx
ui/src/templates/components/TemplateImportOverlay.tsx
ui/src/variables/components/VariableImportOverlay.tsx

Closes [Honeybadger:#3](https://github.com/influxdata/honeybadger-errors/issues/3)
Wrap `JSON.parse` calls in the interface in `try/catch` blocks, and display the error message (usually a cryptic parsing error) to the user.
https://github.com/influxdata/influxdb/issues/16099

fix(ui): handle json parsing failures and let the user know

---

http/dashboard_test.go

makes master whole again. was created when https://github.com/influxdata/influxdb/pull/16077 merged right after another PR that had changes to the dashboard model.

fix: broken tests in dashboard http tests

---

CHANGELOG.md
ui/src/timeMachine/reducers/index.ts

Closes [HoneyBadger #12](https://github.com/influxdata/honeybadger-errors/issues/12)
For the purposes of expediency and fixing a terrible prod bug, this bypasses good hygiene like tests. I [added an issue to follow up on that.](https://github.com/influxdata/influxdb/issues/16106)
Error was introduced [here.](https://github.com/influxdata/influxdb/commit/a90899ebf2e7908d154887bb05b20a22d5281945#diff-afb81e9ccfb919d0134e48bd7176aa6bR1096)
I initially noticed a lot of duplication of the initial state of tags, so I added the notion of an initial tag. Tags in query builder parlance map to the boxes at the bottom of the query builder. So each query that was built with the builder has an array of tags associated with it. On load, these tags are nulled out to an initial state. Here is a kinda …

fix(ui): properly map over queryBuilder tags and set default values

---

CHANGELOG.md
http/dashboard_service.go
http/dashboard_test.go
http/swagger.yml
kv/dashboard.go

Closes #16112
An API user should be able to pass an optional param when creating a dashboard to create all nested data with one request.
**_POST_ /dashboards** now optionally accepts a `properties` object nested within each cell.

feat(http): create cell view properties on dashboard creation

---

CHANGELOG.md

Closes #16116
Moves changelog changes into proper place.
Method I used to figure out what to moved (I'm pretty proud of this git foo):
1. Find the [commit hash](https://github.com/influxdata/influxdb/commit/e52705d2b1f3f2949d46ad8aad48c159ef54ff32) from yesterday where I added the new unreleased changes.
1. If you don't know how to do that, go to [influxdb on github](https://github.com/influxdata/influxdb) and click [commits](https://github.com/influxdata/influxdb/commits/master) and search through them.
1. Since we last released on Nov 20 (the date on the last release on the changelog) look for the commit on that day that represents the last commit in the old changelog: https://github.com/influxdata/influxdb/commit/1177ba3cfd91e72be64ca3a5dfd2b2e09119dd02
1. Now that we have the commit …

chore(ui): move changelog entries that were added to the previous release

---

http/swagger.yml

The `url` property of `HTTPNotificationRuleBase` should not be required:
https://github.com/influxdata/influxdb/blob/dbcdc8dc59a28b819ee50385756a59a284012fdf/notification/rule/http.go#L179

fix(http): remove a HTTPNotificationRuleBase.url from required properties

---

bolt/secret.go
http/org_service.go
http/org_test.go
kv/secret.go

fix(http): Return an empty array if organization has no secret keys

---

ui/src/external/monaco.tomlSyntax.ts
ui/src/external/monaco.tomlTheme.ts
ui/src/external/toml.tmLanguage.json
ui/src/shared/components/TomlMonacoEditor.tsx
ui/src/shared/utils/featureFlag.ts
ui/src/telegrafs/components/TelegrafConfig.tsx
ui/src/timeMachine/components/TimeMachineFluxEditor.scss

upgrading the toml editor to monaco allows us go from zero
to hero

feat(ui): cloning monaco editor for use with toml

---

http/bucket_service.go
http/bucket_test.go
kv/bucket.go

This removes the bucket name validation from the KV BucketService,
and moves it to the http implementation of the service.
The effect is that API user requests still get validated but direct KV access does not

fix(http/bucket): lift bucket name validation to http layer

---

cmd/influx/pkg.go
cmd/influx/pkg_test.go
cmd/influxd/launcher/pkger_test.go
http/swagger.yml
http/telegraf.go
pkger/clone_resource.go
pkger/models.go
pkger/service.go

Closes #16074 
Adds ability to export telegraf configs to an influx package/template

feat(pkger): add support for exporting telegraf

---

ui/src/shared/components/ViewSwitcher.tsx

Closes https://github.com/influxdata/influxdb/issues/16143 as part of https://github.com/influxdata/influxdb/issues/15836

fix(ui): remove prop override to allow Graph + Single Stat to use line positioning option

---

ui/package.json
ui/src/dashboards/constants/index.ts

Closes #15905 
Most of the requested additions were as simple as updating the selections dropdown menu. However, including the `a` flag on formats (indicating that we should include an am/pm) was not compatible with giraffe. Updating the way giraffe handled 24h locales and `a` flags were required in order to complete this functionality.

feat(ui): added more time formats for table dropdown

---

ui/cypress/e2e/queryBuilder.test.ts
ui/src/pageLayout/containers/Nav.tsx

Closes #16106
What it says on the tin ☝️. Adds two e2e test cases for creating a query in the query builder, one via the Data Explorer and one via the Dashboard.

test: add e2e tests for query builder

---

logger/fields.go
query/logger.go
query/logging.go
query/logging_test.go

This adds the trace_id to the query log.

feat(query): add trace_id and sampled to the query log

---

cmd/influxd/launcher/launcher.go

adds pkger telegraf support to the public api

fix(pkger): add telegraf to launcher for public api support

---

dashboard.go
http/dashboard_service.go
http/dashboard_test.go
pkger/clone_resource.go
pkger/service.go
pkger/service_test.go

Closes #16142
- Updates the http client to pass in the `?include=properties` param
- Pkger now uses the cell view-properties param `properties` returned on `GET /dashboards/:dashboardID` when cloning existing resources - no more round trip call to the API for the cell-view
- Pkger can now create cell view-properties in a single API call using `POST /dashboards`

feat(pkger): pkger to use updated dashboard params

---

ui/src/dataLoaders/actions/telegrafEditor.ts
ui/src/dataLoaders/reducers/telegrafEditor.ts
ui/src/store/configureStore.ts
ui/src/types/stores.ts

I'm trying to figure out a way to break down the large amount of work going on for influxdata/idpe#5399 into readable pull requests. This one carves out a little portion of the redux store for the telegraf editor feature. there should be a place to put all plugins, the ones currently being used, and some odds and ends connected to the display state of the editor. The default plugin list is only there for testing routing of the data while we deploy the endpoint to populate it. i expect more changes here as the product functionality is fleshed out, but might as well get the swath of it done.

chore(ui): telegraf redux

---

ui/src/timeMachine/reducers/index.ts

Closes https://github.com/influxdata/honeybadger-errors/issues/15
Previous implementation assumed that files / files[0] would be defined
Added checks for when the files are undefined / empty

fix(honeybadger): updated getTableProps to return empty fieldOptions whenever the files are undefined

---

pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/testdata/notification_endpoint.json
pkger/testdata/notification_endpoint.yml

Add support for notification endpoints to the pkger parser.

feat(pkger): add support for notification endpoints to parser

---

kv/service.go
kv/task.go
kv/task_test.go
task/backend/coordinator.go
task/backend/coordinator_test.go
task/backend/middleware/middleware.go
task/servicetest/servicetest.go

This change ensures the following behavior:
* task LatestScheduled is always set when a task is updated and transitions from a status of inactive to active
* task LatestScheduled is non-zero when created, to set the initial schedule time as some point after it was created
In addition, the kv.Service introduces clock.Clock that is used for task create and task updates only. This change permits testing in a deterministic fashion.

fix(task): LatestScheduled is set when task is updated to active

---

cmd/influx/pkg.go
cmd/influx/pkg_test.go
cmd/influxd/launcher/launcher_helpers.go
cmd/influxd/launcher/pkger_test.go
http/client.go
http/telegraf.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go
pkger/testdata/variables.json
pkger/testdata/variables.yml

governs the concurrency with a simple semaphore. Defaults to 5
concurrent reqs, anything greater, puts a lot of pressure
on the system as a whole (especially OSS/bolt store).

feat(pkger): speed up application of pkg with a touch of concurrency

---

cmd/influxd/launcher/pkger_test.go
mock/bucket_service.go
mock/dashboard_service.go
mock/label_service.go
mock/safe_count.go
mock/telegraf_service.go
mock/variable_service.go
pkger/service_test.go

tests failing from a data race caused in the tests setup. an incrementing
const needs something to serialize it (atomic in this case) to remove that
data race. This touches that up and provides some reuable thread safe
count mechanism within the mock package. Is pretty brittle to tack these
counters on, and then remember to go back in when things are thrown into
concurrent workflows. This lets us take advantage of describing behavior and
it be safe for concurrent access.

fix(pkger): fix flaky test in pkger service tests

---

cmd/influx/bucket.go
cmd/influx/main.go
cmd/influx/pkg.go
cmd/influx/user.go
cmd/influx/write.go
cmd/influxd/launcher/launcher_helpers.go
cmd/influxd/launcher/pkger_test.go
cmd/influxd/launcher/tasks_test.go
http/bucket_service.go
http/bucket_test.go
http/client.go
http/dashboard_service.go
http/dashboard_test.go
http/label_service.go
http/label_test.go
http/telegraf.go
http/user_resource_mapping_service.go
http/variable_service.go
http/variable_test.go
query/stdlib/testing/end_to_end_test.go
source/bucket.go
testing/variable.go

want to take advantage of pooling connections and reducing GC for requests. And reduce 
the amount of boilerplate to get things wrong. Also fill in some holes in testing.
Notes:

chore(http): refactor bucket|dashboard|label|umr|var http clients to use reusable HTTP client

---

cmd/influx/main.go
cmd/influx/organization.go

cleans up the extraneous `init()` calls. part of a larger effort to minimize startup times.
depends on: #15938

chore(influx): refactor orgnization cmd

---

CHANGELOG.md
ui/src/shared/components/tables/TableCell.tsx
ui/src/shared/constants/colorOperations.ts
ui/src/timeMachine/reducers/index.ts

Closes #15904 
Setting table thresholds would not reflect changes to styling in the table ui
Added in check to colorization of the table thresholds to set the background colors correctly. Also updated a table method to correctly determine whether a value is a number or not

fix(ui): updated table threshold to set background colors for thresholds correctly

---

CHANGELOG.md
README.md
http/query_handler.go
logger/fields.go
query/control/controller.go

This PR connects logged errors to their corresponding trace by annotating the logger with the request's trace ID. Additionally, errors bubbling up to the query handler are captured in the trace logs. 
A small, unrelated README update is also included.

feat(query): annotate logger with trace id and record query errors in trace log

---

models/points.go
models/uint_support.go

* Remove all instances of EnableUintSupport()
* Remove all instances of enableUint64Support
Ultimately this unconditionally enables uint64 support.
Closes #15711

refactor(models): permanently enabled uint64 support

---

ui/cypress/e2e/collectors.test.ts
ui/src/telegrafs/components/CollectorList.tsx

During the work for influxdata/idpe#5399, we discovered that there doesn't exist a 1:1 relationship between buckets and telegraf configs, as there can be more than one output plugin per config file. This makes the sort... weird. If the filter is used to select a bucket that contains the string "alpha" and a reverse bucket sort is applied, is the expected behaviour that the config that ALSO references the "zed" bucket is at the top?

fix: remove bucket sort for telegrafs

---

http/notification_endpoint.go
http/notification_endpoint_test.go
kv/notification_endpoint.go
mock/notification_endpoint_service.go
notification_endpoint.go
secret.go

note: tests are seriously borked here. Cannot reuse any existing testing
as the setup is very particular and the http layer doesn't suppport everyting.
that being said, there are goign to be implicit testing in the
`launcher/pkger_test.go` file. This feels broken, and probably needs to be
readdressed before we GA a 2.0 influxdb....
this is work to support notification endpoints support in pkger

feat(http): add notification endpoint service

---

CHANGELOG.md
cmd/influx/bucket.go
cmd/influx/inspect.go
cmd/influx/pkg.go
cmd/influx/task.go
cmd/influx/user.go

enables a user to specify an organization name when creating a bucket from the influx cli.
Closes #15828
The influx bucket create command doesn't seem to have a -o flag for specifying the organization name. This PR adds a flag `--org` or `-o` for specifying the org name to avoid the overhead of having to lookup an organization id

feat(cmd): bucket create to accept org name as flag

---

.github/semantic.yml

Allow use of Merge commits (eg on "Merge branch 'master' into feature/ride-unicorns")
This is only relevant when using commitsOnly: true (or titleAndCommits: true)

style: allow Merge commits in commit messages

---

http/swagger.yml

* added date-time format for start and stop DeletePredicateRequest
* fixed malformed reference to ViewProperties in PkgChart model
* define separate model for RetentionRule as is in Organizations, Buckets, Labels
* "labels" property from Check and PostCheck should be part of CheckBase (it is ancestor for all Check types)
* "labels" property from NotificationRule and PostNotificationRule should be part of NotificationRuleBase (it is ancestor for all NotificationRule and types)
* "labels" property from NotificationEndpoint and PostNotificationEndpoint should be part of NotificationEndpointBase (it is ancestor for all NotificationEndpoint and types)
* The url property of HTTPNotificationRuleBase should not be required
* Added query link for CheckBase and NotificationRuleBase

fix(http): update swagger for easily use in clients

---

CHANGELOG.md
http/query_handler.go
http/query_handler_test.go
http/swagger.yml
kit/tracing/tracing.go

Adds `Trace-Id` response header to query endpoint.

feat(query): add trace response headers

---

ui/src/shared/constants/fluxFunctions.ts

Adds and updates functions to bring the functions list in line with Flux 0.56.

chore(flux): update flux functions list for flux 0.56

---

CHANGELOG.md
ui/src/clockface/components/inputs/multipleInput/MultipleRows.tsx
ui/src/shared/components/cells/CellContext.tsx

Closes #16170
No option was given for deleting note cells
Added the existing delete cell functionality to the dropdown

fix(ui): regression fix, notes are now deletable

---

http/api_handler.go
http/auth_service.go
http/bucket_service.go
http/check_service.go
http/chronograf_handler.go
http/dashboard_service.go
http/delete_handler.go
http/document_service.go
http/label_service.go
http/middleware.go
http/notification_endpoint.go
http/notification_rule.go
http/onboarding.go
http/org_service.go
http/platform_handler.go
http/query_handler.go
http/router.go
http/scraper_service.go
http/session_handler.go
http/source_service.go
http/task_service.go
http/telegraf.go
http/user_service.go
http/variable_service.go
http/write_handler.go

Basic gist is we mount handlers at given prefixes (i.e. `/api/v2/buckets` for bucket handler).
Closes #13320 

chore(http): refactor api handler take advantage of route tree

---

CHANGELOG.md
ui/cypress/e2e/collectors.test.ts
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/shared/constants/fluxFunctions.ts

Closes #15730
Labels require unique names. The buggy behavior when we create a telegraf config is to create a label for the config and to name every label `@influxdata.name`. This fix appends a timestamp to `@influxdata.name` (that string is being filtered on, so we want keep `@influxdata.name`)

fix: add a timestamp to the telegraf label creation to insure uniqueness

---

CHANGELOG.md
ui/cypress/e2e/collectors.test.ts
ui/src/telegrafs/components/TelegrafConfig.tsx

Closes #16205
Changes what is exported from `Loadable` so that it properly conforms and returns an element.

fix: return the telegraf module based on Loadable's interface

---

cmd/influxd/launcher/launcher.go
kv/task.go
mock/task_service.go
task.go
task/backend/analytical_storage.go
task/backend/executor/executor_metrics.go
task/backend/executor/limits_test.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go
task/backend/scheduler/scheduler.go
task/backend/scheduler/scheduler_test.go
task/backend/scheduler/treescheduler.go
task/backend/task.go
task/mock/task_control_service.go

This PR adds a histogram metric `scheduleInterval` to the Executor metrics that records the time lag between when a task is scheduled to be run and when it actually runs. This can be used to determine the "per minute system concurrency" as described in the queryd SLO RFC.
This PR also adds a property `RunAt` to the Run object, which is used to record the time the Run is scheduled to be executed, including the task's Offset. This is added to the Run object because it is possible that the Run object will be changed by the user in the time between the Run being scheduled and being run, which would make our metrics for that Run inaccurate.
The value `ScheduledAt` is changed to `ScheduledFor` to maintain consistency.

feat(metrics): add run latency to executor metrics

---

inmem/kv.go
inmem/kv_test.go

Removes some racy code from `inmem.KVStore`. As long as callers use the correct API (`NewKVStore`) this shouldn't cause problems.

fix: remove racy, redundant initialisation

---

cmd/influx/bucket.go
cmd/influx/inspect.go
cmd/influx/main.go
cmd/influx/pkg.go
cmd/influx/pkg_test.go
cmd/influx/user.go

Closes #15828
#16187 introduced a regression to the pkg cli. This PR ensures that the org SVC is added to the pkg cli in-line with the builder pattern.

fix(cmd): adds org svc dep to pkg

---

task/backend/coordinator/task_coordinator.go
task/backend/coordinator/task_coordinator_test.go
task/backend/scheduler/scheduler.go
task/backend/scheduler/scheduler_test.go
ui/cypress/e2e/queryBuilder.test.ts

This makes schedules that start with `@every ` aligned with the time.

fix(tasks): align @every schedule firings

---

ui/cypress/e2e/orgs.test.ts
ui/cypress/index.d.ts
ui/cypress/support/commands.ts
ui/src/index.tsx
ui/src/organizations/containers/NoOrgsPage.tsx
ui/src/shared/constants/fluxFunctions.ts
ui/src/shared/containers/RouteToOrg.tsx

Closes https://github.com/influxdata/honeybadger-errors/issues/22
Technically, a user does not need to belong to an organization.  However, the UI is organized around an org context.  Most every page is scoped under `orgs/:orgID`.  So, when a user without an org attempted to use the UI, the app would throw.  
If the user does not belong to an org, direct them to a page instructing them on what they need to do to continue.

feat: route user to no orgs page

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/dashboard_index/Table.tsx
ui/src/shared/utils/useVisDomainSettings.ts

Closes #15610
Sorting dashboards by modified dates defaulted to sorting by name
Pass in the correct property to sort by so that the orderby function can sort the elements by their appropriate props

fix(ui): sort by modified now integrated

---

authorizer/notification_endpoint_test.go
cmd/influx/main.go
cmd/influx/pkg.go
cmd/influx/pkg_test.go
cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/launcher_helpers.go
cmd/influxd/launcher/pkger_test.go
http/notification_endpoint_test.go
http/pkger_http_server.go
http/pkger_http_server_test.go
http/swagger.yml
notification/endpoint/endpoint.go
notification/endpoint/endpoint_test.go
notification/endpoint/http.go
notification/endpoint/pagerduty.go
notification/endpoint/slack.go
notification/rule/http_test.go
notification/rule/pagerduty_test.go
notification/rule/slack_test.go
pkger/models.go
pkger/models_test.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go
telegraf.go
telegraf_test.go
testing/notification_endpoint.go
testing/notification_rule.go
testing/util.go

realized as of recent I hadn't set the integration tests to use the server/client. This is a major issue, since I wasn't testing the public API 😳. When changed to use HTTP server, a lot of problems came out of that. This PR remedies the integration tests to use the http server/client and fixes up a bunch of other stuff to make that a reality.

chore(pkger): use http client/server for integration tests

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/reader.go

When we find a bad TSM file during compaction, propagate the error up and move
the bad file aside.
Closes #15804

fix(storage): skip TSM files with block read errors

---

ui/src/dataLoaders/actions/telegrafEditor.ts
ui/src/dataLoaders/components/TelegrafEditor.scss
ui/src/dataLoaders/components/TelegrafEditor.tsx
ui/src/dataLoaders/components/TelegrafEditorFooter.tsx
ui/src/dataLoaders/components/TelegrafEditorMonaco.tsx
ui/src/dataLoaders/components/TelegrafEditorPluginList.tsx
ui/src/dataLoaders/components/TelegrafEditorPluginLookup.tsx
ui/src/dataLoaders/components/TelegrafEditorSidebar.tsx
ui/src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx
ui/src/dataLoaders/components/collectorsWizard/verify/VerifyCollectorsStep.tsx
ui/src/dataLoaders/reducers/telegrafEditor.ts

@alexpaxton took a pass through the UI for influxdata/idpe#5399 based on feedback from product and with some context of future plans from design. Things got moved around and buttoned up. Also, the color palette isn't so chaotic.

feat: telegraf editor design work

---

CHANGELOG.md
ui/cypress/e2e/explorer.test.ts
ui/src/shared/components/tables/TableCell.tsx
ui/src/shared/components/tables/TableGraph.tsx

Closes #15980
The previous implementation was setting a default FE sort for columns if they existed without considering whether the results were already sorted
Removed the default sort assignment so that values are returned based on the flux query sorting. Added tests to ensure that default values are automatically sorted by `_value`

fix(ui): flux sort no longer being overidden by default FE sort

---

CHANGELOG.md
kv/task.go
kv/task_test.go

Task runs are stored and retrieved from the `taskRunsv1` bucket, but when they are canceled they are incorrectly placed in the `tasksv1` bucket. Once this has been done, further look ups of the task run fail, because it is located in the wrong bucket.
This addresses the problem by placing them back into the `taskRunsv1` bucket. An additional test has been added to ensure we are able to successfully read a canceled run.

fix(kv): Store canceled task runs in the correct bucket

---

cmd/influxd/launcher/launcher.go
endpoints/service.go
http/dashboard_test.go
http/notification_endpoint.go
http/notification_endpoint_test.go
kv/notification_endpoint.go
kv/notification_endpoint_test.go
kv/notification_rule.go
pkg/testttp/http.go
testing/notification_endpoint.go

this is a blocker for anyone who hits the endpoint services internally(pkger work surfaced this). They had to know that they need to also know of hte secret service then do all that put/delete alongside the operation. This makes that unified inside the store tx.

chore: refactor notication endpoints into a service with dep injection

---

CHANGELOG.md
cmd/influx/pkg.go
cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/pkger_test.go
http/notification_endpoint.go
http/swagger.yml
pkger/clone_resource.go
pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go
pkger/testdata/notification_endpoint.json
pkger/testdata/notification_endpoint.yml
pkger/testdata/notification_endpoint_secrets.yml

also provides secret refs to be supported

feat(pkger): add export functionality to notification endpoints

---

CHANGELOG.md
cmd/influx/authorization.go
cmd/influx/bucket.go
cmd/influx/inspect.go
cmd/influx/main.go
cmd/influx/organization.go
cmd/influx/pkg.go
cmd/influx/pkg_test.go
cmd/influx/task.go
cmd/influx/user.go

Closes #16214 
Consistently applies env vars to cli commands using flags that could be interchanged with env vars (ie. --org-id INFLUX_ORG_ID, --bucket-name INFLUX_BUCKET_NAME, etc). See https://github.com/influxdata/influxdb/issues/16048 for a more detailed list of env vars.
Also fixes a small bug where we were not setting globally the `INFLUX` prefix before any cobra commands were init.

feat(cmd): apply env vars consistently across cmd

---

ui/src/external/monaco.fluxSyntax.ts
ui/src/external/monaco.onigasm.ts
ui/src/external/monaco.tomlSyntax.ts
ui/src/shared/components/FluxMonacoEditor.tsx
ui/src/tasks/containers/TaskEditPage.tsx

A bunch of honey badger errors came in this morning centered around the monaco editor. this fixes a few:
onigasm is only imported once
function inserts assumed a 0 indexed line number
invisible flux editor on task edit page
closes #16239
closes influxdata/honeybadger-errors#51
closes influxdata/honeybadger-errors#50
closes influxdata/honeybadger-errors#49

fix: errors from the editor

---

ui/src/shared/utils/errors.ts
ui/src/variables/utils/getWindowVars.ts

Closes https://app.honeybadger.io/projects/61122/faults/58676136
The `FunctionSelector` component was triggering the `getWindowPeriod` function with an empty query when the component was initialized. The query would be blank at this time, so the `getMinDurationFromAST` function would throw an error, resulting a repetitive (not blocking) honeybadger error
Added a check before running the `getWindowPeriod` function to see if the `query` is undefined or an empty string to ensure that the error won't be thrown due to an `invalid time range`

fix(ui): added check to ensure that windowperiod isn't calculated when the query is undefined

---

CHANGELOG.md
ui/cypress/e2e/explorer.test.ts
ui/src/dashboards/utils/tableGraph.ts

Closes #16200
Sorting tables via the front end sorted resulted in unordered numbers due to the fact that numbers were being ordered as strings
Type checked to-be sorted values to ensure that values are numeric before sorting. Completed testing for table sorting to ensure stability

fix(ui): front end sorting for numeric values now being handled correctly

---

CHANGELOG.md
notification/endpoint/endpoint_test.go
notification/endpoint/http.go
notification/endpoint/pagerduty.go
notification/endpoint/slack.go

Closes #16240 
Relaxes the rigid validation on endpoints to not require the id be prefixed.

feat(endpoints): drop id prefix req endpoint secret key

---

ui/src/shared/utils/featureFlag.test.ts
ui/src/shared/utils/featureFlag.ts

Adds a utility function to `featureFlags`, `getUserFlags`. This was part of work I did on #16138 that I pulled out into its own logical commit, hence no issue number.

chore: add getUserFlags utility function

---

CHANGELOG.md
ui/cypress/e2e/dashboardsIndex.test.ts
ui/cypress/e2e/tasks.test.ts
ui/cypress/e2e/templates.test.ts
ui/cypress/e2e/variables.test.ts
ui/package.json
ui/src/dashboards/components/DashboardImportOverlay.tsx
ui/src/shared/components/ImportOverlay.tsx
ui/src/tasks/components/TaskImportOverlay.tsx
ui/src/templates/components/TemplateImportOverlay.tsx
ui/src/variables/components/VariableImportOverlay.tsx
ui/yarn.lock

Closes https://github.com/influxdata/influxdb/issues/16099
Added a third party library that wraps JSON.parse with linting and detailed error messaging.
For now, we are going to put the detailed error messages into the toast. As @hoorayimhelping mentioned, there is a potential for moving the detailed error message into something more permanent and useful for the user.

fix(ui): retain user input when parsing invalid JSON during import

---

http/check_service.go
http/check_test.go

small cleanup. Was going to create the CheckService in http, but decided against it after realizing pkger does not need it 🤦‍♂.

chore(http): cleanup http pkg's check implementation cruft

---

CHANGELOG.md
kv/task.go

Closes influxdata/idpe#5592
In the event that `findTaskByIDWithAuth` cannot find the task ID contained in the bucket, the outer loop will never terminate.
This ensures that we are calling `Next()` along-side any calls to `continue` while using a `Cursor`.
**Notes:**
I investigated improving the overall ergonomics of these cursor-based loops by hoisting the cursor advancement to the top of the iterations—instead of being at the tail-end of them. However, due to seeking behavior, the pre-conditions of the loop become a bit trickier. Perhaps this is an area of further improvement. Generally, loops that have cross-iteration state interaction tend to cause surprising behavior like this when `continue` gets involved.

fix(kv): Prevent infinite loop condition when listing tasks by org.

---

http/query_handler.go
http/query_handler_test.go
kit/tracing/testing/testing.go
kit/tracing/tracing.go
logger/fields.go
query/logging.go
task/backend/executor/executor.go
task/backend/executor/task_executor.go
task/backend/executor/task_executor_test.go

This removes the flux statistics from the task run log.
In place of the flux statistics we now have the trace ID and whether the trace was sampled.

feat(tasks): remove flux stats from run log and replace with trace id

---

CHANGELOG.md
http/check_service.go
http/swagger.yml
notification/check/check.go
notification/check/threshold.go
notification/duration.go
pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/testdata/checks.json
pkger/testdata/checks.yml
task.go

add preliminary support for checks to parser

feat(pkger): add support for check resource to pkger parser

---

CHANGELOG.md
authz.go
cmd/influx/pkg.go
cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/launcher_helpers.go
cmd/influxd/launcher/pkger_test.go
http/middleware.go
http/pkger_http_server.go
http/swagger.yml
pkger/models.go
pkger/service.go
pkger/service_test.go

feat(pkger): add check dry functionality

---

ui/src/organizations/actions/orgs.ts
ui/src/shared/actions/me.ts
ui/src/shared/utils/errors.ts

Closes #16138
1. Adds the user id, org id, and current feature flag status to HoneyBadger error context
1. If the environment is not `CLOUD` print a table of the context that would have been sent to honeybadger
[See the context](https://app.honeybadger.io/projects/61122/faults/58718222#notice-context) on a contrived, but actual HoneyBadger error.
Local context in the console:

chore: add more context to honeybadger errors

---

.circleci/config.yml
ui/package.json

This splits the go and js linting steps out of the tests.  This allows them to be run in parallel.
Speeds up the entire js flow from 13 to 9 minutes and go tests from 22 minutes to 19.
Additionally, I paralleled eslint over 8 containers so the linter goes from 9 to 4.5 minutes.

ci: split go and js linting into separate circleci jobs

---

.circleci/config.yml

Similar to #16274, this parallelizes the go race tests across 8 circle containers.
This speeds up the tests from 19 to 11m

ci: run go race tests in parallel over 8 containers

---

CHANGELOG.md
bolt/kv.go
inmem/kv.go
kv/cursor.go
kv/store.go
mock/kv.go
testing/kv.go

Closes #5367
This PR introduces the concept for a `ForwardCursor` as described in the issue above. It's purpose is to create a contract in cursor creators declare upfront the direction and start position in which to create a cursor. This will promote healthier access patterns to the existing cursor. Allowing us to optimize a lot easier in the kv bucket implementations.
1. Define the forward cursor interface. A single direction cursor which is configured with a direction on creation.
```go
c := bucket.ForwardCursor([]byte("runs/"),
kv.WithCursorDirection(kv.CursorDescending),
kv.WithCursorHints(kv.WithCursorHintKeyStart("runs/12345")))
```
2. Update all bucket implementations to adhere to new `ForwardCursor()` method.

feat(kv): define forward cursor interface

---

ui/src/telegrafs/components/TelegrafOutputOverlay.tsx

Closes #16290
just looks like the template function wasn't being passed variables. also took time to normalize some internal state while rummaging around in there.

fix: pass variables into a function

---

CHANGELOG.md
pkger/clone_resource.go
pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/testdata/notification_rule.json
pkger/testdata/notification_rule.yml

feat(pkger): add parser support for notification rules

---

ui/Makefile

tests are failing from the makefile because types aren't being generated from swagger. this runs the generate command more often

feat: generate types for tests

---

CHANGELOG.md
cmd/influx/pkg.go
cmd/influxd/launcher/pkger_test.go
http/swagger.yml
pkger/models.go
pkger/service.go
pkger/service_test.go

feat(pkger): add dry run functionality for notification rules

---

ui/jestSetup.ts

tests jumped from ~1min to ~20min on circleci some time last week, prompting parallelization of those tests in order to run in a usable test window. This worked fine until someone made a good case for running the tests outside of the CI pipeline, in which tests took up to 6hrs on one user's machine.
i did some sleuthing
and it turns out that the problem was just that honey badger is being included in all of these tests as of this PR: https://github.com/influxdata/influxdb/pull/16194
so our tests were breaking our tests
I mocked honey badger from the jest tests in the test setup file (applies to all tests), and now tests are back down to ~1min

fix: speeding them tests right up

---

CHANGELOG.md
cmd/influx/pkg.go
cmd/influxd/launcher/pkger_test.go
http/swagger.yml
pkger/clone_resource.go
pkger/models.go
pkger/parser.go
pkger/service.go
pkger/service_test.go

feat(pkger): add export support for notification rules

---

CHANGELOG.md
cmd/influx/pkg.go
cmd/influxd/launcher/pkger_test.go
http/swagger.yml
pkger/models.go
pkger/parser.go
pkger/service.go

adds dry run functionality for tasks

feat(pkger): add dry run functionality for task resource

---

CHANGELOG.md
cmd/influx/pkg.go
cmd/influx/pkg_test.go
cmd/influxd/launcher/pkger_test.go
http/swagger.yml
pkger/clone_resource.go
pkger/parser.go
pkger/service.go
pkger/service_test.go

lo and behold, our last PR before an MVP can be realized. This is to supply tasks for exporting:
```sh
$ influx pkg export --tasks=04f90352681d3000
apiVersion: 0.1.0
kind: package
meta:
description: ""
pkgName: new_6868142840635702249
pkgVersion: v1
spec:
resources:
- every: 1h
kind: Task
name: task1
offset: 10m0s
query: |-
from(bucket: "rucket1")
|> yield()
```

feat(pkger): add export support for tasks

---

dashboard.go
http/check_test.go
http/query_handler_test.go
notification/check/check_test.go
testing/checks.go

UI in partricular is expecting non nil array vals, this remedies that issue so those are always populated.

fix: add custom marshaler to dashboard builder config to stop breaking api consumers

---

CHANGELOG.md
ui/cypress/e2e/explorer.test.ts
ui/src/dataLoaders/reducers/telegrafEditor.ts
ui/src/shared/utils/featureFlag.ts
ui/src/timeMachine/actions/queryBuilder.ts
ui/src/timeMachine/components/TagSelector.tsx
ui/src/timeMachine/components/builderCard/BuilderCard.tsx
ui/src/timeMachine/components/builderCard/BuilderCardDropdownHeader.tsx
ui/src/timeMachine/reducers/index.ts
ui/src/timeMachine/selectors/index.test.ts
ui/src/timeMachine/selectors/index.ts
ui/src/timeMachine/utils/queryBuilder.ts
ui/src/types/dashboards.ts

Closes #15984
Adds grouping to query builder

feat: Add ability to group in Query Builder

---

pkger/service.go
pkger/service_test.go

when exporting by org the tasks created by a check are exported alongside the check. this removes the extraneous tasks from exported.
Closes #16334

fix(pkger): remove tasks created by checks from being exported

---

CHANGELOG.md
http/check_service.go
http/check_test.go
http/notification_rule.go
http/notification_rule_test.go
http/swagger.yml
ui/cypress/e2e/checks.test.ts
ui/src/alerting/actions/checks.ts
ui/src/alerting/components/CheckCard.tsx
ui/src/alerting/components/notifications/RuleCard.tsx
ui/src/shared/components/lastRunTaskStatus/LastRunTaskStatus.scss
ui/src/shared/components/lastRunTaskStatus/LastRunTaskStatus.tsx

Closes #15838
Added lastrunstatus check and error handling for notification rules and check rules

feat(ui): added notification rule & checks last run status & error

---

CHANGELOG.md
cmd/influx/pkg.go
cmd/influx/pkg_test.go
http/middleware.go
http/pkger_http_server.go
http/pkger_http_server_test.go
http/swagger.yml
pkger/models.go
pkger/parser.go
pkger/service.go
pkger/service_test.go

this provides the ability to add secret refs at runtime instead of adding them to the pkg.
examples for providing secrets via the CLI:
```
$influx pkg -f $PWD/pkger/testdata/notification_endpoint_secrets.yml -o=rg --secret=routing-key-4::routing-key-pair --secret=routing-key-7::someval
$ influx pkg -f $PWD/pkger/testdata/notification_endpoint_secrets.yml -o=rg
Please provide secret value for key routing-key-6 (optional, press enter to skip):
```

feat(pkger): add ability to provide secrets alongside package when applying

---

CHANGELOG.md
ui/src/tasks/components/TaskCard.tsx
ui/src/types/tasks.ts

Closes #15844
Tasks were not displaying the lastRunStatus of the tasks.
Integrated the new lastRunStatus component to display whether a task has been successful or unsuccessful

feat(ui): added last run status to tasks

---

pkger/service.go
pkger/service_test.go

references #16342 
the tasks export all exports system tasks, which this PR is to remove.

fix(pkger): make pkger skip system tasks when exporting all tasks

---

CHANGELOG.md
cmd/influx/task.go

feat(influx): add hide headers flag to influx cli task cmd

---

CHANGELOG.md
pkger/clone_resource.go

Closes #16342 
Right now we have this duality of making the name/offset/every stuffs both inside the flux query and as siblings on the influxdb.Task type.  For pgker, it needs just the query and not the hand jammed `option task` stuffs, b/c of the brittleness of the current Task API. This makes the initial regex no longer greedy, it was capturing too much. The regex playground below is useful if you want to test drive some more stuffs at it:
regex playground for this fix: https://regex101.com/r/xV9wL4/30

feat(pkger): fixup flux query normalization in exporting of task

---

CHANGELOG.md
kit/check/check.go
kit/check/check_test.go

With `/health`, it is possible to override the overall status reported. This change adds the same functionality to `/ready`. This allows incident responders to take an unhealthy pod out of a service without killing it—giving them time to gather meaningful forensic data from the pod. The new contract is:
Force not ready:
GET /ready?force=true&ready=false
Force ready:
GET /ready?force=true&ready=true
Disable override:
GET /ready?force=false

feat(kit/check): Manual Overrides for Readiness Endpoint

---

kv/auth_test.go
kv/bucket_test.go
kv/check_test.go
kv/dashboard_test.go
kv/document_test.go
kv/kvlog_test.go
kv/label_test.go
kv/lookup_service_test.go
kv/notification_endpoint_test.go
kv/notification_rule_test.go
kv/onboarding_test.go
kv/org_test.go
kv/passwords_test.go
kv/scrapers_test.go
kv/secret_test.go
kv/session_test.go
kv/source_test.go
kv/task_test.go
kv/telegraf_test.go
kv/urm_test.go
kv/user_test.go
kv/variable_test.go

no need to test both inmem and bolt. The stores are tested to satisfy the
kv.Store interface already. No need to go through the service layer tests.

chore(kv): drop duplicative bolt service tests

---

kv/service.go
kv/variable.go

issue here is that the unique by name index for variables was implemented
and has the same functionality about it that this orgs index has. The duplicative
orgs index was nuked. The migration to hydrate the org/name index never
happened. This is a stop gap until that migration is in place.

fix(kv): add legacy variable orgs index back

---

ui/src/dashboards/actions/index.ts
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/labels/actions/index.ts
ui/src/labels/components/CreateLabelOverlay.tsx
ui/src/labels/components/LabelsTab.tsx
ui/src/labels/constants/index.ts
ui/src/tasks/actions/index.ts
ui/src/tasks/components/TaskCard.tsx
ui/src/templates/actions/index.ts
ui/src/templates/api/index.ts
ui/src/templates/components/StaticTemplateCard.tsx
ui/src/templates/components/TemplateCard.tsx
ui/src/templates/utils/index.ts
ui/src/types/templates.ts
ui/src/variables/actions/index.ts
ui/src/variables/components/VariableCard.tsx

Closes #16358
The client library is deprecated and no longer being supported, need to transition api routes based on the oats generatedRoutes
Revised the client api calls that directly correlate to labels to use the generatedRoutes. Added defaults for labels where applicable in order to refactor this in stages and prevent TS errors

chore(ui): label client refactor complete

---

http/swagger.yml
kv/notification_rule.go
notification.go
notification/rule/rule.go
notification/rule/rule_test.go

Closes #16017
Before this PR:
|in NR tags| in query params  | returned? |
|---|---|---|
| [a,b] [c,d] | [a,b] [c,d] | yes |
| [a,b] [c,d] | [a,b] [c,d] [e,f] | no |
| [a,b] [c,d] |  [a,b] [c,X] |  no |
| [a,b] [c,d] [e,f] | [a,b] [c,d] |  yes |
---
After this PR:
|in NR tags| in query params | returned? |
|---|---|---|
| [a,b] [c,d] | [a,b] [c,d] | yes |
| [a,b] [c,d] | [a,b] [c,d] [e,f] | yes |
| [a,b] [c,d] |  [a,b] [c,X] |  no |
| [a,b] [c,d] [e,f] | [a,b] [c,d] |  no |

fix(notificationrules): Correct logic on matching notification rules

---

storage/wal/dump.go
storage/wal/dump_test.go

This PR adds some extra context around the predicates contains in WAL delete entries. It lets us see what the predicate in the WAL file looked like.
It could be improved in the future with a better string representation.

feat: add predicate output to WAL dump tool

---

CHANGELOG.md
ui/cypress/e2e/explorer.test.ts
ui/src/alerting/components/builder/AlertBuilder.tsx
ui/src/alerting/components/builder/CheckMatchingRulesCard.tsx
ui/src/shared/utils/featureFlag.ts

Closes https://github.com/influxdata/influxdb/issues/15806
Adds 'matching rules' card to check creation page, which displays any notification rules that "would match" the tags that are on statuses generated by the check. The back end work is in https://github.com/influxdata/influxdb/pull/16328.

feat(ui): Add matching rules card to alert builder

---

CHANGELOG.md
kv/notification_rule.go
kv/notification_rule_test.go
notification/rule/rule.go
notification/rule/rule_test.go

some awkward looping made it hard to reason about the correctness of the tag matching algorithm. Upon closer inspection of a test through the debugger, it was returning false negatives and was causing issues in the `FindNotificiationRules` call.
seeing issues with this upstream, these tests can be enabled. The issue was in tag matcher. Tests pass here and should pass upstream now.
solves for the failures here: https://github.com/influxdata/influxdb/pull/16379
Closes #14799

fix: enable skipped tests for notification rules and fixup issue in tag matcher

---

kv/check.go
kv/encode.go
kv/notification_endpoint.go
kv/store_base.go
kv/store_base_test.go
kv/store_index.go
kv/store_index_test.go
kv/variable.go
testing/notification_endpoint.go

this is to make the new `kv.Entity` more generic so that it can be used in more broad applications.

chore(kv): refactor kv.Entity to provide interface for PK and unique keys

---

CHANGELOG.md
ui/package.json
ui/src/shared/components/XYPlot.tsx
ui/yarn.lock

Closes https://github.com/influxdata/influxdb/issues/16111
When "Stacked" is selected, we ask giraffe to calculate the data for the y-axis. Then we memoize this result to prevent the graph from infinitely re-rendering itself from `useVisDomainSettings`

fix(ui): extend the y-axis when stacked line option is selected

---

cmd/influxd/launcher/launcher.go

Fixes #10628 again
Manually tested #10628 is fixed:
- run influxd
- lsof to verify influxd is listening on port 4222
- git checkout master
- `go test ./cmd/...` fails due to NATS port 4222
- git checkout jgm-fix-nats (this branch)
- `got test ./cmd/...` does not fail

fix(tests): make sure NATS port is open for unit tests

---

CHANGELOG.md
ui/src/buckets/components/Retention.tsx

Currently, when choosing to apply retention limits to new buckets, the default retention period is 72 hours (3 days).
With recent increases to the maximum retention period for free-tier cloud users, we'd like the default to be 30 days instead for all users.
Before:
After:

feat(bucket): Increase default retention to 30 days

---

CHANGELOG.md
ui/cypress/e2e/explorer.test.ts
ui/src/timeMachine/reducers/index.ts

Closes #16369
Calling `buildActiveQuery` after `SET_BUILDER_TAG_VALUES` was resetting the query whenever the timerange was being set
The rationale for calling the `buildActiveQuery` on `SET_BUILDER_TAG_VALUES` was to ensure that:
> it's to build the query when grouping and selecting fields
This seems to already be occurring whenever a query is drafted and is unnecessary. Since this change had originally broken an e2e explorer test, removing this line passes the test.
One key metric to ensure that this is in fact a stable solution would be to:
>  look at switching between filtering and grouping in the query builder

fix(ui): removed buildActiveQuery func to prevent queries from being reset when timeranges are selected.

---

go.mod
go.sum
query/promql/internal/promqltests/go.mod
query/promql/internal/promqltests/go.sum
query/stdlib/influxdata/influxdb/rules.go
query/stdlib/testing/testing.go

The storage engine isn't capable of sending back empty tables when a
series is empty. Because of this, we disable the push down and let flux
do the filtering in the case where there is a filter and it is specified
to keep the empty tables.
Related to influxdata/flux#2287.

feat(query/stdlib): prevent a filter push down if the filter needs to keep empty tables

---

CHANGELOG.md
CONTRIBUTING.md
DEVELOPMENT.MD
README.md

Closes #16407
* Update docs to reference Go 1.13
* Create developer guide
[View the rendered markdown file here](https://github.com/influxdata/influxdb/blob/13805208c18a76c99a868e24e1d608f046f9f27d/DEVELOPMENT.MD)

docs: add developer guide

---

CHANGELOG.md
http/query_handler.go
query/request.go
query/service_test.go

Add source to query request for logging purposes.

feat(query): add source to query request for logging purposes

---

CHANGELOG.md
ui/package.json
ui/yarn.lock

Closes https://github.com/influxdata/influxdb/issues/16395
Updates giraffe to use new logic to determine the optimal spacing of the time labels and use as many labels as d3 can fit in the time axis.

fix(ui): update giraffe

---

.circleci/config.yml
go.mod

Closes #16414 
Updates the ci and build and the go.mod to require go 1.13

chore: update to go 1.13

---

ui/src/shared/constants/fluxFunctions.ts

Added the `onEmpty` parameter to the `filter()` function in `fluxFunctions.ts`.

chore(flux): added onEmpty parameter to flux filter function

---

CHANGELOG.md
ui/.eslintrc.js
ui/src/shared/utils/formatStatValue.ts
ui/src/shared/utils/preventNegativeZero.test.ts
ui/src/shared/utils/preventNegativeZero.ts

Closes https://github.com/influxdata/influxdb/issues/16306
- Prevent negative zero
- Allow zero to have decimal places

fix(ui): Prevent negative zero and allow zero with decimal places

---

cmd/influxd/main.go
query/stdlib/influxdata/influxdb/source.go

This pull request has another part in flux as https://github.com/influxdata/flux/pull/1992
We already have opentracing in influxdb but on a more coarse level. This pull request added more granular opentracing [spans](https://opentracing.io/docs/overview/spans/#what-is-a-span) into the query execution engine. Now, with opentracing enabled, you will be able to see the sources/transformations involved in queries and see how many of them / how much time do they take.
You can visualize the spans by using Jaeger. The following command starts a Jaeger instance using Docker:
```bash
docker run -d --name jaeger \
-e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
-p 5775:5775/udp \
-p 6831:6831/udp \
-p 6832:6832/udp \
-p 5778:5778 \
-p 16686:16686 \
-p 14268:14268 \
-p 9411:9411 \ …
```

feat: opentracing in query execution runtime

---

http/query.go
http/query_handler.go
query/encode.go
query/request.go

This adds a dialect to discard the output in the response of a query.
When somebody specifies `Accept: /dev/null` in his request's headers, the query will return a plain text response containing `null`.
Issue: #14514

feat(query): add dialect to discard output

---

CHANGELOG.md
ui/cypress/e2e/onboarding.test.ts
ui/src/alerting/actions/checks.ts

fix(ui): add honeybadger error report to checks (#16443)

---

CHANGELOG.md
ui/src/dataLoaders/components/BucketsDropdown.tsx
ui/src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx
ui/src/onboarding/actions/index.ts
ui/src/onboarding/reducers/index.ts
ui/src/telegrafs/components/Collectors.tsx

Closes #15659 
Data loader bucket selection was being made in several places, and though the dropdown buckets were filtered to remove system buckets, the default selection was choosing among all buckets. This PR filters system buckets before selecting default.

fix(dataloader-buckets): default bucket selection should not be system bucket

---

ui/cypress/e2e/explorer.test.ts
ui/src/tasks/components/TasksOptionsBucketDropdown.tsx

Closes #16452
Closes #16454
just adds a check to see if we've already selected that bad boy before we try and select it again, and again, and again, and.... [ MAXIMUM CALL STACK EXCEEDED ]

fix: stop looping so hard

---

CHANGELOG.md
http/task_service.go

This PR fixes a bug where manually running a task failed with an "EOF" error. The solution was to check for the length of the request body, and only decode the body if it is not empty. We also check that the response body is not too long, since there is only one expected property in the body at most.

fix(tasks): add content length check to decode force run request

---

delete.go
tsdb/tsm1/cache_test.go
tsdb/tsm1/engine_delete_prefix.go
tsdb/tsm1/file_store.go
tsdb/tsm1/predicate.go

Fixes #15817
This commit addresses several data-races on the `tsm1.Predicate` type
that were causing a live-lock or similar in rare cases during a delete.
Because `tsm1/FileStore.Apply` executes concurrently across TSM files, the state of the delete's predicate was being unsafely mutated.
This commit adds a `Clone` method to the `influxdb.Predicate` type, which should be used whenever an `influxdb.Predicate` implementation needs to be used concurrently. This means that a copy of the predicate is used for each TSM file that is having the delete applied to it.

fix(storage): remove data-races in delete predicates

---

kv/check.go
kv/store_base.go
kv/store_base_test.go
kv/store_index.go
kv/store_index_test.go

Closes #16462
drops the unnecessary concurrency in the store iterator

fix(kv): fix issue with cursor not closing inside TX

---

cmd/influx/pkg.go

switch from the wonky `::` to `=` delimiter
Closes #16476

fix(influx): update influx pkg cmd flag secrets delimter to match vault

---

CHANGELOG.md
errors.go
http/errors.go
http/write_handler.go
http/write_handler_test.go

Closes #13100
This enables support for a limit on the points batch size in bytes (after compression if compression is enabled).
To configure this the functional option `WithMaxBatchSizeByte(50 * 1024 * 1024)` should be used when constructing a `http.WriteHandler`.

feat(http): add configurable limit to points batch size on write endpoint

---

CONTRIBUTING.md
README.md

Closes #16372 
This change just recommend using the `make` targets for testing etc. Using the `go` command requires a good understand of build tags and cgo to use correctly. 
We have a script `env` at the root of the repo and I tried using it, but it doesn't quite do what we need. It successfully setups up the CGO env vars, but all uses of the `go` command still need the `-tags libflux` args added to them and the script can't do that easily. So for now I just recommend using the `make` command. 
Once we can remove the libflux build tag it should make things much easier and the `go` commands should work better in conjunction with the `env` script.

docs(readme): Update README and CONTRIBUTING for Rust dependencies

---

.gitignore
chronograf/bolt/internal/internal.go
chronograf/bolt/internal/internal.pb.go
chronograf/bolt/internal/internal.proto
chronograf/chronograf.go
cmd/chronograf-migrator/README.md
cmd/chronograf-migrator/dashboard.go
cmd/chronograf-migrator/main.go
pkger/clone_resource.go
pkger/models.go
pkger/service.go
pkger/service_test.go

This PR introduces `chonograf-migrator`, a tool that is used to migrate 1.x chronograf dashboards into their 2.0 equivalents. We attempt to compile any existing influxql queries into influx. If we are unable to, we add the influxql as a comment and note the error that we encountered while compiling.

feat: add tool to migrate 1.x chronograf dashboards and variables

---

cmd/influx/main.go

fix(influx): drop persistent pre run func taht double prints help cmd

---

CHANGELOG.md
cmd/influx/pkg.go
http/pkger_http_server.go
http/pkger_http_server_test.go
http/swagger.yml
pkger/models.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go

the following is now possible from the CLI(same in REST API):
`influx pkg -u https://gist.githubusercontent.com/jsteenb2/3a3b2b5fcbd6179b2494c2b54aa2feb0/raw/1717709ffadbeed5dfc88ff4cac5bf912c6930bf/bucket_pkg_json`
one other small thing that mades it way in, noticed while testing the diff and sumary http responses have nulls for some of the slices. I want to normalize all those to provide `[]` if none are there. Guaranteeing no nulls.

feat(pkger): add ability to supply a pkg from a url

---

ui/cypress/e2e/explorer.test.ts
ui/cypress/e2e/tasks.test.ts
ui/src/dashboards/actions/index.ts
ui/src/dashboards/apis/index.ts
ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
ui/src/dashboards/reducers/dashboards.test.ts
ui/src/dashboards/reducers/dashboards.ts
ui/src/dashboards/utils/dashboardSwitcherLinks.ts
ui/src/onboarding/components/CompletionQuickStartButton.tsx
ui/src/onboarding/components/CompletionStep.tsx
ui/src/organizations/apis/index.ts
ui/src/shared/utils/resourceToTemplate.ts
ui/src/templates/api/index.ts
ui/src/types/dashboards.ts
ui/src/types/templates.ts

Closes #16393
Current API and types are dependent upon deprecated client API
Refactored the variables to utilize the new oats generated client API

chore(ui): refactored dashboards client API to oats generated types and API

---

ui/src/alerting/actions/checks.ts
ui/src/alerting/actions/notifications/rules.ts
ui/src/alerting/components/builder/CheckMetaCard.tsx
ui/src/alerting/components/builder/DeadmanConditions.tsx
ui/src/alerting/components/notifications/EditRuleOverlay.tsx
ui/src/alerting/components/notifications/RuleOverlayContents.tsx
ui/src/alerting/components/notifications/RuleSchedule.tsx
ui/src/alerting/components/notifications/utils/index.ts
ui/src/alerting/constants/index.ts
ui/src/alerting/utils/checkValidate.ts
ui/src/dashboards/utils/time.ts
ui/src/shared/components/DurationInput.tsx
ui/src/shared/utils/duration.test.tsx
ui/src/shared/utils/duration.ts
ui/src/timeMachine/constants/queryBuilder.ts

Added duration input component to the check every field.
It's nice in that it gives user examples to choose from without limiting options available to them. 
The duration input does not update the value in the field in redux if it is not valid, but does update local state so that the invalid input is displayed to user in an error state.

fix(durations): Add duration input that checks input validity as duration

---

ui/src/timeMachine/components/TagSelector.tsx
ui/src/timeMachine/selectors/index.test.ts
ui/src/timeMachine/selectors/index.ts

Closes #16518 
Hides the selector to search for keys when grouping. Also shows all the keys that are no longer searchable

feat: query builder - hide the keys search dropdown when grouping

---

tsdb/tsm1/predicate.go
tsdb/tsm1/predicate_test.go

Fixes #15817
This PR addresses a case where a predicate matching against a series key could get stuck in an infinite—and very hot—loop. 
Hitting this loop resulted in the `influxd` process getting stuck and being unresponsive.
Here is an example of a series key that would cause the infinite loop: `hi\ yo\ =w\,est,server=a`. The predicate matcher would use the `predicatePopTagEscape` function to attempt to pop off the first tag key/pair.
1) The function looks for the first comma, which is at `index 11`. It's the first comma in the tag value.
2) The function determines this comma is actually escaped and intends to continue finding next comma in the rest of the key after this escaped comma: `est,server=a`
3) The function finds a comma at `index 3` in this partial key (`t,s`).
4) The function …

fix(storage): prevent infinite loop in predicate matcher

---

CHANGELOG.md
tsdb/engine/tsm1/engine.go

Closes #11776 
Upgrades compaction log message to warning.

fix(tsm1): Compaction log error

---

ui/src/shared/utils/pageTitles.ts

Instead of org names in page titles there was a `''` string, this PR makes it good again

fix(ui): fix appearance of org names in page titles

---

http/api_handler.go
http/write_handler.go
http/write_handler_test.go

This PR uses the `ParsePointsWithOptions` API for parsing a batch of points submitted to the `/api/v2/write` HTTP endpoint. 
All limits are disabled by default, but may be configured by setting values for the documented fields of the `APIBackend` structure.

feat(http): Enforce limits in write handler and expose config options

---

cmd/influx/pkg.go
cmd/influx/pkg_test.go
http/pkger_http_server.go
http/pkger_http_server_test.go
http/swagger.yml
pkger/models.go
pkger/parser.go

also makes the yaml decoder the default. To foten we end up in application/octet-stream
which is the default for many different mime types. This provides a mechanism
around that so that when the automagical detection fails it can allow the user
to provide it via the CLI.
Closes issues I noticed during testing since the url bits got merged

fix(pkger): fixes issue where pkger can't discern the mime/content type of a package

---

CHANGELOG.md
cmd/influx/bucket_test.go
cmd/influx/main.go
cmd/influx/organization_test.go
cmd/influx/setup.go
cmd/influx/user.go
cmd/influx/user_test.go

Closes #16440
Add the feature, so cli can update user's password. manually tested.

feat(cmd/influx): update password in cli

---

CHANGELOG.md
ui/src/alerting/components/builder/CheckMetaCard.tsx
ui/src/alerting/components/notifications/RuleSchedule.tsx
ui/src/shared/components/DurationInput.tsx
ui/src/shared/constants/timeRanges.ts
ui/src/timeMachine/components/FunctionSelector.tsx
ui/src/timeMachine/constants/queryBuilder.ts
ui/src/types/queries.ts
ui/src/variables/utils/getWindowVars.ts

Closes #16354 
If user selects `auto` for aggregate window interval, in the Data Explorer or Cell Editor Overlay, the UI calculates an appropriate aggregate window interval for the query duration. The appropriate value is selected so that the UI doesn't request more points than can be displayed by the visulization. Before  this PR we would divide the query duration by the number of pixels that can be displayed- which would result in aggregate windows which were not rounded like 0.83s for a query range of 5m. In this PR the aggregate window intervals are rounded to "more reasonable" values. 
Along the way, the aggregate window interval input was changed to a duration input, so that users can select any valid duration, and so that the duration is properly labeled and indicated to user. 
| …

feat(ui) More reasonable aggregate window intervals for selected query durations

---

ui/src/shared/components/Gauge.tsx
ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx
ui/src/shared/utils/formatStatValue.ts
ui/src/shared/utils/view.ts
ui/src/timeMachine/actions/index.ts
ui/src/timeMachine/components/view_options/Affixes.tsx
ui/src/timeMachine/components/view_options/SingleStatOptions.tsx
ui/src/timeMachine/selectors/index.ts

Fixes issues related to recent PRs.
- localeFormattedValue does not need to be coerced, because it is not the return value of the function
- run prettier

fix(ui): make localeFormattedValue less confusing

---

Makefile
ui/package.json

This is a clone of #16551 that i messed up because i zigged instead of zagged
The Problem
Firstly, webpack did not exit with a non-zero status code if there was a TypeScript compilation error. Secondly, the Makefile subdirs target loop did not consider the exit codes of each sub-make, so it didn't stop. Therefore, only the final status code bubbled up in CI. See this for more details.
Solution
Copy answers from stack overflow.
Related: #16468

fix: bail webpack build on tsc error

---

CHANGELOG.md
ui/src/cloud/components/CheckoutButton.tsx
ui/src/pageLayout/components/CloudNav.tsx

Closes #16568
Replace billingURL with checkoutURL on upgrade CTAs so the user is taken to the checkout flow instead of the Billing page.

fix(influxdb): swap billingURL with checkoutURL

---

http/query.go
http/query_handler.go
query/encode.go
query/encode_test.go

kept both `no-content` and `...-with-error`.
This also adds proper testing.

feat(query): add 'Prefer: return-no-content-with-error' behavior

---

cmd/influx/main.go

fix(influx): fix description for reuable org/ord id type

---

cmd/influx/pkg.go

Nitpickiest PR I've ever made 🙃
CLI arguments should start with a capital letter and should not have a period if a single sentence in length.

fix(pkg): normalize cli arg format

---

ui/Makefile

Closes #16464
Updates #16468
the problem seems to be caused by having a stale dev environment. this adds a yarn install before running the tests to ensure that all dependencies are up to date.

fix: keep libraries up to date

---

task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go

This PR introduces an improvement that allows for a situation where tasks continue to run and update the `LatestCompleted` date but fail to update the `LatestScheduled`. When a task is added to the scheduler, scheduling begins from the later of either `LatestScheduled` or `LatestCompleted`.
This situation was not anticipated whilst both the old and new scheduler existed as an option. Specifically, the old scheduler did not maintain the `LatestScheduled` field, so running it and then returning to the new scheduler could result in tasks rerunning.

fix(tasks): use LatestCompleted if LatestScheduled is behind

---

.circleci/config.yml
ui/cypress/e2e/variables.test.ts

this turns prettier back on in the jstest target on circleci. should be the last step in getting CI back in order

fix: enabling prettier

---

tsdb/tsm1/array_cursor.gen.go
tsdb/tsm1/array_cursor.gen.go.tmpl
tsdb/tsm1/array_cursor_test.go

This PR fixes an issue where multiple blocks for the same series key were having
values truncated when they were being read into an empty buffer.
The current cursor reader code has an optimisation that incorrectly
assumes the incoming array will be limited to 1,000 values (the maximum
block size), but arrays can contain values from multiple matching
blocks for the same index entry.  Therefore, it's perfectly possible for the array being read to have more than 1,000 values and not fit entirely into the buffer.

fix(storage): ensure all block data returned

---

CHANGELOG.md
bolt/kv.go
inmem/kv.go
kv/store.go
testing/kv.go

Closes https://github.com/influxdata/influxdb/issues/16534
This introduces the new `CursorOption` known as `WithCursorPrefix(prefix)`.
This option configures the returned cursor to only return keys with the provided prefix.
When using `ForwardCursor` with this new option. The provided `seek` bytes must be prefixed with the provided `prefix` bytes, otherwise the forward cursor implementation should return `kv.ErrSeekMissingPrefix` error and a nil cursor.

feat(kv): add support for prefixed cursor search

---

CHANGELOG.md
authorizer/authorize.go
authorizer/backup.go
authz.go
backup.go
bolt/bbolt.go
bolt/kv.go
cmd/influx/backup.go
cmd/influx/main.go
cmd/influxd/launcher/engine.go
cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/launcher_helpers.go
cmd/influxd/main.go
cmd/influxd/restore/command.go
http/api_handler.go
http/backup_service.go
http/client.go
inmem/kv.go
kv/backup.go
kv/service_test.go
kv/store.go
mock/kv.go
storage/engine.go
tsdb/tsm1/engine.go
tsdb/tsm1/file_store.go
tsdb/tsm1/file_store_test.go

Closes #15603
Closes #15604
Closes #15605
Closes #15606
Implements online backup and offline restore.
To test functionality it was necessary to combine #15558 and #16352 into one PR based on recent master/HEAD. Then:
- wrote some data
- read it back
- backed it up with `influx backup`
- terminated influxd
- restored it with `influxd restore` to existing database directory
- started influxd, read it back, terminated influxd
- restored it with `influxd restore` to empty database directory
- started influxd, read it back, terminated influxd
Check before merging:

feat(storage): implement backup and restore

---

bolt/kv.go
inmem/kv.go
kv/bucket.go

Use the new forward cursor when finding all buckets in the bucket service.
This also fixes a bug we discovered while trying to use the few forward cursor. This bug was in the way the bolt implementation performed descending curse.

fix(kv): use forward cursor in find all buckets

---

ui/src/shared/components/cells/CellContext.tsx

Closes #16619
seems like a functional component wasn't completely migrated during #16569

fix: allow edit of cells

---

ui/src/variables/components/VariableFormContext.tsx

Closes #16622
no idea how this one didn't show up earlier, but it's all about props not overriding when they needed to

fix: clear variable editor on close

---

tsdb/index/inmem/inmem.go
tsdb/store_test.go

Prior to this change, new series would be added to the series file
before checking the series cardinality limit. If the limit was exceeded,
the write was rejected even though the series had already been added to
the series file.

fix(tsm1): improve series cardinality limit

---

ui/src/dashboards/components/dashboard_index/DashboardCard.tsx

Closes #16620
no idea how i missed that when i was in here the other day fixing the same thing for clone and export, but it was still expecting the dashboard id to come from the url instead of relying on the props

fix: allow dashboard description editing

---

ui/src/shared/components/cells/Cells.tsx

Closes influxdata/honeybadger-errors#149
Closes influxdata/honeybadger-errors#148
Closes influxdata/honeybadger-errors#144
idk if this is the right place to put it, but it feels like you'd want to return all of the cells with the selector in case you wanted to display the loading state differently.

fix: ensure cells are done before mapping them

---

CHANGELOG.md
bucket.go
context/token.go
context/token_test.go
kv/bucket.go
kv/org.go
kv/service.go
kv/task.go
organization.go
resource/noop/resource_logger.go
resource/resource.go

This change introduces a resource audit logger to track changes to resources in the system. The operations on tasks, buckets and organizations are augmented to use this logger. 
No implementation is currently provided.

feat: resource log

---

cmd/influx/pkg.go
http/pkger_http_server.go
http/pkger_http_server_test.go

little idea that spawned out of demo question

feat(pkger): add support for inspecting url paths to grab extension for pkger decoding

---

CHANGELOG.md
storage/engine.go

Helps influxdata/idpe#5720
It is possible to collect metrics after engine has closed. This checks for engine closed to prevent nil pointer exception.

fix(storage): check engine closed before collecting index metrics

---

CHANGELOG.md
models/points.go
models/points_test.go

This is an improvement to the validation done when parsing points. Certain tag keys are reserved and should not be used. This adds a validation step to the points parsing in the models package.
This step throws an error whenever any of the following tag keys are used:
`"\xff"`
`"\x00"`
`"_measurement"`
`"_field"`
`"time"`
Before this change was introduced the parsing benchmarks looked like this:
```
goos: darwin
goarch: amd64
pkg: github.com/influxdata/influxdb/models
BenchmarkParsePointsTagsSorted2-16       	 2000000	       664 ns/op	  76.76 MB/s
BenchmarkParsePointsTagsSorted5-16       	 2000000	       855 ns/op	  97.07 MB/s
BenchmarkParsePointsTagsSorted10-16      	 1000000	      1206 ns/op	 118.54 MB/s
BenchmarkParsePointsTagsUnSorted2-16     	 2000000	       789 ns/op	  64.57 MB/s …
```

fix(models): filter out reserved tag keys in points parser

---

ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx

Closes influxdata/honeybadger-errors#131
this broke when this.availableLabels[0] didn't exist because it didn't account for a list being empty AND the popover being open

fix: dont crash on malformed label data

---

go.mod
go.sum
query/promql/internal/promqltests/go.mod
query/promql/internal/promqltests/go.sum
query/stdlib/experimental/to.go
query/stdlib/influxdata/influxdb/from.go
query/stdlib/influxdata/influxdb/to.go
query/stdlib/influxdata/influxdb/v1/databases.go
task/options/options.go

This PR merges commits into `feat/use-algo-w` which is currently the same as the latest master.
1. Update `go.mod` to point at the latest commit on the `flux` `feat/use-algo-w` branch
2. Updates function registration to use new lookup method
3. Updates usages of `Type` methods

refactor(query): let influxdb build against algo-w branch

---

CHANGELOG.md
http/telegraf.go
http/telegraf_test.go

fix(http): fix /telegrafs panics when using org=org_name parameter

---

cmd/influx/bucket_test.go
cmd/influx/organization_test.go
cmd/influx/pkg_test.go
cmd/influx/user_test.go

this is inspired by: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd_test.go#L73

chore(influx): fixup flag setting in influx tests to use args

---

pkger/models.go
pkger/parser_test.go

Closes #
issue that came in from @russorat when trying to export from cloud. There are signle stat adn single stat plus line charts that do not have text colors. This allows for that.

fix(pkger): drop text color requirement for single stat charts

---

CHANGELOG.md
ui/src/shared/utils/featureFlag.ts
ui/src/timeMachine/components/TagSelector.tsx
ui/src/timeMachine/reducers/index.test.ts
ui/src/timeMachine/selectors/index.test.ts
ui/src/timeMachine/selectors/index.ts
ui/src/timeMachine/utils/queryBuilder.test.ts
ui/src/timeMachine/utils/queryBuilder.ts

Removes the `queryBuilderGrouping` flag, effectively turning the feature on.

chore: remove queryBuilderGrouping flag

---

CHANGELOG.md
http/bucket_service.go
http/check_service.go
http/dashboard_service.go
http/helpers.go
http/notification_endpoint.go
http/notification_rule.go
http/onboarding.go
http/org_service.go
http/org_service_test.go
http/paging.go
http/paging_test.go
http/user_service.go
http/variable_service.go
kit/transport/http/api.go
kit/transport/http/api_test.go
kit/transport/http/error_handler.go
testing/organization_service.go

Closes #16498
add a reusable api type for decoding and responding to http requests. Improves error handling.
Work is broken up into 2 commits, first one for creating the API decoder/responder, and the 2nd for using it within the org service. The new API type normalizes handling of decoding issues and failed write issues amongst. It is also very extensible, more we can do with it than what meets the eye.

fix(http): improve error handling and response to api consumer for org service

---

tsdb/tsm1/predicate.go
tsdb/tsm1/predicate_test.go

Helps https://github.com/influxdata/idpe/issues/5783
This pull request fixes predicate clone so that the initial clone clones the state but inner nodes all share the same cloned state.

fix(tsdb): Fix predicate clone

---

pkg/encoding/simple8b/encoding.go

Cherry-pick of 8f665ec from 1.8.
* fix(simple8b): disable checkptr on batch decodes
* perf: improve performance of simple8b encoding
```
name                      old time/op    new time/op    delta
EncodeAll/1_bit-24          35.8µs ± 2%    35.8µs ± 2%     ~     (p=0.887 n=10+7)
EncodeAll/2_bits-24         35.7µs ± 4%    35.6µs ± 3%     ~     (p=0.684 n=10+10)
EncodeAll/3_bits-24         36.5µs ± 3%    36.4µs ± 4%     ~     (p=0.780 n=10+9)
EncodeAll/4_bits-24         36.4µs ± 3%    37.8µs ± 2%   +3.71%  (p=0.000 n=10+10)
EncodeAll/5_bits-24         38.0µs ± 3%    38.3µs ± 2%     ~     (p=0.280 n=10+10)
EncodeAll/6_bits-24         39.4µs ± 1%    38.5µs ± 2%   -2.43%  (p=0.001 n=10+9)
EncodeAll/7_bits-24         39.6µs ± 3%    38.9µs ± 3%   -1.83%  (p=0.029 n=10+10)
EncodeAll/8_bits-24 …
```

fix(storage): simple8b passes checkptr (#15512)

---

CHANGELOG.md
tsdb/engine/tsm1/engine.go

When an InfluxDB database is very busy writing new points the backup
the process can fail because it can not write a new snapshot.
The error is: `operation timed out with error: create snapshot: snapshot in progress`.
This happens because InfluxDB takes almost "continuously" a snapshot
from the cache caused by the high number of points ingested.
This PR skips snapshots if the `snapshotter` does not come available
after three attempts when a backup is requested.
The backup won't contain the data in the cache or WAL.
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

chore(tsm1): skip WriteSnapshot during backup if snapshotter is busy

---

cmd/influx/pkg_test.go
cmd/influxd/launcher/pkger_test.go
http/swagger.yml
pkger/clone_resource.go
pkger/http_remote_service.go
pkger/http_server.go
pkger/models.go
pkger/models_test.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/testdata/env_refs.yml

references: #16472
this is the first (of many) PRs to add environment references for pkgs. This enables pkgs to ask for user input, be it http or cli.

feat(pkger): add support for env references for buckets

---

cmd/influxd/launcher/pkger_test.go
pkger/models.go
pkger/models_test.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/testdata/env_refs.yml

rest of resource metadata getting the env refs for pkger

feat(pkger): add env ref fields for remaining resources

---

CHANGELOG.md
kv/notification_rule.go
testing/notification_rule.go

Closes #16293
When sending a patching request without status, notification rule will try to dereference the status, which results a panic. This ticket fixes the issue, adding a new test case for patching without status

fix(kv): fix patching panics

---

cmd/influxd/launcher/pkger_test.go
pkger/parser.go
pkger/parser_test.go
pkger/testdata/env_refs.yml

More pkger goodness, this one enables env refs for all associations

feat(pkger): add env refs for associations

---

bolt/kv.go
inmem/kv.go
kv/store.go
kv/task.go
testing/kv.go

Add support for `WithCursorSkipFirstItem()` which steps over the first item in the cursor.
This is useful for seeking after the provided `seek` bytes.

feat(kv): add cursor option skip first item

---

kit/transport/http/api_test.go
kit/transport/http/middleware.go
kit/transport/http/middleware_test.go
pkg/testttp/http.go

Browsers send a preflight `OPTIONS` request with a `Origin` header to validate the CORS policy before sending the real request. Currently we block this from working, disallowing any developer to build their own tooling with the Influx API

fix(CORS): accept OPTIONS preflight request with Origin header
