- tsdb/series_file.go
- tsdb/series_file_test.go
Backports #10541
Closes #10540
> backport: Fix open/close race in SeriesFile

- ui/src/authorizations/actions/index.ts
- ui/src/shared/copy/notifications.ts
> Display notifications when token is deleted or updated

- CHANGELOG.md
- ui/src/clockface/components/card_select/CardSelectCard.scss
> Fix jumbled labels on card select cards

- tsdb/series_segment.go
> fix(series file): Sync series segment after truncate (#13836)

- bolt/organization.go
- http/org_service.go
- inmem/organization_service.go
- kv/org.go
- organization.go
- testing/organization_service.go
Closes https://github.com/influxdata/influxdb/issues/10925
fixed the error message
> fix(influxdb): invalid filter error

- ui/src/cloud/utils/limits.ts
> Interpret a maxAllowed of zero as no limits on asset.

- task/backend/bolt/bolt.go
- task/backend/storetest/storetest.go
> fix(task): filter tasks by after param

- http/errors.go
If the error returned was normal text instead of JSON, the JSON parsing
would fail and the JSON error would be returned instead of the actual
error.
This has been modified so that when it fails to parse the text as JSON,
it will construct an error with the actual text and then wrap it using
the JSON error.
> fix(http): do not discard non-json encoded errors when using `CheckError`

- http/README.md
Update our HTTP handler style guide.
> chore(http): update error handling example in readme

- ui/cypress/e2e/variables.test.ts
- ui/src/variables/components/VariableCard.tsx
- ui/src/variables/components/VariableContextMenu.tsx
- ui/src/variables/components/VariableList.tsx
- ui/src/variables/components/__snapshots__/Variables.test.tsx.snap
> Update Variables tab to use ResourceList instead of IndexList

- ui/src/pageLayout/components/AccountNavSubItem.tsx
Closes #13211 
Reload page on org switch
> Reload page on switch org

- models/tagkeysset_test.go
- query/stdlib/testing/end_to_end_test.go
- storage/reads/group_resultset_test.go
- tsdb/tsi1/index_test.go
> fix(query): skip failing end to end tests

- ui/src/authorizations/components/BucketsSelector.tsx
- ui/src/shared/components/selectorList/SelectorList.scss
- ui/src/shared/components/selectorList/SelectorList.tsx
- ui/src/shared/components/selectorList/SelectorListBody.tsx
- ui/src/shared/components/selectorList/SelectorListEmpty.tsx
- ui/src/shared/components/selectorList/SelectorListHeader.tsx
- ui/src/shared/components/selectorList/SelectorListMenu.tsx
- ui/src/style/chronograf.scss
Closes #13912 
Created a copy of buildercard component in shared folder to make it more generic for selecting from a list in ui
> Update buckets token overlay to use generic SelectorList component

- ui/package-lock.json
- ui/package.json
- ui/src/shared/components/HistogramContainer.tsx
- ui/src/shared/components/XYContainer.tsx
Just bug fixes in this release.
> Upgrade vis library to 0.7.0

- bolt/bbolt.go
- bolt/bucket.go
- bolt/dashboard.go
- bolt/dashboard_test.go
- bolt/organization.go
- bolt/user.go
- cmd/influxd/launcher/launcher.go
- crud_log.go
- document.go
- http/dashboard_test.go
- http/document_service.go
- http/document_test.go
- http/swagger.yml
- inmem/dashboard.go
- inmem/dashboard_test.go
- inmem/service.go
- kv/bucket.go
- kv/dashboard.go
- kv/dashboard_test.go
- kv/document.go
- kv/kvlog.go
- kv/org.go
- kv/service.go
- kv/user.go
- mock/document_service.go
- mock/generators.go
- testing/dashboards.go
- testing/document.go
Closes https://github.com/influxdata/influxdb/issues/13489
Closes https://github.com/influxdata/influxdb/issues/13488
add audit log for document response,
> feat(http): add audit log

- bolt/organization.go
- inmem/organization_service.go
- kv/org.go
- organization.go
- testing/organization_service.go
> feat(http): update org description

- bolt/bucket.go
- bolt/bucket_test.go
- bolt/onboarding_test.go
- bucket.go
- http/bucket_service.go
- http/bucket_test.go
- http/onboarding_test.go
- http/swagger.yml
- inmem/bucket_service.go
- inmem/bucket_test.go
- inmem/onboarding_test.go
- kv/bucket.go
- kv/bucket_test.go
- kv/onboarding_test.go
- testing/bucket_service.go
- testing/onboarding.go
Closes #https://github.com/influxdata/influxdb/issues/13475
Closes #https://github.com/influxdata/influxdb/issues/13476
Add created and updated for bucket resource
> feat(influxdb): bucket created and updated time

- CHANGELOG.md
- ui/src/shared/components/XYContainer.tsx
- ui/src/shared/utils/vis.ts
- ui/src/timeMachine/components/view_options/Geom.tsx
- ui/src/types/dashboards.ts
> Expose smooth interpolation option for line graphs

- ui/package-lock.json
- ui/package.json
- ui/src/cloud/utils/overrides.ts
- ui/src/index.tsx
> Add honeybadger overrides for cloud

- bolt/dashboard.go
- inmem/dashboard.go
- kv/dashboard.go
- kv/document.go
when a document or a dashboard was created, the updated time should be same with its created time.
> fix(kv): updatedAt should be updated as well

- ui/src/timeMachine/constants/visGraphics.tsx
Add an icon for heatmap visualization type.
> add heatmap icon

- http/swagger.yml
- query/stdlib/testing/end_to_end_test.go
This adds operationId to the swagger template.
For the client generation in golang, operationId defines the function names.
> chore(swagger): update swagger to include operationId

- ui/src/me/components/Support.tsx
> fix(ui): use correct templates for support links

- http/swagger.yml
> chore(swagger): fix a few swagger typos

- http/swagger.yml
> fix(http): remove accept header from query request swagger

- ui/package-lock.json
- ui/src/timeMachine/components/WindowSelector.tsx
- ui/src/timeMachine/constants/queryBuilder.ts
- ui/src/timeMachine/utils/queryBuilder.test.ts
> feat: add "none" selection to query builder function selector aggreation

- CHANGELOG.md
> updating changelog with alpha 10 release date

- ui/package-lock.json
- ui/src/shared/components/RefreshingView.tsx
- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/components/cells/Cell.tsx
- ui/src/shared/components/cells/Cells.tsx
- ui/src/shared/components/cells/Dashboards.scss
- ui/src/shared/components/cells/View.tsx
Closes #14049 
Used the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to determine if a cell is coming into the viewport.  If a cell is not in view do not render the contents or fetch any data.
> perf: dashboard cell and view rendering

- http/task_test.go
- kv/task.go
> fix(task): Ensure tasks clean up user resource maps

- task/backend/analytical_storage.go
> fix(task): Apply grease to the analytic system

- ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx
- ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx
- ui/src/dashboards/selectors/index.ts
- ui/src/shared/components/DefaultErrorMessage.tsx
- ui/src/shared/components/ErrorBoundary.tsx
- ui/src/shared/decorators/errors.tsx
- ui/src/types/shared.ts
- ui/src/variables/components/VariableForm.tsx
Closes #14074
Some more info in the commit messages.
> Populate "Save As Variable" modal with current query

- ui/src/shared/components/dateRangePicker/DatePicker.tsx
> Accept all date formats that are supported by flux in date picker

- ui/src/dashboards/components/createFromTemplateOverlay/DashboardCreateFromTemplateOverlay.tsx
- ui/src/shared/utils/resourceToTemplate.test.ts
- ui/src/shared/utils/resourceToTemplate.ts
Closes #https://github.com/influxdata/influxdb/issues/14116
> Add type to template meta created from resources

- http/telegraf.go
- http/telegraf_test.go
> fix(http): rename OrgID to orgID

- ui/package-lock.json
- ui/package.json
- ui/src/clockface/components/resource_list/ResourceDescription.scss
- ui/src/clockface/components/resource_list/ResourceDescription.tsx
- ui/src/shared/utils/downloads.test.ts
- ui/src/templates/components/StaticTemplateCard.tsx
- ui/src/templates/components/StaticTemplatesList.tsx
- ui/src/templates/components/TemplatesList.tsx
- ui/src/templates/components/TemplatesPage.tsx
- ui/src/utils/ajax.ts
Add tabs and descriptions to Templates Page
> Add tabs and descriptions to Templates Page

- ui/package-lock.json
- ui/package.json
- ui/src/clockface/components/resource_list/ResourceDescription.scss
- ui/src/clockface/components/resource_list/ResourceDescription.tsx
- ui/src/index.tsx
- ui/src/shared/utils/downloads.test.ts
- ui/src/templates/actions/index.ts
- ui/src/templates/components/StaticTemplateCard.tsx
- ui/src/templates/components/StaticTemplateViewOverlay.tsx
- ui/src/templates/components/StaticTemplatesList.tsx
- ui/src/templates/components/TemplatesList.tsx
- ui/src/templates/components/TemplatesPage.tsx
- ui/src/templates/constants/defaultTemplates.ts
- ui/src/utils/ajax.ts
> Static templates

- ui/package-lock.json
- ui/package.json
> Upgrade giraffe to 0.12.1

- CHANGELOG.md
> Update CHANGELOG.md for alpha 13

- ui/src/templates/components/TemplateCard.tsx
Description section of #14098 
Add editable descriptions to user templates.
> Add User Template Descriptions

- ui/cypress/e2e/labels.test.ts
- ui/src/labels/components/LabelsTab.tsx
- ui/src/shared/components/Filter.test.tsx
- ui/src/shared/components/Filter.tsx
> fix: sorting label by description

- ui/package-lock.json
- ui/package.json
> Upgrade influxdb-client-js and influxdb-templates

- ui/src/pageLayout/components/CloudNav.tsx
__Describe your proposed changes here.__
Add a cloud sub nav and feature flag for the billing and usage items.
> feat(ui/cloud_nav): adds and feature flags billing/usage sub navs

- tsdb/tsm1/file_store.go
This should have cut off TSM file levels at 4+.
> fix(storage): reduce tsm level metrics cardinality

- ui/package.json
- ui/src/tasks/actions/index.ts
- ui/src/templates/api/index.ts
- ui/src/utils/api.ts
- ui/yarn.lock
Upgrades giraffe and influxdb-client-js dependencies.
Makes a few source tweaks to accommodate changes in the new client version.
> chore(ui): upgrade dependencies

- CHANGELOG.md
- ui/src/tasks/actions/index.ts
- ui/src/tasks/components/TaskTokenDropdown.tsx
Closes #14019 
Updating a task will update the selected token
Updated task token dropdown to display 'Name this token' when token doesn't have a description
> Add the ability to update a task token

- tsdb/tsm1/engine.go
- tsdb/tsm1/metrics.go
Adds read metrics to package-level prometheus collectors.
> chore(tsdb): Fix read metrics declaration.

- ui/src/shared/constants/fluxFunctions.ts
Updated the in-dashboard Flux function documentation with new Flux functions.
> Added new functions to Flux functions list

- http/query_handler_test.go
Fix the master conflict issue. when latest got merged
> fix(http): query handler conflict

- storage/reads/table.gen.go
- storage/reads/table.gen.go.tmpl
- storage/reads/table.go
> fix(storage/reads): storage table implementation passes table tests

- dbrp_mapping.go
- inmem/dbrp_mapping_service.go
- testing/dbrp_mapping.go
Closes https://github.com/influxdata/idpe/issues/3888
dbrp not found should use influxdb.Error, and return 404 not found.
also fixed some linter issues and some other error code issues in dbrp mapping.
> fix(inmem): fix dbrp not found

- services/httpd/handler.go
Closes #14261
Backport of #10591
> Fix Prometheus read panic

- cmd/influx_inspect/verify/tsm/verify.go
Closes #9763 
Replaces panic with error handling in `influx_inspect verify` if the storage directory cannot be read from.
> fix(storage): replace panic with error in influx_inspect verify

- ui/src/dataExplorer/components/SaveAsTaskForm.tsx
> Fix filtering bug in tokens

- ui/src/shared/utils/featureFlag.ts
- ui/src/timeMachine/components/view_options/LineOptions.tsx
- ui/src/timeMachine/components/view_options/ScatterOptions.tsx
- ui/src/timeMachine/components/view_options/ViewTypeDropdown.tsx
- ui/src/timeMachine/constants/visGraphics.tsx
> Remove feature flags from vis types and options

- CHANGELOG.md
updating changelog for alpha 15
> updating changelog for alpha 15

- ui/src/alerting/containers/AlertHistoryIndex.tsx
- ui/src/alerting/containers/AlertingIndex.tsx
- ui/src/index.tsx
- ui/src/pageLayout/containers/Nav.tsx
- ui/src/shared/utils/featureFlag.ts
> Add initial alerting routes and containers

- http/swagger.yml
> Add alerts and notification swagger definitions

- Gopkg.lock
- Gopkg.toml
> Upgrade to flux v0.36.2

- http/auth_service.go
- http/bucket_service.go
- http/dashboard_service.go
- http/document_service.go
- http/label_service.go
- http/onboarding.go
- http/org_service.go
- http/scraper_service.go
- http/source_service.go
- http/task_service.go
- http/telegraf.go
- http/user_resource_mapping_service.go
- http/user_service.go
- http/variable_service.go
Closes #https://github.com/influxdata/idpe/issues/2939
> feat(http): add auth debug log

- tsdb/series_partition.go
add `key` field to `keyRange`.
so no need to read SeriesKey from the segment file.
> fix(storage): add key field to keyRange

- query/stdlib/influxdata/influxdb/buckets.go
- query/stdlib/influxdata/influxdb/from.go
- query/stdlib/influxdata/influxdb/operators.go
- query/stdlib/influxdata/influxdb/source.go
- query/stdlib/influxdata/influxdb/to.go
Update the influxdb sources to be annotated with flux error codes. This
will enable us to identify different response codes for these
operations.
#14340
> feat(query/stdlib): update influxdb sources to use flux error codes

- kv/service.go
replacing https://github.com/influxdata/influxdb/pull/14364 with another pattern
> refactor(tasks): add Checker to Service struct and document

- http/swagger.yml
Dashboard Query and Query builder specs were out of sync with implementation and UI. 
attn: @kelwang @jademcgough who might be building alerts and notifications apis, since they contain dashboard query data structure.
> Fix dashboard query swagger definition to reflect reality

- ui/package.json
- ui/src/shared/utils/filterUnusedVars.ts
- ui/src/types/dashboards.ts
- ui/yarn.lock
> Consume types from client 1.5

- ui/src/shared/components/code_mirror/_ThemeTimeMachine.scss
- ui/src/shared/constants/codeMirrorModes.ts
- ui/src/shared/constants/fluxFunctions.ts
Addresses #14350
Changed color of objects so they don't appear as strings.
> fix(ui/flux): correct map example

- tests/server_delete_test.go
- tsdb/index/inmem/inmem.go
- tsdb/shard_test.go
Backport https://github.com/influxdata/influxdb/pull/14266
> Fix issue where fields re-appear after DROP MEASUREMENT

- .github/stale.yml
> fixing stalebot config

- http/swagger.yml
Closes https://github.com/influxdata/idpe/issues/583
> chore(tasks): add swagger for canceling task runs

- http/task_service.go
- http/task_service_test.go
> fix(http): task runs and logs no longer use task token

- storage/engine.go
- storage/retention.go
- storage/retention_test.go
- tsdb/tsm1/engine.go
- tsdb/tsm1/engine_delete_prefix_test.go
- tsdb/tsm1/engine_test.go
Fixes for https://github.com/influxdata/influxdb/pull/14400
Closes #14399
> fix(storage): move retention snapshot out of per bucket calls

- .github/semantic.yml
This configuration ensure that all commits are validated not just the PR title.
> chore(semantic): add configuration for semantic PR bot

- ui/package.json
- ui/yarn.lock
> fix(ui): upgrade giraffe to 0.16.1

- authorizer/notification_rule.go
- authorizer/notification_rule_test.go
- authz.go
- cmd/influx/authorization.go
- cmd/influxd/launcher/launcher.go
- crud_log.go
- http/api_handler.go
- http/notification_rule.go
- http/notification_rule_test.go
- http/paging.go
- http/swagger.yml
- http/telegraf.go
- kv/notification_rule.go
- kv/notification_rule_test.go
- kv/service.go
- mock/notification_rule_store.go
- notification.go
- notification/rule/pagerduty.go
- notification/rule/rule.go
- notification/rule/rule_test.go
- notification/rule/slack.go
- notification/rule/smtp.go
- notification/status.go
- notification/status_test.go
- notification/tag.go
- testing/notification_rule.go
- testing/onboarding.go
Closes https://github.com/influxdata/influxdb/issues/14327
Add notification rule, package, kv, http, authorizer, launcher,  cli, and testings
based on swagger doc.
> feat: Add notification rule

- CHANGELOG.md
> chore: move changelog update to correct release

- CHANGELOG.md
> feat(influxdb): add missing change log

- storage/reads/datatypes/storage_common.pb.go
- ui/src/shared/constants/fluxFunctions.ts
> Added documentation for new Flux functions

- ui/src/shared/constants/fluxFunctions.ts
> Added exponentialMovingAverage documentation

- CHANGELOG.md
updates changelog for PR: https://github.com/influxdata/influxdb/pull/14356
> chore(tasks): update changelog

- .circleci/config.yml
> add bzr to release build

- task/backend/executor/executor.go
- task/backend/scheduler.go
Revert extra changes from #14417
> fix(task): push task backend logging messages back to debug

- .circleci/config.yml
> ci(nightly): install protoc

- ui/__mocks__/@influxdata/flux-parser.ts
- ui/package.json
- ui/src/bootstrap.ts
- ui/src/shared/apis/query.ts
- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/utils/insertPreambleInScript.ts
- ui/src/timeMachine/actions/queries.ts
- ui/src/variables/utils/ValueFetcher.ts
- ui/src/variables/utils/getWindowVars.ts
- ui/tsconfig.json
- ui/webpack.common.ts
- ui/yarn.lock
> feat(ui): wasm flux parser

- authorizer/notification_rule.go
- authorizer/notification_rule_test.go
- http/notification_rule.go
- http/swagger.yml
- kv/notification_rule.go
- mock/notification_rule_store.go
- notification.go
- notification/rule/rule.go
- testing/notification_rule.go
> feat(http): patch notification rule

- dashboard.go
> fix(influxdb): rename json option "omitEmpty" to "omitempty"

- CHANGELOG.md
- ui/src/telegrafs/components/TelegrafExplainer.tsx
> fix(components/TelegrafExplainer): Update link to Telegraf docs

- ui/src/tasks/components/TaskTokenDropdown.tsx
- ui/src/templates/components/createFromTemplateOverlay/TemplateBrowserList.tsx
> fix(component/TemplateBrowserList): sort list of templates alphabetically

- ui/src/dashboards/components/EditVEO.tsx
Previously, opening the VEO for a cell on a dashboard would cause the view for the cell on the dashboard to reload. In turn, this would cause the dashboard cell to crash.
This commit updates the logic for opening the VEO so that the view is only reloaded when necessary.
Closes #14508
> fix(ui): prevent dashboard cell crash when editing cell

- ui/package.json
- ui/yarn.lock
See https://github.com/influxdata/giraffe/pull/102
Closes #14504
> fix(ui): upgrade giraffe to 0.16.2

- authorizer/check.go
- authorizer/check_test.go
- authz.go
- check.go
- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- http/check_service.go
- http/check_test.go
- http/swagger.yml
- kv/check.go
- kv/check_test.go
- kv/service.go
- mock/check_service.go
- notification/check/check.go
- notification/check/check_test.go
- notification/check/deadman.go
- notification/check/threshold.go
- notification/tag.go
- notification/tag_test.go
- testing/checks.go
- testing/util.go
Closes https://github.com/influxdata/influxdb/issues/14325
add check struct, kv, http, authorizer, influxd launcher and testings. based on the swagger file design.
> feat: Add check API

- tsdb/tsm1/engine_schema.go
- tsdb/tsm1/engine_schema_test.go
> test(tsm1): TagKeys/TagValues stops scanning when context is cancelled

- ui/src/authorizations/utils/permissions.test.ts
- ui/src/authorizations/utils/permissions.ts
- ui/src/dataExplorer/components/SaveAsTaskForm.tsx
- ui/src/shared/utils/ast.ts
- ui/src/shared/utils/getMinDurationFromAST.ts
- ui/src/shared/utils/getReadBuckets.test.ts
- ui/src/shared/utils/getReadBuckets.ts
Closes #14226
See commits for details
> fix(ui): improve relevant token detection when saving a query as a task

- ui/src/Signin.tsx
- ui/src/timeMachine/apis/QueryBuilderFetcher.ts
- ui/webpack.prod.ts
> fix(ui): silence console spew

- ui/package.json
- ui/webpack.common.ts
- ui/webpack.dev.ts
- ui/webpack.prod.ts
- ui/yarn.lock
> build(webpack): fix hashing and css hmr

- query/statement_rewriter.go
- query/statement_rewriter_test.go
Backport https://github.com/influxdata/influxdb/pull/14444 to 1.7
> fix(query): make show series exact cardinality count only distinct series

- http/task_service.go
- kv/task.go
> fix(task): check ErrTaskNotFound err

- ui/cypress/e2e/buckets.test.ts
- ui/src/buckets/components/BucketCard.tsx
- ui/src/buckets/components/Retention.tsx
- ui/src/buckets/components/UpdateBucketOverlay.tsx
> fix: bucket save

- go.mod
- go.sum
- query/stdlib/testing/testing.go
> Update to Flux v0.38.0

- ui/src/alerting/components/CheckAlertingButton.tsx
- ui/src/timeMachine/components/AlertingButton.tsx
> Add return behavior to Alerting buttons

- ui/package.json
- ui/src/Logout.tsx
- ui/src/onboarding/actions/index.ts
- ui/src/onboarding/components/SigninForm.tsx
- ui/yarn.lock
> refactor(ui): migrate signin/signout to generated client

- dashboard.go
- ui/src/alerting/components/CheckCard.tsx
- ui/src/alerting/components/builder/CheckMetaCard.tsx
- ui/src/alerting/components/builder/RemoveButton.tsx
- ui/src/alerting/constants/index.ts
- ui/src/alerting/reducers/checks.ts
- ui/src/dashboards/actions/index.ts
- ui/src/dashboards/components/EditVEO.tsx
- ui/src/dashboards/components/NewVEO.tsx
- ui/src/dashboards/selectors/index.ts
- ui/src/shared/components/CheckPlot.tsx
- ui/src/shared/components/RefreshingView.tsx
- ui/src/shared/components/ViewSwitcher.tsx
- ui/src/shared/components/cells/Cell.tsx
- ui/src/shared/components/cells/View.tsx
- ui/src/timeMachine/actions/index.ts
- ui/src/timeMachine/components/AlertingButton.tsx
- ui/src/timeMachine/components/Vis.tsx
- ui/src/timeMachine/reducers/index.ts
> Fix checks bugs

- ui/src/alerting/components/EditCheckEO.tsx
- ui/src/alerting/components/builder/RemoveButton.tsx
- ui/src/dashboards/actions/views.ts
- ui/src/dashboards/components/EditVEO.tsx
- ui/src/dashboards/components/NewVEO.tsx
- ui/src/style/chronograf.scss
- ui/src/timeMachine/actions/index.ts
- ui/src/timeMachine/components/AddCheckDialog.scss
- ui/src/timeMachine/components/AddCheckDialog.tsx
- ui/src/timeMachine/components/AlertingButton.tsx
- ui/src/timeMachine/components/TimeMachine.tsx
- ui/src/timeMachine/components/TimeMachineAlerting.tsx
- ui/src/timeMachine/components/VisOptionsButton.tsx
- ui/src/timeMachine/constants/index.ts
- ui/src/timeMachine/reducers/index.ts
- ui/src/types/timeMachine.ts
>  feat(ui): show dialog when adding check to cell

- query/stdlib/testing/end_to_end_test.go
- query/stdlib/testing/testing.go
> fix(flux): Fix hanging test by ensuring results are read

- ui/src/shared/constants/fluxFunctions.ts
Add new Flux functions for Flux 0.36 - 0.39
> fix(docs): Flux function updates

- .circleci/config.yml
> add protoc

- http/check_test.go
- notification/check/check.go
- notification/check/check_test.go
- notification/check/threshold.go
- testing/checks.go
Reverts influxdata/influxdb#14660
> Revert "feat(notification/check): convert threshold type"

- ui/src/shared/constants/fluxFunctions.ts
> fix(fluxFunctions): fix spelling in logBins example

- http/check_test.go
- notification/check/check_test.go
- notification/check/threshold.go
- notification/check/threshold_test.go
- testing/checks.go
> fix(notification/check): convert threshold type

- authorizer/notification_endpoint.go
- authorizer/notification_endpoint_test.go
- check.go
- cmd/influx/authorization.go
- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- http/notification_endpoint.go
- http/notification_endpoint_test.go
- kv/notification_endpoint.go
- kv/notification_endpoint_test.go
- kv/secret.go
- kv/service.go
- mock/notification_endpoint_service.go
- notification.go
- notification/endpoint/endpoint.go
- notification/endpoint/endpoint_test.go
- notification/endpoint/pagerduty.go
- notification/endpoint/slack.go
- notification/endpoint/webhook.go
- notification_endpoint.go
- secret.go
- secret_test.go
- testing/notification_endpoint.go
- testing/notification_rule.go
Closes https://github.com/influxdata/influxdb/issues/14329
add notification endpoint, package, kv, http, authorizer, launcher, test cases.
> feat(influxdb): Add notification endpoint

- authorizer/check.go
- authorizer/check_test.go
- check.go
- http/check_service.go
- http/check_test.go
- http/swagger.yml
- kv/check.go
- kv/check_test.go
- mock/check_service.go
- notification/check/check.go
- notification/check/check_test.go
- testing/checks.go
remove the authorization id dependency, replace with ownerID
fixed skipped test cases
> fix(notification/check): remove authorizationID

- notification/status.go
Closes #14644 
Fixed order of notifications level.
> fix(notification/status): notification order

- check.go
- http/check_service.go
- http/check_test.go
- notification/check/check.go
- testing/checks.go
Closes #14331 
Passes the ownerID to created a task.
> feat(check): pass ownerID to task on create

- kv/notification_rule.go
- notification/rule/http.go
Fixes issues @kelwang pointed out in https://github.com/influxdata/influxdb/pull/14695
> fix(notification/rule): remove println and add json struct tag for http

- notification/endpoint/pagerduty.go
fix the response of the pager duty routing key
> fix(notification/pagerduty): routingKey encode

- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/cypress/support/commands.ts
- ui/src/alerting/actions/notifications/endpoints.ts
- ui/src/alerting/components/endpoints/EditEndpointOverlay.tsx
- ui/src/alerting/components/endpoints/EndpointCard.tsx
- ui/src/alerting/components/notifications/utils/index.ts
- ui/src/alerting/constants/index.ts
- ui/src/alerting/reducers/notifications/endpoints.ts
- ui/src/index.tsx
- ui/src/shared/components/dashed_button/DashedButton.tsx
> feat(alerts): introduce edit endpoint overlay

- http/swagger.yml
- notification/check/threshold.go
- ui/src/alerting/actions/checks.ts
- ui/src/alerting/components/CheckAlertingButton.tsx
- ui/src/alerting/components/EditCheckEO.tsx
- ui/src/alerting/components/notifications/RuleMessage.tsx
- ui/src/alerting/components/notifications/RuleMessageContents.tsx
- ui/src/alerting/components/notifications/utils/index.ts
- ui/src/dashboards/components/EditVEO.tsx
- ui/src/dashboards/components/NewVEO.tsx
- ui/src/dashboards/selectors/index.ts
- ui/src/shared/components/CheckPlot.tsx
- ui/src/shared/components/cells/Cell.tsx
- ui/src/timeMachine/components/AlertingButton.tsx
- ui/src/timeMachine/components/Queries.tsx
- ui/src/timeMachine/utils/queryBuilder.ts
Will likely want to squash this into a single commit since there's a bunch of wip commits in here.
> fix(notification_rules): add misc fixes to UI and backend for alerts and notification

- storage/metrics.go
- storage/retention.go
- storage/retention_test.go
Fixes https://github.com/influxdata/idpe/issues/4366
> chore(storage): bring back storage_retention_checks_total

- http/check_service.go
- http/check_test.go
- http/swagger.yml
Closes https://github.com/influxdata/influxdb/issues/14326
Add the endpoint in http, with test, swagger
> feat(http): checks query endpoint

- go.mod
- go.sum
- notification/check/threshold.go
- notification/check/threshold_test.go
- notification/rule/http.go
- notification/rule/http_test.go
- notification/rule/slack.go
- notification/rule/slack_test.go
- task/options/options.go
> refactor(notification): rename alerts package to monitor in flux

- kv/task.go
- kv/task_test.go
If a task is created and the auth associated is removed
lookup of tasks currently fail. This is bad behavior.
We should expect to be able to at least see and delete task's that
have old auth.
> fix(task): fix failover function for task auth to not fail

- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/src/alerting/actions/checks.ts
- ui/src/alerting/actions/notifications/endpoints.ts
- ui/src/alerting/actions/notifications/rules.ts
- ui/src/alerting/components/CheckCard.tsx
- ui/src/alerting/components/CheckCardContext.tsx
- ui/src/alerting/components/endpoints/EndpointCard.tsx
- ui/src/alerting/components/endpoints/EndpointCardMenu.tsx
- ui/src/alerting/components/notifications/RuleCard.tsx
- ui/src/alerting/components/notifications/RuleCardContext.tsx
- ui/src/shared/copy/notifications.ts
> feat: Alerting context menus

- ui/src/pageLayout/containers/Nav.tsx
> fix(ui): exclude scrapers nav link in cloud

- ui/src/alerting/components/builder/CheckConditionsCard.tsx
- ui/src/alerting/components/builder/CheckLevelsDropdown.tsx
- ui/src/alerting/components/builder/DeadmanConditions.tsx
- ui/src/alerting/constants/index.ts
> Add Deadman Conditions Card

- ui/src/shared/constants/fluxFunctions.ts
> fix(fluxFunctions): fix flux function docs

- ui/src/alerting/components/CheckAlertingButton.tsx
- ui/src/alerting/components/CheckEOHeader.tsx
> Add alerting button

- http/notification_rule_test.go
- http/swagger.yml
- notification/rule/rule_test.go
- notification/status.go
- notification/status_test.go
- ui/src/alerting/components/notifications/RuleLevelsDropdown.tsx
- ui/src/alerting/components/notifications/RuleOverlay.actions.tsx
- ui/src/alerting/components/notifications/RuleOverlay.reducer.tsx
- ui/src/alerting/components/notifications/StatusLevels.tsx
- ui/src/alerting/components/notifications/utils/index.ts
- ui/src/types/alerting.ts
> Add Any to rule levels

- go.mod
- go.sum
- query/stdlib/testing/testing.go
Skips a test that requires special dependencies to pass.
> build(flux): upgrade to Flux v0.42.0

- ui/package.json
- ui/src/alerting/components/CheckAlertingButton.tsx
- ui/yarn.lock
> chore(ui): upgrade Clockface to 0.0.28

- CHANGELOG.md
- ui/src/buckets/components/NoBucketsWarning.scss
- ui/src/buckets/components/NoBucketsWarning.tsx
- ui/src/style/chronograf.scss
- ui/src/telegrafs/components/Collectors.tsx
> fix(ui): Polish no buckets warning in telegraf tab

- tsdb/tsi1/partition.go
Previously the TSI partition would panic if a compaction was started while `Wait()` was waiting. This commit removes the previous wait group and replaces it with a simple counter. The `Wait()` function now polls the counter until it reaches zero.
> fix(storage): replace TSI compaction wait group with counter.

- ui/src/alerting/components/builder/CheckMatchingRulesCard.tsx
- ui/src/alerting/components/builder/MatchingRuleCard.tsx
> feat: Add matching rules cards

- kv/notification_rule.go
- testing/notification_rule.go
Fix the etcd notification rule testing, which is not skipped
> fix(kv): fix notification rule testing

- ui/src/alerting/components/CheckAlertingButton.tsx
> Refrain from showing popover if query is alertable

- notification/flux/ast.go
- notification/rule/http.go
- notification/rule/http_test.go
- notification/rule/rule.go
- notification/rule/slack.go
- notification/rule/slack_test.go
- testing/notification_rule.go
Closes https://github.com/influxdata/influxdb/issues/14772
> fix(notification/rule): add support for status rules

- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/src/alerting/components/CheckCard.tsx
- ui/src/alerting/components/CheckCardContext.tsx
- ui/src/alerting/components/endpoints/EndpointCard.tsx
- ui/src/alerting/components/endpoints/EndpointCardMenu.tsx
- ui/src/alerting/components/notifications/RuleCard.tsx
- ui/src/alerting/components/notifications/RuleCardContext.tsx
> Switch edit and view actions

- ui/src/alerting/utils/history.ts
Previously it was displaying oldest to newest.
> fix(ui): sort alerting history page from newest to oldest

- task/backend/analytical_storage.go
Resolves an invariant that tag keys must always be sorted in TSM.
> fix(task): Create tags using NewTags to ensure they are sorted

- notification/flux/ast.go
- notification/rule/http.go
- notification/rule/http_test.go
- notification/rule/rule.go
- notification/rule/slack.go
- notification/rule/slack_test.go
The three commits included in the PR fix misc issues with slack notification rules.
> fix(notification/rule): fix slack notification rules

- query/stdlib/influxdata/influxdb/v1/databases.go
The `v1.databases()` call did not correctly filter buckets based on
auth. Fortunately, it did not cause any improper permissions such as
allowing a person to see buckets that they had no read access to.
The error instead was that if a user did not have read access to one of
the buckets that was returned, the entire command would fail rather than
filter out the bucket that didn't have permissions.
This changes it so that if the user doesn't gets an unauthorized error
when accessing a bucket, it will filter it from the list instead of
failing. It also changes it so the error message is marked as
`ENotFound` instead of as an internal error.
> fix(query/stdlib): use auth correctly in the v1.databases() call

- http/notification_rule.go
- http/swagger.yml
Closes https://github.com/influxdata/influxdb/issues/14328
Add http endpoint for notification rule query
> feat(http): add rule query endpoint

- ui/src/shared/components/CheckPlot.tsx
> fix(ui): use linear interpolation in check plots

- ui/src/alerting/components/AlertingIndex.scss
- ui/src/alerting/components/CheckAlertingButton.tsx
- ui/src/alerting/components/CheckEOHeader.tsx
- ui/src/timeMachine/utils/queryBuilder.ts
Closes #14940 
- Add numbers to radio buttons in check editor
- Make radio buttons bigger
- Make it more obvious what the next step is in order to define a check
> refactor(ui): polish check editor header

- ui/src/shared/utils/featureFlag.ts
Toggles the `alerting` feature flag to true for cloud env.
> feat(ui/src/shared/utils): toggle alerting feature flag for cloud

- ui/src/alerting/components/notifications/RulesColumn.tsx
- ui/src/alerting/constants/index.ts
- ui/src/me/components/GettingStarted.tsx
Closes #14956
Closes #14938
Closes #14948
> fix(copy): minor copy updates

- http/swagger.yml
Closes https://github.com/influxdata/influxdb/issues/14966
fix the swagger, will also need to regenerate the client libarary
> fix(http): fix check update swagger

- authorizer/bucket.go
- bucket.go
- http/write_handler.go
Updates #14907
Prevent writes to system buckets over http.
> feat(http): block writes to system buckets

- SECURITY.md
> feat(security): add SECURITY.md file

- notification/status.go
Closes https://github.com/influxdata/influxdb/issues/14978
> fix(notification): fix the any checkLevel  string

- notification/rule/pagerduty.go
- notification/rule/pagerduty_test.go
Adds support for a pagerduty notification rule. Although I don't think that the pagerduty package exists for flux yet.
> feat(notification/rule): add pagerduty notification rule

- ui/src/alerting/components/notifications/utils/index.ts
- ui/src/alerting/constants/index.ts
- ui/src/timeMachine/actions/index.ts
- ui/src/timeMachine/reducers/index.ts
> chore(alerting): add default message templates

- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/timeMachine/components/QueryBuilder.tsx
> fix: move system buckets to end of list

- http/notification_endpoint_test.go
- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/src/alerting/components/endpoints/EndpointOptionsSlack.tsx
- ui/src/alerting/components/notifications/SlackMessage.tsx
- ui/src/alerting/constants/index.ts
Closes https://github.com/influxdata/influxdb/issues/14996
> fix(slack): remove option for token in UI

- pkg/limiter/write_test.go
- pkg/limiter/writer.go
> fix(storage): guard against compaction burst throughput limit (#14985)

- http/notification_endpoint_test.go
- http/swagger.yml
- notification/endpoint/endpoint_test.go
- notification/endpoint/http.go
Closes https://github.com/influxdata/influxdb/issues/15003
This is the crud update to add cutomized headers for http endpoint. 
Additional prs are needed for generated flux updates. 
cc @russorat
> feat(notification/endpoint): add headers to http endpoint

- ui/src/alerting/components/endpoints/EndpointOptionsHTTP.tsx
> fix(http): remove template option from http endpoint

- notification/check/check.go
- notification/check/check_test.go
- notification/duration.go
- notification/rule/rule.go
- notification/rule/rule_test.go
Closes https://github.com/influxdata/influxdb/issues/14944
> fix(notification): offset must be smaller than every

- ui/src/alerting/components/notifications/TagRuleOperatorDropdown.tsx
Closes https://github.com/influxdata/influxdb/issues/15030
> fix(tagOps): remove options not implemented

- ui/src/alerting/constants/index.ts
- ui/src/alerting/utils/history.ts
- ui/src/alerting/utils/vis.ts
- ui/src/shared/components/CheckPlot.tsx
- ui/tsconfig.json
See commits for issue links.
The fix for #14965 is a bit crude; it gets around the immediate issue of a threshold marker being rendered outside of the visible plot region, but is still a bit wonky when you drag it back (mouse diverges from threshold position).
> Miscellaneous alerting fixes

- ui/package.json
- ui/src/shared/parsing/flux/response.ts
- ui/src/timeMachine/utils/rawFluxDataTable.test.ts
- ui/src/timeMachine/utils/rawFluxDataTable.ts
- ui/yarn.lock
> fix(ui): handle parsing Flux strings containing newlines

- bucket.go
- http/bucket_service.go
- http/bucket_test.go
- http/swagger.yml
- inmem/bucket_service.go
- kv/bucket.go
Buckets will now return a type of `user` or `system`.
> feat(http): Add bucket types

- ui/src/buckets/components/BucketCard.tsx
- ui/src/buckets/components/BucketContextMenu.tsx
- ui/src/cloud/actions/limits.ts
Closes #
- Update bucket list to hide rename and delete buttons for system buckets
- Filter out system buckets from the list when checking if limits have been exceeded
> Update bucket system

- notification/check/threshold.go
- notification/check/threshold_test.go
- notification/flux/ast.go
Closes https://github.com/influxdata/influxdb/issues/15065
fixed the outside range and test cases
> fix(notification/check): range outside logic

- ui/cypress/e2e/checks.test.ts
- ui/cypress/support/commands.ts
- ui/src/alerting/components/CheckAlertingButton.tsx
- ui/src/alerting/components/CheckEOHeader.tsx
- ui/src/timeMachine/utils/queryBuilder.ts
Closes #14894 
I will update the e2e tests to only run once for each test.
> fix(alerting): disable save button if query is invalid

- notification/endpoint/http.go
Closes https://github.com/influxdata/influxdb/issues/15071
bearere token key should include primary key
manually verified
> fix(notification/endpoint): http bearer token

- ui/src/alerting/components/AlertsColumn.tsx
- ui/src/alerting/components/CheckCards.tsx
- ui/src/alerting/components/ChecksColumn.tsx
- ui/src/alerting/components/EndpointsColumn.tsx
- ui/src/alerting/components/endpoints/EndpointCards.tsx
- ui/src/alerting/components/notifications/RuleCards.tsx
- ui/src/alerting/components/notifications/RuleMessage.tsx
- ui/src/alerting/components/notifications/RulesColumn.tsx
- ui/src/alerting/selectors/index.ts
> chore(alerts): alphabetize endpoints in rule dropdown

- ui/cypress/e2e/collectors.test.ts
- ui/src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx
- ui/src/dataLoaders/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap
- ui/src/telegrafs/components/CollectorCard.tsx
- ui/src/telegrafs/components/TelegrafInstructionsOverlay.tsx
Closes #4589
Also enabled + tweaked an e2e test that was skipped for reasons unknown to me.
> fix(ui): fix telegraf setup link

- ui/src/alerting/components/notifications/StatusLevels.tsx
> fix(alerts): remove status change functionality

- ui/src/alerting/components/ChecksColumn.tsx
- ui/src/alerting/components/EndpointsColumn.tsx
- ui/src/alerting/components/builder/CheckMessageCard.tsx
- ui/src/alerting/components/builder/HelpButton.tsx
- ui/src/alerting/components/notifications/RulesColumn.tsx
> refactor(ui): add real links to alerting documentation

- ui/src/telegrafs/components/CollectorCard.tsx
- ui/src/telegrafs/components/TelegrafConfigOverlay.tsx
Co-Authored-By: Andrew Watkins <watts@influxdb.com>
> fix(telegraf/configs): route to correct path for telegraf collectors

- ui/src/shared/constants/fluxFunctions.ts
Added new functions to `fluxFunctions.ts`.
> Updated Flux functions documentation

- ui/src/alerting/components/builder/AlertBuilder.scss
- ui/src/buckets/components/BucketCard.tsx
- ui/src/timeMachine/components/TimeMachineAlerting.tsx
- Remove all action buttons from system buckets
- Add `Raw Data` toggle to check builder
- Shrink panels so they fit on a smaller screen (screenshot is 1280x720)
> refactor(ui): polish bucket card & check builder

- task.go
`UpdateFlux` is called during updates within the K/V store, and may panic when parsing Flux scripts, which is undesirable. This update uses `defer` / `recover` to handle these.
We will look for an opportunity to log the panic, so they can be tracked down and fixed.
Closes #15107
> fix(task): Ensure Flux parser panics are handled in UpdateFlux

- notification/rule/rule.go
- notification/rule/slack_test.go
This PR special cases `any` level rules so that they will alert on all
conditions.
> fix(notification/rule): alert on all statuses if for any status rule

- query/control/controller_test.go
We are planning to change the allocator interface within flux to use the
arrow allocator. To make the release easier, this updates the test in
advance to use the arrow allocator instead of the to be changed memory
allocator interface from flux.
Related to influxdata/flux#1861.
> refactor(query/control): update a test to use the arrow allocator interface

- ui/src/me/components/UserPageHeader.tsx
Update welcome header for cloud. Change product name from `InfluxCloud` to `InfluxDB Cloud`.
> chore(ui): Update Cloud welcome header

- tsdb/index/tsi1/partition.go
Backport of #14902
Previously the TSI partition would panic if a compaction was started while Wait() was waiting. This commit removes the previous wait group and replaces it with a simple counter. The Wait() function now polls the counter until it reaches zero.
> fix(tsi1): replace TSI compaction wait group with counter

- go.mod
- go.sum
- query/preauthorizer_test.go
- query/spec.go
This has the change to the caller of `WalkIR` to pass in dependencies, and I also added Stuart's unit test from https://github.com/influxdata/idpe/issues/4737.
> chore: update to Flux v0.47.1

- ui/src/alerting/actions/checks.ts
- ui/src/alerting/components/NewDeadmanCheckEO.tsx
- ui/src/alerting/components/NewThresholdCheckEO.tsx
- ui/src/shared/utils/view.ts
trying to edit a check was erroring.
> Fix edit check bug

- CHANGELOG.md
- ui/src/dashboards/components/DashboardsCardGrid.scss
- ui/src/dashboards/components/dashboard_index/Table.tsx
- ui/src/style/chronograf.scss
The number of columns changes based on the screen size.
> refactor(ui): display dashboard cards in a grid

- storage/retention.go
- tsdb/tsm1/engine_delete_prefix.go
This PR adds some more context when emitting logs and traces around the retention service. I'm hoping it will provide more insight.
> refactor(storage): add more context to traces and logs

- cmd/influx/repl.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/query_test.go
- go.mod
- go.sum
- query/bridges.go
- query/control/controller.go
- query/control/controller_test.go
- query/spec.go
- query/stdlib/influxdata/influxdb/buckets.go
- query/stdlib/influxdata/influxdb/dependencies.go
- query/stdlib/influxdata/influxdb/from.go
- query/stdlib/influxdata/influxdb/metrics.go
- query/stdlib/influxdata/influxdb/source.go
- query/stdlib/influxdata/influxdb/source_test.go
- query/stdlib/influxdata/influxdb/storage.go
- query/stdlib/influxdata/influxdb/to.go
- query/stdlib/influxdata/influxdb/to_test.go
- query/stdlib/influxdata/influxdb/v1/databases.go
- query/stdlib/testing/testing.go
- storage/readservice/service.go
- storage/readservice/store.go
- storage/wal/verifier_test.go
- task/backend/analytical_storage_test.go
- task/options/options.go
- tsdb/tsm1/metrics_test.go
> build(flux): update to Flux v0.48.0

- http/swagger.yml
This includes just a general cleanup of the `swagger.yml`. It resolves some inconsistencies in verbiage, capitalization, etc.
> chore(swagger): general cleanup of swagger.yml

- models/points.go
> fix(storage): add string representation of the Unsigned FieldType

- storage/engine.go
- storage/engine_test.go
- storage/retention_test.go
Closes #15134.
This PR adds the ability to inject a functional option into a `storage.Engine`, for controlling when the retention enforcer will run. The enforcer still sticks to its pre-determined interval, but when attempting to run a retention enforcement it must also call a provided _runnable_ function, which returns only when the task may run.
Previously, if you ran multiple storage engines in parallel (as we do in some environments), then it was not possible to coordinate when engines ran retention. Often they would synchronise
because they started at the same time.
This change will let you specify a blocking function to control when the retention enforcer can run. A very simplistinc function for serialising retention enforcement across multiple
storage engines would look like:
```go …
```
> feat(storage): inject function to control when retention enforcer runs

- ui/cypress/e2e/collectors.test.ts
- ui/cypress/e2e/tokens.test.ts
- ui/package.json
- ui/src/alerting/components/AlertsColumn.tsx
- ui/src/alerting/components/CheckCards.tsx
- ui/src/alerting/components/CheckEOSaveButton.tsx
- ui/src/alerting/components/builder/CheckTagRow.tsx
- ui/src/alerting/components/notifications/RuleOverlayContents.tsx
- ui/src/alerting/components/notifications/StatusRule.tsx
- ui/src/alerting/components/notifications/TagRule.tsx
- ui/src/buckets/components/BucketAddDataButton.tsx
- ui/src/clientLibraries/components/ClientLibraries.tsx
- ui/src/dataLoaders/components/collectorsWizard/select/StreamingSelector.tsx
- ui/src/me/components/account/__snapshots__/Settings.test.tsx.snap
- ui/src/onboarding/components/AdminStep.tsx
- ui/src/organizations/components/OrgProfileTab.tsx
- ui/src/shared/components/question_mark_tooltip/QuestionMarkTooltip.scss
- ui/src/shared/components/question_mark_tooltip/QuestionMarkTooltip.tsx
- ui/src/style/chronograf.scss
- ui/src/templates/components/createFromTemplateOverlay/TemplateBrowserDetails.tsx
- ui/yarn.lock
Reverts influxdata/influxdb#15221
> chore: Revert "chore(ui): upgrade Clockface to 0.0.32"

- client/README.md
> Fix documentation links

- client/README.md
Reverts influxdata/influxdb#14247
> Revert "Fix documentation links"

- client/README.md
This reverts commit 8a463e8b60075364963ec6a70d920715a75b38d9.
Closes #
> Revert "Revert "Fix documentation links (#14247)" (#15236)"

- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/src/alerting/components/endpoints/EndpointOptionsHTTP.tsx
- ui/src/alerting/components/endpoints/EndpointOptionsSlack.tsx
- ui/src/alerting/components/endpoints/EndpointOverlay.reducer.ts
- ui/src/types/alerting.ts
> Fix endpoint type conversions

- http/swagger.yml
- notification/check/check.go
- notification/rule/rule.go
Closes #15184
Remove the cron option from checks/rules.
> fix(alerts): remove the cron option from checks/rules

- Gopkg.lock
- Gopkg.toml
Update the InfluxQL dependency in 1.7.
> chore(influxdb): Update InfluxQL dependency

- cmd/influx/organization.go
- cmd/influx/user_resource_mapping.go
- http/label_service.go
- http/user_resource_mapping_service.go
Closes https://github.com/influxdata/influxdb/issues/14823
fix the base path issue for org members, add/remove.
More cleanup, after we have cli testing frame work merged.
> fix(cmd/influx): org add/remove members

- etc/config.sample.toml
- services/httpd/config.go
- services/httpd/handler.go
- services/httpd/handler_test.go
Helps https://github.com/influxdata/EAR/issues/933
Backports #15222 to 1.7
> feat(httpd): Add option to authenticate debug/pprof and ping endpoints

- notification/rule/http_test.go
- notification/rule/rule.go
Closes https://github.com/influxdata/influxdb/issues/15154
Previously, we niavely incremented the unit associated with the leading
duration. Now, if the unit is `s` we double it. For every other unit, we
increase the magnitude by 1.
> fix(notification/rule): ensure stateChanges rule has enough data in window

- http/check_service.go
Closes https://github.com/influxdata/influxdb/issues/15260
Additionally, we look up a task before clearing the taskID from the
check.
> fix(http): prevent writing to http request multiple times

- http/check_service.go
Fixed handler path for a list of all labels for a check.
> fix(http/check): fix handler path for a list of all labels for a check

- http/auth_service.go
- http/bucket_service.go
- http/check_service.go
- http/dashboard_service.go
- http/document_service.go
- http/label_service.go
- http/notification_endpoint.go
- http/notification_rule.go
- http/onboarding.go
- http/org_service.go
- http/scraper_service.go
- http/source_service.go
- http/task_service.go
- http/telegraf.go
- http/user_resource_mapping_service.go
- http/user_service.go
- http/variable_service.go
after discussion with team, dropping the request logging was decided on instead of scrubbing the req's sensitive data.
Closes #15258 
> chore(http): remove logging of senstive data

- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/src/alerting/components/endpoints/EndpointOptions.tsx
- ui/src/alerting/components/endpoints/EndpointOptionsSlack.tsx
> Remove slack token option from endpoint

- kv/task.go
- kv/task_test.go
When we calculate the next due independently we were including a calculation for the offset. But if you used `cron` and had an offset we were no longer including the offset calculation.
> fix(task): include offset in next due calculation

- http/notification_rule.go
When we clear the private data from the notification rule, it removes the task id. This ends up resulting in an error during encoding for each newly created check.
> fix(http): lookup task before clearing it's id from the rule

- ui/package.json
- ui/src/alerting/constants/history.ts
- ui/src/alerting/constants/index.ts
- ui/src/alerting/utils/history.ts
- ui/src/alerting/utils/statusEvents.ts
- ui/src/shared/components/CheckPlot.tsx
- ui/src/shared/components/EventMarker.tsx
- ui/src/shared/components/EventMarkerTooltip.scss
- ui/src/shared/components/EventMarkerTooltip.tsx
- ui/src/shared/components/EventMarkers.scss
- ui/src/shared/components/EventMarkers.tsx
- ui/src/shared/components/RefreshingView.tsx
- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/components/ViewSwitcher.tsx
- ui/src/shared/constants/events.ts
- ui/src/shared/utils/featureFlag.ts
- ui/src/style/chronograf.scss
- ui/src/timeMachine/actions/queries.ts
- ui/src/timeMachine/components/Vis.tsx
- ui/src/timeMachine/reducers/index.ts
- ui/src/types/alerting.ts
- ui/yarn.lock
> feat: Add event markers

- ui/tsconfig.json
summed up in the title. curious that it didn't show up earlier.
> fix(ui): unblock build by adding jest config to typescript ignore list

- cmd/influxd/launcher/launcher.go
- http/middleware.go
- http/middleware_test.go
- http/platform_handler.go
blacklists endpoints with sensitive data from having the body logged
> fix(logging): blacklist endpoints with sensitive data from logging body

- ui/src/tasks/components/TaskScheduleFormField.tsx
> fix(tasks) Example duration on Task Creation pane.

- vault/secret.go
this fix allows the DI of the vault service configuration. There are place
where we'd like to adminster this with flags, but are locked into
the default env var setup we had previously. One other note is that
calling api.DefaultConfig() calls the ReadEnvironment() method already,
so that was dropped.
> fix(vault): add configuration dependency to vault service constructor

- ui/cypress/e2e/dashboardsIndex.test.ts
- ui/src/dashboards/actions/index.ts
- ui/src/shared/copy/notifications.ts
> fix(dashboards)routing to dashboard page instead of 404 

- ui/README.md
- ui/cypress/e2e/checks.test.ts
- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/cypress/e2e/notificationRules.test.ts
- ui/cypress/fixtures/routes.json
- ui/src/alerting/actions/checks.ts
- ui/src/alerting/components/endpoints/EditEndpointOverlay.tsx
- ui/src/alerting/components/notifications/EditRuleOverlay.tsx
- ui/src/index.tsx
- ui/src/shared/copy/notifications.ts
Closes #14651 
See commit message: aa096ca
> fix(endpoints): route user to alerting index 

- ui/src/shared/constants/fluxFunctions.ts
Updated `fluxFunctions.ts` with experimental packages and functions and functions introduced in Flux 0.50.
> chore(flux): update Flux function docs with experimental and 0.50 functions

- .gitignore
that should not have been there 😬
> fix(ui): adding coverage to ignore file

- README.md
> chore: make documentation slightly more agnostic to OS

- ui/cypress/e2e/dashboardsIndex.test.ts
- ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
> (Fix) Create dashboard from empty state test

- cmd/influxd/launcher/launcher.go
> feat(vault): add flags to influxd for vault configuration

- query/stdlib/testing/testing.go
> chore(query/stdlib): skip flaky tests regarding storage meta queries

- ui/cypress/e2e/notificationEndpoints.test.ts
This is the test to make sure this is working
Closes #15104 
> (test) Client URL optional PagerDuty

- ui/cypress/e2e/notificationEndpoints.test.ts
- ui/cypress/e2e/notificationRules.test.ts
- ui/src/alerting/components/AlertHistoryIndex.tsx
- ui/src/alerting/components/endpoints/EndpointCardMenu.tsx
- ui/src/alerting/components/notifications/RuleCardContext.tsx
This is the fix, the button deleted, and extra tests to go with it, one of the tests im blocked on
Closes #15073 
> (fix)(ui)Remove the ability to clone Endpoints

- ui/package.json
- ui/src/dashboards/utils/tableGraph.ts
- ui/src/dataLoaders/constants/pluginConfigs.ts
- ui/src/dataLoaders/utils/pluginConfigs.ts
- ui/src/shared/components/tables/TableCell.tsx
- ui/src/variables/components/CSVVariableBuilder.tsx
- ui/src/variables/utils/hydrateVars.ts
- ui/src/variables/utils/mapBuilder.ts
- ui/yarn.lock
> chore: upgrade typescript

- cmd/influxd/launcher/launcher.go
> feat(tls): add options to run HTTP over TLS

- ui/cypress/e2e/buckets.test.ts
- ui/cypress/e2e/collectors.test.ts
- ui/cypress/e2e/labels.test.ts
- ui/src/shared/components/GetResources.tsx
- ui/src/shared/selectors/getResourcesStatus.ts
- ui/tsconfig.test.json
> refactor: RemoteDataState states in GetResources

- ui/cypress/e2e/labels.test.ts
- ui/src/labels/components/LabelList.tsx
Also the test have been added that correlate to this issue
Closes #13950 
> (fix)(ui) Sort by description broken

- authorizer/bucket.go
- bolt/id_test.go
- bolt/lookup_service_test.go
- bucket.go
- cmd/influxd/launcher/launcher.go
- http/bucket_service.go
- http/influxdb/bucket.go
- http/swagger.yml
- http/write_handler.go
- http/write_handler_test.go
- inmem/bucket_service.go
- kv/bucket.go
- kv/lookup_service_test.go
- kv/org.go
- mock/bucket_service.go
- mock/generators.go
- storage/bucket_service.go
- storage/retention.go
- task/backend/analytical_storage.go
- task/backend/analytical_storage_test.go
- testing/organization_service.go
Creates system buckets on organization creation
> feat(influxdb): Add system buckets on org creation

- bucket.go
- ui/cypress/e2e/buckets.test.ts
- ui/cypress/e2e/labels.test.ts
Fixes system bucket lookup to look for legacy system buckets
> fix(influxdb): fall back to legacy system buckets

- bucket.go
- kv/bucket.go
> fix(influxdb): move system bucket fallback to kv level

- http/task_service.go
Closes #15522 
This PR adds an API-facing interface called `httpRun` that converts the `time.Time` values to `*time.Time` so that empty values can be omitted from the JSON that is sent.
> fix(tasks): create API facing interface for task runs

- http/check_service.go
- http/notification_endpoint.go
- http/notification_rule.go
- http/swagger.yml
- http/swagger_test.go
- kv/notification_rule.go
- ui/src/alerting/actions/checks.ts
- ui/src/alerting/actions/notifications/endpoints.ts
- ui/src/alerting/actions/notifications/rules.ts
- ui/src/alerting/components/notifications/utils/index.ts
- ui/src/types/alerting.ts
- Notification Rules
- Notification Endpoints
- Checks
Closes #15039
> feat(influxdb): Add labels create endpoints

- ui/cypress/e2e/dashboardsView.test.ts
- ui/cypress/fixtures/view.json
- ui/cypress/index.d.ts
- ui/cypress/support/commands.ts
- ui/cypress/support/index.js
- ui/package.json
- ui/src/dashboards/components/EditVEO.tsx
- ui/src/dashboards/components/NewVEO.tsx
- ui/src/index.tsx
- ui/src/shared/components/cells/CellContext.tsx
- ui/src/timeMachine/actions/index.ts
- ui/src/timeMachine/actions/queries.ts
- ui/src/variables/actions/index.ts
- ui/yarn.lock
> Fix: variable selections should persist

- check.go
- http/check_service.go
- http/check_test.go
- http/notification_endpoint.go
- http/notification_endpoint_test.go
- kv/check.go
- kv/notification_endpoint.go
- notification_endpoint.go
- testing/checks.go
- testing/notification_endpoint.go
oss version of https://github.com/influxdata/idpe/issues/4982
Use urm filter to search checks, endpoints.
- [] http/swagger.yml updated (if modified Go structs or API)
> fix(kv): find checks by urm

- ui/.eslintrc.js
- ui/package.json
- ui/src/onboarding/components/OnboardingButtons.test.tsx
- ui/src/tasks/components/TaskCard.test.tsx
- ui/yarn.lock
Connects #15564 
What it says on the tin ;)
> feat(ui): add lint check for it.only tests

- ui/cypress/e2e/dashboardsView.test.ts
- ui/src/dashboards/components/VEOHeader.tsx
Connects #15239
Adds e2e regression test for above ticket ☝️
> test(ui): add e2e regression test for issue #15239

- CHANGELOG.md
> chore: changelog updates for 1.7.9 GA

- ui/src/dashboards/components/DashboardHeader.tsx
- ui/src/shared/components/graph_tips/GraphTips.tsx
> Zs standardizetooltips&popovers #14536

- cmd/influx/delete.go
- cmd/influx/main.go
- http/delete_handler.go
influx cli for delete predicate, manually tested
> feat(cmd/influx): add cli delete predicate

- ui/src/shared/components/cloud/CloudEnv.test.tsx
- ui/src/shared/components/cloud/CloudExclude.tsx
- ui/src/shared/components/cloud/OSSEnv.tsx
> fix(ui): don't exclude features if not in cloud

- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/stdlib/testing/testing.go
https://github.com/influxdata/influxdb/issues/15667
This started failing on master after I merged this:
https://github.com/influxdata/influxdb/commit/7aa1fccee0e6bb69f33103150791dbe20054affe
I filed the above issue to address whatever is causing the flakiness.
> test(query): reskip flakey test

- bucket.go
- http/bucket_service.go
- inmem/bucket_service.go
- kv/bucket.go
- kv/bucket_test.go
- testing/bucket_service.go
Closes #15630
Keep users from removing system buckets.
> feat(influxdb): Prevent the deletion of system buckets

- task/backend/scheduler.go
This ensures that a `context.Context` decorated with an authorizer is used when calling `FinishRun`. In order for the call to be authorized when TaskControlService is a separate service.
This will ultimately be replaced by the new scheduler. Until then ensures FinishRun does not orphan runs.
> fix(tasks): wire auth context down to scheduler runner

- ui/package.json
moving on up to `1.0.4` 🏙 :eastside: :pie:
> chore(ui): bumping clockface

- ui/src/shared/components/EmptyGraphErrorTooltip.tsx
Closes #15418 
Implemented using tooltip
Refactored implementation to use popover
> fix(UI/emptygrapherror): refactored tooltip to popover

- predicate/logical.go
- predicate/parser.go
- predicate/parser_test.go
- predicate/predicate_test.go
- predicate/tag_rule.go
Closes https://github.com/influxdata/influxdb/issues/15677
add _measurement and _field special tag key.
fixed a logical node issue.
manually tested as well.
> fix(predicate): add special tag key, fixed children number

- ui/cypress/e2e/dashboardsIndex.test.ts
- ui/cypress/e2e/tasks.test.ts
Fixes the flaky nature of our e2e tests so they're more deterministic.
> test(ui): Fix flaky tasks and dashboard tests

- ui/cypress/e2e/explorer.test.ts
- ui/src/shared/components/BoxTooltip.scss
- ui/src/timeMachine/components/fluxFunctionsToolbar/FluxFunctionsToolbar.scss
- ui/src/timeMachine/components/fluxFunctionsToolbar/FunctionTooltipContents.tsx
- ui/src/timeMachine/components/fluxFunctionsToolbar/ToolbarFunction.tsx
- ui/src/timeMachine/components/fluxFunctionsToolbar/TooltipLink.tsx
- ui/src/timeMachine/components/variableToolbar/VariableItem.tsx
- ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.tsx
Closes #15419 
ToolbarFunction and VariableItem were not using Popover
Refactored ToolbarFunction and VariableItem to use the clockface/Popover
> fix(toolbar): refactored toolbar and variable to overlay

- task/backend/scheduler/scheduler_test.go
- task/backend/scheduler/treescheduler.go
Fixes a panic with the new scheduler.
> fix(tasks): scheduler btree panic

- ui/src/timeMachine/components/QueriesSwitcher.tsx
Closes https://github.com/influxdata/influxdb/issues/15714
> fix(ui): set the width only on the Popover to fix the button size

- cmd/influx/pkg.go
- dashboard.go
- http/dashboard_service.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/dashboard.json
- pkger/testdata/dashboard.yml
- pkger/testdata/dashboard_associates_label.json
- pkger/testdata/dashboard_associates_label.yml
- pkger/testdata/dashboard_single_stat.yml
This PR extends `pkger` with the ability to standup dashboards with single stat views.
> feat(pkger): dashboards and single stat view

- go.mod
- go.sum
> build(flux): update Flux to v0.53.0

- auth.go
- bolt/authorization_test.go
- bolt/onboarding_test.go
- http/auth_service.go
- http/auth_test.go
- http/onboarding_test.go
- http/swagger.yml
- inmem/auth_test.go
- inmem/onboarding_test.go
- kv/auth.go
- kv/auth_test.go
- kv/service.go
- testing/auth.go
- testing/onboarding.go
Closes #15366 
CreatedAt & UpdatedAt fields were missing from Authorization 
Added createdAt & UpdatedAt fields to Authorization. Refactored a few tests to correspond to these changes
> feat(createdAt): Added createdat and updatedAt to Authorization

- ui/src/shared/components/FluxMonacoEditor.tsx
- ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
- ui/webpack.common.ts
Closes #15636
adding in some of the editor events to maintain the same interface that we have with codemirror
> feat: adding in some editor events for monaco

- pkger/models.go
- pkger/parser_test.go
- pkger/testdata/dashboard_scatter.json
- pkger/testdata/dashboard_scatter.yml
> feat(pkger): adds scatter chart support

- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/testdata/dashboard_heatmap.json
- pkger/testdata/dashboard_heatmap.yml
> feat(pkger): adds heatmap

- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- pkger/parser.go
- pkger/service.go
these tests supply coverage for the happy path of the pkger service
behavior.
> chore(pkger): add integration tests for pkger service

- pkger/doc.go
> feat(pkger): add doc.go to the pkger pkg for a TLDR of what it is and does

- tsdb/index/tsi1/file_set.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_file.go
- tsdb/index/tsi1/index_file_test.go
- tsdb/index/tsi1/log_file.go
- tsdb/index/tsi1/partition.go
> fix(tsi1): index defect with negated equality filters

- cmd/influxd/launcher/pkger_test.go
> feat(pkger): extend integration tests to include rollback functionality

- pkger/clone_resource.go
- pkger/models.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/dashboard_markdown.json
- pkger/testdata/dashboard_markdown.yml
> feat(pkger): adds markdown chart support

- http/pkger_http_server.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
provide more fine grained error identifiers for the parser. This will be incorporated into the changes to the HTTP API.
> feat(pkger): improve error handling for parser

- pkger/parser.go
> fix(pkger): adds back failures var

- cmd/influx/pkg.go
Closes #15699 
This extends the influx cli with the ability to create packages.
> feat(pkger): add pkg new operation to cli to create packages

- ui/package.json
- ui/src/clockface/constants/colors.ts
- ui/src/clockface/types/index.ts
- ui/src/shared/constants/index.ts
- ui/src/style/_influx-colors.scss
- ui/yarn.lock
Tested this out before publishing the newest version, everything looked okay. It is mostly new components rather than any significant changes
> chore(ui): upgrade to clockface 1.0.6

- ui/cypress/e2e/explorer.test.ts
- ui/cypress/e2e/notificationRules.test.ts
Closes https://github.com/influxdata/influxdb/issues/15868
Make the e2e tests compact for better performance.
> test: combine tests and remove unnecessary thens

- ui/package.json
- ui/src/shared/components/EventMarker.tsx
- ui/src/shared/components/EventMarkers.scss
- ui/src/shared/components/EventMarkers.test.tsx
- ui/src/shared/components/EventMarkers.tsx
- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/components/cells/Cell.scss
- ui/src/style/_variables.scss
- ui/src/types/alerting.ts
- ui/yarn.lock
Closes #https://github.com/influxdata/influxdb/issues/15520
> feat(ui): Event marker filtering for check status levels. 

- task/backend/executor/task_executor.go
It is best to standardize the data we store in etcd and influxdb
> fix(task): make calls to update runs force UTC time

- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/dashboard_histogram.json
- pkger/testdata/dashboard_histogram.yml
> feat(pkger): adds histogram chart support

- cmd/influx/main.go
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- pkger/parser.go
Add some small integration tests to validation cobra commands are all working as expected.  Inspiration taken from the `kubectl` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/convert/convert_test.go#L108)
> chore(pkger): add tests to pkg new cli command

- kv/task.go
- task.go
- task/backend/analytical_storage.go
This is a temporary change because auth lookup is very taxing.
> fix(task): add hinting to allow us to skip task auth lookup

- cmd/influx/authorization.go
- cmd/influx/main.go
> chore(influx): refactor auth cli cmd

- http/swagger.yml
Made updates to summaries and descriptions in the swagger.yml.
> [chore/swagger] updated summaries and descriptions in swagger.yml

- ui/package.json
- ui/webpack.dev.ts
> feat: add /oauth proxying in webpack dev server

- ui/assets/index.html
Closes #15780
decided to update the meta tag to a newer version that is more inline with quartz after evaluating this ticket
> fix(ui): update the meta tag

- ui/package.json
> fix(ui): transposed package.json ordering

- ui/src/shared/constants/colorOperations.ts
Now fixed, falsy zero is no longer being bad
Closes #15803 
> fix(ui): value zero has no background color

- ui/src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx
Closes #15992 
this adds a little text under our current wizard to inform users about all of the other great plugins we have available!
> feat(ui): let the user know about more telegraf plugins

- ui/src/cloud/constants/index.ts
- ui/src/shared/copy/notifications.ts
Users should now reach out to `support@influxdata.com` in response to these errors.
> fix: cloudbeta -> support email address

- ui/src/shared/components/cells/View.tsx
- ui/src/timeMachine/reducers/index.ts
Closes influxdata/honeybadger-errors#2
Closes influxdata/honeybadger-errors#6
it said that there was a null being accessed here, so I let it have a null without failing.
> fix(ui): guard against null

- query/stdlib/influxdata/influxdb/rules.go
Use the optimized pivot when the influxdb source is being used.
> feat(query): enable optimized pivot push down rule

- pkger/models.go
- pkger/models_test.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/telegraf.json
- pkger/testdata/telegraf.yml
references: #16074 
this has some small refactoring and adds the telegraf support to the parser.
> feat(pkger): add telegraf support to parser

- cmd/influx/main.go
- cmd/influx/transpile.go
- query/influxql/config.go
- query/influxql/transpiler.go
The command can be run using `influx tranpsile`.
> feat(cmd/influx): add command to manually transpile InfluxQL to Flux

- ui/src/me/constants/index.ts
Add support of the [Georgian](https://en.wikipedia.org/wiki/Georgia_(country)) version hello
We use influx db in multiple projects and like it very much. Hope everything looks good in the PR and will be merged :) Please let me know if it needs some additional changes
> feat(ui): add Georgian version of hello

- cmd/influx/pkg.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- context/token.go
- http/telegraf.go
- mock/telegraf_service.go
- pkger/models.go
- pkger/parser.go
- pkger/service.go
- pkger/service_test.go
- telegraf.go
Adds support for applying a telegraf config via pkger.
references: #16074
> feat(pkger): add dry run and apply functionality for telegraf resources

- ui/cypress/e2e/dashboardsIndex.test.ts
Closes #16129
What the commit message says
> test(ui): scope create dashboard click to body button to avoid conflicts

- ui/package.json
- ui/yarn.lock
Closes #15906 
Needed to update the giraffe version after it was published in order to reflect the changes made there onto master
Updated giraffe version
> chore(ui): updated giraffe dependency

- http/variable_service.go
noticed thsi while working something else... simple fix.. I think 🤔
> fix(http): fixes resource type on variables handler

- ui/package.json
- ui/src/clockface/components/wizard/WizardOverlay.tsx
- ui/src/dataLoaders/actions/telegrafEditor.ts
- ui/src/dataLoaders/components/TelegrafEditor.scss
- ui/src/dataLoaders/components/TelegrafEditor.tsx
- ui/src/dataLoaders/components/TelegrafEditorMonaco.tsx
- ui/src/dataLoaders/components/TelegrafEditorPluginList.tsx
- ui/src/dataLoaders/components/TelegrafEditorSidebar.tsx
- ui/src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx
- ui/src/dataLoaders/reducers/telegrafEditor.ts
- ui/src/scrapers/components/Scrapers.tsx
- ui/src/scrapers/containers/ScrapersIndex.tsx
- ui/src/shared/components/TomlMonacoEditor.tsx
- ui/src/shared/utils/featureFlag.ts
- ui/src/store/configureStore.ts
- ui/src/telegrafs/components/TelegrafConfig.tsx
- ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
- ui/src/types/stores.ts
- ui/yarn.lock
Working on making a telegraf config editor!
this is a stab at a potential interface to address influxdata/idpe#5399
it got a little away from me (it was one giant file this morning), but the functionality is there
all is served behind a lazy loaded feature flag (minimal user impact) so that we can get some stakeholder's eyes on it. here's a picture of it for you fine folks
> feat(ui): create telegraf config

- cmd/influx/authorization.go
- cmd/influx/organization.go
- cmd/influx/query.go
- cmd/influx/repl.go
- http/bucket_service.go
- http/client.go
- http/dashboard_service.go
- http/label_service.go
- http/org_service.go
- http/org_test.go
- http/paging.go
- http/telegraf.go
- http/variable_service.go
- paging.go
- pkger/service.go
Bits of work for the endpiont notification endpoint pkger work. This is broken out to make PRs a bit smaller, easier to reason about.
> chore(http): refactor org service to use httpc client

- ui/src/me/containers/MePage.tsx
we need to be able to detect when a user is on the home page, but not by route, because of reasons, to trigger a walkme workflow. @corriganjohn is the owner on this if that's not enough context.
> fix: adding unique id for walkme

- cmd/influx/pkg.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- http/notification_endpoint.go
- http/swagger.yml
- mock/notification_endpoint_service.go
- notification/endpoint/http.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/notification_endpoint.json
- pkger/testdata/notification_endpoint.yml
adds ability to dry run and apply notification endpoints within a pkg
> feat(pkger): add notification endpoint dry run/apply functionality

- http/bucket_service.go
- http/dashboard_service.go
- http/label_service.go
- http/notification_endpoint.go
- http/org_service.go
- http/telegraf.go
- http/user_resource_mapping_service.go
- http/variable_service.go
- pkg/httpc/client.go
- pkg/httpc/client_test.go
making most common API calls super easy to get up and running
> feat(httpc): extend httpc Client with JSON shorthand methods

- CHANGELOG.md
- ui/package.json
- ui/src/dashboards/constants/index.ts
- ui/yarn.lock
Closes https://github.com/influxdata/influxdb/issues/16122
> fix(ui): update giraffe and time format options

- ui/src/tasks/containers/TaskEditPage.tsx
- ui/src/tasks/containers/TaskPage.tsx
- ui/src/variables/components/VariableArgumentsEditor.tsx
Cleaning up the last couple instances of code mirror
> feat: get monaco into the task page

- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/utils/featureFlag.ts
- ui/src/timeMachine/actions/queries.ts
eventMarkers were behind a feature flag- they're ready to go!
> chore(ui): Remove eventMarkers feature flag

- http/pkger_http_server_test.go
- http/user_test.go
- pkg/testttp/http.go
- pkg/testttp/http_test.go
> feat(testttp): extend testttp with new JSON methods and refactors test to use it

- task/backend/executor/task_executor_test.go
Temporary fix for flaky test, will need a more robust solution
> fix(tasks): fix flaky run latency metric test

- cmd/influx/authorization.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/query_test.go
- cmd/influxd/launcher/tasks_test.go
- http/auth_service.go
- http/auth_test.go
- http/client.go
normalizing the auth service http client to follow suit with other services.
some extra work waiting for flaky test to subside...
> chore(http): refactor auth service http client to use httpc.Client

- cmd/influx/user.go
- http/client.go
- http/user_service.go
- http/user_test.go
some more busy work while CI is running
> chore(http): refactor user http service to use the httpc.Client

- http/source_service.go
last of the CI wait work
Think this will require upstream changes, pretttty sure
> chore(http): refactor source http service client to use httpc.Client

- http/api_handler.go
- http/query_handler_test.go
- http/swagger.yml
- http/telegraf.go
- storage/reads/datatypes/storage_common.pb.go
- telegraf/plugins/plugins.go
- telegraf/plugins/plugins_test.go
> feat(http): expose list of available telegraf plugins

- storage/wal/dump_test.go
> fix: update test to use 'valid' marshalled predicate

- CHANGELOG.md
- cmd/influx/pkg.go
- cmd/influxd/launcher/pkger_test.go
- http/check_test.go
- kv/check_test.go
- mock/check_service.go
- notification/check/check.go
- notification/check/deadman.go
- notification/check/threshold.go
- notification/check/threshold_test.go
- pkger/models.go
- pkger/service.go
- pkger/service_test.go
- testing/checks.go
close: #14799  (found this when trying to figure out why idpe tests fail different than influxdb does... issues remedied and tests turned back on)
> feat(pkger): add apply functionality for checks

- CHANGELOG.md
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- notification/check/deadman.go
- notification/check/threshold.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/service.go
- pkger/service_test.go
This puts the bow on the checks resource.
> feat(pkger): add export for checks

- CONTRIBUTING.md
> New new contrib

- ui/src/alerting/components/AlertHistoryIndex.tsx
- ui/src/alerting/components/AlertHistoryQueryParams.tsx
- ui/src/alerting/components/CheckCard.tsx
- ui/src/alerting/components/CheckHistory.scss
- ui/src/alerting/components/CheckHistory.tsx
- ui/src/alerting/components/CheckHistoryControls.tsx
- ui/src/alerting/components/CheckHistoryVisualization.tsx
- ui/src/alerting/components/CheckTableField.tsx
- ui/src/alerting/reducers/checks.ts
- ui/src/index.tsx
- ui/src/style/chronograf.scss
> Zs addviewcheckpage #14782

- CONTRIBUTING.md
- query/promql/internal/promqltests/go.sum
docs: Add new CONTRIBUTING.md contribution guide.
> docs: Create CONTRIBUTING.md

- query/promql/internal/promqltests/go.sum
Looks like #13370 mistakenly included a bad go.sum change
> fix(query): revert promqltests/go.sum

- ui/src/dataLoaders/actions/telegrafEditor.ts
- ui/src/dataLoaders/components/TelegrafEditor.tsx
- ui/src/dataLoaders/components/TelegrafEditorMonaco.tsx
- ui/src/dataLoaders/components/TelegrafEditorSidebar.tsx
- ui/src/dataLoaders/reducers/telegrafEditor.ts
- ui/src/shared/components/GetResources.tsx
- ui/src/store/configureStore.ts
- ui/src/types/stores.ts
closes the loop for presenting the data exposed in this PR #16233
> feat: connecting telegraf editor to a backend resource

- CHANGELOG.md
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/testdata/tasks.json
- pkger/testdata/tasks.yml
> feat(pkger): add support for tasks to parser

- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
this provides influxdb.Errors whenever possible from the pker service layer.
the behavior that caused the error is somewhat implicated in the errro code.
it is not perfect but is a big step forward. using the http server/client to
run pkger stuff makes it abundantly clear the errors needed to be communicated
better.
closes: #16313
> chore(pkger): improve error handling in service

- CHANGELOG.md
- cmd/influx/pkg.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- mock/task_service.go
- pkger/models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/tasks.json
- pkger/testdata/tasks.yml
> feat(pkger): add apply functionality for task resource

- cmd/influx/pkg.go
> chore(pkger): reorder print statements to be alphabetical

- ui/src/alerting/actions/checks.ts
- ui/src/alerting/components/EditCheckEO.tsx
- ui/src/alerting/components/NewDeadmanCheckEO.tsx
- ui/src/alerting/components/NewThresholdCheckEO.tsx
> feat(ui): Show users errors from saving check before exiting time machine

- Makefile
- cmd/influxd/main.go
set date in go like a sane person
> fix: improve date in `version` command

- ui/package.json
- ui/src/members/actions/index.ts
- ui/src/members/components/Members.tsx
- ui/src/members/reducers/index.ts
- ui/src/schemas/index.ts
- ui/src/shared/components/GetResources.tsx
- ui/src/shared/selectors/getResourcesStatus.ts
- ui/src/shared/selectors/index.ts
- ui/src/store/configureStore.ts
- ui/src/types/resources.ts
- ui/src/types/stores.ts
- ui/yarn.lock
Introduces normalization pattern for the members resource
> refactor(ui): normalize member resource

- kv/check.go
- kv/notification_endpoint.go
- kv/service.go
- kv/store_base.go
- kv/store_base_test.go
- kv/store_index.go
- kv/store_index_test.go
- kv/variable.go
- testing/checks.go
- testing/notification_endpoint.go
- testing/variable.go
> chore(kv): fixup the checks service to use the index store

- cmd/influx/bucket.go
- cmd/influx/inspect.go
- cmd/influx/pkg.go
> fix(pkger): don't swallow errors when failing to get organization

- ui/package.json
- ui/yarn.lock
> chore: upgrade cypress

- kv/check.go
- kv/notification_endpoint.go
- kv/store_base.go
- kv/store_base_test.go
- kv/store_index.go
- kv/store_index_test.go
- kv/variable.go
- testing/checks.go
- testing/variable.go
More work towards the svc definition issue.  Helps to reduce the duplicate code and mark use this common behavior without much of a fuss.
> chore(kv): add new/update checks to kv store base and index store

- kv/variable.go
- testing/variable.go
note: this will remain unique by name case insensitive
closes #16429
> fix(kv): remove normalizing of variables names to downcase

- cmd/influxd/launcher/launcher.go
- http/handler.go
- http/handler_test.go
- http/middleware.go
- http/middleware_test.go
- http/org_service.go
- http/pkger_http_server.go
- http/platform_handler.go
- http/query_handler.go
- http/ready.go
- http/router.go
- http/write_handler.go
- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
- kit/transport/http/status_response_writer.go
> chore(http): fixup middleware stack and normalize metrics into same buckets for id fields

- kv/check.go
> fix(ui): improve error message for create check (#16447)

- http/api_handler.go
- http/write_handler.go
I missed a bit. This is a continuation of https://github.com/influxdata/influxdb/commit/a0c18c9ef700fd23c000ef79fe07cf905fef8191
This exposes the MaxBatchSizeBytes property on the *APIBackend. Such this can be configured higher up the call stack.
I also did a little extra housekeeping.
> fix(http): expose max batch size bytes limit option on *APIBackend

- cmd/influx/pkg_test.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
> fix(pkger): fix missing API version in export of existing resources

- ui/cypress/e2e/variables.test.ts
- ui/src/shared/components/dangerConfirmation/DangerConfirmationForm.tsx
- ui/src/variables/components/RenameVariableForm.tsx
- ui/src/variables/components/VariableContextMenu.tsx
- ui/src/variables/reducers/index.ts
> fix(ui): vars rename

- cmd/influxd/launcher/launcher.go
- pkger/service.go
- pkger/service_logging.go
- pkger/service_tracing.go
was helping @russorat debugging issue he is seeing and wanted to enhance the data the pkger service provides.
> feat(pkger): add service logging

- CHANGELOG.md
- cmd/influx/main.go
> feat(influx): trim space on credentials file

- models/points_parser.go
- models/points_test.go
This PR fixes a bug where the parser did not correctly report `ErrLimitMaxBytesExceeded` when an allocation occurred whilst parsing individual points. 
An additional allocation accounting was added when constructing errors, to ensure these do not exceed total allocations.
Tests were updated to verify these two scenarios.
> fix(models): Fix bug that did not return ErrLimitMaxBytesExceeded

- dashboard.go
- http/swagger.yml
- pkger/clone_resource.go
- pkger/models.go
- ui/src/shared/components/Gauge.tsx
- ui/src/shared/components/GaugeChart.tsx
- ui/src/shared/utils/formatStatValue.ts
- ui/src/shared/utils/view.ts
- ui/src/timeMachine/actions/index.ts
- ui/src/timeMachine/components/view_options/Affixes.tsx
- ui/src/timeMachine/components/view_options/GaugeOptions.tsx
- ui/src/timeMachine/reducers/index.ts
> Zs optionalsuffix15909

- ui/src/shared/components/ViewSwitcher.tsx
- ui/src/shared/utils/formatStatValue.ts
- ui/src/shared/utils/view.ts
- ui/src/timeMachine/components/view_options/Affixes.tsx
- ui/src/timeMachine/components/view_options/SingleStatOptions.tsx
> fix: Fixing master gauge issues

- storage/engine_test.go
This PR adds some benchmarks that show the impact of batch size on writing a fixed number of values into a tsm engine.
> refactor: add engine write benchmarks

- chronograf/id/uuid.go
Update to remove dependency on insecure version of uuid library
https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488
> fix: uuid security

- cmd/influx/pkg.go
> chore(influx): use disable- for color/table borders in pkg cmd

- ui/cypress/e2e/onboarding.test.ts
- ui/cypress/e2e/variables.test.ts
- ui/cypress/support/commands.ts
Closes #16544
Add test to confirm that it is possible to delete a variable
> fix(variable-deleting): Enable test for variable deletion

- README.md
Closes #
adds an icon to the readme for users to join our community slack channel
> chore(readme): add slack community link

- ui/src/dashboards/actions/thunks.ts
Closes #16558
copy pasta malaise
> fix: check status when deleting

- ui/src/dashboards/actions/thunks.ts
Closes #16557
little hiccup from normalization work. works now.
> fix: export should grab the dashboard

- ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx
> fix(popover): Fixing the labels clearing old search

- ui/src/shared/components/inlineLabels/InlineLabelPopover.tsx
- ui/src/shared/components/inlineLabels/InlineLabelsEditor.scss
- ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx
> fix(popover): Fixing the add label popover effect

- tsdb/index/inmem/inmem.go
- tsdb/store_test.go
Prior to this change, new series would be added to the series file
before checking the series cardinality limit. If the limit was exceeded,
the write was rejected even though the series had already been added to
the series file.
> fix(tsm1): improve series cardinality limit

- ui/src/dashboards/actions/thunks.ts
- ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
> fix: enable cloning and exporting of dashboards

- ui/cypress/e2e/onboarding.test.ts
> fix(test): Fixing flakey e2e onboarding test in cypress

- bolt/kv.go
- kv/dashboard.go
By updating to the new forward pointer the query should be more efficient.
> fix(kv): Update dashboard collection to use new forward cursor

- ui/src/alerting/actions/checks.ts
> fix(honeybadger): fixing checks state call

- client/influxdb.go
- client/influxdb_test.go
- cmd/influx/cli/cli.go
- cmd/influx/cli/cli_test.go
- cmd/influx/cli/flux.go
- cmd/influx/main.go
- flux/client/http.go
- query/internal/gota/cmo_test.go
- query/internal/gota/trix_test.go
> feat(influxdb): Add path to cli

- ui/src/authorizations/utils/permissions.ts
> feat(permissions): Add new resources to permissions array

- ui/src/dataExplorer/components/DashboardsDropdown.tsx
- ui/src/dataExplorer/components/SaveAsCellForm.tsx
> fix(dashboard-dd): Add name of newly created dropdown

- ui/src/clientLibraries/graphics/RubyLogo.tsx
Requested by https://github.com/influxdata/influxdb/pull/16617
Add logo for Ruby client library.
> feat(influxdb): Add Ruby Logo

- CHANGELOG.md
> chore: changelog updated for 1.7.10 GA

- ui/cypress/e2e/dashboardsIndex.test.ts
- ui/src/dashboards/actions/thunks.ts
- ui/src/dashboards/apis/index.ts
- ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
> fix: clone dashboards

- ui/src/shared/components/inlineLabels/InlineLabels.tsx
Closes #15455
our normalization efforts should patch this up, but until then, lets keep the frontend working
> fix: default label properties

- inmem/kv.go
- kv/scrapers.go
I also made a minor update to move a db lookup outside of a for loop to save
time and optimize
> fix(kv): Update scrapers to use new forward cursor

- pkger/parser.go
- pkger/parser_test.go
> chore(pkger): update comment and update root of pkg error to be `root`

- ui/cypress.json
- ui/cypress/e2e/explorer.test.ts
> Zs flakeyexplorertest16587

- ui/src/dashboards/components/dashboard_index/DashboardCards.tsx
- ui/src/labels/utils/index.ts
- ui/src/shared/utils/filterUnusedVars.ts
- ui/src/templates/api/index.ts
@corriganjohn brought it to my attention that dashboards didn't load when you imported them. I got through the basic stuff, but view properties are gone and that's breaking everything?
> fix: import dashboards

- tsdb/engine/tsm1/array_cursor.gen.go
- tsdb/engine/tsm1/array_cursor.gen.go.tmpl
> fix(storage): ensure all block data returned

- ui/cypress/e2e/collectors.test.ts
- ui/cypress/e2e/tasks.test.ts
> fix(tests): Collectors and tasks

- ui/src/timeMachine/components/view_options/Affixes.tsx
- ui/src/timeMachine/components/view_options/ViewOptions.scss
> fix: gauge spaced out

- cmd/influxd/launcher/launcher.go
- kit/metric/client.go
- pkger/service_metrics.go
> feat(pkger): add metrics svc middleware

- CHANGELOG.md
- ui/src/organizations/apis/index.ts
Closes #16710 
Was trying to map an object
Added the dashboards that are being returned from the result.data as a property.
> fix(ui): fixed dashboard mapping error

- cmd/influxd/run/server.go
Refactor trace code for clarity and reliability.  The branch is misnamed unfortunately.
> refactor(influxdb): Refactor trace code for clarity and reliability

- cmd/influxd/launcher/launcher.go
- pkger/http_server.go
- pkger/http_server_test.go
more updates to take advantage of new API type
> chore(pkger): refactor http server to use new http.API type

- CHANGELOG.md
> docs(changelog): updating changelog for 1.7.10rc1

- http/bucket_service.go
- http/bucket_service_test.go
- http/source_service.go
- http/swagger.yml
> chore(http): refactor bkt service to use API type

- ui/cypress/e2e/explorer.test.ts
- ui/src/timeMachine/components/view_options/Affixes.tsx
> fix: gauge tests

- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_tracing.go
> feat(influx): extend pkg command with providing env ref entries

- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
> chore(pkger): simplify env refs to remove juggling state between validations

- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
references: #16657 
will be a follow up to extend the CLI and wrap up #16657
> feat(pkger): add support for combining pkgs

- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
> feat(influx): add support for mulitple pkg files to be submitted together

- CHANGELOG.md
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
> feat(influx): add support for providing directories of pkgs to pkg command

- http/bucket_service.go
- http/onboarding.go
This function is required for maintaining a similar buckets reponse.
> chore(http): export NewBucketResponse function

- cmd/influxd/backup_util/backup_util.go
- tests/backup_restore_test.go
> chore: fix code format

- kv/task.go
- task/servicetest/servicetest.go
Closes https://github.com/influxdata/influxdb/issues/16775
A recent regression surfaced around tasks paging using the `After` field. Causing an infinite loop to occur when consumers try to loop over results.
This was fixed in https://github.com/influxdata/influxdb/pull/16758.
This PR just introduces a test around task paging to ensure this doesn't regress again.
I can confirm I ran this against a commit prior to the fix introduced above and this test failed.
UPDATE:
This now fixes https://github.com/influxdata/influxdb/issues/16775 as this test surfaced the problem.
> chore(task): add test around paging using after

- kv/indexer.go
- kv/indexer_test.go
- kv/service.go
This will allow the population of indexes to be incremental and allow
for a rolling update to the index's to be handled cleanly.
> feat(kv): Create a indexer to allow the addition of indexes

- ui/cypress/e2e/tasks.test.ts
> fix: e2e tasks test

- ui/package.json
- ui/yarn.lock
Closes https://github.com/influxdata/influxdb/issues/16489
Updates giraffe to show the additional columns in the tooltip (for real this time).
> fix: update giraffe

- cmd/influx_inspect/buildtsi/buildtsi.go
- tsdb/series_partition.go
This pull request includes fixes for issues found during testing of `-compact-series-file`.
> fix(tsdb): Fix -compact-series-file flag

- cmd/influxd/restore/command.go
Closes #16726
Tested locally, and verified that the cli descriptions are updated:
> refactor: update restore cli flag descriptions

- pkg/httpc/client_test.go
- pkg/httpc/options.go
This will begin work to mimic the browser via the client API.
Signed-off-by: Chris Goller <goller@gmail.com>
> feat(pkg/httpc): add cookie based authorization

- ui/src/timeMachine/components/view_options/Affixes.tsx
- ui/src/timeMachine/components/view_options/GaugeOptions.tsx
- ui/src/timeMachine/components/view_options/SingleStatOptions.tsx
> fix: Hide single stat optional ticks

- ui/webpack.dev.ts
was focused on deployments, forgot about local dev
> fix: broke the dev env

- cmd/influxd/launcher/pkger_test.go
- cmd/influxd/launcher/query_test.go
- kv/notification_rule_test.go
- query/influxql/end_to_end_test.go
- query/stdlib/influxdata/influxdb/to.go
- query/stdlib/influxdata/influxdb/to_test.go
- query/stdlib/testing/end_to_end_test.go
These changes fix the tests in `to_test.go` and also skip tests with filed issues:
- #16809
- #16810
- #16811 
- #16812 
With these changes the `gotest` check turns green, but there are still other issues.
> test(query): skip tests that are not passing in feat/use-algo-w

- ui/src/dashboards/components/Dashboard.tsx
- ui/src/shared/components/cells/Cells.tsx
- ui/src/types/dashboards.ts
> Zs gaugecontainerfit15911

- cmd/influx/main.go
> fix(influx): fix issue with locla state overriding env vars for token

- pkger/models.go
- pkger/models_test.go
just stumbled on this issue where labels were seen to be in conflict when they should not have been.
> fix(pkger): fix check for labels having conflict

- cmd/influx/main.go
🤦‍♂ my mistake. hitting false positive in my test...
> fix(influx): fix token env var and default assignment

- ui/src/resources/reducers/helpers.test.ts
- ui/src/resources/reducers/helpers.ts
Lingering code that I missed in my labels normalization PR.
> test: reducer helpers

- ui/src/shared/components/cells/Cells.tsx
> fix: gauge now fits containers

- CHANGELOG.md
> chore(changelog): add missing link to fix for closing #16874

- ui/src/clientLibraries/components/ClientRubyOverlay.tsx
- ui/src/clientLibraries/constants/index.ts
1. Add query example for Ruby client.
2. Add actual version of Java client
> docs(clientLibs): add query example for Ruby client

- ui/src/authorizations/components/ViewTokenOverlay.tsx
- ui/src/shared/components/CodeSnippet.tsx
- ui/src/shared/components/CopyButton.tsx
- ui/src/shared/copy/notifications.ts
Closes #16781
adds a function that lets you define your own message!
> feat: override the notification text

- ui/src/dashboards/actions/thunks.ts
> fix: weird normalizr bug

- ui/src/shared/constants/index.ts
> fix: cloud user link

- http/document_service.go
- http/document_service_test.go
- kv/document.go
- testing/document.go
- testing/util.go
Issue #16861 
Some (maybe) bugs discovered here and there for authorization (see TODOs).
Don't know if that could be  the expected behavior, though it seems it shouldn't be.
> feat(http): add document service

- ui/src/timeMachine/actions/queries.ts
> fix: clears out the old results

- ui/src/shared/utils/useVisDomainSettings.test.ts
- ui/src/timeMachine/selectors/index.test.ts
> fix: remove moment warning

- cmd/influxd/launcher/query_test.go
- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
Fixes https://github.com/influxdata/influxdb/issues/16810.
> chore: update flux dependency

- cmd/influxd/launcher/pkger_test.go
- go.mod
- go.sum
- kv/notification_rule_test.go
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
Fixes https://github.com/influxdata/influxdb/issues/16809
> chore: update flux dependency and unskip notification test

- ui/src/timeMachine/actions/queryBuilder.ts
> chore: perfection

- storage/readservice/store.go
Use tracing properly, simplify a few lines.
> fix(storage): small improvements to readservice/store

- tsdb/index/tsi1/partition.go
> fix: access tsi active log file with READ lock

- models/points_test.go
Closes #
Discussed with Jonathan Sternberg today on Slack...
Feb 18, 2020
https://influxcommunity.slack.com/archives/CH8RV8PK5/p1582066416080000?thread_ts=1582064001.068600&cid=CH8RV8PK5
One very simple change on points_test.go re-enables having model
be stand alone and not need any other influxdb packages which
is very helpful and handy for many reasons...
> fix(models): Remove tsdb package dependency from tests

- http/api_handler.go
This PR wraps the HTTP Task Service in an authorizer.
> fix(tasks): update tasks authorization

- http/client.go
This is super fast, forgot to do that in a previous PR
Needed for using the service externally.
> feat(http): add document service to http Service

- http/session_handler.go
> fix(http): Add secure flag to session cookie

- cmd/influx/secret.go
typo from this merged ticket
https://github.com/influxdata/influxdb/pull/16961
> chore(cmd/influx): typo

- http/check_service.go
Closes #16988 
This fixes a typo that caused a panic.
> fix(checks): typo causing panic in checks endpoint

- cmd/influxd/launcher/engine.go
- storage/engine.go
- storage/readservice/cursor.go
- storage/readservice/store.go
- storage/series_cursor.go
- storage/series_cursor_test.go
fix(storage): small improvements to readservice/store
Use tracing properly, simplify a few lines.
fix(storage): simplify storage/seriesCursor
storage/seriesCursor releases series file and TSI references sooner.
Remove unhelpful request object, inherited from 1.x
> fix(storage): incremental improvments

- ui/src/pageLayout/containers/Nav.tsx
follow up chore for cloud multi-user.
> chore(multi-user): update user list link

- .circleci/config.yml
> chore: update circleci nightly-sel image chrome version

- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/testdata/dashboard_table.json
- pkger/testdata/dashboard_table.yml
first piece of to add parser support #16882 , PR to follow will add export support
> feat(pkger): add table view parser support

- ui/src/external/monaco.flux.completions.ts
- ui/src/external/monaco.flux.messages.ts
- ui/src/external/monaco.flux.server.ts
- ui/src/shared/components/FluxBucketProvider.tsx
- ui/src/shared/components/FluxMonacoEditor.tsx
- ui/src/utils/Deferred.ts
> chore: Refactor LSP server integration for future work

- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/stdlib/testing/testing.go
> fix(stdlib): update flux dependency and unskip test

- CHANGELOG.md
- ui/cypress/e2e/checks.test.ts
- ui/src/timeMachine/components/TagSelector.tsx
- ui/src/timeMachine/components/builderCard/BuilderCardDropdownHeader.tsx
Reverts influxdata/influxdb#17110
> Revert "fix(ui): disabled group functionality for check query builder"

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> feat(pkger): add support for exporting org resources filtered by label

- ui/src/onboarding/containers/LoginPage.scss
was impossible to build locally on master, this targets the new variable name
> fix: import modules.scss, change variable name to match new cf variable

- tenant/error.go
- tenant/error_bucket.go
- tenant/error_org.go
- tenant/error_urm.go
- tenant/error_user.go
- tenant/storage.go
- tenant/storage_bucket.go
- tenant/storage_bucket_test.go
- tenant/storage_org.go
- tenant/storage_org_test.go
- tenant/storage_urm.go
- tenant/storage_urm_test.go
- tenant/storage_user.go
- tenant/storage_user_test.go
To facilitate the isolation of domain specific systems we need to have a
isolated CRUD action system that we can layer business logic on top.
> feat(tenant): Build the crud actions for the new tenant service

- ui/src/clientLibraries/components/ClientJSOverlay.tsx
- ui/src/clientLibraries/components/ClientPHPOverlay.tsx
- ui/src/clientLibraries/constants/index.ts
- ui/src/clientLibraries/graphics/PHPLogo.tsx
- ui/src/clientLibraries/graphics/index.ts
- ui/src/index.tsx
1. add PHP client library
1. update JavaScript/Node.js examples 
`PHPLogo.tsx` is just placeholder... (cc @mavarius)
> feat(clientLibs): add PHP client library, update JavaScript/Node.js examples

- ui/src/shared/constants/fluxFunctions.ts
Adds functions from the Geo package in Flux 0.63.0
> chore(flux): Add geo package functions

- authorizer/label.go
- authorizer/label_test.go
- http/api_handler.go
- http/bucket_service.go
- http/check_service.go
- http/dashboard_service.go
- http/notification_endpoint.go
- http/notification_rule.go
- http/task_service.go
- http/telegraf.go
- http/variable_service.go
This PR wraps the LabelService passed to the Bucket and Org handlers in an Authorization layer. This is part of the epic to fix member/owner permissions.
> fix(labels): add check for write permissions to create label

- Dockerfile
- releng/_go_versions.sh
> fix: ensure we're using go v1.13.8

- cmd/influx/main.go
- cmd/influx/main_test.go
this verifies things like token/host and all the root lvl flags are being
set appropriately.
Closes #16876
> chore(influx): add test coverage for root influx cmd

- cmd/influxd/launcher/pkger_test.go
- pkger/http_server_test.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/label.json
- pkger/testdata/label.yml
- pkger/testdata/remote_bucket.json
> feat(pkger): extend labels to be able to define a label and rename it

- ui/src/dashboards/components/DashboardLightModeToggle.tsx
> refactor(ui): replace text with icons in dashboard light/dark toggle

- .circleci/config.yml
> chore: added INFLUXPATH parameter required by backup and restore tests

- cmd/influx/completion.go
> fix(influx): update completion cmd with more accurate help message

- cmd/influxd/launcher/pkger_test.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/checks.json
- pkger/testdata/checks.yml
> feat(pkger): extend checks to be able to define a check and rename it

- cmd/influxd/launcher/pkger_test.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/notification_endpoint.json
- pkger/testdata/notification_endpoint.yml
> feat(pkger): extend endpoints to be able to define a endpoint and rename it

- tenant/error.go
- tenant/error_bucket.go
- tenant/error_org.go
- tenant/error_user.go
- tenant/service.go
- tenant/service_bucket.go
- tenant/service_bucket_test.go
- tenant/service_org.go
- tenant/service_org_test.go
- tenant/service_test.go
- tenant/service_urm.go
- tenant/service_urm_test.go
- tenant/service_user.go
- tenant/service_user_test.go
- tenant/storage.go
- tenant/storage_bucket.go
- tenant/storage_bucket_test.go
- tenant/storage_org.go
- tenant/storage_org_test.go
- tenant/storage_user.go
- tenant/storage_user_test.go
- testing/bucket_service.go
- testing/organization_service.go
- testing/user_service.go
Built on top of the crud layer of the system we should now have additional service logic.
The addition of service layer should allow for us to verify similar functionality to the kv system.
> feat(tenant): Add in service functions and business logic

- cmd/influxd/launcher/pkger_test.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/variables.json
- pkger/testdata/variables.yml
> feat(pkger): extend variables to be able to define a variable and rename it

- ui/src/onboarding/containers/LoginPage.scss
- ui/src/onboarding/containers/LoginPage.tsx
- ui/src/onboarding/containers/LoginPageContents.tsx
Simplified the styling for the login flow and removed dead code
> fix(ui): fixed styling for login page

- ui/src/onboarding/containers/LoginPage.scss
- ui/src/onboarding/containers/LoginPage.tsx
> fix(ui): removed more dead code

- tenant/middleware_bucket_logging.go
- tenant/middleware_org_logging.go
- tenant/middleware_org_metrics.go
- tenant/middleware_urm_logging.go
- tenant/middleware_urm_metrics.go
- tenant/middleware_user_logging.go
- tenant/middleware_user_metrics.go
This PR adds logging middleware for the individual services encompassed by the tenant service: user, org, URM, and bucket.
> feat(logging): add logging middleware to tenant service

- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/telegraf.json
- pkger/testdata/telegraf.yml
> feat(pkger): add support for unique by meta.name for telegraf configs

- .circleci/config.yml
> chore(litmus): start influxd on local machine

- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/dashboard.json
- pkger/testdata/dashboard.yml
> feat(pkger): extend dashboard to be unique by name

- kv/tenant_test.go
- tenant.go
- testing/tenant.go
> test: add tests for tenant service

- ui/package.json
- ui/yarn.lock
> fix: upgrade webpack

- ui/cypress/e2e/explorer.test.ts
- ui/package.json
- ui/src/external/monaco.flux.completions.ts
- ui/src/external/monaco.flux.messages.ts
- ui/src/external/monaco.flux.server.ts
- ui/yarn.lock
- Pulls signatures from LSP
Closes #17147
> feat: Add flux function signatures to ui

- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/http_server_test.go
- pkger/internal/wordplay/wordplay.go
- pkger/service_test.go
- ui/webpack.prod.ts
<details><summary>example yaml output, see metadata.name fields </summary>
```yaml
apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
name: gifted_bhaskara_0bb005
spec:
color: '#000000'
description: label 2 description
name: label_2
---
apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
name: vigorous_keller_0bb003
spec:
color: '#FFFFFF'
description: label 1 description
name: label_1
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
name: bettering_payne_4bb005
spec:
associations:
- kind: Label
name: vigorous_keller_0bb003
description: desc_2
name: rucket_2
retentionRules:
- everySeconds: 20000
type: expire
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
name: blissful_benz_0bb007
spec:
associations:
- kind: Label
name: vigorous_keller_0bb003
- …
```
> feat(pkger): add human readable random names to pkg resource metadata name field one export

- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- kv/encode.go
- kv/store_base.go
- kv/store_index.go
- kv/store_index_test.go
- pkger/http_remote_service.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_tracing.go
- pkger/store.go
- pkger/store_test.go
references #17235 
This is the foundation of the new stack implementation for pkger. The CRUD store, the service stub, and the middleware are all coming together. Wanted to get this a review before that, b/c the size of the review would be pretty big if it was one big PR.
> feat(pkger): add foundation for pkger stack functionality

- authorizer/task_test.go
- cmd/influx/setup.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/launcher_test.go
- http/onboarding.go
- http/onboarding_test.go
- kv/auth.go
- kv/bucket.go
- kv/onboarding.go
- kv/onboarding_test.go
- kv/org.go
- kv/urm.go
- kv/user.go
- mock/onboarding_service.go
- onboarding.go
- testing/onboarding.go
Makes functions available that take a transaction to support importing and using kv as a library.
> feat: export transactions to support importing kv as a library

- cmd/influx/pkg_test.go
- pkger/http_remote_service.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_test.go
- pkger/service_tracing.go
- pkger/store.go
- pkger/store_test.go
> feat(pkger): add create stack implementation for service

- ui/package.json
- ui/src/onboarding/components/LoginForm.tsx
- ui/src/onboarding/components/SigninForm.scss
- ui/src/onboarding/containers/LoginPage.scss
- ui/src/onboarding/containers/LoginPage.tsx
- ui/yarn.lock
Updated Clockface to 2.0.3 to allow for use of the `InfluxDBCloudLogo`. Also updated the LoginPage to use the FunnelPage as a wrapper rather than the Page
> chore(ui): updated the login page to new design

- cmd/influx/pkg.go
> chore(influx): small cleanup of pkg command removing duplicate validation

- README.md
> chore(readme): update the working branch

- cmd/influx/authorization.go
- cmd/influx/backup.go
- cmd/influx/bucket.go
- cmd/influx/bucket_test.go
- cmd/influx/config.go
- cmd/influx/delete.go
- cmd/influx/main.go
- cmd/influx/organization.go
- cmd/influx/organization_test.go
- cmd/influx/ping.go
- cmd/influx/pkg.go
- cmd/influx/query.go
- cmd/influx/repl.go
- cmd/influx/secret.go
- cmd/influx/setup.go
- cmd/influx/task.go
- cmd/influx/transpile.go
- cmd/influx/user.go
- cmd/influx/write.go
> chore(influx): make runE middleware application explicit from caller

- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/tenant_test.go
- kv/duplicate_read_test.go
- tenant/duplicate_reads.go
- tenant/metrics_options.go
- tenant/middleware_bucket_metrics.go
- tenant/middleware_org_metrics.go
- tenant/middleware_urm_metrics.go
- tenant/middleware_user_logging.go
- tenant/middleware_user_metrics.go
- tenant/service.go
Can now add the nw meta service:
`INFLUXD_NEW_META_STORE` will enable it  (default false)
`INFLUXD_NEW_META_STORE_READ_ONLY` will make it read-only (default true)
> feat(tenant): add duplicate read service

- ui/src/onboarding/containers/SigninPage.tsx
> refactor(ui): enable background image on signin page

- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/stdlib/testing/testing.go
Closes https://github.com/influxdata/influxdb/issues/17065.
> chore: update flux

- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_logging.go
> feat(pkger): add create stack endpoint for http server

- query/control/controller.go
Revert changes in https://github.com/influxdata/influxdb/pull/17406
> refactor: change log level back for query controller panics

- ui/src/organizations/components/OrgNavigation.tsx
- ui/src/pageLayout/components/UserWidget.tsx
- ui/src/pageLayout/constants/navigationHierarchy.ts
- ui/src/pageLayout/containers/Nav.tsx
- ui/src/settings/components/SettingsNavigation.tsx
- ui/src/shared/constants/index.ts
> fix(ui): fix Quartz URLs

- http/helpers.go
- http/org_service.go
- paging.go
- tenant/http_client_bucket.go
- tenant/http_client_org.go
- tenant/http_client_user.go
- tenant/http_handler_urm.go
- tenant/http_handler_urm_test.go
- tenant/http_server.go
- tenant/http_server_bucket.go
- tenant/http_server_bucket_test.go
- tenant/http_server_org.go
- tenant/http_server_org_test.go
- tenant/http_server_user.go
- tenant/http_server_user_test.go
This helps encapsulate the requirements for the tenant service into the tenant specific package.
> feat(tenant): Add in api elements to tenant service

- cmd/influx/bucket.go
- cmd/influx/pkg.go
bucket|config|secrets|setup|user cmds all afffected in this PR
> feat(influx): normalize output tables and provide json out for several cmds

- cmd/influx/config.go
- cmd/influx/config/config.go
- cmd/influx/organization.go
- cmd/influx/secret.go
- cmd/influx/setup.go
> feat(influx): add support for json out and hide headers to additional influx commands

- tenant/storage.go
- tenant/storage_urm.go
> feat(tenant): add urm indexing into the tenant service

- pkger/README.md
> chore(pkger): add additional documentation for pkger

- ui/src/shared/components/TokenCodeSnippet.tsx
Refresh token button was disabled 
Fixed the way token button was being disabled
> fix(ui): fixed export token refresh bug

- cmd/influx/pkg.go
> fix: add missing flag register to task run list cmd for json out and hide header flags

- ui/src/clientLibraries/constants/index.ts
- fixed examples for PHP 
- fixed examples for JavaScript/Node.js
- fixed examples for Python
- fixed examples for Ruby
> docs(clientLibs): fix examples for PHP and JavaScript/Node.js

- jsonweb/token.go
Reverts https://github.com/influxdata/influxdb/pull/17535
> fix: revert token change to add user ID

- cmd/influx/pkg.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/models.go
- pkger/models_test.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_logging.go
- pkger/service_test.go
- pkger/testdata/bucket.yml
> feat(pkger): add stack state management for buckets

- ui/cypress/e2e/dashboardsView.test.ts
- ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx
Closes #17513
i let all the variables in. @russorat only wants some of the variables in. the good ones. the kind you can change, and the page works more gooderer.
> fix: filter variables to only those you are using

- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/parser.go
- pkger/service.go
> feat(pkger): add stack state management for labels

- ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
Closes #17463
felt like a quick win
> feat: metaKey click opens dashboards in a new tab

- ui/package.json
- ui/src/external/monaco.flux.lsp.ts
- ui/yarn.lock
> chore: update LSP dependency to 0.4.2

- cmd/influx/pkg.go
- http/swagger.yml
- pkger/models.go
- pkger/models_test.go
- pkger/service.go
- pkger/service_test.go
> chore(pkger): refactor summary/diff types for Endpints|Checks|Variables

- cmd/influxd/launcher/pkger_test.go
- notification/check/check.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/service.go
> chore(pkger): add stack state management for checks

- kit/tracing/tracing.go
- query/control/controller.go
I think it is a nice utility function that I would like to use
elsewhere.
So I decided to move it out to the tracing package.
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
> chore(tracing): Span with Prometheus Metrics moved to kit/tracing

- ui/src/clientLibraries/components/ClientGoOverlay.tsx
- ui/src/clientLibraries/constants/index.ts
> docs(client-libs): update-go-client

- go.mod
- go.sum
> chore: update flux to latest algow

- ui/src/cloud/reducers/limits.ts
```
response from /api/v2private/orgs/844910ece80be8bc/limits:
{
orgID: "844910ece80be8bc"
rate: null
bucket: null
task: null
dashboard: null
check: null
notificationRule: null
notificationEndpoint: null
feature: {allowDelete: true}
}
```
> fix: sick of seeing this error

- ui/src/index.html
- ui/src/onboarding/containers/LoginPage.scss
- ui/src/onboarding/containers/LoginPage.tsx
- ui/src/onboarding/containers/LoginPageContents.tsx
- ui/src/shared/utils/pageTitles.ts
This PR intends to sync up changes that occurred with the Quartz sign-up page. Since the two pages should be identical, any changes made on one should be reflected in the other.
> chore(ui): updated login page styling to match Quartz

- ui/src/pageLayout/components/CloudNav.tsx
Closes idpe 6599
What it says on the tin.
> feat(cloud): change text on Upgrade button to Upgrade Now

- tenant/error.go
- tenant/service_bucket.go
- tenant/service_test.go
- tenant/service_urm_test.go
- tenant/storage_bucket.go
- tenant/storage_urm.go
- tenant/storage_urm_test.go
- tenant/storage_user.go
- testing/tenant.go
- testing/user_resource_mapping_service.go
@lyondhill do you think the tests are ok?
I relaxed some assumptions, because I thought about it more and.. That's what I came up with 👍
> fix(tenant): make storage pass tenant tests

- cmd/chronograf-migrator/main.go
- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/service.go
- variable.go
> chore(pkger): add stack state management for variables

- go.mod
- go.sum
> build(flux): update Flux to v0.65.0

- cmd/influxd/launcher/pkger_test.go
- notification/endpoint/endpoint.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/service.go
> chore(pkger): add stack state management for notification endpoints

- CHANGELOG.md
- services/httpd/handler.go
- services/httpd/handler_test.go
Backport https://github.com/influxdata/influxdb/pull/17638 to 1.8
> fix: verify precision parameter in write requests

- cmd/chronograf-migrator/main.go
- cmd/influx/pkg.go
- pkger/clone_resource.go
- pkger/models.go
> feat(pkger): update dashboards with unique constraints

- kit/metric/client.go
- tenant/middleware_bucket_metrics.go
- tenant/middleware_onboarding_metrics.go
- tenant/middleware_org_metrics.go
- tenant/middleware_urm_metrics.go
- tenant/middleware_user_metrics.go
Allow the red metric system to be more generic about what it takes.
> feat(metrics): allow red metrics to be more generic

- ui/src/authorizations/components/ViewTokenOverlay.tsx
> fix(ui): enable token overlay headers to wrap

- cmd/influx/pkg.go
- http/swagger.yml
- pkger/models.go
> feat(pkger): extend tasks with unique constraints

- cmd/influx/pkg.go
> chore(pkger): refactor label mapping diff CLI table output

- CHANGELOG.md
- ui/src/shared/constants/fluxFunctions.ts
> fix(fluxFunctions): fix typo in assert methods, group under tests

- cmd/influx/pkg.go
- pkger/service.go
> fix(influx): add nil check for printing diff of endpoints and checks

- storage/flux/reader.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
> fix(flux): return internal influxdb error for cursor conflict

- http/swagger.yml
> fix(swagger): fix indention problem in swagger doc

- CHANGELOG.md
> chore(changelog): update changelog for beta-8

- models/points.go
This pull request changes point instantiation to reduce the number of required allocations by 20%.
> fix(models): Optimize allocations in NewPoint()

- pkger/models.go
- pkger/parser_test.go
> fix(pkger): add monotoneX geom type to valid geometries

- storage/flux/tags_cache.go
> fix(storage): fix data race on tags map

- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/models.go
- pkger/service.go
- pkger/service_models.go
- pkger/service_test.go
> chore(pkger): refactor embedded types out of stateful types

- ui/src/cloud/constants/index.ts
> feat(demodata): Fix demodata bucket name constant

- http/swagger.yml
- pkger/models.go
- pkger/models_test.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/service.go
- pkger/service_models.go
- pkger/service_test.go
> chore(pkger): refactor parser task state out into stateful type

- http/swagger.yml
- pkger/models.go
- pkger/models_test.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_models.go
- pkger/service_test.go
- pkger/testdata/telegraf.json
- pkger/testdata/telegraf.yml
> chore(pkger): refactor parser telegraf config state out into statefule type

- .circleci/config.yml
Release a nightly image of oss off the `feat/use-algo-w` branch
> feat: release a nightly image of algow

- ui/package.json
- ui/src/external/monaco.flux.lsp.ts
- ui/src/external/monaco.flux.messages.ts
- ui/src/external/monaco.flux.server.ts
- ui/src/shared/components/FluxBucketProvider.tsx
- ui/yarn.lock
> feat: ui measurement completion

- ui/src/shared/components/tables/TableCell.test.tsx
- ui/src/shared/components/tables/TableCell.tsx
Closes #17452
i have no idea how / where to test this, but it happens when you join a sum and a max output with union.
> fix: stop crashing all the time

- cmd/influx/pkg.go
- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/service.go
- telegraf.go
> feat(pkger): add stateful management for telegraf configs

- cmd/influx/pkg.go
small fixer upper noticed during previous work:
> chore(influx): tidy up print summary statements to include pkg names

- ui/package.json
- ui/src/Logout.tsx
fix(package.json): Updated the cloud-dev command to have the CLOUD_URL land on the same default port as Quartz UI
> revert(Logout): simplified Logout component functionality to maintain the original cloud logout

- ui/src/buckets/components/DemoDataBucketCard.tsx
- ui/src/cloud/constants/index.ts
Fix labels styling on demodata buckets.
Rename demodata bucket name to website monitoring bucket. 
In the acceptance environment the demodata bucket is called "Website Monitoring Demo Data Bucket" which got me confused last week. 
in every other environment the demodata bucket is called "Website Monitoring Bucket".
> feat(demodata): polish

- ui/package.json
- ui/src/external/monaco.flux.server.ts
- ui/yarn.lock
> feat: integrate tag key completion in ui

- pkger/service.go
- pkger/store.go
- pkger/store_test.go
> feat(pkger): extend store to support associations

- cmd/influxd/launcher/pkger_test.go
- pkger/parser_models.go
- pkger/service.go
- pkger/service_models.go
- query/stdlib/influxdata/influxdb/source_test.go
> feat(pkger): add stateful management for notification rules

- cmd/influx/config.go
- cmd/influxd/launcher/pkger_test.go
> fix(influx): add arg description into config usage

- cmd/influxd/launcher/pkger_test.go
- http/telegraf.go
- pkger/parser.go
- pkger/service.go
- pkger/service_models.go
references: #17434
this PR has some small fixes for the http pkg. Label http client pointing to wrong routes, and telegraf http client didn't support update. Those are remedied in this, first 2 commits of PR.
> feat(pkger): add support for stateful label mappings

- storage/engine.go
This pull request adds the ability to enable & disable the compactions for the series file, index, & TSM1 engine within a `storage.Engine`.
> feat(storage): Add compaction enablement API to Engine.

- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/querytest/compiler.go
- query/stdlib/influxdata/influxdb/from_test.go
- query/stdlib/influxdata/influxdb/rules.go
> chore: update flux to v0.67.0

- cmd/influxd/launcher/launcher.go
- http/platform_handler.go
- tenant/doc.go
We have reached the stage wehre the new tenant service is being used and
is stable but we want to get it in more hands and used as the default service.
> feat(tenant): change the tenant services default behavior to enabled

- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_test.go
- pkger/service_tracing.go
- pkger/store.go
- pkger/store_test.go
> feat(pkger): add list operation to stacks

- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/errors.go
- http/errors_test.go
- http/swagger.yml
- kit/transport/http/api.go
- kit/transport/http/error_handler.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_test.go
- pkger/service_tracing.go
- pkger/store.go
- pkger/store_test.go
- ui/cypress/e2e/dashboardsView.test.ts
- ui/cypress/support/commands.ts
- ui/src/shared/components/RefreshingView.tsx
- ui/src/shared/components/TimeSeries.tsx
- ui/src/variables/actions/thunks.ts
- ui/src/variables/components/VariableDropdown.tsx
- ui/src/variables/selectors/index.tsx
- ui/src/variables/utils/hydrateVars.test.ts
- ui/src/variables/utils/hydrateVars.ts
> chore: merge master into algo-w branch

- ui/src/Logout.tsx
- ui/src/index.tsx
- ui/src/mockState.tsx
- ui/src/shared/actions/flags.ts
- ui/src/shared/containers/GetFlags.tsx
- ui/src/shared/reducers/flags.ts
Last piece for influxdata/idpe#6654 until we start testing IRL. Works fine with the OSS backend. Mimics the `GetMe` and `GetOrganizations` container patterns in order to ensure the user has loaded flags for themselves before beginning.
sorry about the whitespace only changes in `src/index.jsx`, but i gotta get them stats up somehow
> feat: frontend flags

- ui/src/buckets/components/DemoDataDropdown.scss
- ui/src/buckets/components/DemoDataDropdown.tsx
quick optimization for determining whether a demodata bucket is one that has already been added.
> feat(demodata): Optimize demodata lookup

- ui/package.json
- ui/yarn.lock
> chore: update lsp dependency to 0.5.5

- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- ui/src/buckets/components/DemoDataDropdown.scss
- ui/src/buckets/components/DemoDataDropdown.tsx
> chore: update flux to latest revision

- cmd/influxd/launcher/pkger_test.go
- kv/notification_endpoint.go
- kv/store_index.go
- kv/store_index_test.go
- kv/variable.go
- pkger/service.go
> chore(pkger): make stack integration tests indepdenent

- cmd/influxd/launcher/pkger_test.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
>  chore(pkger): handle edge cases that can manifest from users in the platform and stateful pkg applications

- pkger/service_test.go
> chore(pkger): make export test assertions deterministic

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> chore(pkger): handle edge cases for buckets that manifest from user interaction

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> chore(pkger): handle edge cases for checks that manifest from user interaction

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> chore(pkger): handle edge cases for dashboards that manifest from use interaction

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> chore(pkger): handle edge cases for labels that manifest from user interaction

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> chore(pkger): handle edge cases for endpoints that manifest from user interaction

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> chore(pkger): handle edge cases for rules that manifest from user interaction

- ui/src/organizations/components/OrgNavigation.tsx
> Fix: 404 page on about 'users'

- CHANGELOG.md
- cmd/influx/pkg.go
> feat(influx): extend CLI with stack list and remove commands 

- ui/package.json
- ui/yarn.lock
> chore: update LSP

- inmem/session_store.go
- inmem/session_store_test.go
- kv/session.go
- session.go
- session/errors.go
- session/http_server.go
- session/http_server_test.go
- session/middleware_logging.go
- session/middleware_metrics.go
- session/service.go
- session/service_test.go
- session/storage.go
- session/storage_test.go
- task/backend/analytical_storage.go
- tenant/middleware_onboarding_auth.go
- tenant/storage.go
- testing/session.go
This new session service has the ability to work independant of other systems
it relies on having its own store type which should allow us to be more flexible
then using the built in kv system.
I have included an in-mem session store.
> feat(session): Build out a new session service

- ui/src/shared/components/CloudUpgradeButton.tsx
- ui/src/shared/components/CloudUpgradeNavBanner.tsx
> fix: add default value for "settings"

- CHANGELOG.md
Small task to update CHANGELOG for recently merged PR #17764
> chore(CHANGELOG): update to include recently merged PR #17764

- ui/src/cloud/actions/demodata.ts
- ui/src/cloud/apis/demodata.ts
Demo-data member's api will be updated and this utilizes those new apis. (shouldn't break with the new api in place beforehand)
> feat: use new demodata member apis

- ui/src/index.tsx
- ui/src/notebooks/components/Notebook.tsx
- ui/src/pageLayout/constants/navigationHierarchy.ts
- ui/src/shared/selectors/flags.ts
This adds a conditional route for notebooks based off of a feature flag. just a nav button and empty page for readability.
work spun off of this exploration: #17966
> feat: notebook flag

- ui/src/cloud/actions/demodata.ts
work in this PR creates searchable differences in the error messages reported to HB
> feat(demodata): Disambiguate dd errors

- ui/cypress/e2e/tokens.test.ts
- ui/src/authorizations/components/GenerateTokenDropdown.tsx
- ui/src/authorizations/components/TokenList.tsx
- ui/src/authorizations/components/TokensEmptyState.tsx
- ui/src/authorizations/components/TokensTab.tsx
Closes https://github.com/influxdata/quartz/issues/2630
This updates the copy and some of the functionality of Token's "empty state".
> feat: tokens empty state

- e2e/features/monitoring/history.feature
- e2e/src/pages/monitoring/checkStatusHistoryPage.js
- e2e/src/step_definitions/monitoring/checkStatusHistoryStepDefs.js
- e2e/src/steps/monitoring/checkStatusHistorySteps.js
applied patch from https://github.com/bonitoo-io/selenium-accept-infl2/pull/56 for e2e tests
> tests: add click through test for history

- ui/package.json
- ui/src/external/parser.ts
- ui/src/shared/utils/getMinDurationFromAST.ts
- ui/src/timeMachine/actions/queries.ts
- ui/src/variables/utils/getWindowVars.test.ts
- ui/src/variables/utils/getWindowVars.ts
- ui/webpack.common.ts
- ui/yarn.lock
> fix: update flux parser to fix issues

- ui/src/cloud/apis/demodata.ts
response statuses are numbers and not strings :(
> feat(demodata): Response statuses are numbers

- ui/src/shared/selectors/flags.ts
still going to do some coordinating, but just putting this here.
https://github.com/influxdata/influxdb/issues/16742
> feat(demodata): Flip demodata feature flag

- authorizer/authorize_find.go
- authz.go
- cmd/influx/authorization.go
- cmd/influxd/launcher/launcher.go
- dbrp/error.go
- dbrp/http_client_dbrp.go
- dbrp/http_client_dbrp_test.go
- dbrp/http_server_dbrp.go
- dbrp/http_server_dbrp_test.go
- dbrp/middleware_auth.go
- dbrp/middleware_auth_test.go
- dbrp/service.go
- dbrp/service_test.go
- dbrp_mapping.go
- http/api_handler.go
- http/client.go
- http/swagger.yml
- mock/dbrp_mapping.go
- testing/dbrp_mapping_v2.go
This PR implements the HTTP endpoints required to expose the database retention mapping feature to the outside
> feat: dbrp service

- dbrp/http_server_dbrp.go
This pull request fixes calls to the API that were added between when tests for https://github.com/influxdata/influxdb/pull/18096 passed and when it was merged in.
> fix(dbrp): Fix API interface calls

- ui/package.json
- ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.test.tsx
- ui/yarn.lock
Closes #
upgrade, so we can remove the fancyscrollbars
> chore: upgrade clockface 2.2.0

- ui/src/shared/selectors/flags.ts
alphabetizing the keys of the flags objects for easier scanning
> chore: alphabetize flags list

- ui/src/notebooks/components/AddButtons.tsx
- ui/src/notebooks/components/Pipe.tsx
- ui/src/notebooks/components/PipeList.tsx
- ui/src/notebooks/context/notebook.tsx
- ui/src/notebooks/index.ts
- ui/src/notebooks/pipes/Example/index.ts
- ui/src/notebooks/pipes/Example/view.tsx
hopefully this turns moving thing around on
> feat: moving around

- query/point.gen.go
- query/point.gen.go.tmpl
Quiet staicccheck warning "should merge variable declaration with
assignment on next line (S1021)" by updating point.gen.go.tmpl and
re-generating point.gen.go.
> fix(query): address staticcheck warning S1020

- ui/src/shared/components/MultiGrid/MultiGrid.tsx
- ui/src/timeMachine/components/RawFluxDataTable.tsx
> Fix: Fancy scrollbars

- ui/src/clientLibraries/constants/index.ts
1. updated version of Java client
1. changed how to initialize Ruby client
> docs(clientLibs): updated version of Java client, changed how to initialize Ruby client

- http/swagger.yml
Proposed contract for the unification API
So we can start pulling frontend assets over to OSS from Quartz with less headaches.
Not a huge fan of the name `CloudUser` but `User` was already taken.  Open to suggestions.  Used [these client calls](https://github.com/influxdata/quartz/blob/master/assets/js/client/index.ts) as inspiration.
Apologies for the huge diff but the inconsistencies in quotations and spacing was bothering me.
The relevant chunks are:
https://github.com/influxdata/influxdb/pull/18167/files#diff-33aa613ab26f77a960b47c92852150afR4467
https://github.com/influxdata/influxdb/pull/18167/files#diff-33aa613ab26f77a960b47c92852150afR8602
> feat(unify): user and invite contract

- ui/src/organizations/components/OrgNavigation.tsx
- ui/src/pageLayout/components/UserWidget.tsx
- ui/src/shared/selectors/flags.ts
Closes https://github.com/influxdata/quartz/issues/2590
Let's remove this entirely.
> chore(multiUser): remove feature flag

- cmd/influx/ping.go
> fix: use skip-verify flag in ping

- ui/src/alerting/utils/history.ts
- ui/src/eventViewer/components/EventTable.scss
- ui/src/eventViewer/components/EventTable.tsx
- ui/src/eventViewer/components/LoadingRow.tsx
- ui/src/shared/apis/query.ts
- ui/src/shared/copy/notifications.ts
> Check statuses

- CHANGELOG.md
- ui/src/variables/components/VariableDropdown.tsx
Also update changelog
No issue, just small update changes
> fix: adjust dropdown width + changelog additions

- ui/src/checks/utils/index.ts
> fix(customChecks): bring back custom check saving

- tsdb/index.go
Backport of https://github.com/influxdata/influxdb/pull/18203
> fix(tsdb): Defer closing of underlying SeriesIDSetIterators

- ui/package.json
- ui/yarn.lock
> chore: update lsp to 0.5.11

- .goreleaser-nightly.yml
> fix: gorelease archive format updated for v0.135.0

- releng/_go_versions.sh
> chore: update go version to 1.13.8

- cmd/influxd/launcher/launcher.go
- flags.yml
- http/api_handler.go
- http/label_service.go
- kit/feature/list.go
- label/controller.go
- label/controller_test.go
- label/middleware_auth.go
- label/middleware_auth_test.go
- label/service.go
This PR adds a feature flag for testing and integrating the new refactored label service.
> feat: add feature flag for new labels service

- releng/source-tarball/fs/usr/local/bin/influxdb_tarball.bash
> chore: remove reference to dep ensure

- cmd/influx/pkg.go
adds the stackID to the printed summary for the `influx pkg` command
> chore(influx): provide stack ID in pkg application commands

- ui/src/shared/constants/fluxFunctions.ts
> chore(flux): Add Flux 0.68 functions

- flags.yml
- kit/feature/list.go
- ui/src/cloud/utils/rum.ts
- ui/src/index.tsx
Closes idpe 6933
Adds a feature-flagged call to the app metrics service, which writes metrics line data to tools.
> feat: add feature-flagged app metrics

- ui/cypress/e2e/telegrafs.test.ts
- ui/cypress/fixtures/routes.json
Closes #7302
Looks like we already had some telegraf tests
> chore: rename collectors to telegrafs

- ui/cypress/e2e/dashboardsView.test.ts
- ui/cypress/index.d.ts
- ui/src/dashboards/components/DashboardHeader.tsx
- ui/src/dashboards/components/NoteEditorOverlay.tsx
> test(e2e): dashboard notes

- http/write_handler.go
- http/write_handler_test.go
> fix: ensure the write endpoint contains a bucket in the request

- ui/src/cloud/utils/rum.ts
`/app-metrics` => `/api/v2/app-metrics`
> fix: update app-metrics path to point to the right place

- e2e/src/pages/settings/variablesTab.js
- ui/cypress/e2e/variables.test.ts
- ui/src/variables/components/CSVVariableBuilder.tsx
- ui/src/variables/components/MapVariableBuilder.tsx
- ui/src/variables/components/UpdateVariableOverlay.tsx
- ui/src/variables/components/VariableCard.tsx
- ui/src/variables/components/VariableForm.test.tsx
- ui/src/variables/components/VariableForm.tsx
Closes influxdata/idpe#7328
Closes influxdata/idpe#7330
Closes influxdata/idpe#7329
Closes influxdata/idpe#7331
> test(e2e): variables

- ui/src/notebooks/pipes/Visualization/style.scss
- ui/src/notebooks/pipes/Visualization/view.tsx
- ui/src/timeMachine/components/view_options/ViewTypeDropdown.tsx
> feat: support all of the view types

- ui/src/notebooks/components/NotebookPipe.tsx
- ui/src/notebooks/components/PipeList.tsx
- ui/src/notebooks/components/header/Submit.tsx
- ui/src/notebooks/components/panel/NotebookPanel.tsx
- ui/src/notebooks/context/notebook.tsx
- ui/src/notebooks/context/query.tsx
- ui/src/notebooks/index.ts
- ui/src/notebooks/pipes/Visualization/index.ts
- ui/src/notebooks/pipes/Visualization/style.scss
- ui/src/notebooks/pipes/Visualization/view.tsx
- ui/src/shared/components/EmptyQueryView.tsx
- ui/src/shared/components/ViewSwitcher.tsx
- ui/src/shared/components/XYPlot.tsx
- ui/src/timeMachine/components/view_options/ViewTypeDropdown.tsx
make a graph show up, finish hooking up the loading / error states, general bug fixing and lifecycle definitions (like what happens if you add a visualization to a query cell that has already been called)?
> feat: looking at some graphs

- pkg/httpc/req.go
> feat(httpc): extend request with Auth beahvior

- ui/src/notebooks/components/EmptyPipeList.tsx
- ui/src/notebooks/components/Notebook.tsx
- ui/src/notebooks/components/header/Submit.tsx
- ui/src/notebooks/components/header/index.tsx
- ui/src/notebooks/pipes/Query/Results.tsx
- ui/src/pageLayout/constants/navigationHierarchy.ts
Closes https://github.com/influxdata/idpe/issues/7514
> refactor(ui): rename "Notebooks" to "Flows"

- .goreleaser-nightly.yml
- .goreleaser.yml
- Makefile
> fix(goreleaser): update config for goreleaser nightly releases

- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/service.go
> fix(pkger): provide charts when export stack dashboards by stack

- pkg/httpc/req.go
> chore(httpc): extend httpc reqs with tracing

- ui/src/cloud/utils/rum.ts
the previous writer was in the wrong format, this conforms correctly
> fix: fix points writing to rum endpoint

- ui/cypress/e2e/explorer.test.ts
- ui/src/timeMachine/components/RawFluxDataGrid.tsx
- ui/src/timeMachine/components/RawFluxDataTable.tsx
Closes #18152
See also https://github.com/influxdata/influxdb/pull/18151
> Test for loading data when scrolling error

- ui/src/notebooks/components/panel/NotebookPanelTitle.tsx
- ui/src/notebooks/pipes/Visualization/style.scss
- ui/src/notebooks/pipes/Visualization/view.tsx
- ui/src/notebooks/pipes/markdown/MarkdownPanel.tsx
- When markdown monaco blurs, switch to preview mode
- Clicking a markdown cell switches to edit mode
- Style visualization cells to look more consistent with other cell types
- Allow spaces in cell names (instead of replacing with `_`)
> refactor(ui): misc polish on flows UI

- kv/store_base.go
> chore(kv): update tracing with bucket/resource tags for store base

- storage/reads/array_cursor_test.go
This just creates a common test helper to make it easier to write unit tests that test aggregate array cursors.
> test(storage/reads): create a test helper for agg array cursor tests

- pkger/http_server.go
> chore(pkger): drop unnecessary middleware for http server

- pkger/http_server.go
fixes up a loose end with the http endpoints that can return either yaml or json. This is useful when hitting an endpoint for exporting resources in the form of a template. It now matches up with the swagger definitions.
> chore(pkger): fixup Accept/Content-Type header inspection in export endpoints

- ui/src/variables/components/MapVariableBuilder.tsx
Closes #16907
added more descriptive label to map variable text area
> chore(variables): changed map variable label

- http/router.go
> chore(http): add panic mw for chi base router

- http/router.go
- http/router_test.go
> chore(http): add route path to panic log message

- e2e/features/monitoring/history.feature
- ui/cypress/e2e/checks.test.ts
- ui/src/alerting/components/SearchBar.tsx
- ui/src/checks/components/CheckCardContext.tsx
- ui/src/checks/components/CheckMetaCard.tsx
closes https://github.com/influxdata/idpe/issues/7336 
closes https://github.com/influxdata/idpe/issues/7337
> test: Check history tests

- query/select.go
> feat(query): Parallelize field iterator planning

- ui/cypress/e2e/variables.test.ts
Closes influxdata/idpe#7325
Closes influxdata/idpe#7324
Closes influxdata/idpe#7323
Closes influxdata/idpe#7322
> test(e2e): create CSV, map, and query variables

- ui/src/notebooks/components/AddButtons.tsx
- ui/src/notebooks/index.ts
- ui/src/notebooks/pipes/Query/index.ts
- ui/src/notebooks/pipes/Spotify/editor.tsx
- ui/src/notebooks/pipes/Spotify/embedded.tsx
- ui/src/notebooks/pipes/Spotify/index.ts
- ui/src/notebooks/pipes/Spotify/style.scss
- ui/src/notebooks/pipes/Spotify/view.tsx
allows you to reorder the add button priority and conditionally disable pipe types
> feat: flux flow button order

- ui/src/shared/constants/fluxFunctions.ts
> chore(fluxFunctions): Update hasSuffix/Prefix

- ui/src/cloud/apis/reporting.ts
- ui/src/cloud/utils/reporting.ts
- ui/src/dataExplorer/components/DataExplorerPage.tsx
- ui/src/resources/components/GetResources.tsx
- ui/src/shared/actions/me.ts
- ui/src/shared/containers/SetOrg.tsx
- ui/src/timeMachine/actions/queries.ts
- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/timeMachine/components/QueryBuilder.tsx
- ui/src/timeMachine/components/SubmitQueryButton.tsx
> feat(reporting): Add reporting abstraction and init events

- ui/cypress/e2e/dashboardsIndex.test.ts
Closes #18487 
see: https://github.com/influxdata/influxdb/pull/18400
> test: retaining dashboard sort order

- http/api_handler.go
- http/router.go
> chore(http): export NewBaseChiRouter constructor

- http/api_handler.go
- http/router.go
> chore(http): fixup the chi base router using API type

- ui/src/cloud/utils/reporting.ts
- ui/src/timeMachine/actions/queries.ts
reporting EP needs nanosecond precision timestamp.
> feat(reporting): Convert ms to ns

- ui/cypress/e2e/clientLibraries.test.ts
Linked in issues, closing test issues
> test: Adding simple client libraries test

- ui/src/notebooks/components/panel/NotebookPanel.tsx
- ui/src/notebooks/context/notebook.tsx
- ui/src/notebooks/pipes/Query/index.ts
- ui/src/notebooks/pipes/Visualization/view.tsx
- ui/src/shared/reducers/app.ts
- Minimap closed by default
- First cell can be deleted
- Update copy in empty script cells to be more instructive
- Update copy in empty visualization cells
> refactor(flows): update copy to improve usability

- ui/cypress/e2e/dashboardsView.test.ts
- ui/src/dashboards/components/NoteEditorPreview.tsx
Closes influxdata/idpe#7334
Closes influxdata/idpe#7260
> test(e2e): dashboard cell

- ui/src/notebooks/pipes/Query/Results.tsx
> fix: dont crash on empty result state

- cmd/influxd/launcher/query_test.go
- query/stdlib/influxdata/influxdb/source.go
- query/storage.go
> refactor: windowed read operation should include aggregate name

- http/swagger.yml
> fix(swagger): update swagger spec with correct list output for stacks

- ui/src/shared/utils/fromFlux.ts
> fix(ui): add removal of hidden newlines to the fromFlux parser

- ui/cypress/e2e/dashboardsIndex.test.ts
- ui/src/shared/components/inlineLabels/InlineLabelPopover.tsx
- ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx
> fix(popovers): Refactor popover to controlled component

- ui/src/shared/utils/formatStatValue.test.ts
- ui/src/shared/utils/formatStatValue.ts
> fix(ui): leave strings as strings in formatStatValue

- ui/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx
> fix: add back the refresh button in cloud

- .goreleaser.yml
> chore: remove draft: true in order to publish the container image

- .circleci/config.yml
make circleci look at the correct file for it's cache key
> fix: maybe looking at the correct file will help

- ui/src/shared/components/cells/Cells.tsx
- ui/src/types/dashboards.ts
> fix: Gauge size adjustment

- pkger/main_test.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_models.go
- pkger/service_test.go
vast majority of this PR is test cases to verify new service behavior
references: #18490
> feat(pkger): extend service with ability to skip resources on apply

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
- pkger/service_test.go
> fix(pkger): delete newly created stack when applying a template that encounters err

- pkger/service.go
- pkger/service_models.go
- pkger/service_test.go
> feat(pkger): extend service with ability to skip resources by kind

- tsdb/tsm1/engine_schema.go
This commit adds ref counting for files that we pull tag keys from. Previously, files were only ref counted during the time we extracted tag keys but this commit adds additional ref counting for the life of the `Engine.tagKeysNoPredicate()` function.
> fix(tsdb): Add refs for file-sourced tag keys

- CHANGELOG.md
- cmd/influx/config.go
- cmd/influx/config_test.go
> feat(influx): provide active config when running bare influx config cmd

- ui/cypress/e2e/dashboardsView.test.ts
- ui/src/dashboards/components/NoteEditorOverlay.tsx
> test: add note controls test

- pkger/service.go
- pkger/service_metrics.go
chore(pkger): fixup error messages
> feat(pkger): extend metrics to cover org and user id for template installations

- ui/src/cloud/utils/reporting.ts
- ui/src/resources/components/GetResources.tsx
- ui/src/shared/components/cells/CellContext.tsx
- ui/src/timeMachine/actions/queries.ts
- ui/src/timeMachine/actions/queryBuilder.ts
I'm going to try reporting durations for some of the easily duration-able events, like how long a function takes to execute.
> feat(reporting): events to durations
