- services/meta/client.go
Closes #16326 
this pr is to remove the double index increment when set meta data,
which is describe in the issue #16326
> fix(meta): remove double index increment of set meta

- CHANGELOG.md
- cmd/influx/pkg.go
also provides an interface to mix and match everything together. you can
now provide `-f` flags for file or directories, `-u` flags for urls, and
use the | to pipe in a pkg. all of which can be done at the same time.
> feat(influx): add ability to provide multiple urls to influx pkg command

- cmd/influx/main.go
there was an issue where you could call, `influx pkg summarize`
and the influx cli would actually prescribe that to `influx pkg` cmd
and pass summarize as an arg. This removes that ambiguity
> chore(pkg): remove ambiguity in wrong cmd calls within influx pkg cmd

- task/backend/scheduler/treescheduler.go
Closes #16764
This will reduce memory allocations in the scheduler by removing
unneccessary delete/replace actions on the btree that is used as an
internal priority queue.
> fix(tasks): Reduce allocations in scheduler

- http/swagger.yml
- pkger/http_server.go
- pkger/http_server_test.go
references: #16657 
This PR extends the pkger apply HTTP API to support multiple pkg submission.
> feat(pkger): extend HTTP API to enable users to submit multiple pkgs in one call

- CHANGELOG.md
- ui/package.json
- ui/yarn.lock
Closes https://github.com/influxdata/influxdb/issues/16489
Updates giraffe to fix the tooltip for stacked line graphs
> fix: update giraffe to fix graph tooltip

- http/query.go
- http/swagger.yml
- query/influxql/compiler.go
- query/influxql/config.go
- query/influxql/transpiler.go
- query/influxql/transpiler_test.go
This change allows for the InfluxQL language type to be used with the
/v2/query API endpoint.
This change also introduces a way to give the transpiler an explicit
bucket name instead of using the DBRPMapping service.
Requests to the endpoint will know the bucket name directly but will
likely not have run the migration step to populate the DBRP mappings.
> feat(query): adds support for influxql as language type for queries

- ui/src/authorizations/utils/permissions.test.ts
- ui/src/authorizations/utils/permissions.ts
Closes #influxdata/idpe#5940
Error message received when creating all access token:
```json
{
"code": "forbidden",
"message": "permission read:orgs/03cf84c67a620000/orgs is not allowed: read:orgs/03cf84c67a620000/orgs is unauthorized"
}
```
Resource `/orgs/{orgID}/orgs` isn't defined, removed the `orgs` entry from the authorizations portion.
Probably works.
> fix: remove orgs from token permission list

- CHANGELOG.md
- cmd/influx/bucket.go
- cmd/influx/internal/tabwriter.go
- cmd/influx/main.go
- cmd/influx/organization.go
- cmd/influx/secret.go
- cmd/influx/secret_test.go
- cmd/influx/setup.go
- cmd/influx/user.go
- http/org_service.go
- http/org_service_test.go
- testing/secret.go
Closes #16475
Add the http secret service, cli, and tests
> feat(cmd/influx): add secret cli

- ui/src/shared/apis/query.ts
- ui/webpack.common.ts
- ui/webpack.dev.ts
this removes the requirement for the prod builds to use the vendor cache to build. They receive no benefit from the speed up as they're only run once, and there are some weird artifacts that show up when building the vendor webpack at times (i'm looking at you monaco).
I figured it shouldn't cause friction for deployments.
also found a hard coded api route, so i added a prefix to it because i needed it for a project.
> remove vendor from prod builds

- http/auth_test.go
- kv/auth.go
- kv/auth_test.go
- kv/indexer_test.go
- kv/service.go
- kv/service_private_test.go
- testing/auth.go
This integrates auth lookup via index and also publishes auths not indexed to the new indexer.
When `FindAuthorizations` is called with a non-nil user or user ID, then an index lookup is first performed. Given there are not authorizations in the index, it falls back to full keyspace scan and publishes anything found in the keyspace to the new indexer type.
> feat(kv): Index Authorizations by User ID

- CHANGELOG.md
- http/errors.go
- pkg/httpc/client.go
2 issues from investigating this error. First is the status check func
did not identify it was a media unsupported issue adn tries to unmarshal
the empty response body. The 2nd, was the double content type headers were
causing an error. Locally this error does not surface, cannot repoduce on
macos, but in cloud it is persistent.
closes: #16819
> fix: remove duplicate content types from httpc requests

- ui/src/Logout.tsx
- ui/src/me/components/LogoutButton.tsx
- ui/src/pageLayout/components/CloudNav.tsx
- ui/src/shared/constants/index.ts
this reduces our frontend's image configuration down to one variable in the jenkins pipeline, which we can use as an injection point for some fancy redirect rules.
Instead of:
`influxdb-ui => cloud2.influxdata.com/logout`
where we have to change that last variable for our different cloud environments, now we can use:
`influxdb-ui => influxdb-ui/auth/logout`
where the `/auth` path contains a redirect and rewrite within our ingress rules that maps to our auth provider for the cluster (`cloud2.influxdata.com` in the previous example)
Once the rewrite rules are in place (which can be done after this is deployed), we just need to change this: 
https://github.com/influxdata/monitor-ci/blob/master/deploy/Jenkinsfile.deploy#L526
from `https://cloud2.influxdata.com` to `/auth`
> fix: ignore cluster specific hoopla

- CHANGELOG.md
- ui/src/cells/actions/thunks.ts
- ui/src/dataExplorer/components/SaveAsCellForm.tsx
Closes #15956 
Read-only users were being notified that created dashboards were successful even though no dashboards were being created
The dashboard creation process was ingesting any potential errors thrown throughout the process so the default success notification was being triggered. Continued bubbling errors so that the ultimate error was being caught
> fix(ui): fixed false success message that stemmed from error-swallowing throughout post process

- ui/src/cells/actions/thunks.ts
- ui/src/dataExplorer/components/SaveAsCellForm.tsx
Closes #15956
Problem
Read-only users were being notified that created dashboards were successful even though no dashboards were being created
Solution
The dashboard creation process was ingesting any potential errors thrown throughout the process so the default success notification was being triggered. Continued bubbling errors so that the ultimate error was being caught
> chore(ui): moved logic into thunk reducer

- cmd/influxd/launcher/launcher.go
- http/query_handler.go
Prior to this change influxql requests were sent to the same back end as Flux queries.
This MAY not always be the case. Now InfluxQL queries are specifically routed to the InfluxQLService.
In the case of this OSS build the FluxService and InfluxQLService are the same.
> fix(influxql): add explicit routing to influxql service

- kv/auth.go
- kv/urm.go
- kv/urm_test.go
- testing/user_resource_mapping_service.go
Closes #16833
Current Delete Authorizations action doesn't correctly remove the index from the right bucket.
This change removes the indexed key from the correct bucket.
UPDATE:
Includes a fix for user resource mapping delete. Which now correctly returns not found, when item in index that is not in source.
> fix(kv): delete authorization from correct index bucket

- kv/urm.go
- testing/user_service.go
We are trying to skip deletes that would remove keys
that have already been deleted.  This is a rather
extreme approach and I believe we should think about how
to fix user-resource-mappings.
It is possible that a cursor does not respect transactions and thus a range may contain already
deleted keys.  This is a workaround.
> fix(kv): push down org ID to skip in delete URM

- kv/urm.go
In the event that an index references a key that does not exist, do not bail. Keep going so that we finish the delete operation.
> fix(kv): Don't stop when key not found from index

- mock/reads_resultset.go
- mock/reads_resultset_test.go
- storage/reads/resultset_lineprotocol.go
This PR adds to helpers for working with `reads.ResultSet` and clients which require a `ResultSet` as input.
`mock.NewResultSetFromSeriesGenerator` is a function for transforming a `SeriesGenerator` from the `gen` package into a `ResultSet`. This is useful for mocking data and testing code which requires a `reads.ResultSet` instance.
Additionally, adds a `reads.ResultSetToLineProtocol` function, which transforms a `ResultSet` into InfluxDB line protocol. This is useful to simplify comparing the data from a `ResultSet` with a string.
> feat(mock): Add SeriesGenerator to ResultSet transformation

- ui/src/shared/components/tables/TableCell.tsx
Closes #16168
this takes the cells within the table view and sees if they match a simple url regexp. if they do, it makes them a link.
before it's brought up: https://stackoverflow.com/questions/1500260/detect-urls-in-text-with-javascript/1500501#1500501
this isn't that big of a deal if it fails, as the interaction just reverts to normal, or it's a link that no one wants to go to anyways.
> feat: adding in a simple regexp

- ui/cypress/e2e/explorer.test.ts
- ui/cypress/e2e/tokens.test.ts
- ui/package.json
- ui/yarn.lock
This PR is meant to update the current influxdb version of clockface in order to enable social sign-up functionality without creating confusion later on down the line. Below is a release history for clockface versions:
* [1.1.5](https://github.com/influxdata/clockface/releases/tag/v1.1.5) - Fixes Notification Component exports bug (added exports to Notification component so that it can be imported)
* [1.1.4](https://github.com/influxdata/clockface/releases/tag/v1.1.4) - Added VisibilityInput Component - allows users to toggle an input icon to hide/show their password
* [1.1.3](https://github.com/influxdata/clockface/releases/tag/v1.1.3) - Fixes LinkButton Component exports bug (added exports to LinkButton component so that it can be imported)
* …
> chore(ui): update clockface versions from 1.1.0 -> 1.1.5

- cmd/influxd/restore/command.go
- http/backup_service.go
Backups and restores should work whether or not the original installation uses
a credentials file and whether or not the backup contains a credentials file.
Closes #16723
> fix(backup): handle backup with no credentials file

- CHANGELOG.md
This updates the changelog to reflect the revert we shipped to auth and URM indexes.
> chore(changelog): update changelog to reflect revert of URM and auth indexes

- .circleci/config.yml
- Makefile
- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
This also prepends the `env` script (which sets CGO environment variables) that lets `staticcheck` pass.
The `continuous integration` tests will continue to fail until idpe is also green.
The `e2e` test failures seem related to notifications, that might be related to this?
https://github.com/influxdata/influxdb/issues/16809
> build: remove -tags libflux and FLUX_PARSER_TYPE from build and circleci config

- CHANGELOG.md
- ui/src/me/components/DashboardsList.tsx
- ui/src/me/constants/index.ts
connect #15544
Sorts the dashboard list on the homepage alphabetically
> fix(me): sort dashboards list

- CHANGELOG.md
- ui/src/checks/components/CheckMetaCard.tsx
Closes https://github.com/influxdata/influxdb/issues/16460
sets a default value for tags in case it comes in null.
> fix(checkmetacard): fix for tags being null

- CHANGELOG.md
- ui/src/authorizations/components/TokenList.tsx
Closes https://github.com/influxdata/influxdb/issues/15301
Fixes a bug where the tokens page wasn't able to be sorted by status
> fix(tokenlist): fix sort by status

- ui/src/timeMachine/apis/queryBuilder.ts
- ui/src/timeMachine/utils/queryBuilder.ts
Closes #16229
we escape some flux variables right before they get shot off into the aether
> fix: escaping tag values

- ui/src/timeMachine/reducers/index.test.ts
- ui/src/timeMachine/reducers/index.ts
Closes https://github.com/influxdata/influxdb/issues/16426
if you had multiple tabs, and you deleted the last tab (which you weren't on), we were incorrectly setting the value of activeQueryIndex.
> fix(timeMachine): do not set activeQueryIndex when deleting last tab

- ui/src/pageLayout/containers/Nav.tsx
- ui/src/shared/constants/index.ts
- ui/src/shared/utils/featureFlag.ts
Adding a cloud only feature flagged "NavBox" to the side nav for the cloud specfic `/users` page. 
No one could find where it was living in the Quartz nav.
> feat: add side nav for cloud users

- cmd/influx/authorization.go
- cmd/influx/backup.go
- cmd/influx/bucket.go
- cmd/influx/bucket_test.go
- cmd/influx/delete.go
- cmd/influx/main.go
- cmd/influx/organization.go
- cmd/influx/organization_test.go
- cmd/influx/ping.go
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influx/query.go
- cmd/influx/repl.go
- cmd/influx/secret.go
- cmd/influx/secret_test.go
- cmd/influx/setup.go
- cmd/influx/task.go
- cmd/influx/transpile.go
- cmd/influx/user.go
- cmd/influx/user_test.go
- cmd/influx/write.go
refactors test to use full call paths in addition. testing the full API for the `influx` cli tool. This is the first of several PRs to update this. The next ones will deal with eliminating the drift in other cmds that haven't been worked into shape yet.
work is in support of: #16876
> chore(influx): refactor influx cmd to use factory pattern

- notification/rule/http.go
- notification/rule/pagerduty.go
- notification/rule/pagerduty_test.go
- notification/rule/rule.go
- notification/rule/slack.go
An accidental omission of status a level check resulted in all statuses
triggering notifications for pagerduty rules. This was not caught due
to insufficient testing of the pagerduty rule.
> fix(notification/rule): add alert level filtering to pagerduty rule

- notification/rule/pagerduty.go
- notification/rule/pagerduty_test.go
:facepalm:
As of https://github.com/influxdata/influxdb/pull/16952 we introduced using the experimental package, but we forgot to import it in pagerduty.
> fix(notification/rule): import experimental package for pagerduty rule

- cmd/influx/task.go
- http/client.go
- http/task_service.go
- http/task_service_test.go
Closes #16863
This PR refactors the API functions in the HTTP Task Service to use the new httpc client. This is part of the work to add membership/ownership tests for the API.
> refactor(tasks): add Client to http TaskService

- ui/src/shared/constants/fluxFunctions.ts
Updated `fluxFunctions.ts` with new packages and functions introduced in Flux 0.60.0 and 0.61.0.
> chore(flux): add functions for flux 0.60.0 and 0.61.0

- CHANGELOG.md
- ui/src/shared/constants/fluxFunctions.ts
> fix(fluxFunctions): fix category on fromRange

- CHANGELOG.md
- ui/cypress/e2e/queryBuilder.test.ts
- ui/src/timeMachine/components/TagSelector.tsx
- ui/src/timeMachine/selectors/index.test.ts
- ui/src/timeMachine/selectors/index.ts
Closes #16783 
A picture is worth a thousand words, so here:
**WRONG:**
**Right:**
* **Wrong**: The grouping options map to tag values
* **Right:** The grouping options map to columns
> fix: query builder groups on columns, not tag values

- CHANGELOG.md
- ui/src/alerting/components/AlertingIndex.scss
- ui/src/alerting/components/AlertsColumn.tsx
- ui/src/shared/constants/fluxFunctions.ts
Closes #16827
Resource lists were overflowing past the confines of the parent container
Updated the CSS to hide the overflow and updated the dimension of the inner div to allow for scrolling
> fix(ui): fixed overflow issue on scrollbar list

- tsdb/index/inmem/inmem_test.go
- tsdb/shard.go
With 0ccea81729, it should be checking `PartialWriteError` instead of `*PartialWriteError`
> fix(tsdb): incorrect error type in type switch

- check.go
- http/check_service.go
- http/client.go
Adds a checks API client alongside checks API handlers.
This client does not implement `influxdb.CheckService` because that interface returns an `influxdb.Check` interface, which is not suitable for this use case (because, e.g. it provides a `GetTaskID` method, which would require embedding a task service inside the response object).
New unit tests are not added given this client is a thin wrapper on `httpc`. Tests for that package, as well as the handlers themselves, exercise all meaningful logic on these code paths.
> feat(http): checks client

- .github/CODEOWNERS
Storage team owns, and would like to keep an eye on, /storage/ and /tsdb/
> chore(codeowners): Add storage team

- CHANGELOG.md
- ui/package.json
- ui/yarn.lock
Closes #16984 
Scatterplots can once again render the tooltip correctly
> fix(ui): update giraffe to fix tooltip rendering in scatterplots

- .circleci/config.yml
Signed-off-by: Chris Goller <goller@gmail.com>
To help suss out race-y e2e tests, we'll be running them on an hourly cycle.
> build: run e2e tests hourly

- CHANGELOG.md
- pkger/models.go
- pkger/parser_test.go
> fix(pkger): elminate threshold color requirement for guage charts

- cmd/influx/query.go
- cmd/influx/repl.go
- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
The repl no longer takes in a querier and it will run everything
locally. The spec interface will now not be used and will be removed
from the http endpoint at some point.
> refactor(repl): remove the querier from the repl

- CHANGELOG.md
- cmd/influx/secret.go
- cmd/influx/secret_test.go
- cmd/influx/setup.go
Closes https://github.com/influxdata/influxdb/issues/16475
removes the confirmation of secret input, add an optional parameter for secret value
> fix(cmd/influx): ui change for secret

- pkger/service.go
- pkger/service_test.go
references #17038
first piece of fixing this bug. Still exploring if there are more issues with the root tasks themselves.
> fix(pkger): fix bug where tasks are exported for notification rules

- CHANGELOG.md
- ui/src/dashboards/components/DashboardHeader.tsx
Closes #17037
Closes #17022 
Set interval dropdown on the dashboard header wasn't updating the interval
Updated the function to set the status correctly - something that had been lost in the refactor
> fix(ui): fixed issue where dashboard header interval dropdown wasn't setting correctly

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
- pkger/service_test.go
wrong assumption in original design. The system tasks are actually
the CRUD tasks. Name is a bit confusing for user generated tasks.
closes: #17038
> fix(pkger): correct the export of tasks to include system type tasks

- ui/package.json
- ui/src/onboarding/containers/LoginPageContents.tsx
- ui/yarn.lock
This PR is part of a larger PR to add the sign-in functionality to IDPE. This particular PR is intended to add transitioning effects when users toggle between the sign-up and log-in form so that the transition is a bit smoother. Added react-spring as a dependency to keep with existing transition libraries that are used
> feat(ui): added transition effects between form toggling

- ui/src/Logout.tsx
- ui/src/authorizations/apis/index.ts
- ui/src/onboarding/containers/LoginPageContents.tsx
- ui/src/types/auth.ts
This is PR part of a larger PR that is intended to add sign-in functionality to IDPE. This particular PR deals specifically with logging out and allowing users to logout using the existing logout button
> feat(ui): added logout functionality to epic

- query/stdlib/testing/end_to_end_test.go
- query/stdlib/testing/testing.go
The PR updates the flux dependency to point to the tip of the `feat/use-algo-w` branch. Afterwards I had change occurrences of `semantic.MustLookupBuiltinType` to `runtime.MustLookupBuiltinType`.
The flux end to end tests no longer hang in influxdb. However there were 3 end to end test failures that had to be skipped. Issues were created and linked for each one. They are:
* https://github.com/influxdata/influxdb/issues/17064
* https://github.com/influxdata/influxdb/issues/17065
* https://github.com/influxdata/flux/issues/2570
> unskip flux end-to-end tests

- CHANGELOG.md
- cmd/influx/cli/flux.go
- cmd/influxd/run/server.go
- flux/builtin/builtin.go
- flux/control/controller.go
This PR lazily initializes Flux built-in functions when Flux is used.
It significantly reduces the startup time of the `influxd` and `influx` binaries when Flux is disabled / unused.
Before (4.66s):
```
↳ time bin/18/influx
bin/18/influx  4.66s user 0.19s system 198% cpu 2.441 total
```
After (10ms):
```
↳ time bin/18/influx
bin/18/influx  0.01s user 0.01s system 88% cpu 0.021 total
```
Closes #
> fix(flux): Reduce influxd and influx startup time if Flux unused

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- pkger/models.go
this is super painful, its a symptom of working with the task API. It requires the task be inlined in the query today. Painful b/c ordering matters, especially with `imports` as it turns out.
closes: #17069
> fix(pkger): fix issue with imports causing option task to be injected at wrong point

- CHANGELOG.md
- ui/cypress/e2e/explorer.test.ts
- ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
- ui/src/timeMachine/utils/insertFunction.test.ts
- ui/src/timeMachine/utils/insertFunction.ts
Closes #16668
Currently toggling from the query builder to the script editor will default aggregate functions that are selected to the initial part of the query.
Create a conditional check to update the range that we are adding to to be the end of the existing query. Also added logic to add a new line whenever an aggregate function is selected.
> fix(ui): updated default positioning for adding aggregate funcs when toggling from query builder

- ui/src/shared/constants/fluxFunctions.ts
Closes #17077
just changes the example text, which we also use to populate the function text on insertion.
> feat: change aggregateWindow default text

- CHANGELOG.md
- cmd/influx/authorization.go
Closes #16808 
display the user name
> fix(cmd/influx): fix auth user name

- CHANGELOG.md
- ui/cypress/e2e/dashboardsView.test.ts
- ui/src/dashboards/components/variablesControlBar/VariableDropdown.test.tsx
- ui/src/dashboards/selectors/index.ts
- ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.test.tsx
- ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.tsx
- ui/src/types/variables.ts
- ui/src/variables/utils/ValueFetcher.ts
- ui/src/variables/utils/hydrateVars.test.ts
- ui/src/variables/utils/hydrateVars.ts
- ui/src/variables/utils/resolveSelectedValue.ts
- ui/yarn.lock
Closes #17026
Variable maps that had previously been created were not mapping variables values out properly. 
Undid a change introduced in the following PR which improperly mapped keys of the maps as the value rather than the values:
https://github.com/influxdata/influxdb/commit/78244ce6dec0ed7f5f7be70394d939f3a3d2088a#diff-75e6c7f86f1381fe2013a292310d9d0eL164
> fix(ui): fixed regression bug that preventing variable maps from properly assigning values

- CHANGELOG.md
- pkger/clone_resource.go
- pkger/service_test.go
> feat(pkger): add ability to export table view charts

- cmd/influx/authorization.go
- cmd/influx/bucket.go
- cmd/influx/bucket_test.go
- cmd/influx/main.go
- cmd/influx/organization.go
- cmd/influx/organization_test.go
- cmd/influx/secret.go
- cmd/influx/secret_test.go
- cmd/influx/task.go
- cmd/influx/user.go
- cmd/influx/user_test.go
long-running ask from @sanderson :)
Change all places in the CLI where we have `find` to use `list`. We inconsistently use the two in our CLI, so this adds more consistency in the UX.
Also adds `find` (to make this non-breaking) and `ls` (to be more unixy) as aliases for the command.
> fix(cmd): use list instead of find in cli

- http/client.go
- http/notification_rule.go
This PR creates a new service, `NotificationRuleService` which implements `NotificationRuleStore` using the `httpc.Client`. This is part of the ongoing work to add pipeline test coverage for the API. 
The code in this PR follows a similar structure to the `NotificationEndpointService` added in this PR: https://github.com/influxdata/influxdb/pull/16188. This is because the Endpoint and Rule APIs are similar in structure. (For example, both `NotificationRuleStore` and `NotificationEndpointService` are based in an interface rather than a struct.)
The pipeline testing for this code will be added in an associated PR.
> refactor(api): add HTTPC client service to notification rules API

- CHANGELOG.md
- ui/cypress/e2e/buckets.test.ts
- ui/src/buckets/components/BucketCard.tsx
- ui/src/buckets/components/BucketOverlayForm.tsx
- ui/src/buckets/components/UpdateBucketOverlay.tsx
- ui/src/dataExplorer/components/DataExplorer.tsx
- ui/src/timeMachine/actions/queryBuilder.ts
Closes #https://github.com/influxdata/idpe/issues/6103
> feat(sampledata): Route from buckets index to Data Explorer

- kit/cli/viper.go
- kit/cli/viper_test.go
Allows custom types that implement the `pflag.Value` interface, which simplifies validation and error handling of flag processing.
> feat(cli): Extend flag support to pflag.Value types

- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- http/query.go
- http/query_handler.go
- http/query_handler_test.go
- query.go
- query/fluxlang/service.go
The language service abstracts away the parse source which breaks the
dependency without moving any of the code.
Fixes #16846.
> refactor(http): modify query handler to use a language service

- http/api_handler.go
This PR wraps the `SecretService` on the `OrgBackend` object in an authorizer. This is part of the ongoing work to update pipeline tests for the API.
> fix(secrets): wrap secrets service in authorizer

- CHANGELOG.md
- http/query.go
- http/query_handler_test.go
- http/query_test.go
Addresses influxdata/idpe#5862.
> fix(http): Require Content-Type for query endpoint

- CHANGELOG.md
- ui/cypress/e2e/checks.test.ts
- ui/src/timeMachine/components/TagSelector.tsx
- ui/src/timeMachine/components/builderCard/BuilderCardDropdownHeader.tsx
Closes #16956
Group functionality shouldn't exist on the query builder when setting up checks for alerts
Created custom logic to only display `filter` as an option and disable the dropdown to reduce functionality confusion
> fix(ui): disabled group functionality for check query builder

- services/httpd/handler.go
- services/httpd/v2_write_test.go
This commit adds a /v2/write endpoint that maps the supplied bucket and
org to a v1 database and retention policy.
Closes #16898
> feat(httpd): add /api/v2/write enpoint to 1.x

- CHANGELOG.md
- cmd/influx/bucket.go
- cmd/influx/setup.go
closes: #17107
```sh
$ influx setup -f -b bucket1 -o rg -u user -p some_pass -r 1h && influx bucket list
ID			Name		Retention	OrganizationID
cc8b0b3d091b4019	bucket1		1h0m0s		28eb53ac886c127a
```
> chore(influx): update setup cmd to allow for duration for retention

- .github/CODEOWNERS
We own the pkger tool, so adding that to CODEOWNERS.
Removing api-team, as that team no longer exists.
> chore(github): change CODEOWNERS for tools-team

- CHANGELOG.md
- ui/src/cells/selectors/index.ts
Closes https://github.com/influxdata/idpe/issues/6240
The getCells selector function was mapping over undefined values, so the cells were throwing an error when they were being configured
Added a filter so that the cells are filtered of falsey values before mapping them.
> fix(ui): fixed dashboard cell error for disk usage

- CHANGELOG.md
- http/query.go
- http/query_handler_test.go
- http/query_test.go
This is causing issues for some clients. We are rolling it back until we can completely assess the situation.
> fix(http): Revert requirement of Content-Type

- query/functions.go
Closes #17124
There are a few conditional blocks in functions.go that test a value, and if it is not nil, performs some operations and returns. If it IS false, then it returns nil simply by falling through:
here's an example:
```
// Emit emits the derivative of the reducer at the current point.
func (r *FloatDerivativeReducer) Emit() []FloatPoint {
if !r.prev.Nil {
// Calculate the derivative of successive points by dividing the
// difference of each value by the elapsed time normalized to the interval.
diff := r.curr.Value - r.prev.Value
elapsed := r.curr.Time - r.prev.Time
if !r.ascending {
elapsed = -elapsed
}    
value := diff / (float64(elapsed) / float64(r.interval.Duration))
// Mark this point as read by changing the previous point to nil.
r.prev.Nil = true 
// Drop negative values …
```
> refactor(functions): Save an indent level when checking for r.prev.Nil (Closes #17124)

- ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.tsx
variables crash in the data explorer when they are not type Map because lodash is... weird
> fix: stops variables from crashing

- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/service.go
- pkger/service_test.go
note: all associations are still included for resources that match the filter criteria.
this is work towards exporting by label(#17029)
> feat(pkger): add support for exporting all and filter by resource types

- CHANGELOG.md
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
currently, support by filtering labelName and or by resource kind
Closes #17029
> feat(influx): extend pkg export all cmd to allow for filtering of output

- CHANGELOG.md
- ui/cypress/e2e/dashboardsView.test.ts
- ui/cypress/e2e/explorer.test.ts
- ui/cypress/e2e/variables.test.ts
- ui/src/shared/utils/getMinDurationFromAST.ts
- ui/src/timeMachine/components/variableToolbar/VariableItem.tsx
- ui/src/timeMachine/components/variableToolbar/VariableToolbar.tsx
- ui/src/timeMachine/components/variableToolbar/VariableTooltipContents.tsx
- ui/src/variables/mocks/index.ts
- ui/src/variables/selectors/index.tsx
- ui/src/variables/utils/getTimeRangeVars.test.ts
- ui/src/variables/utils/getTimeRangeVars.ts
- ui/src/variables/utils/getWindowVars.test.ts
- ui/src/variables/utils/getWindowVars.ts
Closes #16058
Variable list was showing only created variables and not showing default variables
Default variables are populated whenever the query runs, so the solution involved calculating the default variables whenever the variable list was rendered & whenever the variable tooltip was being toggled. Here's how it looks like in action:
> fix(ui): displaying variable list default values

- kv/service.go
- ui/src/onboarding/containers/LoginPage.scss
In the past, the default was only being set if a service config wasn't
provided. But if a service config was provided and gave a zero value, it
would not fill in the default value. This changes the code so that it
will always set the default value if the session length is set to zero.
> refactor(kv): when no session length is set, use the default

- CHANGELOG.md
- ui/src/timeMachine/components/view_options/DecimalPlaces.tsx
Closes #16277
The default option for customizing a table's values would not be updated even when the input was selected.
Added an onFocus listener to trim values based on the custom input field
> fix(ui): updated trigger to be onFocus as well as onChange

- CHANGELOG.md
- ui/src/dataLoaders/components/collectorsWizard/select/StreamingSelector.tsx
- ui/src/telegrafs/components/Collectors.scss
Closes #16663 
Closes #17166 
1. Telegraf Config buttons were slightly off-center (too far to the right) (#17166)
2. Filtering through telegraf configs were resizing the cells beyond the screen size (#16663)
1. Removed specific css properties to ensure that the buttons are aligned correctly
2. Updated the sizing process so that cells don't update in size as they get filtered
> fix(ui): updated styling so that telegraf configs maintain their original size when filtering configs

- cmd/influxd/backup_util/backup_util.go
- tests/backup_restore_test.go
- tsdb/index/tsi1/index_file.go
- tsdb/index/tsi1/measurement_block.go
- tsdb/index/tsi1/tag_block.go
- tsdb/series_set_test.go
We remove usages of `tsdb.SeriesIDSet.UnmarshalBinaryUnsafe` and replace with `*tsdb.SeriesIDSet.BinaryUnsafe`, to reduce segfault risk.
> fix: remove some unsafe marshalling to reduce risk of segfault

- cmd/influxd/launcher/launcher.go
- storage/Makefile
- storage/flux/Makefile
- storage/flux/predicate.go
- storage/flux/reader.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/table_test.go
- storage/flux/tags_cache.go
- storage/flux/types.tmpldata
- storage/reads/datatypes/key_types.go
- storage/reads/series_cursor.go
- storage/reads/series_cursor_test.go
- task/backend/analytical_storage_test.go
This PR separates out the `flux` pieces from the main `reads` package within the storage libs. As the code is largely unrelated to the rest of reads, and the reads service uses components within the storage `flux` reference, we should pull this into a new package.
> feat(storageflux): move flux components out to separate package

- authorizer/bucket.go
- authorizer/bucket_test.go
- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- kv/bucket.go
This PR fixes an issue where users were able to access system buckets of an organization with which they are not affiliated.
> fix(buckets): prevent returning system buckets to unauthorized users

- authorizer/notification_endpoint.go
- authorizer/notification_endpoint_test.go
- http/notification_endpoint.go
This does not actually fix auth.
It only refactors it in a way that is conforming to other services.
Before:
```
Check that a user has permission to read/write an org to indirectly deduce that it can read/write endpoints
```
Now:
```
Check that a user has permission to read/write a endpoints (for the endpoint's org)
```
> fix(authorizer): fix endpoint handler auth

- CHANGELOG.md
- ui/src/timeMachine/actions/queries.ts
Closes https://github.com/influxdata/idpe/issues/6240
Race condition was leading to a bug where user was receiving an error due to an undefined variable
Replaced the `state` with `getState` to get the most up-to-date version of the state, thereby resolving the race condition error
> fix(ui): fixed yield bug that was caused by race condition

- cmd/influx_inspect/main.go
- cmd/influx_inspect/verify/tombstone/verify.go
- cmd/influx_tools/compact/command.go
- tsdb/engine/tsm1/tombstone.go
- tsdb/engine/tsm1/tombstone_test.go
This PR adds a new tool for verifying tombstone files. To use the tool simply point it at an arbitrary path; the default is `~/.influxdb`. 
Use the tool like this:
```
$ influx_inspect verify-tombstone
```
The tool will then find all of the `.tombstone` files recursively under that path and verify each one. Currently it verifies files serially; it would be trivial to parallelise this work in future. The path provided can be arbitrary—it doesn't need to be an InfluxDB data directory for example.
The tool iterates through each tombstone entry in each file. You can set verbosity levels to decide how much information you want:
- no verbosity set: tool tells you when it has completed verifying a tombstone file;
- `-v` (verbose): tool tells you when it's verifying a file and will tell you it's …
> feat(inspect): add influx_inspect verify-tombstone tool

- CHANGELOG.md
- dashboard.go
- notification/check/check_test.go
- notification/check/deadman_test.go
- pkger/models.go
- pkger/service_test.go
- testing/checks.go
- ui/cypress/fixtures/view.json
- ui/mocks/dummyData.ts
- ui/src/alerting/utils/customCheck.test.ts
- ui/src/shared/utils/mocks/resourceToTemplate.ts
- ui/src/shared/utils/resourceToTemplate.test.ts
- ui/src/timeMachine/reducers/index.ts
- ui/src/timeMachine/selectors/index.test.ts
- ui/src/views/helpers/index.ts
Closes #17130
1. Updates made to existing Checks were not registering the changes
2. Creating cells with Group as the aggregate function type were not maintaining the aggregate type
Updated the `BuilderConfig tag` struct to account for the `AggregateFunctionType` that had been passed in by the UI but was not being stored on the API. The consequence of this action allows the UI to have access to the `aggregateFunctionType` as a reference for making changes in the query builder. Put simply, the existing query builder is built around the fact that an `aggregateFunctionType` will be passed in as a tag property, but it was not. 
Check Update Fix:
Dashboard Cell Fix:
> fix(ui): fixed dashboard cells and check query builder update bug

- cmd/influxd/inspect/compact_series_file.go
- cmd/influxd/inspect/inspect.go
- tsdb/series_file.go
- tsdb/series_file_test.go
- tsdb/series_partition.go
- tsdb/series_segment.go
This pull request adds an offline command to compact series files:
```sh
$ influxd inspect compact-series-file \
[--sfile-path SERIES_FILE_PATH] \
[--tsi-path INDEX_PATH] \
[--concurrency N]
```
This is a forward port of https://github.com/influxdata/influxdb/pull/16542 except that the command has been separated out (instead of being embedded in `buildtsi`).
Closes https://github.com/influxdata/influxdb/issues/16890
> feat(storage): Series File Compaction

- CHANGELOG.md
- cmd/influx/authorization.go
- cmd/influx/backup.go
- cmd/influx/bucket.go
- cmd/influx/config.go
- cmd/influx/config/config.go
- cmd/influx/config/config_test.go
- cmd/influx/config/mock.go
- cmd/influx/config_test.go
- cmd/influx/debug.go
- cmd/influx/delete.go
- cmd/influx/main.go
- cmd/influx/ping.go
- cmd/influx/pkg.go
- cmd/influx/query.go
- cmd/influx/repl.go
- cmd/influx/setup.go
- cmd/influx/task.go
- cmd/influx/user.go
- cmd/influx/write.go
- http/backup_service.go
Closes https://github.com/influxdata/influxdb/issues/15302
add multiple profiles feature as suggested in the ticket
add the ability to setup against another cluster, even if you have a profile file
> feat(cmd/influx): add profile management

- client/README.md
- client/v2/client.go
- client/v2/example_test.go
- client/v2/params.go
- go.mod
- go.sum
This updates influxql to a newer version that supports complex bound
parameters. This allows bound parameters to be used as identifiers,
regexes, and durations along with the already existing strings, numbers,
and booleans.
This updates the influxdb client to support passing bound parameters as
part of the parameters json and updates the readme to show how to use
this feature.
> feat: add support for complex bound parameters

- services/httpd/accept.go
- services/httpd/response_writer.go
- services/httpd/response_writer_test.go
Closes #14296
Until the standard lib decides to include a standard function to correctly parse Accept headers, we can rely on [goautoneg](https://github.com/golang/go/issues/19307#issuecomment-511133691) library which is a Github port used by Prometheus.
I also added sub-tests as Table Tests for multiples scenarios around this problem.
Adding a new dependency for this amount of code may hurt a bit, so maybe we could add the code directly too.
> fix: services/httpd: parse correctly Accept header with extra test cases

- ui/src/authorizations/actions/thunks.ts
- ui/src/buckets/actions/thunks.ts
- ui/src/buckets/components/BucketsTab.tsx
- ui/src/checks/actions/thunks.ts
- ui/src/dashboards/actions/thunks.ts
- ui/src/dashboards/components/DashboardContainer.tsx
- ui/src/dataExplorer/components/DataExplorerPage.tsx
- ui/src/dataLoaders/actions/telegrafEditor.ts
- ui/src/labels/actions/thunks.ts
- ui/src/members/actions/thunks.ts
- ui/src/notifications/endpoints/actions/thunks.ts
- ui/src/notifications/rules/actions/thunks.ts
- ui/src/scrapers/actions/thunks.ts
- ui/src/shared/components/TimeSeries.tsx
- ui/src/tasks/actions/thunks.ts
- ui/src/telegrafs/actions/thunks.ts
- ui/src/templates/actions/thunks.ts
- ui/src/timeMachine/actions/queries.ts
- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/variables/actions/thunks.ts
Closes #16803
- Dashboard Queries search query string for bucket name, and make the query to the org bucket belongs to instead of users current org. 
- Buckets are filtered by org at the UI level instead of the buckets request containing orgID in query parameter
- Fix getResources bug which would cause unmount on refetch of resources. 
- Query builder uses api call to get buckets instead of creating a buckets query. 
Will add bucket type filtering to get sampledata buckets, after extending bucket type.
> feat(sampledata): Allow users to query buckets in 'other' org

- ui/src/alerting/utils/vis.test.ts
- ui/src/alerting/utils/vis.ts
This was done to reduce amount of data returned to the client. This is
problematic when there are a large number of series that get returned
from a query. Long term we will want to limit the topN tables so that
this is not an issue.
> fix(ui/src/alerting): reduce points per check from 300 to 100

- models/points.go
- models/points_test.go
Signed-off-by: Chris Goller <goller@gmail.com>
models.Points did not have a rendering to line protocol.  This adds it, tests, and some bonus vet changes.
> feat: render models.Points to string

- authorizer/bucket.go
- http/api_handler.go
Changes the authed bucket service to use the no auth URM service to do its internal system bucket authorization. The authed bucket service returns an error when a single malformed URM is returned, which is not the behavior we want here.
Note: The commit message is wrong here, but I'm not fixing it because this fix is for an ongoing issue we want to stop ASAP.
> fix(buckets): use no auth urm service internally in auth bucket service

- storage/config.go
- storage/engine.go
- tsdb/config.go
- tsdb/errors.go
- tsdb/series_iterators.go
- tsdb/series_set.go
- tsdb/seriesfile/config.go
- tsdb/seriesfile/series_file.go
- tsdb/seriesfile/series_partition.go
- tsdb/tsi1/dump_tsi1.go
- tsdb/tsi1/file_set_test.go
- tsdb/tsi1/index.go
- tsdb/tsm1/cache.go
- tsdb/tsm1/cache_entry.go
- tsdb/tsm1/engine_test.go
- tsdb/tsm1/errors.go
- tsdb/value/value.go
The objective, whether it is possible or not, is to remove all dependencies on the tsdb package from it's children (tsm1, tsi1, seriesfile, etc). This gets us closer to that goal.
> refactor(storage): move and remove to help cleanup tsdb package

- ui/assets/images/radial-power-level.svg
- ui/src/timeMachine/components/TimeMachine.scss
- ui/src/timeMachine/components/Vis.tsx
> feat(ui): display graphic in time machine top when in empty state

- testing/kv.go
This adds an edge case to the kv tests ensuring that forward cursor configured using `WithSkipFirstItem` handles a single item cursor properly.
> fix(kv): add test to ensure skip first item behaviour handles single item

- http/api_handler.go
- http/check_service.go
- http/notification_endpoint.go
- http/notification_rule.go
This PR does 2 things:
- makes it so that every resource uses an `authorizer.LabelService` by default.
- fixes resource type for label backends: some of them where mounted on the right endpoint, but with the wrong resource type (bad copy paste?)
> fix(http): make label service authorized by default

- CHANGELOG.md
- cmd/influx/completion.go
- cmd/influx/main.go
this feature adds completions for a users shell. The mac weirdness in the help uses the following [PR](https://github.com/spf13/cobra/pull/887) from cobra as inspiration.
> feat(influx): add completion command for users to generate the completions for the influx cli

- .circleci/config.yml
- etc/litmus_fail_notify.sh
- etc/litmus_success_notify.sh
- after successful E2E run after master build, run integration tests
Closes # Add OSS (influxdb) litmus extended tests when branch==master. litmus_daily is only running smoke tests now.
> chore(litmus): run integration tests on master:

- cmd/influxd/launcher/pkger_test.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/bucket.json
- pkger/testdata/bucket.yml
this work is the first of making resources ALL unique by `metadata.name`. The
`spec.name` is a means to rename an existing resource. This is all to support
pkger idempotency. The metadata.name field will be the unique identifier within
a pkg.
with this new `name` field, the errors are now necessary to improve. The nesting of a field that does not pass validation needs to be nested in the specific object it is from `metadata` or `spec`. This PR adds this additional error handling.
> feat(pkger): extend buckets to be able to define a bucket and rename it

- tsdb/series_iterators.go
- tsdb/series_iterators_test.go
- tsdb/series_set.go
Small cleanup to reduce complexity.
This PR is [the final commit](https://github.com/influxdata/influxdb/commit/0ffcc29fd9f13ce40629aa2341598ddc0c5d169b) in the reverted #17241, which caused incident inc-aws-error-rate-spi-5e6c1423, plus a failing regression test, and a fix.
> refactor(tsdb): remove read from unexported field

- ui/src/shared/constants/fluxFunctions.ts
Closes #
Adds the experimental `csv.from` function `fluxFunctions.ts`.
> chore(flux): add experimental csv.from function

- CHANGELOG.md
- ui/assets/images/dashboard-empty--dark.svg
- ui/assets/images/dashboard-empty--light.svg
- ui/src/dashboards/components/dashboard_empty/DashboardEmpty.scss
- ui/src/dashboards/components/dashboard_empty/DashboardEmpty.tsx
Closes #17150 
- Add empty state image assets for both light and dark modes
- Implement graphics in empty state
- Cleanup some old styles
> feat(ui): add dashboard empty state graphics

- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
This updates our rules test to create function expressions using the Rust parser and analysis, so that we are testing our rules against the kinds of things we'll actually see in production.
> test(query/stdlib/influxdata/influxdb): update rules_test to use algo-w

- tsdb/series_iterators.go
- tsdb/series_iterators_test.go
- tsdb/series_set.go
This reverts commit 0ec2b453b91c3f4102967ce5c73b96a8ac71a851.
Fixes panic.
> chore: Revert "refactor(tsdb): remove read from unexported field (#17279)

- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/stdlib/influxdata/influxdb/buckets.go
- query/stdlib/influxdata/influxdb/v1/databases.go
The `buckets()` and `v1.databases()` functions have been updated to
support their remote counterparts that were added to flux. These
functions now do the same thing as the `from()` call where they will
default to the current organization when run against the server and will
use the remote versions from the repl.
Fixes #17205.
> feat(query): update buckets and v1.databases calls

- tenant/middleware_bucket_metrics.go
- tenant/middleware_org_metrics.go
- tenant/middleware_urm_metrics.go
- tenant/middleware_user_metrics.go
This PR adds a metrics middleware wrapping the services that comprise the Tenant Service: User, URM, Bucket, and Org.
> feat(metrics): add metrics middleware to tenant service

- http/middleware.go
found this little bugger in integration tests
> fix(http): fixup logging for http middleware

- ui/src/index.tsx
- ui/src/organizations/actions/thunks.ts
- ui/src/shared/actions/me.ts
- ui/src/shared/utils/analytics.ts
Closes https://github.com/influxdata/growth/issues/41
(Private repo):
* adds a couple of helper methods to initialize the user in google tag manager
* calls those methods when user data and organization data are loaded
* fire up app
* open your console and look for `window.dataLayer`. it shouldn't exist
* without a lot of config to make cloud work locally, change [this](https://github.com/influxdata/influxdb/pull/17302/files#diff-8c33463caf3e87edc906ec5715cb6eabR68) and [this](https://github.com/influxdata/influxdb/pull/17302/files#diff-023642cbf29399507646a13659e14d24R31) line to say `if (CLOUD || true)`
* open up your console and look for `window.dataLayer` it should be there.
* if you prefer to just see an object with values, you can do something cutesy like:
```ts …
```
> feat(cloud): add userid and org id to gtm

- cmd/influxd/main.go
- cmd/influxd/migrate/command.go
- pkg/bufio/bufio.go
- tsdb/migrate/migrate.go
- tsdb/migrate/migrate_test.go
⚠️ **This is a prototype; it needs more work to be production ready**⚠️ 
:rotating_light: :rotating_light: :rotating_light:  **If you use this tool you may leave your 2.x InfluxDB data in a bad condition. Backup your 2.x data first!!** :rotating_light: :rotating_light:  :rotating_light: 
This PR adds a new sub-command to the `influxd` binary, called `influxd migrate`.
The migrator tool is responsible for taking databases from InfluxDB 1.x (where InfluxDB is `>= 1.7.10`), processing the TSM data within those databases, and rewriting it in an appropriate format to be used in InfluxDB 2.x.
The Migrator maps data in the following way:
```
mydb/autogen/2 --> Bucket mydb/autogen
mydb/autogen/3 --> Bucket mydb/autogen
otherdb/weekly/1 --> Bucket otherdb/weekly
```
**Process**
The process is as …
> feat(storage): prototype 1.x–2.x migration tooling

- ui/src/buckets/actions/thunks.ts
- ui/src/resources/constants/index.ts
- ui/src/timeMachine/actions/queryBuilder.ts
Closes #17068 
Users with more than 20 buckets could not see all their buckets
Increase the `limit` query parameter to 100.  
Implement an app wide pagination / filtering / infiniscroll solution for all resources.
> fix: set bucket limit to 100

- tsdb/seriesfile/series_file.go
- tsdb/seriesfile/series_file_test.go
- tsdb/seriesfile/series_partition.go
- tsdb/seriesfile/series_verify_test.go
- tsdb/tsi1/index.go
- tsdb/tsi1/index_test.go
- tsdb/tsi1/log_file.go
- tsdb/tsi1/partition.go
- tsdb/tsm1/engine_delete_prefix.go
- tsdb/tsm1/engine_delete_prefix_test.go
This pull request significantly improves the performance of deleting with predicate. Local tests show a delete of 1m points going from 20m+ to subsecond. The primary change is batching `Sync()` calls when deleting series & tag values from the index and deleting series from the series file.
> feat(tsdb): Bulk delete series performance improvement

- authorizer/task_test.go
- cmd/influx/setup.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/launcher_test.go
- http/onboarding.go
- http/onboarding_test.go
- kv/onboarding.go
- kv/onboarding_test.go
- mock/onboarding_service.go
- onboarding.go
- testing/onboarding.go
Renaming Generate in anticipation of a new method that will onboard
users other than the initial user. The intent is to simplify multi-user
setups.
Co-authored-by: Chris Goller <goller@gmail.com>
> refactor: rename Generate to OnboardInitialUser

- authorizer/authorize.go
- authorizer/authorize_find.go
- authorizer/bucket.go
- authorizer/check.go
- authorizer/check_test.go
- authorizer/dashboard.go
- authorizer/label.go
- authorizer/label_test.go
- authorizer/notification_endpoint.go
- authorizer/notification_rule.go
- authorizer/notification_rule_test.go
- authorizer/org.go
- authorizer/password.go
- authorizer/scraper.go
- authorizer/scraper_test.go
- authorizer/secret.go
- authorizer/secret_test.go
- authorizer/source.go
- authorizer/task.go
- authorizer/telegraf.go
- authorizer/urm.go
- authorizer/user.go
- authorizer/variable.go
- authz.go
This PR tries to lay out foundations for an auth mini framework.
The idea is that every resource will use the same methods exposed in `authorize.go`.
`authorize_find.go` was generated and edited by hand to avoid repeating that logic in every service.
As a PoC, the changes have been introduced in `bucket` and `dashboard`.
The whole point of this is to:
- clean up the code
- make every resource (almost) authorize in the same way
> refactor(authorizer): auth micro framework

- variable.go
Add a nil check for variable arguments to prevent a panic when checking if a Variable is valid during creation, etc.
> fix(variables): add nil check for variable arguments

- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/notification_rule.json
- pkger/testdata/notification_rule.yml
this PR makes notification rules unique by name within a pkg. A user can have notification rules within a pkg that have the same `spec.name` still. The `metadata.name` field must be unique.
references #17233
> feat(pkger): extend notification rules with ability to define and rename it

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/models_test.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/tasks.json
- pkger/testdata/tasks.yml
> feat(pkger): extend tasks with ability to define and rename it

- models/points_parser.go
- models/points_test.go
Closes https://github.com/influxdata/influxdb/issues/15829
Turns out the issue @sanderson seeing is not related to the batch writer, but a simple line breaker.
> fix(models): fix the line breaker

- CHANGELOG.md
- ui/src/buckets/selectors/index.ts
- ui/src/dataLoaders/actions/dataLoaders.ts
- ui/src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx
- ui/src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx
- ui/src/dataLoaders/selectors/index.ts
- ui/src/resources/selectors/index.ts
- ui/src/shared/components/CodeSnippet.scss
- ui/src/shared/components/TokenCodeSnippet.tsx
- ui/src/shared/copy/notifications.ts
- ui/src/telegrafs/components/TelegrafInstructionsOverlay.tsx
Closes #17118
1. The default buckets that were being passed were passing the system buckets in when they should've been filtering them out
2. Fetching tokens were broken in the normalization process due to a tenuous connection that existed between Telegraf Configs, Telegrafs, Labels, and Tokens
1. Passed in the correct selector to filter out the buckets to remove system buckets from the dropdown
2. After speaking with @russorat and @121watts, it became clear that tokens should be more in line with other conventions that are currently used by Apple, Github, etc... in that tokens that are generated should never be retrieved. That is to say that a token that is created should be stored by the user. If they lose their token, we should give them an opportunity to generate a new token. 
After …
> fix(ui): resolved telegraf bucket dropdown bug and undefined token issue

- kv/service.go
- kv/urm.go
- kv/urm_test.go
- testing/user_resource_mapping_service.go
This adds the user resource mapping by user ID index.
It currently just integrates the write paths (insert, delete) and adds the migrations necessary to intialize the index and populate it with existing source contents.
A subsequent change is necessary to enable the read-path. This does however add configuration to enable it when ready and it runs the test suites against this code with the read-path enabled.
> feat(kv): add user resource mapping by user index

- services/storage/store.go
The storage read service would return a nil cursor if there was no data
and no shards to read from. This modifies it to return an empty cursor
instead.
Fixes influxdata/flux#2641.
> fix: storage read service should not return a nil cursor

- pkger/service.go
- pkger/store.go
- pkger/store_test.go
updates stacks with a human readable/settable name and description. This is just to decorate the stack object with data that is meaningful to the user.
> feat(pkger): extend stack with name and description fields

- query/control/controller.go
This PR adds a stack trace that should help us find the origin of the panic in this issue: https://github.com/influxdata/EAR/issues/1449
> refactor(query): add stack trace to executeQuery in controller

- cmd/influxd/launcher/query_test.go
- go.mod
- go.sum
- http/document_test.go
- http/query.go
- http/query_test.go
- query/influxql/compiler.go
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/stdlib/testing/end_to_end_test.go
- task/backend/executor/executor.go
- task/backend/executor/support_test.go
This makes some changes to the `Compiler` interface used to issue Flux queries. In order to delay deserialization as long as possible, in order to do the deserialization in Rust, fields in serialized data structures like `FluxCompiler`, `ASTCompiler`, and `http.QueryRequest` have been changed to be typed as `json.RawMessage` instead of `*ast.Package`.
> refactor(http): change *ast.Package to json.RawMessage in query requests

- query/control/controller.go
This PR adds more error logging to the query execution function in the query controller to track down the source of this issue: https://github.com/influxdata/EAR/issues/1449
> refactor(query): add stack trace to query controller execution

- CHANGELOG.md
- task/backend/scheduler/treescheduler.go
Reuse the the `toDelete` and `toInsert` slices within the `TreeScheduler` to reduce the allocation churn when creating iterators for the B-Tree ascension.
This is an intermediate step to relieve some of the memory usage. We will be going farther than this in how we handle this iterator in the upcoming `TreeScheduler` refactor.
📎 influxdata/idpe#6479
> fix(task/scheduler): Reuse slices built by iterator to reduce allocations

- ui/src/dashboards/components/dashboard_index/DashboardCards.tsx
Closes influxdata/EAR#1466
no idea why this kinda sometimes worked if state was already loaded into localstorage, and not if it was fetched from the api, had a lot of red herrings based in state management surrounding this one. The core of the issue came down to firefox not rendering _sometimes_ when there was only a single row of results in the infinite scroll. If this doesn't work for the client, the next step is to address a potential race condition where the window is measured before state is loaded, but this fix made the problem disappear locally.
> fix: show more

- CHANGELOG.md
- cmd/influx/bucket.go
- cmd/influx/bucket_test.go
Closes #17277
Be able to delete bucket by name.
> feat(cmd/influx): add delete bucket by name

- CHANGELOG.md
- ui/src/checks/actions/thunks.ts
- ui/src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx
- ui/src/shared/components/TokenCodeSnippet.tsx
Closes #17267
Vague Error Message
Updated the error message to be explicit and actionable
> fix(ui): updated duplicate check error message

- query/control/controller.go
This PR reverts the changes in https://github.com/influxdata/influxdb/pull/17377 and https://github.com/influxdata/influxdb/pull/17392 and updates the log level for logging a stack trace for recovered panics in the `executeQuery` function
> refactor(query): change log level to record panic stack traces

- ui/src/me/components/LogoutButton.tsx
The existing PR addresses the problem that occurs once we integrate auth0 login capabilities into the UI. Since the existing `<LogoutButton />` component conditionally renders the logout button (and it's functionality) based on whether the UI is being displayed in cloud or not. However, since the existing Auth0 logout functionality is wrapped in a `CloudExclude` wrapper, a user is never really logged out of Auth0 on cloud. Instead, they are simply redirected based on the `CloudOnly` logic.
Since the existing `Logout` component already contains the appropriate "CloudOnly" logic we had integrated beforehand, this PR aims to reduce the logic down to one component that can work across OSS and Cloud.
Since we know that the current order of things is functioning, would it instead be more …
> fix(ui): fixed logout functionality so that Logout Component is displayed and used on cloud

- cmd/influx/main.go
- cmd/influx/pkg.go
- pkger/http_server.go
- pkger/parser.go
- pkger/parser_test.go
the `pkger.ValidSkipParseError` option allows our server to be the one to validate the
the pkg is accurate. If a user has an older version of the UI and our cloud gets updated
with new validation rules,they'll get immediate access to that change without having to
role their CLI build.
> chore(pkger): refactor influx pkg cmd to not validate in CLI and have server validate

- authz.go
- user_resource_mapping.go
- user_resource_mapping_test.go
Partially addresses #https://github.com/influxdata/idpe/issues/6341
Authorizes buckets resource that a user has member access to.
> feat(sampledata): Return bucket resources that user has member access to

- authorizer/agent.go
- authorizer/agent_test.go
- authorizer/auth.go
- authorizer/authorize.go
- cmd/influxd/launcher/launcher.go
- pkger/service.go
- pkger/service_auth.go
adds new AuthAgent type that can be reused across service middleware. is added to pkger for stack CRUD calls here.
> feat(pkger): add auth for pkger stack CRUDing

- CHANGELOG.md
- ui/src/utils/ajax.ts
- ui/src/utils/lineWriter.test.ts
- ui/src/utils/lineWriter.ts
Closes #17369
Adds a module that programmatically writes line data to the server, org and bucket specified.
[here's a gist](https://gist.github.com/hoorayimhelping/9e3fc42f152769c0ed9272fc17ebaa58#file-foo-diff-L93) of it being used to implement RUM
> feat: slightly configurable line writer

- ui/src/buckets/actions/thunks.ts
- ui/src/buckets/components/BucketAddDataButton.scss
- ui/src/buckets/components/BucketsTab.tsx
- ui/src/buckets/components/DemoDataDropdown.tsx
- ui/src/cloud/actions/demodata.ts
- ui/src/cloud/apis/demodata.ts
- ui/src/cloud/reducers/demodata.ts
- ui/src/cloud/utils/filterDemoData.ts
- ui/src/shared/utils/featureFlag.ts
- ui/src/store/configureStore.ts
- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/types/stores.ts
Partially Closes #6097
Query sampledata `/buckets` endpoint to get available demodata buckets for `Add demo data` dropdown
Request membership to a demodata bucket on click to demodata bucket dropdown item.
Query for demodata buckets user is member to on fetch buckets. 
All behind feature flag
> feat(sampledata): Add demo data dropdown and membership request to buckets

- CHANGELOG.md
- cmd/influx/main.go
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/service.go
- pkger/service_logging.go
- pkger/store.go
- pkger/store_test.go
> feat(pkger): add stack init cmd to influx cli

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- task/backend/scheduler/noop_scheduler.go
Closes influxdata/influxdb#17375
Introduces `--no-tasks` flag which disables Task scheduling.
> feat(influxd): flag to disable scheduling of tasks

- tenant/middleware_org_auth.go
This PR copies the org auth middleware to the new tenant service directory.
> refactor(tenant): move org auth layer to tenant service

- CHANGELOG.md
- cmd/influx/task.go
> feat(influx): add jsonout and hide headers support to task cmd

- CHANGELOG.md
- cmd/influx/config.go
- cmd/influx/config_test.go
Closes #17401
Add an easy way to switch config, manually tested
> feat(cmd/influx): easy switch config

- tenant/middleware_user_auth.go
Closes #17423
This PR moves the auth layer for the User service into the new tenant directory. (The old authorizer files should be removed when the services switch over to the tenant service entirely.)
> refactor(tenant): move user auth layer into tenant service

- cmd/influx/organization.go
> fix: add missing flag register to org cmd for json out and hide header flags

- flux/client/request.go
- flux/client/request_test.go
Closes #17195
Fixed ignoring dialect annotations.
> fix(query): use query dialect annotations specified in request

- services/snapshotter/service.go
Closes #9968
Properly read request payload.  I wasn't able to identify the problem in the original code but it was complex enough that it is better to replace it all with clearer code that also happens to work.
> fix(snapshotter): Properly read request body

- kv/index.go
- kv/urm.go
- tenant/storage_urm.go
- testing/index.go
This change swaps a `bucket.Get()` for a `bucket.ForwardCursor()` lookup for a single item in the `kv.Index.Walk()`.
This is in-order to address an issue with lots of individual `bucket.Get` calls in a single transaction when walking the index. This causes an issue with a particular implementation of `kv.Store`. Swapping it for a cursor aids this implementation by making the lookup act outside the transaction in this particular implementation of `kv.Store`.
> fix(kv): make index walk use cursor instead of get

- logger/config.go
Though the comments in the sample configuration file say that the default value for the level key in the logging section should be info, this doesn't appear to be so.
We should either update the documentation or update the code to ensure the default log level meets users' expectations.
> fix(logger): Ensure default level value is info

- ui/src/buckets/actions/thunks.ts
- ui/src/cloud/apis/demodata.ts
- ui/src/cloud/utils/filterDemoData.ts
- ui/src/timeMachine/actions/queryBuilder.ts
As per 6591, 
FindBuckets filters by orgID, limits the number of responses, and then filters by authorization. 
So if there is no filtering by orgID query parameter the limit may not return enough buckets to find one that user is authorized to read. 
In this PR we query demodata buckets, and peel off the orgID parameter if it exists, from the first returned bucket and supply the demodata orgID as a query parameter to the second getBuckets request to fetch demodata buckets user is authorized to read.
> feat(sampledata): Request buckets with demodata orgID

- cmd/influx/pkg.go
- go.mod
- go.sum
- http/swagger.yml
- pkger/http_server_test.go
- pkger/models.go
- pkger/models_test.go
- pkger/service.go
- pkger/service_test.go
provides mapping between pkgName and resource the diff represents. Now that
stacks are in place, the existing bucket may change names.
references: #17434 
example of the CLI updates. We have new an addiotional state that resources can be in (Removed) this new CLI design addresses:
> feat(pkger): extend DiffBucket with name for existing and new bucket values

- ui/src/shared/constants/fluxFunctions.ts
Adds Flux 0.65 functions – `geo.shapeData` and `experimental.join`.
> chore(flux): added Flux 0.65 functions

- CHANGELOG.md
- cmd/influxd/backup_util/backup_util.go
- tests/backup_restore_test.go
- tsdb/index/tsi1/index_file.go
- tsdb/index/tsi1/measurement_block.go
- tsdb/index/tsi1/tag_block.go
- tsdb/series_set_test.go
This reverts commit 30dab0331033af22472df89852247b72e4074e32.
This is to test whether this commit causes a doubling of heap memory.
> fix(tsdb): Revert "fix: remove some unsafe marshalling to reduce risk of segfault"

- ui/src/external/monaco.flux.server.ts
- ui/src/timeMachine/components/variableToolbar/VariableItem.tsx
the lsp breaks with a malformed ast, and an empty value is a malformed ast.
> fix: filter out empty nodes on the ast

- ui/src/timeMachine/actions/index.ts
- ui/src/timeMachine/actions/queries.ts
- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/timeMachine/components/Queries.tsx
- ui/src/timeMachine/components/Vis.tsx
- ui/src/timeMachine/reducers/index.ts
- ui/src/timeMachine/selectors/index.ts
Closes #17527 
when refactoring how variables are used in the system, a concept of "context" was added to share state between dashboards and time machine instances so that a time machine could sync it's variable selection state with the dashboard it was operating on. seems like this concept needs to be extended to include time as well, because the visualization of the time could be represented by a variable.
a follow up task is to go through and add a `currentContext` selector to reduce some of the copy pasta going on, but it's currently broken in production, so lets stop the bleeding first
> fix: adding contextual time

- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
The prometheus project doesn't adhere to the module suffix so any
attempt to use it as a library fails with go 1.13 or greater. The
workaround is to `go get` a specific commit revision that corresponds to
a tag and let go figure out a pseudo-version for it.
In this case, I updated the revision to the one pointed at by `v2.9.2`
since that is what the current `go.mod` file pointed at. I also updated
the go version to 1.13 inside of `go.mod` to be the same as influxdb.
See https://github.com/prometheus/prometheus/issues/6048 for details.
> ci(promqltests): update promqltests go.mod file to be compatible with go 1.13

- bolt/kv.go
- inmem/kv.go
- kv/store.go
- mock/kv.go
- testing/kv.go
This adds support for batch getting of keys on the Bucket interface.
There are some operations where a batch retrieval of keys from the underlying store would be more efficient. This exposes that ability.
> feat(kv): add support for batch getting keys on bucket interface

- CHANGELOG.md
- ui/src/timeMachine/actions/queries.ts
- ui/src/timeMachine/reducers/index.test.ts
- ui/src/timeMachine/reducers/index.ts
Closes #17364
Due to a confusing `falsy` check in a reducer, editing a dashboard cell showed the defaults or the query results for any changed properties. This fixes that.
1. Create a dashboard cell that is a `table` visualization
1. Add custom names to the columns in the `Customize` section
1. Save the cell
1. Observe the correct cell name in dashboard
1. Edit the cell again
1. Observe the incorrect cell names in the overlay
This fix changes it so that the final step shows the correct value.
> fix: editing a table cell shows the proper values and respects changes

- jsonweb/token.go
Adds a user ID to the JWT `Token` auth implementation. This implementation is still permission-based; this change just keeps the identity around on the token for reference.
> feat: include user ID with web token

- ui/src/checks/actions/thunks.ts
Closes idpe 6592
Checks in tools are hamstrung because there are more than 20 that need to be shown, but we currently only show 20. This bumps that limit up to `100` the API's hard cap.
1. go to monitoring and alerting
1. create new check
1. clone that check 20 or so times (I know)
1. on `master`, you should only see the 20 items (check 1 and its 19 clones)
1. on this branch, you should see more than 20.
> fix: tech-debt workaround - add limit of 100 to checks fetches

- go.mod
This PR updates the version of go required in our `go.mod` file to 1.13.
> fix(go.mod): Update go version in mod file to 1.13

- ui/src/variables/selectors/index.test.tsx
- ui/src/variables/selectors/index.tsx
this solves part 2 of #17513
summary of the problem is that when a value is loaded for a variable, it inherits an order from the resource. when you add or removing something, the order isn't being updated.
instead of chasing around all of the places where order might be manipulated, i kept the behavior as "use the order that is explicitly created by the user, and fill in anything else". as soon as they reorder something, it should fix itself
> fix: allow the addition of variables

- CHANGELOG.md
- ui/src/shared/components/tables/TableGraphTable.tsx
Rendering graphs in table view is kind of painful. Scrolling is a bit rough. This is a quick, small, low  hanging fruit.
Moved two fields out of React state into internal component state `this.state.foo` ➡️ `this.foo` so that changing them doesn't force re-renders needlessly.
Here is a comparison of the flamegraphs using React's profiling tools. These flame graphs represent scrolling the table at a normal speed. The graphs take place during the same slice of time - the start of the table scroll.
*master*
*branch*
Not a yuge win, but definitely less bursty on the flame graph. A couple of these types of small, easy wins will cumulatively make this feel much better.
I can share the performance `.json` files if you'd like to take a look yourself.
> perf: TableGraphTable: tweak rendering internal state

- tenant/middleware_bucket_logging.go
- tenant/middleware_org_logging.go
- tenant/middleware_urm_logging.go
- tenant/middleware_user_logging.go
This PR changes info level logs in the logging middleware of the tenant service to debug level, to reduce unwanted noise.
> refactor(tenant): change info level logs to debug

- kv/service.go
At the moment, the default session length only gets set to the default
when no service config is specified. So if a service config is used and
it does not set a value for the session length, then the session length
will be zero.
This modifies the creation of the kv service so that it will set the
default session length if the session length is set to zero (the default
value) instead of only doing it when no service config is specified.
> refactor(kv): set the default session length when not specified

- cmd/influx/pkg.go
- http/swagger.yml
- pkger/models.go
- pkger/models_test.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
the pkgName refers to the unqiue label resource within the pkg and the
Remove field indicates the label will be removed when applying the pkg
references: #17434
> feat(pkger): extend labels diff and summary types to include PkgName and Remove

- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
`Access-Control-Allow-Headers` header should also contains a `User-Agent` because we want to monitor version of clients - see https://github.com/influxdata/influxdb-client-js/issues/152
cc https://github.com/influxdata/influxdb-client-js/issues/160
> fix(CORS): added User-Agent to allowed CORS headers

- authorizer/auth.go
- authorizer/auth_test.go
- authorizer/authorize_find.go
This PR changes the auth process for authorizations.
__Before__: authorized for a an authorization => authorized to read/write the user in the auth  
__Now__: authorized for an auth => authorized to read/write the auth
Example:
Given auth:
```
&influxdb.Authorization {
ID: 1,
UserID: 10,
OrgID: 100,
}
```
__Before__: example permission
```
{'action': 'write', 'resource': {'id': '10', 'type': 'users'}}
```
__Now__: example permission
```
{'action': 'write', 'resource': {'id': '1', 'orgid': '100' 'type': 'authorizations'}}
```
__UPDATE__:
Now updated to 
```
authorized for an auth => authorized to read/write the auth and the user in the auth
```
This is more conservative and adheres better to the previous implementation 👍 
The permissions now are twofold (auth + user in auth):
``` …
```
> fix(authorizer): fix auth for authorizations

- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/query_test.go
- http/document_test.go
- query/control/controller.go
- query/control/memory.go
Testing memory limits from the launcher perspective.
Testing if memory gets properly deallocated using metrics.
This PR also adds setting memory limits for OSS via command  line
> test(launcher): e2e test memory limits

- tsdb/engine/tsm1/compact.gen.go
- tsdb/engine/tsm1/compact.gen.go.tmpl
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/digest.go
- tsdb/engine/tsm1/encoding.go
- tsdb/engine/tsm1/encoding_test.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/reader_test.go
fixes #17440
While encoding or decoding corrupt data, the current behaviour is to `panic`.
This commit replaces the `panic` with `error` to be propagated up to the calling `iterator`.
To avoid overwriting other `error`, iterators now wraps a `TSMErrors` which contains ALL the encountered errors. TSMErrors itself implements `Error()`, the returned string contains all the error msgs, separated by `,` delimiter.
> fix(tsdb): Replace panic with error while de/encoding corrupt data

- kv/index.go
- kv/index_test.go
- testing/index.go
This updates the `index.Walk(fn)` function to use the new `bucket.GetBatch(keys...)` lookup for the keys found in the index.
This reduces index lookups from an N+1 access pattern to just 2 bucket operations per lookup.
> fix(kv): update index to use new bucket.GetBatch

- jsonweb/token.go
- task/backend/executor/executor.go
Adds a user ID to the JWT `Token` auth implementation. This implementation is still permission-based; this change just keeps the identity around on the token for reference.
> refactor(tasks): auth user id

- tsdb/tsm1/cache.go
- tsdb/tsm1/cache_entry.go
- tsdb/tsm1/encoding.go
- tsdb/tsm1/engine.go
The root cause is that the `Unsigned` data type has no representation in the `valueType` function in the cache and falls back to the default case of 0.
0 is also a sentinel value in the `entry#add` function that will result in skipping the value type check.
It therefore is possible that unsigned values followed by some other data type is stored in the cache.
It is suspected that the write may be rejected before reaching the cache, and therefore may not occur in practice. Specifically, the series file stores the data types on a per-series basis and would
reject the write.
This commit turns the value types into explicit constants and ensures all existing block types are represented. In addition, it adds a mapping function to convert these to a known Block type,
which will be used by the …
> fix: Invariant violated: mixed block types for a single series

- models/points.go
- models/points_test.go
- storage/engine_measurement_schema.go
- tsdb/cursors/schema.go
- tsdb/tsm1/engine_measurement_schema.go
- tsdb/tsm1/engine_measurement_schema_test.go
- tsdb/tsm1/engine_schema.go
This PR provides implementations of the `MeasurementNames`, `MeasurementTagKeys` and `MeasurementTagValues` schema APIs.
These schema APIs require a measurement, permitting additional optimization to reduce the search space against the TSM index. Specifically, the TSM search key prefix is extended from `org+bucket` to `org+bucket,\x00=<measurement>`.
In addition the `models` package provides a new API, `ParseMeasurement` to efficiently extract the value of the `models.MeasurementTagKey` tag key (`\x00`), with no allocations if the value does not require escaping.
Closes #17446
> feat(storage): Measurement(Names|TagKeys|TagValues) schema APIs

- ui/src/dashboards/actions/thunks.ts
- ui/src/variables/actions/thunks.ts
- ui/src/variables/utils/ValueFetcher.ts
- ui/src/variables/utils/hydrateVars.ts
Closes #17576
Closes #17209
We were waiting for all query variables to return their results before rendering the dashboard. Most users should not have seen this, but the tools cluster was real slow. Some copy pasta later to reorder the execution to not include hydration on a Promise.all, and we are back in business.
While poking around the hydration code, i also found where query variable requests were cached! overriding that fixed the bucket problem and means that navigating away, and then back to, a dashboard refreshes all your variables
> fix: dont wait for query hydration

- kv/service.go
- kv/session.go
- kv/task.go
- task/servicetest/servicetest.go
Add ability to configure disabling max permissions using auth lookup via a `useAuthorizationsForMaxPermissions` filter function.
> feat(kv): add ability to configure a max permissions using auth filter function

- CHANGELOG.md
- ui/src/shared/components/tables/TableCell.tsx
Closes #16924
URL parsing for table results with 1 column would apply funky styling to the results.
I genuinely can't say why the previous implementation was failing. The regex statement was able to parse a URL correctly when multiple columns were present, but the second only 1 column was present, the regex statement failed to parse the URL correctly. After investigating it for a while, I genuinely couldn't a valid reason why it would be failing to parse the values correctly. As such, I switched the initial validation to use a native JS method to validate whether the value is a URL based on the regex parsing that was previously being used to validate the string.
> fix(ui): fixed single column links bug

- CHANGELOG.md
- ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
- ui/src/timeMachine/utils/insertFunction.test.ts
- ui/src/timeMachine/utils/insertFunction.ts
Closes #17282
This bug is a regression that stemmed from our earlier transition from codemirror to monaco. In particular, the issue was that some of the logic that had previously been used to determine the insert line of a function was not integrated into the monaco functionality.
Integrated a few logical steps to calculate where a function should be placed when selecting an aggregate function.
> fix(regression): function inserts now happen on new line

- ui/src/dashboards/actions/thunks.ts
- ui/src/external/monaco.flux.server.ts
- ui/src/timeMachine/actions/queries.ts
- ui/src/types/variables.ts
- ui/src/variables/actions/thunks.ts
- ui/src/variables/selectors/index.tsx
- ui/src/variables/utils/buildVarsOption.ts
- ui/src/variables/utils/hydrateVars.ts
Closes #17606
variables now hold their own values, and we gotta respect that, you know?
> fix: hierarchy of variables is back

- services/httpd/handler.go
- services/httpd/handler_test.go
Closes #17248
Make 1.x support the 2.0 health API.
> feat(handler): Add 2.0 compatible health endpoint

- ui/src/Logout.tsx
- ui/src/Signin.tsx
- ui/src/me/components/LogoutButton.tsx
- ui/src/pageLayout/components/UserWidget.tsx
- ui/src/shared/utils/featureFlag.ts
- ui/src/types/auth.ts
The purpose of this PR is to update the way we are feature flagging the social sign-on feature. After meeting with Mark, Luke and Pat on Friday afternoon, it was decided that the best way to make sure that a rollout of the social sign-on feature happens smoothly would be to ensure that the feature flag we are using for IDPE and the UI are the same. Since we already have a feature flag in place to set specific config values for IDPE, this PR (in conjunction with https://github.com/influxdata/idpe/pull/6653) aims to update the way we are feature flagging the UI based on the feature flag that is being used in IDPE. 
Practically speaking, this means that we will be using a value that is returned from the API to determine whether to toggle the feature rather than using the built-in feature …
> chore(ui): refactor logout to utilize new featureFlagging from IDPE

- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
- storage/reads/array_cursor_test.go
Filter cursors buffer points in between calls to Next() if the number of read points exceeds 1000. Previously, this buffer was being cleared out before being iterated over which caused queries to return a resultset which had a number of rows divisible by 1000.
This change moves the clearing of the buffer until after the points have been read. This change affects any queries which read more than 1000 points from a single series & have a filter that can be successfully applied to at least one of those points.
> fix(storage): Fix query cursor read that caused cursor truncation.

- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
The replace directive in the promqltests pointed to the wrong module
path. This is now fixed.
> chore: fix the promqltests go module file

- storage/reads/group_resultset.go
- storage/reads/group_resultset_test.go
Currently, the comparison function for sorting in `group_resultset.go` `groupBySort` just sorts sortKeys as a contiguous byte array, using commas to separate values.
[](url)
https://github.com/influxdata/influxdb/blob/636a27e77f00f0faeff186c8b6b005d79da7c424/storage/reads/group_resultset.go#L217-L265
This causes an issue whenever there is an ascii character in the byte array that would be sorted before a `,` character.
For example:
`a*,b` would sort before `a,b` because `*` is less than `,`.
This PR resolves that issue.
> fix(storage/reads): update sortKey sorting method to use null byte as delimiter, not comma

- storage/reads/group_resultset.go
- storage/reads/group_resultset_test.go
Currently, the comparison function for sorting in `group_resultset.go` `groupBySort` just sorts sortKeys as a contiguous byte array, using commas to separate values.
[](url)
https://github.com/influxdata/influxdb/blob/636a27e77f00f0faeff186c8b6b005d79da7c424/storage/reads/group_resultset.go#L217-L265
This causes an issue whenever there is an ascii character in the byte array that would be sorted before a `,` character.
For example:
`a*,b` would sort before `a,b` because `*` is less than `,`.
This PR resolves that issue on v.1.8.
> fix(storage/reads): update sortKey sorting method to use null byte as delimiter, not comma 

- ui/src/variables/selectors/index.tsx
while we figure out how to more proactively prevent the user from reaching an error state from unset variables (influxdata/idpe#6675), we can hide the errors from the backend by filling unselected query variables as an empty string.
> feat: swallow unselected variable error

- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
In CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS),
- the server stops processing when satisfying pre-flight requests
- Access-Control-Allow-Origin header is included in CORS-allowed responses
This fix is required for any browser client (including influxdb-client-js) to work fine against influxdb OSS. 
cc influxdata/influxdb-client-js#164
> fix(CORS): stop processing in pre-flight CORS requests

- go.mod
- go.sum
- kit/tracing/tracing.go
- kit/tracing/tracing_test.go
Since moving to chi in some places. Traces have lost their `route` tags. This makes searching for certain requests impossible.
This adds support for hijacking the route of the chi context and annotating the span.
It also bumps chi version because there was a bug fix for extracting the router context.
> fix(tracing): add support for tracing route annotation when using chi

- ui/src/shared/components/CloudUpgradeButton.tsx
Closes 6679
apparently, [adding `_target`](https://github.com/ReactTraining/react-router/issues/3109#issuecomment-189782650) to `Link`s skips state transitions and sends the request directly to the server.
> fix: force a server redirect to /upgrade

- CHANGELOG.md
- services/httpd/handler.go
- services/httpd/handler_test.go
Closes # https://github.com/influxdata/influxdb/issues/17623 and https://github.com/influxdata/influxdb/issues/17622
This change updates the v1 and v2 `/write` endpoints to verify values passed in the `precision` parameter. Invalid values will now return a `400 bad request` to the client.
> fix: verify precision parameter in write requests

- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/promql/query_test.go
- query/promql/types.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- query/stdlib/influxdata/influxdb/to.go
This updates the semantic graph usage to accomodate the change to the
semantic graph that removed the ambiguity of the body so now it is
always a block instead of being a block or an expression.
> refactor(query): update semantic graph usage for function expression refactor

- ui/src/shared/components/CloudUpgradeNavBanner.tsx
Closes # idpe 6679
Fixes the Upgrade Now links on the sidebar to do hard server redirects
> fix: sidebar upgrade now should now redirect properly

- ui/src/alerting/utils/history.ts
- ui/src/alerting/utils/statusEvents.ts
Closes #17516
It looks like... if any statuses have been written to the monitoring bucket with no `_check_id` field in the past 60days, they are picked up by the history query, and the rename flux function errors.
Fixed by adding a filter to filter out statuses where a `_check_id` field does not exist.
> fix(alerting): ensure that status fields exist before renaming them

- ui/src/timeMachine/reducers/index.test.ts
- ui/src/timeMachine/utils/queryBuilder.test.ts
- ui/src/timeMachine/utils/queryBuilder.ts
Closes #17529
instead of using the dot notation, lets just wrap the fields so that we get some escaping for free
> fix: escaping tags in flux queries

- http/authentication_middleware.go
This commit adds `user_id` as a tag for traces. It helps to lookup and
filter traces we need by userID.
OrgID is harder to get right, so I will open an issue, but it will be
nice to have it in as well.
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
Co-authored-by: George MacRorie <gmacrorie@influxdata.com>
> feat(tracing): add userID to lookup traces

- kit/tracing/tracing.go
- kit/tracing/tracing_test.go
It is solid to use retrieve the method directly from the request.
Co-authored-by: George MacRorie <gmacrorie@influxdata.com>
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
> fix(tracing): set method to trace

- ui/src/cells/actions/thunks.ts
- ui/src/client/index.ts
- ui/src/dashboards/actions/thunks.ts
- ui/src/dataExplorer/components/SaveAsCellForm.tsx
- ui/src/dataLoaders/actions/dataLoaders.ts
- ui/src/notifications/endpoints/actions/thunks.ts
- ui/src/shared/copy/notifications.ts
Closes https://github.com/influxdata/quartz/issues/2373
Closes https://github.com/influxdata/quartz/issues/2370
Closes https://github.com/influxdata/quartz/issues/2375
I understand that string comparison in 992f13a is a bit weak.  Should that error message change so would this guard clause.  However, this string is unlikely to change in the near future.  It's certainly better than logging the user out on _all_ 403s.  Good enough for government.
> fix: read only errors

- cmd/influx/pkg.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/http_remote_service.go
- pkger/models.go
- pkger/service.go
- pkger/service_test.go
> feat(pkger): update notification rule with unique constraints

- CHANGELOG.md
- http/query.go
- http/query_test.go
- http/swagger.yml
We are seeing a mismatch between the expected `now()` time of a Task run and what is actually reported at the time the task is executed. Upon further investigation we found that proxied query requests (via HTTP) aren't using the `Now` time provided by the Task Executor.
This teaches the HTTP layer to use the `Now` time provided if it is presented. Otherwise, it falls back to calculating a time with the epoch.
> fix(query): Respect the now-time of the compiled query if it's provided

- cmd/influx/pkg.go
- pkger/http_server_test.go
- pkger/models.go
- pkger/models_test.go
- pkger/service_test.go
1st commit extends tasks. 2nd commit refactors things a bit to consolidate Diff resource identities around a type that includes the behavior if it is new or not.
references: #17434
> feat(pkger): update tasks with unique constraints

- CHANGELOG.md
- ui/src/shared/components/inlineLabels/InlineLabelPopover.tsx
- ui/src/shared/components/inlineLabels/InlineLabels.scss
- ui/src/shared/components/inlineLabels/InlineLabelsCreateLabelButton.tsx
- ui/src/shared/components/inlineLabels/InlineLabelsEditor.scss
- ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx
- ui/src/shared/components/inlineLabels/InlineLabelsList.tsx
Closes #16650 
Closes #17261 
- Fix appearance of `+` button
- Labels popover always aligned to `+` button
- Make labels popover is slightly wider
- Prevent labels popover from uncontrollably expanding
- Add a `maxLength` to inline create label input to prevent text wrapping
- Remove unused styles
> refactor(ui): polish labels interactions

- CHANGELOG.md
- ui/src/me/components/DashboardsList.tsx
- ui/src/me/components/Docs.tsx
- ui/src/me/components/Resources.tsx
- ui/src/me/components/Support.tsx
- ui/src/me/containers/MePage.scss
Closes #17545 
- Make dashboards panel scrollable after a certain height (400px)
- Make long dashboard names wrap
- Sort dashboards by modified date
- Add filter input
- Increase size of dashboard names and handy tutorials
> feat(ui): sort getting started dashboards by modified

- CHANGELOG.md
- ui/package.json
- ui/yarn.lock
Closes #17585 
Separate the generation of vertical and horizontal ticks to allow different spacing. For each direction, ticks can be time ticks or value ticks.
x: time, y: value
y: time, x: value
> fix(ui): update giraffe to fix spacing between ticks

- task/backend/executor/executor.go
Introduces `WithMaxWorkers` option for `Executor` to control the number of workers allowed.
> feat(task): Add worker count option to Executor

- ui/package.json
- ui/src/authorizations/apis/index.ts
- ui/src/cells/actions/thunks.ts
- ui/src/dashboards/actions/thunks.ts
Closes #17505
while the dashboard was getting created, it wasn't being added to the local resources. the cell would then error when it tried to access the dashboard, as it didn't exist until a hard refresh
> fix: load dashboard before accessing

- tsdb/cursors/arrayvalues.go
- tsdb/cursors/schema.go
- tsdb/tsm1/cache.go
- tsdb/tsm1/cache_entry.go
- tsdb/tsm1/encoding.go
- tsdb/tsm1/engine.go
- tsdb/tsm1/engine_measurement_schema.go
- tsdb/tsm1/engine_measurement_schema_test.go
- tsdb/tsm1/engine_schema.go
- tsdb/tsm1/file_store.go
- tsdb/tsm1/reader.go
- tsdb/tsm1/reader_range_iterator.go
- tsdb/tsm1/reader_range_iterator_test.go
- tsdb/tsm1/reader_range_maxtime_iterator.go
- tsdb/tsm1/reader_range_maxtime_iterator_test.go
The primary purpose of this PR is to provide an implementation of the `MeasurementFields` API. However, it also addresses a data race for the existing `TagKeys` and `TagValues` APIs.
The `TagKeys` and `TagValues` APIs use the `Cache#ApplyEntryFn`. The `ApplyEntryFn` API expects a callback function, which passes a cache `entry` as the only argument. Accessing the `values` field of the `entry` struct is a data race, as it may be mutated by other goroutines performing writes, snapshots, etc. See below for the fix.
This PR includes a commit which add a single API to the `Cache` data structure to address a data race with the existing `TagKeys` and `TagValues` APIs.
Specifically, `Cache` and `entry` provide `AppendTimestamps`, which returns a slice of the current timestamps for the given key or …
> feat(tsm1): Implementation of MeasurementFields schema API

- ui/src/shared/components/FluxMonacoEditor.scss
Closes https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/5962
Allow the cursor inside the Script Editor for Safari.
> fix(ui): allow mouse cursor inside Script Editor for Safari

- ui/src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx
This PR is a minor UI tweak to address a warning that was displaying when users were creating a telegraf config for the first time. The original intent of the warning was to align token creation and retrievability to conventions that exist in other platforms (that tokens are unique and cannot be retrieved after creation). This PR removes that warning since:
- Users can still access their tokens in the `tokens` tab
- Tokens can regenerate tokens if they lose their token
> fix(TelegrafInstructions): Updated the TelegrafInstructions to remove the warning to tell users to keep the token

- ui/src/cells/actions/thunks.ts
- ui/src/dashboards/utils/cellGetters.ts
Closes #17630
- Assign cloned cells the same `x`, and `y` as their target cell
- This results in the cloned cell getting created right below the target cell
- react grid layout handles this out of the box
- Append `(Clone)` to the end of a new view name if it was created via cloning
Initially I wrote an e2e test for cloning that asserts the cloned cell is placed next to its target. I spent a non-trivial amount of time setting up the test itself before making the assertion and it started to feel like overkill. I took a step back and concluded there is no point in testing the behavior that comes out of the box from a library.
> fix(ui): make cell cloning more predictable

- CHANGELOG.md
- etc/config.sample.toml
- pkg/tlsconfig/tls_config.go
TLS 1.3 is currently supported with the default configuration. However, the `[tls]` configuration block does yet support TLS 1.3 as an option.
This PR adds TLS 1.3 as an option for `min-version` and `max-version`. The ciphers list was also updated to the [current list of Go ciphers](https://golang.org/pkg/crypto/tls/#pkg-constants). The sample configuration file is also updated to the latest ciphers and `max-version` of 1.3.
> fix(tls): Enable configuration of TLS 1.3

- pkger/clone_resource.go
- pkger/models.go
- pkger/parser_test.go
- pkger/service_test.go
closes: #17708
`influx pkg export --dashboards $ID | influx pkg` results in:
> fix(pkger): fixup field misassignment in table view export

- ui/cypress/e2e/orgs.test.ts
- ui/src/index.tsx
Closes idpe 6730
Adds the component for renaming orgs to the correct place in the routing hierarchy
> fix(ui): add component to route hierarchy to handle org renaming

- ui/src/shared/utils/fromFlux.test.ts
- ui/src/shared/utils/fromFlux.ts
we have to make some weird jumps through spaghetti hoops to get the csv routed from an api response, to timemachine and giraffe for parsing, then back out to display meta data that then goes back into giraffe to choose how to display it.
this can get fixed by just moving the parser out of giraffe
i'm also hoping to get a couple of perf points by using array pointers to build the results table and not cloning of the results for parsing.
existing tests work, but the interface is a little different and readability has been sacrificed for reducing memory footprint where possible
possibly a prereq for #16474
> feat: moved parser

- CHANGELOG.md
- ui/src/dashboards/components/NoteEditorPreview.test.tsx
- ui/src/dashboards/components/NoteEditorPreview.tsx
- ui/src/shared/components/EmptyQueryView.tsx
- ui/src/shared/components/cells/Cell.tsx
- ui/src/shared/components/cells/CellHeaderNote.tsx
- ui/src/shared/components/cells/CellHeaderNoteTooltip.tsx
- ui/src/shared/components/views/MarkdownRenderer.test.tsx
- ui/src/shared/components/views/MarkdownRenderer.tsx
- ui/src/shared/components/views/ScrollableMarkdown.tsx
Closes idpe 5288
* Creates a cloud-aware markdown renderer that behaves as it always has on OSS, but blocks image loading on cloud.
* Refactored existing `Markdown` component to use the new `MarkdownRender` and to be renamed `ScrollableMarkdown` (it's wrapped in a `DapperScrollbar`) to avoid future confusion.
* Made all other instances of markdown rendering use the new cloud aware renderer
**Cloud behavior:**
* In editor window, show warning: `We don't support images in markdown for security purposes`
* In note, show literal markdown string
**OSS Behavior:**
* Render the image normally
1. In an OSS Context:
1. Go to a dashboard
1. Click add note
1. In the text editor add a markdown image `![](url.to.image/image.jpg)`
1. it should render in the preview
1. Click save
1. It should Shown …
> feat(cloud): markdown: do not parse or render images in cloud envs

- ui/src/buckets/components/DemoDataBucketCard.tsx
Was passing the bucket.id instead of the entire bucket value to the removeBucket function.
> feat(demodata): Pass bucket to removeBucket function

- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/models.go
- pkger/models_test.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_models.go
- pkger/service_test.go
- pkger/service_tracing.go
- tenant/service_org.go
this PR separates the parser data from teh stateful data. This is important for a number of reasons:
1. separation of concerns 
2. clean out the crufty state kludge, make it possible to generate the entire parser from a spec
3. make it clearer who owns what with the added bonus of separating the like parts into their own files
4. compiler can help identify issues with state beyond what it had been able too
last bit, the PR is big, but it is moving around 100s of LOCs from one file to another, so this is much more bloated than it otherwise would have been. The separation helps distinguish the separation. That is why it is included here.
references: #17434
> chore(pkger): refactor pkger data model to separate parsed and stateful data

- storage/engine_measurement_schema.go
- storage/engine_schema.go
- tsdb/tsm1/engine_measurement_schema.go
- tsdb/tsm1/engine_schema.go
Completes the work for measurement based schema APIs by making the `MeasurementFields` API public on the `storage.Engine` type.
Additionally, this PR corrects the time intervals for the documentation of the schema APIs.
> feat(storage): Provide public MeasurementFields API

- http/write_handler.go
_http.NewRequestWithContext_ (available since golang 1.13) ensures that the supplied context also controls the entire lifetime of a request and its response. Before this PR, the supplied context was not used at all.
> fix(http/write_handler): propagate context to http request

- query/executor.go
- services/httpd/handler.go
AuthorizeUnrestricted() method and if so, call that to provide the result of AuthorizerIsOpen().
Otherwise we check if the supplied Authorizer is nil.
This preserves the fast-path for checking tag-level (and other) tsdb operations.
This also simplifies how we perform authorization by handling these cases in only one place.
There is no associated bug.
> refactor(http): simplify authorizer

- CHANGELOG.md
- kv/session.go
- testing/session.go
Closes https://github.com/influxdata/influxdb/issues/17750
This change ensures the current expiration time on a session is respected and retained until a new expiration time is presented which extends the life of the session.
Until this change, a session could be shortened via `RenewSession`.
This was happening frequently within the `http.AuthenticationMiddleware`. Rendering all sessions around 5 minutes long.
> fix(kv): don't set session expiration time to earlier than existing expiration on renew session

- CHANGELOG.md
- ui/src/shared/constants/graphColorPalettes.ts
Closes #17546
- Add `Solid Red`, `Solid Blue`, `Solid Yellow`, `Solid Green`, and `Solid Purple` as color schemes
> feat(ui): add single-color schemes for visualizations

- CHANGELOG.md
- ui/src/shared/components/EmptyGraphError.scss
- ui/src/shared/components/EmptyGraphError.tsx
- ui/src/shared/components/RefreshingView.tsx
- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/components/cells/Cell.scss
- ui/src/shared/utils/checkQueryResult.ts
Closes #17594 
Add error messaging for cells in the Dashboard View.
Example: when one cell has error
Example: when all cells have error
> fix(ui): add error messaging for cells in dashdboard view

- ui/src/timeMachine/components/TimeMachineFluxEditor.scss
this allows the user to use the context menu of the flux editor at the expense of having rounded borders on the editor.
> fix: removing overflow

- http/document_service_test.go
- kv/label.go
- label.go
Closes #17092
This PR adds a check for existing labels on a Document before adding a Label Mapping, to prevent duplicate Label Mappings from being created for a given Document.
> fix(documents): prevent adding duplicate labels to documents

- ui/webpack.dev.ts
this PR allows dev mode to work properly when running the frontend behind an nginx proxy with a prefix. Previously, only production builds could be run this way. Testing was done in monitor-ci when moving the application between `https://192.168.3.136:8448/influx/` and `https://192.168.3.136:8448/` by changing the environment variable `CHRONOGRAF_BASE_PATH`. Hot reloading, static resources, and api proxies all seem to work fine now.
> fix: allow dev mode with prefixes

- ui/src/Signin.tsx
- ui/src/onboarding/containers/LoginPageContents.tsx
- ui/src/types/auth.ts
Previously we were using the current window location href as a means to redirect the user after performing a checkSession on their Auth0 session. However, if the user was making the request from an un-whitelisted origin, the request would fail, thereby preventing the single sign-on flow.
Reverted the Signin page redirect logic so that the redirects are happening from the API rather than the UI. This simplifies our authentication flow by reducing the complexity of session validation while maintaining our single sign-on flow
> feat(SigninPage): Updated the Signin checkSession to correspond to API changes

- CONTRIBUTING.md
- README.md
Since moving to modules the README.md and CONTRIBUTING.md docs have gotten out of sync.
This PR updates the docs to mention go 1.13 and modules and removes older versions of go and removes mentions of `dep`.
> fix(docs): Update docs to reflect tooling changes

- cmd/influx/pkg.go
- cmd/influxd/launcher/pkger_test.go
- dashboard.go
- http/swagger.yml
- kv/dashboard.go
- pkger/service.go
- pkger/service_models.go
- testing/dashboards.go
- ui/src/dashboards/actions/thunks.ts
references: #17434 
note: the first commit here updates the dashboard update to allow for updating cells (as a collection) as part of the dashboard update.
>  feat(pkger): add stateful management for dashboards

- go.mod
- go.sum
- query/querytest/compiler.go
- query/stdlib/influxdata/influxdb/from_test.go
- query/stdlib/influxdata/influxdb/rules.go
The `Rewrite` method for planner rules was updated to take in the
context used when running the query.
Related to influxdata/flux#2755.
> feat(query): update planner rules to accept a context

- cmd/influx/pkg.go
- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/service.go
notes on this commit. This commit was grueling ;-(. The task API is not a friendly
API to consume. There are a lot of non obvious things going on and almost every
one of them tripped me up. Things of note:
* the http.TaskService does not satisfy the influxdb.TaskService,
making it impossible to use as a dependency if expecting a influxdb.TasksService
* the APIs for create and update do not share common types. For example:
creating a task takes every field as a string, but in the update it is
taken as a options.Duration type. A step further and you'll notice that
create does not need an option to be provided, but the update does. Its
jarring trying to understand the indirection here. I struggled mightily
trying to make sense of it all with the indirection and differing types.
Made for a …
> feat(pkger): add stateful management for tasks

- CHANGELOG.md
- cmd/influx/main.go
- cmd/influx/main_test.go
- cmd/influx/setup.go
> fix(influx): make CLI respect env vars and flags in addition to the configs

- .circleci/config.yml
It was a request from boonito QA to start running nightly builds 2 hours earlier, instead of 7am UTC to start running nightly builds at 5am UTC (10pm PDT) to give them time to debug test failures.
> chore(build): start running nightly builds 2hour earlier

- ui/src/dashboards/actions/thunks.ts
- ui/src/dashboards/utils/cellGetters.ts
Closes #17787
when fetching a list of dashboards, we weren't filling the cells / views that also come back from the result of this api call.
> fix: filling views and cells when we grab dashboards

- mock/store_reader.go
- query/stdlib/influxdata/influxdb/operators.go
- query/stdlib/influxdata/influxdb/source.go
- query/stdlib/influxdata/influxdb/source_internal_test.go
- query/stdlib/influxdata/influxdb/source_test.go
- query/stdlib/influxdata/influxdb/storage.go
The `ReadWindowAggregateSource` will invoke the `ReadWindowAggregate`
method on the `influxdb.Reader` and return the table. It is implemented
using the same common methods that are used for the other sources.
Fixes #17785.
> feat(query): implement the ReadWindowAggregateSource

- tenant/storage_org.go
- tenant/storage_user.go
- testing/organization_service.go
- testing/user_service.go
This will allow us to match the existing behavior that allows for update requests to go through with the same name.
> fix(tenant): Allow tenant to update user and org with same name

- query/stdlib/influxdata/influxdb/storage.go
- storage/reads/store.go
This modifies the read window aggregate interfaces to future-proof it
if and when we add additional capabilities to the method. Previously,
the interface was all or nothing. If we modified the RPC call itself, we
would have to make a new interface to denote the change to the Go code.
This changes the interface so now a `WindowAggregateCapability` exists.
This way, we can modify the struct to include things like:
```go
type WindowAggregateCapability struct {
WindowPeriodCapability bool
MeanAggregateCapability bool
}
```
This way we can learn if the RPC call itself supports some specific
option. If the first iteration doesn't support a mean aggregate or the
mean aggregate is only supported by single server implementations, the
window aggregate can tell the caller that it won't be able to …
> refactor(query): return detailed capabilities for the read window aggregate interfaces

- ui/src/shared/constants/fluxFunctions.ts
- Added the `experimental.alignTime` functions
- Added the `epsilon` parameter to `testing.diff`
- Added missing `createEmpty` parameter to `window`
---
> chore(flux): add flux 0.66 functions

- ui/src/mockState.tsx
- ui/src/normalizers/localStorage/localStorage.ts
- ui/src/shared/utils/featureFlag.ts
- ui/src/types/localStorage.ts
This PR persists feature flag overrides across refreshes on the frontend. Also makes toggle return the value that the flag was set to (@corriganjohn)
> fix: persist local feature flag overrides

- ui/src/shared/components/cells/Cell.scss
Closes influxdata/idpe#6755
that was a weird journey, but the overflow:hidden is so that the later flex boxes are forced to remeasure themselves during dragging, and the height: 100% is to force a redraw on instantiation (or else it just shows up as a black box)
> fix: make single stats work in catalina

- ui/src/onboarding/containers/LoginPageContents.tsx
This feature is set to release very soon. In the event of any failures with the feature, we want to reduce the scope of the problem in order to get a more focused understanding of what is going wrong, and where we should focus our efforts. In order to narrow the scope of this feature, we are commenting out the Github option for social sign-ups.
By deleting the Github-related UI, we are limiting social sign-up to only allow for Google users. Once this feature has proven successful, we will reintroduce the code to allow Github integration
> feat(github): removing the Github social sign-up option until further notice

- ui/package.json
- ui/src/dashboards/actions/ranges.ts
- ui/src/notifications/rules/components/RuleOverlay.reducer.tsx
- ui/src/shared/components/EventMarker.tsx
- ui/src/types/alerting.ts
- ui/src/types/labels.ts
- ui/src/types/variables.ts
- ui/yarn.lock
TypeScript 3.8 introduces a bunch of [cool features](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)
Specifically, I'm super excited about [Optional Chaning](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) which would allow us to replace / stop using `lodash/get` and the foo && foo.bar && foo.baz patterns!
All we had to do to upgrade was fix a couple of conflicting import / exports
> chore: upgrade ts to 3.8.3

- ui/src/external/monaco.flux.hotkeys.ts
- ui/src/timeMachine/components/EditorShortcutsTooltip.scss
- ui/src/timeMachine/components/EditorShortcutsTooltip.tsx
- ui/src/timeMachine/components/SubmitQueryButton.tsx
Closes #17820
Closes #17821
there was some weird code in there about "only show the loading icon if it was clicked by a person", and i threw that out. also added some verbage around "use ctrl OR cmd" to capture the different environments. This turns off ctrl on macs in favor of cmd. @russorat weigh in if we still want to force the ctrl key on macs in addition to cmd.
> fix: monaco polish

- ui/src/dashboards/components/NoteEditor.tsx
- ui/src/dashboards/reducers/notes.ts
Closes #17412
just checks to see if it's a markdown view (denoting no query) or a new cell (denoting it wont be added to a query)
> fix: remove toggle on note cell

- CHANGELOG.md
- kv/user.go
- testing/user_service.go
`UpdateUser` isn't cleaning up the `userindexv1/<USER_NAME>` index when the name of a user is changed. This change ensures that this key is removed properly.
This work will be superseded by the new tenant service.
> fix(kv): Ensure UpdateUser cleans up the index when updating names

- http/handler.go
This changes the following paths (prefixes) to stop being traced:
- `/health`
- `/ready`
- `/debug`
- `/metrics`
These endpoints are often hit frequently and finish quickly. If they don't finish quickly, metrics suffice to identify them as a problem. Traces offer little insight for these endpoints; especially since they don't tend to cross process boundaries.
Tracing systems often sample aggressively and these kinds of endpoints end up getting picked a lot. Removing them makes room for more traces which relate to user behaviour.
> chore(http): stop tracing system related api paths

- http/errors.go
- http/errors_test.go
- kit/transport/http/api.go
- kit/transport/http/error_handler.go
This is just a little proposal PR to restructure some of the `http.CheckError` behaviour to get a little more context in some cases.
We recently experience what appeared to be a response between tasks and gateway with a non 2XX or 3XX with no content type and an empty body. This is turning up in a task run log as an `Unexpected end of JSON input: ""` error.
While I am unsure if we can get much more context, the status code in the situation is getting dropped on the floor. This change ensures that we at least attempt to convert it into one of our influxdb error codes.
It also leverages both `message` and `error` fields in the event of a failure to unmarshal an error as json. The `error` contains the first line of the response body and the `message` contains an explanation and the error …
> chore(errors): interpret more cases as influxdb error type in http.CheckError

- ui/src/alerting/components/AlertingIndex.tsx
just wanna get that working before going into the weekend
> fix: show buckets in alerting

- CHANGELOG.md
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_tracing.go
> feat(pkger): add the ability to remove a stack and all its associated resources

- pkg/httpc/client.go
the base address should be enough to make a request. All requests
are now valid without a path provided. This will be true as long
as the address is valid.
> chore(httpc): refactor inputs to eliminate required path

- CHANGELOG.md
- notification/check/threshold.go
- ui/cypress/e2e/checks.test.ts
- ui/src/alerting/components/builder/AlertBuilder.scss
- ui/src/alerting/components/builder/ThresholdValueInput.tsx
Closes #17729
1. Checks initialized with the value `0` would not be triggered. When a user would edit their check, the value would return blank
2. On smaller screens, the Configure A Check options would be off the screen:
Updated the threshold value to remove `omitEmpty` on thresholds since that was removing values set to zero.
As per [this helpful resource](https://www.sohamkamani.com/golang/2018-07-19-golang-omitempty/), go will remove nil values if the flag `omitEmpty` is present. 
It doesn't seem like there was any obvious reason for this to be present since a check should never be created without a value set for the threshold. The UI doesn't allow for this condition, and the API shouldn't allow for this condition. 
I added an e2e test to ensure that this bug doesn't pop its head …
> fix(zero_value_checks): checks can now have a value set to 0

- mock/reader.go
- query/storage.go
- storage/flux/reader.go
- storage/reads/store.go
- storage/readservice/store.go
This PR is a follow-up for #17885
We currently have two `WindowAggregateCapability` struct definitions. One is in [query/stdlib/influxdata/influxdb/storage.go](https://github.com/influxdata/influxdb/blob/master/query/stdlib/influxdata/influxdb/storage.go#L154) used by the `WindowAggregateReader` implementations, the other one is in [influxdb/storage/reads/store.go](https://github.com/influxdata/influxdb/blob/master/storage/reads/store.go#L87) used by the `WindowAggregateStore` implementations.
The plan is to add more supported feature flags to those `WindowAggregateCapability` structs in the future as we move forward to add more storage API capabilities. For example:
```go
type WindowAggregateCapability struct {
SupportMutipleAggregates bool
SupportSpreadFunction bool
...
}
```
Then in …
> refactor: unify WindowAggregateCapability

- storage/flux/reader.go
`handleRead` consumes an aggregate window `ResultSet` and translates it to a flux table stream.
Note this relies on a `WindowAggregateStore` producing a `ResultSet` type upon reading. @rockstar let me know if this is not a valid assumption.
> feat(storage): convert ResultSet to table stream for aggregate window

- ui/src/shared/components/SearchableDropdown.tsx
- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/timeMachine/components/TagSelector.tsx
- ui/src/timeMachine/reducers/index.test.ts
- ui/src/timeMachine/reducers/index.ts
Closes #17816
After selecting a list of buckets we would go fetch some tagKeys.  Then, we would go fetch some tagValues for said tagKeys.  If no tagValues returned we would set tagValues to `[]` and tagValues `RemoteDataState` to `Done`. 
With me so far? Great.  
So, the problem occurs after picking a new bucket or tagKey that have tagValues _after_ picking a bucket or tagKey that don't have values .  The state of `Done` and `[]` still existed for tagValues when fetching the new `tagKeys` which caught [this guard clause](https://github.com/influxdata/influxdb/blob/master/ui/src/timeMachine/components/TagSelector.tsx#L209) rendering a confusing message to the user.  
Refresh the tagValues `RemoteDataState` to `NotStarted` when fetching new tagKeys =).
This includes a test.  We should write …
> fix(queryBuilder): display loading text

- flags.yml
- go.mod
- go.sum
- kit/feature/list.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- query/storage.go
Added a (disabled and feature-flagged) planner rule that matches:
ReadRange -> window -> { min, max, mean, count, sum }
The rule requires:
* the pushDownWindowAggregate{Count,Rest} feature flags enabled
* having WindowAggregateCapability
(which StorageReader does not currently have)
* use of "_value" columns only
* window.period == window.every
* window.every.months == 0
* window.every is positive
* window.offset == 0
* standard time columns
* createEmpty is false
> feat: added PushDownWindowAggregate planner rewrite rule

- ui/src/clientLibraries/components/ClientCSharpOverlay.tsx
- ui/src/clientLibraries/components/ClientGoOverlay.tsx
- ui/src/clientLibraries/components/ClientJSOverlay.tsx
- ui/src/clientLibraries/components/ClientJavaOverlay.tsx
- ui/src/clientLibraries/components/ClientPHPOverlay.tsx
- ui/src/clientLibraries/components/ClientPythonOverlay.tsx
- ui/src/clientLibraries/components/ClientRubyOverlay.tsx
- ui/src/clientLibraries/constants/index.ts
* `Initialize the Client` always contains full range of required imports
* `Initialize the Client` contains `org`, `bucket` and `token` constant for reuse on all places
* Timestamps are always current time => user view written data in default settings of DataExplorer
> docs(clientLibs): improve client docs

- ui/src/cloud/actions/orgsettings.ts
- ui/src/cloud/apis/orgsettings.ts
- ui/src/cloud/components/OrgSettings.tsx
- ui/src/cloud/constants/index.ts
- ui/src/cloud/reducers/orgsettings.ts
- ui/src/pageLayout/containers/TreeNav.tsx
- ui/src/shared/components/CloudUpgradeButton.tsx
- ui/src/shared/components/CloudUpgradeNavBanner.tsx
- ui/src/store/configureStore.ts
- ui/src/types/cloud.ts
- ui/src/types/stores.ts
Closes idpe 5891
For Cloud Users only.
To provide the best experience for paid users, by default, we hide the "Upgrade Now" button. The button immediately reveals itself if:
- getting org settings from IDPE results in a failure
- getting org settings from IDPE is successful but a particular setting is not found
The particular setting that we are looking for is updated by Quartz and that functionality will be active soon. For paid users, a successful check on this setting means that the button continues to be hidden.
**Screenshots**
getting org settings fails: **Upgrade Now** button reveals itself
getting org settings successful but particular setting not found: **Upgrade Now** button reveals itself
getting org settings successful and particular setting found: No upgrade button (no need to …
> feat(ui): hide the "Upgrade Now" button for Cloud users when appropriate

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
> feat(pkger): handle edge cases for telegraf configs and tasks that manifest from user interaction

- ui/src/cloud/actions/demodata.ts
I was passing the error object rather than the message from the error object as a string to notifications so app would break. :(
> feat(demodata): get error message from error for notification

- ui/src/shared/selectors/flags.ts
In preparation for multi user release.  Setting `multiUser` to `true`.  DO NOT MERGE.
> chore: multiUser defaults to true

- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- http/check_service.go
- http/notification_endpoint.go
- http/notification_rule.go
- http/notification_rule_test.go
- http/proxy_handler.go
- http/task_service.go
- http/task_service_test.go
- kit/feature/http_proxy.go
- kit/feature/http_proxy_test.go
This introduces the ability to specify a feature flag driven proxy for specific HTTP handlers known to perform Flux `options` parsing. This change should be seen as a temporary measure to ensure the safe rollout of the Algo-W changes to the API. 
In `influxd`, a no-op structure (`http.NoopProxyHandler`) is used which does not do proxying. The Algo-W branch in our rollout will use this same no-op structure to force the use of in-process logic. The `feature.HTTPProxy` will be used in other contexts to direct the traffic to another endpoint.
The handlers that are targeted in this change are:
- Checks
- `POST /api/v2/checks`
- `PUT /api/v2/checks/:id`
- `PATCH /api/v2/checks/:id`
- Tasks
- `POST /api/v2/tasks`
- `PATCH /api/v2/tasks/:id`
- Notification Rules
- `POST /api/v2/notificationRules` …
> feat(http): Allow specific API handlers to be proxied for the Algo-W rollout

- services/httpd/handler.go
- services/httpd/handler_test.go
This PR fixes an issue with `serveExpvar` so that it does not generate invalid JSON. Specifically, the improvement was made to prevent key collisions when serializing `[]*monitor.Statistic` values. 
The algorithm works as such:
1. record each statistic key in a map with a count of occurrences
2. if the count > 0, amend key with the suffix `:<count>`
In practice, key collisions for `hh_processor` were observed with Enterprise:
```json
"hh:/var/lib/influxdb/hh": {"name":"hh",
"hh_processor": {"name":"hh_processor","tags":{"db"
"hh_processor": {"name":"hh_processor","tags":{"db"
"hh_processor": {"name":"hh_processor","tags":{"db"
"hh_processor": {"name":"hh_processor","tags":{"db"
"hh_database": {"name":"hh_database","tags":{"db"
```
This change will serialize these values as:
```json …
```
> fix(httpd): Fixes key collisions when serializing /debug/vars

- storage/flux/tags_cache.go
- storage/flux/tags_cache_test.go
The tags cache was not thread safe when called from multiple goroutines
at the same time. It was intended that it would be, but the locking was
done incorrectly and in too complicated a way. There was an assumption
that the LRU would only be updated from a single thread which wasn't
true at all.
The tags cache has now been updated to include some test cases that test
for race conditions and data validity. The tags cache itself has been
changed to follow a simpler algorithm.
1. Obtain a read lock.
2. Check if the cached array can be used.
3. Release the read lock.
4. If the above was unusable or did not exist, create an array for the
tag.
5. Obtain a write lock.
6. Check if the cached array should be replaced and replace if needed.
7. Move the entry to the front of the LRU.
8. Release the …
> fix(storage/flux): fix a race condition in the tags cache

- http/swagger.yml
Closes #17972 
Added the default handler for POST on /setup, as it is on other POSTs.
> fix: [Swagger] adding default handler for POST on /setup

- .circleci/config.yml
- CHANGELOG.md
- ui/src/checks/components/CheckHistory.tsx
- ui/src/dashboards/selectors/index.test.ts
- ui/src/dashboards/selectors/index.ts
- ui/src/shared/components/TimeZoneDropdown.tsx
- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/timeMachine/components/Vis.tsx
- ui/src/variables/selectors/index.test.tsx
- ui/src/variables/selectors/index.tsx
Reverts influxdata/influxdb#17992
> feat(custom-timerange-tz): timeZone dropdown is now integrated in setting custom time ranges for queries

- http/swagger.yml
Closes #17919 
Despite the swagger, where update password path defines PUT operation, current server and influx tool implementation requires POST. 
Even  PUT is more suitable, POST is also usable from the RESTfull perspective.
> fix(API docs): Changing method of set user password to POST

- http/check_service.go
- http/notification_rule.go
- http/proxy_handler.go
- http/query_handler.go
- http/task_service.go
This is an extension of the work done in #17970 to give us a foothold in proxying specific HTTP handlers to another location for safe vetting of Flux (Algo-W) parsing at the gateway layer before merging. It expands the handlers being proxied to include:
- `POST /api/v2/query`
- `POST /api/v2/query/ast`
- `POST /api/v2/query/analyze`
- `GET /api/v2/query/suggestions`
- `GET /api/v2/query/suggestions/:name`
> feat(http): Allow query handlers to be proxied for Algo-W testing.

- cmd/influxd/launcher/launcher.go
- kit/feature/override/override.go
- kit/feature/override/override_test.go
This change addresses a bug in the `override.Flagger` implementation.
When the override flagger is passed to a `Flag`, e.g. in a call to `Enabled` like this
```feature.BackendExample().Enabled(ctx, flagger)```
the `Flag`'s underlying `Base` type is [passed to `override.Flagger#Flags`](https://github.com/influxdata/influxdb/blob/95913534a0a6148f39b41138c31ab48dfad1bed2/kit/feature/flag.go#L95). This prevents the override flagger from being able to coerce the value type based on the flag type.
This PR fixes the problem by providing the `ByKey` lookup function to the `override.Flagger`, letting it look up the concrete type of any `Base` it is provided.
> fix(kit/feature): lookup typed flag if base is passed to override

- authorization/error.go
- authorization/http_server.go
- authorization/http_server_test.go
- authorization/middleware_auth.go
- authorization/mock_tenant.go
- authorization/service.go
- cmd/influxd/launcher/launcher.go
- flags.yml
- http/api_handler.go
- kit/feature/list.go
- kit/transport/http/feature_controller.go
This PR adds a feature flag for the new authorization package introduced in: https://github.com/influxdata/influxdb/pull/17874
Also included is a new interface `FeatureHandler` which takes in an Enabler (in this case a Flag) and two handlers and uses the Enabler to decide which handler to use. This allows us to switch on feature flagged code at the http level instead of the service level.
> feat: add feature flag for refactored authorization package

- CHANGELOG.md
- cmd/influx/setup.go
> fix(influx): fixup display message for onboarding with interactive and rp flag

- http/swagger.yml
[Permission.Resource](https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L6995) is an embedded object of the `Permission` type in the swagger types definition.
When using [oapi-codegen](https://github.com/deepmap/oapi-codegen) for generating types from the swagger, such type is kept embedded and instantiating such anonymous type requires a  boilerplate code. 
Promoting Resource as a top-level type makes [usage of Authorization API much easier](https://github.com/influxdata/influxdb-client-go/blob/master/client_e2e_test.go#L165).
> refactor: [Swagger] Permission.Resource made top level type

- mock/reads_resultset.go
- mock/reads_resultset_test.go
- storage/reads/resultset_lineprotocol.go
This PR includes two changes.
1. The `ResultSetToLineProtocol` test class was generating incorrect line protocol for string output, by appending `i` to the value. This PR fixes that issue.
2. Improves the `mock.NewResultSetFromSeriesGenerator` type by adding functional options. The one option added is `WithGeneratorMaxValues`, to limit the total number of values produced by the `ResultSet`.
These types are used for mocks and testing.
> fix(reads): Fix ResultSetToLineProtocol to generate correct output

- .circleci/config.yml
- CHANGELOG.md
- ui/src/checks/components/CheckHistory.tsx
- ui/src/dashboards/selectors/index.test.ts
- ui/src/dashboards/selectors/index.ts
- ui/src/mockState.tsx
- ui/src/shared/components/TimeZoneDropdown.tsx
- ui/src/timeMachine/actions/queryBuilder.ts
- ui/src/timeMachine/components/Vis.tsx
- ui/src/variables/selectors/index.test.tsx
- ui/src/variables/selectors/index.tsx
Closes #17877
The primary purpose of this PR is to ensure that whenever a user sets UTC as their timeZone and is querying a custom timeRange, their query will query data that was set at that set time in UTC (not the adjusted locale -> UTC time).
The UI for the timeZone (local or UTC) was often confusing and seemed to indicate functionality beyond displaying graphs in UTC.
Created a selector to update the timeRange whenever a query is executed with a custom timeRange and the timeZone set to UTC.
> feat(custom-tz): added the ability to set UTC as the timezone when making custom time range queries

- check.go
- kv/check_test.go
- testing/checks.go
This changes removes the URM and Organization services from being embedded in the CheckService interface. Nothing out there needs a CheckService to be a URM or and Org service. This was just a hack for tests.
> refactor: remove urm and org service from check service interface definition

- ui/src/cloud/actions/demodata.ts
- ui/src/cloud/utils/demoDataErrors.ts
- ui/src/shared/apis/query.ts
- ui/src/shared/copy/notifications.ts
- ui/src/templates/api/index.ts
- ui/src/timeMachine/actions/queries.ts
In order to feel more comfortable releasing the demodata, we'd like to be able to switch the feature off in case of errore. We also want to give users a seamless experience even if demodata is switched off after they have added dd buckets, or dashboards. 
Before this PR- toggling the demodata feature flag off would 
- remove the dd dropdown, and 
- stop displaying dd buckets a user may have subscribed to.
But dd dashboards would still remain and generate a `failed to initialize execute state: could not find bucket` error from flux. 
after the changes in this PR, toggling the demodata feature flag will also:
- show a notification to the user that the "demodata feature is temporarily unavailable" if they already had dashboards set up to query the demodata bucket, and receive a `failed to …
> feat(demodata): Place dd dashboard errors behind feature flag

- authorization/middleware_logging.go
- session/middleware_logging.go
- tenant/middleware_bucket_logging.go
- tenant/middleware_onboarding_logging.go
- tenant/middleware_org_logging.go
- tenant/middleware_user_logging.go
Closes #18053
Change logging level in tenant service from "error" to "debug" to reduce noise.
> fix: change logging level to debug to reduce noise

- http/check_service.go
I was writing tests using this client and came across this bug.
The PatchCheck now uses the `PATCH` http method.
> fix(http): call PATCH endpoint in checks service PatchCheck

- ui/src/cloud/actions/demodata.ts
- ui/src/cloud/constants/index.ts
- ui/src/dashboards/components/DashboardHeader.tsx
- ui/src/index.tsx
- ui/src/shared/utils/analytics.ts
- ui/src/timeMachine/actions/queries.ts
> feat(demodata):  Add GA events for demodata

- CHANGELOG.md
- ui/cypress/e2e/explorer.test.ts
- ui/src/shared/components/AutoDomainInput.tsx
- ui/src/shared/components/HeatmapPlot.tsx
- ui/src/shared/components/HistogramPlot.tsx
- ui/src/shared/components/ScatterPlot.tsx
- ui/src/shared/components/XYPlot.tsx
- ui/src/shared/utils/useVisDomainSettings.test.ts
- ui/src/shared/utils/useVisDomainSettings.ts
- ui/src/shared/utils/vis.test.ts
- ui/src/shared/utils/vis.ts
- ui/src/timeMachine/components/view_options/LineOptions.tsx
Closes #17793
The purpose of this PR is to allow users to set a Y-domain min/max value without requiring users to set both. In other words, a user should be able to set the Y-domain with either a MIN or a MAX, and should not be required to set both.
This feature required a removal of current restrictions on setting domain values, such as:
- no empty values
- min <= max
The ramifications of these changes were addressed by dynamically setting empty values based on the data range that is returned. If a user set their minimum value to 0, and left the maximum value blank, the upper bounds of their range would be set dynamically based on the data range. Similarly, if a user set their maximum value to 100 and left he minimum value blank, the lower bounds of their range would be set dynamically …
> feat(y_axis_domain): updated y-axis domain settings to allow min OR max values to be set.

- CHANGELOG.md
- dashboard.go
- http/swagger.yml
Closes #18033
timeFormat selections were not persisted for Graph + Single-Stat
Updated the struct and yml file to correctly return timeFormat when it is included in the patch / get
> fix(timeFormat-single-stat-graph): fixed issue where setting the timeFormat on single-state + graph wasn't persisted

- tenant/service_bucket.go
- testing/bucket_service.go
Tenant bucket look up needs route a action to storage to use indexes.
I added an error condtion into the storage code to ensure this was working
but the tests did not exercise this piece of code. Both have been remedied.
> fix: tenant findBucket action needs to properly route actions

- CHANGELOG.md
- auth.go
- authorizer/authorize.go
- authz.go
- http/delete_handler.go
- http/write_handler.go
- jsonweb/token.go
- mock/authorization.go
- session.go
This is a proposal to change the shape of the Authorizer interface.
Each of our authorizers use a slice of Permissions to evaluate whether a single supplied permission is allowed. This changes that contract to simply return the set of permissions and allow the consumer to validate them itself. The `Allowed` method still exists, though now it just exists on the new type `PermissionSet` which is the slice of Permissions.
One advantage of this will be the ability to derive from an authorizer which organizations the authorizer has access to read or write without going via a URM service.
> refactor!: replace authorizer.Allowed method with PermissionSet

- ui/src/shared/utils/useVisDomainSettings.ts
In some situations, storedDomain was being passed as undefined and was triggering a honeybadger error when trying to use the `every` method on undefined
Added a check for `undefined` in the `useVisYDomainSettings`
> fix(useVisYDomainSettings): added check for undefined values

- go.mod
- go.sum
- query/stdlib/influxdata/influxdb/to.go
The row functions were refactored to remove state from the dynamic
function. This updates the code that invoked row functions.
> fix(query/stdlib): update to function to use the refactored row functions

- ui/src/shared/constants/index.ts
This was detemined by looking at the 99th percentile of query responses.
> chore(shared/constants): increase flux response limit to 27MB

- ui/src/shared/components/FluxMonacoEditor.tsx
- ui/src/shared/selectors/flags.ts
- ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
if you turn on the flag `cursorAtEOF`, the cursor will default to the end of a prepopulated flux query when you open monaco. i found the "focus at top of all editors at initialization" behavior annoying when viewing multiple editors with prepolpulated flux comments for the notebooks project (#17966).
prop drilling through the TimeMachineFluxEditor is an artifact of the need for ongoing state decoupling in this area of the code and needed to verify this work.
since the concept of `cursor position` is nested deep in monaco, the tests for this looked a lot like "let a = [], b = a, expect(b).toEqual(a)", which is why we dont see any here.
> feat: move cursor to end of text

- task/backend/executor/executor.go
- task/backend/executor/executor_test.go
This allows us to inject a constructor function into the Task executor that creates a `flux.Compiler` used in the query request via `WithCompilerBuilder` option. Authorization of a `context.Context` is done ahead of this decision and provided to this builder function so we can perform feature flagging of this behavior on a per-task basis.
By default, the `Executor` uses the existing AST parsing logic.
> feat(task): Allow switching of compiler from outside Executor

- .circleci/config.yml
- ui/src/notebooks/components/Notebook.tsx
- ui/src/notebooks/context/notebook.mock.json
- ui/src/notebooks/context/notebook.tsx
creating a context provider for the notebook interaction (#17966) based on the suggested structure from this talk (thanks @121watts):
https://www.youtube.com/watch?v=CDGBTjMBJzg&t=523s
I've anchored the context provider to the page for now. we'll probably want to figure out a better solution than `useState` in the near future so that components can define their own state requirements more towards the leaf nodes, and have that state shared between them, but this technique should hold up through the prototyping phase.
i've included the test mock data i've been using to ensure that interactions between notebook stages are working properly, figuring that they might be useful until we have more of the crud level interactions fleshed out.
> feat: adding notebook context

- ui/src/variables/components/VariableDropdown.scss
- ui/src/variables/components/VariableDropdown.tsx
This will make it so the width of the dropdown will adjust to the longest variable name
Closes #18021 
Ive done a simple math problem that determines the longest length in the values and makes that the width px
> fix: Adjusting the width of dropdown

- ui/src/cloud/actions/demodata.ts
- ui/src/cloud/apis/demodata.ts
- ui/src/cloud/utils/demoDataErrors.ts
- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/copy/notifications.ts
- ui/src/timeMachine/actions/queries.ts
- Add type to demodata notification to avoid notifying multiple times for the same error
- Correct error cases for demodata, to account for errors that now can be returned from sampledata service (following auth work)
- Add demodata availability error to dashboard query path
- Do not report 'adding dashboard would exceed quota errors' to HB
- If demodata bucket can not be found but feature flag is on, guide users to add demodata bucket
> feat(demodata): Polish demo data error reporting

- ui/src/cloud/components/OrgSettings.tsx
Closes #18102 
For Cloud only.
Wait for an org to be loaded before attempting to fetch org settings.
> fix(ui): wait for org to be available then fetch org settings just once

- kit/feature/override/override.go
- kit/feature/override/override_test.go
This PR enhances the `override.Flagger` implementation to verify all provided overrides exist in the `ByKeyFn` lookup map and return an error if not.
> refactor(kit/feature): verify overrides exist at initialization

- authorization/http_server.go
- http/bucket_service.go
- http/org_service.go
- kit/transport/http/api.go
- kit/transport/http/api_test.go
- kit/transport/http/error_handler.go
- pkger/http_server.go
- session/http_server.go
- tenant/http_handler_urm.go
- tenant/http_server.go
- tenant/http_server_bucket.go
- tenant/http_server_onboarding.go
- tenant/http_server_org.go
- tenant/http_server_user.go
This commit checks `http.Request.Context().Err()` to see if the context has been canceled or deadlined before writing an error code. It uses the non-standard Nginx `499` error code for client disconnection and `408` for client timeout.
https://httpstatuses.com/499
Helps influxdata/idpe#7124
> feat(http): Client disconnections should return a HTTP 499 error code.

- query/stdlib/testing/end_to_end_test.go
The e2e test driver in influxdb run the tests twice to get past the fact that there
is no way to force order between the write to storage and the read back. When
the json.Marshal call became mandatory it was added to the first run, but not
the second.
> fix: need to rebuild the query request before the second e2e test run

- query/encode.go
The column reader passed to `flux.Table.Do` is automatically released.
The function passed to the column reader should never release it
manually. This causes a double release which causes the table to be
erroneously freed when it might be referenced by another transformation.
In particular, this affected the following:
tables
|> yield()
|> to()
This is because this would produce a buffered table with two references
and pass it to both `yield()` and `to()` because `yield()` is a
pseudo-node that doesn't really exist. The real graph looks more like:
tables |> yield()
tables |> to()
The `yield()` would double release which would release the `to()`
transformation's copy of the column readers. The `to()` method would
then be invoked with an invalid column reader.
> fix(query): do not free the column reader in the no content encoders

- kit/feature/http_proxy.go
- kit/feature/http_proxy_test.go
This overrides the `net/http.Request.Host` field in the `net/http/httputil.ReverseProxy.Director` function to work around a known bug in the stdlib.
Prohibits an infinite loop in our proxying.
📎 https://github.com/golang/go/issues/28168
> fix(kit/feature): Ensure host is overridden as a workaround for stdlib bug.

- ui/src/shared/components/CloudUpgradeButton.tsx
- ui/src/shared/components/CloudUpgradeNavBanner.tsx
As a followup to https://github.com/influxdata/influxdb/pull/18062 and https://github.com/influxdata/influxdb/pull/18065
A better way to do this is to use an external function for `find` that guarantees a return value rather than throwing an error.
Using the `Array.prototype.find` is hazardous because when `settings` is not falsy, it might not necessarily be an array. We _assume_ the api will give back an array and try to call a built-in function based on that assumption. Very bad. TypeScript can't help us here either.
The best way is to guarantee an error won't be thrown, and a `find` utility function does that.
> refactor(ui): use find util rather than rely on having an array

- ui/package.json
- ui/src/notebooks/components/AddButtons.tsx
- ui/src/notebooks/components/Header.tsx
- ui/src/notebooks/components/Notebook.tsx
- ui/src/notebooks/components/Panel.tsx
- ui/src/notebooks/components/Pipe.tsx
- ui/src/notebooks/components/PipeList.tsx
- ui/src/notebooks/components/RemoveButton.tsx
- ui/src/notebooks/context/notebook.tsx
- ui/src/notebooks/hooks/usePanelState.tsx
- ui/src/notebooks/index.ts
- ui/src/notebooks/pipes/Example/index.ts
- ui/src/notebooks/pipes/Example/style.scss
- ui/src/notebooks/pipes/Example/view.tsx
- ui/src/notebooks/style.scss
This installment adds the structure around notebooks to contain the individual interaction pieces. An example pipe is given to illustrate how a pipe registers into the system and how it connects to the structure. A point of contention currently is if the panel ownership exists on the Pipe component, or on the Pipe's component (_really_ need some more names in this thing). This PR illustrates the latter as it keeps the structure of TypeRegistration smaller and disconnected from the view logic (if it should allow for the first row to be deleted, dynamic titles, etc). From here the PRs should start to diverge between adding individual display types and iterating on the structural components.
part of the initiative to spin #17966 out into real changes
> feat: adding basic structure for notebooks

- tsdb/store_test.go
Before this commit, the to and from variables were being re-declared in a block in such a way that the values were not being used.
This patch uses regular assignment so that the values are visable outside of the block where they're set.
Closes #18128
> fix(tsdb): Fix variables masked by a declaration in test

- tsdb/engine/tsm1/encoding.go
This change removes an unnesessary underscore from method declarations that don't accept a receiver value.
> fix(tsdb): address staticcheck warning st1006

- ui/package.json
Keep the version of flux in package.json in sync with yarn.lock
Resolves the conflicts for  
https://github.com/influxdata/influxdb/pull/18046/files  
https://github.com/influxdata/influxdb/pull/18092/files
> chore: restore flux version

- tsdb/engine/tsm1/compact_test.go
- tsdb/series_partition.go
This commit addresses staticcheck warning SA4006 "this value of VAR is never used" by removing unused variables.
> fix(tsdb): Address staticcheck warning sa4006

- cmd/influxd/launcher/launcher.go
- flags.yml
- http/api_handler.go
- http/session_handler.go
- kit/feature/list.go
- session/controller.go
This is the integration step for the new session service. It is currently backed by an in memory store. this should be sufficient for our OSS use. I added a control system around using the new session system as a service as well as using it as a front end piece.
> feat: integrate the new session system behind a feature flag

- pkg/metrics/registry.go
- query/executor.go
- services/httpd/response_writer_test.go
- tests/server_helpers.go
- tests/server_test.go
- tsdb/index/inmem/meta_test.go
- tsdb/series_set_test.go
This commit quiets staticcheck's warnings about "unnecessary use of
fmt.Sprintf" and "unnecessary use of fmt.Sprint".
Prior to this commit we were wrapping simple constant strings without
any formatting verbs with fmt.Sprintf().
> fix: address static check warning s1039

- client/v2/client.go
Prior to this commit, we passed a nil context to the .QueryCtx() and .createDefaultRequest() methods.
Using any of the context.Context method-set against a nil value will cause a panic.
This patch passes context.Background() instead of nil.
Closes #18137
> fix(client/v2): use non-nil context.Context value

- services/httpd/handler_test.go
Instead of type converting the Body.Bytes() to a string, we can simply
call Body.String().
While we're at it, this patch also uses a simple string comparison
instead of cmp.Equal() for two strings.
According to the docs, they're equivalent.
> refactor(http): replace string(w.Body.Bytes()) with w.Body.String()

- query/statement_rewriter.go
matchAllRegex is a global variable containing the precompiled regex that
matches ".+".
Prior to this commit, it was used in only one place and we called its
.Copy() method.
According to the docs, .Copy() is no longer needed for safe concurrent
access:
Deprecated: In earlier releases, when using a Regexp in multiple
goroutines, giving each goroutine its own copy helped to avoid lock
contention. As of Go 1.12, using Copy is no longer necessary to avoid
lock contention. Copy may still be appropriate if the reason for its
use is to make two copies with different Longest settings.
Since we require Go 1.13 or later now and we're not calling the
Longest() method, this patch removes the .Copy() call.
Now that we have a reusable matchAllRegex value, this patch then
replaces all instances of …
> refactor(query): reuse matchAllRegex

- pkg/slices/strings.go
- query/compile.go
- services/graphite/service.go
- services/meta/data.go
When comparing strings in a case-insensitive way, strings.EqualFold() is
(almost?) always faster than comparing the results of strings.ToLower().
In addition, strings.EqualFold() never causes an allocation.
This patch replaces case-insensitive string comparisons that use
strings.ToLower() with a strings.EqualFold() call.
> refactor: Change ToLower comparisons to EqualFold

- ui/src/dashboards/actions/thunks.ts
- ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
- ui/src/dashboards/components/dashboard_index/DashboardCards.tsx
hopefully addresses #17931 and influxdata/idpe#7172
super hard to detangle, but it seems to have been a combination of rendering pagination being turned off for an EAR and a thunk blocking the ui thread when trying to hydrate extra data.
Moved the follow up thunk actions further down the event loop with `setImmediate` to unblock the ui thread, effectively delaying view / cell hydration until after the dashboard list is populated (should be ok as these aren't accessed until the dashboard is opened), as well as turned pagination back on to reduce rendering of nested resources, but this time with a fixed window size instead of using react to measure the number of dashboards that are visible on the page. The EAR was an issue with a small number of dashboards not registering a full window size …
> fix: faster dashboards

- ui/src/shared/utils/vis.test.ts
- ui/src/shared/utils/vis.ts
- ui/yarn.lock
Closes #18101 
Specifying a y-axis floating number would round the number
Refactor the implementation to use parseFloat rather than parseInt as part of the parseYBounds function
> fix(parseYBounds): parseYBounds was parsing integers, causing floating numbers to be trimmed. Updated parseYBounds to parseFloat instead

- .gitignore
- DEVELOPMENT.md
- Dockerfile
- Makefile
Building and developing InfluxDB 2 locally can be a bit of a pain, as the dependencies are growing and changing with a regular cadence.
These changes allow for the user to develop in an "interactive terminal" that's inside of a container.
While putting this together, I also took it as an opportunity to adopt multi-stage Dockerfile to provide multiple targets. Currently this Dockerfile is capable of building the monolithic InfluxDB 2 image, as well as the UI on its own.
> feat: add dshell environment for local dev

- tsdb/config.go
This commit changes `DefaultSeriesIDSetCacheSize` to zero so that the tag value cache is disabled by default. There is a rare known bug where the cache can cause a segfault which crashes the process. The cache is being disabled instead of removed as some users may still need the cache for performance reasons.
Closes: #14455, #12137
> fix(tsdb): Disable series id set cache size by default.

- flags.yml
- kit/feature/list.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
Added a (disabled) planner rule that matches:
ReadGroupPhys -> { count, sum }
It uses the same physical spec node for group to implement the aggregate. The
rule requires:
* the pushDownGroupAggregate{Count,Sum} feature flags enabled
* no existing aggregate present in the ReadGroup
* use of the "_value" column only
Closes influxdata/influxdb#17892
> feat: added PushDownGroupAggregate planner rewrite rule

- notification.go
- testing/notification_rule.go
This a similar refactor to https://github.com/influxdata/influxdb/pull/17969
NotificationRuleService only has the URM and Organization service embedded to support tests. This is just interface misuse.
This PR stops asserting that URMs are created by the notification rule service as I am undertaking work to remove all references for URMs from this service. In the near future this service (along with most other services) won't know that URMs exist. They will not need them to behave properly.
Also, this test should never have asserted that this happened in the first place. All it needs to do is ensure that it can list notification rules created by the owner or anyone within the org. The presence of the URM is an implementation detail.
> refactor!(notifications): drop URM and Org services from NotificationRuleService

- ui/yarn.lock
Once more, resolving conflicts for package.json and yarn.lock over Flux. It should be:
**"@influxdata/flux": "^0.5.1"**
Here is why:
https://github.com/influxdata/influxdb/pull/18165 - most recently, this updated Flux related dependencies and left the version intact
https://github.com/influxdata/influxdb/pull/18130 - this resolved conflicts between package.json and yarn.lock
https://github.com/influxdata/influxdb/pull/18046 - originally updated Flux to this version
> chore: sync flux in yarn.lock and package.json

- CHANGELOG.md
- ui/src/shared/components/graph_tips/GraphTips.tsx
- ui/src/variables/actions/thunks.ts
- ui/src/variables/components/VariableDropdown.tsx
- ui/src/variables/mocks/index.ts
- ui/src/variables/utils/hydrateVars.test.ts
- ui/src/variables/utils/hydrateVars.ts
- ui/yarn.lock
Closes https://github.com/influxdata/idpe/issues/7030
This PR aims to address the issue of overly hydrating variables when a variable selection is made. 
The solution to this is twofold:
- Compare current selection to previous selection to ensure that selecting the same variable value will not trigger an action to hydrate the variables
- Only pass in the variable that has been selected to hydrate that specific variable
Here's how these changes impact the network requests:
This PR also includes a minor UI tweak that may have been the result of the clockface pendulum update.
Previous:
Now:
> fix(variable_hydration): limiting variable hydration to changing variables

- go.mod
- query/logging.go
- query/logging_test.go
This updates `LoggingProxyQueryService` to only conditionally log queries, based on a condition function passed in when the service is created.
> feat(query): add conditional option to LoggingProxyQueryService

- ui/src/notebooks/components/Pipe.tsx
- ui/src/notebooks/components/PipeList.tsx
- ui/src/notebooks/components/panel/NotebookPanel.tsx
- ui/src/notebooks/components/panel/NotebookPanelTitle.tsx
- ui/src/notebooks/components/panel/PanelVisibilityToggle.tsx
- ui/src/notebooks/context/notebook.tsx
- ui/src/notebooks/index.ts
- ui/src/notebooks/pipes/Example/style.scss
- ui/src/notebooks/pipes/Example/view.tsx
- ui/src/notebooks/style.scss
this keeps the notebook metadata (of known type) away from the Pipe data (of unknown type) so that we can build better visualizations around it. code kind of smells when we're keeping two arrays in sync and not keeping order separate from a lookup table, but this is just a demo. Also removed the concept of a NotebookPanel from a Pipe type and a bunch of "future interfaces", not because i have any feelings about then, but because they need to be redone with the context
> feat: keep notebook meta out of the pipes

- ui/src/checks/actions/thunks.ts
Closes https://app.honeybadger.io/projects/61122/faults/64020050
Users creating a check with a name that already exists on another check was causing us to report a HoneyBadger error. By reporting this error to HoneyBadger, we are creating extra HoneyBadger noise that isn't actionable in any way and reduces the importance of HoneyBadger errors.
Check the error message that's returned in the catch block of the saveCheckFromTimeMachine to see if there's a reference to the "rename your check" string above. If there is, don't report a HoneyBadger error.
> chore(reduce_honeybadger_noise): saveCheckFromTimeMachine creating HoneyBadger noise

- ui/src/variables/actions/thunks.ts
- ui/src/variables/utils/hydrateVars.test.ts
- ui/src/variables/utils/hydrateVars.ts
An issue arose with a recent PR that limited the number of variables we were hydrating when a user updated a variable selection value. This is simply a revert to ensure that dashboards work properly and will be followed with a fast-follow issue here:
https://github.com/influxdata/influxdb/issues/18192
> fix(variable_hydration): reverted filter function to keep dashboards working as expected

- flags.yml
- kit/feature/list.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
This adds a rule to push down aggregates that are directly over a `ReadRange` source.
I followed the existing example of `PushDownWindowAggregateRule` and did some refactoring to avoid duplicating logic.
I'll follow up with a pipeline test and a Flux end-to-end test.
> feat(query): add a planner rule to push down bare aggregates

- tenant/service_bucket.go
- tenant/service_bucket_test.go
We needed to look up the org id from the org name before we could
check to confirm we were making the correct function call
Closes #18195
> fix: when buckets are looked with a org name and bucket name

- ui/src/localStorage.ts
Solves https://app.honeybadger.io/projects/61122/faults/64056920
Inundation by HoneyBadger errors is leading us to ignore the importance of these metrics. In some cases, a HB triggered when trying to log a different error. This can cause valid errors to go unseen and unnoticed. 
This PR aims to reduce the amount of unnecessary noise generated by HB errors by fixing one of the HB errors. While this may not address the root cause of why the error was generated, it will allow for the first error to bubble up and potentially provide us with more relevant information
> chore(hb_parse_error): created a JSON validation function to prevent HB error and correctly log errors

- ui/src/shared/components/EventMarker.tsx
> fix: Change max width to fix hover

- CHANGELOG.md
- http/health.go
- http/health_test.go
- http/swagger.yml
Closes #13907 
InfluxDB 1.8 "/health" endpoint already returns version, 
```js
{
"checks": [],
"message": "ready for queries and writes",
"name": "influxdb",
"status": "pass",
"version": "1.8.0"
}
```
This PR also adds version to 2.0 "/health" endpoint
> fix(api/health): report version

- tsdb/index.go
This commit changes the SeriesIDSet merge/union/intersect functions to attach the underlying iterators as closers so that files can be retained until the data is no longer in use. The roaring operations can leave containers pointing at mmap data in the resulting bitmap so we have to track underlying file usage until the data is finished with.
> fix(tsdb): Defer closing of underlying SeriesIDSetIterators

- dbrp/service.go
- testing/dbrp_mapping_v2.go
This PR fixes a bug in the V2 DBRP Mapping Service where the number of matching mappings was returned incorrectly because the length of the match list was calculated before it was populated.
[An illustration of the bug on the Go playground:](https://play.golang.org/p/isuKrz2BtXu)
```
func main() {
n, a := func() (int, []string) {
var b []string
return len(b), func() []string {
for i := 0; i < 3; i++ {
b = append(b, fmt.Sprintf("%d", i))
}
return b
}()
}()
fmt.Printf("n: %d, a: %v\n", n, a)
}
```
```
n: 0, a: [0 1 2]
```
Tests are also updated and have been confirmed to fail without the fix in place.
> fix(dbrpv2): reflect match count correctly

- .gitignore
As we now install Goreleaser through official channels, we need to ignore
the file so that its presence isn't picked up as dirty state during a release.
Closes #
> fix: goreleaser should be ignored from Git

- ui/src/external/monaco.autogrow.ts
- ui/src/external/monaco.flux.autogrow.ts
- ui/src/notebooks/pipes/Query/style.scss
- ui/src/notebooks/pipes/Query/view.tsx
- ui/src/notebooks/style.scss
- ui/src/shared/components/FluxMonacoEditor.tsx
This allows monaco to grow to whatever hight it wants to fill the content, allowing interfaces that grow vertically. Removes minimap and the scrollbar as well, as they dont make sense when you can't scroll
> feat: allow monaco to autogrow

- tenant/service_bucket.go
- tenant/service_bucket_test.go
Closes #18221
bring tenant inline with the behavior of the old kv system as it comes to bucket lookups.
This regression was allowed through testing because the testing suite eliminate the system buckets when comparing results. That functionality can be removed soon but because we have multiple implementations of the service that behave a little different we need to leave that in for now. I wrote a test to eliminate this regression in the future.
> fix: dont add system buckets when filtering by name

- pkger/parser_models.go
- pkger/parser_test.go
this fixes a bug where we are trying to export a dashboard that has chart
with unexpected missign queries. the root cause of these issues is uknown
but the fix here is to remove the strict requirement. a user can still
delete any unexpected cell if they deem necessary after the export.
> fix(pkger): relax chart validation on query values

- ui/assets/images/notebooks-empty.svg
- ui/src/notebooks/components/EmptyPipeList.scss
- ui/src/notebooks/components/EmptyPipeList.tsx
- ui/src/notebooks/components/Notebook.tsx
- ui/src/notebooks/components/PipeList.tsx
- ui/src/notebooks/components/header/index.tsx
- ui/src/notebooks/style.scss
- ui/webpack.common.ts
Closes https://github.com/influxdata/idpe/issues/7393
- Display `EmptyPipeList.tsx` when no pipes exist
- Disable scrolling on `PageContents` when no pipes exist so empty state can be vertically centered
- Display text label next to add cell buttons (to tie in to copy in empty state)
- Create webpack alias `assets` for loading images
> feat(notebooks): add empty state

- http/swagger.yml
- ui/src/authorizations/utils/permissions.test.ts
- ui/src/authorizations/utils/permissions.ts
Added missing Permission type  `dbrp`. 
https://github.com/influxdata/influxdb/blob/1cf64fd721f855596fb270dcd7c2495240cfeea4/authz.go#L133
> fix(swagger): added missing Permission type: dbrp

- http/swagger.yml
This feature has been live for a while but I left it out of the swagger doc
because I wanted to test it in the cloud environment before I added it to the doc
> feat: add onboard user to the swagger doc

- ui/package.json
- ui/yarn.lock
Closes #18182 
Updates giraffe to latest version.
- heatmaps no longer crash when bin size causes division by zero
- custom layers receive a `key` prop as required by React when rendering a list of elements
> chore: update giraffe

- ui/src/clientLibraries/components/ClientKotlinOverlay.tsx
- ui/src/clientLibraries/components/ClientScalaOverlay.tsx
- ui/src/clientLibraries/constants/index.ts
- ui/src/clientLibraries/graphics/KotlinLogo.tsx
- ui/src/clientLibraries/graphics/ScalaLogo.tsx
- ui/src/clientLibraries/graphics/index.ts
- ui/src/index.tsx
1. add Kotlin client library
1. add Scala client library
`KotlinLogo.tsx` and `ScalaLogo.tsx` are just placeholders.
> feat(clientLibs): add Kotlin and Scala client library

- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_test.go
- pkger/service_tracing.go
references: #17997
This is a refactor to enable extending the new return type with additional arguments that are outside the domain of a summary or diff.  Nothing external to influxdb (HTTP API) is changing.
> chore(pkger): refactor return values for Apply/DryRun to enable extension

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/service.go
- pkger/service_test.go
if no stack is provided then one will be provided for you.
closes: #17997
> feat(pkger): make all pkg applications stateful

- http/swagger.yml
Current [LabelUpdate.properties](https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L10972) makes generator producing Go code mapping as `map[string]inferface{}`, whereas [LabelCreateRequest.properties](https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L10961) and [Label.properties](https://github.com/influxdata/influxdb/blob/master/http/swagger.yml#L10947) produce correctly `map[string]string`.
This PR makes the `LabelUpdate.properties` consistent with others.
> fix: [Swagger] Make LabelUpdate.properties consistent with Label and LabelCreateRequest

- .github/CODEOWNERS
Don't know why, but code owners doesn't work for the storage team. See
if a different team helps.
> fix(codeowners): storage codeowners adjustment

- storage/reads/aggregate_resultset.go
- storage/reads/aggregate_resultset_test.go
This patch adds tests for `ReadWindowAggregate` and the one supported
window aggregate, the count aggregate.
Fixes #18183
> test: add test for windowed count aggregate

- query/executor.go
- services/httpd/handler.go
Have AuthorizerIsOpen() assert if a given authizer has an
AuthorizeUnrestricted() method and if so, call that to provide the
result of AuthorizerIsOpen().
Otherwise we check if the supplied Authorizer is nil.
This preserves the fast-path for checking tag-level (and other) tsdb
operations.
This simplifies how we handle such authorizers by handling this case in
only one place.
Closes #
> refactor(http): Simplify Authorizer (#17704)

- cmd/influxd/launcher/launcher.go
- label/service.go
- label/service_test.go
This PR removes the creation of URMs from the new label service. I looked with @GeorgeMac and we found no place where these URMs are actually use, they are just created when a label is created. Removing their creation should have no side effects.
This code change is only within the new label service, so it will fall under the same feature flag that controls whether the new or old label service is being used ("newLabels").
This PR also removes some debugging fmt.prints that I forgot to remove yesterday.
> refactor: remove urms from new label service

- .github/CODEOWNERS
Storage team isn't being marked as owner in PRs touching /storage/ and
/tsdb/. Let's make sure that a user can be an owner, then iterate.
> fix(codeowners): try user handle along with team

- ui/src/Signin.tsx
- ui/src/onboarding/containers/LoginPageContents.tsx
- ui/src/shared/selectors/flags.ts
This is a temporary solution to a problem that is being addressed elsewhere. This PR aims to add a UI feature flag that can be toggled from the console, rather than using the existing configCat setup since that currently doesn't support unauthenticated requests.
> feat(flag-redirectTo): using old UI feature flag to flag redirectTo

- query/stdlib/influxdata/influxdb/operators.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- query/stdlib/influxdata/influxdb/source.go
- query/storage.go
- storage/flux/reader.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/table_test.go
- storage/flux/window.go
This implements create empty for the window table reader and allows this
table read function to be used when it is specified. It will pass down
the create empty flag from the original window call into the storage
read function.
This also fixes the window table reader so it properly creates
individual tables for each window. Previously, it was constructing one
table for an entire series instead of one table per window.
Tests have been added to verify three edge case behaviors. The first is
the normal read operation where all values are present. The second is
when create empty is specified so null values may be created. The third
is with truncated boundaries to ensure that storage is read from and the
start and stop timestamps get correctly truncated.
> feat(storage/flux): implement create empty for the window table reader

- CHANGELOG.md
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- kit/transport/http/api.go
- pkger/clone_resource.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_tracing.go
this ability exports all resources associated with a stack by the same
metadata.name fields as the original application had done it. This can
be used as a means to snapshot the current state of the stack. This can
be used for source control or other means.
closes: #18271
---
**Acceptance Criteria**
---
> feat(pkger): add ability to export by stack

- CHANGELOG.md
- dbrp/http_client_dbrp_test.go
- dbrp/http_server_dbrp.go
- dbrp/http_server_dbrp_test.go
- http/api_handler.go
- http/swagger.yml
This change adds support for the `org` name parameter in addition to `orgID` for organization lookup when interacting with the DBRP HTTP APIs for reading, updating and deleting DBRP mappings. It also enhances the DBRP mapping creation operation to consider `organization` in the request body, if `organization_id` is missing 
The logic is enhanced to fallback to look up the org ID from the org name if the ID is not present. If both are provided, the name will be ignored in favor of the ID.
> fix(dbrpv2): lookup by org name

- ui/src/timeMachine/actions/queries.ts
these didn't get wrapped when reverting an experimental flux parser. Hoping that this'll fix:
influxdata/idpe#7100
and
influxdata/idpe#7365
as the errors referenced in those issues are generated at these lines. could not reproduce the errors locally, so i'm not sure if this'll fix those, but the code doesn't need to be in here all wild and free anyways
> fix: wrap flux validation

- CHANGELOG.md
- cmd/influx/main.go
> chore(influx): disable failing when providing an unexpected error to influx CLI

- CHANGELOG.md
- cmd/influx/pkg.go
> chore(influx): improve usage for influx pkg commands

- ui/cypress/e2e/explorer.test.ts
specifcally the 'can filter aggregation functions by name from script editor mode'
Closes #
> fix: Flakey explorer test wrong test id

- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
- storage/reads/array_cursor_test.go
I found a bug in `WindowCountArrayCursor` while working on https://github.com/influxdata/flux/issues/2855 where if a window boundary happens to land on an array boundary, we get a wrong answer.
The wrong answer was that we would inadvertently skip creation of a new window, so we would end up with one window of double the `every` duration where there should have been two windows. The test case `window two input arrays` below covers this case.
This could cause us to get incorrect answers when pushing down window+count or a bare count in Flux, so I opted to merge this fix ahead of the refactoring for influxdata/flux#2855.
> fix(storage/reads): fix off-by-one error in WindowCountArrayCursor

- CHANGELOG.md
- Makefile
- cmd/influx/main.go
- pkg/httpc/options.go
Closes: #18336 
Closes: #14821
---
Acceptance Criteria
---
> feat(influx): extend CLI with versoin and user-agent

- ui/src/notebooks/components/Pipe.tsx
- ui/src/notebooks/components/PipeList.tsx
- ui/src/notebooks/context/notebook.tsx
- ui/src/notebooks/context/query.tsx
- ui/src/notebooks/index.ts
- ui/src/notebooks/pipes/Query/Results.tsx
- ui/src/notebooks/pipes/Query/ResultsHeader.tsx
- ui/src/notebooks/pipes/Query/index.ts
- ui/src/notebooks/pipes/Query/style.scss
- ui/src/notebooks/pipes/Query/view.tsx
- ui/src/notebooks/pipes/markdown/style.scss
- ui/src/notebooks/style.scss
Closes https://github.com/influxdata/idpe/issues/7138
- Create new type `BothResults` that contains both raw data and parsed results
- Using this temporarily until `RawDataTable` is included in Giraffe and accepts parsed results
- Create `Results` components as part of the `Query` pipe type
- Allow results to be rendered in 3 sizes
- Small `200px`
- Medium `400px`
- Large `600px`
> feat(notebooks): display raw data within query pipes

- CHANGELOG.md
- cmd/influx/delete.go
> fix(influx): have delete cmd respect the config settings

- go.sum
- secret/http_client.go
- secret/http_server.go
- secret/http_server_test.go
- secret/middleware_auth.go
- secret/middleware_auth_test.go
- secret/middleware_logging.go
- secret/middleware_metrics.go
- secret/service.go
- secret/service_test.go
- secret/storage.go
We needed a secret service handler that would be pluggable in the org service. Building in the new vertical stacked pattern made the most sense to solve our problem and move ahead with the strategy for our api.
> feat(secret): transition the secret service to isolated pattern

- .goreleaser.yml
Closes https://github.com/influxdata/influxdb/issues/17332
Attempts to add a separate influxctl archive to the build which contains only the `influx` cli tool
> fix(goreleaser): add separate influxctl archive

- CHANGELOG.md
- ui/src/Signin.tsx
- ui/src/onboarding/containers/LoginPageContents.tsx
- ui/src/shared/selectors/flags.ts
This PR seeks to integrate the redirectTo functionality for CLOUD users by removing the feature flag
> chore(redirectTo-flag): removed redirectTo featureFlag

- flags.yml
- kit/feature/list.go
- ui/src/index.tsx
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
Closes #18238
Adds a feature flag and a simple copy-pasta component that logs that it's a flagged component and puts that nearly identical component behind the flag.
This is the foundational work for the whole of the Community Templates MVP work. If it looks like a copy/paste job, that's because that's the intent of it! We want this to carry as little risk as possible while we build confidence in the feature flag we've set up. If I managed to set up the flags incorrectly, the worst that will happen is a user will have a statement logged to their console. Once this gets out to prod and we confirm the flagging works the way we expect, we'll start in on the radical changes.
* Run the binary with the following command:
```sh
go run ./cmd/influxd/ --assets-path=ui/build …
```
> feat: add communityTemplate feature flag and put copypasted container in it

- http/swagger.yml
This PR fixes typo in swagger, *dprps* should be *dbrps* to match the go implementation. The swagger-generated clients look ugly with such typos, there is DprsAPI and methods dprs*.
> fix(swagger): change dprps typo to dbrps

- kit/metric/client.go
found this issue trying to find metrics in data explorer. We never captured the reqs metrics until we add the `Inc` call.
> fix(metric): enable metrics collection for requests call count in RED client

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
this bug surfaces when you do not provide a stack ID to the apply call.
the new stack is created, but the resources created are not associated
with it. This remedies that issue.
> fix(pkger): provide correct stackID for recording pkg application

- flags.yml
- kit/feature/list.go
- mock/reader.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- query/stdlib/influxdata/influxdb/source.go
- query/storage.go
- storage/flux/reader.go
- storage/reads/store.go
- storage/readservice/store.go
When pushing down a group followed by an aggregate, storage will aggregate per series (not per group). Therefore a final aggregation is needed on the query side. This PR modifies the planner's rewrite rules for grouped aggregates accordingly.
Note, this PR adds rewrite rules for `group() |> first()` and `group() |> last()`. Because storage does not yet support these operations, I've updated it to expose its current capabilities.
> feat: perform final aggregation of grouped aggregates on flux side

- CHANGELOG.md
- ui/src/buckets/components/BucketCard.tsx
- ui/src/buckets/components/BucketCardActions.tsx
- ui/src/buckets/components/BucketCardMeta.scss
- ui/src/buckets/components/BucketCardMeta.tsx
- ui/src/buckets/components/DemoDataBucketCard.tsx
- ui/src/style/chronograf.scss
Closes #18229 
- Display `bucketid` on user & demo data buckets
- Clicking bucket id copies it to clipbboard (see attached gif)
- Extracted bucket card meta and actions into separate components (makes `BucketCard` easier to read)
> feat(ui): expose bucketid

- ui/src/dashboards/components/DashboardLightMode.scss
> fix(ui): ensure bold cell note text is legible in light mode dashboards

- pkger/service_tracing.go
fallback to using the package.method(type).additional format.  The default is far superior than the one off names.
> chore(pkger): fixup tracing span creation

- CHANGELOG.md
- ui/cypress/e2e/tokens.test.ts
- ui/src/authorizations/components/TokenList.tsx
- ui/src/authorizations/components/TokenRow.tsx
- ui/src/authorizations/components/TokensTab.tsx
- ui/src/shared/components/resource_sort_dropdown/generateSortItems.ts
Closes #13549 
- dropdown sorting
- description
- status
- created at
- added empty state
- added date created metadata
> chore: convert index list to resource list

- http/client.go
- pkg/httpc/options.go
Following precedent established in `net/http`, this PR updates the `influxdb/v2/http` and `influxdb/v2/pkg/httpc` packages to use shared `http.Transport` instances when creating `http.Client`s. This is necessary to ensure connections which utilize HTTP keep-alive are reused, along with other benefits of pooling.
> fix(http): Use shared http.Transport

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- pkger/store.go
> fix(pkger): lazy init the pkger store

- .gitignore
The current `.gitignore` patterns for accidental commits of binaries like `influxd` and `influx` are too aggressive. It's common for tooling to use `.gitignore` to filter out files from listings.
These rules cause the entire `cmd/*` directory to be excluded before the exclusion (!*) rules are applied. Per gitignore manfile:
An optional prefix "!" which negates the pattern; any matching file
excluded by a previous pattern will become included again. It is not
possible to re-include a file if a parent directory of that file is
excluded.
The result is that any files/packages inside `cmd/*` directories cannot be found by tooling  that use `.gitignore` for file-filtering.
This adjusts the most permissive of the rules to target project root only. Files found at other locations in the tree will …
> chore: Fix gitignore for accidental binary commits.

- CHANGELOG.md
- flags.yml
- kit/feature/list.go
- ui/src/shared/utils/filterUnusedVars.ts
- ui/src/variables/actions/thunks.ts
- ui/src/variables/mocks/index.ts
- ui/src/variables/utils/hydrateVars.test.ts
- ui/src/variables/utils/hydrateVars.ts
Closes #18192 
This PR aims to address the issue of overly hydrating variables when a variable selection is made.
The solution is as follows:
- Only pass in the variable that has been selected to hydrate that specific variable
- Create a subgraph of the variables that are being used by performing an in order tree traversal of the parent's child nodes in order to first load children, then their parents
This solution will help reduce the amount of unnecessary query requests made from the UI post order to hydrate variables. However, since it involves a lot of moving parts that currently work, I've set it behind a feature flag in order to make sure that variables are still going to work correctly
> fix(variable-hydration): fixed variable overhydration issue 

- ui/src/clientLibraries/constants/index.ts
Closes influxdata/influxdb-client-js#190
This PR updates the node/JS example to use Point API.
> docs(clientLibs/js): use Point to write data

- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
- storage/reads/array_cursor.go
- storage/reads/array_cursor_test.go
This is the first part of a refactoring that makes merges code `integer<type>WindowCountArrayCursor` with `integer<type>CountArrayCursor`. The intent here is that we only want to have to implement aggregate functions in cursors one time (e.g., first, last, max, min) rather than have to implement them once for windowed aggregation and once for aggregation over a whole range. This will let us more easily push down new aggregate functions moving forward.
I also refactored the code in `integer<type>WindowCountArrayCursor` to send out arrays no larger than `MaxPointsPerBlock` (1000) so that we get bounded memory usage and better streaming properties.
This is all part of the issue influxdata/flux#2855. This just handles `count`.  I will do `sum` in a separate PR.
> refactor(storage/reads): refactor and add unit tests for *WindowCountArrayCursor

- task/backend/executor/executor.go
- task/backend/executor/executor_test.go
In order to control query parsing behavior in Tasks more precisely, we are separating the builder function into two forms: one for system Tasks and one for non-system Tasks. Non-system Tasks are created for Checks and Notifications.
We will install an additional feature flag to drive this behavior in another layer.
> feat(task): Separate System from Non-System query compiler feature flagging.

- CHANGELOG.md
- ui/mocks/dummyData.ts
- ui/src/dashboards/actions/creators.ts
- ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
- ui/src/dashboards/constants/index.ts
- ui/src/dashboards/reducers/dashboards.ts
- ui/src/dashboards/resources.ts
- ui/src/shared/utils/mocks/resourceToTemplate.ts
- ui/src/types/dashboards.ts
Closes #15292
Dashboard page remembers sort order when you go to a different page–does not save across page reloads.
> feat: Dashboards maintain sort order after navigating away

- ui/src/notebooks/context/notebook.tsx
Just adds a little context aware helper test for notebooks so that the user can learn about linking queries together. the location of the code feels a bit weird, but it's because notebooks are allowed to know about queries, but queries arent allowed to know about notebooks. maybe there needs to be an "onAdd" function that gets added to a notebook specific register function? it all gets a little spicy too quick
> feat: adding helper text to cells

- ui/cypress/e2e/dashboardsView.test.ts
- ui/cypress/e2e/variables.test.ts
- ui/src/shared/tabbedPage/TabbedPageTabs.tsx
> test(e2e): remove note cell and variable navigation

- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/query_test.go
This adds a launcher test for the read window aggregate push down to
verify that it is done when a query is sent with the appropriate
pattern, the output is correct, and that the metric is incremented that
signals the push down happened.
Fixes #18184.
> tests(launcher): add a launcher test for read window aggregate push down

- ui/src/cloud/utils/rum.ts
Some of the RUM metrics were reporting negative numbers.
The navigation timing api reports the times that certain events in a sequence happened. To calculate load times, later values are subtracted from earlier values to determine how long an event took. If the later event hasn't finished firing, its value will be 0, resulting in a subtraction looking like `0 - someEarlierValue` leading to a negative value for the metric.
> fix: guard against negative stats when non-fired events are 0

- cmd/influxd/launcher/query_test.go
- query/stdlib/influxdata/influxdb/rules.go
This PR enables the `PushDownBareAggregateRule` and adds testing to cover `count()` as a bare aggregate. 
It also makes a small fix to `PushDownBareAggregateRule.Name()`.
> feat(query): register bare aggregate

- cmd/influx/main.go
- kit/cli/viper.go
> feat(influx): provide means to provide trace debug ids to httpc client

- http/swagger.yml
- pkger/models.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/testdata/checks_ref.yml
- pkger/testdata/notification_endpoint_ref.yml
> feat(pkger): extend SummaryCheck with its env references

- http/swagger.yml
- pkger/models.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/testdata/notification_rule_ref.yml
> feat(pkger): extend SummaryNotifcationRules with its env references

- http/swagger.yml
- pkger/models.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/testdata/bucket_ref.yml
- pkger/testdata/checks_ref.yml
- pkger/testdata/dashboard_ref.yml
- pkger/testdata/notification_endpoint_ref.yml
- pkger/testdata/notification_rule_ref.yml
- pkger/testdata/task_ref.yml
- pkger/testdata/telegraf_ref.yml
- pkger/testdata/variable_ref.yml
> feat(pkger): extend summary resource types with env refs

- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/table_internal_test.go
- storage/flux/table_test.go
The tables produced by `storage/flux` didn't previously pass our table
tests. The `Empty()` call is supposed to return false if the table was
ever not empty, but reading the table or calling `Done()` would cause
the table implementations here to return that they were always empty.
This messes up the csv encoder which then believes that it just emitted
an empty table.
The table tests for valid table implementations states that this is an
error for the table implementation. This change introduces a simple test
for `ReadFilter` and also runs the table tests on the filter iterator.
> fix(storage/flux): fix the empty call for storage/flux

- cmd/influx/write.go
- cmd/influx/write_test.go
Closes #18349 
This PR allows using http(s) URL as a source of data for `influx write` as requested by #18349 
`influx write --help` adds:
```bash
-u, --url stringArray      The URL to import data from
```
The data format detection was also enhanced. If URL's path ends with ".csv" or the URL resource content type is `text/csv`, the input data format is assumed to be `csv`
> feat(cmd/influx/write): write data from url

- ui/src/index.tsx
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/TemplateInstallerOverlay.tsx
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
- ui/src/templates/utils/index.ts
Connects #18234
Infers the name of the template from the github url, launches the first part of the new template overlay. It's still not functional, but it provides a starting point to work from.
It's behind feature flag `communityTemplates`.
To access this flag locally, start your app with:
```sh
go run ./cmd/influxd --assets-path=ui/build --feature-flags=communityTemplates=true
```
> feat(flagged): wireup simple url and name overlay

- http/Makefile
Closes #
removes the line:
`echo '//lint:file-ignore ST1005 Ignore error strings should not be capitalized' >> swagger_gen.go`
everytime you run `make`
> fix(http): silence echo command

- cmd/influx/write.go
- query/stdlib/testing/testing.go
also adds skip for flakey test identified in issue: #18463
> chore(influx): remove client timeout on write cmd's retriever

- flags.yml
- kit/feature/list.go
This PR sets the `expose` flag for the `hydratevars` feature flag so that it can be toggled on the UI
> chore(flags): updated hydratevars to expose feature flag

- .circleci/config.yml
- xcc.sh
Installing `osxcross` to `/opt` requires superuser permissions. This is
built as root in flux, but requires `sudo` for circleCI. Additionally,
there was a problem with `o64-clang` not being on the `PATH` that we
would have discovered the next time we tried to release.
> fix: build osxcross in $HOME rather than /opt

- query/select.go
This pull request changes the InfluxQL query planner to plan each field in parallel to improve planning time. Previously a query with multiple fields (e.g. SELECT SUM(x), COUNT(x)...) would plan each field one after another.
> feat(query): Parallelize field iterator planning

- ui/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx
- ui/src/utils/AutoRefresher.ts
Closes influxdata/idpe#7409
this... removes the autorefresh interaction, and... stops sending data for client instances that already have auto refresh set up on their local state
> feat: remove auto refresh from cloud instances

- ui/src/shared/components/ViewLoadingSpinner.tsx
Closes #18470 
Reset the timer when loading state is error.
> fix(ui): reset the loading spinner timer on error

- http/bucket_service.go
- http/dashboard_service.go
- http/dashboard_test.go
- http/org_service.go
- http/swagger.yml
- http/user_service.go
- ui/src/buckets/selectors/index.test.ts
Work had started on a operation log but was never fully implemented and was later partially removed. The plan here is to remove the partially defunct logs and then build a new robust op log system that will replace it in the future.
closes #18423
closes #18389
> fix: remove operation log system

- go.mod
- go.sum
- pkger/service.go
introduceds small improvement to how we capture stack traces in a panic
example of the panic log it orginated from:
```
lvl=panic msg="panic applying tasks" log_id=0NLTUCC0000 service=pkger stack_trace="[github.com/influxdata/influxdb/v2/pkger/service.go:3312 runtime/panic.go:679 runtime/panic.go:199 runtime/signal_unix.go:394 github.com/influxdata/influxdb/v2/task/options/options.go:59 github.com/influxdata/influxdb/v2/pkger/service.go:2409 github.com/influxdata/influxdb/v2/pkger/service.go:2358 github.com/influxdata/influxdb/v2/pkger/service.go:3323 runtime/asm_amd64.s:1357]"
```
> fix(pkger): capture and fix panics converting tasks

- ui/src/variables/components/VariableDropdown.tsx
The amount of spacing was too small for bucket names between 10-16 characters
No issue number 
> fix: Fixes the dropdown width for variables

- cmd/influx/write.go
- cmd/influx/write_test.go
> chore(influx): use and pass a single context in write cmd processing

- CHANGELOG.md
- ui/src/tasks/actions/thunks.ts
- ui/src/tasks/components/TaskCard.tsx
- ui/src/tasks/components/TasksList.tsx
- ui/src/tasks/containers/TasksPage.tsx
Working with tasks requires a lot of back and forth
Integrate command+click functionality on task names so that users can open and browse multiple tasks in different tabs
> feat(cmdClick-task): Added command click functionality to tasks names to open in separate tab

- task/backend/executor/executor.go
- task/backend/executor/executor_test.go
We need to make sure the runs are removed if we fail to enqueue the run to be worked.
for this we will now add an error message stating why we failed and move the run out of our kv store.
Closes #18481
> fix: clean up old runs when we fail to enqueue it

- cmd/influxd/launcher/query_test.go
- flags.yml
- kit/feature/list.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- storage/readservice/store.go
This adds the storage capability in OSS for pushing down `sum` in `ReadWindowAggregate`, and associated tests and feature flag.
> feat(query): add test and feature flag for pushing down sum

- ui/src/checks/components/ChecksColumn.tsx
- ui/src/checks/selectors/index.ts
- ui/src/dashboards/selectors/index.ts
- ui/src/dataExplorer/components/SaveAsCellForm.tsx
- ui/src/notifications/endpoints/selectors/index.ts
- ui/src/notifications/rules/selectors/index.ts
- ui/src/timeMachine/components/variableToolbar/VariableToolbar.tsx
- ui/src/variables/selectors/index.test.tsx
- ui/src/variables/selectors/index.tsx
Closes #15544
Alphabetizes all the things
> chore(alphabetize): alphabetizes dashboards in the saveas dropdown, variables in script editor, and alerts, endpoints and checks

- ui/src/shared/utils/formatStatValue.test.ts
- ui/src/shared/utils/formatStatValue.ts
Closes #18493 
The util responsible for handling the formatting of single stat values has some logic holes in it. Trailing zeroes were being truncated. This addresses the issue with unit tests.
> fix: update formatStatValue to correctly handle trailing zeroes in all cases

- ui/src/index.tsx
> fix: loads function writeNavigationTimingMetrics after window.load runs

- authorizer/authorize_find.go
- dbrp/middleware_auth.go
- dbrp/middleware_auth_test.go
In order to improve the UX of the 1.x endpoint, we are auto-creating DBRP mappings and Buckets for users if they don't exist. The current DBRP mapping permissions checking has proved problematic, because Bucket write/read tokens generated in the UI only create permissions for Bucket resources. Currently, these tokens don't have permissions to deal with DBRP mappings.
In order to allow for normal Bucket read/write tokens (all buckets and specific buckets) to access this API, I've had to make some minor adjustments to the DBRP mapping service's authorization layer. These changes force the DBRP authorization layer to focus on Buckets resource permissions instead of those of the DBRP resource type.
A few examples to illustration what this means:
- Creating a DBRP mapping will require create …
> fix(dbrp): Change DBRP mapping service to use Buckets resource permissions

- CHANGELOG.md
- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_models.go
- pkger/service_test.go
- pkger/service_tracing.go
- pkger/store.go
- pkger/store_test.go
a good chunk of this PR is jiggling some bits to remove the high lvl Pkg from the svc interface.
references: #18243 
<details><summary>TODOs</summary>
</details>
> feat(pkger): extend pkgs with source identifiers

- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- tenant/http_server_org.go
The rest of the tenant system is in place except the org http api handler and the
user api handler.
> feat: start using the new org handler from the tenant service.

- CHANGELOG.md
- authorization/middleware_metrics.go
- http/swagger.yml
- kit/metric/client.go
- kit/metric/metrics_options.go
- label/middleware_metrics.go
- pkger/service_metrics.go
- pkger/service_test.go
- tenant/middleware_bucket_metrics.go
- tenant/middleware_onboarding_metrics.go
- tenant/middleware_org_metrics.go
- tenant/middleware_urm_metrics.go
- tenant/middleware_user_metrics.go
> feat(pkger): extend metrics to collect remote sources

- CHANGELOG.md
- pkger/parser.go
- pkger/parser_test.go
- pkger/service_metrics.go
- pkger/service_test.go
closes: #18479
preview, can now provide the github.com link:
> feat(pkger): allow for base github content urls for json/yaml/jsonnet templates

- ui/src/templates/actions/creators.ts
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
- ui/src/templates/reducers/index.test.ts
- ui/src/templates/reducers/index.ts
- ui/src/types/templates.ts
Closes #18525 
Adds community template structure to redux. This is all hidden behind the flag `communityTemplates`
Pasting 
```
https://github.com/influxdata/community-templates/tree/master/csgo
```
into the file field results in the template being added to redux. Next part of the iteration will take the data this puts into redux and populate the modal with it.
> chore(flagged): add active template to redux

- cmd/influx/pkg.go
forgot to update the CLI when updating the stacks with sources:
note: I reallly like having the source available in the stack output 😃
> chore(influx): extend stacks output with sources

- http/dashboard_service.go
- kv/dashboard.go
Closes #18503
This PR moves the lookup of an organization by its name from the kv dashboard service to the http layer. This is so that we can remove the outdated organization code from the kv package and switch to using the tenant service exclusively.
> refactor: remove org service from kv dashboard service

- CHANGELOG.md
- cmd/influx/pkg.go
> feat(influx): provide for remote files in the template commands

- CHANGELOG.md
- cmd/influx/pkg.go
- pkger/models.go
> chore(influx): update usage and soften comparisons for kind matching on export

- ui/src/cloud/apis/reporting.ts
reporting errors were being logged on the console as errors. There is no need for these errors to be reflected to the user.
> feat(reporting): Silence reporting errors

- ui/src/shared/utils/fromFlux.ts
> fix(ui): remove newlines in fromFlux parser only for time strings

- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/launcher_test.go
- cmd/influxd/launcher/pkger_test.go
- cmd/influxd/launcher/query_test.go
- cmd/influxd/launcher/storage_test.go
- http/query_handler.go
- http/query_handler_test.go
- query/stdlib/testing/end_to_end_test.go
- query/stdlib/testing/testing.go
Annotate the context with feature flags when handling flux queries in influxdb.
Taking advantage of this in flux end-to-end tests. Using a custom flagger that
can set overrides based on the test case that is about to be run, allowing us
to enable features in the end-to-end tests.
> feat: annotate context with feature flags when handling flux queries

- flags.yml
- kit/feature/list.go
- kv/task.go
- kv/task_test.go
This will greatly reduce the amount of urms created in the system. To make this change to the system we need to also remove our direct reliance on the urm's in tasks.
Remove the create and delete portion of the task actions that are creating and deleting urms
Remove reliance on urm's when we are doing FindTaskByUser and instead rely on the user filter matching the task.OwnerID
One test had to be changed because the test was explicitly hacking the task to remove the owner ID and then trying to successfully look up the task by ownerID
> fix: remove urm create from task create request.

- CHANGELOG.md
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_test.go
- pkger/service_tracing.go
- pkger/store.go
> feat(pkger): extend stacks with update functionality

- CHANGELOG.md
- kit/cli/viper.go
- kit/cli/viper_test.go
adds the ability to provide a config file to Programs when using the `NewCommand` constructor 👍 
closes: #18565
> feat(cli): extend Program with config file

- kv/service.go
- kv/task.go
- kv/task_test.go
Co-authored-by: Alirie Gray <alirie.gray@gmail.com>
> feat: migrate task records to always have an owner id

- ui/src/notebooks/shared/Resizer.scss
> refactor(flows): increase contrast of helper text in cells

- ui/yarn.lock
We're having issues with `yarn.lock`
Process:
```
cd ui
rm yarn.lock
rm -rf node_modules
yarn cache clean
npm cache clean --force
yarn install --force
```
> chore: fix yarn.lock file

- CHANGELOG.md
- cmd/influx/pkg.go
> feat(influx): extend influx stacks cmd with update

- kit/cli/viper_test.go
the config for a daemon should use keys that match the flags of the
daemon it is provided too.
follow up to: https://github.com/influxdata/influxdb/pull/18568
> chore(cli): extend tests for CLI to capture how flags with `-` are in configs

- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/service.go
tie it together e2e
references: #18490
> feat(pkger): add ability to skip a resource within a template

- http/swagger.yml
Closes #
fixes a swagger error:
```
Semantic error at paths./orgs/{orgID}/invites/{inviteID}/resend.post.operationId
Operations must have unique operationIds.
Jump to line 4535
```
> fix(swagger): update opID for post resend endpoint

- cmd/influxd/launcher/pkger_test.go
one PR got merged, then the other without rebase/rerunning tests. That
is what resulted in this broken test.
> fix(pkger): fix flaky test caused by merge race condition

- CHANGELOG.md
- ui/src/organizations/components/OrgProfileTab.tsx
- ui/src/organizations/containers/OrgProfilePage.tsx
Adds user id and org id to about page, along with buttons to copy to clipboard.
> feat: add user and org id to about page

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server.go
> feat(pkger): extend public apply API with new action to skip resources by kind

- CHANGELOG.md
- cmd/influx/pkg.go
> feat(influx): extend apply command with actions to skip kind and/or resource

- ui/src/cloud/utils/reporting.ts
added the ability for the pooling mechanism to have a decay rate (which allows the chain to resolve early if events aren't coming in frequently), as well as having a max pool size, while keeping the same 5sec watchdog mechanism in place
> feat: extending reporting pooling

- CHANGELOG.md
- cmd/influx/setup.go
Convert onboardingRequest RetentionPeriod to a Duration, rather than time.Hour to a uint.
Closes #18547
> fix: uint overflow during setup on 32bit systems

- ui/src/cloud/apis/reporting.ts
- ui/src/cloud/utils/reporting.ts
`reportPoints` is the lowest level function in the reporting system we're setting up - all other calls must go through this function.
This PR moves the `appMetrics` flag / implicit cloud check to this function. Any function calling the reporting framework can now do so without needing to check if its in a cloud context or if `appMetrics` is flagged on.
> chore: move flagging location to lowest possible point - we safe now

- task/backend/executor/executor.go
This mitigates a problem that will be introduced by this: https://github.com/influxdata/influxdb/pull/18564.
> fix(task/executor): Don't send Now for Flux compiler

- ui/src/notebooks/pipes/TestFlux/index.ts
- ui/src/shared/selectors/flags.ts
this moves the flux testing panel type introduced here: https://github.com/influxdata/influxdb/pull/18554 to using the feature flag based toggles
> chore: move flux testing notebook to feature flag

- ui/src/cloud/utils/reporting.ts
- ui/src/shared/utils/errors.ts
Connects IDPE 7432. Doesn't completely finish the task.
* Adds a method that reports a single error metric to tools
* Calls this method on HoneyBadger errors
* Goal: every time we have an error, we report it, then graph each error over time to establish a baseline error rate. If the rate spikes suddenly, we have good indication that something is up.
* Todo: Start sensibly replacing calls to `console.error`. I say sensibly because in the short time I looked around, it seemed clear that there were areas where this isn't appropriate, but we're logging an error with `console.error`
> feat: add error metric writing method. call it during honeybadger errors

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- cmd/influxd/main.go
example config:
```yaml
http-bind-address: ":8888"
log-level: debug
```
logs from startup:
```
2020-06-18T17:45:59.482500Z	info	Listening	{"log_id": "0NU8Rsnl000", "transport": "http", "addr": ":8888", "port": 8888}
```
> feat(influxd): refactor run command to use cli.Program to respect config file

- CHANGELOG.md
- cmd/influx/authorization.go
- cmd/influx/backup.go
- cmd/influx/main.go
- cmd/influx/main_test.go
- cmd/influx/organization.go
- cmd/influx/ping.go
- cmd/influx/query.go
- cmd/influx/repl.go
- cmd/influx/setup.go
- cmd/influx/task.go
- cmd/influx/user.go
all CLI interactions are now to go through the front door (API).
closes: #18616
> fix(influx): remove references to local

- dbrp/http_server_dbrp_test.go
- dbrp/service.go
DBRPs are currently being persisted with a `default` value of `false` even though they are the first DBRP mapping created for a DB. This fix defers writing the DBRP mapping record until after we've determined that it is indeed the default mapping for an Organization + DB. The index that refers to his default bucket is operating as expected.
> fix(dbrp): Wait until we know this bucket is default before writing value

- CHANGELOG.md
- ui/src/shared/components/TimeSeries.tsx
Closes #18312 
Cells would randomly error out after creation because the query that was created was undefined
After some investigating, it seems like this issue is a race condition that makes it hard to reproduce consistently. I investigated the origin of the queries property that's being passed in and everything seems to indicate that queries should be there. As such, I'm not quite sure where this bug actually exists (that queries are undefined in the map dispatch to props), but adding this statement should allow us to prevent the cell from erroring out.
> fix(timeseries-map-bug): prevents random racecondition bug from erroring cells

- flags.yml
- kit/feature/list.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
This rule reorders group and window so it will switch from using
`ReadGroup` to using `ReadWindowAggregate` when the intent is to
aggregate a grouped window. It will then add a group node that groups by
the given columns and the start and stop columns and then reperform the
aggregate. This is more performant than performing the group first.
Fixes #17895.
> feat(query/stdlib): add a rule to reorder group and window

- ui/src/cloud/utils/reporting.ts
Default timestamp on `reportEvent` was clobbered in a merge.
> fix: reportEvent has a default timestamp

- cmd/influxd/launcher/pkger_test.go
- pkger/service.go
- pkger/service_models.go
missed this in the previous PR to add skip actions
missing from AC of issue: #18490
> chore(pkger): accomodate skipping resources that are part of an association

- CHANGELOG.md
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/testdata/bucket_ref.yml
- pkger/testdata/checks_ref.yml
- pkger/testdata/dashboard_ref.yml
- pkger/testdata/notification_endpoint_ref.yml
- pkger/testdata/notification_rule_ref.yml
- pkger/testdata/task_ref.yml
- pkger/testdata/telegraf_ref.yml
- pkger/testdata/variable_ref.yml
> feat(pkger): add env default vaules for template references

- Dockerfile_build_ubuntu64_git
- Dockerfile_build_ubuntu64_go1.13
- Dockerfile_jenkins_ubuntu32
- test.sh
With https://github.com/influxdata/influxdb/pull/17530, go 1.13 is required.
> fix(test): use go 1.13 in test scripts

- authorization/http_server.go
- authorization/http_server_test.go
- authorization/mock_tenant.go
- cmd/influxd/launcher/launcher.go
Addresses #18498
This PR moves the name lookup function that is used by the Authorization service from the kv lookup service to be a function of the Authorization service itself. This will allow us to remove the lookup service from the kv package when the new Authorization service feature flag is fully turned on, which is one of the steps to fully migrate to the tenant service.
This change does remove the functionality of looking up the name of a Telegraf, Dashboard, and Source. However, it doesn't appear that this code path was actually being used. The `Name` property is optional on the `Resource` definition in the swagger, and so I have left the swagger unchanged.
> refactor: move name lookup to auth http

- CHANGELOG.md
- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/variable_ref.yml
- pkger/testdata/variables.json
- pkger/testdata/variables.yml
> feat(pkger): add support for selected fields to variable

- CHANGELOG.md
- cmd/influx/pkg.go
noticed a discrepancy where tasks with a `Offset` value of nil are converted into `""` instead of `0sec`. Tiny fix to clean it up
> fix(influx): normalize output of template task diff

- CHANGELOG.md
- cmd/influx/bucket.go
- cmd/influx/config.go
- cmd/influx/main.go
- cmd/influx/pkg.go
- cmd/influx/setup.go
- task/options/options.go
- task/options/strconv.go
> fix(influx): support days as duration type

- cmd/influx/main.go
small example from setup run:
```sh
> influx setup -b $BUCKET_NAME -o $ORG -u $USER_NAME -p $USER_PASSWORD -r 1w -f
>influx bucket ls
ID			Name		Retention	Organization ID
05e3d28141308001	bucket1		168h0m0s	05e3d28141308000
```
> chore(influx): add support for week duration

- ui/src/variables/actions/thunks.ts
Connects #18296
Checks if variables have been loaded and skips the hydration process for any variables that have already been hydrated.
**previously** _note the delay between double clicking the Submit/Cancel button and the cancel notification firing_
**now** _cancel button fires immediately_*
\* I know we're planning on changing it so it doesn't flash, but the flash is actually the indicator that the ui is responsive.
> fix: don't re-fetch variables if their loading status is done

- flags.yml
- kit/feature/list.go
- kv/task.go
- kv/task_test.go
This installs a feature-flag to switch between normal options parsing and a simplified variant. In this simplified version, we are doing a naive extraction of the content `option task = { ... }` and passing that through the options extractor on its own. This allows for tasks that use functions like `tableFind` to be saved correctly.
An obvious drawback of this approach is that functions cannot be used to create the RHS of the assignment. Since most people don't do this, we should be safe until the Flux team provides some APIs for us to consume that do this extraction in a static manner.
> fix(kv): Install feature-flag for switching between normal and simplified options parsing

- query/iterator.gen.go
- query/iterator.gen.go.tmpl
- query/iterator.gen_test.go
Sorted merge iterator has cpu-intensive operations to sort the points
from multiple inputs. Typical queries like `SELECT * FROM m GROUP BY *`
do not behave well due to the comparison of points though in many cases
it doesn't necessarily have to use the slow path.
This patch adds a shortcut.  If each input has a single and unique
series we can just return the points input by input.
The detection of the shortcut introduces slight overhead but the gains
are significant in many slow queries.
See #8304
>  improvement(query): performance improvement for sorted merge iterator

- ui/src/templates/components/CommunityTemplateContents.tsx
- ui/src/templates/components/CommunityTemplateInstallerOverlay.tsx
- ui/src/templates/components/CommunityTemplateListGroup.tsx
- ui/src/templates/components/CommunityTemplateListItem.tsx
- ui/src/templates/components/CommunityTemplateName.tsx
- ui/src/templates/components/CommunityTemplateNameIcon.tsx
- ui/src/templates/containers/CommunityTemplates.scss
- Create collapsible component for groups of items in resource list
- Create component for individual resources in list
- Create component for template name
- Add SVG component for icon
- Tweak styling
> feat(templates-ui): display template resources in accordion list

- pkger/clone_resource.go
forcing the sorting makes exports deterministic. The axes returned are a map, which don't guarantee any order. This forces that order every time. Makes exporting cleaner. Found this during demo prep
> chore(pkger): ensure sorting of axes on export of a dashboard's query

- models/points_test.go
- storage/engine.go
This commit adds the `WithWritePointsValidationEnabled()` option to disable validation in `Engine.WritePoints()` as the same validation is performed earlier in the call stack by cloud.
> feat(storage): Add option to disable WritePoints() validation.

- tsdb/store.go
> fix(tsi1): wait deleting epoch before dropping shard

- ui/src/Signin.tsx
- ui/src/cloud/components/OrgSettings.tsx
- ui/src/cloud/selectors/orgsettings.ts
- ui/src/cloud/utils/reporting.ts
- ui/src/index.tsx
- ui/src/shared/actions/me.ts
- ui/src/shared/containers/GetFlags.tsx
- ui/src/shared/containers/SetOrg.tsx
wanted to double check our user segmentation vectors were in here.
added session, for when we decouple session ids from user ids
added flags, so we can compare funnels across changes there
added org settings, to reduce cross domain lookups against the datasets
> feat: adding more segmentation vectors

- CHANGELOG.md
- cmd/influx/config.go
- cmd/influx/config_test.go
Closes #18706 
note: ignore white space for this PR, makes this body of work pretty small
> fix(influx): validate host urls for influx config commands

- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/doc.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_test.go
- pkger/service_tracing.go
the Export behavior (renamed from CreatePkg) now provides for stackID as
another input. With this we are able to remove the additional endpoint
/api/v2/packages/stacks/:stack_id/export. It now fits into the
/api/v2/packages/export endpoint as another req body parameter. This also
makes all export functionality in teh same space, encapsulated both in the
endpoint and within the service layer :-).
references: #18646
> chore(pkger): refactor indpendent stack export functionality out of existence

- ui/src/buckets/selectors/index.test.ts
- ui/src/buckets/selectors/index.ts
- ui/src/notebooks/context/buckets.tsx
- ui/src/shared/components/DeleteDataForm/BucketsDropdown.tsx
i got real stoked about reimplementing resources within the system, then realized that the only issue with GetResources is that it merges the request for data with the display of data. So this PR turned into separating concerns. Wrap it around any component that needs bucket information, redux should handle the singleton mechanism required to decouple the resource fetching from the number of things requesting data.
in the same vein, removed display / formatting logic that was defined outside of the view layer to open up default sorting on buckets
> feat: adding a bucket provider

- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/query_test.go
- query/stdlib/influxdata/influxdb/rules.go
- storage/flux/reader.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/table_test.go
- storage/flux/types.tmpldata
- storage/flux/window.go
- storage/readservice/store.go
- Adds launcher tests for windowed first, bare first, and `aggregateWindow(fn: first)`
- Turns on the storage capability for first selection
- Adds a table iterator for windowed selectors
> feat: push down window first to storage

- cmd/influx/pkg.go
- cmd/influx/pkg_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/clone_resource.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/parser.go
- pkger/service.go
- pkger/service_models.go
- pkger/store.go
- pkger/store_test.go
this extends the export command with the ability to export by stack with additional resources that are not part of the stack as part of the template.  An example:
```
$ influx export --stack-id $STACK_ID --labels $UNASSOCIATED_LABEL_ID
```
references: #18646
tip: ignore whitespace changes
> feat(influx): extend influx export command with ability to export stack

- storage/flux/reader.go
- storage/flux/table_test.go
Storage should not have a dependency on libflux. This commit removes
some constants that were used from the flux universe package and
replaces them with local copies so that storage no longer has a
dependecy on the universe package.
> fix(storage): remove libflux dependency from storage

- cmd/influx/pkg.go
- pkger/models.go
- pkger/service_models.go
this was missed in a previous PR wehre we added the status in place of the
remove boolean flag
> chore(pkger): drop remove diff field no longer in use

- ui/cypress/e2e/explorer.test.ts
- ui/src/shared/components/dateRangePicker/DatePicker.tsx
- ui/src/shared/components/dateRangePicker/DateRangePicker.tsx
Sets min & max dates for max & min date picker (respectively). This means that users cannot select a start date that is after the end date, and users cannot select an end date that is after the start date.
Caveat to all of this is that these limitations are not respected when it comes to setting the time. This is an issue with the dependency that I filed here:
https://github.com/Hacker0x01/react-datepicker/issues/2184
This PR address some of the concerns listed here:
#15632
> chore(min-max/customtimerange): set min & max dates for start & vend time respectively

- cmd/influxd/launcher/pkger_test.go
- pkger/clone_resource.go
- pkger/models.go
backfilling a blind sopt in pkger. The diff dashboard charts were not working correctly across RPC boundaries. The marshal/unmarshal stuffs was off.
> fix(pkger): update handling of diff dashboard charts

- checks/service.go
- checks/service_external_test.go
- checks/service_test.go
- cmd/influxd/launcher/launcher.go
Part of #18498
This change copies @GeorgeMac's checks service. This change should not affect any functionality. This will allow us to remove the checks file from the kv package which is the last step to removing all references to orgs and urms from kv so that we can switch entirely to the tenant service remove the dead code from kv.
Blocking https://github.com/influxdata/influxdb/pull/18551
> refactor: move checks service to new package

- ui/src/dataExplorer/components/DataExplorerPage.tsx
- ui/src/timeMachine/actions/queryBuilder.ts
Closes #18510
Navigating to the DataExplorer was making two query requests for buckets
Removed Buckets from GetResources wrapper around DataExplorerPage and updated the loadBuckets function to set the loaded buckets once they are returned from the API and normalized.
> feat(loadBuckets): loadBuckets sets buckets after req and removed Buckets fetching from DataExplorerPage

- CHANGELOG.md
- cmd/influx/template.go
- cmd/influx/template_test.go
- cmd/influxd/launcher/pkger_test.go
- pkger/http_remote_service.go
- pkger/http_server.go
- pkger/http_server_test.go
- pkger/service.go
- pkger/service_logging.go
- pkger/service_test.go
- pkger/store.go
- pkger/store_test.go
> feat(influx): extend stacks update cmd with ability to add resources

- cmd/influxd/launcher/launcher.go
- pkger/http_remote_service.go
- pkger/http_server_packages_deprecated.go
- pkger/http_server_packages_deprecated_test.go
note: going to make this evolution in two steps so that we have a simple
rollback to get back to a working state. We'll be maintaining both packages
and the new templates and stacks endpoints for a while as users start to
move onto a newer CLI version. Sunsetting by end of July.
references: #18580
> chore(pkger): convert packages endpoints into new naming convention

- ui/src/templates/components/CommunityTemplateListGroup.tsx
- ui/src/templates/reducers/index.ts
Template resource collections are made into empty arrays.
Guards against empty or `null` collections coming back from the API.
> fix: update templates contents to handle empty collections

- ui/src/cloud/utils/reporting.ts
Closes influxdata/idpe#7766
idk why typescript wasn't catching this, but... lets force tags to be strings!
> fix: only send strings

- ui/src/shared/components/XYPlot.tsx
- ui/src/shared/utils/vis.ts
When a flux response returned with multiple tables with two different value column types i.e. `bool` in one table and `number` in the other.
see for example: [howdy.txt](https://github.com/influxdata/influxdb/files/4847331/howdy.txt)
The `XYPlot` would sometimes render "Incorrect graph type" and sometimes would display the line data. 
If there is renderable data, we display it.  We do this by selecting a sane default `yColumn` of type `number` if none is provided.  Previously, we could select a default for the y-axis of type `time`.  This didn't make sense for a default.
> fix: intermittent incorrect graph type

- ui/src/notebooks/NotebookVariables.scss
- ui/src/notebooks/components/header/index.tsx
- ui/src/notebooks/components/minimap/MiniMap.scss
- ui/src/notebooks/components/minimap/MiniMap.tsx
- ui/src/notebooks/components/minimap/MiniMapToggle.tsx
- Rename (in UI) "Minimap" to "Table of Contents" to make the component more intuitive
- Move toggle to be contained within the component it is toggling
- Redesign component to have a header and more consistent expand/collapse icons
> feat(flows): redesign minimap and rename to "Table of Contents"

- ui/src/index.tsx
- ui/src/shared/reducers/flags.ts
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/containers/TemplatesIndex.tsx
Tweaks community templates' structure around feature flagging
Previously the flagging occurred in `index.tsx`, but now the flagging is handled by `TemplatesIndex.tsx`, which either renders itself normally or conditionally renders the flagged template path.
to toggle the flag, start your local influxd process with:
```sh
go run ./cmd/influxd --assets-path=ui/build --feature-flags=communityTemplates=true
```
> fix: tweak flagging structure of Community Templates

- ui/cypress/e2e/dashboardsView.test.ts
Closes #18732
Wrote a test to guard against potentially breaking changes to variable hydration when a user has nested query variables that are dependent upon one another
> chore(hydrate-variable-test): added a test to ensure variable hydration happens correctly in nested queries

- cmd/influxd/launcher/launcher.go
- http/swagger.yml
- pkger/http_server_packages_deprecated.go
- pkger/http_server_stack.go
- pkger/http_server_stack_test.go
- pkger/http_server_template.go
- pkger/http_server_template_test.go
this extends pkger with the new stable endpoints for working with templates. The following has been added:
```
/api/v2/templates/export  => replacement for /api/v2/packages
/api/v2/templates/apply   => replacemetn for /api/v2/packages/apply
/api/v2/stacks => replacement for the route tree for /api/v2/packages/stacks
```
The existing `/api/v2/packages` is deprecated and marked with a sunset header. It is still available for older clients (think older CLI versions). It will be dropped end of July or sometime August, likely with OSS-v2-beta 15 or 16.
note: vast majority of this is mostly copy pasta from the deprecated http server. The biggest changes here are the actual public API. To facilitate that we split the HTTP servers as well
references: #18580
> feat(pkger): add stable HTTP APIs for stacks and templates

- CHANGELOG.md
- pkger/http_remote_service.go
this implicitly affects the CLI which uses that client. It will now hit the
new endpoints which will ship with the next release of OSS beta, and have
already landed in our upstream repos.
references: #18580
Closes #
> feat(pkger): update remote http client to use new routes

- cmd/influxd/launcher/pkger_test.go
- pkger/http_remote_service.go
- pkger/parser.go
this PR also deduplicates error messages in the CLI.
> fix(pkger): stop swallowing parser errors from pkger parser in http remote service

- flux/stdlib/influxdata/influxdb/buckets.go
- patches/flux.patch
The buckets call had a column removed and the backport did not remove
that line. This modifies the buckets command to not append a row to a
column that no longer exists.
Fixes #17317.
> fix(flux): buckets call no longer panics

- ui/src/cloud/components/OrgSettings.tsx
fixes an issue where we are unable to unmarshal an app metrics post because of a malformed json schema. no idea where i got the previous shape from, but i am curious why typescript wasn't screaming about it.
> fix: org setting causing 400 errors on app metrics

- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/models.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service_test.go
> feat(pkger): extend template Summary with discrete kinds for each summary type

- tsdb/tsm1/engine_measurement_schema.go
- tsdb/tsm1/engine_measurement_schema_test.go
- tsdb/tsm1/engine_schema.go
Fixes #7589.
Append a comma to the TSM key prefix when matching a full measurement name to avoid erroneously matching other measurement names that include the prefix in their own name. For example, this prevents matching a measurement "cpu1" when targeting "cpu" by updating the prefix to "cpu,". This relies on the fact that tag key-value pairs are separated by commas.
> fix(tsm1): delimit tsmKeyPrefix with appended comma

- .circleci/config.yml
- .goreleaser.yml
- xcc.sh
> fix(release): create static builds for linux amd64

- kv/migration/all/0003_task_owners.go
This is a fix for a typo in a migration name. Introduced in the migration refactor.
> fix: typo in migration name

- cmd/influxd/launcher/launcher.go
- mock/points_writer.go
- storage/points_writer.go
- storage/points_writer_test.go
This commit adds a LoggingPointsWriter which wraps a PointsWriter and provides logging when a write fails.
Initial float write:
```sh
% influx write 'm v=1'                                        
```
Write to the same field but as an integer:
```sh
% influx write 'm v=1i'                                        
Error: Failed to write data: unexpected error writing points to database: partial write: series type mismatch: already Float but got Integer dropped=1.
See 'influx write -h' for help
```
Query logging from the `_monitoring` bucket:
```sh
% influx query 'from(bucket:"_monitoring") |> range(start:-1h)'
Result: _result
Table: keys: [_start, _stop, _field, _measurement]
_start:time                      _stop:time           _field:string     _measurement:string …
```
> feat(storage): Add logging points writer

- cmd/influxd/launcher/query_test.go
- flags.yml
- kit/feature/list.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- query/stdlib/testing/testing.go
This PR turns pushdown optimizations on by default for
```
|> group |> count
|> group |> sum
|> group |> first
|> group |> last
```
> refactor: remove feature flag for certain pushdowns

- http/bucket_service_test.go
- http/swagger.yml
This PR set `orgID` from `PostBucketRequest` as a required field. 
See sources:
https://github.com/influxdata/influxdb/blob/af1119304d7130606235eeec73144c8212b54598/http/bucket_service.go#L345
https://github.com/influxdata/influxdb/blob/5776350a5396b1f5b5f25f8c5b81582d536a35c2/tenant/http_server_bucket.go#L297
https://github.com/influxdata/influxdb-client-python/issues/119
> fix(swagger): PostBucketRequest.orgID is required

- cmd/influxd/launcher/launcher.go
- storage/points_writer.go
- storage/points_writer_test.go
This pull request changes the writer to use `storage.BucketFinder` which is a subset of the `influxdb.BucketService` interface.
> fix(storage): Refactor LoggingPointsWriter to use BucketFinder

- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
Backport https://github.com/influxdata/influxdb/pull/18710 to 1.8
> fix: gracefully handle errors when creating snapshots

- DEVELOPMENT.md
- ui/src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx
- ui/src/dataLoaders/components/lineProtocolWizard/LineProtocolHelperText.tsx
- ui/src/telegrafs/components/TelegrafExplainer.tsx
The "Write Data" section of the v2 documentation was restructured. Although redirects were put in place for all the modified docs, we're adding new functionality that will automatically select and update cloud URLs if users visit the docs from Cloud. 301 redirects lose the referrer. I updated the links to prevent the need for redirects.
> chore(docs): update documentation links

- ui/src/templates/actions/creators.ts
- ui/src/templates/components/CommunityTemplateContents.tsx
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
- ui/src/templates/reducers/index.test.ts
- ui/src/templates/reducers/index.ts
- ui/src/templates/selectors/index.ts
- ui/src/templates/utils/index.ts
- ui/src/types/templates.ts
Community Templates background work. Changes our internal representation of templates to match pkgr's model.
When we send a yaml, json, or jsonnet template file to the pkgr API, it returns an object with a `summary` of the template, and a `diff` of the changes, among other things. Previously, our redux store used `summary` and discarded everything else. Now it's storing the entire object returned from the API. The frontend still only uses `summary` at the moment, but that will change in the future.
These commits were split off of work to install templates which is still underway.
> chore(flagged): rename variables

- cmd/influxd/launcher/launcher.go
- tenant/service.go
This PR adds a new struct called `TenantSystem` which encompasses the services provided by a TenantService, to make it simpler for the engineer who is plugging in the TenantService.
> refactor: add new tenant system struct to consolidate services

- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
- ui/src/templates/containers/TemplatesIndex.tsx
- ui/src/templates/reducers/index.ts
- ui/src/templates/utils/index.ts
Updates community templates to be compatible with react router 5 changes.
Mostly shuffling code around, [this](https://github.com/influxdata/influxdb/pull/18871/files#diff-b8bbbcc08236ad73ba323c538d2d3c51R53) is the only relevant change. 
See: https://codedaily.io/tutorials/48/Use-matchPath-to-Match-Nested-Route-Paths-in-Parent-Routes-with-React-Router
> chore(flagged): update templates to use react router 5 hotness

- ui/cypress/e2e/tasks.test.ts
- ui/src/shared/components/ImportOverlay.tsx
- ui/src/tasks/components/TaskImportFromTemplateOverlay.tsx
- ui/src/tasks/components/TemplateBrowserEmpty.tsx
- ui/src/tasks/containers/TasksPage.tsx
Closes influxdata/idpe/issues/7838
`tasks/import` also matches `tasks/import/template`
Changed the route for importing tasks from a template to end in `import-template`.  Also, added non-existent tests that would have easily caught this.
> fix(tasks): import from template overlay

- cmd/influx/main.go
- cmd/influxd/main.go
Closes #18628 
Calling a function on variable definition appears to be run after ldflags are processed, overwriting anything set in the ldflags. This respects any ldflag settings
> fix: don't overwrite build date set via ldflags

- CHANGELOG.md
- cmd/influx/template.go
- cmd/influx/template_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/clone_resource.go
- pkger/http_remote_service.go
- pkger/http_server_packages_deprecated.go
- pkger/http_server_packages_deprecated_test.go
- pkger/http_server_stack.go
- pkger/http_server_stack_test.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_models.go
- pkger/service_test.go
- pkger/service_tracing.go
- pkger/store.go
- pkger/store_test.go
this PR is a bit of a monster. It upends all the stacks to be event sourced (sorta). The idea is this. We track each change to a stack, create/update/delete. When we retrieve the stack, it has all the details for that stack's operations.  
Things that are painful... working with a kv store here. Having a relational store here would have been super nice. We can order stacks listed coherently without having to force the app layer to get into the kv store weeds. Will take this as a follow up action item to see if I can make this a forcing function for using a relational store. Boy would that make this a thing of beauty.
closes: #18874
> feat(pkger): make stacks event sourced

- CHANGELOG.md
- ui/src/shared/utils/useVisDomainSettings.test.ts
- ui/src/shared/utils/useVisDomainSettings.ts
Closes #18853 
0 is a falsy value and was considered an unallowable custom set minimum value. We will allow 0 and guard against NaN and Infinity instead.
> fix: allow custom set y-axis min to be 0

- storage/engine_measurement_notime_schema.go
- tsdb/cursors/schema.go
- tsdb/tsm1/engine_measurement_notime_schema.go
- tsdb/tsm1/engine_measurement_notime_schema_test.go
- tsdb/tsm1/engine_measurement_schema.go
This PR introduces optimized schema APIs for InfluxQL only that utilize the time series index (TSI) exclusively. These new APIs are prefixed with `Measurement` and suffixed with `NoTime` to reflect this behavioral change that they do not require time bounds. The existing `Measurement*` APIs will be deprecated and removed in future commits, but must remain for the short term to avoid build errors.
These improvements affect all queries for InfluxQL, including schema and `SELECT.
Testing with a dataset of 60,000,000 series across 6 measurements:
* `SHOW MEASUREMENTS` 5,470ms ↓ 0.36ms (15,000x improvement)
* `SHOW TAG VALUES` resulted in a similar improvement
> feat(storage): InfluxQL schema APIs without time range

- cmd/influxd/launcher/query_test.go
- tsdb/tsm1/array_cursor.gen.go
- tsdb/tsm1/array_cursor.gen.go.tmpl
- tsdb/tsm1/array_cursor_test.go
Previously a descending array cursor excluded points whose timestamps were equal to the end time, i.e the beginning of the range. This bug only recently showed up because until now we haven't been using descending array cursors at all. However we recently enabled pushing down `last()` to storage which does in fact use them.
> fix: descending array cursor should include end time

- tsdb/tsm1/file_store.go
- tsdb/tsm1/reader.go
- tsdb/tsm1/tombstone.go
This pull request adds a "created at" field to `tsm1.FileStat` which uses the `ModTime()` of the TSM file but excludes any updates for tombstone files.
> feat(tsdb): Add CreatedAt field for tsm1.FileStat

- FUZZ.md
- jsonweb/fuzz.go
For a basic overview of our fuzzing initiative and [OSS-Fuzz](https://google.github.io/oss-fuzz/) integration, see ~the README~ FUZZ.md included in this PR.
There are many ways to integrate fuzz tests into a project. Instead of the structure proposed here, we might prefer to do things [the way Golang does](https://github.com/golang/go/tree/master/src/html), with fuzz tests included in the packages themselves. This can evolve over time as we find something that works for us.
> feat: Add initial OSS-Fuzz testing integration

- storage/engine_measurement_notime_schema.go
- tsdb/tsm1/engine_measurement_notime_schema.go
- tsdb/tsm1/engine_measurement_notime_schema_test.go
- tsdb/tsm1/keymerger.go
- tsdb/tsm1/keymerger_test.go
Continuation of the work @stuartcarnie performed in https://github.com/influxdata/influxdb/pull/18894.
Fixes influxdata/idpe#7843
> feat(tsdb): SHOW TAG KEYS (no time) query using only TSI data.

- ui/src/templates/actions/creators.ts
- ui/src/templates/actions/thunks.ts
- ui/src/templates/api/index.ts
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplatesActivityLog.tsx
- ui/src/templates/reducers/index.test.ts
- ui/src/templates/reducers/index.ts
- ui/src/types/templates.ts
Closes #18552
Cleans up the template install process:
* adds stacks (which represent installed templates) to templates store in redux
> chore: connected community template stacks to redux

- CHANGELOG.md
- cmd/influx/template.go
- cmd/influx/template_test.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server_packages_deprecated_test.go
- pkger/http_server_stack.go
- pkger/service.go
- pkger/service_auth.go
- pkger/service_logging.go
- pkger/service_metrics.go
- pkger/service_tracing.go
this new ability removes the resources associated with the stack
and adds the uninstall event.
> feat(pkger): extend stacks API with uninstall ability

- .github/CODEOWNERS
CODEOWERS for the storage team was fixed by giving the team permission to write to the repository. Jacob can relax now.
> chore: remove Jacob from CODEOWNERS

- tenant/storage_urm.go
- tenant/storage_urm_test.go
We will now respect limits when passed in for user resource mapping lookups for allrequest types.
> fix: urm list actions when filtering by userID needs to respect page limits

- tsdb/tsm1/engine_schema.go
Checking a channel too regularly could cause context switching to other goroutines. In tight loops, it is prudent to check, but to do so less frequently so as to avoid thrashing.
I have observed traces with huge swings in latency calling the same function repeatedly, which suggests this might be a cause. The alternative is page faults, or other I/O contention.
> fix(storage): Reduce the check frequency

- variable.go
> Variable protected names

- ui/src/eventViewer/components/EventTable.tsx
The Notification Rule history page was erroring out after dispatching a notification. The reason for this is that one of the `useEffect` parameters being passed in was causing a series of rerenders that were crashing the app.
Remove the offending useEffect parameter (since it wasn't being used in the useEffect), and added a clearTimeout function
> fix(EventTable): fixed a max call stack exceeded error

- .circleci/config.yml
I noticed the `lint-feature-flags` check wasn't running on PRs. This aims to fix that by adding it to various jobs lists in the circle config. I added it wherever I saw other lint jobs.
> fix(ci): add lint-feature-flags to jobs lists

- testing/auth.go
- testing/bucket_service.go
- testing/checks.go
- testing/dashboards.go
- testing/dbrp_mapping_v2.go
- testing/keyvalue_log.go
- testing/kv.go
- testing/label_service.go
- testing/notification_endpoint.go
- testing/notification_rule.go
- testing/organization_service.go
- testing/passwords.go
- testing/scraper_target.go
- testing/secret.go
- testing/session.go
- testing/telegraf.go
- testing/user_resource_mapping_service.go
- testing/user_service.go
- testing/variable.go
I mistakenly shadowed a bunch of tests using `t.Parallel()` in some of our test harnesses.
This stops the shadowing happening. Which was leading to some tests not being run and some tests being duplicated.
> fix(testing): accidental shadowing in parallel tests

- ui/cypress/e2e/dashboardsView.test.ts
- ui/src/dashboards/actions/thunks.ts
- ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx
- ui/src/shared/utils/filterUnusedVars.ts
- ui/src/variables/actions/thunks.ts
This PR is part of a broader initiative to reduce the number of issues stemming from variable hydration. The change here is pretty straightforward. If a query variable depends on another variable that is not directly being called within a query, we should still consider that variable as "used" and it should therefore be displayed in the variable control bar.
> feat(VariableControlBar): load nested query variables onto the dashboard variable control bar

- session/service.go
- tenant/storage_urm.go
- tenant/storage_urm_test.go
Support `offset` parameter in ListURM.
Currently, this parameter is not supported and sessions depends on it for pagination.
The recent change to support `limit` has (when occasion permits) now made pages return the size of the page limit. Which breaks the session code when listing URMs. As that code keeps attempting pages until the limit is not met, using an `offset`. However, the `offset` was never added to this action.
> fix(tenant): add support for offset to list urms

- tsdb/tsi1/legacy_test.go
`TestLegacyOpen` wasn't cleaning up tmp files at termination because of a missing `defer`.
> chore(testing): add missing defer to clean up test temp files

- query/stdlib/influxdata/influxdb/dependencies.go
- query/stdlib/influxdata/influxdb/to.go
Closes #18106
This PR just produces an error for `influxdb.to()` instead of a panic when storage dependencies are absent. There will be another issue to fill in the storage dependencies and resolve this error.
> fix(query): produce error, not panic, for influxdb.to()

- CHANGELOG.md
- ui/src/shared/components/SingleStat.scss
- ui/yarn.lock
Closes #18964 
Closes #18966 
Explicitly set the `display` to `flex`.
**Safari**
**Firefox**
**Chrome**
> fix: make Single Stat cells work in Safari again

- ui/src/authorizations/components/AllAccessTokenOverlay.tsx
- ui/src/authorizations/utils/permissions.test.ts
- ui/src/authorizations/utils/permissions.ts
- ui/src/me/selectors/index.ts
Users used to be given the permission `orgs/<orgID>/users`, but this
does not help when the user is trying to access the users api (as it is
not nested under orgs in the api). We have changed the
`orgs/<orgID>/users` to be `users/<userID>` so that the token has access
to the user that created it. This will allow users to access their
tokens via the api.
> fix(ui): give user all access token permission to read user

- tsdb/tsm1/cache.go
- tsdb/tsm1/cache_race_test.go
This PR is to fixed the problem that the cache of the tsm engine may return less data than expected in reading when read&write conccurently.  This PR includes the fix and the unit test to cover this case. 
The `sz` aquired at 
https://github.com/influxdata/influxdb/blob/b74e1f649a0457e15d302328e9f29f2f41e881b5/tsdb/tsm1/cache.go#L395
may be outdated when copy data at
https://github.com/influxdata/influxdb/blob/b74e1f649a0457e15d302328e9f29f2f41e881b5/tsdb/tsm1/cache.go#L420
The actual value slice has already been modified by concurrent reading/writing, which leading the data missing in current reading.
> fix: missing data when reading after writing

- ui/cypress/e2e/dashboardsIndex.test.ts
- ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
- ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
- ui/src/shared/components/ExportOverlay.tsx
The dashboard export overlay was both linked to improperly and not rendered
Render and link to the dashboard export overlay
Refactored many tiny unit-style e2e tests into one larger e2e test as per Cypress best practices.  This includes an added test to ensure the export overlay is rendered properly from the dashboard index.
@jacobmarble
> fix: dashboard exports overlay

- cmd/influxd/launcher/launcher.go
- pkg/mincore/limiter.go
- pkg/mincore/limiter_test.go
- pkg/mincore/mincore_unix.go
- pkg/mincore/mincore_windows.go
- storage/engine.go
- tsdb/tsm1/engine.go
- tsdb/tsm1/file_store.go
- tsdb/tsm1/reader.gen.go
- tsdb/tsm1/reader.gen.go.tmpl
- tsdb/tsm1/reader.go
- tsdb/tsm1/reader_mmap.go
This commit adds `mincore.Limiter` which throttles page faults causedby mmap() data. It works by periodically calling `mincore()` to determine which pages are not resident in memory and using `rate.Limiter` to throttle accessing using a token bucket algorithm.
> feat(mincore): Add page fault limiter

- query/stdlib/influxdata/influxdb/rules_test.go
- query/storage.go
- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
- storage/reads/array_cursor.gen.go.tmpldata
- storage/reads/array_cursor.go
- storage/reads/array_cursor_gen_test.go
- storage/reads/array_cursor_test.gen.go.tmpl
- storage/reads/array_cursor_test.go
- storage/readservice/store.go
This PR adds new `min` and `max` aggregate cursors for the three numeric data types supported by storage.
I had to modify the aggregate cursor template a little bit to make this work right, since `min` and `max` are selectors and so must preserve the timestamps of their input rows (rather than just use the timestamp of the current window's upper bound).
Closes #18636
> feat(storage/reads): add min/max aggregate array cursors

- ui/src/templates/api/index.ts
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/reducers/index.ts
Previously, the UI would allow the user to toggle which resources got installed, but it was never hooked up to the install process. This hooks it up.
Created a hash/object in redux that is keyed on the `templateMetaName`, and stores the `templateKind` which are what is needed by pkger to selectively install resources.
> fix(community-templates): only install selected resources

- http/swagger.yml
> fix(swagger): correct key in TemplateApply component

- CHANGELOG.md
- cmd/influx/main.go
- cmd/influx/telegraf.go
- cmd/influx/template.go
- http/telegraf.go
- telegraf.go
> feat(influx): add telegraf resource support to influx CLI

- ui/cypress/e2e/explorer.test.ts
- ui/src/timeMachine/components/QueryTabName.tsx
Rename the query and Confirm toggle goes back as well
Closes #idpe#7244 and #idpe#7247
> test: rename the query in side menu

- CHANGELOG.md
- authorizer/agent.go
- authz.go
- http/swagger.yml
- pkger/service.go
- pkger/service_auth.go
- tenant/service_user_test.go
- ui/src/authorizations/utils/permissions.test.ts
- ui/src/authorizations/utils/permissions.ts
now that Stacks have landed, the resource type can now be included for
any all access tokens, not just the token from setup
> feat(pkger): add Stack resource type to global list

- cmd/influx/main.go
- cmd/influxd/restore/command.go
- http/backup_service.go
- internal/fs/influx_dir.go
some refactoring to help address the hardcoding of the CLI base directory.
references: #17979
> chore(fs): refactor global file consts into internal/fs

- .gitignore
- Makefile
- tsdb/gen_test.go
Follow-up to https://github.com/influxdata/influxdb/pull/18972, expanding the pattern to the `tsdb/testdata` directory as well. These changes are a pre-requisite to copying OSS code into the Cloud 2 codebase, to avoid introducing large binary files to that project's tree.
> chore: use go generate to download large tsdb testdata

- CHANGELOG.md
- authorizer/agent.go
- authz.go
- http/swagger.yml
- pkger/service.go
- pkger/service_auth.go
- tenant/service_user_test.go
- ui/src/authorizations/utils/permissions.test.ts
- ui/src/authorizations/utils/permissions.ts
Closes #19023
Reverts a change that is causing a sev2 in prod.
Change works locally, but does not work in IDPE because of a blockage in the deploy pipeline that is causing the code this frontend code depends on not to exist in prod.
> revert: "feat(pkger): add Stack resource type to global list"

- query/stdlib/testing/end_to_end_test.go
Force the writing of data and running of the test to happen sequentially. As
the results come out, collect them and report an error only if the diff results
are not empty.
> test: use experimental.chain in flux e2e tests to allow a single pass

- CHANGELOG.md
- cmd/influx/config.go
- cmd/influx/config/config.go
- cmd/influx/config/config_test.go
- cmd/influx/config_test.go
- cmd/influx/main.go
- cmd/influx/setup.go
introduces the new flag --configs-path to the influx CLI. This new
flag has a corresponding env var INFLUX_CONFIGS_PATH. It is useful
to export this env var in a shell dotfile for consumption throughout the
box.
closes: #17979
> feat(influx): enable dynamic configs destination

- ui/cypress/e2e/variables.test.ts
- ui/src/client/index.ts
- ui/src/dashboards/actions/thunks.ts
- ui/src/dashboards/components/DashboardHeader.tsx
- ui/src/resources/components/GetResource.tsx
- ui/src/shared/apis/query.ts
- ui/src/shared/apis/singleQuery.ts
- ui/src/shared/components/TimeSeries.tsx
- ui/src/variables/actions/thunks.ts
- ui/src/variables/utils/ValueFetcher.ts
- ui/src/variables/utils/hydrateVars.ts
Closes #18640
A bunch of slow and unresolved requests to `/query` would continue to fetch despite the user navigating away from the page.  Thus making the rest of their experience slow and 💩 
When the the Dashboard Page un-mounts cancel any requests to `/query` that are in flight.
> perf: cancel dashboard page requests

- ui/cypress/e2e/orgs.test.ts
- ui/cypress/support/commands.ts
- ui/src/pageLayout/components/OrgSwitcherItem.tsx
Closes #18992 
What wins...200,000 lines of javascript or one missing `/`?
e2e test added.  Shocked that there wasn't one for this already.
> fix: switch org

- pkg/mincore/limiter.go
- storage/engine.go
- tsdb/seriesfile/series_file.go
- tsdb/seriesfile/series_index.go
- tsdb/seriesfile/series_partition.go
- tsdb/seriesfile/series_segment.go
- tsdb/tsi1/index.go
- tsdb/tsi1/index_file.go
- tsdb/tsi1/index_files.go
- tsdb/tsi1/log_file.go
- tsdb/tsi1/measurement_block.go
- tsdb/tsi1/measurement_block_test.go
- tsdb/tsi1/partition.go
- tsdb/tsi1/tag_block.go
- tsdb/tsi1/tag_block_test.go
- tsdb/tsi1/tsi1.go
- tsdb/tsi1/tsi1_test.go
This pull request adds the `mincore.Limiter` into the TSI & Series File. The original PR (https://github.com/influxdata/influxdb/pull/18982) only injected the limiter into TSM.
> feat(tsdb): Add optional mincore limiter to TSI & Series File

- CHANGELOG.md
- cmd/influx/main.go
- cmd/influx/telegraf.go
- cmd/influx/template.go
- cmd/influx/write.go
> fix(influx): enforce flag validation

- bolt/kv.go
- kv/kv_test.go
- tenant/service_test.go
Recently @jsternberg brought to our attention some significant slow down in the `kv` package tests:
```
ok  	github.com/influxdata/influxdb/v2/kv	232.568s
```
> OSX 16 hyperthreads
Upon inspection. It appeared that an increase in the number of buckets being created and initial update transactions performed on the multiple instances of bolt we create in parallel was causing a lot of time spent on fsync:
Fortunately, bolt offers the ability to disable fsync if needed. So I have done for `kv` and `tenant` which both use the `testing` package with bolt.
```
ok  	github.com/influxdata/influxdb/v2/kv	12.623s
```
This has improved performance of tests in this package by a factor of >10.
I am unsure if anyone has any reservations about doing this. I personally think it is worth it for test …
> chore(bolt): add option to skip fsync for test purposes

- tenant/http_server_bucket_test.go
- tenant/service_bucket_test.go
- tenant/storage.go
- tenant/storage_bucket.go
- tenant/storage_org.go
- tenant/storage_user.go
Closes #19017
This move tenant back to using the `rand` packages id generator when generating IDs for orgs and buckets.
Prior to this change, it was possible for harmful IDs to be generated for buckets and organizations. Which could leave buckets or even entire orgs unable to read their data (empty responses).
> fix(tenant): use rand org bucket id generator over snowflake in tenant service

- query/stdlib/experimental/to.go
- query/stdlib/influxdata/influxdb/storage.go
This is just a small clean-up PR.
1. ~Tenant bucket auth middleware doesn't need a URM service (It doesn't use it).~ (doing this in another PR)
2. The `to()` related pieces don't need to resolve a bucket or orgs name from an ID in order to function.
> chore: cleanup bucket auth and to transform dependencies

- http/swagger.yml
The generated typescript code (for influxdb-client-js) does not pass a tsdoc linter check and complains with `The code span is missing its closing backtick`. A fix is provided herein.
> docs(swagger): repair description

- CHANGELOG.md
- http/swagger.yml
- pkger/http_remote_service.go
- pkger/http_server_stack.go
- pkger/http_server_stack_test.go
> feat(pkger): add resource links to a stack's resources from public HTTP API list/read calls

- ui/src/shared/utils/vis.test.ts
Co-authored-by: Zoe Steinkamp <zoe.steinkamp@gmail.com>
Closes #19046 
Adds a unit test for the `defaultXColumn` and `defaultYColumn` functions.
> test: add unit test to default x and y column functions

- CHANGELOG.md
- http/swagger.yml
- notification/endpoint/endpoint.go
- notification/endpoint/endpoint_test.go
- notification/endpoint/telegram.go
- notification/rule/rule.go
- notification/rule/rule_test.go
- notification/rule/telegram.go
- notification/rule/telegram_test.go
- ui/src/notifications/endpoints/components/EndpointCards.tsx
- ui/src/notifications/endpoints/components/EndpointOptions.tsx
- ui/src/notifications/endpoints/components/EndpointOptionsTelegram.tsx
- ui/src/notifications/endpoints/components/EndpointOverlay.reducer.ts
- ui/src/notifications/endpoints/components/EndpointTypeDropdown.tsx
- ui/src/notifications/endpoints/components/EndpointsColumn.tsx
- ui/src/notifications/rules/components/RuleMessageContents.tsx
- ui/src/notifications/rules/components/TelegramMessage.tsx
- ui/src/notifications/rules/utils/index.ts
- ui/src/types/alerting.ts
Closes #17899 
This PR adds [telegram](https://telegram.org) notification endpoint and notification rules. It depends on influxdata/flux#2857 that introduces a new *telegram* package to send notifications.
What is in this PR
* implementation and tests of telegram endpoint and rule
* swagger updated with telegram notification rule and endpoint
* updated UI to use the new swagger + new UI for telegram endpoint and rule:
* Create/Edit Telegram Notification Endpoint
* Create/Edit Telegram Notification Rule
* note that telegram default message template wraps variables  into \`preformatted text\` to prevent telegram markdown errors
What is not in this PR
* telegram endpoint and rule in =pkger= 
* new UI tests
> feat(notification/telegram): add telegram notification

- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplateName.tsx
- ui/src/templates/components/CommunityTemplatesActivityLog.tsx
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
- ui/src/templates/containers/TemplatesIndex.tsx
- ui/src/templates/utils/index.ts
Closes #19050
Closes #19052
First round of spit and polish.
- Upload form used to take the url of the repository / directory. Now it takes specific template resources (e.g. yml, json)
- Now shows template name in the activity log.
> fix: community templates ui polish

- ui/src/cloud/utils/reporting.ts
- ui/src/notebooks/components/NotebookPipe.tsx
- ui/src/notebooks/components/panel/InsertCellButton.tsx
- ui/src/notebooks/components/panel/NotebookPanel.tsx
- ui/src/notebooks/components/panel/NotebookPanelTitle.tsx
- ui/src/notebooks/components/panel/PanelVisibilityToggle.tsx
- ui/src/notebooks/context/notebook.current.tsx
- ui/src/notebooks/context/notebook.list.tsx
- ui/src/notebooks/context/pipe.tsx
- ui/src/notebooks/context/refs.tsx
- ui/src/notebooks/context/resource.hook.tsx
- ui/src/notebooks/context/results.tsx
- ui/src/notebooks/context/time.test.tsx
- ui/src/notebooks/index.ts
there's errors that keep showing up on our ci pipelines that are frustrating
this cleans them
> fix: remove fancy types from notebooks

- pkg/httpc/client.go
- pkg/httpc/options.go
- pkg/httpc/req.go
This adds an error return argument to the auth func in httpc package. Just so an auth func provided can get into the control flow if something goes wrong deriving authorization. This is useful for example when deriving a jwt.
> feat(httpc): add error return argument to auth func

- kv/dashboard.go
This PR removes a block of code deleting URMs in the kv dashboard service since URM creation has already been removed from dashboards, so this code is obsolete.
> refactor: remove outdated URM deletion from kv dashboard service

- CHANGELOG.md
- cmd/influx/template.go
- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/http_server_template.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
this change removes implicit default values from env refs returned via the API. All default values moving forward will have to be explicity provided via the template. The magical `env-ENVREFKEY` thing is finally going away. This work is in support of query parameterizations which will follow this.
references: #18237
> feat(pkger): make envRef default values support more types

- ui/src/dashboards/utils/tableGraph.ts
- ui/src/shared/selectors/flags.ts
this addresses influxdata/ear#1644
the current default behavior is to implement a sort on the first column returned from the backend. this over-writes any sort that was explicitly defined in the query and not in the interface. i made it return data just like it came back from the server unless the user specifies a sort in the view options.
weary about the product level consequences, so i'm wrapping it in a flag to let russ click around before removing the flag
> fix: removing default sort on tables

- ui/src/shared/copy/notifications.ts
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplatesInstalledList.tsx
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
- ui/src/templates/utils/index.ts
Closes #18239 
This will add the Error messaging to the community Templates pages. So when users run into problems they will receive an error notification or a success notification if functions are succesful
> feat: Community Template error messages

- cmd/influxd/launcher/query_test.go
- query/dependency.go
- testing/bucket_service.go
The `buckets()` command would use a bucket lookup that wrapped the
`FindBuckets` API. It did not use the pagination aspect of this API
correctly. When the underlying implementation was changed to a version
that correctly implemented pagination, this broke the query `buckets()`
command. Since it was query that used the API incorrectly rather than a
regression in the `FindBuckets` implementation, this fixes the usage to
correctly use pagination.
Fixes #18971.
> fix(query): paginate bucket results in the bucket lookup

- cmd/influxd/launcher/pkger_test.go
- dashboard.go
- http/check_test.go
- http/swagger.yml
- notification/check/threshold.go
This PR has the backend changes for the autoaggregation work to be incorporated in to the UI:
- Add the new `fillValues` property to the autoAggregate property of the builderConfig in dashboards and in the swagger definition
- Change check flux generation logic to check if a createEmpty exists on a call to aggregateWindow, before adding it
- Fix tests
> feat(autoAggregate): BE work for autoAggregate

- ui/src/shared/copy/notifications.ts
- ui/src/templates/api/index.ts
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplatesInstalledList.tsx
Closes #19095
Closes #19096
Names the newly installed template based on the directory and template name. This depends on our github [templates directory](https://github.com/influxdata/community-templates) structure. This'll have to be changed for files.
> feat(community-templates-flagged): name installed templates

- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplatesInstalledList.tsx
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
Adding the error reporting to the community template pages. So when errors happen we have a paper trail of reporting, so we can patterns, bad apples, etc.
> feat: Add Error Reporting to community templates

- ui/src/clientLibraries/constants/index.ts
This change updates the Arduino client library examples to point to the proper location of the orgid and token.
> chore: Update orgID location and Token location for Arduino client library boilerplate.

- CHANGELOG.md
- ui/src/alerting/components/AlertsColumn.tsx
- ui/src/buckets/components/CreateBucketButton.tsx
- ui/src/checks/components/ChecksColumn.tsx
- ui/src/checks/components/CreateCheckDropdown.tsx
- ui/src/cloud/actions/limits.ts
- ui/src/cloud/components/AssetLimitButton.tsx
- ui/src/cloud/components/AssetLimitOverlay.tsx
- ui/src/cloud/utils/limits.ts
- ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
- ui/src/overlays/components/OverlayController.tsx
- ui/src/overlays/reducers/overlays.ts
- ui/src/shared/components/AddResourceDropdown.tsx
- ui/src/shared/components/CloudUpgradeButton.tsx
- ui/src/shared/components/cloud/CloudOnly.scss
- ui/src/tasks/components/TasksHeader.tsx
- ui/src/types/alerting.ts
Change rate-limited create asset experience.
Create asset button disabled when asset limit is reached for **Dashboards**, **Tasks**, & **Buckets**
Trying to create a **Check** fails with an error after going though the process of configuring it
Trying to create a **Rule** fails silently with only a console error
Create asset button is always enabled
When user clicks to create asset they are presented with an upgrade overlay
> feat(ui): Enhance resource creation experience when limits are reached

- cmd/influx/query.go
This modifies the query cli to remove the flux runtime dependency and
uses the public http api to execute the query. It then uses flux's csv
decoder to read the raw response.
This removes any dependency on the flux runtime and substantially
reduces the binary size and the startup execution time.
Fixes #19038.
> feat(cmd/influx): modify the query cli to use the http api

- tenant/service.go
- tenant/service_bucket.go
- tenant/service_org.go
- tenant/service_urm.go
- tenant/service_user.go
Tenant services often need to make function calls to other services inside the tenant system. This can cause a problem when a external system needs to inject middleware into the call stack for the secondary system call. For instance when a bucket is created we may need to alert the storage system of the change. To accomplish this we need a way for the org svc to call a middleware influxdb.BucketService that is a tenant type service wrapped with a middleware piece. This is accomplished by allowing the individual services access to the tenant system that was generated. If a middleware is wrapping one of the systems the embedded system can still make internal calls
Closes #19155
> feat(tenant): Allow tenant to be composable and still maintain access across services

- ui/src/templates/components/CommunityTemplatesInstalledList.tsx
Closes #19054 
When you click on a resource you have imported it now links to the appropriate page for that resource. Ex: click on dashboard, go to dashboard
> feat: Template link to resource

- pkger/http_server_template.go
axes some deprecated fields form the apply endpoint. The fields have been deprecated/removed from the swagger docs for quite a while. This is tieing the knot on axing it.
> chore(pkger): axe deprecated fields

- endpoints/service.go
- endpoints/service_test.go
Closes #19081
This PR fixes the endpoint service so that it does not reset all organization secrets when a notification endpoint is created or updated. `SecretService.PutSecrets` call, which that "deletes" all existing secrets, is replaced by `PatchSecrets` herein. A new test was added.
> fix(endpoints): do not reset organization's secrets when an endpoint is created or updated

- ui/src/dashboards/utils/tableGraph.ts
- ui/src/shared/components/tables/TableGraph.tsx
this closes the loop on this issue #19118
essentially, not applying a default sort is super cool, but we also needed to be able to clear existing sorts
> fix: apply feedback from default sort order

- ui/src/onboarding/containers/OnboardingWizardPage.tsx
Closes #18931
remounting caused the onboarding "is there currently user" api request to refire and invalidate product flow. can also be fixed with memoized FCs, but i think the back button isn't the biggest deal in this flow
> fix: decoupling remounting from onboarding state

- ui/src/shared/constants/fluxFunctions.ts
Fixed a typo in aggregate.range description.
> chore(Flux): fix typo in aggregate.range description

- ui/src/dashboards/actions/thunks.ts
Related #18598 
Clicking on a dashboard immediately after it was set created a weird race where the cells and views were still loading from the initial getDashboards call and were setting over the cells and views that were being gotten from the getDashboard function.
Store a reference to the timeOut that by reference of the dashboard ID and clear the timeout if the dashboard is being loaded since the cells and views for the dashboard are already being loaded when the dashboard mounts
> fix(disappearing-cells): wrapping set views and setting cells in a timeout to ensure they get populated

- ui/src/cloud/utils/reporting.ts
- ui/src/perf/actions/index.ts
- ui/src/perf/components/CellEvent.tsx
- ui/src/perf/reducers/index.ts
- ui/src/shared/components/cells/Cell.tsx
Closes #19163 
Just because a dashboard mounts does not necessarily mean a cell visualization renders.  Users can navigate away, refresh the page, close the browser etc.
Do a some work on the frontend and record the delta between cell mounting and a visualization render.  Emit said event on vis render.
> perf: calculate and emit event for cell mount => cell visualized

- CHANGELOG.md
- ui/src/shared/components/TimeSeries.tsx
- ui/src/timeMachine/actions/queries.ts
Closes #19058 
Mutex instance was running one query and passing the results of that query to all queries being resolved in the cell context
Create a hashmap of query's with a mutex as the corresponding value for each cell, and set the results to the hashmap per cell.
> fix(cell-queries-error): created mutex hashmap to resolve queries independently of one another

- ui/src/dashboards/actions/thunks.ts
reverts https://github.com/influxdata/influxdb/commit/4a410559115ba9246ff7c859cc6f73f4afef97ae
causes inability to clone dashboards: https://github.com/influxdata/influxdb/issues/19192
> fix: revert cell disappear pr

- authorizer/bucket.go
- authorizer/bucket_test.go
- cmd/influxd/launcher/launcher.go
- http/api_handler.go
This simply removes a dangling field from the bucket authorizer service implementation.
The field was a URM service, which is no longer consumed by the authorizer type.
> chore(auth): remove unnecessary URM service from Bucket authorizer

- ui/src/dashboards/components/DashboardPage.tsx
- ui/src/shared/components/RefreshingView.tsx
- ui/src/shared/components/TimeSeries.tsx
- ui/src/shared/components/cells/Cell.tsx
Updates `renderID` when dashboard is manually refreshed.  Also, provides correct render cycle when user scrolls.
> perf: ts mount

- dashboard.go
- http/swagger.yml
- pkger/clone_resource.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/dashboard_mosaic.yml
Closes: #19121 
Closes: #19211
Added mosaic type in the backend files, so that the mosaic graph can be saved. 
Co-authored-by: Rose Parker <reparker837@gmail.com>
> feat: added backend for mosaic graph type

- cmd/influxd/launcher/pkger_test.go
- http/swagger.yml
- pkger/clone_resource.go
- pkger/models.go
- pkger/models_test.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
- pkger/testdata/dashboard_params.yml
This PR enables query parameterization through the option `params` within any flux query within a template. The template backend will substitute the params option with the user provided values. This has the following desireable properties:
1. The query is self sufficient, folks can take the query copy past it wherever they want (from template to UI) and things should just work with minimal changes, if any
2. The parameterization is not flux wide, it is purely for addressing the pkger API. This has zero impact on the flux backend and requires no additional dependencies on the flux language and its maintainers
This PR adds support to dashboard queries. The PRs to follow will add support for tasks/checks/etc.
references: #18237
> feat(pkger): add query parameterization

- ui/src/dashboards/actions/thunks.ts
Related #18958
Clicking on a dashboard immediately after it was set created a weird race where the cells and views were still loading from the initial getDashboards call and were setting over the cells and views that were being gotten from the getDashboard function.
Set the cells when loading the dashboard and also wrap the process in a setTimeout so that it gets added to the callstack and should (hopefully) resolve once the initial getDashboards timeouts resolve
Added an e2e test to ensure dashboard cloning doesn't break (#19207).
> fix(flashing-cells): prevent flashing cells by setting all the cell data when the dashboard is loaded

- .circleci/config.yml
It's possible that the apt cache on the circle ci system isn't up to date. Call
apt-get update before any installs.
> fix: run apt-get update before any apt-get install commands

- cmd/influxd/launcher/query_test.go
- flags.yml
- kit/feature/list.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- storage/flux/reader.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/table_test.go
This PR will enable readGroup min/max in OSS behind a feature flag. 
To do:
> feat(query/stdlib): enable read group min max

- CHANGELOG.md
- ui/src/dashboards/selectors/index.test.ts
- ui/src/dashboards/selectors/index.ts
- ui/src/dashboards/utils/getTimezoneOffset.ts
- ui/src/shared/components/RefreshingView.tsx
- ui/src/shared/components/TimeSeries.tsx
- ui/src/timeMachine/components/Vis.tsx
Closes #17877
The problem with this was twofold: 
1. Toggling between timezones in the explorer (VEO / DE) was incorrectly adjusting times when timezones were East of GMT.
2. Toggling between timezones on the dashboard page was not updating the timerange parameters to respect the timezone in dashboards
3. Timerange selections with a timezone were not being respected in data visualization
The solutions to these issues were:
1. Update the offset to be an absolute value rather than a negative, since that was incorrectly adjusting the times (and was leading to confusing assumptions)
2. Updated the timerange being used for the cells (in the TimeSeries component) to account for timezone selections
3. Updated the timeRange that was being passed to the Views (data visualizations) to respect the …
> fix(dashboard-timezone-selection): toggling timezone should update queries timerange to respect timezone selection

- query/logging.go
- query/logging_test.go
Can specify that a key must be present in the query response metadata before
LoggingProxyQueryService logs the query. Will use this in gateway to only log
the query when the connection to queryd fails.
https://github.com/influxdata/idpe/issues/8013
> feat: allow a metadata key to be required for a query to be logged

- CHANGELOG.md
- cmd/influx/dashboard.go
- cmd/influx/main.go
- cmd/influx/telegraf.go
- cmd/influxd/launcher/pkger_test.go
> feat(influx): add support for dashboards

- CHANGELOG.md
- http/onboarding_test.go
- http/swagger.yml
- kv/onboarding.go
- onboarding.go
- tenant/service_onboarding.go
- testing/onboarding.go
We can now allow passwords as an optional argument. This facilitates api only users.
> feat(onboard): allow optional password

- CHANGELOG.md
- http/bucket_service.go
- http/bucket_service_test.go
- tenant/http_server_bucket.go
- tenant/http_server_bucket_test.go
- testing/bucket_service.go
Closes #19179
This PR adds a check for quotation marks in the Bucket name when creating a Bucket. I checked other special symbols and only quotation marks seem to cause a problem for queries.
> fix: add quotation marks to bucket name validation

- cmd/influxd/launcher/pkger_test.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service_models.go
- pkger/testdata/tasks_params.yml
This is a follow up to the work to the PR #19191. This PR adds paremeterization to task queries.
references: #18237
> feat(pkger): parameterize task queries

- CHANGELOG.md
- ui/cypress/e2e/checks.test.ts
- ui/cypress/support/index.js
- ui/package.json
- ui/src/alerting/components/AlertingIndex.tsx
- ui/src/alerting/components/AlertsColumn.tsx
- ui/src/checks/components/ChecksColumn.tsx
- ui/src/notifications/endpoints/components/EndpointsColumn.tsx
- ui/src/notifications/rules/components/RulesColumn.tsx
- ui/yarn.lock
I got annoyed trying to use my keyboard to filter things on the alerts page, so I rage fixed it. You can use `tab` to navigate into the filter text boxes now.
> feat: add tab index to alerts page

- ui/src/cells/actions/creators.ts
- ui/src/cells/reducers/index.ts
- ui/src/dashboards/actions/thunks.ts
- ui/src/views/actions/creators.ts
- ui/src/views/reducers/index.ts
Related to IDPE 8040
Loading dashboards was causing an exponential number of dispatches to trigger for each dashboard, that was then causing the render cycle of each dashboard card to be triggered, making the dashboard loading process slow. This ended up slowing down associated processes on the dashboard list until the operations finished rerendering. More specifically, this caused searching on the initial page load to be slow
Rather than setting dashboard cells and views in a loop and call each one in a separate setTimeout, we are now wrapping the entire looping event in a setTimeout that is storing a reference to the normalized cell and view outside of the loop. Once the iterators resolve and we have a complete array of normalized cells and views, a new action is dispatched that …
> fix(reduce-dashboard-dispatches): reduce rerender cycles in dashboard list

- pkger/service.go
- task_errors.go
previously it had returned and error of 100, but the limit was 500.
The other thing to note is that the error being changed here, is only used within the task kv service implementation.
This was caught during a discussion with the UI team. The 500 limit was updated in pkger so it could take advantage of a full page size on each find call it makes.
> fix(task): update task max page size error message to include an accurate limit

- ui/src/shared/apis/query.test.ts
- ui/src/shared/apis/queryCache.ts
The previous implementation of the Query cache appended the windowPeriod variable regardless of whether it was added as a variableAssignment. These duplicated extern values were causing an issue when trying to run the query
Added a helper function to check whether the variableAssignment has a reference to the windowPeriod before appending it to the list of variables. Added tests to ensure that windowPeriod (and variableAssignments) are deduplicated before passing them in to runQuery
> fix(dedup-window-vars): added condition and tests for ensuring windowVars don't get passed an extern more than once

- cmd/influx/query.go
The `net/http` package default transport will request content gzipped
automatically if `DisableCompression` is set to false (which is the
default). If the transport does it automatically, it will decompress it
automatically which is what was the original intention of the code. But,
if it is requested explicitly, then go will not decompress the data
automatically.
Fixes #18674.
> fix(cmd/influx): query cli should not explicitly request gzipped content

- tsdb/config.go
This reverts commit 9c41e12ee4fac47434f32af93a07a29129951512 from https://github.com/influxdata/influxdb/pull/18158, which changed `DefaultSeriesIDSetCacheSize` to zero. The change caused some users to experience significantly higher memory usage. A future PR will address the original problem with a different solution.
> fix(tsdb): revert disable series id set cache size by default

- tenant/http_client_urm.go
- tenant/http_handler_urm.go
- tenant/http_handler_urm_test.go
We would like to clean and sanitize the data being return from the urm
response to exclude user names as well as oauthID's
> fix(urm): Sanitize urm response output

- ui/src/templates/actions/creators.ts
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplateInstallInstructions.tsx
- ui/src/templates/components/CommunityTemplateInstallInstructionsIcon.tsx
- ui/src/templates/components/CommunityTemplateInstallerOverlay.tsx
- ui/src/templates/components/CommunityTemplateOverlay.tsx
- ui/src/templates/components/CommunityTemplateOverlayContents.tsx
- ui/src/templates/containers/TemplatesIndex.tsx
- ui/src/templates/reducers/index.test.ts
- ui/src/templates/reducers/index.ts
- ui/src/types/templates.ts
Closes #19177 
- Renames files to be a little more clear about what they do
- `CommunityTemplateContents` => `CommunityTemplateOverlayContents`
- `CommunityTemplatesInstallerOverlay` => `CommunityTemplatesOverlay`
- `CommunityTemplatesName` => `CommunityTemplatesInstallInstructions`
- Removes references to `CommunityTemplateOverlay` in `TemplateIndex`
- Changes default exports => named exports
- Renames redux model concept `communityTemplateToInstall` => `stagedCommunityTemplate` (idea from Alex Paxton)
> refactor: clean up community templates ui

- ui/src/dashboards/components/DashboardPage.tsx
- ui/src/perf/actions/index.ts
- ui/src/perf/components/CellEvent.tsx
- ui/src/perf/reducers/index.ts
- ui/src/shared/components/DashboardRoute.tsx
Closes influxdata/idpe#8152
We were not calculating the time it took to fetch all dashboard resources on initial render
Time the difference between when a dashboard is visited -> all the data is fetched (including variables) -> and a dashboard mounting.  This, combined with the `Cell Render Cycle` calculation can give us a decent approximation of how long it takes our users to visualize their data.  
This PR also removes the concept of `renderID`.  Turns out it's an unnecessary complication.
> perf: calculate and event dashboard visit => dashboard mount times

- cmd/chronograf-migrator/dashboard.go
- cmd/influx/transpile.go
- query/influxql/compiler.go
- query/influxql/end_to_end_test.go
- query/influxql/spectests/testing.go
- query/influxql/transpiler.go
- query/influxql/transpiler_test.go
- query/stdlib/influxdata/influxdb/v1/databases.go
Updating the DBRP Mapping Service to the v2 version within the flux `v1` packages dependencies.
The interface is almost identical. Save a few changes to Find and the obvious V2 suffix.
Moving to v2 will allow me to use the new DBRP mapping service client. Meaning the DBRP metadata can be retrieved from a remote service instead of directly from the kv store.
Update as this now adds it to more places:
- Query Dependencies
- Transpiler
> chore(query): use dbrp v2 service in flux influx.v1 dependencies

- coordinator/points_writer.go
- services/httpd/handler.go
- services/httpd/service.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/shard.go
- tsdb/store.go
This patch adds the "values written" stat to influxdb.
> feat: Collect values written stats

- authz.go
Only check the `MATCHER_BEHAVIOR` flag once in `init` rather than every match call, since it was unnecessary and causing tests to break.
> fix(auth): use init to read envvar once

- ui/cypress/e2e/communityTemplate.test.ts
- ui/src/templates/components/CommunityTemplateHumanReadableResource.tsx
- ui/src/templates/components/CommunityTemplatesInstalledList.tsx
- ui/src/templates/components/CommunityTemplatesResourceSummary.tsx
- ui/src/templates/containers/CommunityTemplates.scss
- ui/src/templates/containers/CommunityTemplatesIndex.tsx
Closes #19278 
Closes #19279 
- Polish appearance of Installed Templates table:
- Resources + types rendered in tinier and collapsible table
- Changed github link to button to conserve space
- Give each column a set width to prevent table jitter
- Make browse/lookup buttons & inputs large size
- Attempted to update the version of Clockface to 2.3.3 (latest) and saw too many things breaking to safely make that change, so it was reverted
> feat(ui): templates polish

- tsdb/engine/tsm1/reader.go
- tsdb/engine/tsm1/reader_test.go
- tsdb/engine/tsm1/writer.go
This PR adds tests and benchmarks for verifyVersion() and refactors verifyVersion() to call only `binary.Read()`.  This saves some lines of code and make the code clearer and easier to understand.
> refactor: Simplify verifyVersion()

- ui/cypress/index.d.ts
- ui/cypress/support/commands.ts
- ui/src/buckets/actions/thunks.ts
- ui/src/notifications/rules/actions/thunks.ts
- ui/src/resources/constants/index.ts
Closes #18684 
User was only seeing 20 of their notification rules.
Increase the limit to max (100). This should unblock the user until...
Dedicate resources to pagination throughout the UI.
> fix: increase notification rule limit

- flags.yml
- kit/feature/list.go
- tenant/middleware_urm_auth.go
- tenant/middleware_urm_auth_test.go
> fix: restrict urm listing of a resource to members of org owning said resource
