influxdata/influxdb

ui/src/shared/constants/fluxFunctions.ts
=> fix(fluxFunctions): fix typo in lastIndex

cmd/influx/pkg.go
=> chore(influx): replace all mentions of packages with templates in the CLI

cmd/influx/config.go
=> chore(influx): refactor influx config delete cmd to for consistency and update usage

cmd/influxd/launcher/launcher.go, kit/cli/viper.go, kit/cli/viper_test.go
@russorat's keen eyes picked this one up 👍
=>  feat(influx): fixup config file env var naming and add support for config directory

ui/src/cloud/utils/reporting.ts
sends all of our user events we're instrumenting for new features off to GA
=> feat: push it all to GA

ui/yarn.lock
Keep yarn.lock in sync with package.json
=> chore(ui): update prettier in yarn.lock

cmd/influx/main.go, cmd/influxd/launcher/pkger_test.go, pkger/service_models.go, variable.go
=> fix(pkger): fixup updates for variables where updates from selected were skipped

ui/package.json, ui/yarn.lock
Update to latest version of giraffe
=> chore(ui): update giraffe

CHANGELOG.md, etc/config.sample.toml, services/httpd/config.go, services/httpd/handler.go
=> fix(httpd): add user authentication for prometheus remote read api

ui/src/alerting/utils/history.ts, ui/src/alerting/utils/statusEvents.ts, ui/src/cloud/utils/reporting.ts, ui/src/external/monaco.flux.server.ts, ui/src/notebooks/context/query.tsx, ui/src/shared/components/TimeSeries.tsx, ui/src/timeMachine/actions/queries.ts, ui/src/timeMachine/apis/queryBuilder.ts, ui/src/variables/utils/ValueFetcher.ts
The idea is to record and establish a KPI for queries made by the UI per session.
=> feat(reporting): Add reporting to instances of the UI running queries for the user

cmd/influx/pkg.go
=> chore(influx): update influx stacks rm cmd printout

tsdb/engine/tsm1/engine.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/index_test.go, tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/partition.go
=> perf(tsi1): batch write tombstone entries when dropping/deleting

cmd/influx/config.go, cmd/influx/config/config.go, cmd/influx/config/config_test.go, cmd/influx/config_test.go
=> fix(influx): stop influx set command forcing url

tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go
=> fix:  gracefully handle errors when creating snapshots

tsdb/store.go
Forward port https://github.com/influxdata/influxdb/pull/17254
=> fix(tsi1): wait deleting epoch before dropping shard

ui/cypress/e2e/dashboardsView.test.ts, ui/cypress/e2e/explorer.test.ts, ui/cypress/support/commands.ts, ui/src/shared/components/EmptyGraphError.tsx
=> test: visualize cell data with variables

cmd/influxd/launcher/launcher.go
=> feat: allow restricting TLS version and ciphers

cmd/influxd/launcher/launcher.go, label/http_handler.go
We will now be able to embed the label mappings apis into other services
=> feat: add a embedded handler for label service api

ui/cypress/e2e/dashboardsView.test.ts, ui/src/dashboards/components/DashboardHeader.tsx
=> test: Add variable control test

cmd/influxd/launcher/query_test.go, storage/flux/reader.go, storage/flux/table.gen.go, storage/flux/table.gen.go.tmpl, storage/flux/table.go, storage/flux/table_test.go
=> fix(storage/flux): the count aggregate will fill in zero values instead of null

ui/cypress/e2e/telegrafs.test.ts, ui/src/telegrafs/components/CollectorCard.tsx
=> test: add telegraf tests

cmd/influxd/launcher/query_test.go, storage/reads/aggregate_resultset.go, storage/reads/array_cursor.gen.go, storage/reads/array_cursor.gen.go.tmpl, storage/reads/array_cursor.go, storage/reads/array_cursor_test.go, storage/reads/group_resultset.go, storage/readservice/store.go
=> feat: push down window last

flags.yml, kit/feature/list.go, query/stdlib/influxdata/influxdb/rules.go
This is in preparation for influxdata/flux#2944.
=> feat(flags): add a feature flag for memory optimized schema mutation

cmd/influx/template.go, cmd/influx/template_test.go, cmd/influxd/launcher/pkger_test.go, http/swagger.yml, pkger/http_server_packages_deprecated_test.go, pkger/http_server_template_test.go, pkger/models.go, pkger/models_test.go, pkger/parser_models.go, pkger/parser_test.go, pkger/service_models.go, pkger/service_test.go, ui/src/templates/containers/CommunityTemplatesIndex.tsx
=> chore(pkger): drop mentions of pkgs from within service model

ui/src/shared/constants/fluxFunctions.ts
Update `fluxFunctions.ts` with updates for Flux 0.70
=> chore(flux): add flux 0.70 function updates

ui/cypress/e2e/explorer.test.ts, ui/cypress/e2e/nav.test.ts, ui/cypress/e2e/telegrafs.test.ts, ui/src/alerting/components/AlertingIndex.tsx, ui/src/dataExplorer/components/DataExplorerPage.tsx, ui/src/me/containers/MePage.tsx, ui/src/onboarding/containers/SigninPage.tsx, ui/src/organizations/components/CreateOrgOverlay.tsx, ui/src/organizations/components/OrgHeader.tsx, ui/src/pageLayout/components/OrgSwitcherOverlay.tsx, ui/src/settings/components/LoadDataHeader.tsx, ui/src/settings/components/SettingsHeader.tsx, ui/src/tasks/components/TasksHeader.tsx
Closes influxdata/idpe#7338
Closes influxdata/idpe#7339
=> test(e2e): nav bar

cmd/chronograf-migrator/main.go, cmd/influx/template.go, cmd/influx/template_test.go, cmd/influxd/launcher/pkger_test.go, pkger/doc.go, pkger/http_remote_service.go, pkger/http_server_packages_deprecated.go, pkger/http_server_packages_deprecated_test.go, pkger/http_server_stack.go, pkger/http_server_template.go, pkger/http_server_template_test.go, pkger/models.go, pkger/models_test.go, pkger/parser.go, pkger/parser_models.go, pkger/parser_test.go, pkger/service.go, pkger/service_auth.go, pkger/service_logging.go, pkger/service_metrics.go, pkger/service_models.go, pkger/service_test.go, pkger/service_tracing.go
=> chore(pkger): finalize adoption of templates naming convention

CHANGELOG.md, cmd/influxd/launcher/pkger_test.go, http/swagger.yml, pkger/models.go, pkger/service_models.go, pkger/service_test.go
note: ignore whitespaces 😬 
closes: #18804
=> feat(pkger): extend template diff types with kind

ui/src/templates/actions/creators.ts, ui/src/templates/components/CommunityTemplateContents.tsx, ui/src/templates/components/CommunityTemplateImportOverlay.tsx, ui/src/templates/components/CommunityTemplateInstallerOverlay.tsx, ui/src/templates/components/CommunityTemplateListGroup.tsx, ui/src/templates/components/CommunityTemplateListItem.tsx, ui/src/templates/containers/CommunityTemplatesIndex.tsx, ui/src/templates/reducers/index.ts, ui/src/templates/selectors/index.ts
Closes #18615 
Allows users to select resources to install. Shows proper resource counts based on user's actions.
=> feat(flagged-community-templates): allow user to select resources to install

cmd/influxd/launcher/query_test.go, storage/flux/table.gen.go, storage/flux/table.gen.go.tmpl
=> fix: window tables are empty if cursor is empty

ui/src/shared/constants/fluxFunctions.ts
Related to #18809 
Update `fluxFunctions.ts` with new functions and parameter options available in Flux 0.71.
=> chore(flux): add flux 0.71 function updates

ui/src/templates/components/CommunityTemplateListGroup.tsx, ui/src/templates/components/CommunityTemplateListItem.tsx, ui/src/templates/containers/CommunityTemplates.scss
=> refactor(ui): style templates checkboxes

go.mod, go.sum
Includes patch fix to negative window every values
=> chore(flux): update Flux to v0.71.1

pkger/http_server_packages_deprecated.go, pkger/http_server_template.go, pkger/http_server_template_test.go
=> chore(pkger): ensure all diff and summary resource collections are not null

cmd/influx/main.go, cmd/influx/template.go, cmd/influx/write.go, pkger/service.go, pkger/service_test.go
=> fix(pkger): fulfill pagination for tasks/checks/not rules for export all

cmd/influxd/launcher/query_test.go, flags.yml, kit/feature/list.go, query/stdlib/influxdata/influxdb/rules.go, query/stdlib/influxdata/influxdb/rules_test.go
=> feat: remove feature flags for first and last pushdowns

authorization/storage_authorization_test.go
Notes:
Refactored code such that each test verifies 10 authorizations at a time.
Added test for DELETE
=> feat(authorization): Added tests for Read, Update, and Delete in Authorization

ui/cypress/e2e/telegrafs.test.ts, ui/src/cloud/components/CheckoutButton.tsx, ui/src/shared/components/CloudUpgradeButton.tsx, ui/src/shared/components/CloudUpgradeNavBanner.tsx, ui/src/telegrafs/components/TelegrafConfig.tsx
Closes #18879
Closes influxdata/idpe/issues/7851
=> fix: telegraf config overlay display and cloud links

CHANGELOG.md
=> chore(changelog): updates for beta-14

ui/src/shared/copy/notifications.ts, ui/src/templates/api/index.ts, ui/src/templates/components/CommunityTemplateContents.tsx, ui/src/templates/components/CommunityTemplateImportOverlay.tsx, ui/src/templates/components/CommunityTemplateInstallerOverlay.tsx, ui/src/templates/components/CommunityTemplateListItem.tsx, ui/src/templates/components/CommunityTemplatesActivityLog.tsx, ui/src/templates/containers/CommunityTemplatesIndex.tsx, ui/src/templates/utils/index.ts
=> feat(flagged - community templates): install templates

ui/cypress/e2e/tokens.test.ts, ui/src/authorizations/components/AllAccessTokenOverlay.tsx, ui/src/authorizations/components/TokenList.tsx, ui/src/authorizations/components/TokenRow.tsx
test for sort by name
edit description
add all access token
Closes #
=> test: Token tests multiple

CHANGELOG.md, cmd/influx/template.go
=> chore(pkger): drop deprecated influx pkg command tree

ui/cypress/e2e/buckets.test.ts
Closes #idpe#7233
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/7233
=> test: adding asc test for buckets retention

ui/src/notebooks/components/header/Submit.tsx, ui/src/timeMachine/components/SubmitQueryButton.test.tsx, ui/src/timeMachine/components/SubmitQueryButton.tsx
=> fix: query button flashes

ui/cypress/e2e/variables.test.ts, ui/cypress/fixtures/data-for-variable.json, ui/cypress/support/commands.ts, ui/package.json, ui/src/shared/components/ImportOverlay.tsx, ui/yarn.lock
=> test: Upload variable file test

ui/src/shared/copy/notifications.ts, ui/src/templates/actions/creators.ts, ui/src/templates/api/index.ts, ui/src/templates/components/CommunityTemplatesActivityLog.tsx
What it says on the tin ☝️ 
Adds a delete button to the UI.
**Reminder:** This is behind a feature flag on prod.
=> feat(community-templates flagged): add delete functionality to UI

ui/src/timeMachine/actions/index.ts
=> fix: No longer query tags on advanced builder

ui/src/shared/utils/options.test.ts, ui/src/shared/utils/options.ts
Closes https://github.com/influxdata/influxdb/issues/18834.
=> feat: typescript api for editing flux options

storage/flux/window.go
When splitting windows into their own individual tables, do not wait for
empty tables to be read. Empty tables may never be read so waiting for
them can result in a deadlock.
This was found while writing a test case for in progress work and so a
test case for this condition will follow in a future commit.
=> fix(storage/flux): do not wait for empty tables in the windower

ui/src/notebooks/components/AddButtons.tsx, ui/src/notebooks/components/header/PresentationMode.tsx, ui/src/notebooks/components/header/Submit.tsx, ui/src/notebooks/components/minimap/MiniMapToggle.tsx, ui/src/notebooks/components/panel/MovePanelButton.tsx, ui/src/notebooks/components/panel/RemovePanelButton.tsx, ui/src/notebooks/pipes/Visualization/DashboardList.tsx, ui/src/notebooks/pipes/Visualization/ExportVisualizationButton.tsx, ui/src/timeMachine/components/SubmitQueryButton.tsx
- Every classname prefixed with `flows-` doesn't carry any styles and just exists for GA to track
=> feat(flows): add classnames and custom events for GA tracking

flags.yml, kit/feature/list.go, query/stdlib/influxdata/influxdb/rules.go, query/stdlib/influxdata/influxdb/rules_test.go, query/stdlib/testing/testing.go
Updated flags.yml to include a rule for mergeFilter and ran make flags to generate code for the flag. Added unit tests to test flag off and on. Made sure that end_to_end_test.go ran and passed the changed made in flux.
=> feat(query/stdlib): update flags.yml with mergleFilterRule and add mergeFilterRule to rules.go with corresponding unit tests.

CHANGELOG.md
=> chore(changelog): updates for beta-15

cmd/influxd/launcher/query_test.go, query/stdlib/testing/testing.go, storage/flux/table_test.go
=> feat(storage/flux): add tests for min/max pushdowns

storage/flux/table.gen.go, storage/flux/table.gen.go.tmpl, storage/flux/table_test.go
=> feat: enable first and last for group window transpose

ui/src/cloud/components/RateLimitAlert.tsx, ui/src/dashboards/components/DashboardPage.tsx
Removes stretched upgrade button from dashboards in Cloud.
=> fix(ui): dashboard upgrade

ui/src/cloud/utils/reporting.ts
Closes #19036
App Metrics isn't reporting the current version reporting of the app
Added the current version as a tag in app-metrics
=> chore(reporting-version): added version reporting to events

http/swagger.yml
=> fix(swagger): update nullable fields in PATCH /stacks/:stack_id

flags.yml, kit/feature/list.go, kv/task.go
This feature flag has been enabled for over a month in the production and have not seen any new issues arise
=> chore: Remove urmFreeTask feature flag

cmd/influxd/launcher/pkger_test.go, pkger/service.go, pkger/service_test.go
=> fix(pkger): update stacks with snapshot of all prevoius event resources

ui/src/templates/components/CommunityTemplateName.tsx
Closes #19068
We are adding a note for our users that there might be more steps to take to get their templates fully working
=> feat: add note for additional scripts

cmd/influxd/launcher/launcher.go, kv/task_test.go, task/backend/analytical_storage_test.go, task/servicetest/servicetest.go, tenant/http_server_onboarding_test.go, tenant/service.go, tenant/service_onboarding.go, tenant/service_onboarding_test.go, tenant/service_org.go
After the introduction of the tenant system we need to switch the testing frameworks
to use it instead of the old kv system
=> chore: update task tests to use the tenant service

ui/cypress/e2e/dashboardsView.test.ts
Closes #19193
This PR addresses the issue of no test coverage for cloning dashboard cells
=> chore(clone-cell-test): added an e2e test for cloning cells

tenant/http_client_urm.go, tenant/http_client_user.go, tenant/http_handler_urm.go, tenant/http_handler_urm_test.go, tenant/http_server_onboarding.go, tenant/http_server_user.go, tenant/service.go
This PR adds a new URM Client service to tenant package (code was migrated from the http package)
=> feat: add urm client to tenant package

cmd/influxd/launcher/query_test.go, flags.yml, kit/feature/list.go, query/stdlib/influxdata/influxdb/rules.go, query/stdlib/influxdata/influxdb/rules_test.go, query/stdlib/testing/testing.go
=> feat: enable pushdowns for sum, count, min, and max by default

.circleci/config.yml
=> fix: use backslash for line breaker

pkger/doc.go
=> chore(pkger): update doc.go

ui/src/resources/constants/index.ts
=> chore(limit): increasing limit to 200

ui/src/resources/constants/index.ts
Reverts influxdata/influxdb#19238
=> revert: "chore(limit): increasing limit to 200"

tenant/http_client_urm.go, tenant/http_handler_urm.go, tenant/http_handler_urm_test.go
This reverts commit 6d61c3cd73ee80092812cb968413931ff7b39844.
=> revert(urm): Sanitize urm response output (#19242)

ui/src/shared/constants/fluxFunctions.ts
Updates fluxFunctions.ts to include all new functions from Flux 0.71 - 0.80.
=> chore(flux): update fluxFunctions.ts for Flux 0.80.0

ui/cypress/e2e/communityTemplate.test.ts, ui/src/templates/components/CommunityTemplateHumanReadableResource.tsx, ui/src/templates/components/CommunityTemplateImportOverlay.tsx, ui/src/templates/components/CommunityTemplateOverlayContents.tsx, ui/src/templates/components/CommunityTemplatesInstalledList.tsx, ui/src/templates/containers/CommunityTemplatesIndex.tsx
Closes #18242 
This is the event and metric tracking for the community template UI. This will help us track in google analytics
=> feat: Eventing and metrics adding to the community templates

dashboard.go, http/swagger.yml, pkger/clone_resource.go, pkger/parser.go, pkger/parser_models.go, pkger/parser_test.go, pkger/service_test.go, pkger/testdata/dashboard_band.yml
=> feat(bandChart): Add backend

ui/src/notebooks/NotebookVariables.scss, ui/src/notebooks/components/panel/InsertCellButton.scss, ui/src/notebooks/components/panel/InsertCellButton.tsx, ui/src/notebooks/components/panel/NotebookPanel.tsx, ui/src/notebooks/style.scss
Closes #19209 
- Add cell button is hard to find, especially for first-time users
- Use a vertical line with nodes instead of horizontal dividers
- Display `+` button on the line
- Last `+` button is always visible
- Node glows blue when cell is in `focus` state
=> feat(flows): improve add cell button ux

http/org_service.go, http/swagger.yml, kv/org.go, tenant/http_server_org.go, testing/organization_service.go
Closes #19319
fix for https://github.com/influxdata/influxdb/issues/19319#issuecomment-673512362
=> fix(api/orgs): (API-design-issue) FindOptions for orgs

cmd/influxd/launcher/engine.go, delete.go, http/delete_handler.go, mock/delete.go, storage/engine.go, storage/engine_test.go, storage/wal/wal.go, storage/wal/wal_test.go, tsdb/tsm1/engine_delete_prefix.go, tsdb/tsm1/engine_delete_prefix_test.go, tsdb/tsm1/engine_test.go
=> feat(influxql): Implement DELETE & DROP MEASUREMENT

ui/cypress/e2e/communityTemplates.test.ts, ui/src/templates/actions/creators.ts, ui/src/templates/components/CommunityTemplateImportOverlay.tsx, ui/src/templates/containers/CommunityTemplatesIndex.tsx, ui/src/templates/reducers/index.test.ts, ui/src/templates/reducers/index.ts, ui/src/templates/utils/index.test.ts, ui/src/templates/utils/index.ts, ui/src/types/templates.ts
Closes # https://github.com/influxdata/idpe/issues/8325
Removes need to install from our github community templates repo
=> chore(community-templates): remove github file restriction

.github/PULL_REQUEST_TEMPLATE.md
Add checkbox to remind to feature flag api changes
=> chore: require flagging in pull request template

ui/src/resources/constants/index.ts, ui/src/tasks/actions/thunks.ts
=> fix: increase task limit to 500

go.mod, go.sum, query/control/controller.go, query/mock/service.go, query/promql/internal/promqltests/go.mod, query/promql/internal/promqltests/go.sum, query/stdlib/testing/testing.go, task/backend/executor/support_test.go
=> build(flux): update Flux to v0.82.2

.circleci/config.yml
=> chore: add grace nightly job and build for oss

.circleci/config.yml
Closes #
Allows test results to display within `test_results` directory in CircleCi.
=> chore: fix build configuration

ui/cypress/e2e/communityTemplates.test.ts, ui/src/templates/components/CommunityTemplateReadMeOverlay.tsx, ui/src/templates/components/CommunityTemplatesInstalledList.tsx
Closes #8326
This will have a read me open when you press the community template button
=> feat: Adding the new overlay read me

releng/unit-tests/Dockerfile
Closes # https://github.com/influxdata/plutonium/issues/3205
=> chore: do not use alpine image, it does not have gcc compiler.

go.mod, go.sum
=> chore: Backport influxql update

.circleci/config.yml
=> chore: remove algo-w branch from nightly builds

pkg/fs/fs.go, pkg/fs/fs_unix.go
Making influxd compilable on Window
=> fix(InfluxDB 2): Making influxd compilable on Windows

authorizer/authorize.go, bucket.go, kv/bucket.go, mock/bucket_service.go, task/backend/analytical_storage_test.go, tenant/storage_bucket.go
Closes #
Description of issue and what this PR seeks to achieve are detailed within this issue: https://github.com/influxdata/influxdb/issues/19547
=> chore: remove hardcoded constants for ids

.circleci/config.yml, .goreleaser.yml, Makefile, cmd/influxd/launcher/launcher.go, scripts/influxdb.service, scripts/init.sh, scripts/logrotate, scripts/post-install.sh, scripts/post-uninstall.sh, scripts/pre-install.sh
- Update CIrcleCI configuration to start release process on an RC build
- Update .goreleaser.yml:
- Start building armel and armhf binaries and rpm and debian packages.
- Generate sha256 checksum file.
- launcher.go: do not use `max` module to escape integeroverflow problem for armel and armhf builds
- Start using `v0.142.0` of goreleaser
- Added pre and post install/uninstall scripts for rpm amd deb packages
Closes # https://github.com/influxdata/influxdb/issues/19473
=> chore(packaging): build rpm and deb packages

cmd/influx_inspect/export/export.go
When applied, this patch will add the -lponly flag to the export command
which instructs influx_inspect to only output line protocol without
comments and other out-of-band data.
Addresses: https://github.com/influxdata/influxdb/issues/19367
=> feat: Add -lponly flag to export sub-command

tsdb/index/tsi1/log_file.go
```
fix(tsi1): Acquire a lock when modifying measurement map
This patch protects an internal map for concurrent use.
(*LogFile).Writes() method calls
(*LogFile).createMeasurementIfNotExists() which writes to a shared map.
(*LogFile).Writes() acquires a read-lock which leaves
createMeasurementIfNotExists() open to concurrent writes to its shared
map.
This commit adds the ExecEntries method to the *LogFile type so that we
can properly lock calls to (*LogFile).appendEntry() using defer.
(*LogFile).ExecEntries() is used to mostly replace the body of
(*LogFile).Writes() and incurs another function call since ExecEntries()
can't be inlined.  Below is the output of build with "-m -m -m" gcflags:
./log_file.go:1076:6: cannot inline (*LogFile).ExecEntries: unhandled op DEFER
The performace impact …
```
=> fix: lock map before writes

tsdb/index/tsi1/log_file.go
=> chore: Merge pull request #19420 from influxdata/fix-unlocked-map-access

ui/cypress/e2e/communityTemplates.test.ts, ui/src/templates/components/CommunityTemplateResourceContent.tsx, ui/src/templates/components/CommunityTemplatesResourceSummary.tsx
this is a reproduction of: https://github.com/influxdata/ui/commit/d6c9186999f4f35568b4556585367302fc422e40
=> test(community-templates): update e2e tests to be less coupled to real templates

tsdb/index/tsi1/log_file.go
=> fix: Merge pull request #19420 from influxdata/fix-unlocked-map-access

.circleci/config.yml, .goreleaser.yml
- add `signs` section to goreleaser to sigh all of the artifacts
- add importing of the private key that is needed to sign p ackages
Closes # https://github.com/influxdata/influxdb/issues/19372
=> chore(build): packages signing

.circleci/config.yml, bolt/bbolt.go, bolt/id.go, bolt/kv.go, bolt/metrics.go, chronograf/bolt/base.go, chronograf/bolt/build.go, chronograf/bolt/change_interval_to_duration.go, chronograf/bolt/client.go, chronograf/bolt/config.go, chronograf/bolt/dashboards.go, chronograf/bolt/layouts.go, chronograf/bolt/mapping.go, chronograf/bolt/org_config.go, chronograf/bolt/organizations.go, chronograf/bolt/servers.go, chronograf/bolt/sources.go, chronograf/bolt/users.go, chronograf/server/server.go, go.mod, go.sum
=> chore: update circleci config to use golang:1.15 images

ui/.eslintrc.js, ui/src/cloud/apis/demodata.ts, ui/src/dashboards/components/dashboard_index/DashboardCards.tsx, ui/src/shared/components/EmptyQueryView.tsx, ui/src/variables/utils/hydrateVars.ts
Turns on the eslint rule `curly`, forcing curly braces.
=> chore: update eslint to force curly braces

services/httpd/handler.go
This PR also allows PATCH requests for clients running from web browsers. It enhances CORS handling that was already approved in #18410.
=> fix(CORS): allow PATCH

releng/unit-tests/Dockerfile
since it is not an alpine image, apk command is no available. Using apt-get instead
Closes #
=> chore: do not use apk command

.circleci/config.yml, .goreleaser.yml
=> chore: revert signature changes to goreleaser

SECURITY.md
Also edit sentence and fix punctuation.
=> chore: Update table of supported security updates

CHANGELOG.md
=> chore(changelog): update changelog for rc0

.circleci/config.yml
=> chore(circleci): change beta to rc

CHANGELOG.md
=> chore: update CHANGELOG for 1.8.3GA

flags.yml, kit/feature/list.go, tenant/middleware_urm_auth.go
=> chore: clean old feature flags

ui/src/writeData/components/telegrafPlugins/win_eventlog.md
duplicates  https://github.com/influxdata/telegraf/pull/8209/files
Closes #
=> fix(writeData): fixing win_eventlog readme

cmd/influx/task.go
=> fix(influx): update default value of list tasks influx command to 100

.circleci/config.yml, .goreleaser.yml
=> chore: added sign section to goreleaser

CHANGELOG.md
=> chore(changelog): changelog updates for rc1

task/backend/executor/limits_test.go, task/backend/middleware/middleware_test.go, task/servicetest/servicetest.go
=> chore: clean todo

go.mod, go.sum, query/promql/internal/promqltests/go.mod, query/promql/internal/promqltests/go.sum
=> build(flux): update Flux to v0.90.0

ui/src/timeMachine/constants/queryBuilder.ts
=> fix(timeMachine): change derivative to 1s

tsdb/engine/tsm1/engine.go
Backport PR https://github.com/influxdata/influxdb/pull/19691 to 1.8
Closes #19761
=> feat: allow disable compaction per shard

services/collectd/service.go
Prior to this commit, we had our own recursive file walker which
required a condition based on if s.Config.TypesDB pointed to a directory
or a regular file.
This commit replaces our own readdir() with filepath.Walk() and treats
recursing directories and loading one file as a single case.  This
simplifies the code quite a bit.
=> refactor: Use filepath.Walk

cmd/influxd/upgrade/upgrade.go
Fixing grammar errors and typos in the influxd upgrade help
=> fix(upgrade): fixing typos and grammar errors

CHANGELOG.md
=> chore: CHANGELOG updates for v2.0.0-rc.2

.goreleaser.yml, cmd/influx/setup.go, cmd/influxd/upgrade/setup.go, onboarding.go
Please see https://github.com/influxdata/influxdb/issues/19755 for more details.
Closes # https://github.com/influxdata/influxdb/issues/19755
=> fix(build): building arm 6

FUZZ.md
Remove section on continuous fuzzing as we're pausing that work.
=> docs: Update FUZZ.md

ui/src/Logout.tsx, ui/src/store/configureStore.ts
This brings over the redux clear during log out changes to influxdb
=> fix: clear logout

ui/package.json, ui/yarn.lock
Imports the latest version of the flux-lsp
=> build(ui): import flux-lsp v0.5.21

cmd/influxd/upgrade/config_test.go, kit/io/limited_read_closer_test.go, storage/reads/influxql_predicate.go, v1/services/storage/predicate_influxql.go, v1/services/storage/store.go
=> fix: tag keys push down

CHANGELOG.md
=> chore: Update CHANGELOG for rc3

cmd/influxd/launcher/query_test.go, flags.yml, go.mod, go.sum, kit/feature/list.go, query/stdlib/influxdata/influxdb/operators.go, query/stdlib/influxdata/influxdb/rules.go, query/stdlib/influxdata/influxdb/rules_test.go, query/stdlib/influxdata/influxdb/source.go, query/stdlib/influxdata/influxdb/source_test.go, query/stdlib/testing/testing.go, query/storage.go, storage/flux/reader.go, storage/flux/table.gen.go, storage/flux/table.gen.go.tmpl, storage/flux/table.go, tsdb/engine/tsm1/array_cursor.gen.go, tsdb/engine/tsm1/array_cursor.gen.go.tmpl, tsdb/engine/tsm1/array_cursor_test.go, tsdb/engine/tsm1/engine_test.go
=> feat: enable window pushdowns

.goreleaser.yml
=> chore: do not build arm arch

ui/src/tasks/actions/thunks.ts
=> fix(ui): Cloning tasks makes actions shared in task list view

CHANGELOG.md
=> chore: update CHANGELOG for rc4

ui/package.json, ui/yarn.lock
=> build(ui): Upgrade flux-lsp-browser to v0.5.22

cmd/influxd/upgrade/security.go, cmd/influxd/upgrade/security_test.go
=> fix: updating v1 auth description

.circleci/config.yml, CHANGELOG.md
=> chore: CHANGELOG updates for GA

.circleci/config.yml, CHANGELOG.md
=> chore: Update CHANGELOG

CHANGELOG.md
=> chore: update CHANGELOG for v2.0.1

CHANGELOG.md
This will hopefully save some annoyance untangling the changes for future releases.
=> chore: sync CHANGELOG from 2.0.1

CHANGELOG.md, cmd/influxd/upgrade/security.go, cmd/influxd/upgrade/security_test.go, cmd/influxd/upgrade/upgrade.go
=> feat(cmd/influxd): warn if auth wasn't enabled and users were upgraded

ui/package.json, ui/yarn.lock
Upgrade to [Flux LSP v0.5.23](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.23)
=> build(ui): upgrade flux-lsp-browser to v0.5.23

.circleci/config.yml
=> chore: remove lint-feature-flag job from OSS

.goreleaser-nightly.yml
=> chore: update goreleaser nightly to be inline with daily/release builds

CHANGELOG.md
=> chore: CHANGELOG updates for v2.0.2

.goreleaser-nightly.yml, .goreleaser.yml, scripts/post-install.sh
=> chore: use influxdb2 name for packaging

.circleci/config.yml
This PR removes nightly and e2e hourly jobs from circleci,
=> chore: remove nightly and hourly e2e jobs

ui/package.json
=> chore(ui): bump version in package.json to prep for release

CHANGELOG.md, models/points.go, models/points_test.go
=> fix(models): grow tag index buffer if needed

CHANGELOG.md, http/middleware.go, http/middleware_test.go
=> fix(http): don't log bodies of V1 write requests

CHANGELOG.md, cmd/influxd/upgrade/config.go, cmd/influxd/upgrade/config_test.go, cmd/influxd/upgrade/upgrade.go
Closes #20105
Backports #20110
=> feat(cmd/influxd): use a better default for upgraded V2 config, and allow users to override it

ui/package.json, ui/yarn.lock
[Flux LSP `v0.5.24`](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.24)
=> build: Upgrade to flux-lsp-browser v0.5.24

services/httpd/handler.go, services/httpd/service.go
=> fix: Shutdown http servers before closing httpd service

services/httpd/handler.go, services/httpd/service.go
=> fix: Properly shutdown multiple http servers

services/httpd/service.go
Once applied, this patch will use the same net/http.Server value to
handle all http requests.
This simplifies cleanly shutting down the server.
Closes #
=> fix: Use a single http server

CHANGELOG.md, kv/migration/all/0013_repair-DBRP-owner-and-bucket-IDs.go, kv/migration/all/0014_reindex-DBRPs.go, kv/migration/all/all.go
Closes #20176 
Backports #20168
=> fix(kv): add KV migration to repair DBRP mappings broken by schema change

CHANGELOG.md, v1/coordinator/points_writer.go, v1/services/meta/data.go
Closes #20198
Forward-ports #20118
=> fix(v1): optimize shard lookup in groups containing only one shard

coordinator/points_writer.go, services/meta/data.go
Closes #20199
Forward-ports #20118 to `1.x`
=> feat: Optimize shard lookups in groups containing only one shard

.circleci/config.yml
=> chore(build): add grace test runs to PR checks (#20210)

CHANGELOG.md, cmd/influxd/launcher/storage_test.go, http/delete_handler.go, http/delete_test.go, predicate/predicate.go, storage/engine.go, tsdb/index.go, tsdb/store.go
Closes #20237 
Backports #20236
=> feat(tsdb): Implement delete with predicate.

CONTRIBUTING.md, README.md
Documentation fix for main READMEmd
=> docs: add clarity to source build instructions

CHANGELOG.md, cmd/influx/setup.go
Closes #20232 
Backports #20155
=> fix: various improvements to setup command

services/httpd/response_writer.go
JSON marshaling errors should be returned properly formatted in JSON
like other errors. 
Closes https://github.com/influxdata/influxdb/issues/20249
This fix formats marshaling errors the same way
influxdb formats other query errors.
=> fix(error): unsupported value: +Inf" error not handled gracefully

cmd/influxd/upgrade/upgrade.go
=> fix(upgrade): add DB URL to log message at end up upgrade

CHANGELOG.md
=> chore: fix CHANGELOG formating

CHANGELOG.md, go.mod, go.sum, query/promql/internal/promqltests/go.mod, query/promql/internal/promqltests/go.sum, ui/package.json, ui/yarn.lock
Closes #20279
These are the latest versions on `master`
=> chore: update flux in backend and UI

.goreleaser-nightly.yml, .goreleaser.yml
=> chore(build): update nightly docker image name to influxdb2

.circleci/config.yml, .goreleaser-nightly.yml, .goreleaser.yml, CHANGELOG.md, Makefile, docker/circleci/Dockerfile, docker/circleci/xcc.sh, go.mod, go.sum
Closes #20291 
Closes #20280 
Backports #20290 
Backports #20260
=> build: add ARM64 support to 2.0 branch

CHANGELOG.md, go.mod, go.sum, query/promql/internal/promqltests/go.mod, query/promql/internal/promqltests/go.sum, ui/package.json, ui/yarn.lock
=> fix: bump Flux for latest fixes

CHANGELOG.md
=> chore: update CHANGELOG to reflect final diff from 2.0.3

.circleci/config.yml, Makefile
=> build: add InfluxQL regression suites to CI

CHANGELOG.md, scripts/init.sh
Closes #20346 
Backports #20349
=> fix: ensure init.d-style install sees our default environment variables

CHANGELOG.md, scripts/post-install.sh
Closes #20341 
Backports #20348
=> fix: adjust post-install logic to only display upgrade notice when needed

.goreleaser-nightly.yml, .goreleaser.yml, CHANGELOG.md
Closes #20338 
Backports #20339
=> fix: add upgrade helper script to nfpms manifest

CHANGELOG.md, cmd/influx/template.go, cmd/influx/template_test.go
Closes #20363 
Backports #20362
=> fix(cli): don't overwrite stack name/desc on stack update (#20362)

.circleci/config.yml, Makefile
Closes #20356
Backports #20358 and #20370
=> build: add new CI jobs for InfluxQL test suites

prometheus/converters.go
=> fix(prometheus): regexp handling should comply with PromQL

CHANGELOG.md
=> chore: update CHANGELOG.md for typo and community PR

CHANGELOG.md, task_errors.go
=> fix: don't duplicate text in task errors

CHANGELOG.md, cmd/influxd/launcher/launcher.go, cmd/influxd/upgrade/security_test.go, tenant/error_user.go, tenant/middleware_onboarding_logging.go, tenant/service_onboarding.go, tenant/service_onboarding_test.go, tenant/service_user.go, v1/authorization/service_password.go
Closes #20233 
Backports #20317
=> fix(onboarding): don't ignore failures to set initial password

.circleci/config.yml
Closes #20367 
Backports #20397
=> build: clean up CircleCI config

tsdb/engine/tsm1/iterator_test.go
Example test failure here: https://app.circleci.com/pipelines/github/influxdata/influxdb/17193/workflows/205076e2-b061-4274-bfc5-68d73ad5a4be/jobs/163272
This test seems inherently prone to flakiness, so I just ballooned the loop counts and timeouts.
=> test: bump timeouts and retry counts to try fixing flaky test failures.

.circleci/config.yml, ui/jest.config.js
Noticed while working on flaky tests. Will comment explanations inline.
=> build(ui): fix report generation & collection for JS tests

.circleci/config.yml, task/backend/executor/executor_test.go, task/backend/executor/support_test.go, tsdb/engine/tsm1/iterator_test.go, ui/jest.config.js
Backports #20412 #20413 and #20414.
=> test: backport fixes to CI and flaky tests

releng/packages/spec/clean_install/_install_uninstall.bash, releng/packages/spec/clean_install/run.bash
=> build: switch tested centos base images

CHANGELOG.md, cmd/influx/main.go
Closes #20378 
Backports #20387
=> fix(cmd/influx): improve CLI error returned on org-not-found

CHANGELOG.md, http/legacy/write_handler.go, http/legacy/write_handler_test.go, http/write_handler.go, http/write_handler_test.go
Closes #20443 
Backports #20442
=> fix(http): don't return 500 errors for partial writes

.circleci/config.yml, Makefile, docker/circleci/Dockerfile
Leftover fixes missed in #20449, flushed out by the nightly job.
=> build: fix goreleaser setup and release jobs

.gitignore, client/influxdb_test.go, cmd/influxd/run/command_test.go, tsdb/engine/tsm1/file_store_key_iterator_test.go, tsdb/engine/tsm1/ring_test.go, tsdb/index/inmem/meta_test.go
=> fix: minor test fixes for go1.15 and also flaky timeouts

CHANGELOG.md, dbrp/error.go, dbrp/http_client_dbrp.go, dbrp/http_server_dbrp.go, dbrp/http_server_dbrp_test.go, dbrp/service.go
Closes #20408 
Backports #20409
=> fix(dbrp): improve DBRP API validation errors

CHANGELOG.md, cmd/influxd/upgrade/database.go, cmd/influxd/upgrade/database_test.go, cmd/influxd/upgrade/setup.go, cmd/influxd/upgrade/upgrade.go
Closes #20384 
Backports #20440
=> fix(cmd/influxd): improve `influxd upgrade` logging, and require manual confirmation of data copy

CHANGELOG.md
=> chore: Update changelog to include geo widget changes

CHANGELOG.md, influxql/query/iterator.go, influxql/query/iterator_test.go
Closes #20259 
Forward-ports #20277
=> fix(influxql): Prevent extra output row from GROUP BY crossing DST boundary

CHANGELOG.md, tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_internal_test.go, tsdb/shard.go, tsdb/shard_test.go, tsdb/store.go, tsdb/store_test.go
Closes #20528 
Backports #20527
=> fix(tsdb): allow backups during snapshotting, and don't leak tmp files

CHANGELOG.md, kit/cli/viper.go, kit/cli/viper_test.go
Closes #20523 
Backports #20522
=> fix(kit/cli): fix loading of .yml config files

CHANGELOG.md, bolt/bbolt.go
Closes #20494 
Backports #20489
=> fix: inject more specific error message for bolt on shared FS

go.mod, go.sum, task/options/flux_deps.go
=> chore(flux): update Flux to v0.101.0

CHANGELOG.md, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/print_config.go, cmd/influxd/launcher/print_config_test.go
Closes #20525 
Backports #20524
=> feat(cmd/influxd): add `print-config` subcommand to support automation

CHANGELOG.md, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go
Closes #20560
Closes #20563
Backports #20561
Backports #20564
=> feat(cmd/influxd): add launcher options to configure NATS server

CHANGELOG.md, http/legacy/influxqld_handler.go, http/legacy/influxqld_handler_test.go, http/swaggerV1Compat.yml, influxql/_v1tests/server_helpers.go, influxql/_v1validation/goldenfiles/example_generated.yaml, influxql/_v1validation/goldenfiles/join.yaml, influxql/_v1validation/goldenfiles/select_aggregate.yaml, influxql/_v1validation/goldenfiles/select_simple.yaml, influxql/_v1validation/goldenfiles/select_star.yaml, influxql/_v1validation/validation.json, influxql/_v1validation/validation_test.go, influxql/query/response_writer.go, influxql/query_request.go, influxql/query_request_test.go
Closes #20529 
Backports #20565
=> fix(influxql): set correct Content-Type on v1 query responses

CHANGELOG.md, cmd/influxd/inspect/export_lp.go, cmd/influxd/inspect/export_lp_test.go, cmd/influxd/inspect/inspect.go, cmd/influxd/main.go
Closes #20460
Backports #20467
=> feat(cmd/influxd): add `influxd inspect export-lp` command to export LP

kv/migration/migration.go
Closes #20570
Backports #20572
=> fix(kv): log migration events at debug level to avoid spam

CHANGELOG.md, cmd/influx/query.go
Closes #20577
Backports #20578
=> fix(cmd/influx): respect --skip-verify in `influx query`

cmd/influxd/upgrade/database.go, cmd/influxd/upgrade/security.go, cmd/influxd/upgrade/upgrade.go
Closes #20637
The original motivation was to make per-user logs `debug` level, but I found more things while I was in the code.
=> fix(cmd/influx): improve logging consistency in `influxd upgrade`

scripts/post-install.sh, scripts/pre-install.sh
=> fix(packaging): don't overwrite existing config on package install

cmd/influx_inspect/main.go, cmd/influx_inspect/report/report.go, cmd/influx_inspect/reportdisk/reportdisk.go, cmd/influx_inspect/reportdisk/reportdisk_test.go, pkg/reporthelper/walkshards.go
=> feat(inspect): Add report-disk for disk usage by measurement

ui/package.json, ui/yarn.lock
[Flux LSP v0.5.30](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.30)
=> chore(ui): Upgrade flux-lsp-browser to v0.5.30

go.mod, go.sum, query/stdlib/testing/testing.go
Upgrade to Flux [v0.104.0](https://github.com/influxdata/flux/releases/tag/v0.104.0)
=> chore(flux): Upgrade Flux to v0.104.0

ui/package.json, ui/yarn.lock
[Flux LSP v0.5.31](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.31)
=> chore(ui): Upgrade flux-lsp-browser to v0.5.31

.circleci/config.yml, CHANGELOG.md, write/batcher.go, write/batcher_test.go
Closes #20668 
Backports #20669
=> fix(write): drop empty lines from write batches

CHANGELOG.md, cmd/influx/user.go, cmd/influx/user_test.go
Closes #20658
Backports #20657
=> fix(cmd/influx): allow for creating users without initial passwords in `influx user create`

CHANGELOG.md, http/write_handler.go, http/write_handler_test.go, influxql/_v1tests/server_helpers.go, mock/write_service.go, tests/client.go, write.go, write/batcher.go, write/batcher_test.go
Closes #20676
Backports #20679
=> fix(http): fix passing of bucket ID by write-handler client

storage/flux/reader.go, storage/flux/table.gen.go, storage/flux/table.gen.go.tmpl, storage/reads/aggregate_resultset.go, storage/reads/array_cursor.gen.go, storage/reads/array_cursor.gen.go.tmpl, storage/reads/array_cursor.go, storage/reads/array_cursor_gen_test.go, storage/reads/array_cursor_test.gen.go.tmpl, storage/reads/array_cursor_test.go, storage/reads/datatypes/predicate.pb.go, storage/reads/datatypes/storage_common.pb.go
=> refactor: update window logic to use interval package

CHANGELOG.md, kit/cli/viper.go, kit/cli/viper_test.go
Closes #20701
Backports #20702
=> fix(kit/cli): fix loading config from directories with '.' in the name

.circleci/config.yml, .goreleaser.yml, CHANGELOG.md
Closes #20698
Backports #20699
=> build: update naming conventions for release builds to prefer hyphens

ui/package.json, ui/yarn.lock
[Flux LSP v0.5.32](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.32)
=> build(ui): Upgrade flux-lsp-browser to v0.5.32

.circleci/config.yml
We got the :+1: to make these images public. This will make it less painful for people to contribute from forks.
=> build: remove quay login before grace and litmus tests

ui/package.json, ui/yarn.lock
Upgrade Flux LSP to [v0.5.33](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.33)
=> chore(ui): Upgrade flux-lsp-browser to v0.5.33

CHANGELOG.md, tsdb/engine/tsm1/ring.go, tsdb/engine/tsm1/ring_test.go
Forward-port of #20172 
I did some extra cleanup in the tests.
=> fix(tsm1): fix data race and validation in cache ring

tsdb/engine/tsm1/cache.go, tsdb/engine/tsm1/cache_test.go, tsdb/engine/tsm1/ring.go, tsdb/engine/tsm1/ring_test.go
Very small refactor so no tracking issue
=> refactor: Remove unused function add and unused variable keysHint

.circleci/config.yml, CHANGELOG.md, flags.yml, kit/feature/list.go, kv/task.go, kv/task_test.go, task.go, task/backend/executor/limits.go, task/options/options.go, task/options/options_test.go, task/servicetest/servicetest.go, task_test.go, ui/cypress/e2e/tasks.test.ts
Closes #20876
Backports #20875
=> fix: make AST-based option parsing the default, remove feature flag

CHANGELOG.md, ui/src/dashboards/constants/index.ts, ui/src/shared/components/tables/TableGraphTable.tsx, ui/src/shared/utils/vis.ts
Closes #20871
Backports #20856
=> fix(ui): respect 24 hour clock format and allow more choices

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, chronograf/server/mux.go, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, cmd/influxd/main.go, cmd/influxd/upgrade/config.go, cmd/influxd/upgrade/config_test.go, http/authentication_middleware.go, http/handler.go, http/handler_test.go, pprof/http_server.go, pprof/pprof.go
And translate pprof-enabled config during upgrade
Closes #20828 
Backports #20827
=> feat(http): allow for disabling pprof

CHANGELOG.md, cmd/influx/main.go, cmd/influx/write.go, cmd/influx/write_test.go
Closes #20765
Backports #20666 and #20763
=> feat(cmd/influx): support reading GZIP data in `influx write`

.circleci/config.yml, Makefile, etc/test-flux.sh
=> feat(ci): run flux integration tests as its own job

cmd/influx/main.go, cmd/influxd/inspect/export_lp.go, cmd/influxd/inspect/inspect.go, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/print_config.go, cmd/influxd/main.go, cmd/influxd/upgrade/upgrade.go, cmd/telemetryd/main.go, kit/cli/viper.go, kit/cli/viper_test.go
Closes #20899 
Backports #20863
=> refactor: remove panics from CLI kit code and influxd CLI setup

CHANGELOG.md, cmd/influx/task.go, cmd/influx/task_test.go
Closes #20743
Backports #20307
=> feat(cmd/influx): add command to find and retry failed task runs

tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/file_store_key_iterator_test.go, tsdb/engine/tsm1/file_store_test.go, tsdb/engine/tsm1/reader.go, tsdb/engine/tsm1/reader_test.go, tsdb/engine/tsm1/tombstone.go, tsdb/engine/tsm1/tombstone_test.go
Closes #20780
Backports #20773 and #20782
=> fix(tsm1): fix data race when accessing tombstone stats

CHANGELOG.md, README.md, ui/src/shared/constants/fluxFunctions.ts
Closes #20830
Backports #20809
=> fix(ui): correct the default port used in UI examples

CHANGELOG.md, ui/src/shared/constants/colorOperations.ts
Closes #20829 
Backports #20819
=> fix: single stats with thresholds won't crash with negative values

cmd/telemetryd/main.go, gather/scheduler_test.go, http/legacy/router.go, http/router.go, logger/logger.go, tsdb/engine/tsm1/engine_internal_test.go, tsdb/engine/tsm1/engine_test.go, tsdb/engine/tsm1/file_store_test.go, tsdb/engine/tsm1/iterator_test.go, tsdb/index/tsi1/sql_index_exporter_test.go, tsdb/index_test.go, tsdb/series_file_test.go, tsdb/shard_internal_test.go, tsdb/shard_test.go, tsdb/store_test.go, v1/services/precreator/service_test.go, v1/services/retention/service_test.go
=> test: replace influxlogger with zaptest logger

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.34](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.34)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.34

logger/config.go
(cherry picked from commit 4d5a688a1ee728c9b421c980614cee5d05631cfd)
Closes #
=> fix(logger): Ensure default level value is info (#17403)

etc/config.sample.toml, pkg/tlsconfig/tls_config.go
=> fix(tls): Enable configuration of TLS 1.3

flux/control/controller.go, flux/control/controller_test.go, mock/flux.go, services/httpd/handler.go
(cherry picked from commit 25fb1077e2dd5469e7a3055db76fc71a99e95139)
Closes #
=> fix(flux): add durations to Flux logging (#19697)

CHANGELOG.md
=> chore: 1.9.0 rc0 changelog

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.35](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.35)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.35

releng/unit-tests/fs/usr/local/bin/influxdb_prebuild_tests.bash
Partial fix of https://github.com/influxdata/influxdb/issues/20854
Previous pull request https://github.com/influxdata/influxdb/pull/20970 overlooked the unit-test script.
=> chore: fix oss unit tests

releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash, releng/unit-tests/fs/usr/local/bin/influxdb_prebuild_tests.bash
Partial fix of https://github.com/influxdata/influxdb/issues/20854
=> chore: add back hashing of build tarball

CHANGELOG.md, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, http/handler.go, http/handler_test.go, kit/transport/http/error_handler.go, pprof/http_server.go
Closes #20956
Backports #20963
=> feat(http): add config option to disable metrics endpoint in influxd

CHANGELOG.md, influxql/query/compile.go, influxql/query/compile_internal_test.go, influxql/query/compile_test.go
Closes #20961
Backports #20882
=> feat(influxql): rewrite regex conditions in subqueries

CHANGELOG.md, authorizer/task_test.go, cmd/influx/setup.go, cmd/influxd/upgrade/security_test.go, cmd/influxd/upgrade/setup.go, http/swagger.yml, onboarding.go, tenant/service_onboarding.go, tenant/service_onboarding_test.go, testing/onboarding.go, tests/pipeline_helpers.go
Closes #20799
Backports #20798
=> fix(onboarding): deprecate misleading `retentionPeriodHrs` key

CHANGELOG.md, tsdb/engine/tsm1/wal.go, tsdb/engine/tsm1/wal_test.go
Closes #20831
Backports #20811
=> fix(tsm1): fix wal's totalOldDiskSize statistics

CHANGELOG.md, http/swagger.yml
Closes #20842 
Backports #20705
=> fix(http/swagger): repair DBRPs type to match implementation

.circleci/config.yml, .gitignore, CHANGELOG.md, Makefile, cmd/influxd/launcher/_tlstests/tls_test.go, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, cmd/influxd/launcher/launcher_helpers.go, etc/test-tls.sh
Closes #20919
Backports #20921
=> fix(tls): Update TLS strict cipher suite to actually work

CHANGELOG.md, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go
Closes #20957
Backports #20971
=> feat(http): add config parameters for HTTP timeouts

CONTRIBUTING.md
=> chore: updated CONTRIBUTING.md for new package config script

CHANGELOG.md, bucket.go, cmd/influx/bucket.go, cmd/influx/bucket_test.go, cmd/influxd/launcher/engine.go, cmd/influxd/launcher/storage_test.go, http/source_service.go, http/swagger.yml, kv/migration/all/0003_task_owners_test.go, kv/migration/all/0015_record-shard-group-durations-in-bucket-metadata.go, kv/migration/all/0015_record-shard-group-durations-in-bucket-metadata_test.go, kv/migration/all/all.go, kv/migration/all/test_service_test.go, storage/bucket_service.go, storage/bucket_service_test.go, storage/engine.go, storage/mocks/EngineSchema.go, tenant/http_client_bucket.go, tenant/http_client_onboarding.go, tenant/http_server_bucket.go, tenant/http_server_bucket_test.go, tenant/storage_bucket.go, testing/bucket_service.go, v1/services/meta/data.go
Closes #20947
Backports #20911
=> feat(cmd/influx): allow setting shard-group durations for buckets via API and CLI

coordinator/statement_executor.go, coordinator/statement_executor_test.go, internal/authorizer.go, internal/tsdb_store.go, query/executor.go, query/iterator.go, query/select.go, query/subquery_test.go, services/httpd/handler.go, services/httpd/handler_test.go, services/meta/data.go, services/meta/query_authorizer.go, services/meta/write_authorizer.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/meta.go, tsdb/store.go
=> refactor: separate coarse and fine permission interfaces

go.mod, go.sum, releng/raw-binaries/Dockerfile, releng/raw-binaries/build.bash, releng/raw-binaries/fs/root/.cargo/config, releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash, releng/source-tarball/Dockerfile, releng/source-tarball/fs/root/.cargo/config, releng/unit-tests/Dockerfile, releng/unit-tests/fs/root/.cargo/config
Closes: https://github.com/influxdata/influxdb/issues/20854
=> build: make windows builds possible

backup.go, backup/backup.go, cmd/influx/backup.go, cmd/influx/restore.go, cmd/influxd/launcher/backup_restore_test.go, cmd/influxd/launcher/launcher_helpers.go, http/middleware.go, restore/restore.go
Pre-step for working on #20758 and #20749
=> refactor: modularize backup/restore behavior so it's possible to test using `go test`

CHANGELOG.md, ui/src/timeMachine/apis/queryBuilder.ts
Closes #21022 
Backports #20925
=> fix: escape regex meta characters in user input

CHANGELOG.md, ui/src/style/chronograf.scss, ui/src/tasks/components/TaskCard.tsx, ui/src/tasks/components/TaskCardMeta.scss, ui/src/tasks/components/TaskCardMeta.tsx
Closes #21023
Backports #20894
=> feat: adding task ids to the ui

coordinator/statement_executor.go, coordinator/statement_executor_test.go, internal/authorizer.go, internal/tsdb_store.go, query/executor.go, query/iterator.go, query/select.go, query/subquery_test.go, services/httpd/handler.go, services/httpd/handler_test.go, services/meta/data.go, services/meta/query_authorizer.go, services/meta/write_authorizer.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/meta.go, tsdb/shard.go, tsdb/store.go
(cherry picked from commit b7e7de24d6a71fe6a0b999dbf1ae3c51e099ad13)
=> refactor: separate coarse and fine permission interfaces (#20996)

releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash
Closes #21018
See https://github.com/golang/go/issues/40795
=> build: fix windows build for go1.15

cmd/influx/task.go
Closes #21025 
Backports #21033
Fixes up unreleased code new to 2.0.5, so no CHANGELOG update needed.
=> fix(cmd/influx): add limits to task and run filters in retry-failed

tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/log_file_test.go, tsdb/series_set.go
Closes #21043
Backports #21013
=> fix(tsi1): optimize the comparison of SeriesIDSet.

CHANGELOG.md, bolt/bbolt.go, bolt/metrics.go, bolt/metrics_test.go
Closes #21027
Backports #21042
=> fix(bolt): prevent concurrent access to telegraf plugin metrics cache

CHANGELOG.md, cmd/influxd/inspect/export_lp.go
Closes #21026
Backports #21046
=> feat(cmd/inflxud): add support for writing to stdout in `export-lp`

CHANGELOG.md, cmd/influx_inspect/help/help.go
Closes #21007
(cherry picked from commit db38959b7a53d84388852b9891a0f84f6b8a3f2c)
=> fix: help text for influx_inspect (#21052)

CHANGELOG.md, cmd/influx/query.go
Closes #21024
Backports #21006
=> feat: add profiler to query command in cli

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.37](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.37)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.37

Dockerfile_build_ubuntu64_git
Fix to inconsistent go versions that's a follow-on from #21034
=> chore: fix inconsistent go version in Dockerfile

.circleci/config.yml, .goreleaser.yml, CHANGELOG.md, go.mod, go.sum, scripts/ci/xcc.sh
=> build: add windows to cross-build

storage/reads/aggregate_resultset.go, v1/services/storage/store.go
merge @philjb's changes into my branch
=> chore: PR cosmetic feedback

CHANGELOG.md, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, cmd/influxd/launcher/query_test.go, query/control/controller.go, query/control/controller_test.go, query/control/metrics.go, task/backend/analytical_storage_test.go
Closes #21120
Forward-ports the bulk of #21108
Still need to get a :+1: from product on the breaking changes
=> feat(flux): allow values of 0 to disable controller limits

.circleci/config.yml, Dockerfile_build_ubuntu64
Improve circleCI config structure in prep for moving automation out of jenkins (influxdata/edge#44).
Well-formatted commit messages
Rebased/mergeable
=> chore: Improve circle automation structure in prep for moving out of Jenkins

.circleci/config.yml, Makefile, etc/test-flux.sh, internal/cmd/fluxtest-harness-influxdb/test.go, query/stdlib/fluxtest.root, query/stdlib/influxdata/influxdb/filter_test.flux
=> build: add flux integration tests to CI

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.39](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.39)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.39

ui/fetch_ui_assets.sh
=> fix(build): update the download path for ui assets

CHANGELOG.md, flags.yml, kit/feature/list.go, ui/cypress/e2e/explorer.test.ts
Closes #21180
Backports #21172
=> feat(ui): enabling feature flags for various UI features

CHANGELOG.md, flux/stdlib/influxdata/influxdb/buckets.go, tests/server_test.go
Closes https://github.com/influxdata/influxdb/issues/21184
Closes https://github.com/influxdata/chronograf/issues/5721
Update the buckets source for the latest flux version
=> fix: flux regression in buckets query

CHANGELOG.md, flux/stdlib/influxdata/influxdb/buckets.go, tests/server_test.go
(cherry picked from commit 461464f1800e1aacf7fa1bd87b3cd08bc11b92d6)
Closes https://github.com/influxdata/influxdb/issues/21185
=> fix: flux regression in buckets query (#21183)

tenant/http_server_bucket.go
Closes #21170
Backports #21179
=> fix: send empty array of retention rules when no parameters are set

.circleci/config.yml
Closes #
Backport from #21162 in `master-1.x`.
=> chore: remove changelog job in circle config

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.40](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.40)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.40

http/swagger.yml
Updates the `GET /api/v2/authorizations` API to allow searching for a token by value.
=> feat: Updated swagger for authorization lookup by token query parameter

CHANGELOG.md, go.mod, go.sum
Closes https://github.com/influxdata/influxdb/issues/21225
=> feat: flux upgrade to v0.112.1

CHANGELOG.md, go.mod, go.sum, query/stdlib/testing/testing.go
=> build(flux): update flux to v0.112.1

CHANGELOG.md, tsdb/shard.go, tsdb/shard_test.go
Closes #20628
Backports #21228
=> fix(tsdb): minimize lock contention when adding new fields or measurements

CHANGELOG.md, cmd/influxd/launcher/launcher.go
Closes #21240
Backports #21235
=> feat: structured logging for HTTP server ErrorLog

ui/cypress/e2e/tasks.test.ts
Closes #21243
Backports #21244
=> fix: remove e2e test for creating a task from a template

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.41](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.41)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.41

CHANGELOG.md, go.mod, go.sum, pkger/service.go, query/stdlib/influxdata/influxdb/min_max_influxdb_test.flux, query/stdlib/influxdata/influxdb/rules.go, storage/flux/table.gen.go, storage/flux/table.gen.go.tmpl, storage/flux/table.go, storage/flux/table_test.go, storage/reads/group_resultset.go, ui/package.json, ui/yarn.lock, v1/services/storage/store.go
Closes #21155 
This PR backports the min/max pushdown to the `2.0` branch for release in 2.0.5.
=> feat(query): enable min/max pushdown

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.42](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.42)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.42

storage/reads/aggregate_resultset.go, storage/reads/array_cursor.go, storage/reads/array_cursor_gen_test.go, storage/reads/array_cursor_test.gen.go.tmpl
=> chore: refactor to make it easier for enterprise to share functionality

CHANGELOG.md, storage/reads/aggregate_resultset.go, storage/reads/array_cursor.gen.go, storage/reads/array_cursor.gen.go.tmpl, storage/reads/array_cursor.gen.go.tmpldata, storage/reads/array_cursor.go, storage/reads/array_cursor_gen_test.go, storage/reads/array_cursor_test.gen.go.tmpl, storage/reads/array_cursor_test.go, storage/reads/datatypes/predicate.pb.go, storage/reads/datatypes/storage_common.pb.go, storage/reads/datatypes/storage_common.proto, storage/reads/gen.go, storage/reads/group_resultset.go, storage/reads/response_writer.gen.go, storage/reads/response_writer.gen.go.tmpl, storage/reads/response_writer.go, tsdb/cursors/arrayvalues.gen.go.tmpl, tsdb/cursors/arrayvalues.gen.go.tmpldata, tsdb/cursors/arrayvalues.go, tsdb/cursors/cursor.go, tsdb/cursors/gen.go
Small refactors to allow code sharing with InfluxDB Enterprise
=> feat: meancount aggregation for WindowAggregate pushdown in enterprise

CHANGELOG.md, storage/reads/aggregate_resultset_test.go, storage/reads/array_cursor.go, storage/reads/group_resultset_test.go, storage/reads/resultset.go, storage/reads/resultset_test.go, tsdb/cursors/cursor.go, tsdb/engine/tsm1/array_cursor.gen.go, tsdb/engine/tsm1/array_cursor.gen.go.tmpl, tsdb/engine/tsm1/array_cursor_iterator.go, tsdb/engine/tsm1/array_cursor_test.go, tsdb/engine/tsm1/engine_test.go
=> fix(storage): cursor requests are [start, stop] instead of [start, stop)

CHANGELOG.md, cmd/influx/setup.go, http/swagger.yml
Closes #21346 
Backports #21345
=> fix: deprecate PostSetupUser and `influx setup user`

tsdb/engine/tsm1/reader.go
Closes #
In tsdb/engine/tsm1/reader.go, I found a word misspelling in line 733. The word "minium" should be "minimum".
=> chore: fix typo

CHANGELOG.md, internal/cmd/fluxtest-harness-influxdb/test.go, query/stdlib/influxdata/influxdb/geo_mergefilter_test.flux, query/stdlib/influxdata/influxdb/rules.go
Add a test to make sure this stays fixed.
Closes #21352
=> fix: disable MergeFiltersRule until it is more stable

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.43](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.43)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.43

ui/package.json, ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.44](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.44)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.44

CHANGELOG.md, internal/cmd/fluxtest-harness-influxdb/test.go, query/stdlib/influxdata/influxdb/geo_mergefilter_test.flux, query/stdlib/influxdata/influxdb/rules.go
Add a test to make sure this stays fixed.
(cherry picked from commit 8124973e0f06276d2de660c844ab5b76c148d201)
Closes #21360
=> fix: disable MergeFiltersRule until it is more stable (#21356)

CHANGELOG.md, http/delete_handler.go, http/delete_test.go
Closes #21370 
Backports #21369
=> fix: add limits to delete api start and stop times

CHANGELOG.md, cmd/influx/restore.go, restore/restore.go
Closes #21476
Backports #21477
=> fix(cmd/influx): accept `--input` flag in `restore` command

CHANGELOG.md, tsdb/engine/tsm1/file_store.go
Closes #21482 
Backports #21481
=> fix: last-modified of empty shard directory shouldn't be Unix epoch.

internal/cmd/fluxtest-harness-influxdb/test.go
This patch adds support for using `testing.load` in flux acceptance
tests.
=> feat: add support for testing.load in fluxtest

CHANGELOG.md, internal/authorizer.go, services/httpd/handler.go, services/httpd/handler_test.go, services/meta/data.go, services/meta/query_authorizer.go
=> fix: FGA enablement

CHANGELOG.md, kit/transport/http/middleware.go, kit/transport/http/middleware_test.go
Closes #21523
Clean backport of #21522
=> fix: add telemetry slug for additional file exts

CHANGELOG.md
Update changelog for 1.8.6 release
=> chore: Update changelog for 1.8.6 release

CHANGELOG.md
Closes #
Updates changelog for 1.8.6
=> chore: update changelog for 1.8.6

flags.yml, kit/feature/list.go
creating new feature flag: rangeAnnotations
already created in config cat
simultaneously creating in idpe repo.
for ui#1417
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1417
=> chore: adding rangeAnnotations feature flag

.circleci/config.yml
Fixes nightly aws teardown logic.
=> chore: correct shell syntax in aws nightly teardown

tsdb/shard.go
(cherry picked from commit 7d10228e19a6032ddd16b560679f00a56d591d05)
=> chore: minor refactor suggested by go lint

tsdb/shard.go
(cherry picked from commit 7d10228e19a6032ddd16b560679f00a56d591d05)
(cherry picked from commit f8202876ad990a503f7a5f355fb5060d3e9552c6)
=> chore: minor refactor suggested by go lint (#21614)

internal/cmd/fluxtest-harness-influxdb/test.go
This change adds a flag to the flux-test-harness cmd that makes the test
harness wait between test runs leaving the InfluxDB instance running for
inspection. The credentials for connecting to the test instance are also
added to the local influx cli configs.
=> feat(fluxtest): add ability to wait between test runs

http/backup_service.go
Closes #21655
The changes here are in a spot that's tough to unit-test, but I manually tested this works via the new CLI code.
=> feat: add gzip support to backup API responses

.circleci/config.yml, scripts/ci/perf_test.sh, scripts/ci/run_perftest.sh
chore: improve and update 1.8 ingest performance test automation
=> chore: adjust ingest perf tests for 1.8 to bring in line with 2.0

backup.go, http/restore_service.go
Closes #21680
Manually tested using the new CLI, can write some unit tests if desired.
=> feat: implement new restore/bucket-metadata API

CHANGELOG.md, tsdb/engine/tsm1/engine.go, tsdb/shard.go, tsdb/shard_test.go
=> fix: avoid rewriting fields.idx unnecessarily

CHANGELOG.md
=> chore: update changelog to sync with 1.9 branch

tests/backup_restore_test.go, tests/server_test.go
=> test: add series cardinality test and fix backup port

query/compile.go, query/compile_test.go
=> fix: error instead of panic for statement rewrite failure (#21792)

CHANGELOG.md
=> chore: changelog for recent backports

pkg/estimator/hll/hll_test.go
=> fix: a few suddenly flaky tests involving randomness

pkg/estimator/hll/hll_test.go
Partial close of #21805 
(cherry picked from commit c240c7906e9d77f10af2430322636fb51a95c2a0)
=> fix: a few suddenly flaky tests involving randomness (#21818)

cmd/influx_inspect/dumptsi/dumptsi.go, tsdb/index/tsi1/file_set.go, tsdb/index/tsi1/file_set_test.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go
cleans up unused members from FileSet.
=> fix(tsi): clean up FileSet fields

cmd/influxd/inspect/dump_tsi/dump_tsi.go, tsdb/index/tsi1/file_set.go, tsdb/index/tsi1/file_set_test.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go
=> fix: simplify file set, remove series file member

scripts/ci/perf_test.sh
Replaces use of influx [command] with curls to the API, which fixes breakages to perf tests following #21797.
=> chore: perftests should use API now that `influx` cmd is gone

.goreleaser.yml, CHANGELOG.md, scripts/influxd-systemd-start.sh, scripts/influxdb.service
Closes #6068 
Cherry-picked from c8de72ddbc5fdf20f821ca473f1fdf92820f9ac3
=> fix: systemd unit should block on startup until http endpoint is ready

scripts/ci/perf_test.sh, scripts/ci/run_perftest.sh
Enable query performance tests in 2.0
=> chore: enable query performance tests

CHANGELOG.md, cmd/influx_tools/export/README.md, cmd/influx_tools/importer/command.go, cmd/influx_tools/importer/importer.go
=> fix: export example and fix adjacent shards

CHANGELOG.md
Update changelog for 1.8.7 release
=> chore: changelog update for v1.8.7 release

CHANGELOG.md
=> chore: update master-1.x changelog to reflect v1.8.7 release

tsdb/shard.go
(cherry picked from commit aca69e530f16441e343265d717001c68cd1db115)
(cherry picked from commit f8ef784cffff663cd4c5f0ec3ac493ef39e6040a)
Port https://github.com/influxdata/influxdb/pull/21693 to 2.0
=> fix: don't access a field in a nil struct

.circleci/config.yml
=> build: verify checksum of Go download in CI

scripts/ci/run_perftest.sh
Query perftests reintroduced use of the `influx` command, which is no longer present in `master` or `2.0`. The API should be used instead.
Additionally, API v2 calls require token and org to be passed in.
=> chore: perftests should use API instead of influx cli

CHANGELOG.md, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, http/api_handler.go, http/platform_handler.go
Closes #21913
Clean cherry-pick of e7685fff01ff8e70127f1a274693e77a5146a579 (except for the `CHANGELOG`)
=> feat: add `ui-disabled` flag to run server with UI disabled

.goreleaser.yml, CHANGELOG.md
=> build: split `influxd` and `influx` into separate `deb`/`rpm` packages

.goreleaser.yml, CHANGELOG.md
=> build: recommend influx-cli in packaging, add section to README

scripts/ci/perf_test.sh
=> build: rename the server binary found by perftests

.goreleaser.yml
Related to influxdata/influx-cli#215
=> build: update name of new CLI deb/rpm package

CHANGELOG.md, services/snapshotter/service.go, services/snapshotter/service_test.go
Forward-port of https://github.com/influxdata/influxdb/pull/20115 to master-1.x
=> fix: restore portable backup

CHANGELOG.md, services/snapshotter/service.go, services/snapshotter/service_test.go
=> fix: restore portable backup bug

scripts/ci/install-rust.sh
=> chore: set rust version to the same as latest tag from flux

CHANGELOG.md
=> chore: update changelog for v1.8.8 release

query/control/controller_test.go
Closes #22032
(cherry picked from commit eef37b96b96280ee8787439bd8b82f5da18d5826)
=> test: ensure compile takes time (#21973)

cmd/influx_tools/export/README.md, cmd/influx_tools/importer/command.go, cmd/influx_tools/importer/importer.go
Closes #22034
* fix: export example and fix adjacent shards
* fix: Cody's review
(cherry picked from commit 22809a33aa7a67e3936a74b77235fe71bc6d8ce6)
=> fix: export example and fix adjacent shards (#21863)

cmd/influx_inspect/dumptsi/dumptsi.go, tsdb/index/tsi1/file_set.go, tsdb/index/tsi1/file_set_test.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go
Closes #22036
(cherry picked from commit 108e2600b3fdd8a8d9cfa53e475517ccf757ea23)
=> fix(tsi): clean up FileSet fields (#18961)

CHANGELOG.md
=> chore: update changelog for v1.8.9 release

tsdb/index/tsi1/partition.go
Closes #22030
* fix: old tsl files should be compacted wihout new writes
* chore: update changelog.md
(cherry picked from commit e62efaf751b851e6c610c2229a10b70730bfb338)
=> fix: old tsl files should be compacted without new writes (#22006)

.circleci/config.yml, pkg/tracing/wire/binary.go, scripts/gogo-path.sh, storage/reads/datatypes/gen.go, v1/services/storage/gen.go
Closes #22087
Added a check to CI so we catch problems in the future.
=> build: fix generation when vendoring dependencies

CHANGELOG.md, go.mod, go.sum
Closes #22079
Cherry-pick of b6966de6c37914727312f0efac9f6bc2b7134236
=> build(flux): update flux to v0.124.0

query/stdlib/influxdata/influxdb/group_first_last_influxdb_test.flux, storage/flux/table_test.go
Closes #22082
Cherry-pick of 9ecddda5ae7762633dd34c5223d261e997143ec8
=> test: add acceptance tests and table tests for group|>first/last

query/stdlib/influxdata/influxdb/group_agg_influxdb_test.flux
Closes #22081
Cherry-pick of 66d9ee8751fd80e8c733cbf2d484a474b74ecf35
=> test: add tests for group and count/sum

CHANGELOG.md, cmd/influxd/run/server.go
Replace usage of the Go log package with the zap
logger and respect the formatting specified in
the configuration file.
closes https://github.com/influxdata/influxdb/issues/22104
=> fix: ensure log formatting (JSON) is respected

tsdb/index/tsi1/cache_test.go, tsdb/index/tsi1/index_test.go
=> test: add extra logging when disk size test fails

go.mod, go.sum
Closes #22127
Cherry pick of 4e7d1b390916de231b059aa4e5504509d94b0d74
=> chore(go-bindata): update to recent version of go-bindata

internal/cmd/fluxtest-harness-influxdb/test.go
Closes #22128
Cherry pick of cd546e9eb8481cda7f3efb8ad95ce7e1d282f4d9
=> fix: report error when a flux acceptance test doesn't have a package statement 

internal/cmd/fluxtest-harness-influxdb/test.go
Closes #22129
Cherry pick of 67f366d9cb59228df7365b05f607671bd2f9bdcb
=> fix(query): do not hide errors from first pass of flux acceptance tests

query/stdlib/influxdata/influxdb/show_fields_with_meas_pred_test.flux
Closes #22125
Cherry-pick of 233943213274b4d9b9c7e4e1db30ee6dbb72dcdc
=> chore: remove duplicate flux test

query/control/controller_test.go
=> test: compile time only needs testing once

.circleci/config.yml, CHANGELOG.md, scripts/ci/main.tf, scripts/ci/tests/auth-enabled.sh, scripts/ci/tests/default-config.sh, scripts/ci/tests/self-signed-certs.sh, scripts/influxd-systemd-start.sh
Continuing to address problems with systemd script identified in #21967.
This PR also includes improvements to pkg_run_test.
=> fix: systemd service -- handle 40x and block indefinitely

CHANGELOG.md, scripts/influxd-systemd-start.sh
=> fix: systemd service -- handle https, 40x, and block indefinitely

.goreleaser.yml, CHANGELOG.md
=> build: revert splitting of linux packages

scripts/ci/tests/03-auth-enabled.sh
=> chore: fix curl syntax for auth setup in pkg_run_test

scripts/ci/run_perftest.sh
Closes #22184
Cherry-pick of 9e8f47a472104d0ba8b34adb3f0ae4f40d2b17c9
=> build: don't include host tag on perf test results

flags.yml, kit/feature/list.go
=> feat(replication): add feature flag for replication-stream backend

CHANGELOG.md
=> chore: update changelog for v2.0.8 release

.circleci/config.yml, scripts/ci/run_perftest.sh
Closes #22152
Adds automated performance benchmarks for the queries implemented in https://github.com/influxdata/influxdb-comparisons/pull/192
=> build: add perf tests for group-window-transpose

.circleci/config.yml
Closes #22233
Cherry-pick of de9855d0738beebfcdb09995e6654f9b580697f6
=> build: dont run `pkg_run_test` on forks

sqlite/migrations/0003_create_remotes_table.sql
=> feat: add SQL migration for remote connection metadata

docker/flux/Dockerfile, docker/influxd/Dockerfile
=> chore: pin base Debian image in Docker builds (#22222)

CHANGELOG.md, task/backend/coordinator/coordinator.go, task/backend/coordinator/coordinator_test.go
Closes #22240
Cherry-pick of 991ff02ea74f883122c82ac3737d3e8df90034c5
=> fix(task): inactive task runs when updated

cmd/influxd/launcher/launcher.go, remotes/middleware_logging.go, remotes/middleware_metrics.go, remotes/service.go, remotes/service_test.go
Closes #22249
Copied the pattern(s) used for other services
=> feat: add logging and metrics middlewares to remotes API

sqlite/migrations/0004_create_replications_table.sql
=> feat: add SQL migration for replication metadata

cmd/influxd/launcher/launcher.go, replications/middleware_logging.go, replications/middleware_metrics.go
=> feat: add logging and metrics middlewares to replications API

tsdb/index/tsi1/cache_test.go, tsdb/index/tsi1/index_test.go
(cherry picked from commit 3ae389b35918ebb9da9f57d7e0e2af2ec8ad38c5)
=> test: add extra logging when disk size test fails (#22103)

.circleci/config.yml, scripts/ci/run_perftest.sh
Related to #22156
Incorporates the improved multi-measurement test added in https://github.com/influxdata/influxdb-comparisons/pull/200 to the perf test CI job
=> build: new multi-measurement perf test

CHANGELOG.md, cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, http/api_handler.go, http/query_handler.go
Closes #22336
Backports  #22072
=> feat: add `--flux-log-enabled` flag for detailed flux logs

.circleci/config.yml, CHANGELOG.md, query/executor_test.go, services/httpd/handler.go, services/httpd/handler_test.go, tsdb/engine/tsm1/engine_test.go
=> fix: flux error properly read by cloud (#22348)

.circleci/config.yml, CHANGELOG.md, CONTRIBUTING.md, annotations/service_test.go, cmd/influxd/upgrade/logging_unix.go, go.mod, jsonweb/fuzz.go, pkg/file/file_unix.go, pkg/fs/fs_unix.go, pkg/mincore/mincore_unix.go, pkg/mincore/mincore_windows.go, pkg/mmap/mmap_solaris.go, pkg/mmap/mmap_unix.go, static/TODO.go, tools.go, tsdb/engine/tsm1/mmap_unix.go, vault/secret_test.go
=> build: upgrade to go1.17

query/stdlib/testing/end_to_end_test.go
Closes #22369
Backports #22366 - Clean cherry-pick
=> feat: add additional log to flux e2e tests

.circleci/config.yml
=> build: update goreleaser version pin

services/snapshotter/service.go
=> fix(snapshotter): properly read payload (#17495)

.circleci/config.yml
=> build: don't run `pkg_run_test` on forks

cmd/influxd/launcher/launcher.go, replications/bucket_service.go, replications/service.go, replications/service_test.go
=> feat: deleting a bucket also deletes all associated replications

.circleci/config.yml, cmd/influxd/upgrade/logging_unix.go, go.mod, go.sum, influxql/query/executor.go, jsonweb/fuzz.go, pkg/file/file_unix.go, pkg/fs/fs_unix.go, pkg/mincore/mincore_unix.go, pkg/mincore/mincore_windows.go, pkg/mmap/mmap_solaris.go, pkg/mmap/mmap_unix.go, query/stdlib/influxdata/influxdb/to.go, static/TODO.go, static/swagger_assets.go, static/swagger_noassets.go, tools.go, tsdb/engine/tsm1/mmap_unix.go, tsdb/index/tsi1/cache.go, vault/secret_test.go
- Upgrade to go1.17.1 from 1.16.5
- Upgrade staticcheck to 0.2.0 from 0.1.3
=> build: upgrade to go 1.17.1 (2.0)

CHANGELOG.md
=> chore: update changelog for 1.9.4rc2

cmd/influxd/launcher/pkger_test.go
=> test: skip pkger URI test when running on Windows

scripts/ci/run_perftest.sh
Closes https://github.com/influxdata/influxdb/issues/22496
Backport of https://github.com/influxdata/influxdb/pull/22480
Clean cherry-pick
=> build: run perf test queries only on specific datasets

.circleci/config.yml, scripts/ci/run_perftest.sh
Closes #22455 for the `1.8` branch
=> build: series cardinality perf test

.goreleaser.yml
Closes #22445 
Backports #22447
=> build: embed tzinfo into Windows builds to avoid panics

telegraf/plugins/inputs/docker.go, telegraf/plugins/inputs/kubernetes.go, telegraf/plugins/inputs/procstat.go
Follow-up to https://github.com/influxdata/influxdb/pull/22476
Matches idpe PR 11833
=> chore: add check for procstat

tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_test.go, tsdb/engine/tsm1/iterator.go, tsdb/index.go, tsdb/series_file.go
Closes #22518
Backports #22316
=> feat(tsi): optimize series iteration

influxql/query/functions_test.go, influxql/query/select_test.go, query/stdlib/testing/testing.go
Closes #22411
Backports #22414
=> test: skip HoltWinters tests when GOARCH != amd64

.circleci/config.yml
Update the cross build container, and fix review comments from backport PR https://github.com/influxdata/influxdb/pull/22332
=> build: update cross build container

http/query.go
Closes #22536
Backports #22537
=> fix: suggest setting flux Content-Type when query fails to parse as JSON

tsdb/series_segment.go
=> fix(tsdb): sync series segment to disk after writing

scripts/ci/run_perftest.sh
=> test: add ungrouped-agg case to perf test suite

.circleci/config.yml
=> build: avoid writing the signing key material to the filesystem

services/meta/data.go, services/meta/data_test.go
=> fix: create shards without overlaps

go.mod, go.sum, query/stdlib/influxdata/influxdb/rules.go, query/stdlib/influxdata/influxdb/rules_test.go
Related to influxdata/flux#4102.
=> feat(query/stdlib): update push down window logic for location option

.circleci/config.yml
=> build: enable rebuilding tag by triggering via API

v1/services/meta/data.go, v1/services/meta/data_test.go
Closes: #22597
(cherry picked from commit 0a6f562a44d9cb5f3301e6ffaac457d12eabcdf3)
=> fix: do not allow shard creation to create overlapping shards (#22604)

cmd/influxd/backup/backup.go
Closes: #22450
(cherry picked from commit 84b785b78c920c6b941ed72f2973d73496afc6b7)
=> fix: better error for no data from snapshots (#22452)

cmd/store/help/help.go, cmd/store/main.go, cmd/store/query/query.go, coordinator/statement_executor.go, go.mod, go.sum, internal/tsdb_store.go, models/uint_support.go, pkg/file/file_unix.go, pkg/mmap/mmap_solaris.go, pkg/mmap/mmap_unix.go, services/storage/store.go, tests/server_concurrent_test.go, tests/server_test.go, tools.go, tsdb/engine/tsm1/mmap_unix.go, tsdb/store.go, tsdb/store_test.go
Closes #3318 for 1.x (will also be forward ported to 2.x)
Allow syntax like `SHOW MEASUREMENTS ON *.*` as described in the linked issue.
=> feat: show measurements database and retention policy wildcards

go.mod, go.sum, http/task_service.go, influxql/v1tests/server_helpers.go, influxql/v1tests/server_test.go, v1/coordinator/statement_executor.go
=> feat: show measurement database and retention policy wildcards

kit/migration/errors.go, kv/migration/migration.go, sqlite/migrator.go, sqlite/migrator_test.go, testing/migration.go
=> feat: recommend `influxd downgrade` after encountering unknown KV migration

cmd/influxd/launcher/launcher.go, kv/migration/migration.go, kv/migration/migration_test.go, sqlite/migrator.go, sqlite/migrator_test.go, sqlite/test_migrations/all.go
Closes #22764
Backports #22765
=> feat: take a backup of KV/SQL metadata stores before applying migrations

cmd/influxd/downgrade/downgrade.go, cmd/influxd/main.go, kv/migration/all/0016_add-annotations-notebooks-to-oper-token.go, kv/migration/all/0016_add-annotations-notebooks-to-oper-token_test.go, kv/migration/all/0017_add-annotations-notebooks-to-all-access-tokens.go, kv/migration/all/0017_add-annotations-notebooks-to-all-access-tokens_test.go, kv/migration/all/0018_repair-missing-shard-group-durations.go, kv/migration/migration.go, testing/migration.go
Closes #22778
Backports #22800
=> feat: initialize `influxd downgrade` command to run `Down()` migrations on metadata

cmd/influxd/downgrade/downgrade.go, cmd/influxd/launcher/launcher.go
=> feat: extended downgrade command to include sql migrations

.circleci/config.yml, scripts/fetch-ui-assets.sh
Closes https://github.com/influxdata/ui/issues/3068
Updates to a new UI version which fixes the stackdriver telegraf plugin display page: https://github.com/influxdata/ui/releases/tag/OSS-2.1.2
=> feat: upgrade UI to 2.1.2

go.mod, go.sum
=> build(flux): update flux to v0.139.0

.circleci/config.yml
=> chore: don't load approximate cache before saving new version

.circleci/config.yml, scripts/ci/CHANGELOG_frozen.md
Backports https://github.com/influxdata/influxdb/pull/22835
=> build: updated changelog automation

cmd/influx_tools/compact/command.go
Closes #https://github.com/influxdata/influxdb/issues/22846
=> fix: log at Debug level in influx_tools compact-shard

tsdb/index/tsi1/index.go
Closes #22850
Variable assignment is added to make the condition valid.
=> fix: unhandled errors returned by Sketch.Merge

.circleci/config.yml, .goreleaser.yml
Simplification to enable #20855
=> build: stop building & pushing images to quay.io

.circleci/config.yml, scripts/ci/install-aws-cli.sh, scripts/ci/perf_test.sh, scripts/ci/run_perftest.sh
Initial refactoring in preparation for https://github.com/influxdata/influxdb/issues/22872
=> chore: refactor performance test to generate queries and data together

replication.go, replications/service.go, replications/service_test.go, scripts/fetch-swagger.sh, sqlite/migrations/0005_create_replications_table.up.sql
=> feat: add field for dropping data resulting in non-retryable errors to individual replications

scripts/ci/perf-tests/iot.yaml, scripts/ci/perf-tests/metaquery.yaml, scripts/ci/perf-tests/multi-measurement.yaml, scripts/ci/perf_test.sh, scripts/ci/run_perftest.sh
Closes #22872
Refactor testing script to read yaml files
=> refactor: allow specifying performance tests with yaml

cmd/influxd/launcher/remote_to_test.go, models/statistic.go, query/stdlib/influxdata/influxdb/rules_test.go, storage/engine.go, task/backend/coordinator/coordinator.go, task/backend/coordinator/coordinator_test.go, task/backend/executor/executor.go, task/backend/executor/executor_test.go, tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/scheduler.go, tsdb/engine/tsm1/scheduler_test.go, tsdb/shard.go, tsdb/store.go
=> feat: tsm compaction metrics via prometheus

cmd/influxd/launcher/launcher.go, replications/internal/queue_management.go, replications/internal/queue_management_test.go, replications/metrics/replications_metrics.go, replications/mock/queue_management.go, replications/service.go, replications/service_test.go
Part of https://github.com/influxdata/influxdb/issues/22734
Adds collection of metrics for functionality that is currently implemented with replications.
=> feat: added metrics collection for replications

.circleci/config.yml, go.mod, models/inline_strconv_parse.go
=> chore: upgrade Go to 1.17

cmd/influxd/upgrade/upgrade.go
=> fix: add causal error when meta.db is missing

scripts/fetch-ui-assets.sh
=> chore: fix up message when build fails due to OS

services/meta/client.go
From https://github.com/influxdata/influxdb/pull/19572
=> fix: use defer for unlock

influxql/query/result.go, tsdb/index.go
Rebased version of https://github.com/influxdata/influxdb/pull/19105
=> chore: remove unused member from TagSet

cmd/influxd/launcher/replication_test.go
=> test: add e2e test for replication streams

services/continuous_querier/service_test.go
=> test: increase timeout in continuous query test

cmd/influxd/launcher/replication_test.go, replications/internal/queue_management.go
=> feat: replication remote writes do not block local writes

replications/internal/queue_management.go, replications/internal/queue_management_test.go, replications/metrics/replications_metrics.go
=> feat: replications metrics include failure to enqueue

tsdb/shard.go
Fixes a race condition in the restore code path that could cause shard data restores to fail. When the race condition occurs, `Error while freeing cold shard resources` appears in the log files.
This is port of PR 22796 from master-1.x to master. Attempts at creating a test case for master failed, so the fix has ported without a corresponding unit test.
fixes #22957
=> fix(restore): fix race condition which could cause restore command to fail

replications/internal/queue_management.go
Closes #22980
This change provides a small performance improvement to ingest rates.
Per the same conditions described in #22971, the following benefit is observed with this change, where the latest dev builds are tested with one replication configured:
| Version                                 	| Load Time (sec) 	|
|-----------------------------------------	|-----------------	|
|                  Latest release (2.1.1) 	|            11.8 	|
| Latest Dev - Before 	|            33.8 	|
| Latest Dev - After 	|            28.9 	|
=> feat: advance queue scanner periodically instead of every remote write

replications/service.go, replications/service_test.go
Closes #22982
Adds an additional batching criteria based on number of points (max of 5000 per batch), and bumps up the batch size limit to minimize impact on local write performance from queue appends.
Per the same conditions described in #22971, the following benefit is observed with this change, where the latest dev builds are tested with one replication configured:
| Version                                 	| Load Time (sec) 	|
|-----------------------------------------	|-----------------	|
|                  Latest release (2.1.1) 	|            11.8 	|
| Latest Dev - Before 	|            33.8 	|
| Latest Dev - After 	|            23.0 	|
=> chore: increase replications batch size limits

cmd/influxd/launcher/launcher.go, cmd/influxd/launcher/replication_test.go, flags.yml, kit/feature/list.go, remotes/transport/http.go, remotes/transport/http_test.go, replications/transport/http.go, replications/transport/http_test.go
=> feat: enable remotes and replication streams feature

cmd/influxd/downgrade/downgrade.go, scripts/ci/test-downgrade.sh
=> feat: add downgrade target for 2.1

.circleci/config.yml, releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash
Increases the stack size of musl builds.
=> build: bigger stack for musl builds

services/storage/store.go
=> fix: allow limiting shards during flux iterator reads

.circleci/config.yml
=> build: use latest build container

etc/config.sample.toml
See https://github.com/influxdata/plutonium/issues/3765.
=> fix: Fix typo in sample config

cmd/influxd/backup/backup.go, tests/backup_restore_test.go
`influxd-ctl backup` will now create a working backup when only the `-shard`
option is given. Previously this would create a backup that could not be
restored.
fixes #16751
=> fix: `influxd-ctl backup` will create a working backup when only `-shard` given

tsdb/shard_test.go
Add additional testing for the fixes for issue https://github.com/influxdata/influxdb/issues/23090
=> fix: add additional testing for MaxSeriesPerDatabase

tsdb/shard_test.go
Added test to ensure new code path taken for inmem index
(cherry picked from commit f27df39c0361efbff66561aa2f5737db09c7fdec)
=> fix: add additional testing for MaxSeriesPerDatabase (#23094)

pkger/http_server_template.go, pkger/http_server_template_test.go
Updates the templates apply endpoint response under certain conditions:
- When `dryRun` is set to true in the API request
- When there is a parse error in the JSON template, and a `422` status code is sent back
There were two possible approaches to try and maintain general compatibility in this response. First off I created a new response struct `RespApplyErr` which is only used in this one case. It could either:
- Embed the `errors.Error` struct and provide the errors block which provides more detailed error information in this one case, or
- Embed the `RespApply` struct and provide the required response fields code and message (as marked by the API documentation here)
I decided to go for the latter, since originally this response simply provided the `RespApply` struct without any …
=> fix: update 422 dry-run response to conform to API spec

.circleci/config.yml, scripts/ci/run-monitor-ci-tests.bash
This backports the changes from #23169 to 2.1.
=> chore: backport changes ci pipeline changes to monitor-ci

telegraf/service/telegraf.go, telegraf/service/testing/testing.go
=> fix: remove telegraf endpoint pagination

session/http_server.go, session/http_server_test.go
=> fix: tell browser about cookie expiry

cmd/influxd/recovery/user/user.go, cmd/influxd/recovery/user/user_test.go
=> feat: allow changing a password with `influxd recovery user update`

.circleci/config.yml
- Go upgrade from 1.17.2 -> 1.17.9
- Rust upgrade from 1.53 -> 1.58.1
=> build: upgrade Go to 1.17.9

annotations/service_test.go
See https://github.com/influxdata/influxdb/issues/23272
=> fix(annotations): skip flaky annotation tests

etc/config.sample.toml
=> chore: fix typo in config.sample.toml

scripts/influxd-systemd-start.sh
Supersedes #22859, as the original community PR author deleted their Github account
=> fix(systemd): fix operator in host detection

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/semantic.yml
This backports the changes from:
https://github.com/influxdata/influxdb/pull/23305
https://github.com/influxdata/influxdb/pull/23300
=> chore: backport semantic PR and commit message checks

.circleci/config.yml
=> build: update changelogger to ignore case when parsing verbs

query/control/controller.go
This changes the statistics merging to use the `Add` method on the
entire statistics struct instead of only the metadata. The purpose of
this is that we want to utilize the existing function for merging the
statistics so that additional properties can be added without modifying
the query controller.
At the same time, there are certain properties that are computed in the
controller and we want to ensure they aren't double counted if flux
starts computing these itself. So we blacklist certain attributes that
we compute so that if flux is modified to return these values, we just
ignore them until we change our own code to use those values.
In immediate terms, we're changing to use the `Add` method so that we
can add profiles to the statistics and have those profiles propagate to
the query …
=> fix(query/control): add all of the statistics from flux statistics instead of only metadata

.circleci/config.yml
Upgrade master-1.x to Go 1.18.3 (latest)
=> build: upgrade to Go 1.18.3

task/backend/analytical_storage.go, task/backend/run_recorder.go, task/taskmodel/task.go
Adds missing field to tasks bucket for compatibility with Cloud.
Closes #23156
=> feat: add name field to tasks bucket to match cloud

cmd/influxd/run/command.go
Always log the log level so we know if there's no logs because of the log level.
=> feat: log the log level regardless of log level

tsdb/index/tsi1/index.go
Fix for #23460 for `master` branch
=> fix: lost TSI reference / close TagValueSeriesIDIterator in error case

monitor/service.go
closes #23468
(cherry picked from commit dd356e0bccc41e316f10d14ff14083abc0396f38)
=> fix: eliminate race condition on Monitor.globalTags

CONTRIBUTING.md
=> feat: Update Contributing.md to be more accurate for a clean checkout

scripts/ci/CHANGELOG_frozen.md
=> build: update frozen changelog for 2.3

scripts/ci/CHANGELOG_frozen.md
=> build: update frozen changelog

.circleci/config.yml, .circleci/scripts/build-package, .circleci/scripts/get-version
This changes the package names so that they are compatible with other scripts. It also ensures that the version is correct when generating releases.
=> build: fix release workflow

go.mod, go.sum
Last version before test framework change.
=> chore: update flux to 0.170.1

.circleci/config.yml, .circleci/scripts/get-version
=> build: upload release and nightly CHANGELOG.md (2.3)

.circleci/config.yml, .circleci/scripts/get-version
=> build: upload release and nightly CHANGELOG.md

.circleci/config.yml
=> chore: disable nightly docker tag for 2.1

tsdb/index/tsi1/partition.go
When a MANIFEST file is created in TSI, it
should be written to a temp file, then
atomically renamed, to avoid overwriting
the existing file only to fail on the
later write.
closes https://github.com/influxdata/influxdb/issues/23536
(cherry picked from commit 061cf55f2ac6c918b219d15e659bd51416d1c52b)
closes https://github.com/influxdata/influxdb/issues/23538
=> fix: create TSI MANIFEST files atomically (#23539)

.circleci/config.yml, .circleci/scripts/get-version, .circleci/scripts/sign-packages
=> chore: Publish Packages and CHANGELOG.md to S3 (1.9)

.circleci/config.yml
=> chore: disable nightly docker tag for 2.0

pkger/README.md
=> chore(pkger): fix typo in README.md

.circleci/config.yml
This upgrades musl to 1.2.3 which resolves some security vulnerabilities.
=> feat: upgrade musl to 1.2.3 (1.9)

.circleci/config.yml
This upgrades musl to 1.2.3 which resolves some security vulnerabilities.
=> feat: upgrade musl to 1.2.3 (1.x)

dbrp/service.go, dbrp_mapping.go, influxql/v1tests/server_test.go, testing/dbrp_mapping.go, v1/coordinator/shard_mapper.go, v1/coordinator/shard_mapper_test.go, v1/coordinator/statement_executor_test.go
=> fix: fix DBRP FindMany, make virtual bucket default if not overridden

scripts/ci/CHANGELOG_frozen.md
Updates CHANGELOG for 2.4.0 release.
=> chore: update CHANGELOG_frozen.md for 2.4

http/notification_rule.go, sqlite/sqlite.go
- Closes https://github.com/influxdata/edge/issues/293 and https://github.com/influxdata/edge/issues/295
=> fix: several minor quality issues

scripts/fetch-ui-assets.sh
Updates the UI to the latest code in UI master.
This brings the UI up to parity with the Cloud UI.
=> feat: unpin ui to point at latest

scripts/fetch-ui-assets.sh
=> feat: bump to latest UI

CONTRIBUTING.md
Cleanup headings and instructions in CONTRIBUTING.md.
Make instructions sequential and remove duplication.
Add explanation for sample commands and expected output.
Documentation
=> docs: cleanup CONTRIBUTING.md - clarify instructions and output.

services/httpd/handler.go
closes https://github.com/influxdata/influxdb/issues/23793
=> feat: add version number to debug/vars

dbrp/service.go, testing/dbrp_mapping.go, v1/coordinator/shard_mapper.go, v1/coordinator/shard_mapper_test.go, v1/coordinator/statement_executor_test.go
- Closes #23620
Querying virtual dbrp mappings would lead to an error, this resolves the error.
=> fix: fixes an error querying virtual dbrps

services/httpd/handler.go
closes https://github.com/influxdata/influxdb/issues/23793
(cherry picked from commit d862a8251573cfbe9551f5b9bcfe774d6fbc9b83)
closes https://github.com/influxdata/influxdb/issues/23794
=> feat: add version number to debug/vars (#23795)

.circleci/package/control/postinst, .circleci/package/fs/usr/lib/influxdb/scripts/influxdb.service, .circleci/scripts/build-package
Reverts influxdata/influxdb#23683
=> Revert "fix: set limited permissions on package installs"

influxql/query/statement_rewriter.go, influxql/query/statement_rewriter_test.go
Use the _fieldKeys system iterator
- Closes #23872
- Closes #23876
=> fix: Optimize SHOW FIELD KEY CARDINALITY

services/httpd/handler.go, services/httpd/handler_test.go
Fix URL processing for V2 buckets API, add error checking.
(cherry picked from commit 636fbb3f79f26784eec1ad40d9bad9f1b0f1cc12)
=> fix: :db/:rp -> :dbrp, fixed create bucket, update bucket (#23898)

tsdb/shard.go
Fix an trace message that incorrectly shows
an error occurring.
=> chore: fix trace message text

cmd/influxd/inspect/inspect.go, cmd/influxd/inspect/type_conflicts/check_schema.go, cmd/influxd/inspect/type_conflicts/merge_schema.go, cmd/influxd/inspect/type_conflicts/schema.go, cmd/influxd/inspect/type_conflicts/schema_test.go
- Closes #23894
Adds commands for checking if there any type conflicts in a shard and merging the resulting schema.
=> feat: port check-schema and merge-schema from 1.x

cmd/influxd/inspect/inspect.go, cmd/influxd/inspect/report_db/aggregators/aggregators.go, cmd/influxd/inspect/report_db/aggregators/aggregators_test.go, cmd/influxd/inspect/report_db/report_db.go, cmd/influxd/inspect/report_tsm/report_tsm.go, pkg/reporthelper/walkshards.go
=> feat: port report-db command from 1.x

.github/CODEOWNERS
The code owners file no longer matched the org structure.
=> chore: cleanup codeowners file

cmd/influx_inspect/type_conflicts/type_conflicts.go
- Backport of https://github.com/influxdata/influxdb/pull/23921/commits/93090a020e9dafc69ec8248513e62e7f5c8355d0
=> fix: add warning if fields.idxl is encountered

gather/prometheus.go
- Closes #23379
NaN was not properly handled for float64 converted values.
=> fix: handle NaN in scraper

scripts/fetch-ui-assets.sh
- Will individually close related Issues with a note about the release.
At some point in the UI development, a regression was introduced to Dashboard behavior and performance. This PR reverts the UI to a commit prior to that to regain the correct behavior.
- Recommended to upgrade if reliant on Dashboard functionality
- Check the PR title: we should be able to …
=> fix: Pin UI to older version to address Dashboard issues

scripts/fetch-ui-assets.sh
This PR pins the UI to a version that should resolve the Dashboard page crashes. It also Closes #23993 by restoring the All Access Token functionality.
=> fix: Update UI to resolve Dashboard crash

go.mod, go.sum
- Closes https://github.com/influxdata/edge/issues/372
=> chore: Bump aws dependency due to dependabot alert.

tsdb/store.go
- Closes #
Examples:
API changes
- …
=> chore: add additional error logging when deleting shard

replication.go, replications/service.go, replications/service_test.go
The previous field naming didn't accurately communicate what each field represented. This PR aims to address that.
API changes
=> fix: rename replication fields for better clarity

scripts/fetch-ui-assets.sh
This pulls in the latest UI fixes including the operator token after onboarding and removal of some Cloud branding.
=> chore: update UI to latest version

go.mod, go.sum
- Closes #
Examples:
API changes
- …
=> build(flux): update flux to v0.194.0

go.mod, go.sum
Upgrades Flux to the latest version, which includes improved error handling for invalid UTF-8 in Flux.
https://github.com/influxdata/flux/pull/5409
This is just a routine update of Flux.
Non-user facing and non-breaking change to Flux implementation.
=> build(flux): update flux to v0.194.1

scripts/fetch-ui-assets.sh
=> fix: update ui to remove new data explorer

annotations/service.go, authorizer/authorize.go, authz.go, v1/authorization/mock_tenant.go
- Closes #
Examples:
API changes
- …
=> chore: fix function name in comment

go.mod, go.sum
Update the flux version to v0.194.4.
=> build(deps): upgrade flux to v0.194.4

.circleci/package/control/postinst
=> fix: only execute "init_config" on install (2.5)

.circleci/scripts/package/influxdb2/control/postinst
=> fix: only execute "init_config" on install (2.7)

scripts/ci/perf-tests/iot.yaml, scripts/ci/run_perftest.sh
This should make CI work properly again.
=> fix: update broken flux and perf tests (main-2.x)

tsdb/engine/tsm1/wal.go
feat(tsm1/wal): encapsulate expiring WAL files in FileDisposer
This changeset introduces an interface extension point named
FileDisposer to control what to do with WAL files when they are no
longer needed. Currently, the only implementation is to delete the file
which is the existing behavior.
=> feat(tsm1/wal): encapsulate expiring WAL files in FileDisposer

.circleci/config.yml, .circleci/scripts/package/requirements.txt
* chore: update ubuntu to 2204:current
* fix: install asciidoc with pip
(cherry picked from commit 70acbd58a8a6c1beb280509708c0ef93e8604192)
Closes #24674
=> fix: correct dependencies in package builds

go.mod, go.sum
=> fix: update logrus to 1.9.3

Dockerfile, Dockerfile.dockerignore
This will fix CI on Main from changes in #24714 that does not run on PRs for the build.
=> fix: Readd the Dockerfile for the main branch

docker/Dockerfile.ci, docker/Dockerfile.ci.dockerignore, docker/entrypoint.sh
Hopefully the last thing we need for CI to go back to green
=> fix: Add docker folder back for CI

Cargo.lock, influxdb3_server/src/service.rs
=> docs: add docs to hybrid service code

.cargo/config, .circleci/config.yml
I also moved the environment variable logic into a script within the cross-compiler to help clean things up.
=> chore: implement musl builds

influxdb3/tests/server/auth.rs, influxdb3_server/src/http.rs, influxdb3_server/src/lib.rs, influxdb3_server/src/service.rs, influxdb3_write/src/lib.rs, influxdb3_write/src/write_buffer/mod.rs
=> chore: fix some typos

tsdb/store.go
Avoid unnecessarily deleting series from the series file
Log all errors on shard deletion
Closes https://github.com/influxdata/influxdb/issues/24834
(cherry picked from commit 8ff06d5a92ca3a0a34b31bfa9d37e6cff72a58a3)
closes https://github.com/influxdata/influxdb/issues/24836
=> fix: improved shard deletion (#24602)

tsdb/store.go
Avoid unnecessarily deleting series from the series file Log all errors on shard deletion
Closes https://github.com/influxdata/influxdb/issues/24834
(cherry picked from commit 8ff06d5a92ca3a0a34b31bfa9d37e6cff72a58a3)
closes https://github.com/influxdata/influxdb/issues/24836
(cherry picked from commit 2066c4be46a9048b0ccc0696b340a4ecc2d0281b)
closes https://github.com/influxdata/influxdb/issues/24837
=> fix: improved shard deletion (#24602) (#24844)

influxdb3/tests/server/write.rs
There is no issue for this. Some tests were recently broken by the PRs I merged. This fixes that.
=> fix: tests that were broken with recent merges

cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, cmd/influxd/recovery/user/user_test.go, cmd/influxd/upgrade/upgrade.go, kit/platform/errors/error_user.go, session/http_server.go, tenant/service.go, tenant/service_onboarding_test.go, tenant/service_user.go, tenant/service_user_test.go, tenant/storage_user.go, tenant/storage_user_test.go, testing/passwords.go, v1/authorization/authorizer_test.go, v1/authorization/caching_password_service_test.go, v1/authorization/service.go, v1/authorization/service_password.go
Allow password length and character class checking.
closes https://github.com/influxdata/influxdb/issues/24856
=> feat: add optional stricter password requirements

tenant/service_user.go
Changes to make password strength
computations closer to constant
closes https://github.com/influxdata/influxdb/issues/24886
=> fix: additional constant time code

influxdb3_load_generator/analysis/README.md, influxdb3_load_generator/analysis/app.py, influxdb3_load_generator/analysis/templates/index.html
Adds a basic Flask and single page web application to compare the results of two load generator runs. Details in readme.
Here's a screenshot of it in action: ![Screenshot 2024-04-04 at 7 37 12 PM](https://github.com/influxdata/influxdb/assets/4331/c2eef001-d969-4790-875d-2076e4d28c94)
=> feat: add basic load generator comparison app

cmd/influxd/launcher/cmd.go, cmd/influxd/launcher/launcher.go, cmd/influxd/recovery/user/user_test.go, cmd/influxd/upgrade/upgrade.go, kit/platform/errors/error_user.go, session/http_server.go, tenant/service.go, tenant/service_onboarding_test.go, tenant/service_user.go, tenant/service_user_test.go, tenant/storage_user.go, tenant/storage_user_test.go, testing/passwords.go, v1/authorization/authorizer_test.go, v1/authorization/caching_password_service_test.go, v1/authorization/service.go, v1/authorization/service_password.go
Allow password length and character class checking.
closes https://github.com/influxdata/influxdb/issues/24856
(cherry picked from commit 7d8884beca1586a38b60a1aae9a0eb4f0461b123)
closes https://github.com/influxdata/influxdb/issues/24884
=> feat: add optional stricter password requirements (#24857)

tenant/service_user.go
closes https://github.com/influxdata/influxdb/issues/24886
(cherry picked from commit 31753c3c9e8871bb5fad01c67128b3374425af03)
closes https://github.com/influxdata/influxdb/issues/24888
=> fix: additional constant time code (#24887)

v1/services/meta/client.go
This adds locking to the load method and renames it to Reload(). This method replaces the cached data from the underlying kv.Store and needs a write lock. The restore api uses it and may have been an issue with concurrent writes into the cached data during a restore.
* fixes #24895
* Closes #24895
=> fix(meta.Client): add write lock to Load method ok kv store client

influxdb3_write/src/write_buffer/mod.rs
This adds an in memory Parquet cache to the WriteBuffer. With this we now have a cache that Parquet files will be queried from when a query does come in. Note this change *does not* actually let us persist any data. This merely adds the cache. Future changes will add the ability to cache the data as well as the logic around what should be cached.
As this doesn't allow any data to be cached or queried a test has not been added at this time, but will in future PRs.
Closes #24897
=> feat: Add and hook in an in memory Parquet cache

Cargo.lock, influxdb3_write/Cargo.toml, influxdb3_write/src/cache.rs, influxdb3_write/src/lib.rs, influxdb3_write/src/paths.rs, influxdb3_write/src/persister.rs, influxdb3_write/src/write_buffer/buffer_segment.rs, influxdb3_write/src/write_buffer/mod.rs, influxdb3_write/src/write_buffer/segment_state.rs
=> feat: implement parquet cache persistance

influxdb3_write/src/lib.rs, influxdb3_write/src/wal.rs, influxdb3_write/src/write_buffer/mod.rs
=> refactor: cleanup unused methods in Bufferer trait

query/iterator.go, query/iterator_test.go
This is actually the second fix for
https://github.com/influxdata/influxdb/issues/20238 
for when the time zone falls back in autumn.
closes https://github.com/influxdata/influxdb/issues/25078
=> fix: GROUP BY queries with offset that crosses a DST boundary fail.

task/backend/scheduler/scheduler_test.go, task/backend/scheduler/treescheduler.go
Avoid converting times to int64 in the Task Scheduler to preserve 
time zone information. This corrects a failure after fall back time 
changes which halts every-type tasks
closes https://github.com/influxdata/influxdb/issues/25110
=> fix: preserve time zone information in Task Scheduler

Cargo.lock, Cargo.toml
=> chore: update object_store to 0.10.2

influxdb3_wal/src/object_store.rs, influxdb3_write/src/write_buffer/mod.rs
This fixes the WAL so that it will skip persisting a file and notifying the file notifier if the wal buffer is empty.
=> fix: wal skip persist and notify if empty buffer

scripts/fetch-ui-assets.sh
Pulls in UI 2.7.9 which is based off of the releases/OSS branch, not master. Includes only the one commit to update the templates.
=> fix: Update UI to v2.7.9

influxdb3_catalog/src/catalog.rs, influxdb3_write/src/write_buffer/mod.rs, influxdb3_write/src/write_buffer/queryable_buffer.rs
This builds on top of #25236 so I have it merging into that branch. Can change that up if it doesn't make sense.
Closes #25217
=> feat: Only persist Catalog on snapshot if it has been updated

go.mod, go.sum
=> build(flux): update flux to v0.195.2

flux/stdlib/universe/bare_aggregate_test.flux, tsdb/index/tsi1/partition.go, tsdb/index/tsi1/partition_test.go
Cherry picks in #24613 
Had to resolve a few merge conflicts as well
=> fix(tsi1/partition/test): fix data race in test code

Cargo.lock, Cargo.toml
- version changed from 1d5011bde4c343890bb58aa77415b20cb900a4a8 to 1eaa4ed5ea147bc24db98d9686e457c124dfd5b7
=> chore: update core dependency revision

influxdb3/src/commands/serve.rs, influxdb3_server/src/query_executor.rs, influxdb3_wal/src/lib.rs, influxdb3_wal/src/object_store.rs, influxdb3_wal/src/snapshot_tracker.rs, influxdb3_write/src/lib.rs, influxdb3_write/src/write_buffer/mod.rs, influxdb3_write/src/write_buffer/validator.rs
=> refactor: Rename level 0 to gen1 to match compaction wording

tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/wal.go, tsdb/index.go, tsdb/shard.go, tsdb/store.go, tsdb/store_test.go
Improve error messages and logging during shard opening.
(cherry picked from commit 23008e5286d0161a6add86e5676ee633871c1d45)
Closes: #25320
=> chore: improve error messages and logging during shard opening

influxdb3_write/src/lib.rs, influxdb3_write/src/write_buffer/mod.rs, influxdb3_write/src/write_buffer/queryable_buffer.rs
=> feat: add watch to writebuffer for persisted snapshots

.circleci/config.yml
Closes https://github.com/influxdata/influxdb/issues/25355
=> fix(ci): Update test_pkgs_64bit image to non-eol ubuntu image

.circleci/config.yml, go.mod
Upgrade to go1.22.7.
Closes: #25363
=> chore: upgrade to go1.22.7

.circleci/config.yml, go.mod
=> feat(ci): Update master-1.x to go1.22.7

tsdb/engine/tsm1/engine.go
Closes #25267
Add RWMutex lock for `seriesKeys` slice.
@davidby-influx
=> fix(tsm1): Fix data race of seriesKeys in deleteSeriesRange

.circleci/config.yml
=> chore(ci): push releases to dl.influxdata.com (1.11)

influxdb3_telemetry/src/bucket.rs, influxdb3_telemetry/src/sampler.rs, influxdb3_telemetry/src/sender.rs, influxdb3_telemetry/src/stats.rs, influxdb3_telemetry/src/store.rs
Added more docs for the telemetry crate
=> chore: udpate docs for the telemetry crate

influxdb3_catalog/src/catalog.rs, influxdb3_write/src/write_buffer/queryable_buffer.rs
I accidentally merged #25388 before I should have because the lint was failing. I don't know why I was not blocked from doing so though 😬
=> fix: lint fixes for #25388

influxdb3_write/src/parquet_cache/mod.rs
Small PR to upstream changes that were needed in Pro.
=> feat: expose path used by cache request

scripts/fetch-ui-assets.sh
Upgrade UI assets package to OSS 2.7.10.
Closes: #25500
=> chore: upgrade ui assets package to 2.7.10

tsdb/store.go, tsdb/store_test.go
Check for uncommitted WRR segments during startup and abort startup if found.
Closes: #25503
=> feat: check for uncommitted WRR segments during startup

services/subscriber/http.go, services/subscriber/service.go, services/subscriber/service_test.go, services/subscriber/udp.go
Print the subscription name, destination,
retention policy, and database on errors in subscription writes
closes https://github.com/influxdata/influxdb/issues/25518
=> feat: improve logging for subscriptions

influxdb3_wal/src/object_store.rs, influxdb3_write/src/write_buffer/mod.rs
Closes #25569 
Only take a snapshot on replay if the snapshot id is greater than the newest snapshot that is being restored from.
=> fix: don't rebuild snapshot if it has already been taken.

cmd/influxd/inspect/build_tsi/build_tsi.go
(cherry-picked from 75eb209f7205f46d3a00e93bce116112575cbb44)
closes https://github.com/influxdata/feature-requests/issues/612
=> feat(buildtsi): Adds log for rebuild TSI completion

cmd/influxd/inspect/build_tsi/build_tsi.go
(cherry picked from commit 75eb209f7205f46d3a00e93bce116112575cbb44)
closes https://github.com/influxdata/feature-requests/issues/612
(cherry picked from commit edbb55777e8f05b7731a0c0e01fdf5d01607d275)
=> feat(buildtsi): Adds log for rebuild TSI completion (#25576)

.circleci/config.yml, go.mod
Upgrade go to 1.22.7
[Closes #](https://github.com/influxdata/edge/issues/741)
=> feat: Upgrade go to 1.22.7

.circleci/config.yml, go.mod
* feat: Upgrade go to 1.22.7
(cherry picked from commit 514e24752c6870695c4b361fe0aca5a80f0fbc49)
=> feat: Upgrade go to 1.22.7 (#25586)

influxdb3_cache/src/meta_cache/mod.rs, influxdb3_cache/src/meta_cache/table_function.rs
=> refactor: display column names for predicates in EXPLAIN for metadata cache

influxdb3_cache/src/meta_cache/provider.rs, influxdb3_write/src/write_buffer/queryable_buffer.rs
=> feat: remove metadata caches on db and table delete

Cargo.lock, influxdb3/Cargo.toml, influxdb3/src/commands/serve.rs, influxdb3_server/Cargo.toml, influxdb3_server/src/lib.rs, influxdb3_server/src/query_executor.rs, influxdb3_server/src/system_tables/mod.rs, influxdb3_sys_events/Cargo.toml, influxdb3_sys_events/src/lib.rs
closes: https://github.com/influxdata/influxdb/issues/25581
=> feat: sys events buffer added

influxdb3_cache/src/meta_cache/cache.rs, influxdb3_cache/src/meta_cache/mod.rs, influxdb3_cache/src/meta_cache/table_function.rs
Closes #25647
* Utilize the `LIMIT` provided to the `TableProvider::scan` from the query when producing records from the metadata cache.
* This also displays the `limit=<value>` in the `MetaCacheExec` in the `EXPLAIN` plan when provided (this can be seen in one of the tests that checks the `EXPLAIN` output).
=> feat: support `LIMIT` in metadata cache

influxdb3_catalog/src/catalog.rs
=> fix: do not count deleted dbs and tables toward limit

influxdb3_server/src/query_executor/mod.rs, influxdb3_server/src/system_tables/mod.rs, influxdb3_server/src/system_tables/parquet_files.rs
This PR also updates the tests to check for correct behaviour on queries to the system.parquet_files table.
Closes #25732
=> feat: remove table_name clause requirement for `system.parquet_files` table

influxdb3_wal/src/object_store.rs
=> feat: Add info log to wal replay

influxdb3_write/src/write_buffer/mod.rs
Closes #25736
See also: https://github.com/influxdata/influxdb_pro/pull/348
=> feat: table creation also creates db if it does not exist

influxdb3/src/commands/serve.rs, influxdb3_telemetry/src/sender.rs
closes: https://github.com/influxdata/influxdb3_hub/issues/5
=> feat: use custom domain name for telemetry

influxdb3/src/commands/disable.rs, influxdb3/src/commands/enable.rs, influxdb3/src/main.rs, influxdb3/tests/server/cli.rs, influxdb3_client/src/lib.rs, influxdb3_processing_engine/src/lib.rs, influxdb3_processing_engine/src/manager.rs, influxdb3_server/src/http.rs
Mostly a bunch of renames, but also a little fix to make a test less flakey.
Closes #25789
=> refactor: rename plugin activate/deactivate to enable/disable

influxdb3/src/commands/test.rs, influxdb3/tests/server/cli.rs, influxdb3_processing_engine/src/plugins.rs, influxdb3_py_api/src/system_py.rs
No issue for this, just a grab bag of little changes based on feedback.
* Add uint64_field to LineBuilder
* Add bool_field to LineBuilder
* Change query_rows to query in Python API
* Update error output for test wal_plugin
=> feat: Updates to plugin API

Cargo.lock, influxdb3_internal_api/Cargo.toml, influxdb3_internal_api/src/query_executor.rs, influxdb3_server/src/lib.rs, influxdb3_server/src/query_executor/mod.rs, influxdb3_server/src/system_tables/mod.rs
See https://github.com/influxdata/influxdb_pro/pull/437
=> chore: bring back enterprise changes

influxdb3_write/src/write_buffer/mod.rs
No issue. I broke `main`, this fixes it, sorry about that.
=> chore: fix main

influxdb3_catalog/src/catalog.rs
No issue. Backporting changes from https://github.com/influxdata/influxdb_pro/pull/491
=> chore: backport change from enterprise

influxdb3_server/src/http.rs
In #25927 we missed that JSON queries were broken despite having some tests use the format. This fixes JSON queries such that they now properly contain a comma between RecordBatches. This commit also includes tests for the formats that now stream data back (CSV, JSON, and JSON Lines) so that we won't run into this issue again.
=> fix: broken format for JSON queries and add tests

install_influxdb.sh, install_influxdb3.sh
Fixes an issue in the install script for the node id for Docker
=> fix: docker command was wrong

tsdb/engine/tsm1/compact.go
This pr adds err handling for branch that did not specify os file removal errors previously.
=> feat: Add error joins/returns

install_influxdb.sh
Slight wording update to clarify that Docker/simple download are both as powerful now that Processing Engine is included.
=> chore: slight wording update

influxdb3/src/commands/serve.rs
Official builds built with python build standalone currently only work with pip. Until https://github.com/influxdata/influxdb/issues/26016 is decided upon, prefer pip instead of uv.
=> fix: prefer pip over over uv

influxdb3/src/commands/common.rs, influxdb3/src/commands/create.rs
Fixes https://github.com/influxdata/influxdb/issues/26084
=> fix: allow equal sign in plugin trigger arguments

tsdb/engine/tsm1/compact.go, tsdb/engine/tsm1/compact_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go
Also fixes error type checks in 
TestCompactor_CompactFull_InProgress
=> chore: add logging to Filestore.purger

tsdb/engine/tsm1/compact.go, tsdb/engine/tsm1/compact_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go
Also fixes error type checks in
TestCompactor_CompactFull_InProgress
(cherry picked from commit 2ab5aad52e9e7a38fa6cfef49156c2055d51eefc)
=> chore: add logging to Filestore.purger (#26089)

influxdb3_processing_engine/src/plugins.rs
In #26086 the looping behavior for write batches could go into an infinite loop. I discovered this while getting the tests working on #26087, so once we get that merged we'll be able to avoid regressions.
=> fix(processing_engine): fix retry behavior on batches to try individual batch.

.circleci/config.yml, Dockerfile, README_processing_engine.md, deny.toml, influxdb3/Cargo.toml, influxdb3/src/commands/serve.rs, influxdb3/src/main.rs, influxdb3/tests/cli/mod.rs, influxdb3/tests/server/mod.rs, influxdb3/tests/server/packages.rs, influxdb3_processing_engine/Cargo.toml, influxdb3_processing_engine/src/environment.rs, influxdb3_processing_engine/src/lib.rs, influxdb3_processing_engine/src/plugins.rs, influxdb3_py_api/Cargo.toml, influxdb3_py_api/src/lib.rs, influxdb3_server/Cargo.toml, influxdb3_server/src/http.rs, influxdb3_write/Cargo.toml
This removes the system-py feature, now requiring some discoverable python to build.
=> feat: remove system-py

README.md
=> feat: Update README with beta info

influxdb3_catalog/src/object_store.rs
When starting up a new cluster in Enterprise we might have multiple nodes starting at the same time. We might have an issue wherby we have multiple catalogs with different UUIDs in their in memory representation.
For example:
- Let's say we have node0 and node1
- node0 and node1 start at the same time and both check object storage to see if there is a catalog to load
- They both see there is no catalog
- They both create a new one by generating a UUID and persisting it to object storage
- Whichever is written second is now the one with the correct UUID in their in memory representation while the other will not have the correct one until restarted likely
This in practice isn't an issue today as Trevor notes in https://github.com/influxdata/influxdb_pro/issues/600, but it could be once we …
=> fix: Prevent Catalog UUID races for new nodes

Cargo.lock, Cargo.toml
=> chore: release beta 2

.circleci/config.yml
Port #24491 and #25535 to 1.12.
Clean cherry-pick of #26190 from master-1.x to 1.
(cherry picked from commit 61f21c5adb87e84f673645bcdfe26005d897706a)
=> chore(ci): push artifiacts to public bucket

influxdb3_cache/src/parquet_cache/mod.rs
This cleans up some tracing statements in the parquet cache code by changing `DEBUG` to `TRACE` for log messages that were a bit too verbose when running queries in `DEBUG` logging mode.
No issue for this.
=> chore: cleanup tracing from cache crate

influxdb3/src/commands/serve.rs
Added an additional check in the serve command to ensure that the frontend has shutdown before exiting so that we don't close any connections pre-emptively.
There is no issue for this but I added this after seeing the test added in #26203 fail in CI [here](https://app.circleci.com/pipelines/github/influxdata/influxdb/45038/workflows/212d98e6-6273-4349-999b-6fd3f56f6cfc/jobs/426660?invite=true#step-110-90344_65).
=> fix: additional check on frontend shutdown

influxdb3/tests/cli/mod.rs, influxdb3_py_api/src/system_py.rs
This handles some issues folks were seeing with returning data from the .query() call in the `PyPluginCallApi`.
=> fix(processing_engine): properly extract data from DictionaryArrays

Cargo.lock, Cargo.toml, deny.toml, influxdb3_processing_engine/Cargo.toml, influxdb3_py_api/Cargo.toml, influxdb3_server/Cargo.toml, influxdb3_write/Cargo.toml
- remove humantime ignore in deny.toml
- update pyo3 to use 0.24.1 (https://rustsec.org/advisories/RUSTSEC-2025-0020.html)
=> chore: couple of updates to fix cargo audit job

influxdb3_catalog/src/catalog.rs
The `exists` method on the catalog Repository type was split into `id_exists`, which only checks for the existence of `id` (for updation) and `id_and_name_exists`, which checks for the existence of _both_ the `id` and the `name` of the resource (for insertion).
Having a single method for both was difficult to reason about and may have led to unexpected behaviour when we get to renaming of resources.
No issue for this.
=> refactor: split existence check to two method in Repository

Cargo.lock
Failure - https://app.circleci.com/pipelines/github/influxdata/influxdb/45188/workflows/5059b8f3-5786-4cf9-a734-1e5ab7362bab/jobs/428101
=> chore: update crossbeam-channel, fixes cargo-audit failure

influxdb3/src/commands/delete.rs, influxdb3/tests/cli/mod.rs, influxdb3/tests/server/configure.rs
No issue. Fixing the build after some regressions were introduced with latest merge.
=> fix: build after some merge regressions

influxdb3_catalog/src/log/versions/v2.rs, influxdb3_processing_engine/src/lib.rs, influxdb3_processing_engine/src/plugins.rs
Back-port changes from https://github.com/influxdata/influxdb_pro/pull/711
=> chore: back-port changes from enterprise

influxdb3/src/help/serve.txt, influxdb3/src/help/serve_all.txt
=> docs: fix typos in help text

Cargo.lock, Cargo.toml
=> chore: version bump to release 3.0

.circleci/config.yml
Pulls our enterprise release steps and copy them over to OSS to resolve current problems with package publishing.
=> fix: Modify package publishing to fix slack msg & publish_packages

Cargo.lock, influxdb3/src/commands/serve.rs, influxdb3/tests/cli/mod.rs, influxdb3_catalog/Cargo.toml, influxdb3_catalog/src/catalog.rs, influxdb3_catalog/src/catalog/update.rs, influxdb3_catalog/src/error.rs, influxdb3_catalog/src/log/versions/v1/conversion.rs, influxdb3_catalog/src/log/versions/v2.rs, influxdb3_process/src/lib.rs, influxdb3_server/src/http.rs, influxdb3_server/src/lib.rs, influxdb3_types/Cargo.toml, influxdb3_types/src/http.rs
Backport of https://github.com/influxdata/influxdb_pro/pull/762
=> chore: back-port changes from influxdb_pro#762

influxdb3/src/commands/create.rs, influxdb3/src/commands/create/token.rs, influxdb3_server/src/system_tables/tokens.rs
This is a port of https://github.com/influxdata/influxdb_pro/pull/780 just to get the types and machinery around tokens aligned
=> refactor: port changes from enterprise

influxdb3/src/commands/serve.rs, influxdb3_telemetry/src/sender.rs, influxdb3_telemetry/src/store.rs
closes: https://github.com/influxdata/influxdb_pro/issues/764
=> feat: add `cluser_uuid`/`catalog_uuid` to telemetry

Cargo.lock, Cargo.toml
Updates the version to `3.0.2`.
=> chore: version bump to 3.0.2

install_influxdb.sh
Updates for 3.0.2 -- to be merged after release
=> chore: update install_influxdb.sh

CONTRIBUTING.md, README.md
Related to #26362
I think there are likely more details to work out in the `System dependencies` section, but this PR is a starting point to iterate on.
=> docs: add Building from source section to CONTRIBUTING.md

Cargo.lock, Cargo.toml, influxdb3/Cargo.toml, influxdb3/src/commands/serve.rs
Part of #26226
This leverages the `object_store_metrics` crate from IOx/`influxdb3_core` to expose a set of metrics (see **Sample Metrics** below) for observing request latencies and bytes transfered to/from the object store.
We need to do upstream work in IOx to add `bucket` and `file_type` labels to the reported metrics:
* https://github.com/influxdata/influxdb_iox/issues/14277
* https://github.com/influxdata/influxdb_iox/issues/14278
<details><summary><h3>Sample Metrics</h3></summary>
<p>
```
object_store_op_duration_seconds_bucket{op="copy",result="error",store_type="main",le="0.001"} 0
object_store_op_duration_seconds_bucket{op="copy",result="error",store_type="main",le="0.0025"} 0
object_store_op_duration_seconds_bucket{op="copy",result="error",store_type="main",le="0.005"} 0 …
```
=> feat: track object store metrics

influxdb3_cache/src/last_cache/cache.rs
These will be used in Enterprise for ongoing work.
=> chore: Increase the visibility of some APIs to the crate

influxdb3_cache/src/last_cache/cache.rs
This removes the use of `VecDeque::pop_back` from the LVC and uses `VecDeque::truncate` instead so that it ensures that the cache is at its desired size.
The eviction routine was also adjusted to do a single scan/truncate vs. iterating over elements and popping them one by one.
There was no issue for this.
=> refactor: use truncate in lvc to ensure elements removed

scripts/fetch-ui-assets.sh
chore: update UI to OSS-v2.7.12
=> chore: update UI to OSS-v2.7.12

Cargo.lock, influxdb3/src/commands/serve.rs, influxdb3_catalog/Cargo.toml, influxdb3_catalog/src/catalog.rs, influxdb3_server/src/lib.rs, influxdb3_server/src/query_executor/mod.rs, influxdb3_telemetry/src/lib.rs, influxdb3_telemetry/src/sampler.rs, influxdb3_telemetry/src/sender.rs, influxdb3_telemetry/src/store.rs
closes: https://github.com/influxdata/influxdb/issues/26285
=> feat: add trigger count to telemetry

RELEASE.md
Made some adjustments to `RELEASE.md` after doing the `3.0.3` release.
=> docs: update release.md with additional details

influxdb3_cache/src/distinct_cache/cache.rs
Exports some APIs necessary to support future work in Pro.
=> chore: Export APIs necessary for future work in Pro

influxdb3_catalog/src/catalog.rs
There was no issue for this.
The main types in the `catalog.rs` module in the `influxdb3_catalog` crate were undocumented. This adds docs to the types that comprise the catalog.
=> docs: add rust docs to catalog types

influxdb3_catalog/src/catalog.rs, influxdb3_load_generator/src/main.rs, influxdb3_processing_engine/src/plugins.rs, influxdb3_server/src/http.rs, influxdb3_write/src/lib.rs, rust-toolchain.toml
Changes were due to a number of clippy improvements.
=> chore: Update rust toolchain to 1.87.0

influxdb3_catalog/src/catalog/update.rs
Opening this as a fast follow for #26479 since there were some comments that came after merge of that PR.
=> chore: address a couple post-merge PR comments

tsdb/engine/tsm1/engine.go
Previously
```go
// StartOptHoldOff will create a hold off timer for OptimizedCompaction
func (e *Engine) StartOptHoldOff(holdOffDurationCheck time.Duration, optHoldoffStart time.Time, optHoldoffDuration time.Duration) {
startOptHoldoff := func(dur time.Duration) {
optHoldoffStart = time.Now()
optHoldoffDuration = dur
e.logger.Info("optimize compaction holdoff timer started", logger.Shard(e.id), zap.Duration("duration", optHoldoffDuration), zap.Time("endTime", optHoldoffStart.Add(optHoldoffDuration)))
}
startOptHoldoff(holdOffDurationCheck)
}
```
was not passing the data by reference which meant we were never modifying the `optHoldoffDuration` and `optHoldoffStart` vars.
This PR also adds additional logging to Optimized level 5 compactions to clear up a little bit of confusion around log …
=> feat: Add new logging for compaction level 5 and remove bug with opt holdoff time (#26488)

tsdb/engine/tsm1/compact.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go
Streamline compaction logging, while
providing more information to debug 
remnant temporary files.
=> chore: improve logging on compaction failures

tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/scheduler.go
Adds trace logging at debug level to
the compaction scheduler
=> chore: add trace logging to compaction scheduler

tsdb/engine/tsm1/engine.go
I've added additional debug level logging that is dependent on having available compaction groups. I've found a few areas of the code to possible "jam" up compactFull.
=> chore: Adds additional debug level logging for compaction

influxdb3_write/src/lib.rs
This is a reproducer for an issue that will need to be resolved upstream in `influxdb_iox`.
Tags with `/` in the name will break the primary key produced by `Schema::primary_key` when using the `v3` series key functions in the `schema` crate.
Failure in CI: [link](https://app.circleci.com/pipelines/github/influxdata/influxdb/46181/workflows/3ae973d3-a402-429e-98f2-46872f9d01a1/jobs/439117?invite=true#step-110-87177_27).
=> test: reproducer for tags with slashes break primary key

install_influxdb.sh
Updates script to be more clear on instructions for Docker, as well as giving more clarity to pulling InfluxDB 3 Explorer. This will likely be updated more in the next week.
=> chore: update script with clarifications

influxdb3_catalog/src/catalog/migrations/v2.rs
* fix: Ensure catalog UUID is preserved during migration
=> chore: Port changes from Enterprise

influxdb3_catalog/src/catalog/migrations/v2.rs, influxdb3_server/src/http.rs, influxdb3_server/src/lib.rs, influxdb3_write/src/write_buffer/mod.rs, influxdb3_write/src/write_buffer/validator.rs
Cherry pick b85f938f7c and 3e7f7d5ac3 from `main` for 3.4.1 release.
=> chore: cherry pick `b85f938f7c` and `3e7f7d5ac3`

Cargo.lock, Cargo.toml
Update release version to 3.4.1
=> chore: Update release version

CHANGELOG.md
=> chore: update CHANGELOG link

install_influxdb.sh
=> chore: Update InfluxDB version to 3.4.2

tsdb/store.go
(cherry picked from commit eab8a8a6e83c3142d11a464df13a99b9b6bdfea5)
=> fix: add locking in ClearBadShardList (#26423)

influxdb3_clap_blocks/src/object_store.rs
backported from https://github.com/influxdata/influxdb_pro/pull/1384
closes: https://github.com/influxdata/influxdb_pro/issues/1382
=> fix: hide sensitive env vars

CHANGELOG.md
(cherry picked from commit 27b8311e63d5173290eb4eed4fb1d8e68811e0d6)
=> chore: update CHANGELOG link (#26777)

influxdb3_clap_blocks/src/object_store.rs, object_store_utils/src/retryable_object_store.rs
This is a cherry-pick of https://github.com/influxdata/influxdb/pull/26869, which backports several changes from the enterprise repo:
* fix: RetryableObjectStore list_with_retries
* chore: remove unnecessary block_on call from ReauthingObjectStore
* test: add more list_with_retries test cases to validate non-trivial retryable list calls
The most notable change is the bug fix to RetryableObjectStore.list_with_retries, where we now peek at the first element in order to actually know if the request needs to be retried.
Related to https://github.com/influxdata/influxdb/issues/26802 and potentially related to https://github.com/influxdata/influxdb/issues/26810.
=> fix: bug in RetryableObjectStore.list_with_retries, clean up ReauthingObjectStore

tsdb/engine/tsm1/compact_property_test.go
Adjacency testing would fail if inputs were
not sorted, because the sorting was on an
unused slice.
(cherry picked from commit f04dcda2a53bf97b5ed4b8bfcd661e849e6f4150)
=> fix: sort files for adjacency testing (#26816)

go.mod
(cherry picked from commit 803e9487f5e420ce683f43356f2547bd09c4e241)
=> feat: Updates go toolchain to 1.23.12 (#26885)
