- CHANGELOG.md
- cmd/influx/authorization.go
this PR also extends the create auth to include ability to
set the auth description
closes: #19156
> fix(influx): add missing description field to auth output

- CHANGELOG.md
- cmd/influx/backup.go
- cmd/influx/config/config.go
- cmd/influx/delete.go
- cmd/influx/main.go
- cmd/influx/ping.go
- cmd/influx/query.go
- cmd/influx/setup.go
- cmd/influx/template.go
- cmd/influx/write.go
- cmd/influx/write_test.go
> feat(influx): add active-config flag to override config on single command call

- ui/src/dashboards/components/DashboardHeader.tsx
- ui/src/shared/apis/queryCache.ts
Closes #19346
Changing the timeRange in the dashboard page does not issue a new query for the newly selected timerange
The issue here is that the system variables stored selected values differently than other variables so we are writing a condition to map system variables differently. This PR also clears the cache whenever the timerange selection is updated
> fix(system-vars-mapping): updated variable mapping for system variabes to register changes in system variables

- ui/cypress/e2e/buckets.test.ts
- ui/cypress/e2e/checks.test.ts
- ui/package.json
- ui/src/checks/components/CheckEOSaveButton.tsx
- ui/yarn.lock
Borked my earlier PR https://github.com/influxdata/influxdb/pull/19349 and using this PR instead
> chore(ui): upgrade clockface dependency to 2.3.4

- CHANGELOG.md
- ui/src/shared/utils/errors.ts
Rather than showing unhelpful HB context that would have been sent, just show the error that caused the issue.
> fix: in non cloud environments, show actual errors, rather than HB

- http/handler.go
- http/handler_test.go
- kit/transport/http/middleware.go
This was added so that we can distinguish between 4XX and 401 class
errors. It should have a minimal impact in overall cardinality.
Co-authored-by: Greg Linton  <greg@influxdata.com>
> chore(http): add response_code as label to http_api_* metrics

- storage/reads/aggregate_resultset.go
- storage/reads/aggregate_resultset_test.go
- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
- storage/reads/array_cursor.go
- storage/reads/array_cursor_gen_test.go
- storage/reads/array_cursor_test.gen.go.tmpl
- storage/reads/group_resultset.go
- storage/reads/group_resultset_test.go
- storage/reads/resultset.go
This replaces the panic that happens when attempting to create a cursor
for an unsupported aggregate type for the mean aggregate. It instead
refactors the result set so the cursor is constructed as part of the
`Next()` call and false is returned when there is an error creating the
cursor. The cursor is then accessed with `Cursor()`. When `Next()`
returns false, an error can be accessed by using `Err()`.
> feat(storage/reads): replace panic on unsupported type with an error

- kit/feature/middleware.go
- kv/task.go
- kv/task_test.go
- task.go
- task/options/options.go
- task/options/options_errors.go
- task/options/options_test.go
- task/servicetest/servicetest.go
- task_test.go
Closes influxdata/idpe#8153
This makes use of new Flux helpers to perform Task options extraction and updating using only the AST representation. We parse Flux in a few different contexts, and some of those contexts don't always have the same libraries available at evaluation time. Parsing with AST enables us to extract options from scripts that were previously problematic.
A drawback of this approach is that option values in a `option task = { ... }` statement **must be value literals** (e.g. `1m`, `"string"`, etc). Given that `option` values are already restricted in the types of identifiers that can be used in them, this seems like an acceptable trade-off.
This removes the previous (hacky) experiment of extracting Task option assignment statements from a Flux script using regular …
> feat(task): Parse Task Options using Flux AST Helpers

- ui/src/notebooks/pipes/Query/index.ts
https://github.com/influxdata/idpe/issues/8118
- Change initial height of script cells raw data from `200` to `320` which shows about 5.5 actual rows of data (not including headers)
> fix(flows): increase default height of raw data view in flux cells

- http/swagger.yml
- kv/dashboard.go
- testing/dashboards.go
Closes #19274
Problem 1: If you specify `orgID` in `filter`, then the `findDashboards` function will ignore your `limit` and `offset` in `FindOptions`.
Problem2:  It seems that the swagger document does not expose params like `limit` and `offset` now, but front-ui will use it.
> fix(api/dashboards): FindOptions not working

- CHANGELOG.md
- notification/rule/http_test.go
- notification/rule/pagerduty_test.go
- notification/rule/rule.go
- notification/rule/slack_test.go
- notification/rule/telegram_test.go
We've been witnessing some failed observations of Check triggers in Notification Tasks. In `from(start: -10m, stop: now())`, the `stop` is **exclusive** to the time range—this is so consecutive windows like `A -> B`, `B -> C`, don't have overlap. If a Notification Task's schedule boundaries align with Check trigger observations, we will miss observations if they occur on that boundary.
This change includes the left-hand boundary in what the Notification Task sees of Check triggers.
> fix(notification/rule): Include the edge of the boundary we are observing.

- tsdb/store.go
Have Store.DeleteShard() return a useful error if it cannot find the
requested shard.
Fixes #17059
Closes #17059
> fix(tsdb): Shard error on delete

- ui/src/dashboards/actions/thunks.ts
- ui/src/resources/constants/index.ts
something went out a couple days ago that started enforcing a limit of 20 dashboards if the limit was not sent to the request. there's a max of 100. this is a quick work around to unblock our customers before following up with pagination and backend changes that revert the changes
> fix: update dashboard limits to 100

- http/swagger.yml
This PR removes an unused route from the Swagger docs: `PATCH /scrapers/{scraperTargetID}/labels/{labelID}`
This because nested Label routes refer to the Label Mapping, not the Label itself. Label Mappings can only be created and deleted, not updated.
> docs: remove unused patch scraper label route from swagger

- flags.yml
- kit/feature/list.go
- kv/dashboard.go
- testing/dashboards.go
As of https://github.com/influxdata/influxdb/commit/ebaa32313be1d6b7e7c3663c38fe5be28642cbf3 we started respecting pagination options in `findDashboards` for organizations. This PR wraps that change in a feature flag.
> fix(kv): gaurd new org dashboard pagination with feature flag

- CHANGELOG.md
- http/swagger.yml
- kv/bucket.go
- paging.go
- tenant/storage_bucket.go
- tenant/storage_bucket_test.go
- testing/bucket_service.go
Closes #19218
This PR adds support for the `after` parameter in the `FindOptions` struct.
`after` is more sympathetic to the structure and interfaces of our K/V store implementations; as opposed to `offset`.
The K/V stores we use support `seek` operations to particular keys, but not numerical index offsets like we expose through our APIs.
To use this feature for pagination, you simply supply `after` with the last ID observed in a list of results.
This PR includes an implementation for `after` in both the `tenant` and `kv` bucket services.
Outstanding:
- ~Figure how widely used the paging links are leveraged and what needs to change to add support for auto-paging links using `after`.~
Im going to forgo forcing the use of after via the paging links for now as offset / limit suffice.
---
> feat(paging): add support for after id parameter in find options

- flags.yml
- kit/feature/list.go
- task/backend/executor/executor.go
We now default task execution to pull from the user service a permission
set.
> chore: remove feature flag for task executor

- CHANGELOG.md
- kv/task.go
- kv/task_test.go
- task.go
Part of https://github.com/influxdata/flux/issues/3080
We currently record the following "last run" information on the Task record:
- `LatestCompleted` (time)
- `LatestScheduled` (time)
- `LastRunStatus` (string)
- `LastRunError` (string)
This change introduces two new timestamps that reflect the last success and failure times of a Task (respectively):
- `LatestSuccess` (time)
- `LatestFailure` (time)
With these timestamps we will be able to compose new APIs for the Task system to make time-gap resilient (in the face of an arbitrary number of Task failures) easier to write. The next step will be to inject this information into Tasks as they get handed off to the Query layer to be run.
> feat(task): Record last success and failure run times in the Task

- CHANGELOG.md
- flags.yml
- kit/feature/list.go
- task/backend/executor/executor.go
- task/backend/executor/executor_test.go
- task/backend/executor/support_test.go
Part of https://github.com/influxdata/flux/issues/3080
Continuation of https://github.com/influxdata/influxdb/pull/19390
Now that we're recording these timestamps, use them in the Task executor by injecting them as part of the Flux `Extern`. This sets the `option tasks.latestSuccessTime = ...` option on the query so that it can be used by some new APIs we're working on.
Will need to be rebased once influxdata/influxdb#19390 is merged.
> feat(task): Inject Task's LatestSuccess Timestamp In Flux Extern

- task/backend/executor/executor.go
- task/backend/executor/executor_test.go
Looks like we had a bit of miscommunication about the naming of this Flux option that will be injected by the Task system. Renaming this to match the code that was recently merged in Flux project. This is still guarded by a feature flag so it shouldn't impact anything.
https://github.com/influxdata/flux/commit/15ebe46149e9a265a338e5511a150772bfd011be#diff-1261452e351aa821eab2dcb6ad8b88b8R98
> fix(task/executor): Use correct name for last success time extern

- bolt/kv.go
- inmem/kv.go
- kv/store.go
- testing/kv.go
This introduces the ability to push down a limit for the number of keys returned for a ForwardCursor via the `WithCursorLimit(n)` option.
Update:
Bringing this back from the dead as it will be crucial for efficient pagination across system wide lookups of resources.
> feat(kv): add support for WithCursorLimit to ForwardCursor

- checks/service_external_test.go
- http/task_service_test.go
- kv/service.go
- kv/task.go
- kv/task_test.go
- task.go
- task/backend/analytical_storage.go
- task/servicetest/servicetest.go
Tasks no longer uses the max permission system to pupulate an
authorization. We can safely remove this dead code.
> chore(task): clean up old maxPermission code

- cmd/influxd/main.go
- flags.yml
- go.mod
- go.sum
- kit/feature/list.go
- query/control/controller.go
- query/control/controller_test.go
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/stdlib/influxdata/influxdb/source.go
Closes #16220.
This adds a feature flag for experimental query tracing, which creates a span for each source and transformation in query requests.
> feat(query): add a feature flag for query tracing

- coordinator/points_writer.go
- services/httpd/handler.go
- services/httpd/service.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/shard.go
- tsdb/store.go
> feat: backport values written metric to 1.8

- CHANGELOG.md
- cmd/influx/query.go
Closes #19254 
Add an option to print raw flux response from `influx query`
```
$ ./influx query --org-id 061309063e504000 -f /tmp/thing.flux -r 
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,string,double,dateTime:RFC3339
#group,false,false,true,true,true,true,true,false,false
#default,mean,,,,,,,,
,result,table,_start,_stop,_field,_measurement,version,_value,_time
,,0,2020-08-25T19:11:41.138618117Z,2020-08-25T19:16:41.138618117Z,gauge,go_info,go1.13.10,1,2020-08-25T19:12:00Z
,,0,2020-08-25T19:11:41.138618117Z,2020-08-25T19:16:41.138618117Z,gauge,go_info,go1.13.10,1,2020-08-25T19:13:00Z
,,0,2020-08-25T19:11:41.138618117Z,2020-08-25T19:16:41.138618117Z,gauge,go_info,go1.13.10,1,2020-08-25T19:14:00Z
,,0,2020-08-25T19:11:41.138618117Z,2020-08-25T19:16:41.138618117Z,ga …
```
> feat(cli): add option to dump the raw flux response from query

- ui/cypress/e2e/communityTemplates.test.ts
- ui/src/templates/api/index.ts
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplateOverlay.tsx
- ui/src/templates/components/CommunityTemplateReadme.tsx
- ui/src/templates/utils/index.test.ts
- ui/src/templates/utils/index.ts
Closes #8199
With these the read me tab will now feed in the read me from github. If there is no github read me we currently have a bioler plate response that will eventually need to be changed
> feat: community template adding the new github raw readme fetch

- ui/cypress/e2e/flows.test.ts
- ui/cypress/fixtures/routes.json
- ui/src/notebooks/components/FlowCard.tsx
- ui/src/notebooks/components/FlowCards.tsx
- ui/src/notebooks/components/FlowCreateButton.tsx
- ui/src/notebooks/components/FlowPage.tsx
- ui/src/notebooks/components/FlowsIndex.tsx
- ui/src/notebooks/components/FlowsIndexEmpty.tsx
- ui/src/notebooks/components/Notebook.tsx
- ui/src/notebooks/components/header/index.tsx
- ui/src/notebooks/context/notebook.current.tsx
- ui/src/notebooks/context/notebook.list.tsx
- ui/src/notebooks/context/notebook.tsx
- ui/src/notebooks/index.ts
- ui/src/pageLayout/constants/navigationHierarchy.ts
- ui/src/shared/containers/SetOrg.tsx
Closes #7151
This index is purposefully very, very ugly.  It is not done.  Not even close.  But, you can now create and view multiple flows and differentiate them based on a meaningful name.
> feat: flows index

- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service.go
- pkger/testdata/task_v2.yml
- pkger/testdata/task_v2_params.yml
- pkger/testdata/task_v2_taskSpec.yml
Closes #19260
User wanted to specify tasks in a template as a query option, this makes that possible
```yaml
apiVersion: influxdata.com/v2alpha2
kind: Task
metadata:
name: task-uuid
spec:
task:
- key: name
default: "bar"
type: string
- key: every
default: 1m
type: duration
params:
- key: custom
default: "bar"
type: string
query:  >
option task = { name: "bar", every: 1m }
option params = { custom: "param" }
from(bucket: "rucket_1")
|> range(start: -5d, stop: -1h)
|> filter(fn: (r) => r._measurement == "cpu")
|> filter(fn: (r) => r._field == "usage_idle")
|> aggregateWindow(every: 1m, fn: mean)
|> yield(name: "mean")
status: inactive
associations:
- kind: Label
name: label-1
```
> feat(templates): handle task as option and spec in template query

- go.mod
- go.sum
This PR adresses https://app.zenhub.com/workspaces/teamedge-5f2b1290f4e2170018660ac1/issues/influxdata/plutonium/3052
> chore: update uuid library from satori to gofrs

- go.mod
- go.sum
This PR updates the go.mod to use the latest version of influxql.
> chore: Use latest version of influxql package

- ui/src/cloud/components/RateLimitAlert.tsx
- ui/src/cloud/components/RateLimitAlertContent.tsx
Display different rate limit alert content to Free users and PAYG users.
**Free**
**PAYG**
> feat(ui): change rate limit content for payg

- ui/src/templates/actions/creators.ts
- ui/src/templates/api/index.ts
- ui/src/templates/components/CommunityTemplateEnvReferences.tsx
- ui/src/templates/components/CommunityTemplateImportOverlay.tsx
- ui/src/templates/components/CommunityTemplateOverlay.tsx
- ui/src/templates/components/CommunityTemplateOverlayContents.tsx
- ui/src/templates/components/CommunityTemplateParameters.tsx
- ui/src/templates/components/CommunityTemplateResourceContent.tsx
- ui/src/templates/reducers/index.test.ts
- ui/src/templates/reducers/index.ts
- ui/src/types/templates.ts
Closes #19273 
- adds Parameterization to community templates.
- adds tasks rendering to templates (somehow got left out)
[this](https://github.com/influxdata/influxdb/blob/master/pkger/testdata/dashboard_params.yml) and [this](https://github.com/influxdata/influxdb/blob/master/pkger/testdata/tasks_params.yml) are the templates I used for testing.
> feat(community-templates): add parameterization

- tenant/service_onboarding.go
- tenant/service_onboarding_test.go
The admin user should no longer be added to the new user created by
setup.
> fix(onboard): onboarding no longer add admin user

- http/scraper_service_test.go
- http/task_service_test.go
- kit/transport/http/error_handler.go
- kv/scrapers.go
- kv/scrapers_test.go
- label/http_handler.go
- scraper.go
- tenant/http_client_user.go
- testing/scraper_target.go
Closes #19157
Now that the tenant service is complete we should be using it for all
test instead of the `kv.Service`.
> chore(tenant): point tests to new tenant service

- cmd/influxd/main.go
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/v1_dump_meta.go
- cmd/influxd/upgrade/v2_dump_meta.go
Includes some example sub commands for dumping v1 and v2 metadata
* `influxd upgrade` (stubs only)
* example `influxd upgrade v1-dump-meta` dumps some InfluxDB 1.x meta data
* example `influxd upgrade v2-dump-meta` dumps some InfluxDB 2.x meta data
The example `dump` commands are not expected in the final release
Closes #19495
> feat: Create initial stubs for influxd upgrade command

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- go.mod
- toml/toml.go
- toml/toml_test.go
- tsdb/config_test.go
Closes #19505
This PR primarily is focused on adding a number of TSM / TSI engine options to the CLI interface of `influxd`.
In addition, it complete a little housekeeping:
* ✅ Remove redundant `replace` directives from `go.mod`
* ✅ Enhances toml package types to implement viper's `pflag.Value` interface for use a CLI arguments
* ✅ Removes `page-fault-rate` flag, which is not available in TSM 1.x
> feat: Add TSM 1.x storage options as flags

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
Closes #19507
This PR adds a number of InfluxQL query engine options to the CLI interface of influxd.
> feat: Expose a subset of InfluxQL coordinator tuning options

- go.mod
From online discussion, the /dev/null replacement was "a hacky way to prevent
people from re-introducing a dependency on the then-deprecated platform repo",
and nothing in the module depends at all on the erroneously capitalized
logrus repo:
```
% go list -m
github.com/influxdata/influxdb/v2
% go mod why -m github.com/Sirupsen/logrus
(main module does not need module github.com/Sirupsen/logrus)
```
Replace directives are potentially dangerous as they can change
semantics for importers of public packages which won't inherit
the same replace directives, so it's best to avoid them if possible.
> fix: remove unnecessary replace directives from go.mod

- http/variable_service.go
- http/variable_test.go
- mock/variable_service.go
- testing/variable.go
This PR fixes the Put route for Variables by adding ID as a parameter. The ID is passed through instead of being taken off the Variable object because it does not come through the HTTP route on the object for some reason, which you can see from the Update route.
> fix(variables): add id to put variable request

- cmd/influxd/launcher/launcher.go
- storage/config.go
- storage/engine.go
- v1/services/precreator/README.md
- v1/services/precreator/config.go
- v1/services/precreator/config_test.go
- v1/services/precreator/service.go
- v1/services/precreator/service_test.go
Closes #19520
This PR copies the shard precreator package from InfluxDB 1.x to enable shard pre-creation support. It makes minor modifications to take a `context.Context` for the `Open` function.
In order to configure the service, the following parameters have been exposed:
```
--storage-shard-precreator-advance-period Duration              The default period ahead of the endtime of a shard group that its successor group is created. (default 30m0s)
--storage-shard-precreator-check-interval Duration              The interval of time when the check to pre-create new shards runs. (default 10m0s)
```
> feat: Port shard pre-creation service from InfluxDB 1.x

- tenant/service_onboarding.go
- tenant/service_onboarding_test.go
When a new user is onboarded the new auth token can now have access to
create auth tokens
> fix: Add me permission to onboarded auth token

- dashboard.go
- http/swagger.yml
- pkger/clone_resource.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/service_test.go
- pkger/testdata/dashboard_band.yml
Closes idpe 8337
Band Plot needs to know explicitly the name of the aggregate function that should be rendered in order to properly group the "upper" and "lower" bands set by the user. Thus, we will add the "mainColumn" property.
> feat: update BandViewProperties

- kv/variable.go
- testing/variable.go
This line was supposed to go in https://github.com/influxdata/influxdb/pull/19368
The ReplaceVariable function needs to use `PutUpdate` instead of `PutNew`, otherwise it will return a "conflict" error. ReplaceVariable is also used to create new Variables for testing, so I added a condition that will allow it to create a Variable if it does not exist or replace it if it does exist.
> fix(variables): use Update function for Put Variable

- CHANGELOG.md
- pkg/csv2lp/csv_table.go
- pkg/csv2lp/csv_table_test.go
Closes #19453
A warning message 
```
WARNING: ignoring duplicate tag 'result' at column index 1, using column at index 14
```
is printed when the CSV data contains duplicate tag names (in a header row). The last column (of the same name) is then used.
> fix(pkg/csv2lp): warn about duplicate tag names #19453

- CHANGELOG.md
- cmd/influx/write.go
- cmd/influx/write_test.go
- pkg/csv2lp/README.md
- pkg/csv2lp/csv2lp.go
- pkg/csv2lp/csv2lp_test.go
- pkg/csv2lp/csv_annotations.go
- pkg/csv2lp/csv_annotations_test.go
- pkg/csv2lp/csv_table.go
- pkg/csv2lp/csv_table_test.go
- pkg/csv2lp/data_conversion.go
- pkg/csv2lp/data_conversion_test.go
Closes #18744 : **indicate a loss of precision when parsing long/unsignedLong data types**
When parsing `long` or `unsignedLong` value from a string value with fraction digits, the whole CSV row fails when in a strict mode, which is turned on using a column dataFormat that starts with `strict`, such as `long:strict`. A warning is printed when not in a strict mode, saying `line x: column y: '1.2' truncated to '1' to fit into long data type`.  [Package documentation](https://github.com/influxdata/influxdb/compare/18744/csv2lp?expand=1#diff-845cb71dbfa49b093ae411b57e24e057R161) explains strict parsing.
Closes #18742 : **add the ability to write rejected records to a specific file**
There is a new --error-file option in `influx write`
```
--errors-file string   The path to the file to write …
```
> feat(cmd/influx/write): add new processing options and enhancements

- CHANGELOG.md
- pkg/csv2lp/csv2lp_test.go
- pkg/csv2lp/csv_annotations.go
- pkg/csv2lp/csv_table.go
Closes #19452
This PR ensures that the #group annotation cannot override the existing line part (measurement, field, tag, time) of a CSV column if it is already set. It also means that all dateTime columns (including _start, _stop from flux query results) cannot become tags with #group annotation, since dateTime columns automatically have _time_ line part.
> fix(pkg/csv2lp): do not override existing line part in group annotation

- cmd/influx/query.go
Updates the annotation headers to be in the same order as the UI: https://github.com/influxdata/influxdb/blob/d3c86e8f4ca85c4f38b37acb7bf57a0a8efd0ba6/ui/src/shared/apis/query.ts#L52
would help with issues like this: https://github.com/influxdata/influxdb/issues/19452
> fix(cli): update annotation order to match UI

- http/swagger.yml
The label creation operation always requires a name, so make the OpenAPI specification reflect that.
Also fix a couple of other minor issues with the OpenAPI specification in passing.
> fix: http: add required name to LabelCreateRequest

- influxql/query/executor.go
- kv/store.go
- telemetry/push.go
- tsdb/index/tsi1/log_file.go
- v1/coordinator/statement_executor.go
```
Prior to this commit we checked for context cancellation with a select
block and context.Context.Done() without multiplexing over any other
channel like:
select {
case <-ctx.Done():
// handle cancellation
default:
// fallthrough
}
This commit replaces those type of blocks with a simple check of
ctx.Err().  This has the following benefits:
* Calling ctx.Err() is much faster than entering a select block.
* ctx.Done() allocates a channel when called for the first time.
* Testing the result of ctx.Err() is a reliable way of determininging if
a context.Context value has been canceled.
There are a few places we optimized the select block by only entering it
every cancelCheckInterval times.  This commit checks ctx.Err() every
time -- this increases the cancellation granularity and is only …
```
> refactor: Replace ctx.Done() with ctx.Err()

- authorization/http_server_test.go
- gather/scraper_test.go
- notification/endpoint/endpoint_test.go
- tsdb/index/inmem/meta_test.go
This PR resolves issues with newer versions of the Go compiler.
* casting an integer to a string results in a compilation error
* The string representation of url.Error has changed (quotes around the URL), so provide a more robust means for comparing the error
> chore: Fix compilation errors and unit tests for newer Go compilers

- tsdb/index.go
- tsdb/index_test.go
- tsdb/shard.go
- v1/services/storage/series_cursor.go
This fixes multi measurement queries that go through the storage service
to correctly pick up all series that apply with the filter. Previously,
negative queries such as `!=`, `!~`, and predicates attempting to match
empty tags did not work correctly with the storage service when multiple
measurements or `OR` conditions were included.
This was because these predicates would be categorized as "multiple
measurements" and then it would attempt to use the field keys iterator
to find the fields for each measurement. The meta queries for these did
not correctly account for negative equality operators or empty tags when
finding appropriate measurements and those could not be changed because
it would cause a breaking change to influxql too.
This modifies the storage service to use new methods …
> fix(services/storage): multi measurement queries return all applicable series

- cmd/influxd/launcher/storage_test.go
- storage/engine.go
Closes #19518
This PR ensures the `ShardGroupDuration` is updated according to rules defined in the `meta` package, when the retention period is updated. It is necessary that the `ShardGroupDuration` ≤ `RetentionPeriod`. This PR also includes a unit test which sets the retention period to the lowest possible value, to exercise the original bug.
> fix: ShardGroupDuration is updated for retention period updates

- .github/CODEOWNERS
The cloud 2 storage team doesn't "own" OSS code any more. We are still
happy to review storage PRs, but we don't need to review all of them.
> chore(storage): remove storage-team from CODEOWNERS

- cmd/influx_inspect/export/export.go
When applied, this patch will add the -lponly flag to the export command
which instructs influx_inspect to only output line protocol without
comments and other out-of-band data.
> feat: Backport lponly feature to 1.8

- chronograf/organizations/dashboards_test.go
- chronograf/organizations/organizations_test.go
- chronograf/organizations/servers_test.go
- chronograf/organizations/sources_test.go
Under later Go versions, the tests panic because it's not OK to pass a nil Context to `context.WithValue`.
> fix: chronograf/organizations: avoid nil context with WithValue

- e2e/package.json
Nightly selenium tests were failing to run due to chromedriver only supporting chrome 83. somewhere a docker image was updated where that version got bumped. this update allows the tests to run.
The error in the nightly tests was:
```
✖ failed
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 83
at Object.throwDecodedError (/home/circleci/project/e2e/node_modules/selenium-webdriver/lib/error.js:550:15)
at parseHttpResponse (/home/circleci/project/e2e/node_modules/selenium-webdriver/lib/http.js:565:13)
at Executor.execute (/home/circleci/project/e2e/node_modules/selenium-webdriver/lib/http.js:491:26)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
(sorry for the assignment/review spam, must be nearing end of day …
> fix(e2e): update chromedriver version

- pkg/csv2lp/README.md
It looks to me like "appended" would make more sense here.
> docs: Edit csv2lp README

- CHANGELOG.md
- cmd/influxd/launcher/engine.go
- errors.go
- http/delete_handler.go
- http/delete_test.go
- kit/transport/http/error_handler.go
- storage/engine.go
Closes #19580
This PR disables the `/api/v2/delete` API and returns a `501 Not implemented`, as there is no available implementation of the feature via the 1.x `tsdb` storage engine. Follow up issue #19635 was created to track the future implementation of this functionality.
> fix: Disable unimplemented delete with predicate API

- CHANGELOG.md
- kit/transport/http/middleware.go
addresses https://github.com/influxdata/influxdb-client-js/issues/262 for oss
> fix(middleware): adding PATCH to access control allow methods

- CHANGELOG.md
- flags.yml
- kit/feature/list.go
Flips template flag to be on to match cloud behavior.
> feat: turn on community templates

- pkg/csv2lp/csv2lp.go
- pkg/csv2lp/csv2lp_test.go
- pkg/csv2lp/examples_test.go
- pkg/csv2lp/line_reader.go
- pkg/csv2lp/line_reader_test.go
Closes #19588 
This PR ensures that correct line numbers are reported when reportings error from CSV file. It introduces LineReader that provides a workaround to golang's CSV reader that does not expose current line number at all (https://github.com/golang/go/issues/26679), 
Moreover, the new LineReader ensures that at most one line is returned by every read in order to ensure that
golang's CSV reader buffers at most one single line into its nested bufio.Reader.
+ small improvements in tests
There were the following alternatives in the implementation, but the current with LineReader is IMHO the best
- introduce a new CSV reader (extended golang's csv.Reader) that expose line numbers
- use unsafe package to get an internal line number from golang's csv.Reader struct
> fix(pkg/csv2lp): report actual line numbers

- query/stdlib/testing/testing.go
- tsdb/engine/tsm1/array_cursor.gen.go
- tsdb/engine/tsm1/array_cursor.gen.go.tmpl
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
This is a backport of #14262 to the 1.x storage engine. The 1.x storage
engine is now the primary engine for open source so when we switched we
regressed to the old behavior.
This also fixes `go generate` for the tsm1 package by running `tmpl`
with `go run` instead of assuming the correct one is installed in the
path.
Fixes #19564.
> fix(tsdb): exclude the stop time from the array cursor

- kit/io/limited_read_closer.go
- kit/io/limited_read_closer_test.go
A fairly minor change, but this saves two allocations every time
points are written to the API (one allocation for the embedded io.LimitReader,
and one allocation to create the `close` closure).
Also fix the code so that it actually limits to the exact requested number of bytes
rather than one more. We don't really need to layer on top of io.LimitReader,
as that code is fairly minimal.
This change also means that the `LimitedReadCloser` can be used without a constructor
function, the same way that `io.LimitedReader` can.
> chore: kit/io: improve LimitedReadCloser

- ui/src/shared/constants/fluxFunctions.ts
Adds functions introduced in Flux 0.82 and 0.83
> chore(flux): add Flux 0.83 functions

- CHANGELOG.md
- cmd/influx/write.go
- pkg/csv2lp/line_reader.go
- pkg/csv2lp/line_reader_test.go
- write/batcher.go
- write/batcher_test.go
Closes #19586
This PR fixes two issues. 
* Fixes a panic that was introduced with a new `LineReader` type.
* Adds an option to override the maximum line length in `write.Batcher` to support line lengths greater than the default 64KiB for a new `bufio.Scanner`
* Adds a CLI argument, `max-line-length`, to configure the maximum line length. The default is 16MB, which should cover the majority of use cases.
> fix: bufio.Scanner: token too long

- README.md
> chore(readme): update readme for next release

- query/stdlib/testing/end_to_end_test.go
- query/stdlib/testing/testing.go
It appears that the double write caused by using to() inside a separate
execution environment (experimental.chain) causes flux e2e tests to behave
unpredictably, when coupled with the 1.x storage engine. Removing the second
write by using two passes, one to write to the db, then another to run the
test, eliminates the flakiness. Verified by running e2e tests in parallel times
8 for 12 hours without any flakiness observed. Before the fix, the flakiness
would take approx 30 minutes on avgerage to exhibit.
Closes #19577
> fix: convert flux e2e test harness to two-pass

- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/config_test.go
This is 3rd PR of 4  for the upgrade feature.
Upgrades config to 2.x format.
_It is branched from PR #19641 which should be merged first to avoid conflicts._
> feat(upgrade): upgrade config

- ui/package.json
- ui/yarn.lock
Closes #19677 
Upgrade the `flux-lsp-browser` in `ui/package/json` to the latest release.
> build(ui): Update flux-lsp-browser dependency to latest release

- go.mod
- go.sum
- query/promql/internal/promqltests/go.mod
- query/promql/internal/promqltests/go.sum
- query/stdlib/testing/testing.go
Closes #19565
This change required a patch release of flux, so it bumps up the flux version from v0.83.1 to v0.83.2. 
It unskips a test that was previously failing in influxDB CI. The fix was to [correct the test's input data](https://github.com/influxdata/flux/pull/3233) to have a consistent `_value` type.
> feat(query/stdlib): unskip agg window median test

- CHANGELOG.md
- cmd/influx/write.go
- cmd/influx/write_test.go
- go.mod
- go.sum
Closes #19335
This PR adds a new flag to `influx write` :
```sh 
--rate-limit string      Throttles write, examples: "5 MB / 5 min" , "17kBs". "" (default) disables throttling.
```
- the rate is specified as: `COUNT(B|kB|MB)/TIME(s|sec|m|min)` with `/` and `TIME` being optional; COUNT is a decimal number, TIME is a positive whole number; spaces in the value are ignored.
- "5MB / 5min" matches the current free tier in the cloud, it can be also expressed as `17476.266666667Bs`, `1MB/1min`, `1MB/min`, `1MBmin` or `1MBm`
- when an invalid rate is supplied, the tool prints out the format and also an exact regular expression to recognize format
- `--rate-limit` can be also used in `influx write dryrun`
> feat(cmd/influx/write): allow to limit write rate

- cmd/influx/telegraf.go
Closes #19626 
This pr works around an irregularity in the cloud api* by retrieving a telegraf config by id, rather than listing all telegraf configs with a filter for the id.
*issue is that the `resourceID` query parameter is not being respected
> fix(cli): workaround for cloud api to return a single telegraf config if specified

- pkger/clone_resource.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_test.go
- pkger/testdata/dashboard_single_stat_plus_line.json
- pkger/testdata/dashboard_single_stat_plus_line.yml
Closes #19441
Something relies on the ID of the cell's color to be set (seems like `"base"` is a common id). This PR preserves that color ID accross import/export so one can now export and re-import a dashboard and any custom colors in cells should go unchanged.
> fix(templates): preserve cell colors on export/import

- CHANGELOG.md
- gather/recorder.go
Fixes #19679
This PR fixes an issue with scrapers not writing data, which occurred during the transition to TSM 1.x.
> fix: Ensure orgID and bucketID are passed to WritePoints API

- pkger/parser.go
- pkger/parser_test.go
- pkger/testdata/tasks.json
- pkger/testdata/tasks.yml
Closes #18939 
This pr utilizes the same duration parsing method that the tasks api does, extending support for such identifiers as `d`, `w`, `mo`, and `y` (for day, week, month, and year; complete list [here](https://github.com/influxdata/flux/blob/12684f51bd0eee66900f0ca59101a136f03cd722/ast/ast.go#L1537-L1548)).
> fix(templates): allow same duration unit identifiers that the tasks api allows

- kv/onboarding.go
- kv/passwords.go
- kv/passwords_test.go
- testing/onboarding.go
Closes #19720
This ensures that transaction lifetimes are shorter to reduce lock contention.
Additionally, this PR removes the ability to set an empty password when running the initial on-boarding process. According to the original developer, this behavior was required to permit Cloud processes to complete. As this code is no longer shared, this security issue is corrected.
> fix(kv): Reorganize bcrypt password hashing outside transactions

- CHANGELOG.md
- flux/control/controller.go
- flux/control/controller_test.go
- mock/flux.go
- services/httpd/handler.go
Closes #19696 
This makes it so we actually log compilation, execution, and total request duration to the log. Previously, we would just log zero durations here.
Some of the things we were trying to report, like queue duration, requeue duration, etc, aren't relevant in 1.x, so I removed them from the log altogether.
> fix(flux): add durations to Flux logging

- write/batcher.go
- write/batcher_test.go
This PR improves and simplifies what was done in #19658 in `write/batcher.go` in a way that the newly introduced `WriteTo(filter)` implementation reuses the same code as the existing `Write(org, bucket)`. 
The newly added WriteTo implementation is then also covered by existing tests, the coverage of write package code is back to 100%.
> chore(write): refactor batcher to reuse code

- cmd/influxd/upgrade/security.go
- cmd/influxd/upgrade/security_test.go
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/upgrade_test.go
This is 4th PR of 4  for the upgrade feature.
Generates script which upgrades users to 2.x. The script uses `influx` tool to create tokens with read/write permission to buckets that were created for 1.x databases. A token represents 1.x user, 1.x user name becomes the description of the token.
_Note: It is branched from PR #19641 which should be merged first to avoid conflicts._
> feat(upgrade): upgrade security

- CHANGELOG.md
- cmd/influx/template.go
Closes #19159
Add `--force` option to `influx stacks rm` command which skips the confirmation prompt prior to deleting the stacks.
> feat(cli): provide means to remove stack without confirmation

- .gitignore
- .goreleaser.yml
- Since a new private.key file is created during the release process, goreleaser is failing with below error
```
git is currently in a dirty state, please check in your pipeline what can be changing the following files
```
private.key files needs to be ignored and as such to be added to `.gitignore` file
- Recently `arm6` builds started to fail with 
```
release failed after 161.43s error=failed to build for linux_arm_6: # github.com/influxdata/influxdb/v2/cmd/influx
cmd/influx/setup.go:292:42: constant 3600000000000 overflows uint
``` 
Not to block the RC release removing the arm6 builds. I will have an issue to fix the overflow problem filed.
> chore: remove arm6 from build and add private.key to gitignore

- tsdb/engine/tsm1/engine.go
This feature allows compaction to be disabled on a per-shard basis by
creating a file named `do_not_compact` in a shard's directory. When
disabled, a message is logged every 15 minutes with the reason for
compaction being disabled (existance of the file). This makes it easy to
know if compaction has been disabled for any shards by searching the log
for `compaction disabled` or running `find path/to/data -type f -name
do_not_compact`.
Example log message:
```
2020-10-06T13:12:02.200598Z     info    TSM compaction disabled {"log_id": "0PgWKQ1W000", "engine": "tsm1", "db_shard_id": 9, "reason": "/home/dgnorton/.influxdb/data/stress/autogen/9/do_not_compact"}
```
> feat: allow disable compaction per shard

- cmd/influx/template.go
Closes #19148
This pr returns an error when `influx stacks update --addResource` fails due to bad input.
```
$ ./influx stacks update --stack-id abc123 --addResource badInput
Error: Invalid 'resourceType=resourceID' key value pair[s]: badInput.
See 'influx stacks update -h' for help
```
> fix(cli): return error on failed resource addition

- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/config_test.go
Current config upgrade saves upgraded configuration to `influxdb.toml`,  but 2.x looks for `config.json|toml|yaml` by default. This tiny PR fixes it. 
Also the related test has been slightly improved and simplified.
> fix(upgrade): proper default 2.x config filename

- services/httpd/pprof.go
Prior to this commit, influxd was writing legacy profiling data which
often (always?) required an accompanying executable to use.
This commit instructs influxd to write profiles in the new format which
can be examined without a binary.
Closes: #19681
> feat: generate modern profiles

- cmd/influxd/launcher/launcher.go
- flags.yml
- kit/feature/list.go
Closes #19762
This commit ensures OSS is using the new implementation of the AuthorizationService from the authorization package.
It also removes the associated feature flag.
> fix(launcher): Switch to AuthorizationService from authorization package

- services/httpd/pprof.go
Backports PR https://github.com/influxdata/influxdb/pull/19655 to 1.8
Closes https://github.com/influxdata/influxdb/issues/19759
* feat: generate modern profiles
Prior to this commit, influxd was writing legacy profiling data which
often (always?) required an accompanying executable to use.
This commit instructs influxd to write profiles in the new format which
can be examined without a binary.
While we're at it, this commit also adds the allocs and threadcreate
profiles.
Finally, this patch also changes the format of the downloaded tar in the
following ways:
* The profiles are added to the profile/ directory -- so instead of
extracting the profiles into your current directory, they're placed in
a "profiles" directory.
* This commit adds the .pb.gz extension to each of the files since …
> feat: backport profile improvements to 1.8

- http/swagger.yml
I am unsure if I am doing this correctly. But this updates the PostDBRP docs to reflect the mutually exclusive requirement of `org` vs `orgID` when creating a DBRP mapping. Since only one or the other is actually required to create the mapping. But the docs currently state both are required.
My knowledge of OpenAPI Spec is a little lacking. But this is what I assertain is correct based on good old SO:
https://stackoverflow.com/questions/21134029/how-to-define-mutually-exclusive-query-parameters-in-swagger-openapi/49199240#49199240
> chore(docs): update PostDBRP docs to reflect mutual exclusive requirement of org vs orgID

- storage/reads/aggregate_resultset.go
- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
- storage/reads/array_cursor.gen.go.tmpldata
- storage/reads/array_cursor.go
- storage/reads/array_cursor_gen_test.go
- storage/reads/array_cursor_test.gen.go.tmpl
- storage/reads/array_cursor_test.go
- storage/reads/group_resultset.go
- storage/reads/resultset.go
> feat: aggregate array cursors

- pkg/fs/fs_unix.go
Prior to this patch, DiskUsage() would calculate bytes available
by multiplying blocks available by block size in bytes:
disk.Avail = fs.Bavail * uint64(fs.Bsize)
Under some versions of Unix, fs.Bavail is of type uint64 and on
others (like FreeBSD) it is of type int64.
This causes a compile time error:
```
$ go build
./fs_unix.go:81:25: invalid operation: fs.Bavail * uint64(fs.Bsize) (mismatched types int64 and uint64)
```
This patch type-converts fs.Bavail to unit64 to ensure that all
types in the expression align.
This prevents compile time errors under FreeBSD and other platforms
where fs.Bavail isn't uint64.
Closes #
> fix: Type-convert fs.Bavail for portability

- cmd/influxd/launcher/launcher.go
- http/platform_handler.go
- kv/migration/all/0008_LegacyAuthBuckets.go
- kv/migration/all/all.go
- v1/authorization/error.go
- v1/authorization/http_client.go
- v1/authorization/http_server.go
- v1/authorization/http_server_test.go
- v1/authorization/mock_tenant.go
- v1/authorization/service.go
- v1/authorization/storage.go
- v1/authorization/storage_authorization.go
- v1/authorization/storage_authorization_test.go
Closes #19812
This PR introduces a new package, `v1/authorization`, that provides an implementation of `influxdb.AuthorizationService` for managing v1 authorization tokens. It is a private API, exposed via `/private/legacy/authorizations`, with the same operations as `/api/v2/authorizations` for creating, reading, updating and deleting data.
As this is a private API, it is not noted in the `CHANGELOG`.
Note that this commit does not hook up the service to the v1 `/query` and `/write`, which will occur in a subsequent PR .
> feat(authorization): Create a v1 authorization service

- v1/services/storage/series_cursor.go
In order to let TagKeys and TagValues get the right answer,
sometimes they will need to examine their predicate and
see if using the index is possible, or if a block scan is needed.
For those cases we want to examine the predicate before creating
the index series cursor. This change allows us to create an
index series cursor with an already-deserialized influxql.Expr.
This just a refactoring and should have no effect on behavior.
> refactor: allow newIndexSeriesCursor() to accept an influxql.Expr

- http/swagger.yml
> docs: Fix typos in http/swagger.yml

- cmd/influxd/launcher/query_test.go
- mock/reader.go
- query/stdlib/influxdata/influxdb/rules.go
- query/stdlib/influxdata/influxdb/rules_test.go
- query/stdlib/influxdata/influxdb/source_test.go
- query/storage.go
- storage/flux/reader.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/window.go
- storage/reads/store.go
- v1/services/storage/store.go
Final issue to port window agg mean and bare agg mean pushdown to OSS. 
As discussed below, this PR will also remove capabilities and consolidate the `Store` and `StoreReader` interfaces as well as any mock interfaces for testing.
> feat(storage): enable window agg mean pushdown

- cmd/influx/main.go
- cmd/influx/v1_authorization.go
- cmd/influx/v1_commands.go
- v1/authorization/http_client.go
- v1/authorization/http_server.go
- v1/authorization/http_server_test.go
Closes #19765
This commit add a series of new subcommands to the `influx` CLI tool. The specific commands are:
* `influx v1` to host any InfluxDB v1 specific commands
* `influx v1 auth` for v1 authorization token management.
* `influx v1 auth set-password` to assign a password to a token for V1 API authorization
The `v1 auth` commands enable access to the private authorization APIs (see #19815 and #19837) used to manage authorization tokens for v1 compatibility APIs, including:
* `/write`
* `/query`
The final issue, #19768 will update the authorization handlers to use these new tokens and their assigned passwords.
> feat(cli): Extend CLI with v1 authorization commands

- http/swagger.yml
- http/swaggerV1Compat.yml
> fix: add 1.x compatible endpoints to swagger

- models/points.go
Go tip now enforces that strconv.ParseFloat receives a bitSize parameter
of 32 or 64. Previously, any value that was not 32, was treated as 64.
The previous value of 10 was likely a copy-paste error from integer
parsing.
> fix(models): correctly parse float as 64-bits

- CHANGELOG.md
- cmd/influx/authorization.go
This PR updates the `influx auth` subcommand to use the HTTP client from the `authorization` package rather than the old one.
> chore: Use updated HTTP client for authorization service

- cmd/influxd/upgrade/database.go
- cmd/influxd/upgrade/security.go
- cmd/influxd/upgrade/security_test.go
- cmd/influxd/upgrade/upgrade.go
This PR upgrades 1.x users to 2.x tokens using v1 authorization API. The upgrade is done at upgrade runtime instead of with a script after `upgrade` command finishes.
> feat(upgrade): use v1 authorization for users upgrade

- pkger/service.go
- pkger/service_metrics.go
Closes #19688 
Although there are current metrics related to templates, this adds a simple count of community templates installed ("custom" if it's not an official template).
```
service_pkger_template_count{method="apply",org_id="ORGID",source="https://github.com/influxdata/community-templates/blob/master/linux_system/linux_system.yml",user_id="USERID"} 2
templates_installed_count{template="linux_system"} 2
```
> chore: add simple metrics related to installed templates

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- cmd/influxd/upgrade/upgrade.go
- storage/bucket_service.go
- storage/bucket_service_test.go
- task/backend/analytical_storage_test.go
Closes #19876 
Ensure the `log` field is initialized at construction of the `BucketService` to avoid panics.
> fix: Add Logger to constructor function to ensure log field is initialized

- cmd/influxd/launcher/launcher.go
- cmd/influxd/main.go
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/v1_dump_meta.go
- cmd/influxd/upgrade/v2_dump_meta.go
- fluxinit/init.go
The builtin package performs costly initialization work in the go init()
function, which causes the work to be performed for all paths of the main
executables that need it, including help screens. This patch uses the fluxinit
package, which requires a call to do the costly work. It allows help screens
and other code paths to execute quickly.
Closes ##9714
> fix: use fluxinit package to init flux library instead of builtin

- v1/services/storage/store.go
Fixes influxdata/flux#3300.
We were returning `nil` instead of an empty iterator, and callers expect a non-nil result set for any non-error return.
I added a regression test for this here: influxdata/flux#3303.
> fix: return empty iterator instead of null in tagValues

- .circleci/config.yml
Closes # https://github.com/influxdata/influxdb/issues/19892
- Update regex to be able to tag GA releases
- Remove selenium acceptance test run from nightly build
> chore: make 2.0 RC builds optional

- go.mod
- go.sum
- services/httpd/handler.go
- services/httpd/handler_test.go
Address CVE-2020-26160 for the jwt-go package.
Closes #
> fix: Upgrade version of jwt-go package to v4.0.0

- ui/src/shared/constants/fluxFunctions.ts
Adds the `influxdb.cardinality()` function introduced in Flux 0.92.0 to `fluxFunctions.ts`.
> chore(flux): flux 0.92 functions

- CHANGELOG.md
- http/ready.go
- http/ready_test.go
The [swagger `/ready` 200 response content type](https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetReady)  is `application/json` , whereas the implementation returns 'text/plain'. This PR fixes the implementation.
Originally reported in https://github.com/influxdata/influxdb-client-js/issues/277.
> fix(http): fix /ready response content type

- Makefile
Addresses #18866
This pr forgoes building the cli with assets as well as omits symbol tables and debug information.
On linux the cli's footprint was reduced by ~45%; 62M before -> 34M after.
> chore: reduce filesize of influx binary

- go.mod
- go.sum
- services/httpd/handler.go
- services/httpd/handler_test.go
This commit updates the dependencies for influxdb to require v4.0.0-preview1 of
the jwt-go package.  This required updating the go.mod and go.sum files as well
as any source file that directly imported that package.
Prior to this commit, the TestHandler_Query_Auth() tests would fail as it
checked for specific error strigns returned by the jwt-go package.
Version 4.0.0-preview1 of the package changed the verbiage of those errors a
bit.  This patch updates the test to detect the new error string.
> fix: jwt-go fix backport

- CHANGELOG.md
- cmd/influxd/upgrade/security.go
- cmd/influxd/upgrade/upgrade.go
Closes #19921 
"Security script" is unused / irrelevant since #19854
> fix(upgrade): delete references to 'security script' in upgrade command

- CHANGELOG.md
- cmd/influx/setup.go
- cmd/influxd/upgrade/setup.go
Closes #19926 
Prior to #19885, `influxd` would multiply RPs from onboarding requests by a factor of an hour. This caused overflows in many cases, so I removed the multiplication. The tests didn't catch all the places where the CLI was anticipating that multiplication...
The 3 lines changed here mirror the fix I made to [non-interactive upgrade](https://github.com/influxdata/influxdb/pull/19885/files#diff-ec11f92a3df5beb5cc1657892bfc169a49bed091ce94ebd1fae3d989a8c6eceeL57-R57) as part of the original PR.
> fix: don't divide RPs provided over the CLI by a factor of an hour

- id.go
- models/inline_strconv_parse.go
Currently, unsafeBytesToString function violates the 6th rule of unsafe
pointer usage. That is, reflect.SliceHeader/String header should never
be used as plain struct. This misuse can lead to silent memory
corruption, which can be difficult to track down when problem occurred.
Instead, use the more (right) idiom to convert slice of byte to string
without heap allocation.
```
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
BenchmarkInvalid-8   	1000000000	         0.497 ns/op	       0 B/op	       0 allocs/op
BenchmarkValid-8     	1000000000	         0.239 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	command-line-arguments	0.815s
```
> fix: misuse of reflect.SliceHeader

- cmd/influxd/launcher/launcher.go
Closes #19929 
The help text for `influxd` says that `config.yaml` will be used as a default, if found. As far as I can tell from reading [this](https://github.com/influxdata/influxdb/blob/master/kit/cli/viper.go#L78-L81), the CLI will actually find any of `config.{json|toml|yaml|yml}`.
> fix: make influxd help more specific

- CHANGELOG.md
- cmd/influx/v1_authorization.go
- kit/cli/viper.go
Closes #19933
This PR improves the `v1 auth` commands of the `influx` CLI tool, and includes some minor improvements to the `kit/cli` package. The enhancements and fixes to the user experience are as follows:
* Rename `--auth-token` to `--username` for the `v1 auth create` command to clarify its purpose in the context of v1 requests
* `v1 auth create` now requires a password when creating a new authorisation. It can be optionally disabled with the `--no-password` flag, however, the user much set a password using the `v1 auth set-password` command prior to using the token.
* Rename `v1 auth active` and `v1 auth inactive` commands to the actions `set-active` and `set-inactive` respectively to clarify their behaviour.
For example, to set a token to active:
```
influx v1 auth set-active …
```
> fix: Improve the UI for the influx v1 auth commands

- ui/src/writeData/components/telegrafPlugins/gnmi.md
- ui/src/writeData/components/telegrafPlugins/kafka_consumer.md
- ui/src/writeData/components/telegrafPlugins/proxmox.md
- ui/src/writeData/components/telegrafPlugins/ras.md
- ui/src/writeData/components/telegrafPlugins/stackdriver.md
- ui/src/writeData/constants/contentTelegrafPlugins.ts
- ui/src/writeData/graphics/ras.svg
> feat: adding RAS telegraf input

- CHANGELOG.md
- cmd/influxd/upgrade/database.go
- cmd/influxd/upgrade/database_test.go
Closes #19951 
Use / instead of - to separate DB and RP when upgrading to 2.x buckets. The comments & error messages were already using /.
> fix(upgrade): use db/rp naming convention when upgrading DBs

- CHANGELOG.md
- authorizer/authorize_find.go
- cmd/influxd/launcher/launcher.go
Closes #19944 
Our V1 auth layer allows for write-only users, but our V1 write-path requires looking up buckets via DBRP mappings. That lookup currently performs multiple checks for bucket-read permission, causing failures.
> fix: enable write-only users to pass auth checks in the V1 API

- cmd/influx/v1_authorization.go
Closes #19955
Improve the help for the `--no-password` switch
> chore: Improve help for --no-password switch

- CHANGELOG.md
- http/legacy/write_handler.go
- http/legacy/write_handler_test.go
Closes #19954
This PR remove the automatic creation of buckets and DB/RP mappings when processing V1 `/write` requests.
> fix: Remove bucket and mapping auto-creation from /write API

- http/swagger.yml
This PR adds `operationId` to swagger `POST /delete` operation. `operationId` is required for the [swagger API documentation](https://docs.influxdata.com/influxdb/v2.0/api/) to generate an anchor such as https://v2.docs.influxdata.com/v2.0/api/#operation/PostDelete`. Such links are used in the generated code and documentation of influxdb-client-js, see for example https://influxdata.github.io/influxdb-client-js/influxdb-client-apis.bucketsapi.html
> chore(swagger): add operationId to /delete

- http/swagger.yml
reference: https://github.com/influxdata/ui/pull/293
removes `Invite` and `Invites` components from `http/swagger.yml`
> chore: remove Invites from swagger

- CHANGELOG.md
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/upgrade_test.go
Closes #19973
Removes obsolete unused option `influx-command-path`. which was previously used in security upgrade, but since it is now done at runtime using v1 auth API, this option is obsolete and not used at all.
> fix(upgrade): remove obsolete unused option (influx-command-path)

- CHANGELOG.md
- cmd/influxd/upgrade/setup.go
- cmd/influxd/upgrade/setup_test.go
- cmd/influxd/upgrade/upgrade.go
Closes #19968
Adds check for existence of 2.x CLI configs file. If it exists, `upgrade` fails with error.
> fix(upgrade): check for existing 2.x CLI configs file

- CHANGELOG.md
- cmd/influxd/upgrade/upgrade.go
Closes #19923
Adds `--log-level` option to `upgrade` command with the same default level as `run` ie. _info_.
> fix(upgrade): add log-level option

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- http/legacy/write_handler.go
- http/legacy/write_handler_test.go
Closes #19974 
This is a big of a hack, it doesn't fit how we structure our auth checks elsewhere. Suggestions appreciated!
> fix: check write permission in legacy write path

- CHANGELOG.md
- cmd/influx/backup.go
- cmd/influx/restore.go
This pull request passes the `--skip-verify` flag to the underlying HTTP client in for the `BackupService` & `RestoreService`. This allows backup & restore to work on self-signed servers.
Fixes https://github.com/influxdata/influxdb/issues/19989
> fix: Use --skip-verify flag for backup/restore CLI command.

- CHANGELOG.md
- cmd/influxd/inspect/export_index.go
- cmd/influxd/inspect/inspect.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/main.go
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/v1_dump_meta.go
- cmd/influxd/upgrade/v2_dump_meta.go
Closes #19922 
I'm not incredibly happy with this whack-a-mole approach, but it seemed like the most minimal approach. I'm going to open a separate issue for refactoring the CLI code here.
> fix(cmd/influxd): suggest running with -h on error instead of printing usage

- CHANGELOG.md
- cmd/influx/backup.go
- cmd/influx/restore.go
- cmd/influxd/inspect/export_index.go
- cmd/influxd/inspect/inspect.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/main.go
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/v1_dump_meta.go
- cmd/influxd/upgrade/v2_dump_meta.go
Closes #19993 
Closes #19994 
Backports #19991 and #19995 to the 2.0 branch.
> chore: backport fixes to 2.0

- tsdb/index/tsi1/log_file.go
This commit fixes a locking issue that caused the `TestShard_WritePoints_FieldConflictConcurrent`
test to fail.
Closes #19664
link to the PR (not the Issue)
> fix: Add locking during tsi iterator creation.

- cmd/influxd/launcher/launcher.go
- go.mod
- go.sum
- nats/server.go
This PR is number 2 in a series of 3. In this PR, it resolves observed race conditions finding ports for the embedded nats server, when running test suites that utilise the `TestLauncher`. As a bonus, this improvement reduces test times considerably, by eliminating a slow, fragile loop to find a free port.
> chore: Remove fragile nats port assignment code

- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_internal_test.go
- tsdb/shard.go
- tsdb/shard_test.go
- tsdb/store.go
- tsdb/store_test.go
When an InfluxDB database is very busy writing new points the backup the process can fail because it can not write a new snapshot. The error is: operation timed out with error: create snapshot: snapshot in progress.This happens because InfluxDB takes almost "continuously" a snapshot from the cache caused by the high number of points ingested.
The fix for this was https://github.com/influxdata/influxdb/pull/16627 but it was for OSS only, and was not in the code path for backups in clusters.
This fix adds a `skipCacheOk` flag to `tsdb.Engine.CreateSnapshot()`.
A value of `true` allows the backup to proceed even if a cache snapshot
cannot be taken.
This flag is set to `true` in `tsm1.Engine.Backup()`, the OSS backup code path
and in `tsdb.Shard.CreateSnapshot()`, the cluster backup code …
> fix(tsm1): "snapshot in progress" error during backup

- CHANGELOG.md
- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/database_test.go
- cmd/influxd/upgrade/setup.go
- cmd/influxd/upgrade/setup_test.go
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/upgrade_test.go
Part of #19985
Validate existence / nonexistence of source and target paths provided to the `upgrade` command before doing any work, to avoid annoyance.
> fix(cmd/influxd): validate all input paths to `upgrade` up-front

- http/session_handler.go
See https://golang.org/pkg/net/http/#SameSite.
> fix(http): Add same site strict flag to session cookie

- flags.yml
- kit/feature/list.go
- kv/task.go
- task/backend/analytical_storage.go
- task/backend/analytical_storage_test.go
- task/servicetest/servicetest.go
Closes #19247
This PR will respect the before/after time filters for runs. 
Note that this mirrors the already (new) added functionality from idpe. See influxdata/idpe#8973
> feat(tasks): added functionality to filter runs by time

- CHANGELOG.md
- influxql/_v1tests/query_test.go
- influxql/_v1tests/server_helpers.go
- tests/client.go
- v1/coordinator/statement_executor.go
Closes #19984 
This PR ensures correct behaviour of `SHOW DATABASES`, such that it does not return duplicates for the same database name. Unit tests were added to verify this expectation.
Requires #20004
> fix: Don't include duplicates for SHOW DATABASES

- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/config_test.go
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/upgrade_test.go
Closes #20037 
The help text for `influxd upgrade` says `--v1-dir` is only used if `--config-file` isn't passed, but the validation logic I added in #20012 always validated `--v1-dir`. This fixes the behavior.
I had to refactor config-loading logic to support loading V1 config separately from translating it to V2, so we could still run all validation checks before writing any new files to disk.
> fix(cmd/influxd): don't validate unused paths in `upgrade`

- tsdb/engine/tsm1/engine.go
WIP
Loop with backoff in (*Engine).CreateSnapshot() to retry (*Engine).WriteSnapshot() up to 3 times if ErrSnapshotInPrgress is returned.  Then continue on no error or on SnapshotInProgress if skipCacheOk is true.
-- [X] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
> fix(tsm1): "snapshot in progress" error during backup: restore loop with backoff

- CHANGELOG.md
- gather/prometheus.go
- gather/scheduler.go
- gather/scraper_test.go
- http/swagger.yml
- scraper.go
Closes #20045
- Adding a new optional field, `allowInsecure` with the default value of `false` to the API `POST /api/v2/scrapers`
- Using the new `allowInsecure` field to the `Gather()` method
> fix: Allow self signed certificates to ScraperTarget

- CHANGELOG.md
- gather/prometheus.go
- gather/scheduler.go
- gather/scraper_test.go
- http/swagger.yml
- scraper.go
Closes #20045 
Forward-ports #20047 to `master` (I didn't notice it was targeting `2.0` until after I merged)
> fix: Allow self signed certificates to ScraperTarget (#20047)

- CHANGELOG.md
- cmd/influx/v1_commands.go
- cmd/influx/v1_dbrp.go
- dbrp/http_client_dbrp.go
Closes #19950 
This adds DBRP management to the CLI.
> feat(cli): dbrp cli

- CHANGELOG.md
- cmd/influxd/upgrade/v1_dump_meta.go
- cmd/influxd/upgrade/v2_dump_meta.go
> fix(cmd/influxd): remove internal subcommands of `upgrade` from help text

- CHANGELOG.md
- http/legacy/write_handler.go
- http/legacy/write_handler_test.go
Closes #20070 
If no RP is specified on a V1 write, the system should find & use the default DBRP mapping, not _any_ DBRP mapping.
> fix(http/legacy): filter on Default=true when no RP given in V1 write

- ui/package.json
Relates to #20007 
The UI displays the version that was set in `package.json` at build time. We'll need to fix this "for real" as part of vendoring out the UI, but this will at least make the value correct for 2.0.2.
> chore(ui): bump version in package.json so it displays correctly

- CHANGELOG.md
- dashboards/transport/http_test.go
- http/variable_test.go
- paging.go
Currently, in the API, pagination is not working; to mitigate this, we
can drastically increase the page size.
> fix(api): raise API pagesizes

- cmd/influx/v1_dbrp.go
Closes #20085
As described in #20085, this PR includes the following changes:
* Expand _DBRP_ to _database and retention policy_ in the help text, as DBRP won't make sense to a new user
* At the same time, we're teaching them that the `dbrp` command is an abbreviated form
* Fix a number of identified bugs
> fix: UX improvements and bug fixes to dbrp commands

- CHANGELOG.md
- dbrp/http_server_dbrp.go
- dbrp/http_server_dbrp_test.go
- dbrp_mapping.go
This is to make the DBRP api match the swagger spec.
Closes #20087
> fix(api): make the dbrp api match the swagger spec

- CHANGELOG.md
- paging.go
The default/max are specified in our API spec, so we can't change them without coordinating with cloud.
> fix: revert changes to API page-sizes

- query/storage.go
The rationale is to make the semantics of `ReadWindowAggregateSpec` clearer. 
This PR adds comments partially explaining semantics of `ReadWindowAggregate`. 
They are simply ported from this PR (InfluxDB internal) by @fchikwekwe 
in [this PR](https://github.com/influxdata/idpe/pull/8636/files#diff-94c0a8d7e427e2d7abe49f01dced50ad776b65ec8f2c8fb2a2c8b90e2e377ed5R82) -- I found this information very useful while working on https://github.com/influxdata/influxdb_iox/issues/449 and wanted to make sure it was in OSS as well
> fix: update comment about ReadWindowAggregate semantics

- CHANGELOG.md
- cmd/influx/v1_dbrp.go
- cmd/influxd/launcher/pkger_test.go
- dashboards/transport/http_test.go
- dbrp/http_server_dbrp.go
- dbrp/http_server_dbrp_test.go
- dbrp_mapping.go
- http/variable_test.go
- paging.go
> chore: final backports for 2.0.2

- CHANGELOG.md
I looked through the changes from #20095 and added lines here for things that weren't already covered by a line. PR links point at the original merges to master.
> chore: bring CHANGELOG up to date after 2.0.2 release.

- CHANGELOG.md
- cmd/influx/v1_authorization.go
Closes #20106 
Reach feature-parity with the V2 user creation commands by allowing users to specify passwords as CLI args, enabling automation to bypass the interactive password-entry step.
> feat(cmd/influx): allow for setting v1 passwords via CLI args

- CHANGELOG.md
- coordinator/points_writer.go
In v1.8.3 and earlier, the write path through (*PointsWriter) writeToShardWithContext() always increments the WriteErr count in the debug variables, and does not increment the WriteOK count.
https://github.com/influxdata/influxdb/blob/v1.8.3/coordinator/points_writer.go line 450 should be an `else if err != nil {` instead of an `else`
This has been reported in a customer cloud instance, and verified under a debugger.
Closes: https://github.com/influxdata/influxdb/issues/20098
> fix(write): Successful writes increment write error statistics incorrectly

- CHANGELOG.md
- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/config_test.go
- cmd/influxd/upgrade/upgrade.go
> feat(cmd/influxd): use a better default for upgraded V2 config, and allow users to override it

- .circleci/config.yml
Closes #
This PR updates the build job to use Go 1.15 vs 1.13
> chore(build): build job is now using golang version 1.15

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- kit/cli/viper.go
- kit/cli/viper_test.go
- query/control/controller.go
Closes #20144 
`math.MaxInt32` is the biggest value that the `WaitGroup` wrapped in the query controller will accept without panicking. When I try running `influxd` with that parameter it takes a loooooong time to boot up, but I assume it'd be faster on a beefed-up VM.
> fix: enforce bounds on query-related CLI/config parameters to avoid startup panics

- CHANGELOG.md
- kv/migration/all/0013_repair-DBRP-owner-and-bucket-IDs.go
- kv/migration/all/0014_reindex-DBRPs.go
- kv/migration/all/all.go
Closes #20167
I tested the new command locally, happy to refactor and set up automated tests if the reviewers would like.
> fix(kv): add KV migration to repair DBRP mappings broken by schema change

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- kit/cli/viper.go
- kit/cli/viper_test.go
- query/control/controller.go
Closes #20147
Closes #20148 
Backports #20149
> fix(cmd/influxd): enforce size checks on query-related CLI args

- services/httpd/handler.go
- services/httpd/service.go
This backport uses a single http server to simplify http shutdown.
> fix: Use a single http.Server instance for httpd service

- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/launcher/pkger_test.go
- cmd/influxd/launcher/query_test.go
- cmd/influxd/upgrade/upgrade.go
- kit/cli/loglevelflag.go
- kit/cli/viper.go
- kit/cli/viper_test.go
Part of #19976 
This took more boilerplate than I expected, I could be convinced it's not worth the trouble.
> refactor(cmd/influxd): parse log-level CLI opts directly to correct type

- CHANGELOG.md
- coordinator/points_writer.go
- services/meta/data.go
No need to compute point hash if there is only one shard contained in shard group. We can save a lot of computing resources because of two reason:
1. In the OSS version of the single-node architecture, a shard group must only contain one shard.
2. Each point in the write request needs to call the ShardFor method.
> feat: No need to compute point hash if there is only one shard

- .circleci/config.yml
> chore(build): add grace test runs to daily PR checks

- CHANGELOG.md
- cmd/influx/main.go
- cmd/influx/v1_authorization.go
Related to #20084 
This should hopefully help un-puzzle users if they type the wrong thing.
> feat(cmd/influx): add hints to ID-related errors in DBRP CLI commands

- dbrp/service.go
Noticed this while I was going through porting some of this to IDPE. The new Org-based index for DBRP mappings won't get cleaned up properly without this.
> fix(dbrp): Don't use record ID removing orgID index

- CHANGELOG.md
- cmd/influx/setup.go
When checking for existing configs, check the length of the array after
parsing. There could be an empty config file present.
If --name was specified then use that as the configuration name, regardless of
whether or not there are existing configs.
Allow a 0 (infinite) retention to be specified with --retention when in
interactive mode.
> fix: various improvements to setup command

- CHANGELOG.md
- cmd/influxd/launcher/storage_test.go
- http/delete_handler.go
- http/delete_test.go
- predicate/predicate.go
- storage/engine.go
- tsdb/index.go
- tsdb/store.go
This pull request implements the "delete with predicate" API that was previously disabled. It works by implementing a new `tsdb.Store.DeleteSeriesWithPredicate()` function that operates on a predicate directly instead of an `influxql.Expr`. This PR also adds a `PredicateSeriesIDIterator` that filters an underlying iterator by predicate.
Note: The predicate does not currently support `OR`. That will need to be implemented separately.
Closes https://github.com/influxdata/influxdb/issues/19635
```sh
$ influx write -b influx "cpu,region=us-east-1 value=1"
$ influx write -b influx "cpu,region=us-west-1 value=1"
```
```sh
$ influx query 'from(bucket:"influx")|>range(start:0)' 
Result: _result
Table: keys: [_start, _stop, _field, _measurement, region]
_start:time                      _stop:time …
```
> feat(tsdb): Implement delete with predicate.

- query/iterator.go
- query/iterator_test.go
Customer reported that a GROUP BY query with an offset that caused an interval
to cross a daylight savings change inserted an extra output row off by one hour.
This fix ensured that the start time for the interval of a GROUP BY operator is
correctly set before calculating the time zone offset for that date and time. 
Fixes https://github.com/influxdata/influxdb/issues/20238
> fix(query): Group By queries with offset that crosses a DST boundary can fail

- services/meta/data.go
Clustering requires taking the hash of synthetic points, so
allow this function to work on anything with a HashID.
(cherry picked from commit d96c8fb125468c11680cec71ef1c65067b5fce5e)
> chore: fix clustering build

- ui/package.json
- ui/yarn.lock
Upgrade `flux-lsp-browser` to [flux-lsp v0.5.25](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.25)
Note: This will disable callbacks for user data and any auto-complete functionality that relies on them. This should not require any change to the ui code. See https://github.com/influxdata/flux-lsp/pull/194 for details.
> build(ui): Upgrade flux-lsp-browser to v0.5.25

- CHANGELOG.md
- services/httpd/response_writer.go
JSON marshalling errors should be returned properly formatted in JSON
like other errors.
Fixes https://github.com/influxdata/influxdb/issues/20249
(cherry picked from commit 240707757671f1680838169325adccdd8ef20290)
Closes https://github.com/influxdata/influxdb/issues/20251
This fix formats marshalling errors the same wayinfluxdb formats other query errors.
> fix(error): unsupported value: +Inf" error not handled gracefully

- tcp/mux.go
A customer has seen a rash of "connection refused" errors to the meta node.
This fix ensures that when net.Listener instances are closed because of an
error in Accept(), influxdb logs the error which caused the closures, as well
as any errors in closing the Listeners.
Fixes https://github.com/influxdata/influxdb/issues/20256
> fix: cp.Mux.Serve() closes all net.Listener instances silently on error.

- Makefile
Closes #20288 
I confirmed that this change fixed the panics on `make test-go` in my aarch64 docker image. The goreleaser config still needs updated to match, but I'll do that in my open Docker/release PR.
> fix: detect non-amd64 arch and set noasm tag

- CHANGELOG.md
- tcp/mux.go
A customer has seen a rash of "connection refused" errors to the meta node.
This fix ensures that when net.Listener instances are closed because of an
error in Accept(), influxdb logs the error which caused the closures, as well
as any errors in closing the Listeners.
Fixes https://github.com/influxdata/influxdb/issues/20256
(cherry picked from commit 5b98166b056d78662057ff723aab0cb87616f9f4)
Closes #20278
> fix: cp.Mux.Serve() closes all net.Listener instances silently on error

- ui/package.json
- ui/yarn.lock
Upgrade `flux-lsp-browser` to [v0.5.26](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.26)
> build(ui): upgrade flux-lsp-browser to v0.5.26

- .goreleaser-nightly.yml
- .goreleaser.yml
- CHANGELOG.md
Closes #20337 
Tested using these steps:
1. Ran our CI docker image
2. Cloned this branch
3. Ran `make nightly` to generate archives
4. Ran `dpkg -i` on the generated .deb
5. Copy-pasted the command to run the upgrade script, and confirmed it ran without modifications
> fix: add upgrade helper script to nfpms manifest

- CHANGELOG.md
- scripts/post-install.sh
Closes #20340
In addition to checking for V2 data, check for a V1 config file. Display the upgrade notice when V1 is present and V2 isn't.
To test this, I:
1. Built the .deb from my branch
2. Mounted the .deb into an ubuntu docker container
3. `dpkg -i`'d the .deb, and confirmed:
1. The upgrade notice didn't show
2. `config.toml` was populated with default paths for bolt and engine
4. `dpkg -r influxdb2 && rm /etc/influxdb/config.toml`
5. Set up the influxdata repo, then `apt-get install -y influxdb && apt-get remove -y influxdb`
6. `dpkg -i`'d the .deb, and confirmed the upgrade notice showed
> fix: adjust post-install logic to only display upgrade notice when needed

- CHANGELOG.md
- scripts/init.sh
Addresses #20132 
I think the `set` trick will work since the shebang on the script points at `/bin/bash`, let me know if it's not portable.
Tested by building the package & installing into a fresh ubuntu VM. Without these changes, I see this in the logs:
```
ts=2020-12-15T22:52:12.224551Z lvl=info msg="Resources opened" log_id=0R69W2FG000 service=bolt path=/var/lib/influxdb/.influxdbv2/influxd.bolt
```
After this change, I see:
```
ts=2020-12-15T22:56:05.258672Z lvl=info msg="Resources opened" log_id=0R69jGY0000 service=bolt path=/var/lib/influxdb/influxd.bolt
```
With these env / config file contents:
```
$ cat /etc/default/influxdb2
INFLUXD_CONFIG_PATH=/etc/influxdb/config.toml
$ cat /etc/influxdb/config.toml
bolt-path = "/var/lib/influxdb/influxd.bolt"
engine-path = …
```
> fix: ensure init.d-style install sees our default environment variables

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- cmd/influxd/upgrade/security_test.go
- tenant/error_user.go
- tenant/middleware_onboarding_logging.go
- tenant/service_onboarding.go
- tenant/service_onboarding_test.go
- tenant/service_user.go
- v1/authorization/service_password.go
Fixes #20088 
This was the most obvious problem with the onboarding path's handling of passwords. There's also a lot of duplication in the CLI with slight differences between the onboarding paths for interactive vs. noninteractive runs and the `influx setup` vs. `influxd upgrade` runs, but I'm leaving that refactor for a follow-up PR.
> fix(onboarding): don't ignore failures to set initial password

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
Part of #19976 
Ayan noticed in a separate PR that we were misusing `ctx` values here, resulting in an immediate timeout of our graceful-shutdown code. Splitting out the fix to make it easy to review.
> fix: don't use a finished context for graceful shutdown

- http/swagger.yml
> chore: add dictionaries to the swagger ast specification

- .circleci/config.yml
These steps were accidentally removed in #20358
> build: save cache and artifacts after gotest in CI

- prometheus/converters.go
(cherry picked from commit 5296fe990f6379a535f76d4473368be4996423f5)
Closes https://github.com/influxdata/influxdb/issues/19831
> fix(prometheus): regexp handling should comply with PromQL (#19832)

- CHANGELOG.md
- cmd/influx/main.go
Closes #20054 
This is a lame "fix", but I feel it's the best we can do without significant server-side API changes.
> fix(cmd/influx): improve CLI error returned on org-not-found

- task/backend/executor/executor_test.go
- task/backend/executor/support_test.go
Will comment links to failed jobs inline.
> test: bump & add timeouts in executor tests to avoid flaky failures

- releng/packages/spec/clean_install/_install_uninstall.bash
- releng/packages/spec/clean_install/run.bash
(cherry picked from commit 2e26dc62cbcb670de912be405e1904a1108497db)
> build: switch tested centos base images (#20417)

- cmd/influxd/run/server.go
- coordinator/statement_executor.go
- etc/config.sample.toml
- tsdb/config.go
When a SELECT INTO query generates an illegal value that cannot be inserted,
like +/- Inf, it should return an error, rather than failing silently.
This adds a boolean parameter to the [data] section of influxdb.conf:
* strict-error-handling
When false, the default, the old behavior is preserved.  When true,
unsupported values will return an error from SELECT INTO queries
Closes https://github.com/influxdata/influxdb/issues/20426
> fix(error): SELECT INTO doesn't return error with unsupported value

- CHANGELOG.md
- cmd/influxd/run/server.go
- coordinator/statement_executor.go
- etc/config.sample.toml
- tsdb/config.go
When a SELECT INTO query generates an illegal value that cannot be inserted,
like +/- Inf, it should return an error, rather than failing silently.
This adds a boolean parameter to the [data] section of influxdb.conf:
* strict-error-handling
When false, the default, the old behavior is preserved.  When true,
unsupported values will return an error from SELECT INTO queries
Fixes https://github.com/influxdata/influxdb/issues/20426
(cherry picked from commit 9e33be2619cd0d7ad5a4323455bf5c3308908f23)
Closes https://github.com/influxdata/influxdb/issues/20427
> fix(error): SELECT INTO doesn't return error with unsupported value (#20429)

- CHANGELOG.md
- http/legacy/write_handler.go
- http/legacy/write_handler_test.go
- http/write_handler.go
- http/write_handler_test.go
> fix(http): don't return 500 errors for partial writes

- ui/package.json
Works around #20007
Closes #20373 
The UI build process hard-codes the `version` value from `package.json` into its output, to set the value displayed on the login page.
> chore(ui): bump UI version in prep for 2.0.4 release

- .circleci/config.yml
_facepalms_
This fixes the key of the `godeps` job to match the key expected by all downstream jobs. Important because `godeps` is the step that generates the cache for everything else!
> build: fix cache key used by godeps job

- CHANGELOG.md
- storage/engine.go
Closes #20410 
Backports part of #20313. The `WithLogger` methods do some extra work that was getting skipped.
> fix(storage): use methods to set storage engine loggers

- cmd/influxd/launcher/launcher.go
Preemptive fix for unreleased code.
While running `influxd` in Docker I noticed a new error message on shutdown: `sync /dev/stdout: invalid argument`. uber-go/zap#328 shows the error is known, and the internal "fix" was just to ignore it.
> fix: ignore a harmless error to avoid a confusing log message

- CHANGELOG.md
- cmd/influxd/upgrade/database.go
- cmd/influxd/upgrade/database_test.go
- cmd/influxd/upgrade/setup.go
- cmd/influxd/upgrade/upgrade.go
Closes #20383
Before this patch, we were:
1. Calculating expected disk size needed to make a full copy of V1 data
2. Logging the info, but only in `verbose` mode
3. Auto-proceeding with the copy if the disk had enough space
After this patch:
1. `verbose` is deprecated/hidden in favor of debug-level logging (reduce the number of levers users need to pull to get useful diagnostics)
2. Most verbose-level logs are now debug, but the size-log is info
3. Add an explicit y/n input point before copying data (skippable by using `--force`)
> fix(cmd/influxd): improve `influxd upgrade` logging, and require manual confirmation of data copy

- CHANGELOG.md
- dbrp/error.go
- dbrp/http_client_dbrp.go
- dbrp/http_server_dbrp.go
- dbrp/http_server_dbrp_test.go
- dbrp/service.go
> fix(dbrp): improve DBRP API validation errors

- CHANGELOG.md
- bolt/bbolt.go
Closes #20051 
Kinda lame, but I think it's the best we can do without modifying `bolt` itself.
> fix: inject more specific error message for bolt on shared FS

- ui/package.json
- ui/yarn.lock
Upgrade flux-lsp-browser to [v0.5.27](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.27)
> chore(ui): Upgrade flux-lsp-browser to v0.5.27

- .circleci/config.yml
- docker/influxd/Dockerfile
Closes #20479 
* Reduce cache usage across job types (I saw weird errors about files missing from paths in the GOCACHE)
* Split our Dockerfile into multiple stages, with all `RUN` commands in the 1st stage
* Uninstall any system-provided emulators before installing the recommended `binfmt` QEMU
* Move our Docker setup to the front of the cross-build steps
* Build the 1st stage of our Docker immediately after setting up the cross-builder, to fail fast on any issues
> build: adjust emulator setup and ordering for Docker cross-build

- .circleci/config.yml
Closes #20505
Follows the instructions described in [this blog post](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/) from the CircleCI team.
> build: add guards against using secrets in forked PR builds

- CHANGELOG.md
- cmd/influxd/upgrade/upgrade.go
- cmd/influxd/upgrade/upgrade_test.go
> feat(cmd/influxd): add --overwrite-existing-v2 flag to influxd upgrade

- tsdb/shard.go
- tsdb/shard_test.go
fields.idx frequent writes cause lock contention and fields.idx is recreated
when a field or measurement is added in a WritePointsWithContext()
Closes https://github.com/influxdata/influxdb/issues/20500
This eliminates locking during the actual file rewrite, and limits it to
the times when the MeasurementFieldSet is actually being read or written
> fix(tsdb): minimize lock contention when adding new fields or measurements

- CHANGELOG.md
- kit/cli/viper.go
- kit/cli/viper_test.go
Closes #20521
The actual fix is 1 character, but I took the chance to beef up our tests in this area.
> fix(kit/cli): fix loading of .yml config files

- CHANGELOG.md
- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_internal_test.go
- tsdb/shard.go
- tsdb/shard_test.go
- tsdb/store.go
- tsdb/store_test.go
Closes #20526 
Backports the end combination of #19869 and #20063, which I believe were the relevant PRs in 1.x.
> fix(tsdb): allow backups during snapshotting, and don't leak tmp files

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/print_config.go
- cmd/influxd/launcher/print_config_test.go
Closes #20517 
This command is meant to support our Docker entry-point in two ways.
First, in our documentation for how to customize the `influxd` config we can advise running `influxd print-config` to generate a starting template file. This mirrors the [existing docs](https://github.com/influxdata/docker-docs/blob/master/influxdb/README.md#configuration) for our 1.x image.
Second, we want the container entry-point to support running setup scripts mounted by the user, but _only_ if the DB hasn't already been set up. To do this in a robust way while also supporting custom config / env vars / CLI args, we need to be able to determine the final values of configs like the bolt path & HTTP bind address. We can use `influxd print-config` with the `--key-name` option to do this.
If the user runs …
> feat(cmd/influxd): add `print-config` subcommand to support automation

- ui/package.json
- ui/yarn.lock
[Flux LSP v0.5.28](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.28)
> chore(ui): Update flux-lsp-browser to v0.5.28

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
Closes #16442
Relevant git archeology:
* `nats.NewDefaultServerOptions()` returns a struct with `Port` set to `4222`
* Unit tests that used the `influxd` launcher sometimes failed with port conflicts because of NATS
* 047afcfc10fec049e09b4abd396b9cd104203886 added a hacky loop that would try to find an unused port closest to `4222`
* fab99c9512f86bd013fbd0c933865bbf17e9bfe7 replaced the loop with a built-in marker for random port selection
Random isn't very good for running in Docker, so we add a config parameter to support setting a specific value. I left the default as random just in case.
> feat(cmd/influxd): add `nats-port` config option to influxd server

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
Closes #19713 
I went with raw bytes instead of a `toml.Size` for simplicity, but I could be convinced to change it.
> feat(cmd/influxd): add `nats-max-payload-bytes` config option to influxd

- CHANGELOG.md
- http/legacy/influxqld_handler.go
- http/legacy/influxqld_handler_test.go
- http/swaggerV1Compat.yml
- influxql/_v1tests/server_helpers.go
- influxql/_v1validation/goldenfiles/example_generated.yaml
- influxql/_v1validation/goldenfiles/join.yaml
- influxql/_v1validation/goldenfiles/select_aggregate.yaml
- influxql/_v1validation/goldenfiles/select_simple.yaml
- influxql/_v1validation/goldenfiles/select_star.yaml
- influxql/_v1validation/validation.json
- influxql/_v1validation/validation_test.go
- influxql/query/response_writer.go
- influxql/query_request.go
- influxql/query_request_test.go
Closes #20514 
See reasoning for this approach in the issue.
> fix(influxql): set correct Content-Type on v1 query responses

- cmd/influxd/launcher/launcher_helpers.go
- internal/cmd/fluxtest-harness-influxdb/test.go
The internal command can be used to execute flux tests using the same
internals as the `flux test` command, but it will invoke these tests
against a test influxdb instance that is launched in-process.
Closes #19882.
> feat(internal/cmd): add internal command for influxdb flux test harness

- kv/migration/migration.go
> fix(kv): log migration events at debug level to avoid spam

- CHANGELOG.md
- cmd/influx/query.go
Closes #19782 
I tested this manually for now to avoid TLS setup headaches in our CI/CD process.
> fix(cmd/influx): respect --skip-verify in `influx query`

- ui/package.json
- ui/yarn.lock
[Flux LSP v0.5.29](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.29)
> chore(lsp): Upgrade flux-lsp-browser to v0.5.29

- go.mod
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/engine/tsm1/iterator.go
- tsdb/index.go
- tsdb/series_file.go
When using queries like 'select count(_seriesKey) from bigmeasurement`, we
should iterate over the tsi structures to serve the query instead of loading
all the series into memory up front.
Closes #20543
> feat(tsi): optimize series iteration

- CHANGELOG.md
- ui/src/shared/constants/fluxFunctions.ts
Closes #20606
Backports #20495 
Bugfix because the backend Flux change was merged in October 2020: https://github.com/influxdata/flux/commit/d115c75ebd33120b58bce1c697ea1f3df223ce4d
> fix(ui): update Flux function list to reflect renamed package

- cmd/influxd/launcher/launcher.go
- go.mod
- go.sum
- internal/cmd/fluxtest-harness-influxdb/test.go
- query/stdlib/testing/end_to_end_test.go
- query/stdlib/testing/testing.go
> feat(fluxtest): add support for testing/expect planner rules

- .circleci/config.yml
- write/batcher.go
- write/batcher_test.go
Closes #20667
The 2nd commit is unrelated, but useful for having Support test with binaries built from branches.
> fix(write): drop empty lines from write batches

- CHANGELOG.md
- cmd/influx/user.go
- cmd/influx/user_test.go
Closes #20645 
I manually tested the case of setting a password without specifying an org, it's tough to unit-test because the org-flag helpers are coded to read a global config file as a fallback when no flags are passed in.
> fix(cmd/influx): allow for creating users without initial passwords in `influx user create`

- CHANGELOG.md
- http/write_handler.go
- http/write_handler_test.go
- influxql/_v1tests/server_helpers.go
- mock/write_service.go
- tests/client.go
- write.go
- write/batcher.go
- write/batcher_test.go
Closes #20675
As part of this, I deleted an alternate `Write` method that was only used in testing. The two impls had slightly different behavior (`Write` didn't have the bug, but it also didn't support writing-by-name instead of by-ID). Hopefully eliminating one option will make testing & catching bugs easier in the future.
> fix(http): fix passing of bucket ID by write-handler client

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- go.mod
- go.sum
- internal/cmd/fluxtest-harness-influxdb/test.go
- query/stdlib/testing/end_to_end_test.go
- query/stdlib/testing/testing.go
- task/options/flux_deps.go
- ui/package.json
- ui/yarn.lock
Closes #20391
Closes #20470
Backports #20508, #20554, #20662, #20678, and #20680
> chore: update flux to pull latest fixes into release

- tsdb/store.go
Closes #17059
The original fix for this issue used a custom error string, it would be better to use the `ErrShardNotFound`
error.
> fix: consistent error for missing shard

- cmd/influxd/run/server.go
- coordinator/points_writer.go
- coordinator/points_writer_test.go
- coordinator/statement_executor.go
- etc/config.sample.toml
- internal/tsdb_store.go
- services/collectd/service.go
- services/collectd/service_test.go
- services/graphite/service.go
- services/graphite/service_test.go
- services/opentsdb/handler.go
- services/opentsdb/service.go
- services/opentsdb/service_test.go
- services/udp/service.go
- services/udp/service_test.go
- tsdb/config.go
- tsdb/ingress_metrics.go
- tsdb/ingress_metrics_test.go
- tsdb/store.go
- tsdb/store_test.go
After turning on authentication and both forms of ingress metrics:
"ingress": {"name":"ingress","tags":{"db":"_internal","login":"_systemuser_monitor","measurement":"cq","rp":"monitor"},"values":{"pointsWritten":38,"valuesWritten":76}},
"ingress:1": {"name":"ingress","tags":{"db":"_internal","login":"_systemuser_monitor","measurement":"database","rp":"monitor"},"values":{"pointsWritten":76,"valuesWritten":152}},
"ingress:2": {"name":"ingress","tags":{"db":"_internal","login":"_systemuser_monitor","measurement":"httpd","rp":"monitor"},"values":{"pointsWritten":38,"valuesWritten":874}},
"ingress:3": {"name":"ingress","tags":{"db":"_internal","login":"_systemuser_monitor","measurement":"ingress","rp":"monitor"},"values":{"pointsWritten":534,"valuesWritten":1068}},
"ingress:4": …
> feat: ingress metrics by login

- .circleci/config.yml
The nightly grace tests have been failing, but I can't tell why because report collection is broken.
> build: fix test-result collection for grace_nighty job

- cmd/influx/main.go
- cmd/influx/write.go
- cmd/influx/write_test.go
Before we start adding new functionality to `influx write`, I wanted to give the existing tests a facelift.
> refactor(cmd/influx): clean up existing tests for `influx write`

- CONTRIBUTING.md
Tiny PR to fix up the docs - OSX build appears to need pkg-config with normal 'make' build, so add it to the docs.
> docs: OSX always needs pkg-config

- .circleci/config.yml
- .goreleaser.yml
- CHANGELOG.md
Closes #20697 
Update our binaries to match [Google naming conventions](https://developers.google.com/style/filenames).
> build: update naming conventions for nightly builds to prefer hyphens

- CHANGELOG.md
- kit/cli/viper.go
- kit/cli/viper_test.go
Closes #20696
Instead of using an extension-check to guess if `INFLUXD_CONFIG_PATH` is pointing to a file vs. a directory, use `os.Stat` + `IsDir()`.
This change introduces a new failure mode when `INFLUXD_CONFIG_PATH` is set in the env, but points to a nonexistent file. I think that's a win, but could be convinced to revert to the previous behavior.
> fix(kit/cli): fix loading config from directories with '.' in the name

- cmd/influx_inspect/buildtsi/buildtsi.go
- cmd/influx_inspect/verify/seriesfile/verify_test.go
- cmd/influx_tools/generate/exec/generator.go
- cmd/influx_tools/importer/series_writer.go
- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/index.go
- tsdb/index/inmem/inmem.go
- tsdb/index/inmem/inmem_test.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/log_file.go
- tsdb/index/tsi1/log_file_test.go
- tsdb/index/tsi1/partition.go
- tsdb/index_test.go
- tsdb/ingress_metrics.go
- tsdb/ingress_metrics_test.go
- tsdb/series_file.go
- tsdb/series_file_test.go
- tsdb/series_partition.go
- tsdb/shard.go
- tsdb/store.go
After turning this on and testing locally, note the 'seriesCreated' metric
"localStore": {"name":"localStore","tags":null,"values":{"pointsWritten":2987,"seriesCreated":58,"valuesWritten":23754}},
"ingress": {"name":"ingress","tags":{"db":"_internal","login":"_systemuser_monitor","measurement":"cq","rp":"monitor"},"values":{"pointsWritten":2,"seriesCreated":1,"valuesWritten":4}},
"ingress:1": {"name":"ingress","tags":{"db":"_internal","login":"_systemuser_monitor","measurement":"database","rp":"monitor"},"values":{"pointsWritten":2,"seriesCreated":2,"valuesWritten":4}},
"ingress:2": {"name":"ingress","tags":{"db":"_internal","login":"_systemuser_monitor","measurement":"httpd","rp":"monitor"},"values":{"pointsWritten":2,"seriesCreated":1,"valuesWritten":46}},
"ingress:3": …
> feat: series creation ingress metrics

- CHANGELOG.md
- http/swagger.yml
> chore: add flux dictionaries to the swagger AST specification

- pkg/estimator/hll/hll.go
- query/call_iterator.go
- query/compile.go
- query/functions.gen.go
- query/functions.gen.go.tmpl
- query/functions.go
- query/functions_test.go
- query/iterator.go
- query/iterator_test.go
- query/select.go
- query/select_test.go
- tsdb/engine/tsm1/engine.go
Closes #717
Adds HyperLogLog operator to influxql to allow computing count-distinct approximately.
> feat(query): Hyper log log operators in influxql

- CHANGELOG.md
* Geo feature was (purposefully) left out of 2.0.4
* Flux-related features are purposefully filled in at release time to avoid pointless churn when it's upgraded every week
Dated for release today
> chore: update CHANGELOG to reflect final status of 2.0.4

- CHANGELOG.md
- tsdb/index.go
This use-after-free bug may lead to segfault. The iterators that have
reference to the underlying index files were closed too early while
the bitmaps were still used afterwards. If a compaction occurs
concurrently and removes the index files, it would result in accessing
unmap'd memory address.
> fix(tsi): close series id iterator after merging

- CHANGELOG.md
- tsdb/engine/tsm1/wal.go
- tsdb/engine/tsm1/wal_test.go
it should check against the local saved SegmentSize instead of the
default const DefaultSegmentSize.
> fix(tsm): should not check write-ahead-log size against default size

- query/statement_rewriter.go
- query/statement_rewriter_test.go
- tests/server_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/iterator.go
- tsdb/index.go
Closes #20614
In addition to the query rewrites, fix a recent bug in seriesKey iteration exposed by the cardinality tests,
and add an extra tests for the recent ingress metric work.
> feat: use count_hll for 'show series cardinality' queries

- cmd/telemetryd/main.go
- gather/scheduler_test.go
- http/legacy/router.go
- http/router.go
- logger/logger.go
- tsdb/engine/tsm1/engine_internal_test.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/engine/tsm1/file_store_test.go
- tsdb/engine/tsm1/iterator_test.go
- tsdb/index/tsi1/sql_index_exporter_test.go
- tsdb/index_test.go
- tsdb/series_file_test.go
- tsdb/shard_internal_test.go
- tsdb/shard_test.go
- tsdb/store_test.go
- v1/services/precreator/service_test.go
- v1/services/retention/service_test.go
Related to #20579 
The ultimate goal is to adjust the implementation / APIs in the `logger` package for more consistency across our CLI commands. When I started making changes I noticed many tests stopped building.
I think this is a nice stand-alone win. Zaptest's logger automatically sets debug-level logging, and only shows the logs for a test if the test fail or `-v` is passed to `go test`.
> test: replace influxlogger with zaptest logger

- CHANGELOG.md
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/file_store_key_iterator_test.go
- tsdb/engine/tsm1/file_store_test.go
- tsdb/engine/tsm1/reader.go
- tsdb/engine/tsm1/reader_test.go
- tsdb/engine/tsm1/tombstone.go
- tsdb/engine/tsm1/tombstone_test.go
> fix(tsm1): fix data race when accessing tombstone stats

- tsdb/engine/tsm1/tombstone.go
Fixes up #20773, see https://github.com/influxdata/influxdb/commit/efd766d60febc066f14caf59f87cdcf99a5319f5#r47320007
> fix(tsm1): mark tombstone stats as loaded to enable caching

- CHANGELOG.md
- cmd/influx/write.go
- cmd/influx/write_test.go
Closes #20659
This is meant to mirror the implementation of the existing CSV support.
* A new CLI option allows for explicitly specifying compression of all inputs
* If the flag isn't set, the line-reader checks the names of input files & URLs to detect GZIP
* Files or URLs ending in `.gz` enable decompression
* URLs that respond with `Content-Encoding: gzip` enable decompression
Unlike the existing CSV impl, gzip-or-not is handled on an input-by-input basis when the CLI option isn't set.
> feat(cmd/influx): support reading GZIP data in `influx write`

- cmd/influxd/run/server.go
- coordinator/statement_executor.go
- internal/tsdb_store.go
- query/executor.go
- query/executor_test.go
- query/task_manager.go
- services/continuous_querier/service_test.go
- services/httpd/handler_test.go
- services/storage/store.go
- tests/server_concurrent_test.go
- tsdb/store.go
- tsdb/store_test.go
Meta queries (SHOW TAG VALUES, SHOW TAG KEYS, SHOW SERIES CARDINALITY, etc.) do not respect
the QueryTimeout config parameter. Meta queries should check the query context when possible
to allow cancellation and timeout. This will not be as frequent as regular queries, which
use iterators, because meta queries return data in batches.
Add a context.Context to
(*Store).MeasurementNames()
(*Store).MeasurementsCardinality()
(*Store).SeriesCardinality()
(*Store).TagValues()
(*Store).TagKeys()
(*Store).SeriesSketches()
(*Store).MeasurementsSketches()
which is tested for timeout or cancellation
to allow limitation of time spent in meta queries
Closes https://github.com/influxdata/influxdb/issues/20736
> feat: Make meta queries respect QueryTimeout values

- tsdb/engine/tsm1/ring.go
- tsdb/engine/tsm1/ring_test.go
Backport of #20797 (which was a forward-port++ of #20172)
> fix(tsm1): fix data race and validation in cache ring

- Makefile
Commit https://github.com/influxdata/influxdb/commit/074cd24a60ddd5aa2a851a7d04faaef5c126562a added a fix to compile with the go noasm build tag for all non-amd64 arch because arm64 tests panic without it. This also makes s390x compile with noasm even though the tests run fine on s390x without noasm. 
This change adds s390x to the list of architectures that should not set noasm.
> fix: detect s390x arch and exclude noasm tag

- CHANGELOG.md
- authorizer/task_test.go
- cmd/influx/setup.go
- cmd/influxd/upgrade/security_test.go
- cmd/influxd/upgrade/setup.go
- http/swagger.yml
- onboarding.go
- tenant/service_onboarding.go
- tenant/service_onboarding_test.go
- testing/onboarding.go
- tests/pipeline_helpers.go
Closes #20452 
Using seconds as the unit matches the create-bucket API. Need to open a matching PR in Cloud
> fix(onboarding): deprecate misleading `retentionPeriodHrs` key

- CHANGELOG.md
- README.md
- ui/src/shared/constants/fluxFunctions.ts
Correct the default port desc to 8086. as the default port has been changed.[1]
[1] https://github.com/influxdata/influxdb/pull/19494
- [-] Tests pass
> correct the default port desc to 8086

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
- chronograf/server/mux.go
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/main.go
- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/config_test.go
- http/authentication_middleware.go
- http/handler.go
- http/handler_test.go
- pprof/http_server.go
- pprof/pprof.go
Closes #20764
The big chunks of new logic are the `/all` profile, ported from 1.x. I didn't port the pieces of that code that gathered InfluxQL statistics, since we have other endpoints & tooling for scraping that info.
As a side-effect of switching away from using the default Mux, the `/debug/vars` endpoint is no longer exposed. Those vars were mostly empty in 2.x since we turned off the internal diagnostics service. The `/metrics` endpoint is the intended replacement.
> feat(http): allow for disabling pprof

- services/httpd/response_writer.go
Closes #20249
We should avoid infinite recursion!
> fix: infinite recursion bug

- cmd/influx/main.go
- cmd/influxd/inspect/export_lp.go
- cmd/influxd/inspect/inspect.go
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/print_config.go
- cmd/influxd/main.go
- cmd/influxd/upgrade/upgrade.go
- cmd/telemetryd/main.go
- kit/cli/viper.go
- kit/cli/viper_test.go
1st "half" of #20491
Return errors from `kit/cli` code instead of using `panic`. The impact was pretty minimal outside of `cmd/influx`, so I've included the fixed up code here. The impact on the `influx` CLI is very extensive, so I've shimmed a `panic` back in at that layer for now. Will open a follow-up to finish the job after this one merges, in case we decide it's not worth the diff.
> refactor: remove panics from CLI kit code and influxd CLI setup

- CHANGELOG.md
- ui/src/dashboards/constants/index.ts
- ui/src/shared/components/tables/TableGraphTable.tsx
- ui/src/shared/utils/vis.ts
Closes https://github.com/influxdata/ui/issues/768
Identical to change made in InfluxDB Cloud UI. See https://github.com/influxdata/ui/pull/772
- 'HH' triggers 24 hour clock format
- Add more choices to allow users to keep 12 hour formats
- Add meridiem to 12 hour formats
> fix(ui): respect 24 hour clock format and allow more choices

- tsdb/engine/tsm1/cache.go
- tsdb/engine/tsm1/cache_test.go
Suggested by @StoneYunZhao in https://github.com/influxdata/influxdb/pull/20843#issuecomment-789472552
The `Write` method was only used in tests. To avoid a huge diff, I added a method in the test code that translates `Write` calls to `WriteMulti` calls.
> refactor(tsm1): delete unused Write method on cache

- CHANGELOG.md
- tsdb/engine/tsm1/wal.go
- tsdb/engine/tsm1/wal_test.go
Closes #20742
Backports #20585
> fix(tsm): use configured value instead of default when checking WAL segment size

- CHANGELOG.md
- tsdb/shard.go
- tsdb/shard_test.go
…ments (#20504)
fields.idx frequent writes cause lock contention and fields.idx is recreated
when a field or measurement is added in a WritePointsWithContext()
This eliminates locking during the actual file rewrite, and limits it to
the times when the MeasurementFieldSet is actually being read or written
in memory and when the new file is being renamed.
Test verification of correct behavior by checking the fields.idx
file matches the in-memory copy after heavily parallel measurement addition.
Fixes https://github.com/influxdata/influxdb/issues/20500
(cherry picked from commit fe3af66c54ff00400acdbe4d73ff66485d34fd91)
> fix(tsdb): minimize lock contention when adding new fields or measure

- CHANGELOG.md
- services/httpd/response_writer.go
* Revert "fix(error): unsupported value: +Inf" error not handled gracefully (#20250)"
This reverts commit 6ac0bb3fe337ca6ec6a7ad651a2ec533c049dae4.
* fix: No infinite recursion on write error
If there is some error writing to the response writer, we
would previous have infinite recursion.
Re-closes https://github.com/influxdata/influxdb/issues/20249
(cherry picked from commit d6f7716924d40aa55304d2c60e266af173163065
> fix: infinite recursion bug (#20862)

- ui/package.json
Works around #20007
Closes #20715
The UI build process hard-codes the `version` value from `package.json` into its output, to set the value displayed on the login page.
> chore(ui): bump UI version in prep for 2.0.5 release

- storage/reads/array_cursor.gen.go
Backport https://github.com/influxdata/influxdb/commit/abfe5a54a0b419d0231762574229caddf971bbfd
(cherry picked from commit 77d1a4180b09f83138c59ca5ae9294ee771e1d86)
Closes #
> fix(storage): ArrayFilterCursor truncation for multi-block data (#19439)

- flux/stdlib/influxdata/influxdb/buckets.go
- patches/flux.patch
The buckets call had a column removed and the backport did not remove
that line. This modifies the buckets command to not append a row to a
column that no longer exists.
(cherry picked from commit 637ca24d5e933cd147882c324914f5f5548e09e6)
Closes #
> fix(flux): buckets call no longer panics (#17319)

- services/storage/store.go
The storage read service would return a nil cursor if there was no data
and no shards to read from. This modifies it to return an empty cursor
instead.
(cherry picked from commit 2852bf0399c279d2f665fd6484d8bd75ccae1430)
Closes #
> fix: storage read service should not return a nil cursor (#17359)

- CHANGELOG.md
- ui/src/shared/components/tables/TableCell.tsx
Closes https://github.com/influxdata/ui/issues/815
Follow-up to https://github.com/influxdata/influxdb/pull/20856 - don't format the time column headers
Matching pull request in UI: https://github.com/influxdata/ui/pull/833
> fix: prevent time field names from being formatted

- CHANGELOG.md
- cmd/influxd/upgrade/upgrade.go
Make upgrade error in upgrade log more specific.  It isn't very helpful here.
Closes #
> fix(cmd/influx): log error details when `influxd upgrade` fails to migrate databases

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- http/handler.go
- http/handler_test.go
- kit/transport/http/error_handler.go
- pprof/http_server.go
Closes #20755
NOTE: We wire up the `influxd` process with a `prom.Registry` even when `/metrics` is disabled, because the metrics are also used by our telemetry reporter. A follow-up improvement could avoid all the prometheus code paths when _both_ metrics and reporting are disabled.
> feat(http): add config option to disable metrics endpoint in influxd

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- Makefile
- cmd/influxd/launcher/_ssltests/ssl_test.go
- cmd/influxd/launcher/_tlstests/tls_test.go
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- etc/test-tls.sh
Closes #20762
The cipher suite we had hard-coded was invalid, and would cause the `influxd` process to hang on startup. The user who reported the problem referenced a Mozilla page that showed the proper suite to use, so I swapped to using it. I also fixed the code so a failure to serve HTTP/HTTPS will cause `influxd` to exit instead of hang.
I've added a regression suite to check that enabling TLS works at all. Hopefully that'll catch problems like this in the future...
> fix(tls): Update TLS strict cipher suite to actually work 

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
Closes #20769
I left the defaults for the read- and write-timeout parameters as 0, as I assume those will be workload-dependent.
> feat(http): add config parameters for HTTP timeouts

- CONTRIBUTING.md
- DEVELOPMENT.md
- README.md
Updates the Go version referenced in `README.md` under "Building From Source" to be Go 1.15 instead of Go 1.13. Go 1.15 is required to successfully build from source. This is purely a documentation update.
> docs(readme): update README to reference go 1.15

- CONTRIBUTING.md
#20747 deleted `DEVELOPMENT.md` as it was mostly outdated. I missed a reference to it in `CONTRIBUTING.md`
> docs: remove broken reference to old DEVELOPMENT.md

- CHANGELOG.md
- cmd/influx_inspect/export/export.go
add a special value to the -out flag, a hyphen, to write to stdout.
While writing to stdout, send status messages to stderr instead of
stdout (the current behavior).
Closes https://github.com/influxdata/influxdb/issues/20974
> feat: influx_inspect export to standard out

- CHANGELOG.md
- cmd/influx_inspect/export/export.go
Add a special value to the -out flag, a hyphen, to write to stdout.
While writing to stdout, send status messages to stderr instead of
stdout (the current behavior).
Closes https://github.com/influxdata/influxdb/issues/20974
(cherry picked from commit 642726e898c895b82b81784f79adfe4b296f2f54)
Closes https://github.com/influxdata/influxdb/issues/20976
https://github.com/influxdata/docs-v2/issues/2308
> feat: influx_inspect export to standard out (#20977)

- CHANGELOG.md
- services/httpd/response_logger.go
The HTTP handler logs URLs, but not body values for POST requests.
This means that queries sent by GET are logged, because the query
is in the URL, but queries sent by POST have no query text in the
log.  This feature prints all the key-value pairs in the post body,
which includes the query text
Closes https://github.com/influxdata/influxdb/issues/20653
> feat: Log query text for POST requests

- CHANGELOG.md
- services/httpd/response_logger.go
The HTTP handler logs URLs, but not body values for POST requests.
This means that queries sent by GET are logged, because the query
is in the URL, but queries sent by POST have no query text in the
log.  This feature prints all the key-value pairs in the post body,
which includes the query text, except passwords, which are redacted.
Closes https://github.com/influxdata/influxdb/issues/20653
(cherry picked from commit 70755bf42c075f474a49f59d515d84310ef8cace)
Closes https://github.com/influxdata/influxdb/issues/21000
> feat: Log query text for POST requests (#20993)

- go.mod
This appears to be the only place where influxdata/plutonium#3339 occurs in source
> fix: set correct go version in go.mod

- bolt/bbolt.go
- bolt/metrics.go
- bolt/metrics_test.go
Closes #20999 
I'm not happy with the timing-based pieces of the test I added, but it's probably better than nothing?
> fix(bolt): prevent concurrent access to telegraf plugin metrics cache

- CHANGELOG.md
- cmd/influxd/inspect/export_lp.go
Closes #20975
Forward-ports the relevant piece of #20977. The 2.x command doesn't write out DML, and was already configured to log to stderr by default.
> feat(cmd/inflxud): add support for writing to stdout in `export-lp`

- CHANGELOG.md
- cmd/influx_inspect/help/help.go
> fix: help text for influx_inspect

- releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash
Closes #21061
Newer versions of Flux depend on Apache Arrow, which uses c2goasm to optimize some operations (see [their README](https://github.com/apache/arrow/tree/master/go#performance)). The optimized code only works on `amd64` and `s390x`; other architectures will panic.
Setting the `noasm` tag disables the optimizations. We added the tag to the 2.x line across a few PRs:
* #20260
* #20290
> build: set 'noasm' tag when building ARM64 binaries

- CHANGELOG.md
- cmd/influxd/run/config.go
- cmd/influxd/run/server.go
- prometheus/converters.go
- prometheus/converters_test.go
- query/control/controller.go
- query/control/controller_test.go
- query/control/metrics.go
Closes #17212
A sample of the new config:
```
[flux-controller]
query-concurrency = 0
query-initial-memory-bytes = 0
query-max-memory-bytes = 0
total-max-memory-bytes = 0
query-queue-size = 0
```
Also use the prometheus metrics in debug/vars, here is a sample:
```
"query_control_all_active": {"name":"query_control_all_active","tags":null,"values":{"gauge":0}},
"query_control_all_duration_seconds": {"name":"query_control_all_duration_seconds","tags":null,"values":{"0.001":0,"0.005":0,"0.025":0,"0.125":0,"0.625":0,"15.625":2,"3.125":2,"count":2,"sum":2.9953034240000003}},
"query_control_compiling_active": {"name":"query_control_compiling_active","tags":null,"values":{"gauge":0}},
"query_control_compiling_duration_seconds": {"name":"query_control_compiling_duration_seconds","tags":null,"value …
```
> feat: make flux controller limits configurable

- .circleci/config.yml
- CHANGELOG.md
- ui/Makefile
- ui/README.md
- ui/cypress.json
- ui/cypress/e2e/checks.test.ts
- ui/cypress/e2e/dashboardsIndex.test.ts
- ui/cypress/e2e/dashboardsView.test.ts
- ui/cypress/e2e/explorer.test.ts
- ui/cypress/e2e/notificationRules.test.ts
- ui/cypress/e2e/queryBuilder.test.ts
- ui/cypress/e2e/tasks.test.ts
- ui/cypress/e2e/telegrafs.test.ts
- ui/cypress/e2e/tokens.test.ts
- ui/cypress/e2e/variables.test.ts
- ui/cypress/support/commands.ts
- ui/fetch_ui_assets.sh
Backports #21090
Everything is the same except for a couple of differences:
- The `.circleci/config.yml` file isn't the same between the `master` branch and the `2.0` branch for reasons outside this change. For this backport, I removed everything related to `jslint` and `jstest` from the `2.0` config, as well as bumping the e2e resource class to `large`. This is conceptually identical to the PR on master.
- The URL for the `fetch_ui_assets.sh` script is different since the OSS 2.0 branch will get its assets from a different release in the `ui` repository - one on the `ui` branch `OSS-2.0`.
> feat: synchronize ui folder with ui repository

- internal/shard/writer.go
- storage/flux/table_test.go
This ports the table tests that existed with the pre-beta version of the
storage engine to the one that is now used in the production version.
A few of the tests are skipped. These are portions of the storage engine
that have not been ported over. They should be unskipped when that
functionality is ported over.
> tests(storage/flux): port table tests for the storage engine

- internal/shard/writer.go
- storage/flux/table_test.go
Backports #21128
Only change needed was removing the `platform` import, and renaming `platform.ID` -> `influxdb.ID`
> test(storage/flux): port table tests for the storage engine

- CHANGELOG.md
- services/httpd/handler.go
> fix: redundant registration for prometheus collector metrics

- CHANGELOG.md
- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
Closes #21163
Backports #21158
In `kit/transport/http/middleware.go` the properties and methods associated with ID's have been moved from `influxdb` to `platform` per #21101 on `master`. Since the `2.0` branch continues to use `influxdb` for ID's, this backport uses `influxdb.IDLength` and `influxdb.IDFromString(...)` instead of their respective `platform` equivalents on the `master` branch.
> feat(telemetry): replace unique ids for resources with a slug

- CHANGELOG.md
- flux/stdlib/influxdata/influxdb/operators.go
- flux/stdlib/influxdata/influxdb/rules.go
- flux/stdlib/influxdata/influxdb/rules_test.go
- flux/stdlib/influxdata/influxdb/source.go
- flux/stdlib/universe/bare_aggregate_test.flux
- flux/stdlib/universe/window_aggregate_by_time_test.flux
- flux/stdlib/universe/window_aggregate_test.flux
- internal/cmd/fluxtest-harness-influxdb/test.go
- services/storage/store.go
- storage/reads/aggregate_resultset.go
Backports #21124
This includes:
* The fix for last() within the `WindowAggregate` cursor code
* Rewrite rules for bare & window aggregates
* e2e test cases showing everything works
> feat(flux): implement rewrite rules for window and bare aggregates

- .circleci/config.yml
The port of `changelog` from jenkins is failing. This PR disables it until/unless it's better understood.
> chore: Circleci/remove changelog job

- flags.yml
- kit/feature/list.go
- ui/cypress/e2e/explorer.test.ts
Partially closes #21164
This PR turns "on" the feature flags for various UI features, including:
- Axis Ticks Generator (for controlling the number of axis ticks on plots)
- Band Plot Type
- Mosaic Plot Type
- UI CSV Uploader (upload annotated CSVs to a bucket)
- Editable Telegraf Configurations (edit telegraf configs from the UI)
- Legend Orientation in the UI (customize the appearance of the legend)
- Refresh Single Cell (instead of refreshing the entire dashboard's cells)
The two that aren't being turned on with this PR are listed below. To turn these on, we will need to move on from using our "legacy" e2e tests in `influxdb/ui/cypress` and be able to use the latest and greatest e2e tests from the `ui` repo, the implementation of which is described in …
> feat(ui): enabling feature flags for various UI features

- tenant/http_server_bucket.go
Closes #21169
For backwards-compatibility, send an empty array of retention rules if the user didn't specify expiration seconds or shard-group duration.
> fix: send empty array of retention rules when no parameters are set

- .circleci/config.yml
- flags.yml
- kit/feature/list.go
Closes influxdata/ui#942
Removes unused `communityTemplate` flag
> chore: remove unused feature flags: communityTemplates, backendExample, frontendExample

- flags.yml
- kit/feature/list.go
Closes #21204
Adds a feature flag for annotations to allow the feature to be "off" by default while it is being developed for OSS. `influxd` can be started with the flag set to `true` by passing the command-line flag `--feature-flags=annotations=true`.
> feat(annotations): add feature flag for annotations

- CHANGELOG.md
- go.mod
- go.sum
(cherry picked from commit e97c5d9785eb9a5c247e7c685ca81bad2b037e4c)
Closes https://github.com/influxdata/influxdb/issues/21225
> feat: flux upgrade to v0.112.1 (#21226)

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
Closes #20740
This change makes the `httpLogger` available to the top-level `http.Server` via the `ErrorLog` property to ensure that errors from the server will follow the standard logging format used everywhere else.
> feat: structured logging for HTTP server ErrorLog

- ui/cypress/e2e/tasks.test.ts
Closes #21242
Comments out the part of the e2e test for creating a task from a template so that the tests don't break when running against the latest UI.
> fix: remove e2e test for creating a task from a template

- query/stdlib/influxdata/influxdb/min_max_influxdb_test.flux
- query/stdlib/influxdata/influxdb/rules.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/table_test.go
- storage/reads/group_resultset.go
- v1/services/storage/store.go
> feat(query): enable min/max pushdown

- ui/cypress/e2e/onboarding.test.ts
Closes #21271
Updated the e2e test to look for "Welcome to InfluxDB" as the splash page text to be consistent with the latest UI from the `ui` repo.
> fix: updated the onboarding e2e test

- ui/cypress/e2e/onboarding.test.ts
Closes #21271
Updates an additional test that was missed in #21272. There are actually TWO places in the onboarding tests where the splash text is checked - this PR updates the additional location.
> fix: updated the text for the e2e onboarding test splash page

- tsdb/engine/tsm1/file_store.go
The anti-entropy service will loop trying to copy an empty shard to a
data node missing that shard.  This fix is one of two changes that
correctly create an empty shard on a new node. 
Fixes: https://github.com/influxdata/influxdb/issues/21273
This fix will set the LastModified date of an empty shard directory to the 
modification time of that directory, instead of to the Unix epoch.
> fix: Anti-Entropy loops endlessly with empty shard

- CHANGELOG.md
- tsdb/engine/tsm1/file_store.go
The anti-entropy service will loop trying to copy an empty shard to a
data node missing that shard.  This fix is one of two changes that
correctly create an empty shard on a new node. This fix will set the
LastModified date of an empty shard directory to the modification time
of that directory, instead of to the Unix epoch.
Fixes: https://github.com/influxdata/influxdb/issues/21273
(cherry picked from commit 7f300dc248d767ee1a96642480dfa1daa28f18ba)
Closes #https://github.com/influxdata/influxdb/issues/21288
> fix: Anti-Entropy loops endlessly with empty shard (#21275)

- Jenkinsfile
Follows the rename of credentials in Jenkins.
> chore: rename Jenkins creds for 1.8

- CHANGELOG.md
- models/points.go
- models/points_test.go
(cherry picked from commit cae14176aa4d2f953f1330bc48051641b8c7fc78)
Closes https://github.com/influxdata/influxdb/issues/21303
> fix(models): grow tag index buffer if needed (#20137) (#21303)

- CHANGELOG.md
- models/points.go
- models/points_test.go
(cherry picked from commit cae14176aa4d2f953f1330bc48051641b8c7fc78)
Co-authored-by: Tristan Su <foobar@users.noreply.github.com>
(cherry picked from commit f646cbc5406bd4d28d54c522f7c19963a719755e)
Closes #https://github.com/influxdata/influxdb/issues/21305
> fix(models): grow tag index buffer if needed [Backport to 1.9]

- CHANGELOG.md
* Rename "unreleased" -> 2.0.5, add a new "unreleased"
* Move things that weren't in 2.0.5 up to the new "unreleased" section
* Add missing things from 2.0.5
> chore: update CHANGELOG to match 2.0.5

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/config_test.go
- cmd/influxd/upgrade/upgrade_test.go
- http/api_handler.go
Closes #21315 
1. Stop rewriting `0` to `10` when upgrading `query-concurrency` config, now that 0 is a valid value
2. If writing a value > 0 for `query-concurrency`, ensure we also write a > 0 value for `query-queue-size`
I had to refactor a bunch of things to make our upgrade-real-DB regression test actually test loading upgraded config. I confirmed that the 1st commit fails with the error seen in #21315, and the 2nd commit gets things to pass again.
> fix(upgrade): ensure query config written by `influxd upgrade` is valid

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher_helpers.go
- query/control/controller.go
Related to #21321
In 2.0.4:
* `query-concurrency: 0` was not allowed
* The default values of `query-concurrency` and `query-queue-size` were both 10
In practice, we found that users quickly hit the default threshold. See #17912.
In 2.0.5:
* `query-concurrency: 0` was enabled as a short-hand for infinite concurrency
* Validation was added to assert that:
* `query-queue-size` is 0 when `query-concurrency` is 0
* `query-queue-size` is > 0 when `query-concurrency` is > 0
* The default values of `query-concurrency` and `query-queue-size` were both updated to be 0
This is guaranteed to be a breaking change for any users that had updated their deployments to override the config value for `query-concurrency` without also updating `query-queue-size`, because concurrency must have been > 0 and …
> fix(query): make config validation for query controller less strict

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/launcher_helpers.go
- cmd/influxd/upgrade/config.go
- cmd/influxd/upgrade/config_test.go
- cmd/influxd/upgrade/upgrade_test.go
- http/api_handler.go
- query/control/controller.go
Closes #21319 
Backports #21321 and #21324
* Ensure query config written by influxd upgrade is valid.
* Revert to nonzero defaults for `query-concurrency` and `query-queue-size` to avoid validation failures for upgrading users.
* Don't fail validation when `query-concurrency` is 0 and `query-queue-size` is > 0.
> fix(query): avoid breaking query config validation when upgrading from older versions

- CHANGELOG.md
- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpldata
Small follow-up to https://github.com/influxdata/influxdb/pull/21291
> fix: summation should be in native type for new meancount iterator

- storage/reads/aggregate_resultset_test.go
- storage/reads/array_cursor.go
- storage/reads/group_resultset_test.go
- storage/reads/resultset.go
- storage/reads/resultset_test.go
- tsdb/cursors/cursor.go
- tsdb/engine/tsm1/array_cursor.gen.go
- tsdb/engine/tsm1/array_cursor.gen.go.tmpl
- tsdb/engine/tsm1/array_cursor_iterator.go
- tsdb/engine/tsm1/array_cursor_test.go
- tsdb/engine/tsm1/engine_test.go
The cursors were previously [start, stop) to be consistent with how flux
requests data, but the underlying storage file store was [start, stop]
because that's how influxql read data. This reverts back the cursor
behavior so that it is now [start, stop] everywhere and the conversion
from [start, stop) to [start, stop] is performed when doing the cursor
request to get the next cursor.
> fix(storage): cursor requests are [start, stop] instead of [start, stop)

- CHANGELOG.md
- storage/reads/aggregate_resultset.go
- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
- storage/reads/array_cursor.gen.go.tmpldata
- storage/reads/array_cursor.go
- storage/reads/array_cursor_gen_test.go
- storage/reads/array_cursor_test.gen.go.tmpl
- storage/reads/array_cursor_test.go
- storage/reads/datatypes/predicate.pb.go
- storage/reads/datatypes/storage_common.pb.go
- storage/reads/datatypes/storage_common.proto
- storage/reads/gen.go
- storage/reads/group_resultset.go
- storage/reads/response_writer.gen.go
- storage/reads/response_writer.gen.go.tmpl
- storage/reads/response_writer.go
- tsdb/cursors/arrayvalues.gen.go.tmpl
- tsdb/cursors/arrayvalues.gen.go.tmpldata
- tsdb/cursors/arrayvalues.go
- tsdb/cursors/cursor.go
- tsdb/cursors/gen.go
Partial close of #21337
We support only one aggregate list [mean,count]. All other aggregates
still must be single-element lists.
(cherry picked from commit 32aa970eba8a77b59b51c01354c0a23db19a19e9)
> feat: mean,count aggregation for WindowAggregate pushdown in enterprise (#21291)

- CHANGELOG.md
- cmd/influx/setup.go
- http/swagger.yml
Closes #21342
* Mark `PostSetupUser` as deprecated in our API docs
* Hide the `influx setup user` command that uses the API
* Add a loud warning to the help-text and output of `influx setup user` for people who are already using it / who find it later
> fix: deprecate PostSetupUser and `influx setup user`

- CHANGELOG.md
- storage/reads/aggregate_resultset_test.go
- storage/reads/array_cursor.go
- storage/reads/group_resultset_test.go
- storage/reads/resultset.go
- storage/reads/resultset_test.go
- tsdb/cursors/cursor.go
- tsdb/engine/tsm1/array_cursor.gen.go
- tsdb/engine/tsm1/array_cursor.gen.go.tmpl
- tsdb/engine/tsm1/array_cursor_iterator.go
- tsdb/engine/tsm1/array_cursor_test.go
- tsdb/engine/tsm1/engine_test.go
* fix: backport tsdb fix for window pushdowns
From https://github.com/influxdata/influxdb/pull/19855
* fix(storage): cursor requests are [start, stop] instead of [start, stop)
The cursors were previously [start, stop) to be consistent with how flux
requests data, but the underlying storage file store was [start, stop]
because that's how influxql read data. This reverts back the cursor
behavior so that it is now [start, stop] everywhere and the conversion
from [start, stop) to [start, stop] is performed when doing the cursor
request to get the next cursor.
cherry-pick from #21318
Co-authored-by: Sam Arnold <sarnold@influxdata.com>
(cherry picked from commit 776667279733519972dbc27fe559c1d8ffd5864a)
* chore: fix formatting
Co-authored-by: Jonathan A. Sternberg <jonathan@influxdata.com> …
> fix(storage): cursor requests are [start, stop] instead of [start, stop) (#21347)

- CHANGELOG.md
- cmd/influxd/launcher/launcher.go
- nats/logger.go
- nats/server.go
Part of #20510 
Connect the NATS server to our logging system so we can see what's going on when it fails to start.
> fix: add logging to NATS streaming server

- CHANGELOG.md
- flux/control/controller_test.go
- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/shard.go
- tsdb/store.go
tsdb.Engine.IsIdle and tsdb.Engine.Digest now return a reason string for why the engine & shard are not idle.
Callers can then use this string for logging, if desired.  The returned reason does not allocate memory, so the 
caller may want to add the shard ID and path for more information in the log. This is intended to be used in 
calls from the anti-entropy service in Enterprise.
Closes https://github.com/influxdata/influxdb/issues/21380
> chore(ae): add more logging

- flags.yml
- kit/feature/list.go
For ui #21307
@wbaker85 :  please review (the removal of the type ahead flag is on prod, so it is on oss already, correct?)
thanks
> chore: remove type ahead flag

- CHANGELOG.md
- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/shard.go
- tsdb/store.go
tsdb.Engine.IsIdle and tsdb.Engine.Digest now return a reason string for why the engine & shard are not idle.
Callers can then use this string for logging, if desired. The returned reason does not allocate memory, so the
caller may want to add the shard ID and path for more information in the log. This is intended to be used in
calls from the anti-entropy service in Enterprise.
(cherry picked from commit bf45841359a06a4c3c923cfc29d5c2516cbaecc5)
Closes https://github.com/influxdata/influxdb/issues/21448
> chore(ae): add more logging (#21381)

- CHANGELOG.md
- http/user_service.go
- tenant/http_server_user.go
- tenant/storage_user.go
- testing/user_service.go
Closes #21402
Related to https://github.com/influxdata/influxdb-client-csharp/issues/190
List users via the API now supports `offset`, `limit` or `after` parameter
> feat(users): list users via the API now supports `offset`, `limit` or `after` parameter

- CHANGELOG.md
- cmd/influx/restore.go
- restore/restore.go
Closes #21475
`--input` has been effectively useless up until now, but all of the examples in our public docs show using it instead of the positional arg.
I chose to deprecate `--input` instead of the arg because `influx backup` uses a positional arg to specify the path where backup data should be stored, and it felt intuitive to have symmetry between the two.
> fix(cmd/influx): accept `--input` flag in `restore` command

- .circleci/config.yml
Closes #21505
Updates the Circle config to produce a static build during the `build` job using `goreleaser` that is used in the downstream tests. The latest `goreleaser` version is used to make the static binary for linux during the build step.
This should better align the binaries that we do e2e tests on with those that we release, and will allow for future testing of binaries that require static builds for the downstream tests suites to work properly.
> build: static image for e2e tests

- CHANGELOG.md
- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
Closes #21517
This will cause requests for `ttf`, `woff`, and `eot` files to have the file name also replaced by a slug for telemetry reporting purposes to manage cardinality. For example: requests for `/35bb8d560d.ttf` or `/anythingelse.ttf` will both be reported as `/:file_name.ttf`.
Behavior for most files of this nature was already handled by #21158, but `ttf` files were missed in that implementation, so this PR is merely adding that file extension to the list. `woff` and `eot` files may not be accessed often (if ever), but I added those to the list as well since they are given hashed-based names by UI builds.
> fix: add telemetry slug for additional file exts

- CHANGELOG.md
- flags.yml
- kit/feature/list.go
Closes idpe 10605
Removes the feature flags `axisTicksGenerator`, `legendOrientation`, `mosaicGraphType`, and `bandPlotType` as they have become permanent UI features.
UI issues:
https://github.com/influxdata/ui/issues/1460  
https://github.com/influxdata/ui/issues/1462  
https://github.com/influxdata/ui/issues/1463  
https://github.com/influxdata/ui/issues/1464
> feat: remove ui feature flags for permanent features

- cmd/influxd/launcher/engine.go
- cmd/influxd/launcher/storage_test.go
- internal/tsdb_store.go
- storage/engine.go
- tsdb/store.go
- tsdb/store_test.go
- v1/coordinator/statement_executor.go
- v1/coordinator/statement_executor_test.go
- v1/services/storage/store.go
Closes #20738
Forward-ports #20736. It wasn't a clean cherry-pick, but I think the interesting code in `tsdb/store.go` and `tsdb/store_test.go` is an exact match.
> fix(influxql): make meta queries respect query timeout

- CHANGELOG.md
- ui/fetch_ui_assets.sh
Closes #21562
Also:
Closes #21447
Closes #21354
Closes [influxdata-docker#484](https://github.com/influxdata/influxdata-docker/issues/484)
Updates the build script to include the built assets from https://github.com/influxdata/ui/releases/tag/OSS-v2.0.7.
> feat: upgrade UI to v2.0.7

- cmd/influx/template.go
- measurement_schema.go
- measurement_schema_errors.go
- measurement_schema_test.go
- models/points.go
- pkger/models.go
- pkger/parser.go
- pkger/parser_models.go
- pkger/parser_models_schema.go
- pkger/parser_test.go
- pkger/testdata/bucket_schema.yml
This PR teaches the `influx` CLI how to export and apply buckets with explicit schema from Cloud 2. The existing CLI subcommands to `export` and `apply` templates require a significant amount of logic be duplicated from the server to validate and parse the template prior to upload. Preferably, the template would be passed to the server for parsing and validation and an appropriate response sent to the client to display to the user. Changing this would require significant refactoring of the HTTP and CLI APIs, which is beyond the scope of this feature.
**NOTES**
The Packager CLI does not show diffs of hierarchical data, so it is unable to show detailed differences when new measurements are added or new columns to an existing measurement. An existing example of this is Dashboards, which are …
> feat: influx CLI Packager support for explicit schema buckets

- .circleci/config.yml
- run_perftest.sh
- test.sh
This PR enables the running of ingest (bulk load) performance testing for the `1.8` branch.
The automation logic works by launching an AWS EC2 instance and installing the deb produced from the test build on the VM. Then, using the github.com/influxdata/influxdb-comparisons repo, a dataset is generated on the VM and loaded into the influxdb instance running there.
Results are reported to an influxdata cloud 2 bucket.
AWS instances are destroyed via a callback mechanism, as well as a nightly cleanup which is intended as a backstop for any instances left running by ephemeral api failures.
All api tokens are stored in CircleCI config.
> chore: enable ingest performance tests

- notebooks/service.go
- notebooks/service_test.go
Closes #21587
This change will allow the API to respond with `{flows: []}` instead of `{flows: null}` when making a request to list notebooks that includes 0 notebooks.
This is important for cases where all the notebooks are removed external to the UI - by doing a database restore for example - the `{flows: null}` response in this case was not able to be processed by the UI and resulting in the old notebooks to still show up via the browser local storage. With the `{flows: []}` the browser updates the list of notebooks to have 0 notebooks and display correctly.
> fix: empty notebooks list returns empty array

- CONTRIBUTING.md
Closes #21589
Updates build from source docs [here](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#building-with-the-go-command) to remove the section about using the go command to build, in favor of using `make`. Additionally I updated the additional dependencies section [here](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#additional-dependencies) to be a little clearer for OSX, mentioning that Homebrew is required, as well as stating that `make` is included in the Apple Developer Tools.
> docs: Update build-from-source docs to favor make commands

- internal/cmd/fluxtest-harness-influxdb/test.go
Closes #21051 
Currently, we do not show error messages if something fails while running influxdb flux acceptance test harness. This patch will help to report an error message that tells the user what the issue is.
> fix: report error when a flux acceptance test doesn't have a package statement

- CHANGELOG.md
- tsdb/engine/tsm1/engine.go
- tsdb/shard.go
- tsdb/shard_test.go
Under heavy write load creating new fields and measurements
the rewrite of the fields.idx file is a bottleneck. This
enhancement combines multiple writes into a single one and
shares any error return value with all of the combined
invocations.
Closes #21577
> fix: avoid rewriting fields.idx unnecessarily

- .circleci/config.yml
* Stop using `GOCACHE`, it only ever grows in size and the upload/download ends up dominating job runtime
* Use RAMdisks in build/test steps where we expect it'll help runtime
Before:
After:
> build: speed up CI runtime

- CHANGELOG.md
- tsdb/engine/tsm1/engine.go
- tsdb/shard.go
- tsdb/shard_test.go
Under heavy write load creating new fields and measurements
the rewrite of the fields.idx file is a bottleneck. This
enhancement combines multiple writes into a single one and
shares any error return value with all of the combined
invocations. MeasurementFieldSet and the new
MeasurementFieldSetWriter must both now be explicitly
closed.
Closes #21577
(cherry picked from commit f64be286be178d481c9897b8a388d227ebb62b52)
Closes https://github.com/influxdata/influxdb/issues/21597
> fix: avoid rewriting fields.idx unnecessarily (#21592) [Port to 1.9]

- internal/cmd/fluxtest-harness-influxdb/test.go
The test harness was hidding errors from the first pass making it difficult to debug why a test was failing.
> fix(query): do not hide errors from first pass of flux acceptance tests

- CHANGELOG.md
Keeping things in-sync.
There are 2 changes in the 2.0.7 log that I've left out of here, because there isn't a matching PR in the `master` branch:
1. [21564](https://github.com/influxdata/influxdb/pull/21564): Upgrade UI to [v2.0.7](https://github.com/influxdata/ui/releases/tag/OSS-v2.0.7) (only made against the 2.0 branch because `master` has its own UI branch)
1. [21501](https://github.com/influxdata/influxdb/pull/21501): Don't deadlock in `influx org members list` when an org has > 10 members. (fixed in `influx-cli` so I didn't bother changing the code on `influxdb/master`)
I'm not sure of the best way to handle those. We could link to the PRs against the 2.0 branch, or just leave them out.
> chore: update CHANGELOG to reflect 2.0.7 release

- annotation.go
- annotations/transport/annotations_router.go
- annotations/transport/annotations_router_test.go
- annotations/transport/annotations_test.go
- annotations/transport/helpers_test.go
- annotations/transport/http.go
- annotations/transport/streams_router.go
- annotations/transport/streams_router_test.go
- mock/annotation_service.go
This PR closes several issues on the annotations epic, including:
#21205
#21206
#21207
#21208
There was not as much need to break these up as I had originally thought, and reviewing them as a whole unit should be easier than looking at them individually since they are so similar.
The handler code is mostly straight-forward. There were also a few small tweaks I made to the service definition for OSS-specific things, particularly only requiring the org ID when it's necessary to do the query since that will have to be passed in the query parameters.
> feat(annotations): annotations api handlers

- CHANGELOG.md
- tsdb/engine/tsm1/digest.go
tsm1.DigestWithOptions closes its network connection
twice. This may cause broken pipe errors on concurrent
invocations of the same procedure, by closing a reused
i/o descriptor. This fix also captures errors from TSM
file closures, which were previously ignored.
Closes https://github.com/influxdata/influxdb/issues/21656
> fix: Do not close connection twice in DigestWithOptions

- CHANGELOG.md
- tsdb/engine/tsm1/digest.go
tsm1.DigestWithOptions closes its network connection
twice. This may cause broken pipe errors on concurrent
invocations of the same procedure, by closing a reused
i/o descriptor. This fix also captures errors from TSM
file closures, which were previously ignored.
Closes https://github.com/influxdata/influxdb/issues/21656
(cherry picked from commit bce6553459e0eadea414696c0c564ad28275116b)
Closes https://github.com/influxdata/influxdb/issues/21660
> fix: Do not close connection twice in DigestWithOptions (#21659)

- CHANGELOG.md
- query/iterator.go
We have seen occasional panics in Iterators.Close()
when cleaning up after failed iterator creation.
This commit checks for nil on any iterator to be
closed, and now returns any errors generated by
that Close().
Closes https://github.com/influxdata/influxdb/issues/19579
Closes https://github.com/influxdata/influxdb/issues/19476
> fix: do not panic on cleaning up failed iterators

- CONTRIBUTING.md
> docs: bump Go version in build-from-source docs

- http/middleware.go
- http/restore_service.go
Closes #21669 
Closes #21670 
Closes #21671 
For the 3 APIs that expect the request-body to be a file, check if `Content-Encoding: gzip` is set and wrap a gzip reader around the body stream if so. Tested manually with the new CLI.
> feat: add support for gzip request bodies in restore API

- .circleci/config.yml
chore: Clean up nightly AWS teardown job logic, bringing it in line with config from `1.8` branch.
> chore: fix query logic in nightly aws teardown

- backup.go
- backup/backup.go
Closes #21681
Updates the manifest to match influxdata/openapi#130. Adding these new fields will allow the new `restore/bucket-metadata` API to recreate buckets based solely off the manifest contents.
> feat: add bucket description and retention rules to backup manifest

- go.mod
- go.sum
It seems that go-bindata version 3.11.0 was changed and causes issues
when building from a clean Go env.
I encountered this error:
```
verifying github.com/kevinburke/go-bindata@v3.11.0+incompatible: checksum mismatch
downloaded: h1:GiPs9jxaG2xY1B5Dt/d/yHUOMlTk14uS35VcmHrdo4I=
go.sum:     h1:RcC+GJNmrBHbGaOpQ9MBD8z22rdzlIm0esDRDkyxd4s=
```
This change updates to the latest go-bindata release.
> chore(go-bindata): update to recent version of go-bindata

- .circleci/config.yml
- scripts/ci/perf_test.sh
- scripts/ci/run_perftest.sh
This PR adds a series of circle jobs around running ingest/data load tests on builds:
* `perf_test`: this jobs starts an EC2 instance in the InfluxData AWS test account, installs the build from earlier in CI, and runs a non-blocking test script, which places results in an InfluxData Cloud 2 bucket.
* `aws_destroy_by_name`: this is a job meant to be triggered via the Circle API: the aforementioned test script is configured by default to make this call once the performance tests have finished; the job terminates any EC2 instance with a "Name" tag matching its arguments
* `aws_destroy_by_date`: this is a "backstop" job to run nightly and clean up any EC2 instances with a "Name" tag matching a prefix from the day before or prior
> chore: enable ingest performance tests for master

- tsdb/shard.go
Move an access to a waitgroup into a `if` that ensures 
the containing struct is not nil.
> fix: don't access a field in a nil struct

- tsdb/shard.go
Move an access to a waitgroup into an `if` that ensures
the containing struct is not nil.
(cherry picked from commit aca69e530f16441e343265d717001c68cd1db115)
> fix: don't access a field in a nil struct (#21693)

- CHANGELOG.md
- query/iterator.go
We have seen occasional panics in Iterators.Close()
when cleaning up after failed iterator creation.
This commit checks for nil on any iterator to be
closed, and now returns any errors generated by
that Close().
Closes https://github.com/influxdata/influxdb/issues/19579
Closes https://github.com/influxdata/influxdb/issues/19476
(cherry picked from commit acc4105b8c48657287ddeaed56c28fd2840dd862)
Closes https://github.com/influxdata/influxdb/issues/21667
> fix: do not panic on cleaning up failed iterators (#21666)

- authorizer/authorize_find.go
- authorizer/notebook.go
Closes #21668
This adds an additional filtering step for the "list all" operation on notebooks to filter the list down to only specific resources that the user has access to. Although it's not currently used, this could be useful in the future if fine-grained authz is implemented, and is consistent with #21668 and the other REST resources of the platform.
> feat(notebooks): additional auth filter for listing

- http/backup_service.go
- http/backup_service_test.go
Closes #21700
This is a small simplification to the metadata backup API to remove the unnecessary filename key from the content-disposition.
> chore: remove unnecessary file name from metadata backup api

- annotations/service.go
- annotations/service_test.go
- cmd/influxd/launcher/launcher.go
Part of #21553
This PR is mostly to wire up the annotations backend service to the main API handler so that its endpoints can be exposed.
While doing some manual testing I also found a bug where if an annotation doesn't have any stickers, it couldn't be selected for reading or deleting. That is fixed as part of this PR as well as test updates related to that bug.
> feat: enable annotations backend

- CHANGELOG.md
- cmd/influx_tools/compact/command.go
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
Closes https://github.com/influxdata/influxdb/issues/21704
Add progress logging and more detailed error logging for compaction and compaction-related procedures.
> chore: add logging to compaction

- CHANGELOG.md
- cmd/influx_tools/compact/command.go
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
Compaction logging will generate intermediate information on
volume of data written and output files created, as well as
improve some of the anti-entropy messages related to compaction.
This will also apply to `influx_tools compact`
Closes https://github.com/influxdata/influxdb/issues/21704
(cherry picked from commit 73bdb2860e303702ef00be3c91bec8be92906589)
Closes https://github.com/influxdata/influxdb/issues/21705
> chore: add logging to compaction (#21707)

- scripts/fetch-ui-assets.sh
Closes https://github.com/influxdata/idpe/issues/10889
Adds a check to verify the SHA256 checksum of the downloaded `tar` for the UI assets matches the checksum attached to the release for the UI assets. This will ensure the integrity of the download. Also adds some additional comments to the script.
You can see an example of what happens if the check is "bad" here, where I intentionally linked a different `tar` file than what was attached with the respective SHA256: https://app.circleci.com/pipelines/github/influxdata/influxdb/21476/workflows/867eaf25-6615-4d97-972f-ac17d6c8c7ae/jobs/197526
> build: verify checksum of built ui assets

- http/legacy/backend.go
- http/legacy/influxqld_handler_test.go
- http/legacy/ping_handle_test.go
- http/legacy/ping_handler.go
- http/platform_handler.go
This PR fix the `/ping` endpoint:
- change build type from `cloud2` to `oss2`
- use correct version for `X-Influxdb-Version` header
> fix(pingEndpoint): change build type to 'oss2', use correct version

- .goreleaser.yml
- CHANGELOG.md
Addresses influxdata/build-scripts#6 in `master`.
Yum refers to arm64 as aarch64, and our rpms should reflect this requirement to enable correct use with Yum on arm64 machines.
> fix: rename arm rpms with yum-compatible names

- CHANGELOG.md
- models/points.go
- services/subscriber/service.go
- services/subscriber/service_test.go
Added a check for valid UTF-8 strings in measurement names,
tags name, tag values, and field names when writing to subscriptions.
Do not send the failing points to subscribers, and log the errors if at
debug level logging
Closes https://github.com/influxdata/influxdb/issues/21557
(cherry picked from commit a08b69098eba5362ffcaeabf748ada57ff009ffa)
Closes https://github.com/influxdata/influxdb/issues/21559
> fix: do not send non-UTF-8 characters to subscriptions (#21558)

- CHANGELOG.md
- releng/packages/fs/usr/local/bin/influxdb_packages.bash
Further adjustments to docker-based build system to produce correctly-named arm rpm packages, to address influxdata/build-scripts#6.
Follow-on to #21750.
> fix: convert arm arch names for rpms during builds via docker

- CHANGELOG.md
- cmd/influxd/inspect/dump_tsm/dump_tsm.go
- cmd/influxd/inspect/dumptsm.go
- cmd/influxd/inspect/inspect.go
Closes #19532
Ports the `./influx inspect dump-tsm` subcommand to 2.x.
> feat: port `influxd inspect dump-tsm`

- CHANGELOG.md
- query/compile.go
- query/compile_test.go
Closes #21791
Statement rewriting signals errors by panic'ing, so swallow the panic into an error.
> fix: error instead of panic for statement rewrite failure

- CHANGELOG.md
- cmd/influxd/inspect/dump_tsi/dump_tsi.go
- cmd/influxd/inspect/inspect.go
- tsdb/index/tsi1/index.go
Closes #19531
Ports the `./influx inspect dumptsi` subcommand to 2.x.
> feat: port `influx inspect dumptsi` subcommand

- CHANGELOG.md
- cmd/influxd/inspect/delete_tsm/delete_tsm.go
- cmd/influxd/inspect/inspect.go
Closes #19530
Ports the `./influx inspect deletetsm` inspect subcommand to 2.x.
> feat: port `influxd inspect deletetsm` to 2.x

- CHANGELOG.md
- coordinator/statement_executor.go
- tests/server_test.go
> fix: show shards gives empty expiry time for inf duration shards

- CHANGELOG.md
- client/v2/client.go
- client/v2/udp.go
- cmd/influxd/run/server.go
- coordinator/points_writer.go
- coordinator/points_writer_test.go
- models/points.go
- services/subscriber/config.go
- services/subscriber/http.go
- services/subscriber/service.go
- services/subscriber/service_test.go
- services/subscriber/udp.go
Closes #21733
Fixes the concurrency patterns for subscriptions and adds the `total-buffer-bytes` subscription configuration to limit the amount of memory taken by subscriptions.
> feat: add total-buffer-bytes config parameter to subscriptions

- CHANGELOG.md
- client/v2/client.go
- client/v2/udp.go
- cmd/influxd/run/server.go
- coordinator/points_writer.go
- coordinator/points_writer_test.go
- models/points.go
- services/subscriber/config.go
- services/subscriber/http.go
- services/subscriber/service.go
- services/subscriber/service_test.go
- services/subscriber/udp.go
Reverts PR #21752
This reverts commit 85abb3af36e153d87b99589bf4db1a63c81cbf9c.
> revert: revert add total-buffer-bytes config parameter to subscriptions

- client/v2/client.go
- client/v2/udp.go
- cmd/influxd/run/server.go
- coordinator/points_writer.go
- coordinator/points_writer_test.go
- models/points.go
- services/subscriber/config.go
- services/subscriber/http.go
- services/subscriber/service.go
- services/subscriber/service_test.go
- services/subscriber/udp.go
* chore: harmonize OSS and Enterprise subscriber initialization
* refactor: chanwriter close blocks until chanwriter is flushed
* refactor: remove redundant state
* test: add test for blocked subscriber during subscription update
* fix: blocked subscriber does not fail subscription update
* fix: only iterate matching subscriptions
* fix: use serialized points in subscriber queues
* feat: add total-buffer-bytes config parameter to subscriptions
* fix: put subscription serialization on the write path
* fix: subscription service only needs regular mutex, not RWMutex
* fix: review comments
* chore: update changelog
(cherry picked from commit 85abb3af36e153d87b99589bf4db1a63c81cbf9c)
Partial close of #21805
> feat: add total-buffer-bytes config parameter to subscriptions (#21752)

- tests/backup_restore_test.go
- tests/server_test.go
This reverts commit 9a3bd84d61fca00287180c49642df023b0d432d2.
Reverting due to persistent test failures around the new test.
> revert: add series cardinality test and fix backup port (#21787)

- CHANGELOG.md
- client/v2/client.go
- client/v2/udp.go
- cmd/influxd/run/server.go
- coordinator/points_writer.go
- coordinator/points_writer_test.go
- models/points.go
- services/subscriber/config.go
- services/subscriber/http.go
- services/subscriber/service.go
- services/subscriber/service_test.go
- services/subscriber/udp.go
This reverts commit 4d82ed2c07dda05494b6824f5f5e7abff26ab31f.
Closes #21733
> feat: un-revert add total-buffer-bytes config parameter to subscriptions

- cmd/influxd/inspect/export_lp/export_lp_test.go
- cmd/influxd/inspect/verify_seriesfile/verify_seriesfile.go
- cmd/influxd/inspect/verify_seriesfile/verify_seriesfile_test.go
- cmd/influxd/inspect/verify_tombstone/verify_tombstone_test.go
- cmd/influxd/inspect/verify_tsm/verify_tsm_test.go
This PR simply moves away from using `ioutil` in the `inspect` command package for test cases, and favors using their replacements in `io` and `os` instead, as is recommended in Go 1.16.
> chore: move to os/io for inspect test code

- annotations/README.md
- notebooks/README.md
- sqlite/README.md
Closes #21265 (notebooks)
Closes #21216 (annotations)
This PR includes 3 `README.md` files to provide a high-level description of the new annotations and notebooks features, as well as the new sqlite service. They are intended to provide future developers a quick way to get oriented with the associated code and make changes/extend it as needed.
> docs: README for annotations, notebooks, and sqlite

- query/stdlib/experimental/to.go
- query/stdlib/experimental/to_test.go
- query/stdlib/influxdata/influxdb/to_test.go
The kind for experimental-to is in conflict with the one used by native
flux. In the past, native flux didn't use the kind and expected
implementations to register their own procedure spec with that value.
In the latest Flux, this isn't the case and it is using the kind for a
native implementation. As we have not implemented the requirements for
the native implementation, we are still replacing the procedure spec but
using a different name that's unique to our implementation.
> refactor(query): rename the kind for experimental-to so that it is different from native flux

- go.mod
- go.sum
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
This is a straightforward upgrade of the Flux version, save for I needed to tweak how pushdowns of `group|>last` work. New tests added to the latest `flux` version test this change. Shortly I'll have another PR that will include more test coverage for `group()` and `first` and `last`.
See also this issue for a more in-depth discussion of `group` and `last`:
https://github.com/influxdata/idpe/issues/11201
> build(flux): update flux to v0.122.0

- CHANGELOG.md
- tests/server_test.go
- tsdb/config.go
- tsdb/engine.go
- tsdb/field_validator.go
- tsdb/shard.go
Per https://docs.influxdata.com/enterprise_influxdb/v1.9/write_protocols/line_protocol_reference/
we only support 64KB, but 1MB is a more realistic practical limit. Before this commit there was
no enforcement of field value size.
Closes #21841 
> fix: hard limit on field size while parsing line protocol

- CHANGELOG.md
- cmd/influxd/inspect/inspect.go
- cmd/influxd/inspect/verify_wal/verify_wal.go
- cmd/influxd/inspect/verify_wal/verify_wal_test.go
Closes #19539
This PR creates the `./influxd inspect verify-wal` subcommand. I created test cases which give about 93% coverage of the command file, only skipping basic error handling like `os` failing to open a file.
> feat: create `influxd inspect verify-wal` command

- query/stdlib/influxdata/influxdb/group_agg_influxdb_test.flux
This PR adds testing for pushdowns of `group|> count` and `group|>sum`.
Pushing down these operations has been enabled for some time in OSS 2.0. These changes only extend existing tests in the `flux` repo to assert that the planner rule to push down these operations actually fire.
> test: add tests for group and count/sum

- query/stdlib/influxdata/influxdb/group_first_last_influxdb_test.flux
- storage/flux/table_test.go
This PR adds testing for our support of pushing down Flux operations `group|>first` and `group|>last` into the storage tier.
This optimization has been available for some time, this PR just adds tests for it.
Tests for the planner rule already existed, I only needed to extend Flux acceptance tests to show that the planner rule is actually applied. I also added "table tests" to test the `<datatype>GroupTable` structures used by storage to implement Flux sources.
> test: add acceptance tests and table tests for group|>first/last

- scripts/ci/run_perftest.sh
context: configuring unique data as tags causes series cardinality to
grow in an unbounded manner; data with unique values should be set
as fields
cherry-picked commit from #21824
> chore: change commit and branch keys to fields instead of tags

- cmd/influxd/inspect/verify_seriesfile/verify_seriesfile_test.go
- cmd/influxd/inspect/verify_tombstone/verify_tombstone.go
- cmd/influxd/inspect/verify_tsm/verify_tsm.go
- cmd/influxd/upgrade/fs.go
- influxql/v1validation/validation_test.go
- internal/fs/influx_dir.go
- pkg/tar/stream.go
This PR changes all instances of `filepath.Walk()` to `filepath.WalkDir()` which is a new and more performant function introduced in Go 1.16. I started by just doing this for the `inspect` commands which used `filepath.Walk()` a few times, but when replacing these I noticed we only had a few extra uses of this function in the repository, so I went ahead and updated them as well.
> chore: move to `filepath.WalkDir` for slight performance gain in Go 1.16

- .goreleaser.yml
- CHANGELOG.md
- scripts/influxd-systemd-start.sh
- scripts/influxdb.service
Closes #6068 
Implements a wrapper around influxd when called by systemd to wait until the server is ready before exiting startup.
> fix: systemd unit should block on startup until http endpoint is ready

- .circleci/config.yml
- CHANGELOG.md
- go.mod
- go.sum
- scripts/ci/xcc-builds/build-osxcross-clang.sh
- scripts/ci/xcc.sh
- tsdb/store_test.go
Backports #21642 and #21658
I was on the fence about this one, and decided to go through with it because:
* AFAIK it's low-risk
* It's needed to import the CLI as a dependency
* Importing the CLI is needed to replace some test code & fix some bugs in `influxd upgrade`
> build: upgrade to go1.16

- task/backend/scheduler/scheduler_test.go
Closes #21883
Use a fixed time for the task scheduler tests which do not include a DST change to ensure that the test suite can be run on systems which do not determine time differences based on UTC.
> fix: task scheduler test uses a fixed time

- CHANGELOG.md
- cmd/influxd/inspect/inspect.go
- cmd/influxd/inspect/report_tsm/report_tsm.go
- cmd/influxd/inspect/report_tsm/report_tsm_test.go
- go.mod
- go.sum
> feat: port `influx inspect report-tsm` to 2.x

- CHANGELOG.md
- tsdb/engine.go
- tsdb/engine/tsm1/engine.go
- tsdb/shard.go
- tsdb/store.go
tsdb.Engine.IsIdle and tsdb.Engine.Digest now return a reason string for why the engine & shard are not idle.
Callers can then use this string for logging, if desired. The returned reason does not allocate memory, so the
caller may want to add the shard ID and path for more information in the log. This is intended to be used in
calls from the anti-entropy service in Enterprise.
(cherry picked from commit bf45841359a06a4c3c923cfc29d5c2516cbaecc5)
fixes https://github.com/influxdata/influxdb/issues/21448
(cherry picked from commit c8da9bafbf4121898fd68fdc1ade1d6f0246c4af)
Closes https://github.com/influxdata/influxdb/issues/21894
> chore: add more logging

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- http/platform_handler.go
Closes #21896
Adds the config flag `--ui-disabled` to `influxd` to allow for running the `influxd` server with the UI disabled. 
With this change, if the boolean flag `--ui-disabled` is provided, requests to the "root" path where the UI would normally be served (for example, http://localhost:8086) will return a 404.
> feat: add `ui-disabled` flag to run server with UI disabled

- CHANGELOG.md
- secret/http_server.go
- secret/http_server_test.go
This adds a route to delete individual secrets in preparation to remove the old `post` to `/secrets/delete` route.
> chore: add route to delete individual secret

- .goreleaser.yml
- scripts/ci/perf_test.sh
Making the names of these files match what's going to be used in 2.0.8
> build: update deb and rpm names to match 2.0.8

- CHANGELOG.md
- chronograf/influx/authorization.go
- chronograf/influx/influx_test.go
- go.mod
- go.sum
- jsonweb/token.go
- jsonweb/token_test.go
CVE-2020-26160[0] is an access restriction bypass under certain
circumstances when validating audience checks. The original
dgrijalva/jwt-go project is no longer maintained[1] and will not be
issuing a fix for this CVE[2]. Instead, they have transferred ownership
to golang-jwt/jwt[2][3][4].
The following was performed:
1. update chronograf and jsonweb to import golang-jwt/jwt
2. go mod edit -require github.com/golang-jwt/jwt@v3.2.1+incompatible
3. go mod edit -droprequire github.com/dgrijalva/jwt-go
4. go mod tidy
5. make
6. make test
Note: 1.x is *not* affected since 1.8.4rc and 1.9.0rc pulled in a prerelease version of dgrijalva/jwt-go v4 that had the fix. We should move 1.x to golang-jwt/jwt, but that s for future maintenance and not a security fix.
References:
[0] …
> chore: upgrade to golang-jwt 3.2.1 to fix CVE-2020-26160

- CHANGELOG.md
- cmd/influx_inspect/buildtsi/buildtsi.go
- cmd/influx_tools/importer/command.go
- cmd/influxd/restore/restore.go
- kit/metric/client.go
- kit/tracing/tracing.go
- kit/transport/http/api.go
- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
- query/encode_test.go
- services/collectd/test_client/client.go
- services/meta/client_test.go
- services/meta/data_internal_test.go
- services/meta/data_test.go
- services/snapshotter/client.go
- tsdb/engine/engine.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/log_file_test.go
- tsdb/index/tsi1/partition.go
- tsdb/shard_test.go
Closes #21942
In addition to cleaning up old log files that are too large, ensure that a full TSI compaction is run on the same schedule as the TSM full compaction - so by default after the shard is cold for 4 hours, compact the TSL log files into the TSI index regardless of size.
> fix: tsi index should compact old or too-large log files

- CHANGELOG.md
- cmd/influxd/inspect/build_tsi/build_tsi.go
- cmd/influxd/inspect/inspect.go
Closes #19529
Ports the `influx inspect build-tsi` subcommand to 2.x. Optional flags to filter by `database` and `retention` were replaced with an optional `bucket-id` flag. dataPath and walPath are now optional flags instead of required, so a user can specify custom paths, but otherwise it will use the default paths for these.
> feat: port influxd inspect build-tsi

- CHANGELOG.md
- cmd/influxd/launcher/storage_test.go
- v1/coordinator/points_writer.go
- v1/coordinator/points_writer_internal_test.go
Unlike in Enterprise, the dropped writes caused by the bug were truly silent (other than incrementing a metrics counter). The fix is the same.
> fix: prevent silently dropped writes with overlapping shards

- CHANGELOG.md
- http/api_handler.go
- http/api_handler_test.go
Closes #21620
In the `APIHandler`, the `serveLinksHandler` is incorporated using `h.Mount`. This causes any arbitrary requests to a subpath of `/api/v2` to hit the `serveLinksHandler`, for example `/api/v2/anyrandomthing`, or something more confusing like `/api/v2/query&foo=bar` where the correct request should look like `/api/v2/query?foo=bar`. These invalid requests will return a successful status code currently.
Changing `h.Mount` to `h.Handle` fixes this, so that only requests specifically made to `/api/v2` (or `/api/v2/`) will return the links page. Invalid requests will return a 404 Not Found.
This will also help with https://github.com/influxdata/influxdb/issues/21167
See equivalent PR in IDPE: https://github.com/influxdata/idpe/pull/9069
> fix: return 404 instead of links page on bad /api/v2 requests

- .circleci/config.yml
- go.mod
- go.sum
- influxql/query/executor.go
- query/stdlib/influxdata/influxdb/to.go
Noticed while messing around with the build, the latest version of `staticcheck` is more module-/cgo-aware and comes with more checks. Bumping the version revealed one style nitpick and one outright bug.
> build: upgrade staticcheck, fix new linter warnings

- CHANGELOG.md
- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
- static/static.go
- static/static_test.go
Closes #21167
This PR will reduce the cardinality of reported telemetry metrics in the following two ways:
- Requests which do not result in a successful status code (in the range of `200` - `299`) OR result in a server error (in the range of `500` - `599`) will not have metrics collected. This is to prevent arbitrary requests from endpoints like `/api/v2/...` from being able to generate unbounded cardinality. Also see https://github.com/influxdata/influxdb/pull/21950
- Requests to the server root `/` will have their paths normalized to a placeholder slug if they do not match a file contained on the server. This should eliminate the huge amount of unique series reported in telemetry data for arbitrary requests to the server root.
A side-effect of the second point is that requests made to …
> feat(telemetry): Do not record telemetry data for invalid requests; replace invalid static asset paths with a slug

- cmd/influxd/inspect/delete_tsm/delete_tsm.go
- cmd/influxd/inspect/delete_tsm/delete_tsm_test.go
Adds test cases to `influxd inspect deletetsm`, and cleans up the error handling slightly to be clearer. Additionally, `deletetsm` will now completely remove a TSM file if all of its measurements are removed, instead of leaving an empty TSM file behind.
> chore: deletetsm command tests

- CHANGELOG.md
- query/stdlib/influxdata/influxdb/show_fields_with_meas_pred_test.flux
- v1/services/storage/predicate_influxql.go
Closes #21961
This PR updates the logic for detecting if a query that is attempting to get values for `_field` contains a predicate on something other than `_measurement`.
Since the `influxql` expression will have had references to `_measurement` or the bytes equivalent `\x00` replaced with `_name` by `reads.NodeToExpr`: https://github.com/influxdata/influxdb/blob/5d84c602c8d68ef71c2e9bb11b5443d9822af67f/storage/reads/influxql_predicate.go#L137-L143
...we need to check for that equivalent remapped value when determining if an expression node contains something other than that.
This will allow a query like the one in #21961 to avoid a performance-intensive block scan. The performance increase can be dramatic when querying a large number of series, and this kind of query is very common when …
> fix: field metaqueries take fast path if predicate is only on `_measurement`

- go.mod
- go.sum
- query/influxql/response_iterator.go
- query/influxql/result.go
- query/stdlib/influxdata/influxdb/to.go
- storage/flux/table.gen.go
- storage/flux/table.gen.go.tmpl
- storage/flux/table.go
- storage/flux/tags_cache.go
- storage/flux/tags_cache_test.go
- storage/flux/types.tmpldata
- storage/flux/window.go
- task/backend/analytical_storage.go
This updates the flux integration to use the `flux/array` package rather than
directly using the `arrow/array` package.
Flux recently switched to wrapping the array types from arrow and creating its
own array package to be used for table columns instead of directly referencing
the arrow package. This allows us to keep a consistent interface, but
potentially change internal implementations without changing downstream
consumers. Most recently, the `*array.String` type has some of its own
optimizations for certain array patterns.
This change updates the flux integration to use the new API.
Related to influxdata/flux#3897.
> feat: update flux components to use flux/array instead of arrow/array

- query/control/controller_test.go
Add a sleep since part of the test is checking that the compile time is non-zero.
> test: ensure compile takes time

- cmd/influxd/inspect/dump_tsm/dump_tsm.go
- cmd/influxd/inspect/dump_tsm/dump_tsm_test.go
Adds unit tests for `influxd inspect dump-tsm`, achieving almost 96% coverage. In the process, I expanded error handling for the command to be clearer, and discovered a possible panic if a key has no additional fields, so I am now handling that case with a `len()` check.
> chore: add test cases for `inspect dump-tsm`

- CHANGELOG.md
- flags.yml
- kit/feature/list.go
- notebooks/transport/http_test.go
Closes #21217
Closes #21266
This PR enables notebooks and annotations by removing the feature flag for `notebooks` and `notebooksApi`, both of which are no longer checked for in the UI (they are always on in the latest UI), and turns the feature flag for `annotations` to be `true` by default.
I also cleaned up a few other UI-related feature flags that have been removed from the UI
> feat: enable notebooks and annotations

- cmd/influxd/inspect/dump_wal/dump_wal.go
- cmd/influxd/inspect/dump_wal/dump_wal_test.go
Adds unit test coverage for the `inspect dump-wal` command (85.9% coverage). I also made changes to dump_wal.go to enable the tests to read output.
> chore: add unit test coverage to inspect dump-wal

- releng/raw-binaries/Dockerfile
- releng/source-tarball/Dockerfile
- releng/unit-tests/Dockerfile
Prevent unexpected breakages from rust updates by pinning the rust version
> chore: pin rust version

- CHANGELOG.md
- tsdb/index/tsi1/partition.go
Closes #21942
In addition to previous fixes in #21943 , check during each compaction for if the active log file should be rolled.
> fix: old tsl files should be compacted without new writes

- CHANGELOG.md
- coordinator/statement_executor.go
- query/statement_rewriter.go
- query/statement_rewriter_test.go
- tests/server_test.go
Ensure that the Sources field of the ShowTagValuesStatement is
filled in. Then use the sources to limit the retention policies,
and thus the shards from which tag values are collected.
This fix only works on TSI databases; INMEM shards share
indices, so restricting shard indices used does not restrict
the tag values returned.
Closes https://github.com/influxdata/influxdb/issues/21981
> feat: SHOW TAG VALUES should produce results from one specific RP

- Dockerfile_build_ubuntu64
- releng/raw-binaries/Dockerfile
- releng/source-tarball/Dockerfile
- releng/unit-tests/Dockerfile
Earlier PR to pin rust version passed testing without this change, but this should keep master-1.x in line with 1.9, where this pin is required to avoid linting errors from rust 1.54
> chore: pin rust version in additional place

- .circleci/config.yml
- CHANGELOG.md
- build.py
- releng/packages/fs/usr/local/bin/influxdb_packages.bash
- scripts/ci/main.tf
- scripts/ci/terraform.tfvars
These changes:
* fix an issue preventing systemd from executing startup script included in deb and rpm packages
* add a install-and-launch test for the deb package as a smoke test for that installation path
> fix: systemd-start script should be executable by group and others

- .circleci/config.yml
- CHANGELOG.md
- scripts/influxd-systemd-start.sh
Closes #21967 
Check for https-enabled in influxdb config. Exit if certificate path does not exist or if 10 attempts have been made to contact the endpoint after startup.
This PR also updates the package install test to include a test of https using a self-signed certificate.
****
> fix: handle https in systemd wrapper, and prevent it from looping forever

- CHANGELOG.md
- services/snapshotter/service.go
Closes #22028
Backport from #22019.
> fix: error instead of panic when enterprise tries to restore with OSS

- CHANGELOG.md
- services/snapshotter/service.go
- services/snapshotter/service_test.go
Originally committed by rickif in https://github.com/influxdata/influxdb/pull/20115/files
This is manual copy of the changes to master-1.x
(cherry picked from commit 5bbb61b81525d2958add3d740c737bb707233171)
Closes #21989
> fix: restore portable backup error (#21978)

- CHANGELOG.md
- tsdb/index.go
This fix ensures that memory-mapped files are not released
before pointers into them are copied into heap memory.
MeasurementNamesByExpr() and MeasurementNamesByPredicate() can
cause panics by copying memory from mmapped files that have been
released. The functions they call use iterators to files which
are closed (releasing the mmapped files) before the memory is
safely copied to the heap.
closes https://github.com/influxdata/influxdb/issues/22000
> fix: copy names from mmapped memory before closing iterator

- tsdb/index/tsi1/index_test.go
Closes #22054
The recent change to actually test TSI index compaction exposed a test bug where the series file gets torn down before the index.
The index is still compacting:
```
unexpected fault address 0x7f371ca0501f
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f371ca0501f pc=0x8beea0]
goroutine 64 [running]:
runtime.throw(0xc902bd, 0x5)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0004eefe0 sp=0xc0004eefb0 pc=0x439632
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:749 +0x405 fp=0xc0004ef010 sp=0xc0004eefe0 pc=0x44f965
github.com/cespare/xxhash.Sum64(0x7f371ca0501f, 0x5, 0x3fffe1, 0x0)
/root/go/pkg/mod/github.com/cespare/xxhash@v1.1.0/xxhash_amd64.s:130 +0x160 fp=0xc0004ef018 sp=0xc0004ef010 pc=0x8beea0 …
```
> test: fix order of index teardown

- tsdb/index/tsi1/index_test.go
Closes #22055
(cherry picked from commit 444c22b67d425dbd23d8b71690effcfe8cbcba58)
> test: fix order of index teardown (#22038)

- CHANGELOG.md
- tsdb/index.go
This fix ensures that memory-mapped files are not released
before pointers into them are copied into heap memory.
MeasurementNamesByExpr() and MeasurementNamesByPredicate() can
cause panics by copying memory from mmapped files that have been
released. The functions they call use iterators to files which
are closed (releasing the mmapped files) before the memory is
safely copied to the heap.
closes https://github.com/influxdata/influxdb/issues/22000
(cherry picked from commit a989f8f8b6fc453c85075e5ae73033d5bd036e21)
Closes https://github.com/influxdata/influxdb/issues/22002
> fix: copy names from mmapped memory before closing iterator (#22040)

- cmd/influx_inspect/buildtsi/buildtsi.go
- cmd/influx_tools/importer/command.go
- cmd/influxd/restore/restore.go
- kit/metric/client.go
- kit/tracing/tracing.go
- kit/transport/http/api.go
- kit/transport/http/middleware.go
- kit/transport/http/middleware_test.go
- query/encode_test.go
- services/collectd/test_client/client.go
- services/meta/client_test.go
- services/meta/data_internal_test.go
- services/meta/data_test.go
- services/snapshotter/client.go
- tsdb/engine/engine.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/log_file_test.go
- tsdb/index/tsi1/partition.go
- tsdb/shard_test.go
Closes #22033
* fix: tsi index should compact old log files that are too large
* chore: run automated formatter
* chore: update changelog
* fix: review comments
(cherry picked from commit b64c2c3dcf1a5766fd671ea8ee3caa544e65611f)
> fix: tsi index should compact old or too-large log files (#21943)

- .circleci/config.yml
- scripts/ci/run_perftest.sh
This updates the `run_perftest.sh` script to also run a set of benchmarks to evaluate metaquery performance.
I extracted some of the common logic between the existing set of tests & the metaquery tests into separate functions so that it could be re-used.
> chore: add metaquery perf tests

- scripts/ci/run_perftest.sh
I suspect that the cardinality explosion we saw before was due to including `commit` as a tag, and that `branch` should be safe. Using `branch` as a tag will make writing queries in our results dashboard a lot easier.
> build: re-add branch as a tag in perftest results

- .goreleaser.yml
- scripts/ci/perf_test.sh
Closes #22077
@jdstrand warned that changing the file names here breaks some conventions, and could cause problems with other tooling in the packaging ecosystem. Revert back to the names we used before splitting out the CLI.
> build: revert renaming of influxd-only release artifacts

- CHANGELOG.md
- tests/server_test.go
- tsdb/config.go
- tsdb/engine.go
- tsdb/field_validator.go
- tsdb/shard.go
Per https://docs.influxdata.com/enterprise_influxdb/v1.9/write_protocols/line_protocol_reference/
we only support 64KB, but 1MB is a more realistic practical limit. Before this commit there was
no enforcement of field value size.
Closes #22094
(cherry picked from commit 6d22e69ef178abfeb546c736e367312989bbd49e)
> fix: hard limit on field size while parsing line protocol (#21843)

- scripts/ci/install-rust.sh
> chore: set rust version to the same as latest tag from flux (#21996)

- CHANGELOG.md
- scripts/fetch-ui-assets.sh
Closes #22080
Updates the pinned UI release version. The latest UI release uses the latest `flux-lsp-browser`.
> feat: upgrade UI to v2.0.8, `flux-lsp-browser` to v0.5.53

- CHANGELOG.md
- cmd/influxd/run/server.go
Replace usage of the Go log package with the zap
logger and respect the formatting specified in
the configuration file.
closes https://github.com/influxdata/influxdb/issues/22104
(cherry picked from commit 0315d2ede106c18dc2b54172b569990ecb0fd3f8)
closes https://github.com/influxdata/influxdb/issues/22105
> fix: ensure log formatting (JSON) is respected (#22106)

- scripts/ci/run_perftest.sh
Closes #22119
Setting `file_tag` adds a redundant tag to each line of result data we collect. Remove it to reduce our cardinality.
> build: remove file_tag from perf-test telegraf config

- cmd/influxd/inspect/dump_tsm/dump_tsm_test.go
This PR should fix the issue with dump_tsm tests failing in CI reported by @danxmoran
> chore: fix dump_tsm test missing flag

- .circleci/config.yml
- scripts/ci/perf_test.sh
- scripts/ci/run_perftest.sh
Follow-up to #22118
Prevent naming collisions when a single commit launches multiple perf-test VMs
> build: include query-format in EC2 perftest instance names

- CHANGELOG.md
- http/api_handler.go
- http/resources.go
- http/resources_test.go
This will add a route to return resources known to the platform. This allows the ui to generate an all-access token in a more uniform, and less brittle, way between cloud and oss.
> feat: add route to return platform known resources

- cmd/influxd/inspect/dump_tsm/dump_tsm_test.go
Removes a couple output checks in a testcase that seems to fail occasionally.
> chore: remove some flaky checks from `dump_tsm_test`

- .circleci/config.yml
- scripts/ci/run_perftest.sh
Closes #22147
This adds the existing IoT `1-home-12-hours` query test to the list of benchmarks that are run. As configured, this query runs very fast and takes ~1-2 ms with InfluxQl compared to ~10 ms with flux. See #22147 for the reasoning to do this.
> build: add perf test for fast query

- flags.yml
- kit/feature/list.go
Closes influxdata/ui#2306
Removes the `annotations` and `rangeAnnotations` flags
> chore: remove annotations and rangeAnnotations flags

- .circleci/config.yml
- scripts/ci/run_perftest.sh
Closes #22149
This adds a performance test for queries which just return a filtered set of data, with no additional transformations. Queries like this have been reported as being slower with Flux compared to InfluxQL. Based on the initial results of these tests, it looks like the Flux queries are actually now faster, so this test will help prevent performance regression.
Also see: https://github.com/influxdata/influxdb-comparisons/pull/188 & https://github.com/influxdata/influxdb-comparisons/pull/189
> build: add perf test for filtered queries

- scripts/ci/run_perftest.sh
Related to #18088
This adds performance tests for a set of data where an aggregateWindow function is called, followed by a keep and a mean. This query was orders of magnitude slower in Flux than in InfluxQL originally, but seems to have improved significantly since the original issue was opened.
See also https://github.com/influxdata/influxdb-comparisons/pull/182
> build: add perf test for aggregate-keep

- .circleci/config.yml
- CHANGELOG.md
- scripts/ci/main.tf
- scripts/ci/terraform.tfvars
- scripts/ci/tests/01-default-config.sh
- scripts/ci/tests/02-self-signed-certs.sh
- scripts/ci/tests/03-auth-enabled.sh
- scripts/influxd-systemd-start.sh
Closes #21967 for 2.0, #22155 
The systemd startup script should be able to handle an https endpoint.
This PR also adds a test for the install & run path for the deb on a VM host.
> fix: systemd service -- handle 40x and block indefinitely

- .circleci/config.yml
- scripts/ci/run_perftest.sh
Closes #22180
This is a simple adjustment to prevent the `host` tag from being included with the perf test results, to prevent unbounded growth in cardinality.
> build: don't include host tag on perf test results

- tests/backup_restore_test.go
- tests/server_concurrent_test.go
- tests/server_delete_test.go
- tests/server_helpers.go
- tests/server_test.go
- tsdb/shard.go
* docs: update comment for series updates
* fix: expose TCP address for Enterprise test harness
* refactor: remove dead RemoteServer code
(cherry picked from commit fd81373937c5823c7d131f79c733473c82a7aaf1)
> test: expose tcpaddr for enterprise tests (#22172)

- scripts/ci/run_perftest.sh
Closes #22016 
This adds performance tests to ensure that sorted-pivot pushdown occurs for Flux. Also can be used to catch any regressions in performance, as currently the time difference between Flux and InfluxQL is minimal.
See also https://github.com/influxdata/influxdb-comparisons/pull/190
> build: add perf test for sorted-pivot

- go.mod
- go.sum
- http/restore_service.go
- scripts/fetch-swagger.sh
The inconsistent form of the API remains (marked as deprecated) since v2.1.0 of the CLI uses it.
> refactor: use updated API in restore service

- CHANGELOG.md
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
When the compaction planner runs, if it cannot acquire
a lock on the files it plans to compact, it returns a
nil list of compaction groups. This, in turn, sets the
engine statistics for compactions queues to zero,
which is incorrect. Instead, use the length of pending
files which would have been returned.
closes https://github.com/influxdata/influxdb/issues/22138
> fix: avoid compaction queue stats flutter.

- CHANGELOG.md
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
When the compaction planner runs, if it cannot acquire
a lock on the files it plans to compact, it returns a
nil list of compaction groups. This, in turn, sets the
engine statistics for compactions queues to zero,
which is incorrect. Instead, use the length of pending
files which would have been returned.
closes https://github.com/influxdata/influxdb/issues/22138
(cherry picked from commit 7d3efe1e9e9f6efa92a41da1fc225886362d41a2)
closes https://github.com/influxdata/influxdb/issues/22139
> fix: avoid compaction queue stats flutter. (#22195)

- scripts/ci/run_perftest.sh
Adds the `iot` usecase and query-types `aggregate-keep`, `light-level-8-hr`, and `sorted-pivot` to 1.8 to track performance differences between master and 1.8
> build: add iot usecase tests to 1.8

- .circleci/config.yml
- scripts/ci/run_perftest.sh
Closes #22216
Adds the queries generated via https://github.com/influxdata/influxdb-comparisons/pull/193 to the performance tests that are automatically run.
> build: add multi measurement query benchmarks

- docker/flux/Dockerfile
- docker/influxd/Dockerfile
Closes #22221.
Pin "buster" in dockerfiles instead of using latest "stable" Debian release, as this seems to be causing problems when fetching from the package archive.
> chore: pin base Debian image in Docker builds

- .circleci/config.yml
Closes #22231
This makes it so that `pkg_run_test` will not run on forks, duplicating the filter that the `e2e-monitor-ci` job uses for the same purpose.
> build: dont run `pkg_run_test` on forks

- .goreleaser.yml
- CHANGELOG.md
Closes #22225 for `master`
The systemd wrapper script uses `curl` so it should be listed as a package dependency.
> fix: influxdb-server packages should depend on curl

- .circleci/config.yml
Ever since #22186, litmus tests have been passing against merges to `master` but failing in our nightly builds. I investigated and found that the way litmus is invoked in the nightly build caused it to pull & test the [`quay.io/influxdb/influxdb2:nightly`](https://github.com/influxdata/litmus-2.0/blob/master/src/cloud/conftest.py#L323) image. This image is:
1. Undocumented
2. Not auto-updated by any process
Rather than pour more energy into litmus, I've updated the nightly workflow to use the same litmus-test process as the workflow that runs per-commit.
I made a similar change for our grace tests because I've noticed they can be flaky in nightly runs, I think because of timing issues when the grace suite tries to launch `influxd` in Docker vs. us launching `influxd` as a pre-step before …
> build: delete duplicate jobs for grace/litmus, update nightly workflow

- .circleci/config.yml
- scripts/ci/run_perftest.sh
Closes #22227
Closes #22208
Cherry-pick of 2bf5f8ef3ed3927979f940a475f6d82f6efa2718 (multi-measurement) & d677fa1eebf0e536be22595bb951ac2a1c7843f9 (`group() |> aggregateWindow()`)
This backports the multi-measurement and `group() |> aggregateWindow()` perf tests from `master`.
> build: multi-measurement & `group() |> aggregateWindow()` backports

- CHANGELOG.md
- task/backend/coordinator/coordinator.go
- task/backend/coordinator/coordinator_test.go
Closes #21874
When a tasks is being updated, ensure is scheduled only when the tasks status is active. Otherwise, an already-inactivated tasks might be scheduled if the task status is not being changed.
> fix(task): inactive task runs when updated

- scripts/ci/run_perftest.sh
Closes #22226, #22209, #22178
Backports #22148, #22159, #22175, #22192, #22199, #22217 
This syncs the `run_perftest.sh ` for the `2.0` branch with the `master` branch. With this PR, the two scripts are identical.
> build: backport current perf tests to 2.0

- CHANGELOG.md
- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/engine_test.go
When the compaction planner runs, if it cannot acquire
a lock on the files it plans to compact, it returns a
nil list of compaction groups. This, in turn, sets the
engine statistics for compactions queues to zero,
which is incorrect. Instead, use the length of pending
files which would have been returned.
closes https://github.com/influxdata/influxdb/issues/22138
(cherry picked from commit 7d3efe1e9e9f6efa92a41da1fc225886362d41a2)
closes https://github.com/influxdata/influxdb/issues/22141
> fix: avoid compaction queue stats flutter

- .circleci/config.yml
- scripts/ci/run_perftest.sh
Updates the benchmark perf test script to use the alternate IoT query type names implemented by https://github.com/influxdata/influxdb-comparisons/pull/195
> build: use alterate names for IoT query types

- kv/migration/all/0017_add-annotations-notebooks-to-all-access-tokens.go
- kv/migration/all/0017_add-annotations-notebooks-to-all-access-tokens_test.go
- kv/migration/all/all.go
Closes #22256
The actual logic in the migration & unit tests is largely copy-pasted from migration 16, introduced in #21840
> fix: migrate all-access tokens to grant notebook/annotation permissions

- cmd/influxd/launcher/launcher.go
- notebooks/middleware_logging.go
- notebooks/middleware_metrics.go
- notebooks/service.go
- notebooks/service_test.go
Closes #22259
Adds logging and metrics middleware for the notebooks service. Follows the pattern used by other services.
> feat(notebooks): add logging and metrics to notebooks service

- annotations/middleware_logging.go
- annotations/middleware_metrics.go
- annotations/service.go
- annotations/service_test.go
- cmd/influxd/launcher/launcher.go
Closes #22260
Adds logging and metrics middleware for the annotations service. Follows the pattern used by other services.
> feat(annotations): add logging and metrics to annotations service

- CHANGELOG.md
- authorization/http_server.go
- authorization/http_server_test.go
- authorization/storage_authorization_test.go
Closes #22261
Fixes requests to `/api/v2/authorizations` so that the query parameters of `user` and/or `org` will be used to populate the filter with the respective ID's if `user`/`org` are present but `userID`/`orgID` are not in the query.
Giving precedence to the `ID` parameters if they are present over the "name" parameters seems to be consistent with how other resource endpoints work. For example, if you provide both a `user` and a `userID`, the `userID` will be used to filter the authorizations.
> fix: auth requests use org and user names if present

- tsdb/engine/tsm1/wal.go
- tsdb/engine/tsm1/wal_test.go
current code checks segment file size for rolling agains the default const, instead of the configured size.
> fix(tsm): check write-ahead-log size

- CHANGELOG.md
- coordinator/statement_executor.go
- coordinator/statement_executor_test.go
SHOW CONTINUOUS QUERIES now requires the same permissions
as SHOW DATABASES in order to see the continuous queries
in a database.
closes https://github.com/influxdata/influxdb/issues/10292
> fix: require database authorization to see continuous queries

- CHANGELOG.md
- coordinator/statement_executor.go
- coordinator/statement_executor_test.go
SHOW CONTINUOUS QUERIES now requires the same permissions
as SHOW DATABASES in order to see the continuous queries
in a database.
closes https://github.com/influxdata/influxdb/issues/10292
(cherry picked from commit 71b3d064943f3b0f940aaa4bdb1b6fa35b91a35a)
closes https://github.com/influxdata/influxdb/issues/22284
> fix: require database authorization to see continuous queries (#22283)

- CHANGELOG.md
- query/execution_context.go
- query/executor.go
- query/executor_test.go
executeQuery() iterates over statements until each is
processed or if an error is encountered that causes
the loop to exit pre-maturely. It should return
ErrNotExecuted for each remaining statement in the
query
closes https://github.com/influxdata/influxdb/issues/19136
> fix: return correct count of ErrNotExecuted

- sqlite/migrations/0004_create_replications_table.sql
> fix: add created_at and updated_at columns to replications table

- CHANGELOG.md
- query/execution_context.go
- query/executor.go
- query/executor_test.go
executeQuery() iterates over statements until each is
processed or if an error is encountered that causes
the loop to exit pre-maturely. It should return
ErrNotExecuted for each remaining statement in the
query
closes https://github.com/influxdata/influxdb/issues/19136
(cherry-picked from commit 0090c5b11141e99ee80dc8980cff615c3b63dfd6)
closes https://github.com/influxdata/influxdb/issues/22274
> fix: return correct count of ErrNotExecuted (#22273)

- cmd/influxd/inspect/delete_tsm/delete_tsm.go
- cmd/influxd/inspect/dump_tsi/dump_tsi.go
- cmd/influxd/inspect/dump_tsm/dump_tsm.go
- cmd/influxd/inspect/dump_tsm/dump_tsm_test.go
- cmd/influxd/inspect/report_tsi/report_tsi.go
- cmd/influxd/inspect/report_tsm/report_tsm.go
- cmd/influxd/inspect/report_tsm/report_tsm_test.go
- cmd/influxd/inspect/verify_seriesfile/verify_seriesfile.go
- cmd/influxd/inspect/verify_seriesfile/verify_seriesfile_test.go
- cmd/influxd/inspect/verify_tombstone/verify_tombstone.go
- cmd/influxd/inspect/verify_tombstone/verify_tombstone_test.go
- cmd/influxd/inspect/verify_tsm/verify_tsm.go
- cmd/influxd/inspect/verify_tsm/verify_tsm_test.go
- cmd/influxd/inspect/verify_wal/verify_wal.go
- cmd/influxd/inspect/verify_wal/verify_wal_test.go
Small changes to usage text and flag naming for 2.x `influxd inspect` commands for consistency between sub-commands.
> refactor: influxd inspect consistent usage and flag naming

- cmd/influxd/inspect/build_tsi/build_tsi.go
- cmd/influxd/inspect/build_tsi/build_tsi_test.go
Adds unit test coverage for the `inspect build-tsi` command. Achieves 84% coverage. Also includes changes to `build_tsi.go` to reduce the amount of logging during series compaction (unless verbose flag is chosen), and direct logs to stdout instead of stderr.
> chore: added unit test coverage to inspect build-tsi 2.x command

- CHANGELOG.md
Updates the `CHANGELOG.md` on the `master` branch to reflect the 2.0.8 release.
> chore: update `CHANGELOG` to reflect 2.0.8 release

- CHANGELOG.md
- http/legacy/backend.go
- http/legacy/influxqld_handler_test.go
- http/legacy/ping_handler.go
- http/legacy/ping_handler_test.go
- http/platform_handler.go
- static/data/swagger.yml
This PR fix the `/ping` endpoint:
- change build type from `cloud2` to `oss2`
- use correct version for `X-Influxdb-Version` header
> fix(pingEndpoint): change build type to 'oss', use correct version

- cmd/influxd/launcher/launcher.go
- prometheus/influx.go
Part of #19976
(Probably) best reviewed commit-by-commit.
* f72c752 switches the launcher to track a `closers` array so it doesn't have to track named references to various subsystems for use in `Shutdown`
* a5b1d6e moves the setup of tracing & metadata DBs out of `run` and into their own methods
* 8263c96 deletes some unused getters and their linked fields
* 613217f cleans up imports
> refactor: clean up launcher code

- CHANGELOG.md
- influxql/query/call_iterator.go
- influxql/query/compile.go
- influxql/query/functions.gen.go
- influxql/query/functions.gen.go.tmpl
- influxql/query/functions.go
- influxql/query/functions_test.go
- influxql/query/iterator.go
- influxql/query/iterator_test.go
- influxql/query/select.go
- influxql/query/select_test.go
- pkg/estimator/hll/hll.go
- pkg/estimator/hll/hll_test.go
- tsdb/engine/tsm1/engine.go
Closes #22317
Forward-ports #20603 and #21818
> feat(influxql): Add hyper log log operators 

- CHANGELOG.md
- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- http/api_handler.go
- http/query_handler.go
Closes #22071
Adds a flag `--flux-log-enabled` which when active will show detailed logs for flux queries.
> feat: add `--flux-log-enabled` flag for detailed flux logs

- CHANGELOG.md
- tsdb/index/tsi1/log_file.go
- tsdb/index/tsi1/partition.go
modTime should be protected by the read lock.
Closes #22337
> fix: TSI logfile race

- CHANGELOG.md
- cmd/influxd/inspect/build_tsi/build_tsi.go
- tsdb/index/tsi1/cache_test.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/log_file.go
- tsdb/index/tsi1/partition.go
Closes #22305
Forward-ports #21943, #22006, and #22338
> fix: make TSI index compact old and too-large log files

- tsdb/index.go
Named returns were not cherry-picked correctly from
commit a989f8f8b6fc453c85075e5ae73033d5bd036e21 in
master-1.x branch.
closes https://github.com/influxdata/influxdb/issues/22303
> fix: repair bad port dropping return value names

- tsdb/index.go
Rename variable for error return to avoid shadowing.
Closes https://github.com/influxdata/influxdb/issues/22351
> fix: correct error return shadowing

- authorizer/backup.go
- authorizer/sql_backup_restore.go
- backup.go
- bolt/kv.go
- cmd/influxd/launcher/engine.go
- http/backup_service.go
- http/backup_service_test.go
- inmem/kv.go
- kv/store.go
- mock/backup_service.go
- mock/kv.go
- sqlite/sqlite.go
- storage/engine.go
- v1/services/meta/client.go
- v1/services/meta/filestore/kv.go
The bolt KV implementation was already taking a read-lock instead of a read-write-lock, and mirroring that implementation in the inmem KV store also seems to work. Since our use-cases for locking the KV store from "outside" are all read-based (taking a backup, checking that bucket data matches info in sqlite) I think it makes sense to keep this pattern. Renaming the methods helps understand what's going on at a glance.
> refactor: rename Lock/Unlock on KV stores to RLock/RUnlock

- .circleci/config.yml
- CHANGELOG.md
- query/executor_test.go
- services/httpd/handler.go
- services/httpd/handler_test.go
- tsdb/engine/tsm1/engine_test.go
> fix: flux error properly read by cloud

- CHANGELOG.md
- build.py
- releng/packages/fs/usr/local/bin/influxdb_packages.bash
Closes #22225 for `1.8`.
The systemd wrapper script uses curl so it should be listed as a package dependency.
> fix: influxdb packages should depend on curl

- query/stdlib/testing/end_to_end_test.go
Closes #22365
This adds some additional logging output in the event of a failed flux e2e test. If a test fails, a query will be run to get all the data from the bucket, and log it in a format looking like this:
```
end_to_end_test.go:256: all data in TestFluxEndToEnd/planner/window_eval:
end_to_end_test.go:244: ,result,table,_start,_stop,_time,_value,_field,_measurement,host
end_to_end_test.go:244: ,_result,0,1970-01-01T00:00:00Z,2021-09-01T19:56:15.694996Z,2018-05-22T19:53:26Z,1.83,load1,system,host.local
end_to_end_test.go:244: ,_result,0,1970-01-01T00:00:00Z,2021-09-01T19:56:15.694996Z,2018-05-22T19:53:36Z,1.72,load1,system,host.local
end_to_end_test.go:244: ,_result,0,1970-01-01T00:00:00Z,2021-09-01T19:56:15.694996Z,2018-05-22T19:53:37Z,1.77,load1,system,host.local …
```
> feat: add additional log to flux e2e tests

- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/reader_test.go
The tsmBatchKeyIterator discards excessive errors to avoid
out-of-memory crashes when compacting very corrupt files.
Any error beyond DefaultMaxSavedErrors (100) will be
discarded instead of appended to the error slice.
closes https://github.com/influxdata/influxdb/issues/22328
> fix: discard excessive errors

- tsdb/engine/tsm1/compact.go
- tsdb/engine/tsm1/reader_test.go
The tsmBatchKeyIterator discards excessive errors to avoid
out-of-memory crashes when compacting very corrupt files.
Any error beyond DefaultMaxSavedErrors (100) will be
discarded instead of appended to the error slice.
closes https://github.com/influxdata/influxdb/issues/22328
(cherry picked from commit e53f75e06d0d2576e6db0175fe96c486014663a0)
Closes https://github.com/influxdata/influxdb/issues/22380
> fix: discard excessive errors (#22379)

- task/options/options.go
The latest flux version added a function for formatting durations via the rust formatter, so we can delete our copy of the logic.
> refactor: use new flux function to format duration literals

- tsdb/store_test.go
I've noticed `TestStore_CreateMixedShards` occasionally gets flagged by the race-detector (for example, [here](https://app.circleci.com/pipelines/github/influxdata/influxdb/23677/workflows/2c440cfb-687d-4112-a96b-4bc83cdde2b9/jobs/211276/tests#failed-test-0)). Instead of fixing the test, I think we can delete it. It's meant to check that multiple shards can be created using different index types, but 2.x only has TSI indexes.
> chore: delete pointless test for mixed-index shards

- authz.go
Closes #22408 
Use `path.Join` instead of `filepath.Join` so auth resources have a consistent string representation across Linux, Mac, and Windows.
> fix: use consistent path separator in permission string representation

- influxql/query/functions_test.go
- influxql/query/select_test.go
- query/stdlib/testing/testing.go
Closes #22410
The logic used in our HoltWintersReducer produces different floating-point results depending on the CPU architecture. Tests that assert on specific outputs of the functions fail on non-amd64 architectures (see #18254 for an example).
> test: skip HoltWinters tests when GOARCH != amd64

- cmd/influxd/launcher/launcher.go
- remote_connection.go
- remotes/mock/service.go
- remotes/service.go
- remotes/transport/http.go
- remotes/transport/http_test.go
- remotes/transport/middleware_logging.go
- remotes/transport/middleware_metrics.go
- replication.go
- replications/mock/service.go
- replications/service.go
- replications/transport/http.go
- replications/transport/http_test.go
- replications/transport/middleware_logging.go
- replications/transport/middleware_metrics.go
Instead of keeping these interfaces at the root, move them to their use-sites (the HTTP layer). I expect that different pieces of the system will have different requirements for what a "remote service" and (especially) a "replication service" means. 
Rather than bloating a single centralized interface, shift towards a model of client-side interfaces.
This also moves the logging & metrics middlewares into the `transport` package, since they're HTTP-focused layers.
> refactor: move interfaces for remotes & replication services out of root package

- .circleci/config.yml
Discovered while working on the kapa build.
Circle has released a newer linux machine image with a newer docker version. We can use the image and delete the manual step of upgrading docker.
> build: bump machine executor image to version with upgraded docker

- sqlite/sqlite_helpers.go
Linux & Mac are apparently forgiving enough to allow the `os.RemoveAll` to pass even when the SQL store is still pointing at the files inside, but Windows fails the deletion.
> test: close test SQL store before deleting its tmp dir in tests

- .circleci/config.yml
Closes #22431
`docker_layer_caching` was enabled in #22402. Since then we've seen spurious failures in the `cross_build` job when setting up docker cross-builders. [This community post](https://discuss.circleci.com/t/build-docker-image-fails-randomly-with-error-response-from-daemon-container-is-marked-for-removal-and-cannot-be-started/39429/3) suggests that bad caching is to blame for the failures we've seen. Revert the caching config to see if that stabilizes things for us.
> build: disable docker-layer-caching in machine executors

- .circleci/config.yml
Closes #22429
The grace tests apparently don't wait-for-it on startup, so we have to do it manually before launching the test suite.
> build: add curl loop before grace-daily runs to wait for server startup

- .circleci/config.yml
- .goreleaser.yml
- CHANGELOG.md
Continuation of development on #19645 
Because `master` is a protected branch requiring at least 1 review of a PR for any push, we are instead electing to redirect those interested in the changelog to an s3 link instead of trying to update VCS with every changelog change.
> chore: omit VCS commands for changelog in favor of s3-only approach

- .circleci/config.yml
- .goreleaser.yml
Incremental CI improvement in service of #19645 
This PR enables nightly builds of the `2.0` branch, to be "published" to s3 and quay
> chore: enable nightly builds

- .circleci/config.yml
Nightly changelog automation needs to first fetch changelog files from the previous night.
> chore: fetch changelog files prior to updating

- .goreleaser.yml
Closes #22444
Set the `timetzdata` flag when building Windows binaries to embed fallback time-zone info. This prevents a panic when using `time.LoadLocation` on a Windows machine that doesn't have Go installed.
> fix: embed tzinfo into Windows builds to avoid panics in InfluxQL engine

- cmd/influxd/inspect/build_tsi/build_tsi.go
The most immediate benefit of this is that it allows the `buildtsi` unit tests to pass when running tests as a root user, which is what happens when we use our cross-builder image in 2.x CI.
> fix: detect noninteractive prompt when displaying warning in buildtsi

- kit/signals/context.go
- kit/signals/context_test.go
`context_test.go` uses `syscall.SIGUSR1` and `syscall.SIGUSR2`, which aren't available on Windows. AFAIK the only signals shared between Windows and *nix Go platforms are Interrupt and Kill, both of which would be tricky to use in the existing test structure. Skip the test on Windows instead of going through the effort of refactoring the test.
> test: skip signals test on Windows

- .goreleaser.yml
Closes #22456
Goreleaser should use the version it is passed for quay.io tags, instead of the latest git tag; this is to prevent nightly builds from stepping on releases.
> build: the tag used for quay images should be determined by the VERSION

- cmd/influxd/inspect/delete_tsm/delete_tsm.go
- cmd/influxd/inspect/delete_tsm/delete_tsm_test.go
Windows is apparently really strict about enforcing that there are no open handles to a file when you try to move or delete it; if there's a dangling reference, you get a permissions error. It also prevents a move that overwrites an existing file; you have to delete the file at the destination first, then move.
> fix: ensure files are closed before they are deleted or moved in `deletetsm`

- cmd/influxd/inspect/report_tsi/report_tsi_test.go
On Windows, the outputs come out separated by `\` instead of `/`.
> test: don't assume unix paths in reporttsi tests

- .circleci/config.yml
- .goreleaser.yml
Allows changelogs to be successfully found and uploaded to S3 by goreleaser
> chore: persist changelog artifacts to workspace for uploading

- cmd/influxd/inspect/build_tsi/build_tsi.go
- cmd/influxd/inspect/build_tsi/build_tsi_test.go
* Make sure any series files created as part of test setup are fully closed before running the `buildtsi` command
* Replace hard-coded unix paths with use of `filepath.Join`
> test: close temp sfile before running buildtsi compaction test

- cmd/influxd/backup/backup.go
> fix: better error for no data from snapshots

- .circleci/config.yml
- scripts/ci/run_perftest.sh
Closes #22350
Updates the perf test script to populate the database with the data from one use case at a time and run all applicable tests against that data, removing the data from the database between runs.
> build: run perf test queries only on specific datasets

- cmd/influxd/backup/backup.go
Close temp files before removing them, because 
Windows does not permit open files to be removed.
Closes https://github.com/influxdata/influxdb/issues/21470
> fix: For Windows, close temp file before removing

- .circleci/config.yml
Fixes a flaky issue with changelog job in CI where a `curl` to `dl.influxdata.com` will sometimes fetch an old file, likely due to the CDN distribution not having been invalidated since the previous nightly.
> build: changelog job should use aws domain to avoid CDN caching

- cmd/influxd/inspect/dump_wal/dump_wal_test.go
- cmd/influxd/inspect/report_tsi/report_tsi_test.go
- cmd/influxd/inspect/verify_tombstone/verify_tombstone_test.go
- cmd/influxd/upgrade/fs_test.go
- cmd/influxd/upgrade/upgrade_test.go
* Assert on subset of error messages common between Windows and Unix
* Assert that file permissions don't change after being moved instead of asserting on a unix-specific permission
* Use generic filepath separators instead of hard-coding `/`
* Ensure files are closed before moving / deleting them
> test: update various tests to pass on Windows

- go.mod
- go.sum
Follow-up to the go1.17.1 upgrade.
Backports #22367
> fix: upgrade golang.org/x/sys to avoid panics on Macs

- tsdb/index/tsi1/file_set.go
- tsdb/index/tsi1/file_set_test.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/partition.go
Backports #20770, #21831, and #22309
Useful to backport because it makes cherry-picking other changes easier
> refactor: various cleanups to the TSI file set

- go.mod
Follow-up to  #22521, this reformats the `go.mod` file to be back into a single `require(...)` section. Fundamentally nothing is changing - the `go.sum` is unchanged. This just puts things back into the format they were before, retaining the updates for the latest version of flux.
> chore: clean up go.mod

- cmd/influxd/inspect/build_tsi/build_tsi_test.go
- tsdb/series_file_test.go
Closes #22514
This refactors 1 test and skips another to work around Windows' requirement that files be resized to the target length before being mmap'd.
> test: check post-compaction series file sizes before reopening

- http/handler.go
- tsdb/index/tsi1/index_test.go
Closes #20224
Also a forward port of #22038 since I saw the same test failing on 2.x
> feat: set X-Influxdb-Version and X-Influxdb-Build headers

- http/query.go
Closes #16941
The linked issue suggests that when a query request fails to parse as JSON, we should try parsing it as Flux and (if successful) return a message saying to set the appropriate `Content-Type` header. This PR simplifies that idea by always returning the suggestion to try setting `Content-Type: application/vnd.flux` when a query fails to parse as JSON, and letting users decide whether or not the suggestion is appropriate. I feel better about this approach for two reasons:
1. We aren't burning CPU parsing request bodies just to return an error message
2. We end up showing the suggestion to more relevant failure cases (i.e. to users who try sending raw Flux queries, but typo their request bodies in a way that would cause parsing to fail)
> fix: suggest setting flux Content-Type when query fails to parse as JSON

- cmd/influxd/restore/restore.go
closes https://github.com/influxdata/influxdb/issues/15901
Ensure that the `-db` parameter is given if the `-newdb` parameter is.
> fix(restore): enforce the -db parameter when -newdb used

- tsdb/engine/tsm1/copy_or_link_unix.go
- tsdb/engine/tsm1/copy_or_link_windows.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/engine/tsm1/file_store.go
On Windows, make copies of files for snapshots, because
Go does not support the FILE_SHARE_DELETE flag which
allows files (and links) to be deleted while open. This
causes temporary directories to be left behind after
backups.
closes https://github.com/influxdata/influxdb/issues/16289
> fix: for Windows, copy snapshot files being backed up

- tsdb/engine/tsm1/engine_test.go
I've seen `TestEngine_LastModified` fail occasionally on the Windows executor. My guess is the root cause is the same as #22479, where the test is running faster than `time.Now()` updates on Windows.
This test already had a `time.Sleep` between two checks of `LastModified()`, so I added another one. The timing of the existing sleep felt excessive, so I borrowed time from it to use in the 2nd sleep so the total test time stays about the same.
> test: sleep between 2nd and 3rd checks of engine last-modified time

- tsdb/engine/tsm1/copy_or_link_unix.go
- tsdb/engine/tsm1/copy_or_link_windows.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/engine/tsm1/file_store.go
On Windows, make copies of files for snapshots, because
Go does not support the FILE_SHARE_DELETE flag which
allows files (and links) to be deleted while open. This
causes temporary directories to be left behind after
backups.
closes https://github.com/influxdata/influxdb/issues/16289
(cherry picked from commit 3702fe8e7688499dc6183ad20c90e6c3a6a812ed)
closes https://github.com/influxdata/influxdb/issues/22557
> fix: for Windows, copy snapshot files being backed up (#22551)

- cmd/influxd/restore/restore.go
- tsdb/engine/tsm1/copy_or_link_unix.go
- tsdb/engine/tsm1/copy_or_link_windows.go
- tsdb/engine/tsm1/engine_test.go
- tsdb/engine/tsm1/file_store.go
* fix(restore): enforce the -db parameter when -newdb used
closes https://github.com/influxdata/influxdb/issues/15901
(cherry picked from commit 1dde65bb75f3744c01313f5bd8f54f0262dd0da4)
closes https://github.com/influxdata/influxdb/issues/22560
* fix: for Windows, copy snapshot files being backed up
On Windows, make copies of files for snapshots, because
Go does not support the FILE_SHARE_DELETE flag which
allows files (and links) to be deleted while open. This
causes temporary directories to be left behind after
backups.
closes https://github.com/influxdata/influxdb/issues/16289
(cherry picked from commit 3702fe8e7688499dc6183ad20c90e6c3a6a812ed)
closes https://github.com/influxdata/influxdb/issues/22559
> fix(restore): parameter validation, Windows temp file deletion

- tsdb/series_segment.go
> fix(tsdb): (1.9) sync series segment to disk after writing

- tsdb/series_segment.go
Clean cherrypick of #22545 
Closes #20245
> fix(tsdb): (1.x) sync series segment to disk after writing

- scripts/ci/run_perftest.sh
Adds tests for "ungrouped" aggregates that return a single value, i.e. the total count of records matching a predicate
> test: add ungrouped-agg case to perf test suite

- .circleci/config.yml
I also looked into downloading the Linux binary and using the public-key crypographic verification method outlined in the goreleaser docs here: https://goreleaser.com/install/#verifying-the-binaries. However, this uses `cosign`. I felt this would have added too much complexity. Instead, we just use the checksum provided on the release page.
> ci: Verify checksum of goreleaser install script

- http/points/points_parser.go
- http/write_handler_test.go
Closes #22573
Allow empty writes. Cloud has allowed this since influxdata/idpe#9724, some of the changes here match that PR 1:1
> fix: allow empty reqeust bodies to write API

- .circleci/config.yml
- scripts/ci/build-tests.sh
- scripts/ci/run-prebuilt-tests.sh
Part of #20855
This is a subset of a broader change to switch the 2.x CI pipeline over to use our cross-builder image with additional parallelization. It extends the CLI pipeline to:
1. In parallel, compile our `_test.go` files into runnable binaries targeted at `linux/arm64`, `darwin/amd64`, and `windows/amd64`
2. In parallel, run the prebuilt binaries from step 1 on the native executors provided by Circle
The benefit of adding these steps is guarding against regressions on all of our target platforms. It doesn't speed up or slow down the overall runtime of our pipeline; to do that, we'll need to break up our `cross_build` step into parallel jobs and reimplement the packaging logic currently provided by goreleaser.
> build: add CI jobs to natively test ARM64, Mac, and Windows

- http/api_handler.go
- http/resources.go
- http/resources_test.go
(cherry picked from commit 7aaba338b2c4eeda57a6155badedad1900645855)
Backports #22135
> feat: add route to return platform known resources (#22135)

- Makefile
Various make targets call '$(GO_BUILD)' but there is no facility for
specifying arguments to 'go build'. As a first step, introduce the
GCFLAGS Makefile variable that when unset, operates as always, but when
set, adds '-gcflags "$(GCFLAGS)"' to go build. Eg, when unspecified,
maintain the current behavior:
```
$ make
...
env GO111MODULE=on go build -tags ... -ldflags ...
```
When specified, add the specified -gcflags:
```
$ GCFLAGS="all=-N -l" make
...
env GO111MODULE=on go build -tags ... -gcflags "all=-N -l" -ldflags ...
```
This could be useful in various situations such as producing unoptimized
builds (like in the above).
In addition, remove the now unused (since cmd/influx was removed)
GO_BUILD_SM environment variable.
> chore(Makefile): allow specifying -gcflags via env

- .circleci/config.yml
Jobs do not get run during tags unless specifically identified by the
filter stanza
> build: ensure changelog job is run during tag

- .circleci/config.yml
* push artifacts to "experimental" folder in s3
* otherwise build in the same way
This PR will help prevent surprises on release day and avoid us having to e.g. move tags because of build failures in tagged commit.
> build: enable testing of release workflow via *test tag

- tsdb/series_segment.go
This reverts commit 6692a14cf4569cfe73b888d5e3cde5cdc44a6a10.
> chore: Revert "fix(tsdb): sync series segment to disk after writing (#22565)"

- v1/services/meta/data.go
- v1/services/meta/data_test.go
> fix: do not allow shard creation to create overlapping shards

- cmd/influxd/launcher/launcher.go
- http/api_handler_test.go
- http/auth_test.go
- http/authentication_test.go
- http/check_test.go
- http/delete_test.go
- http/document_service_test.go
- http/document_test.go
- http/errors_test.go
- http/label_test.go
- http/legacy/influx1x_authentication_handler_test.go
- http/legacy/influxqld_handler_test.go
- http/legacy/write_handler_test.go
- http/notification_endpoint_test.go
- http/query_handler_test.go
- http/router_test.go
- http/scraper_service_test.go
- http/task_service_test.go
- http/user_test.go
- http/variable_test.go
- http/write_handler_test.go
- kit/transport/http/error_handler.go
- kit/transport/http/error_handler_test.go
> fix: more expressive errors

- cmd/influxd/backup_util/backup_util.go
Use `atomic` operations to update and report CountingWriter.Total through a new method.
Closes https://github.com/influxdata/influxdb/issues/22618
> feat: add thread-safe access to CountingWriter byte total

- cmd/influxd/launcher/backup_restore_test.go
- cmd/influxd/launcher/replication_test.go
- go.mod
- go.sum
- replications/internal/validator.go
- replications/service.go
Closes #22295
To validate a replication, we send an empty payload to the `/api/v2/write` of the remote server.
> feat: implement replication validation

- cmd/influxd/downgrade/downgrade.go
- cmd/influxd/main.go
- kv/migration/all/0016_add-annotations-notebooks-to-oper-token.go
- kv/migration/all/0016_add-annotations-notebooks-to-oper-token_test.go
- kv/migration/all/0017_add-annotations-notebooks-to-all-access-tokens.go
- kv/migration/all/0017_add-annotations-notebooks-to-all-access-tokens_test.go
- kv/migration/all/0018_repair-missing-shard-group-durations.go
- kv/migration/all/0019_add-remotes-replications-to-tokens.go
- kv/migration/all/0019_add-remotes-replications-to-tokens_test.go
- kv/migration/migration.go
- testing/migration.go
Closes #22774
For now the command only downgrades KV metadata. A follow-up PR will add support for downgrading SQL.
> feat: initialize `influxd downgrade` command to run `Down()` migrations on metadata

- cmd/influxd/downgrade/downgrade.go
- cmd/influxd/launcher/launcher.go
Closes #22779
Backports https://github.com/influxdata/influxdb/issues/22775
Clean cherry-pick of 88d6487f4a95dfd4d699bdc155f1fff57a792efb
> feat: extended downgrade command to include sql migrations

- .circleci/config.yml
- scripts/ci/test-downgrade.sh
The test isn't very intensive right now. It:
1. Starts up the binary built from a previous job
2. Calls the `setup` API on it
3. For each downgrade target (currently just `2.0`):
1. Downloads the old binary
2. Runs `influxd downgrade` using the new binary on a copy of the new meta stores
3. Boots the old binary on the downgraded meta stores
> build: add a CI job to test `influxd downgrade`

- tests/backup_restore_test.go
- tests/slowproxy_test.go
- tsdb/shard.go
Fixes a race condition in the restore code path that causes shard data restores to fail. When the bug occurs, `Error while freeing cold shard resources` appears in the log files.
fixes issue #15323
> fix(restore): fix race condition which causes restore command to fail

- CONTRIBUTING.md
- gather/metrics.go
- gather/metrics_test.go
- gather/prometheus.go
- gather/scheduler_test.go
- gather/scraper_test.go
- go.mod
- prometheus/filter.go
- prometheus/filter_test.go
- prometheus/prometheus_test.go
- telemetry/push_test.go
- telemetry/telemetry_test.go
- Remove `gogo/protobuf` and `golang/protobuf` deps
- Fix mistake in `CONTRIBUTING.md`
- Use Prometheus `MetricType` type over our own copy-paste version
After this PR, Protobuf work on `master` should be fully complete
> chore: clean up protobuf loose ends

- pkg/durablequeue/queue.go
- pkg/durablequeue/queue_test.go
- replications/internal/queue_management.go
- replications/mock/queue_management.go
- replications/service.go
- replications/service_test.go
- sqlite/migrations/0005_create_replications_table.up.sql
Related to #22171
Maintaining the current queue size in a SQL column would require updating the DB on every queue operation. Avoid that contention by instead looking up the current size on the in-memory durable queue struct, which is already tracked & updated as data enters & leaves the queue.
> refactor: remove replications.current_queue_size_bytes from sqlite

- .goreleaser.yml
Follow-up to https://github.com/influxdata/influxdb/pull/22835; should fix the nightly deploy & release job problems with goreleaser not able to find the `changelog-commit` file (because it is no longer generated or needed).
> chore: don't look for non-existent changelog file in release job

- .goreleaser.yml
Follow-up to https://github.com/influxdata/influxdb/pull/22842, looks like I missed one of the references.
> build: remove additional commit file from goreleaser config

- .circleci/config.yml
- .goreleaser.yml
Closes #22855
Closes #22854
Updates `goreleaser` to the latest version. The updated `goreleaser` does _not_ skip the semver tag check with `--skip-validate`. This will ensure our builds cannot use invalid versions.
Also adds the `GORELEASER_CURRENT_TAG` which [goreleaser uses to determine the version it should use for builds](https://github.com/goreleaser/goreleaser/blob/master/www/docs/cookbooks/set-a-custom-git-tag.md). This will ensure that the same version information is used for all binaries and packages produced by goreleaser, and that is consistent with the tag that triggered the release.
To test this, I temporarily modified the CI config so that the "release" job would run on commits (but not publish anything) and simulate what would happen if there were one or more good/bad tags …
> build: better versioning and verification for releases

- .circleci/config.yml
Fixup for #22877, to prevent failures like [this](https://app.circleci.com/pipelines/github/influxdata/influxdb/25839/workflows/f52234dd-febf-4078-a1e2-b38b822ea604/jobs/230474)
> build: setup docker before trying to push image

- .circleci/config.yml
Successful run of job with these changes: https://app.circleci.com/pipelines/github/influxdata/influxdb/25872/workflows/36ac5268-649d-4453-b247-9cfe7fe5e821/jobs/230973
> build: pull SHA-specific image before tagging it as latest

- replications/internal/queue_management.go
- replications/internal/queue_management_test.go
- replications/service.go
Closes #22878
This PR moves to using a separated remote write function for the NewDurableQueueManager function, which is what will be called when the Scanner pops data off the queue for writing to a remote host.
It also refactors the `replicationQueue` struct to hold a ptr reference to the durableQueueManager, since it references several pieces of the queue manager (logger, writeFunc, maybe more to come in the future)
> refactor: use remote write func in NewDurableQueueManager

- cmd/influxd/inspect/build_tsi/build_tsi.go
- tsdb/engine/tsm1/cache.go
- tsdb/engine/tsm1/cache_race_test.go
- tsdb/engine/tsm1/cache_test.go
- tsdb/engine/tsm1/compact_test.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
Closes #20022
Example:
```
➜  ~ curl localhost:8086/metrics | grep storage_cache
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 29901    0 29901    0     0  14.2M      0 --:--:-- --:--:-- --:--:-- 14.2M
storage_cache_disk_bytes{bucket="b7da63cc2f6d922f",engine="tsm1",id="5",path="/Users/sarnold/.influxdbv2/engine/data/b7da63cc2f6d922f/autogen/5",walPath="/Users/sarnold/.influxdbv2/engine/wal/b7da63cc2f6d922f/autogen/5"} 0
storage_cache_disk_bytes{bucket="b7da63cc2f6d922f",engine="tsm1",id="7",path="/Users/sarnold/.influxdbv2/engine/data/b7da63cc2f6d922f/autogen/7",walPath="/Users/sarnold/.influxdbv2/engine/wal/b7da63cc2f6d922f/autogen/7"} 0
storage_cache_disk_bytes{bucket="d2dc443f48b2c910",engine="tsm1",id="1" …
```
> feat: metrics for cache subsystem

- cmd/influxd/inspect/verify_wal/verify_wal_test.go
- tsdb/engine/tsm1/cache.go
- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/wal.go
- tsdb/engine/tsm1/wal_test.go
Depends on https://github.com/influxdata/influxdb/pull/22915
Closes #20026
Example:
```
➜  ~ curl localhost:8086/metrics | grep storage_wal
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 32082    0 32082    0     0  15.2M      0 --:--:-- --:--:-- --:--:-- 15.2M
storage_wal_size{bucket="b7da63cc2f6d922f",engine="tsm1",id="5",path="/Users/sarnold/.influxdbv2/engine/data/b7da63cc2f6d922f/autogen/5",walPath="/Users/sarnold/.influxdbv2/engine/wal/b7da63cc2f6d922f/autogen/5"} 0
storage_wal_size{bucket="b7da63cc2f6d922f",engine="tsm1",id="7",path="/Users/sarnold/.influxdbv2/engine/data/b7da63cc2f6d922f/autogen/7",walPath="/Users/sarnold/.influxdbv2/engine/wal/b7da63cc2f6d922f/autogen/7"} 134623 …
```
> feat: metrics for WAL subsystem

- tsdb/index/tsi1/partition.go
Sync index file before close.
Index file may be broken after a system crash or a power failure, which will cause an error when loading shard after restart: unsupported index file version.
> fix(tsi): sync index file before close

- .circleci/config.yml
- go.mod
- models/inline_strconv_parse.go
- models/uint_support.go
- pkg/file/file_unix.go
- pkg/mmap/mmap_solaris.go
- pkg/mmap/mmap_unix.go
- tools.go
- tsdb/engine/tsm1/mmap_unix.go
* chore: upgrade Go to 1.17
* fix: update circleci container to go1.17
* fix: correct unsafe conversion of []byte to string
Co-authored-by: Sam Arnold <sarnold@influxdata.com>
(cherry picked from commit 08a4a710ebc54bd5ce7b57e6828e2266f093961f)
> chore: upgrade Go to 1.17 

- CONTRIBUTING.md
- README.md
Update CONTRIBUTING doc to reflect the separation of influxdata/influx (CLI) from influxdata/influxdb (influxd).
Order and cleanup build instructions.
Update Flux description in README.
> fix: remove influx CLI output from CONTRIBUTING

- replications/internal/queue_management.go
- replications/internal/queue_management_test.go
- replications/metrics/replications_metrics.go
- replications/remotewrite/writer.go
- replications/remotewrite/writer_test.go
Closes #22734
Finishes metrics implementation for replications by adding metrics for remote writes. Also improves debug logging for remote writes.
> feat: metrics collection for replications remote writes

- replications/internal/queue_management.go
- replications/internal/queue_management_test.go
Closes #22964
Advances the queue after successful remote writes. This prevents a condition where after a sequence of successful remote writes, an error returned from the remote write function [perhaps due to a server shutdown](https://github.com/influxdata/influxdb/pull/22958) puts the queue into a state where remote writes will be duplicated when `SendWrite` is called again.
> fix: advance replications queue after successful remote writes

- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/cmd_test.go
- cmd/influxd/launcher/launcher.go
Closes #22863
Throws an error on server startup if there are values in the config file ~which do not correspond to a valid configuration option~ which are determined to be from a 1.x config. Also adds debug logging if a config file is loaded.
> feat: error out when config file contains 1.x config values

- cmd/influxd/launcher/cmd.go
- query/control/controller.go
Closes #23012
Helps with https://github.com/influxdata/influxdb/issues/22917
Instead of defaulting to the maximum `int64` value while parsing the configuration and binding the variables, set the `MemoryBytesQuotaPerQuery` to unlimited in the query controller if a config value is not set. This will prevent the runtime configuration from including a large number that cannot be parsed accurately from a config file in JSON format.
The small change here is actually identical to code on the 1.x branch: https://github.com/influxdata/influxdb/blob/e8c9f545323371ab9a4a1129f97ca16351daecae/query/control/controller.go#L119
Which was implemented in https://github.com/influxdata/influxdb/pull/21100
...so it does not introduce divergence between common areas of 1.x and 2.x code.
> feat: `query-memory-bytes` zero-value is unlimited

- cmd/influxd/launcher/print_config.go
Part of #22917
Adds deprecation notice to `influxd print-config`.
> chore: add deprecation notice for print-config command

- pkger/doc.go
- pkger/http_server_template.go
- pkger/http_server_template_test.go
- pkger/parser.go
- pkger/parser_test.go
- pkger/service.go
- pkger/service_test.go
Disables server-side jsonnet processing to eliminate potential issues with the `go-jsonnet` implementation.
> fix(templates): disable use of jsonnet with `/api/v2/templates/apply`

- .circleci/config.yml
- releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash
This increases the c-stack size because the MUSL stack is too small for the rust-based flux parser.
> build: bigger stack for musl builds

- replications/internal/queue_management_test.go
Closes #23002
See dcdd46be3adf27fe15abec287ab1f4f18f80ea5f for a run with a failure; this was manipulated to run the test a large number of times. The race tests in particular showed many failures: https://app.circleci.com/pipelines/github/influxdata/influxdb/26540/workflows/0d2f953d-0293-43b1-a4c1-5c76955eb435/jobs/238266
9f9ed84f9c5b1c01dfc2866cc2fb6e8ffad2e14f & 5cdabe8ef50b38d79ab44db51236b4a2afffdbb2 also both ran the test ~1000 times each, without failure, after the fix was applied.
The failure was pretty hard to reproduce, but I think what was happening was the test closing the `done` channel simultaneously with the `receive` channel having a message available, and that was (rarely) causing the write function to return before actually processing the enqueue'd data, hence the lack …
> test: fix flaky enqueue test

- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- query/control/controller.go
Closes #21286
Results in a log line like this if the server is shutdown with SIGINT while a flux query is in-progress:
```
2021-12-29T21:34:54.612657Z	info	Cancelling Flux query because of server shutdown	{"log_id": "0Yj1cVWW000", "service": "storage-reads", "query": "import \"http\" http.post(url: \"http://localhost:8080\") from(bucket: \"bucket\") |> range(start: 0) |> yield()"}
```
> feat: option to log flux queries cancelled because of server shutdown

- etc/config.sample.toml
- tsdb/config.go
- tsdb/store.go
Currently, deletion of series or measurements are
serialized. This new feature will add
max-concurrent-deletes to the [data] section of the
configuration file. Legal values are any positive
number, defaulting to 1, the current behavior.
closes https://github.com/influxdata/influxdb/issues/23054
> feat: configurable DELETE concurrency

- checks/service.go
- notification/check/check.go
- notification/check/check_test.go
Closes #16317
Straightforward change, since the [API spec](https://github.com/influxdata/openapi/blob/master/src/common/schemas/CheckBase.yml) already doesn't show this field as being required, [OwnerID](https://github.com/influxdata/influxdb/blob/11c00813f106062829759a97673c7c945d5859ca/notification/check/check.go#L21) is already an optional field in the JSON struct, and as it currently works even if you tried to update the `ownerID` it wouldn't do anything anyway since the existing `ownerID` is always set by the storage service: https://github.com/influxdata/influxdb/blob/11c00813f106062829759a97673c7c945d5859ca/checks/service.go#L506
> fix: updating a check does not require an owner id

- tsdb/index/inmem/inmem.go
- tsdb/shard.go
- tsdb/shard_test.go
- tsdb/store_test.go
Check for the correctly returned PartialWriteError
in (*shard).validateSeriesAndFields, allow partial
writes.
closes https://github.com/influxdata/influxdb/issues/23090
> fix: correctly handle MaxSeriesPerDatabaseExceeded

- tsdb/index/inmem/inmem.go
- tsdb/shard.go
- tsdb/shard_test.go
- tsdb/store_test.go
Check for the correctly returned PartialWriteError
in (*shard).validateSeriesAndFields, allow partial
writes.
closes https://github.com/influxdata/influxdb/issues/23090
(cherry picked from commit 0c3dca883ee58ca204e6cb0d528bfe2b93e1956d)
closes https://github.com/influxdata/influxdb/issues/23092
> fix: correctly handle MaxSeriesPerDatabaseExceeded (#23091)

- tsdb/shard.go
Check for the correctly returned PartialWriteError
in (*shard).validateSeriesAndFields, allow partial
writes.
closes https://github.com/influxdata/influxdb/issues/23096
> fix: correctly handle PartialWriteError

- tsdb/index/inmem/inmem.go
- tsdb/shard_test.go
- tsdb/store_test.go
To simplify debugging, print the database name when the
max-series-per-database limit is exceeded in InMem indices.
closes https://github.com/influxdata/influxdb/issues/23112
> fix: add database to MaxSeriesPerDatabase error message

- tsdb/index/inmem/inmem.go
- tsdb/shard_test.go
- tsdb/store_test.go
To simplify debugging, print the database name when the
max-series-per-database limit is exceeded in InMem indices.
closes https://github.com/influxdata/influxdb/issues/23112
(cherry picked from commit 7d182158f436e454c27af01cc90cbd2e9c759923)
closes https://github.com/influxdata/influxdb/issues/23114
> fix: add database to MaxSeriesPerDatabase error message (#23113)

- query/control/controller.go
- query/control/controller_test.go
- query/stdlib/influxdata/influxdb/source.go
We're removing this functionality from flux because it doesn't work
properly so remove the invocations here.
> refactor(query): remove detailed query traces

- authorizer/authorize_find.go
- cmd/influxd/launcher/query_test.go
- http/legacy/write_handler.go
We previously enabled write tokens to also find DBRP buckets, in order to allow
the legacy /write (not /api/v2/write) endpoint to read the DBRP mappings and
find the real bucket id to write to.
This had the unintended consequency of allowing tokens with only write permissions
to read data in buckets via the legacy /query (not /api/v2/query) endpoint with
InfluxQL.
This change fixes the behaviour to allow writing to /write with a write-only
token, while forbidding reading from /query.
Closes #23110
> fix: forbid reading OSS buckets for a token with only write permissions

- cmd/influxd/upgrade/database.go
Closes #23041 
Small changes to influxd upgrade logging - changes log level for DBRP mapping creation to info level rather than debug, and includes the sourcePath in the warning log message if no data/shards are found in a particular 1.x database. This will make it clear by default which databases/retention policies have been migrated to 2.x and which have not.
> refactor: improve logging during `influxd upgrade` 

- .circleci/config.yml
- scripts/ci/run-monitor-ci-tests.bash
Partial #https://github.com/influxdata/ui/issues/3565
* When making changes in quartz-mock PR, incorporate CI tests including e2e with UI.
* Make it such that bad mock bad (in quartz-mock), does not break our CI pipeline.
* This included updates for our monitor-ci pipeline (making it a bit cleaner)...which is why this PR in oss exists.
* explicitly set the workflow enum which is run.
* update the `run-monitor-ci-tests.bash` to match the updated script in monitor-ci.
* note: removed the other workflows which are not oss.
* note to @wbaker85 the updated script, for embedded UI, uses `UI_SHA` (not `SHA`)
* tested by running against the monitor-ci branch (which has all the updates).
* temp commit: https://github.com/influxdata/influxdb/pull/23169/commits/694ce3aa3dd79b1c2b6001d3e55e3a3f07707f1 …
> chore: update OSS ci pipeline to match the updates to monitor-ci

- cmd/influxd/launcher/launcher.go
- cmd/influxd/launcher/replication_test.go
- query/stdlib/influxdata/influxdb/provider.go
- replications/service.go
Fixes a few issues:
* flux needs to write to the replication service, instead of the engine directly.
* the replication service incorrectly had value receiver methods, I think this
was just an accident. Pointer receivers make things easier to reason about. Also
with value receivers flux was not picking up the replication config properly.
* The flux to() function previously did not receive the org properly for internal
writes. Previously this was not necessary as the write path only needs the bucket
ID at this level (after authentication). But now we need the org id to look up
replications properly.
Closes #23183
> fix: replications replicates flux to() writes

- tsdb/shard.go
- tsdb/shard_test.go
When migrating users from OSS/Enterprise to Cloud2, we have run into issues with series having different types on different shards. In cloud2, this causes a type collision and we end up dropping a lot of the data. To prevent this, we'd like to get information about any type collisions up front and we have the "fields.idx" files available to us, which we would like to read.
This PR introduces a new method to help us read these files, and get a list of all measurement names. This will not impact the running of the service at all, but will allow us to import this into the tooling that we are building around the migration process.
> feat: Add MeasurementNames method to MeasurementFieldSet

- query/stdlib/influxdata/influxdb/dependencies.go
The `DefaultDependencies` behaviour is for flux http requests failed silently after 100MB of data transfer, which seems wrong.
> fix: allow flux http calls to be unlimited

- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- pkger/http_server_template.go
- pkger/http_server_template_test.go
- pkger/parser.go
- pkger/service.go
- query/stdlib/influxdata/influxdb/dependencies.go
- task/backend/analytical_storage_test.go
Flux HTTP and template fetching requests do not perform IP address checks for local addresses. This behavior on the one hand allows SSRF (Server Side Request Forgery) attacks via authenticated requests but on the other hand is useful for scenarios that have legitimate requirements to fetch from private addresses (eg, hosting templates internally or performing flux queries to local resources during development.
To not break existing installations, the default behavior will remain the same but a new `--hardening-enabled` option is added to influxd turn on IP address verification and limit both flux and template fetching HTTP requests to non-private addresses. We plan to enable new security features that aren't suitable for the default install with this option. Put another way, this new …
> feat: add --hardening-enabled option to limit flux/pkger HTTP requests

- services/subscriber/service.go
When creating a subscription, return the wrapped error
on failure
closes https://github.com/influxdata/influxdb/issues/23216
> fix: return underlying error creating a subscription

- services/subscriber/service.go
When creating a subscription, return the wrapped error
on failure
closes https://github.com/influxdata/influxdb/issues/23216
(cherry picked from commit c3a958cb5f09ab0cc9a792394ea13d5702399305)
Closes https://github.com/influxdata/influxdb/issues/23220
> fix: return underlying error creating a subscription (#23217)

- testing/util.go
- v1/coordinator/statement_executor.go
- v1/coordinator/statement_executor_test.go
We previously allowed read tokens access to all of v1 query, including
InfluxQL queries that made state changes to the DB, specifically,
'DELETE' and 'DROP MEASUREMENT'. This allowed tokens with only read
permissions to delete points via the legacy /query endpoint.
/api/v2/query was unaffected.
This adjusts the behavior to verify that the token has write permissions
when specifying 'DELETE' and 'DROP MEASUREMENT' InfluxQL queries. We
follow the same pattern as other existing v1 failure scenarios and
instead of failing hard with 401, we use ectx.Send() to send an error to
the user (with 200 status):
{"results":[{"statement_id":0,"error":"insufficient permissions"}]}
Returning in this manner is consistent with Cloud 2, which also returns
200 with "insufficient permissions" for these two …
> fix: add write permissions check for DELETE and DROP MEASUREMENT

- models/points.go
- models/points_test.go
A preallocated slice needs to be cleared to be used with append,
otherwise the existing elements will be seen in the result and this does
not appear to be the intention. The bug doesn't seem to have caused
issues as no callsites use a preallocated slice.
Closes #
> fix(models): reset provided slice correctly

- cmd/influxd/launcher/replication_test.go
- go.mod
- go.sum
- replication.go
- replications/internal/queue_management.go
- replications/internal/queue_management_test.go
- replications/internal/store.go
- replications/internal/store_test.go
- replications/mock/http_config_store.go
- replications/mock/queue_management.go
- replications/remotewrite/writer.go
- replications/remotewrite/writer_test.go
- replications/service.go
- replications/service_test.go
- sqlite/migrations/0005_create_replications_table.up.sql
Closes #23109 
Introduces a maximum age for replications so that data can be timed out and dropped (configurable).
A value of `0` means that there is no time-out.
> feat: add maximum age to replication queues

- scripts/fetch-ui-assets.sh
fix: pin UI version to 2.1.2 so that tokens can be accessed.
Closes #23235
> fix: pin UI to OSS-2.1.2 so tokens can be accessed

- internal/storage_store.go
- services/httpd/handler.go
- services/httpd/handler_test.go
- services/storage/store.go
Support to V2 delete api
Does not support deletion by field, only by tag value, time, and measurement.
> fix: implement v2/api/delete

- .circleci/config.yml
- Upgrades Go 1.18 -> 1.18.1
- Upgrades Rust 1.53 -> 1.58.1
- Fixes an issue with OSXCross and Darwin builds. This results in the new minimum OSX version being `MacOSX10.14`/`darwin18`
> build: upgrade to Go 1.18.1

- cmd/influx_inspect/export/export.go
> fix(influx_inspect): multiple retention policies problem in influx_inspect export

- services/httpd/handler.go
abort processing write request when encountering a precision error.
Reproducing: 
```bash
curl -X POST http://localhost:8086/write?db=1&rp=2&precision=aa
```
Expect: 
```json
{"error":"invalid precision \"aa\" (use n, u, ms, s, m or h)"}
```
Got: 
```json
{"error":"invalid precision \"aa\" (use n, u, ms, s, m or h)"}
{"error":"database not found: \"1\""}
```
> fix(httpd): abort processing write request when encountering a precision error.

- query/control/controller.go
I understand 32-bit architectures are no longer officially supported, but this is a minor change.
Calling `atomic.AddUint64()` on `lastID` resulted in an alignment panic in armv7, due to it not being 64bit aligned.
Declaring it first in the struct solved it.
See https://pkg.go.dev/sync/atomic#pkg-note-BUG fore more details
> fix: remove controller 64bit misalignment

- tsdb/store.go
- tsdb/store_test.go
Clamp the value of Store.MeasurementsCardinality so that it can not be less
than 0. This primarily shows up as a negative `numMeasurements` value in
/debug/vars under some circumstances.
Closes #23285
> fix: MeasurementsCardinality should not be less than 0

- internal/storage_store.go
- services/httpd/handler.go
- services/httpd/handler_test.go
- services/meta/query_authorizer.go
- services/storage/store.go
Partial support for V2 API buckets endpoints
create, delete, list, and retrieve
This PR partially implements the /v2/api/buckets
POST for create a bucket
DELETE for deleting a bucket
GET for listing buckets
GET for retrieving one bucket
See here for details:
https://docs.influxdata.com/influxdb/cloud/api/#tag/Buckets
> feat: partial /v2/api/buckets support: create, delete, list, retrieve

- services/httpd/handler.go
- services/httpd/handler_test.go
Stub out unsupported /api/V2/buckets endpoints. 
Minor refactoring of other /api/v2/buckets code without functional changes.
> feat: stub out bucket members, owners, and labels

- flux/stdlib/influxdata/influxdb/dependencies.go
This is to prevent the following error
```
/ # cat broke.flux 
import "types"
host="http://127.0.0.1:8086"
token="myuser:mypass"
from(bucket: "vehicle_communication/30days", host: host, token: token)
|> range(start: -1h)
|> filter(fn: (r) => types.isType(v: r["_value"], type: "int"))
|> aggregateWindow(every: 1m, fn: mean)
/ # cat broke.flux | /influx -username influx_support -type flux -password <pass>
{"error":"failed to initialize execute state: Provider.ReaderFor called on an error dependency"}
```
> fix(flux): inject sane defaults for flux, to prevent an error

- flux/stdlib/influxdata/influxdb/dependencies.go
This is a cherry-pick to fix a couple bugs:
One is where the query results are too large and get cut off.  The other is to prevent the following error.
This is to prevent the following error
```
/ # cat broke.flux 
import "types"
host="http://127.0.0.1:8086"
token="myuser:mypass"
from(bucket: "vehicle_communication/30days", host: host, token: token)
|> range(start: -1h)
|> filter(fn: (r) => types.isType(v: r["_value"], type: "int"))
|> aggregateWindow(every: 1m, fn: mean)
/ # cat broke.flux | /influx -username influx_support -type flux -password <pass>
{"error":"failed to initialize execute state: Provider.ReaderFor called on an error dependency"}
````
> fix(flux): inject sane defaults dependency for flux (#23309)

- cmd/influxd/run/server.go
Log long-running queries if "log-queries-after" > 0,
even if general query logging is not enabled.
closes https://github.com/influxdata/influxdb/issues/23147
> feat: log slow queries even without query logging

- cmd/influxd/run/server.go
Log long-running queries if "log-queries-after" > 0,
even if general query logging is not enabled.
closes https://github.com/influxdata/influxdb/issues/23147
(cherry picked from commit 1c89102276ba861f5dde3428e574118715a8d3e6)
Closes https://github.com/influxdata/influxdb/issues/23337
> feat: log slow queries even without query logging (#23320)

- cmd/influx_inspect/verify/tsm/verify.go
This removes the line that appends "/data" to the given -dir path for `influx_inspect verify`.
Since the `loadFiles` method uses `filepath.Walk`, TSM files in a /data directory will still be checked, as well as other any other TSM files in the root directory or its subdirectories.
Closes #22572
> fix: remove data directory appending for influx_inspect verify

- tsdb/shard.go
- tsdb/shard_internal_test.go
Replace unprintable and invalid characters with '?'
in logged errors.  Truncate consecutive runs of them to
only 3 repeats of '?'
closes https://github.com/influxdata/influxdb/issues/23386
> fix: replace unprintable and invalid characters in errors

- tsdb/shard.go
- tsdb/shard_internal_test.go
Replace unprintable and invalid characters with '?'
in logged errors.  Truncate consecutive runs of them to
only 3 repeats of '?'
closes https://github.com/influxdata/influxdb/issues/23386
(cherry picked from commit 0ae0bd6e2eb6eeeb97b67bc8c96ad6b158ce28f5)
Closes https://github.com/influxdata/influxdb/issues/23391
> fix: replace unprintable and invalid characters in errors (#23387)

- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/file_store_internal_test.go
- tsdb/engine/tsm1/file_store_test.go
- tsdb/engine/tsm1/reader.go
If NewTSMReader() fails because mmap fails, do not
rename the file, because the error is probably
caused by vm.max_map_count being too low
closes https://github.com/influxdata/influxdb/issues/23172
> fix: do not rename files on mmap failure

- .circleci/config.yml
Upgrade 1.9 to Go 1.17.11 (latest 1.17 version)
> build: upgrade to Go 1.17.11

- .circleci/config.yml
Upgrades 1.10 to Go 1.18.3 (latest)
> build: upgrade to Go 1.18.3

- tsdb/engine/tsm1/engine.go
- tsdb/engine/tsm1/file_store.go
- tsdb/engine/tsm1/file_store_internal_test.go
- tsdb/engine/tsm1/file_store_test.go
- tsdb/engine/tsm1/reader.go
If NewTSMReader() fails because mmap fails, do not
rename the file, because the error is probably
caused by vm.max_map_count being too low
closes https://github.com/influxdata/influxdb/issues/23172
(cherry picked from commit ec412f793b0fbb0d4c1ee35ebbb1fbbc69baabf0)
closes https://github.com/influxdata/influxdb/issues/23413
> fix: do not rename files on mmap failure (#23396)

- cmd/influx_inspect/cardinality/aggregators/aggregators.go
- cmd/influx_inspect/cardinality/aggregators/aggregators_test.go
- cmd/influx_inspect/cardinality/cardinality.go
- cmd/influx_inspect/help/help.go
- cmd/influx_inspect/main.go
- cmd/influx_inspect/report/report.go
- go.mod
- go.sum
feat: estimate Cloud2 cardinality on 1.X databases
To ease migrations to Cloud 2 installations from
1.X databases, estimate Cloud 2 cardinality for
a data node (or OSS system).
closes https://github.com/influxdata/influxdb/issues/23356
(cherry picked from commit ef90bc830f6fc085062c2e827ef1fb015f1a1b6d)
closes https://github.com/influxdata/influxdb/issues/23416
> feat: estimate Cloud2 cardinality on 1.X databases (#23351)

- coordinator/points_writer.go
- tsdb/store.go
- tsdb/store_test.go
If a shard cannot be opened store its ID and last error.
Prevent future attempts to open during this invocation of
influxDB. This information is not persisted, however.
partial close of https://github.com/influxdata/influxdb/issues/23428
closes https://github.com/influxdata/influxdb/issues/23426
> fix: remember shards that fail Open(), avoid repeated attempts

- cmd/influxd/run/command.go
Always log the log level so we know if there's no logs because of the log level.
(cherry picked from commit febf7a927cfe543194ce0e797d7146da589a87bf)
> feat: log the log level regardless of log level (#23425)

- coordinator/points_writer.go
- tsdb/store.go
- tsdb/store_test.go
If a shard cannot be opened, store its ID and last error.
Prevent future attempts to open during this invocation of
influxDB. This information is not persisted.
closes https://github.com/influxdata/influxdb/issues/23428
closes https://github.com/influxdata/influxdb/issues/23426
(cherry picked from commit 54ac7e54edbbb8a495d5b1be626a21b0165fb77e)
closes https://github.com/influxdata/influxdb/issues/23433
closes https://github.com/influxdata/influxdb/issues/23435
> fix: remember shards that fail Open(), avoid repeated attempts (#23437)

- go.mod
- go.sum
- pkg/mmap/mmap_unix.go
- tsdb/index/tsi1/file_set.go
- tsdb/index/tsi1/index.go
- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/partition.go
When one partition in a TSI fails to open, all previously opened
partitions should be cleaned up, and remaining partitions
should not be opened
closes https://github.com/influxdata/influxdb/issues/23427
(cherry picked from commit d3db48e93d561c0125d6a1fab146fd0ded20fedc)
closes https://github.com/influxdata/influxdb/issues/23432
> fix: fully clean up partially opened TSI (#23430)

- .circleci/config.yml
Add the newly supported `GRACE_VALIDATE_OPENAPI` environment variable to support the tests.
Also use a shared `latest-cd` container, instead of the `daily` container for grace.
> test: add openapi spec validation to OSS grace tests

- cmd/influxd/launcher/cmd.go
- cmd/influxd/launcher/launcher.go
- replications/service.go
- replications/service_test.go
Closes #23360 
This flag identifies edge nodes during replication and prevents collisions if 2 edge nodes write the same measurement,tagset
> feat: add instance-id flag for identifying edge nodes

- cmd/influxd/launcher/replication_test.go
- replications/internal/queue_management.go
- replications/internal/queue_management_test.go
- replications/remotewrite/writer.go
- replications/remotewrite/writer_test.go
Closes #23397
Fixes an issue where we could get stuck on a `time.Timer#C` channel listen. If we had multiple remote write failures in a row, we would end up in a situation where the `retry.C` channel was just drained, then we call `retry.Stop()`, followed by `<-retry.C`, which would deadlock the goroutine responsible for sending remote writes.
Additionally, this PR adds several new test cases, and refactors the `remoteWriter` interface to no longer return `shouldRetry`, since it was unnecessary and unused.
> fix: replications remote write failure can deadlock remote writer

- .gitignore
- bolt/bbolt.go
- bolt/metrics.go
- bolt/metrics_test.go
- cmd/influxd/launcher/launcher.go
- kv/migration/all/0020_add_remotes_replications_metrics_buckets.go
- kv/migration/all/all.go
- prometheus/filter.go
- remotes/transport/http.go
- remotes/transport/middleware_kv.go
- remotes/transport/middleware_kv_test.go
- replications/transport/http.go
- replications/transport/middleware_kv.go
- replications/transport/middleware_kv_test.go
- telemetry/metrics.go
Closes #23372
The number of remotes and replications are now reported with telemetry.
> feat: Add remotes and replications to telemetry

- tsdb/index/tsi1/index.go
(cherry picked from commit 8bd4fc502d12a0e2ece10eb86e64832646640cda)
closes https://github.com/influxdata/influxdb/issues/23460
> fix: lost TSI reference / close TagValueSeriesIDIterator in error case (#23461)

- monitor/service.go
> fix: eliminate race condition on Monitor.globalTags

- cmd/influxd/launcher/launcher.go
Unlike the changes for 1.x, only log the log level if we are at 'info' level. We'll know we're not at 'info' if there is no `Welcome to InfluxDB` log line.
> fix: log the log level at startup

- .circleci/config.yml
- .circleci/scripts/build-package
- .circleci/scripts/get-version
This changes the package names so that they are compatible with other scripts. It also ensures that the version is correct when generating releases.
> build: fix release workflow for 2.3

- .circleci/scripts/build-package
The original code emitted `.tar.gz` archives for Windows. This updates it so it instead emits `.zip` archives.
> fix: emit zipfile for windows

- go.mod
- go.sum
Last flux version before change of test harness
> chore: update flux to 0.170.1

- .circleci/config.yml
- scripts/ci/CHANGELOG_frozen.md
This also regenerates CHANGELOG_frozen.md (from version 1.8.0 - 1.9.7)
so that it is compatible with the new changelogger.
> feat: use new changelogger (1.x)

- .circleci/config.yml
- scripts/ci/CHANGELOG_frozen.md
This also regenerates CHANGELOG_frozen.md (from version 1.8.0 - 1.9.7)
so that it is compatible with the new changelogger.
> feat: use new changelogger (1.9)

- .circleci/config.yml
- scripts/ci/CHANGELOG_frozen.md
This also regenerates CHANGELOG_frozen.md (from version 1.8.0 - 1.9.7)
so that it is compatible with the new changelogger.
> feat: use new changelogger (1.10)

- query/stdlib/influxdata/influxdb/filter_test.flux
- storage/reads/array_cursor.gen.go
- storage/reads/array_cursor.gen.go.tmpl
Filters that contain `or` may change between cursor resets so we must remember to update the condition in the read cursor.
```flux
|> filter(fn: (r) => ((r["_field"] == "field1" and r["_value"]==true) or (r["_field"] == "field2" and r["_value"] == false)))
```
Closes https://github.com/influxdata/flux/issues/4804
n be erased if not applicable to your Pull Request. -->
> fix: Update the condition when reseting cursor

- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/partition.go
- tsdb/index/tsi1/partition_test.go
Where possible, add the file path path to any errors
on opening, reading, (un)marshaling, or validating
the various files comprising a partition
closes https://github.com/influxdata/influxdb/issues/23506
> fix: improve error messages opening index partitions

- label/storage_test.go
Whilst working on cloud labels, I noticed that the label storage test
isn't correctly capturing the testScenario. This is because t.Parallel()
is in use, so only the "delete" scenario will only ever be tested.
The following changes fix that, by capturing the testScenario in a local
variable so that the test function can use that correctly.
As a drive-by, I fixed the error referencing the wrong expectation.
Closes #23352
> test(label): Invalid closure capture

- tsdb/index/tsi1/partition.go
When a MANIFEST file is created in TSI, it
should be written to a temp file, then
atomically renamed, to avoid overwriting
the existing file only to fail on the
later write.
closes https://github.com/influxdata/influxdb/issues/23536
> fix: create TSI MANIFEST files atomically

- tsdb/index/tsi1/index_test.go
- tsdb/index/tsi1/partition.go
- tsdb/index/tsi1/partition_test.go
Where possible, add the file path path to any errors
on opening, reading, (un)marshaling, or validating
the various files comprising a partition
closes https://github.com/influxdata/influxdb/issues/23506
(cherry picked from commit a2dd708a264202995d1437cb29ccaa24577ab060)
closes https://github.com/influxdata/influxdb/issues/23534
> fix: improve error messages opening index partitions (#23532)
