influxdata/influxdb

cmd/influx_inspect/help/help.go

`reporttsi` was not listed as a command in the `influx_inspect` help text.  Now it is.

fix: add reporttsi to the help text

---

.circleci/config.yml

It appears that the Mac OSX image we were using was deprecated by CircleCI.

chore: upgrade CircleCI Mac OSX image

---

models/points_test.go
tsdb/index/tsi1/index_file.go
tsdb/index/tsi1/index_test.go
tsdb/index/tsi1/log_file.go

Add paths to various TSI errors on opening and unmarshaling files
to help pinpoint the corrupt files.
Closes https://github.com/influxdata/influxdb/issues/23556
(cherry picked from commit 25cea95beb4fa050d58062cfffd13669b1bb17e2)
closes https://github.com/influxdata/influxdb/issues/23558

fix: add paths to tsi log and index file errors (#23557)

---

.circleci/config.yml

This upgrades Go to 1.18.4 to resolve security vulnerabilities within the compiler.

build: upgrade to Go 1.18.4 (master-1.x)

---

.circleci/config.yml

This upgrades Go to 1.18.4 to resolve security vulnerabilities within the compiler.

build: upgrade to Go 1.18.4 (1.10)

---

.circleci/config.yml

This upgrades Go to 1.17.12 to resolve security vulnerabilities within the compiler.

build: upgrade to Go 1.17.12 (1.9)

---

.circleci/config.yml

This upgrades Go to 1.18.4 to resolve security vulnerabilities within the compiler.

build: upgrade to Go 1.18.4 (2.3)

---

tsdb/index/tsi1/index.go
tsdb/index/tsi1/partition.go
tsdb/index/tsi1/partition_test.go

Do not update the `FileSet` or `activeLogFile` field in the in-memory 
Partition structure if the Manifest file is not correctly saved to
the disk.
closes https://github.com/influxdata/influxdb/issues/23553

fix: restore in-memory Manifest on write error

---

cmd/influx_inspect/help/help.go

reporttsi was not listed as a command in the influx_inspect help text.
(cherry picked from commit 5c22d6c729ac59acbccc6a7f431ddaa8090d8bf2)
closes https://github.com/influxdata/influxdb/issues/23567

fix: add reporttsi to the help text (#23566)

---

tsdb/index/tsi1/partition.go

When a MANIFEST file is created in TSI, it
should be written to a temp file, then
atomically renamed, to avoid overwriting
the existing file only to fail on the
later write.
closes https://github.com/influxdata/influxdb/issues/23536
(cherry picked from commit 061cf55f2ac6c918b219d15e659bd51416d1c52b)
closes https://github.com/influxdata/influxdb/issues/23537

fix: create TSI MANIFEST files atomically (#23539)

---

tsdb/index/tsi1/index.go
tsdb/index/tsi1/partition.go
tsdb/index/tsi1/partition_test.go

Do not update the `FileSet` or `activeLogFile` field in the in-memory
Partition structure if the Manifest file is not correctly saved to
the disk.
closes https://github.com/influxdata/influxdb/issues/23553
(cherry picked from commit a8732dcf524053c972fcfabb38f528e7ef3eba5a)
closes https://github.com/influxdata/influxdb/issues/23555

fix: restore in-memory Manifest on write error (#23552)

---

tsdb/index/tsi1/partition.go
tsdb/index/tsi1/partition_test.go

Also eliminate race condition in tests of Partitions
(cherry picked from commit 7e37a7ad1610771409d9b651a775f3a4ab4352ed)

fix: generalize test for Windows

---

tsdb/index/tsi1/partition.go
tsdb/index/tsi1/partition_test.go

Also eliminate race condition in tests
(cherry picked from commit 7e37a7ad1610771409d9b651a775f3a4ab4352ed)
(cherry picked from commit eb3cc887724a9b897d28affff3e27c1f2130f92d)

fix: generalize test for Windows (#23580)

---

query/stdlib/influxdata/influxdb/rules.go
query/stdlib/influxdata/influxdb/rules_test.go

The flux native aggregate window, which is now on by default, creates a new
procedure spec. We need to teach it how to convert this native aggregate window
to the appropriate push down to ensure we still use the push down when
appropriate.
See above.
Just required for the new flux version.
- Check the PR title: we should be able to put this as a one-liner in the …

feat(query): add planner rule for converting aggregate window to a push down

---

remotes/transport/http.go
sqlite/migrations/0006_migrate_replications_foreign_key.down.sql
sqlite/migrations/0006_migrate_replications_foreign_key.up.sql

Closes #23491 
Fixes the above issue by no longer cascade deleting replication configs when the remote foreign key is deleted. Instead we return an error, requiring the user to delete the replication themselves first. This should "fix" the issue by not letting that situation happen. Additionally, this means that the user will not accidentally delete their replications by deleting a remote, and potentially losing data in the queue.

fix: do not delete replication on remote config delete

---

dbrp/http_server_dbrp_test.go
dbrp/service.go
dbrp/service_test.go
dbrp_mapping.go
influxql/v1tests/query_test.go
testing/dbrp_mapping.go

- Closes #23457
Originally, I worked on #23525 to create and update physical DBRP mappings in the bucket service wrapper. This solution meant more state needed to be preserved, required a migration, etc. Virtual mappings, on the other hand, are not written on disk (corruptible), would be changed by a bucket name change implicitly, and overall made much more sense with less code.
This makes it so users don't have to create a custom DBRP mapping every time they create a bucket.
- API changes: `DBRPMapping` gained a `Virtual` field -  https://github.com/influxdata/openapi/pull/462
- CLI commands: `influx v1 dbrp list` prints a new `Virtual` column - https://github.com/influxdata/influx-cli/pull/435

feat: add virtual DBRP mappings based on bucket name

---

cmd/influx_inspect/help/help.go
cmd/influx_inspect/main.go
cmd/influx_inspect/type_conflicts/resolve_conflicts.go
cmd/influx_inspect/type_conflicts/schema.go
cmd/influx_inspect/type_conflicts/schema_test.go
cmd/influx_inspect/type_conflicts/type_conflicts.go
tsdb/shard.go

adds two commands, `check-schema` and
`merge-schema`, to `influx_inspect`.
These test for field type conflicts
in all fields.idx beneath a directory
and merge the derived schemas if
"check-schema" has been run multiple
times on different directories
- `influx_inspect check-schema -path <data directory> -schema-file <schema output file> -conflicts-file <conflicts output file>`
- `influx_inspect merge-schema  schema-file <schema output file> -conflicts-file <conflicts output file>`
Defaults
- path: `.`
- schema-file: `schema.json`
- conflicts-file: `conflicts.json`

feat: add type conflict checker to influx_inspect

---

.circleci/scripts/sign-packages

The original code used the 2.x signing key for 1.x releases.

chore: use 1.x signing key (1.x)

---

.circleci/scripts/sign-packages

The original code used the 2.x signing key for 1.x releases.

chore: use 1.x signing key (1.10)

---

.circleci/scripts/sign-packages

The original code used the 2.x signing key for 1.x releases.

chore: use 1.x signing key (1.9)

---

cmd/influx_inspect/help/help.go
cmd/influx_inspect/main.go
cmd/influx_inspect/type_conflicts/resolve_conflicts.go
cmd/influx_inspect/type_conflicts/schema.go
cmd/influx_inspect/type_conflicts/schema_test.go
cmd/influx_inspect/type_conflicts/type_conflicts.go
tsdb/shard.go

adds two commands "check-schema" and
"merge-schema" to influx_inspect.
These test for field type conflicts
in all fields.idx beneath a directory
and merges the derived schemas if
"check-schema" has been run multiple
times on different directories
(cherry picked from commit 84c4f676b040ce8d197977c99a82e6566d4096ce)
Port of https://github.com/influxdata/influxdb/pull/23616 
Doc:
https://github.com/influxdata/docs-v2/issues/4324

feat: add type conflict checker to influx_inspect (#23616)

---

.circleci/config.yml
scripts/ci/build-tests.sh
scripts/ci/build.sh

feat: enable static-pie builds (2.x)

---

.circleci/config.yml
scripts/ci/build-tests.sh
scripts/ci/build.sh

feat: enable static-pie builds (2.3)

---

dbrp/service.go
testing/dbrp_mapping.go

This improves the virtual DBRP default handling. 
- **Before:** a virtual DBRP would be default unless there was another DBRP already set to default for a given _bucket_. 
- **Now:** a virtual DBRP is default if all of these are true:
-  The database name has no slashes. cc @lesam 
(a bucket named `foo` has a default DBRP of `foo`/`autogen`, but a bucket named `foo/bar` would not be default)
- There is no DBRP, physical or virtual, that is default with the same _database name_ for a given bucket.

fix: improve virtual DBRP default handling

---

.circleci/config.yml
cmd/influxd/inspect/dump_tsm/dump_tsm.go
go.mod
go.sum
kv/migration/create.go
pkger/parser_models.go
scripts/ci/build-tests.sh
scripts/ci/build.sh
task/backend/scheduler/scheduler_test.go
v1/services/meta/data.go

feat: enable static-pie builds (2.2)

---

etc/test-flux.sh

Update the skiplist for the various scripts and CI jobs that run flux integration tests.
https://github.com/influxdata/flux/pull/5103 removed the `skip` tag from tests that were passing with `flux test`. If a test was failing using the influxdb fluxtest harness, it was added to the skiplist in this patch.

chore: update fluxtest skip list

---

cmd/influxd/downgrade/downgrade.go
replication.go
replications/internal/store.go
replications/internal/store_test.go
replications/remotewrite/writer.go
replications/service.go
replications/service_test.go
replications/transport/http_test.go
sqlite/migrations/0007_migrate_replications_add_bucket_name.down.sql
sqlite/migrations/0007_migrate_replications_add_bucket_name.up.sql

- This adds compatibility with 1.x replication targets
- Closes #23550
Replications now support using a bucket name instead of a bucket id. This will allow replications to a 1.x instance.
The main value in this addition is full compatibility with replicating to enterprise 1.x instances.
CLI change (add --replication-bucket flag) https://github.com/influxdata/influx-cli/pull/440
API change (add replicationBucketName to several replication routes) https://github.com/influxdata/openapi/pull/478
- Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except …

feat: replicate based on bucket name rather than id

---

.circleci/config.yml

feat: enable static-pie builds (1.10)

---

.circleci/config.yml

feat: enable static-pie builds (1.9)

---

.circleci/config.yml

feat: enable static-pie builds (1.x)

---

http/query_test.go
http/source_service.go

It appears to be dead and not used anymore.
It's removing some dead code that I want to refactor in the flux library
itself.
Should affect nothing.

refactor: remove reference to flux.Spec in query tests

---

sqlite/migrator_test.go

This fixes an occurrence of a loop variable being captured in a
parallel test. With the previous code, only the last test case is
actually exercised. To work around this problem, we create a local
copy of the range variable before the parallel test, as suggested in
the Go documentation for the `testing` package:
https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks
Issue was found automatically using the `loopvarcapture` linter.
- Build: build script changes, CI …

fix: use copy of loop variable in parallel test

---

releng/protoc-gen

chore: add protoc-gen script to releng (1.10)

---

releng/protoc-gen

chore: add protoc-gen script to releng (1.x)

---

releng/protoc-gen

chore: add protoc-gen script to releng (1.9)

---

tenant/error_user.go
tenant/storage_user.go
tenant/storage_user_test.go

- Closes https://github.com/influxdata/edge/issues/292
- Providing an already in-use user ID to `api/v2/users` create will now be an error, which is a behavior change. However docs do not seem to need an update from this

fix: check that user IDs are not in use in user create

---

authorization/middleware_auth.go

- Closes #23668
Fail earlier and with a better error message when trying to create an auth with instance type.

fix: don't allow creating an auth with instance resources

---

.circleci/package/control/postinst
.circleci/package/fs/usr/lib/influxdb/scripts/influxdb.service
.circleci/scripts/build-package

- Closes https://github.com/influxdata/edge/issues/294
Tightens permissions on the default install directory.
This is follows best practices around access controls.

fix: set limited permissions on package installs

---

.circleci/config.yml
releng/protoc-gen

chore: add protoc-gen script to releng (2.4)

---

.circleci/config.yml
releng/protoc-gen

chore: add protoc-gen script to releng (2.x)

---

.circleci/config.yml
releng/protoc-gen

chore: add protoc-gen script to releng (2.3)

---

tsdb/shard.go

One line move in an error message concatenation.  Caught by `lint` in the master branch.

fix: incorrect error message concatenation

---

kit/transport/http/middleware.go
session/http_server.go
session/http_server_test.go

Use `SameSite=Strict` as a hardening measure against cross-origin attacks. While browsers have been moving to default to `SameSite=Lax`, explicitly setting `SameSite` ensures that all browsers enforce it consistently. While `lax` is a reasonable hardening choice, the cookie is only required for requests to `/api/...` and we don't expect 3rd party links into `/api/...`, so this stricter setting should be safe in terms of usability. Furthermore, while our `GET` APIs are not state-changing, using 'strict' future-proofs us in case we add a state-changing `GET` API (`lax` allows cross-origin `GET` requests for increased usability for read-only requests).
Also add a comment to `SetCORS()` lack of `Access-Control-Allow-Credentials` as a reminder that its omission is intentional for defense in …

feat(security): set SameSite=strict on session cookie

---

backup/backup.go
tenant/storage_bucket.go
tenant/storage_bucket_test.go
tenant/storage_org.go
tenant/storage_org_test.go
tenant/storage_user.go
tenant/storage_user_test.go

Fixes an issue where backups were only limited to the first 20 buckets. These changes will allow backup of all buckets.
This should help with potential data loss during backup/restore.

fix: allow backup of all buckets

---

etc/test-flux.sh
query/stdlib/influxdata/influxdb/group_first_last_influxdb_test.flux

Refs: 
- https://github.com/influxdata/flux/pull/5172
- https://github.com/influxdata/influxdb/issues/23757
In https://github.com/influxdata/flux/pull/5172 various tests which have been skipped long-term were repaired. This diff removes them from the skip list during the flux integration tests run as a part of CI here.
Some tests had a **sort** added so they'd pass in cloud, vanilla, and OSS.
This also **broke some extended testcases** here in OSS since pushdown rules
no longer match the plan.
This diff "inlines" the testcase body for each of these so we get our
coverage back, but leaves a `FIXME` to note that it would be better if we
could somehow thread the needle and retain the extension.
Adds additional coverage to the flux integration tests.
CI, specifically test selection for …

test: remove group skips

---

pkg/file/file_unix.go

When a file rename fails with EXDEV
(cross device or volume error), copy the
file and delete the original instead
Differs from master branch by overwriting
existing files instead of erring.
closes https://github.com/influxdata/influxdb/issues/22997

fix: use copy when a rename spans volumes

---

pkg/file/file.go
pkg/file/file_test.go
pkg/file/file_unix.go
pkg/file/file_windows.go

Add tests for https://github.com/influxdata/influxdb/issues/22997

fix: add tests for file rename across volumes

---

pkg/file/file.go
pkg/file/file_test.go
pkg/file/file_unix.go
pkg/file/file_windows.go

When a file rename fails with EXDEV
(cross device or volume error), copy the
file and delete the original instead
Differs from master branch by overwriting
existing files instead of erring.
closes https://github.com/influxdata/influxdb/issues/22997
(cherry picked from commit 0913276ff0f33d1639a14cb49c971772232b5af3)
- fix: add tests for file rename across volumes (https://github.com/influxdata/influxdb/pull/23787)
Also move shared code from file_unix.go
(cherry picked from commit https://github.com/influxdata/influxdb/commit/bc8d9ea9f33b964ada77a9057a603255f13eeb59)
closes https://github.com/influxdata/influxdb/issues/23791

fix: use copy when a rename spans volumes (#23785)

---

cmd/influxd/launcher/launcher.go
kv/task.go
task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go
task/backend/coordinator/support_test.go
task/backend/executor/executor.go
task/mock/executor.go

- Closes #23545
When creating a manual run of a task with a `scheduledFor` time, it was executing immediately rather than at that time. This fixes that behavior.
This brings it in line with Cloud2 behavior as well as operating as a user would expect.

fix: manually scheduled task runs now run when expected

---

cmd/influxd/launcher/engine.go
delete.go
http/delete_handler.go
http/delete_test.go
mock/delete.go
storage/engine.go
tsdb/store.go
tsdb/store_test.go

- Closes #23741
The current delete statement does not take into account the measurement predicate. It will blindly loop through all the measurements in each shard and run the delete. This can be very slow on instances with a lot of measurements. This change checks for measurement existence, and if found, only runs the delete on that measurement.
The value add is faster deletes that have a measurement predicate.
- Build: build script changes, CI config changes, build …

fix: improve delete speed when a measurement is part of the predicate

---

.circleci/config.yml

CircleCI is removing "cron" workflows later this year. This preemptively switches to scheduled pipelines as to not introduce downtime when "cron" is removed.

chore: update to use scheduled pipeline (1.x)

---

.circleci/config.yml

CircleCI is removing "cron" workflows later this year. This preemptively switches to scheduled pipelines as to not introduce downtime when "cron" is removed.

chore: update to use scheduled pipeline (2.x)

---

.circleci/config.yml

CircleCI is removing "cron" workflows later this year. This preemptively switches to scheduled pipelines as to not introduce downtime when "cron" is removed.

chore: update to use scheduled pipeline (2.4)

---

.circleci/config.yml

CircleCI is removing "cron" workflows later this year. This preemptively switches to scheduled pipelines as to not introduce downtime when "cron" is removed.

chore: update to use scheduled pipeline (1.10)

---

services/continuous_querier/service.go

Log errors writing statistics from continuous queries to the `_internal` database `cq_query` measurement.

fix: log errors in continuous query statistics storage

---

services/continuous_querier/service.go

Backport of https://github.com/influxdata/influxdb/pull/23822
(cherry picked from commit bfccddc7b6951895f0acb46c694fe3b5ab0a577f)

fix: log errors in continuous query statistics storage (#23822)

---

cmd/influxd/downgrade/downgrade.go

Downgrading to 2.3 was broken with a "migration not found" error. This should resolve that issue.

fix: downgrading to 2.3 was broken

---

replication.go
replications/internal/store_test.go
replications/remotewrite/writer.go
replications/service.go
replications/service_test.go

- Closes #23769
Fixes sql scan error on replicating data to a 1.x instance. See #23769 for detailed info on the issue and the exact error

fix: sql scan error on remote bucket id when replication to 1.x

---

http/platform_handler.go

- Closes #23805
This PR enables gzip compression on the legacy handler, as it was in influxdb v1.x versions.
The goal is to reduce bandwidth usage when possible.

fix: support gzipped responses in the legacy handler

---

gather/scheduler.go

This is due to the Golang for-loop variable problem.
- Closes #23802
Due to the for-loop variable problem, the scraper request that was pulled off the channel was always the last one in the list of scrapers. See https://github.com/golang/go/discussions/56010 for further explanation. This PR addresses that issue.
- Check the PR title: we should be able to put …

fix: only the latest scraper being run

---

v1/services/storage/store.go

Closes #23073
CreateIterator could return a nil iterator and a nil error. This could lead to several potential panics when trying to type assert the iterator or call methods on it. This should fix those cases.

fix: handle a potential nil iterator leading to a panic

---

.circleci/package/control/postinst
.circleci/package/fs/usr/lib/influxdb/scripts/influxdb.service
.circleci/scripts/build-package

This reverts commit 8d5f0b52f3dde1078d08fbb6ba07f4b4a783ff44.
This addresses the broken RPMs/DEBs that were released in 2.5.0. The intention behind this PR will be readdressed in a later release.
recommend for immediate release.

Revert "fix: set limited permissions on package installs (#23683)"

---

storage/reads/response_writer.gen.go
storage/reads/response_writer.gen.go.tmpl
storage/reads/response_writer.go

Also a performance improvement for when we don't need to write series keys that have no data.
- Closes #23845
#23845
This simplifies the code and reduces allocation work when a large number of series are queried without any data.
None - refactor and performance enhancement

fix: response writer simplification

---

scripts/ci/CHANGELOG_frozen.md

- Closes #
Examples:
API changes
- …

chore: update 2.5 changelog

---

cmd/influx_inspect/export/export.go

This switches so that the message
skipped missing file: /path/to/tsm.tsm
is written to stdErr instead of stdout (or the output file if `-out` has been provided)
Without this change, when TSM or WAL files are missing, the message about them being skipped is written along with the line protocol output, which can lead to difficulties ingesting that LP back into a DB (it can be `sed`'d or `grep`'d out, but that requires additional processing).

fix: don't write skipped shard messages into the line protocol output

---

query/statement_rewriter.go
query/statement_rewriter_test.go
tsdb/shard.go

Use the `_fieldKeys` system iterator
Closes https://github.com/influxdata/influxdb/issues/23840

fix: Optimize SHOW FIELD KEY CARDINALITY

---

cmd/influx_tools/export/command.go
tsdb/shard.go

New argument validation code for `_fieldKeys` system iterator broke Enterprise tests because it is misused all over the place. Back out the safety check.

fix: remove breaking argument validation for _fieldKeys iterator

---

services/httpd/handler.go
services/httpd/handler_test.go

- Closes #23861
GET on /api/v2/buckets  (list buckets) currently returns a JSON array, which is wrong. The response is expected to be a JSON object according to the [InfluxDB 2 swagger](https://github.com/influxdata/openapi/blob/master/contracts/oss.yml#L4140).  
.

fix(1.10): GET /api/v2/buckets properly returns wrapped response

---

services/httpd/handler.go
services/httpd/handler_test.go

closes https://github.com/influxdata/influxdb/issues/23861
(cherry picked from commit e6e0fd2d9c12ea156f380d0a95a766d9bf622fbb)
closes https://github.com/influxdata/influxdb/issues/23883

fix: listBuckets properly returns wrapped response (#23883)

---

services/httpd/handler.go
services/httpd/handler_test.go

- Closes #23889
- Buckets endpoints have a single REST path variable, instead of two.
- POST to `/api/v2/buckets` properly returns 201 and JSON object
- PATCH to `/api/v2/buckets/:dbrp` doesn't rename retention policy and returns JSON object
I hesitated about naming the REST path variable. I left the previous naming `:dbrp`, but it could be `:bucket`

fix(1.10): make buckets API fully compatible

---

replications/internal/queue_management.go

- Closes https://github.com/influxdata/influxdb/issues/23681
Creating a replication stream with maxAgeSeconds (following this guide https://docs.influxdata.com/influxdb/v2.4/write-data/replication/replicate-data/?t=API)
Creates a replication stream with max age in nanoseconds (100_000_000ns = 1s) which makes the maxAgeSeconds=604800 in the docs to be 0.6048ms instead of 168h
Related issue https://github.com/influxdata/influxdb/issues/23681
Converts the maxAgeSeconds to be seconds instead of nanoseconds.
Examples:
API changes
Configuration …

fix: fix wrong max age transformation from seconds

---

replications/internal/store_test.go
sqlite/migrations/0008_migrate_remotes_null_remote_org.up.sql
sqlite/migrator.go

- Closes #23867
Upgrading to 2.5.1 with an existing remote fails due to a foreign key constraint. This PR reorders some commands in the migration to resolve that issue.

fix: Fixes migrating when a remote already exists

---

cmd/influxd/launcher/launcher.go
tenant/http_server_user.go
tenant/middleware_user_auth.go
tenant/service.go

- Closes #23716
There were a whole host of discrepancies between how `/me` is supposed to work and how it was actually working. This PR should bring it (and `/users`) back up to spec with the docs/cloud 2.

fix: update me and users routes to match cloud/documentation

---

services/httpd/handler.go
services/httpd/handler_test.go

Pulls `crypto` diagnostics and includes them in `/debug/vars` output. If no `crypto` diagnostics are available, then OSS crypto information will be shown instead.
closes: #23947
Added to enhance supportability of Enterprise releases.
Extra `crypto` section is now included in `/debug/vars`
This is blocking the Enterprise FIPS release.
- Check the PR title: we …

feat: include `crypto` diagnostics in `/debug/vars` output

---

.circleci/package/fs/usr/lib/influxdb/scripts/influxdb.service
.circleci/package/fs/usr/lib/influxdb/scripts/init.sh

This restricts the permissions of files and directories generated by influxd when run as a system daemon. These permissions prevent the world from reading these files as (depending on the context) they may contain sensitive information. These settings can be configured by using systemd overrides or overwriting environment variables.

fix: restrict file permissions by default

---

cmd/influx_inspect/type_conflicts/type_conflicts.go

Absolute file paths in influx_inspect check-schema cause an 
'Invalid Argument' error. This was caused fs.WalkDir using 
fs.ValidPath. Replacing with filepath.WalkDir permits absolute 
paths.
Closes https://github.com/influxdata/influxdb/issues/23987

fix: support absolute file paths in check-schema

---

etc/config.sample.toml
services/udp/config.go
services/udp/service.go

Adds multiple writers to the udp service to increase write throughput.
I've reached a maximum write points throughput (at 164k points/s in my setup) after tuning batch-size properly.
The first interval in the image shows points received and written for 1.8.10 and the second interval shows the same data with this changes applied and writers=2
```
[[udp]]
writers = 2

feat(perf): UDP service multiple writers

---

cmd/influx_inspect/type_conflicts/type_conflicts.go

Absolute file paths in influx_inspect check-schema cause an 
'Invalid Argument' error. This was caused fs.WalkDir using 
fs.ValidPath. Replacing with filepath.WalkDir permits absolute 
paths.
closes https://github.com/influxdata/influxdb/issues/23987
(cherry picked from commit 144aca1f7fd1cacee78ab324b639cd55246b1af2)
closes https://github.com/influxdata/influxdb/issues/23994

fix: support absolute file paths in check-schema (#23991)

---

cmd/influxd/run/server.go
coordinator/config.go
etc/config.sample.toml
query/task_manager.go

- Closes https://github.com/influxdata/plutonium/issues/3886
Adds a flag to log when a query is killed for exceeding the timeout.
There is no currently no easy way to see what query might be leading to a timeout.
Adds a new config option.

feat: add the ability to log queries killed by `query-timeout`

---

cmd/influx/cli/cli.go
go.mod

The CLI code used a single function from the `golang.org/x/crypto/ssh/terminal` package (`terminal.IsTerminal`) which is just a wrapper around the `golang.org/x/term` package's `term.IsTerminal` function. Replacing this call prevents unnecessary and non-FIPS crypto functions from being pulled into the binary.
- Closes #24035
Replace usage of `terminal.IsTerminal` function from `golang.org/x/crypto/ssh/terminal` package with `term.IsTerminal` from the `golang.org/x/term` package. This avoids pulling in the `golang.org/x/crypto/ssh` package, which in turn pulled in otherwise unused crypto functions.
The unused crypto functions pulled in were not using BoringCrypto, and therefore should be avoided in a FIPS build to avoid issues during audit process.
- Feat: a …

chore: eliminate use of `golang.org/x/crypto/ssh/terminal` package

---

cmd/influxd/run/server.go
coordinator/config.go
etc/config.sample.toml
query/task_manager.go

- See https://github.com/influxdata/plutonium/issues/3886

feat: add the ability to log queries killed by `query-timeout` (1.11 backport)

---

go.mod
go.sum

chore: Bump aws dependency due to dependabot alert (#24072)

---

query/stdlib/influxdata/influxdb/provider.go
query/stdlib/influxdata/influxdb/provider_test.go

- Closes #24075
Prevents someone with a read only token from being able to write using the `to` function in flux.

fix: prevent unauthorized writes in flux "to" function

---

go.mod
go.sum

- Closes #
This PR is bumping the testcontainers-go dependency from 0.15.0 to the recently released 0.18.0 
Keep dependencies up-to-date.
Given the usage is narrowed down to one single place, the risks of a breakage are very low.
- ✅ Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
- Refactor: non-user-visible …

chore: bump testcontainers-go to 0.18.0

---

replications/internal/queue_management.go
replications/internal/queue_management_test.go

- Closes #24120 
The replication queue is not included in backup/restore. Backing up and restoring an instance that has a replication requires sqlite surgery to get a running instance. This addresses that issue by creating the queue directory if it is not there.

fix: handle replication missing queue

---

http/delete_handler.go
http/delete_test.go

The current error message implies there is an issue with the query. This more explicitly explains that this is not a supported feature.

fix: add error message when attempting to delete by field

---

gather/prometheus.go

- Closes #20193
This patch will assume `Content-Type` to be text/plain for cases where it's not specified, see https://github.com/influxdata/influxdb/issues/20193
An example where this applies is on commit `2d82a9c06c3262867322519970865dbcc6e5b93b` at the time of writing for the prometheus Wireguard exporter https://github.com/MindFlavor/prometheus_wireguard_exporter/tree/2d82a9c06c3262867322519970865dbcc6e5b93b
Why was this added? What value does it add? What are risks/best practices.
This avoids having to patch every project that implements a Prometheus-style metrics endpoint to offer a `Content-Type`.
No known risks, as the error handling is still being performed for cases where the error is a different one than a lacking `Content-Type`.
Upgrade recommended for InfluxDB users who want …

fix: scraping failed when Content-Type header is not set

---

services/httpd/handler.go

Setting the DB and RP in measurements extracted from
the predicate and used as sources causes Enterprise
/api/v2/delete to fail. The DB must explicitly be passed
to Store.Delete without being set in the measurement
struct passed as a source.
closes https://github.com/influxdata/influxdb/issues/24139

fix: do not set measurement db or rp in V2 delete

---

services/httpd/handler.go

An empty slice in Sources causes an empty
WHERE clause to be generated by
Statement.String(). Use a nil in the field
to omit the WHERE clause completely
closes https://github.com/influxdata/influxdb/issues/24144

fix: use nil Sources field in /api/v2/delete

---

.circleci/package/fs/usr/lib/influxdb/scripts/influxdb.service

Closes #22803
Adds [TimeoutStartSec](https://www.freedesktop.org/software/systemd/man/systemd.service.html) set to infinity to ensure that the service starts up even if there is a large database and/or a slow server.  The lack of a timeout is consistent with the solution implemented in #21967 in that it loops until the service is up.  Credit to [akomlik](https://github.com/influxdata/influxdb/issues/22803#issuecomment-973090633) for suggesting this solution.

fix: removed timeout which is hit with large databases or slow servers #22803

---

.circleci/config.yml

Implements remote artifact signing which is more secure than the current signing method.

chore: use remote package signing (master-1.x)

---

.circleci/config.yml

Implements remote artifact signing which is more secure than the current signing method.

chore: use remote package signing (1.11)

---

.circleci/config.yml

Implements remote artifact signing which is more secure than the current signing method.

chore: use remote package signing (1.10)

---

.circleci/config.yml

Implements remote artifact signing which is more secure than the current signing method.

chore: use remote package signing (1.9)

---

services/httpd/handler.go

*   An empty slice in Sources causes an empty
WHERE clause to be generated by
Statement.String(). Use a nil in the field
to omit the WHERE clause completely
closes https://github.com/influxdata/influxdb/issues/24144
(cherry picked from commit f365bb7e3a9c5e227dbf66d84adf674d3d127176)
closes https://github.com/influxdata/influxdb/issues/24146
*   Setting the DB or RP in measurements extracted from
the predicate and used as sources causes Enterprise
/api/v2/delete to fail. The DB must explicitly be passed
to Store.Delete without being set in the measurement
struct passed as a source.
closes https://github.com/influxdata/influxdb/issues/24139
(cherry picked from commit c31e99574ffd6fad591bcf25f68c883b908ce0e3)
closes https://github.com/influxdata/influxdb/issues/24140

fix: /api/v2/delete - user nil sources field, do not set measurement db or rp

---

tsdb/index/tsi1/partition.go

When a new MANIFEST file is created, set
its permissions to 644, not 666
closes https://github.com/influxdata/influxdb/issues/24233

fix: prevent world-writable MANIFEST files

---

tsdb/index/tsi1/partition.go

When a new MANIFEST file is created, set
its permissions to 644, not 666
closes https://github.com/influxdata/influxdb/issues/24233
(cherry picked from commit aad79e471ffff4a77d6f89f87e2fac46280c0011)
closes https://github.com/influxdata/influxdb/issues/24234

fix: prevent world-writable MANIFEST files (#24235)

---

tsdb/index/tsi1/partition.go

When a new MANIFEST file is created, set
its permissions to 644, not 666
closes https://github.com/influxdata/influxdb/issues/24233
(cherry picked from commit aad79e471ffff4a77d6f89f87e2fac46280c0011)

fix: prevent world-writable MANIFEST files [Port to 1.10]

---

.circleci/config.yml

This allows changelogs to be built from "non-release" tags. These changelogs use "UNRELEASED" as the first section header. Commits from these sections are eventually rolled into a proper "release" tag (e.g v2.7.0).

chore: upgrade changelogger to latest version (2.7)

---

.circleci/config.yml

This allows changelogs to be built from "non-release" tags. These changelogs use "UNRELEASED" as the first section header. Commits from these sections are eventually rolled into a proper "release" tag (e.g v2.7.0).

chore: upgrade changelogger to latest version (2.6)

---

go.mod
go.sum

This updates OSS 2.0 to the latest Flux version, which includes a fix for https://github.com/influxdata/flux/issues/5415.
Fixes bug with Flux function `histogramQuantile`.

build(flux): update flux to v0.194.3

---

go.mod
go.sum

This applies changes from https://github.com/influxdata/influxdb/pull/24252 to the 1.11 branch.

chore: upgrade flux to v0.194.3 (1.11)

---

go.mod
go.sum

This applies https://github.com/influxdata/influxdb/pull/24252 to the master-1.x branch.

chore: upgrade flux to v0.194.3 (master-1.x)

---

tsdb/series_partition.go

Series file indices monotonically grew even
when series were deleted.
Partially
closes https://github.com/influxdata/EAR/issues/3643

fix: series file index compaction

---

tsdb/series_partition.go

Series file indices monotonically grew even
when series were deleted.  Also stop
ignoring error in series index recovery
Partially closes https://github.com/influxdata/EAR/issues/3643
(cherry picked from commit 53856cdaae63a699946b388ffbba5bb56784ba51)

fix: series file index compaction (#23916)

---

.circleci/config.yml

This halts execution of the nightly workflow for InfluxDB 2.0. While the contents of `.circleci/config.yml` remains consistent over time, the CircleCI environment changes regularly (available executors, environment variables, etc). These older branches cause unnecessary workflow failures to populate the CircleCI dashboard. Presumably, but probably not importantly, these also consume a small amount of Circle tokens.

chore: stop executing nightly workflow (2.0)

---

.circleci/config.yml

While we have the individual `.sha256` and `.md5` files, this writes a single .digests file for all artifacts. If required, this should decrease the amount of time it takes to audit releases.

chore: generate "influxdb.${CIRCLE_TAG}.digests" for each release (1.11)

---

.circleci/config.yml

While we have the individual `.sha256` and `.md5` files, this writes a single .digests file for all artifacts. If required, this should decrease the amount of time it takes to audit releases.

chore: generate "influxdb.${CIRCLE_TAG}.digests" for each release (1.10)

---

.circleci/config.yml

While we have the individual `.sha256` and `.md5` files, this writes a single .digests file for all artifacts. If required, this should decrease the amount of time it takes to audit releases.

chore: generate "influxdb.${CIRCLE_TAG}.digests" for each release (1.9)

---

.circleci/config.yml

While we have the individual `.sha256` and `.md5` files, this writes a single `.digests` file for all artifacts. If required, this should decrease the amount of time it takes to audit releases.

chore: generate "influxdb2.${CIRCLE_TAG}.digests" for each release (2.x)

---

.circleci/config.yml
.circleci/scripts/package-validation/redhat

The terraform shipped with snap (in the older version of Ubuntu) only supported public key encryption with ssh-rsa. New versions of Linux started deprecating ssh-rsa, so this version bump is required.
Edit: While debugging this, I recreated the ssh keypair in AWS.

fix: update terraform with newer version (2.x)

---

.circleci/config.yml
.circleci/scripts/package-validation/redhat

The terraform shipped with snap (in the older version of Ubuntu) only supported public key encryption with ssh-rsa. New versions of Linux started deprecating ssh-rsa, so this version bump is required.
Edit: While debugging this, I recreated the ssh keypair in AWS.

fix: update terraform with newer version (2.7)

---

.circleci/config.yml
.circleci/scripts/package-validation/redhat

The terraform shipped with snap (in the older version of Ubuntu) only supported public key encryption with ssh-rsa. New versions of Linux started deprecating ssh-rsa, so this version bump is required.
Edit: While debugging this, I recreated the ssh keypair in AWS.

fix: update terraform with newer version (2.6)

---

.circleci/config.yml

This updates the job logic so that workflow condition is evaluated by CircleCI rather than the shell. This also uses the "aws-s3" orb for uploading to S3 (rather than awscli).

fix: correct CHANGELOG.md upload destination (2.x)

---

.circleci/config.yml

This updates the job logic so that workflow condition is evaluated by CircleCI rather than the shell. This also uses the "aws-s3" orb for uploading to S3 (rather than awscli).

fix: correct CHANGELOG.md upload destination (2.7)

---

.circleci/config.yml

This updates the job logic so that workflow condition is evaluated by CircleCI rather than the shell. This also uses the "aws-s3" orb for uploading to S3 (rather than awscli).

fix: correct CHANGELOG.md upload destination (2.6)

---

cmd/influx_inspect/dumptsi/dumptsi.go
models/points.go
models/points_test.go
monitor/service_test.go
services/httpd/response_writer.go
storage/reads/resultset_lineprotocol.go
storage/reads/store_test.go
tsdb/engine/tsm1/engine_test.go
tsdb/index_test.go

CSV output is incorrectly escaped.
Add a boolean flag to tag output
functions to prevent this.
closes https://github.com/influxdata/influxdb/issues/24309

fix: do not escape CSV output

---

cmd/influx_inspect/dumptsi/dumptsi.go
models/points.go
models/points_test.go
monitor/service_test.go
services/httpd/response_writer.go
storage/reads/resultset_lineprotocol.go
storage/reads/store_test.go
tsdb/engine/tsm1/engine_test.go
tsdb/index_test.go

CSV output is incorrectly escaped.
Add a boolean flag to tag output
functions to prevent this.
closes https://github.com/influxdata/influxdb/issues/24309
(cherry picked from commit 2dc3dcb3d1795e0c6091e5b113e6297836ce5f2f)
closes https://github.com/influxdata/influxdb/issues/24310

fix: do not escape CSV output (#24311)

---

.circleci/config.yml
.circleci/scripts/install-rosetta

This will prevent issues when CircleCI deprecates the x86/Intel Mac images.

chore: update MacOS executor to M1 (2.5)

---

.circleci/config.yml
.circleci/scripts/install-rosetta

This will prevent issues when CircleCI deprecates the x86/Intel Mac images.

chore: update MacOS executor to M1 (2.x)

---

.circleci/config.yml
.circleci/scripts/install-rosetta

This will prevent issues when CircleCI deprecates the x86/Intel Mac images.

chore: update macos executor (2.7)

---

.github/dependabot.yml

Before switching to rust-based IOx, influxdb was a Go project which dependabot tracked. After the switch, dependabot would issue alerts for go files that no longer exist. Tell dependabot to ignore "gomod"

chore: ignore Go in .github/dependabot.yml

---

.github/dependabot.yml

2 new alerts for go came in. Let's try a different way.

chore: ignore Go in .github/dependabot.yml, take 2

---

.github/dependabot.yml

Update to use the documented dependency-name: "*" methodology rather than an undocumented example.
References:
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

chore: ignore Go in .github/dependabot.yml, take 3

---

go.mod
go.sum

Prerequisite for https://github.com/influxdata/edge/issues/534
* Upgrades Flux to v0.194.4
* Upgrade go version reference directive to 1.20 - other 1.x branches have that it seems this was overlooked (?)

build(deps): upgrade flux to v0.194.4

---

gather/metrics.go
gather/scheduler_test.go

Correctly handle errors in converting `MetricSlice` 
elements into `model.Points`. Add a test to verify 
error handling.

fix: handle MetricSlice to Points conversion errors

---

gather/metrics.go
gather/scheduler_test.go

Correctly handle errors in converting MetricSlice
elements into model.Points. Add a test to verify
error handling.
(cherry picked from commit 19e5c0e1b7c40f95fd9d70d51c72281d2d4b4b6b)

fix: handle MetricSlice to Points conversion errors (#24452)

---

context/token.go
http/authentication_middleware.go
http/legacy/influx1x_authentication_handler.go
http/middleware.go

To allow rudimentary security auditing of logs,
add the authenticating ID and the user ID when
possible to the request logs. When a request is
authorized for V1 or V2 API, store the authorizer
object to be used by the logger up the call stack.
closes https://github.com/influxdata/influxdb/issues/24473

feat: Add authenticating ID and user ID to request logging

---

context/token.go
http/authentication_middleware.go
http/legacy/influx1x_authentication_handler.go
http/middleware.go

To allow rudimentary security auditing of logs,
add the authenticating ID and the user ID when
possible to the request logs. When a request is
authorized for V1 or V2 API, store the authorizer
object to be used by the logger up the call stack.
closes https://github.com/influxdata/influxdb/issues/24473
(cherry picked from commit 13cf6be49ec6c23ac99cd26cc745814712985e0d)
closes https://github.com/influxdata/influxdb/issues/24475

feat: Add authenticating ID and user ID to request logging (#24474)

---

.circleci/config.yml
scripts/ci/build-tests.sh

When the build takes longer than 10 minutes, CirceCI times out. This emits the build commands as the build is running to prevent CircleCI from timing out.

chore: emit build commands (2.7)

---

replications/remotewrite/writer.go
replications/remotewrite/writer_test.go

To assist debugging of write failures
in Edge Data Replication, do not
write only the HTTP status code to
the log, but also include any error
messages returned by the recipient.
closes https://github.com/influxdata/influxdb/issues/24481

feat: write detailed logs from EDR failures

---

replications/remotewrite/writer.go
replications/remotewrite/writer_test.go

To assist debugging of write failures
in Edge Data Replication, do not
write only the HTTP status code to
the log. Also include any messages
returned by the write recipient.
closes https://github.com/influxdata/influxdb/issues/24481
(cherry picked from commit 0ccd35c2537df50d447ed181981de581d68ac10f)
closes https://github.com/influxdata/influxdb/issues/24482

feat: write detailed logs from EDR failures (#24496)

---

cmd/influx_inspect/verify/seriesfile/verify.go
tsdb/series_file.go
tsdb/series_partition.go
tsdb/series_segment.go
tsdb/series_segment_test.go

Some series files which are smaller than the standard sizes 
cause SIGBUS in `influx_inspect` and `influxd`, because 
entry iteration walks onto mapped memory not backed by 
the file.  Avoid walking off the end of the file while iterating 
series entries in oddly sized files.
closes https://github.com/influxdata/influxdb/issues/24508

fix: avoid SIGBUS when reading non-std series segment files

---

cmd/influx_inspect/verify/seriesfile/verify.go
tsdb/series_file.go
tsdb/series_partition.go
tsdb/series_segment.go
tsdb/series_segment_test.go

Some series files which are smaller than the standard sizes cause SIGBUS in influx_inspect and influxd, because entry iteration walks onto mapped memory not backed by the the file.  Avoid walking off the end of the file while iterating series entries in oddly sized files.
closes https://github.com/influxdata/influxdb/issues/24508
Co-authored-by: Geoffrey Wossum <gwossum@influxdata.com>
(cherry picked from commit 969abf3da274052a843032704a590efb94fce6af)
closes https://github.com/influxdata/influxdb/issues/24510

fix: avoid SIGBUS when reading non-std series segment files (#24509)

---

cmd/influxd/inspect/verify_seriesfile/verify_seriesfile.go
tsdb/series_file.go
tsdb/series_partition.go
tsdb/series_segment.go
tsdb/series_segment_test.go
tsdb/shard_test.go

Some series files which are smaller than the standard sizes cause SIGBUS in influx_inspect and influxd, because entry iteration walks onto mapped memory not backed by the the file.  Avoid walking off the end of the file while iterating series entries in oddly sized files.
closes https://github.com/influxdata/influxdb/issues/24508
Co-authored-by: Geoffrey Wossum <gwossum@influxdata.com>
(cherry picked from commit 969abf3da274052a843032704a590efb94fce6af)
closes https://github.com/influxdata/influxdb/issues/24511
(cherry picked from commit 081f95147ecf7be3a1f96b07dcb19ff95bab054a)
closes https://github.com/influxdata/influxdb/issues/24512

fix: avoid SIGBUS when reading non-std series segment files (#24509) (#24520)

---

session/http_server.go
session/http_server_test.go

When TLS is enabled, set the HttpOnly and
Secure flags when a cookie is created.
closes: https://github.com/influxdata/influxdb/issues/24522

fix: enable HttpOnly and Secure using TLS

---

session/http_server.go
session/http_server_test.go

Set the HttpOnly and, when TLS is enabled,
Secure flags on cookies
closes: https://github.com/influxdata/influxdb/issues/24522
(cherry picked from commit 8e8700f14f8b45601f59cb20908ee5baa8667328)
closes https://github.com/influxdata/influxdb/issues/24523

fix: enable Secure when using TLS and enable HttpOnly (#24524)

---

ingest_structure/src/lib.rs

Run `cargo fmt -all` as main is dirty, and as such all PRs fail the fmt job.

chore: Run cargo fmt --all

---

Cargo.lock
influxdb_line_protocol/Cargo.toml
influxdb_line_protocol/README.md
influxdb_line_protocol/RELEASE.md
influxdb_line_protocol/src/lib.rs

* Increase influxdb-line-protocol version
* run `cargo rdme`
* Pull changes from influxdb_iox
* only missing: https://github.com/influxdata/influxdb_iox/commit/61082a000005cd2f88cfd3799072e3e14e3d5005

chore: Sync and release v1.0.1 of influxdb-line-protocol

---

Dockerfile

Now that we're transitioning the repo code to have influxdb3 Edge not IOx be what's here, we can update the Dockerfile to build influxdb3. This is mostly just updating which version of Rust to use, changing the command that's run when docker runs the container to serve, and changing influxdb_iox to influxdb3 everywhere in the file.
I've confirmed locally that running docker build works fine and that running the resulting file will run the `influxdb3 serve`command. This should also fix the failing build on CI which uses Docker for the release build. In the future I think this discrepancy should be fixed (what runs on main should run here), but it works for now

fix: set Dockerfile to build influxdb3 not IOx

---

CONTRIBUTING.md

Following the current guide led me to some errenous errors, largely because I followed the need for Go 1.15 :facepalm:
Once I checked the `go.mod` file, I noticed the mention of Go1.15 was outdated. Using 1.20 fixed my issue and I've included a small setup change to help any other weary travellers avoid my mistake, by directly installing the correct version via `gvm` using the `go.mod` file as the source of truth.

docs(contributing): update setup

---

.circleci/config.yml

This pipeline was meant to be fixed with #24562, but my understanding was incorrect as the dockerfile was not the only thing that needed to be changed. This PR fixes that by actually fixing up the CI pipeline to do what we expect.
CI Build that passed: https://app.circleci.com/pipelines/github/influxdata/influxdb/37015/workflows/ad86eb32-7450-48ee-b902-d2836895e0e3/jobs/346060
I rebased and squashed the PR so that it wouldn't fail the Semantic PR check, but I'm confident this should work
~~NOTE: Currently I'm testing this out in a draft PR that will get changed to a full PR once I've determined it works and I will revert 73aeaa5 before merging as we want it to run on main only.~~

fix: main build_release pipeline

---

.circleci/config.yml

We currently don't need or want to deploy influxdb as we're still building out the Edge product. Maybe later for a demo, but for now it just breaks CI and so this removes it.

fix: remove deploy step for images

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/lib.rs
influxdb3_write/src/wal.rs
influxdb3_write/src/write_buffer.rs

This WAL implementation uses some of the code from the wal crate, but departs pretty significantly from it in many ways. For now it uses simple JSON encoding for the serialized ops, but we may want to switch that to Protobuf at some point in the future. This version of the wal doesn't have its own buffering. That will be implemented higher up in the BufferImpl, which will use the wal and SegmentWriter to make data in the buffer durable.
The write flow will be that writes will come into the buffer and validate/update against an in memory Catalog. Once validated, writes will get buffered up in memory and then flushed into the WAL periodically (likely every 10-20ms). After being flushed to the wal, the entire batch of writes will be put into the in memory queryable buffer. After that …

feat: add basic wal implementation for Edge

---

Cargo.lock
influxdb3_write/src/lib.rs
influxdb3_write/src/paths.rs
influxdb3_write/src/wal.rs

This commit introduces 3 new types in the paths module for the influxdb3_write crate. They are:
- ParquetFilePath
- CatalogFilePath
- SegmentFilePath
Each of these corresponds to an object store path and also on disk path that we can use to address the needed files in a consistent way and not need to have path construction be duplicated to address these files.
These types also Deref/AsRef to the Path type so that they can be used in places that expect the type such as various std::fs methods and so that we can use methods like `exist()` without needing to implement them for each type as they are thin wrappers around PathBuf.
This commit adds some tests to make sure that the path construction works as intended and also updates the `wal.rs` file to use the new `SegmentFilePath` instead of …

feat: Add paths module to influxdb3_write

---

tsdb/index.go
tsdb/index/tsi1/log_file.go
tsdb/series_cursor.go
tsdb/series_file.go
tsdb/series_file_test.go

This is a cherry-pick of 6af0be9 (introduced in https://github.com/influxdata/influxdb/pull/24565) for a port the `2.7` branch.
_Original pull request comment:_
Panics can be avoided by checking the validity of the return from `ReadSeriesKeyLen`, at the moment the size check resulting from this function is entirely discarded. The contained call to [`binary.Uvarint`](https://pkg.go.dev/encoding/binary#Uvarint) contains an implicit error, depending on the returned value:
> If an error occurred, the value is 0 and the number of bytes n is <= 0
In every occurrence of `ReadSeriesKeyMeasurement`, the `ReadSeriesKeyLen` function is called prior to it, determined by glancing over the output of `rg "ReadSeriesKeyMeasurement" -B 5` across the full codebase. 
This PR refactors the flow slightly to …

fix: panic index out of range for invalid series keys [Port to 2.7]

---

query/stdlib/universe/last_test.flux
tsdb/index/tsi1/partition.go
tsdb/index/tsi1/partition_test.go

TestPartition_Compact_Write_Fail test was not locking the partition before changing the value of MaxLogFileSize. This PR exports the mutex of the partition to allow the test to access it and lock. Alternatives require more changes such as a Setter method if we need to hide the mutex.
* fixes #24042, for #24040
Closes #

fix(tsi1/partition/test): fix data race in test code

---

Cargo.lock
rust-toolchain.toml

Added the `rust-analyzer` component to the `rust-toolchain.toml` file so that the correct version of Rust Analyzer is installed on Apple Silicone.
This will allow the LSP to work on Apple Silicone machines.

fix: add rust-analyzer to toolchain file

---

.circleci/config.yml

Prior to this change we've had CI fail nightly because we can't push the image to CI due to permissions issues. The problem is that influxdata/influxdb_iox is the one that actually has access to push that data to quay.
This commit removes the nightly build and references to it as this image is built nightly by the IOx team. If things break we have access to fix it, but I don't think it'll be an issue.

fix: Remove nightly CI build from Circle CI runs

---

Cargo.lock
influxdb3_server/Cargo.toml
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs

This commit adds the ability to choose the output format of a query via
the v3 api so that a user can choose, whether by Accept headers or the
format url param, how the data will be returned to them.
Prior to this commit the default was a pretty printed text format, but
that instead has been changed to json as the default.
There are multiple formats one can choose:
1. json
2. csv
3. pretty printed text
4. parquet
I've tested each of these out and it works well. In particular the
parquet output is exciting as users will be able to perform a query and
receive back parquet data that they can then load into say a Python
script or something else to work on and operate it. As we extend what
data can be queried, as well as persisting it, what people will be able
to do with Edge will be really …

feat: Add different output support to queries

---

Cargo.lock
influxdb3_server/src/query_executor.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/catalog.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/paths.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/wal.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/mod.rs

This builds on #24624, which should get merged in first. 
Fixes #24573. This adds persist to `ClosedBufferSegment`, which will persist the Catalog, if it has been modified, persist all tables and partitions in the buffer as parquet files and then write the segment file.
It doesn't have retries if errors are encountered during persistence and it doesn't parallelize them, which we should do later. Logged #24657 and #24658 to track those.

feat: Add segment persist of closed buffer segment

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3/tests/common.rs
influxdb3/tests/flight.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/grpc.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_server/src/service.rs

Closes #24643
This PR adds support for FlightSQL queries via gRPC to the `influxdb3` service. It does so by ensuring the `QueryExecutor` implements the `QueryNamespaceProvider` trait, and the underlying `QueryDatabase` implements `QueryNamespace`. Satisfying those requirements allows the construction of a `FlightServiceServer` from the `service_grpc_flight` crate.
The `FlightServiceServer` is a gRPC server that can be served via `tonic` at the API surface; however, enabling this required some `tower::Service` wrangling. The `influxdb3_server/src/server.rs` module was introduced to house this code. The code there is largely inspired by [this series of blog posts](https://www.fpcomplete.com/blog/axum-hyper-tonic-tower-part1/). The objective is to serve both gRPC (via the newly introduced …

feat: support FlightSQL in 3.0

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_write/src/catalog.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs

* This implements a loader for the write buffer. It loads the catalog and the buffer from the WAL.   
* Move Persister errors into their own type now that the write buffer load could return errors from the persister.
* Moved persister tests into tests block
* Fixes a bug where the persister would throw an error if attempting to load segments when none had been persisted.
This doesn't yet rotate segments or trigger persistence of newly closed segments, which will be addressed in a future PR.
Fixes #24572

feat: implement loader for persisted state

---

influxdb3/tests/server/flight.rs
influxdb3/tests/server/limits.rs
influxdb3/tests/server/main.rs
influxdb3/tests/server/query.rs
influxdb3_server/src/http.rs
influxdb3_write/src/catalog.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs

This commit is the final piece for the write_lp endpoint. It adds limits to Edge such that:
- There can only be 5 Databases
- There can only be 500 Columns per Table
- There can only be 2000 Tables across all Databases
We do this by modifying the catalog code to error out whenever one of these limits would be exceeded before permanently modifying the schema. These are hard coded limits and cannot be configured by the user.
Closes #24554

feat: Add limits for InfluxDB Edge

---

.circleci/config.yml

I ran the changes on this branch to make sure CI would pass when merged to main and it will:
https://app.circleci.com/pipelines/github/influxdata/influxdb/38009/workflows/ce0c7c6d-fc6b-4ecd-aa47-60a344fc90aa/jobs/355115

fix: CircleCI image deprecations

---

Cargo.lock
iox_query_influxql_rewrite/src/lib.rs

Extended the InfluxQL rewriter to handle SELECT statements with nested sub-queries, as well as EXPLAIN statements.
Tests were added to check all the rewrite cases for happy path and failure modes.
This works by recursively rewriting the nested sub-queries, extracting their database (DB) and retention policy (RP), and checking that only a single DB/RP is being used up the chain to the parent `SELECT` statement. For example, a valid `SELECT` statement with a sub-query would be:
```sql
SELECT * FROM foo.bar.cpu, (
SELECT * FROM foo.bar.mem
);
```
because the DB/RP (`foo.bar`) is consistent between the top-level `SELECT` and its nested sub-query.
An invalid case would be, for example:
```sql
SELECT * FROM cpu, (
SELECT * FROM foo.bar.mem
);
```
because the outer source does not have its DB/RP …

feat: extend InfluxQL rewriter for `SELECT` and `EXPLAIN`

---

Cargo.lock
Cargo.toml
influxdb3/tests/server/query.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs

Added support through the `influxdb3` `QueryExecutor` to perform `SHOW RETENTION POLICIES` queries, both on a specific database as well as across all databases.
There are three ways to invoke this through the V3 API, and test cases were added to check each in the `query::api_v3_query_influxql` E2E test.
* omitting the `db` parameter, and providing the query `SHOW RETENTION POLICIES`
* omitting the `db` parameter, and providing the query `SHOW RETENTION POLICIES ON <db_name>`
* providing the `db` parameter, and the query `SHOW RETENTION POLICIES`
In the first case, all databases and their retention policies will be listed. In the latter cases, only the retention policy for the specified database will be listed.
One could also provide the `db` parameter, and the query `SHOW RETENTION …

feat: support `SHOW RETENTION POLICIES`

---

Cargo.lock
influxdb3/tests/server/flight.rs
influxdb3/tests/server/main.rs

Part of #24645 - but does not close it, as all the special InfluxQL support that was added in the HTTP API (see #24644, #24696, #24726, #24729) is not currently supported over Flight. Supporting such queries will require changes to `influxdb3_core`.
This change adds end-to-end tests to ensure that InfluxQL queries can be sent via Flight. No new functionality was added, just tests, as the `FlightService` that was setup in #24643 already had the capability to serve InfluxQL queries.

test: add tests to check InfluxQL over Flight

---

.circleci/config.yml
influxdb3/Cargo.toml
influxdb3/tests/server/limits.rs

There is no issue for this. This puts a feature gate on the `influxdb3::server::limits` end-to-end test, as it takes some time to run locally.
The test can be run with the feature flag `limits`, e.g.,
```
cargo test --workspace --features=limits
```
CI has been updated to run tests this way.

chore: gate `limits` test behind a feature flag

---

influxdb3/src/commands/serve.rs
influxdb3_server/src/builder.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs

This is a proposed change to the #24738 to use dynamic dispatch for the `Authorizer` on the `Server`.
It also removes the old `Server::new` method which is no longer used.

refactor: use dynamic dispatch for Authorizer

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_server/src/builder.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/lib.rs
influxdb3_write/src/paths.rs
influxdb3_write/src/wal.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs

Closes #24706. As I was implementing that initial design, I realized that everything would be much cleaner and easier to explain if all data was simply ingested into the segment period that it falls into. However, this could potentially cause a problem if users are spraying data all over history, so it currently limits open segments that can be written to to no more than 100. I will log follow up issues for items that still need to be done.
I did this with WIP commits along the way, but the design evolved as I developed it. So it's best to just view the whole thing. If it's too much to take in, I can break it down into smaller PRs that will be easier to review. Things are pretty tied together so that could get a little tricky.
* Update WAL to work with many segments and to store segment …

feat: Segment the write buffer on time

---

influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/wal.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/segment_state.rs

Builds on top of #24745 so that should be reviewed and merged in first.
This implements automatic segment persistence and cleanup of the WAL files. Every second the write buffer checks to and persists segments that have been open for longer than half the segment duration and that are not in the current or next block of time.
One thing left to do is to deal with blocks of time that have had multiple segments persisted in them. This will be addressed in a follow on PR.
Specific udpates:
* Update Persister persist_segment to take borrow
* Move SegmentState into its own module
* Create functions to close open segments and persist them when time
* Add tokio task to check every second to see if segments should be persisted

feat: Implement automatic segment persistence

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/chunk.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/segment_state.rs

This adds the functionality to query from Parquet files that have been persisted in object storage. Any segments that are loaded up on boot up will be included (limit of 1k segments at the time of this PR). In a follow on PR we should add a good end-to-end test that has persistence and query through the main API (might be tricky).
* Move BufferChunk and ParquetChunk into chunk module
* Add object_store_url to Persister
* Register object_store on server startup
* Add loaded persisted_segments to SegmentState

feat: wire up query from parquet files

---

influxdb3/tests/server/auth.rs
influxdb3_server/src/http.rs

Closes #24754 
The `p` URL query parameter can be used to authenticate requests to the `/api/v1/query` and `/api/v1/write` APIs
An E2E test was added to ensure this works.

feat: support authenticating v1 APIs with p parameter

---

Cargo.lock
Cargo.toml
influxdb3/Cargo.toml
influxdb3/tests/server/auth.rs
influxdb3/tests/server/main.rs
influxdb3/tests/server/query.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/auth.rs
influxdb3_server/src/http.rs
influxdb3_server/src/http/v1.rs

Part of #24740 
This PR adds support for the `/api/v1/query` API, which is meant to serve the original InfluxDB v1 query API (see [docs](https://docs.influxdata.com/influxdb/v1/tools/api/#query-http-endpoint)), to serve single statement `SELECT` and `SHOW` queries. The response, which is returned as JSON, can be chunked via the `chunked` and optional `chunk_size` parameters (_see below_). An optional `epoch` parameter can be supplied to have `time` column timestamps converted to a UNIX epoch with the given precision.
The response is buffered by default, but if the `chunked` parameter is not supplied, or is passed as `false`, then the entire query result will be buffered into memory before being returned in the response. This is how the original API behaves, so we are replicating that …

feat: support v1 query API

---

tsdb/cursors/arrayvalues.gen.go
tsdb/cursors/arrayvalues.gen.go.tmpl

Do not panic if a cursor array is nil and the number of timestamps is retrieved.
closes https://github.com/influxdata/influxdb/issues/24536

fix: do not panic when empty tags are queried

---

tsdb/cursors/arrayvalues.gen.go
tsdb/cursors/arrayvalues.gen.go.tmpl

Do not panic if a cursor array is nil and the number of timestamps is retrieved.
closes https://github.com/influxdata/influxdb/issues/24536
(cherry picked from commit bc80e881fa34aef4145007aa510ffe3e78d3e7ab)

fix: do not panic when empty tags are queried (#24784)

---

Cargo.lock
Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/chunk.rs
influxdb3_write/src/write_buffer/mod.rs

`influxdb3_core` was recently updated in https://github.com/influxdata/influxdb3_core/pull/4
This brings in the latest changes, with any needed refactoring.

chore: `influxdb3_core` update

---

.circleci/config.yml
influxdb3/src/commands/query.rs
influxdb3_write/src/wal.rs
rust-toolchain.toml

This is a fairly quiet upgrade. The only changes are some lints around `OpenOptions` that were added to clippy between 1.75 and this version and they're small changes that either remove unecessary function calls or add a needed function call.
Release Blog Post: https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html

chore: Update to Rust 1.77.0 

---

influxdb3/tests/server/query.rs
influxdb3_server/src/http.rs
influxdb3_server/src/http/v1.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs

Closes #24801
* This adds support for parameters in the `/api/v3/query_sql` and `/api/v3/query_influxql` APIs.
* The new parameter `params` is supported in the URL query string of a `GET` request, or in the JSON body of a `POST` request.
* Two new E2E tests were added to check successful GET/POST as well as error scenario when params are not provided for a query string that would expect them.
Consider the following query containing the parameter `$bar`:
```sql
SELECT * FROM foo WHERE bar = $bar;
```
We can invoke this query via the `GET /api/v3/query_sql` API:
```http
GET /api/v3/query_sql?params=<params>[...]
```
where `<params>` is a stringified JSON object containing `name`:`value` pairs for provided parameters, e.g.,
```json
{
"bar": "baz"
}
```
We can also invoke this query via the …

feat: support query parameters

---

influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/segment_state.rs

When a write comes into the buffer that both updates the catalog and creates a new segment, it would create that segment with a catalog sequence number that matched what happened after the catalog modification. The result is that when the segment is persisted, the catalog won't be persisted because it wasn't being viewed as being updated. This fixes that.

fix: catalog persist with new segment

---

influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/loader.rs

Fixes a bug where the loader would error out if there was a wal segment file for a previous segment that hand't been persisted, and a new wal file had to be created for the new open segment. This would show up as an error if you started the server and then stopped and restarted it without writing any data.

fix: loader error with single wal file

---

tsdb/store.go

Avoid unnecessarily deleting series from the series file
Try harder to delete series from InMem indices 
Log all errors on shard deletion
Closes https://github.com/influxdata/influxdb/issues/24834

fix: improved shard deletion

---

cmd/influx_tools/internal/storage/resultset.go
storage/reads/array_cursor.gen.go
storage/reads/array_cursor.gen.go.tmpl
storage/reads/array_cursor.go
tsdb/engine/tsm1/array_cursor.gen.go
tsdb/engine/tsm1/array_cursor.gen.go.tmpl
tsdb/engine/tsm1/array_cursor_iterator.gen.go
tsdb/engine/tsm1/array_cursor_iterator.gen.go.tmpl
tsdb/engine/tsm1/array_cursor_iterator.go
tsdb/engine/tsm1/array_cursor_test.go

ArrayCursors were ignoring errors, which led to panics when nil
cursors were operated on. This fix passes errors back up the stack 
and uses them to enforce healthy cursor creation.   
Closes https://github.com/influxdata/influxdb/issues/24789

fix: return and respect cursor errors

---

storage/reads/array_cursor.gen.go
storage/reads/array_cursor.gen.go.tmpl
storage/reads/array_cursor.go
tsdb/engine/tsm1/array_cursor.gen.go
tsdb/engine/tsm1/array_cursor.gen.go.tmpl
tsdb/engine/tsm1/array_cursor_iterator.gen.go
tsdb/engine/tsm1/array_cursor_iterator.gen.go.tmpl
tsdb/engine/tsm1/array_cursor_iterator.go
tsdb/engine/tsm1/array_cursor_test.go

ArrayCursors were ignoring errors, which led to panics when nil cursors were operated on. This fix passes errors back up the stack and uses them to enforce healthy cursor creation.
Closes https://github.com/influxdata/influxdb/issues/24789 
---------
Co-authored-by: Stuart Carnie <stuart.carnie@gmail.com>
(cherry picked from commit fe6c64b21ed7e0757375e57b8eca21e9c05f3c89)
closes https://github.com/influxdata/influxdb/issues/24825

fix: return and respect cursor errors (#24791)

---

storage/reads/array_cursor.gen.go
storage/reads/array_cursor.gen.go.tmpl
storage/reads/array_cursor.go
tsdb/engine/tsm1/array_cursor.gen.go
tsdb/engine/tsm1/array_cursor.gen.go.tmpl
tsdb/engine/tsm1/array_cursor_iterator.gen.go
tsdb/engine/tsm1/array_cursor_iterator.gen.go.tmpl
tsdb/engine/tsm1/array_cursor_iterator.go
tsdb/engine/tsm1/array_cursor_test.go

ArrayCursors were ignoring errors, which led to panics when nil cursors were operated on. This fix passes errors back up the stack and uses them to enforce healthy cursor creation.
Closes https://github.com/influxdata/influxdb/issues/24789
Co-authored-by: Stuart Carnie <stuart.carnie@gmail.com>
(cherry picked from commit fe6c64b21ed7e0757375e57b8eca21e9c05f3c89)
closes https://github.com/influxdata/influxdb/issues/24836
(cherry picked from commit 49d0bef3ea6ea5e2836844cd059159bd246cc5bb)
closes https://github.com/influxdata/influxdb/issues/24826

fix: return and respect cursor errors (#24791) (#24846)

---

Cargo.lock
influxdb3_load_generator/Cargo.toml
influxdb3_load_generator/src/commands/common.rs
influxdb3_load_generator/src/commands/query.rs
influxdb3_load_generator/src/commands/write.rs
influxdb3_load_generator/src/line_protocol_generator.rs
influxdb3_load_generator/src/main.rs
influxdb3_load_generator/src/query_generator.rs
influxdb3_load_generator/src/report.rs
influxdb3_load_generator/src/specification.rs
influxdb3_load_generator/src/specs/example.rs
influxdb3_load_generator/src/specs/mod.rs
influxdb3_load_generator/src/specs/one_mil.rs

Part of #24828
This PR implements the `query` load generator. The design follows that of the existing `write` load generator.
A `QuerySpec` is defined that will be used by the `query` command to generate a set of queriers to perform queries against a running server in parallel.

feat: initial query load generator

---

influxdb3_write/src/catalog.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/segment_state.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This updates the buffer to use Arrow builders. This significantly improves the memory footprint for data in the buffer. It also makes querying the buffer significantly faster as it no longer creates copies to query against. In earlier tests when querying against a large buffer, it would cause writes to stop while making copies. This also significantly speeds up persisting of data when segments are closed.
This also fixes a bug in the catalog where the Arrow schema wouldn't get updated when new columns were added to a table.

refactor: buffer using Arrow builders

---

influxdb3_load_generator/src/commands/write.rs

When starting up with many write generators, some may fail because of contention to create the schema. This forces all but the first one to wait for a little bit giving the first generator time to call to the db and have schema created.

fix: make write load_generators wait

---

Cargo.lock
Cargo.toml
influxdb3_load_generator/Cargo.toml
influxdb3_load_generator/src/commands/query.rs
influxdb3_load_generator/src/commands/write.rs
influxdb3_load_generator/src/report.rs
influxdb3_process/src/lib.rs

Closes #24829
Added the mechanism to report system stats during load generation. The following stats are saved in a CSV file. Stats pertain specifically to the `influxdb3` process running on the local operating system:
- `wall_time`: timestamp of when row was written
- `test_time_ms`: time since test started
- `cpu_usage`: total CPU usage of the process, may be greater than 100 if more than one core is being used
- `written_bytes`: total bytes written to disk since last system stat refresh, i.e., since the previous row of data
- `read_bytes`: total bytes read from disk since last system stat refresh
- `memory_bytes`: total memory usage at given time
- `virtual_memory_bytes`: total virtual memory usage at given time
System stats can only be tracked when running the load generator against a …

feat: report system stats in load generator

---

Cargo.lock
Cargo.toml
influxdb3/tests/server/flight.rs

Updates to use the latest version of `influxdb3_core`. This was primarily to resolve an issue with the `iox_http` crate that was preventing direct compilation of crates that depended on it, e.g., `influxdb3_write`

chore: update to latest core

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3/tests/server/query.rs
influxdb3_server/src/lib.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/chunk.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/segment_state.rs
influxdb3_write/src/write_buffer/table_buffer.rs

When persisting parquet files we now will sort and dedupe on persist using the
COMPACT operation implemented in IOx Query. Note that right now we don't choose
any column to sort on and default to no column. This means that we dedupe and
sort on whatever the default behavior is for the COMPACT operation. Future
changes can figure out what columns to sort by when compacting the data.
Closes #24823

feat: sort and dedupe on persist

---

Cargo.lock
influxdb3_load_generator/src/commands/common.rs
influxdb3_load_generator/src/commands/full.rs
influxdb3_load_generator/src/commands/query.rs
influxdb3_load_generator/src/commands/write.rs
influxdb3_load_generator/src/main.rs
influxdb3_load_generator/src/report.rs
influxdb3_load_generator/src/specification.rs

Closes #24832
This implements a new `full` sub-command for the `influxdb3_load_generator` binary. This will run both the `query` and `write` loads simultaneously. The required refactoring was split over a few commits, which I have described below.
---
Refactored the argument interface for the `query` and `write` load generator sub-commands to make them easier to unify in a new `full` command.
In summary:
- remove the query sampling interval arg
- make short-form of `--querier-count` `q` instead of `Q`
- remove the short-form for `--query-format`
- remove `--spec-path` in favour of `--querier-spec` and `--writer-spec` for specifying spec path of the `query` and `write` loads, respectively
Refactored the `query` and `write` command clap configurations to make them composable for the `full` …

feat: add the `full` sub-command to load generator

---

influxdb3_load_generator/src/commands/common.rs
influxdb3_load_generator/src/commands/full.rs
influxdb3_load_generator/src/commands/query.rs
influxdb3_load_generator/src/commands/write.rs
influxdb3_load_generator/src/report.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Closes #24879
* make the `--end` argument common to both the `query` and `write` load generation runners, so that they will both terminate at the given future offset time.
* changed the `full` command to use `tokio::task::JoinSet` for spawning the query and write tasks.
* added a panic message in the table buffer where unwraps were causing panics (part of #24880)

refactor: make end argument common to query and write load generation

---

tsdb/store.go

Avoid unnecessarily deleting series from the series file Try harder to delete series from InMem indices
Log all errors on shard deletion
Closes https://github.com/influxdata/influxdb/issues/24834
(cherry picked from commit 8ff06d5a92ca3a0a34b31bfa9d37e6cff72a58a3)
closes https://github.com/influxdata/influxdb/issues/24835

fix: improved shard deletion (#24602)

---

influxdb3_load_generator/analysis/app.py
influxdb3_load_generator/analysis/templates/index.html
influxdb3_load_generator/src/commands/common.rs

There is no issue for this.
* Have the load generator output files with seconds in the file name, e.g., `write_<spec_name>_2024-04-12T10-11-12.csv`
* this was so that runs could be started within a minute of each other
* **Note**: this will likely break the tool for previously generated files that do not have this naming convention
* Have the front-end produce graphs dynamically, based on what was run, e.g., if only `query` and `system` were run, only graphs for those will be displayed. Previously, it would error if all three (`write`/`query`/`system`) were not present. Example:

feat: QoL improvements to the load generator and analysis tools

---

.circleci/config.yml
go.sum

Closes https://github.com/influxdata/edge/issues/640
Despite the names of recently closed PRs mentioning 1.22, they upgraded Go to 1.21.9. Hence the version same here, although branch name  contains 1.22.

chore: upgrade go 1.21.8 -> 1.21.9

---

go.mod
go.sum

Performed:
$ go mod edit golang.org/x/net@v0.23.0
$ go mod tidy

chore: update golang.org/x/net to v0.23.0 (1.11)

---

Cargo.lock
Cargo.toml

Pointing at the latest version of `influxdb3_core` after https://github.com/influxdata/influxdb3_core/pull/16.

chore: point at latest core

---

.circleci/config.yml
.circleci/packages/config.yaml
foo

This uses the new `ci-packager` container that doesn't mangle the version strings. Some modifications to `config.yaml` were required, so I pushed the image to `ci-packager-next`. When I make all other workflows using this image compatible, I'll move everything over to `ci-packager` proper.
The only thing of note is that RPMs don't accept `-` in either the `Version` or `Release` section. So I've split the version by the first encountered `-`. For instance, here's what a snapshot package results with:
```sh
$ rpm -qip influxdb3-3.0.0+snapshot-fdee5321.x86_64.rpm
Name        : influxdb3
Version     : 3.0.0+snapshot
Release     : fdee5321
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 86751347
License     : MIT/Apache-2.0
Signature   : (none)
Source …
```

feat: use new package builder

---

.circleci/config.yml
.circleci/packages/config.yaml
.circleci/packages/influxdb3/control/post-install
.circleci/packages/influxdb3/control/pre-install
.circleci/scripts/docker_build_release.bash
.circleci/scripts/package-validation/debian
.circleci/scripts/package-validation/redhat
.circleci/scripts/package-validation/tf/main.tf
.circleci/scripts/package-validation/validate
.circleci/scripts/publish.bash
Cargo.lock
Cargo.toml
Dockerfile
foo
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3_process/Cargo.toml
influxdb3_process/src/lib.rs
influxdb3_server/src/lib.rs

feat: build binaries and Docker images in CI 
For releases we need to have Docker images and binary images available for the
user to actually run influxdb3. These CI changes will build the binaries on a
release tag and the Docker image as well, test, sign, and publish them and make
them available for download.
Co-Authored-By: Brandon Pfeifer <bpfeifer@influxdata.com>
Closes #24773

feat: build binaries and Docker images in CI

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/file_store.go

Ensure that compaction does not leave TSMReaders
open when complete, and that KeyIterators are all closed.

fix: ensure TSMBatchKeyIterator closes all TSMReaders

---

Cargo.lock
influxdb3_server/src/query_executor.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/catalog.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/segment_state.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This implements an index for the data in the table buffers. For now, by default, it indexes all tags, keeping a mapping of tag key/value pair to the row ids that it has in the buffer. When queries ask for record batches from the table buffer, the filter expression is evaluated to determine if a record batch can be built on the fly using only the row ids that match the index. If we don't have it in the index, the entire record batch from the buffer will be returned.
This also updates the logic in segment state to only request a record batch with the projection. The query executor was updated so that it pushes the filter and projection down to the request to get table chunks.
While implementing this, I believe I uncovered a bug where when limits are hit, a write still attempts to get …

feat: Implement index for buffer

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/file_store.go

Do not let errors on closing
a TSMReader prevent other
closes.
(cherry picked from commit 82cbdb5478af885c79a5a7dbe78c0297599bb616)
closes https://github.com/influxdata/influxdb/issues/24960

fix: ensure TSMBatchKeyIterator and FileStore close all TSMReaders (#24957)

---

.circleci/config.yml
.gitignore
Cargo.lock
influxdb3/Cargo.toml
influxdb3/src/main.rs
influxdb3_process/Cargo.toml
influxdb3_process/src/lib.rs
influxdb3_server/src/http.rs

* Setup the use of jemalloc as default allocator using `tikv-jemallocator` crate instead of `tikv-jemalloc-sys`.
You can verify jemalloc is working by doing:
```
cargo build --no-default-features
nm /target/debug/influxdb3 | rg jemalloc # produces no output
```
```
cargo build
nm /target/debug/influxdb3 | rg jemalloc # produces a bunch of output
```
* Removed `heappy` and `pprof`, and also cleaned up all the mutually exclusive compiler flags for using heappy as the allocator.
Closes #24865

chore: clean up heappy, pprof, and jemalloc

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/file_store.go

Do not let errors on closing
a TSMReader prevent other
closes.
(cherry picked from commit 82cbdb5478af885c79a5a7dbe78c0297599bb616)
closes https://github.com/influxdata/influxdb/issues/24961
(cherry picked from commit 0a4d41bc906450b2afc8137bef6ab60f08d3ba98)
closes https://github.com/influxdata/influxdb/issues/24962

fix: ensure TSMBatchKeyIterator and FileStore close all TSMReaders (#24957) (#24964)

---

go.mod
go.sum

Closes #24708
https://github.com/influxdata/influxdb/pull/24716 updated main-2.x for this, but the change didn't get pulled back to 2.7 before 2.7.6 release, so submitting against 2.7.

fix: update logrus to 1.9.3 [2.7]

---

influxdb3_write/src/lib.rs
influxdb3_write/src/wal.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs

Up to this point we assumed that a precision for everything was in nanoseconds. While we do write and persist data as nanoseconds we made this assumption for the WAL. However, we store the original line protocol data. If we want it to be replayable we would need to include the precision and use that when loading the WAL from disk. This commit changes the code to do that and we can see that that data is definitely peristed as the WAL is now bigger in the tests.
Closes # 24753

feat: Store precision in WAL for replayability

---

.circleci/config.yml

Closes https://github.com/influxdata/edge/issues/678

chore: upgrade go 1.21.9 -> 1.21.10 (1.11)

---

.circleci/config.yml

Closes https://github.com/influxdata/edge/issues/677

chore: upgrade go 1.21.9 -> 1.21.10 (master-1.x)

---

.circleci/config.yml

Closes https://github.com/influxdata/edge/issues/679

chore: upgrade go 1.21.9 -> 1.21.10 (1.10)

---

query/iterator.gen.go
query/iterator.gen.go.tmpl

Return any errors from closing a
MergeIterator

fix: return MergeIterator.Close errors

---

query/iterator.gen.go
query/iterator.gen.go.tmpl

Ensure that errors from closing the
iterators underneath a MergeIterator
are returned up the stack.
(cherry picked from commit 5fda409f39be40c0624fd1aaf38b63411b517725)
closes https://github.com/influxdata/influxdb/issues/24976

fix: return MergeIterator.Close errors (#24975)

---

influxql/query/iterator.gen.go
influxql/query/iterator.gen.go.tmpl

Ensure that errors from closing the
iterators underneath a MergeIterator
are returned up the stack.
(cherry picked from commit 5fda409f39be40c0624fd1aaf38b63411b517725)
closes https://github.com/influxdata/influxdb/issues/24977
(cherry picked from commit a97566bc31ba99916c41cef2c8135f239dc10574)
closes https://github.com/influxdata/influxdb/issues/24978

fix: return MergeIterator.Close errors (#24975) (#24997)

---

Cargo.lock
Cargo.toml

No issue for this. This brings in changes to the `IoxSystemTable` trait to support query predicates. See https://github.com/influxdata/influxdb3_core/pull/19

chore: sync latest core

---

influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This adds tracking of the instant of the last write to open buffer segment and methods to the table buffer to compute the estimated memory size of it.
These will be used by a background task that will continuously check to see if tables should be persisted ahead of time to free up buffer memory space.
Originally, I had hoped to have the size tracking happen as the buffer was built so that returning the size would be zero cost (i.e. just returning a value), but I found in different kinds of testing that I wasn't able to get something that was even close to accurate. So for now it will use this more expensive computed method and we'll check on this periodically (every couple of seconds) to see when to persist.
This is the first bit of work for #24956

feat: Add last_write_time and table buffer size

---

influxdb3/tests/server/write.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/mod.rs

* Added a reproducer to replicate the scenario described in #25006 
* Added a step in the write path to validate fields against the existing schema, to ensure that the fields being written have the same types as the existing schema
* _Note_: this incurs an extra check against each field in each line written when `accept_partial=true`; if this degrades performance, we could introduce a parameter that turns this check off, e.g., `validate_schema`, for users that don't want schema validation.
```json
{
"error":"partial write of line protocol occurred",
"data":[
{
"original_line":"t0,t0_tag0=initTag t0_f0=0u 1715694000",
"line_number":1,
"error_message":"invalid field value in line protocol for field 't0_f0' on line 0: expected type i64, but got u64"
},
{
"original_line":"t0,t0_tag0=initTag …
```

fix: writes with incorrect schema should fail

---

Cargo.lock
Cargo.toml
influxdb3_write/Cargo.toml
influxdb3_write/src/catalog.rs
influxdb3_write/src/catalog/serialize.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/snapshots/influxdb3_write__catalog__tests__catalog_serialization.snap
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Closes #25031
[`data_types::ColumnType`](https://github.com/influxdata/influxdb3_core/blob/0f5ecbd6b17f83f7ad4ba55699fc2cd3e151cf94/data_types/src/columns.rs#L295-L307) was meant for the IOx catalog and its interweaving into the catalog and related code in monolith was not absolutely necessary. This PR removes it in favour of using the [`schema::Schema`](https://github.com/influxdata/influxdb3_core/blob/0f5ecbd6b17f83f7ad4ba55699fc2cd3e151cf94/schema/src/lib.rs#L123-L149) type directly, which uses the [`InfluxColumnType`](https://github.com/influxdata/influxdb3_core/blob/0f5ecbd6b17f83f7ad4ba55699fc2cd3e151cf94/schema/src/lib.rs#L613-L633).
As part of https://github.com/influxdata/influxdb/issues/24979, removing `data_types::ColumnType` will make extending the data model to more complex …

refactor: add dedicated type for serializaing catalog tables

---

cmd/influx_inspect/deletetsm/deletetsm.go

An empty index is appropriate when deleting the last measurement.  Also clean up error handling, avoid
duplicate calls to Close.
closes https://github.com/influxdata/influxdb/issues/9929
(cherry picked from commit b09e4b751f9ac24e53558764df64b74e9b06fc3d)
closes https://github.com/influxdata/influxdb/issues/25038

fix: ignore empty index error deleting last measurement (#25037)

---

influxdb3/tests/server/query.rs
influxdb3_server/src/http.rs

This PR addresses the first part of issue #24981. It replaces the usage of `&arrow_json::writer::record_batches_to_json_rows(batches.as_slice())?` with `arrow_json::ArrayWriter` in the file `influxdb3_server/src/http.rs.`

refactor: remove arrow_batchtes_to_json

---

go.mod
go.sum

Update the flux version used in influxdb

build(flux): update flux to v0.195.1

---

cmd/influx_tools/compact/command.go
internal/tsdb_store.go
services/retention/service.go
services/retention/service_test.go
tsdb/engine.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/file_store.go
tsdb/engine/tsm1/file_store_test.go
tsdb/shard.go
tsdb/shard_test.go
tsdb/store.go
tsdb/store_test.go

Fix issue that can cause the retention service to hang waiting on a `Shard.Close` call. When this occurs, no other shards will be deleted by the retention service. This is usually noticed as an increase in disk usage because old shards are not cleaned up.
The fix adds to new methods to `Store`, `SetShardNewReadersBlocked` and `ShardInUse`. `ShardInUse` can be used to poll if a shard has active readers, which the retention service uses to skip over in-use shards to prevent the service from hanging. `SetShardNewReadersBlocked` determines if new read access may be granted to a shard. This is required to prevent race conditions around the use of `ShardInUse` and the deletion of shards.
If the retention service skips over a shard because it is in-use, the shard will be checked again the next …

fix: prevent retention service from hanging

---

influxdb3_write/src/write_buffer/mod.rs
rust-toolchain.toml

Fairly quiet update for us. The only change was around using the numeric constants now inbuilt into the primitives not the ones from `std`
https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants
Release post: https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html

chore: Update Rust to 1.79.0

---

Cargo.lock
Cargo.toml
influxdb3/tests/server/flight.rs
influxdb3/tests/server/main.rs
influxdb3/tests/server/write.rs
influxdb3_server/src/http.rs
influxdb3_write/src/catalog.rs
influxdb3_write/src/catalog/serialize.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/segment_state.rs
influxdb3_write/src/write_buffer/table_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

Closes #25033
Introduce the experimental series key feature to monolith, along with the new `/api/v3/write` API which accepts the new line protocol to write to tables containing a series key.
The series key is supported in the `schema::Schema` type by the addition of a metadata entry that stores the series key members in their correct order. Writes that are received to `v3` tables must have the same series key for every single write.
Nullability of columns is enforced in the core `schema` crate based on a column's membership in the series key. So, when building a `schema::Schema` using `schema::SchemaBuilder`, the arrow `Field`s that are injected into the schema will have `nullable` set to false for columns that are part of the series key, as well as the `time` column.
The `NOT NULL` …

feat: v3 write API with series key

---

cmd/influxd/launcher/cmd.go
cmd/influxd/launcher/launcher.go
pkg/fs/special.go
pkg/fs/special_linux.go
pkger/parser.go
pkger/parser_test.go
pkger/service.go
pkger/service_test.go

Stacks and templates allow specifying file:// URLs. Add option to disable their use for people who don't require them.

feat: disable file:// urls when hardening enabled

---

influxql/query/iterator.go
influxql/query/iterator_test.go

This is actually the second fix for
https://github.com/influxdata/influxdb/issues/20238 for when the time zone falls back in autumn.
closes https://github.com/influxdata/influxdb/issues/25078
(cherry picked from commit d60741b5063ce829cf32ca86f4746b16d1c4d31c)
closes https://github.com/influxdata/influxdb/issues/25080

fix: GROUP BY queries with offset that crosses a DST boundary fail. (#25082)

---

Cargo.lock
influxdb3/tests/server/main.rs
influxdb3/tests/server/query.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/http.rs
influxdb3_server/src/http/v1.rs

This PR is Part of #24770 
**Goal:** Extend current v1 implementation to support CSV format.
- Added `QueryFormat` enum to handle CSV, JSON, and pretty JSON formats.
- Refactored conversion of `QueryResponse` to `Bytes` to include CSV support.
Check-list:

feat: add csv influx v1

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/paths.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/wal.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persister.rs
influxdb3_write/src/write_buffer/segment_state.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This is a bit light on the test coverage, but I expect there is going to be some big refactoring coming to segment state and some of these other pieces that track parquet files in the system. However, I wanted to get this in so that we can keep things moving along. Big changes here:
* Create a persister module in the write_buffer
* Check the size of the buffer (all open segments) every 10s and predict its size in 5 minutes based on growth rate
* If the projected growth rate is over the configured limit, either close segments that haven't received writes in a minute, or persist the largest tables (oldest 90% of their data)
* Added functions to table buffer to split a table based on 90% older timestamp data and 10% newer timestamp data, to persist the old and keep the new in memory
* When …

feat: track buffer memory usage and persist

---

influxql/query/iterator.go
influxql/query/iterator_test.go

This is actually the second fix for
https://github.com/influxdata/influxdb/issues/20238 for when the time zone falls back in autumn.
closes https://github.com/influxdata/influxdb/issues/25078
(cherry picked from commit d60741b5063ce829cf32ca86f4746b16d1c4d31c)
closes https://github.com/influxdata/influxdb/issues/25080
(cherry picked from commit 0c77b4cbd2be68dc4ff7935a836f46fec2dcf0e7)
closes https://github.com/influxdata/influxdb/issues/25081

fix: GROUP BY queries with offset that crosses a DST boundary fail. (#25082) (#25087)

---

Cargo.lock
influxdb3_server/src/query_executor.rs

There were several tracing statements that were making the log output for each query rather verbose. This reduces the amount of `info!` statements by converting them to debug!, and clarifies some of the logged messages.
The type of query is also logged on the internal query log, i.e, as "sql" vs. "influxql", where before they were all "sql".
There was no issue for this.

chore: clean up log statements in query_executor

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3_write/Cargo.toml
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/buffer_segment.rs
influxdb3_write/src/write_buffer/loader.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Closes #25088
As the issue explained, there are some places where we would benefit from using the `entry_ref` API from the hashbrown crate. This PR changes the uses of `std::hashmap` that would benefit from this to the implementation of `hashbrown::HashMap`.
I ran some grep commands to find all occurrences of using `std::HashMap`, and to the best of my knowledge, the issue already listed all these cases. 
I found, for example, the following candidate to use `entry_ref`, but `Time` from core doesn't implement `From<&Time>`, which the API needs (it's also stated in the documentation) .
https://github.com/influxdata/influxdb/blob/2ddef9f8da1a0e23106bc190c641458af049435d/influxdb3_write/src/write_buffer/flusher.rs#L136
So I can't make these changes, unless …

refactor: Replace use of `std::HashMap` with `hashbrown::HashMap`

---

influxdb3_write/src/write_buffer/flusher.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/persister.rs
influxdb3_write/src/write_buffer/segment_state.rs

This refactors persisted parquet files out of the SegmentState into a new struct PersistedParquet files. The intention is to have SegmentState be only for the active write buffer that has yet to be persisted to Parquet files in object storage.
Persisted files will then be accessible throughout the system without having to touch the active in-flight write buffer.
Closes #25105

refactor: move persisted files out of segment state

---

task/backend/scheduler/scheduler_test.go
task/backend/scheduler/treescheduler.go

Avoid converting times to int64 in the Task Scheduler to 
preserve time zone information. This corrects a failure 
after fall back time changes which halts every-type tasks
closes https://github.com/influxdata/influxdb/issues/25110
(cherry picked from commit ebb597d16cd83d50e04ca9e29b6fbdee816db73c)
closes https://github.com/influxdata/influxdb/issues/25111

fix: preserve time zone information in Task Scheduler (#25112)

---

influxdb3_process/src/lib.rs

Closes #25132
This restores windows build to work again as a cfg guard was missing to bypass jemalloc on window.

fix: restore windows build to working state

---

v1/services/storage/store.go
v1/services/storage/store_test.go

Store.ValidateArgs incorrectly bounds time ranges which precede 
the Unix epoch time.
Closes https://github.com/influxdata/influxdb/issues/24669

fix: Store.validateArgs wrongfully overwriting start, end unix time

---

tsdb/shard.go

The measurementFieldSetChangeMgr has a possibly infinite loop if the writeRequests channel is closed while in the inner loop to consolidate write requests. We need to check for ok on channel receive and exit the loop when ok is false.
closes https://github.com/influxdata/influxdb/issues/25151

fix: prevent an infinite loop in measurementFieldSetChangeMgr

---

tsdb/shard.go

The measurementFieldSetChangeMgr has a possibly infinite loop if the writeRequests channel is closed while in the inner loop to consolidate write requests. We need to check for ok on channel receive and exit the loop when ok is false.
closes https://github.com/influxdata/influxdb/issues/25151
(cherry picked from commit 176fca2138a856ed54243a17d06e0926d200d382)
closes https://github.com/influxdata/influxdb/issues/25153

fix: prevent an infinite loop in measurementFieldSetChangeMgr (#25155)

---

services/storage/store.go

When querying data before 1970-01-01 (UNIX time 0) validateArgs would set start to -in64 max and end to int64 max.
closes https://github.com/influxdata/influxdb/issues/24669
Co-authored-by: Paul Hegenberg <paul.hegenberg@gmail.com>
closes https://github.com/influxdata/influxdb/issues/25149

fix: Store.validateArgs wrongfully overwriting start, end unix time (#25146)

---

influxdb3_client/src/lib.rs

Closes #25099
This PR adds methods to the `influxdb3_client` to create and delete last caches. These utilize the new APIs added in #25096 and #25097, respectively.
Unit tests were added to check the new methods with a mock server.

feat: add methods to create and delete last caches to `influxdb3_client`

---

influxdb3/src/commands/last_cache/create.rs
influxdb3/src/commands/last_cache/delete.rs
influxdb3/src/commands/last_cache/mod.rs
influxdb3/src/commands/token.rs
influxdb3/src/main.rs

Closes #25100
This PR adds a new command to the `influxdb3` CLI, which includes two sub-commands to create and delete last caches, respectively.
Here are each of their `--help` outputs:
```
Create a new last-n-value cache
Usage: influxdb3 last-cache create [OPTIONS] --dbname <DATABASE_NAME> --table <TABLE>
Options:
-h, --host <HOST_URL>                The host URL of the running InfluxDB 3.0 server [env: INFLUXDB3_HOST_URL=] [default: http://127.0.0.1:8181]
-d, --dbname <DATABASE_NAME>         The database name to run the query against [env: INFLUXDB3_DATABASE_NAME=]
--token <AUTH_TOKEN>             The token for authentication with the InfluxDB 3.0 server [env: INFLUXDB3_AUTH_TOKEN=]
-t, --table <TABLE>                  The table name for which the cache is being created
--cache-name …
```

feat: CLI to manage last caches

---

tsdb/index/tsi1/log_file.go

Closes #25181
From version 1.6.6 to 1.8.10, there are two relevant changes in `tsdb/index/tsi1/log_file.go`:
- 331569bc11d9c4212812d33305d07fdb393e4150: `f.mu.RLock()` has been used instead of `f.mu.Lock()` in [`Writes(entries []LogEntry)`](https://github.com/influxdata/influxdb/commit/331569bc11d9c4212812d33305d07fdb393e4150#diff-a32d3c62b7f891108e6cf9d79c6aea67ea7cafe3c88d0e10feb3add4b0deb64bR1076), causing an internal map to be modified for concurrent use
- 4ef4fe9aef0a75f1058e493bd7c26434f40f8b0a: Fixed the problem of the previous commit 331569bc11d9c4212812d33305d07fdb393e4150, but do not solve the write competition problem between [`ExecEntries`](https://github.com/influxdata/influxdb/commit/4ef4fe9aef0a75f1058e493bd7c26434f40f8b0a#diff-a32d3c62b7 …

fix(tsi1): fix data race between appendEntry and FlushAndSync tsi1.(*LogFile)

---

Cargo.lock
influxdb3/tests/server/client.rs
influxdb3/tests/server/main.rs
influxdb3/tests/server/system_tables.rs
influxdb3_client/src/lib.rs
influxdb3_server/src/system_tables/last_caches.rs
influxdb3_write/src/catalog.rs
influxdb3_write/src/catalog/serialize.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-allowing-time-to-persist-segments-after-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap

Last cache definitions in the catalog were augmented to either store an explicit set of column names (including time), or to accept new fields.
This will allow caches configured to store all non-key columns to be loaded properly on server restart.
Closes #25171
_Note: I do want to add tests to verify that last caches with this configuration (and others) will load properly on server start, as I have only checked that manually at this point. I filed https://github.com/influxdata/influxdb/issues/25183 to work on that._

fix: last cache catalog configuration tracks explicit vs. non-explicit value columns

---

Cargo.lock
Cargo.toml
influxdb3/Cargo.toml
influxdb3_process/Cargo.toml
influxdb3_process/src/lib.rs
rust-toolchain.toml

This commit updates us to rustc 1.80. There are two significant changes here:
1. LazyLock and LazyCell have been stabilized meaning we can replace our usage of Lazy from the once_cell crate with the std lib versions
2. Lints were added to handle unknown cfg directives. `tokio_unstable` is affected by this and while we do have the flags in our .cargo/config.toml Cargo still output a lint for it so we supress that warning now in our Cargo.toml for the workspace
Besides that it was a painless upgrade and now we're on the latest and greatest.

chore: Upgrade to rustc 1.80

---

influxdb3_write/src/catalog.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/last_cache/snapshots/influxdb3_write__last_cache__tests__catalog_initialization.snap

Part of #25183
This PR adds a unit test to check the function that initializes the last cache from a Catalog. It would also be useful to verify loading on server start/stop/restart, so I did not close the issue with this PR.

test: add a test to check last cache init from catalog

---

.circleci/config.yml

Fixes CVE-2024-24790, reported by X-Ray.

chore: upgrade go toolchain to 1.21.12

---

Cargo.lock
influxdb3_write/src/chunk.rs
influxdb3_write/src/lib.rs

This doesn't affect anything in the OSS version, but these changes are needed for Pro as part of our compactor work.

fix: make ParquetChunk fields and mod chunk pub

---

Cargo.lock
influxdb3/tests/server/query.rs
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This fixes three different bugs with the buffer. First was that aggregations would fail because projection was pushed down to the in-buffer data that de-duplication needs to be called on. The test in influxdb3/tests/server/query.rs catches that.
I also added a test in write_buffer/mod.rs to ensure that data is correctly queryable when combining with different states: only data in buffer, only data in parquet files, and data across both. This showed two bugs, one where the parquet data was being doubled up (parquet chunks were being created in write buffer mod and in queryable buffer. The second was that the timestamp min max on table buffer would panic if the buffer was empty.
Closes #25206, #25215

fix: query bugs with buffer

---

influxdb3/src/commands/serve.rs
influxdb3/tests/server/main.rs
influxdb3_server/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/paths.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs

Closes #25216
This enforces the use of a host identifier prefix in all object store paths, i.e., for parquet files, catalog files, snapshot files, and WAL files.
Both the `PersisterImpl` and `WalObjectStore` hold the host identifier prefix and use it when constructing paths to get/put files in the object store.
The `influxdb3` binary requires a new argument `--host-id` to be passed to the `serve` command that is used to specify the prefix:
```
$ influxdb3 serve --help
Run the InfluxDB 3.0 server
Usage: influxdb3 serve [OPTIONS] --host-id <HOST_IDENTIFIER_PREFIX>
Options:
[...]
--host-id <HOST_IDENTIFIER_PREFIX>
The host idendifier used as a prefix in all object store file paths
[env: INFLUXDB3_HOST_IDENTIFIER_PREFIX=]
```

feat: use host identifier prefix in object store paths

---

influxdb3_server/src/query_executor.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Follows #25225
This fixes some compiler errors that slipped through in the above PR, and also un-`pub`'s the `QueryableBuffer`, returning it to only be `pub(crate)`, which was missed in the above PR.

fix: un-pub QueryableBuffer and fix compile errors

---

services/storage/store.go

When querying data before 1970-01-01 (UNIX time 0) validateArgs would set start to -in64 max and end to int64 max.
closes https://github.com/influxdata/influxdb/issues/24669
Co-authored-by: Paul Hegenberg <paul.hegenberg@gmail.com>
closes https://github.com/influxdata/influxdb/issues/25149
(cherry picked from commit c4bfaa895417c174cef76f5308eebb6aaddbfa36)
closes https://github.com/influxdata/influxdb/issues/25150

fix: Store.validateArgs wrongfully overwriting start, end unix time (#25146) (#25165)

---

tsdb/index/tsi1/log_file.go

Extend lock lifespan to encompass the
flushAndSync() call to avoid a race
closes https://github.com/influxdata/influxdb/issues/25181
(cherry picked from commit 7333da95920a4723829ddff631df14c71cd71430)
closes https://github.com/influxdata/influxdb/issues/25186

fix(tsi1): fix data race between appendEntry and FlushAndSync tsi1.(*LogFile) (#25182)

---

Cargo.lock
deny.toml

This is a temporary change to ignore the RUSTSEC advisory causing CI failure from the recent `sqlx` vulnerability. We do not even use `sqlx` in `influxdb`, it is a nested dependency, so we can ignore this until `sqlx` releases a new version to address the advisory.
I also ran `cargo update` on this PR.

chore: ignore sqlx rustsec advisory

---

Cargo.lock
Cargo.toml

This is a small core sync to check that the latest change to remove the `cache_system` crate in core does not break `influxdb`.
The `json` feature was also added to the `reqwest` dependency, as compiler errors were popping up without it.

chore: core sync and add reqwest json feature

---

influxdb3_catalog/src/catalog.rs
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_wal/src/snapshot_tracker.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/paths.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Closes #25249
* Updated the `WalFileSequenceNumber::get` method to `as_u64` to make the method's intent clearer from the call site.
* Snapshots get their own monotonically increasing sequence number independent of the WAL file sequence number. This allows GET'ing the next snapshot file from the object store using the most recent pulled snapshot, vs. having to do a LIST operation to see if there are more snapshots.
* The most recent snapshot sequence number is used to initialize the `SnapshotTracker` on startup.
* In addition, the catalog sequence number associated with a snapshot is tracked on the `SnapshotDetails`.
* Existing tests were updated to handle the struct changes and a new test was added to the write buffer test suite that verifies when an existing snapshot is loaded, the new …

feat: snapshots track their own sequence number

---

influxdb3_write/src/cache.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

This commit does a few things:
1. It adds a u64 id field to ParquetFile
2. It gets this from an AtomicU64 so they can always use the most up to date one across threads
3. The last available file id is persisted as part of our snapshot process
4. The snapshot when loaded will set the AtomicU64 to the proper value
With this current work on the FileIndex in our Pro version will be able to utilize these ids while doing compaction and we can refer to them with a unique u64.
Closes #25250

feat: Add u64 id field to ParquetFiles

---

deny.toml
influxdb3/src/commands/serve.rs
influxdb3_server/src/builder.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Closes #25259
In addition, `deny.toml` had some incorrect field names in `[license.exceptions]`, those were fixed from `crate` to `name`.

refactor: remove `Persister` trait in favour of concrete implementation

---

influxdb3/src/commands/serve.rs
influxdb3_server/src/builder.rs
influxdb3_server/src/http.rs
influxdb3_server/src/http/v1.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

There is no issue for this. The purpose of these changes are to enable downstream implementations of the write buffer in InfluxDB Pro.
* Refactor the `WriteBufferImpl` to remove its `<T>` generic for the `TimeProvider` by using an `Arc<dyn TimeProvider>`.
* Change the type definition for `Server` and `HttpApi` to use an `Arc<dyn WriteBuffer>` instead of a generic for the write buffer.
* Make `QueryableBuffer` and its `pub(crate)` methods `pub`.
* Make the `LastCacheProvider::new_from_catalog` method `pub`.

refactor: use more `dyn Trait` in write buffer

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs

There is no issue for this PR. This is some refactoring required for downstream efforts to enable read replication.
* Moved initialization of the catalog and last cache out of the `WriteBufferImpl::new` function, and have them passed into that function as arguments. This was done so that we can initialize them independently of the write buffer, which adds a step when setting up the write buffer, but this was necessary to enable the initialization of a write buffer and read replicas that co-exist and share the catalog/last cache.
* Some error variants were added to enable the above change as well as allow for different write buffer implementations downstream.
Otherwise, there are some minor visibility changes and tweaks here and there.

refactor: move catalog and last cache initialization out of write buffer

---

influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_wal/src/serialize.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This applies some needed updates downstream in Pro.
Namely,
* visibility changes that allow types to be used in the pro buffer
* allow parsing a WAL file sequence number from a file path
* remove duplicates when adding parquet files to a persisted files list

chore: updates for pro

---

internal/authorizer.go
query/executor.go
query/subquery_test.go
services/meta/data.go
tsdb/index.go
tsdb/store.go

Closes #25212 
Backport to 1.11
(cherry picked from commit https://github.com/influxdata/influxdb/commit/2cf2103cc454b9bba4dee4fc3466669e55b1184d)

feat: add hook for optimizing series reads based on authorizer (#25207)

---

influxdb3_write/src/write_buffer/mod.rs

This commit changes the write_buffer tests to acquire a lock so that in tests where we need to have access to NEXT_FILE_ID that it won't be overwritten since rust tests run as one process and share the same statics.
While this isn't a problem for Edge as a singular process it is for our tests. It's a bit unfortunate, but this solution is the easiest and the locks are not held for long so there's no real big impact on running these tests.
Closes #25286

fix: test failure due to global static

---

Cargo.lock
Cargo.toml
influxdb3/tests/server/write.rs
influxdb3_server/src/query_executor.rs
influxdb3_server/src/system_tables/mod.rs
influxdb3_server/src/system_tables/queries.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/last_cache/table_function.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

No issue for this.
- This is a core sync that uses the `v3` feature flag on the `schema` and `influxdb_line_protocol` crates, so we can point at the main branch on core again (see https://github.com/influxdata/influxdb3_core/pull/33).
- This also brought in some recent updates to `datafusion` and IOx crates that made for some refactoring.
- One notable change upstream was the `v3` line protocol now separates the measurement name from the series key with a `,` vs. a space

chore: sync to latest core

---

etc/config.sample.toml

Closes #25294
`MaxConcurrentDeletes` should be replaced with `max-concurrent-deletes`
https://github.com/influxdata/influxdb/blob/0582cf41484da8e0ea9791381f8ededb9ae86e79/etc/config.sample.toml#L114-L117

fix(config): fix max-concurrent-deletes typo in config.sample.toml

---

query/executor.go
query/monitor_test.go
tests/server_test.go

Closes #25295
https://github.com/influxdata/influxdb/blob/0582cf41484da8e0ea9791381f8ededb9ae86e79/query/executor.go#L61-L63

fix: fix typo 'exceeed' with 'exceeded' in master-1.x

---

coordinator/points_writer.go

Closes #25290
Just remove opened `closing` in `NewPointsWriter`

fix(coordinator): fix closing opened twice in points writer

---

tsdb/shard.go

Log the path of the file being loaded, and when loglevel=debug,
log progress for each set of field changes
closes https://github.com/influxdata/influxdb/issues/25289

fix: add additional logging on loading fields.idxl files

---

services/httpd/config.go

Closes https://github.com/influxdata/feature-requests/issues/421
Adds a "flux-enabled" boolean column to our diagnostics output when calling SHOW DIAGNOSTICS;
With flux disabled in influxdb.conf
```
name: config-httpd
access-log-path bind-address enabled flux-enabled https-enabled max-connection-limit max-row-limit
--------------- ------------ ------- ------------ ------------- -------------------- -------------
:8086        true    false        false         0                    0
```
With flux enabled in influxdb.conf
```
name: config-httpd
access-log-path bind-address enabled flux-enabled https-enabled max-connection-limit max-row-limit
--------------- ------------ ------- ------------ ------------- -------------------- -------------
:8086        true    true         false         0 …
```

feat(edge): Add 'flux enabled' to 'show diagnostics'

---

tsdb/shard.go

Log the path of the file being loaded, and when level=debug log progress fpr each set of field changes
closes https://github.com/influxdata/influxdb/issues/25289
(cherry picked from commit 5d8d1120e1ba060b0842d533953519fc5cd1aeed)
closes https://github.com/influxdata/influxdb/issues/25310

fix: add additional logging on loading fields.idxl files (#25309)

---

tsdb/shard.go

Log the path of the file being loaded, and when level=debug log progress for each set of field changes
closes https://github.com/influxdata/influxdb/issues/25289
(cherry picked from commit 5d8d1120e1ba060b0842d533953519fc5cd1aeed)
closes https://github.com/influxdata/influxdb/issues/25311
(cherry picked from commit 96c97a76f4d4c7bfb96a4a90cbf7fb36bbbcd083)
closes https://github.com/influxdata/influxdb/issues/25313

fix: add additional logging on loading fields.idxl files (#25309) (#25319)

---

influxdb3/tests/server/auth.rs
influxdb3/tests/server/main.rs

Closes #25321 
This makes some changes to the TestServer E2E framework, which is used for running integration tests in the `influxdb3` crate. These changes are meant so that we can more easily split the code for pro.

test: split e2e test harness up for pro

---

tsdb/engine.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/file_store.go
tsdb/engine/tsm1/wal.go
tsdb/index.go
tsdb/shard.go
tsdb/store.go
tsdb/store_test.go

Improve error messages and logging during shard opening.
Ported from master-1.x.
(cherry picked from commit 23008e5286d0161a6add86e5676ee633871c1d45)
Closes: #25328

chore: improve error messages and logging during shard opening

---

.circleci/config.yml
deny.toml

This changes our CI to use cargo-nextest which is faster and does not
have issues around global statics. Since it runs each test in it's
own process we don't have to worry about tests stepping on each other's
toes in this regard. It also updates the CI to ignore the current
cargo deny failure as we can't do anything until the arrow crates are
upgraded.

feat: change CI to use cargo-nextest

---

tsdb/index/tsi1/index.go
tsdb/index/tsi1/partition.go
tsdb/index/tsi1/partition_test.go

* fix(tsi1/partition/test): fix data races in test code
This PR is like influxdata/influxdb#24613 but solves it with a setter method for MaxLogFileSize which allows unexporting that value and MaxLogFileAge. There are actually two places locks were needed in test code. The behavior of production code is unchanged.
(cherry picked from commit f0235c4daf4b97769db932f7346c1d3aecf57f8f)
Closes #

fix(tsi1/partition/test): fix data races in test code (#57)

---

Cargo.lock
Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
influxdb3_write/src/write_buffer/validator.rs

- uses Arc<str> to represent create once and read everywhere type of string
- updated snapshots for insta asserts, uses redaction to hardcode randomly generated UUID strings
- added methods to catalog to expose instace and host ids
Closes: https://github.com/influxdata/influxdb/issues/25315

feat: add instance id and host id to catalog

---

tsdb/index/tsi1/partition.go

* fix(tsi1/partition/test): fix data races in test code (#57)
* fix(tsi1/partition/test): fix data races in test code
This PR is like influxdata/influxdb#24613 but solves it with a setter method for MaxLogFileSize which allows unexporting that value and MaxLogFileAge. There are actually two places locks were needed in test code. The behavior of production code is unchanged.
(cherry picked from commit f0235c4daf4b97769db932f7346c1d3aecf57f8f)
* feat: modify error handling to be more idiomatic
closes https://github.com/influxdata/influxdb/issues/24042
* fix: errors.Join() filters nil errors
closes https://github.com/influxdata/influxdb/issues/25341 ---------
Co-authored-by: Phil Bracikowski <13472206+philjb@users.noreply.github.com>
(cherry picked from commit …

fix(tsi1/partition/test): fix data races in test code (#57) (#25338)

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap

- when no catalog is found, create a new one with instance id and persist it immediately
- enabled test-log in influxdb3_write
Closes: https://github.com/influxdata/influxdb/issues/25346

refactor(catalog): catalog initialisation refactor

---

.circleci/config.yml
go.mod

Closes https://github.com/influxdata/edge/issues/744

chore: upgrade go 1.21.12 -> 1.22.7

---

Cargo.lock
Cargo.toml
influxdb3/Cargo.toml
influxdb3_telemetry/Cargo.toml
influxdb3_telemetry/src/lib.rs

- `TelemetryStore` is exposed for holding telemetry samples
- added influxdb3_telemetry dependency to influxdb3 crate

feat(telemetry): added basic types

---

Cargo.lock
Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3_telemetry/Cargo.toml
influxdb3_telemetry/src/cpu_mem_sampler.rs
influxdb3_telemetry/src/lib.rs
influxdb3_telemetry/src/sender.rs
influxdb3_telemetry/src/stats.rs
influxdb3_telemetry/src/store.rs

- basic setup to initialise the static values for telemetry store added.
- cpu and memory used by influxdb3 is sampled at 1min interval
- some minor tidyups
Closes: https://github.com/influxdata/influxdb/issues/25370, https://github.com/influxdata/influxdb/issues/25371

feat(telemetry): static values, cpu and mem metrics gathering

---

tsdb/engine/tsm1/file_store.go

Replace uses of `%v` with `%w` where appropriate in file_store.go
Closes: #25357

chore: replace uses of %v with %w

---

influxdb3/tests/server/auth.rs
influxdb3_server/src/http.rs

closes: https://github.com/influxdata/influxdb/issues/25394

feat(auth): allow Token or Bearer as valid schemes

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/parquet_cache/mod.rs
influxdb3_write/src/write_buffer/mod.rs

Closes #25382 
Closes #25383 
This refactors the parquet cache to use less locking by switching from using the `clru` crate to a hand-rolled cache implementation. The new cache still acts as an LRU, but it uses atomics to track hit-time per entry, and handles pruning in a separate process that is decoupled from insertion/gets to the cache.
The `Cache` type uses a [`DashMap`](https://docs.rs/dashmap/latest/dashmap/struct.DashMap.html) internally to store cache entries. This should help reduce lock contention, and also has the added benefit of not requiring mutability to insert  into _or_ get from the map.
The cache maps an `object_store::Path` to a `CacheEntry`. On a hit, an entry will have its `hit_time` (an `AtomicI64`) incremented. During a prune operation, entries that have the oldest …

refactor: parquet cache with less locking

---

services/httpd/handler.go
services/httpd/handler_test.go

When searching for a measurement in the v2/delete API, remove any quotes put on the measurement name (e.g. to alllow special characters) before string comparisons.
closes https://github.com/influxdata/influxdb/issues/25406

fix: strip double quotes from measurement names in v2/delete

---

coordinator/statement_executor_test.go
internal/tsdb_store.go

Fix `MeasurementNamesFn` missing `retentionPolicy` parameter caused by #22388.

test: fix MeasurementNamesFn missing retentionPolicy parameter caused by #22388

---

cmd/influxd/backup_util/backup_util.go

Closes #25361
Use ``separatorRegexp = regexp.MustCompile(`[/\\]`)`` to `Split` instead of `strings.Split(path, string(filepath.Separator))`

fix(backup): fix DBRetentionAndShardFromPath parsing error between different OS

---

influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/parquet_cache/mod.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Checked that the parquet cache will serve queries when chunks are requested from the write buffer. The added test also checks for get_range requests made to the object store, which are typically made by DataFusion to infer schema for parquet files.
Closes #25392

test: check parquet cache in the write buffer

---

influxdb3/src/commands/serve.rs
influxdb3_write/src/parquet_cache/mod.rs

Closes #25395
This adds the following options to the `influxdb3 serve` CLI:
```
--parquet-mem-cache-size <PARQUET_MEM_CACHE_SIZE>
The size of the in-memory Parquet cache in bytes
[env: INFLUXDB3_PARQUET_MEM_CACHE_SIZE=]
[default: 1073741824]
--parquet-mem-cache-prune-percentage <PARQUET_MEM_CACHE_PRUNE_PERCENTAGE>
The percentage of entries to prune during a prune operation on the in-memory Parquet cache
[env: INFLUXDB3_PARQUET_MEM_CACHE_PRUNE_PERCENTAGE=]
[default: 0.1]
--parquet-mem-cache-prune-interval <PARQUET_MEM_CACHE_PRUNE_INTERVAL>
The interval on which to check if the in-memory Parquet cache needs to be pruned
[env: INFLUXDB3_PARQUET_MEM_CACHE_PRUNE_INTERVAL=]
[default: 10ms]
--disable-parquet-mem-cache
Disable the in-memory Parquet cache
[env: …
```

feat: enable parquet cache config through CLI

---

influxdb3/src/commands/serve.rs

No issue, this includes a fix for a mistake made in https://github.com/influxdata/influxdb/pull/25415 where the MB parquet cache size was not being multiplied correctly when creating the cache for the `influxdb3 serve` command.
Related to https://github.com/influxdata/influxdb/issues/25347

fix: use correct multiplier for parquet cache size

---

deny.toml

We will need to wait on the RUSTSEC advisory to be resolved upstream, i.e., by having tonic and hyper upgraded in core, before we can lift this advisory ignore and use the latest versions of those crates.

chore: unblock CI for tonic/hyper audit failures

---

Cargo.lock
Cargo.toml
influxdb3_test_helpers/Cargo.toml
influxdb3_test_helpers/src/lib.rs
influxdb3_test_helpers/src/object_store/mod.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/parquet_cache/mod.rs
influxdb3_write/src/write_buffer/mod.rs

This adds a new crate `influxdb3_test_helpers` which provides two object store helper types that can be used to track request counts made through the store, as well as synchronize requests made through the store, resp.
These replace the `TestObjectStore` type that was added in the `influxdb3_write/src/parquet_cache` module and will be used in testing the parquet cache in pro for read replicas.
Related to #25347

test: add test helpers for object store types

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_telemetry/Cargo.toml
influxdb3_telemetry/src/sender.rs
influxdb3_telemetry/src/store.rs
influxdb3_write/src/write_buffer/persisted_files.rs

- added mechanism within PersistedFile to expose parquet file related metrics. The details are updated when new snapshot is generated and also when all snapshots are loaded when the process starts up
- at the point of creating the telemetry payload these parquet metrics are looked up before sending it to the server.
Closes: https://github.com/influxdata/influxdb/issues/25418

feat: telemetry report for parquet metrics

---

influxdb3_write/src/parquet_cache/mod.rs

This adds a watch channel to check for when prunes have happened on the parquet cache oracle, so we can notify something, like a test, that needs to know when a prune has happened.
This should make the cache eviction test in the parquet_cache module not flake out anymore.
There is no issue for this.

fix: flaky parquet cache for real this time

---

influxdb3_write/src/paths.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Cleans up a legacy method for producing parquet file paths that was no longer used in release code (was only being used in tests) and makes the method that produces the parquet file path using a WAL sequence number and i64 timestamp the defaul `new` constructor for the `ParquetFilePath` type.
Tests that checked this function were modified accordingly.
Closes #25387

fix: add host id to parquet file paths

---

influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_server/src/http.rs
influxdb3_server/src/query_executor.rs
influxdb3_server/src/system_tables/parquet_files.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/last_cache/table_function.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
influxdb3_write/src/write_buffer/validator.rs

This is some follow up work to #25421 where we move the table mapping into the DatabaseSchema struct itself. This code as a result has been simplified compared to the original version and has the following changes:
- By using the DatabaseSchema over the catalog in as many places as possible, we reduce the number of locks that we need to take on the Catalog. In many places we already had access to the schema and so this simplified things as we now would not need to look up tables with both the database id and the name/id of the table
- Code centered on making sure the ids was updated so that it only needed to occur when applying catalog ops
- We still need to add the id to name mapping in the validate lines fns for both v1 and v2, but it's now in the same spot as when we insert the table …

feat: move Table Id/Name mapping into DB Schema

---

Cargo.lock
Cargo.toml
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_telemetry/Cargo.toml
influxdb3_telemetry/src/lib.rs
influxdb3_telemetry/src/sampler.rs
influxdb3_telemetry/src/sender.rs
influxdb3_telemetry/src/stats.rs
influxdb3_telemetry/src/store.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/write_buffer/persisted_files.rs

- Introduced traits, `ParquetMetrics` and `SystemInfoProvider` to enable writing easier tests
- Uses mockito for code that depends on reqwest::Client and also uses  mockall to generally mock any traits like `SystemInfoProvider`
- Minor updates to docs

refactor: Tidy up telemetry tests

---

.circleci/config.yml
.circleci/scripts/package-validation/validate
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_telemetry/src/sender.rs
influxdb3_telemetry/src/store.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/validator.rs

Add inclusivity checks to the build and fail if using non-inclusive language. The codebase is already quite clean with just a handful of fixes needed.
The output when encountering non-inclusive language is clear and actionable. Eg:
```
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap:71:14-19: `dummy` may be insensitive, use `placeholder`, `sample` instead (error)
"host_id": "dummy-host-id",
```
Other tools exist, but the `woke` tool is easy to use, supports overrides and is used by a lot of companies and projects (2.5M downloads). Sadly, the underlying tool's name may elicit negative responses from some, but this PR is not about any of that. It is about creating and maintaining an inclusive environment when developing InfluxDB.
References:
- …

feat(circleci): add inclusivity checks

---

influxdb3_write/src/parquet_cache/mod.rs
run-tests.sh

When running the tests repeatedly the tests failed intermittently as the background runner wakes up to prune the cache and the tests are loading and removing the data. The check whether `n_to_prune` is greater than 0 before going ahead with pruning fixes the issue
Closes: https://github.com/influxdata/influxdb/issues/25446

fix: check num items to prune before pruning parquet cache

---

.circleci/config.yml

In thinking about PR #25437 more, I couldn't help but feel like the choice of tool (ie, it's name) could perhaps be a distraction for some contributors. Since the [tool itself](https://github.com/get-woke/woke) is popular, easy to use, etc I decided to [fork the project](https://github.com/jdstrand/language-checker) and update influxdb to use the fork instead to reduce any impediments to contribution.

chore(circleci): update to use language-checker

---

cmd/influxd/launcher/cmd.go
tsdb/config.go
tsdb/config_test.go
tsdb/engine.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go
tsdb/engine/tsm1/wal.go
tsdb/shard.go
tsdb/store.go
tsdb/store_test.go

Add `--storage-wal-flush-on-shutdown` to flush WAL on database shutdown. On successful shutdown, all WAL data will be committed to TSM files and the WAL directories will not contain any .wal files.
Closes: #25422

feat: add option to flush WAL on shutdown

---

influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/serialize.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap

This commit adds the column_id field to ColumnDefinition so that the output for a Catalog will contain the id of that column. This is non unique, whereas TableIds and DbIds will be unique. The column_id corresponds to it's index in the schema.
Closes #25386

feat: Add non-unique u16 Id to ColumnDefinition

---

influxdb3_catalog/src/catalog.rs
influxdb3_server/src/http.rs
influxdb3_server/src/query_executor.rs
influxdb3_server/src/system_tables/parquet_files.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/last_cache/table_function.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

This extends the Catalog and underlying DatabaseSchema API to make accessing database and table schema, as well as their IDs moreconvenient.
For example, instead of having to call `db_name_to_id`, then use that ID to call `db_schema`, this just reverts `db_schema` to be called with the name, and handles the ID conversion internally.
A `db_schema_by_id` method was added where we are accessing via the ID.
This would reduce the number of read locks acquired from two down to one.
The `db_name_to_id` and `db_id_to_name` methods are still available in the API in case they are needed, but these changes make them less needed throughout our codebase.
Otherwise, I changed the arg to be `impl Into<Arc<str>>` instead of `Arc<str>`, which allows us to pass in `&str`s without having to call `.into()`. …

refactor: improvements to the catlog API

---

influxdb3/src/commands/serve.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/lib.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_server/src/system_tables/parquet_files.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/last_cache/table_function.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Separate out methods of the Catalog API that are used on the query side into a new trait `DatabaseSchemaProvider`. The new trait includes methods from the Catalog that get the underlying `DatabaseSchema` or interact with names/IDs.
This will allow for a separate implementation of the Catalog for pro that only needs to hold a replicated/combined view in-memory of one or more catalogs without the need to do persistence that a write buffer's catalog needs to do.
While in there I also switched the `QueryExecutorImpl::new` method to take an args struct to avoid the clippy lint.

refactor: separate catalog schema API

---

cmd/influx/main.go
importer/v8/importer.go

Allow `influx -import` to import from stdin by specifying `-` as the path. Example: `influx -import -path -`

feat: allow `influx -import` to import from stdin

---

influxdb3/src/commands/serve.rs
influxdb3_telemetry/src/sender.rs
influxdb3_telemetry/src/store.rs

Allow the endpoint for telemetry to be passed in via the cli args, e.g
```
--telemetry-endpoint "https://somehost/test/"
```
and the actual endpoint always appends `v3` to it. So, above URL becomes "https://somehost/test/v3"

feat: allow telemetry endpoint to be passed in

---

tsdb/shard_internal_test.go
tsdb/store.go
tsdb/store_test.go

This PR adds test and new method to clear out the bad shards list
the method will return the values of the shards that it cleared out
along with the errors. This is the first part in the feature
for adding a load-shards command to influxd-ctl.
companion PR: https://github.com/influxdata/plutonium/pull/4193
Closes https://github.com/influxdata/feature-requests/issues/591

feat: Adds functionality to clear out bad shard list 

---

Cargo.toml

No issue for this, but this adds the `"yaml"` feature to our [`insta`](https://insta.rs/) dependency, which provides a much better user-experience when doing snapshot tests, via the `insta::assert_yaml_snapshot()` macro. YAML is easier to read than JSON, and it also can serialize integers as keys, which is useful for our various ID types.

feat: add insta crate yaml feature

---

influxdb3_catalog/src/catalog.rs
influxdb3_write/src/last_cache/mod.rs

No issue, this changes the function signature for the `Catalog::insert_database` method to take `&self` instead of `&mut self`, the latter being unnecessary since the type allows interior mutability.

refactor: method on catalog did not need mut self

---

influxdb3/src/commands/common.rs
influxdb3/src/commands/last_cache/create.rs

Correctly parse key and value column args to create last cache command.

fix: last cache cli parser bug

---

influxdb3_server/src/lib.rs

closes: https://github.com/influxdata/influxdb/issues/25466

feat: set tcp_nodelay in hyper builder

---

cmd/influxd/launcher/launcher_test.go

fix: correct flaky test (TestLauncher_PIDFile_Locked)

---

cmd/influxd/launcher/cmd.go
cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/launcher_helpers.go
cmd/influxd/launcher/launcher_test.go

Add `--pid-file` option to write PID files on startup. The PID filename is specified by the argument after `--pid-file`. If the PID file already exists, influxd will exit unless the `--overwrite-pid-file` flag is also used.
Example: `influxd --pid-file /var/lib/influxd/influxd.pid`
PID files are automatically removed when the influxd process is shutdown.
Closes: #25498 
(cherry picked from commit c35321b470b319738b8e7bfaf04f693597d4691a)
(cherry picked from commit 48f760065bdb7c8272909d6509589650be1be8a6)

feat: add `--pid-file` option to write PID files

---

scripts/fetch-ui-assets.sh

Upgrade UI assets package to OSS 2.7.10.
Closes: #25504
(cherry picked from commit 9d9e92c67d868c5a3906eef1d15c664f845e4b9d)

chore: upgrade ui assets package to 2.7.10

---

services/httpd/handler.go
services/httpd/handler_test.go

When searching for a measurement in the v2/delete API, remove any quotes put on the measurement name (e.g. to alllow special characters) before string comparisons.
closes https://github.com/influxdata/influxdb/issues/25406
(cherry picked from commit e3e9232de528b7566ad239f6879c98d94ce8707a)
closes https://github.com/influxdata/influxdb/issues/25476

fix: strip double quotes from measurement names in v2/delete (#25407)

---

cmd/influxd/run/startup_logger.go
storage/engine.go
tsdb/store.go
tsdb/store_test.go

* feat(tsdb): Adds shard opening progress checks to startup
This PR adds a check to see how many shards are remaining
vs how many shards are opened. This change displays the percent
completed too.
closes influxdata/feature-requests#476
(cherry picked from commit 3c87f52)
closes #25506

feat(logging): Add startup logging for shard counts (#25378)

---

Dockerfile

No issue for this. The cache target for Rust build artefacts in the `Dockerfile` was still set to the old `influxdb_iox` directory. This changes it over to the `influxdb3` directory.

fix: the cache target for build artefacts in Dockerfile

---

cmd/influxd/run/startup_logger.go
storage/engine.go
tsdb/store.go
tsdb/store_test.go

* feat(logging): Add startup logging for shard counts (#25378) This PR adds a check to see how many shards are remaining vs how many shards are opened. This change displays the percent completed too.
closes influxdata/feature-requests#476
(cherry picked from commit 3c87f52)
closes https://github.com/influxdata/influxdb/issues/25506
(cherry picked from commit 2ffb108a270b076fafee03fda1a0dd9de631e4ff)

feat(logging): Add startup logging for shard counts (#25378) (#25507)

---

influxdb3/src/commands/serve.rs
influxdb3_telemetry/src/sender.rs

closes: https://github.com/influxdata/influxdb/issues/25502

fix: default url for telemetry should include protocol

---

Cargo.lock
Cargo.toml
deny.toml
influxdb3_write/src/write_buffer/table_buffer.rs

`cargo deny` was showing that no crate matched the advisory criteria for this [RUSTSEC advisory](https://rustsec.org/advisories/RUSTSEC-2024-0376.html), so this PR removes the ignore entry.
In addition, the `hashbrown` crate was causing a new audit failure, and updating it required that the `Zlib` license be added to our list of allowed licenses.
No issue for this, but it is blocking another PR at the moment (https://github.com/influxdata/influxdb/pull/25515).

chore: remove unnecessary rustsec for the tonic cve

---

influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/validator.rs

The write validator now builds the row data destined for the WAL directly, vs. creating an intermediate type to hold row data.
This also extends the test in the write validator to test the new vs. existing table code paths.
Closes #25512

refactor: remove conversion step in validator

---

influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Closes #25519
This alters the eviction behaviour of the last-n-value cache:
* The cache, when queried, will not produce entries that are expired. This actually wasn't done before, which would have been a bug, but this also allows us to more leniently run cache eviction.
* The process that runs eviction on the `LastCacheProvider` is now run in the background, by default, every `1m`, but the interval can be configured by the user on server start with the `--last-cache-eviction-interval` argument.
* Cache eviction is no longer run on every buffered write, which should reduce lock contention

feat: configurable last cache eviction

---

influxdb3_catalog/src/catalog.rs
influxdb3_wal/src/create.rs
influxdb3_wal/src/lib.rs

Closes #25524
In addition to throwing an error when an `AddFields` operation is applied for a table that does not exist, this PR adds some helper methods to the `influxdb3_wal` crate for creating WAL operations that were previously added in pro.
A test was added to check for the failure condition.

fix: throw error when adding fields to non-existent table in WAL

---

influxdb3_catalog/src/catalog.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/paths.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

Updates the catalog to use its own sequence number in the path. This will enable downstream Pro systems that pick up PersistedSnapshots to get the specific catalog that a snapshot is associated with since its sequence number is included.
Also updated the type to be CatalogSequenceNumber to make it more clear & readable when being used.

feat: Update catalog to use sequence number in path

---

tsdb/store.go
tsdb/store_test.go

Changes to `loadShards` to support a 2.x feature without making it difficult to keep TSM code in sync. Also includes minor code quality improvements.

chore: loadShards changes to more cleanly support 2.x feature

---

Cargo.lock
Cargo.toml
deny.toml
influxdb3_catalog/Cargo.toml
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_wal/Cargo.toml
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

- arrow/parquet deps are patched (as in core)
- three specific code changes to cope with changes in core crates
- TransitionPartitionId, use `from_parts` instead of `new`
- arrow buffers can take &[u8] directly without `to_vec()`/`vec!`
(used only in tests)
- `schema` and `influxdb_line_protocol` crates need `v3` feature enabled

chore: update core deps

---

tsdb/store_test.go

Remove unnecessary fmt.Sprintf calls for static code checks in main-2.x.

chore: remove unnecessary fmt.Sprintf calls

---

influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/snapshots/influxdb3_write__persister__tests__persisted_snapshot_structure.snap

refactor: use `SerdeVecMap` in `PersistedSnapshot`

---

influxdb3_write/src/persister.rs

This commit changes the code so that we only keep the 10 most recent Catalogs. When a new one is persisted we delete any old ones that exist. If the deletion would fail we don't panic and let a future persist cleanup the catalogs rather than failing the persist itself. This commit also adds a test to make sure that only the catalogs we expect to are deleted on persist.

feat: delete old Catalogs on persist

---

cmd/influx_inspect/buildtsi/buildtsi.go

Output for re-building TSI now includes a completion log
example: 
```
......
renaming new segment "/Users/devan/.influxdb/data/tstestdbthree/_series/00/0000.tmp" to "/Users/devan/.influxdb/data/tstestdbthree/_series/00/0000"
renaming new segment "/Users/devan/.influxdb/data/tstestdbthree/_series/07/0000.tmp" to "/Users/devan/.influxdb/data/tstestdbthree/_series/07/0000"
removing index file /Users/devan/.influxdb/data/tstestdbthree/_series/07/index
removing index file /Users/devan/.influxdb/data/tstestdbthree/_series/00/index
compacted  /Users/devan/.influxdb/data/tstestdbthree/_series/00
compacted  /Users/devan/.influxdb/data/tstestdbthree/_series/01
compacted  /Users/devan/.influxdb/data/tstestdbthree/_series/02
compacted  /Users/devan/.influxdb/data/tstestdbthree/_series/03
compacted …
```

feat(influx_inspect): Adds an additional log to rebuild TSI

---

services/subscriber/service.go

Log writes to subscriptions that are rejected because
the queue is full by bytes or by length metrics.

fix: log rejected writes to subscriptions

---

Cargo.lock
influxdb3_server/src/builder.rs
influxdb3_server/src/grpc.rs
influxdb3_server/src/http.rs
influxdb3_server/src/http/v1.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs

- This commit moves `QueryExecutorImpl` behind a `dyn` (trait object) as we have other impls in core for `QueryExecutor` and this will keep both pro and OSS traits in sync
The other commit fixes the errors picked up by audit job, below is the summary
- address https://rustsec.org/advisories/RUSTSEC-2024-0399.html by running `cargo update --precise 0.23.18 --package rustls@0.23.14`
- address yanked version of `url` crate (2.5.3) by running `cargo update -p url`
(No issue)

feat: make query executor as trait object

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3/tests/server/configure.rs
influxdb3/tests/server/query.rs
influxdb3_cache/Cargo.toml
influxdb3_cache/src/meta_cache/cache.rs
influxdb3_cache/src/meta_cache/mod.rs
influxdb3_cache/src/meta_cache/provider.rs
influxdb3_catalog/src/catalog.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_wal/src/lib.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/last_cache/mod.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

Closes #25546 
Closes #25547
Adds two new APIs:
* `POST /api/v3/configure/meta_cache`: create a metadata cache
* `DELETE /api/v3/configure/meta_cache`: delete a metadata cache
These operations, like similar for the last cache, tie into the WAL; so corresponding catalog/WAL operations were added for both create/delete.
An integration test was added in the `influxdb3` crate for both of these APIs, and in addition, a test was added to check that the metadata cache can be queried via the `/api/v3/query_sql` API.
Also made some QoL improvements to the `WriteBufferImpl` and `QueryExecutorImpl` by using arg structs in their `new` constructors.

feat: metacache REST APIs to create and delete

---

influxdb3/tests/server/flight.rs
influxdb3/tests/server/main.rs
influxdb3/tests/server/system_tables.rs
influxdb3_cache/src/meta_cache/cache.rs
influxdb3_cache/src/meta_cache/provider.rs
influxdb3_server/src/system_tables/meta_caches.rs
influxdb3_server/src/system_tables/mod.rs

This adds a new system table "meta_caches" that allows users to view the state of their metadata caches on a per-db basis
An integration test was added to verify that it works.
Closes #25545

feat: meta_caches system table

---

influxdb3/src/commands/meta_cache/create.rs
influxdb3/src/commands/meta_cache/delete.rs
influxdb3/src/commands/meta_cache/mod.rs
influxdb3/src/main.rs
influxdb3/tests/server/cli.rs
influxdb3_client/src/lib.rs

This follows #25593.
This adds two new CLI commands to the `influxdb3` binary:
* `influxdb3 meta-cache create`
* `influxdb3 meta-cache delete`
To create and delete metadata caches, respectively.
A basic integration test was added to check that this works E2E.
The `influxdb3_client` was updated with methods to create and delete metadata caches, and which is what the CLI commands use under the hood.
Closes #25548

feat: CLI to create and delete metadata caches

---

influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_server/src/query_planner.rs

Related to #25562
This follows changes that were made in `influxdb_iox` to improve the handling of concurrent queries (see https://github.com/influxdata/influxdb_iox/pull/11029). Those can be seen in action in `influxdb3_core` in the flight service here: https://github.com/influxdata/influxdb3_core/blob/6fcbb004232738d55655f32f4ad2385523d10696/service_grpc_flight/src/lib.rs#L664-L679
Though we use that flight service for servicing gRPC requests, our code for handling queries made via the REST API was still performing query planning on the IO thread pool.
Query planning is CPU intensive, so can throttle the amount of requests that can be handled concurrently. This offloads the planning to the DataFusion thread pool in the REST API.
A `Planner` type was added as a central point for handling …

fix: plan queries on DF threadpool to not block IO in REST API

---

influxdb3_client/src/lib.rs
influxdb3_write/src/last_cache/mod.rs
rust-toolchain.toml

No issue for this. This updates the Rust toolchain to the latest 1.83.0 release

chore: upgrade to rust 1.83.0

---

influxdb3_sys_events/src/lib.rs

- This commit allows `RecordBatch` to be created directly from sys event store. It means we can avoid cloning events and avoids creating intermediate vec. To achieve that, there's a new method `to_record_batch` that's been added with a trait bound `ToRecordBatch` that events are expected to implement.
closes: https://github.com/influxdata/influxdb/issues/25609

feat: tidy up sys event store

---

influxdb3_cache/src/last_cache/cache.rs
influxdb3_cache/src/last_cache/mod.rs
influxdb3_cache/src/last_cache/provider.rs
influxdb3_cache/src/last_cache/table_function.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/write_buffer/mod.rs

Predicate handling in the last-n-value cache was refactored. As per the related issue, the main reason for this was to make it possible to verify that predicate pushdown is happening in the last cache.
A lot of the changes here are very similar to the implementation in the metadata cache:
* use DataFusion to analyze the query predicates and convert them to either an inclusive or exclusive set
* update the `Predicate` type to support only those variants, i.e., by removing the `Eq` and `NotEq` variants.
* implement a custom `ExecutionPlan` for the last cache that captures the predicates that are pushed down to the cache
* add a test that verifies the predicate conversion and pushdown
One of the key aspects of this change is that the predicate pushdown can be verified using `EXPLAIN` on a …

feat: LastCacheExec to track predicate pushdown in last cache queries

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3/tests/server/query.rs
influxdb3/tests/server/snapshots/server__query__api_v3_query_sql_meta_cache.snap

No issue for this here, but this is related to an issue for performance testing the metadata cache in Pro (https://github.com/influxdata/influxdb_pro/issues/218). This just checks that queries to the metadata cache, which uses Arrow's `Utf8View` type, can be written as JSON in API responses.

test: metadata cache query using JSON format

---

influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs

Part of #25627 
This removes the query concurrency limit (which was previously hard-coded to `10`) by setting the query semaphore limit in the `QueryExecutorImpl` to [`tokio::sync::Semaphore::MAX_PERMITS`](https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html#associatedconstant.MAX_PERMITS).
This does not close the related issue, as the concurrency should probably have _at least_ a configurable limit.

refactor: remove query concurrency limit

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_cache/Cargo.toml
influxdb3_cache/src/parquet_cache/metrics.rs
influxdb3_cache/src/parquet_cache/mod.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/src/write_buffer/mod.rs

Closes #25427
Adds metrics to track the following in the in-memory parquet cache:
* cache size in bytes (also included a fix in the calculation of that)
* cache size in n files
* cache hits
* cache misses
* cache misses while the oracle is fetching a file
A test was added to check this functionality

feat: track parquet cache metrics

---

influxdb3_catalog/src/catalog.rs

In adding additional CatalogOps for Processing Engine Plugins and Triggers, I had to work through `new_if_updated_batch()`. The intention is reasonable, which is to process CatalogOps and if they _do_ update the DatabaseSchema, return a new copy that can then be inserted. However, this is done by updating a bunch of state inside the method as the ops are iterated. This ends up relying on brittle assumptions, mainly that there won't be a bunch of different operations in a single CatalogBatch, for instance that there won't be multiple deletes or a delete followed by a table creation. 
I pulled out the logic into a couple of traits, one or DB level changes and another for table updates. Among other things this will make #25639 cleaner.

refactor(catalog): Rework how CatalogOps update the DatabaseSchema

---

.circleci/config.yml

This builds and pushes artifacts to the snapshot bucket on merge to main. The snapshot workflow does not include the tests run from within the PR as it would duplicate work and increase CI costs.

feat: publish snapshot on merge to main

---

Cargo.lock
Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3_cache/src/last_cache/snapshots/influxdb3_cache__last_cache__tests__catalog_initialization.snap
influxdb3_client/src/lib.rs
influxdb3_server/src/lib.rs
influxdb3_wal/Cargo.toml
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_wal/src/serialize.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

feat: add startup time to logging output 
This change adds a startup time counter to the output when starting up
a server. The main purpose of this is to verify whether the impact of
changes actually speeds up the loading of the server.
feat: Significantly decrease startup times for WAL 
This commit does a few important things to speedup startup times:
1. We avoid changing an Arc<str> to a String with the series key as the
From<String> impl will call with_column which will then turn it into
an Arc<str> again. Instead we can just call `with_column` directly
and pass in the iterator without also collecting into a Vec<String>
2. We switch to using bitcode as the serialization format for the WAL.
This significantly reduces startup time as this format is faster to
use instead of JSON, which …

feat: Significantly decrease startup times for WAL

---

influxdb3_sys_events/benches/store_benchmark.rs
influxdb3_sys_events/src/lib.rs

move ringbuffer to be allocated on heap as the MAX_CAPACITY per event type has gone up to 10k
(no issue)

chore: porting the changes from pro

---

Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3_catalog/src/catalog.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs

This changes the code to reference InfluxDB 3 OSS rather than Edge which had been it's original name when we first started the project. With this we now have the code reflect what we are actually calling it. On top of this the long help text has been changed to give advice about how to actually run the code now with the bare minimum set of flags needed now as `influxdb serve` is no longer a viable command on it's own.
Closes #25649

fix: Change references of Edge into OSS

---

influxdb3_id/src/lib.rs

With this change we now provide a check for new IDs for overflow. This will cause the system to panic on overflow now rather than causing silent corruption as this is an unrecoverable state. While this is a highly unlikely scenario given how big the id numbers can be, it would be better to have this in place now, rather than trying to figure out a subtle nasty corruption bug later.
Closes #25542

fix: move to fetch_update from fetch_add for IDs

---

Cargo.lock
Cargo.toml
influxdb3/Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3_clap_blocks/Cargo.toml
influxdb3_clap_blocks/src/lib.rs
influxdb3_clap_blocks/src/tokio.rs

Added a new workspace crate `influxdb3_clap_blocks` which will be a starting point for adding InfluxDB 3 OSS/Pro specific CLI configuration that no longer references IOx, and allows for us to trim out unneeded configurations for the monolithic InfluxDB 3.
To start, in this PR, this ports over the code from the `clap_blocks` [`tokio.rs` module](https://github.com/influxdata/influxdb3_core/blob/7eefba96954bdfb6fe69b26cd6d1fc9acd8e9160/clap_blocks/src/tokio.rs) from core/IOx.
Other than changing references from `IOX` to `INFLUXDB3`, this makes one important change: it enables IO on the DataFusion runtime. This, at least for now, is an experimental change to see if we can relieve some concurrency issues that we have been experiencing.
This leverages the configurable IO runtime from the main …

feat: add influxdb3_clap_blocks crate with runtime config

---

services/httpd/handler.go
services/httpd/service.go

Closes #25671 
This PR adds an additional statistic "fluxQueryRespBytes" to the output of /debug/vars, in turn making it available to Telegraf and other monitoring tools.

feat: Added fluxQueryRespBytes metric to 1.x /debug/vars

---

Cargo.lock
Cargo.toml
influxdb3_write/Cargo.toml
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Fixes bug in queryable buffer where if a block of data was missing one of the columns defined in a table, the creation of the logical plan to sort and dedupe the data would fail, causing a panic.
Fixes #25670

fix: Snapshot QueryableBuffer error

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/serialize.rs
influxdb3_py_api/Cargo.toml
influxdb3_py_api/src/system_py.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_wal/src/lib.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/plugins.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

This makes two major changes, running plugins in their own tasks and enabling writing back line protocol to the WriteBuffer.
Each plugin now runs in its own task, started either when created through the API or when the system is started. It is connected to the rest of the system through two mechanisms: 
* A broadcast channel whose sender is owned by the `QueryableBuffer` and whose receiver it polls from.
* An Arc<dyn WriteBuffer> to enable write-backs. This also gives access to the catalog and much of the rest of the db as we continue to build out the API.
Right now the only message being sent is `Arc<WalContents>`, but I expect the PluginEvent enum to be expanded both for other triggering events and control messages, e.g. Shutdown, Status, etc.
The running pythons have a reference to the …

feat(processing_engine): Runtime and Write-back improvements

---

influxdb3_cache/src/meta_cache/cache.rs
influxdb3_cache/src/meta_cache/mod.rs
influxdb3_cache/src/meta_cache/table_function.rs

feat: suport projection pushdown in metadata cache

---

influxdb3_write/src/write_buffer/queryable_buffer.rs

This adds some error handling and logging around the method that sorts, deduplicates, and persists parquet data during the snapshot process
The errors will need to be handled in follow-on work, but this is for helping debug fatal errors during the process.
Closes #25677
See also #25676

feat: log errors on panic in sort_dedupe_persist

---

influxdb3/tests/server/query.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This injects empty strings into tags for any rows in the buffer where the tag value is null. This is required because the tags are what make up the series key, which must have all non-null values.
There is an ongoing discussion about what the real behavior should be here, but for now this will get our users running that break without this behavior. Discussion is in #25674.
Fixes #25648

fix: Ensure tags are never null

---

influxdb3/src/commands/manage/database.rs
influxdb3/src/commands/manage/table.rs
influxdb3/src/main.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/configure.rs
influxdb3_catalog/src/catalog.rs
influxdb3_client/src/lib.rs
influxdb3_server/src/http.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs

This commit does a few things:
1. It brings the database command naming scheme for types inline with the rest of the CLI types
2. It brings the table command naming scheme for types inline with the rest of the CLI types
3. Adds tests to check that the num of dbs is not exceeded and that you cannot create more than one database with a given name.
4. Adds tests to check that you can create a table and put data into it and querying it
5. Adds tests for the CLI for both the database and table commands
6. It creates an endpoint to create databases given a JSON blob
7. It creates an endpoint to create tables given a JSON blob
With this users can now create a database or table without first needing to write to the database via the line protocol!
Closes #25640
Closes #25641

feat: create DB and Tables via REST and CLI

---

influxdb3/tests/server/query.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Fixes an error that would get thrown when doing a query against a table that has a field defined in its schema, but doesn't have it in the queryable buffer because that field hasn't been written to.

fix: Field not in queryable buffer

---

influxdb3/src/commands/serve.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/write_buffer/metrics.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/validator.rs

Closes #25689
Added prometheus metrics to track lines written and bytes written per database. The write buffer does the tracking after validation of incoming line protocol.
Added a test to check that this works via writes made through the `write_lp` method on the write buffer.
_Note_: I did not track writes on a per-table basis, only per-database. Doing it per-table, as per #25689, would be possible but will require a bit of overhead tracking the table name for each line all the way through the validation process. Currently, validation converts the table name to a table ID, and carries that through to the point that the line is deemed valid, since the WAL does not need the table name for write batches.

feat: ingest metrics

---

influxdb3/tests/server/query.rs
influxdb3_server/src/http.rs

This changes the status code of a failed query that uses a db that does not exist. We now instead return a 404 rather than the default 500 code
Closes #25653

fix: change failed query with missing db to 404

---

influxdb3/src/commands/query.rs
influxdb3/tests/server/query.rs
influxdb3_client/src/lib.rs
influxdb3_server/src/http.rs

This commit adds support for JSON Lines which also lets us stream the body back to the consumer, rather than needing to buffer the entirety of the query in memory before sending it back to the user.
Closes #24654

feat: Add json lines support to query output

---

Cargo.lock
Cargo.toml
deny.toml
influxdb3/src/commands/serve.rs

- one notable change is `make_object_store` from clap_blocks has been removed. Instead use `ObjectStoreConfig::make_object_store()`
(no issue - there are updates downstream that'll be useful when looking into `cargo deny` failures)

chore: update core dependencies

---

influxdb3_server/src/query_executor/mod.rs
influxdb3_server/src/system_tables/mod.rs
influxdb3_server/src/system_tables/parquet_files.rs
influxdb3_sys_events/src/lib.rs

- query_executor is moved to it's own module so that it's easier to swap the setup for pro.
- system_tables setup is also modified
(no issue)

refactor: porting changes in pro to oss

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_clap_blocks/Cargo.toml
influxdb3_clap_blocks/src/datafusion.rs
influxdb3_clap_blocks/src/lib.rs

This is needed for https://github.com/influxdata/influxdb_pro/issues/308
This allows the `max_parquet_fanout` to be specified in the CLI for the `influxdb3 serve` command. This could be done previously via the `--datafusion-config` CLI argument, but the drawbacks to that were:
1. that is a fairly advanced option given the available key/value pairs are not well documented
2. if `iox.max_parquet_fanout` was not provided to that argument, the default would be set to `40`
This PR maintains the existing `--datafusion-config` CLI argument (with one caveat, see below) which allows users to provide a set key/value pairs that will be used to build the internal DataFusion config, but in addition provides the `--datafusion-max-parquet-fanout` argument:
```
--datafusion-max-parquet-fanout …
```

feat: cli arg to specify max parquet fanout

---

v1/coordinator/points_writer.go

Avoid panicking when mapping points to a shard group
that has no shards. This does not address the root problem,
how the shard group ended up with no shards.
helps: https://github.com/influxdata/influxdb/issues/25715

fix: avoid panic if shard group has no shards

---

coordinator/points_writer.go

Avoid panicking when mapping points to a shard group that has no shards. This does not address the root problem, how the shard group ended up with no shards.
helps: https://github.com/influxdata/influxdb/issues/25715 (cherry picked from commit 5b364b51c865f7acc18756f8dd1362bc92992a6d)
closes: https://github.com/influxdata/influxdb/issues/25718

fix: avoid panic if shard group has no shards (#25717)

---

influxdb3_write/src/write_buffer/metrics.rs
influxdb3_write/src/write_buffer/mod.rs

This adds the metric `influxdb3_write_lines_rejected_total` metric which tracks the total number of lines rejected from incoming writes.
Note, that this only tacks the number of rejected lines when the default `accept_partial` of `true` is provided to incoming write requests.
This also changes the names of the `influxdb3_write_lines_total` and `influxdb3_write_bytes_total` internally to `influxdb3_write_lines` and `influxdb3_write_bytes`, respectively. Since the Prometheus exporter adds the `_total` for counter metrics for us see [here](https://github.com/influxdata/influxdb3_core/blob/db48a4f721086ffdb65b8c6b5d7d1bcbf61b5c64/metric_exporters/src/lib.rs#L54), these were previously being exported as `influxdb3_write_lines_total_total` and `influxdb3_write_bytes_total_total` - FYI …

feat: track lines rejected in prometheus metrics

---

influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/serialize.rs
influxdb3_server/src/http.rs
influxdb3_server/src/system_tables/python_call.rs
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/plugins.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

I've also added support for deleting plugins. In particular, a plugin can't be deleted if it is associated with a trigger. I plan on adding deletes for triggers shortly.
In order to do this I needed to use a separate channel per trigger, rather than them all looking at a broadcast channel.  This in turn caused `notify()` to need to be async. This should be fine as notify_and_snapshot() already was.
Tests should pass both with and without the system-py feature.

feat(processing_engine): Add REST API endpoints for activating and deactivating triggers.

---

CONTRIBUTING.md
docker/Dockerfile.ci
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3_load_generator/src/main.rs

This removes references to IOx in our docs and comments as when we started making Monolith last year it was a fork of influxdb_iox. This was something that we changed in some places, but not all as time went on. To avoid confusion whenever we more broadly release this software I've removed references to IOx in our code and docs. Note however that we still use a lot of IOx code and our system tables also return iox as part of the name. This is a separate issue namely #25227. Some things like env vars will also be cleaned up in #25646
Closes #25662

chore: Remove references to IOx in docs/comments

---

influxdb3/tests/server/limits.rs
influxdb3_server/src/http.rs

Prior to this change we would error correctly with a 422 if a limit was hit. However, we would not send back the correct error in the case of a limit being hit that caused a partial write. This change fixes that by checking the error messages for failed lines and if one is found that caused a limit to be hit, then a 422 is returned rather than a 400 as we would have been able to process the line otherwise, but the limit was hit instead
Closes #25208

fix: Return a 422 for limits on a partial write

---

influxdb3/src/commands/processing_engine/mod.rs
influxdb3/src/commands/processing_engine/plugin.rs
influxdb3/src/commands/processing_engine/trigger.rs
influxdb3/src/main.rs
influxdb3/tests/server/cli.rs
influxdb3_catalog/src/catalog.rs
influxdb3_client/src/lib.rs
influxdb3_server/src/http.rs
influxdb3_wal/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/plugins.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Closes #25697.
All of the new CLI commands are under the `processing-engine` subcommand, split further into `plugin` and `trigger` subcommands.

feat(processing_engine): Add CLI support for plugins and triggers

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/writer.go

There are a number of code paths in Compactor.write which on error can lead to leaked file handles to temporary files. This, in turn, prevents the removal of the temporary files until InfluxDB is rebooted, releasing the file handles.
closes https://github.com/influxdata/influxdb/issues/25724

fix: do not leak file handles from Compactor.write

---

influxdb3/src/commands/manage/table.rs
influxdb3/tests/server/configure.rs
influxdb3_server/src/http.rs
influxdb3_write/src/write_buffer/mod.rs

This commit removes the required fields restriction when using the CLI or the API to create a new table. As users can't write via the line protocol without a field this is fine and the schema will be updated on write. This expands the test to check for the correct response code now and make sure that we can both query the empty table and write new data to it.
Closes #25735

feat: remove required field restriction for tables

---

Cargo.lock
Cargo.toml
influxdb3/tests/server/write.rs

Prior to this change we would deny writes that used n and u for the precision argument when doing writes. We only accepted ns and us for those apis. However, to be backwards compatible we would need to enable accepting writes with n and u. This is mostly just upgrading our deps as this was a change that landed in IOx first. We test that it works for our code by adding test cases for their precision in this repo.
Closes #25734

feat: allow n/u for precision in v1/v2 write apis

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/writer.go

There are a number of code paths in Compactor.write which on error can lead to leaked file handles to temporary files. This, in turn, prevents the removal of the temporary files until InfluxDB is rebooted, releasing the file handles.
closes https://github.com/influxdata/influxdb/issues/25724
(cherry picked from commit e974165d252a1904b5ede5b88104301b32842b81)
closes https://github.com/influxdata/influxdb/issues/25739

fix: do not leak file handles from Compactor.write (#25725)

---

influxdb3/tests/server/main.rs

Closes #25760
This changes the E2E tests so that the `TEST_LOG` env var does not pass its value forward to the log filter on the running process. We need the process to use an `info` log filter so that the server's local address can be scraped from the logs (see https://github.com/influxdata/influxdb/pull/25758).

test: do not pass TEST_LOG to log filter in e2e tests

---

influxdb3/tests/server/query.rs
influxdb3_server/src/http/v1.rs

fix: `/query` API emits empty result as JSON

---

influxdb3/src/commands/create.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/snapshots/server__cli__meta_cache_create_and_delete-2.snap
influxdb3/tests/server/snapshots/server__cli__meta_cache_create_and_delete.snap
influxdb3_client/src/lib.rs

In https://github.com/influxdata/influxdb/pull/25737 token creation was broken as a client would attempt to be
made, but hit an unreachable branch. The fix was to just make the branch
create a Client that won't do anything. We also add a test to make sure
that if there is a regression we'll catch it in the future.
Closes https://github.com/influxdata/influxdb/issues/25764
fix: make client turn a duration into seconds/u64
This commit fixes the creation of a metadata cache made via the cli by
actually sending a time in seconds as a u64 and not as a duration. With
that we can now make metadata caches again when the `--max-age` flag is
specified.
This commit also adds a regression test for the CLI so that we can catch
this again in the future.

fix: get create token subcommand to work again 

---

influxdb3/src/commands/serve.rs
influxdb3_wal/src/lib.rs
influxdb3_wal/src/snapshot_tracker.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

This commit allows checking memory in the background and force snapshotting if query buffer size is > mem threshold. This hooks into the function (`force_flush_buffer`) to achieve it.
closes: https://github.com/influxdata/influxdb/issues/25685

feat: check mem and force snapshot

---

influxdb3_clap_blocks/src/datafusion.rs
influxdb3_write/src/persister.rs

- reduce parquet row group size to 100k
- add cli option to disable cached parquet loader
No issue, see https://github.com/influxdata/influxdb_pro/pull/349

chore: patch changes from enterprise

---

Cargo.lock
Cargo.toml
influxdb3/src/commands/test.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/main.rs
influxdb3_client/src/plugin_development.rs
influxdb3_internal_api/Cargo.toml
influxdb3_internal_api/src/lib.rs
influxdb3_internal_api/src/query_executor.rs
influxdb3_py_api/Cargo.toml
influxdb3_py_api/src/system_py.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/builder.rs
influxdb3_server/src/grpc.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/plugins.rs

This ended up being a couple things rolled into one. In order to add a query API to the Python plugin, I had to pull the QueryExecutor trait out of server into a place so that the python crate could use it.
This implements the query API, but also fixes up the WAL plugin test CLI a bit. I've added a test in the CLI section so that it shows end-to-end operation of the WAL plugin test API and exercise of the entire Plugin API.
Closes #25757

feat: Add query API to Python plugins

---

.gitignore

No issue.
This adds an entry to `.gitignore` to ignore the `.helix` directory, which can store repo-local configuration for the [Helix editor](https://helix-editor.com/).
This is useful for enabling feature flags as needed in the `.helix/languages.toml` file like so:
```toml
[language-server.rust-analyzer.config.cargo]
features = ["system-py"]
```
In order that `rust-analyzer` will compile/check parts of the codebase flagged by a given feature.

chore: add helix config dir to gitignore

---

influxdb3_server/Cargo.toml

In the refactor we missed propagating this feature.

fix(processing_engine): enable downstream system-py feature

---

Cargo.lock
influxdb3/src/commands/create.rs
influxdb3/src/commands/test.rs
influxdb3/tests/server/cli.rs
influxdb3_catalog/src/serialize.rs
influxdb3_client/Cargo.toml
influxdb3_client/src/lib.rs
influxdb3_client/src/plugin_development.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_py_api/Cargo.toml
influxdb3_py_api/src/system_py.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/http.rs
influxdb3_wal/src/lib.rs

This allows the user to specify arguments that will be passed to each execution of a wal plugin trigger. The CLI test was updated to check this end to end.
Closes #25655

feat: Wire up arguments to wal plugin trigger

---

influxdb3_telemetry/src/bucket.rs
influxdb3_telemetry/src/metrics.rs
influxdb3_telemetry/src/sampler.rs
influxdb3_telemetry/src/sender.rs
influxdb3_telemetry/src/store.rs

closes: https://github.com/influxdata/influxdb/issues/25713
New fields end with `..sum_1h`
```javascript
{
"os": "linux",
"version": "influxdb3-0.1.0",
"storage_type": "file",
"instance_id": "08c62980-603c-4dec-9034-47d0bf69fcc7",
"cores": 14,
"product_type": "OSS",
"uptime_secs": 0,
"cpu_utilization_percent_min_1m": 0.0,
"cpu_utilization_percent_max_1m": 0.0,
"cpu_utilization_percent_avg_1m": 0.0,
"memory_used_mb_min_1m": 0,
"memory_used_mb_max_1m": 0,
"memory_used_mb_avg_1m": 0,
"write_requests_min_1m": 0,
"write_requests_max_1m": 0,
"write_requests_avg_1m": 0,
// newly added
"write_requests_sum_1h": 0,
"write_lines_min_1m": 0,
"write_lines_max_1m": 0,
"write_lines_avg_1m": 0,
// newly added
"write_lines_sum_1h": 0,
"write_mb_min_1m": 0,
"write_mb_max_1m": 0,
"write_mb_avg_1m": 0,
// …
```

feat: 1h sum fields for telem writes/queries

---

influxdb3_wal/src/object_store.rs
influxdb3_write/src/write_buffer/persisted_files.rs

No issue for this.
This makes a change to the WAL replay whereby it takes into account the last WAL file sequence number from the most recent snapshot. It will use that number to ignore loading any WAL files from object store that were included or came before that snapshot.

feat: only load wal files after most recent snapshot

---

Cargo.lock
deny.toml
influxdb3_cache/src/distinct_cache/cache.rs
influxdb3_catalog/Cargo.toml
influxdb3_clap_blocks/src/datafusion.rs
influxdb3_client/src/lib.rs
influxdb3_internal_api/src/query_executor.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_telemetry/src/sampler.rs
influxdb3_telemetry/src/store.rs
influxdb3_wal/src/create.rs
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/chunk.rs
influxdb3_write/src/lib.rs
rust-toolchain.toml

This PR patches changes from enterprise back into core so they are as in-sync as possible, and to pull back changes that have been made to core code in the enterprise repo.

chore: patch enterprise back to core

---

.circleci/config.yml
.circleci/scripts/docker_build_release.bash
.circleci/scripts/publish.bash
Dockerfile

Closes #25795 
This builds linux images for x86 and arm64, and pushes them up to `quay.io/influxdb:influxdb3`. If it runs from the main branch then it will replace the :latest tag. Right now it is only running with --profile quick-release. I'll update this to use `--profile release` for releases later.

feat: Docker multi arch

---

.circleci/config.yml
.circleci/scripts/publish.bash

This switches the name to influxdb3-core and makes it parameter in circleci.

feat: parameterize docker image name, use influxdb3-core.

---

Cargo.lock
influxdb3/src/commands/create.rs
influxdb3/tests/server/cli.rs
influxdb3_catalog/src/serialize.rs
influxdb3_client/src/lib.rs
influxdb3_processing_engine/Cargo.toml
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_server/src/http.rs
influxdb3_server/src/system_tables/python_call.rs
influxdb3_wal/src/lib.rs

This updates the create plugin API and CLI so that it doesn't take the pugin code, but instead takes a file name of a file that must be in the plugin-dir of the server. It returns an error if the plugin-dir is not configured or if the file isn't there.
Also updates the WAL and catalog so that it doesn't store the plugin code directly. The code is read from disk one time when the plugin runs.
Closes #25797

feat: Update create plugin to use server file

---

influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs

Closes #25786 
Holding the lock on the PluginChannels caused a deadlock. Instead we only take the lock to send down the shutdown signal, and then wait for the plugin to exit.

fix: change trigger shutdown implementation to avoid deadlock.

---

.circleci/packages/config.yaml

Should fix the build signing/snapshot step

fix: package signing artifact names to use core not edge

---

influxdb3/src/commands/create.rs
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3/tests/server/main.rs
influxdb3_cache/src/last_cache/mod.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/snapshots/influxdb3_write__persister__tests__persisted_snapshot_structure.snap
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
influxdb3_write/src/write_buffer/validator.rs

* [**BREAKING**] This changes the CLI arg `host-id` to `writer-id` to more accurately indicate meaning.
* This changes also goes through the codebase and changes struct fields, methods, and variables to use the term `writer_id` or `writer_identifier_prefix` instead of `host_id` etc., to make the meaning clear and consistent in the code.
* [**BREAKING**] This also changes the catalog serialization to use the field `writer_id` instead of `host_id`, which is breaking change.
Here is the section from the updated `influxdb3 serve --help`:
```
Run the InfluxDB 3 Core server
Usage: influxdb3 serve [OPTIONS] --writer-id <WRITER_IDENTIFIER_PREFIX>
Options:
[...]
--writer-id <WRITER_IDENTIFIER_PREFIX>
The writer idendifier used as a prefix in all object store file paths. This should be unique for …
```

refactor: change host-id to writer-id

---

influxdb3/tests/server/auth.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/configure.rs
influxdb3/tests/server/flight.rs
influxdb3/tests/server/limits.rs
influxdb3/tests/server/query.rs
influxdb3/tests/server/system_tables.rs
influxdb3/tests/server/write.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

This commit sets InfluxDB 3 Core to have a 72 hour limit for queries and writes. What this means is that writes that contain historical data older than 72 hours will be rejected and queries will filter out data older than 72 hours. Core is intended to be a recent timeseries database and performance over data older than 72 hours will degrade without a garbage collector, a core feature of InfluxDB 3 Enterprise. InfluxDB 3 Enterprise does not have this write or query limit in place.
Note that this does *not* mean older data is deleted. Older data is still accessible in object storage as Parquet files that can still be used in other services and analyzed with dataframe libraries like pandas and polars.
This commit does a few things:
- Uses timestamps in the year 2065 for tests as these should …

feat: Set 72 hour query/write limit for Core

---

.circleci/config.yml

Related to https://github.com/orgs/influxdata/projects/108/views/1?pane=issue&itemId=91339068
The CI image has been removed. For more information, see [this discussion](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177). The `ubuntu-2204:current` image is the same as used in the 1.11 branch.
We need to fix the CI before releasing the new version of Plutonium.
https://app.circleci.com/pipelines/github/influxdata/influxdb/43361/workflows/6c772afa-d2ed-423b-ab83-157ce0d1b298/jobs/407782

fix: update CI to use a new version of the Ubuntu image as the old one has been deprecated by CircleCI

---

install_influxdb.sh
install_influxdb3.sh

chore: update gsg link

---

.circleci/config.yml
Dockerfile

This also adds curl and wget, which was requested for ECS healthchecks.

feat: rework when docker builds and have main builds use release profile.

---

cmd/influx_inspect/export/export.go

Adds the ability to use `influx_inspect export` to export data from a single tsm file, for example `influx_inspect export -out - -tsmfile 000000006-000000002.tsm.bad -database thermo -retention autogen`.

feat: influx_inspect export from a single tsm file

---

influxdb3/src/commands/create.rs

This is a followup to https://github.com/influxdata/influxdb/pull/25773/files#r1913406770.

chore: use an unusable url instead of localhost for token create

---

influxdb3_clap_blocks/src/object_store.rs

Creates AmazonS3 object using all environmental variables for additional cases where command line parameters are not appropriate.
This makes step 4 here possible - https://docs.aws.amazon.com/sdk-for-rust/latest/dg/credproviders.html
Alternative approach may have been to add a similar command line option for AWS_CONTAINER_CREDENTIALS_RELATIVE_URI but this makes no sense to provide on a CLI given it is only to be set automatically on Fargate and EKS containers.
As from_env() looks up all relevant environmental variables, it no longer makes sense to look for them as part of the CLI option parsing, so those relevant env options are removed.
Closes #25828

fix: create S3 client with from_env() instead of new() to allow eks and fargate container builds

---

tsdb/config.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go

This PR changes the algorithm for compaction to account for the following
cases that were not previously accounted for:
- Many generations with a groupsize over 2 GB
- Single generation with many files and a groupsize under 2 GB
Where groupsize is the total size of the TSM files in said shard directory.

feat: Modify optimized compaction to cover edge cases

---

influxdb3_catalog/src/catalog.rs
influxdb3_wal/src/snapshot_tracker.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

No issue yet, this is a reproducer test for empty snapshot files being generated under some very strict settings,
- flush interval: 1s
- snapshot size: 1
- force snapshotting mem threshold: 2000 bytes
The good news is, after investigating this code there is no data loss or any possibility of inconsistent query results. However you see these snapshot files with 0 rows in them. Loading them (during restart) does not cause any panics. It loads the file and ignores it as it does not have any pointers to parquet files. It would be good to fix this nevertheless.

fix: reproducer for the empty snapshot file issue

---

influxdb3_wal/src/object_store.rs

- update the last wal file seen first so that removal doesn't wait for one more cycle
- added the worked out example test
- minor tidy ups (introduce inner so that block scopes are delegated)

refactor: update tests for wal file removal

---

Cargo.lock
influxdb3/tests/server/cli.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_py_api/Cargo.toml
influxdb3_py_api/src/lib.rs
influxdb3_py_api/src/system_py.rs

This sets up the framework for fleshing out more useful plugin execution errors that get returned to the user during testing. We'll also want to capture these for logging in system tables.
Also fixes a test that was broken in previous commit on time limits. Didn't show up because of the feature flag.

feat: return better plugin execution errors

---

influxdb3/tests/server/cli.rs
influxdb3_py_api/src/system_py.rs

Updates the plugin log functions so they can take any number of Python objects which will be converted into a single log line string.
Closes #25847

feat: improve plugin logging interface

---

influxdb3/src/commands/serve.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/main.rs
influxdb3_catalog/src/catalog.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_server/src/builder.rs
influxdb3_server/src/lib.rs

In an earlier change we dropped the logic that started running triggers when the database runs. Adds it back in with a `start_triggers()` call on ProcessingEngineManager.

fix(processing_engine): start triggers when server is started.

---

Cargo.lock
influxdb3/tests/server/cli.rs
influxdb3_processing_engine/Cargo.toml
influxdb3_processing_engine/src/lib.rs

Adds the ability to load a plugin from our public github repo here: https://github.com/influxdata/influxdb3_plugins
If the plugin filename is specified as `gh:examples/wal_plugin` it will pull from the github repo at `<dir>/<name>/<name>.py`.
Currently this test actually hits github to pull the file. Not sure what we want to do here to mock it out. Or do we?
Closes #25836

feat: load plugins from our github plugin repo

---

Cargo.lock
Cargo.toml
influxdb3/src/commands/test.rs
influxdb3/tests/server/cli.rs
influxdb3_client/src/lib.rs
influxdb3_client/src/plugin_development.rs
influxdb3_processing_engine/Cargo.toml
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_py_api/Cargo.toml
influxdb3_py_api/src/system_py.rs
influxdb3_server/src/http.rs
influxdb3_wal/Cargo.toml
influxdb3_wal/src/lib.rs

Closes #25815.
This adds the `CronSchedule` plugin type to the processing engine, and an accompanying variant of `TriggerSpecificationDefinition`.
When a cron schedule runs it looks at the current time to construct an iterator, using the `cron` library. Calls to the plugin proceed sequentially, and there is not currently any catchup. The time passed down to the plugin is the time the cron schedule triggered for, rather than the current time.
I've added an endpoint to test cron plugins, similar to the existing one for the wal_plugin.
Some semantics questions I'd appreciate feedback on:
* Right now we will fall behind if the plugin consistently takes longer to run than the time between triggers. Do we want to have a different default or expose this as an option?
* The cron library we're …

feat(processing_engine): Add cron plugins and triggers to the processing engine.

---

influxdb3_write/src/write_buffer/mod.rs

- assertions for what remains in the queryable buffer when out of order timestamps are encountered. This could be true for back filling, and in that case back filled data takes over the queryable buffer and moving all the recent data into parquet files (as part of snapshotting)
- assertions to check last cache still retains the most recent values when out of order data is encountered

chore: add out of order tests

---

influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Related to https://github.com/influxdata/influxdb_pro/issues/436
This PR updates the filter handling in the `WriteBuffer` so that sets of `Expr`s provided in a query will better prune both chunks from the in-memory buffer, as well as the set of parquet file chunks that are forwarded to DataFusion, for query execution.
This introduces the [`BufferFilter`](https://github.com/influxdata/influxdb/blob/bab428f0eb5ec6a59882a71a2f7b807c85db8122/influxdb3_write/src/lib.rs#L496) type. This converts a set of `Expr`s from a logical query plan into a filter that can be used to:
* prune chunks based on a provided lower/upper `time` boundary from both the buffer and parquet
* prune chunks from the buffer based on any literal guarantees predicated on tag columns in the query, e.g., `WHERE tag = 'a'` or …

feat: expr analyzer for buffer to filter table chunks

---

influxdb3/tests/server/main.rs
influxdb3/tests/server/query.rs
influxdb3_server/src/http.rs

Although the `format` in the request is used, the value coming through the header is parsed earlier. So, when that lookup in the header fails an error is returned (`InvalidMimeType`).
In this commit, there are extra checks to allow the default `Accept` header values that come from the browser by defaulting it to `json`
closes: https://github.com/influxdata/influxdb/issues/25874

fix: allow default browser header

---

influxdb3/src/commands/common.rs
influxdb3/src/commands/query.rs
influxdb3/src/commands/show.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/query.rs

closes: https://github.com/influxdata/influxdb/issues/25873

feat: rename json_lines to jsonl for cli

---

Cargo.lock
influxdb3/src/commands/create.rs
influxdb3/tests/server/cli.rs
influxdb3_processing_engine/Cargo.toml
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_py_api/Cargo.toml
influxdb3_py_api/src/lib.rs
influxdb3_py_api/src/system_py.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/http.rs
influxdb3_wal/src/lib.rs

Adds the request plugin type. Triggers can be bound to an API endpoint at /api/v3/engine/<path>. Requests will get yielded to the plugin with the query parameters, request parameters, and request body.
I didn't implement the test endpoint for this plugin type as it seems much more natural for users to save the file and make a new request. Once #25863 is done it'll make it very easy.
Closes #25862

feat: Add request plugin capability

---

influxdb3/tests/server/cli.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/plugins.rs

This updates plugins so that they will reload the code if the local file is modified. Github pugins continue to be loaded only once when they are initially created or loaded on startup.
This will make iterating on plugin development locally much easier.
Closes #25863
Leaving this in draft until #25864 gets merged in as this builds on top of that.

feat: reloads plugins if modified

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/reader_test.go

The error type check for errBlockRead was incorrect,
and bad TSM files were not being moved aside when
that error was encountered. Use errors.Join,
errors.Is, and errors.As to correctly unwrap multiple
errors. 
Closes https://github.com/influxdata/influxdb/issues/25838

fix: move aside TSM file on errBlockRead

---

influxdb3_catalog/src/catalog.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_wal/src/create.rs
influxdb3_wal/src/lib.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/table_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

The main refactor was to change the `ChunkContainer` trait to use the `DatabaseSchema` and `TableDefinition` types directly in the signature, vs. their names; using their names led to an additional catalog lock and lookups for both entities, because there was already a catalog lock/lookup upstream in the `QueryTable`.
However, using the names in the `ChunkContainer::get_table_chunks` was convenient, specifically for tests, so I included a test helper trait in `influxdb3_write::test_helpers` called `WriteBufferTester` that provides convenience methods for getting record batches from a `WriteBuffer` implementation. Alongside the definition of `WriteBufferTester` is a blanket `impl` on that any `T` that implements `WriteBuffer`.
We have been implementing similar methods manually in several …

refactor: reduce catalog locks when getting chunks

---

influxdb3/src/commands/serve.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

This commit does a few key things:
- Removes the 72 hour query and write restrictions in Core
- Limits the queries to a default number of parquet files. We chose 432 as this is about 72 hours using default settings for the gen1 timeblock
- The file limit can be increased, but the help text and error message when exceeded note that query performance will likely be degraded as a result.
- We warn users to use smaller time ranges if possible if they hit this query error
With this we eliminate the hard restriction we have in place, but instead create a soft one that users can choose to take the performance hit with. If they can't take that hit then it's recommended that they upgrade to Enterprise which has the compactor built in to make performant historical queries.

feat: loosen 72 hour query/write restriction

---

influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/plugins.rs

This cleans up how plugins receive their triggering events. It'll also clean up the logs a bit without warnings that plugin events of the wrong type are going to different plugins.
Closes #25879

feat: each plugin type uses its own channel

---

influxdb3/src/commands/create.rs
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/main.rs
influxdb3_cache/src/last_cache/mod.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/snapshots/influxdb3_write__persister__tests__persisted_snapshot_structure.snap
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
influxdb3_write/src/write_buffer/validator.rs
install_influxdb.sh
install_influxdb3.sh

Related: https://github.com/influxdata/influxdb_pro/issues/429
This changes the naming of the identifier used to uniquely identify an InfluxDB 3 server from `writer-id` to `node-id`.
Therefore, the argument that is passed on server start will now be `--node-id` (not `--writer-id`, or previously `--host-id`).
This PR makes changes of naming throughout the codebase so that struct fields, variable names, function arguments, etc. all follow the new naming convention.

refactor: `writer-id` to `node-id`

---

influxdb3_catalog/src/catalog.rs
influxdb3_write/src/lib.rs

This change is to reduce friction from the recent change from `writer-id` to `node-id` in https://github.com/influxdata/influxdb/pull/25905 by adding deserialization aliases to the catalog and snapshot types so that existing catalog and snapshot JSON files will still successfully deserialize without users needing to start completely from scratch.
Any users that have been running since the alpha release will have catalog and snapshot files written with `writer_id`. This will still support those files, but write new ones with the `node_id` field name going forward.

fix: add alias for node_id to writer_id for backward compatibility

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_cache/Cargo.toml
influxdb3_cache/src/parquet_cache/mod.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

closes: https://github.com/influxdata/influxdb/issues/25887
This PR allows local updates for parquet cache without going to object store. Following are the main changes,
- Introduces `Immediate` and `Eventual` modes for cache request
- The oracle now holds the reference to cache through object store that is used in the background runner
- Any requests with `Immediate` mode directly goes into the cache in a synchronous call, the machinery built to cache in the background now takes only `EventualCacheRequest` (where we know only the path and do not have access to serialized parquet bytes, this option will be used)
- All await to wait for all cache request being fulfilled in queryable buffer is removed, as when snapshotting we always have access to serialized bytes.

feat: first stab at locally updating parquet cache

---

influxdb3/src/commands/query.rs
influxdb3/src/commands/write.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/fixtures/file.lp
influxdb3/tests/server/fixtures/file.sql

This change allows *both* the write and query commands to accept input
via stdin or by a file. With this change larger queries are more
feasible to write as they can now be written in a file and smaller
writes via a string are now possible. This also makes the program work
more like people would expect it to, especially on unix based systems.
This commit also contains three tests to make sure the functionality works
as expected.
Closes #25772
Closes #25892

feat(cli): write & query via stdin, string  & file

---

influxdb3/tests/server/write.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_server/src/http.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs

In cases where a user does not need the guarantees that data is persisted to the WAL on write and needs faster ingest speed then the no_sync param added in this commit are what they need. Rather than waiting on a sync to the WAL a task to do so is spawned and the code continues executing to return a successful HTTP code to the user.
The upside to this is that they can ingest data faster, but there is a small risk that between writing the data and it eventually being written to object storage, that the server crashes and it's irrevocably lost. Also if the write to the WAL fails, then at most the user will get an error printed in the logs rather than a failed response code they can handle. The data will still be in the buffer, but will not be durable until persisted as a parquet file in …

feat: add no_sync write_lp param for fast writes

---

influxdb3_write/src/write_buffer/queryable_buffer.rs

This speeds up snapshot persistence by taking all of the persist jobs and running them simultaneously on a JoinSet. With this we can speed things up a bit by not waiting for each file to persist before the next one can be persisted. Instead we now can run all the persisting at the same time using the tokio runtime.
Closes #24658

feat: persist snapshots in parallel

---

influxdb3/src/commands/create.rs
influxdb3/tests/server/cli.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_server/src/http.rs

This updates trigger creation to load the plugin file before creating the trigger.
Another small change is to make Github references use filenames and paths identical to what they would be in the plugin-dir. This makes it a little easier to have the plugins repo local and develop against it and then be able to reference the same file later with gh: once it's up on the repo.
In draft until #25914  gets merged in

feat: Update trigger creation to validate plugin file present

---

influxdb3_cache/src/last_cache/cache.rs
influxdb3_cache/src/last_cache/mod.rs

Closes #25923
Closes #25922
This fixes last cache construction when an explicit set of value columns is provided. As a result, such caches will be queryable.
A test to verify, i.e., from the reproducer, was added.

fix: last cache with specific value columns can be queried

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3/src/commands/install.rs
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/main.rs
influxdb3/tests/server/packages.rs
influxdb3_clap_blocks/src/lib.rs
influxdb3_clap_blocks/src/plugins.rs
influxdb3_client/src/lib.rs
influxdb3_processing_engine/Cargo.toml
influxdb3_processing_engine/src/environment.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_processing_engine/src/virtualenv.rs
influxdb3_py_api/Cargo.toml
influxdb3_server/Cargo.toml
influxdb3_server/src/builder.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_write/Cargo.toml

This integrates the processing engine with a specified virtual environment, either from a CLI flag or through the VIRTUAL_ENV environment variable. In order for this to work we switch from auto-initializing pyo3 to an initialize call that first sources the bin environment. I've only tested this on OS X, let me know how much time I should spend getting this to work on windows.
I've also added an `install` verb to the CLI. It currently is used to install packages, namely either a list of python packages or a requirement.txt. It supports either `pip` or `uv pip` instillation. Note that the operator will have to be careful lining up the virtual environment and the package manager. In particular, a virtualenv created by `uv` will not see packages installed directly via pip.
The tests create a …

feat(processing_engine): integration with virtual environments.

---

influxdb3/src/commands/write.rs
influxdb3/tests/server/cli.rs
influxdb3/tests/server/snapshots/server__cli__invalid_precision.snap
influxdb3_client/src/lib.rs

Addresses https://github.com/influxdata/influxdb/issues/25930
This adds simple `--precision` flag to the `influxdb3 write` subcommand along with round trip write/query tests to validate the resulting timestamp precision in the query output.

feat: add precision flag to write subcommand

---

influxdb3/src/commands/serve.rs
influxdb3_cache/Cargo.toml
influxdb3_cache/src/parquet_cache/mod.rs
influxdb3_write/src/write_buffer/mod.rs

This commit scans the parquet files that will be used in query to check if they can be cached. There are three conditions to satisfy,
- not cached already
- cache has enough space
- file times overlap with the cache policy times
closes: https://github.com/influxdata/influxdb/issues/25906
The approach taken in this commit allows background handler to decide whether parquet files in query path need caching. An alternate approach would be to filter them out based on the time ranges first and only submit request where parquet files time ranges overlap with cache policy. But these parquet files are only to be cached when there is space and that would've possibly meant adding some flag or creating another variation of cache request which is eventual but conditional (i.e space is there or not). …

feat: introduce parquet caching in query path

---

influxdb3/tests/server/cli.rs
influxdb3_catalog/src/catalog.rs

Closes #25943.
Decided to make the action always updating. It should generally be a null-op, but this ensures that it is being flushed to the wal log.

fix: persist create database action.

---

influxdb3_server/src/http.rs

This commit allows us to stream data back for CSV and JSON formatted queries. Prior to this we would buffer up all of the data in memory before sending it back. Now we can make it so that we only buffer in one RecordBatch at a time to reduce memory overhead.
Note that due to the way the APIs for writers work and for how Body in hyper 0.14 works we can't use a streaming body that we can write too. This in turn means we have to use a manually written Future state machine, which works but is far from ideal.
Note this does not include the pretty and parquet files as streamable. I'm attempting to get the pretty one to be streamable, but I don't think that this one and parquet are as likely to be streamable back to the user. In general we might want to discourage these formats from being used.

feat: stream data back for CSV and JSON queries

---

influxdb3/tests/cli/mod.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_wal/src/lib.rs

Closes #25940.
Let me know if you think I should handle that error different. It's currently unreachable, as it is called inside of the correct match block and we're basically rematching on the trigger definition a second time.

fix(processing_engine): Use the configured request path for Request plugins.

---

Cargo.lock
influxdb3_write/Cargo.toml
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/table_buffer.rs

This removes the `BufferIndex` from the write buffer in core and lifts the literal guarantee analysis from the `ChunkFilter` which was only used by the `BufferIndex`.
Closes #25898

refactor: remove buffer index and literal guarantee analysus in filter

---

cmd/influx_inspect/type_conflicts/schema.go

Add parentheses to ensure a deferred
function is called on method exit.

fix: actually call the deferred function

---

influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

This commit clears the query buffer incrementally as soon as a table's data in buffer is written into parquet file and cached. Previously, clearing the buffer happened at the end in the background

feat: clear query buffer incrementally when snapshotting

---

influxdb3_processing_engine/src/virtualenv.rs

Closes #25933.
This seems to do the trick. I've tested it with the system_metrics plugin both locally (OS X) and on a debian docker image.

fix(processing_engine): ensure default SIGINT behavior from python.

---

influxdb3_server/src/http.rs

I noticed this while running tests on a WIP branch I've been working on.
To be clear, this is a problem because it results in spurious debug logs to stderr every time the JsonFuture is polled.

fix: remove accidentally-commited dbg! macro

---

Cargo.lock
influxdb3/src/commands/common.rs
influxdb3/tests/server/client.rs
influxdb3_cache/src/distinct_cache/cache.rs
influxdb3_client/src/lib.rs
influxdb3_load_generator/Cargo.toml
influxdb3_load_generator/src/query_generator.rs
influxdb3_server/src/http.rs
influxdb3_types/Cargo.toml
influxdb3_types/src/http.rs

Finishes (?) addressing https://github.com/influxdata/influxdb/issues/24672.
I started out intending only to refactor the `*RequestBuilder` types here but when I started DRYing up some of the HTTP request handling code in those I started noticing more or less the same HTTP request handling in all the `Client` methods so I went ahead and applied the same new pattern to those as well, which is to rely on a smaller set of generic functions, eg `send_json`, `send_json_get_bytes`, `send_get_bytes`, `send_create`.
I can think of another refactor that could reduce these down to just two generic functions but I think I'll leave it at what I've got for now.

refactor: DRY up influxdb3_client code

---

cmd/influxd/inspect/type_conflicts/schema.go
sqlite/sqlite.go

This fix will stop leaking file handles to temporary files.
* fixes #25950
* Closes #25950

fix: defer calls that return a closure need to be called

---

influxdb3_server/src/builder.rs
influxdb3_server/src/system_tables/python_call.rs

- missing clone/copy impl for NoProcessingEngine
- scope the visibility of a method

chore: fixes for the build

---

influxdb3_cache/src/parquet_cache/mod.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs

Includes 2 main changes
- update the function signature for `cache_parquet_files`
- bring in `Evict` variant for parquet `CacheRequest`

feat: port changes back to core from enterprise

---

influxdb3_server/src/http.rs

Changes an `error!` from logging the full request URI to just log the path. This is to prevent emitting passwords for legacy APIs that accept the auth token in the `p` parameter (`/query` and `/write`).

fix: remove request uri from error log

---

influxdb3_client/src/lib.rs

Closes #
Fix a typo in influxdb3 client documents.

fix: typo in influxdb3 client docs

---

influxdb3_catalog/src/catalog.rs
influxdb3_id/src/lib.rs

There is no issue for this. I added a macro to generate code for the catalog ID types to keep from copy/pasting.
I also refactored the test that checks deleted tables do not count against the limits. In Enterprise this test is quite slow where the limits are higher.

refactor: use macro to define id types

---

Cargo.lock
Cargo.toml
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/serialize.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_distinct_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap

The distinct cache info for tables was not serialized in the catalog. This fixes that, but also updates the catalog serialization to use the same snapshot pattern for serialization from the Catalog type all the way down. This removes the need to serialize the `db_map` from the catalog.
The Eq and PartialEq derives were removed from Catalog and InnerCatalog as they were only used in tests, where assertions using them were replaced by insta snapshot tests.
A test was added to check serialization/deserialization of distinct caches in the catalog.
There is no issue for this.

fix: serialize distinct cache in catalog

---

tsdb/engine/tsm1/compact.go

This pr adds err handling for branch that did not specify os file removal errors previously. This is part of EAR #5819.
(cherry picked from commit 306a184a8dfc76a27a0214186895ede25b5a5f0e)

feat: Add error joins/returns (#25996)

---

tsdb/engine/tsm1/compact.go

This PR adds an error join to help with handling multiple errors from snapshot file writers.

feat: Add error join for file writing in snapshots

---

tsdb/engine/tsm1/compact.go

This PR adds an error join to help with handling multiple errors from snapshot file writers.
(cherry picked from commit 4ad5e2aba7d6d725e4ba81ed15a2b96fb2869ec2)

feat: Add error join for file writing in snapshots (#26004)

---

influxdb3/tests/server/flight.rs
influxdb3/tests/server/mod.rs

Related to #26002 
This was an attempt at re-producing the issue described in #26002. An integration test is added that queries the distinct cache using the FlightSQL client, in the same manor as in the issue.
Here is an example of the log output during a query that succeeded:
```
2025-02-13T16:00:36.172967Z  INFO service_grpc_flight: GetFlightInfo request namespace_name=foo cmd=CommandStatementQuerySELECT * FROM distinct_cache('bar') trace=
2025-02-13T16:00:36.196305Z  INFO iox_query::query_log: query when="received" id=ad150cad-51f0-4086-827b-cb3a8b460f2b namespace_id=0 namespace_name="influxdb3 oss" query_type="flightsql" query_text=CommandStatementQuerySELECT * FROM distinct_cache('bar') query_params=Params { } issue_time=2025-02-13T16:00:36.195870+00:00 success=false running=true …
```

test: query distinct cache via flight sql

---

tsdb/engine/tsm1/engine.go
tsdb/field_validator.go
tsdb/shard.go
tsdb/shard_test.go

There was a window where a race between writes with 
differing types for the same field were being validated. 
Lock the MeasurementFields struct during field
validation to avoid this.
closes https://github.com/influxdata/influxdb/issues/23756

fix: lock MeasurementFields while validating

---

pkg/data/gensyncmap/gensyncmap.go
tsdb/shard.go
tsdb/shard_test.go

Simplify and speed up synchronization for
MeasurementFields structures by switching
from a mutex and atomic.Value to a sync.Map

fix: switch MeasurementFields from atomic.Value to sync.Map

---

influxdb3_server/src/http.rs

This propagates a `TraceCollector` to the query call path from the common server state. With this we should get many of the same traces that we see in IOx since there is a lot of shared code on that call path.
I have not yet been able to see traces show up in the jaeger instance that this connects to so it seems like there must still be something missing in the setup. My setup is more or less to run jaeger in docker:
```
docker run -d \
--name jaeger \
-p 6831:6831/udp \
-p 16686:16686 \
jaegertracing/all-in-one:latest
```
Then to run `influxdb3 serve ...` as usual with the following environment variables set:
```
export TRACES_EXPORTER=jaeger
export TRACES_EXPORTER_JAEGER_AGENT_HOST=localhost
export TRACES_EXPORTER_JAEGER_AGENT_PORT=6831
```
Once I've done this, I use the …

feat: add tracing to query path

---

pkg/data/gensyncmap/gensyncmap.go
tsdb/engine/tsm1/engine.go
tsdb/field_validator.go
tsdb/shard.go
tsdb/shard_test.go

* fix: switch MeasurementFields from atomic.Value to sync.Map (#26022)
Simplify and speed up synchronization for
MeasurementFields structures by switching
from a mutex and atomic.Value to a sync.Map
(cherry picked from commit b617eb24a767c9adfcfd490e0d543bd5924c2052)
closes https://github.com/influxdata/influxdb/issues/26001
* fix: lock MeasurementFields while validating (#25998)
There was a window where a race between writes with
differing types for the same field were being validated.
Lock the  MeasurementFields struct during field
validation to avoid this.
closes https://github.com/influxdata/influxdb/issues/23756
(cherry picked from commit 5a20a835a55d9bd77810b1d47a0699dee18c42b9)
helps https://github.com/influxdata/influxdb/issues/26001

fix: prevent differing field types in the same shard

---

influxdb3/src/commands/serve.rs
influxdb3_processing_engine/src/environment.rs
influxdb3_processing_engine/src/virtualenv.rs

Helps with #26012
https://github.com/influxdata/influxdb/pull/25969 left open a number of issues surrounding initial default venv setup and entering a venv when python build standalone is used which were captured in #26012. @jacksonrnewhouse noted that things worked when PATH was set to point to where the unpacked python build standalone was. This PR builds on the techniques from https://github.com/influxdata/influxdb/pull/25969 to resolve these issues by:
* adjusting `influxdb3/src/commands/serve.rs` to consider PYTHONHOME when looking for a valid `pip`
* adjusting `influxdb3_processing_engine/src/environment.rs` to have PipManager look for VIRTUAL_ENV and PYTHONHOME when creating the initial venv and installing packages (in practice, PYTHONHOME will be used when creating the venv and …

fix: detect python runtime for PipManager and venv setup

---

tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go
tsdb/field_validator.go
tsdb/shard.go
tsdb/shard_test.go

Refactor the new field creation code for maintainability.
Address review comments in the port work of the 
field creation.  Also fixes one bug in returning the wrong
error.

chore: refactor field creation for maintainability

---

influxdb3/src/main.rs
influxdb3_processing_engine/src/virtualenv.rs

fix: properly perform venv activation on windows

---

influxdb3/src/commands/common.rs
influxdb3/src/commands/serve.rs

- breaking change, replaced `--parquet-mem-cache-size-mb` and env var for it with `--parquet-mem-cache-size` (takes value now in percentage or MB) and it now defaults to 20% of total available memory
- force snapshotting is set at 50%
- datafusion mem pool is set to 20%
closes: https://github.com/influxdata/influxdb/issues/26009

feat: updates to default memory settings

---

Dockerfile
influxdb3/src/commands/serve.rs
influxdb3_clap_blocks/src/plugins.rs
influxdb3_processing_engine/src/environment.rs
influxdb3_processing_engine/src/manager.rs

Since @jdstrand got the venv stuff working in a different way than #26027, I thought I'd just pull this out. The main thing it does is ensure that /plugins is created in the docker images with the right permissions, which had been a pain point for users.

feat(processing_engine): Have automatic plugin dir at /plugins for docker.

---

Dockerfile

The perf team reported build issues with the following error message:
```
0.454 error: process didn't exit successfully: `/usr/local/rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/bin/rustc -vV` (exit status: 127)
0.454 --- stderr
0.454 /usr/local/rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/bin/rustc: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```
Looking into their CI job, I noticed that they override the RUST_VERSION in our dockerfile to automatically change the upstream container image: https://github.com/influxdata/perf-tools/blob/c9073f681429ac093206c0a8f86e89cf62421467/.circleci/template.yml#L532
This PR updates our default RUST_VERSION to 1.85 and attempts a fix that can be verified by our own CI.

chore: update Dockerfile to RUST_VERSION=1.85, install libz-dev

---

docker/entrypoint.sh
install_influxdb.sh

Removed all of the shellcheck complaints that were showing up in my editor.
Where possible, I just fixed them directly but I just told it to ignore this one in the install scripts https://www.shellcheck.net/wiki/SC2059
Happy to go and fix that lint too I just wasn't sure if we prefer the current approach, since it doesn't seem to be causing any problems.

chore: fix shellcheck lints

---

tsdb/engine/tsm1/engine.go
tsdb/field_validator.go
tsdb/shard.go
tsdb/shard_test.go

A field could be created in  memory but not
saved to disk if a later field in that
point was invalid (type conflict, too big)
Ensure that if a field is created, it is
saved

fix: ensure fields in memory match on disk

---

README_processing_engine.md
influxdb3/src/commands/serve.rs
influxdb3/src/main.rs
influxdb3_processing_engine/src/environment.rs
influxdb3_processing_engine/src/virtualenv.rs

ccd5d22aab introduced working but temporary code for setting up the python runtime environment. This cleans that up:
* chore: clean up runtime code for python setup
ccd5d22aab introduced working but temporary code for setting up the
python runtime environment. This cleans that up:
* refactor various find_python() functionality into virtualenv.rs
* refactor PYTHONHOME calculation to virtualenv.rs:find_python_install()
* adjust init_pyo3() to temporarily set PYTHONHOME based on
virtualenv.rs:find_python_install() as this is the only place it is
needed (indeed, venv activation scripts try to remove it)
Importantly, virtualenv.rs:find_python_install() tries to find the
python build standalone runtime based on a few heuristics. This function
could be improved in the fullness of time to, eg, be …

chore: clean up runtime code for python setup

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/engine.go

Add more robust temporary file removal
on a failed compaction. Don't halt on
a failed removal, and don't assume a
failed compaction won't generate
temporary files.
closes https://github.com/influxdata/influxdb/issues/26068

fix: ensure temp files removed on failed compaction

---

docker/entrypoint.sh
install_influxdb.sh

Reverts influxdata/influxdb#25956
The changes seem to have broke the script for some users (see https://influxdata.slack.com/archives/C084G9LR2HL/p1740528785302339).

chore: revert fix shellcheck lints

---

.circleci/config.yml
scripts/ci/build-tests.sh
scripts/ci/build.sh

This PR should fix the build step failures for influxdb on windows amd64. Updates the cross builder to
go1.23.5-ba67b11de54aa0bf8f1f92a81f786205de8024b6
Adds `export CGO_LDFLAGS="-lntdll -ladvapi32 -lkernel32 -luserenv -lws2_32 ${CGO_LDFLAGS}"` to cgo linker to link NT specific syscalls. 
Closes #26051

feat: update crossbuilder to tagged version and update go linker

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/engine.go

Add more robust temporary file removal
on a failed compaction. Don't halt on
a failed removal, and don't assume a
failed compaction won't generate
temporary files.
closes https://github.com/influxdata/influxdb/issues/26068
(cherry picked from commit ba95c9b0f061d9730739a2997d18efd7ed11dc8e)
closes https://github.com/influxdata/influxdb/issues/26069

fix: ensure temp files removed on failed compaction (#26070)

---

tsdb/engine/tsm1/compact.go

Compactor.writeNewFiles should delete
temporary files created on iterations
before an error halts the compaction.
closes https://github.com/influxdata/influxdb/issues/26073

fix: remove temp files on error in Compactor.writeNewFiles

---

tsdb/engine/tsm1/compact.go

Compactor.writeNewFiles should delete
temporary files created on iterations
before an error halts the compaction.
closes https://github.com/influxdata/influxdb/issues/26073
(cherry picked from commit 1efb8dad431b22aea75f9146a17c88141b3296ee)
closes https://github.com/influxdata/influxdb/issues/26075

fix: remove temp files on error in Compactor.writeNewFiles (#26074)

---

influxdb3/tests/cli/mod.rs
influxdb3_py_api/src/system_py.rs

Closes #26050.
At first I got this working by manually including the __builtin__ module, but it turns out it works if we use the default global. individual plugin code is still isolated.

fix(processing_engine): Use default globals so that builtins are automatically included.

---

Cargo.lock
influxdb3_clap_blocks/Cargo.toml
influxdb3_clap_blocks/src/object_store.rs

While initially attempting to reproduce a data corruption issue in enterprise, I encountered unexpected behavior during compactor restarts -- namely, that the compactor would always load the wrong compaction summary. It should just load the latest compaction summary which would show up as the first item in an object store listing if the object store listed items in UTF-8 binary order (ascending). 
This [is the case when using the S3-backed object store](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ListingKeysUsingAPIs.html), but not when using the [`LocalFileSystem`](https://docs.rs/object_store/latest/object_store/local/struct.LocalFileSystem.html).
Indeed, the `ObjectStore` trait [explicitly doesn't guarantee](https://docs.rs/object_store/latest/object_store/trait.ObjectStore.ht …

fix: ensure "local" ObjectStore.list returns ordered elements

---

influxdb3/src/commands/common.rs
influxdb3/src/commands/create.rs
influxdb3/src/commands/plugin_test/wal.rs
influxdb3/src/commands/test.rs
influxdb3/tests/cli/mod.rs

This fixes #25854 as discussed in the issue.
This removes the `SeparatedList` abstraction in favor of `clap`'s `value_delimiter` using `,` as the delimiter. This aligns us with the approach used in https://github.com/influxdata/influxdb3_core/tree/main/clap_blocks.

feat: improve CLI list arg consistency (always use commas)

---

influxdb3/src/commands/create.rs

In https://github.com/influxdata/influxdb/pull/26094 I introduced a buggy test case, but it somehow passed CI: https://app.circleci.com/pipelines/github/influxdata/influxdb/44477/workflows/71d2b9c9-b2e3-4cca-8fb2-da68542861bd/jobs/420814?invite=true#step-103-50025_110
But main branch is demonstrating the problem: https://app.circleci.com/pipelines/github/influxdata/influxdb/44479/workflows/6fd5d9f9-1c31-4863-8e9c-a2935cf6194f/jobs/420844?invite=true#step-103-46166_55
This PR should fix it.

fix: test case introduced by #26094

---

.circleci/config.yml

- activate toolchain explicitly
- add clippy and rustfmt components
You can see the failures in main branch [here](https://app.circleci.com/pipelines/github/influxdata/influxdb/44497/workflows/6c87a561-cabf-41fb-8d77-29ec59e2c3b8). Not sure if these can be moved to the rust image itself that we're pulling from quay.io, but for now this fixes the failing jobs.

chore: rust ci job fix to address rustup 1.28.0 changes

---

influxdb3/src/commands/create.rs
influxdb3/tests/cli/mod.rs
influxdb3_py_api/src/system_py.rs

Closes #25894. Also patches a minor regression introduced in #26094.

feat(processing_engine): Support Flask semantics for responses from request plugins.

---

influxdb3/src/commands/create.rs

I didn't rebase before merging #26086, and that broke a new test.

fix: add error_behavior to test matching expression.

---

.circleci/config.yml
scripts/ci/build-tests.sh

This PR updates the build_windows function in build-tests.sh to use the -ldext flag to specify that we are using the windows compiler for cross compilation. It also removes -x as a flag which would output all file names as it was built. This fixes the build-tests script.

feat: Use ldext in build-test.sh

---

etc/config.sample.toml
tsdb/config.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go

This PR adds an additional parameter for influxd
CompactPointsPerBlock. It adjusts the DefaultAggressiveMaxPointsPerBlock to 10,000. We had discovered that with the points per block set to 100,000 compacted TSM files were increasing. After modifying the points per block to 10,000 we noticed that the file sizes decreased. The value has been set as a parameter that can be adjusted by administrators this allows there to be some tuning if compression problems are encountered.

feat: Add CompactPointsPerBlock config opt

---

Cargo.lock
influxdb3_cache/src/parquet_cache/mod.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/write_buffer/mod.rs

- spans added for buffer, parquet chunks along with number of files that are already in parquet cache along with the sql
**NOTE: The parquet cache check for files is done at the point of call to `TableProvider::scan`, the data may get evicted by the time datafusion actually tries to access it but for a lot of the queries which are running in perf test env, this is a good enough approximation for now**
The workflow here is, 
- spin up `influxdb3` with extra switches `--traces-exporter-jaeger-agent-port 6831 --traces-exporter-jaeger-service-name influxdb3-core --traces-exporter jaeger` and 
- `jaeger` - following [docs](https://www.jaegertracing.io/docs/2.3/getting-started/)
Once it's running, issue queries and then in jaeger ui (running on `http://localhost:16686`), search for 
- service …

feat: query path instrumentation

---

Cargo.lock
Cargo.toml
influxdb3_cache/src/test_helpers.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_distinct_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
influxdb3_processing_engine/src/plugins.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
influxdb3_write/src/write_buffer/table_buffer.rs
influxdb3_write/src/write_buffer/validator.rs
rust-toolchain.toml

This commit restores the old behavior we had where new tags can be added to a schema. To do this we made tags nullable and brings us in line with our other products. These changes were made in this PR:
https://github.com/influxdata/influxdb3_core/pull/41.
Changes to accomplish this new behavior were:
- Queries now do not return an empty string for null tags instead they are returned as null, or in many formats not at all.
- References to v1 for parsing and validating lines were removed as we only have one path for doing so these days shared amongst all the write_lp endpoints.
- We fixed failing tests that expected us to not be able to have new tags or depended on that functionality indirectly
- Tests had their snapshot files updated to reflect that tags are nullable by default
- Behavior …

feat: allow new tags in schema again

---

Cargo.lock
deny.toml

- update ring (ring v0.17.8 -> v0.17.13)
- added paste crate (unmaintained) to ignore list

chore: fix cargo audit failures

---

.circleci/config.yml

There is no issue for this.
In the week leading up to beta, we will be making a series of breaking changes. Disabling the automated release on merge to `main` so that we can make these changes incrementally.

chore: disable release on merge to main for beta

---

influxdb3_catalog/src/catalog/update.rs

No issue.
The method for updating the catalog to a given sequence number was off-by-one, and was only updating to the sequence before the given `update_to` sequence. This fixes that by correcting the condition.
I checked this change in enterprise as well, but making it here so it can be sync'd up.
See related [slack thread](https://influxdata.slack.com/archives/C06BQA608J3/p1741779301185649).

fix: off-by-one in catalog update logic

---

influxdb3/src/commands/serve.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/update.rs
influxdb3_catalog/src/log.rs
influxdb3_catalog/src/object_store.rs
influxdb3_catalog/src/snapshot.rs
influxdb3_wal/src/object_store.rs
influxdb3_wal/src/snapshot_tracker.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/write_buffer/validator.rs

No issue.
There were a lot of excess `DEBUG` logs littered around the catalog code from the catalog refactor that were causing a lot of noise in the log output.
This reduces that noise by:
* removing log statements that were redundant
* simplifying what is included in log statements to make them less verbose
* changing some `DEBUG` to `TRACE` in case that verbosity is needed in some cases
* several `>>>` were removed from the beginning of `DEBUG` logs throughout the code
In addition, the severity of the message emitted when there are no subscribers on catalog broadcast was changed from `WARN` to `INFO` to not raise any alarms.

chore: back-port catalog debug log cleanup from enterprise

---

influxdb3_write/src/lib.rs
influxdb3_write/src/persister.rs
influxdb3_write/src/snapshots/influxdb3_write__persister__tests__persisted_snapshot_structure.snap
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

~~Below are two commits that add versioning for PersistedSnapshot and Catalog based files.~~ The work for Enterprise versions of these files can be found [over in the Enterprise repo](https://github.com/influxdata/influxdb_pro/pull/565). The approach is much the same: a wrapper versioned enum used for serialization and deserialization that we then can use to handle different versions when we read them from object store. We need to do this now so that we can keep our formats stable during the beta.
UPDATE: With the changes to the catalog they now include a version number in the header of the file and so that commit was dropped

feat: Add versions for InfluxDB Files

---

influxdb3/tests/cli/mod.rs
influxdb3_server/src/http.rs

This fixes an issue when querying for data with no values would create incomplete JSON. This first showed up in #26057 due to `influxdb3 show database` having no data on a fresh run of the server.
While the code we had, handled the fact that if there was no data written then we should have written `[]`, however, there was a subtle edge case we did not handle. If we got a record batch and wrote it into the writer we would expect it to then write the opening `[` even if there was no data. However, this was not the case. It would only do so once it was actually writing data or we called `finish` which doesn't work for us here since we're hacking around the API in order to stream data back.
This took quite a while to track down, but the end result is a simple fix to a hard problem: if we're …

fix: Make sure JSON fully closes on empty records

---

.circleci/scripts/package-validation/validate
README_processing_engine.md

Closes #26011
Here is the followup I promised in https://github.com/influxdata/influxdb/pull/26124 (but there I was thinking the validation checks were in `ci-support`; they're not).
* fix(circleci): add librt.so to list of acceptable libraries
* feat(circleci): check for glibc portability
* fix(circleci): remove rpm --nodeps workaround in rpm validate
* chore: update README_processing_engine.md for glibc portability
Note, it's the `check_package_*` CircleCI jobs that run these scripts and they are only run on release builds, which are currently disabled. I did run snippets of the scripts locally.

fix: updates for package validation with portable glibc builds

---

.circleci/config.yml

Closes #26113
This is what we're doing with the zip file created with ci-support, but for some reason the website lists the tar.gz file for Windows rather than the zip (and the zip is not downloadable), so make the tar.gz work too.

fix(ci): update windows tarball to put dlls next to influxdb3.exe

---

query/select.go
query/select_test.go

Multiple subqueries in a FROM clause caused a
panic, insead of returning an error because
they are syntactically invalid. This corrects
that problem
closes https://github.com/influxdata/influxdb/issues/26139

fix: do not panic on invalid multiple subqueries

---

.circleci/config.yml

Re-enable the snapshot process in CI to do build on merge to `main`.

chore: re-enable release on merge to main

---

.circleci/config.yml
.gitignore

Closes #26147
fix: don't use modified .cargo/config.toml
We need to both add and remove keys from rustflags, but modifying
.cargo/config.toml in place causes the version string to have -dirty
appended to it. Use ci-support that instead creates ./.cargo/config (a
historic filename that is preferred over ./.cargo/config.toml if it
exists) and then git ignore ./.cargo/config.
References:
- https://github.com/influxdata/influxdb/issues/26147
- https://doc.rust-lang.org/cargo/reference/config.html?highlight=rustflags#hierarchical-structure
Tested by:
* after putting this PR up, triggered a CircleCI pipeline for the PR to use `persist_debug = true` (which causes the `build-dev` to persist debug builds that we can examine)
* download a Linux debug tarball for this CI run, eg, …

fix: don't use modified .cargo/config.toml

---

influxdb3/src/commands/serve.rs
influxdb3_cache/src/distinct_cache/mod.rs
influxdb3_cache/src/distinct_cache/provider.rs
influxdb3_cache/src/last_cache/mod.rs
influxdb3_cache/src/last_cache/provider.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/update.rs
influxdb3_catalog/src/channel.rs
influxdb3_catalog/src/error.rs
influxdb3_catalog/src/lib.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs

Adds the `channel.rs` module to the `influxdb3_catalog` crate that provides types for ACK'd catalog broadcast.
This makes it so that when a catalog update is made, or received from object store, it will be broadcast to the components that are subscribed to it, but will wait until each component has finished processing the update before it returns an `Ok` to the caller that invoked the catalog change.
The `CatalogSubscription` is basically a `HashMap` of MPSC channels, one for each component that subscribes to the catalog: https://github.com/influxdata/influxdb/blob/5917b7e2dc6be55646b42e964820eace5f321d1e/influxdb3_catalog/src/channel.rs#L63-L66
That sends a `CatalogUpdateMessage`: https://github.com/influxdata/influxdb/blob/5917b7e2dc6be55646b42e964820eace5f321d1e/influxdb3_catalog/src/ch …

feat: ack catalog update broadcast

---

coordinator/statement_executor.go

As I was going through some of the `statement_executor` code I noticed that we were dereferencing a nil value after checking whether it was nil.

fix: Remove nil dereference

---

influxdb3/src/commands/create.rs

No issue for this. An internal tester expressed some confusion around the `influxdb3 create token` command output with respect to the default arguments chosen by the install script:
1. By default, the data dir is completely different `--data-dir /home/ubuntu/.influxdb/data` than the install script
2. It states to use _my host name_ for `--node-id` when it uses `node0` by default.
This PR simplifies the output to not make any assumptions about their object store configuration and changing the placeholder for `--node-id` to be `<NODE_ID>` instead of `MY_HOST_NAME`.
I do not think there is a way to get the actual `--node-id` for their server.
* [Slack thread](https://influxdata.slack.com/archives/C084G9LR2HL/p1742253589376809)

chore: cleanup token create CLI message

---

influxdb3_write/src/write_buffer/mod.rs

This adds a sleep so that the parquet cache has a little bit of time to populate before we make another request to the query buffer. Sometimes it does not populate and so we have a race condition where the new request comes in and actually goes to object store. This is fine in practice because it would also take time to fill the cache in production as well. I haven't really seen the test fail since adding this, but triggering it in the first place is really hard and in practice does not happen all that often.

fix: maybe fix flakiness for parquet cache test

---

.circleci/config.yml
.circleci/packages/config.yaml

This updates:
* `.circleci/packages/config.yaml` to add a stricter regex for release images that conforms to https://github.com/influxdata/influxdb_pro/pull/606#issuecomment-2734361619 with documentation
* `.circleci/config.yml` to use the latest ci-support images (to fix an issue with `v3.0.0` and deb packages observed in preparing this PR)
* `.circleci/config.yml` to update release_filter (a looser regex than `.circleci/packages/config.yaml` for easier maintenance; `.circleci/packages/config.yaml` needs to be the most precise version so it can create packages correctly) and add some documentation on how to set tags (based on and referring to `.circleci/packages/config.yaml`)
The `.circleci/packages/config.yaml` updates were verified by running the updated `ci-support` locally. The …

chore(ci): update to handle release tags

---

influxql/query/select.go
influxql/query/select_test.go

Multiple subqueries in a FROM clause caused a
panic, insead of returning an error because
they are syntactically invalid. This corrects
that problem
closes https://github.com/influxdata/influxdb/issues/26139
(cherry picked from commit 9e00f0de98d234c76c0daeb6c60d2ec62113df1b)

fix: do not panic on invalid multiple subqueries (#26143)

---

Cargo.lock
Cargo.toml
influxdb3_process/build.rs

This is a port of [enterprise](https://github.com/influxdata/influxdb_pro/pull/606) PR to get beta builds out

chore: 3.0.0-beta.1 release ready

---

influxdb3/src/commands/query.rs
influxdb3/src/main.rs
influxdb3/tests/cli/api.rs
influxdb3/tests/cli/mod.rs
influxdb3/tests/cli/snapshots/lib__cli__fail_without_database_name.snap
influxdb3/tests/server/configure.rs
influxdb3/tests/server/mod.rs
influxdb3/tests/server/packages.rs
influxdb3/tests/server/query.rs

We need some additional multi-node testing for the Enterprise multi-node system. The CLI tests so far have just use `run()` or `run_with_confirmation()`, which requires implementers to correctly construct the CLI commands. This change introduces a variety of Query structs that have a `run()` command.

chore: Overhaul CLI tests for better ergonomics.

---

influxdb3_load_generator/src/commands/full.rs
influxdb3_load_generator/src/commands/query.rs
influxdb3_load_generator/src/commands/write.rs
influxdb3_load_generator/src/lib.rs
influxdb3_load_generator/src/line_protocol_generator.rs
influxdb3_load_generator/src/main.rs
influxdb3_load_generator/src/specification.rs

This PR refactors the load generator to make it easier to use in a set of end-to-end tests I am writing for an Antithesis PoC. It includes the following changes:
* Add a lib target to the crate, make public all the methods & types needed in the binary target.
* Make a bunch of other types public (eg `Generator`, `GeneratorRunner`, `FieldValue`, etc) to support their use in a separate e2e crate
* Fix a bug in the load generator where a cardinality value less than the lines per sample value led to duplicate LP lines where the field values of the last generated LP line overwrites all the previous values.
* The fix here was basically to give each line-per-sample a unique timestamp by incrementing the nanosecond for each generated line in a batch. It's worth noting we could potentially run …

feat: support deterministic load generator values

---

.circleci/config.yml

This is to enable checking if build is dirty due to changes to git versioned file during the build process. This used to be reported in the `influxdb3 --version` which in turn was relying on `git describe`. Because,
- we don't want the final `revision` string to contain `-dirty` and
- `git describe` does more than just report the commit hash used to tag a release
it was switched to use `git rev-parse` in [commit](https://github.com/influxdata/influxdb/pull/26167/files#diff-52906b695490184d379b6c26ce97a2b340b3cbbe924d00e50a0fbcd34136d277). 
Now with this PR, instead of reporting it's been dirtied the pipeline itself checks and stops the job if it detects any changes. 
**Test**
Tested locally and checked if the script works by manually `ssh`ing into circle ci instance and introducing …

chore: check if build is dirty and fail

---

influxdb3_load_generator/src/line_protocol_generator.rs
influxdb3_load_generator/src/specification.rs

This PR is a follow-up to https://github.com/influxdata/influxdb/pull/26174 that adds support for sequentially-generated boolean and floating point values.

feat: add BooleanValue::Toggle and FloatValue::SequentialWithInc

---

.circleci/config.yml

chore(ci): push artifacts to public bucket
Port #24491 and #25535 to master-1.x.
Clean cherry-pick of #25435 to master-1.x. Manual port of remaining piece of #24491.
Closes: #26184, #26188
(cherry picked from commit ca80b243ed929726292bf46f865c8d105e25e808)

chore(ci): push artifiacts to public bucket

---

Cargo.lock
Cargo.toml
influxdb3/Cargo.toml
influxdb3/src/commands/serve.rs
influxdb3_processing_engine/Cargo.toml
influxdb3_processing_engine/src/lib.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_shutdown/Cargo.toml
influxdb3_shutdown/src/lib.rs
influxdb3_wal/Cargo.toml
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/Cargo.toml
influxdb3_write/src/write_buffer/mod.rs

Closes #26175
Provides a new crate `influxdb3_shutdown` which provides helpers for managing clean process shutdown.
* [`wait_for_signal`](https://github.com/influxdata/influxdb/blob/56190f9ee2150e5b6aa45b683361c94f657112b7/influxdb3_shutdown/src/lib.rs#L24-L43) method that provides a system dependent future for waiting for a `Ctrl+C` signal
* The [`ShutdownManager`](https://github.com/influxdata/influxdb/blob/56190f9ee2150e5b6aa45b683361c94f657112b7/influxdb3_shutdown/src/lib.rs#L45-L51) which is used to coordinate application shutdown.
This is currently only used in the WAL, where it triggers the WAL shutdown so that the buffer is flushed and responses to waiting requests are returned before exiting the process. Other components than the WAL that need to do cleanup before proper shutdown …

feat: handle graceful shutdown

---

influxdb3/tests/cli/mod.rs
influxdb3/tests/server/mod.rs
influxdb3_wal/src/object_store.rs

Closes #26161
This makes it so that in the event that the WAL is overwritten by another process, a node that attempts to persist the next WAL file will fail and shutdown. Currently, it would just overwrite the file and keep running, which means there could be multiple processes running and overwriting each other on object store, thus corrupting data.
An integration test was added to check at the CLI level that this works as intended.

feat: shutdown on WAL overwritten

---

influxdb3/tests/cli/mod.rs
influxdb3_shutdown/src/lib.rs
influxdb3_wal/src/object_store.rs

While working the recent addition of the `influxdb3_shutdown` crate into Enterprise, I found a few gaps in its API. This brings those changes back to core. In summary,
* `ShutdownManager` is `Clone` - this works since the underlying types ([`CancellationToken`](https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html) and [`TaskTracker`](https://docs.rs/tokio-util/latest/tokio_util/task/task_tracker/struct.TaskTracker.html)) are shareable via clone.
* `ShutdownToken` is no longer `Clone`, but instead provides a `clone_cancellation_token` when just the ability to signal shutdown is needed. Cloning the `ShutdownToken` meant that when the clone was dropped, completion would be signalled and would lead to early process exit. This forces the waiting on and handling of …

chore: back-port changes to shutdown code from enterprise

---

influxdb3_server/src/builder.rs
influxdb3_server/src/http.rs
influxdb3_server/src/http/v1.rs
influxdb3_server/src/lib.rs

This is a QOL change, that could let us make the time provider something that we can set for our integration tests.

chore: remove generic term from HttpApi

---

.circleci/config.yml

`ci-support/ci-packager-next` intended to include `_<arch>` in the windows zip filename like other build artifacts (and other product downloads) but had a bug that prevented it. This updates to a `ci-support` that fixes that bug. In practice, the zip filename changes from something like `influxdb3-3.0.0-0.beta.4-windows.zip` to `influxdb3-3.0.0-0.beta.4-windows_amd64.zip`.

fix(ci): update ci-support to add _<arch> to zip filename

---

.circleci/packages/config.yaml

Helps with https://github.com/influxdata/influxdb/issues/26217
With this change, now have packages names like (tested locally):
```
influxdb3-core-3.0.0-0.beta.9998.aarch64.rpm
influxdb3-core_3.0.0-0.beta.9998_amd64.deb
influxdb3-core_3.0.0-0.beta.9998_arm64.deb
influxdb3-core-3.0.0-0.beta.9998_darwin_arm64.tar.gz
influxdb3-core-3.0.0-0.beta.9998_linux_amd64.tar.gz
influxdb3-core-3.0.0-0.beta.9998_linux_arm64.tar.gz
influxdb3-core-3.0.0-0.beta.9998-windows_amd64.zip
influxdb3-core-3.0.0-0.beta.9998.x86_64.rpm
```

fix: rename influxdb3 to influxdb3-core when building packages

---

influxdb3_server/src/http.rs
influxdb3_write/src/write_buffer/mod.rs

Closes #26222
Prevents empty writes, or writes that only contain invalid lines from creating an empty `WriteBatch` in the WAL, which results in a corrupted WAL file.
This includes the reproducer from #26222 with updates to the test to check for correct behaviour.

fix: empty writes do not corrupt wal

---

Cargo.lock
Cargo.toml

Addresses [RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023)

chore: update tokio to 1.43.1 for RUSTSEC

---

influxdb3/tests/server/configure.rs

Added an integration test that verifies that invalid field types produce an error instead of leading to a panic.
Closes #25993

test: check error behaviour on create table api

---

cmd/influx_tools/compact/command.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go

PlanOptimize is being checked far too frequently. This PR is the simplest change that can be made in order to ensure that PlanOptimize is not being ran too much. To alleviate the frequency I've added a lastWrite parameter to PlanOptimize and added an additional test that mocks the edge cause out in the wild that led to this PR.
Previously in test cases for PlanOptimize I was not checked to see if certain cases would be picked up by Plan I've adjusted a few of the existing test cases after modifying Plan and PlanOptimize to have the same lastWrite time.
(cherry picked from commit 96e44cac735baa4d7a4d40ee4f9ff9e9658a2b59)

fix: PlanOptimize is running too frequently (#26211)

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_catalog/Cargo.toml
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/update.rs
influxdb3_catalog/src/log/versions/v2.rs

This is a back-port of changes from enterprise to make it so that node state in the catalog is set to `Stopped` when the node shuts down gracefully.
I tested this manually. It is mainly needed so that when upgrading to Enterprise, the node is in a `Stopped` state in the catalog, so that there is no forced delay for an `ingest` node.

feat: catalog updates state to stopped on shutdown

---

RELEASE.md
install_influxdb.sh

Tested with:
```
$ rm -rf ~/.influxdb ; sh ~/code/dev/influxdb/install_influxdb.sh  # defaults to core
$ rm -rf ~/.influxdb ; sh ~/code/dev/influxdb/install_influxdb.sh core
$ rm -rf ~/.influxdb ; sh ~/code/dev/influxdb/install_influxdb.sh enterprise
```

fix: update install_influxdb.sh for core rename and download releases

---

Cargo.lock
Cargo.toml
influxdb3/Cargo.toml
influxdb3/src/help/influxdb3.txt
influxdb3/src/help/influxdb3_all.txt
influxdb3/src/help/serve.txt
influxdb3/src/help/serve_all.txt
influxdb3/src/main.rs

This changes the help messages for the serve command and the influxdb3 top level help output. This is to provide better help output and options for users compared to the clap defaults. After many iterations this code was the final design I landed on. In order to make our custom help work we:
1. Roughly parse the args to check for a given command and help message
2. If there is no subcommand we print out our custom help message for the top level command
3. If there is a subcommand we only print it out for serve currently
4. --help-all prints a more detailed message
This lets us upgrade our help messages in place over time as the subcommands themselves have subcommands that also need their own help messages. For now we only include these two.
We could not use something like `clap-help` or …

feat: Change help messages for influxdb3 and serve

---

install_influxdb.sh

sha256sum is present on some versions of OSX, but not all. Use 'shasum -a 256' on OSX since it should always be present.

fix(install_influxdb.sh): use 'shasum -a 256' on OSX

---

influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/error.rs

Adding this limit to ensure future compatibility with planned storage updates. I don't expect that any existing users would hit this as the system would very likely fall over if they have even close to this number of tags.

feat: limit tag columns per table to 250

---

influxdb3/src/commands/create.rs
influxdb3/src/commands/serve.rs
influxdb3/tests/cli/mod.rs
influxdb3/tests/server/configure.rs
influxdb3/tests/server/mod.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_server/src/system_tables/mod.rs
influxdb3_server/src/system_tables/tokens.rs

- Removes `--bearer-token` support and starts the server with auth by default.
- Adds `--without-auth` switch to start the server without any auth
when auth is turned off,
- disallow token endpoints (returns 405)
- remove hash column when querying tokens system table
Test runs
- Start with `--bearer-token` (fails)
```
❯ cargo run -- serve --node-id node-1 --object-store file --data-dir /home/praveen/projects/influx/test-data/  --disable-telemetry-upload --snapshotted-wal-files-to-keep 10 --force-snapshot-mem-threshold 4000 --log-filter 'info,iox_query=debug,influxdb3_server::query_executor=warn,influxdb3_server::http=warn,influxdb3_wal=debug,influxdb3_write::write_buffer::queryable_buffer=debug,influxdb3_write::write_buffer::table_buffer=debug,influxdb3::write_buffer=debug,influxdb3_enterp …
```

feat: enable auth by default

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_cache/src/last_cache/mod.rs
influxdb3_cache/src/test_helpers.rs
influxdb3_catalog/Cargo.toml
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/metrics.rs
influxdb3_catalog/src/catalog/update.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
influxdb3_write/src/write_buffer/table_buffer.rs
influxdb3_write/src/write_buffer/validator.rs

Part of #26225
Adds a metric for tracking the number of times a catalog update needed to be retried if the catalog was updated by another HTTP request or process.
The metric is included in the `/metrics` API output:
```
influxdb3_catalog_operation_retries_total 0
```

feat: catalog metrics retry counter

---

influxdb3/src/commands/create/token.rs
influxdb3/tests/cli/mod.rs
influxdb3/tests/server/mod.rs

Before this commit regenerating token didn't require confirmation, it is corrected in this PR
Test:
```
❯ cargo run -- create token --admin --regenerate  --token apiv3_EFnUPcaYl5L1kgL9DHWn2ndHCZszLJ_u1_C07hxbbijPdyxU-peBpocrkYw8DesXF5ABZPIHcSgAOpemWIVaaw
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
Running `target/debug/influxdb3 create token --admin --regenerate --token apiv3_EFnUPcaYl5L1kgL9DHWn2ndHCZszLJ_u1_C07hxbbijPdyxU-peBpocrkYw8DesXF5ABZPIHcSgAOpemWIVaaw`
Are you sure you want to regenerate admin token? Enter 'yes' to confirm
yes
Token: apiv3_3wraFGruQJd9dptX0bs-HZOUrAcmP2MZdp9yC7jwxUNlMb8fGlJwuafE3DD_lXrrf6teky3ciOSVWV31JZKLSA
HTTP requests require the following header: "Authorization: Bearer apiv3_3wraFGruQJd9dptX0bs-HZOUrAcmP2MZdp9yC7jwxUNlMb8fGlJwuafE3DD_ …
```

feat: ask for confirmation when regenerating token

---

influxdb3/src/help/serve.txt
influxdb3/src/help/serve_all.txt

Both `influxdb3 serve --help` and `influxdb3 serve --help-all` have been updated,
- updated examples section (points 2 & 3 are newly added for both `--help` and `--help-all`)
- `--without-auth` flag is added to `Common options:` section
- `--help`
```
❯ cargo run -- serve --help
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
Running `target/debug/influxdb3 serve --help`
Run the InfluxDB 3 Core server
Examples
1. influxdb3 serve --node-id node1 --object-store file --data-dir ~/.influxdb_data
2. influxdb3 create token --admin
3. Write and query with unhashed token
1. influxdb3 serve --node-id node1 --object-store s3 --bucket influxdb-data \
--aws-access-key-id KEY --aws-secret-access-key SECRET
2. influxdb3 create token --admin
3. Write and query with unhashed token …
```

feat: updates to token help message

---

influxdb3/src/commands/create.rs
influxdb3/tests/cli/api.rs
influxdb3/tests/cli/mod.rs

Closes #25824
- Changes `--tags` option for `create table` to optional
- When `--tags` is specified, requires a minimum of 1 tag be specified
> [!WARNING]
>
> Requiring a tag when `--tags` is specified is a breaking change of the CLI. The intent is now clearer and the error is specific when `--tag` is specified without additional arguments.
No longer lists `--tags` in the required **usage**.
**Before**
```
Create a new table in a database
Usage: influxdb3 create table [OPTIONS] --tags <TAGS> --database <DATABASE_NAME> <TABLE_NAME>
```
**After**
```
Create a new table in a database
Usage: influxdb3 create table [OPTIONS] --database <DATABASE_NAME> <TABLE_NAME>
```
```
influxdb3 create table cats --database dev
Table "dev"."cats" created successfully
```
```
influxdb3 query 'show columns …
```

fix: `--tags` argument is optional and now requires at least one tag

---

influxdb3/src/commands/create.rs
influxdb3/src/commands/create/token.rs
influxdb3/src/commands/delete.rs
influxdb3/src/commands/disable.rs
influxdb3/src/commands/enable.rs
influxdb3/src/commands/install.rs
influxdb3/src/commands/query.rs
influxdb3/src/commands/serve.rs
influxdb3/src/commands/show.rs
influxdb3/src/commands/show/system.rs
influxdb3/src/commands/test.rs
influxdb3/src/commands/write.rs
influxdb3/src/help/serve.txt
influxdb3/src/help/serve_all.txt

This commit is a follow up to #26246 and adds env vars to all of the TLS options in Core/Enterprise. This allows users to specify things like a CA file so that they don't need to run every single command with it specified. Same with the cert and key files. This is also nice for letting users configure environments like a Docker container with an env var rather than with command line args.
Closes #26253

feat: Add env vars for TLS options

---

influxdb3/tests/cli/api.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/update.rs
influxdb3_catalog/src/error.rs
influxdb3_server/src/http.rs

This back-ports some changes to how limits are enforced on the catalog from enterprise. There were some changes that would catch some potential bugs.
See https://github.com/influxdata/influxdb_pro/issues/567
See https://github.com/influxdata/influxdb_pro/pull/758

chore: back-port catalog limit refactor from enterprise

---

influxdb3/src/commands/create.rs

Tiny PR. Clarifies that the default max age for a Distinct Cache is 1d (86000 seconds) and default max cardinality is 100000.
Will have to move this into the new CLI help eventually. 
No ticket. Based on user feedback.

docs: clarify default maxes for distinct cache

---

Cargo.lock
Cargo.toml
install_influxdb.sh

Updates the version in Cargo and the install script.

chore: version bump for 3.0.1 (#26282)

---

influxdb3/src/commands/create.rs
influxdb3/src/commands/create/token.rs
influxdb3/tests/cli/mod.rs

closes: https://github.com/influxdata/influxdb/issues/25913
```
cargo run -- create token --admin --format json
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
Running `target/debug/influxdb3 create token --admin --format json`
{
"hashed_token": "c0d5ab879856384becbd77b326e0d160a01ca9270c4c38599a65be99f236d55bfd21360da8e1042e181a68df44c9c1663a8dd384067814fd215322a5ad3aea61",
"help_msg": "HTTP requests require the following header: \"Authorization: Bearer apiv3_MjgUZqQRNbzQgt6byYic8t1K_H9crv0d5ZS_bWhJxZxB6FSeXetjFni-X2vEiXFN7DGU0WaIjnGd-fu6-NHQRA\"",
"token": "apiv3_MjgUZqQRNbzQgt6byYic8t1K_H9crv0d5ZS_bWhJxZxB6FSeXetjFni-X2vEiXFN7DGU0WaIjnGd-fu6-NHQRA"
}
```
I've also included `help_msg`, although I suspect if someone is choosing to use `--format json` they're already …

feat: expose `--format json` for token creation cmd

---

coordinator/points_writer.go
coordinator/points_writer_test.go

Log the reason for a point being dropped,
the type of boundary violated, and the
time that was the boundary. Prints the
maximum and minimum points (by time)
that were dropped
closes https://github.com/influxdata/influxdb/issues/26252

feat: improve dropped point logging

---

influxdb3/src/help/influxdb3_all.txt
influxdb3/src/main.rs
influxdb3_clap_blocks/src/tokio.rs

Closes #26270
Introduces thread arguments consistent with InfluxDB3 Pro.
> [!IMPORTANT]
>
> If the old environment variables are used, a warning will be displayed on the console with the recommended replacement.
>
> ```sh
> influxdb3 serve
> ```
> ```text
> WARN: Use of deprecated environment variable INFLUXDB3_NUM_THREADS: replace with INFLUXDB3_NUM_IO_THREADS
> WARN: Use of deprecated environment variable INFLUXDB3_DATAFUSION_NUM_THREADS: replace with INFLUXDB3_NUM_DATAFUSION_THREADS
> ```

fix: Consistent thread arguments with influxdb3_pro

---

influxdb3/tests/cli/api.rs
influxdb3/tests/server/mod.rs
influxdb3/tests/server/query.rs
influxdb3/tests/server/snapshots/lib__server__query__api_v3_query_show_tables_ordering.snap
influxdb3_server/src/query_executor/mod.rs

Closes #25860
Teaches the `iox` table provider to sort the output of the `table_names` API, so that `SHOW TABLES` sorts the output.
Introduced a new unit test to verify the output is sorted for `SHOW TABLES`

fix: Ensure `iox` table schema is sorted for SHOW TABLES

---

.circleci/config.yml

Closes https://github.com/influxdata/edge/issues/824
Upgrade Go version from 1.23.5 to 1.23.8.

chore: upgrade go 1.23.5 -> 1.23.8 [1.10]

---

influxdb3/tests/server/mod.rs

feat: Add a negative cert test
This adds a test that will panic on server startup because connections
to said server are invalid. We add a bad expired cert to our cert
generation for usage in our tests.
Note that this test is only really valid if other tests pass as it
depends on waiting for the server start checks to fail. If other
tests run then their server started fine and so did this one, the
only difference being that connections will error due to a bad tls cert.
Closes #26256
feat: Add minimum TLS version test 
This is a follow on to #26307. In this commit we add a test where we
check that connections only pass if TLS is set to v1.3. The default is
1.2 and other tests connect with that just fine. In this test we spin
up a server using only v1.3 as the minimum and try to connect …

feat: Add more TLS tests to the test suite

---

influxdb3/tests/server/query.rs
influxdb3_server/src/http/v1.rs

Closes #26216 
Closes #26218 
`GROUP BY` identifiers that were escape quoted, e.g., `\"name\"`, were not having the quotes removed when compared to columns in the `Schema` during `GROUP BY` evaluation. This uses the `Identifier::as_str` method to exclude the quotes.
The reproducer from #26128 is included in this PR.

fix: group by tag columns with escape quotes

---

influxdb3/src/commands/serve.rs
influxdb3/tests/server/mod.rs
influxdb3_server/src/lib.rs

No issue for this. I was working on https://github.com/influxdata/influxdb/issues/26216 and decided to make this change.
This alters the logging behaviour and UX for the [`TestServer`](https://github.com/influxdata/influxdb/blob/6fb4112dc3c51c9723eefd50077e439aa1b9771d/influxdb3/tests/server/mod.rs#L195-L200) harness that is used in our integration tests in the `influxdb3` crate.
The primary change is the addition of a CLI argument for the `serve` command (`--tcp-listener-file-path`) that the server will use to write out the listener address that it is listening for TCP connections on.
The argument is hidden and defaults to `None`.
This can be used by our test harness, which uses a bind address of `0.0.0.0:0` in order to select a randomly available port.
The test harness creates a …

feat: improve control of logs on test harness

---

influxdb3_cache/src/distinct_cache/cache.rs
influxdb3_cache/src/distinct_cache/mod.rs
influxdb3_catalog/src/catalog.rs

Closes #26318
Includes and fixes the reproducer for #26318 originally added in https://github.com/influxdata/influxdb/pull/26331/commits/cf79b28071d3256e06e8c288e59648362e5ef915
The distinct cache was not counting the number of results properly when a projection on one column was used in conjunction with a `WHERE` predicate on another column.

fix: distinct cache counting bug

---

influxdb3/src/commands/create.rs
influxdb3/tests/server/configure.rs
influxdb3_cache/src/last_cache/mod.rs
influxdb3_cache/src/last_cache/snapshots/influxdb3_cache__last_cache__tests__catalog_initialization.snap
influxdb3_catalog/src/error.rs
influxdb3_catalog/src/log/versions/v2.rs

Removes limitation on cache size of 10 for Last Value Cache. 
Additionally, closes #25522

feat: Remove Last Cache Size Limitation

---

influxdb3/src/commands/serve.rs
influxdb3/tests/cli/mod.rs
influxdb3_server/src/http.rs

- return 405 message body to indicate the endpoints are disabled
- extra log to say server has been started without auth

feat: additional info when started --without-auth

---

Cargo.lock
influxdb3/Cargo.toml
influxdb3/src/commands/create.rs
influxdb3/tests/cli/mod.rs
influxdb3/tests/server/mod.rs

Updates the output to more clearly identify the success of the command, the output of the command, and the importance of storing the token. 
Uses ANSI for styling, so it's non-terminal specific, but requires Regex for parsing now. 
The current design is very nondescript, doesn't mention the importance of saving the token, and is easily lost as CLI outputs and commands grow.
The new design is specifically calls out success of creating a token, more cleanly identifies the token itself, and also very clearly mentions that it should be stored securely.
The green could have been helpful, but I feel pollutes the UX with too much visual overload with an additional color. 
Additionally, tried an example with the left bars to more cleanly display results. This looks nice, but on smaller terminals …

fix: update token creation output

---

RELEASE.md

Update `RELEASE.md` for the new release process.
See the preview'd markdown [here](https://github.com/influxdata/influxdb/blob/hiltontj/release-process-udpate/RELEASE.md).

docs: update RELEASE.md for post-GA process

---

tsdb/config.go
tsdb/engine.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/scheduler.go
tsdb/store.go

Limit number of concurrent optimized compactions so that level compactions do not get starved. Starved level compactions result in a sudden increase in disk usage.
Add [data] max-concurrent-optimized-compactions for configuring maximum number of concurrent optimized compactions. Default value is 1.
Closes: #26315

fix: limit number of concurrent optimized compactions

---

tsdb/config.go
tsdb/engine.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/scheduler.go
tsdb/store.go

Limit number of concurrent optimized compactions so that level compactions do not get starved. Starved level compactions result in a sudden increase in disk usage.
Add [data] max-concurrent-optimized-compactions for configuring maximum number of concurrent optimized compactions. Default value is 1.
Co-authored-by: davidby-influx <dbyrne@influxdata.com>
Co-authored-by: devanbenz <devandbenz@gmail.com>
Closes: #26315
(cherry picked from commit 66f4dbe)Closes #

chore: update to go 1.23.8 (1.12) (#26309)

---

influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/metrics.rs

Closes #26225 
This adds the `influxdb3_catalog_operations_total` metric for tracking the number of catalog operations by their type.
They appear in the prometheus `/metrics` output like so:
```
influxdb3_catalog_operations_total{type="create_database"} 1
influxdb3_catalog_operations_total{type="create_table"} 1
influxdb3_catalog_operations_total{type="register_node"} 1
```

feat: catalog metrics to count operation types

---

tsdb/index/tsi1/log_file.go

I looks like we are holding a reader lock and defer'ing it, while at the same time acquiring that same reader lock within the call to `return tk.TagValueIterator()` 
According to Go's RWMutex documentation this is not a good idea: https://pkg.go.dev/sync#RWMutex
> If any goroutine calls [RWMutex.Lock](https://pkg.go.dev/sync#RWMutex.Lock) while the lock is already held by one or more readers, concurrent calls to [RWMutex.RLock](https://pkg.go.dev/sync#RWMutex.RLock) will block until the writer has acquired (and released) the lock, to ensure that the lock eventually becomes available to the writer. Note that this prohibits recursive read-locking.
I believe this is what is causing the deadlock we are seeing in a few different tickets. I had ran a reproducer where I was effectively reading …

feat: TagValueIterator holds RLock recursively

---

influxdb3/tests/server/auth.rs
influxdb3_server/src/http.rs

closes: https://github.com/influxdata/influxdb/issues/25833
The tokens below are base64 encoded built from `export BASIC=$(echo -n "username:$TOKEN" | base64 -w 0)`
- Before this change
```
❯ curl -H "Authorization: Basic dXNlcm5hbWU6YXBpdjNfSmthbHYtSVBLcUpSMlA3UVQwbjI4Z0ZwZjFpRXdLLWVaN3E2aFhxeXpySnUwa0VQQi1WRTg4ZUdYVFR6OUdLaHdLbTM4LTZxa3lrS1BkaE5lZHVTOWc=" -H "Content-type: application/text" http://localhost:8181/write\?db=foo -X POST --data-binary "mymeas,mytag1=sometag value=0.56 $(date +%s%N)" -vv
Note: Unnecessary use of -X or --request, POST is already inferred.
12:03:01.635872 [0-0] * Host localhost:8181 was resolved.
12:03:01.635910 [0-0] * IPv6: ::1
12:03:01.635921 [0-0] * IPv4: 127.0.0.1
12:03:01.635933 [0-0] * [SETUP] added
12:03:01.635963 [0-0] *   Trying [::1]:8181... …
```

feat: support `Basic $TOKEN` for all apis

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/reader_test.go

The error type check for errBlockRead was incorrect, and bad TSM files were not being moved aside when
that error was encountered. Use errors.Join,
errors.Is, and errors.As to correctly unwrap multiple errors.
Closes https://github.com/influxdata/influxdb/issues/25838
(cherry picked from commit 800970490a715d2b6eb5a0a7fed7fb4e9707af5d)
Closes https://github.com/influxdata/influxdb/issues/25840
(cherry picked from commit dd7b4ce35165cc6b355298fc3ae8cc58e8679717)

fix: move aside TSM file on errBlockRead (#25899)

---

cmd/influxd/inspect/type_conflicts/schema.go
sqlite/sqlite.go

* fix: defer calls that return a closure need to be called
* fixes #25950
* chore: avoid a double close
* chore: call defer
(cherry picked from commit de12b6d07efe4c638ef3e325db3cf466df114b84)

fix: defer calls that return a closure need to be called (#25951)

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/writer.go

There are a number of code paths in Compactor.write which on error can lead to leaked file handles to temporary files. This, in turn, prevents the removal of the temporary files until InfluxDB is rebooted, releasing the file handles.
closes https://github.com/influxdata/influxdb/issues/25724
(cherry picked from commit e974165d252a1904b5ede5b88104301b32842b81)
closes https://github.com/influxdata/influxdb/issues/25739
(cherry picked from commit c82d4f86eeb554c94e7e21644a98cd7a3ca071f2)

fix: do not leak file handles from Compactor.write (#25725) (#25740)

---

tsdb/engine/tsm1/compact.go

This PR adds an error join to help with handling multiple errors from snapshot file writers.
(cherry picked from commit 4ad5e2aba7d6d725e4ba81ed15a2b96fb2869ec2) (cherry picked from commit 982ae57f22c3b772747f7621c1cf78834698f463)

feat: Add error join for file writing in snapshots (#26004) (#26005)

---

pkg/data/gensyncmap/gensyncmap.go
tsdb/engine/tsm1/engine.go
tsdb/field_validator.go
tsdb/shard.go
tsdb/shard_test.go

* fix: switch MeasurementFields from atomic.Value to sync.Map (#26022)
Simplify and speed up synchronization for
MeasurementFields structures by switching
from a mutex and atomic.Value to a sync.Map
(cherry picked from commit b617eb24a767c9adfcfd490e0d543bd5924c2052)
closes https://github.com/influxdata/influxdb/issues/26001
* fix: lock MeasurementFields while validating (#25998)
There was a window where a race between writes with
differing types for the same field were being validated.
Lock the  MeasurementFields struct during field
validation to avoid this.
closes https://github.com/influxdata/influxdb/issues/23756
(cherry picked from commit 5a20a835a55d9bd77810b1d47a0699dee18c42b9)
helps https://github.com/influxdata/influxdb/issues/26001

fix: prevent differing field types in the same shard (#26025)

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/engine.go

Add more robust temporary file removal
on a failed compaction. Don't halt on
a failed removal, and don't assume a
failed compaction won't generate
temporary files.
closes https://github.com/influxdata/influxdb/issues/26068
(cherry picked from commit ba95c9b0f061d9730739a2997d18efd7ed11dc8e)
closes https://github.com/influxdata/influxdb/issues/26069
(cherry picked from commit d169651dff15065fa564dca5ee4155b0a584efcc)
closes https://github.com/influxdata/influxdb/issues/26384

fix: ensure temp files removed on failed compaction (#26070) (#26071)

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/file_store.go

Also fixes error type checks in
TestCompactor_CompactFull_InProgress
(cherry picked from commit 2ab5aad52e9e7a38fa6cfef49156c2055d51eefc) (cherry picked from commit efebf4d569ec2d355db7f05958a09dde080e6a16)

chore: add logging to Filestore.purger (#26089) (#26103)

---

influxql/query/select.go
influxql/query/select_test.go

Multiple subqueries in a FROM clause caused a
panic, insead of returning an error because
they are syntactically invalid. This corrects
that problem
closes https://github.com/influxdata/influxdb/issues/26139
(cherry picked from commit 9e00f0de98d234c76c0daeb6c60d2ec62113df1b)
(cherry picked from commit e8625017698c7e873e6ed212fd9845c1357dd3bb)

fix: do not panic on invalid multiple subqueries (#26143) (#26162)

---

tsdb/shard.go
v1/coordinator/points_writer.go
v1/coordinator/points_writer_test.go

Log the reason for a point being dropped,
the type of boundary violated, and the
time that was the boundary. Prints the
maximum and minimum points (by time)
that were dropped
closes https://github.com/influxdata/influxdb/issues/26252
(cherry picked from commit 62e803e673ace7aeb3204b5b13c55665cf1fc1a8)
closes https://github.com/influxdata/influxdb/issues/26295
(cherry picked from commit eebe655e4c596b8f78bae30e5729092b6732d1a7)
closes https://github.com/influxdata/influxdb/issues/26399

feat: improve dropped point logging (#26303)

---

tsdb/index/tsi1/log_file.go

I looks like we are holding a reader lock and defer'ing it, while at the same time acquiring that same reader lock within the call to `return tk.TagValueIterator()`
According to Go's RWMutex documentation this is not a good idea: https://pkg.go.dev/sync#RWMutex
> If any goroutine calls [RWMutex.Lock](https://pkg.go.dev/sync#RWMutex.Lock) while the lock is already held by one or more readers, concurrent calls to [RWMutex.RLock](https://pkg.go.dev/sync#RWMutex.RLock) will block until the writer has acquired (and released) the lock, to ensure that the lock eventually becomes available to the writer. Note that this prohibits recursive read-locking.
I believe this is what is causing the deadlock we are seeing in a few different tickets. I had ran a reproducer where I was effectively reading …

feat: TagValueIterator holds RLock for too long (#26369)

---

influxdb3_cache/src/last_cache/metrics.rs
influxdb3_cache/src/last_cache/mod.rs
influxdb3_cache/src/last_cache/provider.rs
influxdb3_cache/src/last_cache/table_function.rs
influxdb3_catalog/src/catalog.rs

Part of #26227 
Adds a prometheus metric to track query duration for successful queries made to the last values cache: `influxdb3_last_values_cache_query_duration_seconds_*`.
This tracks query durations as a histogram _per_ database, via the `db` label.
The implementation tracks the time it takes for datafusion to scan the cache and produce a record batch by instantiating the metric recorder in the `TableProvider::scan` implementation for the last cache function (see [here](https://github.com/influxdata/influxdb/blob/2041cb95c3fe4cd39507ee9cb8671df9ec19569c/influxdb3_cache/src/last_cache/table_function.rs#L78-L81)).
Here is an example of the metrics added to the `/metrics` output:
<details><summary>Expand</summary>
<p>
```
influxdb3_last_values_cache_query_duration_seconds_bucket{db="foo", …
```

feat: query duration metrics in lvc

---

.circleci/config.yml
go.mod

Clean cherry-pick of #26291 to 2.7 branch.
(cherry picked from commit dc86dcb55ee417d6041f0902733fede7fa7d0497)

chore: update to go 1.23.8

---

Cargo.lock
Cargo.toml
influxdb3/tests/server/ping.rs
influxdb3_process/Cargo.toml
influxdb3_process/build.rs
influxdb3_process/src/lib.rs
influxdb3_server/Cargo.toml
influxdb3_server/src/http.rs

Further, the product version can be modified by updating the metadata in the `influxdb3_process` `Cargo.toml`.
Closes #26138
Adds additional headers to the `/ping` response per the requirements outlined in #26138
```sh
❯ curl -i $"($env.INFLUXDB3_HOST_URL)/ping"
```
```http
HTTP/1.1 200 OK
content-type: application/json
request-id: 0196e6d7-5ae5-7650-8f73-e81033bd8197
x-influxdb-build: Core
x-influxdb-version: 3.1.0-nightly
x-request-id: 0196e6d7-5ae5-7650-8f73-e81033bd8197
access-control-allow-origin: *
transfer-encoding: chunked
date: Mon, 19 May 2025 04:39:55 GMT
{"version":"3.1.0-nightly","revision":"a967e23171","process_id":"836df3ab-4cab-4c10-90cc-fadf9c92731e"}
```
> [!NOTE]
>
> The HTTP stack in Rust is normalising the header field names to lowercase, which is fine. Per [Section …

feat: `/ping` API contains versioning headers

---

Cargo.toml
influxdb3_cache/src/distinct_cache/cache.rs
influxdb3_cache/src/last_cache/cache.rs
influxdb3_py_api/src/system_py.rs
influxdb3_wal/src/lib.rs
influxdb3_write/src/write_buffer/table_buffer.rs

There were several `Key` variants for handling series key columns from the experimental v3 write API that was phased out and removed from an earlier iteration of `influxdb3`.
This removes those variants as that feature is no longer planned.
Helps with #26441

refactor: remove variants for unused series key type

---

.circleci/config.yml

see: https://circleci.com/docs/deploy-to-aws/#deploy-awscli
This will install `awscli` to the CI machine while running s3 sync

feat: Install awscli per circle ci docs

---

influxdb3_write/src/write_buffer/mod.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Part of #26441 
I found a place where empty string was being used to fill in missing tags, instead of `NULL`. This is when persisting parquet. If a tag column has not been written, e.g., since the last snapshot, and therefore is absent in the buffer, then tags were being filled in with `""` instead of nulls (see [here](https://github.com/influxdata/influxdb/blob/56df158afd593e0f90590a658e36476158cd47f8/influxdb3_write/src/write_buffer/table_buffer.rs#L399)).
A reproducer was added for this scenario, which can be seen failing originally [in CI](https://app.circleci.com/pipelines/github/influxdata/influxdb/45990/workflows/a7bad554-a490-415e-924b-19135f394b42/jobs/437126?invite=true#step-110-96428_41) for 62cca91745cdc1aa342205d80d9b772f91dc3a8f
The issue is fixed in …

test: reproduce problem with NULL backfill of omitted tag cols

---

influxdb3_cache/src/distinct_cache/cache.rs
influxdb3_cache/src/last_cache/cache.rs
influxdb3_py_api/src/system_py.rs
influxdb3_wal/src/lib.rs
influxdb3_write/src/write_buffer/table_buffer.rs

Addresses #26452
Re-introduce the `Key` variant to the `FieldData` type in the WAL to fix WAL file deserialization of WAL files created before https://github.com/influxdata/influxdb/pull/26443

fix: add key variant back to wal to fix bitcode deserialization

---

Dockerfile

The `INFLUXDB3_OBJECT_STORE` and `INFLUXDB3_DB_DIR` env vars were not being used in the Dockerfile.
Helps with https://github.com/influxdata/influxdb/issues/26459

fix: use correct ENV vars in Dockerfile

---

influxdb3_authz/Cargo.toml
influxdb3_authz/src/lib.rs

Adds the `lints.workspace = true` to `influxdb3_authz/Cargo.toml` and addresses resulting linter errors.

chore: add workspace lints to influxd3_authz crate

---

Cargo.lock
Cargo.toml

Update version in `Cargo.toml` to `3.1.0` for the `3.1` release branch.

chore: update version to 3.1.0

---

RELEASE.md

Added some documentation to `RELEASE.md` following the `3.1` release.

docs: minor release docs

---

go.mod
go.sum
scripts/ci/test-downgrade.sh
scripts/fetch-ui-assets.sh

sha256sum in busybox doesn't support --check.
go-sqlite3 fails to build: https://github.com/mattn/go-sqlite3/issues/1164

fix: fix compilation on alpine linux

---

influxdb3/src/commands/serve.rs
influxdb3_wal/src/lib.rs

Currently when there is an OOM while snapshotting, the process keeps going without crashing. This behaviour is observed in main (commit: be25c6f). This means the wal files keep increasing to a point that restarts never can replay all the files.
This is happening because of the distribution of memory, in enterprise especially there is no need for an ingester to be allocated just 20% for datafusion memory pool (which runs the snapshot) as parquet cache is not in use at all. This 20% is too conservative for an ingester, so instead of redistributing the memory settings based on the mode it's running, a separate write path executor is introduced in this commit with no bound on memory (still uses `GreedyMemoryPool` under the hood with `usize::MAX` as upper limit). This means write path executor …

feat: separate out write path executor with unbounded memory limit

---

tsdb/engine/tsm1/engine.go

Previously 
```go
// StartOptHoldOff will create a hold off timer for OptimizedCompaction
func (e *Engine) StartOptHoldOff(holdOffDurationCheck time.Duration, optHoldoffStart time.Time, optHoldoffDuration time.Duration) {
startOptHoldoff := func(dur time.Duration) {
optHoldoffStart = time.Now()
optHoldoffDuration = dur
e.logger.Info("optimize compaction holdoff timer started", logger.Shard(e.id), zap.Duration("duration", optHoldoffDuration), zap.Time("endTime", optHoldoffStart.Add(optHoldoffDuration)))
}
startOptHoldoff(holdOffDurationCheck)
}
```
was not passing the data by reference which meant we were never modifying the `optHoldoffDuration` and `optHoldoffStart` vars. 
This PR also adds additional logging to Optimized level 5 compactions to clear up a little bit of confusion around …

feat: Add new logging for compaction level 5 and remove bug with holdoff

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3/src/help/serve_all.txt
influxdb3_processing_engine/src/lib.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_server/tests/lib.rs
influxdb3_wal/Cargo.toml
influxdb3_wal/src/object_store.rs
influxdb3_wal/src/snapshot_tracker.rs
influxdb3_write/src/write_buffer/mod.rs

WAL replay currently loads _all_ WAL files concurrently running into OOM. This commit adds a CLI parameter `--wal-replay-concurrency-limit` that would allow the user to set a lower limit and run WAL replay again.
Also, small refactor to introduce args struct to hold the all the params to `WalObjectStore::new` method and remove `#[allow(clippy::too_many_arguments)]`.
CLI changes added to WAL section as below,
```
WAL Configuration:
--wal-flush-interval <INTERVAL>  Interval to flush data to WAL file [default: 1s]
[env: INFLUXDB3_WAL_FLUSH_INTERVAL=]
--wal-snapshot-size <SIZE>       Number of WAL files per snapshot [default: 600]
[env: INFLUXDB3_WAL_SNAPSHOT_SIZE=]
--wal-max-write-buffer-size <SIZE>
Max write requests in buffer [default: 100000]
[env: INFLUXDB3_WAL_MAX_WRITE_BUFFER_SIZE=] …
```

feat: add concurrency limit for WAL replay

---

Cargo.lock
Cargo.toml

Update `influxdb3_core` dependencies to use changes from https://github.com/influxdata/influxdb3_core/pull/48

chore: update `influxdb3_core`

---

influxdb3/tests/cli/mod.rs
influxdb3_server/src/http.rs

Prevents database names that start with `_` when created explicitly through the Create Database or Create Table APIs.
Closes #26505

fix: do not allow _ in db names on API-based create

---

influxdb3/src/help/serve.txt
influxdb3/src/help/serve_all.txt

Moves some commands to better locations, removes `--bearer-token`, and removes yours truly from the output.

fix: update help text

---

cmd/influxd/run/server.go
services/retention/service.go
services/retention/service_test.go

Stop noisy logging about phantom shards that do not belong to the current node by checking the shard ownership before logging about the phantom shard. Note that only the logging was inaccurate. This did not accidentally remove shards from the metadata that weren't really phantom shards due to checks in `DropShardMetaRef` implementations.
closes: #26525

fix: stop noisy logging about phantom shards that do not belong to node

---

Cargo.lock
influxdb3/src/commands/serve.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/metrics.rs
influxdb3_catalog/src/catalog/update.rs
influxdb3_process/src/lib.rs
influxdb3_server/src/http.rs
influxdb3_shutdown/Cargo.toml
influxdb3_shutdown/src/lib.rs
influxdb3_write/src/write_buffer/mod.rs

(no issue for this)
- `AbortableTaskRunner` and it's friends in influxdb3_shutdown
- `ProcessUuidWrapper` and it's friends in influxdb3_process
- Change sleep time in test
They're not used currently in any of the core code, but helps when sync'ing core back to enterprise

chore: porting some utilities that were created in pro

---

influxdb3/src/commands/serve.rs
influxdb3/src/help/serve_all.txt
influxdb3_processing_engine/src/lib.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_server/tests/lib.rs
influxdb3_write/src/write_buffer/mod.rs

This PR addresses a shortcoming in `PersistedFiles` (an index of gen1 files kept in querier/ingester memory) load during startup by:
* Making the "lookback" duration configurable with the number of persisted files determined by dividing the configured gen1 file duration into this new gen1 lookback duration.
* Setting the default lookback to 1 month. With the default gen1 file duration of 10m, this would lead to roughly 4320 files loaded by default.
One good bit of feedback reviewers could give here would be whether we should consider looking further back, maybe as far back as 3 or 6 months? This would lead to 12960 or 25920 files loaded on startup by default.

feat: make persisted file buffer size configurable

---

influxdb3/src/commands/serve.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_server/src/query_executor/mod.rs
influxdb3_server/tests/lib.rs
influxdb3_wal/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_wal/src/serialize.rs
influxdb3_write/src/write_buffer/mod.rs

This PR fixes a critical issue where InfluxDB3 would panic on startup when encountering corrupt or empty WAL files, typically after power outages or disk failures.
When WAL files become corrupted (e.g., truncated to 0 bytes during power loss), the server would panic with:
```
thread 'main' panicked at influxdb3_wal/src/serialize.rs:50:30:
range end index 8 out of range for slice of length 0
```
This prevented the server from starting, requiring manual intervention to remove corrupt files.
Now, the user will see a WARN log when encountering corrupt WAL files:
```
2025-06-24T07:19:41.278619Z  WARN influxdb3_wal::object_store: Skipping corrupt WAL file error=WAL file too small: expected at least 12 bytes, but got 0 bytes path=ingest/wal/00000000009.wal
```
The user can opt-out of this …

fix: handle corrupt WAL files during replay without panic

---

.circleci/config.yml

Stop publishing nightly changelog since we do not publish nightly build artifacts. This addresses issues with dependent projects that check status of CI for influxdb.
This is a clean cherry-pick from master-1.x.
Closes: #26540
(cherry picked from commit 4378e857441aaca5b972ddda48441935658c551b)

chore: stop publishing nightly changelog

---

Cargo.lock
Cargo.toml
install_influxdb.sh

- Version bump `Cargo.toml`
- Update `install_influxdb.sh` script to point to `3.2.0`

chore: version bump in Cargo.toml to 3.3.0-nightly

---

influxdb3/src/commands/create.rs
influxdb3/src/commands/delete.rs
influxdb3/src/commands/disable.rs
influxdb3/src/commands/enable.rs
influxdb3/src/commands/plugin_test/wal.rs
influxdb3/src/commands/serve.rs
influxdb3/src/commands/update.rs
influxdb3/tests/cli/admin_token.rs
influxdb3/tests/cli/api.rs
influxdb3/tests/cli/db_retention.rs
influxdb3/tests/cli/mod.rs
influxdb3/tests/server/limits.rs
influxdb3/tests/server/packages.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/log/versions/v2.rs
influxdb3_catalog/src/log/versions/v3.rs
influxdb3_load_generator/src/commands/write.rs
influxdb3_load_generator/src/commands/write_fixed.rs
influxdb3_load_generator/src/line_protocol_generator.rs
influxdb3_process/build.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_processing_engine/src/plugins.rs
influxdb3_processing_engine/src/virtualenv.rs
influxdb3_py_api/src/system_py.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs
influxdb3_wal/src/object_store.rs
influxdb3_write/src/write_buffer/persisted_files.rs
influxdb3_write/src/write_buffer/queryable_buffer.rs
rust-toolchain.toml

🦀 1.88. See [blog post](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0) for more!
Biggest change was the lint for [uninlined format args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args)

chore: Update to Rust 1.88

---

influxdb3/tests/server/query.rs
influxdb3_server/src/http/v1.rs

This fixes https://github.com/influxdata/influxdb/issues/26570
See additional discussion in that issue, particularly around the difference in default output timestamp formatting for CSV vs JSON.

fix: v1 query API should default to ns for CSV output

---

influxdb3/tests/cli/api.rs
influxdb3/tests/cli/mod.rs
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/update.rs
influxdb3_catalog/src/log/versions/v3.rs
influxdb3_server/src/lib.rs
influxdb3_server/src/system_tables/databases.rs
influxdb3_server/src/system_tables/mod.rs
influxdb3_server/src/system_tables/tables.rs
influxdb3_types/src/http.rs

Helps
- #26568
This PR addresses the following TODO items from #26568
Further, it extends the `databases` and `tables` system tables for the `_internal` database to include a new column for the `hard_deletion_date`:
```sh
influxdb3 query --database _internal 'select * from system.tables'
```
```text
+---------------+--------------------+--------------+--------------------+------------------+----------------------+---------+---------------------+
| database_name | table_name         | column_count | series_key_columns | last_cache_count | distinct_cache_count | deleted | hard_deletion_date  |
+---------------+--------------------+--------------+--------------------+------------------+----------------------+---------+---------------------+
| dev           | t1-20250701T063942 | 9 …
```

fix: Existing soft-deleted schema can be hard-deleted

---

docker/Dockerfile.ci

https://www.influxdata.com/blog/linux-package-signing-key-rotation/ discusses the signing key rotation we did in 2023. We are getting to the point of having to rotate the key and this will assist in that work. Most docs and containers are still using the `influxdata-archive_compat.key` which was created for maximum compatibility, but it has limitations because it does not use the modern primary/subkey approach used by `influxdata-archive.key`. The compat key is required for very old systems like RHEL 7 (standard support ended in June 2024), Debian 9 (EOL in June 2022), Ubuntu 18.04 (standard support ended in April 2023).
RHEL 8, Debian 10 (buster; already EOL), Ubuntu 20.04 (standard support ended in April 2025), et al have new enough RPM and APT that supports `influxdata-archive.key`. …

chore: use influxdata-archive.key in docker/Dockerfile.ci

---

services/httpd/handler.go
services/httpd/handler_test.go

* This PR will add a `time_format` parameter which takes in the value "epoch" or "rfc3339". The default will be "epoch" depending on the value output timestamps will be formatted in epoch or rfc3339.
Closes FR#615

feat: Adds time_format param for httpd

---

influxdb3_catalog/src/lib.rs

This PR backports influxdata/influxdb_pro#1004 which adds module documentation to `influxdb3_catalog`.
- Added comprehensive module documentation to `influxdb3_catalog/src/lib.rs`
- Documents the catalog's persistence mechanism using log and snapshot files
- Explains the versioning system for both file types
- Provides instructions for adding new versions, including:
- Creating version modules
- Implementing conversion functions
- Updating deserialization logic
- Managing module re-exports
- Working with the `Snapshot` trait (snapshot files only)
- Includes code snippets and considerations for maintaining backward compatibility
- Documents the version history (v1-v3) and migration patterns
The catalog is the metadata management system for InfluxDB 3, maintaining information about …

chore: backport module documentation for influxdb3_catalog

---

influxdb3/src/commands/create.rs
influxdb3/src/commands/create/token.rs
influxdb3/src/commands/serve.rs
influxdb3/src/help/serve_all.txt
influxdb3/tests/cli/admin_token.rs
influxdb3/tests/cli/api.rs
influxdb3/tests/server/mod.rs
influxdb3_server/src/http.rs
influxdb3_server/src/lib.rs

- new server to only serve admin token regeneration without an admin token has been added
- minor refactors to allow reuse of some of the utilities like trace layer for metrics moved to their own functions to allow them to be instantiated for both servers
- tests added to check if both the new server works right for regenerating token and also ensure none of the other functionalities are available on the admin token recovery server
closes: #26330
The admin token recovery (using `--regenerate`) currently requires a valid admin token to be passed in. If that's lost for some reason there is no way to get back into the server other than switching back to running `--without-auth`. This PR addresses it by assuming the following workflow,
- User starts the server passing in …

feat: admin token recovery

---

tsdb/shard.go

Currently we do not expose the error thrown by Shard.LastModified, this PR will add `Shard.LastModifiedOrErr` which will expose the actual error when it's called.

feat: Adds LastModifiedOrErr to expose error for LastModified

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/file_store.go

Streamline compaction logging, while
providing more information to debug
remnant temporary files.
(cherry picked from commit https://github.com/influxdata/influxdb/commit/ea36c5ff479fcaf14dd123dde4014039cf2d38ee)

chore: improve logging on compaction failures (#26545)

---

Cargo.lock
influxdb3/tests/server/snapshots/lib__server__write__special_chars_query_results.snap
influxdb3/tests/server/snapshots/lib__server__write__special_chars_table_columns.snap
influxdb3/tests/server/write.rs
influxdb3_catalog/Cargo.toml
influxdb3_catalog/src/catalog.rs
influxdb3_catalog/src/catalog/update.rs

Adds validation to reject empty tag and field names, or those containing control characters when creating tables via the catalog API, ensuring compatibility with the line protocol parser.
**Validation logic**
Added `validate_key()` function in `influxdb3_catalog/src/catalog/update.rs` that rejects:
- Empty strings
- Control characters (ASCII 0x00-0x1F and 0x7F)
**Test coverage**:
- Unit tests with `rstest` for various invalid cases (empty strings, newlines, tabs, etc.)
- Unit tests confirming valid names including those requiring line protocol escaping (spaces, commas, equals)
- Integration test demonstrating end-to-end table creation and line protocol writes with special characters
- Not a breaking change - tables with control characters were already unusable via line protocol
- Special …

fix: validate tag and field names when creating tables

---

tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go

Correct locking bug in `Engine.deleteReadSeries`. Under certain circumstances delete requests can cause a read lock to be leaked, which can then block further write locks in a `deleteReadSeries` call. This blocks the delete request from completing, and potentially blocks other options which use `FileStore.Apply`, such as compaction.
Also added tests that fail with a timeout with the previous improper locking.
Closes: #26648

fix: correct locking bug when deleting a series

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go

Fix issue introduced with 1.12.1 that caused some TSM files to not be scheduled for full compaction when they should be. The user visible symptom was an unbounded increase in disk space for impacted shards.
This simplifies the compaction planning code by removing the PT_SmartOptimize and PT_NoOptimize special cases. These are no longer needed for performance thanks to the first block caching code that was also added in #26432. Issues with the PT_SmartOptimize and PT_NoOptimize cases could cause TSM files to be locked by the compaction planner as in-use, preventing them from being compacted.
The optimized compaction hold-off is now handled entirely in Engine.compact rather than by the compaction planner.
Update test cases as necessary for changes, plus add checks for issue that caused …

fix: full compactions not scheduled under some circumstances

---

influxdb3/src/help/serve_all.txt
influxdb3_clap_blocks/src/object_store.rs

This commit allows users to specify the endpoint that they want when using Azure for blob storage. We also automatically enable the allow http flag so that they can specify localhost as their URL if using something like Azurite to test Azure Blob Storage locally.
Closes #26390

feat: Add --azure-endpoint argument to the CLI

---

cmd/influx_tools/main.go
cmd/influxd/run/server.go
monitor/build_info_test.go
monitor/go_runtime_test.go
monitor/network_test.go
monitor/service.go
monitor/service_test.go
monitor/system_test.go
services/httpd/handler.go
tsdb/config.go

* Adds new field to debug/vars which includes various configuration information about a data node\ Example output:
```
"config": {
"aggressive-points-per-block": 10000,
"cache-max-memory-size": 1073741824,
"cache-snapshot-memory-size": 26214400,
"cache-snapshot-write-cold-duration": "10m0s",
"compact-full-write-cold-duration": "4h0m0s",
"compact-throughput": 50331648,
"compact-throughput-burst": 50331648,
"dir": "/home/foo/.influxdb/data",
"max-concurrent-compactions": 0,
"max-index-log-file-size": 1048576,
"max-series-per-database": 1000000,
"max-values-per-tag": 100000,
"series-file-max-concurrent-compactions": 0,
"series-id-set-cache-size": 100,
"strict-error-handling": false,
"wal-dir": "/home/foo/.influxdb/wal",
"wal-fsync-delay": "0s"
},
```

feat: Adds 'config' to 'debug/vars' http endpoint

---

.circleci/packages/influxdb/fs/usr/lib/influxdb/scripts/init.sh

The init.sh script assumes that it being run as root so thus we can use
sudo to switch user to the influxdb user to run buildtsi; otherwise the
files are owned by root and influxdb can't start.
* fixes #26698

fix(packaging): init.sh should run buildtsi as influxdb user

---

influxdb3/src/commands/common.rs
influxdb3/src/commands/create.rs
influxdb3/src/commands/create/token.rs
influxdb3/src/commands/delete.rs
influxdb3/src/commands/install.rs
influxdb3/src/commands/show.rs
influxdb3_load_generator/src/commands/common.rs
influxdb3_load_generator/src/commands/write_fixed.rs

Use clap crate's "hide_env_values" option to suppress displaying the current value of the env var of the db token INFLUXDB3_AUTH_TOKEN when displaying cli help. The default behavior of clap is to display env var values for arguments when displaying the generated help messages. Showing the token disrupts formatting of the help because it is often long and in a way leaks the token's value.
* closes #26713

chore(cli): hide the token's env var value in cli help

---

influxdb3/src/commands/serve.rs
influxdb3_processing_engine/src/lib.rs
influxdb3_write/src/lib.rs
influxdb3_write/src/table_index.rs
influxdb3_write/src/table_index_cache.rs

Summary of backported changes:
fix: Persister doesn't actually need a TableIndexCache
* allow TableIndexCache initialization to gracefully fail
fix: TableIndexCache initialization and ObjectStore improvements
* By not exiting the process when the TableIndexCache fails to load, we allow it to continue starting up in a degraded state. We emit warning messages letting the user know that gen0 file retention policies and hard deletes may not be able to complete and that compaction and queries are unaffected.
* Add retries with exponential backoff to object store operations in the `influxdb3_write::table_index` and `influxdb3_write::table_index_cache` modules. Warning logs on retry let the user know what is failing when it happens, to assist with troubleshooting.

chore: backport Enterprise fixes for TableIndexCache

---

tsdb/engine/tsm1/file_store.go

Skip purger call if no TSM files are held open
during a replace operation. Reduce useless
log entries.

fix: reduce unnecessary purger operations and logging

---

influxdb3/src/commands/create/token.rs
influxdb3/tests/cli/mod.rs

This commit fixes panic when `influxdb3 create token` is called without `--admin`. Removed `expect` and switched to a clap::Error which is better than panicking
closes: https://github.com/influxdata/influxdb/issues/26730
- Missing subcommand
```
❯ ./target/debug/influxdb3 create token
error: Missing required subcommand. Use: influxdb3 create token --admin [OPTIONS]
Usage: influxdb3 [OPTIONS] [COMMAND]
For more information, try '--help'.
```
- Help text
```
❯ ./target/debug/influxdb3 create token --help
Create a new auth token
Usage: influxdb3 create token [COMMAND]
Commands:
--admin  Create or regenerate an admin token
Options:
-h, --help      Print help information
--help-all  Print more detailed help information
```

fix: avoid panic when `--admin` is missing

---

influxdb3/tests/cli/mod.rs
influxdb3/tests/cli/offline_tokens.rs
influxdb3/tests/server/mod.rs

This commit adds an offline token creation test. We did not have this as
part of the 3.4 test in the interest of time. This adds automated
testing to make sure the flow we expect happens which includes:
- Ability to create admin tokens via the CLI
- Token creation on startup
- Database creation on start
With this we can be more confident that the feature works as expected
and that other changes that might affect it have regression coverage.

feat: Add offline token creation test

---

influxdb3_server/src/system_tables/databases.rs
influxdb3_server/src/system_tables/mod.rs
influxdb3_server/src/system_tables/tables.rs

This PR backports changes from [influxdb_pro PR #1031](https://github.com/influxdata/influxdb_pro/pull/1031) which fixes missing system tables in compact mode.
The changes modify the visibility of `DatabasesTable` and `TablesTable` from `pub(super)` to `pub(crate)` to allow them to be used in other modules, specifically in the enterprise compact mode implementation.

chore: backport visibility changes for system tables from PR #1031

---

influxdb3/tests/server/write.rs
influxdb3_server/src/http.rs

- Backports changes from influxdb_pro PR https://github.com/influxdata/influxdb_pro/pull/1294
- Updates /v2/write API error responses to conform to [documented](https://docs.influxdata.com/influxdb3/clustered/api/v2/#tag/Write) schema
- Ensures backward compatibility with existing v2 API clients
- Added `V2WriteApiError` wrapper type to format errors according to v2 API specification
- Updated error handling in API_V2_WRITE route to use new error format
- Error responses now return JSON with `{"code": "...", "message": "..."}` structure

chore: backport v2 write API error response format fix

---

clippy.toml
influxdb3/src/help/influxdb3_all.txt
influxdb3/src/main.rs
influxdb3_clap_blocks/src/object_store.rs
influxdb3_clap_blocks/src/tokio.rs
influxdb3_server/src/http.rs

This is a backport from the enterprise fork that addresses a bug in the
ReauthingObjectStore that would lead to tokio runtime deadlocks under certain
low thread count conditions.
* fix(tokio): futures::executor::block_on is not compatible with tokio
futures::executor::block_on takes over the thread that calls it with a
while loop expecting another thread or runtime to drive the contained
future to completion. This doesn't work with tokio's runtime thread
expectations where it expects to swap tasks off threads as it likes.
While it doesn't always cause an issue with tokio, the futures block_on
can stall the tokio runtime.
The method tokio::task::block_in_place runs the contained closure in a
blocking manner without blocking the runtime. Within it then, you can
use …

fix(tokio): futures::executor::block_on is not compatible with tokio

---

services/httpd/handler.go
services/httpd/handler_test.go

* feat: Adds time_format param for httpd
* This PR will add a time_format parameter which takes in the value "epoch" or "rfc3339". The default will be "epoch" depending on the value output timestamps will be formatted in epoch or rfc3339.
Closes FR#615
* feat: Adding some changes
* error if incorrect param
* update naming for converter function
* combine tests
* chore: fmt'ing
* feat: A few modifications
* Rename convertToRfc3339Nano to convertToTimeFormat
* allow time formatting to be passed as parameter
* adjust error handling to use already defined timeFormats
* merge test data for test cases to reduce boilerplate
(cherry picked from commit 57da7aa4e77ab258017659c884c704fc34554213)

feat: Adds time_format param for httpd (#26596)

---

Cargo.lock
Cargo.toml

Version naming convention is based on: https://github.com/influxdata/influxdb/blob/0a9de807a608ce1c0ab9831d5acc4cef7ba1c1d4/.circleci/packages/config.yaml#L1-L65

chore: update Cargo.toml for 3.5.0-0.rc.1

---

influxdb3/src/commands/serve/cli_params.rs
influxdb3_clap_blocks/src/object_store.rs

Back-port `--object-store-request-timeout` arg from enterprise `influxdb3 serve` command.
Closes https://github.com/influxdata/influxdb_pro/issues/1204

chore: back-port object-store-request-timeout arg

---

go.mod
go.sum

(cherry picked from commit 40ec5b01a1f8947d8b1817724d2ff8fee57f1073)

chore(deps): bump golang.org/x/oauth2 from v0.21.0 to 0.27.0 (#26625)

---

tsdb/index/tsi1/log_file.go

(cherry picked from commit 016d77fbba6c3ed6c9aaa3a138451b72f81b3129)

feat: TagValueIterator holds RLock for too long (#26369) (#26372)

---

influxdb3_catalog/src/catalog/versions/v2.rs

This backports changes from https://github.com/influxdata/influxdb_pro/pull/1394 that prevents errors when trying to stop a node that doesn't exist in the catalog.

chore: backport stop node only if node exists fix

---

influxdb3/src/commands/serve.rs
influxdb3/src/commands/serve/cli_params.rs
influxdb3/tests/cli/mod.rs

Back-ports the `--node-id-from-env` argument for `influxdb3 serve` from enterprise.
Closes https://github.com/influxdata/influxdb_pro/issues/1203

chore: back-port --node-id-from-env from enterprise

---

cmd/influxd/run/server.go
monitor/build_info_test.go
monitor/go_runtime_test.go
monitor/network_test.go
monitor/service.go
monitor/service_test.go
monitor/system_test.go
services/httpd/handler.go
tsdb/config.go

(cherry picked from commit c28b917f5946d5017f982d1088f457a3917035ea)

feat: Adds 'config' to 'debug/vars' http endpoint (#26624)

---

tsdb/engine/tsm1/compact_common_test.go
tsdb/engine/tsm1/compact_property_test.go
tsdb/engine/tsm1/compact_test.go

Adds property based testing framework for our compaction testings. Current we support checking for "gaps" within adjacent compaction groups.
For example:
```
expectedResult: func() TestLevelResults {
return TestLevelResults{
// Our rogue level 2 file should be picked up in the full compaction
level4Groups: []tsm1.PlannedCompactionGroup{
{
tsm1.CompactionGroup{
"000016844-000000002.tsm",
"000016948-000000004.tsm",
"000016948-000000005.tsm",
"000017076-000000004.tsm",
"000017094-000000004.tsm",
},
tsdb.DefaultMaxPointsPerBlock,
},
},
// Other files should get picked up by optimize compaction
level5Groups: []tsm1.PlannedCompactionGroup{
{
tsm1.CompactionGroup{
"000016684-000000007.tsm",
"000016684-000000008.tsm",
"000016684-000000009.tsm",
"000016684-000000010.tsm", …
```

feat: Adds property based testing framework for compaction (#26783)

---

influxdb3_clap_blocks/src/object_store.rs
object_store_utils/src/retryable_object_store.rs

This backports several changes from the enterprise repo:
* fix: RetryableObjectStore list_with_retries
* chore: remove unnecessary block_on call from ReauthingObjectStore
* test: add more list_with_retries test cases to validate non-trivial retryable list calls
The most notable change is the bug fix to RetryableObjectStore.list_with_retries, where we now peek at the first element in order to actually know if the request needs to be retried.
Related to https://github.com/influxdata/influxdb/issues/26802 and potentially related to https://github.com/influxdata/influxdb/issues/26810.

fix: bug in RetryableObjectStore.list_with_retries, clean up ReauthingObjectStore

---

cmd/influxd/run/server.go
monitor/service.go
monitor/service_test.go
services/continuous_querier/service.go
services/httpd/handler.go

This PR adds continuous query diags to our /debug/vars endpoint
Example
```
"cq": {
"queryFail": 0,
"queryOk": 2
},
```

feat: Adds 'cq' diagnostics to /debug/vars

---

influxdb3/src/commands/serve.rs
influxdb3/src/help/serve.txt
influxdb3/src/help/serve_all.txt
influxdb3_clap_blocks/src/plugins.rs
influxdb3_processing_engine/src/environment.rs
influxdb3_processing_engine/src/manager.rs
influxdb3_server/src/http.rs

Backports [1440](https://github.com/influxdata/influxdb_pro/pull/1440) -- passes tests.

feat: backport 1440
