influxdata/influxdb

tsdb/engine/tsm1/batch_cursor_test.go

remove empty file

---

CHANGELOG.md
Godeps

Fixed via influxdata/influxql#4 by @stop-start. Thanks!

Fix space required after regex operator

---

CHANGELOG.md
tsdb/engine/tsm1/file_store.gen.go
tsdb/engine/tsm1/file_store.gen.go.tmpl
tsdb/engine/tsm1/file_store.go
tsdb/engine/tsm1/file_store_test.go

Backport 9129

---

CHANGELOG.md
coordinator/statement_executor.go
coordinator/statement_executor_test.go
internal/authorizer.go
internal/tsdb_store.go
pkg/slices/bytes.go
pkg/slices/strings.go
query/query_executor.go
services/httpd/handler.go
services/storage/series_cursor.go
tests/server_concurrent_test.go
tsdb/engine.go
tsdb/engine/tsm1/engine.go
tsdb/index.go
tsdb/index/inmem/inmem.go
tsdb/index/inmem/meta.go
tsdb/index/inmem/meta_test.go
tsdb/index/tsi1/file_set.go
tsdb/index/tsi1/index.go
tsdb/index/tsi1/index_test.go
tsdb/index/tsi1/measurement_block.go
tsdb/index_test.go
tsdb/shard.go
tsdb/shard_test.go
tsdb/store.go
tsdb/store_test.go

[1.4 BP] Implement FGA on SHOW commands

---

CHANGELOG.md
tsdb/engine/tsm1/cache.go
tsdb/engine/tsm1/cache_test.go
tsdb/engine/tsm1/encoding.gen.go
tsdb/engine/tsm1/encoding.gen.go.tmpl

Backport #9173

---

CHANGELOG.md
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go

1.3 Backport delete fixes

---

CHANGELOG.md
cmd/influxd/backup/backup.go
cmd/influxd/backup_util/backup_util.go
cmd/influxd/restore/restore.go
internal/tsdb_store.go
man/influxd-backup.txt
services/snapshotter/client.go
services/snapshotter/client_test.go
services/snapshotter/service.go
services/snapshotter/service_test.go
tsdb/engine.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go
tsdb/shard.go
tsdb/store.go

Replaces half of https://github.com/influxdata/influxdb/pull/9148, a complementary review for Restore is forthcoming.  

OSS new backup arguments -start  -end  -enterprise

---

tsdb/engine/tsm1/file_store.go

fix bug in filestore snapshot path that affects windows users

---

CHANGELOG.md
tsdb/engine.go
tsdb/engine/tsm1/digest.go
tsdb/engine/tsm1/digest_reader.go
tsdb/engine/tsm1/digest_test.go
tsdb/engine/tsm1/digest_writer.go
tsdb/engine/tsm1/digest_writer_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go
tsdb/shard.go
tsdb/store.go

feat #9212: add ability to generate shard digests

---

CHANGELOG.md
Godeps
etc/config.sample.toml
pkg/limiter/write_test.go
pkg/limiter/writer.go
tsdb/config.go
tsdb/engine.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/writer.go
tsdb/store.go

Backport #9225

---

CHANGELOG.md
pkg/bytesutil/bytesutil.go
pkg/bytesutil/bytesutil_test.go
tsdb/index/inmem/inmem.go
tsdb/index/inmem/inmem_test.go
tsdb/shard.go

Backport of https://github.com/influxdata/influxdb/pull/9235

Backport of PR 9235 – Improve performance when writes exceed max-values-per-tag or max-series

---

CHANGELOG.md
Godeps

Allow lone boolean literals in a condition expression

---

tsdb/series_file.go

Fix series index compaction.

---

tsdb/series_segment.go

Fix series segment replay.

---

tsdb/store.go

Change location of series file directory to `_series`.

Change series dir location

---

tsdb/series_file.go
tsdb/store.go

WIP: Close series file on database deletion.

---

tsdb/engine.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go
tsdb/shard.go
tsdb/store.go

fix #9286: return digest size

---

tsdb/store.go

Fix series file removal after DROP DATABASE.

---

tsdb/index.go
tsdb/series_file.go
tsdb/store.go

Ensure series file is not closed while in use

---

tsdb/index/inmem/inmem.go

This pull request changes `inmem` to batch insert series to the series file if the write is well below the max series threshold.
Time to write `1M` series decreases from `25s` to `10s`.

In-mem Batch Insert

---

tsdb/index/tsi1/partition.go

Fixes a race condition between `Partition.Close()` and starting compactions.
Previously, the `Close()` function did this:
```go
// Wait for goroutines to finish outstanding compactions.
i.wg.Wait()
// Lock index and close remaining
i.mu.Lock()
defer i.mu.Unlock()
i.once.Do(func() { close(i.closing) })
...
```
and the compactions would start like this:
```go
i.wg.Add(1)
go func() {
defer i.wg.Done()
i.compactLogFile(logFile)
i.Compact() // check for new compactions
}()
```
A compaction can begin after `wg.Wait()` but before the lock is obtained. This pull request closes the `closing` channel first before waiting and checks the channel before beginning compactions.
Fixes #9322.

Add tsi1.Partition closing check before compaction.

---

CHANGELOG.md
Godeps

Update influxql version

---

CHANGELOG.md
tsdb/engine.go
tsdb/engine/tsm1/engine.go
tsdb/index.go
tsdb/index/inmem/inmem.go
tsdb/index/inmem/meta.go
tsdb/index/tsi1/index.go
tsdb/shard.go
tsdb/store.go

[1.4 BP] SHOW TAG KEYS with high cardinality and many shards 

---

CHANGELOG.md
prometheus/converters.go
prometheus/converters_test.go
services/httpd/handler_test.go

[BP 1.4] Fix Prometheus regex parsing

---

tsdb/index/tsi1/index.go
tsdb/index/tsi1/index_file_test.go
tsdb/index/tsi1/index_files.go
tsdb/index/tsi1/index_files_test.go
tsdb/index/tsi1/log_file.go
tsdb/index/tsi1/log_file_test.go
tsdb/index/tsi1/partition.go
tsdb/series_partition.go

Interrupt TSI & Series File Compactions

---

tsdb/engine/tsm1/compact_test.go
tsdb/engine/tsm1/writer.go

ensure tsmWriter#Write returns ErrMaxBlocksExceeded

---

cmd/influxd/backup/backup.go

update variable value check, and log messages to be more informative of what time bounds are set in backup.

update to logs to print start/end values when relevant

---

tsdb/index.go

Because of a race between the index and series file lookups, empty keys can be returned for series which are tombstoned after the series ids are obtained but before the caller looks up the key.
Fixes #9387

Verify series key after lookup.

---

circle.yml

We no longer use circle to deploy new releases.

Remove the deployment section from circle.yml

---

CHANGELOG.md
Jenkinsfile

On the master or release branches, `git changelog` will be run to
automatically update the changelog based off of the pull requests that
have been merged and then it will commit and push those changes.

Configure Jenkins to automatically update the changelog

---

client/influxdb.go
client/v2/client.go
client/v2/client_test.go

[BUGFIX] client url path

---

.github/PULL_REQUEST_TEMPLATE.md

The changelog is now updated automatically, tests are reported to github
as part of the CI status, and rebased/merged are also covered by
built-in github functionality.

Remove unnecessary checkboxes in the pull request template

---

cmd/influx/cli/cli.go

An issue reported by a windows user in `InfluxDB China User Group`.
The `windows` OS  have no `$HOME` env, so he got an empty `c.historyFilePath`, but there is an error every time. 
Now use `USERPROFILE ` env on windows.

Fix windows history file location

---

cmd/influx_inspect/buildtsi/buildtsi.go
cmd/influx_inspect/dumptsi/dumptsi.go
pkg/estimator/hll/hll.go
tsdb/engine.go
tsdb/engine/tsm1/engine.go
tsdb/index.go
tsdb/index/tsi1/file_set.go
tsdb/index/tsi1/index.go
tsdb/index/tsi1/index_file.go
tsdb/index/tsi1/index_file_test.go
tsdb/index/tsi1/index_files.go
tsdb/index/tsi1/index_files_test.go
tsdb/index/tsi1/index_test.go
tsdb/index/tsi1/log_file.go
tsdb/index/tsi1/partition.go
tsdb/index_test.go
tsdb/meta_test.go
tsdb/shard.go
tsdb/store.go
tsdb/store_test.go

Sketches, Cont'd

---

tsdb/store.go

Fix data race when collecting sketches

---

tsdb/store.go

Without this, deleting a shard could trigger things so that a write would attempt to create the shard again before it was actually deleted.

Mark a shard as in process of being deleted

---

tsdb/index/tsi1/log_file.go

Fix panic on tsi1 log replay of deleted series.

---

cmd/influxd/run/command.go

Users will expect the following to work:
```sh
INFLUXDB_LOGGING_FORMAT=json ./influxd -config config.toml
```

ensure ENV overrides are applied when configuring logging

---

CHANGELOG.md

Updated CHANGELOG.md to the GA released date - 2017-03-06

---

Godeps
tsdb/index/inmem/meta.go
tsdb/index/tsi1/file_set.go

Evaluate a true boolean literal when calculating tag sets

---

Godeps

Allow time variable to be case insensitive again

---

etc/config.sample.toml

Fixed typo in config comments

---

cmd/influxd/run/config.go
cmd/influxd/run/config_test.go

Support setting the log level through the environment variable

---

cmd/influxd/run/config.go
toml/toml.go
toml/toml_test.go

This code has been duplicated to other projects and its implementations
have grown out of sync. Now the code can live in one place instead of
coupled with a particular struct.

Move ApplyEnvOverrides to toml package

---

models/points.go
models/points_test.go

Ensure correct number of tags parsed

---

models/points.go
models/points_test.go

Back port of https://github.com/influxdata/influxdb/pull/9559

Improve query performance

---

tsdb/index.go
tsdb/shard.go

Back port of https://github.com/influxdata/influxdb/pull/9582

Improve performance of SHOW SERIES query

---

services/subscriber/service_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_cursor.go
tsdb/index.go
tsdb/shard.go
tsdb/shard_test.go
tsdb/store_test.go

Fix panic when checking fieldsets

---

CHANGELOG.md

Updated CHANGELOG for 1.5.1

---

tsdb/engine.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go

This adds the capability to use a different compaction planner programatically.

Add capability change compaction planner

---

query/compile.go
query/select_test.go

Fix regression to allow now() to be used as the group by offset again

---

services/retention/service.go
services/retention/service_test.go

Backport https://github.com/influxdata/influxdb/pull/9647

[1.5] Delete deleted shards

---

cmd/influx_inspect/export/export.go
tsdb/engine/tsm1/cache.go

Log error encountered when reading WAL files

---

query/select.go

Example outputs:
```
> explain analyze select mean(usage_steal), mean(usage_idle) from cpu
EXPLAIN ANALYZE
---------------
.
└── select
├── execution_time: 222.736µs
├── planning_time: 875.22µs
├── total_time: 1.097956ms
└── build_cursor
├── labels
│   └── statement: SELECT mean(usage_steal::float), mean(usage_idle::float) FROM telegraf.autogen.cpu
├── iterator_scanner
│   ├── labels
│   │   └── expr: mean(usage_steal::float)
│   └── create_iterator
│       ├── labels
│       │   ├── measurement: cpu
│       │   └── shard_id: 718
│       ├── cursors_ref: 9
│       ├── cursors_aux: 0
│       ├── cursors_cond: 0
│       ├── float_blocks_decoded: 9
│       ├── float_blocks_size_bytes: 819
│       ├── integer_blocks_decoded: 0
│       ├── integer_blocks_size_bytes: 0
│       ├── …
```

Update explain analyze to output data related to the iterator scanners

---

cmd/influx_inspect/buildtsi/buildtsi.go

This commit also adds the `max-log-file-size` flag.

Check for root user when running buildtsi.

---

tsdb/engine/tsm1/engine_test.go

This will help us address performance problems in the underlying tsm1
implementations of the aggregate iterators.

Adding additional aggregate benchmarks for tsm1

---

cmd/influxd/backup/backup.go

Changed file download retry rate to have exponential wait times 

---

cmd/influx_inspect/deletetsm/deletetsm.go
cmd/influx_inspect/help/help.go
cmd/influx_inspect/main.go

Provides a tool for bulk deleting a measurement from raw TSM files.

Add 'influx_inspect deletetsm'

---

services/subscriber/service_test.go

fix flaky subscriber tests

---

tsdb/index/inmem/inmem_test.go

Fix tsdb/index/inmem benchmark tests

---

cmd/influx-tools/importer/README.md
cmd/influx-tools/importer/command.go
cmd/influx-tools/importer/importer.go
cmd/influx-tools/importer/series_writer.go
cmd/influx-tools/importer/shard_writer.go
cmd/influx-tools/internal/errlist/errlist.go
cmd/influx-tools/internal/format/binary/reader.go
cmd/influx-tools/internal/format/binary/reader_test.go
cmd/influx-tools/internal/tlv/tlv.go
cmd/influx-tools/main.go
cmd/influx-tools/server/server.go

Addressed https://github.com/influxdata/influxdb/issues/9674

Command line tool to import binary format data

---

query/task_manager.go

Previously, the task manager was modified to keep the query status so it
could track which queries were running and which ones were killed.
In those previous versions, we removed a task from the process table
as soon as it was killed and did not remove it after it had finished
executing. This meant there could be zombie goroutines running in the
background that were impossible to see.
When the task manager was updated to track the task status, we forgot to
expose the status in the public interface so consumers could see the
task status.

Include the query task status in the QueryInfo struct

---

tsdb/engine/tsm1/file_store.go

(backport of https://github.com/influxdata/influxdb/pull/9785/)

Backport #9785: Rename corrupt tsm files on load.

---

cmd/influx-tools/export/exporter.go
cmd/influx-tools/importer/README.md
cmd/influx-tools/importer/command.go
cmd/influx-tools/importer/importer.go
cmd/influx-tools/internal/format/binary/writer.go

Backport of https://github.com/influxdata/influxdb/pull/9805

Backport import fixes

---

tsdb/engine/tsm1/engine.go

While toying with the TSM Engine, I notice that WAL files are created when WAL is disabled. Turns out that the WAL object is instantiated, but only checked for sometimes, when configured to be disabled.
This change removes instantiation and all use of `Engine.WAL` when the option is disabled.

tsdb/WAL: Better respect for WAL disabled

---

tsdb/engine/tsm1/file_store.go

Backport of #9866 again fixing #9786

Close TSMReaders from FileStore.Close after releasing FileStore mutex

---

tsdb/index/inmem/inmem.go

In my test, this optimization can improve performance 20%.  This optimization can make full use of my machine's CPU.
The big reason is that my test machine performance is better, 64-core cpu, ssd disk.
This optimization is what I found out through the flame graph, but sorry for the flame graph is lost.
I use influxdb own stress tools. stress config like this:
```
[provision]
[provision.basic]
enabled = true
address = "xxxx:xxxx"
database = "xxxx"
reset_database = false
[write]
[write.point_generator]
[write.point_generator.basic]
point_count = 1000
series_count = 1000000
tick = "10s"
jitter = true
precision = "s"
measurement = "cpu"
start_date = "2009-Jan-02"
[[write.point_generator.basic.tag]]
key = "host"
value = "server"
[[write.point_generator.basic.tag]]
key = "location"
value = …
```

Performance optimization suggestions

---

tsdb/index/inmem/inmem.go

Reverts influxdata/influxdb#9836; need signed CLA

Revert "Performance optimization suggestions"

---

etc/config.sample.toml
services/httpd/config.go
services/httpd/handler.go
services/httpd/handler_test.go

Backport https://github.com/influxdata/influxdb/pull/9877

[1.6] HTTP Write Throttle

---

tsdb/engine/tsm1/reader.go
tsdb/index/inmem/inmem.go

Backports of
* https://github.com/influxdata/influxdb/pull/9896
* https://github.com/influxdata/influxdb/pull/9836

Backports of tsdb performance improvements

---

services/storage/group_resultset.go
services/storage/series_cursor.go
services/storage/store.go

fix(services/storage): Add nil checks to prevent panics

---

cmd/influxd/run/command.go
etc/config.sample.toml
services/httpd/config.go

[1.6] Add optional pprof http endpoint immediately on startup.

---

cmd/influx_inspect/deletetsm/deletetsm.go
cmd/influx_inspect/help/help.go
cmd/influx_inspect/main.go
models/points.go

Backport https://github.com/influxdata/influxdb/pull/9793 & https://github.com/influxdata/influxdb/pull/9743

[1.5] influx_inspect deletetsm

---

tsdb/index.go

Fixes #9956: `SHOW TAG KEYS` slow when configured for `tsi1`.
Before fix:
```
real    0m12.782s
user    0m0.020s
sys     0m0.001s
```
After fix:
```
real    0m0.097s
user    0m0.015s
sys     0m0.005s
```

fix SHOW TAG KEYS perfomance regression

---

cmd/influxd/backup/backup.go
tsdb/store_test.go

Iterator could be left open.
Fixes #9965

Fix flaky test TestStore_BackupRestoreShard

---

cmd/influxd/backup/backup.go
tsdb/engine/tsm1/engine.go

This PR adds logging to shard digest generation.

add digest logging

---

CHANGELOG.md

Added the description for PR 9996

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml
tsdb/store_test.go

Improve the number of regex patterns that are optimized to static OR conditions

---

pkg/mmap/mmap_windows.go

This pull request fixes a broken test on Windows where `mmap()` was returning `nil` if the file size was zero. This changes the functionality to match the Unix implementation where the mmap is extended to the length of the `sz` argument.

Fix windows mmap on zero length file.

---

CHANGELOG.md

Updated release date for 1.6

---

services/httpd/handler.go
services/httpd/handler_test.go

there were two problems with this code:
1. the send on pending did not imply that the handler was running
2. there was a race starting the handler with timing out
1 is fixed by sending to a begin channel inside the handler. it is
then guaranteed that the timeout handler code has been entered.
2 is fixed by attempting to acquire the semaphore channel once before
checking the timeout channel. in this way, if there is capacity, which
in this test there is known to be, it is guaranteed to be taken. if
we check with the timer at the same time and the timer has already
fired, there is a pseudorandom chance the timer will be taken even
if there is capacity.

httpd: fix flaky test in timeout handler

---

tsdb/series_segment.go
tsdb/series_segment_test.go

Backport https://github.com/influxdata/influxdb/pull/10002

Improve series segment recovery

---

tsdb/index.go
tsdb/index/tsi1/file_set.go
tsdb/index/tsi1/log_file.go
tsdb/index/tsi1/measurement_block.go
tsdb/series_set.go

Backport https://github.com/influxdata/influxdb/pull/10044

Improve LogFile performance with bitset iterator

---

tsdb/index.go
tsdb/meta_test.go
tsdb/shard_test.go

Ensure Filter iterators executed as late as possible 

---

cmd/influx_inspect/main.go
cmd/influx_inspect/reporttsi/report.go
cmd/store/query/query.go

Add TSI index cardinality report to influx_inspect

---

CONTRIBUTING.md
Dockerfile
Dockerfile_build_ubuntu32
Dockerfile_build_ubuntu64
Dockerfile_build_ubuntu64_git
Dockerfile_build_ubuntu64_go1.11
Dockerfile_jenkins_ubuntu32
Jenkinsfile
cmd/influx-tools/internal/format/binary/writer_test.go
releng/_go_versions.sh
test.sh

Update to Go 1.10

---

cmd/influx_inspect/buildtsi/buildtsi.go
models/points.go
tsdb/index/tsi1/index.go
tsdb/index/tsi1/log_file.go
tsdb/index/tsi1/partition.go
tsdb/series_set.go

Improve performance of buildtsi and TSI planning 

---

tsdb/series_partition.go

bug fix from seriesfile enable EnableCompactions function

---

Gopkg.lock
Gopkg.toml
tsdb/store.go

Allow tag keys to contain underscores

---

appveyor.yml

Update Windows CI Go to 1.10

---

Gopkg.lock
Gopkg.toml

Fix a panic when matching on a specific type of regular expression

---

pkg/radix/sort.go
pkg/radix/sort_test.go
tsdb/index/inmem/meta.go

inmem: use radix sort for series ids

---

coordinator/statement_executor_test.go
services/storage/predicate_influxql.go
services/storage/predicate_test.go
services/storage/series_cursor.go
tsdb/shard.go
tsdb/shard_test.go

Improve performance of read service for single measurements 

---

CHANGELOG.md

Update to include release date for 1.6 and maintenance releases for 1.5.x where x > 0

Update CHANGELOG on master for 1.5.x releases and 1.6 release date.

---

tsdb/store.go

Remove max concurrent compaction limit

---

tsdb/store.go

If some error or message is in the context of some shard or database
be sure to include it in the message.

Make store include context in logs

---

tsdb/engine/tsm1/digest.go
tsdb/engine/tsm1/digest_reader.go
tsdb/engine/tsm1/digest_test.go
tsdb/engine/tsm1/digest_writer.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go

This PR backports #10113 to 1.6.

Add digest manifest

---

Godeps

updated influxql sha to the latest

---

pkg/slices/bytes.go
pkg/slices/bytes_test.go
tsdb/index.go

backport SHOW MEASUREMENTS panic fix

---

CHANGELOG.md

updated CHANGELOG with PR 10184

---

models/points.go
models/points_test.go

Fix line protocol parsing panic

---

pkg/snowflake/gen.go
pkg/snowflake/gen_test.go

Applies #10197 and #10202 to platform branch.

pkg/snowflake: update platform branch.

---

pkg/limiter/writer.go

fix the comments error

---

tsdb/config.go
tsdb/config_test.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go
tsdb/index.go
tsdb/index/inmem/inmem.go
tsdb/index/tsi1/index.go
tsdb/index_test.go
tsdb/shard_internal_test.go
tsdb/shard_test.go
tsdb/store.go
tsdb/store_test.go

Ensure orhpaned series cleaned up with shard drop

---

Godeps

Update to the Godeps for the latest influxql

---

tsdb/index/tsi1/log_file.go

Resolves a panic when attempting to sort the `logMeasurements` slice,
which holds on to mmap'd data.
Reverts commit 9970620ee0033aeb84c4f5bd9008dd1e8d4b3b45

Revert: Unmap LogFile on successful open

---

monitor/config.go

Use the const var as the parameter in the construction function

---

query/compile.go
query/compile_test.go

The derivative function and others similar to it would preload
themselves with data so that the first interval would be the start of
the time range. That meant reading data outside of the time range.
One change to the shard mapper back in v1.4.0 caused the shard mapper to
constrict queries to the intervals given to the shard mapper. This was
correct because the shard mapper can only deal with times it has mapped,
but this broke the functionality of looking back into the past for
the derivative and other functions that used that functionality.
The compiler has been updated with an additional attribute that records
how many intervals in the past will need to be read so that the shard
mapper can include extra times that it may not necessarily read from,
but may be queried because of the …

Fix the derivative and others time ranges for aggregate data

---

tsdb/index/tsi1/file_set.go
tsdb/index/tsi1/index.go
tsdb/index/tsi1/index_file.go
tsdb/index/tsi1/log_file.go
tsdb/index/tsi1/measurement_block.go
tsdb/index/tsi1/partition.go
tsdb/index_test.go
tsdb/store_test.go

Remove TSI1 HLL sketches from heap.

---

client/README.md

- fix NewUDPClient to use UDPConfig

update UDP client example

---

tsdb/index/tsi1/index.go

Fix tsi1 sketch locking.

---

flux/functions/store/reader.go
flux/functions/store/table.go

fixes https://github.com/influxdata/flux/issues/81

fix(flux): Fix panicks when executing grouping flux queries

---

CHANGELOG.md
query/cast.go
query/iterator.gen.go
query/iterator.gen.go.tmpl
query/iterator.go
query/iterator_mapper.go
query/iterator_mapper_test.go
query/subquery.go
query/subquery_test.go

Assorted fixes to subquery regressions in 1.6

---

cmd/influx_inspect/dumptsi/dumptsi.go

Add -series-file flag to dumptsi command help.

---

monitor/diagnostics/diagnostics.go
monitor/service.go

Golint monitor (and sub-pacakges) to address issue #4098

golint monitor package

---

uuid/uuid.go

Golint uuid to address issue #4098

golint uuid package

---

cmd/influx_inspect/buildtsi/buildtsi.go

If there is a significant amount of data in the WAL, then building the
TSI index can be problematic without being able to set the max cache
size to something larger.
This PR adds an option to set the maximum cache size.

Set cache size when building TSI index

---

cmd/influx_inspect/buildtsi/buildtsi.go

Set cache size when building TSI index 

---

tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/file_store.go

 Cleanup failed TSM snapshots

---

tsdb/shard.go

This backport is needed for Enterprise changes.

Backport #9937: Export Shard.Engine()

---

tsdb/engine/tsm1/file_store.go

Fix TSM1 panic on reader error.

---

cmd/influx_inspect/verify/seriesfile/verify.go
cmd/influx_inspect/verify/seriesfile/verify_test.go
tsdb/series_file_test.go
tsdb/series_index.go
tsdb/series_partition.go

Fix series file tombstoning.

---

CHANGELOG.md
tsdb/index.go
tsdb/index_test.go

Do not panic when a series id iterator is nil

---

tsdb/store.go

Move `filterShards` inside the lock, as it enumerates the shards map, which can result in data race when the map is written concurrently.

Fix data race when shards are deleted and created concurrently

---

tsdb/engine/tsm1/digest_reader.go
tsdb/engine/tsm1/digest_writer.go
tsdb/engine/tsm1/digest_writer_test.go

Make digest reader skip manifest

---

internal/flux_controller.go
services/httpd/config.go
services/httpd/flux.go
services/httpd/handler.go
services/httpd/handler_test.go
services/httpd/service.go

This PR completes a number of tasks for the Flux 0.7 integration to InfluxDB per influxdata/influxdb#10374

Add Flux 0.7 HTTP API

---

tsdb/index.go
tsdb/index/tsi1/partition.go
tsdb/shard.go
tsdb/store.go
tsdb/store_test.go

Fix panic in IndexSet

---

CHANGELOG.md
client/v2/client.go
client/v2/client_test.go
client/v2/udp.go

Fix #10257 add `QueryAsChunk`

---

Gopkg.lock

update flux dependency after planner integration

---

Gopkg.lock
flux/builtin/builtin.go

add Flux output functions

---

flux/client/http.go
services/httpd/handler.go
services/httpd/handler_test.go

Return 403 Forbidden when Flux API is disabled

---

Gopkg.lock

The platform update is required for influxdata/platform/pull/1249

Update platform and flux dependencies

---

CHANGELOG.md
Godeps
Gopkg.lock

- Update CHANGELOG.md bug fixes section.
- Update Godeps with latest influxql revision.
- Update Gopkg.lock with latest influxql.

chore: update revisions of flux and influxql

---

Gopkg.lock

The platform update is required for influxdata/platform/pull/1262

chore(deps): Update platform and flux

---

Gopkg.lock

Includes fix for distinct push down

Update Flux and Platform dependencies

---

models/points.go
tsdb/engine/tsm1/engine.go

Some typo and Wrong position of comment

---

CHANGELOG.md

Added missing release notes

---

services/storage/series_cursor.go
services/storage/series_cursor_test.go

Fix empty results when using _value in filter expression

---

pkg/encoding/simple8b/encoding.go
pkg/encoding/simple8b/encoding_test.go
tsdb/engine/tsm1/compact.gen.go
tsdb/engine/tsm1/compact.gen.go.tmpl
tsdb/engine/tsm1/compact_test.go

Simple8B EncodeAll incorrectly encodes 120 or 240 1s if last value is not a 1

---

CHANGELOG.md
Gopkg.lock

chore: changelog updates

---

cmd/influx_inspect/verify/seriesfile/verify.go

Tombstone entries don't contain a key, and parsing the empty key panics.

fix verify seriesfile in presence of tombstones

---

Gopkg.lock
Gopkg.toml
flux/control/controller.go
flux/functions/inputs/buckets.go
flux/functions/inputs/from.go
internal/storage_store.go
services/httpd/handler.go
services/storage/context.go
services/storage/store.go

This PR includes some minor changes to simplify Flux support in Enterprise

Update Platform dependency

---

cmd/influx_inspect/verify/seriesfile/verify.go

Backport fix verify seriesfile in presence of tombstones

---

Gopkg.lock
flux/control/controller.go
flux/functions/inputs/buckets.go
flux/functions/inputs/from.go
internal/storage_store.go
services/httpd/handler.go
services/storage/context.go
services/storage/store.go

Back port of #10506 required for Flux support in Enterprise 1.7

Backport of #10506 to update platform dependency

---

tsdb/store.go

TSI1 and inmem indexes have different properties during deletes.
Specifically, inmem shares a global index across all shards, where
every tsi1 index is contained to a specific shard. When deleting
a series, it may cause the last reference to the series across all
shards to be dropped, necessitating a removal from the series file.
Since the inmem index shares the index across all shards, removing
the series when it's removed from the series file is sufficient.
However, in the case of a mixed index database, if the last shard
is a TSI1 shard, the other inmem indexes are not available when we
discover that it was the last reference to the series. This ends
up leaving the series in the inmem index without a series id in
the series file, causing all sorts of misbehavior.
Rather than continue …

tsdb: don't allow deletes to a database in mixed index mode

---

tsdb/store.go

Backport: don't allow deletes to a database in mixed index mode

---

tsdb/engine/tsm1/engine.go
tsdb/index.go
tsdb/index/inmem/inmem.go
tsdb/index/inmem/inmem_test.go
tsdb/index/tsi1/index.go

Backport: always cleaning up the fields index

---

tsdb/store.go

Backport https://github.com/influxdata/influxdb/pull/10525

Skip and warn series files in retention policy directory.

---

tsdb/epoch_tracker.go
tsdb/epoch_tracker_test.go
tsdb/guard.go
tsdb/guard_test.go
tsdb/store.go

tsdb: conflict based concurrency resolution

---

Gopkg.lock
Gopkg.toml
cmd/influx_tools/internal/format/binary/reader_test.go
cmd/influx_tools/internal/format/binary/writer_test.go
flux/functions/inputs/buckets.go
internal/array_cursors.go
internal/storage_store.go
services/httpd/handler.go
tsdb/cursor.go
tsdb/engine/tsm1/array_cursor.gen.go
tsdb/engine/tsm1/array_cursor.gen.go.tmpl
tsdb/engine/tsm1/array_cursor_iterator.go

Requires influxdata/platform#1618

Update to Flux 0.7.1

---

CHANGELOG.md

chore: CHANGELOG changes

---

Gopkg.lock

Update platform to resolve panic with group push down

---

tsdb/store_test.go

Specifically tests around the global index for fields with mixed shard types.

tsdb: mixed shard tests

---

services/meta/data.go
services/meta/data_test.go
services/meta/errors.go

Limit database and retention policy names to 255 characters

---

CHANGELOG.md

chore: set a release date for 1.5.5 GA

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go

Limit force-full and cold compaction size.

---

Gopkg.lock
Gopkg.toml
cmd/influxd/run/server.go
flux/control/controller.go
flux/functions/inputs/buckets.go
flux/functions/inputs/from.go
services/httpd/handler.go
services/httpd/handler_test.go
services/meta/context.go
services/meta/query_authorizer.go

Add user authentication and authorization support for Flux HTTP requests

---

README.md

Ensuring date matches blog post; minor capitalization fix.

Fixing date; capitalization of InfluxDB

---

services/httpd/handler.go

Fix panic in Prometheus read API

---

CHANGELOG.md

CHANGELOG updates for 1.6.5

---

http/view_service.go
http/view_test.go

fix(http): add labels to view links responses

---

ui/src/onboarding/components/verifyStep/CreateOrUpdateConfig.test.tsx
ui/src/onboarding/components/verifyStep/CreateOrUpdateConfig.tsx
ui/src/onboarding/components/verifyStep/DataStreaming.tsx
ui/src/onboarding/components/verifyStep/TelegrafInstructions.tsx
ui/src/shared/copy/notifications.ts

fix(ui/onboarding): Update verify step to fail more gracefully if requests fail

---

.gitignore

* this line prevents new files from being added to ui/src

Stop ignoring ui/src

---

cmd/influx/authorization.go

feat(cmd): add missing auth cli params

---

README.md

Improve README to help folks get started using 2.0 quickly.

fix: Add 'Basic Usage' fodder to README

---

go.mod
go.sum
http/task_service.go
query/functions/tests/placeholder.go
task.go
task/backend/bolt/bolt.go
task/backend/inmem_store.go
task/backend/store.go
task/backend/storetest/storetest.go
task/options/options.go
task/platform_adapter.go
task/servicetest/servicetest.go
task_test.go

feat(tasks): update task options from api

feat(tasks): update task options from api

---

tsdb/index/tsi1/index.go
tsdb/index/tsi1/log_file.go
tsdb/index_test.go
tsdb/store_test.go

Fix cardinality estimation error

---

ui/src/clockface/components/dropdowns/DropdownButton.tsx
ui/src/dashboards/constants/index.ts
ui/src/dataExplorer/components/DashboardsDropdown.tsx
ui/src/dataExplorer/components/SaveAsButton.tsx
ui/src/dataExplorer/components/SaveAsCellForm.tsx
ui/src/dataExplorer/components/SaveAsTaskForm.tsx
ui/src/shared/copy/notifications.ts

Co-authored-by: Alirie Gray<alirie.gray@gmail.com>
Co-authored-by: Deniz Kusefoglu <deniz@influxdata.com>
Closes #10897

Add send to dashboard functionality to Data Explorer

---

CHANGELOG.md

added one more bug fix to changelog

---

http/dashboard_service.go
http/dashboard_test.go
http/proto_test.go

fix(http): add owners/members links to dashboards responses

---

ui/src/onboarding/actions/dataLoaders.ts
ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx
ui/src/onboarding/components/configureStep/Scraper.test.tsx
ui/src/onboarding/components/configureStep/Scraper.tsx
ui/src/onboarding/components/configureStep/Scraping.tsx
ui/src/onboarding/components/configureStep/__snapshots__/Scraper.test.tsx.snap
ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.test.tsx
ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocol.test.tsx.snap
ui/src/onboarding/components/selectionStep/TypeSelector.tsx
ui/src/onboarding/reducers/dataLoaders.test.ts
ui/src/onboarding/reducers/dataLoaders.ts
ui/src/types/v2/dataLoaders.ts

Closes #10969 #10783 
Created new component for scraping which includes the ui to input interval, select bucket dropdown and add urls.
Created actions and reducers for the input, bucket and urls.

Build ui for scraping component on onboarding

---

ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.tsx
ui/src/onboarding/components/configureStep/lineProtocol/LineProtocolTabs.tsx
ui/src/onboarding/components/configureStep/lineProtocol/TabBody.tsx
ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocol.test.tsx.snap
ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocolTabs.test.tsx.snap
ui/src/shared/components/DragAndDrop.scss
ui/src/shared/components/DragAndDrop.tsx

Closes #11027 
Closes #11024
Update Line Protocol button styles. Submit form on file upload to move to verify step.

Update Line Protocol button styles, submit form on file upload.

---

ui/src/organizations/apis/index.ts
ui/src/organizations/components/CollectorList.tsx
ui/src/organizations/components/CollectorRow.tsx
ui/src/organizations/components/Collectors.tsx
ui/src/organizations/containers/OrganizationView.tsx

Closes #10796 
Added Collectors tab to Organization page. Displaying list of config name and bucket from api response on telegraf configs.

Build ui for Collectors on Organizaitons page

---

http/cur_swagger.yml
ui/src/api/api.ts
ui/src/authorizations/apis/__mocks__/data.ts
ui/src/me/components/account/ViewTokenOverlay.tsx
ui/src/me/components/account/__snapshots__/Tokens.test.tsx.snap
ui/src/me/components/account/__snapshots__/ViewTokenOverlay.test.tsx.snap

Co-authored-by: Deniz Kusefoglu <deniz@influxdata.com>
Co-authored-by: Michael Desa <mjdesa@gmail.com>
Updates the resource structure of a permission in cur swagger and the ui.

fix(ui): update permissions type in cur swagger and associated ui

---

ui/src/clockface/components/overlays/Overlay.scss
ui/src/clockface/components/panel/Panel.scss
ui/src/dashboards/components/dashboard_index/TableRow.tsx
ui/src/me/components/GettingStarted.tsx
ui/src/me/components/account/Settings.tsx
ui/src/me/components/account/Tokens.tsx
ui/src/me/components/account/TokensList.tsx
ui/src/me/components/account/__snapshots__/Settings.test.tsx.snap
ui/src/me/components/account/__snapshots__/Tokens.test.tsx.snap
ui/src/organizations/components/BucketOverlayForm.tsx
ui/src/organizations/components/CreateBucketOverlay.tsx
ui/src/organizations/components/Labels.tsx
ui/src/organizations/components/Retention.tsx
ui/src/organizations/components/RetentionDuration.tsx
ui/src/organizations/components/UpdateBucketOverlay.tsx
ui/src/tasks/components/TaskRow.tsx

Closes #11100 
Closes #11103 
Closes #11104 
Closes #11108 
Close #11025 
Clean up the bucket update/edit overlay
Link to the `Collectors` tab of the first org from the homepage `Configure a Data Collector` button
Link to the owner's org profile from a dashboard list item
Style the `My Settings` tab
Update tooltip on add/edit labels buttons on Dashboards and Tasks lists
Remove excess padding on Labels and Tokens pages

Various Polish Stories

---

ui/src/shared/apis/v2/queryBuilder.ts

Update meta queries for query builder

---

bolt/bucket.go
http/bucket_service.go
inmem/bucket_service.go
paging.go
testing/bucket_service.go

fix(http): filter buckets by FindOptions

---

ui/src/organizations/apis/index.ts
ui/src/organizations/components/ScraperList.tsx
ui/src/organizations/components/ScraperRow.tsx
ui/src/organizations/components/Scrapers.tsx
ui/src/organizations/containers/OrganizationView.tsx

Closes #10795 
Added the api call to Scraper targets to get all scrapers

Add the ability to list all scrapers using api response

---

.circleci/config.yml

chore(ci): Restore nightly schedule

---

ui/assets/images/cubo_doodle.svg
ui/assets/images/cubo_doodle_green.svg
ui/src/onboarding/OnboardingWizard.scss
ui/src/onboarding/components/CompletionAdvancedButton.tsx
ui/src/onboarding/components/CompletionQuickStartButton.tsx
ui/src/onboarding/components/CompletionStep.tsx
ui/src/onboarding/components/__snapshots__/CompletionStep.test.tsx.snap

Closes #11047 
Add options to the final step of onboarding to allow the user to decide when/how to add data.

Update final onboarding step to offer next step options to the user

---

ui/src/dashboards/actions/v2/views.ts
ui/src/shared/reducers/v2/timeMachines.ts
ui/src/types/v2/dashboards.ts

Ensure view retains cellID, and use cellID or id in updateVeiw

---

ui/src/shared/actions/v2/queryBuilder.ts

Use bucket api for listing buckets in time machine

---

ui/src/shared/apis/v2/queryBuilder.ts

Improve meta query for tags

---

ui/src/shared/apis/v2/queryBuilder.ts

Fix incorrect meta query

---

ui/src/clockface/components/form_layout/Form.scss
ui/src/shared/components/ColorDropdown.tsx
ui/src/shared/components/TimeMachine.scss
ui/src/shared/components/columns_options/ColumnsOptions.scss
ui/src/shared/components/columns_options/ColumnsOptions.tsx
ui/src/shared/components/draggable_column/DraggableColumn.tsx
ui/src/shared/components/tables/TableSidebar.tsx
ui/src/shared/components/view_options/TableOptions.tsx
ui/src/shared/components/view_options/options/SortBy.tsx
ui/src/shared/components/view_options/options/ThresholdItem.tsx
ui/src/shared/components/view_options/options/ThresholdList.scss
ui/src/shared/components/view_options/options/TimeAxis.tsx
ui/src/shared/components/view_options/options/TimeFormat.scss
ui/src/shared/components/view_options/options/TimeFormat.tsx

Closes #11144 
Polished a variety of things in the table options:

Polish Table Options

---

ui/src/organizations/components/TaskList.tsx
ui/src/organizations/components/TaskRow.tsx
ui/src/organizations/components/Tasks.tsx
ui/src/organizations/containers/OrganizationView.tsx

Closes #11147 
Remove the hardcoded delete value and add the button instead
Add functionality to delete a task from task row

Add the ability to delete a task from organization

---

ui/src/index.tsx

Clean up routes

---

ui/src/index.tsx

Fix org routes

---

bolt/bucket.go
bolt/dashboard.go
dashboard.go
http/dashboard_service.go
http/dashboard_test.go
http/proto.go
http/proto_test.go
http/swagger.yml
inmem/dashboard.go
testing/bucket_service.go
testing/dashboards.go

Closes #11139 
Addition of pagination and sorting (descending one) capabilities to dashboards services (bolt, inmem, http).
Also aligning dashboards proto.
Some improvements for buckets pagination, too.

Dashboards pagination

---

ui/src/shared/apis/v2/queryBuilder.ts
ui/src/shared/utils/queryBuilder.ts

Use v1 namespaced functions for metaqueries

---

ui/src/clockface/components/context_menu/ContextMenuItem.tsx
ui/src/clockface/components/panel/Panel.tsx
ui/src/dashboards/actions/v2/index.ts
ui/src/dashboards/components/DashboardPage.tsx
ui/src/dashboards/utils/cellGetters.ts
ui/src/organizations/components/Collectors.tsx
ui/src/organizations/components/Scrapers.tsx
ui/src/organizations/components/TelegrafExplainer.scss
ui/src/organizations/components/TelegrafExplainer.tsx
ui/src/organizations/containers/OrganizationView.tsx
ui/src/shared/components/TagSelector.scss
ui/src/shared/components/TagSelector.tsx
ui/src/shared/components/TimeMachineQueryBuilder.scss
ui/src/shared/components/cells/CellContext.tsx
ui/src/tasks/components/TaskRow.tsx
ui/src/tasks/components/TasksList.tsx
ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap
ui/src/tasks/components/__snapshots__/TasksList.test.tsx.snap
ui/src/tasks/containers/__snapshots__/TasksPage.test.tsx.snap

Closes #11109 
Closes #11246 
Closes #11177 
Closes #11229 
Redistributed tasks page column widths to optimize for long task names
Labels align with task name
Task name is large (how it is in Dashboards list)
All blocks in query builder are removable
Renamed "Collector" to "Telegraf Configurations"
Added a panel that explains what Telegraf is and links to the Getting Started guide in documentation
Cloned cells will have the same width and height as their source cell

Moar Polish

---

ui/src/onboarding/components/configureStep/Scraping.tsx

Closes #10784 
Updated redux state to the correct bucketID on dropdown select change

Create the scraper for the bucket selected in dropdown

---

ui/src/dashboards/components/dashboard_index/TableRow.tsx
ui/src/organizations/components/DashboardList.tsx
ui/src/organizations/components/DashboardRow.tsx
ui/src/organizations/components/Dashboards.tsx
ui/src/organizations/containers/OrganizationView.tsx

Closes #11150 
User can copy a dashboard from the orgs dashboard list

Add clone dashboard functionality to orgs dashboard list

---

ui/src/shared/apis/v2/query.ts

Display flux error in UI

---

ui/src/onboarding/actions/dataLoaders.ts

UPdate the path to get the id so telegraf config updating works

fix(ui/dataLoaders): Fix update telegraf config

---

ui/src/onboarding/components/configureStep/lineProtocol/TabBody.tsx

Wait till submit to verify manual line protocol

---

authz.go
bolt/metrics.go
bolt/metrics_test.go
bolt/onboarding.go
bolt/user.go
cmd/influxd/launcher/launcher.go
http/auth_test.go
inmem/onboarding.go
task/backend/storetest/logstoretest.go
testing/onboarding.go

Add metrics to boltdb to gather total number of:
* orgs
* tasks
* dashboards
* buckets
* dashbaords
* boltdb reads
* boltdb writes

feat(bolt): add metrics for resources stored in boltdb

---

ui/src/onboarding/constants/pluginConfigs.ts

Closes #11272
Update nginx to have urls to configure.

fix(ui/dataLoaders): Update Nginx configs to include urls

---

http/cur_swagger.yml
ui/src/api/api.ts
ui/src/tasks/actions/v2/index.ts
ui/src/tasks/api/v2/index.ts

Pass task options on update

---

bolt/dashboard.go
bolt/dashboard_test.go

log dashboard removed event

---

http/router.go
http/router_test.go

fix(http): log api panic with a stack trace

---

http/write_handler.go

fix(http): convert write error

---

cmd/influx/authorization.go
cmd/influx/bucket.go
cmd/influx/internal/errorfmt.go
cmd/influx/internal/errorfmt_test.go
cmd/influx/main.go
cmd/influx/organization.go
cmd/influx/query.go
cmd/influx/repl.go
cmd/influx/setup.go
cmd/influx/task.go
cmd/influx/user.go
cmd/influx/write.go

Closes #11346 
This PR introduces a setup check any time an error is encountered during CLI usage.

feat(cmd/influx): check if instance has been setup if error encountered

---

ui/src/clockface/components/context_menu/ContextMenu.scss
ui/src/clockface/components/context_menu/ContextMenu.tsx
ui/src/clockface/components/context_menu/ContextMenuItem.tsx
ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx
ui/src/organizations/components/BucketList.tsx
ui/src/organizations/components/BucketRow.tsx

Closes #10806
Closes #11270
Jump to data loader step from buckets "Add Data" button

Jump to data loader step from buckets "Add Data" button

---

ui/src/dashboards/components/NoteEditor.tsx

Fix Visibility Toggle in Note Editor

---

ui/src/clockface/components/form_layout/FormElementError.tsx

fix(ui/validation): jiggling elements with validation errors

---

ui/src/index.tsx
ui/src/onboarding/components/SigninForm.tsx

Closes #11304 
Update IndexRoute from `DashboardsPage` to `MePage`. Fixes inconsistent index page for logged in vs newly logged in users.

fix(ui): update IndexRoute to MePage

---

ui/src/Logout.tsx
ui/src/me/components/LogoutButton.tsx
ui/src/pageLayout/containers/Nav.tsx

Closes #11302
Removes returnTo query param on logout

fix(ui): remove returnTo on logout

---

query/stdlib/influxdata/influxdb/to.go
query/stdlib/influxdata/influxdb/to_test.go

Use orgID when to function reports its write buckets.

---

ui/src/dataLoaders/components/DataLoadersWizard.tsx
ui/src/onboarding/components/PluginsSideBar.test.tsx
ui/src/onboarding/components/PluginsSideBar.tsx
ui/src/onboarding/components/__snapshots__/PluginsSideBar.test.tsx.snap
ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx
ui/src/onboarding/components/configureStep/Scraping.tsx
ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.test.tsx
ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.tsx
ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocol.test.tsx.snap
ui/src/onboarding/reducers/dataLoaders.test.ts
ui/src/onboarding/reducers/dataLoaders.ts

Closes #11399 #11402 
Removed add new source button from onboarding

Remove Add new source button from onboarding sidebar

---

cmd/influx/internal/errorfmt.go
cmd/influx/main.go
cmd/influx/query.go
cmd/influx/setup.go
cmd/influx/write.go
http/bucket_service.go

Closes #11412 
This PR gives context to errors that can be encountered during setup, write, and query.

Solidify setup, write, query experience for CLI

---

ui/src/onboarding/components/verifyStep/TelegrafInstructions.tsx
ui/src/onboarding/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap

chore: change streaming copy to telegraf branding

---

ui/src/shared/components/view_options/TableOptions.tsx

chore: remove time axis feature from TableGraphs

---

http/Makefile
http/api_handler.go
http/no_assets.go
http/platform_handler.go
http/redoc.go
http/swagger.go

Closes #
Host swagger docs at /docs

feat(http): host swagger docs at /docs and /api/v2/swagger.json

---

.goreleaser.yml

To prepare for a release, this adds version, commit and date to main.

feat(goreleaser): add version, commit and date to builds

---

ui/src/shared/constants/fluxFunctions.ts

Closes #11401 
- Copy over 1.7.6 flux functions

fix(ui): add flux functions from 1.7.6

---

telemetry/push.go

Sends telemetry to https://telemetry.influxdata.com

feat(telemetry): add telemetry.influxdata.com as telemetry URL

---

ui/src/shared/components/QueryViewSwitcher.tsx
ui/src/shared/components/view_options/LineOptions.tsx
ui/src/shared/components/view_options/OptionsSwitcher.tsx
ui/src/shared/components/view_options/SingleStatOptions.tsx
ui/src/shared/components/view_options/options/ThresholdColoring.tsx
ui/src/shared/reducers/v2/timeMachines.ts
ui/src/shared/utils/view.ts

Closes #11371
Add single stat options into the the vis options for the line with single stat.

feat(ui/explorer): Add single stat controls to line + singlestat visoptions

---

ui/src/shared/copy/v2/notifications.ts
ui/src/tasks/actions/v2/index.ts

Closes #11165
Update notifications in Tasks UI to api response error messages

Update error message to api response message on tasks

---

ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.tsx
ui/src/onboarding/components/configureStep/lineProtocol/TabBody.tsx

Await writing line protocol

---

ui/src/organizations/components/Buckets.tsx
ui/src/organizations/containers/OrganizationView.tsx
ui/src/shared/copy/v2/notifications.ts

Closes #11407
Update buckets to display notification when deleted

Show notification when a bucket has been deleted

---

ui/src/shared/copy/v2/notifications.ts
ui/src/tasks/actions/v2/index.ts

Closes #11432 
Showing notification when task status is updated to active or inactive

Show notification when task status is updated

---

ui/src/shared/constants/queryBuilder.ts

Enable selecting derivative function in query builder

---

README.md

As well as some minor formatting/typo correction.

chore(readme): indicate that port 9999 is temporary

---

ui/src/shared/components/TimeMachineQueryBuilder.tsx

When all tags have selector, don't show add button

---

ui/src/shared/components/TimeMachineQueries.scss
ui/src/shared/components/TimeMachineQueries.tsx
ui/src/shared/components/TimeMachineQueriesSwitcher.tsx
ui/src/shared/components/TimeMachineQueriesTimer.scss
ui/src/shared/components/TimeMachineQueriesTimer.tsx
ui/src/shared/components/TimeMachineQueryTab.scss
ui/src/shared/components/TimeMachineQueryTab.tsx
ui/src/shared/components/TimeMachineQueryTabName.tsx

Closes #11158
make tabs scroll instead of pushing buttons off screen

scrolling query tabs

---

ui/src/dataExplorer/components/SaveAsTaskForm.tsx
ui/src/organizations/components/GetOrgResources.tsx
ui/src/tasks/actions/v2/index.ts
ui/src/tasks/components/TaskForm.tsx
ui/src/tasks/components/TasksOptionsBucketDropdown.tsx
ui/src/tasks/components/TasksOptionsOrgIDDropdown.tsx
ui/src/tasks/components/__snapshots__/TaskForm.test.tsx.snap
ui/src/tasks/reducers/v2/index.ts
ui/src/utils/taskOptionsToFluxScript.ts

Add destination to task flux script

---

ui/src/me/components/Docs.tsx
ui/src/me/components/Support.tsx

chore(ui): update helpful links

---

ui/mocks/dummyData.ts
ui/src/onboarding/components/selectionStep/SelectDataSourceStep.test.tsx
ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx
ui/src/onboarding/components/selectionStep/StreamingSelector.tsx

fixes ui error when there are no buckets whenopening the collectors dataloader ui

Fix empty dropdown bucket in collectors

---

ui/src/configuration/apis/index.ts
ui/src/configuration/components/Labels.tsx

Closes #11461 
- Use labelTypes in state instead of labels in props

fix(ui): fix label deletion

---

ui/src/dataLoaders/components/DataLoadersWizard.tsx
ui/src/onboarding/OnboardingWizard.scss
ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx
ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx
ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx
ui/src/onboarding/components/side_bar/SideBar.scss
ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx

Remove Sidebar on plugin selection step

remove sidebar on selection step

---

ui/src/organizations/components/Collectors.tsx
ui/src/organizations/components/TelegrafExplainer.tsx

fix(ui): spacing typo

---

ui/src/clockface/components/label/LabelSelector.tsx

- adds a guard for cases where this in no label

fix(ui): add guard for no highlight labels

---

telemetry/handler.go

Update to telemetry information to: https://www.influxdata.com/telemetry"

feat(telemetry): update redirection website for telemetry information

---

.gitignore

chore(gitignore): ignore swagger_gen.go

---

ui/src/dataLoaders/components/DataLoadersWizard.tsx
ui/src/dataLoaders/components/StepSwitcher.tsx
ui/src/onboarding/components/verifyStep/CreateOrUpdateConfig.test.tsx
ui/src/onboarding/components/verifyStep/CreateOrUpdateConfig.tsx
ui/src/onboarding/components/verifyStep/DataStreaming.tsx
ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx
ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.tsx
ui/src/protos/actions/index.ts
ui/src/shared/copy/notifications.ts

Create dashboards for plugins in verify step

---

inmem/organization_service.go
testing/bucket_service.go
testing/organization_service.go

Fixes test failures introduced by #11469.

fix(testing): return organization name in failure messages

---

cmd/influxd/launcher/launcher.go

First line of logs is now:
```
2019-01-23T03:31:22.337905Z     info    Welcome to InfluxDB     {"log_id": "0DAC2COG000", "version": "nightly", "commit": "37d7a49f6", "build_date": "2019-01-23T03:25:05Z"}
```
When we have a release, those will be set to the correct release version.

feat(cmd/influxd): log build information

---

ui/src/onboarding/components/OnboardingButtons.tsx
ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx
ui/src/onboarding/components/configureStep/Scraping.tsx
ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.test.tsx
ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.tsx
ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocol.test.tsx.snap
ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx

Closes #11417 
Update scraping, line protocol and streaming to remove previous button

Remove previous button from dataloader wizard on configure step

---

ui/src/dataLoaders/components/DataLoadersWizard.tsx
ui/src/organizations/components/Scrapers.tsx

fixes error occuring when theres not scrapers

fix no scrapers error

---

.circleci/config.yml
.goreleaser-nightly.yml
.goreleaser.yml
Makefile

Add a goreleaser for releases and one for nightlies.
Configure goreleaser to build docker and upload to s3.

ci(goreleaser): create a release version of goreleaser

---

CHANGELOG.md

Changelogs are useful for folks.

doc(CHANGELOG): add initial changelog for 2.0

---

http/task_service.go

And ensure that the task HTTP client consistently expects influxdb
errors, so that they're properly extracted and returned to the caller.
Closes #11426.

fix(http): consistently use influxdb errors in task handlers

---

ui/package-lock.json
ui/package.json
ui/src/Logout.tsx
ui/src/me/apis/index.ts
ui/src/onboarding/actions/index.ts
ui/src/onboarding/apis/index.ts
ui/src/onboarding/components/SigninForm.tsx
ui/src/utils/api.ts

Move authentication to external client

---

http/task_service_test.go
task.go
task/servicetest/servicetest.go

Remove owner from task json responses

---

ui/src/me/components/Resources.tsx
ui/src/onboarding/components/CompletionStep.tsx
ui/src/organizations/actions/index.ts
ui/src/organizations/apis/index.ts
ui/src/organizations/containers/OrganizationView.tsx
ui/src/shared/apis/v2/organization.ts
ui/src/utils/api.ts

Move organizations to external client library

---

http/task_service.go

chore(task): add messages to all HTTP errors from tasks

---

cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/query_test.go
cmd/influxd/launcher/tasks_test.go

Closes #11360
Adds some end to end tests for tasks using the launcher.
- [x ] Rebased/mergeable
- [x ] Tests pass

feat(tasks):end-to-end tests for the task system

---

.circleci/config.yml

Add litmus test runs to nightly build

---

tsdb/index/tsi1/index.go
tsdb/series_set.go
tsdb/series_set_test.go

Remove copy-on-write when caching bitmaps

---

ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/onboarding/apis/index.ts
ui/src/utils/api.ts

Switch write to client library

---

ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/onboarding/apis/index.ts
ui/src/onboarding/components/CompletionStep.tsx
ui/src/organizations/apis/index.ts
ui/src/organizations/components/Scrapers.tsx
ui/src/organizations/containers/OrganizationView.tsx
ui/src/utils/api.ts

Move scraper api calls to client library

---

services/snapshotter/client.go

- [:heavy_check_mark:] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
Golint services/snapshotter for https://github.com/influxdata/influxdb/issues/4098

Fix lint warnings snapshotter

---

services/graphite/parser.go

- [:heavy_check_mark:]  Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
Golint services/graphite for https://github.com/influxdata/influxdb/issues/4098

Fix golint warnings for services/graphite

---

.github/PULL_REQUEST_TEMPLATE.md

- [x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

to fix the dead link to InfluxQL in the PR template

---

models/points.go
models/time.go
pkg/encoding/simple8b/encoding.go
pkg/estimator/hll/hll.go
query/call_iterator.go
query/executor.go
query/iterator.go
query/select.go
services/httpd/handler_test.go
stress/config.go
stress/v2/stress_client/stress_client.go
tests/server_test.go
tsdb/engine/tsm1/batch_integer_test.go
tsdb/engine/tsm1/bool.go
tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/engine.go
tsdb/engine/tsm1/engine_test.go
tsdb/engine/tsm1/file_store.go
tsdb/engine/tsm1/int_test.go
tsdb/engine/tsm1/reader.go
tsdb/engine/tsm1/timestamp.go
tsdb/engine/tsm1/wal.go
tsdb/index.go
tsdb/index/tsi1/tsi1.go
tsdb/series_segment.go

Fix go report card issues identified by misspell.

Fix misspelling identified by misspell

---

http/dashboard_test.go
http/macro_test.go
http/telegraf_test.go

chore(http): simplify code

---

ui/package-lock.json
ui/package.json
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/onboarding/apis/index.ts
ui/src/onboarding/apis/mocks.ts
ui/src/onboarding/apis/onboarding.test.ts
ui/src/organizations/apis/index.ts
ui/src/organizations/components/Collectors.tsx
ui/src/organizations/components/Scrapers.tsx
ui/src/organizations/containers/OrganizationView.tsx
ui/src/utils/api.ts

Move telegraf configs api to client library

---

task/backend/scheduler.go
task/backend/scheduler_test.go

Previously a run that started successfully and then failed, would be
incorrectly marked as a success.
Closes #11627.

fix(task): set run status to failed if execution fails

---

ui/src/onboarding/components/CompletionStep.tsx
ui/src/onboarding/components/__snapshots__/CompletionStep.test.tsx.snap

Closes #11571 
Updates wording

fix(ui/onboarding): update Influx 2.0 -> InfluxDB 2.0

---

ui/package-lock.json
ui/package.json
ui/src/dashboards/apis/v2/index.ts
ui/src/utils/api.ts

Move cells api calls to client

---

ui/package-lock.json
ui/package.json
ui/src/dashboards/actions/v2/index.ts
ui/src/dashboards/apis/v2/index.ts
ui/src/dashboards/components/DashboardHeader.tsx
ui/src/dashboards/components/DashboardPage.tsx
ui/src/organizations/apis/index.ts
ui/src/types/v2/dashboards.ts
ui/src/utils/api.ts

Update dashboard api calls to use client

---

CHANGELOG.md
ui/src/clockface/components/wizard/WizardOverlay.tsx
ui/src/dataLoaders/components/DataLoadersWizard.tsx
ui/src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx
ui/src/dataLoaders/components/lineProtocolWizard/LineProtocolWizard.tsx
ui/src/dataLoaders/components/verifyStep/FetchAuthToken.tsx
ui/src/organizations/components/CollectorList.tsx
ui/src/organizations/components/CollectorRow.tsx
ui/src/organizations/components/Collectors.tsx
ui/src/organizations/components/TelegrafInstructionsOverlay.tsx

Closes #11481
Show an instructions from verify step using the associated influxdb_v2 plugin config token and id.

fix(ui): show telegraf config instructions

---

http/swagger.yml

Consolidate swagger files

---

http/swagger.yml

Swagger fixes

---

http/swagger.yml

Fix tasks response in swagger

---

http/swagger.yml

Add complete list of links to sources swagger

---

CHANGELOG.md
ui/src/index.tsx
ui/src/organizations/components/OrgTaskEditPage.tsx
ui/src/organizations/components/OrgTaskPage.tsx
ui/src/organizations/components/OrgTasksPage.tsx
ui/src/organizations/containers/OrganizationView.tsx
ui/src/tasks/actions/v2/index.ts
ui/src/tasks/containers/TaskPage.tsx

Updated index.tsx to include the routes for new and update tasks
Updated the actions for tasks to include an optional route parameter so it's accessible from org task page
Created org's own new task and task edit components

Update routes to create, update and select task from org page

---

CHANGELOG.md
ui/src/organizations/components/Retention.tsx

Closes #11575 
Swap retention policies from 'Periodically | Never' to 'Never | Periodically'

Swap retention policy on Create bucket overlay

---

etc/config.sample.toml
tsdb/config.go
tsdb/config_test.go
tsdb/index/tsi1/index.go
tsdb/index/tsi1/index_test.go
tsdb/index/tsi1/testdata/line-protocol-1M.txt.gz
tsdb/index_test.go

Allow TSI bitset cache to be configured

---

ui/package-lock.json
ui/package.json

Update client library dependency

---

ui/src/organizations/components/OrgTasksPage.tsx
ui/src/shared/components/EditableName.tsx
ui/src/tasks/components/TaskRow.tsx
ui/src/tasks/components/TasksList.tsx

Fix the inline edit for org tasks page
Update TaskRow to take in optional parameter for updateTask name.

Fix the inline edit for org tasks page

---

http/api_handler.go
http/label_service.go
http/label_test.go

Fix root labels endpoint

---

.circleci/config.yml
etc/litmus_fail_notify.sh
etc/litmus_success_notify.sh
etc/success_notify.sh

- created a litmus_daily job
- added persist_to_workspace to build job to have access to influxd binary
- added litmus_daily to build workflow
Closes #

enable Litmus Smoke tests on daily PRs

---

.circleci/config.yml

use attach_workspace for litmus nightly builds

---

.circleci/config.yml

fix nightly

---

CHANGELOG.md
cmd/influxd/restore/restore.go

- [x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
Fix #10072 see [comment](https://github.com/influxdata/influxdb/issues/10072#issuecomment-411077712)
- Restore original functionality (as documented)
- Print correct error messages

Fix legacy restore bug #10072

---

tsdb/engine/tsm1/compact.go
tsdb/engine/tsm1/compact_test.go

This reverts commit 381f206f4acbd34698b1349582117a551a918d62. (https://github.com/influxdata/influxdb/pull/10593)

Revert "Limit force-full and cold compaction size."

---

http/swagger.yml

Add name to scrapers target response in swagger file

Add name to scraper target response in swagger

---

bolt/authorization.go
bolt/bucket.go
bolt/keyvalue_log.go
bolt/kv.go
bolt/organization.go
bolt/user.go
bolt/user_resource_mapping.go
cmd/influxd/launcher/launcher.go
kv/auth.go
kv/bucket.go
kv/dashboard.go
kv/dashboard_test.go
kv/kvlog.go
kv/org.go
kv/service.go
kv/urm.go
kv/user.go

Closes #11721 
This PR migrates the bolt dashboard service to the kv store.

feat(kv): add dashboards to kv

---

task/backend/scheduler.go
task/backend/scheduler_test.go

Previously the DesiredState would not be cleared after an individual run
failed.
Fixes #11816.

fix(task): clean up run state after a run fails

---

task/servicetest/servicetest.go

The earliest time needed to be captured before creating the task, not
after; otherwise a test running close to a second boundary would fail.
Also make the failure message slightly more readable.

test(task): deflake test for CreatedAt, UpdatedAt

---

tsdb/index/tsi1/cache.go

Backport of https://github.com/influxdata/influxdb/pull/11829

Convert TagValueSeriesIDCache to use string fields

---

http/task_service.go
http/task_service_test.go

Update task http handler to use user resource mapping.

---

ui/src/clockface/components/tabs/TabContents.tsx
ui/src/clockface/components/tabs/Tabs.tsx
ui/src/index.tsx
ui/src/organizations/containers/OrgBucketsIndex.tsx
ui/src/organizations/containers/OrgHeader.tsx
ui/src/organizations/containers/OrganizationView.tsx

Extract Org Bucket Tab to use react router

---

ui/src/index.tsx
ui/src/organizations/components/Dashboards.tsx
ui/src/organizations/containers/OrgDashboardsIndex.tsx
ui/src/organizations/containers/OrganizationView.tsx

Move org dashboards to use react router

---

ui/src/index.tsx
ui/src/organizations/containers/OrgMembersIndex.tsx
ui/src/organizations/containers/OrganizationView.tsx

Use react router for members tab

---

ui/src/me/components/GettingStarted.tsx

Update from 'collectors_tab' to 'telegrafs_tab' to match the route.

fix(ui): update configure data collector  link on me page

---

CHANGELOG.md

add missing 1.5.5 entries

---

ui/src/dashboards/components/dashboard_index/CreateDashboardDropdown.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx

Add import dashboard option to create dashboard dropdown

---

cmd/influxd/launcher/launcher.go
kv/kv_test.go
kv/lookup_service.go
kv/lookup_service_test.go

Closes #11717 
Implements lookup service using the key-value store.  Ported from BoltDB impl.

feat(kv): add lookup service

---

bolt/scraper.go
cmd/influxd/launcher/launcher.go
http/scraper_service.go
http/user_service.go
inmem/scraper.go
kv/scrapers.go
kv/scrapers_test.go
kv/service.go
testing/scraper_target.go
testing/util.go

Closes #11889 
Convert scrapers to use kv store.  Update various error messages.

feat(cmd/influxd): add kv scraper

---

CHANGELOG.md
ui/src/me/components/account/ViewTokenOverlay.tsx
ui/src/me/components/account/__snapshots__/ViewTokenOverlay.test.tsx.snap

Closes #11780 
Updated token overlay to create an object with unique keys and values array for multiple actions

Combine permisssions in the ui on token overlay

---

ui/package-lock.json

Update npm dependencies with security issues

---

ui/src/tasks/components/TaskRow.tsx
ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap

Closes #
Commenting out the view runs buttons from tasks list

Comment out the view runs button from Tasks page

---

session.go
task/platform_adapter.go

Allow session authorization for tasks

---

ui/src/dashboards/components/dashboard_index/CreateDashboardDropdown.tsx

Hide un-implemented import functionality from UI

Remove unimplemented import functionality

---

authorizer/auth.go
http/task_service.go

WIP: Create Authz for tasks when using session (if no token is provided)

---

cmd/influxd/launcher/launcher.go
http/router.go
http/task_service.go
http/task_service_test.go
http/task_test.go
task/backend/bolt/bolt.go
task/backend/coordinator/coordinator.go
task/backend/inmem_store.go
task/backend/store.go
task/backend/storetest/storetest.go
task/platform_adapter.go
task/servicetest/servicetest.go
ui/package-lock.json

Clean out user from the task store's

---

ui/src/dashboards/components/dashboard_index/CreateDashboardDropdown.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/shared/components/DragAndDrop.tsx
ui/src/shared/components/ImportOverlay.scss
ui/src/shared/components/ImportOverlay.tsx
ui/src/shared/copy/notifications.ts

Generic import overlay

---

ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/dashboards/components/dashboard_index/TableRow.tsx
ui/src/shared/components/ExportOverlay.scss
ui/src/shared/components/ExportOverlay.tsx

Add generic export overlay

---

ui/src/shared/components/FeatureFlag.tsx

Some clean up on feature flag component

---

tsdb/index/inmem/meta.go

Backport https://github.com/influxdata/influxdb/pull/11750

Update tagKeyValue mutex to write lock.

---

tsdb/series_file.go
tsdb/series_file_test.go

Fix open/close race in SeriesFile

---

http/task_service_test.go
task.go
task/backend/coordinator/coordinator_test.go
task/backend/executor/executor_test.go
task/backend/store.go
task/backend/storetest/storetest.go
task/platform_adapter.go
task/validator_test.go

remove task owner from task struct

---

http/task_service.go
http/task_service_test.go
task/backend/inmem_logreaderwriter.go
task/backend/query_logreader.go
task/backend/scheduler_test.go
task/backend/store.go
task/backend/storetest/logstoretest.go

fix(task): use HTTP 404 for no results when listing runs, logs

---

ui/package-lock.json
ui/package.json

npm was reporting vulnerabilities, ran npm audit to to generate an audit report, and performed the recommended upgrades.

Fix package vulnerabilities

---

http/swagger.yml

Closes #11823 
Updated swagger to camel case the latest completed date for tasks get request

Update swagger to camel case the latest completed date

---

http/swagger.yml

docs(http): add operation log endpoints

---

http/swagger.yml

docs(http): fix typos

---

.editorconfig
.gitignore
Makefile
go.mod
go.sum
http/swagger.yml
tools.go

chore: add .editorconfig and enable in CI

---

authz.go

A dependency for billing metrics.

feat(influxdb): add billing resource type

---

authz.go

Reverts influxdata/influxdb#12001

Revert "feat(influxdb): add billing resource type"

---

ui/cypress/e2e/buckets.ts
ui/cypress/e2e/dashboards.ts
ui/cypress/e2e/orgs.ts
ui/cypress/e2e/tasks.ts
ui/cypress/index.d.ts
ui/cypress/support/commands.ts
ui/src/index.tsx

Adds back `GetSource` and `GetActiveSources`.
Creates a source on signin because the `debug/flush` endpoint doesn't recreate the `self` source after flush.

fix(ui): get active source

---

ui/src/organizations/components/Members.tsx

Update filter text for members to 'filter members'

---

ui/src/index.tsx
ui/src/me/components/account/Tokens.tsx
ui/src/organizations/containers/OrgTelegrafsIndex.tsx
ui/src/organizations/containers/OrganizationView.tsx

Extract telegrafs org view to use react router

---

cmd/influxd/launcher/launcher.go
http/task_service.go
http/task_service_test.go
http/task_test.go
task/platform_adapter.go
task/servicetest/servicetest.go

Populate organization name on task create action

---

docs/UpdatingAPICLient.md
docs/UpdatingSwagger.md

Create documentation for updating api client and updating swagger

---

http/swagger.yml

docs(http): update request body for updating a task

---

http/swagger.yml

Add description to spec for telegraf config

---

cmd/influx/task.go

feat(cmd/influx): show AuthorizationID of tasks

---

task/validator.go
task/validator_test.go

The previous behavior specifically looked for organization-wide task
read/write permissions. Now we allow permissions on specific tasks.

fix(task): validate permissions on specific tasks

---

ui/src/dashboards/components/dashboard_index/TableRow.tsx
ui/src/shared/components/AddResourceDropdown.tsx
ui/src/tasks/components/TaskRow.tsx
ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap

put export buttons behind feature flag and delete import option from generic dropdown button.

Place imports and exports behind feature flag

---

http/telegraf_test.go
telegraf.go
ui/mocks/dummyData.ts
ui/package-lock.json
ui/package.json
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx
ui/src/dataLoaders/reducers/dataLoaders.ts
ui/src/organizations/components/CollectorRow.tsx
ui/src/shared/components/editable_description/EditableDescription.tsx
ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap
ui/src/tasks/components/__snapshots__/TasksList.test.tsx.snap
ui/src/tasks/containers/__snapshots__/TasksPage.test.tsx.snap
ui/src/types/v2/dataLoaders.ts

Closes #11614 
Can add a description when creating a config:
Or after it has been created:

Enable adding a description to a telegraf config

---

CHANGELOG.md

Add labels updates to changelog

fix(ui/changelog): add labels changes to changelog 

---

http/task_service.go

This is a partial rollback of changes from #12004. Issue to track adding a
test: #12089.

fix(task): restore functionality for creating task with org name

---

cmd/influxd/launcher/launcher.go
task/backend/bolt/bolt.go
task/backend/bolt/bolt_test.go

Allow tasks to skip catchup

---

CHANGELOG.md
ui/package-lock.json
ui/package.json
ui/src/tasks/actions/v2/index.ts

Closes #12031
when cloning a task, the labels should also get cloned
Move task cloning logic to external client library

feat(ui): Clone a task's labels when cloning the task

---

http/task_service.go
http/task_service_test.go

The query system specifically expects an Authorization. When a request
comes in using a Session, use the target task's Authorization, if we are
allowed to read it, when executing a query against the system bucket.
Closes #11974.

fix(task): pass task's authorization to query system, if using sessions

---

ui/src/shared/components/dateRangePicker/DatePicker.tsx
ui/src/shared/components/dateRangePicker/DateRangePicker.scss
ui/src/shared/components/dateRangePicker/DateRangePicker.tsx

date picker styles

---

ui/src/minard/components/Axes.tsx
ui/src/minard/components/Plot.tsx
ui/src/minard/index.ts
ui/src/minard/utils/bin.ts
ui/src/minard/utils/plotEnvActions.ts
ui/src/minard/utils/plotEnvReducer.ts
ui/src/shared/components/Histogram.tsx
ui/src/shared/utils/view.ts
ui/src/timeMachine/actions/index.ts
ui/src/timeMachine/components/view_options/HistogramOptions.tsx
ui/src/timeMachine/reducers/index.ts
ui/src/types/v2/dashboards.ts
view.go

Add x axis label option to histogram

---

ui/src/organizations/components/CollectorList.tsx
ui/src/organizations/components/CollectorRow.tsx
ui/src/organizations/components/CreateOrgOverlay.tsx
ui/src/organizations/components/OrgTasksPage.tsx
ui/src/organizations/components/TelegrafConfigOverlay.tsx
ui/src/organizations/components/Variables.tsx
ui/src/organizations/components/__snapshots__/Collectors.test.tsx.snap
ui/src/organizations/containers/OrgBucketsIndex.tsx
ui/src/tasks/components/TasksHeader.tsx

Closes #12064 
Closes #12110 
Closes #12075 
Closes #12077 
Closes #12065 
Closes #12092

Misc. UI Polish

---

http/org_service.go
kv/bucket.go
kv/dashboard.go
kv/org.go
kv/user.go

fix(http): return an empty list of operation logs if not found

---

task/backend/executor/executor.go
task/backend/scheduler.go
task/mock/scheduler.go

Add stats to the run log

---

ui/package-lock.json
ui/src/minard/components/Plot.tsx
ui/src/minard/components/SizedPlot.tsx
ui/src/shared/components/Histogram.tsx

Let `Plot` components measure the dimensions of their containing element automatically. I think this is a slightly nicer public API.

Let Plot components size themselves

---

ui/src/organizations/components/Scrapers.tsx

Closes #12055
Updated Scraper component to filter on input change on scrapers

Add filtering to scrapers tab on org

---

task.go
task/options/options.go
task_test.go

Closes #12100 and #12093 and #11670

fix(tasks): allow switching between cron and every options

---

ui/cypress/e2e/variables.test.ts
ui/cypress/index.d.ts
ui/cypress/support/commands.ts

Closes #12130
This PR will add an end-to-end Cypress test for variable deletion.

test(variables): add test for deletion

---

ui/cypress/e2e/explorer.test.ts
ui/src/timeMachine/components/QueriesSwitcher.tsx
ui/src/timeMachine/components/SubmitQueryButton.tsx

Add e2e test for dis/enabled DE submit button

---

tsdb/errors.go

storage: cleanup shard errors

---

pkg/data/gen/seriesgenerator.go

Removes a dependency on influxdata/platform

Remove influxdata/platform dependency

---

ui/src/timeMachine/actions/index.ts
ui/src/timeMachine/components/QueriesSwitcher.tsx
ui/src/timeMachine/components/TimeMachine.tsx
ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
ui/src/timeMachine/reducers/index.test.ts
ui/src/timeMachine/reducers/index.ts
ui/src/timeMachine/selectors/index.ts
ui/src/types/v2/dashboards.ts

In time machine only show a confirmation modal if the script is
different that the builder
Closes #12151

Show confirmation modal only if script changed

---

http/task_service.go
http/task_service_test.go
task.go

fix(http): validate status for creating and updating a task

---

ui/package-lock.json
ui/src/organizations/components/CreateVariableOverlay.tsx
ui/src/organizations/components/Variables.tsx
ui/src/organizations/containers/OrganizationView.tsx
ui/src/shared/copy/notifications.ts
ui/src/store/configureStore.ts
ui/src/timeMachine/components/variableToolbar/VariableToolbar.tsx
ui/src/types/v2/index.ts
ui/src/variables/actions/index.ts
ui/src/variables/reducers/index.ts
ui/src/variables/selectors/index.tsx

Working towards #12162
Moves `Variable` state from local component state to the Redux store.

Centralize variables state in Redux store

---

ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/organizations/components/Buckets.tsx
ui/src/organizations/components/CollectorList.tsx
ui/src/organizations/components/CollectorRow.tsx
ui/src/organizations/components/Collectors.tsx
ui/src/organizations/components/Scrapers.tsx
ui/src/shared/copy/v2/notifications.ts
ui/src/tasks/components/TasksHeader.tsx

Closes #12220 
Add the ability to show notifications on telegrafs update/delete actions
Updated all the filter input text to look the same

Update telegraf to display notifications for update/delete

---

ui/package-lock.json
ui/package.json
ui/src/shared/copy/v2/notifications.ts
ui/src/tasks/actions/v2/index.ts
ui/src/tasks/components/RunLogRow.tsx
ui/src/tasks/components/RunLogsList.tsx
ui/src/tasks/components/TaskRunsList.tsx
ui/src/tasks/components/TaskRunsPage.tsx
ui/src/tasks/components/TaskRunsRow.tsx
ui/src/tasks/reducers/v2/index.ts

Closes #12155 
Update TaskRunRow to connect with redux to get the logs for a task run

Update logs to use api call instead of dummy data

---

ui/cypress/e2e/explorer.test.ts
ui/cypress/e2e/tasks.test.ts
ui/cypress/tsconfig.json
ui/cypress/webpack.config.js
ui/src/shared/components/EmptyGraphMessage.tsx
ui/src/shared/components/EmptyQueryView.tsx
ui/src/timeMachine/components/TimeMachineBottom.tsx

test(e2e/de): shows an error syntactically incorrect query is submitted

---

ui/cypress/e2e/buckets.test.ts
ui/cypress/index.d.ts
ui/cypress/support/commands.ts

test(buckets): add test for deletion

---

ui/src/dashboards/actions/v2/index.ts
ui/src/dashboards/apis/v2/index.ts
ui/src/organizations/components/OrgTaskEditPage.tsx
ui/src/organizations/components/OrgTasksPage.tsx
ui/src/organizations/containers/OrganizationView.tsx
ui/src/tasks/actions/v2/index.ts
ui/src/tasks/components/TasksList.tsx
ui/src/tasks/containers/TaskEditPage.tsx
ui/src/tasks/containers/TasksPage.tsx
ui/src/tasks/reducers/v2/index.ts
ui/src/types/v2/dashboards.ts
ui/src/types/v2/index.ts
ui/src/types/v2/tasks.ts

Closes #12238 
Consolidate types for Tasks and fix Task labels to use `src/types/v2`

fix(ui/types/v2/tasks): consolidate task types

---

ui/src/organizations/components/OrgTaskEditPage.tsx
ui/src/organizations/components/OrgTaskPage.tsx
ui/src/organizations/components/OrgTasksPage.tsx
ui/src/tasks/components/TaskRow.tsx

Routes were not routing correctly without backslash at beginning of route

Add backslash to org routes

---

ui/cypress/e2e/scrapers.test.ts
ui/cypress/index.d.ts
ui/cypress/support/commands.ts
ui/src/organizations/components/__snapshots__/Buckets.test.tsx.snap
ui/src/shared/components/EditableName.tsx

test(scrapers): update a scraper name

---

ui/cypress/e2e/scrapers.test.ts
ui/cypress/support/commands.ts

test(scrapers): test for deleting a scraper

---

ui/cypress/e2e/collectors.tests.ts
ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx
ui/src/dataLoaders/components/verifyStep/DataListening.tsx

test(collectors) Test telegraf config creation on collectors tab

---

task.go
task/backend/bolt/bolt.go
task/backend/store.go
task/platform_adapter.go
task/servicetest/servicetest.go

fix(tasks): fix task update validation

---

task/backend/bolt/bolt.go
task/backend/store.go

Cleans up comments that got accidentally merged.

chore(task): Clean up comments.

---

errors.go
http/swagger.yml

Re-opening of #12296, to test CODEOWNERS change.

fix(swagger): synchronize enum with defined error constants

---

ui/cypress/e2e/buckets.test.ts
ui/cypress/e2e/collectors.test.ts
ui/cypress/e2e/dashboardsIndex.test.ts
ui/cypress/e2e/orgs.test.ts
ui/cypress/e2e/scrapers.test.ts
ui/cypress/e2e/tasks.test.ts
ui/cypress/e2e/variables.test.ts
ui/src/dashboards/actions/v2/index.ts
ui/src/dashboards/components/ImportDashboardOverlay.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/index.tsx
ui/src/organizations/components/OrgTaskImportOverlay.tsx
ui/src/organizations/components/OrgTasksPage.tsx
ui/src/shared/components/AddResourceDropdown.tsx
ui/src/shared/components/ImportOverlay.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/copy/v2/notifications.ts
ui/src/tasks/components/TasksHeader.tsx
ui/src/tasks/containers/TasksPage.tsx

Move Import Overlay to be rendered by routes.

Add import overlay to org tasks by way of routes

---

gather/recorder.go
http/write_handler.go
models/points.go
models/points_internal_test.go
models/points_test.go
query/stdlib/influxdata/influxdb/to.go
query/stdlib/influxdata/influxdb/to_test.go
storage/engine_test.go
tsdb/explode.go
tsdb/explode_test.go
tsdb/index_test.go
tsdb/tsm1/engine_delete_bucket_test.go
tsdb/tsm1/engine_test.go

This pull request optimizes the write path by merging the parse & explode code to minimize allocations.

Merge point parse & explode.

---

gather/recorder.go
http/write_handler.go
models/points.go
models/points_internal_test.go
models/points_test.go
query/stdlib/influxdata/influxdb/to.go
query/stdlib/influxdata/influxdb/to_test.go
storage/engine_test.go
tsdb/explode.go
tsdb/explode_test.go
tsdb/index_test.go
tsdb/tsm1/engine_delete_bucket_test.go
tsdb/tsm1/engine_test.go

Revert "Merge point parse & explode."

---

ui/src/shared/constants/fluxFunctions.ts

refactor(stdlib): moved influxFieldsAsCols to influxdata/influxdb/v1; removed references in influxdb code

---

ui/src/buckets/actions/index.ts
ui/src/buckets/reducers/index.ts
ui/src/configuration/components/BucketList.tsx
ui/src/configuration/components/Buckets.tsx
ui/src/configuration/components/ConfigurationPage.tsx
ui/src/configuration/components/CreateBucketOverlay.tsx
ui/src/configuration/components/GetResources.tsx
ui/src/labels/reducers/index.ts
ui/src/organizations/components/BucketRow.tsx
ui/src/organizations/components/__snapshots__/Buckets.test.tsx.snap
ui/src/shared/copy/notifications.ts
ui/src/store/configureStore.ts
ui/src/types/v2/index.ts

refactor: make get labels generic

---

ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx
ui/src/dataLoaders/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap
ui/src/dataLoaders/constants/pluginConfigs.ts
ui/src/organizations/components/CreateScraperOverlay.tsx

fix: replace hardcoded localhost:9999 with browser origin

---

ui/cypress/e2e/tasks.test.ts
ui/package-lock.json
ui/package.json
ui/src/dataExplorer/components/SaveAsTaskForm.tsx
ui/src/organizations/components/OrgTaskPage.tsx
ui/src/shared/apis/ast.ts
ui/src/shared/utils/insertPreambleInScript.ts
ui/src/tasks/actions/v2/index.ts
ui/src/tasks/containers/TaskPage.tsx
ui/src/variables/utils/getWindowVars.ts

fix: flux imports

---

cmd/influxd/launcher/tasks_test.go
http/task_service_test.go
task.go
task/backend/inmem_logreaderwriter.go
task/backend/query_logreader.go
task/backend/storetest/logstoretest.go
task/servicetest/servicetest.go
task/validator_test.go

change task logs from a string to a struct

---

ui/src/mockState.tsx
ui/src/pageLayout/components/NavMenuItem.tsx
ui/src/pageLayout/components/NavMenuSubItem.tsx
ui/src/pageLayout/containers/Nav.test.tsx
ui/src/pageLayout/containers/Nav.tsx

fix: nav double highlight

---

task/backend/store.go

Respect the incoming flux script

---

ui/src/timeMachine/constants/visGraphics.tsx

Closes #12367
Add Histogram Icon

add histogram icon

---

query/stdlib/influxdata/influxdb/from.go
query/stdlib/influxdata/influxdb/storage.go
storage/reads/reader.go
storage/reads/table.gen.go
storage/reads/table.gen.go.tmpl
storage/reads/table.go

Related to influxdata/flux#1021.

fix(storage/reads): track memory allocations when reading from storage

---

authz.go
cmd/influxd/launcher/launcher.go
document.go
http/api_handler.go
http/document_service.go
http/swagger.yml
http/user_resource_mapping_service.go
kv/document.go
kv/document_test.go
kv/label.go
kv/service.go
testing/document.go
user_resource_mapping.go

Closes #2443
This PR implements templates via a generic documents resource type.
TODO

Add templates

---

ui/package-lock.json
ui/package.json
ui/src/protos/actions/index.ts
ui/src/types/v2/dashboards.ts

- Update client to 0.2.27
- Extend IDashboard in `src/types/v2/dashboards`

chore(ui/client:) update client to 0.2.27

---

http/swagger.yml
http/task_service.go
ui/src/clockface/components/overlays/OverlayContainer.tsx
ui/src/tasks/actions/v2/index.ts
ui/src/tasks/components/RunLogRow.tsx
ui/src/tasks/components/RunLogsList.scss
ui/src/tasks/components/RunLogsList.tsx
ui/src/tasks/components/TaskRunsRow.tsx

Update Logs type in task_service to include an object for Events. Add styling to the logs list to wrap the message. Update the date to display in readable javascript date format

Update Logs type in tasks response to include an object for event

---

ui/src/onboarding/OnboardingWizard.scss
ui/src/onboarding/components/CompletionStep.tsx
ui/src/onboarding/components/OnboardingButtons.tsx
ui/src/onboarding/components/OtherStep.tsx
ui/src/onboarding/components/__snapshots__/CompletionStep.test.tsx.snap

Closes #12030
Rework onboarding scroll area styles to remove outer box and prevent unnecessary scrolling.

fix onboarding scrollbars

---

proto/system.json

Closes https://github.com/influxdata/influxdb/issues/12413

fixing system dash

---

http/task_service.go
http/task_service_test.go
task.go

feat(http): add task paging links

---

kv/session.go

If the user is the oper user give them the permissions on their token. This is a hack.

Grant user union of their tokens and urms perms

---

ui/cypress/e2e/orgs.test.ts

test: reintroduce org

---

ui/src/pageLayout/containers/Nav.tsx

chore: add buckets sub item to config nav

---

task/backend/inmem_logreaderwriter.go
task/backend/query_logreader.go
task/backend/scheduler_test.go
task/backend/storetest/logstoretest.go
ui/package-lock.json

Return empty list of runs and logs when none are found

---

http/swagger.yml
task.go

Update the required fields for task swagger

---

ui/package-lock.json
ui/package.json
ui/src/tasks/actions/v2/index.ts

Update client library dependency and update some tasks client calls based on client library changes.

fix(ui): Update client library dependency to fix duplicating labels on task import

---

bolt/passwords.go
inmem/passwords.go
kv/passwords.go
testing/passwords.go
ui/src/organizations/components/CreateScraperOverlay.tsx

Minor text updates for password error and default scraper name

---

bolt/bucket.go
inmem/bucket_service.go
kv/bucket.go
testing/bucket_service.go

Closes https://github.com/influxdata/influxdb/issues/12449
fix the update problems

fix(kv): fix bucket update issue

---

kv/org.go

This PR removed an organizations bucket when the organization is deleted.

fix(kv): deleted organizations leave orphaned buckets

---

ui/src/variables/actions/index.ts
ui/src/variables/reducers/index.ts
ui/src/variables/selectors/index.tsx
ui/src/variables/types/index.ts
ui/src/variables/utils/ValueFetcher.test.ts
ui/src/variables/utils/ValueFetcher.ts
ui/src/variables/utils/getVarAssignment.ts
ui/src/variables/utils/hydrateVars.test.ts
ui/src/variables/utils/hydrateVars.ts
ui/src/variables/utils/resolveSelectedValue.ts

Closes #12162
This PR provides a utility to run the queries for a collection of variables. It will support all the various variable related-features in the UI.

Variable hydration

---

task/backend/executor/executor.go
task/backend/executor/executor_test.go

Rather than only putting the authorization on the context, also, add it to the proxy query service request.

fix(task): set query request authorization

---

ui/package-lock.json
ui/package.json

Update client library dependency
Fixes error that occurs if a task with labels that exist with the same name but different ids.

chore(ui): update client library dependency

---

http/bucket_service.go
http/bucket_test.go
http/org_service.go
http/scraper_service.go
http/scraper_service_test.go
http/swagger.yml
http/telegraf.go

docs(http): add members/owners links

---

ui/src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx
ui/src/dataLoaders/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap

Update the language for the portion that kicks off telegraf after initial registration of the endpoint.

Tweak language in the initial telegraf registration for v2.0 alpha

---

ui/src/clockface/components/dropdowns/Dropdown.scss
ui/src/clockface/components/dropdowns/Dropdown.tsx
ui/src/clockface/components/dropdowns/DropdownButton.scss
ui/src/clockface/components/dropdowns/DropdownButton.tsx
ui/src/shared/components/TimeRangeDropdown.tsx
ui/src/shared/constants/timeRanges.ts
ui/src/shared/data/autoRefreshes.ts

Closes #12148 
Closes #12501 
Closes #12502
Animate rotation of caret between open/closed state
Remove large left padding when dropdown is in `Action` mode
Ensure `Paused` is highlighted in the dropdown menu when the option is selected
Add divider with label to top of dropdown for consistency

Polish Dropdowns 

---

ui/src/clockface/components/dropdowns/MultiSelectDropdown.tsx
ui/src/organizations/components/AddMembersForm.tsx
ui/src/organizations/components/AddMembersOverlay.tsx
ui/src/organizations/components/SelectUsers.tsx

Closes #12438 
Create filter on the add member overlay and add member list to display selected members before saving changes.

Add filter to the users dropdown and list of selected members

---

ui/src/dashboards/actions/v2/views.ts
ui/src/dashboards/apis/v2/index.ts
ui/src/dashboards/components/DashboardExportOverlay.tsx
ui/src/shared/components/cells/Cell.tsx
ui/src/shared/utils/resourceToTemplate.ts

Closes #12324 
Transforms the dashboard, cells and views using the json api relationships, attributes, included, and id,  and type.

feat(ui/export/json): format export using jsonapi

---

ui/package-lock.json
ui/package.json
ui/src/dashboards/components/DashboardExportOverlay.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/organizations/components/OrgTaskExportOverlay.tsx
ui/src/shared/components/ExportOverlay.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/utils/resourceToTemplate.test.ts
ui/src/shared/utils/resourceToTemplate.ts

Add export dashboard to template button to export overlay

---

ui/src/onboarding/actions/index.ts
ui/src/organizations/constants/index.ts

Create system template on onboarding

---

ui/src/shared/constants/timeRanges.ts

fix(ui): update default time range to relative time range

---

http/swagger.yml

docs(http): add missing logs links

---

http/swagger.yml

docs(http): add bucket and org links to ScraperTargetResponse

---

ui/src/organizations/components/UpdateVariableOverlay.tsx

Fix updating variable script

---

ui/src/shared/components/TimeSeries.tsx

Fix unresponsive time range dropdown on dashboards

---

ui/src/organizations/constants/index.ts

fix(ui): add v namespace before variables in System template

---

http/swagger.yml

fix(ui): Remove name from cell in swagger definition

---

ui/src/tasks/components/TaskRunsList.tsx

Closes #12463 
Added sorting to the header cells on task run

Add sorting to  Task Runs List

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12546
fixed the swagger based on current implementation

fix(http): fix ready swagger

---

http/source_service.go
http/source_service_test.go

Closes https://github.com/influxdata/influxdb/issues/12547
fixed the links, and message error

fix(http): fix source health endpoint

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12588
update swagger file to use labelResponse like telegraf and dashboard

fix(http): fix swagger label response

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12591

fix(http): fix task swagger links labels

---

ui/src/index.tsx
ui/src/organizations/components/TaskExportOverlay.tsx
ui/src/organizations/components/TaskImportOverlay.tsx
ui/src/shared/components/ExportOverlay.tsx
ui/src/shared/copy/notifications.ts

Closes #12495 
Enables task export to template from export overlay

Create template from task

---

ui/package-lock.json
ui/src/configuration/components/ConfigurationPage.tsx
ui/src/configuration/components/CreateVariableOverlay.tsx
ui/src/configuration/components/GetResources.tsx
ui/src/configuration/components/Variables.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/variables/actions/index.ts

Add variables to configuration page and navigation for config tabs

---

kit/check/check.go
kit/check/check_test.go

Restores a force healthy/unhealthy option previously in 2.0 code.

check: restore force healthy

---

task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go
task/backend/scheduler.go

Ensure when a manual run is called we run it as soon as possible

---

http/task_service.go
http/task_service_test.go

test(task): ensure task can be created over HTTP using org name

---

task/backend/scheduler.go
task/backend/scheduler_test.go

This should considerably simplify debugging when things go wrong with
the tasks, as this error can be displayed from the UI or CLI. Prior to
this change, you would have to view the console output from influxd.
Fixes #12548.

feat(task): include run errors in task log

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12590

feat(http): update swagger to use runs

---

ui/src/shared/constants/fluxFunctions.ts
ui/src/timeMachine/components/fluxFunctionsToolbar/FluxFunctionsToolbar.tsx
ui/src/timeMachine/components/fluxFunctionsToolbar/ToolbarFunction.tsx

Closes https://github.com/influxdata/chronograf/issues/5088

fix(fluxui/union): removes pipes and strings from union insertion

---

CHANGELOG.md
ui/src/shared/components/code_mirror/_ThemeTimeMachine.scss

Connects #12503
Fixes issue number 2 in mentioned issue.

Stop scrollbars from covering text in flux editor

---

ui/src/tasks/components/TaskRunsPage.tsx

Closes #12453 
Update Tasks Run page to allow user to run a task manually

Add the ability to run task manually from tasks run page

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12647

fix(http): remove dup tasks definition

---

bolt/label.go
http/swagger.yml
inmem/label_service.go
kv/label.go
label.go
testing/label_service.go

Allow label names to be updated.

Label names

---

CHANGELOG.md

Update Changelog for Alpha 6

---

http/swagger.yml
http/telegraf.go

Closes https://github.com/influxdata/influxdb/issues/12643

fix(http): fix telegraf delete

---

ui/package-lock.json
ui/package.json
ui/src/dashboards/components/DashboardExportOverlay.tsx
ui/src/organizations/components/TaskExportOverlay.tsx
ui/src/shared/components/ExportOverlay.tsx
ui/src/shared/utils/resourceToTemplate.ts

Update UI to accept updated template types from client

Adapt template types to client

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12675
fix the resource owner and member response of bucket

Swagger bucket owner

---

ui/package-lock.json
ui/src/dashboards/actions/views.ts
ui/src/dashboards/components/DashboardPage.tsx
ui/src/dashboards/components/VEO.tsx
ui/src/dashboards/selectors/index.ts
ui/src/index.tsx
ui/src/timeMachine/components/TimeMachine.tsx

VEO use react router for rendering and moves view retrieving into the VEO.

VEO uses react router

---

http/api_handler.go

fix(http): wrap label service with authorizer

---

query/stdlib/influxdata/influxdb/from_test.go

test(stdlib): fix mismatched planner node types

---

ui/package-lock.json
ui/src/tasks/actions/v2/index.ts
ui/src/utils/api.ts

Closes #12689
I really like [this](https://github.com/influxdata/influxdb/pull/12704/files#diff-26d13671c2309446101c125ea3499756R7) pattern.  Whoever wrote this, kudos.  Now to only implement it everywhere...

fix(task/ui): display server error message

---

ui/package-lock.json
ui/package.json
ui/src/configuration/components/CreateLabelOverlay.tsx
ui/src/configuration/components/Labels.tsx
ui/src/labels/actions/index.ts

Closes #12578
- imports updates to the client 
- you can now change a label's name 😸

feat(labels/ui): update label name

---

http/swagger.yml

Remove required label param from Document types

---

authz.go
http/swagger.yml

fix(swagger): synchronize permission enum with code

---

task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go

Closes https://github.com/influxdata/influxdb/issues/12650.

fix(task): only claim active tasks at startup

---

telegraf.go
telegraf_test.go

Closes https://github.com/influxdata/influxdb/issues/12671
added one more test case

feat(telegraf): allow config to be empty

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12670
Closes https://github.com/influxdata/influxdb/issues/12627
Closes https://github.com/influxdata/influxdb/issues/12673

fix(http): telegraf swagger issues

---

ui/src/configuration/components/ConfigurationPage.tsx
ui/src/configuration/components/Labels.tsx
ui/src/configuration/components/Telegrafs.tsx
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/labels/constants/index.ts
ui/src/organizations/components/TelegrafInstructionsOverlay.tsx

Closes #12579 
This PR establishes an MVP for managing chronograf specific resource relationships with labels.
- Prefix application specific labels with name `@influxdata`
- Make connections upon linked resource creation
- Cleanup labels upon linked resource deletion
- Filter labels with `@influxdata` prefix from label views

chore(telegraf/ui): link tokens to telegraf configs via labels

---

ui/package-lock.json
ui/package.json
ui/src/configuration/components/Labels.tsx
ui/src/index.tsx
ui/src/organizations/components/OrgTemplateFetcher.tsx
ui/src/organizations/components/OrgTemplatesList.tsx
ui/src/organizations/components/OrgTemplatesPage.tsx
ui/src/organizations/components/OrganizationNavigation.tsx
ui/src/organizations/containers/OrgTemplatesIndex.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/utils/resourceToTemplate.ts
ui/src/store/configureStore.ts
ui/src/templates/actions/index.ts
ui/src/templates/components/EmptyTemplatesList.tsx
ui/src/templates/components/TemplateCard.tsx
ui/src/templates/components/TemplateExportOverlay.tsx
ui/src/templates/components/TemplateImportOverlay.tsx
ui/src/templates/components/TemplatesHeader.tsx
ui/src/templates/constants/index.ts
ui/src/templates/reducers/index.ts
ui/src/types/v2/index.ts

Add templates tab to orgs

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx
ui/src/dashboards/components/variablesControlBar/VariablesControlBar.scss
ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx
ui/src/variables/actions/index.ts
ui/src/variables/selectors/index.tsx
ui/src/variables/utils/hydrateVars.ts

Closes #12654
Fixes a grab bag of issues with variables:
- Refresh all variables when a variable selection is made on a dashboard
(to handle variables depending on other variables)
- Show a loading state in the variable control bar on a dashboard when
variable values are loading
- Do not attempt to form a `VariableAssignment` from a variable with no
available values
- Memoize the `getVariablesForDashboard` selector
- Cancel outdated variable hydration requests
- Fix a bug that caused more variables to be hydrated that necessary

Misc variables polish

---

ui/cypress/e2e/dashboardsIndex.test.ts
ui/cypress/e2e/tasks.test.ts
ui/cypress/support/commands.ts
ui/package-lock.json
ui/package.json
ui/src/configuration/components/Labels.tsx
ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/dataLoaders/reducers/dataLoaders.ts
ui/src/dataLoaders/utils/pluginConfigs.ts
ui/src/labels/actions/index.ts
ui/src/labels/api/index.ts
ui/src/tasks/components/TaskCard.tsx
ui/src/types/v2/dataLoaders.ts

Update client for labels orgID changes

---

query/bridges.go

The asyncStatsResultIterator used inside QueryServiceProxyBridge assumed
that Release would only be called once. The godoc for ResultIterator
specifies that it is safe to call Release multiple times. Now, you can
do that without causing Release to block indefinitely.

fix(query): allow multiple calls to Release proxy bridge iterator

---

ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx
ui/src/organizations/components/CollectorRow.tsx
ui/src/organizations/components/Collectors.tsx
ui/src/organizations/components/__snapshots__/Collectors.test.tsx.snap
ui/src/organizations/containers/OrgTelegrafsIndex.tsx
ui/src/organizations/reducers/orgView.ts
ui/src/shared/components/tabbed_page/TabbedPageSection.tsx
ui/src/telegrafs/actions/index.ts

Reduxify the org view for telegrafs.

chore: Update telegrafs in orgs view to use redux

---

storage/reads/table.gen.go
storage/reads/table.gen.go.tmpl

fix(storage/reads): release arrow buffers when advancing on table

---

task/options/options.go
task/options/options_test.go

Closes https://github.com/influxdata/influxdb/issues/12699.
Leaving in draft state until https://github.com/influxdata/influxdb/pull/12370 is merged first, to avoid creating a merge conflict.

feat(task): reject unknown task options

---

.github/PULL_REQUEST_TEMPLATE

This PR adds a checkbox for updating the changelog to the PR message template

Add CHANGELOG.md to PR template

---

ui/src/index.tsx
ui/src/organizations/components/CreateOrgOverlay.tsx
ui/src/organizations/containers/OrganizationsIndex.tsx

Move create organization overlay to route

---

ui/src/dashboards/components/VEO.tsx

fix(ui): fetch queries when opening veo

---

ui/src/configuration/components/Buckets.tsx
ui/src/configuration/components/ConfigurationPage.tsx
ui/src/configuration/components/CreateScraperOverlay.tsx
ui/src/configuration/components/GetResources.tsx
ui/src/configuration/components/Scrapers.tsx
ui/src/pageLayout/containers/Nav.tsx
ui/src/scrapers/actions/index.ts
ui/src/scrapers/reducers/index.ts
ui/src/store/configureStore.ts
ui/src/types/v2/index.ts

Closes #12252 
Adding Scrapers tab and navigation link under configuration

Move Scrapers to configuration page

---

ui/src/me/components/account/TokenRow.tsx

Closes #12709 
Add confirmation button to tokens for delete

Add confirmation to the delete button on tokens

---

ui/package-lock.json
ui/package.json
ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/DashboardExportOverlay.tsx
ui/src/index.tsx
ui/src/organizations/components/TaskExportOverlay.tsx
ui/src/organizations/containers/OrgDashboardsIndex.tsx
ui/src/shared/components/ExportOverlay.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/utils/resourceToTemplate.ts
ui/src/tasks/actions/index.ts
ui/src/templates/actions/index.ts
ui/src/templates/components/TemplateExportOverlay.tsx
ui/src/templates/reducers/index.ts

Closes #12490 
Closes #12397
Fixed routing issues for import and export overlays, 
Port export states for templates, tasks and dashboards to redux
Add variables to dashboard template at export.

Add vars to dash temp

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12824
add the swagger endpoint of delete template

fix(http): swagger add template endpoint

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12717
Closes https://github.com/influxdata/influxdb/issues/12723

fix(http): fix scraper, buckets label swagger resp

---

.gitignore
chronograf/influx/queries/select.go
chronograf/server/mountable_router_test.go
go.mod
go.sum
task/backend/storetest/logstoretest.go

And fix newly discovered errors.

chore: update staticcheck to latest

---

http/source_service.go

Closes https://github.com/influxdata/influxdb/issues/12814

fix(http): fix invalid source buckets

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12776

fix(http): swagger write precision

---

ui/cypress/e2e/variables.test.ts
ui/src/configuration/components/Variables.tsx
ui/src/organizations/components/Variables.tsx

Closes #12763 
Update variables component to use the same component for create button as the one in the header

Update variables to use the same component for create button

---

ui/package-lock.json
ui/package.json
ui/src/dashboards/actions/index.ts
ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx
ui/src/templates/api/index.ts
ui/src/templates/types/index.ts
ui/src/templates/utils/index.test.ts
ui/src/templates/utils/index.ts
ui/src/types/v2/index.ts

Closes #12489
Also move create dashboard functions from client to UI

Create included variables when creating dashboards from template

---

CHANGELOG.md

doc(changelog): Updates for 1.7.5 release

---

http/swagger.yml
http/user_service.go

Closes https://github.com/influxdata/influxdb/issues/12772

fix(http): swagger change user pass reset resp

---

ui/src/pageLayout/components/CloudNav.tsx
ui/src/pageLayout/components/NavMenu.tsx
ui/src/pageLayout/containers/Nav.tsx

Add cloud navigation

---

CHANGELOG.md
ui/package-lock.json
ui/package.json
ui/src/shared/copy/notifications.ts
ui/src/templates/actions/index.ts
ui/src/templates/components/TemplateCard.tsx
ui/src/templates/components/TemplateImportOverlay.tsx
ui/src/templates/reducers/index.ts

Co-authored-by: Alirie Gray <alirie.gray@gmail.com>
Closes #12742 
Updated the client to match the swagger's definition of delete template
Updated template card to call Delete action
Created actions and reducers to update the redux state to remove the template

Add the ability to delete a template

---

http/org_service.go
http/org_test.go
http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12716
fixed the swagger file, response code, test case.
manually tested

fix(http): fix org secrets delete

---

kv/document.go

Closes #12858 
This PR populates the labels field on a document whenever it is created or updated.

Include labels when creating/updating documents

---

ui/src/shared/copy/notifications.ts
ui/src/variables/actions/index.ts

Display notifications when variables are updated or deleted

---

document.go
kv/document.go
testing/document.go

Closes https://github.com/influxdata/influxdb/issues/12864
Closes https://github.com/influxdata/influxdb/issues/12871
add an error check for not found errors for documents

fix(http): fix template not found error

---

ui/src/Logout.tsx
ui/src/shared/constants/index.ts

Redirect to logout page in cloud

---

ui/src/timeMachine/reducers/index.ts
ui/src/timeMachine/utils/queryBuilder.ts

Clear query when new bucket selected

---

testing/document.go

Fixed the recent unit testing broken

fix(kv): documents unit testing

---

ui/package-lock.json
ui/package.json
ui/src/me/components/Resources.tsx

chore(ui/account): remove token link

---

kv/document.go
testing/document.go

Closes https://github.com/influxdata/influxdb/issues/12860

fix(http): fix doc label not found error

---

cmd/influx/authorization.go
cmd/influx/bucket.go
cmd/influx/main.go
cmd/influx/organization.go
cmd/influx/user.go

Should use kv implementation.
The bolt implementation will be removed.

refactor(cmd): replace bolt.Client with kv.Service

---

http/swagger.yml

docs(http): add Document links

---

http/swagger.yml

docs(http): add Variable org link

---

ui/src/variables/utils/hydrateVars.test.ts

Wrap export variable test in `test` handler.

Fix(ui/exportVariables): wrap exportVariables in test

---

ui/package-lock.json
ui/src/shared/components/TimeRangeDropdown.tsx

Remove disable of time range dropdown when custom timerange selected

---

ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx

Need to return something in getDerivedStateFromProps even if theres no update

fix variables controll bar error

---

ui/src/shared/components/Legend.tsx

Fix runaway legend

---

CHANGELOG.md

Updating for alpha 7

---

ui/src/organizations/components/OrgTemplatesList.tsx
ui/src/templates/components/EmptyTemplatesList.tsx

Templates empty state should only have import option

---

tsdb/tsm1/engine.go

This change closes #10511 that manifests when a shard is considered cold
faster than its cache is snapshotted. Previously the code only looked at
the last modification of compacted tsm1 files. Instead the (restored)
Engine.lastModified() also takes the cache into account.
Ports #10522 to master where engine.go has moved and Engine.LastModified()
was deleted because it was unused.
1. Modify `tsdb/tsm1/config.go`: (I didn't find how to change these configuration options in v2.0; I just guess that's not implemented yet?)
* Set `DefaultCacheSnapshotMemorySize        = 64 * 1024   // 64KB`
* Set `DefaultCompactFullWriteColdDuration = time.Duration(30 * time.Second)`
2. Compile and start InfluxDB.
3. Setup via CLI: `$ ./bin/linux/influx setup -u test -p test -o test -b test -r 0 -f`
4. Write …

Fix compaction logic on infrequent cache snapshots

---

task/backend/task.go

Ensure requested at is only set when a task was manually requested

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12952

fix(http): swagger user password reset to 204

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12970

fix(http): swagger dashboard meta date-time

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12948

fix(http): addtional property of variable map

---

auth.go
authorizer/auth.go
authorizer/auth_test.go
bolt/authorization.go
cmd/influx/authorization.go
http/auth_service.go
http/auth_test.go
http/swagger.yml
inmem/auth_service.go
kv/auth.go
mock/auth_service.go
prometheus/auth_service.go
prometheus/auth_service_test.go
status.go
testing/auth.go
zap/auth_service.go

Closes https://github.com/influxdata/influxdb/issues/12938
update the authorization interface, replace the function SetAuthorizationStatus to UpdateAuthorization

feat(kv): add auth description update

---

ui/package-lock.json
ui/package.json
ui/src/organizations/components/Members.tsx

Update client to 0.2.54 and fix breaking changes

---

ui/src/configuration/components/ConfigurationPage.tsx
ui/src/organizations/components/OrganizationsIndexContents.tsx

Exclude links to non functioning areas in cloud

---

http/swagger.yml
http/variable_service.go
http/variable_test.go

feat(http): add labels to variables

---

http/swagger.yml

fix(http): start -> started in swagger

---

http/swagger.yml

fix(http): nest secret key response links in swagger

---

fs/proto.go
http/proto_test.go

fix(http/proto): return 404 if proto not found

---

ui/src/shared/components/notifications/Notification.tsx
ui/src/shared/components/notifications/Notifications.scss

Co-authored-by: Daniel Campbell <metalwhirlwind@gmail.com>
Closes #12029 

Update onboarding notification on step 2 to be not chopped

---

ui/src/Logout.tsx
ui/src/shared/constants/index.ts

Redirect to quartz logout in cloud

---

cmd/influxd/launcher/launcher.go
task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go
task/mock/scheduler.go

Update task coordinator to act as a TaskService middleware

---

pkg/tlsconfig/tls_config.go

tls: fix incorrect tls1.0 version mapping

---

cmd/influx/cli/cli.go
cmd/influx/cli/flux.go
flux/client/http.go

Back port: Ensure credentials are passed for Flux queries when using influx command

---

ui/src/index.tsx
ui/src/shared/containers/GetOrganizations.tsx
ui/src/shared/containers/SetOrg.tsx

Add SetOrg intermediary component to set org

---

cmd/influxd/launcher/launcher.go
task/backend/executor/executor.go
task/backend/executor/executor_test.go

Update task executor to use a TaskService

---

ui/cypress/e2e/dashboardsIndex.test.ts
ui/src/configuration/components/Labels.tsx
ui/src/dashboards/actions/index.ts
ui/src/dashboards/apis/index.ts
ui/src/dashboards/components/VEO.tsx
ui/src/dashboards/components/dashboard_index/DashboardCard.tsx
ui/src/dashboards/components/dashboard_index/DashboardCards.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndexContents.tsx
ui/src/dashboards/components/dashboard_index/Table.tsx
ui/src/labels/actions/index.ts
ui/src/organizations/components/CollectorRow.tsx
ui/src/organizations/components/Dashboards.tsx
ui/src/tasks/components/TaskCard.tsx

feat(ui): make dashboards pages org centric

---

services/httpd/handler.go
services/httpd/handler_test.go

Fix security vulnerability when shared secret is blank

---

ui/src/shared/utils/resourceToTemplate.test.ts
ui/src/variables/actions/index.ts
ui/src/variables/utils/exportVariables.ts

Closes #13044 
This verifies variable relationships are templated as expected and fixes an issue where an exported  variable was included in it's own variable relationships.

fix(ui/var/relationships): add tests for vars exports

---

ui/src/dashboards/actions/index.ts

Fix failing test

---

ui/package-lock.json
ui/src/pageLayout/containers/Nav.tsx

Remove tokens link

---

http/swagger.yml
http/variable_test.go
variable.go

Closes #12833
This PR adds the `description` property to the Variable object on the server side.

chore(variables): add description property to Variable struct

---

bolt/bucket.go
http/bucket_service.go
inmem/bucket_service.go
kv/bucket.go
testing/bucket_service.go

Closes https://github.com/influxdata/influxdb/issues/12713

fix(kv): fix bucket not found by name

---

ui/src/authorizations/containers/TokensIndex.tsx
ui/src/buckets/containers/BucketsIndex.tsx
ui/src/organizations/containers/OrgDashboardsIndex.tsx
ui/src/organizations/containers/OrgHeader.tsx
ui/src/organizations/containers/OrgMembersIndex.tsx
ui/src/organizations/containers/OrgScrapersIndex.tsx
ui/src/organizations/containers/OrgTasksIndex.tsx
ui/src/organizations/containers/OrgTelegrafsIndex.tsx
ui/src/organizations/containers/OrgTemplatesIndex.tsx
ui/src/organizations/containers/OrgVariablesIndex.tsx

Closes part of #13063 
Add org name to org header, remove ability to rename org from org header

Org Header receives org name from redux

---

ui/src/index.tsx
ui/src/localStorage.ts
ui/src/mockState.tsx
ui/src/onboarding/containers/OnboardingWizard.tsx
ui/src/shared/containers/RouteToOrg.tsx
ui/src/shared/containers/SetOrg.tsx
ui/src/types/localStorage.ts

feat(ui): store orgID in local storage

---

http/swagger.yml

Update swagger endpoints to include orgID parameters

---

CHANGELOG.md
ui/package-lock.json
ui/package.json
ui/src/configuration/components/CreateVariableOverlay.tsx
ui/src/configuration/components/Variables.tsx
ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx
ui/src/dataExplorer/components/SaveAsVariable.tsx
ui/src/organizations/components/CreateVariableOverlay.tsx
ui/src/organizations/components/UpdateVariableOverlay.tsx
ui/src/organizations/components/VariableList.tsx
ui/src/organizations/components/VariableRow.tsx
ui/src/organizations/components/Variables.tsx
ui/src/organizations/components/__snapshots__/Variables.test.tsx.snap
ui/src/shared/copy/v2/notifications.ts
ui/src/shared/utils/filterUnusedVars.ts
ui/src/shared/utils/resourceToTemplate.test.ts
ui/src/shared/utils/resourceToTemplate.ts
ui/src/templates/utils/index.ts
ui/src/timeMachine/components/variableToolbar/FetchVariables.tsx
ui/src/timeMachine/components/variableToolbar/VariableItem.tsx
ui/src/timeMachine/components/variableToolbar/VariableToolbar.tsx
ui/src/types/templates.ts
ui/src/variables/actions/index.ts
ui/src/variables/mocks/index.ts
ui/src/variables/reducers/index.ts
ui/src/variables/selectors/index.tsx
ui/src/variables/utils/exportVariables.ts
ui/src/variables/utils/hydrateVars.test.ts
ui/src/variables/utils/hydrateVars.ts

Closes #12932 
Co-authoerd-by: Delmer Reed <delmer814@gmail.com>
Add inline labels on Variables
Add actions to variables to add labels and remove labels
Add filtering on labels
Add notifications for failed to add/remove labels

Add the ability to add labels on variables

---

ui/src/tasks/actions/index.ts
ui/src/tasks/components/TaskRunsPage.tsx

Add task name to Tasks Runs page

---

tsdb/index/inmem/meta.go
tsdb/index/inmem/meta_test.go

Add nil check for tagKeyValueEntry.setIDs()

---

ui/package-lock.json
ui/package.json
ui/src/labels/actions/index.ts
ui/src/organizations/containers/OrgScrapersIndex.tsx
ui/src/scrapers/actions/index.ts
ui/src/shared/components/FetchLabels.tsx
ui/src/templates/api/index.ts

now that everything is scoped under an org getting a list of resources requires a orgID to scope under.

Update client to now allow org ids

---

ui/package-lock.json
ui/package.json

Move influx dependency to github branch

---

prometheus/converters.go
services/httpd/handler.go
services/httpd/handler_test.go

Drop all unsupported Prometheus values written to the remote write endpoint

---

ui/src/tasks/components/TaskRunsPage.tsx

Add the ability to edit a task from tasks runs page

---

task/servicetest/servicetest.go

tests for https://github.com/influxdata/idpe/pull/3058

chore(tasks): more task tests

---

ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/me/components/DashboardsList.tsx
ui/src/me/components/Resources.tsx

Remove organizations section in landing page. 
Move dashboards links to org context

Fix links on landing page

---

pkg/rhh/rhh.go
storage/config.go
storage/engine.go
tsdb/config.go
tsdb/series_file.go
tsdb/series_index.go
tsdb/series_partition.go
tsdb/series_partition_test.go
tsdb/tsm1/config.go

Reapplying https://github.com/influxdata/platform/pull/1599 to `influxdb` repo.

Improve bulk series file writes.

---

ui/src/pageLayout/containers/Nav.tsx

Add the feedback button to left  Nav bar

---

ui/src/shared/components/PageTitleWithOrg.tsx

stop capitalizing org name in page title

---

task/backend/executor/executor.go

fix(task): fix go fmt failure

---

http/swagger.yml

docs(http): remove view link from api links

---

http/swagger.yml

docs(http): remove unused Views schema

---

ui/src/me/components/UserPageHeader.tsx
ui/src/me/containers/MePage.tsx

feat(ui): Add org name to home page title

---

ui/src/organizations/actions/orgs.ts
ui/src/organizations/components/CreateOrgOverlay.tsx

feat(ui): Create new bucket when creating new org

---

ui/src/dashboards/components/dashboard_index/Table.tsx
ui/src/tasks/components/TasksList.tsx
ui/src/tasks/components/__snapshots__/TasksList.test.tsx.snap

Remove owner from sortKeys

---

task/backend/coordinator/coordinator.go
task/backend/coordinator/coordinator_test.go

Allow coordinator to skip task claiming in startup

---

ui/Makefile
ui/src/dashboards/apis/index.ts
ui/src/dashboards/apis/v2/index.ts
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/organizations/components/Dashboards.tsx

Closes #13259 
Provide orgID when cloning dashboards and resolve linting errors.

fix(ui/dash.clone): add orgID to clone

---

kv/service.go
kv/task.go
kv/task_test.go
task.go
task/servicetest/servicetest.go
task_test.go

build kv based TaskService

---

ui/src/dataExplorer/components/SaveAsCellForm.tsx
ui/src/dataExplorer/components/SaveAsTaskForm.tsx

Closes #12505
Updates save as cell to create new dashboard in the current org

feat(ui): Make data explorer org centric

---

ui/src/dashboards/components/variablesControlBar/VariableDropdown.scss
ui/src/shared/components/columns_options/ColumnsOptions.scss

Update cursor to grab over draggable areas

---

http/document_service.go
http/document_test.go
http/label_service.go
http/swagger.yml
label.go

Closes https://github.com/influxdata/influxdb/issues/12937

feat(http): add document labe handler

---

ui/src/dashboards/components/NoteEditorOverlay.tsx

Ensure note is loaded in note editor after refresh

---

ui/src/tasks/actions/index.ts

Update duration to display in seconds instead of milliseconds

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12718

fix(http): swagger add get target by id

---

ui/src/shared/copy/notifications.ts
ui/src/templates/actions/index.ts
ui/src/templates/components/TemplateCard.tsx

Closes #12925 
Adds a create resource button to the templates page
Awaiting updates from client to fix linting errors: https://github.com/influxdata/influxdb2-js/pull/93

Create resource from template button

---

bolt/label.go
document.go
http/document_service.go
http/document_test.go
http/label_test.go
http/swagger.yml
inmem/label_service.go
kv/document.go
kv/label.go
label.go
testing/document.go
testing/label_service.go
testing/util.go

Closes https://github.com/influxdata/influxdb/issues/12973
Closes https://github.com/influxdata/influxdb/issues/13317

feat(http): accept label id for template post

---

services/httpd/handler.go

Backport https://github.com/influxdata/influxdb/pull/10617 to 1.7

fix #10595: fix panic in Prometheus read API

---

http/dashboard_service.go

Closes https://github.com/influxdata/influxdb/issues/11254
quick fix for the master blocking issue

fix(http): fix go vet issue

---

storage/engine_schema.go

Stub implementation of storage schema APIs

---

api-compat.Jenkinsfile

Update which image is used during the build operations.

chore(Jenkins): Update Golang build container to 1.12

---

ui/package-lock.json
ui/src/dataExplorer/components/SaveAsTaskForm.tsx
ui/src/utils/taskOptionsToFluxScript.ts

Pass org to save as task script builder

---

ui/src/pageLayout/components/AccountNavSubItem.tsx

Closes #13348 
Issue is caused by dapperscrollbars. Removed from the release.

Fix sidenav menu closing when switching orgs

---

kv/document.go
testing/document.go

fix(http): return an empty list of labels if not found

---

bolt/dashboard.go
dashboard.go
dashboard_test.go
http/dashboard_service.go
http/swagger.yml
inmem/dashboard.go
kv/dashboard.go
testing/dashboards.go

fix(http): remove viewID

---

auth.go
bolt/authorization.go
http/auth_service.go
http/swagger.yml
inmem/auth_service.go
kv/auth.go
testing/auth.go

feat(http): find auths by org

---

http/swagger.yml

docs(http): remove view id

---

query/stdlib/testing/end_to_end_test.go

test(stdlib): skip flaky range test

---

ui/src/dataExplorer/components/DataExplorer.tsx
ui/src/dataExplorer/components/DataExplorerPage.tsx
ui/src/dataExplorer/components/SaveAsVariable.tsx
ui/src/variables/components/CreateVariableOverlay.tsx
ui/src/variables/components/VariableForm.tsx
ui/src/variables/utils/validation.ts

Closes #13297 
Add a variables uniqueness validation to the variable creation form.

feat(ui/variables): add name validation to overlay

---

ui/package-lock.json
ui/src/authorizations/actions/index.ts
ui/src/tasks/actions/index.ts

Incorporate getAll changes in tasks and auths from client

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/VEOContents.tsx
ui/src/shared/components/RefreshingView.tsx
ui/src/shared/components/RefreshingViewSwitcher.tsx
ui/src/shared/components/VisTableTransform.tsx
ui/src/timeMachine/selectors/index.ts

Closes #13407
Ensure that a histogram has valid `xColumn` and `fillColumn` settings when it is saved.

 Ensure column selections are saved with histograms

---

ui/src/pageLayout/containers/Nav.tsx

Closes #3151 https://github.com/influxdata/idpe/issues/3151

Put feedback nav item below the cloud nav item

---

document.go
http/document_test.go
http/swagger.yml
testing/document.go

Closes https://github.com/influxdata/influxdb/issues/13333
add doc meta type

feat(influxdb): add doc meta type

---

CHANGELOG.md

- CHANGELOG updated for v1.7.6 release.
Closes #

chore(doc): Update CHANGELOG

---

kv/task.go
kv/task_test.go
task.go
task/backend/analytical_storage.go
task/backend/analytical_storage_test.go
task/backend/point_logwriter.go
task/servicetest/servicetest.go
ui/package-lock.json

Create an analytical storage middleware layer

---

CHANGELOG.md
ui/src/index.tsx
ui/src/organizations/actions/orgs.ts
ui/src/organizations/components/EditOrgConfirmationForm.tsx
ui/src/organizations/components/EditOrgProfileOverlay.tsx
ui/src/organizations/components/OrgProfileTab.tsx
ui/src/organizations/components/RenameOrgForm.tsx
ui/src/organizations/containers/OrgProfilePage.tsx
ui/src/organizations/reducers/orgs.ts
ui/src/settings/components/SettingsNavigation.tsx
ui/src/shared/copy/v2/notifications.ts

feat(ui): Add ability to rename org

---

errors.go
http/errors.go
http/swagger.yml

chore(http): add 429 response to errors

---

README.md

Adding a tool dependency install note

---

ui/src/dashboards/components/DashboardPage.tsx

Fix autorefresh icon always showing pause

---

ui/src/variables/components/UpdateVariableOverlay.tsx

Allows renaming changes not to be lost when changing variable type.

fix(ui/var/rename): resolve naming when changing types

---

http/swagger.yml

fix(http): remove incorrect param from labels post

---

ui/src/me/components/Resources.tsx

Closes #13239 
Remove this link until the API supports updating users again

Remove Profile Link

---

kv/task.go
task/backend/scheduler.go
task/backend/scheduler_test.go
task/mock/task_control_service.go
task/servicetest/servicetest.go

fix task limit in kv and add tests Also fix a minor race condition in task scheduler

---

ui/src/index.tsx
ui/src/variables/components/RenameVariableForm.tsx
ui/src/variables/components/RenameVariableOverlay.tsx
ui/src/variables/components/UpdateVariableOverlay.tsx
ui/src/variables/components/VariableList.tsx
ui/src/variables/components/VariableRow.tsx
ui/src/variables/components/__snapshots__/Variables.test.tsx.snap
ui/src/variables/utils/validation.ts

Closes #13496 
Closes #13507 
Update variables to use a danger zone for renaming and adds validations for reserved variable names.

feat(ui/variables/rename): add danger zone to rename

---

services/httpd/response_writer.go
services/httpd/response_writer_test.go

fixes https://github.com/influxdata/EAR/issues/786

Fix csv decoder bug where empty tag values cause an array index panic

---

storage/reads/merge.go
storage/reads/merge_test.go
storage/reads/string_iterator_reader_test.go
storage/reads/string_iterator_writer_test.go

Merge stats with StringIterator.
Helps https://github.com/influxdata/idpe/issues/3198

chore(storage): Merge StringIterator cursor stats

---

ui/cypress/e2e/collectors.test.ts
ui/src/telegrafs/components/CollectorCard.tsx
ui/src/telegrafs/components/CollectorList.tsx
ui/src/telegrafs/components/__snapshots__/Collectors.test.tsx.snap

Update telegraf list to use ResourceList

---

http/swagger.yml

docs(http): add missing Zap-Trace-Span header

---

http/swagger.yml

docs(http): add oplog user

---

bolt/bucket.go
bucket.go
http/bucket_service.go
http/swagger.yml
inmem/bucket_service.go
kv/bucket.go
testing/bucket_service.go

Closes https://github.com/influxdata/influxdb/issues/13474
add bucket description, update tests, swagger
@russorat Do we want to add this to the cli as well?

feat(influxdb): add bucket desc

---

ui/src/cloud/actions/limits.ts
ui/src/cloud/apis/limits.ts
ui/src/cloud/components/GetAssetLimits.tsx
ui/src/cloud/reducers/limits.ts
ui/src/cloud/utils/limits.ts
ui/src/dashboards/actions/index.ts
ui/src/dashboards/apis/index.ts
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndexContents.tsx
ui/src/shared/components/AddResourceDropdown.tsx
ui/src/shared/copy/notifications.ts
ui/src/store/configureStore.ts
ui/src/types/stores.ts

Add rate limiting to dashboard asset

---

http/swagger.yml
organization.go
testing/organization_service.go

Closes https://github.com/influxdata/influxdb/issues/13478
add org desc

feat(influxdb): add org desc

---

document.go
http/document_test.go
http/swagger.yml
testing/document.go

Closes https://github.com/influxdata/influxdb/issues/13487
add description in the meta

feat(influxdb): add doc description

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12771

fix(http): swagger define security schemes

---

http/swagger.yml

Closes https://github.com/influxdata/influxdb/issues/12721

fix(http): fix telegraf get default swagger

---

ui/src/tasks/components/TaskRunsList.tsx
ui/src/tasks/components/TaskRunsPage.tsx

Closes #13607 
Updated TaskRunsPage and TaskRunsList component to use the sorting similar to other resource lists

Update task runs list to sort

---

models/points.go
models/points_test.go
models/tagkeysset.go
models/tagkeysset_test.go
storage/engine_schema.go
storage/readservice/store.go
tsdb/cursors/string.go
tsdb/tsm1/engine_schema.go
tsdb/tsm1/engine_schema_test.go
tsdb/tsm1/reader_range_iterator.go
tsdb/tsm1/reader_range_iterator_test.go

Provide an implementation of the `TagKeys` API
Closes #13377
----
Last commit implements statistics for billing. Closes #13541

Implementation of storage schema TagKeys API

---

ui/src/dataLoaders/components/lineProtocolWizard/LineProtocolWizard.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/LineProtocol.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/LineProtocolTabs.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/PrecisionDropdown.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/TabBody.tsx
ui/src/dataLoaders/components/lineProtocolWizard/configure/__snapshots__/LineProtocol.test.tsx.snap
ui/src/dataLoaders/components/lineProtocolWizard/configure/__snapshots__/LineProtocolTabs.test.tsx.snap
ui/src/onboarding/OnboardingWizard.scss

Closes #13616 #13597 #13598 
Moved precision dropdown from footer to top of the line protocol body
Updated Line protocol to not proceed to next step automatically when file is uploaded
Updated styling for line protocol
Before:
After:

Fix line protocol bugs with upload and styling

---

http/swagger.yml

fix(http): update bucket swagger to reflect recent changes

---

ui/src/telegrafs/components/CollectorCard.tsx
ui/src/telegrafs/components/CollectorList.tsx
ui/src/telegrafs/components/Collectors.tsx
ui/src/telegrafs/components/__snapshots__/Collectors.test.tsx.snap

Update telegraf config setup instructions to use Link

---

http/swagger.yml

fix(http): make org & orgID optional

---

authorizer/scraper.go
authorizer/scraper_test.go
bolt/scraper.go
bolt/scraper_test.go
gather/scheduler.go
gather/scraper_test.go
http/api_handler.go
http/scraper_service.go
http/scraper_service_test.go
http/swagger.yml
inmem/scraper.go
inmem/scraper_test.go
kv/scrapers.go
kv/scrapers_test.go
mock/scraper_service.go
scraper.go
testing/scraper_target.go

Closes https://github.com/influxdata/influxdb/issues/13189
Closes https://github.com/influxdata/influxdb/issues/13433
Closes https://github.com/influxdata/influxdb/issues/13573

feat(influxdb): add scraper filter

---

ui/src/buckets/actions/index.ts
ui/src/buckets/components/BucketsTab.tsx
ui/src/buckets/containers/BucketsIndex.tsx
ui/src/cloud/actions/limits.ts
ui/src/cloud/components/AssetLimitAlert.tsx
ui/src/cloud/reducers/limits.ts
ui/src/cloud/utils/limits.ts
ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/shared/components/AddResourceDropdown.tsx
ui/src/shared/components/TimeSeries.tsx
ui/src/shared/copy/notifications.ts
ui/src/tasks/actions/index.ts
ui/src/tasks/components/TasksHeader.tsx
ui/src/tasks/components/TasksList.test.tsx
ui/src/tasks/components/TasksList.tsx
ui/src/tasks/containers/TasksPage.tsx
ui/src/timeMachine/actions/queries.ts

Closes #13421 for buckets and tasks

Buckets tasks limits

---

cmd/influxd/launcher/launcher.go

fix(query): remove per-query memory limit from OSS

---

ui/mocks/dummyData.ts
ui/src/authorizations/components/ViewTokenOverlay.test.tsx
ui/src/authorizations/components/ViewTokenOverlay.tsx
ui/src/authorizations/components/__snapshots__/ViewTokenOverlay.test.tsx.snap
ui/src/utils/permissions.ts

Closes #13633 
The reduce function to create the object with keys and values to display the permissions was not adding actions correctly. Updated the reduce function and created the test for it in any case if changed in future, it will fail if not meeting the expected values for permissions.

Fix permissions on view token overlay

---

ui/src/shared/components/notifications/Notification.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/reducers/notifications.test.ts
ui/src/shared/reducers/notifications.ts
ui/src/types/notifications.ts

Add notification type to notifications and prevent re-publishing same notification

---

http/document_service.go

fix document service panic

---

ui/src/me/components/LogoutButton.tsx

fix(ui): duplicate logout buttons

---

http/router.go
logger/style_guide.md

When printing out a stacktrace with a logged error message, it is better
to set the `Stack` property on the entry than to include it as a string
within the context fields. It is also better than using `zap.Stack()`
too.
This is because certain encoders will perform a pretty print of the
stacktrace. The default zap-logfmt will read this property and include
it as a field so this code is identical when using that encoder, but the
console encoder, which is commonly used in local development because it
is automatically used with a TTY available, will print out a newline and
pretty print the stacktrace if it is included on the entry itself.

feat(http): pretty stack trace for the http panic recovery handler

---

ui/package-lock.json
ui/src/tasks/actions/index.ts

fix(ui): task update

---

ui/src/cloud/constants/index.ts
ui/src/cloud/utils/limits.ts
ui/src/dataLoaders/actions/dataLoaders.ts
ui/src/shared/components/EmptyGraphError.tsx
ui/src/shared/components/RefreshingView.tsx
ui/src/shared/components/TimeSeries.tsx
ui/src/shared/components/cells/Cell.scss
ui/src/shared/constants/errors.ts
ui/src/timeMachine/actions/queries.ts

When limit error  occurs, display the error text in cells, also wrap the error texts that appear in cells.

Display Limit Errors in cells and wrap error texts. 

---

ui/src/scrapers/components/CreateScraperForm.tsx
ui/src/scrapers/components/CreateScraperOverlay.tsx

Update scraper create overlay to create scraper on enter

---

bolt/organization.go
http/org_service.go
inmem/organization_service.go
kv/org.go
organization.go
storage/bucket_service_test.go
testing/organization_service.go

Closes https://github.com/influxdata/idpe/issues/2871
fixed the error, add more tests

fix(kv): fix empty org name

---

http/org_service.go

Closes https://github.com/influxdata/influxdb/issues/10802
fix error

fix(http): fix delete bad org id

---

tsdb/tsm1/batch_string.go
tsdb/tsm1/batch_string_test.go

Don't panic when encoding string blocks and length of source slice is too large

---

task/backend/scheduler.go
task/backend/scheduler_test.go

Closes #
Fix the task scheduler so it will no longer work tasks that are inactive.

Fix inactive task scheduling

---

ui/src/dataExplorer/components/SaveAsCellForm.tsx

Closes #13733
See issue for more context.

fix(ui): fix issue saving histograms via Data the Explorer

---

ui/src/shared/utils/resourceToTemplate.test.ts
ui/src/shared/utils/resourceToTemplate.ts

Sanitize query builderConfigs before exporting dashboards

---

ui/package-lock.json
ui/package.json

Pin client version to 0.3.3

---

CHANGELOG.md

updating changelog for alpha-9

---

CHANGELOG.md

adding section for alpha 10

---

CHANGELOG.md
ui/src/templates/constants/defaultTemplates.ts

remove telegraf bucket name from getting started with flux template

---

query/stdlib/testing/end_to_end_test.go

test(flux/e2e): skip flaky window_generate_empty test

---

ui/src/cloud/constants/index.ts
ui/src/cloud/utils/limits.ts

Return asset limit error when asset limits have been reached

Differentiate between asset limit errors and rate limit errors

---

ui/src/shared/copy/notifications.ts
ui/src/tasks/actions/index.ts

Update task run to not display NaN seconds

---

http/query_handler.go
http/query_handler_test.go

Like https://github.com/influxdata/influxdb/pull/13655, but in a different handler.

fix(http): use influxdb.Error in FluxHandler

---

ui/src/variables/components/RenameVariableForm.tsx
ui/src/variables/components/VariableRow.tsx

Closes #13777 #13778 
Remove overlay from the VariableForm
Update Variable Row to use the argument type instead of hard coded `Query`

Update variable rename overlay and argument type

---

ui/src/members/components/MemberRow.tsx
ui/src/pageLayout/components/CloudNav.tsx

Remove delete user from cloud

---

ui/cypress/e2e/dashboardsIndex.test.ts
ui/cypress/e2e/tasks.test.ts
ui/cypress/e2e/variables.test.ts
ui/src/buckets/components/BucketsTab.tsx
ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/dashboards/components/dashboard_index/Table.tsx
ui/src/shared/components/AddResourceDropdown.tsx
ui/src/tasks/components/TasksHeader.tsx

Fix dropdowns in limited status

---

ui/src/buckets/components/BucketOverlayForm.tsx

chore(ui/buckets): change update rp copy

---

ui/src/dataLoaders/components/verifyStep/DataListening.tsx
ui/src/shared/apis/query.ts
ui/src/shared/components/TimeSeries.tsx
ui/src/timeMachine/actions/queries.ts
ui/src/timeMachine/apis/queryBuilder.ts
ui/src/variables/utils/ValueFetcher.ts

Use streaming interface from client library

---

ui/src/buckets/actions/index.ts
ui/src/cloud/actions/limits.ts
ui/src/organizations/actions/orgs.ts
ui/src/shared/copy/notifications.ts
ui/src/utils/api.ts

Closes #
Update bucket create and update to show errors that are caught from backend

Update buckets notifications to display error from backend

---

ui/package-lock.json
ui/package.json

Bump client version

---

task/backend/scheduler.go

fix(task): fix metrics for tasks currently running tasks

---

CHANGELOG.md
ui/src/dashboards/components/DashboardHeader.tsx
ui/src/dashboards/components/variablesControlBar/DraggableDropdown.tsx
ui/src/dashboards/components/variablesControlBar/VariableDropdown.scss
ui/src/dashboards/components/variablesControlBar/VariablesControlBar.scss

- Variable Dropdowns can only be dragged from the hamburger icon
- Change appearance of dropdowns to match theme of feature (purple)
- Make variable control bar toggle purple to match theme of feature
- Change dragging placeholder to match style of cell dragging placeholder

Polish Variable Dropdowns
