influxdata/influxdb

circle.yml, coordinator/statement_executor.go, internal/tsdb_store.go, tests/server_delete_test.go, tests/server_helpers.go, tests/server_suite.go, tests/server_test.go, tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_test.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/meta.go, tsdb/index/tsi1/file_set.go, tsdb/index/tsi1/file_set_test.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/index_file.go, tsdb/index/tsi1/index_files.go, tsdb/index/tsi1/index_test.go, tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/measurement_block.go, tsdb/index/tsi1/partition.go, tsdb/index/tsi1/tsi1_test.go, tsdb/series_set.go, tsdb/series_set_test.go, tsdb/shard.go, tsdb/shard_test.go, tsdb/store.go, tsdb/store_test.go
This PR addresses #9299.
This PR implements the correct `DROP`/`DELETE` semantics in both the `tsi1` and `inmem` indexes. These semantics are:
- When deleting series data using the `DROP` keyword, all series data for all time periods is removed from both the `tsm` engine and the index.
- When deleting series data using the `DELETE` keyword, series data is removed from the `tsm` data in the relevant shards. Further, if the deleted `tsm` data contained the only remaining occurrences of data (across _any_ shard) for a given series, then that series is also removed from the index.
As discussed in more detail in #9299, the two indexes behave differently, requiring a different implementation for each. The `inmem` index is shared across all shards, while the `tsi1` index is shard-local.
For the …
=> Implement DROP/DELETE semantics in indexes

pkg/escape/bytes.go, pkg/escape/bytes_test.go
Preallocating the capacity of the output is faster and uses less memory than letting append() do its own (over)allocation. 
Benchmarking shows that this is ~42% faster than the original. The benchmark used is here: https://gist.github.com/mjs/bc3219a79d4e4a1d7848c5aaa12b3c40. The results on my machine are:
```
BenchmarkOrig-4   	20000000	        85.1 ns/op
BenchmarkNew-4    	30000000	        49.4 ns/op
```
=> pkg/escape: Preallocate output in Unescape

tests/server_delete_test.go, tsdb/index.go, tsdb/store.go
#9308 prevents the series file from being closed when in use.
However, because the reference counting was implemented via
mutexes, it was possible to double `RLock` the series file mutex. This
allows a `Lock` to arrive in-between the two `RLock`s, (such as when
deleting the database), causing deadlock.
This PR addresses this by ensuring that from within `IndexSet`
methods, when calling other `IndexSet` methods, that they're all
unexported, and that those unexported methods never take a lock on the
series file.
Keeping series file locking in exported `IndexSet` methods only, allows
one to see any future races more easily.
=> Ensure no double Rlocking occurs in IndexSet

tests/server_delete_test.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/meta.go, tsdb/index/inmem/meta_test.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/index_files.go, tsdb/index/tsi1/partition.go, tsdb/series_set.go, tsdb/shard.go, tsdb/store.go
This PR relies on #9315. I will rebase this, once that is merged.
This PR cleans up the `inmem` index by removing all methods and data structures associated with shard assignment/unassignment.
Now that each shard-local index is maintaining a bitset of series ids, tracking the series present in the local shard's tsm engine, there is no need to track shards in the `inmem` index.
It also removes the `Shard.CloseFast` method, as all shard closes should be "fast".
=> Cleanup Shard assignment/unassignment 

tsdb/series_set.go, tsdb/shard.go, tsdb/store.go, tsdb/store_test.go
This PR builds on #9315  and #9316; they should be merged first.
The only commit directly relevant to this PR is https://github.com/influxdata/influxdb/commit/2bb0b79b0da6c8e4411b49b95711eb124d20462c.
Series should only be removed from the series file when they're no
longer present in any shard. This commit ensures that during a shard
rollover, the series local to the shard are checked against all other
series in the database.
Series that are no longer present in any other shards' bitsets, are then
marked as deleted in the series file.
=> Remove series when shard rolls over

tsdb/engine/tsm1/engine.go, tsdb/shard.go, tsdb/shard_test.go
If the fields.idx was corrupted in someway, it would cause the shard
to fail to load.  Deleting the file will allow it to be rebuilt.
This change handles this automatically so it's rebuilt if necessary
without user intervention.
=> Rebuild corrupted fields index when necessary

tsdb/series_set_test.go, tsdb/store.go, tsdb/store_test.go
Prior to this, the series file was being used (more precisely, the series file index) to determine series cardinality in a database. This isn't accurate if a series file index has not been compacted for a while.
We now switch to using the bitsets of series ids that we have to maintain within each shard to determine cardinality.
The `_internal` database requests these cardinalities every 10 seconds, so I was concerned about performance of unioning these bitsets constantly, but upon benchmarking it appears that even unioning 1B spread across 100 shards would take only a millisecond or so on a laptop.
=> Use bitsets to calculate series cardinality

tsdb/index/tsi1/log_file.go
`binary.Uvarint()` returns a zero length when it fails that was not being checked before so it could get to the end of the entry and cause a checksum error instead of a `io.ErrShortBuffer`.
=> Fix LogEntry.UnmarshalBinary() short buffer check.

query/query_executor.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/meta.go
We were seeing problems with `SHOW MEASUREMENTS` being slow. I inserted 20 measurements with a couple of million series and was seeing `SHOW MEASUREMENTS` taking `~600ms`. A torch graph showed we were diving into iterators that get all series and sort them for a measurement.
In the end it turned out we were not short-circuiting the FGA auth check due to a missed check on the `auth` variable. 
I have unified that approach—methods that take an `auth` should now just always call `query.AuthorizerIsOpen` to determine if an authorizer can be short-circuited.
The new time for `SHOW MEASUREMENTS` is `~800 µs`, which in this case is 600x faster 😂 
It also shows that for a couple of million series we seems to have a fixed cost of `600ms` to initialise a series id iterator. We should investigate …
=> Unify approach to short-circuit auth

tsdb/engine/tsm1/engine.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/index_test.go, tsdb/index/tsi1/partition.go, tsdb/series_set.go
This speeds up deletes by separating the series deletes from the measurement delete.  There was a lot of time spent checking if a measurement still had any series.  Since series are delete one at a time, we ended up checking the measurement N times as well.
Instead, this now deletes each series and keeps track of the measurement involved and drops those measurements (if possible), at the end.  So instead of N (drop series) + N (measurement checks), it is now N (drop series) + 1 (measurement checks)
Dropping 32m series improved from 75m to 12m.  And dropping 100m took 62m.
=> Speed up deletes for tsi

CHANGELOG.md, tsdb/engine/tsm1/engine_test.go, tsdb/engine/tsm1/wal.go
The current behavior with the WAL code causes the `LastModified` time of a shard to incorrectly be reported as the modified time of the most recent WAL segment. Due to some other behavior in the WAL, that could be as recent as the last time the server started up, even if the shard hasn't seen writes in weeks or months prior to that.
=> wal: update lastWriteTime behavior

tsdb/index/tsi1/index_test.go, tsdb/series_file.go, tsdb/series_partition.go
This reworks the series ID allocation to prevent an overflow issue.
=> Use full 32bits for series IDs

tsdb/index/tsi1/index_file.go, tsdb/index/tsi1/index_file_test.go
If all the series in a measurement were tombstones, MeasurementHasSeries
would return true because the ok var was re-used from a prior check
earlier in the func.  This caused it to be true all the time unless
the measurment was actually tombstoned.
=> Fix MeasurementHasSeries returning incorrect value

tsdb/engine/tsm1/engine.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go, tsdb/series_file.go, tsdb/series_partition.go
This adds the capability to disable TSI and SeriesFile compactions.  Disabling them prevents new compactions from starting, but does not end any in-progress.  This fixes deleting w/ TSI where a TSI/SeriesFile compaction would run while deleting causing deleted data to re-appear.
This also disables the compactions (like TSM) when deleting series.
=> TSI/SeriesFile Compaction Disabling

CHANGELOG.md, tcp/mux.go
This fixes two data races around concurrent calls to (*tcp.Mux).Close
and (*tcp.Mux).handleConn, discovered in Enterprise test suites.
=> Fix data races in tcp.Mux and tcp.listener

CHANGELOG.md, services/httpd/response_writer.go, services/httpd/response_writer_test.go
Got the below panic from my client when it tried to do an invalid query. The problem and fix is obvious, so putting up a PR.
```
[panic:runtime error: invalid memory address or nil pointer dereference] goroutine 25614 [running]:
runtime/debug.Stack(0xc42068b420, 0xc420108600, 0xbe91793e8d120376)
/usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc42068b420, 0xc420108600, 0xbe91793e8d120376, 0x55582cbe9a, 0x12f00c0, 0xc4201f8a50, 0x12a57a0, 0xc421ab27e0)
/tmp/.gdm_32513/src/github.com/influxdata/influxdb/services/httpd/handler.go:1537 +0xcd
panic(0xccd700, 0x12dc3b0)
/usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/influxdata/influxdb/services/httpd.(*msgpackFormatter).WriteResponse(0xc421b214e0, 0x0, 0x0, 0x0, …
```
=> fix nil err panic in httpd WriteResponse

CHANGELOG.md, services/httpd/response_writer.go, services/httpd/response_writer_test.go
=> fix nil err panic in msgpack httpd WriteResponse

client/v2/client.go
Just fixing a few typos, no functional change.
=> Fix typos in variable name, comment

tsdb/index/inmem/inmem.go, tsdb/index/tsi1/index.go, tsdb/shard_test.go, tsdb/store_test.go
Fixes #9372.
In the case of the `inmem` index, we can expose shard-level cardinality by using the series bitset that's stored on the `ShardIndex` shim.
In the case of the `tsi1` index, we can do the same using the union of all the partition bitsets.
=> Ensure shard-level  cardinality correct

cmd/influx_inspect/buildtsi/buildtsi.go, cmd/influx_inspect/help/help.go, cmd/influx_inspect/main.go
Renames the `inmem2tsi` tool to `buildtsi`. Updates to work against the entire system with database, retention policy, & shard filters.
```sh
$ influx_inspect buildtsi -datadir ~/.influxdb/data -waldir ~/.influxdb/wal
```
```sh
$ influx_inspect buildtsi -datadir ~/.influxdb/data -waldir ~/.influxdb/wal -database db0
```
```sh
$ influx_inspect buildtsi -datadir ~/.influxdb/data -waldir ~/.influxdb/wal -database db0 -retention autogen
```
```sh
$ influx_inspect buildtsi -datadir ~/.influxdb/data -waldir ~/.influxdb/wal -database db0 -retention autogen -shard 123
```
=> Refactoring 'buildtsi' command.

cmd/influxd/backup/backup.go, cmd/influxd/restore/restore.go
looks like a lot, just removed some tabs and fixed some bad line breaks.
=> Removed tabs from help text  for backup/restore

pkg/mmap/mmap_unix.go, pkg/rhh/rhh.go, tsdb/engine/tsm1/mmap_unix.go, tsdb/engine/tsm1/mmap_windows.go, tsdb/engine/tsm1/reader.go, tsdb/index/tsi1/log_file.go
This fixes a few performance issues I was seeing with series creation.
* There was lock contention on the series file when `LogFile.execSeriesEntry` was run.  We already had the parsed series data further up the stack and `LogFile.execSeriesEntry` would need to look it up again and re-parse it.  I tacked on the parsed series data to the `LogEntry` and `execSeriesEntry` will use it if exists, otherwise fall back to looking it up in the `SeriesFile`.
* Inserting to RHH was creating lots of little allocations.  I switched it to use some temp buffers that can be re-used.
* The `mmap.Map` call `madvise(MADV_RANDOM)` which was trigger a lot of read IOPS on the series files.  I removed that and seems to reduce read IOPS.
* Loading a big TSM file was also trigger lots of read IOPS due to page …
=> Series creation improvements

tsdb/engine/tsm1/cache.go, tsdb/engine/tsm1/ring.go, tsdb/engine/tsm1/ring_test.go, tsdb/engine/tsm1/wal.go
This helps with stability for higher cardinality write loads.
* Reduce cache partitions from 4096 to 16.  4096 causes big swings in HeapInUse which can OOM the processes if snapshotting gets backed up.
* Increase WAL write buffer size to 16k.  Investigating the memory spikes showed that writes to the WAL were taking several 4k IOs.  Under higher write load, this can cause disks to be saturated more quickly which can back up cache snapshotting.  With the higher partition count, the process can OOM.
=> Reduce cache partitions

CHANGELOG.md, Godeps
=> Fix stddev() call to report itself as always returning a float

CHANGELOG.md
Remove some miscellaneous whitespace at the end of changelog entries and
fix two older entries. One accidentally included an inline html tag and
didn't display. The other was missing a newline between two changelog
entries and so didn't display correctly as separate bullet points.
=> Fix some changelog entries

CHANGELOG.md, importer/v8/importer.go, tests/export_import_test.go
Fixes #9336
I'm not happy with some of the names here. I also want to add a test that hits the 5000 batchSize to verify everything works there. Will probably look at `cmd/influx_inspect/export/export_test.go` to see how to generate larger test dbs.
batchWrite was using the last database and retention policy read from
the input file. Because batchWrite was called only every batchSize lines
or at EOF, databases with fewer than batchWrite points could be imported
into the incorrect database.
This change forces a flush with batchWrite whenever processDML reads a
change in database or retention policy.
=> Fix imports of multiple databases in one export file

Dockerfile_build_ubuntu32, Dockerfile_build_ubuntu64, Dockerfile_build_ubuntu64_go19
Upstream must have changed and now autoconf isn't installed as an
implicit dependency of one of the packages anymore. Install is
explicitly so the fpm portion of the circle build works correctly.
=> Install autoconf in the circle build for fpm

tsdb/shard.go
The `tsdb.Shard#closing` channel is not used anywhere
=> remove redundant closing channel from tsdb.Shard

client/influxdb.go, client/influxdb_test.go
The default port for HTTP is 80 and HTTPS is 443. When you host InfluxDB
on a service that uses a reverse proxy, the `Host` header needs to be
exactly correct. Since the host header isn't expecting to see the port
when it is the default, this causes routing to fail.
Fixes #9259.
=> Do not explicitly specify ports 80 or 443 when they are the default port

services/meta/client_test.go, services/meta/data.go
This makes the behavior similar to other places in the DB where we
don't return an error when we try to drop an object from a non-
existent database.
=> Do not report an error when dropping a CQ on a non-existent DB/RP

cmd/influxd/run/server.go, services/storage/service.go, services/storage/store.go
Was incorrectly flagged as unused by some automated tools
=> restore `MetaClient`, which is needed by store

pkg/estimator/hll/hll.go, tsdb/store.go
It's possible that if `SHOW SERIES/MEASUREMENT CARDINALITY` is executed before any points are written to a database that `nil` sketches would be accessible from the Store. This is not ideal from an API consumer perspective.
=> Ensure nil sketches never returned

monitor/service_test.go
A deadlock would happen if the monitor attempted to write multiple
points. Since the test only reads the first set of points written to the
channel and does not read from the channel on the second read, the
WritePoints call deadlocks while the monitor is trying to close since
the monitor requires all of its goroutines to end. But, one of the
goroutines is attempting to call WritePoints which is waiting for the
test to read the point it is trying to write.
This change ensures that the done channel is closed before calling close
so the WritePoints call can exit.
=> Fix a deadlock in the monitor test

Dockerfile_build_ubuntu32, Dockerfile_build_ubuntu64, Dockerfile_build_ubuntu64_git, Dockerfile_build_ubuntu64_go19, Dockerfile_jenkins_ubuntu32
The progress bar makes it hard to scroll through the output and the
progress bar information is never useful.
=> Use --no-verbose with wget to reduce output

coordinator/statement_executor.go
Fixes #9365.
Ensures that a database is specified before executing `SHOW SERIES CARDINALITY` or `SHOW MEASUREMENT CARDINALITY`
=> Ensure db specified for SHOW CARDINALITY

tsdb/engine/tsm1/engine.go
Spawning a new goroutine is no longer necessary
=> simplify code

services/meta/client_test.go, services/meta/data.go
The method was only called in tests.
=> Remove IsAdmin() method from meta.User interface

query/compile.go, query/compile_test.go
=> Fix regression when math between literals is used in a field

cmd/influxd/run/command.go, etc/config.sample.toml, logger/logger.go
This PR removes the InfluxDB logo when output is redirected to a non-TTY device in order to strip extraneous data from log files.
=> Suppress the InfluxDB banner if the log output is not a TTY

etc/config.sample.toml, services/httpd/config.go, services/httpd/handler.go, services/httpd/service.go
Added a new option for the `[http]` service configuration to redirect request logging to a separate file, to address part of #9438
> Add a way to split out HTTP logs into a separate access log.
The new key is as follows
```
[http]
#
```
**NOTES:** 
* when request logging is redirected to a file, the `[httpd] ` prefix is stripped, so access log parsing tools like [lnav](https://lnav.org) can render them without additional modification.
* to rotate the log file, use the `copytruncate` method of `logrotate` or similar to leave the original file in place.
=> Added option to write HTTP request logs to separate file

tsdb/index/inmem/inmem.go, tsdb/index/inmem/meta.go, tsdb/series_segment.go
This improves series creation throughput.
* Remove the `lastModified` time on `inmem` Series which was used for concurrent writes and deletes.  We have the series bitmaps now that works for both `inmem` and `tsi` so this is not needed.  The `time.Now()` was showing up in profiles.
* Increase the `SeriesSegment` write buffer size to 32k from 4k.  This reduces IOs and time spent while the segment is locked and waiting for flushes.
* Fix `max-series-per-database` limit checks that ended up creating series one at a time.  This now does it in bulk which is less accurate, but more efficient.
=> Inmem series creation improvements

tsdb/engine/tsm1/engine_test.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/wal.go, tsdb/engine/tsm1/wal_test.go
Re-open the last wal segment instead of creating a new one.  This fixes
an issue where the last modified time of the WAL would change on
restart.  It also avoids a lot of IO file churn on restart.
Fixes #9333
=> Re-open last WAL segment

etc/config.sample.toml
The original PR that modified this was modified without changing the
sample config so this makes the sample config more accurate.
=> Fix the logging sample config

cmd/influxd/main.go, cmd/influxd/run/command.go, coordinator/points_writer.go, logger/logger.go, logger/style_guide.md, monitor/service.go, monitor/service_test.go, services/collectd/service.go, services/continuous_querier/service.go, services/graphite/service.go, services/httpd/handler.go, services/httpd/service.go, services/meta/client.go, services/opentsdb/handler.go, services/opentsdb/service.go, services/precreator/service.go, services/retention/service.go, services/snapshotter/service.go, services/subscriber/service.go, services/udp/service.go, tsdb/engine/tsm1/cache.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/wal.go, tsdb/store.go
Includes a style guide that details the basics of how to log.
=> Update logging calls to take advantage of structured logging

tsdb/engine/tsm1/iterator.gen.go, tsdb/engine/tsm1/iterator.gen.go.tmpl, tsdb/engine/tsm1/iterator_test.go
Double closing a bufCursor would cause a panic.  There was also
some typed cursors that had the same problem.
=> Make closing TSM cursors idempotent

tsdb/engine/tsm1/engine.go
This logging is noisy and allocates a lot of garbage.  There are
stats now that have the same information.
=> Remove noisy trace logging in TSM engine

cmd/influx_inspect/buildtsi/buildtsi.go, logger/fields.go, logger/logger.go, monitor/service.go, pkg/snowflake/README.md, pkg/snowflake/gen.go, pkg/snowflake/gen_test.go, services/collectd/service.go, services/continuous_querier/service.go, services/graphite/service.go, services/httpd/handler.go, services/meta/client.go, services/opentsdb/service.go, services/retention/service.go, services/subscriber/service.go, services/udp/service.go, tsdb/engine/tsm1/engine.go, tsdb/index/tsi1/partition.go, tsdb/series_partition.go, tsdb/store.go
Traces create a child logger with additional context that is used to log any subsequent events during the trace. Specifically
* `op.name` is a unique identifier for the operation. We can filter on all operations of a specific name. An example of an `op.name` might be `tsm1.compact_group`
* `op.event` currently has two values `start` or `end` indicating the start or end of an operation
* for example, you can grep by values in `op.name` AND `op.event` to find all starting operation logs
* Traces begin and end with a consistent log entry
* traces begin with a friendly description of the operation, like **TSM compaction** and the `op.event` context
* Traces end with the same description of the operation, like **TSM compaction**
* `trace_id` is a unique identifier used for a specific instance …
=> Generate trace logs for a number of important InfluxDB operations

etc/config.sample.toml, query/query_executor.go
Update the query executor to log a message using the style guide. The
actual message is static and the query is now in a context field.
=> Update sample config with information on logging levels

services/storage/series_cursor.go
Series keys from TSI are produced in ascending order. Setting `Ascending` to `true` ensures the merge iterator performs an ascending comparison.
=> series keys are produced in ascending order

.gitignore, logger/fields.go, services/continuous_querier/service.go, services/retention/service.go, tsdb/engine/tsm1/engine.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go, tsdb/series_partition.go, tsdb/store.go
All keys and operation names use underscore. Do not use periods for any key or identifier names.
Namespacing keys like `level` to `tsm1_level`
* avoid future collisions and 
* confusion with a global `level` which might be interpreted as the log level
| old key | new key |
| ------- | ------- |
| `level`    | `tsm1_level`    |
| `strategy` | `tsm1_strategy` |
| `optimize` | `tsm1_optimize` |
| old key | new key |
| ------- | ------- |
| `index.tsi.compact_to_level` | `tsi1_compact_to_level` |
| `index.tsi.compact_log_file` | `tsi1_compact_log_file` |
=> rename + namespace keys, fix doc comment

tsdb/engine/tsm1/engine.go
prefix `cache_snapshot` operation key name with `tsm1_` for consistency with other TSM1 operation names
=> prefix with `tsm1_` for consistency

tsdb/engine/tsm1/engine.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/tsi1/index.go
This PR improves the startup time when using the `inmem` index by
ensuring that the series are created in the index and series file in
batches of 10000, rather than individually.
Fixes #9486.
Using the same dataset as #9486 with 4M series:
| release  | startup time |
| ------------- | ------------- |
|1.3.9 |   27s |
|1.4.2  |   27s |
|1.5.0rc3 |  91s | 
| PR | 20s |
So that's an improvement of `~25%` on `1.3.9`. However @jwilder @stuartcarnie I'm not set on this PR yet as we may not be able to re-use the `keys` buffer as I'm currently doing. I'm going to dig around a bit and see if it needs to be changed to allocate a new `[][]byte` for each batch rather than re-using the same one.
=> Improve startup time of inmem index

cmd/influx_inspect/dumptsi/dumptsi.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go
This pull request adds validation to the `influx_inspect dumptsi` utility to check if a directory is an index before opening it. Previously it would assume the directory was an index and open it which would generate partitions.
This PR also moves the series iteration out of the partitions and into a single call for the index.
Fixes #9482.
=> Add dumptsi path error handling.

tsdb/engine/tsm1/engine.go
Use the child logger so the appropriate context is attached to the log entry
=> use child logger

tsdb/index/inmem/inmem.go, tsdb/index/inmem/meta.go, tsdb/index/inmem/meta_test.go
There was a check in inmem TagSets to see if a series was assigned
to a shard to prevent cursors for non-existent series getting created.
This check was lost during TSI development because inmem Series tracking
was removed and then replaced with bitsets.  The bitsets were not
re-incorporated as before.  This adds the functionality back using
the bitsets.
=> Skip creating cursors for series not in a shard

tsdb/engine/tsm1/engine_test.go
Some filesystems only have second-level `mtime` precision (`HFS+`) or 2 second level precision (`FAT32`). 
This ensures that the test passes on those filesystems.
=> Support less granular mtime in LastModified test

query/compile.go, query/iterator.go, query/select.go, query/subquery.go
The implicit time range for an interval is supposed to be now when no
end is specified. In a subquery though, the interval doesn't exist and
so it doesn't set the end time to now, but to the max time. Since the
subquery qualifies as something that should have the implicit end time
apply, this results in a query that runs slowly because it is filling in
a bunch of unasked for intervals if a fill is specified.
This hack adds the implicit end time if it sees the parent query's end
time is set to the maximum available time.
This is a temporary fix for this problem. The query compilation should
perform these time range calculations in the compilation stage and the
subqueries should use the compilation stage during execution instead of
ignoring it. That work takes a lot more effort though and …
=> Fix the implicit time range in a subquery

Godeps, tsdb/index.go, tsdb/index/inmem/meta.go
=> Evaluate a true boolean literal when calculating tag sets

tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/log_file_test.go
Adds additional `tsi1.LogFile` recovery and unit tests.
=> Fix TSI log file recovery.

tsdb/store.go
Add a missing `sync.Mutex.Unlock()` to `Store.Close()`
=> Fix missing Store.Close() unlock.

cmd/influxd/run/server.go, coordinator/statement_executor.go, coordinator/statement_executor_test.go, query/executor.go, query/executor_test.go, query/monitor.go, query/task_manager.go, services/continuous_querier/service.go, services/continuous_querier/service_test.go, services/httpd/handler.go, services/httpd/handler_test.go
Remove the `Query` prefix from some structs and interfaces. They were
there so when the query engine was in the same package as influxql,
these would be differentiated. Now that the package name is query, the
extra prefix seems redundant.
=> Rename some of the structs and interfaces in the query package

coordinator/statement_executor.go, query/compile.go, query/execution_context.go, query/executor.go, query/executor_test.go, query/iterator.go, query/iterator_test.go, query/monitor.go, query/monitor_test.go, query/select.go, query/task_manager.go, services/continuous_querier/service_test.go, services/httpd/handler_test.go
Along with modifying ExecutionContext to be a context and have the
TaskManager return the context itself, this also creates a Monitor
interface and exposes the Monitor through the Context. This way, we can
access the monitor from within the query.Select method and keep all of
the limits inside of the query package instead of leaking them into the
statement executor.
An eventual goal is to remove the InterruptCh from the IteratorOptions
and use the Context instead, but for now, we'll just assign the done
channel from the Context to the IteratorOptions so at least they refer
to the same channel.
=> Turn the ExecutionContext into a context.Context

monitor/service_test.go
This was previous fixed in b740567 for one test, but the other tests in
the package were still vulnerable. The tests are all updated to use a
cancel context instead since then it doesn't need to be wrapped in a
sync.Once.
=> Fix the deadlocks in the monitor tests

cmd/influxd/run/config.go, cmd/influxd/run/config_test.go
=> Support setting the log level through the environment variable

client/influxdb.go, client/influxdb_test.go, client/v2/client.go, client/v2/client_test.go, cmd/influx/cli/cli.go, man/influx.txt
This also adds support for both the v1 and v2 APIs to set the Proxy
function on the underlying http.Transport.
The functionality for proxy environment variables is provided by the
[http.ProxyFromEnvironment](https://godoc.org/net/http#ProxyFromEnvironment).
=> Support proxy environment variables in the influx client

tsdb/engine.go, tsdb/engine/tsm1/engine.go
This adds an internal option (not exposed via config) to disable the WAL
when using the TSM engine directly.
=> Add option to disable WAL

services/subscriber/service_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_cursor.go, tsdb/index.go, tsdb/shard.go, tsdb/shard_test.go, tsdb/store_test.go
This fixes #9548.
Within the `Store`, there is the concept of an `IndexSet`, which is an arbitrary collection of shard indexes. When dealing with iterators over an `IndexSet` a lot of the merging and filtering is handled automatically. The introduction of the `IndexSet` was a side-effect of the moving of index-query-planning up from the shard level to the database level.
One optimisation introduce during the `1.5.` cycle was to reduce the size of the `IndexSet` down to `1`, for `inmem` indexes. This was possible because each shard index in the `inmem` index is identical.
However, each `Shard` also stores a `MeasurementFieldSet`, which tracks the fields associated with measurements within that shard only. For the case of the `inmem` index, all`MeasurementFieldSet`s except for one belonging …
=> Fix panic when checking fieldsets

tsdb/engine/tsm1/pools.go
Currently if a buffer from the buffer is too small to satisfy its request then we simply drop it and allocate a new one.
This change puts it back in the pool and then allocates a new one.
=> Do not drop on the floor small buffers

models/points.go, models/points_test.go
```
name                                old time/op    new time/op    delta
EscapeMeasurement/this_is_a_test-8     142ns ± 3%      17ns ± 4%   -87.93%  (p=0.008 n=5+5)
EscapeMeasurement/this,is,a,test-8     195ns ± 1%     101ns ± 4%   -48.05%  (p=0.008 n=5+5)
Tags_HashKey/5_tags-no_esc-8          1.04µs ± 2%    0.25µs ±14%   -75.78%  (p=0.008 n=5+5)
Tags_HashKey/25_tags-no_esc-8         4.85µs ± 2%    1.00µs ± 4%   -79.27%  (p=0.008 n=5+5)
Tags_HashKey/5_tags-esc-8             1.79µs ±11%    0.82µs ± 1%   -53.86%  (p=0.008 n=5+5)
Tags_HashKey/25_tags-esc-8            8.02µs ± 0%    4.14µs ± 0%   -48.34%  (p=0.016 n=4+5)
MakeKey/this_is_a_test-8               327ns ± 1%      73ns ± 1%   -77.70%  (p=0.016 n=5+4)
MakeKey/this,is,a,test-8               392ns ± 3%     163ns ± 3%   -58.48% …
```
=> Performance improvements to MakeKey and HashKey APIs

models/points.go, models/points_test.go
Fixes #9545.
This PR fixes a parsing bug that was causing extra tags to be
generated when the incoming point contained escaped commas.
As an optimisation, the slice of tags associated with a point was
being pre-allocated using the number of commas in the series key as a hint to
the appropriate size. The hinting did not consider literal comma values in
the key though, and so it was possible for extra (empty) tag key and
value pairs to be part of the tags structure associated with a parsed
point.
The fix here is simply to pre-allocate the capacity (which is the upper bound on the maximum number of tag pairs), and then to use the slightly slower `append`, rather than index into the slice directly.
I think this will still be faster than parsing the key to determine the true number of tag …
=> Ensure correct number of tags parsed when commas used

cmd/influxd/restore/restore.go, tests/backup_restore_test.go
=> Bugfix for shard collisions resulting from attempted _internal import

tsdb/index.go, tsdb/shard.go
Use single `SeriesPointIterator` and combine each shard index into a single `IndexSet`. Assuming series keys are relatively consistent between shards, this shows a 2x improvement in performance for 2 shards. Should show linear improvement in performance, so 10 shards, 10x.
=> Improve performance of SHOW SERIES query

tsdb/index.go, tsdb/shard.go
Previously, large `SHOW SERIES` queries would block until merging was complete before being interrupted. Interruption checks have been added to the iterator and the merge loop. I also tried adding interruption checks to the sort phase but it's difficult to break out of `sort.Sort()` upon interruption.
=> Allow SHOW SERIES kill

toml/toml.go, toml/toml_test.go
One of the closed source copies of applyEnvOverrides needed this
behavior.
=> Handle embedded and ignored fields in toml env override

tsdb/shard.go
A `nil` iterator should be returned on an empty shard set.
=> Remove error for series file when no shards exist

CHANGELOG.md, query/compile.go, query/cursor.go, query/executor.go, query/functions.go, query/iterator.gen.go, query/iterator.gen.go.tmpl, query/iterator.go, query/iterator_test.go, query/math.go, query/monitor.go, query/select.go, query/select_test.go, query/subquery.go, tests/server_test.go, tsdb/shard.go
This change makes it so that we simplify the math engine so it doesn't
use a complicated set of nested iterators. That way, we have to change
math in one fewer place.
It also greatly simplifies the query engine as now we can create the
necessary iterators, join them by time, name, and tags, and then use the
cursor interface to read them and use eval to compute the result. It
makes it so the auxiliary iterators and all of their complexity can be
removed.
This also makes use of the new eval functionality that was recently
added to the influxql package.
No math functions have been added, but the scaffolding has been included
so things like trigonometry functions are just a single commit away.
This also introduces a small breaking change. Because of the call
optimization, it is now possible …
=> Refactor the math engine to compile the query and use eval

query/compile.go, query/math.go
This adds support for math functions into the query language. Math
functions are special because they are transformations and do not access
the filesystem in the same way aggregate functions do. A transformation
takes one point and always outputs one point making it more similar to
binary expressions so these math functions follow the same rules as
binary expressions.
This also supports using math literals (so you can do `sin(1)`) and the
math functions can be used anywhere such as in a field or an expression.
Both of the following are supported:
SELECT sin(value) FROM cpu
SELECT value FROM cpu WHERE sin(value) > 0.5
Arguments are in radians. Degrees is not supported.
Fixes #9424.
=> Implement basic trigonometry functions

tsdb/engine/tsm1/mmap_unix.go, tsdb/engine/tsm1/mmap_windows.go, tsdb/engine/tsm1/reader.go
This reverts commit ee270e1dd2135d91dbaf0b3adb25d9c2801b6639.
The `madvise(MADV_WILLNEED)` significantly slowed down TSM startup for CentOS/RHEL.
See https://github.com/influxdata/influxdb/issues/9534
=> Revert "Use MADV_WILLNEED when loading TSM files"

tests/server_test.go
The LocalServer could be closed before the goroutine writing points
exited causing nil pointer panic.
Fixes #9583
=> Fix flaky test TestServer_ConcurrentPointsWriter_Subscriber

cmd/influxd/restore/restore.go
bug fix:  helper function LoadIncremental may return a nil manifest value without returning an error so the manifest must be checked explicitly.
=> check for failure case where backup dir has no manifest files

query/call_iterator.go, query/cursor.go, query/iterator_mapper.go, query/select_test.go
This ensures that NaN gets serialized as a null value and that it does
not get replaced with the fill value.
=> Use a null placeholder for NaN results

cmd/influxd/restore/restore.go
=> backport: check for failure case where backup dir has no manifest files

services/retention/service.go, services/retention/service_test.go
Previously the `retension.Service` would only delete expired shards but ignore already deleted shards in the local filesystem. If a shard directory was not deleted for some reason then this would cause the shard to never get checked and removed later.
=> Delete deleted shards in retention service.

tsdb/engine/tsm1/mmap_unix.go, tsdb/engine/tsm1/mmap_windows.go, tsdb/engine/tsm1/reader.go
This reverts commit ee270e1dd2135d91dbaf0b3adb25d9c2801b6639.
=> 1.5: Revert "Use MADV_WILLNEED when loading TSM files"

query/cursor.go, query/iterator_mapper.go, query/select.go, query/select_test.go, query/subquery.go, query/subquery_test.go
This is not complete, but it is a starting point for more thorough tests
of subqueries.
This also reorders the use of `cmp.Diff` so the `want` is first and
`got` is second. This way, the `want` shows up as a minus sign in the
diff rather than, confusingly, as a plus sign.
=> Add some unit tests to subqueries

tsdb/engine/tsm1/engine.go
TSM includes index in DiskSize(), however, indexes are not copied and shouldn't be included in this method. This causes issues with `copy-shard`.
=> Ignore index size in Engine.DiskSize().

cmd/influx_inspect/buildtsi/buildtsi.go
Previously the TSM series key was not being passed into `CreateSeriesIfNotExists()` for `buildtsi` because the series key wasn't originally used in TSI. The series key started being used after partitioning was added but `buildtsi` was not updated.
This can affect users who rebuild TSI on hot shards since the built partition will not match newly inserted series.
=> Fix buildtsi partition key.

CONTRIBUTING.md
The existing curl commands are not working due to implementation has changed.
For `query` api, warning was returned:
```
{
"results": [
{
"statement_id": 0,
"messages": [
{
"level": "warning",
"text": "deprecated use of 'CREATE DATABASE mydb' in a read only context, please use a POST request instead"
}
]
}
]
}
```
For `write` api, error was returned:
```
{"error":"database is required"}
```
- Use POST in `query` api
- Move db to query parameter in `write` api
=> Fix curl commands in contributing doc

query/cast.go, query/cursor.go, query/iterator.gen.go, query/iterator.gen.go.tmpl, query/iterator.go, query/iterator_mapper.go, query/iterator_mapper_test.go, query/select.go, query/subquery.go, query/subquery_test.go
This also fixes the cursor system to abandon iterators that will not
produce meaningful results since the variables are all unknown types.
This creates a weird behavior that existed in previous releases and we
are keeping here for backwards compatibility. If a subquery referenced a
field that didn't exist in the subquery, it will return nothing. But, if
there are two subqueries and one of them has the field exist and the
other doesn't, the second will return all null values.
Fixes #9624.
=> Enable casting values from a subquery

etc/config.sample.toml, tsdb/config.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go
This commit adds the `max-index-log-file-size` configuration flag so that users can restrict the maximum size of log files before compaction. The default limit was also lowered from `5MB` to `1MB`. The original size was set before we partitioned the index so the change reflects this.
=> Add adjustable TSI log file size.

etc/config.sample.toml, tsdb/config.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/partition.go
Backport https://github.com/influxdata/influxdb/pull/9670
=> [1.5] Adjustable TSI Compaction Threshold

query/iterator.go, query/iterator_test.go
ConditionExpr would output conditions that may not have had parenthesis
in the same place so they would not marshal into a proper expression.
This fixes the condition before it gets encoded.
This is done instead of fixing influxql because the current version of
influxql is not compatible with 1.5 anymore and this version of influxdb
doesn't have a very good way of using a branch. While it would be
possible, this method is a more direct way to fix the problem for 1.5
and then fix it properly for 1.6.
=> Ensure that conditions are encoded correctly even if the AST is not properly formed

query/math.go
implement  floor, ceil, round functions (listed in #5930) requested in #3691.
the functions has be implemented based on /query/math.go  as math functions. #9499
so all the (floor, ceiling, truncate) can be used anywhere such as in a field or an expression.
Example usage: 
`select load from cpu`
> name: cpu
>time                load
>1434055562000000000 42
>1434055562000000000 15.4
>1434055562000000000 78
---- 
`select floor(load) from cpu`
> name: cpu
> time                floor
> 1434055562000000000 42
> 1434055562000000000 15
> 1434055562000000000 78
---- 
`select ceil(load) from cpu
> name: cpu
> time                ceiling
> 1434055562000000000 42
> 1434055562000000000 16
> 1434055562000000000 78
---- 
`select round(load) from cpu`
> name: cpu
> time                truncate
> …
=> Implement floor, ceil, and round functions

services/httpd/config.go, services/httpd/service.go, toml/toml.go, toml/toml_test.go
=> Allow customizing the unix socket group and permissions created by the server

tsdb/engine/tsm1/tombstone.go, tsdb/engine/tsm1/tombstone_test.go
The length check was backwards so if a series key was longer than
4096 bytes, it would cause a slice out of bounds panic.
```
--- FAIL: TestTombstoner_Add_LargeKey (0.00s)
panic: runtime error: slice bounds out of range [recovered]
panic: runtime error: slice bounds out of range
goroutine 5 [running]:
testing.tRunner.func1(0xc4201960f0)
/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x16e9460, 0x1ba6340)
/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Tombstoner).readTombstoneV4.func1(0xc420108dc0, 0xc420087b48, 0xc420087b20, 0xc420087b30, 0xc420087ae8, 0xc420087af0, 0xc420087ca0, 0xc420073b28, 0x102c1c4)
/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/tombstone.go:619 +0x591 …
```
=> Fix panic in readTombstoneV4

services/httpd/response_writer.go, services/httpd/response_writer_test.go
If the columns change between series, it will now act as if it was a new
statement id and reprint the headers. This only happens with show
diagnostics at the moment and we shouldn't add this functionality
anywhere else anyway.
Fixes #9504.
=> Avoid a panic when using show diagnostics with text/csv

tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_test.go, tsdb/shard.go
This moves the time range to delete to be returned by the predicate
func in `DeleteSeriesRangeWithPredicate`.  It allows for a single delete
to delete different ranges of times per series instead of a single
range of time for all series.
cc @jacobmarble
=> Return time range from delete predicate func

services/httpd/response_writer.go, services/httpd/response_writer_test.go
The number of bytes written for CSV responses and probably MessagePack
responses was incorrect.
Fixes #9690.
=> Properly track the response bytes written for queries in all format types

tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/measurement_block.go, tsdb/index/tsi1/tag_block.go, tsdb/index/tsi1/tag_block_test.go, tsdb/index/tsi1/tsi1.go
Closes #9425
This change doesn't do anything with the CRC check because the CRC sum isn't available until after the panic likely occurs. This change does check the result of `binary.Uvarint` which is the likely source of panic.
=> Check for errors from binary.Uvarint when reading TSI logs

tsdb/index.go
Fix by adding default case to `select` to avoid blocking
=> SHOW SERIES hangs

client/README.md
The best practice is to close used resources at the end. I've had a problem when I used this code in AWS Golang Lambda function without `c.Close()`: `socket: too many open files` - I've reached connection limit because InfluxDB connections have been still opened.
=> Update client README - close client resources

coordinator/statement_executor.go, coordinator/statement_executor_test.go, query/executor.go, services/httpd/handler.go
Before this change, `/query?db=db&rp=alternate` does not respect `rp`.
Makes progress on #7973
When `rp=foo` (HTTP url param or POST form) and the queried measurement is `db.bar.m`, `bar` wins.
=> Respect rp parameter in /query

pkg/estimator/hll/hll.go, pkg/estimator/hll/hll_test.go
Get a rough estimate of HLL memory footprint. This makes progress toward estimating memory footprint of inmem index in #9766
=> HLL++: estimate memory footprint bytes

cmd/influxd/backup/backup.go, cmd/influxd/restore/restore.go, man/influxd-backup.txt, man/influxd-restore.txt, tests/backup_restore_test.go
Added short- and long- form versions of -database  and -retention to  both backup and restore so that users' experience is consistent between tools (prevents some copy/paste errors)
@stevebang   will make comments on the man-pages.   Need an engineer to sign off on backup.go  and restore.go
=> Update backup flags to have long/short versions

client/v2/client.go, models/points.go
Validate points when using Client API.   If input value is +Inf or -Inf influxdb server side will give an incorrect error (invalid boolean, or invalid number).
This PR only validates on Client side.  Server side would need a different set of changes.
Also make sure to skip any "nil" points when the client attempts a Write.
Did not update CHANGELOG.md as PR could be considered trivial.
=> Validate points on input

tsdb/shard.go, tsdb/store.go
Contributes to #9707.
This PR adds two new useful things to the logs:
1) During startup the index type in use for a shard will be logged when the shard is opened, using the `index_version` key. The two types available are: `{"inmem", "tsi1"}`.
2) The TSDB store will track all the different index types for all shards within all databases. Then, it will determine if there exist shards within a database that are running differing indexes, and log the frequency of each index type as a warning.
An example of the new logs (including a database with mixed index types) is as follows:
```
...
...
2018-04-25T12:56:53.953773Z	info	Opened shard	{"log_id": "07gDtm50000", "service": "store", "trace_id": "07gDtmVW000", "op_name": "tsdb_open", "index_version": "tsi1", "path": …
```
=> Log information about index version during startup

tsdb/index/inmem/inmem_test.go
Megacheck is pinging all of our PRs with an unused function; this fixes that.
=> tsdb/indx/inmem: Fix megacheck issue

coordinator/points_writer.go, tsdb/engine/tsm1/engine_test.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/reader.go, tsdb/engine/tsm1/reader_test.go, tsdb/store.go
Fixes #9786
`TSMReader.Close` returns an error when queries are referencing the TSM file, but `FileStore.Close` ignores the error.
In this change, `FileStore.Close` checks the error, and `TSMReader.Close` blocks, rather than returning the error. This makes it clear to the caller of `FileStore.Close` (`drop shard X` for example) that the file is safely closed, rather than requiring the caller to retry up to thousands of times when the query load is constantly high.
After this change, TSM files are always closed when `drop shard X` returns, and writing to a shard that is currently being deleted returns a partial error.
=> TSM: TSMReader.Close blocks until reads complete

cmd/influx_inspect/deletetsm/deletetsm.go, tsdb/engine/tsm1/file_store.go
While opening, this change updates TSM files to have a `.tsm.bad` extension if the files are corrupt.
=> Rename & log corrupt tsm files on load

cmd/influx_inspect/deletetsm/deletetsm.go, models/points.go
This commit adds the `-sanitize` flag to `influx_inspect deletetsm` which will delete all keys that contain invalid, non-printable, or replacement character unicode.
```sh
$ influx_inspect deletetsm -sanitize PATH
```
/cc @timhallinflux
=> Add key sanitization to deletetsm

pkg/estimator/hll/hll.go, pkg/estimator/hll/hll_test.go, pkg/estimator/sketch.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/inmem_test.go, tsdb/index/inmem/meta.go, tsdb/index/tsi1/file_set.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/index_file.go, tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/measurement_block.go, tsdb/index/tsi1/partition.go, tsdb/series_set.go, tsdb/shard.go
Provides internal API to make progress on #9766 
Memory counting is a bit complicated because `go vet` does not allow copying instances of `sync.Mutex` and similar data structures, and `unsafe.Sizeof` violates that check. To work around this, there is a lot of field-by-field counting in this change, but I tried to consistently comment exceptions and count fields in the order they are presented in each struct.
=> tsdb/index: Add Bytes() methods

pkg/radix/tree.go, pkg/radix/tree_test.go, tsdb/engine/tsm1/cache.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_test.go, tsdb/engine/tsm1/file_store.go, tsdb/shard.go
This fixes the `Engine` to prevent type conflicts within a series.  This is handled by using a radix tree to map series keys to types.  The radix tree provides compression for the mostly duplicate prefixes of the series keys and functions as a map like structure.
There is no persistence of this structure and it does not require it.  The first time a series is written, the mapping is checked and if the series does not exists, it is looked up from the `Cache` and/or `FileStore`.   This means there is no extra disk IO at write time or startup.
This does not currently handle deletes (will follow up with separate PR) and stats are not recorded for type conflicts.
=> Prevent series type conflict 

cmd/influxd/run/server.go, coordinator/statement_executor.go, tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/inmem_test.go, tsdb/index/inmem/meta.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/log_file.go, tsdb/shard.go, tsdb/store.go
Closes #9766 
This change adds `SHOW STATS FOR 'indexes'` which returns an estimate of memory use of all indexes. Index memory use is *not* reported with `SHOW STATS` because it is a potentially expensive operation, and the implementation of `SHOW STATS` is also triggered every 10s to populate the `_internal` database.
Tested by comparing the output of this new function to the heap pprof. Results are comparable, not perfect, but pprof doesn't hold absolute truth either.
=> Implement SHOW STATS FOR 'indexes'

tsdb/series_file.go, tsdb/series_partition.go
The existing godoc doesn't match the implementation (SeriesPartition in particular) or the way CreateSeriesListIfNotExists is used in the two places where the returned `ids` value isn't thrown away. In fact, those two usages look like they might break if current godoc were true.
=> Correct godoc for SeriesFile.CreateSeriesListIfNotExists

query/task_manager.go
Previously, the task manager was modified to keep the query status so it
could track which queries were running and which ones were killed.
In those previous versions, we removed a task from the process table
as soon as it was killed and did not remove it after it had finished
executing. This meant there could be zombie goroutines running in the
background that were impossible to see.
When the task manager was updated to track the task status, we forgot to
expose the status in the public interface so consumers could see the
task status.
Backport of #9778.
=> Include the query task status in the QueryInfo struct

cmd/influx_inspect/dumptsmwal/dumptsmwal.go, cmd/influx_inspect/main.go
This pull request adds the ability to dump the raw data from a TSM WAL file.
```sh
$ influx_inspect dumptsmwal _00001.wal
```
=> Add dumptsmwal command to influx_inspect.

tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/inmem_test.go, tsdb/index/tsi1/index.go, tsdb/index_test.go, tsdb/shard.go, tsdb/store.go
`IndexSet.DedupeInmemIndexes()` was written with a subtle bug, which only returned one inmem index when multiple, distinct inmem indexes existed. This change includes a regression unit test. The bug was introduced here:
https://github.com/influxdata/influxdb/commit/493c1ed0d1f103c357eb9289deba22f593fa8835#diff-c218be2666dc8c31e018b8ebca9b46ceR1067
With that out of the way, there's a much cleaner way to walk all indexes for counting their memory footprint. #9766
=> Cleanup index memory footprint counting code

tsdb/engine/tsm1/compact.go, tsdb/engine/tsm1/compact_test.go, tsdb/engine/tsm1/file_store.go
The InUse call on TSMFiles is inherently racy in the presence of
Ref calls outside of the file store mutex. In addition, we return
some TSMFiles to callers without them being Ref'd which might allow
them to be closed from underneath. While I believe it is the case
that it would be impossible, as the only thing that gets a handle
externally is compaction, and compaction enforces that only one
handle exists at a time, and thus is only deleted once after the
compaction is done with it, it's not very obvious or enforced.
Instead, always return a TSMFile with a Ref call under the read
lock, and require that no one else calls Ref. That way, it cannot
transition to referenced if the InUse call returns false under the
write lock.
The CreateSnapshot method was racy in a number of ways in the …
=> tsm1: ensure some race conditions are impossible

pkg/radix/buffer.go, pkg/radix/buffer_test.go, pkg/radix/tree.go, pkg/radix/tree_test.go, tsdb/engine/tsm1/engine.go
- reduce allocations by making leaf a value type with a bool
- make longestPrefix inlineable and have no bounds checks
- delete any code for functions we don't plan to use
- operate on []byte and only copy when necessary
- inline calls to sort.Search to avoid allocations and indirections
- insert directly in the correct location for addEdge
- reduce allocations during copying with a buffer helper
results:
```
name              old time/op    new time/op     delta
Tree_Insert-8       1.10ms ± 4%     0.73ms ± 4%  -33.54%  (p=0.000 n=10+10)
Tree_InsertNew-8    3.18ms ± 2%     1.91ms ± 6%  -39.90%  (p=0.000 n=10+10)
name              old speed      new speed       delta
Tree_Insert-8     9.12MB/s ± 4%  13.72MB/s ± 4%  +50.46%  (p=0.000 n=10+10)
Tree_InsertNew-8  3.15MB/s ± 2%   5.24MB/s ± 6% …
```
=> radix: optimize for our use case

query/functions.go, query/iterator_test.go, query/point.gen.go, query/point.gen.go.tmpl, query/select_test.go
When `top()` or `bottom()` were used and selected auxiliary values, they
would return the wrong values that would be equal to the last point
selected. This is because the aggregators saved the memory address of
the auxiliary fields instead of copying them over. Since the same
auxiliary fields memory location is used for every value returned by the
storage engine, this resulted in the values being incorrect because they
were overwritten with incorrect values.
This fixes that so the auxiliary fields are copied out when they are
saved rather than only the memory location.
Fixes #9197.
=> Return the correct auxiliary values for top/bottom

tsdb/engine/tsm1/file_store.go
More work to properly fix #9786
Confirmed that `DROP SHARD X` works properly when the service is loaded with 10 concurrent select sum(f) style queries. Files are deleted, and file descriptors are closed. So #9792 is WAI.
Looking at RP more closely:
- created a 1 minute RP (one-line local code modification)
- set 10 second RP check interval (config file setting)
- loaded the service with the same queries mentioned above
- watched the oldest shard (89) disappear from `SHOW SHARDS`
- shard 89's files never deleted from the filesystem
- shard 89's file descriptors never closed
- waited 30 minutes, then killed the query load
Discovered that a RP event and exactly one query were deadlocked. RP was blocking here:
```
// Close closes the TSMReader.
func (t *TSMReader) Close() error { …
```
=> Close TSMReaders from FileStore.Close after releasing FileStore mutex

query/call_iterator.go, query/compile.go, query/functions.go, query/select.go
This renames the function `triple_exponential_average` to `triple_exponential_derivative` to more accurately reflect what it does. Ref https://github.com/influxdata/influxdb/pull/9260#issuecomment-389333924
Per the referenced discussion, instead of naming it "trix", as this is indeed what it is generally known as, I still opted for the long name due to consistency. What influx calls "average" is generally known as "sma" (simple moving average), and renaming this isn't an option, so I think consistency is more important.
@jsternberg
=> rename "triple_exponential_average" -> "triple_exponential_derivative"

query/select_test.go
The new tests accidentally labeled the `p3` variable as the data type
rather than a string.
=> Fix the new top/bottom unit tests

tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go
just adds some interface for hooks about when these files come and go.
we do them before the action is taken so that if the hook has an
error, it doesn't have any consistency problems.
=> file store: send notifications about new/deleted tsm files.

query/math.go, query/math_test.go
The passed in argument wasn't correct so it always returned null instead
of the appropriate value.
Also includes unit tests for all of the math functions and restricts the
`asin()` and `acos()` functions to floats only since those functions
don't give any meaningful results when using integers or unsigned.
Fixes #9850.
=> Fix the log2 function to return values

tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go
an observer may want to know what shard the file is part of. this
way, they don't have to rely on brittle file path parsing.
=> tsdb: add shard number to the observer

tsdb/engine/tsm1/reader.go
This improvement avoids performing a binary search on the index by
first checking the key against the lower and upper bounds. Particularly
useful for multiple, fully-compacted TSM files.
=> fix(tsm1): Avoid searching index if key outside index bounds

cmd/influxd/run/command.go, etc/config.sample.toml, services/httpd/config.go
This pull request adds `debug-pprof-enabled` which will start the default `net/http/pprof` endpoint and bind against `localhost:6060`. This will help to debug startup performance issues.
=> Add optional pprof http endpoint immediately on startup.

tsdb/engine.go, tsdb/engine/tsm1/compact_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/file_store_observer.go, tsdb/engine/tsm1/file_store_test.go, tsdb/engine/tsm1/reader.go, tsdb/engine/tsm1/tombstone.go, tsdb/engine/tsm1/tombstone_test.go
I worry that I have tangled myself into a mess with the `WithObserver` pattern in order to avoid a mandatory, optional, parameter everywhere. It seems fragile to future changes in that one must consider if upon any opening of a TSMFile, if it may generate a tombstone. Open to suggestions.
=> tsdb: observe tombstone files as well

tsdb/engine/tsm1/tombstone.go, tsdb/engine/tsm1/tombstone_test.go
=> [1.5] Fix panic in readTombstoneV4

tsdb/engine.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go, tsdb/store.go
This commit restricts the number of TSM1 files that can be opened concurrently across the entire `tsdb.Store`. There is currently a limit for the number of shards that can be opened concurrently, however, this limit does not help when the number of CPU cores is higher than the number of shards. Because TSM1 files have a 2GB limit and there is no limit on the number of files per shard, extremely large shards (1TB+) can load 1,000s of files simultaneously.
Testing on a m5.12xlarge w/ a 2.1TB dataset containing 1,084 `.tsm` files, load time was reduced by `31%` from `8m48s` to `6m2s`.
=> TSM1 Open Limiter

tsdb/engine/tsm1/file_store.go
Enterprise was failing to start because `EngineOptions.OpenLimiter` was `nil`, and reading from a `nil` channel blocks forever.
=> TSM: Enforce OpenLimiter must not be nil

models/points.go, models/points_test.go, tsdb/engine/tsm1/engine.go, tsdb/meta.go
When `influx_inspect buildtsi` is used to create a new `tsi1` index, spaces in measurement names are escaped, so measurement "a b" is changed to "a\ b".
This change modifies `models.ParseKeyBytes()` and `models.ParseName()` to unescape measurement names. `models.ParseKeyBytes()` returns unescaped tag keys, so this seems like the natural place to unescape measurement names.
Also followed `scanMeasurement()` to see what other code could be problematic, and this should be everything (the result of one other use of `scanMeasurement()` is later escaped).
Removed `tsdb.MeasurementFromSeriesKey()`. These methods are exported, so checked for side effects in other InfluxData repositories.
After this change, existing TSI indexes that include backslashed measurements created by this bug will need to …
=> buildtsi: Do not escape measurement names

services/storage/group_resultset.go, services/storage/group_resultset_test.go, services/storage/response_writer.go, services/storage/rpc_service.go
Group frames were being serialized when no series had points for the given time range.
=> fix(services/storage): Don't serialize empty group frames

cmd/influx-tools/importer/importer.go
=> Remove an unused variable caught by megacheck in the importer

stress/basic.go
first, show my flame graph Captured in the pressure measurement phase in the test server. 
40% of cpu detected waiting on sync.(*Mutex), can only run up to 800% cpu usage, the pressure on influxdb is only 20w/s points.
so may be it necessary to optimize. 
show my stress test config file. 
```
[provision]
[provision.basic]
enabled = true
address = "xxxx:xxxx"
database = "xxxx"
reset_database = false
[write]
[write.point_generator]
[write.point_generator.basic]
point_count = 1000
series_count = 1000000
tick = "10s"
jitter = true
precision = "s"
measurement = "cpu"
start_date = "2009-Jan-02"
[[write.point_generator.basic.tag]]
key = "host"
value = "server"
[[write.point_generator.basic.tag]]
key = "location"
value = "us-west"
[[write.point_generator.basic.field]]
key = "value"
value = …
```
=> Performance optimization for testcode

tsdb/shard.go
This pull request exports the `Shard.Engine()` so that individual `Engine` properties can be manipulated by the Enterprise API.
=> Export Shard.Engine()

cmd/influx/cli/cli.go
Previously the CLI retention policy was not being passed to the server correctly. `SELECT` commands were working properly because they are rewritten on the client side, however, `SHOW` commands are rewritten on the server side.
Repro:
1. Insert data with different fields into retention policies "autogen" & "X"
2. Inside `influx`, execute `use mydb.X`
3. Inside `influx`, execute `SHOW FIELD KEYS`
The correct fields should show for the `X` retention policy.
Fixes https://github.com/influxdata/influxdb/issues/8589
=> Add retention policy flag to CLI queries.

cmd/influx_inspect/buildtsi/buildtsi.go, tsdb/engine/tsm1/cache.go, tsdb/engine/tsm1/cache_race_test.go, tsdb/engine/tsm1/cache_test.go, tsdb/engine/tsm1/compact_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_test.go
When WAL is disabled, snapshot compaction never happens due to `CacheFlushWriteColdDuration` is exceeded, only when `CacheFlushMemorySizeThreshold` is exceeded.
This is a problem for quiet clusters that pull from Kafka, because Kafka has it's own retention policy; if Kafka cleans up before influxdb snapshots, and then influxdb terminates, then the cached data is lost.
This change depends on `Cache.LastWriteTime` rather than `WAL.LastWriteTime`, which are nearly identical anyway, because `Engine.WritePoints` calls `Cache.WriteMulti` just before `WAL.WriteMulti`.
=> TSM: Fix ShouldCompactCache without WAL

Godeps, Gopkg.lock, Gopkg.toml, LICENSE_OF_DEPENDENCIES.md, cmd/influxd/backup/backup.go, cmd/influxd/restore/restore.go
Drop-in of pgzip for gzip
Compression for the backup and restore commands of influxd were able to download the data from the database quickly, but subsequent compression and decompression was done in a single-threaded manner that is extremely slow.
- [ x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
=> Parallelize compression/decompression during backup and restore

cmd/influxd/backup/backup.go, tsdb/index/tsi1/log_file.go
Flushes the `bufio.Writer` and fsync's to disk after writes.
Fixes #9863
Fixes #9957
Fixes #9987
=> Flush/sync TSI1 WAL

tsdb/engine/tsm1/engine.go
Cherry picking shard digest logging change from `master` back to `1.6`.
=> Cherry pick add digest logging to 1.6

Gopkg.lock, Gopkg.toml
See influxdata/influxql#21 for details.
Fixes #9574.
=> Improve the number of regex patterns that are optimized to static OR conditions

Gopkg.lock, services/storage/predicate_influxql.go, services/storage/predicate_test.go
This fixes a bug where the read endpoint (used by flux and the prometheus read endpoint) was not calling into our regex optimisation logic.
As such, regex expressions were not getting re-written, resulting in slower read performance.
=> Ensure read service regexes get optimised

tsdb/engine/tsm1/compact.go, tsdb/engine/tsm1/writer.go, tsdb/engine/tsm1/writer_test.go
we were asserting to an *os.File in order to call Sync, but in some
cases the file handle has been wrapped, for example with limiting.
instead, assert to minimal interfaces for the functionality we need
and attempt to add some robustness in the code that creates the
writers by using a stronger interface with a Sync method.
fixes #9991
=> tsm1: ensure all written tsm files are fsynced

tsdb/engine.go, tsdb/engine/tsm1/file_store.go
Backport #9928 and #9933, which fix a bug introduced in #9918
=> Backports to fix bug in #9918

tsdb/index.go, tsdb/meta_test.go, tsdb/shard_test.go
Previously we were filtering iterators at a very low level, which meant we were filtering series that would have been merged out by higher iterators anyway.
Filtering is expensive because it involves locking on the series file partitions, which has a fixed cost of ~35ns per seriesID checked. For millions of series that can expensive at planning time.
This PR moves the filtering to as high a level as possible.
=> Filter iterators as high up a possible

cmd/influx_inspect/main.go, cmd/influx_inspect/reporttsi/report.go
Resolves https://github.com/influxdata/influxdb/issues/10023
This PR adds a new tool `reporttsi` to `influx_inspect`. You run it as follows:
```
$ influx_inspect reporttsi -db-path ~/.influxdb/data/stress -top 10
```
The report does the following:
- calculates the total exact series cardinality in the database;
- segments that cardinality by measurement, and emits those cardinality values;
- optionally limits the result to the "top n";
- Emits total exact cardinality for each shard in the database;
- Segments for each shard the exact cardinality for each measurement in the shard;
- optionally limits the results in each shard to the "top n".
This tool is primarily of use when there has been a change in cardinality, and it's not clear which measurement is responsible for this change, and …
=> Add new TSI index cardinality report to influx_inspect 

tsdb/index.go, tsdb/index/tsi1/file_set.go, tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/measurement_block.go, tsdb/series_set.go
This pull request implements iterators based on `SeriesIDSet`. This allows faster merging of large series sets. This improves planning time by approximately 20%, however, a large amount of time is still spent building the bitsets. This change, along with changes from @e-dard, and some additional caching should help remove the bitset building time.
=> Implement bitset iterator

tsdb/index/tsi1/partition.go, tsdb/shard.go
TSI LogFile compactions occasionally race with insert and delete
operations because the index partition FileSet is retained needlessly by
the method that calls Partition.CheckLogFile.
In this change:
- TSI LogFile compaction respects enable/disable compactions
- Partition FileSet.Release before log compaction is triggered
An alternative to the second step is to handle log file compaction in a
new goroutine. Log file compaction errors would be logged and not
returned to the caller.
After this change, `DELETE FROM /regex/` does not deadlock; performance:
- 30s to delete 100 measurements
- 5m30s to delete 1000 measurements
Fixes #9636
=> Resolve deadlock deleting from many measurements concurrently

cmd/influx_inspect/buildtsi/buildtsi.go, models/points.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/partition.go, tsdb/series_set.go
Fixes #10019 
This PR significantly improves the performance of `influx_inspect buildtsi`. It makes building a TSI index around 4-10 times faster than 1.5.3, and 17–46 times faster than current `master`. 😃 
- Shards will be processed concurrently (adjustable with `-c`);
- Series batch size configurable. This is an "expert" option, and users should typically stick with the default value, which is 10,000; and
- Much. More. Fasterer.
I wrote 100,000,000 series with inch across 25 shards.
- 4 measurements
- 5 tag keys
```
inch -b 10000 -c 5 -t 10,10,10,100,1000 -f 1 -m 4 -p 1 -start-time '2018-07-02T00:00:00Z' -time 100h  -v
```
These results show the time taken to build the TSI index with a pre-existing series file. Most of the performance boost comes from changes to how the index is built …
=> Improve performance of buildtsi tool / series creation

uuid/uuid.go
=> Missing hardwareAddr in uuid v1 generation

uuid/uuid.go
Introduced in #10005. Not sure why CircleCI didn't run against that PR.
=> cleanup import order in uuid.go

etc/config.sample.toml, services/udp/config.go, services/udp/config_test.go
This updates the config and diagnostic info for the UDP service to include the `precision` option, which was added in PR https://github.com/influxdata/influxdb/pull/5565.
=> Update example config with UDP precision option

CONTRIBUTING.md, Dockerfile, Dockerfile_build_ubuntu32, Dockerfile_build_ubuntu64, Dockerfile_build_ubuntu64_git, Dockerfile_build_ubuntu64_go1.11, Dockerfile_jenkins_ubuntu32, Jenkinsfile, cmd/influx_tools/internal/format/binary/writer_test.go, releng/_go_versions.sh, test.sh
This PR updates the Go runtime used to 1.10.
In 289a05e I have updated the "next" version we run in tests to Go 1.11, however until that release is available I have left the actual version at 1.10.3.
=> Update to Go 1.10

CHANGELOG.md
Added the 1.5.x maintenance release changes to the 1.6 change log....where x > 0.
=> Update CHANGELOG on the 1.6 branch to include the 1.5.x maintenance releases.

etc/config.sample.toml, services/udp/config.go, services/udp/config_test.go
Backport https://github.com/influxdata/influxdb/pull/10051 to correct UDP `precision` configuration setting omission.
=> Document UDP precision setting in config

pkg/radix/sort.go, pkg/radix/sort_test.go, tsdb/index/inmem/meta.go
I've seen this sort call showing up in some profiles. Radix sort benchmarks favorably on uint64s.
@e-dard @timhallinflux
=> inmem: use radix sort for series ids

Gopkg.lock
=> Fix a panic when matching on a specific type of regular expression

tsdb/store.go
This PR removes the maximum default limit of `4` concurrent compactions, introduced in #9204.
The idea in #9204 was to reduce IO utilisation on large systems with many cores,
and high write load. Often on these systems, disks were not scaled
appropriately to to the write volume, and while the write path could
keep up, compactions would saturate disks.
Further, in #9225 work was also done to reduce IO saturation by limiting the
compaction throughput. To some extent, both #9204 and #9225 work towards
solving the same problem.
We have recently begun to notice larger clusters suffering from
a buildup of un-compacted TSM data, because compactions are not keeping up. This is usually because they have scaled up the box for a higher write load, but the limit of 4 concurrent compactions has stayed …
=> Remove max concurrent compaction limit

cmd/influx_tools/internal/format/binary/reader_test.go, cmd/influx_tools/internal/format/binary/writer.go, cmd/influx_tools/internal/format/binary/writer_test.go, cmd/influx_tools/internal/format/conflictwriter.go, cmd/influx_tools/internal/format/line/writer.go, cmd/influx_tools/internal/format/text/writer.go, cmd/influx_tools/internal/format/writer.go
A recent change for the columnar work changed the default cursor types used by the storage read service. This service is used by the `influx_tools export` command and required updating to utilize the new types.
=> fix(influx_tools): Use Array cursor types

client/influxdb.go, cmd/influxd/run/config.go, cmd/influxd/run/config_test.go, cmd/influxd/run/server.go, cmd/influxd/run/tls_config.go, etc/config.sample.toml, pkg/tlsconfig/tls_config.go, services/httpd/config.go, services/httpd/service.go, services/opentsdb/config.go, services/opentsdb/service.go, services/subscriber/config.go, services/subscriber/http.go, services/subscriber/service.go
This PR allows one to specify
- Which cipher suites to use
- A minimum supported TLS version
- A maximum supported TLS version
in the config files.
Fixes #8637.
=> Allow specifying some TLS configuration.

client/influxdb.go, cmd/influxd/run/config.go, cmd/influxd/run/config_test.go, cmd/influxd/run/server.go, cmd/influxd/run/tls_config.go, etc/config.sample.toml, pkg/tlsconfig/tls_config.go, services/httpd/config.go, services/httpd/service.go, services/opentsdb/config.go, services/opentsdb/service.go, services/subscriber/config.go, services/subscriber/http.go, services/subscriber/service.go
This PR allows one to specify
- Which cipher suites to use
- A minimum supported TLS version
- A maximum supported TLS version
in the config files.
Backport of #10150.
=> Provide configurable TLS options

etc/config.sample.toml, tsdb/config.go, tsdb/config_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/mmap_unix.go, tsdb/engine/tsm1/mmap_windows.go, tsdb/engine/tsm1/reader.go
Fixes #10117.
This PR adds a new configuration option - `tsm-use-madv-willneed` / `INFLUXDB_DATA_TSM_USE_MADV_WILLNEED`, which, when true, will hint to the kernel that we plan on sequentially reading TSM files.
This option defaults to false because we have had some issues in the past with certain kernels/operating systems. However, it may be useful to some users with slow disks.
=> Add option to hint MADV_WILLNEED to kernel

etc/config.sample.toml, tsdb/config.go, tsdb/config_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go, tsdb/engine/tsm1/mmap_unix.go, tsdb/engine/tsm1/mmap_windows.go, tsdb/engine/tsm1/reader.go
=> Add option to hint MADV_WILLNEED to kernel 

coordinator/points_writer_test.go, services/meta/data.go, tsdb/engine/tsm1/engine_test.go, tsdb/store.go
`megacheck` was [recently updated](https://github.com/dominikh/go-tools/commit/7ca3f547f9335a25653ffb1b68a21ed576ae1854) to simplify some loops. This PR fixes the cases in the repo that could be simplified in this way.
=> Simplify loops

cmd/influx_inspect/buildtsi/buildtsi.go
Exported two methods in `buildtsi.go` so that they can be used from other code.
Follow-up to #10019
=> influx_inspect: Make buildtsi code resusable

tsdb/store.go
Follow up to #9939.
I tested #9939 and this change cleans up logging and a little bit of logic.
=> tsdb: Cleanup compaction throughput code

stress/stress_test.go
Fixes a flaky test point values with a leading zero (`0` or `0i`) are generated
```
=== RUN   Test_typeArr
--- FAIL: Test_typeArr (0.00s)
stress_test.go:86: Expected line protocol int got 0i
```
=> test(stress): Fix flaky test

tsdb/index.go
Do not add `nil` values when calling `MergeSeriesIDIterators`, which will result in a panic. A `nil` value may occur when a predicate contains regular expressions.
fixes #10171
=> Fix iterator panic in read service 

cmd/influxd/restore/restore.go
Restore would fail when file paths contained extra periods.
Taking the basename of the files fixes this.
I discovered this when trying to automate a legacy backup/restore via a temporary directory. By default `mktemp` puts a period in the directory name. This causes errors of the form:
2018/06/17 13:49:14 Restoring live from backup /tmp/tmp.Nl8QvA4Iq9/database.*
2018/06/17 13:49:14 Skipping mis-named backup file: /tmp/tmp.Nl8QvA4Iq9/database.autogen.00167.00
2018/06/17 13:49:14 error updating shards: strconv.ParseUint: parsing "autogen": invalid syntax
restore: strconv.ParseUint: parsing "autogen": invalid syntax
Full disclosure: I've not written any Go code before, but the test suite still works so I don't think it broke anything. I searched through the code base and can't see any other …
=> Minor fix for legacy restore

pkg/snowflake/gen.go, pkg/snowflake/gen_test.go
use atomics rather than mutexes to synchronize state between calls.
```
name            old time/op  new time/op  delta
Next-8           244ns ± 0%    30ns ± 2%  -87.70%  (p=0.000 n=8+7)
NextParallel-8   215µs ±60%     0µs ± 1%  -99.96%  (p=0.000 n=8+8)
```
The results for NextParallel are around ~80ns/op, but that doesn't
show up in the benchstat output.
=> pkg/snowflake: reduce contention in Next calls

pkg/snowflake/gen.go, pkg/snowflake/gen_test.go
it's slightly slower, but the safety is worth it i think.
```
name            old time/op  new time/op  delta
Next-8          30.0ns ± 2%  31.0ns ± 3%   +3.56%  (p=0.002 n=7+8)
NextParallel-8  79.4ns ± 1%  92.5ns ± 1%  +16.58%  (p=0.000 n=8+8)
```
=> pkg/snowflake: be more robust against sequence rollover

etc/config.sample.toml, tsdb/config.go, tsdb/shard.go
This pull request adds a `validate-keys` configuration field that requires shard writes to check for valid, printable UTF-8 characters. Points with invalid keys will be dropped and a partial write error is returned.
=> Add option for unicode validation.

services/httpd/handler.go, services/meta/data.go
This changes adds additional auth shortcutting, primarily for enterprise
usecases with simple FGA setups. OSS users won't see any changes.
=> httpd/meta: use open auth when unrestricted

Dockerfile_build_ubuntu64_go1.11, coordinator/meta_client_test.go, releng/_go_versions.sh, services/continuous_querier/service_test.go, services/retention/service_test.go, services/snapshotter/service_test.go
This test will bring Go 1.11rc1 into the CI pipeline.
=> Test InfluxDB on Go 1.11rc1

tsdb/config.go, tsdb/config_test.go, tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/engine_test.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/tsi1/index.go, tsdb/index_test.go, tsdb/shard_internal_test.go, tsdb/shard_test.go, tsdb/store.go, tsdb/store_test.go
This PR fixes an issue where series could be left in the `inmem` index, when they should have been removed.
It could be triggered as follows:
- insert some series into a shard that only exist in that shard;
- wait for the retention policy enforcement to remove the shard;
- run a `SHOW` query such as `SHOW TAG KEYS`;
- The series that were removed with the shard will be missing (as expected);
- re-insert the same series;
- run a `SHOW` query such as `SHOW TAG KEYS`;
- The series will **not** be present (they should bed).
This manifests itself because the series were removed from the series file, but not from the `inmem` index. If the server was restarted the issue would resolve itself.
Commit f52de2d ensures that the series are removed from the `inmem` index if they're the last occurence …
=> Ensure orhpaned series cleaned up with shard drop

tsdb/engine/tsm1/cursor_iterator.go
booleans are, in fact, not strings. :smile:
=> fix(tsm1): return boolean iterator for booleans

tsdb/engine/tsm1/digest.go, tsdb/engine/tsm1/digest_reader.go, tsdb/engine/tsm1/digest_test.go, tsdb/engine/tsm1/digest_writer.go
Some enterprise users with larger shards were seeing significant increases in CPU usage caused by reading shard digests. Profiling showed most of the time was spent decompressing the digest data. This PR improves performance of the shard digest writer and reader by switching from `gzip` to `snappy` compression, which is faster.
Local test with 13.2 GB shard (3.9 M series & 5.2 M time ranges):
```
gzip:   read in 4.5 seconds (80.7 MB digest)
snappy: read in 2.4 seconds (101.9 MB digest)
```
=> Switch digests to use snappy compression

tsdb/engine/tsm1/digest.go, tsdb/engine/tsm1/digest_reader.go, tsdb/engine/tsm1/digest_test.go, tsdb/engine/tsm1/digest_writer.go
This PR backports https://github.com/influxdata/influxdb/pull/10215 to 1.6.
=> Use snappy compression for digests

Gopkg.lock, Gopkg.toml
This PR updates the version of influxql to this commit https://github.com/influxdata/influxql/commit/a7267bff5327e316e54c54342b0bc9598753e3d5 . This fixes a bug where predicate expressions were getting parsed incorrectly.
=> update influxql version

tsdb/index/tsi1/log_file.go
Since we append to the file itself, once we have read the file in, we
can be done with the mmap'd data.
Ideally we can rework UnmarshalBinary and do away with the mmap
completely. That is future work.
For databases with lots of TSI indexes this PR could reduce RSS.
=> Unmap LogFile on successful open

tsdb/engine/tsm1/array_cursor_iterator.go
booleans are still not strings. :smile:
=> fix(tsm1): return boolean array iterator for booleans

query/compile.go, query/compile_test.go
The compiler was too strict. The inherited interval from an outer query
should not have caused the inner query to fail because inherited
intervals are only implicitly passed to inner queries that support group
by time functionality. Since the inner query with a derivative doesn't
support grouping by time and the inner query itself doesn't specify a
time, the outer query shouldn't have invalidated the inner query.
=> Fix the inherited interval for derivative and others

CHANGELOG.md
Since there is no v1.6.0 in the revision list for the changelog, it
assumes that the current commits are for 1.6.0.
=> Fixing the changelog

tsdb/engine/tsm1/batch_float.go, tsdb/engine/tsm1/batch_float_test.go
FloatBatchDecodeAll behaves the same as the iterator-based float
decoder, returning an empty slice and no error when passed a buffer
with no encoded float values.
Fixes #10270
=> fix(tsm1): Fix FloatBatchDecodeAll to return empty slice an no error

query/compile.go, query/compile_test.go
The derivative function and others similar to it would preload
themselves with data so that the first interval would be the start of
the time range. That meant reading data outside of the time range.
One change to the shard mapper back in v1.4.0 caused the shard mapper to
constrict queries to the intervals given to the shard mapper. This was
correct because the shard mapper can only deal with times it has mapped,
but this broke the functionality of looking back into the past for
the derivative and other functions that used that functionality.
The compiler has been updated with an additional attribute that records
how many intervals in the past will need to be read so that the shard
mapper can include extra times that it may not necessarily read from,
but may be queried because of the …
=> Fix the derivative and others time ranges for aggregate data

tsdb/index/tsi1/file_set.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/index_file.go, tsdb/index/tsi1/log_file.go, tsdb/index/tsi1/measurement_block.go, tsdb/index/tsi1/partition.go, tsdb/index_test.go, tsdb/store_test.go
This commit removes the HLL sketches on each `tsi1.LogFile` and `tsi1.IndexFile` and instead caches the data at the `tsi1.Index` level. This reduces the heap size significantly for servers with many TSI-enabled shards.
Tests using `inch` showed a reduction from `~900MB` to `~200MB` for a `638` shard server with this change. The reduction is larger if there are more compacted index files in each shard.
=> Remove TSI1 HLL sketches from heap.

CONTRIBUTING.md, Dockerfile, Dockerfile_build_ubuntu32, Dockerfile_build_ubuntu64, Dockerfile_build_ubuntu64_git, Dockerfile_jenkins_ubuntu32, Jenkinsfile, releng/_go_versions.sh, services/httpd/response_writer_test.go, test.sh
This PR updates the Go runtime used to build InfluxDB to Go 1.11.
We will continue to test the "next version of Go" using 1.11 until a 1.12 RC is available. We should really turn that test runner off until then but I don't know how to do that.
=> Update to Go 1.11

services/storage/predicate_influxql.go, services/storage/predicate_test.go
Transforming an RPC predicate to InfluxQL should set the Type field to Tag, as it is explicitly set as a NodeTypeTagRef in the protobuf predicate
=> fix(storage): Set the Type field to Tag

cmd/influxd/backup/backup.go, man/influxd-backup.txt
there are some edge cases where a shard backup fails on a live backup if it is deleted by a retention policy 
after the shard is identified, but before the download starts.  This fix allows the backup process to continue, even with failures so that empty/deleted shards are ignored.  
Adds a new flag : 
`# influxd backup -portable -skip-errors -db telegraf /tmp/backup`
if skip-errors is set, then errors will be skipped as described above.  The default for skip-errors is false, maintaining backward compatability.  
docs PR:  https://github.com/influxdata/docs.influxdata.com/pull/1844
=> Backup continue on errors

tsdb/index/tsi1/index.go
Recent changes to the TSI sketches missed required locking. This change only caused issues with in-memory representations and not on-disk representations. This pull request adds the necessary locking.
=> Fix TSI1 Sketch Locking

cmd/influx/cli/cli.go
This fixes #9277 on client side.
=> Print error message for unknown errors in client

services/httpd/handler.go
=> Changes /ping route to return status code 200 instead of 204 when verbose is set

CHANGELOG.md, query/cast.go, query/iterator.gen.go, query/iterator.gen.go.tmpl, query/iterator.go, query/iterator_mapper.go, query/iterator_mapper_test.go, query/subquery.go, query/subquery_test.go
This fixes two problems in subqueries that were introduced in 1.6. The first is that using a function on a tag when the tag was in a subquery such as the following:
SELECT count(host) FROM (SELECT value, host FROM cpu)
This was previously allowed, but during a refactor, I forgot to treat tags as strings when reading from a subquery result so it would discard the results rather than read from them as if it were a string.
The second is that tags were not stripped from subqueries when the outer query did not group by that tag as in this example:
SELECT value FROM (SELECT value FROM cpu GROUP BY host)
Both of these regressions have been fixed and test cases have been added.
=> Assorted fixes to subquery regressions in 1.6

tsdb/index/tsi1/log_file.go
This commit updates an iterator list to ignore `nil` iterators.
Adding a `nil` caused the `SeriesIterators.Close()` to panic.
=> Fix append of possible nil iterator.

cmd/influx_inspect/verify/seriesfile/verify.go, cmd/influx_inspect/verify/seriesfile/verify_test.go, tsdb/series_file_test.go, tsdb/series_index.go, tsdb/series_partition.go
This commit fixes an issue with the series file compaction process where tombstones are lost after compaction and series existence checks are not correct. This commit also fixes some smaller flushing issues within the series file that mainly related to testing.
=> Fix series file tombstoning.

tsdb/engine/tsm1/engine.go, tsdb/engine/tsm1/file_store.go
Fixes #10160.
If there was an error after the cache has been snapshotted to one or
more TSM files, but before the cache and WAL are cleaned up, then the
cache would be repeatedly snapshotted, generated duplicate level 1 TSM
files.
This PR attempts to clean those files up by removing the temporary TSM file(s). The snapshot will be retried.
=> Cleanup failed TSM snapshots

tsdb/engine/tsm1/file_store.go
This commit fixes an error check so that a `nil` TSM reader does
not cause a panic. Fixes #10244.
=> Fix TSM1 panic on reader error.

cmd/influx_inspect/deletetsm/deletetsm.go, tsdb/shard.go
This is to support an enterprise change.
=> Backport #9937: Export Shard.Engine()

services/storage/predicate_influxql.go
We rewrite queries for `_measurement` to `_name`, but we didn't also
rewrite `_m`. During some of the code sharing, it started being the
case that it received `_m` instead of `_measurement`. Additionally,
we need to start mapping `_f` to `_field` for the same reason.
=> Fix measurement/field filtering for flux queries

query/iterator.gen.go, query/iterator.gen.go.tmpl
The stream iterator would ignore an error that happened when reading
points. This may have caused it to potentially return an error that got
ignored and then to try invoking `Next()` on an iterator in an invalid
state and that iterator would then actually return a point which it
wasn't supposed to.
Also added some defensive coding to that same call to prevent a nil map
from being assigned to in the event of an invalid iterator returning
junk data.
=> Fixing the stream iterator to not ignore the error

tsdb/engine/tsm1/engine.go
Queries such as 'DELETE FROM "measurement" WHERE time > someTime' will typically only affect a few shards. However, this causes all series indexes to be rebuilt as long as the series existed in the shard, but it did not care about the min/max time.
It looks like the existing if check was wrong because it just checked the length of the series array, but did not care about the series name that was set to empty in the loop above.
This PR should fix #10218, or at least partially.
=> Prevent DELETE FROM to rebuild series files for shards where nothing is deleted

tsdb/engine/tsm1/batch_float.go, tsdb/engine/tsm1/batch_float_test.go
Performance has been improved significantly and the code heavily documented with reasons…
Fixes #10318 
```
name                        old time/op   new time/op    delta
FloatArrayDecodeAll/1-8      45.9ns ± 1%    13.8ns ± 1%   -70.00%  (p=0.000 n=9+9)
FloatArrayDecodeAll/55-8      686ns ± 0%     232ns ± 1%   -66.10%  (p=0.000 n=9+8)
FloatArrayDecodeAll/550-8    5.78µs ± 0%    2.22µs ± 1%   -61.61%  (p=0.000 n=9+9)
FloatArrayDecodeAll/1000-8   10.2µs ± 2%     4.0µs ± 5%   -60.47%  (p=0.000 n=10+10)
name                        old speed     new speed      delta
FloatArrayDecodeAll/1-8     414MB/s ± 1%  1383MB/s ± 1%  +233.76%  (p=0.000 n=9+9)
FloatArrayDecodeAll/55-8    144MB/s ± 0%   424MB/s ± 1%  +194.19%  (p=0.000 n=9+9)
FloatArrayDecodeAll/550-8   133MB/s ± 0%   346MB/s ± 1%  +160.09% …
```
=> Improve performance of Gorilla float block decoding

Gopkg.lock, flux/control/controller.go, flux/functions/inputs/buckets.go
The buckets function for influxdb will retrieve all db/rp info in the system.   To be consistent with platform's `buckets` implementation, the columns are the same, but `platformID` and `organizationID` are left empty.  The `organizationName` I set to `influxdb`.  I'm open to different interpretations on these columns.
=> added physical implementation for the buckets()  function

Gopkg.lock, cmd/influx/cli/cli.go, cmd/influx/cli/flux.go, cmd/influx/main.go, flux/client/http.go, flux/client/request.go, services/httpd/flux.go, services/httpd/handler_test.go
Flux queries can be executed similarly to InfluxQL:
1. Start a Flux REPL:
```sh
$ influx -type=flux
````
2. Execute Flux query via parameter
```sh
$ influx -type=flux -execute '<flux query>'
````
3. Execute Flux query via STDIN
```sh
$ echo '<flux query>' | influx -type=flux
````
Resolves #10407
=> Add Flux support to the influx CLI command

Gopkg.lock, flux/functions/inputs/buckets.go, services/storage/series_cursor.go
The `Value` function must return a `string`, however `SeriesTags#Get` returns `[]byte`, resulting in the reduced expression always becoming `false` and thus returning no data.
An expression such as:
```
tag == "value0" AND _value == 1
```
would always reduce to 
```
[]("value0") == "value" AND _value == 1
```
which becomes
```
false AND _value == 1
```
=> Fix filtering by _value excludes all data

tsdb/index.go, tsdb/index/tsi1/partition.go, tsdb/shard.go, tsdb/store.go, tsdb/store_test.go
This PR fixes a panic where a concurrent removal of a shard and meta query could cause a `nil` index to be added to the IndexSet`.
=> Fix panic in IndexSet

tsdb/shard.go
This commit adds an `indexType` key to the shard sections of the
`/debug/vars` endpoint, as well as the `_internal` shard statistics.
The tag will be reported as `"indexType": "inmem"` or `"indexType":
"tsi1"`.
Note, this will increase the cardinality of the `_internal` database.
=> Add shards' index types to /debug/vars

tsdb/index.go
We already make copies when no expression is provided, because
the backing slices may go away if the shard they came from is
closed. This fixes the other spot where some backing slices
would be returned.
Backport of #10421.
=> fix(tsdb): copy measurement names when expression is provided

tsdb/engine/tsm1/batch_timestamp.go, tsdb/engine/tsm1/compact.gen.go, tsdb/engine/tsm1/compact.gen.go.tmpl, tsdb/engine/tsm1/compact.go
This fixes a bug on `master` where the max time for a block in the TSM index was being incorrectly written out. The bug was caused by the new TSM encoder/decoders using a buffer as scratch space. There was some existing merging code higher up in the engine that read those buffers after the blocks were encoded, and so the the incorrect max times were being read from the mutated buffers.
=> Fix TSM index maxtime modification

cmd/influx/cli/cli_test.go
Deleted the two flaky test functions that don't exercise any useful behavior or valid use cases. Closes #10430 
----
The original code was racy, as the `c.Quit` channel is closed in the test here:
https://github.com/influxdata/influxdb/blob/9ac37ca459bf15572f4d6c3adfc5ad99452b3a99/cmd/influx/cli/cli_test.go#L52-L54
In addition, it will be closed if the following line results in io.EOF
https://github.com/influxdata/influxdb/blob/c5ec3a32441c56be6477c0a897ec56e1c1714d7c/cmd/influx/cli/cli.go#L259
which leads to l being set to `"exit"`, calling `ParseCommand("exit")` and finally executing the `"exit"` case in the switch statement:
https://github.com/influxdata/influxdb/blob/c5ec3a32441c56be6477c0a897ec56e1c1714d7c/cmd/influx/cli/cli.go#L284-L285
=> Remove flaky CLI tests

cmd/influxd/run/server.go, flux/control/controller.go, flux/functions/inputs/buckets.go, services/httpd/handler.go, services/httpd/handler_test.go, services/httpd/service.go
Various API refinements to increase reuse in Enterprise and improve testability by lowering the required dependencies to the `control.NewController` function.
=> Improve APIs to increase reuse in Enterprise

tsdb/shard.go, tsdb/shard_test.go
Removes cloning measurement fields for a lighter way to handle contention between writes adding fields.
=> Reduce allocations for high measurement writes

client/v2/client.go
In a few places, the client was assuming that an error
string would necessarily be safe to pass as a format string.
This seems unwise.
It also seems trivial enough that I don't think it needs all the fancy overhead. I'm pretty sure that nothing is intentionally using formatting characters in things that won't have any additional arguments passed.
=> Don't use fmt.Errorf on random strings

pkg/encoding/simple8b/encoding.go, pkg/encoding/simple8b/encoding_test.go, tsdb/engine/tsm1/compact.gen.go, tsdb/engine/tsm1/compact.gen.go.tmpl, tsdb/engine/tsm1/compact_test.go
Resolves an encoding issue with simple8b. 
Closes #10465
For a run of 1s, if the 120th or 240th entry is not a 1, the run will be incorrectly encoded as selector 0 (240 1s) or selector 1 (120 1s), resulting in a loss of data for the 120th or 240th value.
This bug manifests itself as an infinite loop during a compaction, when the last timestamp in a block is the 120th or 240th in a run of 1s and is itself not a 1.
----
When timestamps are encoded using simple8b, they are first reduced to deltas and then a common divisor is computed. For example, take the following timestamps:
```
1:      12000
2:      13000
3:      14000
4:      15000
5..119: repeated values
120   : 133000
```
Deltas would first reduce the list to
```
1:      1000
2:      1000
3:      1000
4:      1000
5..119: 1000 …
```
=> Simple8B EncodeAll incorrectly encodes 120 or 240 1s if last value is not a 1

toml/toml.go, toml/toml_test.go
Most parts of `ApplyEnvOverrides` will check if the value is empty
before attempting to apply the environment override. One exception is
that when a type implements Unmarshaler and it is within a slice, it
does not check that an empty value was passed.
This change fixes it so that we will not call `UnmarshalText` when the
environment variable is set to empty.
Fixes #10487.
=> Fix ApplyEnvOverrides when a type that implements Unmarshaler is in a slice

flux/control/controller.go
The flux controller will use the log level of the logger to log queries and plans instead.
=> Remove "Verbose" option from controller.Config

tsdb/engine/tsm1/engine.go, tsdb/index.go, tsdb/index/inmem/inmem.go, tsdb/index/inmem/inmem_test.go, tsdb/index/tsi1/index.go
Before this, if you deleted everything with `delete where true`
for example, then you would be left with all of your measurements
in the fields index. That would cause ghost fields to reappear
if someone reinserted to the measurement.
This fixes that by making it so the deepest most delete code
checks if the measurement was removed from the index, and if so
cleaning it up out of the fields index.
Additionally, it fixes bugs in that cleanup code where if you had
a measurement like "m1" and "m10", when iterating over the cache
or file store, "m1" would match "m10" due to it only checking the
prefix. This also has it check the character right after the
measurement to be either a comma because tags started, or the first
character of the field separator.
Updates #9694.
=> tsdb: clean up fields index for every kind of delete

tsdb/epoch_tracker.go, tsdb/epoch_tracker_test.go, tsdb/guard.go, tsdb/guard_test.go, tsdb/store.go
There are some problematic races that occur when deletes happen
against writes to the same points at the same time. This change
introduces guards and an epoch based system to coordinate these
modifications.
A guard matches a point based on the time, measurement name, and
some conditions loaded from an influxql expression. The intent
is to be as precise as possible without allowing any false
neagatives: if a point would be deleted, the guard must match it.
We are allowed to match more points than necessary, at the cost
of slowing down writes.
The epoch based system keeps track of outstanding writes and
deletes and their associated guards. When a delete operation
is going to start, it waits until all current writes are
done, and installs its guard, blocking all future writes that
contain …
=> tsdb: conflict based concurrency resolution

client/v2/client.go
The current HTTP Go client for InfluxDB is a bit locked down. It supports directly connecting to a remote InfluxDB server and it supports going through a SOCKS5 proxy via the `client.HTTPConfig.Proxy` config field. It however does **not** support setting a custom dialer.
A custom dialer can have much more fine grained control as to how the remote connection is established. Also, setting custom dialers is a feature of Go's `http` package via the [`http.Transport`](https://golang.org/pkg/net/http/#Transport)'s `DialContext` field, so it's something API users kind of expect to be available.
This PR just adds this additional field to the `client.HTTPConfig`, to permit configuring a different TCP dialer for the HTTP client.
---
A concrete example where this comes in handy is if we'd like to …
=> client/v2: support custom dialer, not just socks proxy

coordinator/statement_executor.go, coordinator/statement_executor_test.go
When an NaN value was computed, it would be written back incorrectly as
a string type instead of being omitted. This happened very rarely in the
case that `stddev()` of a single value was computed and only when it was
being done on a new shard.
This correctly drops the value. The reason this wasn't correctly dropped
previously is because NaN values are represented as a `(*float64)(nil)`
which does not equal `nil` so the writeback system thought it was a
non-nil point, but the writer encoded it as a string.
In addition to the above, this also fixes the point writer to report the
number of points actually written rather than the number of points
desired to be written. Previously, if there was an error writing a point
for some reason, the point would be silently dropped, but still recorded …
=> Drop NaN values when writing back points

query/iterator.go, query/subquery_test.go
The query authorizer was not being properly passed to subqueries so
rejections did not happen when a subquery was the one reading the value.
Similarly, the max series limit was not being propagated downwards
either.
=> Pass the query authorizer to subqueries

query/iterator.go, query/subquery_test.go
The query authorizer was not being properly passed to subqueries so
rejections did not happen when a subquery was the one reading the value.
Similarly, the max series limit was not being propagated downwards
either.
This backport was a clean cherry-pick.
=> Backport #10549: Pass the query authorizer to subqueries

Gopkg.lock, Gopkg.toml, cmd/influx_tools/export/exporter.go, cmd/influx_tools/generate/exec/command.go, cmd/influx_tools/generate/exec/generator.go, cmd/influx_tools/generate/exec/series_generator.go, cmd/influx_tools/generate/init/command.go, cmd/influx_tools/generate/plan.go, cmd/influx_tools/generate/spec.go, cmd/influx_tools/help/help.go, cmd/influx_tools/importer/importer.go, cmd/influx_tools/internal/profile/profile.go, cmd/influx_tools/internal/shard/writer.go, cmd/influx_tools/main.go, cmd/influx_tools/server/server.go
* `influx_tools gen-init` initializes a database based on the provided CLI spec
* `influx_tools gen-exec` generates the data for the target database based on the same
CLI spec as `gen-init`
This PR is dependent on influxdata/platform#1751
----
Initialize a database, `db/rp` with 1000⨯100⨯10 series (`-t 1000,100,10`), each series containing 1,000 (`-p 1000`) points with remaining options as defaults (number of shards, start time):
```sh
$ bin/influx_tools gen-init -db=db -rp=rp -p 1000 -t 1000,100,10 -config <influxdb.toml>
```
To clarify, `-t 1000,100,10` will generate a sequence of series keys using the pattern `tag0=[value000...value999],tag1=[value00...value99],tag2=[value0..value9]`, or similar to the following:
```
m0,tag0=value000,tag1=value00,tag2=value0 …
```
=> Add data generator to influx_tools command

flux/functions/inputs/from.go
This fix ensures group(mode:"by") is correctly pushed down to the
storage layer.
=> Flux group(mode:"by") does not push down correct operation to storage layer

CONTRIBUTING.md, Dockerfile, Dockerfile_build_ubuntu32, Dockerfile_build_ubuntu64, Dockerfile_build_ubuntu64_git, Dockerfile_build_ubuntu64_go1.11, Dockerfile_jenkins_ubuntu32, Jenkinsfile, appveyor.yml, coordinator/meta_client_test.go, releng/_go_versions.sh, services/continuous_querier/service_test.go, services/httpd/response_writer_test.go, services/retention/service_test.go, services/snapshotter/service_test.go, test.sh, tsdb/engine/tsm1/engine.go
This PR updates the runtime to `go 1.10.3`. At the time of this PR `go 1.10.4` was not available in the Docker repos.
It also adds `go 1.11.6` as the release to run as an extra test in CI.
=> Update Go runtime to 1.10.6

tsdb/engine/tsm1/compact.go, tsdb/engine/tsm1/compact_test.go
This pull request limits the number of files that can be compacted in a single group when forcing a full compaction or when a shard becomes cold. This is to prevent too many files being compacted at the same time.
=> Limit force-full and cold compaction size.

cmd/influxd/run/server.go, flux/control/controller.go, flux/functions/inputs/buckets.go, flux/functions/inputs/from.go, services/httpd/handler.go, services/httpd/handler_test.go, services/meta/context.go, services/meta/query_authorizer.go
* Add `AuthorizeDatabase` API to `QueryAuthorizer` to verify a user has appropriate access to the specified database
* Update `serveFluxQuery` handler, adding a `meta.User` parameter, which triggers the Flux API requires a user when auth is enabled
* update Flux `createFromSource` and `createBucketsSource` dependencies to require `Authorizer` when auth is enabled in configuration
* update `createFromSource` verify read permissions for each bucket specified in a Flux query
* update `BucketsDecoder`, which implements the `buckets()` Flux function, to limit the displayed buckets to those the user has read or write permissions to. This replicates the behavior of the `SHOW DATABASES` InfluxQL command
* add unit tests to verify authentication is required for Flux HTTP requests when auth is …
=> Add user authentication and authorization support for Flux HTTP requests

flux/functions/inputs/from.go
This fix ensures group(mode:"by") is correctly pushed down to the
storage layer.
(cherry picked from commit 881f27fe6fd43c96eff0039d75c2a6c9dad11182)
=> Call storage.Group API to correctly map group mode

query/functions.go
These functions, when used on non-float types in subqueries, would
return incorrect results as the type system thought they would return a
different type than the actual implementation would return.
=> Marked functions that always return floats as always returning floats

go.mod, go.sum
We were using a fork, but the change introduced in that fork has since
been merged upstream.
Closes #10626.
=> chore: use upstream version of kin-openapi

api-compat.Jenkinsfile
To get CI sorted out, we need the 2.x Jenkinsfile to have a different
name from the 1.x Jenkinsfile.
=> ci: rename api-compatibility Jenkinsfile

ui/src/organizations/components/ScraperList.tsx, ui/src/organizations/components/ScraperRow.tsx, ui/src/organizations/components/Scrapers.tsx, ui/src/organizations/containers/OrganizationView.tsx
Closes #10795 
Add scrapers tab to organizaitons page with create button and delete button to the list
=> Add Scrapers tab to Organizations page

etc/config.sample.toml, services/httpd/config.go, services/httpd/handler.go
New configuration:
```toml
[http]
flux-log-enabled = true
```
will produce log entries similar to:
```
ts=2019-01-11T14:47:46.124347Z lvl=info msg="Executed Flux query" log_id=0CwLysq0000 service=httpd compiler_type=flux response_size=1467 query="from(bucket:\"test\") |> range(start: -5000h) |> limit(n:5)" stat_total_duration=3.949ms stat_compile_duration=3.183ms stat_queue_duration=0.026ms stat_plan_duration=0.055ms stat_requeue_duration=0.000ms stat_execute_duration=0.668ms stat_max_allocated=3200 stat_concurrency=1
```
=> Add support for optionally logging Flux queries

Jenkinsfile
Master is switching to 2.x development today, and we are not going to
continue using the changelog strategy we used in 1.x.
=> Only update the changelog on 1.x branches

http/swagger.yml
Closes https://github.com/influxdata/platform/issues/2264
add swagger doc for frontend.
To start scrape a target, make a post request to create a new scraper target.
To stop scrape a target, make a delete request to the scraper target endpoint
=> feat(http): add scraper target swagger

ui/src/dashboards/components/VEOHeader.tsx, ui/src/dataExplorer/components/DataExplorerPage.tsx, ui/src/me/components/Resources.tsx, ui/src/me/components/account/Account.tsx, ui/src/me/components/account/__snapshots__/Account.test.tsx.snap, ui/src/pageLayout/containers/Nav.tsx, ui/src/shared/components/TimeMachine.scss, ui/src/shared/components/TimeMachineBottom.tsx, ui/src/shared/components/TimeMachineControls.tsx, ui/src/shared/components/TimeMachineQueriesSwitcher.tsx, ui/src/shared/components/VisOptionsButton.tsx, ui/src/shared/components/tabbed_page/TabbedPage.scss, ui/src/shared/components/view_options/ViewTypeDropdown.tsx
Closes #11010 
Closes #11009 
Closes #11007 
Closes #10970 
Closes #10979 
Moved `ViewTypeDropdown` to page header in VEO & DE
Also converted the tab controller into a single button (also in page header)
Increased contrast on tabbed page tab controllers:
=> Misc. UI Improvements

ui/mocks/dummyData.ts, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/actions/steps.ts, ui/src/onboarding/apis/index.ts, ui/src/onboarding/apis/mocks.ts, ui/src/onboarding/components/AdminStep.test.tsx, ui/src/onboarding/components/AdminStep.tsx, ui/src/onboarding/components/OnboardingStepSwitcher.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx, ui/src/onboarding/reducers/steps.ts
Currently the api returns an error for get requests to the /telegrafs endpoint. Formerlly the ui would make that request to see if the config was already created to determine whether to update an existing config or create a new one. This check and update were removed until that fix is made to make onboarding work.
Additionally, we now store the organization id returned from setting up an admin since a telegraf post request now requires it.
=> Update onboarding to be able to make telegraf configs

bolt/telegraf.go, cmd/influx/setup.go, inmem/telegraf.go, telegraf.go, testing/telegraf.go
Closes #11018 
When, given an organization ID, there are not `platform.TelegrafConfig`s associated with it, the `FindTelegrafConfigs` methods should return an empty slice rather than error out.
=> fix(telegrafconfigs): find by organization ID

bolt/dashboard.go, bolt/lookup_service_test.go, dashboard.go, http/dashboard_service.go, http/dashboard_test.go, http/proto.go, http/proto_test.go, inmem/dashboard.go, testing/dashboards.go
Closes https://github.com/influxdata/influxdb/issues/10778
This PR adds `OrganizationID` to dashboards supports filtering by organization id via the API.
=> Add organization to dashboards

http/cur_swagger.yml, http/swagger.yml, ui/src/api/api.ts, ui/src/onboarding/actions/dataLoaders.ts
Closes #11030
In https://github.com/influxdata/influxdb/pull/11029 the get and update of telegraf plugins were removed because the get request was returning an error. This pr will add that get back in to check if there is an existing telegraf configuration. if there is, it will update that one rather than creating a new one. Additionally, this makes sure that during an update the influxdb_v2 output plugin is included.
=> fix(ui/dataLoaders): Add check for existing configs for update

appveyor.yml
This should restore appveyor builds on PRs, although getting the build
to work properly is still outstanding:
https://github.com/influxdata/influxdb/issues/10937
=> ci: stop whitelisting appveyor branches

.circleci/config.yml
The project is currently using goreleaser to manage building nightly binaries, docker images and uploads to s3.
The tool has a strict dependency on semantic versioned tags. InfluxDB history does not have a valid semantic tag causing the tool to fail. This commit creates a valid tag for the current time to allow nightly builds to continue.
=> chore(ci): Fix nightly build bug

ui/src/me/components/account/ViewTokenOverlay.tsx, ui/src/me/components/account/__snapshots__/ViewTokenOverlay.test.tsx.snap
Closes #11005
Removed hardcoded token permission data from token overlay and use the api response that includes the permissions.
=> Remove hard coded token permissions and uses api response instead

ui/src/dataExplorer/components/SaveAsButton.test.tsx, ui/src/dataExplorer/components/SaveAsButton.tsx, ui/src/dataExplorer/components/SaveAsTaskForm.tsx, ui/src/dataExplorer/components/__snapshots__/SaveAsButton.test.tsx.snap, ui/src/tasks/components/TaskForm.scss, ui/src/tasks/components/TaskForm.test.tsx, ui/src/tasks/components/TaskForm.tsx, ui/src/tasks/components/TaskHeader.tsx, ui/src/tasks/components/TaskScheduleFormField.tsx, ui/src/tasks/components/__snapshots__/TaskForm.test.tsx.snap, ui/src/tasks/containers/TaskEditPage.tsx, ui/src/tasks/containers/TaskPage.tsx, ui/src/tasks/reducers/v2/index.ts
Closes #10896
This PR adds the `TaskForm` component to the Save As overlay in the Data Explorer to create a new task with the active query in the explorer.
Also adds form validation, so that a task can only be saved if it has a name, a schedule (interval/cron), and a script.
=> Add save query as task functionality to Data Explorer

cmd/influx/authorization.go, cmd/influx/bucket.go, cmd/influx/main.go, cmd/influx/organization.go, cmd/influx/query.go, cmd/influx/repl.go, cmd/influx/task.go, cmd/influx/user.go, cmd/influx/write.go
Closes #10995 
This PR represents an attempt to standardise our CLI as suggested by @edd in the referred issue.
Rules
- ID always completely uppercase
- Custom help message for all commands and subcommands, starting with an uppercase word too
- Commands short (and long) descriptions starting with an uppercase word
- Flags descritions starting with an uppercase 
---
=> Standardise CLI

http/cur_swagger.yml, http/swagger.yml, ui/mocks/dummyData.ts, ui/src/api/api.ts, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/apis/index.ts, ui/src/onboarding/apis/onboarding.test.ts
Add organization ID to TelegrafsRequest schema in swagger and cur_swagger,
Update generated api client, 
Update consumers of generated client to add organizationID to telegrafs POST requests, and not try to send organizationID in request parameters
=> Add organizationID to telegrafsRequest schema

task/validator.go
fixes #10987
When task validation returns an error it should be of the bas model errors type so that the api can determine what status codes to return. This allows us to return the proper 400 status code when its an invalid request.
=> Make task validation errors more clear

ui/src/shared/components/view_options/TableOptions.tsx
Closes #11077 
Previously, the `SortBy` dropdown was crashing when field options could not be fetched from the server.
This PR ensures that the `SortBy` dropdown is only rendered if the field options array has at least one item.
=> Only render SortBy dropdown if FieldOptions exist

ui/src/shared/components/TimeMachineQueries.tsx, ui/src/shared/reducers/v2/timeMachines.test.ts, ui/src/shared/reducers/v2/timeMachines.ts
Closes #11021
When switching from query builder to editor and back, query should be
persisted
=> Remember query from query builder

authorizer/authorize.go, authorizer/org.go, authorizer/org_test.go, authorizer/util_test.go, errors.go, http/api_handler.go, http/errors.go, testing/util.go
This PR introduces an `authorizer` package that is used to authorize service methods. It pulls the authorizer from context and uses it to authorize an action.
=> Authorize organization requests.

ui/src/shared/components/tables/TableGraphs.tsx, ui/src/shared/components/tables/TableSidebarItem.tsx
TableGraphs.tsx line 96/93 was an assignment `=` overwriting `tables` rather than an equality check `===`, and this was editing the name of the first table with the one user selected- making it so selecting a table would cause no change in the data being visualized. 
fixed that and changed the name of the getter to disambiguate from state variable called `selectedTableName`
=> Prevent in place editing of tables that broke table selection

authz.go
The set of permissions that a user was given during a session did not contain the appropriate permission to view/create resources for an organization. This PR special cases the organization permission to allow for read/create permissions for an organization.
=> fix(influxdb): special case the orgs resource when generating permissions

Makefile
This enables workflows that use `go mod edit` commands to rely on the
Makefile correctly rebuilding the Go binaries.
=> chore: add go.mod and go.sum to list of Go sources

ui/src/organizations/apis/index.ts, ui/src/organizations/components/ScraperList.tsx, ui/src/organizations/components/ScraperRow.tsx, ui/src/organizations/components/Scrapers.tsx, ui/src/organizations/containers/OrganizationView.tsx
Closes #10786
This PR adds an API call to delete a scraper from the organizations page. It also updates the empty state text for the scrapers tab.
=> Add ability to delete a scraper from an organization

ui/src/clockface/components/overlays/Overlay.scss, ui/src/clockface/components/overlays/OverlayFooter.tsx, ui/src/clockface/index.ts, ui/src/shared/components/TimeMachineQueriesSwitcher.scss, ui/src/shared/components/TimeMachineQueriesSwitcher.tsx, ui/src/shared/copy/v2/index.ts
Closes #11115 
Use the Clockface overlay components instead of the browser dialog
=> Use Clockface Overlay when confirming switch from editor to builder

http/api_handler.go, http/bucket_service.go, http/bucket_test.go, http/org_service.go, http/org_test.go, http/write_handler.go
Link https://github.com/influxdata/flux/issues/875
Previously, we blanket wrapped all instances of `OrganizationService` and `BucketService` with a variation that authorized actions. This however lead to a weird situation where in order to write data to a bucket, you needed to have both read and write access to the bucket, as well as read access to an organization. This was unintuitive and wrong. Instead, we now only wrap the services for the direct action that is being performed.
We also now resolve organization names to ID in the organization http handler before we attempt to create a bucket, so that we can more easily check the that the action is authorized.
Additionally, we modified the errors returned by the write handler so that they more …
=> fix(http): use wrapped org/bucket services only when required

authorizer/macro.go, authorizer/macro_test.go, authz.go, http/api_handler.go
Closes #11201
This PR introduces a macro service for authorizing requests.
=> Authorize macros

gather/metrics.go, gather/metrics_test.go
Scraping was enriching the tag set by adding the
prometheus data type in the tag key name, "type."
If a scraped metric already had the tag, "type," then
this would cause errors far away from problem in flux.
Co-authored-by: Kelvin Wang <sherkrainwang@gmail.com>
Closes #11054
=> fix(scraper): remove enriched type label

ui/src/shared/constants/fluxFunctions.ts
The documention for `group` used the old function signature. Updated
with the most recent from the spec.
=> fix(ui): update the flux doc for group

authorizer/telegraf.go, authorizer/telegraf_test.go, http/api_handler.go
Closes https://github.com/influxdata/influxdb/issues/11159
TODO:
Closes Part of #10814 
This PR introduces a bucket service for authorizing requests.
=> feat(authorizer): add telegraf authorizer

fs/proto.go
Closes #11178
Directory was previous read and write but not execute.  Now, it is improved with execute!
=> fix(fs): fix proto dir permission from rw to rwx

ui/src/Logout.tsx, ui/src/Signin.tsx, ui/src/me/components/LogoutButton.tsx, ui/src/onboarding/components/SigninForm.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx, ui/src/onboarding/containers/SigninPage.tsx, ui/src/pageLayout/containers/Nav.tsx
Closes #
-  Redirects to `/me` after signin or onboarding exit 
- Also, fixes an issue where failed sign in notifications were not being displayed until after signin.
- Changes index route to redirect to `/me`
=> feat(ui): login redirect to /me 

ui/src/configuration/components/ConfigurationPage.tsx, ui/src/dashboards/components/VEO.scss, ui/src/me/components/Resources.tsx, ui/src/pageLayout/containers/Nav.tsx
- Rename `My Settings` to `Profile`
- Rename `My Tokens` to Tokens`
- Shrink horizontal padding on VEO (optimize space)
=> A Modest Polish PR

ui/src/shared/utils/renderQuery.ts
Closes #11175 
Also lowers the `DESIRED_POINTS_PER_GRAPH` constant so that queries return faster. Once Flux becomes more efficient at windowing, we should increase this constant again.
=> Ensure computed windowPeriod is an integer

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/dashboards/apis/v2/index.ts, ui/src/protos/actions/index.ts, ui/src/protos/apis/index.ts, ui/src/protos/reducers/index.ts, ui/src/store/configureStore.ts, ui/src/types/v2/index.ts, ui/src/utils/api.ts
doesn't close anything, but creates the infrastructure for loading protos, and instantiating dashboards from them
next, can create protos themselves, and decide when we want to call these functions
=> Add protos state in redux and create protos API infrastructure

http/cur_swagger.yml, http/query.go, http/query_handler.go, http/query_test.go, http/swagger.yml
Fixes #10745
This change means that 1.x and 2.x should be in sync, and the easy way to curl a query to the server is using the `application/vnd.flux
```
curl -XPOST -sS -H 'Authorization: Token foo:pass' -H accept:application/csv -H 'content-type:application/vnd.flux' http://localhost:9999/api/v2/query -d 'from(bucket:"test") |> range(start:-1000h) |> group(columns:["_measurement"], mode:"by") |> sum()'
```
=> feat(http): add vnd.flux content-type support

http/user_resource_mapping_service.go, http/user_resource_mapping_test.go
There was an extra s in owner links, for example:
{"links":{"self":"/api/v2/taskss/034356818538f000/owners"},"users":[]}
All of the ResourceType values in authz.go already are plural, so I am
fairly certain that the extra s was just a typo all along.
=> fix(http): fix typo in owner/member links

ui/src/dataLoaders/components/DataLoadersWizard.tsx, ui/src/dataLoaders/components/StepSwitcher.tsx, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.test.tsx, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx, ui/src/onboarding/components/configureStep/Scraping.tsx, ui/src/organizations/components/BucketList.tsx, ui/src/organizations/components/CollectorList.tsx, ui/src/organizations/components/ScraperList.tsx, ui/src/organizations/components/ScraperRow.tsx, ui/src/organizations/components/Scrapers.tsx, ui/src/organizations/containers/OrganizationView.tsx, ui/src/types/v2/dataLoaders.ts
Closes #10785
Clicking the Create scraper button on the scrapers tab in admin ui will open the the dataloaders wizard to the correct step and type. 
Additionally, fix a bug with creating scrapers.
=> feat(ui/dataLoaders): Add new scraper from scrapers tab

http/cur_swagger.yml, http/swagger.yml, telegraf.go, ui/src/api/api.ts, ui/src/onboarding/OnboardingWizard.scss, ui/src/onboarding/components/configureStep/streaming/PluginConfigForm.tsx, ui/src/onboarding/constants/pluginConfigs.ts, ui/src/types/v2/dataLoaders.ts
Closes #10886
Add links on the plugin forms to telegraf plugin docs.
Additionally fix a typo. `ngnix` -> `nginx`
=> Add additional info links to plugin forms

ui/src/tasks/components/TaskForm.tsx, ui/src/tasks/components/TaskScheduleFormField.tsx, ui/src/tasks/components/__snapshots__/TaskForm.test.tsx.snap
Closes #10843
This PR changes the `TaskForm` elements for the task interval to read "every" instead of "interval". Note that the app still uses the word "interval" for storing tasks in local state.
=> Change interval label in TaskForm to every

ui/src/onboarding/components/AdminStep.tsx, ui/src/onboarding/components/CompletionAdvancedButton.tsx, ui/src/organizations/components/BucketList.tsx, ui/src/shared/components/resource_fetcher/ResourceFetcher.tsx
Closes #11060
This PR sets the "Advanced" button in the onboarding to open the Data Loaders overlay in the buckets tab of the organizations page.
Also, this PR changes the "Next" behavior on the admin setup step of onboarding to wait for the admin setup API call to finish before going to the Completion step. This is so that the Completion step will have a bucket to add Data Loaders to when the user clicks the Advanced option.
=> Feat(adminui)/advanced data collection step

ui/src/organizations/components/DashboardList.tsx, ui/src/organizations/components/DashboardRow.tsx, ui/src/organizations/components/Dashboards.tsx, ui/src/organizations/containers/OrganizationView.tsx
Closes #11149
This PR creates a new component, `DashboardRow`, in the organizations page, with a button to delete the dashboard.
=> Add ability to delete a dashboard from the organizations page

ui/src/onboarding/components/verifyStep/DataListening.tsx, ui/src/shared/actions/v2/queryBuilder.ts, ui/src/shared/apis/v2/query.ts, ui/src/shared/apis/v2/queryBuilder.ts, ui/src/shared/components/TimeSeries.tsx, ui/src/types/promises.ts, ui/src/utils/restartable.test.ts, ui/src/utils/restartable.ts
Previously, outdated queries in the `TimeSeries` and `QueryBuilderFetcher` would run to completion even though their results were ignored.
Now, pending but outdated queries will be truly canceled via `XmlHttpRequest#abort`. This frees up server and network resources.
Closes #10801
=> Support true time series query cancellation

ui/src/dataLoaders/components/DataLoadersWizard.tsx, ui/src/dataLoaders/components/StepSwitcher.tsx, ui/src/onboarding/OnboardingWizard.scss, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/apis/index.ts, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.test.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx, ui/src/onboarding/components/selectionStep/StreamingSelector.test.tsx, ui/src/onboarding/components/selectionStep/StreamingSelector.tsx, ui/src/organizations/components/Collectors.tsx, ui/src/organizations/containers/OrganizationView.tsx
Closes #11234 
Closes #11048 
Add the ability to open to the collectors section of the dataloader wizard by clicking create collector.
Fix save telegraf action so that it doesnt just update the same config over and over and you can add new configs.
=> feat(ui/dataLoaders): Add new collector from collectors tab

authorizer/user.go, authorizer/user_test.go, authz.go, bolt/session.go, http/api_handler.go, testing/session.go
This PR introduces a user service that authorizes actions. It additionally grants users the permission to view themselves.
=> feat(influxdb): add authorization for user actions

authorizer/auth.go, authorizer/auth_test.go, http/api_handler.go
Closes part of #10814
This PR introduces an authorized authorization service.
=> add authorized authorization service

authorizer/source.go, authorizer/source_test.go, http/api_handler.go, source.go
Closes #11201
Closes part of #10814
This PR introduces a source service for authorizing requests.
=> Authorize sources

cmd/influx/task.go, http/api_handler.go, http/router.go, http/swagger.yml, http/task_service.go, http/task_service_test.go, http/task_test.go, task.go, task/platform_adapter.go, task/servicetest/servicetest.go, task/validator.go, task/validator_test.go
Closes #10876 
Actions on resources under an organization show the org id as well as the name. This should bring the tasks resource inline with the rest of the resources in the same category. It also grants the advantage of allowing the api to accept org name instead of org id when creating a task.
=> Show organization names in task api actions

http/api_handler.go, http/scraper_service.go, http/scraper_service_test.go, http/swagger.yml
Closes https://github.com/influxdata/influxdb/issues/11284
make the endpoint much simpler
=> fix(http): update scrapers endpoint

ui/src/dataExplorer/components/SaveAsTaskForm.tsx, ui/src/shared/components/TimeMachineQueryTab.scss, ui/src/shared/components/TimeMachineQueryTab.tsx, ui/src/shared/reducers/v2/timeMachines.test.ts, ui/src/shared/reducers/v2/timeMachines.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/containers/TaskPage.tsx
Closes #11228
- Fixes an issue where saving a query in the DE as a task would fail with a 400 error (the script was using variables that didn't exist)
- Moves the visibility icon to the left of the name in each query tab in the DE
- Fixes an issue where the query builder and graph were out of sync after switching from script mode to query builder mode
=> Misc alpha polish

tsdb/tsm1/engine_delete_measurement.go
If a bucket had bytes in it that would be escaped by the models
parser/package, then the index would not be correctly purged of those
series data when the bucket was dropped.
Closes #11153.
This PR ensures that when dropping a bucket or deleting from a bucket, the correct escaping happens.
=> Fix bucket delete for all buckets

ui/src/dataLoaders/components/DataLoadersWizard.tsx, ui/src/onboarding/actions/steps.ts, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.test.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx, ui/src/onboarding/components/verifyStep/DataListening.test.tsx, ui/src/onboarding/components/verifyStep/DataListening.tsx, ui/src/onboarding/components/verifyStep/DataStreaming.tsx, ui/src/onboarding/components/verifyStep/VerifyDataStep.test.tsx, ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.test.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.tsx, ui/src/onboarding/reducers/steps.ts
Closes #11048 
Clicking next on the scraper configure step closes the wizard rather than taking you to an empty verify step.
Remove progress bar from dataloaders wizard which allowed for the removal of step statuses.
Fix issue with not being able to click back on streaming selection step.
=> Remove empty scraper verify step and data loaders progress bar 

http/authentication_middleware.go, http/authentication_test.go, http/errors.go, http/session_handler.go, http/swagger.yml, ui/src/Signin.tsx, ui/src/onboarding/components/SigninForm.tsx
Closes #11022 
Closes #11143
- Adds a notification when a user is redirected to login after session timeout.
- Adds a notification when the user fails to sign in correctly
- **Bug fix:** update `http/authentication_middleware` to send `401` instead of different errors for either a bad username or `500` and `X-Influx-Error: crypto/bcrypt: hashedPassword is not the hash of the given password`.
=> fix(ui): add session timeout notification

chronograf/influx/influx.go, http/auth_service.go, http/bucket_service.go, http/dashboard_service.go, http/label_service.go, http/macro_service.go, http/onboarding.go, http/org_service.go, http/query_handler.go, http/scraper_service.go, http/source_proxy_service.go, http/source_service.go, http/user_resource_mapping_service.go, http/user_service.go, http/write_handler.go
This avoids leaking resources.
Found by manually inspecting results of `git grep -A5 -F '= hc.Do'`.
=> fix(http): ensure response body always closed

ui/src/logs/constants/index.ts, ui/src/onboarding/components/CompletionStep.test.tsx, ui/src/onboarding/components/CompletionStep.tsx, ui/src/onboarding/components/OnboardingStepSwitcher.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx, ui/src/shared/copy/notifications.ts
Closes #11186
Create scraper with url of http://localhost:9999/metrics when clicking quick start in the completion step for the onboarding wizard.
Notifications for creating and error
=> feat(ui/onboarding): Create default scraper when Quick Start is selected

ui/src/onboarding/constants/pluginConfigs.ts, ui/src/onboarding/reducers/dataLoaders.test.ts
Closes #11275
Removed procstat plugin from system bundles and updated tests
=> Remove procstat plugin from system bundles

bucket.go, query/preauthorizer.go
When trying to create a task that writes to an unknown bucket,
previously the error message would resemble:
could not find bucket {<nil> 0xc0000dfcc0 <nil> 0xc0000dfce0}: <not found> bucket not found
Now print something human-readable:
could not find write bucket with filter: [Bucket Name: b, Org Name: a]: <not found> bucket not found
=> fix(query): improve preauthorizer errors on unknown buckets

ui/src/dataLoaders/components/DataLoadersWizard.tsx
Fixes issue with after using the dataLoader, it clears state without reseting it when opening it again.
=> fix(ui/dataLoaders): Ensure correct starting step in data loading wizard

ui/src/shared/actions/v2/queryBuilder.ts, ui/src/shared/apis/v2/queryBuilder.ts, ui/src/shared/components/TagSelector.scss
Closes #10800 
- Caches metaqueries used in the query builder. This avoids the awkward reloading when switching between different queries. Before/after:
- Tweaks alignment of the `TagSelector` empty state. Before/after:
- Fixes an issue where the query builder would issue the following invalid metaquery:
```
import "influxdata/influxdb/v1"
v1.tagKeys(bucket: "a", predicate: (r) => , start: -30d)
|> filter(fn: (r) => r._value != "_field")
|> filter(fn: (r) =>
r._value != "_time" and
r._value != "_start" and
r._value !=  "_stop" and
r._value != "_value")
|> distinct()
|> limit(n: 200)
```
- Default first tag key selection to `_measurement` 
- Tweaks the formatting of issued metaqueries to aid in debugging
=>  Cache metaqueries used in query builder

authorizer/urm.go, authorizer/urm_test.go, bolt/organization.go, cmd/influxd/launcher/launcher.go, http/api_handler.go
This PR wraps a user resource mapping service with some that authorizes actions against the resource type used in the mapping.
cc @leodido
=> authorize user resource mapping operations

bolt/onboarding.go
When adding a org owner, the `UserResourceMappingService` add the owner to org's buckets:
https://github.com/influxdata/influxdb/blob/02cc100b4f56eaefabc521eba96fb1c12e5b75f1/bolt/user_resource_mapping.go#L81-L93
https://github.com/influxdata/influxdb/blob/02cc100b4f56eaefabc521eba96fb1c12e5b75f1/bolt/user_resource_mapping.go#L120-L140
---
In `OnboardingService.Generate` , Add a org owner after the org's bucket is created.
=> fix(bolt): create user mapping after bucket is created

http/handler.go
The API response time buckets had a fairly broad range.  I'm thinking we could narrow down the range.
Old:
```
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",status="2XX",le="0.001"} 0
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",status="2XX",le="0.0015"} 0
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",status="2XX",le="0.0022500000000000003"} 0
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",status="2XX",le="0.0033750000000000004"} 0
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",status="2XX",le="0.005062500000 …
```
=> feat(http): use default prom histogram buckets

http/task_service.go, task/options/options.go
The client expects influxdb.Error, so use them on the server.
Also clarify the message when the task option is missing.
=> fix(task): use formal errors during task creation

authorizer/secret.go, authorizer/secret_test.go, authz.go, bolt/secret.go, secret.go
Closes #11283 
This PR introduces a secrets service for authorizing requests.
=> Authorize secrets

cmd/influxd/launcher/launcher.go
Previously, scrapers were running every one minute.
=> feat(cmd/influxd): scrapers should run every ten seconds

ui/src/shared/components/view_options/TableOptions.tsx
Closes #11373
This PR prevents the result and table columns from being shown in the table options sidebar for a table graph, since they do not appear on the table graph itself.
=> Hide result and table columns from being shown in table options

task/platform_adapter.go, task/servicetest/servicetest.go
The response from a created task was missing the name field; now a test
ensures that response matches what is returned when listing tasks.
=> fix(task): populate created task response, the same as finding

ui/src/dashboards/utils/tableGraph.ts
Closes #11368 
Resolved field options was being calculated before excluding noisy columns, and this was causing a mismatch between what was in the table and how time column was being determined.
=> Resolve field options after excluding data in tables

ui/src/onboarding/components/configureStep/Scraping.tsx
Closes #11378
This PR changes the button text from "next" to "finish" for the configure scraping data step of the admin UI wizard. The verify scrapers step mentioned in the issue above seems to already have been removed from the wizard.
=> Change button text from next to finish for configure scraping step

ui/src/shared/components/Gauge.tsx, ui/src/shared/components/SingleStat.tsx, ui/src/shared/components/view_options/options/DecimalPlaces.tsx, ui/src/shared/utils/formatStatValue.ts
- Extract value formatting in the the `SingleStat` and `Gauge` components to a shared utility function
- Rewrite `SingleStat` for readability
- Implement the "auto" mode for a `DecimalPlaces` setting. For now, this will format integers with no digits after the decimal place, and will format rationals with 2 digits after the decimal place.
Closes #11370
=> Fix single stat and gauge value formatting

ui/src/clockface/components/dropdowns/Dropdown.scss, ui/src/clockface/components/dropdowns/DropdownItem.tsx
Align active and inactive items in dropdown menus via indentation
Ensure dropdown items have a higher specificity `text-align: left` so they don't inherit other alignments from parents
Closes #11383
=> Polish Dropdowns

ui/src/shared/utils/getMinDurationFromAST.test.ts
`getMinDurationFromAST` relies on `Date.now()` internally. Depending on the current time, the test for `getMinDurationFromAST` would sometimes fail due to floating point arithmetic inaccuracies.
This commit adds a bit of leeway so that the test won't fail due to tolerable floating point inaccuracies.
=> Fix flaky getMinDurationFromAST test

ui/src/organizations/components/BucketOverlayForm.tsx, ui/src/organizations/components/CreateBucketOverlay.tsx, ui/src/organizations/components/Retention.scss, ui/src/organizations/components/Retention.tsx, ui/src/organizations/components/RetentionDuration.tsx, ui/src/organizations/components/UpdateBucketOverlay.tsx, ui/src/organizations/constants/index.ts
Closes #11299 
Implementation wise, this splits validation logic somewhat awkwardly between the `CreateBucketOverlay` / `UpdateBucketOverlay` and `BucketOverlayForm`. It would be nice to have this all in one place, but I think we should reduce the duplication between the `CreateBucketOverlay` and `UpdateBucketOverlay` before consolidating any validation logic. In the interest of time, I opted to not do this right now.
=> Enforce minimum retention policy of 1 hour in UI

cmd/influx/bucket.go
=> fix(main): require either org or org-id when creating buckets

ui/src/dataExplorer/components/DataExplorer.tsx, ui/src/shared/actions/v2/queryBuilder.ts, ui/src/shared/apis/v2/queryBuilder.ts
Fixes an issue where a user would:
1. Use the Data Explorer
2. Navigate to an organization page and create a bucket
3. Navigate back to the Data Explorer
4. Not see the bucket
=> Clear query builder cache on Data Explorer load

authz.go
Closes #11344
Previously, we only allowed the token with the oper privileges create organizations. This PR makes it so that any org owner can create other organizations.
=> fix(influxdb): grant user privileges to create orgs

ui/src/clockface/components/wizard/WizardFullScreen.scss, ui/src/onboarding/containers/OnboardingWizardPage.tsx
Closes #11395
This PR creates an empty state for when the user reaches the `/onboarding` route when a user has already been set up. This page has a button to redirect the user to the home page.
=> Add page for hitting onboarding route with user already created

ui/src/organizations/components/Collectors.tsx, ui/src/organizations/components/Scrapers.tsx
Closes #11101 
Remove `<h1`> on tabs in favor of `FilterList` and `Input` controls
=> fix(ui): add filter list and input to scrapers/collectors

ui/src/logs/constants/index.ts, ui/src/onboarding/components/CompletionStep.tsx, ui/src/onboarding/constants/pluginConfigs.ts, ui/src/onboarding/reducers/dataLoaders.test.ts, ui/src/onboarding/reducers/dataLoaders.ts, ui/src/shared/copy/notifications.ts
use `http://localhost:9999/metrics` rather than `http://127.0.0.1:9999/metrics`
constant was originally made in the wrong location
=> Update scraper url to match quick start scraper url

ui/src/shared/utils/renderQuery.ts
Closes #11428
Extract import statement(s) and the query expression(s) from the query AST. Inject any UI-generated variables between these two statement blocks. Then submit the concatenated Flux query to the server.
We're opting to retrieve the AST here to base our work on a source of truth. This should help to avoid situations where the user submits an invalid query that is unintentionally made valid by hoisting import statements. We take a latency hit here, but this approach should at least be sufficient for an alpha release.
=> fix(ui): inject tvar statements between imports and body

http/scraper_service.go, http/scraper_service_test.go, ui/src/organizations/components/ScraperList.tsx, ui/src/organizations/components/Scrapers.tsx, ui/src/organizations/containers/OrganizationView.tsx
Previously, scrapers would not return if any bucket or org was missing.
Now, the bucket or org and their links will not be shown.
=> fix(http): if bucket or org do not exist, do not report

ui/src/shared/components/tables/TableCell.tsx, ui/src/shared/components/tables/TableGraph.tsx, ui/src/shared/components/tables/TableGraphTable.tsx, ui/src/shared/components/tables/TableGraphTransform.tsx
Closes #10834 
quick and hacky way to format any time column with dates using flux's `dataTypes` annotation headers
works with hiding/showing/moving/renaming columns.
=> feat(ui/tables): use dateTypes annotations for column formatting

ui/src/shared/components/Legend.tsx
Before:
After:
Revolutionary, really.
=> Fix misplaced emdash in hover legend

.circleci/config.yml
Trying to not get race tests killed by circle by decreasing the number of parallel tests run.
=> ci(circle): decrease the number of parallel race tests

cmd/influxd/launcher/launcher.go, cmd/influxd/launcher/launcher_test.go, gather/recorder.go, gather/scheduler.go, nats/server.go
Previously, scrapers would scrape the target 10 times.  This was
because each scraper subscriber was not put into a queue group.
I've added the queue group "metrics" and now we the subcribers
will only scrape the target once.
Additionally, I moved to using nats memory instead of nats file
store.  We don't need durability for scraper runs across restarts.
=> fix(gather): add all subscribers to a single nats queue group

prometheus/influx.go
The prometheus metric `influx_info` had the label `date`.  This was the build date, so, for clarity, I've renamed it `build_date`.
=> refactor(prometheus): rename date to build_date for clarity

docker/influxd/Dockerfile
Previously, we didn't have certs in our containers.
=> ci(docker): add ca-certificates to the docker build

cmd/influx/task.go
Runs are retried; tasks aren't.
Closes #11170.
=> chore(task): move 'task retry' command to 'task run retry'

ui/package.json, ui/src/localStorage.ts, ui/src/me/components/Resources.tsx, ui/src/shared/constants/index.ts
Closes #10818
Adds the first 7 characters of the latest commit hash next to the version stamp in the UI. For example, see the `Version 2.0.0 (5207308)` stamp in the lower right:
=> Display latest commit hash in UI

ui/src/shared/apis/v2/ast.ts, ui/src/shared/utils/getMinDurationFromAST.ts, ui/src/shared/utils/renderQuery.ts, ui/src/types/ast.ts
These types were lifted from the [Flux source](https://github.com/influxdata/flux/blob/master/ast/ast.go).
Eventually it would be nice to generate them directly from the source, rather than writing them by hand. This might prove a bit challenging, since Go's type system is at odds with TypeScript's (there are no union types in Go).
=> Add types for JSON representation of a Flux AST

ui/src/dataLoaders/components/DataLoadersWizard.tsx, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx, ui/src/onboarding/components/configureStep/streaming/PluginConfigForm.test.tsx, ui/src/onboarding/components/configureStep/streaming/PluginConfigForm.tsx, ui/src/onboarding/components/configureStep/streaming/PluginConfigSwitcher.test.tsx, ui/src/onboarding/components/configureStep/streaming/PluginConfigSwitcher.tsx, ui/src/onboarding/components/configureStep/streaming/TelegrafPluginInstructions.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx, ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx, ui/src/onboarding/reducers/dataLoaders.test.ts, ui/src/onboarding/reducers/dataLoaders.ts, ui/src/organizations/components/CollectorList.tsx, ui/src/organizations/components/CollectorRow.tsx, ui/src/organizations/components/Collectors.tsx, ui/src/types/v2/dataLoaders.ts
Closes #11273 
Clicking next from the plugin bundle selection will take you to a plugin information step.
on this step, you can name the telegraf config.
clicking on the sidebar will take you to a plugin form.
this form has no previous just a continue and clicking continue will take you to the plugin info step.
clicking continue on the plugin info step will move users to the verify step.
=> feat(ui/dataLoaders): Add telegraf plugin information step with config naming

authorizer/scraper.go, authorizer/scraper_test.go, bolt/scraper.go, bolt/scraper_test.go, gather/scraper_test.go, http/api_handler.go, http/mock/middleware.go, http/scraper_service.go, http/scraper_service_test.go, http/swagger.yml, inmem/scraper.go, inmem/scraper_test.go, mock/middle_ware.go, mock/scraper_service.go, scraper.go, testing/scraper_target.go
Closes https://github.com/influxdata/influxdb/issues/11237
add user resource mapping for scraper http endpoint.
user resource mapping become part of scraper creating transaction. 
when create the scraper, creator should become the owner.
when delete the scraper, related user resource mapping will be removed
=> Add urm scraper

authorizer/label.go, authorizer/label_test.go, authz.go, bolt/label.go, http/label_service.go, http/label_test.go, inmem/label_service.go, label.go, testing/label_service.go
Closes #11280 
Implementation of authorization layer for v2 labels.
Addition of `ResourceType` to `LabelMapping` struct and `LabelMappingFilter` struct since we need it to check for permissions on resources.
=> Labels authorizer

etc/config.sample.toml, tsdb/config.go, tsdb/config_test.go, tsdb/index/tsi1/index.go, tsdb/index/tsi1/index_test.go, tsdb/index/tsi1/testdata/line-protocol-1M.txt.gz, tsdb/index_test.go
This PR allows the TSI series id set cache (bitset cache) to be configured via the config. The new config option is as follows:
```toml
[data]
...
tsi-cache-size = 100
...
```
The value defaults to `100`. Setting the value to `0` will disable the cache completely. Disabling the cache can lead to query performance degradation. 
From a docs perspective, I would describe this setting as follows:
>The size of the internal cache used in the TSI index to store previously calculated series results. Cached results will be returned quickly from the cache rather than needing to be recalculated when a subsequent query with a matching tag key/value predicate is executed. Setting this value to 0 will disable the cache, which may lead to query performance issues. This value should only be increased if …
=> Allow TSI bitset cache to be configured

tsdb/series_set.go, tsdb/series_set_test.go, tsdb/tsi1/index.go
In the case of caching TSI bitmaps belonging to immutable .tsi files,
the underlying bitset data can be mmapped. It is possible, though rare,
for this data to be unmapped (e.g., via a TSI compaction) but for the
cached bitmap to be subsequently read. This leads to a segfault.
This only happens when copy-on-write is set to true on the roaring
bitmap, because in that case only the internal pointers are cloned.
This change will reduce the TSI cache performance by around 10%, which I
have deemed to account for only a few microseconds typically.
=> Remove copy-on-write when caching bitmaps

cmd/influx/main.go, cmd/influx/ping.go
For environments that do not have `nc`, `lsof`, `nmap`, `netstat`, but just a way to know if influxdb is up, this subcommand should work nicely.
I'll use it in Kubernetes with the nightly influxdb image, something like this:
```
...
containers:
- name: influxdb
image: quay.io/influxdb/influx:nightly
lifecycle:
postStart:
exec:
command:
- sh
- -c
- until influx ping; do echo waiting for influxd; sleep 1; done; influx setup -u $USERNAME -p $PASSWORD -o $ORGANIZATION -b $BUCKET -r 720 -t $INFLUX_TOKEN -f
...
```
=> feat: Add influx ping subcommand

errors.go, http/auth_service.go, http/auth_test.go, http/bucket_service.go, http/bucket_test.go, http/dashboard_service.go, http/dashboard_test.go, http/duration.go, http/errors.go, http/errors_test.go, http/handler.go, http/label_service.go, http/macro_service.go, http/macro_test.go, http/onboarding.go, http/org_service.go, http/paging.go, http/query.go, http/query_handler.go, http/query_handler_test.go, http/query_service.go, http/scraper_service.go, http/task_service.go, http/telegraf.go, http/user_resource_mapping_service.go, http/user_service.go, http/view_service.go, http/write_handler.go
Closes https://github.com/influxdata/influxdb/issues/10667
_Briefly describe your proposed changes:
Remove kit/errors from http package, all the http response error will now be influxdb.error
=> Http error cleanup

http/task_service.go, http/task_service_test.go
For an operation that looks up a task or a run, when that operation
fails, only set the status to 404 if that operation explicitly returns
ErrTaskNotFound or ErrRunNotFound.
It's possible that the operation could fail for a reason other than the
ID being invalid: for example, if there was an IO error preventing the
lookup from succeeding.
Harden that behavior with tests for the task handler.
Closes #11589.
=> fix(http): return 404 when task or run is not found

tsdb/tsi1/DESIGN.md
This PR adds an initial skeleton TSI design document. I plan to flesh the entire document out in due course, but for now my main goal was to have somewhere to add some general benchmarks around retrieval times in the index.
=> Add skeleton TSI design doc

task/backend/query_logreader.go, task/backend/storetest/logstoretest.go
This is necessary to return 404 from the HTTP handler.
=> fix(task): return ErrRunNotFound when finding run by ID

.circleci/config.yml
Closes #
- Add a conditional slack notification to litmus nightly job. The notification(s) will be sent to the #testing channel and wold contain a link to the build.
=> Add slack notifications to litmus nightly runs

query/iterator.go, query/math.go, query/math_test.go, services/continuous_querier/service.go
Added inline bit-shift absolute value for int64 type as per:
http://cavaliercoder.com/blog/optimized-abs-for-int64-in-go.html
Updated implementations in Iterator and the continuous query service
=> Fix bug with incorrect ABS results for negative integer values 

cmd/influx_tools/internal/errlist/errlist.go
References #4098 (Enable `golint` on codebase)
=> Fix linting errors in the errlist package

tsdb/engine/tsm1/ring.go
even though ringShards==paritions==16, i think it's better to mod the
length of the ring's partitions.
=> Hash ring's hash mod

releng/unit-tests/Dockerfile
Running OSS unit tests for the release is failing due to a missing `gcc`.
=> chore: install gcc

logger/config.go, logger/context.go, logger/fields.go, logger/logger.go
Golint logger to address issue #4098. Breaking change to exported logger package due to rename of ```LoggerFromContext```  to ```FromContext```.
=> Golint logger package

client/v2/client.go, client/v2/udp.go
A simple modification allowing to pass a context to the clientv2 when performing queries. This is most helpful when a client launches thru a reverse proxy a long read and closes the connection before the batch is finished.
Dummy example:
```golang
func readHandler(w http.ResponseWriter, r *http.Request) {
// snappy decode
// [...]
// protobuff unmarshall
// [...]
// spawn our influx client
influx, err := influxdb.New("http://<host>:8086", database, user, password)
if err != nil {
fmt.Println(err)
if r.Context().Err() == nil {
http.Error(w, fmt.Sprintf("can't spawn InfluxDB controller: %v", err),
http.StatusInternalServerError)
}
return
}
defer func() {
if err = influx.Close(); err != nil {
fmt.Println(err)
}
}()
// Build & perform request
// [...]
resp, err := influx.QueryCtx(r.Context(), …
```
=> clientv2 - QueryCtx()

tsdb/engine/tsm1/engine.go
This change fixes #10511 that manifests when a shard is considered cold
faster than its cache is snapshotted. This can happen if WAL is enabled
because previously the code only considered the last modification of
compacted tsm1 files. Instead Engine.LastModified() also takes the WAL
into account if necessary.
I haven't added a test to prevent regressions because I couldn't find a test that calls this code path and checks when a compaction is triggered (especially a full compaction). For that reason I've done some manual tests:
1. Generate default configuration: `$ influxd config > influxdb.conf`
2. Modify parameters: `sed -i -e 's/cache-snapshot-memory-size = .*/cache-snapshot-memory-size = "24k"/' -e 's/compact-full-write-cold-duration = ".*"/compact-full-write-cold-duration = "30s"/' …
=> Fix compaction logic on infrequent cache snapshots

ui/src/dataLoaders/components/BucketsDropdown.test.tsx, ui/src/dataLoaders/components/BucketsDropdown.tsx, ui/src/dataLoaders/components/collectorsWizard/select/StreamingSelector.tsx, ui/src/dataLoaders/components/configureStep/ScraperTarget.tsx, ui/src/dataLoaders/components/configureStep/Scraping.tsx, ui/src/dataLoaders/components/configureStep/__snapshots__/Scraper.test.tsx.snap
Closes #11585
Previously, both scrapers and telegraf configs had a dropdown for the buckets in which to write data. Now, there is a bucket component so that they use the same component
=> refactor(ui/dataLoaders): Update dataLoaders bucket dropdowns to be the same component

ui/src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx, ui/src/organizations/components/Collectors.tsx
The issue is that after the state for data loader type was cleared after completing the collectors setup flow, the type was getting reset to 'streaming/collectors'. The problem was from the type getting set on the component did mount for one of these components. This just changes where the type gets set.
=> fix(ui/dataLoaders): Set collectors data loading type in the correct place

CHANGELOG.md, ui/mocks/dummyData.ts, ui/src/dataLoaders/constants/pluginConfigs.ts, ui/src/dataLoaders/reducers/dataLoaders.test.ts
Closes #11584 
Swap was missing from the system telegraf plugin bundle. This pr will add that plugin.
=> fix(ui/dataLoaders): Add swap to system bundle

ui/src/dataLoaders/components/collectorsWizard/configure/PluginConfigForm.test.tsx, ui/src/dataLoaders/components/collectorsWizard/configure/PluginConfigForm.tsx
Name was no longer getting extracted from telegrafPlugin so the documentation link did not take you to the plugin's documentation.
=> fix(ui/dataLoaders): Update plugin form to use correct documentation link

CHANGELOG.md, ui/src/dataLoaders/components/collectorsWizard/configure/PluginConfigForm.tsx
Closes #11581
Update the wording in for the plugin config form button to say `Done` instead of `Continue`.
=> fix(ui/dataLoaders): Update plugin config button to 'Done'

CHANGELOG.md, ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx
Closes #11583
Change the continue button on the configure step of the Telegraf configuration page to be `Create and Verify` rather than `Continue`.
=> fix(ui/dataLoaders): Update the collectors configure step button to 'Create and Verify'

CHANGELOG.md, ui/src/dataLoaders/actions/dataLoaders.ts, ui/src/dataLoaders/components/verifyStep/CreateOrUpdateConfig.tsx, ui/src/dataLoaders/components/verifyStep/DataStreaming.tsx, ui/src/dataLoaders/reducers/dataLoaders.test.ts
Closes #11609
Rather than using the actual auth token for the telegraf config, the environmental variable `$INFLUX_TOKEN` will now get saved into the config.
=> feat(ui/dataLoaders): Use env var for telegraf config auth token

query/cursor.go, tsdb/engine/tsm1/iterator.gen.go, tsdb/engine/tsm1/iterator.gen.go.tmpl
Scanner objects and iterators often need a ValuerEval. This
object is created, often with a function call, and has at
least one interface in it, so it allocates storage. Then it's
dropped again right away. The only part of it that might be
subject to change is usually a map. While the map's contents
change over time, the actual map doesn't change for the
lifetime of the object.
So, in both iterators and scanners, stash the ValuerEval
and continue reusing it. On a query returning a fair number
of data points, this produces a small (<5% in practice)
improvement in observed performance, visible as a significant
reduction in time spent in runtime (mallocgc, newobject,
etcetera).
The performance improvement isn't big, but it's reasonably
easy to evaluate it and establish that it's a safe …
=> reuse ValuerEval objects

CHANGELOG.md, ui/src/clockface/components/dropdowns/Dropdown.scss, ui/src/dataExplorer/components/DashboardsDropdown.tsx
Closes #11538 
Show style for selected items in multi select dropdown
=> fix(ui): show checked on multidropdown

docker/influxd/Dockerfile
Include ca-certificates and tzdata in influxdb image.
=> chore(docker): Include ca-certificates

cmd/influxd/launcher/launcher_test.go, cmd/influxd/launcher/tasks_test.go, http/api_handler.go, http/task_service.go
This PR unwraps the authorized user resource mapping service for internal calls to the service. Calls directly `/api/v2/tasks/:id/{members,owners}` will still result in `Failed to create task: unsupported resource type tasks`, but creation of a task and setting of an owner of a task during creation should be possible.
TODO:
Note:
This does not solve the issue described in https://github.com/influxdata/influxdb/issues/11491
=> fix(http): use urm without authz where appropriate

CHANGELOG.md, cmd/influx/authorization.go, http/auth_service.go, http/auth_test.go
This PR undoes the work behavior that was added in https://github.com/influxdata/influxdb/pull/10947
=> fix(influxdb): revert functionality added in pr#10947

CHANGELOG.md, ui/src/organizations/components/CollectorList.tsx, ui/src/organizations/components/CollectorRow.tsx, ui/src/organizations/components/Collectors.tsx, ui/src/organizations/components/FetchTelegrafConfig.tsx, ui/src/organizations/components/TelegrafConfig.tsx, ui/src/organizations/components/TelegrafConfigOverlay.tsx
Closes #11605
Add a button on the telegraf collector's row to view the telegraf config which is shown in a readonly text editor. 
Update instructions button to be `Setup Details`
includes a missed changelog update
=> Add a button to view the telegraf config toml

scripts/post-install.sh, scripts/post-uninstall.sh
Amazon Linux 2 uses systemd. This PR adds support for Amazon Linux 2 in `influxd`'s `post-install.sh` and `post-uninstall.sh` scripts.
=> Use Systemd for Amazon Linux 2

scripts/post-install.sh, scripts/post-uninstall.sh
Amazon Linux 2 uses systemd. This PR adds support for Amazon Linux 2 in `influxd`'s `post-install.sh` and `post-uninstall.sh` scripts.
=> Backport: Use Systemd for Amazon Linux 2

http/bucket_service.go, http/dashboard_service.go, http/dashboard_test.go, http/label_service.go, http/onboarding.go, http/org_service.go, http/scraper_service.go, http/task_service.go, http/task_service_test.go, http/telegraf.go
As of https://github.com/influxdata/influxdb/pull/11362, we introduced resource type on to the labels struct. This type was not propagated to the various handlers that have label routes. This caused adding/updating labels to fail.
=> Pass resource type to generic resource handler for labels

CHANGELOG.md, ui/src/organizations/components/CollectorList.tsx, ui/src/organizations/components/CollectorRow.tsx, ui/src/organizations/components/Collectors.tsx, ui/src/organizations/components/TelegrafConfigOverlay.scss, ui/src/organizations/components/TelegrafConfigOverlay.tsx
Closes #11606
Move the Download Config button into the View config overlay.
=> feat(ui/dataLoaders): Move download config into view overlay

services/httpd/handler.go, services/httpd/handler_test.go
While using InfluxDB I have been getting several nil pointer dereference issues when hitting the `/api/v1/prom/read` endpoint. Specifically, the error looks like this:
```
[httpd] 127.0.0.1 - - [19/Dec/2018:15:43:13 -0500] "POST /api/v1/prom/read?db=mydb HTTP/1.1" 200 0 "-" "Go-http-client/1.1" b43f30ed-03ce-11e9-8001-54e1adf55cb9 135 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 26 [running]:
runtime/debug.Stack(0xc000bf6020, 0xc00012a500, 0xbefec938560986be)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc000bf6020, 0xc00012a500, 0xbefec938560986be, 0xf4a63c64, 0x1d49060, 0xc000273100, 0x137cca0, 0xc000bfa000)
/tmp/influx/src/github.com/influxdata/influxdb/services/httpd/ha …
```
=> [BUG FIX] Fix nil pointer dereference at /api/v1/prom/read

bolt/authorization.go, bolt/bucket.go, bolt/organization.go, bolt/user.go, bolt/user_resource_mapping.go, cmd/influxd/launcher/launcher.go, kv/auth.go, kv/auth_test.go, kv/bucket.go, kv/bucket_test.go, kv/kvlog.go, kv/kvlog_test.go, kv/org.go, kv/org_test.go, kv/service.go, kv/urm.go, kv/urm_test.go, kv/user.go
Closes #11716 
Closes #11718 
Closes #11719 
Closes #11720  
The PR moves Orgs, Buckets, Authorizations, and Users to their kv implementations.
=> Move org/bucket/auth/user services from bolt to kv

query/influxql/README.md, query/influxql/end_to_end_test.go, query/influxql/group.go
The selector will be normalized to the start time interval when `GROUP
BY time(X)` is present in the query.
Fixes #10747.
=> fix(query/influxql): normalize selectors when an interval is present

ui/src/shared/components/ColorDropdown.tsx, ui/src/timeMachine/components/view_options/ThresholdItem.tsx, ui/src/timeMachine/components/view_options/ThresholdList.scss, ui/src/timeMachine/components/view_options/ThresholdList.tsx
Closes #11786 
Improve clarity of feature by exposing `<=` (was previously obscured what operator was being use)
=> Polish Threshold Styles

ui/src/clockface/components/index_views/IndexList.scss, ui/src/clockface/components/tabs/NavigationTab.tsx, ui/src/clockface/components/tabs/TabContents.tsx, ui/src/clockface/components/tabs/TabContentsHeader.tsx, ui/src/clockface/components/tabs/Tabs.scss, ui/src/clockface/components/tabs/Tabs.tsx, ui/src/clockface/components/tabs/TabsNav.tsx, ui/src/clockface/index.ts, ui/src/organizations/components/Buckets.tsx, ui/src/organizations/components/Collectors.tsx, ui/src/organizations/components/Members.tsx, ui/src/organizations/components/OrgDashboardIndex.tsx, ui/src/organizations/components/OrganizationNavigation.tsx, ui/src/organizations/components/OrganizationTabs.tsx, ui/src/organizations/components/Scrapers.tsx, ui/src/organizations/containers/OrganizationView.tsx
Previously the organization view component was using TabbedPage to generate the side bar tabs and tabs section for sections of the organizations/admin ui. This component does a lot of functionally similar things to react-router rather than using react router. This pr is a precursor to another pr that will create separate pages for the admin ui organization tabs that will render the organization navigation tabs and only the appropriate tab.
=> refactor(ui): Separate tab navigation from tabs in organization view

cmd/influxd/launcher/launcher.go, kv/label.go, kv/label_test.go, kv/service.go
Closes #11724 
This PR migrates labels to kv.
=> feat(kv): implement labels generically on kv

ui/src/index.tsx, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/TaskRunsPage.tsx, ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap, ui/src/tasks/dummyData.ts
Closes #11501 
Updated route to display new page when clicked on view runs on tasks page. Using dummy data to display the runs, will create a new card to update the client and use the api response once the api is fixed.
=> Create Tasks Run Page for dispalying runs for specific TaskID

CHANGELOG.md, ui/src/organizations/components/ScraperList.tsx, ui/src/organizations/components/ScraperRow.tsx, ui/src/organizations/components/__snapshots__/Scrapers.test.tsx.snap
Closes #11811 
Add scraper name as the first column in the scrapers list.
Allow for renaming of this scraper.
No longer allow url to updated from this list.
=> feat(ui): Display scraper name in scrapers list

CHANGELOG.md, ui/src/shared/components/EditableName.tsx
Closes #11818 
Update Editable Name to not allow empty string for name
=> Update Editable name to not allow empty string inline edit

CHANGELOG.md, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/TasksList.tsx, ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap, ui/src/tasks/components/__snapshots__/TasksList.test.tsx.snap, ui/src/tasks/containers/__snapshots__/TasksPage.test.tsx.snap
Closes #10902 
Update tasks list and task row to display the new column for last completed task run
=> Update TasksList to display last run date

pkg/tracing/context.go, query/executor.go, tsdb/index/tsi1/cache.go
This commit changes `name`, `key`, and `value` to from `[]byte` to `string`.
=> Convert TagValueSeriesIDCache to use string fields.

http/swagger.yml
This PR fixes the return type in the swagger documentation of the /get/macros route to be an array instead of a single macro.
=> Change return type of get/macros to an array

cmd/influx/task.go, cmd/influxd/launcher/tasks_test.go, http/swagger.yml, http/task_service.go, http/task_service_test.go, mock/task_service.go, task.go, task/platform_adapter.go, task/servicetest/servicetest.go, task/validator.go, task/validator_test.go
With the ongoing authorization work, creation arguments will differ from
what's returned on reads. More specifically, creation will accept a
token, but reads will report back a token ID.
This refactor facilitates that authorization work, and also brings the
code closer to the swagger definition, for the TaskCreateRequest type in
particular.
=> refactor(task): extract TaskCreate struct

tsdb/index/tsi1/cache.go, tsdb/index/tsi1/cache_test.go
=> Ensure that cached series id sets are Go heap backed

CHANGELOG.md, ui/src/tasks/components/RunLogsOverlay.tsx, ui/src/tasks/components/TaskRunsList.tsx, ui/src/tasks/components/TaskRunsPage.tsx, ui/src/tasks/components/TaskRunsRow.tsx, ui/src/tasks/components/TasksList.tsx, ui/src/tasks/dummyData.ts
Closes #11500 
Create an overlay to display the log data returned for a specific task. Using dummyData for now, until the run api is updated
=> Add the ability to view logs for a specific task run

cmd/influxd/launcher/launcher.go, kv/macro.go, kv/macro_test.go, kv/secret.go, kv/secret_test.go, kv/service.go, kv/session.go, kv/session_test.go, kv/source.go, kv/source_test.go
Closes #11727
This PR moves the bolt implementation of the macro, source, session, and secret services to the generic kv store.
=> Migrate {macro, source, session, secret} service from bolt to kv 

CHANGELOG.md, ui/src/dataLoaders/components/verifyStep/CreateOrUpdateConfig.test.tsx, ui/src/dataLoaders/components/verifyStep/CreateOrUpdateConfig.tsx
Closes #11783
Rather than creating  a template dashboard on every telegraf config creation and update, a template dashboard will only get created when the telegraf config gets created.
=> fix(ui): Ensure template dashboard only gets created on config creation

CHANGELOG.md, ui/src/clockface/components/wizard/WizardOverlay.scss, ui/src/clockface/components/wizard/WizardOverlay.tsx, ui/src/dataLoaders/components/DataLoadersOverlay.scss, ui/src/dataLoaders/components/DataLoadersWizard.tsx, ui/src/dataLoaders/components/collectorsWizard/CollectorsStepSwitcher.tsx, ui/src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx, ui/src/dataLoaders/components/collectorsWizard/configure/ConfigFieldHandler.tsx, ui/src/dataLoaders/components/collectorsWizard/configure/PluginConfigForm.tsx, ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx, ui/src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx, ui/src/dataLoaders/components/collectorsWizard/verify/VerifyCollectorsStep.tsx, ui/src/dataLoaders/components/configureStep/ConfigureDataSourceSwitcher.tsx, ui/src/dataLoaders/components/configureStep/Scraping.tsx, ui/src/dataLoaders/components/side_bar/SideBar.scss, ui/src/dataLoaders/components/verifyStep/DataStreaming.tsx, ui/src/onboarding/OnboardingWizard.scss, ui/src/onboarding/components/OnboardingButtons.tsx
Co-authored-by: Daniel Campbell <metalwhirlwind@gmail.com>
Closes #11782
Fix overlapping button bug.
Clean up and consolidate some dataLoading styles so future styling issues arent so difficult to resolve.
=> Fix overlapping buttons and clean up data-loading styles

http/swagger.yml
This PR updates the shape of the `QueryMacroProperties` type on the Macros spec to match the implementation.
=> Add values and language properties to QueryMacroProperties

bolt/onboarding.go, cmd/influxd/launcher/launcher.go, http/swagger.yml, kv/auth.go, kv/bucket.go, kv/onboarding.go, kv/onboarding_test.go, kv/org.go, kv/service.go, kv/urm.go, kv/user.go, onboarding.go, testing/onboarding.go
Closes #11883
Implement onboarding service with kv store.  Also, I took the opportunity to make the onboarding a single transaction.
=> feat(kv): add kv onboarding service

http/macro_test.go, http/swagger.yml, macro.go, macro_test.go
This PR adds an orgID to the Macro type in the swagger documentation
=> Add orgID property to Macro (variable) type in swagger

http/swagger.yml
This PR will add required properties to the Macro (Variable) type in the Swagger documentation
=> Add name, orgID, and arguments as required properties to Macro type

macro.go, package-lock.json, ui/package-lock.json, ui/package.json, ui/src/organizations/components/CreateVariableOverlay.tsx, ui/src/organizations/components/VariableRow.tsx, ui/src/organizations/components/Variables.tsx, ui/src/organizations/components/VariablesList.tsx, ui/src/organizations/containers/OrgBucketsIndex.tsx, ui/src/organizations/containers/OrganizationView.tsx, ui/src/tasks/components/TaskForm.tsx
Closes #11808 
Closes https://github.com/influxdata/applications-team-issues/issues/285
This PR allows the user to create a new template variable from the organizations page.
Next steps are to add update and delete capabilities to variables from this page.
=> Add ability to create a new template variable

ui/mocks/dummyData.ts, ui/src/organizations/components/VariableList.tsx, ui/src/organizations/components/VariableRow.tsx, ui/src/organizations/components/Variables.test.tsx, ui/src/organizations/components/Variables.tsx, ui/src/organizations/components/__snapshots__/Variables.test.tsx.snap, ui/src/organizations/containers/OrganizationView.tsx, ui/src/shared/copy/notifications.ts
Closes: https://github.com/influxdata/applications-team-issues/issues/286
This PR adds a button to the `VariableRow` component that allows the user to delete a variable.
=> Add ability to delete a variable from organizations page

ui/src/shared/utils/renderQuery.ts
=> Display more helpful errors when fetching AST fails

ui/src/minard/components/Histogram.tsx, ui/src/minard/components/HistogramTooltip.tsx, ui/src/minard/components/Plot.tsx, ui/src/minard/utils/useMousePos.ts, ui/src/shared/components/HistogramTooltip.scss, ui/src/timeMachine/components/view_options/HistogramOptions.tsx
Adds an empty state to the histogram "Column" option:
Updates the tooltip positioning so that it can overflow the `Plot` component. It will detect collisions with the edge of the screen instead:
=> Histogram polish

http/swagger.yml
This PR fixes the return type of the get by ID route for a task in the Swagger documentation.
=> Update return type for get/task route

ui/mocks/dummyData.ts, ui/package-lock.json, ui/package.json, ui/src/organizations/components/CreateVariableOverlay.tsx, ui/src/organizations/components/VariableList.tsx, ui/src/organizations/components/VariableRow.tsx, ui/src/organizations/components/Variables.tsx, ui/src/organizations/containers/OrganizationView.tsx
This PR renames the imports from the generated client library from "Macro" to "Variable"
=> Rename Macro to Variable in generated client imports

cmd/influx/task.go
Setting the authorizer from the HTTP client wasn't necessary, and
looking up the token to do so didn't work as written.
Fixes #11903.
=> fix(cmd/influx): don't set authorizer context when creating task

task/backend/scheduler.go, task/backend/scheduler_test.go, task/mock/scheduler.go
This was a missed case from #11817.
This case currently occurs when creating a task through the UI, using a
session rather than a full-fledged authorization. It doesn't fix that
case yet, but at least it will log an informative message.
=> fix(task): recover when call to execute fails

ui/src/organizations/components/Variables.tsx
This PR fixes an error when filtering variables.
=> Remove unnecessary search term from Variables filter

CHANGELOG.md, ui/src/organizations/components/OrgTasksPage.tsx, ui/src/shared/copy/v2/notifications.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/components/TaskRow.test.tsx, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/TasksList.tsx, ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap, ui/src/tasks/containers/TasksPage.tsx
Closes #10903 
Update task row to have a button to run task manually
=> Add the ability to run a task manually

cmd/influx/task.go, cmd/influxd/launcher/tasks_test.go, http/task_service.go, http/task_service_test.go, task.go, task/backend/inmem_logreaderwriter.go, task/backend/query_logreader.go, task/backend/scheduler_test.go, task/backend/store.go, task/backend/storetest/logstoretest.go, task/platform_adapter.go, task/servicetest/servicetest.go, task/validator.go, task/validator_test.go
Task ID is now a required value on run and log filters. It was
effectively required by all implementations before anyway, so now those
types reflect that requirement.
Organization ID was removed from those same fields. The TaskService
looks up the organization ID via the task in cases where we need it at a
lower layer.
Closes #11807.
=> refactor(task): remove explicit org from run/log lookup

tsdb/index/inmem/meta.go
This commit changes the read lock to a write lock when calling the
`ids()` function because `ids()` can mutate the underlying series
ids slice.
=> Update tagKeyValue mutex to write lock.

CHANGELOG.md, ui/src/configuration/components/GetLabels.tsx, ui/src/organizations/components/GetOrgResources.tsx, ui/src/organizations/containers/OrgBucketsIndex.tsx, ui/src/organizations/containers/OrgDashboardsIndex.tsx, ui/src/organizations/containers/OrgMembersIndex.tsx, ui/src/organizations/containers/OrganizationView.tsx, ui/src/shared/components/FetchLabels.tsx, ui/src/tasks/components/TaskForm.tsx
Closes #11891
Adds ordering to labels and org resources
=> fix(ui): add ordering to org resources

tsdb/store.go
We're not allowed to access the s.epochs map without holding the mutex against shard creation and deletion, so create a copy of all of the epoch trackers we will need while we hold the mutex.
Closes #11967.
=> Fix some more shard epoch races

tsdb/store.go
We're not allowed to access the s.epochs map without holding the mutex against shard creation and deletion, so create a copy of all of the epoch trackers we will need while we hold the mutex.
Backport of #11970.
=> Backport fixes for epoch races.

ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/organizations/components/Variables.tsx, ui/src/shared/components/AddResourceDropdown.tsx
Closes #11913
This PR creates a new component, `AddResourceDropdown`. This component takes in a string `resource` and two functions, `onSelectNew` and `onSelectImport`. From this dropdown, the user can create a new resource by either creating it from scratch or by importing it.
=> Create a generic dropdown for creating/importing a resource

http/swagger.yml
Closes #11840 
This PR adds the get by ID route for a variable to the Swagger documentation
=> Add get variable by ID route to swagger.yml

ui/src/shared/components/Histogram.tsx, ui/src/shared/utils/useSetIdentity.ts
Closes #11953
Previously, opening the histogram options would cause the the histogram computation (binning algorithm) to rerun. Since this computation is rather expensive for large or high cardinality datasets, we only want to run it when absolutely necessary.
The computation would run on every rerender of the parent component, during which a `fill` prop was instantiated and passed to the `Histogram` component. Since the prop was reinstantiated on every render, its reference identity would change, and hence the binning computation would appear stale a run again.
This commit avoids reinstantiating this passed prop on every render with a custom hook.
=> Avoid unnecessary Histogram rerenders

ui/src/organizations/components/GetOrgResources.tsx
Fixes checking key in primitive or null types
Closes #11993 
Empty resources and primitive data types could cause the `in` operator to error and not load resources.
=> fix(ui): add guard for hasKey check

cmd/influx/setup.go
Closes https://github.com/influxdata/influxdb/issues/11893
Added check that password length is more then `8` on SetUp step.
=> Added password length check

http/scraper_service.go
Closes #11767
The problem is that the NewScraperBackend doesn't have associate UserService, UserResourceMappingService and LabelService.
=> NewScraperBackend doesn't have associate UserService, UserResourceMappingService and LabelService

CHANGELOG.md, ui/package-lock.json, ui/package.json, ui/src/shared/components/ClickOutside.tsx, ui/src/shared/components/TimeRangeDropdown.tsx, ui/src/shared/components/dateRangePicker/DatePicker.tsx, ui/src/shared/components/dateRangePicker/DateRangePicker.scss, ui/src/shared/components/dateRangePicker/DateRangePicker.tsx, ui/src/shared/constants/index.ts, ui/src/shared/constants/timeRanges.ts, ui/src/shared/utils/timeRangeVariables.ts, ui/src/timeMachine/components/flux_functions_toolbar/FluxFunctionsToolbar.scss, ui/src/timeMachine/utils/queryBuilder.test.ts, ui/src/timeMachine/utils/queryBuilder.ts
Closes #11692
Add a '
`Custom Time Range` option to the timerange dropdown that opens a calendar selection to choose the time range
Change the clickOutside component to listen to `mousedown` rather than `click`
Add react-datepicker as dependency
add stop to queries built by the query builder that default to `now()` if a custom time is not selected
=> feat(ui): Add custom time range option in time range dropdown

CHANGELOG.md, ui/src/organizations/components/Retention.tsx, ui/src/organizations/components/UpdateBucketOverlay.tsx
Closes #11915 
Updated handler for retention policy to update the type of retention policy and the state of bucket to take in default seconds
=> Update retention policy for bucket if time changes

CHANGELOG.md, ui/src/me/components/Resources.tsx, ui/src/onboarding/containers/SigninPage.tsx, ui/src/shared/components/VersionInfo.scss, ui/src/shared/components/VersionInfo.test.tsx, ui/src/shared/components/VersionInfo.tsx, ui/src/shared/components/__snapshots__/VersionInfo.test.tsx.snap, ui/src/shared/components/splash_page/SplashPage.scss
Closes #11779 
Move the version information into its own component that can be reused
Display version on the login page
=> feat(ui): Display version on login page

CHANGELOG.md, ui/src/configuration/components/LabelOverlayForm.scss
Closes #11860
Make the label preview shorter.
=> fix(ui): Update the label preview to be shorter

ui/cypress/e2e/explorer.ts, ui/cypress/fixtures/routes.json, ui/cypress/support/commands.ts, ui/src/timeMachine/components/TagSelector.tsx
Closes #11753
If the TagSelector is the first TagSelector then you cannot remove it.
=> fix(ui/explorer): empty tag selector

CHANGELOG.md, ui/package-lock.json, ui/package.json
Closes #11977
Update the client library to a version that clones labels when cloning a dashboard.
=> update client libarary dependency for dashboard cloning

ui/src/clockface/components/label/LabelSelector.scss, ui/src/clockface/components/label/LabelSelector.tsx, ui/src/clockface/components/label/LabelSelectorMenu.tsx, ui/src/clockface/components/label/LabelSelectorMenuItem.tsx, ui/src/configuration/components/RandomLabelColor.scss, ui/src/configuration/components/RandomLabelColor.tsx, ui/src/configuration/utils/labels.ts, ui/src/shared/components/EditLabelsOverlay.tsx, ui/src/shared/components/FetchLabels.tsx, ui/src/shared/components/ResourceLabelForm.scss, ui/src/shared/components/ResourceLabelForm.tsx
Closes #11624
Add resource label creation form when label is not present. Tune label filtering to not aggressively match labels not in the list to more easily enable user to create a new label. Add a random color button instead of a color dropdown which does not work well in the label list dropdown.
=> fix(ui): add label from resource labels editor

ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndexContents.tsx, ui/src/organizations/components/Buckets.tsx, ui/src/organizations/components/Collectors.tsx, ui/src/organizations/components/OrgTasksPage.tsx, ui/src/organizations/containers/OrganizationsIndex.tsx, ui/src/shared/components/Filter.test.tsx, ui/src/shared/components/Filter.tsx
Closes #11866 
Updates filterList to allow searching by inexact object paths using `labels[].name`. Label names are kept in sorted order and searched using binary search for a closest suffix and then checked for term inclusion.
=> fix(ui/FilterList): add filtering on labels

cmd/influx/setup.go
Closes #12048 
If retention duration is not set by default during a non-interactive setup, no retention policy is set (infinite).
```
$ ./influx setup -f -b prom -o prom -u prom -p prometheus
Your token has been stored in /Users/goller/.influxdbv2/credentials.
User    Organization    Bucket
prom    prom            prom
```
=> feat(cmd/influx): allow infinite retention in non-interactive setup

ui/src/clockface/components/index_views/IndexList.scss, ui/src/clockface/components/panel/Panel.scss
Ensure panels nested inside tabbed pages receive the depth styling
Remove deprecated classname from stylesheet
=> Cleanup Tabbed Page Nested Styles

ui/src/clockface/components/label/LabelSelector.scss, ui/src/shared/components/ResourceLabelForm.tsx
Closes #12056
Wrong default was set for form state.invalid and padding was required instead of margin.
=> fix(ui/resourceLabelForm): fix ResourceLabelForm invalid default

bolt/organization.go, cmd/influxd/launcher/launcher.go, cmd/influxd/launcher/launcher_test.go, cmd/influxd/launcher/storage_test.go, http/org_service.go, http/query_handler.go, http/swagger.yml, kv/org.go, storage/engine.go, storage/readservice/cursor.go, storage/series_cursor.go, storage/series_cursor_test.go, testing/organization_service.go
These changes modify the parameters to a series cursor request and render the intent explicitly; series keys returned by the cursor must never cross organization boundaries.
* `SeriesCursorRequest` takes a single `Name` parameter, specifying the 16-byte tsdb encoded org and bucket ID
* `seriesCursor` ensures the first 8 bytes of the measurement name returned from the series index matches the current organization ID
**Blocked by #12010**
=> Enforce single org for series key reads

.circleci/config.yml
- add a step to check if PR is from fork. If it is, then stop execution of the step and successfully return.
- Fix for https://github.com/influxdata/influxdb/issues/11965
Closes #
=> ci(litmus): do not run litmus tests on forked PRs

CHANGELOG.md, ui/src/onboarding/actions/index.ts, ui/src/onboarding/components/AdminStep.tsx, ui/src/shared/copy/notifications.ts
Closes #12028 
Update admin page to not proceed to next step if there is an error with passwords that are not 8 characters long
=> Update admin to show error if password is not 8 characters

http/swagger.yml
Connects #11612
update swagger to reflect that a post request to the telegraf config labels endpoint should return the label rather than a list of labels.
update the description for a post request to the dashboards labels endpoint's response
=> Update the swagger definition for a telegraf labels post response

ui/src/tasks/actions/v2/index.ts
Create task from the client expects the org name, not the org id. Org name is now being passed rather than org id.
=> update to use org name to create task

ui/src/dataLoaders/components/verifyStep/DataListening.test.tsx, ui/src/dataLoaders/components/verifyStep/DataListening.tsx, ui/src/organizations/selectors/index.ts, ui/src/shared/apis/v2/query.ts, ui/src/shared/components/TimeSeries.tsx, ui/src/timeMachine/actions/queryBuilder.ts, ui/src/timeMachine/apis/QueryBuilderFetcher.ts, ui/src/timeMachine/apis/queryBuilder.ts, ui/src/timeMachine/components/QueryBuilder.test.tsx
The `/api/v2/query` endpoint requires an organization or organization ID query parameter.
Previously, there existed a bug in the API where if the organization parameters were left off, the API would use the first organization created in the backend, rather than returning a 400 error.
We built the entire UI on top of this bug, but it has now been fixed. So in every location where we use the `/api/v2/query` endpoint, we need to supply an organization.
This commit updates all such locations to use the first organization present in our Redux store as the organization parameter, thus roughly reproducing the behavior of the load bearing bug.
This is just a quick fix. Long term, we will want to think about what organization queries should run under and build an appropriate UI around that design.
=> Fix query bug resulting from missing org ID

cmd/influx/setup.go
Signed-off-by: Julius Volz <julius.volz@gmail.com>
This tripped me up because the CLI does not actually create the directory it wants to write the token into, and at the same time the CLI always uses the user's home dir, while the server allows configuring the storage path (which is what I did, which is why the `~/.influxdbv2` didn't exist for the CLI to find). So that should probably also be fixed (create the dir if it doesn't exist) and configurable.
=> Check error when writing token file during setup

http/swagger.yml
The YAML parser used by the go-openapi libraries treats an unquoted y as
a boolean key, which will lead to a difficult-to-understand parser
error:
> types don't match expect map key string or int got: bool
See also https://yaml.org/type/bool.html.
=> fix(swagger): quote keys named "y"

http/task_service.go, http/task_service_test.go
Also set the generated token's description while we're here.
This enables us to use task's Authorization when we need to query the
system bucket to get run logs, etc. but we only have a Session.
Closes #11948.
=> fix(task): create authorizations for tasks, which can read their task

cmd/influxd/launcher/launcher.go, http/api_handler.go, http/query_handler.go
Previously the APIBackend understood only a ProxyQueryService,
but it needs to understand that there are two implementations of the
ProxyQueryService one for handling InfluxQL queries and one for handling
Flux queries. The names of the fields have been updated to make this
clear. As well as the FluxBackend is now initialized using the
FluxService explicitly.
=> fix(http): separate InfluxQL and Flux services

kv/dashboard.go, kv/org.go, kv/urm.go
Closes #12067
This PR attempts to add the user as an owner of an organization or dashboard when they are created. If the add fails, it logs an error, but still creates the resource.
=> Make user owner of org/dashboard on create

ui/src/minard/components/Histogram.tsx, ui/src/minard/components/HistogramBars.tsx, ui/src/minard/components/HistogramTooltip.tsx, ui/src/minard/index.ts, ui/src/minard/utils/bin.test.ts, ui/src/minard/utils/bin.ts, ui/src/minard/utils/findHoveredRowIndices.tsx, ui/src/minard/utils/getBarFill.ts, ui/src/minard/utils/getHistogramTooltipProps.ts, ui/src/minard/utils/isNumeric.ts, ui/src/minard/utils/plotEnvActions.ts, ui/src/minard/utils/plotEnvReducer.ts, ui/src/minard/utils/useLayer.ts, ui/src/shared/components/Histogram.tsx, ui/src/shared/utils/toMinardTable.test.ts, ui/src/shared/utils/toMinardTable.ts, ui/src/timeMachine/actions/index.ts
This PR contains some refactoring of the histogram implementation
- Improve the typing of various vis objects
- Use a different `Table` shape for plot layers that colocates data and data types
- Renames the "aesthetics" field of a plot layer to "mappings", since "aesthetics" is difficult to say, difficult to spell, and is less clear than "mappings"
=> Clean up histogram implementation

query/preauthorizer_test.go, query/stdlib/influxdata/influxdb/from.go, query/stdlib/influxdata/influxdb/from_test.go, query/stdlib/influxdata/influxdb/to.go, query/stdlib/influxdata/influxdb/to_test.go
Closes https://github.com/influxdata/flux/issues/114
there was a cyclic dependency between Flux and InfluxDB because of `from` being in Flux.
Now that `from` is in InfluxDB, pre-authorization can work for `from`.
I fixed every test that contained "https://github.com/influxdata/flux/issues/114" in the `Skip` reason.  
If there is something else I should be aware of, please tell me.
=> fix(query/stdlib/influxdb): make FromOpSpec a BucketAwareSpec

query/preauthorizer_test.go, ui/cypress/e2e/tasks.test.ts, ui/cypress/support/commands.ts
=> fix(e2e-tests): make task use default bucket from user fixture

gather/recorder.go, http/write_handler.go, mock/points_writer.go, query/stdlib/influxdata/influxdb/to.go, storage/engine.go, storage/engine_test.go, storage/points_writer.go, task/backend/point_logwriter.go
This PR adds context to the storage points writer. Where possible the context is plumbed through. If the caller invoking `WritePoints` does not have a context available a `context.TODO()` is used instead.
=> Add context to storage.PointsWriter

http/swagger.yml
I was trying to build the PHP client lib and the generation was failing due to path/name mismatch.
=> Fix Name of Label Path Var

ui/src/shared/copy/v2/notifications.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/TaskRunsList.tsx, ui/src/tasks/components/TaskRunsPage.tsx, ui/src/tasks/components/TaskRunsRow.tsx, ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap, ui/src/tasks/reducers/v2/index.ts
Closes #12120 
Connected tasks runs page with redux to use the state to get runs and display runs on the page
=> Update tasks runs to use the api instead of dummy data

http/swagger.yml, http/task_service.go, http/task_service_test.go, task_test.go
closes #11822 and #11781
This allows lookups by org name and makes the api more consistent.
=> feat(tasks): look up tasks by orgname

ui/cypress/e2e/explorer.test.ts
Closes #12193
Adds test for adding then removing a query. However, an empty query
with only spaces will not currently disable the de submit
=> test(ui/de): add test for deleting de query text

ui/cypress/e2e/explorer.test.ts, ui/src/timeMachine/components/TimeMachineFluxEditor.tsx, ui/src/timeMachine/components/fluxFunctionsToolbar/FunctionCategory.tsx, ui/src/timeMachine/components/fluxFunctionsToolbar/ToolbarFunction.tsx
Closes #12188 
This PR adds an end-to-end test for filtering aggregation functions in the data explorer by name.
=> test(explorer): add end-to-end testing for filtering functions by name

ui/cypress/e2e/explorer.test.ts
This fixes an error in an earlier PR where the filtering function test was added to the wrong code block.
=> test(explorer): move test for filtering functions

cmd/influx_inspect/buildtsi/buildtsi.go
In a 2.0 world, the index isn't necessarily in the same folder as the data. This allows separating that for consumers of the `IndexShard` api.
=> buildtsi: support specifying a specific index path

ui/cypress/e2e/collectors.tests.ts, ui/cypress/e2e/explorer.test.ts, ui/src/timeMachine/components/TagSelector.tsx
Closes #12180
This PR adds a test for the empty state of the tag keys card in the Data Explorer when the selected bucket is empty.
It also fixes a failing e2e test by renaming `telegrafs_tab` to `telegrafs` in the URL in the collectors test.
=> test(explorer): test empty state for tag keys

http/swagger.yml
Updates the swagger definition for the post dashboard request.  Using `Dashboard` for both Request and Response causes typing paining in the UI where `labels`, `cells`, etc are optional. 
Our first steps for fixing `labels` being generated as optional on `Bucket`, `Dashboard`, `Telegraf`, and `Task` is to create PRs for separating out their post request schema from the response schema.
=> fix(http/swagger/dashboard): update the swagger post dashboards

.github/CODEOWNERS
Require API team to review changes to http/swagger.yml
Add a github CODEOWNERS file that specifies the api team as reviewers for http/swagger.yml.  
To enable this feature someone will need to turn on "code owners" in the reviewing:
https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests
Here is more information about code owners:
https://help.github.com/en/articles/about-code-owners
> When someone with admin or owner permissions has enabled required reviews, they also can optionally require approval from a code owner before the author can merge a pull request in the repository. For more information, see "Enabling required reviews for pull requests."
=> chore(.github): specify influxdata api team as code owner of swagger.yml

tsdb/metrics_test.go, tsdb/series_index.go
During Recover, we forgot to propagate the disabled flag to the keyIDMap options like we do during Open. Since we still do propagate the singleton `ims` which is initialized lazily, if the first initialization has a different set of labels, it will cause an inconsistent usage even if the metrics are disabled.
=> tsdb: fix disabling metrics in the series index

ui/cypress/e2e/explorer.test.ts
Closes #12178
This PR adds an end-to-end test that checks for the empty state in the Data Explorer visualization when the query entered returns no results.
=> test(explorer): add end-to-end test for empty state

ui/cypress/e2e/explorer.test.ts, ui/src/clockface/components/dropdowns/DropdownItem.tsx
Closes #12179 
This PR adds an end-to-end test for the number of buckets shown in the dropdown in the query builder mode of the data explorer.
=> Test(explorer): check length of bucket dropdown items

http/task_service.go, task/platform_adapter.go
In the platform adapter, we ask the URM for a list of tasks the user
owns, and then we look up each task individually.
The task service tests uncovered a legitimate bug where FindTasks would
return a "task not found" error, originating from looking up a task that
was present when we interrogated the URM but was deleted before we could
find it in the task store.
This change also removes duplicated URM logic from the HTTP handler
which has since been pushed down into the platform adapter.
Closes #12003.
=> fix(task): don't error when URM task disappears

http/swagger.go
The previous "." argument with "-ignore go" accidentally matched
README.md and Makefile too, neither of which we care to actually include
as assets.
Now we just explicitly include swagger.yml. It's simple enough to add
another file to the go:generate line if and when we need it.
=> refactor(http): only generate bindata asset for swagger.yml

pkg/lifecycle/resource.go, pkg/lifecycle/resource_debug_disabled.go, pkg/lifecycle/resource_debug_enabled.go, pkg/lifecycle/resource_test.go, storage/series_cursor.go, tsdb/index.go, tsdb/series_file.go, tsdb/tsi1/file_set.go, tsdb/tsi1/file_set_test.go, tsdb/tsi1/index.go, tsdb/tsi1/index_file.go, tsdb/tsi1/index_file_test.go, tsdb/tsi1/index_files.go, tsdb/tsi1/index_test.go, tsdb/tsi1/log_file.go, tsdb/tsi1/partition.go, tsdb/tsi1/partition_test.go, tsdb/tsm1/engine.go, tsdb/tsm1/engine_delete_bucket.go, tsdb/tsm1/engine_delete_bucket_test.go, tsdb/tsm1/engine_test.go
This commit adds the `pkg/lifecycle.Resource` type to help manage opening, closing, and leasing out references to some resource. A resource cannot be closed until all acquired references have been released. If the `debug_ref` tag is enabled, all resource acquisitions keep track of the stack trace that created them and have a finalizer associated with them to print on stderr if they are leaked. It also registers a handler on SIGUSR2 to dump all of the currently live
resources.
Having resources tracked in a uniform way with a data type allows us to do more sophisticated tracking with the `debug_ref` tag, as well. For example, we could show references and panic the process if a resource cannot be closed within a certain time frame, or attempt to figure out the DAG of resource ownership …
=> storage: fix problems with keeping resources alive

ui/cypress/e2e/explorer.test.ts, ui/package-lock.json, ui/src/shared/components/EmptyGraphMessage.tsx, ui/src/shared/components/EmptyQueryView.tsx, ui/src/shared/components/TimeSeries.tsx
Fixes an issue where the Data Explorer would issue an empty (invalid)
query upon first load.
Adds a test to catch similar regressions in the future, and refactors
e2e tests to use a `testID` for asserting that empty graph messages
exist.
Closes #12326
=> Fix invalid query submission on Data Explorer load

ui/src/clockface/components/resource_list/ResourceName.tsx, ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/dashboards/components/dashboard_index/TableRow.tsx, ui/src/organizations/components/BucketRow.tsx, ui/src/organizations/components/CollectorRow.tsx, ui/src/organizations/components/ScraperRow.tsx, ui/src/organizations/components/VariableRow.tsx, ui/src/shared/components/EditableName.tsx, ui/src/tasks/components/TaskCard.tsx
Closes #12059
Adds a spinner to pending updates to resource list names
=> fix(ui/editablename): add spinner to  pending name edits

ui/src/organizations/components/CreateVariableOverlay.tsx, ui/src/organizations/components/Variables.tsx, ui/src/variables/actions/index.ts
Closes #12332
Closes #12335
This PR fixes a couple issues with the manage variables page: the create overlay now closes when the submit button is pressed, and the variables in the index are now sorted by name. Also, a notification is displayed to the user when a variable is successfully created.
=> fix(variables): close create overlay when new variable created

ui/package-lock.json, ui/package.json, ui/src/dashboards/apis/v2/index.ts, ui/src/dashboards/constants/index.ts, ui/src/dashboards/resources.ts, ui/src/types/v2/labels.ts, ui/src/variables/utils/getWindowVars.ts
Closes #12231 
- Bump version of client to `0.2.21`
- Creates a temporary wrapper for `Package` type incompatability
It would have been nice to have `Dashboard` in `src/types/v2/dashboards` extend the `IDashboard` interface, but it looks like this this creates more conflicts with the `0.2.21` version of the client.  See more on this issue here: https://github.com/influxdata/influxdb2-js/issues/33 `IDashboard` is preferable because it requires `id`, `name`, etc.
The issue of consuming types that require labels can be found here: https://github.com/influxdata/influxdb/issues/12243
=> chore(ui/client): update ui client to 0.2.21

ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
Closes #12340
This PR places the variables tab in the explorer sidebar behind a feature flag.
The feature flag will be removed when the user is able to add a variable to the script from the sidebar.
=> refactor(explorer): hide variables tab in explorer behind feature flag

ui/src/timeMachine/constants/queryBuilder.ts
Fixes an issue where you could not build a query with a `derivative` function applied using the builder (regression introduced in #12217).
=> Fix building queries with derivatives

ui/cypress/e2e/explorer.test.ts, ui/src/clockface/components/right_click_menu/RightClickMenuItem.tsx, ui/src/timeMachine/components/QueryTab.tsx
Closes #12182 
Add test for removing a query tab when more than one query tab exists.
=> test(de): remove a second query

context/token.go, context/token_test.go, http/query_service.go
Tasks instantiates the query service but does not know the token
it will use ahead of time.  This allows the token to be optionally
set on context.
=> feat(http): query client fallback uses context auth

task/backend/logreaderwriter_test.go, task/backend/storetest/logstoretest.go
This is particularly relevant when the backing systems (like a real
query service) check authorizations.
=> test(task): allow log reader/writer test harness to provide authz

storage/reads/merge.go, storage/reads/mergegroupresultset_test.go, storage/reads/reader.go, storage/reads/stream_reader.gen.go, storage/reads/stream_reader.gen.go.tmpl, storage/reads/stream_reader.go, storage/reads/stream_reader_test.go
This work is necessary to support gRPC streams.
It is possible a `StreamReader` (gRPC) may return an empty response. This change adds retry and bail-out support. When a bail-out occurs, `reads.ErrStreamNoData` is returned.
=> Add retry and bail-out to reader

ui/src/organizations/components/BucketRow.tsx, ui/src/organizations/components/OrganizationNavigation.tsx, ui/src/shared/components/CloudFeatureFlag.tsx, ui/src/shared/constants/index.ts
Closes #12337
Create a CloudFeatureFlag that disables features if in the cloud environment.
This assumes there is an environmental variable CLOUD that is set to `"true"`
Use this flag to hide scrapers in the organization view and from the buckets add data drop down
=> Add a cloud feature flag and prevent scrapers from showing up in cloud

http/swagger.yml, ui/mocks/dummyData.ts, ui/src/organizations/actions/orgView.ts, ui/src/organizations/components/OrgTaskEditPage.tsx, ui/src/organizations/components/OrgTasksPage.tsx, ui/src/organizations/reducers/orgView.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/components/TaskCard.tsx, ui/src/tasks/components/TasksList.tsx, ui/src/tasks/components/__snapshots__/TasksList.test.tsx.snap, ui/src/tasks/containers/TaskEditPage.tsx, ui/src/tasks/reducers/v2/index.ts, ui/src/types/tasks.ts, ui/src/types/v2/index.ts, ui/src/types/v2/tasks.ts
Closes #12250 
This PR replaces removes the wrapper for the Task type from the "types" directory and replaces it with a direct import from the client library. It also moves the Task types file to live under "src/types" rather than "src/types/v2."
The addition of an "organization" object to Tasks in the `orgView` actions is removed. The correct property on a Task object is a string `org` which is the name of the organization the Task belongs too.
=> fix(tasks): replace organization on tasks with org name string

CHANGELOG.md, ui/src/shared/components/cells/react-grid-layout.scss
Co-authored-by: thealexpaxton@gmail.com
Closes #11579
Prevent cells' edit menus from getting clipped when there is another cell directly beneath them.
=> fix(ui): update z-index of cells when hovered

bolt/bucket.go, inmem/bucket_service.go, kv/bucket.go, testing/bucket_service.go
Closes https://github.com/influxdata/influxdb/issues/12381
fix the update bucket name to prevent duplicate name
add test case
=> fix(testing): update bucket update uniqueness

task/platform_adapter.go, task/servicetest/servicetest.go
The previous code was mistakenly updating the task's authorization even
when it wasn't part of the update request.
=> fix(task): only update authorization when requested

cmd/influx/main.go, cmd/influx/setup.go
Closes https://github.com/influxdata/influxdb/issues/12356
So this issue happens when the influxdb user and cli user is different. Which results the InfluxDir ends up with different folders. 
=> fix(setup): create dir when influxdb ran as a different user

ui/src/Logout.tsx, ui/src/Signin.tsx, ui/src/onboarding/containers/SigninPage.tsx, ui/src/shared/constants/index.ts
Creates a redirect for `/api/v2/signin` in the ui when `CLOUD=true` otherwise does the typical auth flow for OSS.
=> feat(ui/oauth/redirect): redirects to /api/v2/signin

CHANGELOG.md, ui/src/organizations/components/AddMembersForm.tsx, ui/src/organizations/components/AddMembersOverlay.tsx, ui/src/organizations/components/Members.tsx, ui/src/organizations/components/SelectUsers.tsx, ui/src/organizations/containers/OrgMembersIndex.tsx, ui/src/shared/copy/v2/notifications.ts
Closes #11854 
Create a component overlay for the add members and a form component on the overlay. Add api calls on the client to get all users and add member to an org.
=> Add the ability to add members to an org

authz.go, ui/cypress/e2e/orgs.test.ts
This will disallow web users from creating organizations until
we figure out how.
=> fix(authz): revert https://github.com/influxdata/influxdb/pull/11441

cmd/influxd/launcher/launcher_test.go
Adds an integration test for #12422
It runs setup, creates a user, and then mimics chronograf by signing in and checking for users.
=> feat(influxd/launcher): add test mimicing chronograf setup

ui/package-lock.json, ui/package.json, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
Update the client dependency will fix issue where cells are duplicated during a dashboard clone and fix issue where task labels are not imported when a task is imported
Removes console.log
=> Update client dependency to fix dashboard cloning and task import

ui/src/Signin.tsx
Closes #12420 
Moves the transition from `Loading` state to `Done` state to onMount only so as to not render a spinner every 60secs and reload the app.
=> fix(ui/signin): remove signin loading state change

ui/src/organizations/components/AddMembersForm.tsx, ui/src/organizations/components/AddMembersOverlay.tsx, ui/src/organizations/components/Members.tsx, ui/src/organizations/components/SelectUsers.tsx, ui/src/organizations/containers/OrgMembersIndex.tsx
Closes #12426 #12411 
Changed users to be a key value object instead of an array. Added filter on users object for the members that already exist in an org. Updated the component to re-fetch members when save is clicked on the overlay.
=> Update users dropdown to filter out the users that already exist in org

http/proxy_query_service.go, http/query.go, http/query_handler.go, session.go
When a query from the UI occurs this transforms authorizer from a session to an ephemeral authorization token.
=> feat(http): convert user sessions to auth for query service

CHANGELOG.md, ui/package-lock.json, ui/package.json, ui/src/organizations/components/AddMembersOverlay.tsx, ui/src/organizations/components/MemberList.tsx, ui/src/organizations/components/MemberRow.tsx, ui/src/organizations/components/Members.tsx, ui/src/organizations/components/__snapshots__/Members.test.tsx.snap, ui/src/shared/copy/v2/notifications.ts
Closes #10921 
Updated the client version number which includes api call to remove the member. Add delete and functionality button to the members row. Display notification when success/fail for deleting members
=> Add the ability to remove a member from org

cmd/influx/setup.go
Closes https://github.com/influxdata/influxdb/issues/12439
manually tested
=> fix(influx): return the error when token file already exists

kit/tracing/tracing.go, kit/tracing/tracing_test.go
```
benchmark                               old ns/op     new ns/op     delta
BenchmarkLocal_StartSpanFromContext-8   1382          718           -48.05%
benchmark                               old allocs    new allocs    delta
BenchmarkLocal_StartSpanFromContext-8   6             4             -33.33%
benchmark                               old bytes     new bytes     delta
BenchmarkLocal_StartSpanFromContext-8   376           224           -40.43%
```
=> Use alternate runtime APIs to reduce allocs / cpu

ui/src/dashboards/components/DashboardExportOverlay.tsx, ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/dashboards/components/dashboard_index/DashboardCards.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndexContents.tsx, ui/src/dashboards/components/dashboard_index/Table.tsx, ui/src/index.tsx, ui/src/organizations/components/Dashboards.tsx, ui/src/shared/utils/resourceToTemplate.ts
Closes #11151
Add the dashboards export route and redirect to `id/export` on export.
=> feat(ui/dash/export): add route for dash exporting

http/task_service.go, query/preauthorizer.go, query/preauthorizer_test.go, query/querytest/compile.go, query/spec.go, query/stdlib/influxdata/influxdb/from.go, query/stdlib/influxdata/influxdb/to.go, task/validator.go, task/validator_test.go
Closes https://github.com/influxdata/influxdb/issues/12462
Add an optional orgID to the preAuthorizer func
=> fix(query): fix same bucket name with different orgs

http/api_handler.go, http/swagger.go, http/swagger_assets.go, http/swagger_noassets.go
In a development build (i.e. does not have the assets build tag), the
first request to GET /api/v2/swagger.json will produce log output like:
INFLUXDB_VALID_SWAGGER_PATH not set; falling back to checking relative paths	{"log_id": "0E4I7Dkl000", "service": "swagger-loader"}
Successfully loaded swagger.yml	{"log_id": "0E4I7Dkl000", "service": "swagger-loader", "path": "/.../influxdb/http/swagger.yml"}
There is no such log line in production builds.
But now both builds correctly serve swagger.json, instead of just
production builds.
=> chore: serve swagger.json in development builds

http/telegraf_test.go
Fixes a PR merge test failure of telegraf member/owner links not in tests.
=> fix(http/telegraf): add missing member/owner test links

http/bucket_service.go, http/bucket_test.go, http/dashboard_service.go, http/dashboard_test.go, http/org_service.go, http/proto_test.go, http/swagger.yml, http/user_resource_mapping_test.go, http/user_service.go
Closes #12484 
Previously, our endpoints were "log" and not "logs."
Plural for consistency.
=> fix(http): log endpoint should be logs

http/swagger.yml
When creating a new telegraf, the plugin's type is a required field. I've updated the swagger to reflect this.
=> fix(swagger): add type to expected telegraf request properties

CHANGELOG.md, ui/src/dashboards/actions/v2/index.ts, ui/src/dashboards/components/ImportDashboardOverlay.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/organizations/components/Dashboards.tsx, ui/src/shared/components/ImportOverlay.tsx, ui/src/shared/copy/notifications.ts
Closes #11533
Create a dashboard from the imported dashboard.
Make import button in import overlay visible and disabled rather than not visible
=> feat(ui/dash/import): create dashboards from imported templates

http/swagger.yml
Closes #12482 
Without this restriction the specification implied the key could be any data type.
=> docs(http): specify that label properties keys must be strings

http/bucket_service.go, http/bucket_test.go, http/swagger.yml
Closes #12483
Add /write convenience links to bucket response.
=> fix(http): update bucket write links to include org/bucket

CHANGELOG.md, ui/src/organizations/components/Dashboards.tsx
=> feat(ui/dash): Add import dashboard button to org view

CHANGELOG.md, ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/tasks/components/TaskCard.tsx
Closes #12522
remove feature flag around dashboard and tasks export buttons.
=> feat(ui): Show dashboard and template export buttons

storage/reads/stream_reader.gen.go, storage/reads/stream_reader.gen.go.tmpl, storage/reads/table.go
A cursor can be in-process (local) or remote. Remote cursors have already applied the `hasPoints` check, to reduce network traffic. Testing whether the cursor has points again here:
https://github.com/influxdata/influxdb/blob/9216528555244353725b6a565dd056be41fe2c4b/storage/reads/reader.go#L221-L224
will always return `false` for a remote cursor that has applied the `NoPoints` optimization.
This temporary fix allows the `hasPoints` function to differentiate a streamCursor and always return true in that case.
A future fix will ensure `hasPoints` is always performed by the cursor to remove the check in reader.go
=> Create interface to identify a remote streamed cursor

ui/src/dataLoaders/components/collectorsWizard/configure/TelegrafPluginInstructions.tsx, ui/src/protos/actions/index.ts, ui/src/shared/copy/notifications.ts
Closes #12492
Create dashboards from templates rather than protos after creating telegraf plugins
=> feat(ui): Create dashboards from templates for telegraf plugins

ui/src/dataLoaders/actions/dataLoaders.ts
For the moment we need to create a permission with an orgID.  I suspect we'll remove orgID soon.
=> fix(dataLoaders/actions): add orgID to resource permissions

ui/package-lock.json, ui/package.json, ui/src/dashboards/actions/v2/index.ts, ui/src/dashboards/actions/v2/views.ts, ui/src/dashboards/components/DashboardPage.tsx, ui/src/dashboards/reducers/v2/views.ts, ui/src/dashboards/selectors/index.ts, ui/src/shared/components/RefreshingView.tsx, ui/src/shared/components/cells/Cell.tsx, ui/src/shared/components/cells/View.tsx, ui/src/shared/copy/notifications.ts, ui/src/shared/utils/filterUnusedVars.ts, ui/src/variables/actions/index.ts, ui/src/variables/selectors/index.tsx
Closes #12470
This enables a user to create a cell that uses an external variable (e.g. `from(bucket: v.my_bucket)`). Then when that dashboard is first loaded, an appropriate value for the `my_bucket` variable will be loaded, selected, and substituted before executing the query for that cell.
It doesn't yet refetch the values for variables when a cell is created or edited, and doesn't allow for selecting different values. These will follow in a future PR.
=> Populate and substitute variables on dashboard load

tsdb/series_file.go, tsdb/series_index.go, tsdb/series_partition.go
Currently, the `SeriesIDSize` constant is declared but unused.
Use `SeriesIDSize` constant to read/write series ID from/to `SeriesIndexElem`.
Add `SeriesOffsetSize` constant to read/write series offset from/to `SeriesIndexElem`.
=> storage: add SeriesOffsetSize constant

ui/src/App.tsx, ui/src/index.tsx, ui/src/me/components/GettingStarted.tsx, ui/src/onboarding/containers/SigninPage.tsx, ui/src/shared/actions/notifications.ts, ui/src/shared/containers/Notifications.tsx, ui/src/shared/reducers/notifications.ts, ui/src/types/actions/notifications.ts
Closes #12455 
Clears all notifications on redirect for the `SigninPage` and puts notifications in the `.chronograf-root` container.
=> fix(ui/signin): clear notifications on redirect

ui/src/shared/components/Filter.test.tsx, ui/src/shared/components/Filter.tsx
Closes #12441 
Updates the `Filter` sortBy option to utilize lowercasing when sorting string values.
=> fix(ui/filter): update filter sorting to ignore casing

ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/labels/actions/index.ts, ui/src/shared/components/inlineLabels/InlineLabels.tsx, ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx, ui/src/shared/copy/notifications.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/components/TaskCard.test.tsx, ui/src/tasks/components/TaskCard.tsx
Closes #124688
Stale labels stored in component state required the dashboard index to be refreshed to add a newly created label to multiple list items. This change prefers to filter the labels by search term on render and resolves issues with stale label lists.
=> fix(ui/inlinelabels): filter labels in render

ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx, ui/src/shared/components/inlineLabels/InlineLabelsList.tsx
Closes #12469 
Resolves awkward empty state with prompting for typing to create a new label
=> fix(ui/labels): update empty state for no labels

ui/src/dashboards/actions/v2/index.ts, ui/src/dashboards/actions/v2/views.ts, ui/src/dashboards/components/DashboardPage.tsx, ui/src/dashboards/selectors/index.ts, ui/src/shared/copy/notifications.ts, ui/src/variables/utils/ValueFetcher.ts
Closes #12550
The set of external variables used in a dashboard may change whenever a cell is added, updated, or removed, so we refresh the variable values when these actions are taken.
Here's an example of a cell using a `my_bucket` variable that I have defined in the org page:
=>  Refresh dashboard values when any cell changes

ui/src/clockface/components/index_views/IndexList.scss, ui/src/clockface/components/panel/Panel.scss
Closes #12576 
This is a quick CSS fix that solves the visual problem. I created https://github.com/influxdata/influxdb/issues/12600 to track the tech debt side of this issue
=> Ensure IndexList + Panels Contrast

ui/src/shared/components/Legend.tsx
Fixes issue when a query returns a lot of series you get a ton of console warning for the duplicate key
=> fix(ui): Update keys for legend items to avoid duplicate key warnings

ui/src/clockface/components/overlays/OverlayHeading.tsx, ui/src/dashboards/components/ImportDashboardOverlay.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/me/components/account/__snapshots__/ViewTokenOverlay.test.tsx.snap, ui/src/organizations/actions/orgView.ts, ui/src/organizations/components/Dashboards.tsx, ui/src/organizations/components/OrgTaskImportOverlay.tsx, ui/src/shared/components/ExportOverlay.tsx, ui/src/shared/components/ImportOverlay.scss, ui/src/shared/components/ImportOverlay.tsx, ui/src/shared/components/OrgDropdown.tsx
Closes #12504
Closes #12306
Add org dropdown to import overlays
Use form in import and export overlays
=> feat(ui): add organization dropdown to import overlay

CHANGELOG.md, ui/src/dataExplorer/components/SaveAsButton.tsx, ui/src/dataExplorer/components/SaveAsVariable.tsx, ui/src/dataExplorer/components/__snapshots__/SaveAsButton.test.tsx.snap, ui/src/organizations/components/CreateVariableOverlay.tsx, ui/src/organizations/components/VariableForm.tsx, ui/src/organizations/components/Variables.tsx
Closes #11985
This PR adds an option to the "Save As" overlay in the data explorer, allowing the user to save their query as a variable.
Also included is a generic `VariableForm` component that is used for both the "Save As" and "Create" overlays for Variables.
=> feat(explorer): add save as variable overlay

ui/src/organizations/components/TelegrafInstructionsOverlay.tsx
Fixes issue where there is no token in the setup instructions overlay when viewed from the org view.
=> fix(ui): Ensure telegraf setup instructions has token information

http/org_service.go, http/org_test.go
Closes https://github.com/influxdata/influxdb/issues/12587
update the link endpoint to match swagger file
=> fix(http): change secrets to match swagger

kit/tracing/tracing.go, kit/tracing/tracing_test.go
Every span has an operation name, which shows up in multiple places in the Jaeger UI. Verbose function names like
```
github.com/influxdata/influxdb/kit/tracing.StartSpanFromContext
```
are not readable in this UI. Shorter function names like
```
StartSpanFromContext
```
improve UX. Context is not lost because (1) the filename and line number are logged with the span and (2) spans are understood in the context of other spans, marked with service name and operation name.
Extra cost is ~22 ns per call to StartSpanFromContext. No additional memory is allocated.
=> fix: Use simple function name for tracing operation name

task/backend/query_logreader.go, task/backend/storetest/logstoretest.go
Closes #12452 
Task runs have an optional field (requestedAt). This causes problems when we attempt to query it. If we include the optional field and the table doesn't have the column it fails. To remedy this we attempt to run the query with the optional field and if it fails we remove the optional field and run the query again.
=> Fix requested at for task runs

ui/src/timeMachine/actions/index.ts, ui/src/timeMachine/components/SubmitQueryButton.tsx, ui/src/timeMachine/components/TimeMachine.tsx, ui/src/timeMachine/components/TimeMachineFluxEditor.tsx, ui/src/timeMachine/reducers/index.test.ts, ui/src/timeMachine/reducers/index.ts, ui/src/variables/selectors/index.tsx
This PR enables a user to use variables in the Data Explorer and CEO.
When they first open up the CEO to edit a cell, any variables in use in the queries for that cell will be hydrated ("hydrate" = "load values for a variable by executing its query").
When they edit their script and then press submit, any variables they have started to use in their script will be hydrated before executing the query.
=> Initial support for variables in DE/CEO

ui/package-lock.json, ui/package.json, ui/src/dashboards/apis/v2/index.ts, ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/dashboards/components/dashboard_index/DashboardCards.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndexContents.tsx, ui/src/dashboards/components/dashboard_index/Table.tsx, ui/src/organizations/actions/orgView.ts, ui/src/organizations/components/Dashboards.tsx, ui/src/organizations/containers/OrgDashboardsIndex.tsx, ui/src/organizations/reducers/orgView.ts, ui/src/protos/actions/index.ts, ui/src/shared/actions/links.ts, ui/src/shared/reducers/links.test.ts, ui/src/shared/reducers/links.ts
Closes #12574 
Org view dashboards were loading dashboards in a number of places in the component hierarchy and there was a lot of general confusion in the components. 
I did a lot of clean up, as well as centralizing where dashboard get was being performed.
=> Fix dashboards in org

query/bridges.go
The statistics are only finalized after release is called. Defer a call
to release to ensure they are released, but explicitly release on
success to ensure that the statistics are finalized from all sources
before returning them.
=> fix(query): release the query results before requesting statistics

CHANGELOG.md, ui/cypress/e2e/dashboardsIndex.test.ts, ui/mocks/dummyData.ts, ui/src/clockface/components/empty_state/EmptyStateText.tsx, ui/src/clockface/components/form_layout/Form.tsx, ui/src/configuration/components/LabelOverlayForm.tsx, ui/src/dataLoaders/components/lineProtocolWizard/configure/__snapshots__/LineProtocol.test.tsx.snap, ui/src/me/components/account/__snapshots__/Settings.test.tsx.snap, ui/src/onboarding/components/__snapshots__/AdminStep.test.tsx.snap, ui/src/shared/components/inlineLabels/InlineLabelPopover.test.tsx, ui/src/shared/components/inlineLabels/InlineLabelPopover.tsx, ui/src/shared/components/inlineLabels/InlineLabels.test.tsx, ui/src/shared/components/inlineLabels/InlineLabelsCreateLabelButton.tsx, ui/src/shared/components/inlineLabels/InlineLabelsEditor.scss, ui/src/shared/components/inlineLabels/InlineLabelsEditor.test.tsx, ui/src/shared/components/inlineLabels/InlineLabelsEditor.tsx, ui/src/shared/components/inlineLabels/InlineLabelsList.test.tsx, ui/src/shared/components/inlineLabels/InlineLabelsList.tsx, ui/src/shared/components/inlineLabels/InlineLabelsListItem.tsx, ui/src/tasks/components/__snapshots__/TaskForm.test.tsx.snap
Closes #12609 
- Text field in `Add Label` popover is always focused (to receive keyboard commands)
- There is always a selected item in the list (so that hitting `Enter` always does something)
- Hitting `ArrowUp`/`ArrowDown` changes the selected item in the list
- Abiity to select the suggestion via keyboard shortcuts
- Selected item is much brighter
- Wrote unit tests for every mouse & keyboard interaction associated with inline labels
=> Fine tune inline label keyboard interactions

cmd/influxd/launcher/launcher.go, task/validator.go, task/validator_test.go
This should simplify debugging when a user isn't allowed to do something
with a task, that they expect to be able to do.
Closes #12540.
=> feat(task): log authorization errors

.github/stale.yml
This PR configures https://probot.github.io/apps/stale/ (which I installed separately) to mark all tickets inactive for 90s as stale - and to close stale tickets 7 days later.  
This is a step towards applying discipline to the influxdb repository issue cruft.
Separately, Russ and I are creating a triage process for new issues and community PRs.
=> Add configuration for stale probot

.circleci/config.yml, Makefile, etc/circle-detect-committed-binaries.sh, etc/detect-committed-binaries.sh
Binary files can be whitelisted with the special line 'Adds-Binary:
<path/to/binary/file>' included in the commit message body. Deliberately
checked-in binary files should be very rare.
With minimal effort, this could probably be repurposed as a local
postcommit hook.
=> ci: fail build if binary files committed

CHANGELOG.md, ui/src/shared/components/FluxEditor.tsx, ui/src/timeMachine/components/TimeMachineFluxEditor.tsx, ui/src/timeMachine/components/fluxFunctionsToolbar/FluxFunctionsToolbar.tsx, ui/src/timeMachine/utils/scriptInsertion.ts
=> feat(ui): Update flux functions insertion from  toolbar to add to current line or below

task/backend/query_logreader.go, task/backend/scheduler_test.go
The late measurement filter, after a pivot, had the potential to result
in empty groups without a runID, which would cause a runtime error,
which would cause the whole query to fail.
Experimentation has shown that those empty tables will no longer arrive
by filtering early on measurement.
=> fix(task): filter by measurement early in query logreader

ui/cypress/e2e/dashboardsIndex.test.ts, ui/cypress/e2e/tasks.test.ts, ui/src/clockface/components/empty_state/EmptyState.scss, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndexContents.tsx, ui/src/dashboards/components/dashboard_index/Table.tsx, ui/src/organizations/components/Dashboards.tsx, ui/src/organizations/components/OrgTasksPage.tsx, ui/src/tasks/components/EmptyTasksList.tsx, ui/src/tasks/components/TasksList.test.tsx, ui/src/tasks/components/TasksList.tsx, ui/src/tasks/components/__snapshots__/TasksList.test.tsx.snap, ui/src/tasks/containers/TasksPage.tsx
Updates PR: https://github.com/influxdata/influxdb/pull/12121
Adds generic import dropdown instead of the create resource button to empty states of dashboards and tasks
=> Add import to empty

http/api_handler.go, http/source_service.go
Closes https://github.com/influxdata/influxdb/issues/12674
fixed the response, manually tested as well
=> fix(http): change source buckets from slice to obj

query/stdlib/testing/end_to_end_test.go
Closes #
Skip failing end-to-end test due to https://github.com/influxdata/flux/issues/1067
=> test(stdlib): skip failing window test due to new trigger optimization

authorizer/label.go, authorizer/label_test.go, http/label_service.go, http/label_test.go, http/swagger.yml, kv/label.go, label.go, label_test.go, testing/label_service.go
- adds an organization ID to labels
- labels must specify their org on creation; a user can create that label if they have read permissions for that org (is that weird?)
- user resource mappings are created for a newly created label, to allow auth enforcement over non-token session
This is red right now because it breaks some chronograf tests (chronograf needs to be updated include an `orgID` in the label body when posting a new label).
=> Scope labels to organizations

CHANGELOG.md, ui/src/organizations/components/ScraperList.tsx, ui/src/organizations/components/Scrapers.tsx, ui/src/organizations/components/Variables.tsx, ui/src/organizations/components/__snapshots__/Scrapers.test.tsx.snap
Closes #12659
Updates the grey box in the scrapers empty state to be the full width
Larger scrapers empty state text
Update variables create button to be smaller
=> Update the scrapers and variables empty state to match other org views

authorizer/label.go
This fix will ignore the old labels without append them.
=> fix(authorization): ignore the labels

query/stdlib/influxdata/influxdb/to.go
Should return the error if != nil.
I don't know if there is a valid reason not to do it, but I spent a lot of time wondering why `to` was not writing without knowing it was erroring.
=> fix(query/stdlib/influxdb): return error on point explosion

cmd/influxd/launcher/tasks_test.go, task/backend/executor/executor.go, task/backend/scheduler_test.go, task/mock/scheduler.go
The synchronous executor was missing a call to ResultIterator.Release.
The asynchronous executor wasn't even calling Query.Statistics.
Also add a test that the scheduler records the statistics to the run
log, and that the statistics are visible from the launcher test. The
launcher test is the most likely place to catch if something goes wrong
in the full stack.
=> fix(task): report query statistics correctly

task/backend/scheduler.go, task/backend/scheduler_test.go
Closes #12667
Task updates now attempt to keep the existing runners working.
This causes the system to be slightly slower after a task update and caused a flakey test.
=> fix(task): Fix flakey tests introduced by task updates

CHANGELOG.md, ui/src/timeMachine/components/Queries.tsx, ui/src/timeMachine/components/QueryBuilder.scss, ui/src/timeMachine/components/QueryBuilder.tsx, ui/src/timeMachine/components/QueryBuilderDataCard.tsx, ui/src/timeMachine/components/RawDataToggle.tsx
Closes #11012 
Also made the raw data toggle into a component that doesn't get any props from its parent so it will be easier to experiment with placement.
=> Move bucket selection to first card in Query Builder

ui/src/onboarding/OnboardingWizard.scss
Firefox:
Chrome:
Safari:
Closes #12551 
Add `flex: 1` styling to the onboarding step container so it fills the available height. This is also similar to what the onboarding form and other onboarding styles do.
=> fix(ui/onboarding): add flex 1 to admin step

CHANGELOG.md, ui/src/timeMachine/actions/index.ts, ui/src/timeMachine/actions/queryBuilder.ts, ui/src/timeMachine/apis/QueryBuilderFetcher.ts, ui/src/timeMachine/apis/queryBuilder.ts, ui/src/timeMachine/components/TagSelector.scss, ui/src/timeMachine/components/TagSelector.tsx, ui/src/timeMachine/reducers/index.ts, ui/src/variables/utils/formatExpression.ts, ui/src/variables/utils/formatVarsOption.ts
=> Use selected time range for metaqueries in DE

CHANGELOG.md, ui/src/clockface/components/overlays/Overlay.scss
Closes #12719
Make the style that hides the horizontal scroll in overlays more specific. It should only hide it for the direct children, not any children.
=> fix(ui): Stop hiding horizontal scrollbar in flux raw data view

ui/src/configuration/components/Labels.tsx, ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/labels/constants/index.ts, ui/src/labels/selectors/index.ts, ui/src/organizations/components/CollectorRow.tsx, ui/src/tasks/components/TaskCard.tsx
Closes #12783 
Removes `LABEL_TOKEN` from the list of labels used for inline label suggestion.
=> fix(ui/labels): filter out hidden label tokens

ui/src/timeMachine/components/TimeMachineFluxEditor.tsx
This PR removes the feature flag on the variables tab in the script editor of the DE/VEO
=> chore(explorer): remove feature flag from variables tab

http/task_test.go, task/backend/task.go, task/service_test.go, task/servicetest/servicetest.go
closes #12724
We will now have the capability to write new task services that dont have to implement the backend.Store or LogReader or LogWriters
=> Update task servicetest to move dependency to the new TaskControlService

ui/src/shared/components/dygraph/Dygraph.tsx
Closes #12658 
Dygraph could render and be `undefined` causing hoverTime conversion to `toDomXCoord` to fail. This update ensures dygraph is defined in the constructor and appends dygraph once the graph container is mounted.
=> fix(ui/dygraph): guard against undefined dygraph

ui/src/configuration/components/Telegrafs.tsx, ui/src/organizations/components/CollectorList.tsx, ui/src/organizations/components/CollectorRow.tsx, ui/src/organizations/components/Collectors.tsx, ui/src/organizations/containers/OrgTelegrafsIndex.tsx, ui/src/shared/copy/v2/notifications.ts, ui/src/telegrafs/actions/index.ts, ui/src/telegrafs/reducers/index.ts
Closes #11612 
Add inline labels to the collectors row for labeling Telegraf configs
=> feat(ui/telegrafs): add inline labels to telegraf rows

CHANGELOG.md, ui/src/timeMachine/components/RawFluxDataTable.tsx
=> Fix Raw Data view screen tearing bug

ui/src/dashboards/components/VEO.tsx, ui/src/dashboards/components/VEOContents.tsx
Closes #12803
The VEO sets initial time machine state and the veo contents executes the queries.
Separate veo from veo contents. Veo contents assumes that there already is a view.
=> Ensure view loaded before rendering veo

CHANGELOG.md, ui/src/dashboards/components/NoteEditorText.tsx
Closes #12506
call focus to editor once editor mounts.
=> ensure editor is focused when editing/creating note

prometheus/converters.go, services/httpd/handler.go, services/httpd/handler_test.go
Fixes #10490.
This PR extends the Prometheus remote write endpoint to drop
unsupported Prometheus values, rather than reject the entire batch.
InfluxDB does not support `NaN`, `-Inf` or `+Inf`, but Prometheus does. The
remote write endpoint will now drop these and write valid values in the
provided batch.
If the user enabled write trace logging (`[http] write-tracing = true`)
then summaries of any dropped values within a batch will be logged.
If a batch of values contains any values that are subsequently dropped,
the returned status code will be `204`.
/cc @stevebang we should edit https://docs.influxdata.com/influxdb/v1.7/supported_protocols/prometheus/#how-prometheus-metrics-are-parsed-in-influxdb so that it explains what happens if `NaN`,  `Inf` or `-Inf` are written to InfluxDB via …
=> Drop all unsupported Prometheus values written to the remote write endpoint

ui/src/clockface/components/resource_list/ResourceName.tsx, ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/shared/components/cells/Cell.tsx, ui/src/tasks/components/TaskCard.tsx, ui/src/templates/components/TemplateCard.tsx
Closes #12493
giving the resource card  name an href causes a full page reload. By providing an onClick to the link that uses the router.push syntax to change the route, a full page reload is prevented. 
with this change, some loading state was added to make sure that view resources are finished getting fetched before rendering the views.
=> fix(ui): Prevent full page reload when clicking a dashboard

ui/src/organizations/components/OrgTemplatesPage.tsx, ui/src/templates/components/TemplatesHeader.tsx
Closes #12755
Rather than having both the option to create and import a template. Remove the option to create a template, so only import remains.
=> Remove the option to create a template

CHANGELOG.md, ui/src/shared/components/EmptyGraphError.scss, ui/src/shared/components/EmptyGraphError.tsx, ui/src/shared/components/EmptyQueryView.tsx, ui/src/shared/components/TimeSeries.tsx, ui/src/shared/components/cells/Cell.scss, ui/src/shared/utils/checkQueryResult.test.ts, ui/src/shared/utils/checkQueryResult.ts, ui/src/style/chronograf.scss, ui/src/timeMachine/actions/queries.ts
Closes #12686
Also tweaks the query execution code to check for [error messages that appear as a Flux table](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#errors). Previously we ignored these errors and attempted to plot the data anyway.
=> Improve display of query errors

CHANGELOG.md, ui/src/me/components/account/TokenRow.tsx
Closes #12854 
Update Token Row to include slide toggle to update token's status from active to inactive vice versa
=> Add the ability to enable or disable a token

CHANGELOG.md, ui/src/dashboards/components/variablesControlBar/DraggableDropdown.tsx, ui/src/dashboards/components/variablesControlBar/VariableDropdown.scss, ui/src/dashboards/components/variablesControlBar/VariableDropdown.tsx, ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx, ui/src/localStorage.ts, ui/src/mockState.tsx, ui/src/types/localStorage.ts, ui/src/variables/actions/index.ts, ui/src/variables/reducers/index.ts, ui/src/variables/selectors/index.tsx
Closes #12512
Closes #12376
This PR allows variables to be moved left and right within the `VariablesControlBar` in a dashboard. The order of the variables on a given dashboard is stored in the `values` property of the Variables state in local storage.
=> feat(dashboard): add ability to change order of variable dropdowns

logger/fields.go
Logs include a `trace_id` field which is generated by the logger, and corresponds to nothing useful. Remove that field.
Helps https://github.com/influxdata/idpe/issues/2961
=> chore(storage): Remove unused trace_id field from log

storage/reads/group_resultset.go
Every read request gets a little love from `groupResultSet.sort` which creates a massive logging burden at scale. Removed the log altogether because there's a span that's just as useful.
Also reduced the cardinality of the span by converting tags to logs.
Helps https://github.com/influxdata/idpe/issues/2961
=> chore(storage): Don't log every read request

ui/package-lock.json, ui/package.json, ui/src/organizations/actions/orgView.ts, ui/src/templates/api/index.ts, ui/src/types/templates.ts
Closes #12889
Move `createTaskFromTemplate` from `client` to UI.
=> chore(ui/templates/api): add create task from template

CHANGELOG.md, ui/src/dashboards/actions/views.ts, ui/src/dashboards/components/DashboardHeader.tsx, ui/src/dashboards/components/DashboardPage.tsx, ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/dashboards/components/variablesControlBar/VariablesControlBar.scss, ui/src/dashboards/components/variablesControlBar/VariablesControlBar.tsx, ui/src/dashboards/reducers/views.ts, ui/src/localStorage.ts, ui/src/mockState.tsx, ui/src/shared/components/RefreshingView.tsx, ui/src/store/configureStore.ts, ui/src/types/localStorage.ts, ui/src/types/stores.ts, ui/src/userSettings/actions/index.ts, ui/src/userSettings/reducers/index.ts, ui/src/variables/selectors/index.tsx
Closes #12845
Closes #12846
Save user preference for open or closed variables control bar in local storage.
default to open.
=> feat(ui): Persist variables control bar preferences

http/document_service.go
Closes #12861 
This PR introduces a nil check to ensure that nil documents aren't passed
=> Add check for nil document in post document request

CHANGELOG.md, ui/package-lock.json, ui/package.json, ui/src/shared/copy/notifications.ts, ui/src/templates/actions/index.ts, ui/src/templates/components/TemplateCard.tsx, ui/src/templates/reducers/index.ts
Closes #12741 
Updated the client to include the clone function
Updated actions and reducers to add the cloned template to the redux state
Updated Template card to include clone button
=> Add the ability to clone a template

ui/package-lock.json, ui/src/dashboards/components/VEO.tsx, ui/src/timeMachine/reducers/index.ts
Closes #12789
A VEO contains a time machine. When the VEO opens, we reset the time machine state according to the current view being edited (for example, the queries in the time machine should start as the queries for the view being edited).
We previously added additional state to the time machine that depends on the view (https://github.com/influxdata/influxdb/pull/12619) , but neglected to reset this state whenever a new time machine was activated.
In particular, the `queryResults` field of the time machine state was not reset, which led to stale data being momentarily rendered in the time machine visualization when a time machine was activated (#12789).
This commit ensures the `queryResults` field is reset whenever a new time machine is activated. It also ensures other data that only …
=> Fix stale render flash upon opening VEO

CHANGELOG.md, ui/package-lock.json, ui/package.json, ui/src/shared/copy/notifications.ts, ui/src/templates/actions/index.ts, ui/src/templates/components/TemplateCard.tsx, ui/src/templates/reducers/index.test.ts, ui/src/templates/reducers/index.ts
Closes #12744
This PR creates an action and reducer for updating a template, and adds the ability to update a template's name inline with the pencil icon.
=> feat(templates): add ability to update template name inline

ui/src/index.tsx, ui/src/organizations/components/OrgVariableExportOverlay.tsx, ui/src/organizations/components/VariableRow.tsx, ui/src/organizations/components/__snapshots__/Variables.test.tsx.snap, ui/src/organizations/containers/OrgVariablesIndex.tsx, ui/src/shared/utils/resourceToTemplate.test.ts, ui/src/shared/utils/resourceToTemplate.ts, ui/src/variables/actions/index.ts
Closes #11872 
Add the ability to export a variable as a template using an overlay at `/organizations/:id/variables/:varID/export`.
=> feat(ui/org/vars): export var as template

CHANGELOG.md, ui/src/Signin.tsx, ui/src/onboarding/components/SigninForm.tsx
Closes #12892
If a user's session expires while they are viewing a modal, they will be taken through the following router flow:
1. Start at
```
/dashboards <-- current route
```
1. Open modal, pushes modal route onto stack
```
/dashboards/:dashboardID/export <--
/dashboards
```
1. Session expires, push signin route onto stack
```
/signin?returnTo=/dashboards/:dashboardID/export <--
/dashboards/:dashboardID/export
/dashboards
```
1. After signin, push `returnTo` onto stack
```
/dashboards/:dashboardID/export <--
/signin?returnTo=/dashboards/:dashboardID/export
/dashboards/:dashboardID/export
/dashboards
```
1. Dismiss modal, which pops last route
```
/signin?returnTo=/dashboards/:dashboardID/export <--
/dashboards/:dashboardID/export
/dashboards
```
This creates an infinite loop :boom: …
=> Fix routing loop

CHANGELOG.md, ui/src/index.tsx, ui/src/organizations/components/Variables.tsx, ui/src/organizations/containers/OrgTemplatesIndex.tsx, ui/src/shared/components/ImportOverlay.tsx, ui/src/templates/api/index.ts, ui/src/types/templates.ts, ui/src/variables/actions/index.ts, ui/src/variables/components/VariableImportOverlay.tsx
=> feat(ui): Create import overlay to import variables

http/bucket_service.go, http/dashboard_service.go, http/label_service.go, http/org_service.go, http/task_service.go, http/telegraf.go
This was removed in the labels 2.0 rewrite, and looks like it was added back as a regression.
I need :eyes: on this from someone consuming from the labels API to make sure that this endpoint isn't being used (it shouldn't be, because it's not in our swagger docs).
=> fix(http): remove newPatchLabelHandler

cmd/influxd/launcher/launcher_helpers.go, cmd/influxd/launcher/launcher_test.go, cmd/influxd/launcher/query_test.go, cmd/influxd/launcher/storage_test.go, cmd/influxd/launcher/tasks_test.go, query/stdlib/testing/end_to_end_test.go
InfluxDB's counterpart of https://github.com/influxdata/idpe/issues/2900
This PR adds a launcher test for query memory limits and helpers for launcher tests.  
It also refactors tests that use the launcher.
=> test(launcher): test for query memory limits and launcher test helpers

ui/src/tasks/components/TaskRunsList.tsx
Closes #12874 
Sorting was not working since sort key was null in state so updated sort key to "scheduleFor"
Updated runs to filter for 20 runs to display latest 20 runs
=> Update tasks runs list to display 20 latest runs

CHANGELOG.md, ui/src/authorizations/actions/index.ts, ui/src/me/components/account/TokenRow.tsx
=> Add the ability to edit token's description

http/swagger.yml
Closes https://github.com/influxdata/influxdb/issues/13036
Add the swagger missing properties
=> fix(http): swagger dashboard links

http/swagger.yml
Closes https://github.com/influxdata/influxdb/issues/12811
Added the server override for /health and /ready
=> fix(http): fix swagger health & ready

http/swagger.yml
Closes #13034
Closes #13059
There were several issues with label add responses that I found in our swagger, where either it did not specify the correct 201 response, or used `LabelsResponse` instead of `LabelResponse`. This PR fixes these issues.
=> fix(http): update swagger to include correct label add responses

cmd/influx/cli/cli.go, cmd/influx/cli/flux.go, flux/client/http.go
Fixes #11710
Credentials were being ignored when using the `influx` CLI tool and the `-type=flux` switch. This PR ensures the credentials are correctly passed when executing Flux HTTP requests.
=> Ensure credentials are passed for Flux queries when using influx command

ui/cypress/e2e/login.test.ts, ui/src/clockface/index.ts, ui/src/clockface/types/index.ts, ui/src/pageLayout/components/NavMenu.tsx, ui/src/pageLayout/components/NavMenuItem.tsx, ui/src/pageLayout/components/NavMenuSubItem.tsx, ui/src/pageLayout/containers/Nav.test.tsx, ui/src/pageLayout/containers/Nav.tsx, ui/src/pageLayout/utils/index.ts
Making some changes to the navbar in preparation of moving it to Clockface
- Move highlighting logic to container
- Remove `lodash` from presentational components
- Add `testID` props to all presentational components
- Add `className` props to all presentational components
- Make `NavMenuItem` and `NavMenuSubItem` configurable via a `type` prop
- Can be either `RouterLink` or `HTTPLink`
=> Improve Navbar

CHANGELOG.md, ui/cypress/e2e/dashboardsIndex.test.ts, ui/cypress/index.d.ts, ui/cypress/support/commands.ts, ui/src/clockface/components/card_select/CardSelectCard.scss, ui/src/clockface/components/card_select/CardSelectCard.tsx, ui/src/clockface/components/grid_sizer/ResponsiveGridSizer.scss, ui/src/dashboards/actions/index.ts, ui/src/dashboards/components/DashboardImportFromTemplateOverlay.scss, ui/src/dashboards/components/DashboardImportFromTemplateOverlay.tsx, ui/src/dashboards/components/dashboard_index/DashboardCards.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/components/dashboard_index/Table.tsx, ui/src/index.tsx, ui/src/organizations/components/Dashboards.tsx, ui/src/shared/components/AddResourceDropdown.tsx, ui/src/style/chronograf.scss, ui/src/templates/actions/index.ts
Closes #12913
This PR adds an overlay to create a new dashboard from a template.
=> feat(dashboards): add overlay to create dashboard from template

ui/src/organizations/components/OrgTemplatesPage.tsx, ui/src/shared/components/inlineLabels/InlineLabels.tsx, ui/src/shared/copy/notifications.ts, ui/src/templates/actions/index.ts, ui/src/templates/components/TemplateCard.tsx
Closes #12907 
Display labels for templates, but hold off on adding and removing templates labels in the UI. This is accomplished by adding a `editMode` prop to the `InlineLabels` component. 
Clicking also filters
=> feat(ui/template/labels): show template labels

ui/package-lock.json, ui/package.json, ui/src/shared/components/Histogram.tsx, ui/src/shared/utils/view.ts, ui/src/timeMachine/components/view_options/HistogramOptions.tsx
The latest release of [@influxdata/vis](https://github.com/influxdata/vis) has a new, non-JSX public API. This PR updates the UI to use it.
=> Upgrade @influxdata/vis to 0.2.3

storage/engine.go, storage/metrics.go, storage/retention.go, storage/retention_test.go
In the case that there are multiple engines, we want the retention metrics from all of them.
=> storage: make retention metrics global

ui/src/dashboards/components/dashboard_index/DashboardCard.tsx, ui/src/labels/selectors/index.ts
Closes #13112
Currently filtering by org id rather until getLabels takes an orgID as a query parameter.
=> Update labels in dashboards to be org specific

ui/package-lock.json, ui/package.json, ui/src/authorizations/apis/__mocks__/data.ts, ui/src/authorizations/components/TokenRow.tsx, ui/src/dashboards/apis/index.ts, ui/src/dashboards/apis/v2/index.ts
Additionally, updates the where the Authorization status enum comes from due to api generation changes.
=> Update client dependency for dashboards get all

ui/src/tasks/actions/index.ts, ui/src/tasks/components/TaskCard.tsx, ui/src/tasks/components/TaskRunsList.tsx, ui/src/tasks/components/TaskRunsPage.tsx, ui/src/tasks/components/TaskRunsRow.tsx, ui/src/tasks/reducers/index.ts
Closes #13047 
Updated the order of columns on tasks runs and added duration onto the Run object
Updated tasks runs route to include orgs/orgID
=> Reorder the task runs columns

tsdb/index/inmem/meta.go, tsdb/index/inmem/meta_test.go
Previously it was possible to set IDs on a `nil` entry which would in turn cause a panic. If this panic was recovered by the server then it would result in a mutex in the `inmem` index staying locked indefinitely.
Related: https://github.com/influxdata/influxdb/issues/13010
=> Add nil check for tagKeyValueEntry.setIDs()

document.go, http/document_service.go, http/document_test.go, http/swagger.yml, kv/document.go, mock/document_service.go
Closes https://github.com/influxdata/influxdb/issues/13076
Added the option of getting docs by org id
=> feat(influxdb): get docs by org id

ui/src/configuration/components/ConfigurationPage.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dataExplorer/components/DataExplorerPage.tsx, ui/src/me/components/account/Account.tsx, ui/src/me/components/account/__snapshots__/Account.test.tsx.snap, ui/src/organizations/containers/OrgHeader.tsx, ui/src/shared/components/PageTitleWithOrg.tsx, ui/src/tasks/components/TaskHeader.tsx, ui/src/tasks/components/TaskRunsPage.tsx, ui/src/tasks/components/TasksHeader.tsx, ui/src/templates/components/TemplatesHeader.tsx
Closes #13113
Updates places where we show a page title to use a connected page title component that adds `orgname / ` to the front of the page title
=> Add org name to page titles

storage/reads/predicate.go, storage/reads/predicate_test.go
Closes #
The function `HasKeyFieldValue` searched an influxql expression for references to `_value`. But the function `NodeToExpr` takes an influxql expression (protobuf message) and replaces all references to `_value` with `$`.
This change makes it so `HasKeyFieldValue` searches for references to `$`. This fixes a bug where a value predicate would mistakenly be assigned as predicate consisting only of tag values.
https://github.com/influxdata/influxdb/blob/a5478652ba0eefa2c1bef8dc091305f29086d405/storage/readservice/cursor.go#L67
This would cause a series cursor error for any queries that filtered on `_value` like so:
from() |> range() |> filter(fn: (r) => r._value < 3000)
=> fix(reads): HasFieldValueKey searches for "$", not "_value"

services/httpd/handler.go, services/httpd/handler_test.go
Backport https://github.com/influxdata/influxdb/pull/13088 from 1.8 to 1.7
=> Fix security vulnerability when shared secret is blank

CHANGELOG.md, services/httpd/handler.go
Closes #13167
track remote read requests from prometheus handler with the PromReadRequests stat. aka mirror functionality done in the PromWriteRequests stats from the servePromWrite() handler
=> track remote read requests to prometheus remote read handler

CHANGELOG.md, ui/src/clockface/types/index.ts, ui/src/pageLayout/components/AccountNavSubItem.tsx, ui/src/pageLayout/components/Nav.scss, ui/src/pageLayout/components/NavMenuSubItem.tsx, ui/src/pageLayout/containers/Nav.tsx
Closes #13157
This PR adds an organizations dropdown to the Home nav bar item. From this dropdown, the user can switch organizations and will be redirected to the Home page in that organization context.
This feature is feature flagged for Cloud for now.
The `/me` subroute is also removed from the Home page because it is redundant.
=> feat(nav): allow user to switch orgs from the navbar

ui/cypress/e2e/buckets.test.ts, ui/src/buckets/components/BucketsTab.tsx, ui/src/index.tsx, ui/src/organizations/actions/orgs.ts, ui/src/organizations/components/CreateOrgOverlay.tsx, ui/src/pageLayout/containers/Nav.tsx, ui/src/shared/copy/v2/notifications.ts
=> feat(ui): Add create org to side nav

services/storage/predicate_influxql.go
When a Flux predicate is transformed to a Store.Read / GroupRead request,
the `_measurement` and `_field` keys are remapped to match 2.x internal
tag keys.
This change does not modify the 2.x behavior, but rather updates the
1.x mapping, so merging future updates from the 2.x storage/reads
package should have fewer conflicts.
Closes #13194
=> Update predicate key mapping to match 2.x behavior

ui/src/pageLayout/components/AccountNavSubItem.tsx, ui/src/pageLayout/containers/Nav.tsx
Closes #13195 
Closes #13202 
Move create org under cubeoctahedron nav tab
alphabetize orgs under switch org
switch to using nav menu components from clockface
ensure after leave nav menu, it goes back to top level menu with switch orgs and logout
=> Move Create Org near Switch Org and alphabetize orgs

ui/src/templates/components/TemplateCard.tsx
Closes #13232
This PR fixes a 404 error by updating the export template URL to reflect the re-org route change.
=> fix(templates): update export template route

http/swagger.yml
Closes #13145
The `FluxLinks` 
https://github.com/influxdata/influxdb/blob/77829324e949aef5b022f51f8e2d431dfad64795/http/swagger.yml#L5910-L5921
has been replaced by 
https://github.com/influxdata/influxdb/blob/77829324e949aef5b022f51f8e2d431dfad64795/http/swagger.yml#L5948-L5965
Related PR https://github.com/influxdata/platform/pull/2088
=> docs(http): remove FluxLinks schema

ui/src/dashboards/components/DashboardImportFromTemplateOverlay.tsx, ui/src/organizations/components/OrgTemplateFetcher.tsx, ui/src/organizations/containers/OrgTemplatesIndex.tsx, ui/src/templates/actions/index.ts
Closes #13246
This PR fixes the Import Dashboard from Template Overlay by updating `orgName` to `orgID` when fetching templates from the server.
=> fix(templates): update org name to ID for fetching templates

ui/src/index.tsx, ui/src/variables/components/CreateVariableOverlay.tsx, ui/src/variables/components/VariablesTab.tsx
Closes #13243
This PR changes the `CreateVariableOverlay` to use React Router rather than open/close state in the parent component.
=> refactor(variables): update CreateVariableOverlay to use routes

query/mock/service.go
This updates the mock Query object, only used by the billing service test in idpe.  Not closing the results channel caused this test to hang.
=> fix(query): make mock Query close its resutls channel

ui/src/configuration/components/CreateLabelOverlay.tsx, ui/src/labels/components/LabelsTab.tsx
Ensure that labels tab only shows labels for current org
=> feat(ui): make labels org centric

ui/src/shared/constants/fluxFunctions.ts
Closes #12859
update shift to timeShift. 
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#timeshift
=> fix(ui): Update flux function shift to timeShift in the functions list

ui/package-lock.json, ui/src/shared/components/Histogram.tsx, ui/src/shared/components/HistogramTransform.tsx, ui/src/timeMachine/actions/index.ts, ui/src/timeMachine/components/HistogramTransform.tsx, ui/src/timeMachine/components/Vis.tsx, ui/src/timeMachine/components/VisSwitcher.tsx, ui/src/timeMachine/components/view_options/HistogramOptions.tsx, ui/src/timeMachine/reducers/index.ts, ui/src/timeMachine/selectors/index.ts
Closes #13227
- Removes derived data from the time machine reducer in favor of computing it in memoized selector functions instead
- Removes two-way data binding from the `Histogram` component (which caused #13227)
- Separates the `QueryViewSwitcher` into two components—one used for dashboards, and one used for time machines. The previous implementation was accumulating confusing branching logic to handle rendering in different locations. The separation into two components introduces some duplication, but removes the branching logic and reduces prop drilling in the time machine version.
- Introduce two `HistogramTransform` components. One is used on dashboards, and one is used in time machines. They provide data from different sources, and behave differently when attempting to render a …
=> Refactor vis data provisioning

ui/src/index.tsx, ui/src/shared/components/ViewOverlay.tsx, ui/src/templates/components/TemplateCard.tsx, ui/src/templates/components/TemplateViewOverlay.tsx, ui/src/templates/containers/TemplatesIndex.tsx
Closes #12914
Created a generic component for ViewOverlay
Created a TemplateViewOverlay that gets the template and passes into ViewOverlay as a resource.
Updated the route for viewing templates to `/view`
=> Update variables to use view overlay instead of export overlay

ui/src/shared/components/ExportOverlay.tsx, ui/src/templates/actions/index.ts
Closes #13294 
Use the dispatch props `createTemplateFromResource` in the export overlay.
=> fix(ui/exportOverlay): use dispatch props

go.mod, go.sum, query/preauthorizer.go, query/preauthorizer_test.go, query/spec.go
Closes #13278 
tests won't pass until go.mod is updated with the change to flux on https://github.com/influxdata/flux/pull/1149
=> refactor(query/preauthorizer): preauthorizer now uses a BucketsAccessed method that accepts AST

CHANGELOG.md, ui/src/dashboards/components/NoteEditor.tsx, ui/src/dashboards/components/NoteEditorPreview.tsx, ui/src/dashboards/components/NoteEditorText.tsx
=> feat(ui): sync note editor text and preview scrolling

cmd/influxd/launcher/launcher.go, gather/scheduler.go, http/client.go, http/handler.go, http/influxdb/client.go, kit/tracing/tracing.go, query/dependency.go, query/stdlib/influxdata/influxdb/from.go, query/stdlib/influxdata/influxdb/source.go, query/stdlib/influxdata/influxdb/storage.go, query/stdlib/influxdata/influxdb/to.go, query/stdlib/influxdata/influxdb/to_test.go, storage/readservice/cursor.go, storage/wal/wal.go, task/backend/scheduler.go, tsdb/tsm1/engine.go
Various tracing cleanups:
- Add parent spans where child spans were triggering root spans (eg Scheduler, Flux from/to)
- Remove a Tracer pointer (we use `opentracing.GlobalTracer`)
- Add some `tracing.LogError` love
- Inject and extract HTTP headers with library rather than copy-pasted code
- Log file/line from `tracing.LogError`
- Add `tracing.StartSpanFromContextWithOperationName`
- Generally replace opentracing usage with `kit/tracing` for consistency and better spans
=> chore(tracing): Cleanup

ui/src/shared/components/ImportOverlay.tsx, ui/src/templates/actions/index.ts, ui/src/templates/components/TemplateImportOverlay.tsx
Closes #13307 
Fixes an issue where orgID was not set in create and where onDismiss was causing the remote data state be stuck in loading templates.
=> fix(ui/templates/import): add orgID to created

auth.go, authorizer/auth.go, authorizer/auth_test.go, bolt/authorization.go, cmd/influx/authorization.go, http/auth_service.go, inmem/auth_service.go, kv/auth.go, mock/auth_service.go, prometheus/auth_service.go, prometheus/auth_service_test.go, testing/auth.go, zap/auth_service.go
Closes https://github.com/influxdata/influxdb/issues/13026
Update the authorization update interface to return the updated authorization
=> fix(influxdb): updated auth shall return

query/querytest/compile.go, query/stdlib/influxdata/influxdb/from_test.go, query/stdlib/influxdata/influxdb/to_test.go
This re-enables some bucket tests for from/to after they were disabled.  I also renamed `BucketAwareQueryTest*` to `BucketsAccessedTest*`, since it's tricky to check both the buckets accessed and verify the spec in the same test case, since `flux.Spec` is trickier to create.
=> fix(query): re-enable some from/to bucket tests

ui/src/shared/copy/notifications.ts, ui/src/tasks/actions/index.ts, ui/src/telegrafs/actions/index.ts, ui/src/templates/actions/index.ts, ui/src/templates/components/TemplateCard.tsx, ui/src/templates/reducers/index.ts, ui/src/variables/actions/index.ts
Closes #13064
Wrap up handling of remove/add on template labels using the updated client. Also, fix notifications not firing for failed labels add/remove.
=> feat(ui/template/labels): add and remove template labels

ui/src/buckets/containers/BucketsIndex.tsx
This PR adds a `GetResources` component for Telegrafs to the `BucketsPage` in order to open the `TelegrafConfigOverlay`
=> fix(telegrafs): add get telegrafs to BucketsPage

CHANGELOG.md, ui/src/onboarding/actions/index.ts, ui/src/organizations/actions/orgs.ts, ui/src/templates/constants/defaultTemplates.ts
=> adding new default template

ui/cypress/e2e/dashboardsIndex.test.ts, ui/src/dashboards/components/DashboardImportFromTemplateOverlay.tsx
Fix a flaky Create Dashboard From Template end-to-end test by making sure that the Template has been selected before trying to create the Dashboard.
Also disables the "Create Dashboard" button in `CreateDasboardFromTemplateOverlay` until the user has selected a template
=> fix(tests): fix flaky dashboards e2e test

bolt/dashboard.go, dashboard.go, dashboard_test.go, http/dashboard_service.go, http/swagger.yml, inmem/dashboard.go, kv/dashboard.go, testing/dashboards.go
The view ID field is being relied on by Chronograf.
Closes #13408
=> Revert "remove view ID"

ui/src/index.tsx, ui/src/members/actions/index.ts, ui/src/members/components/AddMembersForm.tsx, ui/src/members/components/AddMembersOverlay.tsx, ui/src/members/components/Members.tsx, ui/src/members/containers/MembersIndex.tsx, ui/src/members/reducers/index.ts, ui/src/shared/components/GetResources.tsx
Closes https://github.com/influxdata/applications-team-issues/issues/292
The users in new members overlay are now stored in redux state.
Updated the route to /new and include orgID
=> Add route to new member overlay

query/bridges.go, query/bridges_test.go, query/mock/service.go
The ProxyQueryServiceAsyncBridge was not returning statistics when there
was an encoder error. Because the encoder was just writing to an
io.Writer, it was possible that a remote disconnect could happen and
statistics could not be reported.
=> fix(query): return statistics even in encoder error case

cmd/influxd/launcher/launcher.go, http/api_handler.go, http/metric/recorder.go, http/query.go, http/query_handler.go, http/query_test.go, http/status.go, http/write_handler.go, prometheus/metric_recorder.go
Closes # (not sure if there's a direct issue for this)
This PR adds usage tracking for the write and query endpoints. In particular we track
1. The write request size (after gzip) and number of requests, per org
2. The query response size and number of query requests, per org
=> Add prometheus counters for tracking write/query usage

query/iterator.gen.go, query/iterator.gen.go.tmpl, query/subquery_test.go
The reduce iterators would read in the points for a window, which
matched the grouping of the outermost query, and then it would sort them
by the time before emitting the points.
When there were multiple series, this would sometimes cause a conflict
because it would change the sorting of the inner query output when
selectors were used within a subquery. Then, these emitted points would
be output in the wrong order and they wouldn't join correctly when
multiple cursors were used.
This fixes it so the sorting happens per series grouping rather than on
all of the points together so they retain their tag order which is the
correct sorting method.
=> Fix the sort order for aggregates so that they are sorted by tag and then time

storage/reads/string_iterator_writer.go
Add `WrittenN` method to `StringIteratorWriter`.
Helps https://github.com/influxdata/idpe/issues/3114
=> feat(storage): Add StringIteratorWriter.WrittenN()

tsdb/tsi1/file_set.go, tsdb/tsi1/index.go, tsdb/tsi1/index_test.go, tsdb/tsi1/partition.go, tsdb/tsi1/stats.go
Removes the `STATS` file generated during TSI compaction as it had
potential for becoming inconsistent with the index data. Instead,
stats are recalculated on start up and on each compaction on a
per-partition basis.
Computing stats for 10M series across 10K measurements takes
approximately 0.171s.
=> fix(tsdb): Remove TSI stats file cache

cmd/influx_inspect/verify/seriesfile/verify.go, cmd/influx_inspect/verify/seriesfile/verify_test.go
The series index looks at a set of tombstones when querying the id for
a given key, but it does not look when asking for the offset for some
id, even if that id is deleted.
Update the verify tooling to check that the index agrees with the
deleted status of the id, but skip doing the extra checks if the
id is deleted.
=> fix(influx_inspect): verify-seriesfile with deleted index entries

tsdb/index.go, tsdb/series_file.go, tsdb/series_segment.go, tsdb/tsi1/file_set.go, tsdb/tsi1/partition.go, tsdb/tsi1/tsi1.go, tsdb/tsm1/batch_integer_test.go, tsdb/tsm1/bool.go, tsdb/tsm1/compact.go, tsdb/tsm1/file_store.go, tsdb/tsm1/int_test.go, tsdb/tsm1/reader_index.go, tsdb/tsm1/timestamp.go
Fixes some typos in the `tsdb` package. Probably doesn't need a CHANGELOG entry.
=> Fix typos in tsdb package
